### PR TITLE
chore: Update default & blog starter to v3

### PR DESCRIPTION
**Pull request by LekoArts**
## Description

- Change README to include link to cloud
- Add "Live Preview" to README
- Change React imports to preferred syntax
- Use StaticImage
- blog
	- comment out google-analytics as it would fail otherwise
	- change feed plugin so that it works

### CODE REVIEW

**Review by laurieontech — APPROVED** [review]
Thank you for tackling this!

**Review by ascorbic — APPROVED** [review]
Nice one!

**Review by wardpeet — APPROVED** [review]
Looks good to me, do we want to enable avif by default?

**Comment by LekoArts** [comment]
@wardpeet yeah, AVIF is a good idea. I'll open a follow-up PR.

**Pull request merged**
