### PR TITLE
readme(gatsby-dev-cli): change npm to yarn

### PR DESCRIPTION
**Pull request by muescha**
## Description

change npm to Yarn in docs since we use Yarn for development. be consistent with other Gatsby docs

## Related Issues

#19349

### CODE REVIEW

**Comment by muescha** [comment]
i don't know how to check the `Gatsby Build Service` failing :(

**Comment by LekoArts** [comment]
Thanks for the PR!
But it’s not necessary to change these as developing works fine with following those instructions. Yarn is only important for the installation of the repo so that workspaces work.

**Comment by muescha** [comment]
but at least it should be equal in the docs? 

here is yarn used: https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/

**Comment by LekoArts** [comment]
It seems it was changed to that because yarn is mentioned at the beginning. But since the readme is out of context of this npm is just fine as in all other readmes

**Pull request closed without merging**
