### PR TITLE
Fix page renderer

### PR DESCRIPTION
**Pull request by jquense**
This was a page conflict fix on my end, the location state was updated inconsistently so in prod sites never actually navigate since the `state.location` was always stale in cDU

I removed the state so it should be a bit more resilient to react 16.3 and the change in 16.4

### CODE REVIEW

**Comment by jquense** [comment]
i'd appreciate a quick turnaround i have a broken site :)

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 2ec5d0adc274013e1da8edc628481e9f040ea690

https://app.netlify.com/sites/using-glamor/deploys/5b17ed58c965923b7550d586

**Comment by m-allanson** [comment]
> i'd appreciate a quick turnaround i have a broken site :)

on it :)

**Comment by m-allanson** [comment]
Running this locally I got a build error with gatsbygram, but netlify seems happy so let's merge this in? 

@jquense do you have the ability to publish a new version? I have access rights to do it, but haven't run through the process yet.

**Comment by jquense** [comment]
i do have publish rights, but i'm not super comfortable with the process either!

**Comment by m-allanson** [comment]
Released in `2.0.0-alpha.51` (thanks @KyleAMathews )

**Pull request merged**
