### PR TITLE
(#6941): tutorial part zero rewrite

### PR DESCRIPTION
**Pull request by amberleyromo**
- part zero rewrite to structure tutorial in a more step-by-step format
- focus entirely on setting up environment
- address recommending VS Code and Prettier, and provide resources to troubleshoot permissions issues on global package installs.
- includes the changes to the intro text, as well

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit ca4b27abb102bbe2a093b42f97efd44cc1d1e398

https://app.netlify.com/sites/gatsbyjs/deploys/5b631805fdd72a63e30b4345

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit ca4b27abb102bbe2a093b42f97efd44cc1d1e398

https://app.netlify.com/sites/using-postcss-sass/deploys/5b631806fdd72a63e30b4351

**Comment by KyleAMathews** [comment]
Deploy preview for *using-remark* failed.

Built with commit ca4b27abb102bbe2a093b42f97efd44cc1d1e398

https://app.netlify.com/sites/using-remark/deploys/5b631808fdd72a63e30b4363

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit ca4b27abb102bbe2a093b42f97efd44cc1d1e398

https://app.netlify.com/sites/using-contentful/deploys/5b631808fdd72a63e30b4360

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit 0d2382bf94b494a834236ad1e9a20fa7bb21c034

https://app.netlify.com/sites/image-processing/deploys/5b631957b13fb13d95c83493

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 0d2382bf94b494a834236ad1e9a20fa7bb21c034

https://app.netlify.com/sites/using-glamor/deploys/5b631957b13fb13d95c83496

**Comment by KyleAMathews** [comment]
Deploy preview for *using-styled-components* failed.

Built with commit 0d2382bf94b494a834236ad1e9a20fa7bb21c034

https://app.netlify.com/sites/using-styled-components/deploys/5b631957b13fb13d95c83499

**Comment by KyleAMathews** [comment]
Deploy preview for *using-jss* failed.

Built with commit 0d2382bf94b494a834236ad1e9a20fa7bb21c034

https://app.netlify.com/sites/using-jss/deploys/5b63195ab13fb13d95c834b4

**Comment by amberleyromo** [comment]
@shannonbux made the changes re: VS Code and removing the section on git and GitHub -- extended the earlier line as you suggested!

**Pull request merged**
