### PR TITLE
feat(gatsby-source-shopify): Add `apiVersion` option

### PR DESCRIPTION
**Pull request by Saideepak01**
## Description

Add an `apiVersion` option to `gatsby-source-shopify` so that a user can modify the API version used for the fetching of data. The default for now is set to `2022-04`.

### Documentation

README was updated

## Related Issues

Fixes https://github.com/gatsbyjs/gatsby/issues/37548

### CODE REVIEW

**Comment by DennisKraaijeveld** [comment]
Well, first of all, thanks. But to be honest, this isn't that future proof and we should add the Admin API version to the plugin options. If you need help with that, let me know.

**Comment by Saideepak01** [comment]
@DennisKraaijeveld well thanks for mentioning this is my first ever open source contribution i am not aware of that fully could you guide me on that 🙂

**Comment by LekoArts** [comment]
- You'll need to add the option to https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-shopify/src/plugin-options-schema.ts and set `2022-04` as the default value. Name the option `apiVersion`
- You'll need to adjust https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-shopify/types/interface.d.ts#L143 to add the new option
- Use the new option inside the two places where the API is currently used

**Comment by Saideepak01** [comment]
@LekoArts done the changes but windows_unit_tests and  e2e_tests_development_runtime_with_react_18 tests are failing i think those are not failing because of my changes can you take a look into the testing results

**Review by LekoArts — APPROVED** [review]
Thanks 👍

**Pull request merged**
