### PR TITLE
docs(starters): Added Shopify Gatsby starter

### PR DESCRIPTION
**Pull request by AlexanderProd**
## Description
I've created a Shopify Gatsby starter to quickly build an e-commerce experience store with Gatsby.
It's work in progress but the shop functionality is working. 

https://github.com/AlexanderProd/gatsby-shopify-starter

### CODE REVIEW

**Comment by AlexanderProd** [comment]
Can someone take a look at this PR? @gatsbyjs/ecosystem 🤙🏻

**Comment by AlexanderProd** [comment]
@DSchau fixed the tags!

**Comment by AlexanderProd** [comment]
@DSchau Fixed it, can I add a new Shop Tag though?

**Comment by DSchau** [comment]
@AlexanderProd how about "eCommerce"? That's sort of a convention we've seen in our Site Showcase.

**Comment by AlexanderProd** [comment]
@DSchau done ✅

**Pull request merged**
