### PR TITLE
Sass/SCSS Integration

### PR DESCRIPTION
**Pull request by Bartekus**
- sass-loader & node-sass modules added
- webpack.config.js modified to enable .scss & .sass extensions
- .gitignore modified to exclude .idea/ directory
- linted ok

### CODE REVIEW

**Comment by Bartekus** [comment]
This might be much faster than rebasing the last one :/

**Comment by MoOx** [comment]
Maybe gatsby should offer people custom webpack configuration like statinamic does. Much more flexible.

**Comment by KyleAMathews** [comment]
@MoOx there's [this](https://github.com/gatsbyjs/gatsby#how-to-use-your-own-webpack-plugins).

Also going to merge this in tomorrow.

**Comment by KyleAMathews** [comment]
Finally got this merged :) thanks for your patience @Bartekus!

**Comment by Bartekus** [comment]
It's all good, glad I could help :)

**Comment by jlengstorf** [comment]
Hiya @Bartekus! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
