### PR TITLE
Add active state to top navigation

### LINKED ISSUE #7425: [www] doesn't show selected state along top nav bar
### Initial problem

Many users, when they are on the Tutorial page, can't remember how to get back to Docs.

In an effort to solve this issue, I made a link to the Main Tutorial under Quick Start category in Docs. I also made a link to the Quick Start doc at the top of the Tutorial sidebar. 

It appears this has created more confusion and didn't solve the initial problem. So that's getting taken care of in Issue #7424 

Let's make sure we make the selected state along the top nav bar clear and see if it solves the initial problem.

### PR DESCRIPTION
**Pull request by kkemple**
This PR implements active state for the top navigation of the www site. Currently it just sets the font weight of the active item bold, but any styles can be added to the `activeNavItemStyles` object in `src/components/navigation.js`.

I figured @fk would have some input based off the convo in #7425.

Closes #7425

### CODE REVIEW

**Comment by fk** [comment]
Hey Kurt! To quote myself (from [my review](https://github.com/gatsbyjs/gatsby/pull/7429#pullrequestreview-147688723) of the other PR we got for this):

> I was sceptic if font-weight: bold would be a good idea, but this is working quite well and I think we should get this in while discussing if we want to go down a different path in terms of styling.

…so still 👍for getting this in as it is right now.

For all of my ongoing .org nav redesign mocks ([Figma](https://www.figma.com/file/eY2XGFAV06IW8CG3xGNSYwzY/gatsbyjs.org?node-id=0%3A1)), I've chosen the "2px underline" variant for now—that's the second option from the ones shown below:

bildschirmfoto 2018-08-20 um 16 54 09

I think any of those will work; the one I currently opted for most probably being the _least clear_ of all options. What do you think?

Any of those free us of the slight jumping connected to `font-weight: bold`.
The first two options should be the least costly in regards to implementation.

**Comment by LeKoArts** [comment]
Any reason why you didn’t use getProps?
https://reach.tech/router/api/Link

**Comment by kkemple** [comment]
@LeKoArts fix for that coming

**Comment by kkemple** [comment]
@fk, let me play with styles a bit, I think we can prevent jumping when using bold, will also add underline

**Pull request merged**
