### PR TITLE
docs(gatsby-plugin-netlify): Remove H/2 server push section

### PR DESCRIPTION
**Pull request by sw-yx**
## Description

hi! i work at netlify. add note that H/2 server push does not work on Netlify right now

## Related Issues

n/a

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Maybe just remove the section altogether?

**Comment by sw-yx** [comment]
idk, what if we manage to fix it someday? your call you wrote it :)

**Comment by sidharthachatterjee** [comment]
Let's remove the section for now and add it back once it works consistently!

**Comment by sw-yx** [comment]
done

**Pull request merged**
