### PR TITLE
Add context to query-runner error log

### PR DESCRIPTION
**Pull request by slorber**
Having context in debug log can make debugging more easy

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Ah interesting! Could you post a screenshot of what this looks like?

**Comment by slorber** [comment]
image

**Comment by slorber** [comment]
Not sure it's easy. The same problem is already present on graphql query
and I've copied the stringify from other error messages already existing in
other places.

Le mar. 1 mai 2018 à 20:23, Kyle Mathews <notifications@github.com> a
écrit :

**Comment by m-allanson** [comment]
Would removing [`report.stripIndent` from line 36](https://github.com/slorber/gatsby/blob/58d4b5afd784b6d730a1e331fd62b1cd087658f5/packages/gatsby/src/internal-plugins/query-runner/query-runner.js#L36) and then [unindenting lines 37-48](https://github.com/slorber/gatsby/blob/58d4b5afd784b6d730a1e331fd62b1cd087658f5/packages/gatsby/src/internal-plugins/query-runner/query-runner.js#L37-L48) fix the formatting?

It'd make the source file look less neat, but that's probably a good trade-off here.

**Comment by m-allanson** [comment]
Oh, Travis had timed out. Restarting.

**Comment by slorber** [comment]
great thanks, sorry don't have time to look at formatting now

**Pull request merged**
