### PR TITLE
Move schema inference to separate module

### PR DESCRIPTION
**Pull request by Zalastax**
See #1116 for the reason behind this change. This is fairly WIP, but I guess it's already mergeable if you want.

What I have done so far is just to replace requires that went outside the schema folder with dependency injection. I would prefer if schema inference was pure, but that would require a large rewrite since `createPageDependency`, `apiRunner` ,  and `getNodes` are used quite much. Do we need to run `getNodes`, `createPageDependency`, and `apiRunner` in several stages or could we run them just one time each before/after the calls into `gatsby-infer-schema`?

### CODE REVIEW

**Comment by KyleAMathews** [comment]
So what's your goal here? Are you intending to use Gatsby's GraphQL inference engine in a separate project?

I ask because while in theory I support splitting it off into its own project — it'd mean almost certainly a lot of ongoing work for me and other maintainers + we'd need to do a lot of work to ensure that the API for the engine is good, etc. None of which honestly I have any interest in doing :-) so if you're like super committed to this project & you have at least one very solid use case for using this potential new package outside of Gatsby and want to do a lot of solid work on the implementation then I say go ahead.

If this is more just to explore the idea then feel free to but let's not merge this.

**Comment by Zalastax** [comment]
It's not something I personally need, I just wanted to hack on something and I already know the schema code somewhat. The issue comments and tags led me to believe this was already an approved change. To give the code a good structure would need quite a lot of work, especially as I have to battle flows aweful error reporting, but if the change was actually wanted I'd be fine with that.

**Comment by KyleAMathews** [comment]
Yeah, sorry to come off a bit harsh sounding but abstractions are expensive to create and so while it'd be *cool* if lots of other projects are using our inference engine, it'd be a big burden to shoulder by ourselves unless other projects are actively using the new package and helping maintain it. A big burden that's not needed as it hurts more than helps our architecture.

I should have made that more clear in the other issue :-(

**Comment by Zalastax** [comment]
OK, no problem. I'll close this PR and it would be nice if you can add something to the issue to mark that stance, e.g. by removing the "Help Wanted in Core" tag. I still think the schema inference code could favor from separating effectful and pure functions, but we'd need a plan for that and I know you have more important things to do first.

**Comment by KyleAMathews** [comment]
Sure thing, will remove the tag.

**Comment by KyleAMathews** [comment]
Sorry again about the bother.

**Pull request closed without merging**
