### PR TITLE
[www] Replace Tex Gyre Schola with Spectral

### PR DESCRIPTION
**Pull request by fk**
Also brighten header and body color a little.

IMO Gyre Schola renders a bit too dark, is spaced a little too tightly, and some letterforms (e.g. the uppercase "G", lowercase "t") feel almost a little noisy. Spectral feels friendlier, less dark and stiff, and I much prefer its italic.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit fced88832f484a1f0d92e5626bfa2b58b62f9b70

https://app.netlify.com/sites/gatsbygram/deploys/596f6aae8ebdd92a6f50f4ea

**Comment by fk** [comment]
Meh, just compared on mobile and now I'm torn. Maybe brightening up colors was too much for Spectral, but would have done good for Gyre Schola… ;-)

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit a812e2f8fe56d8c70058ac551b3d6cf6d0089377

https://app.netlify.com/sites/using-glamor/deploys/5970d8a7cf321c298055a78f

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit a812e2f8fe56d8c70058ac551b3d6cf6d0089377

https://app.netlify.com/sites/using-remark/deploys/5970d8a7cf321c298055a798

**Comment by KyleAMathews** [comment]
Closing this in lieu of #1605

**Pull request closed without merging**
