### PR TITLE
Update how-to-add-a-list-of-markdown-blog-posts

### PR DESCRIPTION
**Pull request by shannonbux**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 594cd0a817e2680d005bb493be6ff859c5c4fa9a

https://app.netlify.com/sites/using-glamor/deploys/59fa070b0b79b76b27ae9048

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by shannonbux** [comment]
Huh, all the links on stubs to Gatsby Style Guide are still loading ultra-slow for me...

**Comment by KyleAMathews** [comment]
The first one will since it's probably not preloaded. If you click on another of the stubs and then click on the style guide it'll be instantaneous.

**Comment by shannonbux** [comment]
wohoo it works!!!!! so faaast

**Pull request merged**
