### PR TITLE
fix(gatsby-remark-autolink-headers): option to disable "position: relative" when icon is not present

### LINKED ISSUE #26961: gatsby-remark-autolink-headers: option to disable style="position: relative"
## Summary
`gatsby-remark-autolink-headers` adds `style="position: relative"` to `<h..>` Tags. Adding the style attribute to `<h..>` Tags is intrusive and not always wanted. It should be possible to disable this behavior.

### Motivation

Not all designs work well with relative positioned heading elements. One example is `"float:right"`

### PR DESCRIPTION
**Pull request by parulc7**
## Description

gatsby-remark-autolink-headers always use relative positioning. However, this doesn't always work fine. This Pull Request aims to fix this issue and provide relative positioning only when the icon is present.
## Related Issues
Fixes #26961

### CODE REVIEW

**Comment by parulc7** [comment]
@LekoArts

**Comment by parulc7** [comment]
@LekoArts any changes required?

**Comment by parulc7** [comment]
@gatsbybot

**Comment by LekoArts** [comment]
@parulc7 Please refrain from tagging people, the PR will be reviewed during working days (so not on the weekend) and they are on our radar.

**Review by LekoArts — APPROVED** [review]
👍

**Pull request merged**
