### PR TITLE
Add Gatsbygram case study and code for blog

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Lemme know if you have any thoughts on the gatsbygram blog post — I'll probably publish it tomorrow sometime.

**Comment by kristojorg** [comment]
I am reading through it now. I think it might make sense to emphasize a bit more how gatsby is unique in its ability to create dynamic routes from data source. 

I'm thinking about how you might do that, but it seems like it should go in the template component section.

**Comment by kristojorg** [comment]
I'll send a PR with a suggestion later today... I have to learn how to balance an AVL tree on paper before my data structures and algorithms exam :dizzy_face:

**Comment by KyleAMathews** [comment]
@kristojorg good idea! Yeah — kinda forgot that it is pretty unique :-) I've been heads down on Gatsby for so long that it's hard to remember sometimes where and how it's unique :-D

Good luck on your exam!

**Comment by kristojorg** [comment]
Thanks @KyleAMathews :) here is the PR: #708

**Comment by KyleAMathews** [comment]
Oof, finally merging this big boy.

**Comment by KyleAMathews** [comment]
Adding DNS over and then we'll be live!

**Comment by KyleAMathews** [comment]
And we're live 😅

https://www.gatsbyjs.org/blog/gatsbygram-case-study/

**Pull request merged**
