### PR TITLE
Create README_ES.md

### PR DESCRIPTION
**Pull request by LuigiBaute**

### CODE REVIEW

**Comment by m-allanson** [comment]
Thanks @LuigiBaute! I don't we're accepting translations directly into the Gatsby repo yet. If you want to create a separate GitHub repo with your translations, then we can link to them from here. 

When translating markdown files, working from the [source document](https://raw.githubusercontent.com/gatsbyjs/gatsby/master/README.md) instead of the rendered version will probably give you better results.

**Comment by jquense** [comment]
Why aren't we accepting translations here?

**Comment by jquense** [comment]
This seems kinda silly not take here, what is the downside or cost?

**Comment by m-allanson** [comment]
My understanding is that there's plans to use https://crowdin.com to manage translations, but it needs some setup first. 

Currently there's no way to publish any translated docs, maybe we can accept translated README's though? What does @KyleAMathews think?

**Comment by KyleAMathews** [comment]
The downside is extra maintenance time I guess. Also I doubt we'd ever want the README translated and other development-related stuff.

**Comment by jquense** [comment]
That's fair, though it'd be great to give @LuigiBaute a more specific avenue to help while they're ready to go :)

**Pull request closed without merging**
