### PR TITLE
chore(docs) Bring back small caps titles for /docs/ sidebar first-level accordions

### PR DESCRIPTION
**Pull request by fk**
* back to a more obvious information hierarchy for https://www.gatsbyjs.org/docs/ by bringing back small caps titles for first-level sidebar accordions (originally removed in #12842)
* move "Cheat Sheet" link down below "Commands (Gatsby CLI)"
* link to "Cheat Sheet" from "Commands (Gatsby CLI)" and vice versa
* move "Glossary" stub down a bit
* finally remove the "Ecosystem" section as we have all its links at the top of the docs hierarchy now, and the item itself only links to https://www.gatsbyjs.org/ecosystem/ (which we still have to take a leap for)

image

image

### CODE REVIEW

**Comment by fk** [comment]
Thanks Dustin! (-;

**Comment by shannonbux** [comment]
Just getting to this after coming back into town!

I'm wondering if it's possible to make the cheat sheet clickable and just use that as a landing page for the docs? It seems like it's the most up-to-date resource on what Gatsby users want at their fingertips based on @marcysutton's research, so surfacing it in some way would make sense to me. @calcsam what was the reason for putting it below the fold?

**Comment by marcysutton** [comment]
@shannonbux do you mean the Cheat Sheet images? They link to full-size images, and there is PDF link to download as well as a link to the Quick Start documentation.

I didn't get a chance to review this before it was merged unfortunately, but I'm wondering what the reasoning was for keeping Awesome Gatsby up so high in the sidebar (what do the analytics look like for that page?). The [ecosystem page](https://www.gatsbyjs.org/ecosystem/) links to it as "Browse Resources", perhaps we could move it farther down? 

Related to all of this: one of my Learning tasks is to come up with a proposal for a docs IA reorg (things like Advanced Tutorials moving into Tutorial(s), which could give the docs a more limited scope for translations). I'll be sure to loop y'all in when there is something ready to review, so we can pick up from where this PR left off.

Thanks for all your work on this, @fk!

**Comment by fk** [comment]
@marcysutton Sorry for not letting you properly review it — Dustin and me went a little too YOLO here with the quick merge!

> I'm wondering what the reasoning was for keeping Awesome Gatsby up so high in the sidebar

@calcsam was of the same opinion, it was me who worried about mobile users and "changing too much on the fly". We also observed that the whole top part of "Awesome Gatsby" is quite redundant, so I'm absolutely seeing where you're coming from.

I really shouldn't be messing around here, I mainly tried to pick up the feedback in regards to information hierarchy, and adressed the other input from the team in the same PR, which was a mistake IMO — content and UI appearance should have went to separate PRs.

**Comment by marcysutton** [comment]
No worries, this is a great PR! We can make subsequent changes for sure–I think the styling stuff and IA reorg can be separate items, so it makes sense to not hold that work up here.

**Pull request merged**
