### PR TITLE
chore(docs): "behaviour" to "behavior"

### PR DESCRIPTION
**Pull request by bryndyment**
docs update: `behaviour` -> `behavior`

## Related Issues

(none)

### CODE REVIEW

**Comment by wardpeet** [comment]
Hey! I don't think we're going to accept this one as there is nothing wrong with `behaviour`. (correct me if I'm wrong but this is what google said)

> Behavior is the preferred spelling in American English. Behaviour is preferred everywhere else. Other than the spelling, there is no difference between the two words.

https://www.grammar.com/behavior_vs._behaviour

**Comment by yogeshkotadiya** [comment]
> Hey! I don't think we're going to accept this one as there is nothing wrong with `behaviour`. (correct me if I'm wrong but this is what google said)
> 
> > Behavior is the preferred spelling in American English. Behaviour is preferred everywhere else. Other than the spelling, there is no difference between the two words.
> 
> [grammar.com/behavior_vs._behaviour](https://www.grammar.com/behavior_vs._behaviour)

There is none, its like `color` vs `colour`.

**Comment by bryndyment** [comment]
True, they are both correct depending upon your country.  We spell it `behaviour` in Canada, for instance.

There are 59 instances of `behavior` on the site and 5 of `behaviour`, and it's an American company, so I think it makes sense to standardize on the American spelling.

What do you think?

**Comment by wardpeet** [comment]
I think it's going to be hard to standardize on this one and keep an 👁 on following releases.

I'm not going to make the call so pinging @gatsbyjs/docs

**Pull request merged**
