### PR TITLE
feat(www): update tags design, add 'View All Tags' buttons

### PR DESCRIPTION
**Pull request by LMulvey**
## Description

This PR adds the following UI updates:

- Update the TagsListing to allow filtering + UI updates
search-gif

- Added 'View All Tags' button to Blog List underneath pagination
bloglist

- Added 'View All Tags' button to Blog Post - next to tag listing
blogpost

- Update specific Tag page to match 'View All Tags' button added throughout
viewtag

I am by no means a designer so _please_ let me know if I can update the designs here in any way. 

## Related Issues

Addresses #10907

### CODE REVIEW

**Comment by wardpeet** [comment]
Sweet! :tada: I'm not a big fan of having the tags inside the TagsListing centered. I rather have them left align but that's just a personal preference of course. Not sure how others feel about that.

**Comment by amberleyromo** [comment]
I'd echo the left align preference, but not a huge deal (/not blocking). Thanks for picking this up!

**Comment by LMulvey** [comment]
I agree! I'll tinker with it this evening and see if I can get it to look right.

I originally opted for the center align because of the uneven lengths/widths of the tags. It was creating rows that were sometimes three columns wide and sometimes two and it looked a _bit_ more natural if it was center aligned. I'll mess with it and see if I can get it looking a little nicer before we move ahead 😄

**Comment by wardpeet** [comment]
@LMulvey don't worry to much about it. We love the redesign! Thanks for taking it on.

**Comment by LMulvey** [comment]
@wardpeet Heyo! Wanted to check in and see if there was anything else I could change/modify here. I have some time this evening if it needs a bit more finesse.

**Comment by sidharthachatterjee** [comment]
cc @fk

**Comment by wardpeet** [comment]
@LMulvey i'm loving this! hopefully someone from @gatsbyjs/ecosystem & @gatsbyjs/website can check this out!

**Comment by LMulvey** [comment]
@fk Consistency is key! I'll add this fix tonight and push it up. Thank you for the review 🙏

The left-hand column for filtering by category doesn't make sense here so I'll likely leave that portion of the UI out but keep the header/search bar consistent. I had looked around the site for something similar before opting for a version of the nav search. This works way better for our purposes here though.

**Comment by fk** [comment]
> The left-hand column for filtering by category doesn't make sense here so I'll likely leave that portion of the UI out but keep the header/search bar consistent. 

💯 Yep! I think caused a little misunderstanding here — please don't worry with porting the whole Showcase "header"; my comment was just in regards to the search input: 
image

**Comment by fk** [comment]
Thank you @LMulvey and @pieh!

**Comment by pieh** [comment]
Here's tag page with button below title:
screenshot 2019-02-05 at 15 08 19

I've spent some time with trying to use flexbox, but there is so much margin things to work out (that would be pretty hacky IMO) and decided to just put "View all tags" below title

**Comment by KyleAMathews** [comment]
Could we fix the styling at the end of blog posts? I assume you meant to add the "all tags" link after the other tags?

screenshot 2019-02-05 10 04 49

**Comment by KyleAMathews** [comment]
Oops, ignore that vertical line haha — I added that by accident.

**Comment by LMulvey** [comment]
I sure did! I can take a peek at this tonight if someone else doesn't grab it during the day. I mistakenly tested on posts without enough tags 😊

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
