### PR TITLE
Fix(gatsby-plugin-catch-links): SVGAnimatedString may not be available in some browsers.

### PR DESCRIPTION
**Pull request by didia**
## Description

In some browsers like Internet Explorer, Samsung Internet and Chrome Android, Opera Mini (see https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString), SVGAnimatedString is not available. This produces a runtime UndefinedVariableError.

I propose we check if `SVGAnimated` is available in `window` before checking if `clickedAnchor.href` is an instance of it.

### CODE REVIEW

**Comment by blainekasten** [comment]
Also referencing this there are several browsers that do not support this variable. https://caniuse.com/#search=SVGAnimatedString

I think this fix looks great.

Any chance you could add a unit test for this before we merge it?

**Comment by didia** [comment]
@blainekasten Sure, on it

**Comment by didia** [comment]
@blainekasten I have added a unit test! Let me know if there is something else I should do. Thanks

**Review by wardpeet — APPROVED** [review]
Awesome! Thank you for this!!! 💯

**Pull request merged**
