### PR TITLE
Add KaTeX support to remark

### PR DESCRIPTION
**Pull request by jeffrey-xiao**
I did the simplest solution I had in mind: the user would define a list of parser plugins that remark would use to change the markdownAST in `gatsby-config.js`. This is the repo containing a sample setup: https://github.com/jeffrey-xiao/gatsby-katex-site

The blog post with KaTeX is under `/blog/sample-post`

Is it a good idea for the user to add custom config the [rendering options](https://github.com/Khan/KaTeX#rendering-options)?

If everything looks good, I'll add tests.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Looks good! Let's not make this a configuration option though (more work plus error-prone) but make it part of the gatsby-remark plugin itself. So transformer-remark should ask its plugins for remark plugins.

**Comment by jeffrey-xiao** [comment]
Just to clarify, should each `gatsby-remark-*` plugin export a list of remark plugins along with a function to mutate `markdownAST`?

**Comment by jeffrey-xiao** [comment]
I changed the `gatsby-remark-*` plugins to export a dict containing a parse function. Plugins can also define `getParserPlugins` that returns a list of remark plugins to use.

**Comment by KyleAMathews** [comment]
Plugins should only implement APIs as needed so if they don't add a remark parser then they shouldn't export anything.

Can you run "npm run format" from the base of the repo? Your diff got really messy.

**Comment by KyleAMathews** [comment]
Looked over this in more detail.

You can't change the API for gatsby-remark-* plugins (i.e. using `parse`) as this is a breaking change and would require a major release. (Also "parse" isn't the right name as the markdown source is already parsed at this point — these plugins are transforming the parsed markdown AST).

I believe in Node.js you can just leave the `module.exports` as is but also add a `module.exports. getParserPlugins`

Also the API name should be `setParserPlugins` per our API spec https://www.gatsbyjs.org/docs/api-specification/#operators

**Comment by jeffrey-xiao** [comment]
I reverted and added a `setParserPlugins` method. Also added tests and `README.md`.

**Comment by KyleAMathews** [comment]
Sweet! Looking good especially tests 😋

Last thing I think is to add an example page to the using-remark example site to demo this new functionality.

**Comment by jeffrey-xiao** [comment]
Done!

**Comment by KyleAMathews** [comment]
Looking great! Thanks for the great PR!

screen shot 2017-08-08 at 6 15 50 pm

**Comment by jbolda** [comment]
@jeffrey-xiao  💓 the KaTeX support! Gracias!

**Comment by fk** [comment]
@jeffrey-xiao 👍 👍 👍

**Comment by jlengstorf** [comment]
Hiya @jeffrey-xiao! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
