### PR TITLE
chore(blog): Bring back links in `Pullquote citation`

### PR DESCRIPTION
**Pull request by fk**
Ref. https://github.com/gatsbyjs/gatsby/issues/25240, https://github.com/gatsbyjs/gatsby/pull/25239

image

<3 @sidharthachatterjee

### CODE REVIEW

**Comment by fk** [comment]
Uh … I forgot the mandatory PR YouTube link: https://www.youtube.com/watch?v=ZEq7q8IMz9U

**Comment by fk** [comment]
Booooooooooooooo 😭 😉 @sidharthachatterjee 

```shell
$ remark --quiet --frail "./docs/"
 docs/blog/2020-06-22-Announcing-Gatsby-Partner-Program/index.md
   37:1  warning  Missing marker in block quote  no-blockquote-without-marker  remark-lint
   37:1  warning  Remove 1 line before node      no-consecutive-blank-lines    remark-lint
   38:1  warning  Missing marker in block quote  no-blockquote-without-marker  remark-lint
   39:1  warning  Missing marker in block quote  no-blockquote-without-marker  remark-lint
   40:1  warning  Missing marker in block quote  no-blockquote-without-marker  remark-lint
   62:1  warning  Missing marker in block quote  no-blockquote-without-marker  remark-lint
   62:1  warning  Remove 1 line before node      no-consecutive-blank-lines    remark-lint
   63:1  warning  Missing marker in block quote  no-blockquote-without-marker  remark-lint
   64:1  warning  Missing marker in block quote  no-blockquote-without-marker  remark-lint
   65:1  warning  Missing marker in block quote  no-blockquote-without-marker  remark-lint
   66:1  warning  Missing marker in block quote  no-blockquote-without-marker  remark-lint
   67:1  warning  Missing marker in block quote  no-blockquote-without-marker  remark-lint
 ⚠ 12 warnings
 error Command failed with exit code 1.
 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ```

Unfamiliar with the linter — do you have an idea?

**Comment by sidharthachatterjee** [comment]
@fk Same. I think @tesseralis added this linter recently!

**Comment by mgienow** [comment]
this linter has been making my recent blog publishing life recently miserable 😹

**Comment by fk** [comment]
@mgienow I reverted the changes from this PR because if we kept them in our `master` branch, all subsequent deploys of our website would have failed, because the linter check told us to. LMK if you have any questions — happy to chat about this more! (even though there probably are people who can explain this way better than I can)

**Comment by fk** [comment]
FWIW, here are the two things that the parser chokes on:

* https://www.npmjs.com/package/remark-lint-no-blockquote-without-marker
* https://www.npmjs.com/package/remark-lint-no-consecutive-blank-lines

**Comment by muescha** [comment]
@fk: fixed in:

- #25414 `fix(blog): Gatsby Partner program - add links back to Pullquote`

**Comment by muescha** [comment]
@mgienow 

> this linter has been making my recent blog publishing life recently miserable 😹

can you please describe it with details in this issue (to give you a better publishing experience):
- #25290 `enhancement (docs): Improvements to retext-spell`

**Pull request merged**
