### PR TITLE
don't watch files to copy them when building

### PR DESCRIPTION
**Pull request by quarterto**
i've been running into a problem with builds throwing `ENOSPC` on CI but not locally. i'm guessing it's hitting the inotify ulimit, since even for build it's using chokidar to copy the static directory, and my static directory happens to contain symlinks to node_modules because reasons, so it's very large.

switching this to a straight copy should avoid this and still work the same for static builds.

### CODE REVIEW

**Comment by quarterto** [comment]
test failures are, i'm guessing, unrelated (problems installing gatsby and yarn)

**Comment by pieh** [comment]
@quarterto Yeah, UI test sometimes get stuck doing weird things - don't worry about it!

Behaviour wise I think Your changes make sense. Did you try to see if that approach actually solves the problem? For example renaming `static` directory to something else so Gatsby doesn't try to handle it and use `fs.copy` in one of Gatsby node APIs (for example `onPreBootstrap` or `onPostBootstrap`)?

If it indeed fixes the problem then only change I would like is to export both `copyStaticDirectory` and `syncStaticDirectory` from single file to group similiar functions together and maybe some jsdocs for both of them so future contributors know why there are two functions doing similiar thing.

**Comment by m-allanson** [comment]
Hey @quarterto do you have the time to update this following @pieh's feedback? Great 👍 if you do! 

No worries if not though. If you have an example repo that can reproduce the bug you're seeing then someone else would be able to finish this up and get it merged.

**Comment by m-allanson** [comment]
@DSchau / @pieh this is good for review now. I thought about adding integration tests for this also, what do you think?

**Pull request merged**
