### PR TITLE
feat(remark-images): support relative root path `/`

### PR DESCRIPTION
**Pull request by ekoeryanto**

### CODE REVIEW

**Comment by pieh** [comment]
Can you add more context on this? when would you use this?

**Comment by LekoArts** [comment]
So there exists this plugin: https://github.com/danielmahon/gatsby-remark-relative-images
It also handles some edge cases and things like different paths.

Also there is this plugin: https://github.com/escaladesports/gatsby-plugin-netlify-cms-paths

I'm not sure if there's a need to add this functionality @pieh ?

**Comment by ekoeryanto** [comment]
@LekoArts I just thought that it'll be great to have that internally

**Comment by LekoArts** [comment]
Hi! We won't merge this as this is an edge case introduced by Netlify CMS. We recommend using the aforementioned plugins instead.

We absolutely want to have you as a contributor, so please take a look at [our open issues][open-issues] for ideas, and please reach out to us on Twitter at `@gatsbyjs` with questions.

We offer pair programming sessions if you’d like to work with one of our maintainers to make your first contribution.

Thanks again, and we look forward to seeing more PRs from you in the future! :muscle::purple_heart:

[open-issues]: https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by erquhart** [comment]
Relative image path support is now in beta as of Netlify CMS 2.9.8-beta.2 - try it out:

```
npm update netlify-cms-app@beta
```

Then add `media_folder_relative: true` to your Netlify CMS config.

[Docs here](https://www.netlifycms.org/docs/beta-features/#relative-image-paths).

**Pull request closed without merging**
