### PR TITLE
docs : added more sites to gatsby showcase

### PR DESCRIPTION
**Pull request by siddhant1**

### CODE REVIEW

**Comment by siddhant1** [comment]
ref #8978

**Comment by siddhant1** [comment]
@kakadiadarpan ptal

**Comment by amberleyromo** [comment]
@siddhant1 let me know when this is ready for review!

**Comment by siddhant1** [comment]
@amberleyromo , can you please take a look at it now and tell me any further changes in this one.

**Comment by siddhant1** [comment]
I think there is a merge conflict happening due to another pr , resolving that ..

**Comment by siddhant1** [comment]
@amberleyromo PTAL

**Pull request merged**
