### PR TITLE
Prevent gatsby-plugin-sharp from generating 0-height images

### LINKED ISSUE #2204: gatsby-remark-images: "image has shrunk to nothing" error
While working on the [React Gatbsy site](https://github.com/facebook/react/tree/gatsby) I found a problem with the `gatsby-remark-images` and certain images on the site. This issue causes Gatsby (prod and dev) to crash when certain images are referenced in markdown files (eg [this one](https://github.com/facebook/react/blob/master/docs/img/docs/perf-exclusive.png) or [this one](https://github.com/facebook/react/blob/master/docs/img/docs/perf-dom.png)). Both of these images are relatively short compared to their width (eg 687 x 32).

The [Gatsby docs for `gatsby-remark-images`](https://www.gatsbyjs.org/packages/gatsby-remark-images/) say:
> Useing the “blur up” technique popularized by Medium and Facebook where a small 20px wide version of the image is shown as a placeholder until the actual image is downloaded.

This means an image originally sized 687 x 32 would get scaled down to a height of < 1 pixel which probably gets rounded to 0 and causes [`shrinkv` to error](https://github.com/jcupitt/libvips/blob/master/libvips/resample/shrinkv.c#L388).

Seems like the Gatsby plug-in should be more robust to this case. I will look into this and hopefully submit a PR.

PS. While poking around I noticed that the `gatsby-remark-images` plugin declares a dependency on `image-size` but it isn't used anywhere in the plugin. (IT _is_ used in `gatsby-plugin-sharp` though.)

### PR DESCRIPTION
**Pull request by bvaughn**
This solution might be too naive and overlooking use cases I'm unaware of.

Resolves #2204

### CODE REVIEW

**Comment by bvaughn** [comment]
Whoops, looks like a test failed. Not sure if this failure indicates an actual regression or if the test just _happened_ to rely on the previous behavior.

**Comment by sebastienfi** [comment]
That looks good 👍

**Comment by bvaughn** [comment]
Thanks @sebastienfi! 😄 

Kyle/Jason, let me know once you've had a chance to publish a new release of the plug-in 😄

**Comment by KyleAMathews** [comment]
If only https://github.com/gatsbyjs/gatsby/pull/2198 was in already, it would have just happened :-D

Thanks for knocking off that edge case bug!

**Comment by KyleAMathews** [comment]
Oh and just published everything :-)

**Comment by bvaughn** [comment]
No problem 😄 Happy to help contribute back!

**Pull request merged**
