### PR TITLE
fix(wordpress): ensure all file links are rewritten

### LINKED ISSUE #31646: [gatsby-source-wordpress] fetchReferencedMediaItemsAndCreateNodes resolves too early
## Description

I have an ACF that contains HTML content which contains multiple audio element which is referencing a wordpress hosted audio file. The sum of all referenced media items exceeds the configured `schema.perPage` configured page size. 
In this case it seems that the promise for `fetchReferencedMediaItemsAndCreateNodes` resolves with only parts of the received data (IMHO the last page) rather than the combined list of media Items.

This leads to the case where you have only a few of the media items urls replaced, while the others still point to the wordpress server.

### Steps to reproduce

1. generate the starter project `gatsby new my-wordpress-gatsby-site https://github.com/gatsbyjs/gatsby-starter-wordpress-blog`
2. configure the following options
    ```
     schema: {
          perPage: 2,
        },
    ```
3. Create an empty wordpress instance, install, wp-graphql and update the automatically created post to contain 3 audio tags (mp3)
4. run 
   ```
   yarn clean
   yarn develop
    ```
5. now go to http://localhost:8000/___graphql and execute the following query
   ```
    query MyQuery {
     allWpPost {
      nodes {
        slug
        content
        }
      }
    }
    ```
6. observe the output HTML
   ```
     {
      "data": {
         "allWpPost": {
           "nodes": [
             {
               "slug": "hello-world",
               "content": "\n<p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!</p>\n\n\n\n<figure class=\"wp-block-audio\">
                       <audio controls src=\"http://dockerhost:8000/wp-content/uploads/2021/05/file1.mp3\"></audio></figure>\n\n\n\n<figure class=\"wp-block-audio\">
                      <audio controls src=\"http://dockerhost:8000/wp-content/uploads/2021/05/file2.mp3\"></audio></figure>\n\n\n\n<figure class=\"wp-block-audio\">
                       <audio controls src=\"http://dockerhost:8000/wp-content/uploads/2021/05/file3.mp3\"></audio></figure>\n"
             }
           ]
         }
       },
       "extensions": {} 
    }
    ```

### Expected result

the 3 audio files should be rewritten to `/static...`  urls 

### Actual result

The urls are not rewritten at all.

### Environment

```

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /var/folders/dm/59s6_w2s3jl78c__p8j_cn1w0000gn/T/yarn--1622281277197-0.1413190554991537/node
    Yarn: 1.22.10 - /var/folders/dm/59s6_w2s3jl78c__p8j_cn1w0000gn/T/yarn--1622281277197-0.1413190554991537/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.3.0 => 3.6.1 
    gatsby-image: ^3.3.0 => 3.6.0 
    gatsby-plugin-manifest: ^3.3.0 => 3.6.0 
    gatsby-plugin-offline: ^4.3.0 => 4.6.0 
    gatsby-plugin-react-helmet: ^4.3.0 => 4.6.0 
    gatsby-plugin-sharp: ^3.3.0 => 3.6.0 
    gatsby-source-filesystem: ^3.3.0 => 3.6.0 
    gatsby-source-wordpress: ^5.4.1 => 5.6.0 
    gatsby-transformer-sharp: ^3.3.0 => 3.6.0 
```

### PR DESCRIPTION
**Pull request by rburgst**
## Description

Ensure that all file links are properly resolved even in cases where it spans multiple graphql queries.

### Documentation

- in the case of either having a small `schema.perPage` setting
  or many many referenced resources on a single page only the first
  page of links were properly rewritten
- now we ensure that all pages are fully processed until we resolve the
  promise
## Related Issues

Fixes #31646

### CODE REVIEW

**Comment by rburgstaller** [comment]
anyone home?

**Comment by wardpeet** [comment]
Hey, thank you for creating the PR, and sorry for taking so long to get to you.

I'll test the reproduction and come back to you!

**Comment by rburgst** [comment]
> Hey, thank you for creating the PR, and sorry for taking so long to get to you.
> 
> I'll test the reproduction and come back to you!

Any news? we need this fix quite urgently

**Comment by rburgst** [comment]
@wardpeet any updates?

**Review by wardpeet — APPROVED** [review]
Thanks, sorry for keeping you waiting. The function is a bit weird here so I had a hard time wrapping my head around it.

**Comment by TylerBarnes** [comment]
I think we're going to need to revert this. It looks like it's causing the process to freeze now in tests on another branch.

**Comment by TylerBarnes** [comment]
Looks like the tests were failing here too when this was merged :thinking: weird that the gatsbybot merged this when it wasn't green

**Comment by TylerBarnes** [comment]
fwiw the solution here wont work because it will only ever resolve 1 time now that resolve is in that if statement but we need it to resolve for every request since it resolving is part of what adds those nodes to Gatsby.

**Comment by rburgst** [comment]
Well the initial problem was that it resolved too soon in case there were more than one pages. Imho it's correct to only resolve once all pages have been fetched. @TylerBarnes could you add a test case that shows the problem. I would be happy to fix it once I know what the problem is.

**Comment by TylerBarnes** [comment]
@rburgst I don't think we need to add another test case for it since the integration tests caught this. The problem was the tests didn't run for your PR originally for some reason and then when "merge on green" was added the WP integration tests weren't marked as required so the PR merged with them failing. You can run them by running `yarn test` in `integration-tests/gatsby-source-wordpress`.

My guess is your code breaks when there's only 1 page. Somehow the condition you added never gets tripped and the promise never resolves so we wait indfeinitely.
Ideally we should create a new promise for each page in the loop that adds pages to the queue here https://github.com/rburgst/gatsby/blob/7904abff5c2d64f8f364c3a3c4763074a3f039aa/packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js#L342 and then wait for all pages to resolve before calling resolveFutureNodes() after the loop.

**Comment by rforster-dev** [comment]
Sorry to interject, but does this I wonder relate to the bug I raised: #32350 around having low perPage schema settings?

**Comment by TylerBarnes** [comment]
@rforster-dev potentially yes. We should probably run a build in our integration tests with perPage set low since there are multiple places throughout the codebase that that setting effects and for a lot of sites that setting is needed for the build to succeed.

**Comment by rburgst** [comment]
@TylerBarnes I checked out the last commit before the revert (79b7b0407ddc6b53c2e86b0cdd16866283a928d2) and ran the int tests. The only difference is that the test `resolves node interfaces without errors` (https://github.com/gatsbyjs/gatsby/blob/master/integration-tests/gatsby-source-wordpress/test-fns/data-resolution.js#L65) returns 31 nodes in the response rather than 30. The extra node is 
```json
{
            "id": "cG9zdDoxMTgzMQ==",
            "slug": "11828",
            "__typename": "WpBlockEditorPreview"
          },
```
I could not find any failed tests where the promise was not resolved.

**Comment by TylerBarnes** [comment]
There were some changes to the int tests related to media items so you likely need to pull master into your branch. The other thing is I think promises will sometimes resolve and sometimes not since it'll be a race condition. So there might be some cases where the tests still pass 🤔

**Comment by rburgst** [comment]
That's why I checked out https://github.com/gatsbyjs/gatsby/commit/79b7b0407ddc6b53c2e86b0cdd16866283a928d2. I couldn't see a problem there other than the extra node. 

If you can point me to a commit that would be better suited I would be grateful. At any rate I will try and replicate the problem with this commit in the meantime.

**Comment by TylerBarnes** [comment]
@rburgst you should be able to create a branch from your latest commit in this PR and then merge latest master into it 👍

**Comment by rburgst** [comment]
@TylerBarnes I did exactly this and now the tests succeed without error. I am not sure what to do. Could it be that this fix interacted with a different bug which was fixed in the meantime?

**Comment by rburgst** [comment]
@TylerBarnes since I cannot replicate any problem, I have rebased the changes and created a new PR: https://github.com/gatsbyjs/gatsby/pull/32679

**Comment by rburgst** [comment]
@TylerBarnes note that I tweaked the PR more like you suggested by creating individual per page promises and using `Promise.all` at the end. I also added unit tests for single page usage.

**Pull request merged**
