### PR TITLE
Fix redirect history.replace error

### LINKED ISSUE #7000: [v2] createRedirect throws an error and isn't working
## Description

Redirects doesn't work and throws an error

### Steps to reproduce

Clone the [gatsby-starter-default v2](https://github.com/gatsbyjs/gatsby-starter-default/tree/v2) 

Add this to the `gatsby-node.js` file
```js
exports.createPages = ({actions}) => {
  const { createRedirect } = actions;
  
  createRedirect({
    fromPath: '/foo.html',
    redirectInBrowser: true,
    toPath: '/bar',
  });
};
```
and then try to visit the `/foo.html` url

### Expected result

To be redirected to `/bar`

### Actual result

`TypeError: history.replace is not a function` error throws

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.9.2 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 68.0.3440.84
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-beta.64 => 2.0.0-beta.67 
    gatsby-plugin-catch-links: ^2.0.2-beta.5 => 2.0.2-beta.5 
    gatsby-plugin-feed: next => 2.0.0-beta.4 
    gatsby-plugin-glamor: next => 2.0.0-beta.3 
    gatsby-plugin-google-analytics: next => 2.0.0-beta.3 
    gatsby-plugin-manifest: next => 2.0.2-beta.3 
    gatsby-plugin-netlify: next => 2.0.0-beta.5 
    gatsby-plugin-nprogress: next => 2.0.0-beta.4 
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4 
    gatsby-plugin-sharp: next => 2.0.0-beta.7 
    gatsby-plugin-twitter: next => 2.0.0-beta.3 
    gatsby-remark-autolink-headers: next => 2.0.0-beta.5 
    gatsby-remark-code-repls: next => 2.0.0-beta.4 
    gatsby-remark-copy-linked-files: next => 2.0.0-beta.3 
    gatsby-remark-embed-snippet: next => 3.0.0-beta.3 
    gatsby-remark-images: next => 2.0.1-beta.9 
    gatsby-remark-prismjs: next => 3.0.0-beta.5 
    gatsby-remark-responsive-iframe: next => 2.0.0-beta.3 
    gatsby-remark-smartypants: next => 2.0.0-beta.3 
    gatsby-source-filesystem: next => 2.0.1-beta.10 
    gatsby-transformer-remark: next => 2.1.1-beta.5 
    gatsby-transformer-sharp: next => 2.1.1-beta.6 
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

### PR DESCRIPTION
**Pull request by alexandernanberg**
Fixes #7000 

It also works if we use `window.___history.replace` but I think it is more correct to use `window.___replace` right?

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 4824ac6de67a67dd58b802b70ed64959d5952ebf

https://app.netlify.com/sites/using-postcss-sass/deploys/5b65dc8573f2cf7e314f76eb

**Comment by KyleAMathews** [comment]
Yup as history.replace will immediately navigate while `window.___replace` will make sure the resources for the next page are loaded before navigating.

Thanks for finding the fix!

**Comment by alexandernanberg** [comment]
Oh but in this scenario (a redirect) wouldn't it make more sense to use `history.replace` tho? Because if the page that you are redirecting to is really heavy you have to wait for it to fully load before navigating? 🤔

**Comment by alexandernanberg** [comment]
Ah okay, got it 👍

**Pull request merged**
