### PR TITLE
perf(gatsby-source-contentful): dont re-create nodes

### PR DESCRIPTION
**Pull request by pvdz**
A warm build will currently still attempt to create the node even if it already exists. This PR will do an early check, compare the digest (`entry.sys.updatedAt`), and return early if the node already exists for that digest.

There might be a simpler solution but for now, this cuts the warm "no changes" build for a 2 million node site down from to about 894s (120s for node createion step) down to 512s (35s for the node creation step), saving about 5 minutes.

Need verification from Contentful that this approach is sound. But I think it is. (Tests will fail too, will fix them before we merge)

### CODE REVIEW

**Comment by wardpeet** [comment]
This makes code harder to reason with. The real issue is inside gatsby-node where we merge existing nodes together with new nodes. That part needs to refactor so I'm inclined to close that PR for that reason

**Comment by wardpeet** [comment]
I was missing a lot of context on the why here. I'm fine with this patch as it does improve performance. If we could run some tests to make sure references and all are still being updated 👍

**Comment by zcei** [comment]
Heja there 👋 

got hinted to this PR by @axe312ger, I'm one of Contentful's backend engineers and want to increase your confidence into the solution. 🙂 

For a single given Contentful entity, a write towards it will update its `.sys.updatedAt` property. This is even the case for no-change writes (i.e. a PUT to an entity with the same payload as its current shape).

That means using the `.sys.updatedAt` property for cache invalidation even gives users the ability to easily invalidate single nodes without changing content (why ever this might be useful 🤷‍♂️ ).

Phrased differently: 
* **same updatedAt** the content of two versions of one entity _is_ the same.
* **different updatedAt** the content of two versions of one entity _might_ be the same 

Hope this helps!

**Comment by axe312ger** [comment]
Rerunning CI

**Review by axe312ger — APPROVED** [review]
LGTM

**Pull request merged**
