### PR TITLE
Adding bootstrap CV starter

### PR DESCRIPTION
**Pull request by mhjadav**
Add bootstrap based template to list of starters
Demo url - https://elegant-hawking-bbad05.netlify.com/

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 9d690edd670a0b96dbad9951169572b9d0f0bbcf

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6d18f682d3f10976405169

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 9d690edd670a0b96dbad9951169572b9d0f0bbcf

https://app.netlify.com/sites/gatsbyjs/deploys/5b6d18f582d3f10976405161

**Comment by KyleAMathews** [comment]
Deploy preview for *using-jss* failed.

Built with commit aa4873c6bdcd344572761ff8ced732c078303482

https://app.netlify.com/sites/using-jss/deploys/5b6d5ddac6aed659ee26cbd9

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit aa4873c6bdcd344572761ff8ced732c078303482

https://app.netlify.com/sites/image-processing/deploys/5b6d5ddac6aed659ee26cbb8

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit aa4873c6bdcd344572761ff8ced732c078303482

https://app.netlify.com/sites/using-glamor/deploys/5b6d5ddac6aed659ee26cbbb

**Comment by KyleAMathews** [comment]
Deploy preview for *using-styled-components* failed.

Built with commit aa4873c6bdcd344572761ff8ced732c078303482

https://app.netlify.com/sites/using-styled-components/deploys/5b6d5ddac6aed659ee26cbbe

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit aa4873c6bdcd344572761ff8ced732c078303482

https://app.netlify.com/sites/using-contentful/deploys/5b6d5ddac6aed659ee26cbc1

**Comment by mhjadav** [comment]
Thanks @m-allanson 😊

**Pull request merged**
