### PR TITLE
fix for cheerio v1

### PR DESCRIPTION
**Pull request by 3axap4eHko**
Fix
https://github.com/gatsbyjs/gatsby/issues/2536
https://github.com/gatsbyjs/gatsby/issues/2493

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Looks great! Just updated the snapshots so tests should pass now.

**Comment by 3axap4eHko** [comment]
@KyleAMathews are the jest snapshots correct?

**Comment by KyleAMathews** [comment]
Yeah, what failed before was a linting error.

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
