### PR TITLE
chore(gatsby-source-filesystem) Migrate package to Typescript

### PR DESCRIPTION
**Pull request by arthurjdam**
## Description

Migrates `gatsby-source-filesystem` to Typescript
A little more changes than I wanted, but the interface stays the same entirely. 

## Related Issues

Related to #21995

### CODE REVIEW

**Comment by arthurjdam** [comment]
`ci/circleci: integration_tests_gatsby_cli` failing until #22699 is done I guess?

**Comment by blainekasten** [comment]
@arthurjdam Hey there! Holy buckets this was a lot of changes 🎉 

I'm not sure what to do with this yet. We aren't targeting source packages or other plugin packages right now for TS conversions. At the moment we are only doing the packages outlined in #21995.

I'm going to leave this PR here for now. We might merge this later, but unfortunately I'm not sure if we are wanting to accept these changes yet. We are beyond thankful for your hard work and hope you can jump into make typescript contributions for the files outlined in that issue. 💜

**Comment by arthurjdam** [comment]
No worries. Feel free to close if source packages won't make it onto the roadmap

**Comment by LekoArts** [comment]
Let's close this for now as we currently can't/want to also process PRs for these packages. Thanks for the PR though, once we want to convert these packages we'll write in the Umbrella issue!

**Pull request closed without merging**
