### PR TITLE
fix(gatsby-plugin-netlify): do not cache service worker file on Netlify

### PR DESCRIPTION
**Pull request by matthieuauger**
Related to https://www.netlify.com/blog/2018/06/28/5-pro-tips-and-plugins-for-optimizing-your-gatsby---netlify-site/#4-get-your-service-workers-um-working

Recommandation is not to cache service worker file : https://github.com/w3c/ServiceWorker/issues/893

### CODE REVIEW

**Comment by DaleJefferson** [comment]
Is this PR compatible with https://github.com/gatsbyjs/gatsby/pull/9245

**Comment by matthieuauger** [comment]
@DaleJefferson Yes, if the line provided by @tanvibhakta is added after mine, it will

**Comment by pieh** [comment]
@matthieuauger, @DaleJefferson That PR need changes - we won't be targetting all js files - we will read manifest from webpack and use assets paths generated by webpack (which will have hash for cache busting)

**Comment by pieh** [comment]
Published `gatsby-plugin-netlify@2.0.5`

**Comment by matthieuauger** [comment]
@pieh Really no need to be sorry, thanks for what you do!

About you last comment any hints about how we should perform this so I could have a look?

Thanks

**Pull request merged**
