### PR TITLE
fix: Bumping Serve Up to 9.2.0 Broke Calls to Serve's API

### PR DESCRIPTION
**Pull request by trvsysadmin**
Follow Up on:

https://github.com/gatsbyjs/gatsby/issues/6546

https://github.com/gatsbyjs/gatsby/commit/69125ccb5604830f6b11996ff3f6dddbe6fe0260

Apologies in advance if some things are lacking, not super familiar with gatsby code base yet. I tested locally for v1 and it was fine.

In particular:
- is `directory` still needed? See https://github.com/zeit/serve-handler#public-string
- is `open` still needed?

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit f83d18f08db5ad12311e8560e042e56093efa2b1

https://app.netlify.com/sites/using-postcss-sass/deploys/5b51658fe39e7c041042611e

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit f83d18f08db5ad12311e8560e042e56093efa2b1

https://app.netlify.com/sites/gatsbyjs/deploys/5b51658ee39e7c0410426116

**Comment by KyleAMathews** [comment]
Yeah, you can run `gatsby serve --open`. We should use something like https://www.npmjs.com/package/openurl to restore opening the URL after it's started.

**Comment by KyleAMathews** [comment]
We don't need `directory` because `serve` defaults to using the current working directory as the base? E.g. you don't need an absolute path anymore?

**Comment by trvsysadmin** [comment]
## Directory Question

Yes it seems to be so as far as this description: https://github.com/zeit/serve-handler#public-string

```
By default, the current working directory will be served. If you only want to serve a specific path, you can use this options to pass a custom directory to be served relative to the current working directory.

For example, if serving a Jekyll app, it would look like this:

{
  "public": "_site"
}
```

**Comment by trvsysadmin** [comment]
# Dash Dash Open Option

- I checked the current package.json and `opn` is already there
- `openurl` dies for me via "GPU Process Fail" or something like that - I am on a ubuntu16 latest Chrome
- `opn` has no such issue.

**Pull request merged**
