### PR TITLE
examples: Update using-mdx

### PR DESCRIPTION
**Pull request by pragmaticpat**
## Description
The existing example doesn't even work currently. This PR updates the chart library used, and ensures the project works for users.

- [x] Update the examples to use a well-supported charing library
- [ ] ~~Make the repository name consistent with the expected format~~

Todo

- [x] Show a bar chart example
- [x] Show a line chart example
- [x] Ensure the code is commented to explain what's happening

### CODE REVIEW

**Comment by pragmaticpat** [comment]
Thanks for updating to use `gatsby-plugin-image` also @Khaledgarbaya ! 🙌

**Comment by pragmaticpat** [comment]
I think we're good to open the PR at this point. Thanks for your help again @Khaledgarbaya

**Comment by pragmaticpat** [comment]
@Khaledgarbaya - I'd also like to get this folder updated to be `using-mdx` instead of `using-MDX` - no need for the upcase.

What's the best way to do this without breaking incoming links to the upcase version? That's the only thing left on this todo list at this point.

**Comment by Khaledgarbaya** [comment]
@pragmaticpat I don't see way there, redirects only available in Github pages

**Comment by pragmaticpat** [comment]
We'll skip the directory rename.  I'll now open the PR. Thanks for the help @Khaledgarbaya

**Review by LekoArts — APPROVED** [review]

**Pull request merged**
