### PR TITLE
chore(showcase): Add Chris Otto's Site

### PR DESCRIPTION
**Pull request by chrisotto6**
## Description

Add Chris Otto's Site to the Gatsby Showcase

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! Site looks great.

I noticed that the README doesn't include instructions for running the site. Can we update that and then we can get this merged?

**Comment by chrisotto6** [comment]
@laurieontech you bet! That has been done with the following commit:

https://github.com/chrisotto6/chrisottodev/commit/19fd5e23bacc960a197344843f43277d1b64a2ab

**Comment by laurieontech** [comment]
Looks great! And so fast.

**Comment by chrisotto6** [comment]
Thank you for the review and merge!

**Pull request merged**
