### PR TITLE
fix(gatsby): Fixed error message when path is undefined

### LINKED ISSUE #18661: Hot reloading error: "path" argument must be of type string
Hot reloading in `gatsby develop` gives this error in my project. Hot reloading sometimes works despite the error (as in, I see the error in the console window where I ran `gatsby develop`, but the website in browser appears to hot reload and work just fine). This error appeared after I updated some (mainly Gatsby) npm dependencies. Stack trace is giving me no ideas on how to debug this. Is it a Gatsby bug?

Note that this error only comes up on hot reload. So I can run `gatsby develop` just fine as long as I don't make any changes to any files. I can also build just fine.

```
[ { TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
      at assertPath (path.js:39:11)
      at Object.resolve (path.js:1085:7)
      at findLinkedFileNode (/.../node_modules/gatsby/dist/schema/resolvers.js:208:47)
      at resolveValue (/.../node_modules/gatsby/dist/schema/resolvers.js:223:108)
      at /.../node_modules/gatsby/dist/schema/resolvers.js:220:10
      at process._tickCallback (internal/process/next_tick.js:68:7)
    message:
     'The "path" argument must be of type string. Received type undefined',
    locations: [ [Object] ],
    path:
     [ 'allMarkdownRemark', 'edges', 0, 'node', 'frontmatter', 'cover' ] } ]

```

### PR DESCRIPTION
**Pull request by drakeloud**
## Description

PR to fix the issue with the findLinkedFileNode assuming that 'dir' attribute exists on the object. Adds null and undefined check so that Path.resolve is not passed erroneous data. 

## Related Issues

Link to the issue that is fixed by this PR (if there is one)
Fixes #18661

### CODE REVIEW

**Comment by Jc2k** [comment]
I believe this also fixes #17469. There is another user hitting this on [StackOverflow](https://stackoverflow.com/questions/58358559/gatsby-develop-crashes-every-time-a-blog-entry-is-changed/58540703#58540703) too.

**Comment by pieh** [comment]
See my comment in the issue - https://github.com/gatsbyjs/gatsby/issues/18661#issuecomment-545912376 - this just silence the error and is not actually fixing it. I'm not yet sure why this happens (we can't find File node that is parent of remark/mdx node)

**Comment by drakeloud** [comment]
Hmm. I'm not exactly sure why either... I can keep looking around to see if I can find the root issue. I'm not super familiar with the Gatsby codebase yet, but I am happy to dig a little deeper.

**Comment by pieh** [comment]
Let's close this PR as this is not correct fix. I'll add some context to the issue about how this should work (and which parts seems not to work anymore).

**Pull request closed without merging**
