### PR TITLE
Topics: Add gatsby-plugin-decap-cms

### PR DESCRIPTION
**Pull request by ErikAGriffin**
## Description

The package `gatsby-plugin-netlify-cms` is referencing a deprecated version of the Netlify CMS, which is now Decap CMS.  Please see https://github.com/gatsbyjs/gatsby/issues/38553.  

### Documentation

Documentation updated with correct references to Decap CMS.

### Tests

Only a few code references were changed, as well as the docs.  If someone can help instruct me on how to install this new plugin package before it is published I will be able to test further that there are no mistakes.

## Related Issues

https://github.com/gatsbyjs/gatsby/issues/38553

### CODE REVIEW

**Comment by ErikAGriffin** [comment]
@LekoArts could I please get a review on this?  It's blocking quite a bit of work, and is a very low-complexity change that adds a plugin appropriately referencing DeCap CMS.

**Comment by JackDevAU** [comment]
bump - This is a major pain :( 
Please approved this PR :(

**Comment by Isaac-Tait** [comment]
Decap released a beta version of their CMS to test compatibility with React 18 (and by default Gatsby) https://github.com/decaporg/decap-cms/discussions/6954#

**Comment by MarcL** [comment]
After a discussion with the Decap team, we agreed that the Decap CMS plugin will live in their repo rather than in Gatsby.

https://github.com/decaporg/gatsby-plugin-decap-cms

We'll add a deprecation notice for the `gatsby-plugin-netlify-cms` package which points users to the new plugin.

**Pull request closed without merging**
