### PR TITLE
Docs: Rm stubs from sidebar

### PR DESCRIPTION
**Pull request by amberleyromo**
@shannonbux @DSchau.

Just rms some of the incomplete stubs we discussed from sidebar. Shannon, I also removed some from under Images. As discussed, left the actual stub pages intact.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Perhaps we could have a page in each section (or in its index page) that lists docs pages we'd like to add, links to their markdown files, and talks about the process for adding additional documentation?

**Comment by KyleAMathews** [comment]
A lot of the stubs _have_ led to contributions so just removing them altogether seems sub-optimal. Still expose them but make it clear they're not interesting.

I don't want us to overreact to one grumpy tweet.

**Comment by amberleyromo** [comment]
@KyleAMathews this is not removing all of the stubs. It's just removing some of them from being linked in the sidebar. We had a separate conversation in Slack that touched led to the conclusion that if we want a contributor to pick up a stub, it needs to be more tightly scoped / described (a valid request). In the meantime, before @shannonbux can revisit, we decided to remove some of them from the sidebar.

**Comment by amberleyromo** [comment]
IMO we're not overreacting to a grumpy tweet, we discussed the context around a piece of valid feedback (that happened to be in the form of a grumpy tweet 😉) and decided how we wanted to approach it.

**Comment by KyleAMathews** [comment]
Sorry for not being clear about my critique — my point is that issues in PRs have a lot less visibility than when they're exposed somehow within the docs. Issues get 100x (more or less) less visitors than the website.

Exposing prospective docs pages in the sidebar a) can lead to new contributors and b) lets people know that Gatsby's docs are actively growing and improving.

I totally agree that issues are a good thing as we found with Oktoberfest as it makes it easier for someone to claim work just don't want to lose value from the other reasons we've had stub docs.

**Comment by amberleyromo** [comment]
Sure, that's a valid critique. I was not sure of @shannonbux's intent with some of these docs, and she doesn't remember making some of these stubs; Therefore she could not speak to the context/intent behind them. Combined with the fact that the docs should reflect her research findings, I thought this was a fair way to proceed (if she doesn't remember making them, and they're inadequately scoped, why leave them there?) I removed the parts under images as well, because I previously had a similar conversation about that section during Hacktoberfest.

The main thought I'll leave here is that I think any doc that's up as a stub should be formatted such that A) the intent is clear B) it's scoped for a contributor to easily pick up (if they choose).

https://github.com/gatsbyjs/gatsby/issues/10373#issuecomment-445603250
> I would say the title is not so clear, If I wanted to write something under that title, I probably wouldn't. The stubs should explain the context of that page with at least one paragraph I think.
> 
> It does not look very inviting to edit or contribute to be honest.

I do agree with this feedback.

Overall tl;dr:  I'll leave this up to @shannonbux since it's her area.

**Comment by shannonbux** [comment]
@KyleAMathews I'm fairly certain that in this whole year, only the testing section of stubs has ever been picked up by contributors outside of the content migration project, which we managed during Hacktoberfest (I could be wrong, would need to measure this). So, we reasoned that we need to replicate the Hackborfest style of issues for each stub article in order for them to every get finished. I don't care too much whether the stub articles stay up right now or not. Perhaps we could put them back up after we've linked to the issue that describes how to fill out the stub article?

**Comment by KyleAMathews** [comment]
I'm not overly concerned about how we do things but some way of indicating to people planned additions and asking for help to write them is important. Perhaps even just having one page that lists docs we'd like written would work.

It'd be cool if there's a way for people to vote as well which we could do once we add GitHub logins.

**Comment by shannonbux** [comment]
Yeah that sounds awesome @kyleamathews. I'm working on issues for all stub
articles. For now, will put them in an overview issue or epic to see how
that goes.

**Pull request closed without merging**
