### PR TITLE
Add --https option for `gatsby develop`

### PR DESCRIPTION
**Pull request by fabe**
Regarding #1975.

This adds the option of using HTTPS for `gatsby develop`, thanks to [`devcert`](https://github.com/davewasmer/devcert). The implementation is heavily inspired by what [`preact-cli`](https://github.com/developit/preact-cli) has done, minus the fallback to `simplehttp2server`. Wondering if that's necessary?

So using `-S` or `--https` would give you:

cert

It appears that only `localhost` is verified, so it probably won't work well together with `--host`. Same behavior can be seen at `preact-cli`.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Nice! I looked at preact-cli's implementation a while ago and thought it'd be great to port over as well.

Code looks really good from a quick look over — figuring out HMR would be great of course.

**Comment by fabe** [comment]
HMR does work with this on both `http` and `https`, I'm checking for the flag inside [gatsby/src/utils/webpack.config.js](https://github.com/gatsbyjs/gatsby/pull/4522/files#diff-c4777e791f64fbb6c82255341b381dabR147), so we should be good there.

**Comment by KyleAMathews** [comment]
Cool!

Could you add some docs? It looks like there's some extra software that needs installed and steps to follow. Perhaps a new guide in the docs? Then link from the CLI help to the docs page https://www.npmjs.com/package/devcert-san

**Comment by fabe** [comment]
Sure, guide is added to the docs! Also linked it from the `gatsby-cli` readme.

**Comment by KyleAMathews** [comment]
Nice! Thanks for the great work!

**Pull request merged**
