### PR TITLE
chore(starter): Gatsby Starter with Docz and Netlify CMS

### PR DESCRIPTION
**Pull request by colbyfayock**
## Description

Starter that spins up a Gatsby-powered Docz site with Netlify CMS to manage the content.

### Documentation

https://gatsby-starter-docz-netlifycms.netlify.com/

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! Starter looks great.
Could you update the README in the repo with instructions for using the starter? The [gatsby-default-starter README](https://github.com/gatsbyjs/gatsby-starter-default) is a good example.

**Comment by colbyfayock** [comment]
@laurieontech updated the README to show how to bootstrap the app locally (particularly the Gatsby spinup). i plan on utilizing the deployed example of it (the starter itself) with more instructions on how to do anything within the CMS, would that work okay? https://gatsby-starter-docz-netlifycms.netlify.com

**Comment by laurieontech** [comment]
Thanks! Overall it looks great. I noticed the instructions use `yarn develop`. To keep things consistent it'd be good to use `gatsby develop`. Beyond that I think this is good to go.

**Comment by colbyfayock** [comment]
is that a new requirement for starters? i've always used `yarn develop` for the other starters I've successfully submitted with no issues. 

beyond that - the issue here is it doesn't actually use gatsby to build from a user point of view, it uses the `docz` cli to perform that. see `package.json`:

```
  "scripts": {
    "develop": "docz dev",
    "build": "docz build --dest public",
    "serve": "docz serve"
  },
```

**Comment by laurieontech** [comment]
We're trying to be more in line with the main Gatsby documentation so that users have a consistent experience. The main docs use Gatsby commands npm installation. If this particular starter has a reason that it can't use those commands we can merge without that. But perhaps we can compromise to use npm for at least some consistency?

**Comment by colbyfayock** [comment]
sure, though ill need to swap lockfiles then - will be able to grab that later this evening

**Comment by laurieontech** [comment]
Thanks @colbyfayock. The hope is that newer users are able to pick up plugins and starters based on having just started working through the tutorial. Lower the barrier to entry :)

**Comment by colbyfayock** [comment]
fair enough :) should be good to go with npm!

**Comment by laurieontech** [comment]
Awesome! LGTM.

**Pull request merged**
