### PR TITLE
chore: standardize on lowercase/dasherized file names

### PR DESCRIPTION
**Pull request by DSchau**
## Description

I've seen some tweets that indicate that _sometimes_ there can be confusion as to whether to use uppercase or lowercase conventions for React component file names.

This isn't specific to Gatsby, but we can resolve some of this by documenting a consistent format, and for that I'd recommend that we consistently document lowercase with a dash separating terms (dasherized, e.g. NavBar is `nav-bar.js`). This is what we use in the starters (e.g. src/components/header.js instead of src/components/Header.js) outside of the blog starter--which has been normalized in this PR.

I've also done a simple find and replace for usage of these (e.g. src/components/Bio.js -> src/components/bio.js) so that the documentation matches the usage. There are additional uppercase components (e.g. src/components/SEO.js) but I left those as is, since the usage of them where referenced is also uppercase.

## Related Issues

Sorta related to gatsbyjs/gatsby#10671 as well as my comment [here](https://github.com/gatsbyjs/gatsby/pull/10690#discussion_r244221748)

### CODE REVIEW

**Comment by DSchau** [comment]
Also note I removed some misc. files from the starter blog (e.g. .eslint.js, .travis.yml, etc.)

**Comment by polarathene** [comment]
>  lowercase with a dash separating terms (dasherized, e.g. NavBar is nav-bar.js)

This is called [kebab-case](https://medium.com/@pddivine/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841)

**Comment by DSchau** [comment]
@polarathene lodash (and probably jQuery, underscore, and other libraries) popularized the kebab-case term, but it's been called a few different things (including dash-case).

https://stackoverflow.com/a/17820138

But yeah--noted. Thanks!

**Comment by DSchau** [comment]
@pieh mentioned a possibly helpful plugin to automate this out.

https://github.com/selaux/eslint-plugin-filenames

Worth checking out as part of this PR

**Comment by DSchau** [comment]
@ZYSzys re: uppercase, yeah, I honestly don't really care what we use as long as it's consistent. I tend to use kebab-case (dash-case) in my personal projects, but as long as we are consistent in a style I vote that.

Also note, that we don't really use Airbnb style-guide in Gatsby whatsoever, although it certainly is ubiquitous!

**Comment by LekoArts** [comment]
What's the status here? 😊 Do only the merge conflicts need to be resolved?

**Comment by DSchau** [comment]
@LekoArts it should be ready now. Sorry for the delay!

**Pull request merged**
