### PR TITLE
Update deploying user/org site to gh-pages docs

### PR DESCRIPTION
**Pull request by psongpin**
Added Section for creating user/org sites in gh-pages

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Can you use `gh-pages` (the NPM package) for this? That'd be preferable.

Also please move your new section after the instructions for padding project sites as I'd guess people will more frequently create project sites than user/org sites.

**Comment by psongpin** [comment]
Not sure if we can automate this process using gh-pages npm package. But I can only think of pushing the whole project under `username.github.io` repo then moving all contents of the public folder in the root folder of the gatsby project.

**Comment by psongpin** [comment]
or the other way around placing build contents in the root folder then push it to `username.github.io`

**Comment by KyleAMathews** [comment]
Another way would be to use `gh-pages` still. Keep the source for the website on a `src` or `gatsby` branch (or whatever) and then the build script, using `gh-pages` would publish the site to the `master` branch.

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit bb4cf4af87b379de1630db7f91606b3dc7501d98

https://app.netlify.com/sites/using-glamor/deploys/599df297cf321c08ba804665

**Pull request merged**
