### PR TITLE
Reload page if resource fetch fails, and appears online

### PR DESCRIPTION
**Pull request by lsirivong**
Addresses #2954, #1807

### CODE REVIEW

**Comment by KyleAMathews** [comment]
woah awesome!

This is almost 100% correct. The problem still is that the loader is often "prefetching" resources. So when loading something fails, we're not necessarily ever going to visit that page. What we should when a page fails is mark the path as "corrupted" or something like that, so when gatsby-link tries to go to that page, it checks to see if the path is corrupted and if so, does a full-reload.

Also we'd need to account for when the navigation to that page is already in progress — in that case, we should send an event saying this path didn't load correctly and have component-renderer.js trigger the reload — at least I think that'd be the right place after thinking about it briefly :-)

Thoughts?

**Comment by lsirivong** [comment]
Failed prefetching resources won't trigger a reload and I think it's okay to wait until `getResourcesForPathname` is called to do so, since that's the last possible moment when they are necessary.

Just to make sure we're on the same page, in this branch, what will happen is:

1. index page is loaded, which attempts to prefetch resources for page-2
2. let's say that fails - index page still interactable
3. upon navigation to page-2 the loader will again attempt to fetch resources
4. this time failure will trigger the reload

> Also we'd need to account for when the navigation to that page is already in progress

Am I understanding correctly that this only necessary if we start tracking corrupt pages from prefetch results as suggested?

**Comment by KyleAMathews** [comment]
The downside to checking again on actual navigation is that we'd have to wait again for a failed request — which on slow connections could take a while. I'd prefer a heuristic that set a global saying "the client is outdated cause it's getting intermittent 404s on resources" and then on the next page navigation, immediately triggering a reload.

**Comment by lsirivong** [comment]
Ah I see. Thanks for that explanation.

I'll take a crack at adding that to this PR sometime this week.

**Comment by lsirivong** [comment]
OK! I've added tracking so failed paths & resources aren't attempted more than once.

@KyleAMathews I didn't add any event handling via component-renderer since in my testing I wasn't seeing how "navigation to that page is already in progress" could happen and not get caught by these changes.

**Comment by KyleAMathews** [comment]
Looks awesome! This is a really elegant solution and will cover a lot of edge cases where Gatsby sites can break now 🎉 

Touching Gatsby's runtime is always tricky though as it can break a lot of stuff potentially. Could you describe how you've been testing this? I can take that to do my own testing + try to break it in other ways 😈

**Comment by lsirivong** [comment]
Cool! Thanks for taking another look at this.

Here's how I tested: I was using this in an example project that had 3 pages, where the index linked to page-2 and page-2 linked to page-3. (Not much to it, but can be viewed [here](https://github.com/lsirivong/gatsby-page-sample))

1. `yarn build`
2. `mv public public-a`
3. Edit the content of a page so that the it's resource would change and would have a different hash
4. `yarn build`
5. `http-serve public`
6. Load the home page of the project in a browser
7. `mv public public-b && mv public-a public`
8. Click on link to page-2
  - this should successfully load page-2 and attempt to fetch page-3 resources. The page-3 resources should fail since they've changed.
9. Click on link for page-3
  - Should trigger an app reload, getting the current page-3 content.

I would then repeat step 7 as I iterated, swapping between the 2 rendered folders to simulate the content of the site getting re-deployed in the middle of a browser session.

Since the parts of the loader that were modified here only error handling scenarios, I believe the impact to the internals should be pretty minimal.

**Comment by KyleAMathews** [comment]
Thanks! I'm out the rest of the day but almost certainly can land this tomorrow 🎉

**Comment by KyleAMathews** [comment]
Great stuff! Tested it and it worked perfectly <3 this it's so elegant. Love it.

**Comment by KyleAMathews** [comment]
Out in 1.9.133

**Pull request merged**
