### PR TITLE
chore(gatsby-plugin-mdx): refactored to use createContentDigest (#8805)

### PR DESCRIPTION
**Pull request by StanEgo**
## Description
gatsby-plugin-mdx refactored to use createContentDigest helper

## Related Issues
#8805 feat: update gatsby plugins to use new createContentDigest helper

### CODE REVIEW

**Comment by muescha** [comment]
please see this comment: https://github.com/gatsbyjs/gatsby/pull/18139#pullrequestreview-299211154

**Comment by muescha** [comment]
hi @StanEgo it is similar to #20076
if you don't have time i would like complete it

**Comment by StanEgo** [comment]
Hi @muescha. Check please if this is what you've asked for.

**Comment by muescha** [comment]
yes - thx :)

but the @gatsbyjs/core core team has to approve & merge the PR

**Pull request merged**
