### PR TITLE
Look's Like the image is missing

### PR DESCRIPTION
**Pull request by kaknut**
Image giving 404.
URL: https://www.gatsbyjs.org/packages/gatsby-plugin-sharp
Location: Just above https://www.gatsbyjs.org/packages/gatsby-plugin-sharp/#fit

Just checking if build passes and image get's recognized. Not sure though.

### CODE REVIEW

**Comment by kaknut** [comment]
Mind having a look @KyleAMathews ?

**Comment by LekoArts** [comment]
There's no need to individually mention people, please hold off on that and wait until the PR is triaged.

**Comment by vladar** [comment]
Thanks for opening this @kaknut !

But it is not entirely clear what your issue is and how this PR is solving it.

I suggest you open a GitHub issue first. Please follow [these steps](https://www.gatsbyjs.org/contributing/how-to-file-an-issue/) to fill an issue. It is also incredibly helpful if you provide a [minumum reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) for the issue (I assume that's what you are trying to do in this PR?)

Closing this PR for now. We can continue this discussion in the issue and prepare a new PR once it is clear what the issue is.

Thanks for using Gatsby 💜

**Comment by vladar** [comment]
Oh, I think now I understand what you mean. But still, it is better to start with an issue because it is probably related to gatsby.org website, not the plugin itself.

This image exists in the repository but is not displayed on the website. See here: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sharp#fit

So the issue you've discovered is valid but we need to address it somewhere else.

Thanks! 💜

**Comment by kaknut** [comment]
I'll open an issue but isn't the data pulled from the readme.md? Not sure which directory to look for.

**Comment by muescha** [comment]
@kaknut thx for PR and error report.

i created an issue based on your info: 

- #25999 `Bug: relative url for links and images in package readme are not working`

**Pull request closed without merging**
