### PR TITLE
[docs][gatsby-plugin-styled-components] .babelrc config

### PR DESCRIPTION
**Pull request by Mokkapps**
Add information about `.babelrc` configuration from [styled-components tooling docs](https://www.styled-components.com/docs/tooling#babel-plugin) to `gatsby-plugin-styled-components` docs

### CODE REVIEW

**Comment by LeKoArts** [comment]
The plugin is already doing that for you:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-styled-components/src/gatsby-node.js

**Comment by Mokkapps** [comment]
@LeKoArts Thanks for the link, that makes sense. Unfortunately, I had to add it manually in my case. 

Maybe because I first installed `gatsyb-plugin-styled-components` in the lastest `3.0.0-rc.1` version and `babel-plugin-styled-components` afterwards?

**Comment by LeKoArts** [comment]
If you added the entry in gatsby-config.js file it *should* work

**Comment by Mokkapps** [comment]
@LeKoArts I did but my `.babelrc` had no corresponding entry in the plugin section.

Ok but nevertheless it is not necessary to add this to the documentation at the moment.

Thanks!

**Pull request closed without merging**
