### PR TITLE
<BrowserRouter> ignores the history prop. #1913

### PR DESCRIPTION
**Pull request by 3axap4eHko**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
The `<Router>` component is the low-level component higher-level ones like `<BrowserRouter>` use and is what you're supposed to use with custom history implementations.

**Comment by KyleAMathews** [comment]
I made the same change to the production entry file/router implementation.

Thanks!

**Comment by 3axap4eHko** [comment]
@KyleAMathews I think production change is not necessary be cause there are no runtime history object changes

**Comment by KyleAMathews** [comment]
@3axap4eHko I think it's necessary as there's an API to make customizations to the history object which I guess wasn't working without this?

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit eb7f29825ebcd4f217fcb5d9f11e587f53f95ced

https://app.netlify.com/sites/using-glamor/deploys/59a469457960b17dd8d3faac

**Comment by jlengstorf** [comment]
Hiya @3axap4eHko! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
