### PR TITLE
team development workflows

### PR DESCRIPTION
**Pull request by calcsam**
People using Gatsby for professional website development projects have reported a number of workflow changes. I've catalogued a few here as a starting point.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
My thought reading this is that this should start as a blog post — I agree with @m-allanson that it doesn't feel quite right in the docs as is. @shannonbux is working on a revamp of the IA of the docs so might have thoughts.

**Comment by calcsam** [comment]
Seems reasonable. Changing this to a blog post.

**Comment by calcsam** [comment]
@shannonbux let's discuss sometime later where this would go in a revised IA

**Comment by shannonbux** [comment]
Great @calcsam and love this as a blogpost and think it could turn into an article eventually. Since it's a persuasive kind of document, it seems like it'd fit in either as an introduction / starting point to case studies (seems like a good fit to me), an introduction / starting point to more factual guides on workflow (I'd probably hesitate to do this one), or fit into either .com or .org groupings of articles on "why choose Gatsby?" (seems like the easiest fit to me), which wouldn't be in docs.

**Pull request merged**
