### PR TITLE
chore: more cleanup after Node 8 drop

### PR DESCRIPTION
**Pull request by shisama**
## Description

Node.js v8 is scheduled to stop maintenance on December 2019.
Please see https://nodejs.org/en/about/releases/

This is still draft. This will be opened when Node.js v8 will be End-of-Life.

### CODE REVIEW

**Comment by pvdz** [comment]
Related: https://github.com/gatsbyjs/api.gatsbyjs.org/pull/33

**Comment by pvdz** [comment]
I think the `yarn.lock` file changes also need to be dropped...?

**Comment by shisama** [comment]
@sidharthachatterjee Thank you for your review. I changed lowest version to v10.13.0.

**Comment by shisama** [comment]
@pvdz Thank you. I dropped `yarn.lock` file change which needs not to be changed.

**Comment by sidharthachatterjee** [comment]
I've added a deprecation warning in https://github.com/gatsbyjs/gatsby/pull/20466

Let's give people a month and then get this in. Marking as blocked for now. Thanks!

**Comment by pieh** [comment]
There are couple of good changes here that we missed in https://github.com/gatsbyjs/gatsby/pull/22400 so I synced it

**Pull request merged**
