### PR TITLE
fix(docs): Remove `--save` from install prompts

### PR DESCRIPTION
**Pull request by lacrosse91**
## Description

--save is no longer necessary for modern versions of npm, so I fixed pages of docs/docs folder.
## Related Issues

#22444

### CODE REVIEW

**Comment by LekoArts** [comment]
I'd be great to change all occurrences of `--save` in one PR. Would you be up for making the changes?

My IDE finds alone in the `docs/docs` folder 79 matches:

image

You can ignore the `docs/blog` folder.

**Comment by lacrosse91** [comment]
@LekoArts 
Thanks for review!
I will change occurrences of `--save` except for `docs/blog` folder.

**Comment by lacrosse91** [comment]
@LekoArts 
 I removed `--save` from `npm install` in `docs/docs` folder.
Please review the changes.

**Review by LekoArts — APPROVED** [review]
Looks good to me! Thank you very much for those changes! 🎉

**Pull request merged**
