### PR TITLE
docs(deploying-to-firebase.md): add firebase.json cache configuration

### PR DESCRIPTION
**Pull request by portenez**
Adds how to update the `firebase.json` to configure the firebase cache correctly.

## Description

The instructions to deploy to `firebase hosting` were missing the correct `firebase.json` configuration. This updated config file allows for the correct serving of gatsby content according to the gatsby caching guide: https://www.gatsbyjs.org/docs/caching/

### Documentation

Attn @gatsby/learning

References:

- Gatsby cache caching: https://www.gatsbyjs.org/docs/caching/

### CODE REVIEW

**Comment by portenez** [comment]
Here are 2 live sites running this config, if someone wants to take a look:

1. my personal blog [https://vgarcia.dev](https://vgarcia.dev/) with service worker.
2. A sample site deployed to firebase [https://gatsby-hosting-example.firebaseapp.com/](https://gatsby-hosting-example.firebaseapp.com/) without service worker.

**Comment by laurieontech** [comment]
Thanks for the PR! Want to verify this behavior before merging, so hang tight.

**Comment by laurieontech** [comment]
I'm wondering if we want to include the entire json file or if it'd make more sense to link to the [caching docs](https://www.gatsbyjs.org/docs/caching/) and note that those recommendations should be followed when setting up `firebase.json`?

**Comment by portenez** [comment]
I think it's very useful to have a sample `json` file. People could be up and running right away after reading this page. 

When I was setting up the cache for the first time, I did have the `gatsby caching` docs available, and even with those open took couple/several hours to completely get it right. 

There a few quirks here and there when setting up, and I have to deploy and test several times. In the end, people would end up with exactly the same `json` file. 

I guess we could indicate that this json asumes the defaults (like building agains `public`) and so on.

**Comment by laurieontech** [comment]
That seems fair to me. Just wanted to pose the question.

**Comment by laurieontech** [comment]
Looks good! Let's get this in.

**Pull request merged**
