### PR TITLE
Basic template for new issues

### PR DESCRIPTION
**Pull request by leandromuto**
A basic template to standardize the issues reported by the community.

### CODE REVIEW

**Comment by benjaminhoffman** [comment]
@leandromuto can you take advantage of html comment syntax `<!-- -->` just in case users forget to delete some of your explanations from your template.  See here for an example (click the preview tab to notice most of the text does not render): https://github.com/ReactTraining/react-router/issues/new

**Comment by benjaminhoffman** [comment]
also, please add some of the content & instructions listed here: https://github.com/gatsbyjs/gatsby/blob/master/CONTRIBUTING.md#filing-an-issue

**Comment by leandromuto** [comment]
@benjaminhoffman just updated the template. Please take a look and if you could give me a feedback, I'll appreciate! 👍🏼

**Comment by KyleAMathews** [comment]
Thanks! Good idea.

Tweaked the language a bit — let's get this in.

**Comment by jlengstorf** [comment]
Hiya @leandromuto! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by leandromuto** [comment]
Hi @jlengstorf 

Thank you so much for the swag, made my day with this awesome t-shirt! I'm not part of the Gatsby organization and would be an honor to be part of. Can you send me the invite again? I guess I deleted it accidentally :disappointed: 

Thanks again and keep up the good work! :muscle: :smile:

**Pull request merged**
