### PR TITLE
[v2] Update sitemap example

### PR DESCRIPTION
**Pull request by piotrkwiecinski**
Refs #5598

### CODE REVIEW

**Comment by pieh** [comment]
This example is very weird for me. It doesn't actually show sitemap other than linking to `https://gatsbyjs.org/sitemap.xml`. I was looking at git history and it seems like `gatsby-plugin-sitemap` has evolved, but example was never updated so I personally would just remove it from examples and add link to example sitemap.xml in plugin's description. Thoughts?

**Comment by piotrkwiecinski** [comment]
It is or other option would be to extend the example to include the post md files and add page exclude to align it more with plugins readme. I don't mind doing it. I wasn't sure if I should bundle both compatibility and new things here.

**Comment by pieh** [comment]
If you are up for updating whole example, then sure go for it - but this probably would to land in master (gatsby v1) first, and then get backported to v2 with added v2 compatibility changes

**Comment by piotrkwiecinski** [comment]
I'm going to park it for now and update V1 example and reopen this one after.

**Pull request closed without merging**
