### PR TITLE
Redirect from non-slash to slash page, fixes #452.

### LINKED ISSUE #452: Redirect from non-slash to slash page in development
This trips up people all the time.

This would be an easy PR if someone wants to take it on!

Check [here](https://github.com/gatsbyjs/gatsby/blob/ac270441f4489f0aca85720237b6a95dc6ff9da7/lib/utils/develop.js#L131) if the path ends with a slash and if not, add it.

### PR DESCRIPTION
**Pull request by babruix**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@babruix this looks great! Thanks!

If you could fix the lint errors real quick, I'll merge and make a new release.

**Comment by babruix** [comment]
I have fixed eslint issues, but don't have access to netlify build log.

**Comment by KyleAMathews** [comment]
Awesome, thanks! This will save a lot of people frustration.

Yeah, I enabled the Netlify stuff to start working on the website but haven't quite got to it yet so it's failing because there's nothing for it to do. So we can ignore that error for now.

**Comment by KyleAMathews** [comment]
Published 0.12.13 🎉

**Comment by jlengstorf** [comment]
Hiya @babruix! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
