### PR TITLE
fix(gatsby-source-wordpress): fetch referenced media items during single node updates

### LINKED ISSUE #31503: gatsby-source-wordpress Not reflecting changes from the WP GQL
## Description

Not seeing changes on the local Gatsby GraphQL. Images object returning `null` instead.

### Steps to reproduce

WP GQL Query:
```gql
query MyQuery {
  page(id: "cG9zdDoxMTA2NzA=") {
    id
    title
    generalModulesGroup {
      modules {
        ... on Page_Generalmodulesgroup_Modules_VerticalImageFeaturedModule {
          description
          images {
            horizontal {
              sourceUrl
            }
            vertical {
              sourceUrl
            }
          }
        }
      }
    }
  }
}
```

Gatsby GQL Query:
```gql
query MyQuery {
  wpPage(id: {eq: "cG9zdDoxMTA2NzA="}) {
    id
    title
    generalModulesGroup {
      modules {
        ... on WpPage_Generalmodulesgroup_Modules_VerticalImageFeaturedModule {
          description
          images {
            horizontal {
              sourceUrl
            }
            vertical {
              sourceUrl
            }
          }
        }
      }
    }
  }
}

```

### Expected result

Expecting the same data as on WP GQL Query.

```json
{
  "data": {
    "page": {
      "id": "cG9zdDoxMTA2NzA=",
      "title": "Accueil",
      "generalModulesGroup": {
        "modules": [
          {
            "description": "<p>Nos produits sont fabriqués avec le concept exclusif de transport des nutriments (NTC®) qui fournit les nutriments exactement quand ils sont nécessaires et où ils sont nécessaires – au niveau cellulaire, de l&#8217;intérieur et de l&#8217;extérieur.</p>\n",
            "images": {
              "horizontal": {
                "sourceUrl": "mydomain.com/wp-content/uploads/2021/05/2020.08.07_SPP70717-aspect-ratio-328-186.jpg"
              },
              "vertical": {
                "sourceUrl": "mydomain.com/wp-content/uploads/2021/05/pic1-os.jpg"
              }
            }
          },
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {}
        ]
      }
    }
  }
}
```

### Actual result

Got `null` on images (Gatsby GQL Query).

```json
{
  "data": {
    "wpPage": {
      "title": "Accueil",
      "generalModulesGroup": {
        "modules": [
          {
            "description": "<p>Nos produits sont fabriqués avec le concept exclusif de transport des nutriments (NTC®) qui fournit les nutriments exactement quand ils sont nécessaires et où ils sont nécessaires – au niveau cellulaire, de l&#8217;intérieur et de l&#8217;extérieur.</p>\n",
            "images": {
              "horizontal": null,
              "vertical": null
            }
          },
          {},
          {},
          {},
          {},
          {},
          {},
          {},
          {}
        ]
      }
    }
  }
}
```

### Environment

```bash

  System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.13.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Edge: 90.0.818.51
    Firefox: 87.0
    Safari: 14.1
  npmPackages:
    gatsby: ^3.5.1 => 3.5.1 
    gatsby-plugin-env-variables: ^2.1.0 => 2.1.0 
    gatsby-plugin-gatsby-cloud: ^2.5.0 => 2.5.0 
    gatsby-plugin-gdpr-cookies: ^2.0.0 => 2.0.0 
    gatsby-plugin-image: ^1.5.0 => 1.5.0 
    gatsby-plugin-manifest: ^3.5.0 => 3.5.0 
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0 
    gatsby-plugin-robots-txt: ^1.6.2 => 1.6.2 
    gatsby-plugin-root-import: ^2.0.6 => 2.0.6 
    gatsby-plugin-sass: ^4.5.0 => 4.5.0 
    gatsby-plugin-sharp: ^3.5.0 => 3.5.0 
    gatsby-plugin-transition-link: ^1.20.5 => 1.20.5 
    gatsby-plugin-typegen: ^2.2.4 => 2.2.4 
    gatsby-source-filesystem: ^3.5.0 => 3.5.0 
    gatsby-source-wordpress: ^5.5.1 => 5.5.1 
    gatsby-transformer-sharp: ^3.5.0 => 3.5.0 

```

Gatsby config for `gatsby-source-wordpress` plugin:
```
{
    resolve: 'gatsby-source-wordpress',
    options: {
        url: process.env.WORDPRESS_GRAPHQL_URL,
        debug: {
            timeBuildSteps: true,
            throwRefetchErrors: true,
            graphql: {
                showQueryOnError: true,
            },
        },
        production: {
            hardCacheMediaFiles: true,
            allow404Images: true,
        },
        develop: {
            hardCacheMediaFiles: true,
            hardCacheData: true,
        },
        schema: {
            perPage: 50,
            requestConcurrency: 3,
            previewRequestConcurrency: 2,
            timeout: 60000,
        },
        html: {
            useGatsbyImage: false,
            createStaticFiles: false,
        },
        type: {
            Category: {
                exclude: true,
            },
            Comment: {
                exclude: true,
            },
            Menu: {
                exclude: true,
            },
            MenuItem: {
                exclude: true,
            },
            ContentType: {
                exclude: true,
            },
            User: {
                exclude: true,
            },
            UserRole: {
                exclude: true,
            },
            Taxonomy: {
                exclude: true,
            },
            Tag: {
                exclude: true,
            },
            PostFormat: {
                exclude: true,
            },
            Post: {
                exclude: true,
            },
            MediaItem: {
                localFile: {
                    requestConcurrency: 3,
                },
            },
        },
    },
}
```

### PR DESCRIPTION
**Pull request by TylerBarnes**
Fixes #31503.

This was really hard to track down!

To reproduce the problem you need to run through very specific steps:

1. Add a new media item to WordPress via the media library uploader
2. Run a cold build on your CI service (probably because of a code update)
3. Add the previously updated media item to an image field on a post and update the post
4. Run a cached build on CI
5. Observe the image field is null

The reason for this is related to 2 features:
1. The source plugin only fetches images that are referenced by a node somewhere. 
2. WPGatsby doesn't send webhooks for media item updates to prevent unnecessary builds.

The cold build after uploading the image means our next cached build wont pull in the Media item events in ActionMonitor in WPGatsby. So the image doesn't exist in Gatsby.
This was hard to find because uploading a new image to a post and saving the post doesn't trigger the problem. Neither does adding an old image to a post and saving the post if that image is being used on another post.

The solution is very simple, in the `createSingleNode` helper, we need to check for referenced MediaItem node id's and fetch them if necessary by calling the `fetchReferencedMediaItemsAndCreateNodes` helper.

I've added a test to catch this issue. To do so I needed to create a new WP plugin "WPGatsby test plugin". This plugin allows us to attach a featured image to a post after a cold build but before a warm build. On the cold build the MediaItem node shouldn't exist in Gatsby (even though it already exists in WP) and on the warm build it should exist in Gatsby and have a local File node.

### CODE REVIEW

**Comment by TylerBarnes** [comment]
Also likely fixes #29820 and #31614

You can try this fix via this canary `gatsby-source-wordpress@5.10.0-alpha-wordpress.19+3d743f8f07`!

**Comment by fk** [comment]
wow! 🤯
_Thank you!!!_ 💎

**Review by DanielSLew — APPROVED** [review]
Love all the extra test coverage! 10/10 PR.

**Comment by TylerBarnes** [comment]
Merging since the failing tests are unrelated to this PR and all related tests are passing 👍

**Pull request merged**
