### PR TITLE
Prevent infer input fields infinite recursion

### PR DESCRIPTION
**Pull request by jasonphillips**
Test and fix for https://github.com/gatsbyjs/gatsby/issues/2420

Ensures that the recursive type-checking of new graphql fields added by plugins does not infinitely recur when types contain circular references. The solution used is to simply track the set of types during a traversal, aborting at the first instance of circularity, yet preserving the functionality of input type inference up until that point.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks!

Seems correct. @Zalastax any feedback?

**Comment by Zalastax** [comment]
Very nice! Merge it!

It's great that since createTypeNames guarantees unique names this won't run into conflicts even if two fields have the same name.
When gatsby start using React 16 I'd consider using Set, but that's for the future.

**Comment by KyleAMathews** [comment]
This is node.js code so we're already good there :-) Set was first added to Node 4 which is the lowest version we support.

**Comment by KyleAMathews** [comment]
But anyways, this is plenty good enough. Merging! Thanks!

**Comment by jlengstorf** [comment]
Hiya @jasonphillips! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
