### PR TITLE
If someone uses a private repo git address accessed over ssh use that otherwise use normal git address

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Fixes https://github.com/gatsbyjs/gatsby-starter-default/issues/42

Apparently https://github.com/gatsbyjs/gatsby/pull/3703 (which switched us to use the ssh form of git addresses) broke `gatsby new gatsby-site` for people without ssh keys :-(

This PR makes it so we always use the normal git form of the address *unless* someone passes in the ssh form.

**Comment by VinSpee** [comment]
Who would have thought it would be so complicated!

**Comment by VinSpee** [comment]
Out of curiosity, why can’t we just use the URL they pass in w/ committish?

**Comment by KyleAMathews** [comment]
Not us clearly 😅

**Comment by KyleAMathews** [comment]
>Out of curiosity, why can’t we just use the URL they pass in w/ committish?

No because we're running the git clone directly — we add back the "commitish" in the next line.

**Comment by KyleAMathews** [comment]
At least that's my understanding of this.

**Pull request merged**
