### PR TITLE
Add jsdoc comments to several sections

### LINKED ISSUE #4120: document helper functions passed to gatsby-node APIs
## Description

I have a collection of markdown files that I'd like to become blog posts. In the course of trying to figure out how to filter by folder, I came across `getNode()` in various code samples, but I can't find anything about it the docs. ~~It seems to be a part of the `boundActionCreators` inside `onCreateNode`, but I'm not 100% sure of that.~~

Can we add it to the docs? I'm happy to have a bash if somebody can point me the right direction.

EDIT: I realise that `getNode` looks like a sibling of `boundActionCreators` rather than a child of it.

### PR DESCRIPTION
**Pull request by vprasanth**
Covered a few areas to begin with. 

Close #4120

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 5b92407ac35f1ad2029798affe518585b4011d48

https://app.netlify.com/sites/using-glamor/deploys/5aadb61148769b34da7f5c36

**Comment by vprasanth** [comment]
Taking a look

**Comment by m-allanson** [comment]
Thanks @vprasanth!

**Comment by jlengstorf** [comment]
Hiya @vprasanth! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
