### PR TITLE
[v2] Pass actions to onCreateWebpackConfig

### PR DESCRIPTION
**Pull request by jaredpalmer**

### CODE REVIEW

**Comment by jaredpalmer** [comment]
This actually doesn't fix #5520, but was my first guess.

**Comment by jaredpalmer** [comment]
This actually does fix the problem.

**Comment by jquense** [comment]
this is a bit confusing since `actions` are passed automatically to all api calls: https://github.com/jaredpalmer/gatsby/blob/f869f250d9e194d9567b68ef401cebf192303581/packages/gatsby/src/utils/api-runner-node.js#L76 is something overloaded?

**Comment by jquense** [comment]
hmm and it already works elsewhere...https://github.com/gatsbyjs/gatsby/blob/v2/packages/gatsby-plugin-less/src/gatsby-node.js

**Comment by KyleAMathews** [comment]
Yeah — this PR doesn't seem like the right fix — @jaredpalmer could you double check what keys are on the initial object parameter?

**Comment by jaredpalmer** [comment]
Yeah i don't thin this is the issue. Closing

**Pull request closed without merging**
