### PR TITLE
Add gatsby-starter-kit to the list

### PR DESCRIPTION
**Pull request by greglobinski**

### CODE REVIEW

**Comment by greglobinski** [comment]
Thanks Kyle

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit ada2c76cc0da77dbb3c4b2c90ad495a8a92e79c8

https://app.netlify.com/sites/using-postcss-sass/deploys/5b732dabe39e7c0ae9a0a849

**Comment by greglobinski** [comment]
@KyleAMathews Could you please also delete this branch https://github.com/gatsbyjs/gatsby/tree/greglobinski-patch-1-1 
I duplicated the previous one and probalby I am not able to delete it, or I don't know how to do it :)

**Comment by KyleAMathews** [comment]
Deleted!

**Comment by greglobinski** [comment]
Thank you

**Pull request merged**
