### PR TITLE
Add styled-components support

### PR DESCRIPTION
**Pull request by gutenye**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit a77289a66ff298c335a5ed2d0b4a8c9c44b696ac

https://app.netlify.com/sites/gatsbygram/deploys/592d7770a700c417f85bf2de

**Comment by KyleAMathews** [comment]
The deploy preview failures are my fault — just added a PR to fix that.

Thanks for adding this! One follow-up task that would improve the UX of this plugin somewhat is instead of returning the styles and expecting the user to add them to their `html.js` just put them in `headComponents` as users will already be rendering that in the `<head>` of their html.js.

**Comment by KyleAMathews** [comment]
Oh and if you could also add me as an owner on NPM so I can make releases of the package along with the rest of them https://docs.npmjs.com/cli/owner

**Comment by gutenye** [comment]
> Oh and if you could also add me as an owner on NPM so I can make releases of the package along with the rest of them https://docs.npmjs.com/cli/owner
@KyleAMathews Done.

**Comment by jlengstorf** [comment]
Hiya @gutenye! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
