### PR TITLE
Make Gatsby Image more configurable

### LINKED ISSUE #3561: [gatsby-image] object fit is not configurable
It took me a while to uncover this, because I was using gatsby-plugin-sharp and react-flexbox-grid, so I was investigating those. However, it seems that gatsby-image only loads images within their wrapper as `object-fit: cover`. With certain aspect ratios, this cuts off the edges. For example:

https://imgur.com/a/jW8kg

The lefthand side is ever so cropped (so is the righthand side of the whole image but it's less noticeable there so I just snapped the left side). I looked into the source of gatsby-image and the css style is hardcoded as `cover`. Is there a way to allow it configurable to be either `cover` or `contain`?

### PR DESCRIPTION
**Pull request by tsriram**
Closes #3561

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hey awesome work! Nice refactor + feature improvement.

It does seem to have broken a few images in using-gatsby-image for reasons I'm not quite sure of — https://deploy-preview-4105--using-gatsby-image.netlify.com/blur-up/

**Comment by tsriram** [comment]
@KyleAMathews thanks! But I don't see any broken images on https://deploy-preview-4105--using-gatsby-image.netlify.com/blur-up/ - I tested this example site locally and it worked fine too. Can you check again? Anything in the console?

**Comment by KyleAMathews** [comment]
The top image never loads

screen shot 2018-02-17 at 9 53 11 am

**Comment by tsriram** [comment]
Ah, another "works on my machine" moment! But this looks weird. Let me take a detailed look.

image

**Comment by tsriram** [comment]
Well, pushed in a minor change but it shouldn't have been the cause of this issue. I could not reproduce the issue either locally or in the preview build on both Chrome 64 & Firefox 58 on Ubuntu. Wonder if this could be an issue with specific browser/version with `IntersectionObserver`?

**Comment by KyleAMathews** [comment]
Hmmm could just be a Netify error actually

screen shot 2018-02-17 at 10 26 46 pm

**Comment by tsriram** [comment]
@KyleAMathews do you see the error consistently? If it's a Netlify error, I should also be getting it I guess. Wonder if others are able to see the bug? @m-allanson could you check if the deploy preview works for you?

**Comment by KyleAMathews** [comment]
I've never seen it before actually so not sure what it is or means. Just checked the same page again and now it's working 🤷‍♂️

**Comment by KyleAMathews** [comment]
Thanks for the PR!

**Comment by fk** [comment]
Thank you @tsriram!!

**Pull request merged**
