### PR TITLE
Moar bugs

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by jquense** [comment]
oops forgot to update the snapshots. @KyleAMathews is there any reason not to use a single underscore here vs `___`

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 554e194b1119ed9a258e7fa21c8df704ca5d227f

https://app.netlify.com/sites/gatsbyjs/deploys/593acd203c1d5e48aebd312d

**Comment by KyleAMathews** [comment]
Eh not a great reason. The thought was to make it obvious when there was a replaced field vs. when you just had an underscore to begin with. But not sure that matters much...

Also, while you're working on this, any thoughts on https://github.com/gatsbyjs/gatsby/issues/1111?

**Comment by fabien0102** [comment]
As said in https://github.com/gatsbyjs/gatsby/pull/949#discussion_r121276740 , this fix in not functionnal on my starter (my integration test in typescript)

**Comment by KyleAMathews** [comment]
Been playing with this locally. Changing to one underscore is fine with one extra weird trick that I'll add in a separate commit.

**Comment by KyleAMathews** [comment]
this commit fixes the tests + adds a custom delimiter when flattening the example values for creating enum fields https://github.com/gatsbyjs/gatsby/commit/eab7d284f99903644363ad583312abc1f26a20a2

Which was necessary as we "deflatten" the field names in run-sift to sort connection results https://github.com/gatsbyjs/gatsby/blob/eab7d284f99903644363ad583312abc1f26a20a2/packages/gatsby/src/schema/run-sift.js#L56

**Pull request merged**
