### PR TITLE
fix(gatsby): Fix develop SSL by moving the SSL setup to the proxy

### LINKED ISSUE #24272: SSL errors when using `gatsby develop --https`
##  Description

When running `gatsby develop --https` both with without `--cert-file`/`--key-file` SSL does not work in Firefox, Chrome or Safari (screenshots below).

### Steps to reproduce

1. I've created a minimal reproduction in https://github.com/patrickarlt/gatsby-ssl-issue-reproduction. This is based off the default starter with the latest version of Gatsby.
2. `npm install`
3. `npm run start:devcert` this starts the local dev server and automatically creates SSL certs.
4. Observe failures.
5. Install [`mkcert`](https://github.com/FiloSottile/mkcert), for Mac this means:
   * `brew install mkcert`
   * `brew install nss`
   * `mkcert install`
   * `mkcert localhost`
6. `npm run start:local-certs` this starts the dev server with the local certs from `mkcert`
7. Observe failures.

In order to check that the certs are valid you can use [`http-server`](https://www.npmjs.com/package/http-server):

* `npm i -g http-server`
* `http-server . -C localhost.pem -K localhost-key.pem -S -a localhost`

This displays the directory structure of our project tin the browser over `https://...` note the lock icon in Chrome:

### Expected result

The server should successfully serve pages over `https://...`.

### Actual result

Browsers produce SSL errors.

### Environment

**Gatsby**

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 77.0
    Safari: 13.1
  npmPackages:
    gatsby: ^2.22.3 => 2.22.3
```

**OpenSSL**

```
$ openssl version
LibreSSL 2.6.5
```

**mkcert**

```
$ brew info mkcert 
mkcert: stable 1.4.1 (bottled)
Simple tool to make locally trusted development certificates
https://github.com/FiloSottile/mkcert
/usr/local/Cellar/mkcert/1.4.1 (6 files, 5.3MB) *
  Poured from bottle on 2020-04-08 at 18:45:14
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mkcert.rb
==> Dependencies
Build: go ✘
==> Analytics
install: 3,827 (30 days), 11,641 (90 days), 47,679 (365 days)
install-on-request: 3,351 (30 days), 10,186 (90 days), 40,390 (365 days)
build-error: 0 (30 days)
```

**nss**

```
$ brew info nss
nss: stable 3.52 (bottled)
Libraries for security-enabled client and server applications
https://developer.mozilla.org/docs/NSS
/usr/local/Cellar/nss/3.52 (225 files, 34.1MB) *
  Poured from bottle on 2020-05-19 at 16:52:58
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/nss.rb
==> Dependencies
Required: nspr ✔
==> Analytics
install: 38,963 (30 days), 105,774 (90 days), 394,028 (365 days)
install-on-request: 8,110 (30 days), 19,022 (90 days), 62,334 (365 days)
build-error: 0 (30 days)
```

### PR DESCRIPTION
**Pull request by mxstbr**
This fixes #24272 (and the duplicate #24301) by moving the SSL setup from the target to the proxy server.

The chain now looks like this if `--https` is passed:

```
Browser => Proxy => Target (develop) server
       HTTPS    HTTP
```

I tested this with the great reproduction @patrickarlt submitted and it works great, I can visit `https://localhost:8000` just fine:

```
~/projects/patrickarlt/gatsby-ssl-issue-reproduction
❯ sudo yarn run start:devcert
Password:
yarn run v1.19.1
$ gatsby develop --https
setting up automatic SSL certificate (may require elevated permissions/sudo)
...
You can now view gatsby-starter-hello-world in the browser.
⠀
  https://localhost:8000/
```

----

The only question I'm not sure about is how to replace `report.panic({ id: ... })`. As @sidharthachatterjee and @pieh noticed, we cannot use `reporter` in the parent process due to sideeffects on import. However the `get-ssl-cert` util did use it, which I've mostly replaced with `console.info` calls, however I'm not sure what to do about `report.panic({ id ... })` calls. Any ideas?

### CODE REVIEW

**Comment by pieh** [comment]
From testing:
 - it seems we no longer get `https` urls in terminal output (`You can now view gatsby-starter-blog in the browser.  http://localhost:8000/` thingie), because this is displayed in `develop-process` and it checks for `program.ssl` which is not set in that process - we serialize program before this is added, but also it appears like we don't actually want inner server to run https, so we likely just want some boolean switch on program to let child process know which protocol to display)
 - I'm getting whole lot of SSL protocol errors - the resource it tries to connect to seems to be parent process websocket ssl-proto-error

**Comment by JustFly1984** [comment]
Is there any movement on this issue? can't update since 2.21.40

**Comment by mxstbr** [comment]
Yep, I just got back to this and cleaned up @pieh's comments! :blush: Ready for another review!

**Comment by pieh** [comment]
Published in `gatsby@2.22.19`

**Pull request merged**
