### PR TITLE
Add michaelcereda.com to the list of sites 

### PR DESCRIPTION
**Pull request by MichaelCereda**

### CODE REVIEW

**Comment by MichaelCereda** [comment]
I just finished the new version of my website.
I created it in gatsby doing a lot of customizations. I think that can be very useful for people that are going to see what is possible to achive with gatsby so I decided to release the source code.

The live version is accessible here http://michaelcereda.com

Thanks!

**Comment by MichaelCereda** [comment]
I'm also writing some posts about the website itself to show the techniques used.

https://medium.com/@michaelcereda/creating-an-isomorphic-universal-website-with-react-part-1-a905350acba8#.rc2xxzjg5

**Comment by KyleAMathews** [comment]
Nice looking site! And the articles look great too! I'm sure people will find them very helpful. Will tweet them out in the morning.

**Comment by MichaelCereda** [comment]
Oh ... thanks a lot ... other 3 articles are arriving ;)
I'm going to post them out in the next days.

I'll add also a some tips & tricks on gatsby.
I think that it's a great tool, i love it,  but I also found some
limitations/lack of flexibility that should be fixed.
I'll try to add some issues and maybe also a couple of PR.

Thanks!



On Mon, Jun 6, 2016 at 2:07 AM Kyle Mathews <notifications@github.com>
wrote:

> Merged #313 <https://github.com/gatsbyjs/gatsby/pull/313>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gatsbyjs/gatsby/pull/313#event-682431109>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAGjftcpK4yCUamlp9357AGgfVVjiY0Iks5qI7kqgaJpZM4IujTj>
> .
>
-- 
Michael Cereda
http://michaelcereda.com

**Comment by KyleAMathews** [comment]
Awesome! And agree there are some things that should be approved and we'd
love your help!

**Comment by KyleAMathews** [comment]
@MichaelCereda added your blog series to the talks/blog section 👊  https://github.com/gatsbyjs/gatsby/commit/676f78be63c31c5692d6948ef86a335cfab20fdf

**Comment by jlengstorf** [comment]
Hiya @MichaelCereda! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
