### PR TITLE
fix(develop): don't sort the task queue when adding low-priority tasks to the end

### PR DESCRIPTION
**Pull request by me4502**
## Description

This change prevents the entire task queue being sorted every time a low-priority task is added to the queue. This takes a run of `npm run develop` with 60k pages from 50 minutes to 1.5 minutes. There should be no behaviour change here, as these were already the lowest priority and will be added to the end of a FIFO queue. High priority tasks still sort, which means they will still be correctly moved to the front.

## Related Issues

Fixes one aspect of #12343

### CODE REVIEW

**Comment by pieh** [comment]
This seems very valid fix (or rather workaround) for excessive sorting done by default memory store used by `better-queue` ( https://github.com/diamondio/better-queue-memory/blob/master/index.js#L41-L57 ) - as pointed in description - it just pushes task to tail of queue and avoid excessive sorting

**Comment by me4502** [comment]
I think this should basically fix it for any size site also, as I assume the activePaths refers to currently open pages in the web browser that are being handled by web hooks? So it'll only sort for the number of different pages open in tabs. Which means during the initial build process it'll never actually do a sort, only on hot-reload.

**Comment by pieh** [comment]
Ok, I just checked and setting priority to `undefined` will break prioritization completely, because comparator will always always be `false` when you compare any value with undefined:

```
10 < undefined // false
10 > undefined // false
10 == undefined // false
```

As you mentioned we still don't need priorities for initial query running so instead of this change we could return `undefined` during initial query running:
Priority could look like:
```js
priority: (job, cb) => {
	if (runningInitialQueries) {
      return cb(null, undefined)
    }
    const activePaths = Array.from(websocketManager.activePaths.values())
    if (job.id && activePaths.includes(job.id)) {
      cb(null, 10)
    } else {
      cb(null, undefined)
    }
  },
```
`runningInitialQueries` would be initially false, and we could call from https://github.com/gatsbyjs/gatsby/blob/1ef70f474dab51c44f92a001ba2d88e1ba318245/packages/gatsby/src/internal-plugins/query-runner/page-query-runner.js#L27-L35 after `await runQueries() ` that we finished initial queries and to toggle `runningInitialQueries` to false and enable prioritization after that

**Comment by pieh** [comment]
Other - probably mess lessy solution would be to create custom better-queue store implementation that instead of sorting would have priority queue and normal queue (because we only have really 2 priorities) and wouldn't do any sorting just always get from prio queue first and only after that pop tasks from normal queue.

For reference - https://github.com/diamondio/better-queue-memory/blob/master/index.js this is currently used store implementation so ~100 loc which could be used as a base

**Comment by me4502** [comment]
One potential idea I've had rather than having two queues, would be to have a custom MemoryStore inside Gatsby that handles "high/low priority" as a boolean in putTask, and then just unshifts / pushes to the queue based on which is given. Would this work? No sorting, and it's a smaller change as it doesn't require setting up a second queue and changing all the task queue length etc code.

**Comment by me4502** [comment]
I've implemented a solution that is based off your suggestion, however I made it support an arbitrary number of priorities rather than just 2.

**Comment by pieh** [comment]
> however I made it support an arbitrary number of priorities rather than just 2.

Nice!

Let me take that for a test run

**Comment by pieh** [comment]
Ok, it seems like it has some problems. If You don't mind I'll apply some changes and few tests

**Comment by me4502** [comment]
Looks good, thanks. Didn’t think about the ability to change priorities etc after the task had been made.

**Comment by KyleAMathews** [comment]
Nice work! Better living through algorithms 👌

**Comment by me4502** [comment]
Would it be possible to please get this reviewed soonish? 😃

**Comment by pieh** [comment]
Published `gatsby@2.2.2`

**Pull request merged**
