### PR TITLE
Update showcase info for miyamadojinja.com

### PR DESCRIPTION
**Pull request by mnishiguchi**
## Description

This is a minor improvement for [Miyamadojinja's showcase info](https://www.gatsbyjs.org/showcase/www.miyamadojinja.com), including a typo.

TL;DR: `Japanses` (wrong) -> `Japanese` (correct)

Related PR: https://github.com/gatsbyjs/gatsby/pull/20856

### CODE REVIEW

**Comment by mnishiguchi** [comment]
There are four typo warnings but they are correct Japanese words.

**Comment by laurieontech** [comment]
Thanks for the PR!

**Comment by mnishiguchi** [comment]
@laurieontech You are absolutely right. I updated the site repo's README with instructions for installation. https://github.com/mnishiguchi/miyamadojinja/blob/master/README.md

**Comment by laurieontech** [comment]
Thanks for the PR!

**Pull request merged**
