### PR TITLE
fix(gatsby): Allow `export { default }` named exports in page templates

### PR DESCRIPTION
**Pull request by yanneves**
This change addresses an incorrect warning in `gatsby develop` when using an `export { default } from '<file path>'` pattern in page templates.

For example, the following is valid:

```js
import { graphql } from 'gatsby'
export { default } from './Page'
export const query = graphql`
  query {
    ...
  }
`
```

along with:
```js
export { Component as default } from '../components/Component'
```

but this rule would not recognise a default named export. So it would have to be rewritten as:

```js
import Page from './Page'
export default Page
```

and

```js
import { Component } from '../components/Component'
export default Component
```

to prevent the warning.

Now with this change we can do either! 🎉

### CODE REVIEW

**Comment by wardpeet** [comment]
We should check if fast-refresh still works correctly as ignoring it for these exports might cause the errors we're trying to mitigate

**Comment by yanneves** [comment]
I've been using this pattern in development and production for a couple of months and haven't noticed any issues with fast-refresh running `gatsby develop`, but if you have some specific test cases I'd be happy to check that out

**Comment by LekoArts** [comment]
We use fast-refresh by default now in Gatsby v3 so we'll need to test this pattern with that version now and see if hot reloading still works.

**Comment by yanneves** [comment]
gotcha, will upgrade to latest my end also and look for anything unexpected

**Comment by yanneves** [comment]
managed to upgrade with little difficulty (great job Gatsby team!) and this pattern works fine with Gatsby v3 fast refresh

there's one data point for you 😊

**Comment by yanneves** [comment]
just wondering if there were any more thoughts on this - happy to take on some of the testing if that's a bottleneck

**Review by LekoArts — APPROVED** [review]
I know, it's late... But tried it out with Fast Refresh, all works. So just had to update the branch :)

**Pull request merged**
