### PR TITLE
Add example using filbert-js

### PR DESCRIPTION
**Pull request by kuldeepkeshwar**
Add starter for [filbert-js](https://filbert-js.vercel.app/docs/introduction)

### CODE REVIEW

**Comment by kuldeepkeshwar** [comment]
@sidharthachatterjee let me know if any thing is required to get this pull request merge

**Comment by KyleAMathews** [comment]
Hey @kuldeepkeshwar! Thanks for the PR documenting filbert-js! We decided a while to stop adding many example sites into the repo as they take a lot of time to maintain. Do you think you could perhaps instead turn this into a starter and add it to the starter showcase? https://www.gatsbyjs.com/starters/?v=2 That way people could still easily learn how to start using filbert w/ Gatsby.

**Comment by kuldeepkeshwar** [comment]
@KyleAMathews sure!!

**Comment by kuldeepkeshwar** [comment]
> Note: Showcase and starter contributions are currently paused while the Gatsby team develops a new workflow for sharing your Gatsby sites with the community.

https://www.gatsbyjs.com/contributing/community-contributions/

@KyleAMathews  seems starters are currently paused

**Pull request closed without merging**
