### PR TITLE
fix(gatsby-image): When art-directing images, default the padding aspect ratio to first image without a media query when no media query matches

### PR DESCRIPTION
**Pull request by mjmaurer**
## Description

When art directing multiple images and no media query matches, the current implementation chooses the first image with a media query.

This PR will choose the first image without `media` if no images match current `window`. This reflects what one would expect [from the documentation](https://www.gatsbyjs.org/packages/gatsby-image/#art-directing-multiple-images) (right now the mobile image would never be selected)
The documentation reflects what one would expect from mobile-first design.

I don't believe this is a breaking change. Any client that has `media` with every image will continue to work the same way. Any client that has an image without `media` probably expects the behavior that this PR implements.

## Related Issues

Addresses documentation error mentioned above
Addresses #15189 when adding a "default" image (without media query)
Related to art direction support in #13395

### CODE REVIEW

**Comment by waverly** [comment]
This would be really useful - is this going to merge anytime soon?

**Comment by andrezimpel** [comment]
I am using gatsby-image 2.3.4 and unfortunately this does not work for me. When the page is loaded it is still using the aspect ratio of the first source instead of the matched one. I am logging out the `image.aspectRatio` and that is indeed correct when loading the page, although the `paddingBottom` does not get updated. As soon as I navigate to a different page and then come back it works.
 
Here is a preview link: https://preview.zuckerjagdwurst.com

**Comment by bogdansoare** [comment]
Aso having this issue, but only on production builds, on development it works as expected

**Comment by andrezimpel** [comment]
@bogdansoare yea, it's only happening in production!

**Comment by denisgoryaynov** [comment]
I have the same issue

**Comment by bogdansoare** [comment]
For now the easiest way to fix this is to have 2 gatsby images one for small screens and one for larger, then toggle between the 2 of them with media queries

**Comment by polarathene** [comment]
Please sub to [this issue](https://github.com/gatsbyjs/gatsby/issues/24748) to be notified of a fix, continue discussion there.

**Pull request merged**
