### PR TITLE
enhancement(docs): add Remark MDX

### PR DESCRIPTION
**Pull request by tesseralis**
## Description

Add `remark-mdx` for better parsing of the docs linter.

* Remove MDX imports from the dictionary
* Switch to using `.remarkignore` instead of `<!-- lint ignore` since it doesn't work with `remark-mdx`
  * Add docs explaining this and how to ignore linting

## Related Issues

Making for #25629, since remark seems to not be able to parse some of the graphql queries correctly.

### CODE REVIEW

**Comment by muescha** [comment]
Note: 

You excluded the `/docs/docs/mdx/customizing-components.md` But the 3 rows with table syntax  is not rendered well on the live page: https://www.gatsbyjs.org/docs/mdx/customizing-components/

**Comment by muescha** [comment]
I am not sure if the place for `remark-mdx` was the right place. 

I asked at [Spectrum chat](https://spectrum.chat/unified/remark/remark-retext-remark-mdx~4ac792ff-5a12-4d88-8dee-7315467c9b51?m=MTU5NDQ2MTIwNDk0Nw==) and @wooorm suggested:

> remark-mdx works on the parser provided by remark-parse. The process then would look something like this:
> 
```javascript
.use(remarkParse)
.use(remarkMdx)
// ... other stuff that works on MDX (remark)
.use(remarkRehype)
// ... other stuff that works on HTML (rehype)
.use(rehypeRetext)
// ... other stuff that works on prose (retext)
```

(The rehype step in the middle is needed because otherwise table cells are not checked)

**Comment by wooorm** [comment]
Hi you both!

The place that @tesseralis proposed is all good: it should work exactly the same way! I would personally put `remark-mdx` right after `remark-frontmatter`: that way you have the syntax plugins together.

My suggestion on Spectrum had to do with other information that was provided.

For more information on processing between syntaxes, remark and rehype, see [“Programming interface” and its next section “Processing between syntaxes” in unified’s readme](https://github.com/unifiedjs/unified#programming-interface)!

**Comment by muescha** [comment]
Thanks a lot for clarification:)

**Comment by tesseralis** [comment]
@muescha good catch on the tables! Let me see if I can figure out how to fix it.

**Comment by muescha** [comment]
i am working on a plugin for a fine grained filter messages on vfile level done with glob syntax and path and rule - it is not needed to exclude a file complete from linting. 

I just have to figure out how to publish my first package to npmjs :)

**Comment by LekoArts** [comment]
Since the linting currently mostly works, we're juggling with different MDX versions (and waiting for MDX v2) and we don't need it right now we'll push back on this and can revisit `remark-mdx` later if necessary.

**Pull request closed without merging**
