### PR TITLE
fix(gatsby): Add tests for and partially fix circular reference issue.

### LINKED ISSUE #11364: gatsby-source-contentful: Maximum call stack size exceeded
Not sure if this is a bug or not. And unfortunately I don't really have much time this week to investigate. But I thought I might as well put this up here.

I'm using the `gatsby-source-contentful` plugin. In my contentful content model I'm having two content types, both with the new Richtext editor. Problems occurs when I have entry links to each other.

To be more clear. Say I have two pages, home and about. If I link from home -> about and from about -> home inside the Richtext editor I get this error.

Like I said before. Not sure if this is a bug.

Here's a callstack https://pastebin.com/fD676e6j

### Environment (if relevant)
```
  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Shell: 3.0.0 - /usr/local/bin/fish
  Binaries:
    Node: 10.15.0 - /var/folders/vh/cx86q1vs2xz5rxlf8b8cny2r0000gn/T/yarn--1548706327929-0.8647198662198463/node
    Yarn: 1.13.0 - /var/folders/vh/cx86q1vs2xz5rxlf8b8cny2r0000gn/T/yarn--1548706327929-0.8647198662198463/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.3
  npmPackages:
    gatsby: 2.0.98 => 2.0.98 
    gatsby-plugin-layout: 1.0.11 => 1.0.11 
    gatsby-plugin-offline: 2.0.21 => 2.0.21 
    gatsby-plugin-react-helmet: 3.0.5 => 3.0.5 
    gatsby-plugin-styled-components: 3.0.4 => 3.0.4 
    gatsby-source-contentful: 2.0.26 => 2.0.26 
    gatsby-transformer-remark: 2.2.0 => 2.2.0 
```

`gatsby-config.js`:
```
plugins: [
        {
            resolve: 'gatsby-plugin-styled-components',
            options: {
                displayName: false
            }
        },
        'gatsby-plugin-react-helmet',
        {
            resolve: 'gatsby-plugin-layout',
            options: {
                component: require.resolve('./src/components/Layout')
            }
        },
        {
            resolve: 'gatsby-source-contentful',
            options: {
                spaceId: '<spaceID>',
                accessToken: process.env.CONTENTFUL_ACCESS_TOKEN
            }
        },
        {
            resolve: '@contentful/gatsby-transformer-contentful-richtext',
            options: contentfulRenderOptions
        },
        'gatsby-plugin-offline'
    ]
```

### PR DESCRIPTION
**Pull request by cameron-martin**
## Description

This particular issue occurs when a rich text hyperlink links to a page that is involved in a circular reference. This causes a circular data structure to be created, which causes problems in some algorithms that traverse this.

I believe this is the same issue as issue #11364.

I've added a new e2e test called "contentful" that contains a test that is a minimal reproduction of this issue. This uses a contentful space where I don't mind people having the API keys, but possibly for making tests deterministic this should be mocked. For convenience I have also [attached an export of the space](https://github.com/gatsbyjs/gatsby/files/3355189/contentful-export-mn2gkf1rxy7p-master-2019-07-03T14-34-73.zip).

This also contains a partial fix to the issue - it fixes the node tracking algorithm to deal with circular data structures. However, it now fails when doing schema inference.

## Related Issues

Fixes #11364 
Supersedes #14612

### CODE REVIEW

**Comment by cameron-martin** [comment]
cc @wardpeet

**Comment by cameron-martin** [comment]
@wardpeet Did you end up doing that second pair programming session regarding this issue that you mentioned during our session?

**Comment by LekoArts** [comment]
Hey @cameron-martin , could you please move these tests to unit tests as suggested by Sid? That would be super awesome, thanks!

**Comment by cameron-martin** [comment]
I don't see how unit tests would be sufficient to test this. The fix touches multiple different units (basically anywhere that breaks when a node is cyclic), and if we were to just rely on unit tests there would be nothing to verify that we haven't introduced any more such units in the future.

**Comment by LekoArts** [comment]
> However, I can roll this test case into one of the other e2e suites due to speed.

Yeah, that would be awesome, too 👍 And thanks for understanding (as our e2e tests already take up quite some time).

**Comment by cameron-martin** [comment]
So at the time I was working for an organisation that this problem was affecting but no longer do so I have little interest in fixing it since I'm no longer using Gatsby. Sorry

**Comment by pieh** [comment]
> So at the time I was working for an organisation that this problem was affecting but no longer do so I have little interest in fixing it since I'm no longer using Gatsby. Sorry

This is ok! Don't be sorry! :) We just needed to know what's the status of this. Let's close this PR, as e2e tests would need to be reworked and node tracking have also changed since this PR started.

**Pull request closed without merging**
