### PR TITLE
Plugin remove trailing slashes

### PR DESCRIPTION
**Pull request by scottyeck**
Another plugin we've been using internally for a while. It's super simple but I'm guessing we're not the only ones who would benefit.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Haha this is great — we can turn our doc pages into links to plugins :-)

**Comment by KyleAMathews** [comment]
Oh actually, could you update the docs page to point to this new plugin? Maybe keep the existing docs but say, "hey, if you want easy street, just install this plugin".

**Comment by scottyeck** [comment]
I actually like the idea of removing the code from the docs and linking to the source. Something like: "_Several plugins leverage the `onCreatePage` API to modify pages in this way. For example..._" and then the list of links to source. That way we never have to worry about the source and the docs getting out of sync.

**Comment by KyleAMathews** [comment]
oh yeah! Definitely would love to automatically link to plugins that use different APIs — been hoping to get to that for a while. SourceGraph could help here e.g. try this query in their GraphQL console:

```graphql
{
  root {
    search2(query: "r:gatsbyjs/gatsby exports.onCreatePage", scopeQuery: "") {
      results {
        results {
          ... on FileMatch {
            resource
            lineMatches {
              preview
              lineNumber
              offsetAndLengths
              limitHit
            }
          }
        }
      }
    }
  }
}
```

https://sourcegraph.com/.api/graphql

**Comment by scottyeck** [comment]
Woah.

**Pull request merged**
