### PR TITLE
[blogpost] Small fixes to "How to convert an existing Gatsby blog to use MDX"

### PR DESCRIPTION
**Pull request by thomaswangio**
## Description

Updated the date and fixed the full configuration file for `gatsby-plugin-mdx`. 

## Related Issues

#19412

### CODE REVIEW

**Comment by thomaswangio** [comment]
@laurieontech thanks for the merge for #19412! Noticed an issue with the config for `gatsby-plugin-mdx`. It has one wrong plugin included `gatsby-remark-vscode` and they didn't need to be in their own separate resolve blocks. 

If you could review and push this quickly that'd be great :)

**Comment by laurieontech** [comment]
Noted! Thanks for the quick fix

**Comment by marcysutton** [comment]
Following up on this -- in the future, this kind of topic would work best in the Gatsby docs, as opposed to the blog. Check out the contributing docs for more info. https://www.gatsbyjs.org/contributing/blog-and-website-contributions/

**Comment by thomaswangio** [comment]
> Following up on this -- in the future, this kind of topic would work best in the Gatsby docs, as opposed to the blog. Check out the contributing docs for more info. https://www.gatsbyjs.org/contributing/blog-and-website-contributions/

My reasoning behind choosing a blog post was for the "time-sensitive storytelling" factor. Using MDX with Gatsby has changed even in just the past few months, and there might soon be an official MDX starter so I didn't want to make this post an official tutorial. I think it's useful for when the MDX integrations with official Gatsby starters and themes becomes more mature it's worth making an official tutorial for it!

**Pull request merged**
