### PR TITLE
 test: exported method can be static; will never be called directly 

### PR DESCRIPTION
**Pull request by TheAadithyan**
#include <node.h>
#include <v8.h>

void Method(const v8::FunctionCallbackInfo<v8::Value>& args) {
static void Method(const v8::FunctionCallbackInfo<v8::Value>& args) {
  v8::Isolate* isolate = args.GetIsolate();
  args.GetReturnValue().Set(v8::String::NewFromUtf8(
        isolate, "world", v8::NewStringType::kNormal).ToLocalChecked());

### CODE REVIEW

**Comment by open-source-explorer** [comment]
@TheAadithyan You need to submit a PR from a branch within your forked repo. Also, kindly take a look at the issues labelled as `good-first-issue` to land your very first contribution :clap:

**Comment by sidharthachatterjee** [comment]
PRs from branches in this repo are also okay! 

@TheAadithyan Can you please clean up the title snd description of this PR? Seems irrelevant/unrelated?

**Comment by TheAadithyan** [comment]
> @TheAadithyan You need to submit a PR from a branch within your forked repo. Also, kindly take a look at the issues labelled as `good-first-issue` to land your very first contribution 👏

**Comment by sidharthachatterjee** [comment]
Okay, it’s appears that after merging master in, there are no changes left to be merged? 

Closing this! Sorry, @open-source-explorer (you were correct) 

@TheAadithyan Feel free to take a look at other issues! Thanks

**Pull request closed without merging**
