### PR TITLE
chore(starters): add  gatsby-starter-reason-blog

### PR DESCRIPTION
**Pull request by mukul-rathi**
## Description

Add new starter - Gatsby Starter Reason Blog

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! It looks like your README includes instructions for creating the site, but not for running it. Could you add those?
The [Gatsby default starter](https://github.com/gatsbyjs/gatsby-starter-default) is a good example.

**Comment by mukul-rathi** [comment]
Sure thing! Have updated the repository (https://github.com/mukul-rathi/gatsby-starter-reason-blog/commit/f56b2388d59dbf04fbdc404f5d0a163fbd4d0417)  in response to your comments.

**Comment by laurieontech** [comment]
Thanks so much for the quick response! If possible, it'd be great for the main instructions to use npm and gatsby commands. That way users have consistency between the Gatsby docs and starters they may use. But certainly let me know if there is a reasonml dependency that prevents that.

**Comment by mukul-rathi** [comment]
Have updated the README to use npm and gatsby instructions. https://github.com/mukul-rathi/gatsby-starter-reason-blog/commit/66fb813c009f628e30af96aa661a9d3bff891d64

**Comment by laurieontech** [comment]
Awesome! Going to re-run tests and then will get this merged.

**Pull request merged**
