### PR TITLE
prismjs: always escape unless language is none

### PR DESCRIPTION
**Pull request by docwhat**
Suggested by @KyleAMathews

https://github.com/gatsbyjs/gatsby/pull/4599#issuecomment-374411895

### CODE REVIEW

**Comment by KyleAMathews** [comment]
No I meant that we should *always* escape. The expectation for code in markdown is that they're always escaped.

**Comment by docwhat** [comment]
I’m not sure what you mean?  If the language is known, then PrismJS will escape it for us. 

The none is an escape clause if you know what you’re doing.

**Comment by KyleAMathews** [comment]
Oh I see. Is setting it as "none" documented? Don't remember it.

**Comment by docwhat** [comment]
It’s in the prismjs docs, but I can document it here.

**Comment by docwhat** [comment]
Done. It is documented.

**Comment by KyleAMathews** [comment]
Nice! Thanks for the great PR!

**Pull request merged**
