### PR TITLE
chore(docs): Make Documentation paragraphs/descriptions single line

### PR DESCRIPTION
**Pull request by caitlinselca**
## Description

The changes introduced by this PR close Issue #23482. It was found that in some cases the paragraphs/descriptions are spread over multi-lines rather than a single one. I fixed the recommended files to follow this single-line convention, as well as others that did not follow this convention in gatsby/docs/tutorial, in order to facilitate the translation and update process.

### Documentation

This documentation is in gatsby/docs/tutorial, there are several files (the index.md of several parts) in which the documentation style needed to be fixed to follow the single-line convention in order to make translations easier.

## Related Issues

The issue that is fixed by this PR is #23482. I follow the summary and steps to resolve the issue as noted in the ticket. Although there are two files listed in the ticket that did not follow the single-line convention, I also found other files in the gatsby/docs/tutorial that also did not so I fixed these files as well.

### CODE REVIEW

**Comment by AishaBlake** [comment]
Actually, I'm having trouble pushing updates to this branch. @caitlinselca, would you mind addressing the merge conflicts?

**Comment by caitlinselca** [comment]
> Actually, I'm having trouble pushing updates to this branch. @caitlinselca, would you mind addressing the merge conflicts?

Okay I went through and believe I have fixed the merge conflicts. Please let me know if it is successful! Thank you 😄

**Comment by caitlinselca** [comment]
> Actually, I'm having trouble pushing updates to this branch. @caitlinselca, would you mind addressing the merge conflicts?

Hi, I realize that my fork of this repository was extremely behind and had to adjust to this. I created a new pull request with what should be the correct changes, #23934. I would greatly appreciate it if you closed this PR and reviewed #23934 for merging instead. Thank you 😄

**Comment by ascorbic** [comment]
Closing in favour of #23934

**Pull request closed without merging**
