### PR TITLE
fix early bail when testing if string field should link to File node

### LINKED ISSUE #6467: Document best practice usage of pageContext
Edit (by @m-allanson): original issue was solved - this is now a documentation issue. See https://github.com/gatsbyjs/gatsby/issues/6467#issuecomment-405613559 and follow up comments.

## Description

Recently upgraded my blog to Gatsby v2 and am seeing it take ~50 seconds longer to build.

### Steps to reproduce

This is the PR that upgrades my PR to Gatsby v2: https://github.com/hswolff/blog/pull/4

You can check out master and run install deps and then run `yarn build` on both branches to see the change in behavior.

### PR DESCRIPTION
**Pull request by pieh**
`mime@^1.0.0` used to return `'application/octet-stream'` for unkown filenames - this was changed in `mime@^2.0.0` and now it returns `null` ( ref: https://github.com/broofa/node-mime/issues/139 ) 

When we upgraded `mime` and didn't adjust this caused every string field to go through quite expensive `File` nodes lookup - causing very long schema generation in some cases.

Closes #6467

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Looks like there's a few other places we make this check? https://github.com/gatsbyjs/gatsby/search?q=%22application%2Foctet-stream%22&unscoped_q=%22application%2Foctet-stream%22

**Comment by pieh** [comment]
Yeah, I checked that before and just didn't update it because it would work:
https://github.com/gatsbyjs/gatsby/blob/27a4f4bdcc1d30e07b165b7cb37bea3c2a19872d/packages/gatsby-source-filesystem/src/create-file-node.js#L43-L49
this will actually keep v1 behaviour of setting `application/octet-stream` for `File` nodes if `mime.getType` will report `null`, but probably noone will test against either `null` or `application/octet-stream`

But I guess if it doesn't matter let's not diverge from current `mime`, so I'll just update it too

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 16e79e7bf7200398fa6e9e92c058ab55339ee85f

https://app.netlify.com/sites/using-postcss-sass/deploys/5b4f136f82d3f10a7424957a

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit 16e79e7bf7200398fa6e9e92c058ab55339ee85f

https://app.netlify.com/sites/image-processing/deploys/5b4f137082d3f10a7424957e

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit d9b0affadf6f89ad9c24deb2057902e0afcf384d

https://app.netlify.com/sites/using-postcss-sass/deploys/5b4f13a482d3f116bf249545

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit d9b0affadf6f89ad9c24deb2057902e0afcf384d

https://app.netlify.com/sites/image-processing/deploys/5b4f13a582d3f116bf249549

**Pull request merged**
