### PR TITLE
Fix Broken File Paths

### PR DESCRIPTION
**Pull request by abrad45**
Just changed a few URLs to restore broken images. Will write some documentation later!

### CODE REVIEW

**Comment by pieh** [comment]
Problem is same file is used for gatsby website page - https://deploy-preview-3982--gatsbyjs.netlify.com/docs/how-to-contribute/ and your change break images on that site and until proper solution show up to have them working both on github and on website its preferred that they work on website.

**Comment by KyleAMathews** [comment]
Yeah... perhaps we should move contributing.md out of the repo root so images work on GitHub. We should also link to the website page from the README

**Comment by abrad45** [comment]
Ha. Sorry for not having a better understanding of where those files were linked from / to. Let me know if you'd like me to take any specific set of steps to remedy.

**Comment by m-allanson** [comment]
@KyleAMathews would it be possible to create a transformer that rewrites these relative urls? Then links would all work on GitHub and gatsbyjs.org.

**Comment by KyleAMathews** [comment]
@m-allanson yeah that'd totally work. We'd just have a list of URLs & URL patterns to change.

**Pull request closed without merging**
