### PR TITLE
Allow configuration of asset file output location

### PR DESCRIPTION
**Pull request by jrskerritt**
See #7289

This PR adds a configuration for the output location of asset files (any JS, CSS, JSON, and source maps created by `gatsby build`). Check out the documentation I added in `asset-path.md` to learn how to use it.

tl;dr: where previously the `/public/static` and `/public/static/d` directories were being assumed, I updated to check for the `assetPath` value in `gatsby-config.js`. It behaves very similarly to `pathPrefix`.

## To Maintainers:
Definitely take a close look at the changes I made to the plugins to make sure I didn't accidentally break anything! I did my best, but they are plugins I haven't used before.

### CODE REVIEW

**Comment by pieh** [comment]
What is the relation between assetPath and pathPrefix - I see You used `assetPath || pathPrefix` so it seems like if `pathPrefix` is used, then `assetPath` should contain it, otherwise it will not work correctly?

**Comment by jrskerritt** [comment]
@pieh Correct -- my idea was to make `assetPath` an absolute path that was separate from `pathPrefix` but I suppose it might make more sense to concatenate them if both are configured. What do you think?

**Comment by pieh** [comment]
Ultimately we would also want to have e2e cypress tests for this like ones we have for path-prefix

**Comment by KyleAMathews** [comment]
Yeah... this feels like a feature that'd be hard to support for relatively little benefit. Wouldn't it be easier for you to change how you deploy your sites than for us to change a core part of gatsby's internals?

**Comment by jrskerritt** [comment]
I understand why you'd be uncomfortable adding this. If stuff breaks later on, you guys would be the ones fixing it, not me. But unfortunately it's not possible for me to change how our site is deployed or how the urls are structured.

Without this feature, our only options would likely be either to maintain an internal fork of Gatsby or move away from Gatsby entirely. Both of these I'd rather not do 🙂

If there's anything else I could do to help potentially make this less fragile and give you guys more confidence, let me know. Happy to help.

**Comment by DSchau** [comment]
@jrskerritt I'm not _all_ that familiar with Cloudfront, but I'd have to think this is a solvable problem outside of changes to Gatsby.

If we presume all _files_ are in S3 (e.g. have an extension) is it possible to create some type of rule that whitelists those? I'd think routes (e.g. /research/US/whatever) would implicitly fall to the S3 bucket, because that's how public/index.html is working, I'd assume?

Another (hackier) solution would be to deploy Gatsby at a unique path, e.g. `/research/US/static` and then do a path re-write on that directory when serving, which _could_ be possible.

I'd think both of those are totally possible, and would solve the problem in a way that's cleaner for us.

Anything I'm missing--apart from knowing whether either of those are possible? Like I said, not an AWS guru by any means!

**Comment by jrskerritt** [comment]
@DSchau - I did some research into your suggestions.

In theory, we could forward only files with desired extensions under `/research` to our S3 origin, but my concern is that this could cause issues if other `.js` or `.css` or whatever files end up (or currently exist) in the same route that aren't in S3. A lot of our website I'd consider "legacy" and so I have no idea what else may exist under `/research`. So I'm not confident that this would work for us.

Rewriting _might_ be possible with lambda functions but that seems like overkill to me.

I can see that you guys aren't willing to budge on this feature so I'm just going to maintain my own fork. It's not ideal, but it's the next best path forward for me and my team.

**Comment by DSchau** [comment]
> A lot of our website I'd consider "legacy" and so I have no idea what else may exist under /research

For sure! It sounded like it was largely API driven, so I figured whitelisting files with extensions seemed like a fair approach!

> Rewriting might be possible with lambda functions but that seems like overkill to me.

It honestly seems like a pretty tenable solution, but totally understand! I'd rather we were able to come to some compromise, but like I said, not an AWS expert so it's hard for me to know best practices from that context.

We appreciate the PR, and sorry we couldn't come to a consensus on this!

**Pull request closed without merging**
