### PR TITLE
Update babel.md

### PR DESCRIPTION
**Pull request by twxia**
Remove `polyfill` option from `@babel/plugin-transform-runtime`.
(Reference: https://babeljs.io/docs/en/next/babel-plugin-transform-runtime.html#polyfill)

This may cause the error while executing other scripts.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 5d4fe42d8f9fc9a1c4e939eadf2a5d2bba74f355

https://app.netlify.com/sites/using-postcss-sass/deploys/5b65822f67610c3313ed4ceb

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 481e2c03ec8fc6af1ba500e37709cf6bd6d75e29

https://app.netlify.com/sites/gatsbyjs/deploys/5b6a9478b312745b5c986d17

**Comment by m-allanson** [comment]
@KyleAMathews `polyfill: false,` is mentioned in a few other places, I guess we should remove these too?

https://github.com/gatsbyjs/gatsby/blob/lerna-fix/packages/gatsby/src/internal-plugins/load-babel-config/utils.js#L96

https://github.com/gatsbyjs/gatsby/blob/lerna-fix/packages/gatsby/cache-dir/__tests__/.babelrc#L37

https://github.com/gatsbyjs/gatsby/blob/lerna-fix/docs/docs/gatsby-config.md#L81

**Pull request merged**
