### PR TITLE
Docs: fixed the error in blog dated 26-09-2019

### LINKED ISSUE #17921: blog: except shows unescaped `\$15' instead of `$15'
## Description

Blog except shows unescaped `\$15' instead of `$15'

### Steps to reproduce

open https://www.gatsbyjs.org/blog/

### Expected result

normal text: `15$`

### Actual result

Bildschirmfoto 2019-09-26 um 20 48 30

### Environment

n/a

### PR DESCRIPTION
**Pull request by devgupta2607**
\$15M is changed to $15M
Gatsby-error

## Description

There was a typing error in the blog post dated 26-09-2019. The value displayed is \\$15M and fixed to $15M.

## Related Issues

Fixes #17921

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Yeah... this is actually a bug in Prettier/MDX (see how the change failed linting). It was fixed in MDX https://github.com/mdx-js/mdx/pull/740 — not sure yet when it'll be upstreamed to Prettier — @johno do you know?

**Comment by johno** [comment]
AFAICT www is running an older version of MDX that doesn't have the patch. It _should_ be fixed in MDX so we don't need anything on prettier's end.

**Comment by devgupta2607** [comment]
Hi @KyleAMathews , I think it would be better if this PR is closed

**Comment by sidharthachatterjee** [comment]
@johno Thanks! Looks like minor updates were only working for `packages/**` as a result of a custom Renovate rule I added. Fixed that in https://github.com/gatsbyjs/gatsby/commit/67333f4d370416eaaf10edef1e86cba6af57c927 so `www` should be up to date soon (and fix this as a result)

Let's close this! Thank you so much nonetheless @devgupta2607 👍

**Comment by devgupta2607** [comment]
Thank you @sidharthachatterjee . I am just new to gatsby and seeking issues to contribute to.

**Pull request closed without merging**
