### PR TITLE
Revert "docs(gatsby-plugin-mdx): Add gatsby-remark-images to list of plugins for gatsby-plugin-mdx"

### PR DESCRIPTION
**Pull request by sidharthachatterjee**
Reverts gatsbyjs/gatsby#16251

### CODE REVIEW

**Comment by DSchau** [comment]
This broke the build somehow? Invalid JS or something?

**Comment by sidharthachatterjee** [comment]
@DSchau No, that's unrelated. This was an incorrect addition to documentation.

**Comment by vpicone** [comment]
@ChristopherBiscardi so the preferred work around for now is

```javascript
'gatsby-remark-images',
{
  resolve: `gatsby-plugin-mdx`,
  options: {
    gatsbyRemarkPlugins: [
      { resolve: `gatsby-remark-unwrap-images` },
      { resolve: `gatsby-remark-smartypants` },
      {
        resolve: `gatsby-remark-images`,
        options: {
          maxWidth: 1152,
          linkImagesToOriginal: false,
          quality: imageQuality,
          withWebp,
        },
      },
      { resolve: `gatsby-remark-responsive-iframe` },
      { resolve: `gatsby-remark-copy-linked-files` },
    ],
    remarkPlugins: [remarkSlug],
    defaultLayouts: {
      default: require.resolve('./src/templates/Default.js'),
    },
  },
},
```

**Comment by vpicone** [comment]
@ChristopherBiscardi so the intended work around for now is something like this? Wondeirng if we should be duplicating all the plugins that use the gatsby-remark-x plugins that use the gatsby APIs not just gatsby-remark-images.

```javascript
// root plugins array
`gatsby-plugin-sharp`,
{
  resolve: `gatsby-remark-images`,
  options: {
    maxWidth: 1152,
    linkImagesToOriginal: false,
    quality: imageQuality,
    withWebp,
  },
},
{
  resolve: `gatsby-plugin-mdx`,
  options: {
    gatsbyRemarkPlugins: [
      { resolve: `gatsby-remark-unwrap-images` },
      {
        resolve: `gatsby-remark-images`,
        options: {
          maxWidth: 1152,
          linkImagesToOriginal: false,
          quality: imageQuality,
          withWebp,
        },
      },
    ],
  },
},
```

**Pull request merged**
