### PR TITLE
docs(readme_typo)

### PR DESCRIPTION
**Pull request by maurocarrero**
Fix typo on Gatsby word on README.md file.

### CODE REVIEW

**Comment by maurocarrero** [comment]
I see that build is failing because of some failure with yarn or lerna, not sure.

As feedback: I could run `yarn run bootstrap` **only** when commenting the .yarnrc line: `--install.ignore-engines true`, otherwise I receive the following error: `error An unexpected error occurred: "Unknown token 1:0".`

Honestly, I did not dedicate time to investigate this, since my change was just a typo and I must continue with other tasks. I can come back later though.

**Comment by KyleAMathews** [comment]
🤦‍♂️ 

Wow, how'd that slip in haha.

Not sure what the bootstrapping error is… let us know if you figure something out!

**Comment by jlengstorf** [comment]
Hiya @maurocarrero! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by maurocarrero** [comment]
Thanks @jlengstorf!

**Pull request merged**
