### PR TITLE
Update starters.yml

### PR DESCRIPTION
**Pull request by robertistok**
Add https://gatsby-starter-fusion-blog.netlify.com/ starter theme

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! Looks like the lint tests are failing. Could you run `yarn format` on your branch and commit?

**Comment by robertistok** [comment]
@laurieontech Sure, I just did it! Looks like there was an extra space in one of the features :)

**Comment by laurieontech** [comment]
Awesome! That fixed it.

One last thing. Noticed that the README on the repo is using yarn commands.

We encourage documenting gatsby develop (and gatsby build) as a way to run your site for the following reasons:
- It’s consistent with the rest of our documentation so reduces the likelihood of confusion for our users
- It’s easier to pass in command line flags to gatsby. Also, gatsby-cli is already a required global dependency when using Gatsby. 

Could you please update the README to follow this?

**Comment by robertistok** [comment]
Of course, thanks for reminding me.

I just updated the Readme file. Let me know if I should do something more :)

**Comment by laurieontech** [comment]
Looks great! Thanks for the PR.

**Comment by robertistok** [comment]
Awesome, thank you so much! Feels so great to contribute, this was my first ever PR merged in OS :)

**Comment by laurieontech** [comment]
Yay! We're so thrilled to have been that project :D

**Pull request merged**
