### PR TITLE
Support https and custom certs on gatsby serve

### PR DESCRIPTION
**Pull request by cranberyxl**
## Description

Allows serving static gatsby site via https with custom ssl certificates.

- [ ]  Get integration tests working

### Documentation
Added to gatsby-cli README 

## Related Issues

fixes: #8463

### CODE REVIEW

**Comment by cranberyxl** [comment]
If anyone is available to help me understand how integration tests should work, I'm happy to chat.

**Comment by vilchesalves** [comment]
> If anyone is available to help me understand how integration tests should work, I'm happy to chat.

Not sure if I understand what you don't understand but there isn't much secret, there, I guess. There's an engine (in case o #8463 people mention cypress) running and doing automated clicking and typing.

From my experience, it works mostly fine on the develop server but because the dev build and the prod build sometimes differ, people want the ability to serve their prod build over https, possibly replicating the `developMiddleware` in the gatsby-config.js?

Not sure if that's useful for you. But thanks for tackling it!

**Comment by cranberyxl** [comment]
@vilchesalves I believe cypress is only for browser testing. There is a separate cli integration testing suite that I need help with.

**Comment by LekoArts** [comment]
Hey! Thanks so much for opening this pull request!

Sadly this PR got stale and didn't have any activity for some time. We're trying to do better with PR reviews! To get a better overview of all actionable PRs we're going through all open PRs and triage them. Since we won't be able to do everything and adding new features _always_ means added maintenance burden, we have to be more picky about what's beneficial for the average user and the project itself longterm.

Having said all this, we dropped the ball on this PR and we're sorry about not responding to it earlier. As said above, we want to do better in the future but here we should have communicated earlier what will happen with the PR.

In the meantime Gatsby 5 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

We absolutely want to have you as a contributor and are sorry for any inconveniences we caused with replying too late to this PR.

Thanks for submitting to Gatsby! 💜

**Pull request closed without merging**
