### PR TITLE
fix(docs): brand name Webpack to webpack

### PR DESCRIPTION
**Pull request by muescha**
## Description

changed:

- brandname from `Webpack` to `webpack`: [should always in lower-case letters, even at the beginning of a sentence](https://webpack.js.org/branding/#the-name)
- added `webpack` to common words list in the style guide section [capitalize proper nouns](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#capitalize-proper-nouns)

unchanged:
- uppercased `Webpack` in code

## Related Links

- https://www.gatsbyjs.org/contributing/gatsby-style-guide/#capitalize-proper-nouns
- https://webpack.js.org/branding/#the-name

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! However, I'm going to opt not to merge for a couple of reasons.
1. We're not in the habit of going through the site showcase and making changes of this level. 
2. While webpack may be the correct typing, the changes you've made are in titles where we're opting to use capitalization for emphasis.

**Comment by muescha** [comment]
thx

> I'm approving this so we can merge it, but please don't open such large PRs in the future (41 files is a lot to review at once, even for tweaky changes like this).
> 
> Thanks!

ok - i just was trying avoid PR "spam" with 41 PRs with all the same type 😕

**Comment by muescha** [comment]
@marcysutton is there something to do from my side for a merge?

**Comment by marcysutton** [comment]
@muescha I pushed a change from our end to merge from master, hopefully that will clean things up.

**Comment by muescha** [comment]
thx :)

**Comment by muescha** [comment]
it fails because of `npm audit security report` ... maybe it is fixed now?

**Comment by muescha** [comment]
@marcysutton i don't know how i can rerun the CI again?

**Pull request merged**
