### PR TITLE
Create CONTRIBUTING_ES.md

### PR DESCRIPTION
**Pull request by LuigiBaute**
Please let me know any change proposal and I'll do it gladly.

### CODE REVIEW

**Comment by LuigiBaute** [comment]
Hello @m-allanson have you checked the pull request?

**Comment by m-allanson** [comment]
Looks good, thanks @LuigiBaute! 

Could you move this file to a new directory? `/translations/es/CONTRIBUTING_ES.md`

**Comment by LuigiBaute** [comment]
Hi @m-allanson I made the file as you asked! :) Hope you like it, any suggestions let me know I'll gladly change it any times as necessary.

**Comment by m-allanson** [comment]
Thanks @LuigiBaute! I can see you've made the changes over at #4135 so I'm going to close this PR.

**Pull request closed without merging**
