### PR TITLE
chore(gatsby-cli): Remove data explorer

### PR DESCRIPTION
**Pull request by kiwimonk**
## Description
I've been working on getting gatsby to host some Markdown over Graphql.  The data-explorer was in place already, but seems like it hasn't been used in a while.  I added it to the gatsby-cli and updated it with feature from the develop command I thought would be useful.

Also, I updated the docker file to use the Alpine image (much smaller).  It can also be used to create a docker image running in develop or data-explorer mode.  I haven't tested any other modes, but I feel like this is a good start to making the file more useful and universal for everyone's needs.

PS.  I've only recently started using github and contributing to projects.  Hopefully everything is in order with this pull request.

Thanks

### CODE REVIEW

**Comment by kiwimonk** [comment]
Ah, I was looking for a solution and found your commit via google.  You're right that develop would work equally well with just a bit of extra baggage.  My needs are a bit of a hack.  I have a nuxt.js site I'm working on and want to static generate via GraphQL using Markdown files generated in Netlify CMS.

Thanks.  I'll make the reversions when I get a chance.

**Comment by wardpeet** [comment]
Any chance you can work on this in the near future @kiwimonk? If not, we can take it from here. We always encourage contributors to get a PR over the finish line themselves ⭐️.

**Comment by kiwimonk** [comment]
Hey Ward,
I apologise for not continuing with this.  I'm currently in Greece..
Without much access to power or the internet, so I don't have much time to
spend coding.

It was more a request to delete things, and it would be great to contribute
in such a small way, but I think you'll be able to take care of it much
better than I can.

Thanks,
Kent K

**Comment by sidharthachatterjee** [comment]
@kiwimonk No worries at all! I've gone ahead and made the changes Mike requested on this PR itself because we want you to get credit for your contribution here! Enjoy Greece and thank you so much 🙌

**Pull request merged**
