### PR TITLE
Fix a bug where keywords in plaintext were highlighted in JSX

### LINKED ISSUE #4002: Code blocks highlight all keywords even in which are enclosed in HTML tags
## Description

In the Gatsby Docs, the code blocks highlight keywords even though they are plain text within html.
I started noticing this while I was at this particular tutorial page: (https://www.gatsbyjs.org/tutorial/part-three/)

### Actual result
image

### Expected behavior

The above image, the words `do`, `of`, `as` should be displayed like normal text, not highlighted.

### PR DESCRIPTION
**Pull request by tryzniak**
This should fix #4002. 

Closes #4002

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 493b0ca85e71a02aa6bb2b2837b6175f1410c2bd

https://app.netlify.com/sites/using-postcss-sass/deploys/5b7409a1dd28ef535bced77f

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit 493b0ca85e71a02aa6bb2b2837b6175f1410c2bd

https://app.netlify.com/sites/using-contentful/deploys/5b7409a2dd28ef535bced78e

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 493b0ca85e71a02aa6bb2b2837b6175f1410c2bd

https://app.netlify.com/sites/gatsbyjs/deploys/5b74099ddd28ef535bced773

**Comment by KyleAMathews** [comment]
Is #4002 still happening? I thought the upstream fix was all we needed?

**Comment by tryzniak** [comment]
Here's a screenshot from Gatsby docs v1, section `Querying Data with GraphQL`:

image

Notice "return".

And I also tried an example from `examples/using-emotion-prismjs`, and the bug was present.

**Comment by KyleAMathews** [comment]
Ok cool thanks. Could you link to the docs for the changes you're making?

**Comment by tryzniak** [comment]
You mean PrismJS docs?

**Comment by KyleAMathews** [comment]
Yes

**Comment by tryzniak** [comment]
Go to https://prismjs.com/#basic-usage and search for `Usage with Node`. For some reason they always supply the 3rd argument.

**Comment by KyleAMathews** [comment]
You've verified this change fixes the highlighting locally?

**Comment by tryzniak** [comment]
Yeah, I tested it on a slightly modified `examples/using-emotion-prismjs` repo, which can be found here https://github.com/tryzniak/gatsby-prismjs-bug. I just added some keyword there to see how highlighting was working.

Here are screenshots before and after.
screen shot 2018-08-15 at 20 41 45
Notice how `do while` are highlighted.


screen shot 2018-08-15 at 20 38 49

And here they aren't.

**Comment by KyleAMathews** [comment]
Huh, super strange. Would you mind filing a bug in prismjs for this as well? At the very least, whatever is going on should be documented.

Thanks! Merging!

**Comment by KyleAMathews** [comment]
Oh actually the snapshot for `jsx` needs updated (as it should!) so the tests can pass. Can you run `yarn test:update` to update the snapshots?

**Comment by tryzniak** [comment]
done!

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by KyleAMathews** [comment]
Published in 3.0.0-beta.7

**Comment by fk** [comment]
Trying to put together the pieces for #8058…FWIW, for those following along ;-)

* The third parameter `language` which this PR adds to the `PrismJS.highlight` function call is indeed undocumented: https://prismjs.com/extending.html (search for "PrismJS.highlight").
* Peeking into the Prism JSX language defintion explains why this PR fixes its linked issue (#4002): https://github.com/PrismJS/prism/blob/master/components/prism-jsx.js#L119-L124 — its `walkTokens` relies on that undocumented third parameter `language`.

Changing the language of a codeblock from `jsx` to `javascript` resolves any line highlighting issues (#8058).

**Pull request merged**
