### PR TITLE
fix(gatsby): bail early if pageResources are not available in public pageRenderer

### PR DESCRIPTION
**Pull request by whs-dot-hk**
See https://github.com/gatsbyjs/gatsby/issues/12138

### CODE REVIEW

**Comment by pieh** [comment]
This doesn't seem correct - it will render same page component infinite amount of times (as it will render itself recursively)

**Comment by whs-dot-hk** [comment]
@pieh Brilliant.

It looks something like here

https://github.com/gatsbyjs/gatsby/blob/2ba27496107bb6895e6e1371f0b75b5e93a9cafa/packages/gatsby/cache-dir/json-store.js#L87-L89

but I can't fire up the production build with `yarn build` here to confirm

**Comment by pieh** [comment]
@whs-dot-hk we don't use `json-store` in production (only in development). The crashes happen if `pageResources` in `public-page-renderer-prod.js` is null and we try to access `pageResources.json` (in https://github.com/gatsbyjs/gatsby/blob/6dc5dcd5d5b7205d426fc0ffc34d73fd0e3247bd/packages/gatsby/cache-dir/public-page-renderer-prod.js#L16 )

**Comment by pieh** [comment]
I was testing it out, and it works, I just forgot to merge it after I pushed changes and was waiting for tests to come back

**Comment by whs-dot-hk** [comment]
Thanks, one more thing we will have to upgrade the gatsby package version of the site later when there is new release

**Pull request merged**
