### PR TITLE
chore(starters): add gatsby-starter-resume-cms

### PR DESCRIPTION
**Pull request by barancezayirli**
## Description

It is a resume/CV starter with Netlify CMS as the headless CMS for editing content.

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
@barancezayirli Starters typically have the `gatsby-starter-` naming convention. Would you like to rename this to follow that?

**Comment by barancezayirli** [comment]
@sidharthachatterjee sure doing now :)

**Comment by barancezayirli** [comment]
Thank you! @siddhant1

**Comment by barancezayirli** [comment]
@siddhant1 I am trying to figure out why starters_validate is passing (my first assumption was actually it was yaml) but from the script, it is not related. Can you help me out?

**Comment by sidharthachatterjee** [comment]
@barancezayirli That seems unrelated (appears that npm audit is failing because their API is acting funny, happens occasionally) 

Once the rest pass, I'll merge it in anyway 🙂 

(Also you tagged the wrong Sid hehe)

**Comment by barancezayirli** [comment]
@sidharthachatterjee I think I am sleeping still 😃  Trying to finish up everything before Christmas brunch sorry for the spamming :sweat_smile:

**Comment by sidharthachatterjee** [comment]
@barancezayirli Haha, no worries at all! Have fun!

**Pull request merged**
