### PR TITLE
[docs] Add video lesson to the StaticQuery docs

### PR DESCRIPTION
**Pull request by jlengstorf**
NOTE: This is currently blocked because the video is limited to members only. Once it's switched to public, this is good to merge.

This adds a short video demonstrating how `StaticQuery` works to the docs for people who prefer learning through video over reading.

Thanks so much to the @eggheadio team for adding embed support!

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 0ebed2cc805811859a20ad4cb1e09419665efc0f

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6f15aec6aed6471f0c63b8

**Comment by amberleyromo** [comment]
This is going to be an amazing addition to this section! 🔥

Related: #7231, #7059

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 0ebed2cc805811859a20ad4cb1e09419665efc0f

https://app.netlify.com/sites/gatsbyjs/deploys/5b6f15adc6aed6471f0c63ad

**Comment by jlengstorf** [comment]
@amberleyromo this one’s ready for review now. Can you check the way I put the video in to make sure it lines up with your new doc organization?

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit b1be72366d33aaac01970cc9d9243091f88babfa

https://app.netlify.com/sites/using-contentful/deploys/5b7209731f12b77a983c03f7

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit 18a0fc7983a0aba99c366bc6755dd8bb20feac49

https://app.netlify.com/sites/using-contentful/deploys/5b720a10dd28ef1a92c859d6

**Comment by jlengstorf** [comment]
@amberleyromo Yeah, that's fair. Currently the video and the docs aren't related — I made the video not thinking it would be part of the docs, so didn't use the same code.

I've opened #7297 to track lining these up later.

**Pull request merged**
