### PR TITLE
feat(www): Move sidebar settings to YAML, add sidebar title "meta" field

### LINKED ISSUE #12767: Move ecosystem links into top docs nav
Screenshot 2019-03-22 11 40 32

I've heard a number of reports that people have to google the starters library to find it e.g. https://github.com/gatsbyjs/gatsby/pull/12622. I often have trouble finding the link as well.

The problem arises because a) you have to know to open the ecosystem nav and b) if you have "guides" open, this is remembered when you return which means that ecosystem is now pushed very far down the screen so you might not even see if as you scroll by.

Moving the starter/plugin/awesome links to the top might be the right solution. Or perhaps a tweak to how the sidebar nav works in general.

### PR DESCRIPTION
**Pull request by fk**
Inspired by #12767. Describing the changes is a bit … complicated, matching the convoluted stuff we are currently doing for our tutorial/docs/features sidebars. Please ask if something is unclear!

---

Prior to this, we added information

- about the sidebar `key` (`docs`, `tutorial`, `contributing`, `features`), used to write and read local storage information about the expanded/collapsed status of sidebar items,
- wether the sidebar has an „Expand/Collapse All“ button („Features“ does not) via the `disableExpandAll` option, and
- wether the sidebars _first level_ accordions should be disabled via the (unfortunately not clearly named) `disableAccordions` option (again to facilitate the "Features" sidebar UI)

to _each_ sidebar item’s information in [`src/utils/sidebar/item-list`](https://github.com/gatsbyjs/gatsby/blob/master/www/src/utils/sidebar/item-list.js). 💩 

This PR moves that information to the root node of each sidebar’s YAML file  in [`src/data/sidebars`](https://github.com/gatsbyjs/gatsby/tree/master/www/src/data/sidebars):

- puts all current sidebar meta/config data into the sidebar’s YAML
- allows a simpler, generic `src/utils/sidebar/item-list`
- adds a **setting for the sidebar title without having to abuse sidebar items** (see the following description, and https://github.com/gatsbyjs/gatsby/issues/12767#issuecomment-475815324 ff.)

—

Prior to this, we also

- nested all navigation items in „Contributing“ and „Tutorial“ under a root item „Contributing“ and „Tutorial (step-by-step)“ respectively, **only to have a headline for the sidebar items** 😿 
- prevented those items from being collapsable by setting `disableAccordions` to `true`

With this PR, we now expect exactly one node for each sidebar YAML.
This node’s 

- `title` is now used to provide the title for the sidebar,
- `disableAccordion` and `disableExpandAll` can be set here
- `items` does now contain the items to be rendered in the sidebar

`title` allows us to drop nesting all navigation items in "Contribution" and "Tutorial", and removing the "Documentation" item in `src/data/sidebars/doc-links.yaml`.

—

We also relied on the „Tutorial“ sections to be subitems in regards to their styling — we didn’t want them to be rendered as small caps items, like all root-level items with subitems were rendered up to now.

This PR simplifies the appearance of root-level items with subitems, removing their small caps styling. I was extremely hesitant to do so, and I'm not 100% sure it is. **Going back to small caps is a matter of uncommenting a couple lines of CSS**.

If we want specific items to appear as headlines (like e.g. "Guides"), IMO we should do that via a setting on the item level, e.g.

```
    - title: Guides
      link: /docs/guides/
      ui: small-caps
      items:
        - title: Preparing Your Environment
          link: /docs/preparing-your-environment/
``` 

—

Along the way

- ensure that `isActive` and `isExpanded` is correctly set for root-level items
- only apply an „active“ background color to the root level item that is active or is a parent of the currently active item, instead of applying the active background color to each parent item of the currently active item — this lightens the active section background significantly, which IMO is a good thing
- use `colors.white` as background color for sidebars on larger screens (as opposed to a light purple)
- increase the color contrast on the caret icon
- add borders to top-level expandable items

image

image

image

image

image

image

image

## Issues

Fixes #12767 — moves "Plugins", "Starters", and "Awesome Gatsby Resources" below "Cheat Sheet", like suggested in https://github.com/gatsbyjs/gatsby/issues/12767#issuecomment-475749045.

### CODE REVIEW

**Comment by shannonbux** [comment]
Hi @fk!

Do you have an idea of what this would look like?
> paves the way to enable a setting for the sidebar title without having to abuse sidebar items (see the following description, and #12767 (comment) and following)

I left a comment here about the original problem that sidebar titles were trying to solve. It could be solved in other ways. The core need is to provide users with a clear sense of place (i.e. they know when they are in the docs vs. the tutorial. Right now the sidebars look similar enough that they can get confused). https://github.com/gatsbyjs/gatsby/issues/12767#issuecomment-476409129

I really enjoy the lower case option. I think it's easier to read!

Are you also proposing taking out the linked dots to show related parts of the tutorial? If so, just wondering the reasoning.

**Comment by marcysutton** [comment]
Thanks for working on this, @fk! I think the consistency in title casing is a really good change. There's a lot going on, and it's a ton of effort to detangle this stuff...so I really appreciate you taking the lead on it (and including screenshots!)

Some questions / comments I have:
- Can we increase the color contrast on the caret icon so it stands out more (and double check contrast of text / background colors)?
- In the first "after" screenshot with everything neatly collapsed, I wonder if horizontal rules would help users identify the expandable items quickly (a top or bottom border)
- Do the top-level accordion items still navigate you to pages *and* expand subsections (e.g. "Guides" and "Deploying and Hosting")? I could see those being a little confusing without a clear indicator of multiple actions.
- Also curious about the linked dots in the tutorial. They could use more contrast, but I think they do a good job of communicating a set of steps to be completed in order.

**Comment by fk** [comment]
@shannonbux 

>> paves the way to enable a setting for the sidebar title without having to abuse sidebar items (see the following description, and #12767 (comment) and following)

> Do you have an idea of what this would look like?

I had half of a detailed answer to this prepared yesterday, but wasn't finished, didn't send it, and instead relied on GitHub auto-saving it. Then I accidentially closed the tab. Auto-saving didn't work. 🤷‍♂️ … So here's another try, going for a TL;DR this time:

This PR does not change the look of the sidebar title, and doesn't aim to. It does add an option to set the sidebar title though — with this, there's no need anymore to wrap all (in case of "Tutorial" — https://github.com/gatsbyjs/gatsby/blob/a1b8f24e0dfe08a057df7eba1b267185a2b176ed/www/src/data/sidebars/tutorial-links.yaml#L1-L11) or the first items ("Documentation" — https://github.com/gatsbyjs/gatsby/blob/0cc074f0e4becd5a68fd9ec845f173542f8c4807/www/src/data/sidebars/doc-links.yaml#L1-L8) in a _navigation item_ with the sidebar title — instead, there's a bespoke option to set the sidebar title, seperated from the sidebar navigation items.

So this PR resolves the issue of the expandable/collapsible "Documentation" navigation item Kyle asked about in https://github.com/gatsbyjs/gatsby/issues/12767#issuecomment-475815324, but doesn't change (much) how the sidebar headline looks like, but how it is defined — and since it's a "true" headline now, behaves:

image

The other stuff happening in this PR, and why I decided to drop small caps for first-level navigation items that have subitems, is related to that; in an effort to keep this as short as possible I won't try to squeeze that in here for now. Does the rest make sense up to here?

> Are you also proposing taking out the linked dots to show related parts of the tutorial? If so, just wondering the reasoning.

No! They "got lost" while refactoring, and I want to bring them back.

---

@shannonbux @marcysutton 

> I really enjoy the lower case option. I think it's easier to read!

> I think the consistency in title casing is a really good change.

🎉 👍 Yay! _Really_ happy to hear that!

---

@marcysutton

> Can we increase the color contrast on the caret icon so it stands out more (and double check contrast of text / background colors)?

Yes to both. That caret icon color creeps me out every time. Yes! 😅 

> In the first "after" screenshot with everything neatly collapsed, I wonder if horizontal rules would help users identify the expandable items quickly (a top or bottom border)

Yeah, I've been toying with the idea of borders just for the first-level items, too. I'll give that a try!

> Do the top-level accordion items still navigate you to pages and expand subsections (e.g. "Guides" and "Deploying and Hosting")? I could see those being a little confusing without a clear indicator of multiple actions.

Yes, the current behavior — items with subitems can link to pages — hasn't changed.
Do you find it confusing on https://www.gatsbyjs.org/docs/ right now?
IMO I'm leaning towards removing that "split button" functionality — either expand/collapse, or link to a page…

> Also curious about the linked dots in the tutorial. They could use more contrast, but I think they do a good job of communicating a set of steps to be completed in order.

💯

**Comment by shannonbux** [comment]
That all makes sense!

In usability tests last summer, people universally liked the linked dots in
the tutorial, fwiw.

Also, fwiw, I think removing the split button functionality is a good idea
bc it has confused quite a few people (including some more prominent Gatsby
users, which may be swaying me lol). Well, people aren't typically confused
per se, but just don't realize there is a page there and just use the
carat. So I think we should just use the carats and then place the content
from those overview articles into their own docs called "Plugin overview"
etc.

**Comment by marcysutton** [comment]
> we should just use the carats and then place the content from those overview articles into their own docs called "Plugin overview" etc.

Great idea! I think that would clear up any confusion about whether there are intro docs under those accordion links. 👍

**Comment by wardpeet** [comment]
@fk let us know when it's not WIP anymore 😉 also checkout https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by fk** [comment]
> https://github.blog/2019-02-14-introducing-draft-pull-requests/

Oh nice, thanks for the heads up!

**Comment by fk** [comment]
🤞 for getting back to this today.

**Comment by fk** [comment]
Good for review now — I fixed the "Tutorial" links ("bullet path" UI) and indention issues, and cleaned up another round.

> In the first "after" screenshot with everything neatly collapsed, I wonder if horizontal rules would help users identify the expandable items quickly (a top or bottom border)

Added that, too.

> Can we increase the color contrast on the caret icon so it stands out more (and double check contrast of text / background colors)?

Also done.

I also moved "Plugins", "Starters", and "Awesome Gatsby Resources" below "Cheat Sheet", like suggested in #12767 and https://github.com/gatsbyjs/gatsby/issues/12767#issuecomment-475749045, and updated the PR description including the screenshots.

**Comment by fk** [comment]
> so clean

… 50 iterations later 😓 😅 
obv. doesn't solve the bigger issue (that is one hell of a sidebar), but hopefully improves stuff a bit for our users!

Oneeternitylater

**Comment by shannonbux** [comment]
@fk for sure! Small wins can be big wins because you can do them faster! Awesome work

**Pull request merged**
