### PR TITLE
chore(gatsby): add environment variable for setting tracing config file

### PR DESCRIPTION
**Pull request by rudouglas**
## Description

Currently, the only way to enable tracing is to pass the `--open-tracing-config-file` flag as part of the `gatsby build/develop` commands.

Because Gatsby Cloud just seems to run `gatsby build` and ignores these flags in the `package.json`, it's not possible to enable tracing on Gatsby Cloud

This enables tracing by allowing a user to set `GATSBY_OPEN_TRACING_CONFIG_FILE` instead

### CODE REVIEW

**Comment by jpvajda** [comment]
I was just following up on his PR review. if someone could let us know when it may be actioned that be cool! - Than you

**Comment by jpvajda** [comment]
Gatsby confirmed today @rudouglas 

> The tracing PR that you made is being addressed in the current sprint this week!

**Comment by jpvajda** [comment]
Is this PR still on track to be merged in by Aug 31st?

**Review by KyleAMathews — APPROVED** [review]

**Comment by KyleAMathews** [comment]
This is great!

Pushed a couple of updates to standardize the env var name & document it.

I've been thinking/working on tracing support a fair bit this week. Just posted a discussion topic @ https://github.com/gatsbyjs/gatsby/discussions/33145 & have put up some PRs:
- https://github.com/gatsbyjs/gatsby/pull/33142
- https://github.com/gatsbyjs/gatsby/pull/33122
- https://github.com/gatsbyjs/gatsby/pull/33098

Would love y'all's thoughts on improving Gatsby's observability support.

**Comment by rudouglas** [comment]
@KyleAMathews amazing thanks for looking at this, and thanks for the fresh PR's they look awesome and will really help get more valuable data from tracing. We would love to collaborate more and making this even more valuable 🥇

**Comment by jpvajda** [comment]
@KyleAMathews Thank you!

**Pull request merged**
