### PR TITLE
Support the in operator for an array of objects 

### PR DESCRIPTION
**Pull request by LeKoArts**
While using Prismic.io as my data source I encountered the problem that I can't filter for tags anymore like with using markdown. I found this issue:
https://github.com/gatsbyjs/gatsby/issues/3643
Kyle suggested that the tests should be modified first so that other people (who can actually fix that 😆 ) can figure it out.

**Would be cool of course if the initial request of the issue could be done, not only my issue with Prismic.** Feel free to edit this PR to make it work 👍 

I added everything like Prismic is outputting it and how GraphiQL suggests the query/filter. At the moment the result is null. The `can filter for Prismic tags` was just a random name, there's probably a better solution.

Query output:
image

Filter attempt:
image

Filter with query variable:
image

### CODE REVIEW

**Comment by pieh** [comment]
So main thing here is that we shouldn't even use `in` operator for array of objects (in sift that will only really work for scalars or array of scalars - it uses Array.indefOf, so it would never work for newly construct objects). We should use `elemMatch`.

As this never actually worked I think it wouldn't be breaking change to change from `in` to `elemMatch` operator in schema?

**Comment by LeKoArts** [comment]
@pieh Cool, thanks for the fix! 😊

**Comment by LeKoArts** [comment]
@pieh so ready to merge? Will test it immediately then ☺️

**Comment by pieh** [comment]
Not yet, as mentioned in my comment - I need to change operator name to `elemMatch` which fits better to what this operator do than `in` - still need to update code that does that for fields created by `setFieldsOnGraphQLNodeType` api.

**Comment by m-allanson** [comment]
Released as `gatsby@2.0.0-beta.22`

**Comment by LeKoArts** [comment]
@m-allanson @pieh Not working for me 😦 

image

The second elemMatch doesn't get autocompleted.

image

**Comment by Whaitiri** [comment]
I'm encountering this bug in GatsbyV1, since we are in the middle of a project migrating to V2 isn't extremely viable at the moment... is there any way to get this change into V1?

**Pull request merged**
