### PR TITLE
Add `og:image` to Gatsby Default Starter and improve readability of `seo.js` file

### PR DESCRIPTION
**Pull request by thomaswangio**
## Description

This is a continuation of https://github.com/gatsbyjs/gatsby/pull/12626. 

- Added `keywords`, `image` and `url` to  `siteMetadata` in `gatsby-config`
- Added `og:image` and `og:url` to `seo.js` to have a better boilerplate for sharing on Twitter and FB
- Reorganized and declared variables `metaTitle`, `metaAuthor`, `metaKeywords`, `metaImage`, and `metaUrl` to make sure every page will have the these meta tags even if not passed as props to the component. This improves the readability of this file.
- Added corresponding propTypes

## Related Issues

https://github.com/gatsbyjs/gatsby/pull/12626#discussion_r267927939

I have addressed @muescha's concerns about using local path by making a `static` folder and using `withPrefix` to reference the path to `img/gatsby-share.png`. I append this path to `window.location.origin` - which returns the base url, including protocol (HTTP/HTTPS). We need this because `og:image` only accepts `content` which is requires this format to generate the image on social media (FB/Twitter/etc.)

### CODE REVIEW

**Comment by thomaswangio** [comment]
Ok so not sure what's happening, but the ci/circleci `starters_validate` is always failing. Any help would be appreciated!

Screen Shot 2019-03-22 at 8 56 59 AM

**Comment by muescha** [comment]
thats the resolve path: gatsby-plugin-sharp > svgo > js-yaml

you have to wait until the svgo is updated, then gatsby-plugin-sharp can update the version

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/package.json#L25

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/package.json#L25

**Comment by thomaswangio** [comment]
Thanks @muescha, will wait and update when `svgo` PR is merged

**Comment by thomaswangio** [comment]
Thanks for the comments @DSchau! I'll take a look at the other PR and the critique and see if I can come up with something.

**Comment by DSchau** [comment]
Closing this out (for now!) in favor of continuing work on #10921.

Thanks!

**Pull request closed without merging**
