### PR TITLE
New .org title -- Build blazing fast / modern / beautiful / secure websites with React (slider)

### PR DESCRIPTION
**Pull request by calcsam**
Changes the title to "Build blazing fast / modern / beautiful / secure websites with React."

(1) We want to do this to move away from the term "static". It's confusing to people because Gatsby can do way more than people expect from an SSG
(2) Want to highlight the capabilities of Gatsby. It can do so many things so a sliding adjective might highlight that better than just a simple transition => "Build blazing fast websites with React."

Notes and questions:
(1) @fk -- what do you think about drop-in animation vs other types? Eg anything on here: https://codepen.io/amritleone/pen/qERPmW. 
(2) By making the rotating world an adjective about website we aren't able to highlight other features of Gatsby. @jlengstorf suggested "Build blazing fast sites  / more efficient teams / React + GraphQL apps / modern apps / happier with Gatsby." 

We currently treat the homepage as more of a homepage for a docs site, rather than talking about organizational / personal / etc benefits to Gatsby. Open to change this but worth a discussion.
(3) Are there other adjectives we'd want to use in addition to / in place of the ones above?
(4) We probably want to clean this up a bit into its own component but want to get feedback on overall PR first.

### CODE REVIEW

**Comment by m-allanson** [comment]
Preview link: https://deploy-preview-6284--gatsbyjs.netlify.com/

**Comment by jlengstorf** [comment]
screenshot_20180704-092859

I think the line-height may need adjustment, because the "g" is cut off.

Also, there's a blank cell in the rotation. 

Overall, I dig this. I think my preference would be to speed up the transition speed a bit (same pause between transitions) and maybe tighten up the range a bit, like have it travel a shorter distance on the way in and out.

**Comment by fk** [comment]
Niiice!

> what do you think about drop-in animation vs other types?

"drop-in" would have been my choice, too, but I also think it's a little to slow: 💯 to everything @jlengstorf said regarding speed and range.

**Comment by calcsam** [comment]
Thanks @fk and @jlengstorf! 

* Adjusted line-height so that the 'g' is not cut off
* Sped up transition by 20%
* Decreased travel distance by 40%
* Removed empty fifth space

(when it deploys: https://deploy-preview-6284--gatsbyjs.netlify.com/)

@fk -- what's your thought on this orange hex? I used the orange later down on the page as a base and darkened it a bit to match the purple. 

@KyleAMathews -- thoughts?

**Comment by KyleAMathews** [comment]
Like it! Definitely agree it's time to move away from "static" branding Two concerns are a) orange color feels off and b) the spacing is too large between "build" and the different messages.

**Comment by jlengstorf** [comment]
Looking good, @calcsam!

On small viewports the purple text runs into the purple background, though:

screen shot 2018-07-05 at 2 38 28 pm

Maybe it could shrink a bit on smaller viewports?

Here's a version with `font-size: 1.5rem`:

screen shot 2018-07-05 at 2 41 03 pm

Here's a version with decreased top padding on the container dropped to `5.5rem`:

screen shot 2018-07-05 at 2 42 20 pm

**Comment by fk** [comment]
@jlengstorf Ugh, that $#! skewed background again… :/

Re: orange—maybe try [`colors.lilac`](https://github.com/gatsbyjs/gatsby/blob/4a946428cb555c8141c7f69544bbd528f11a5c1a/www/src/utils/colors.js#L61); doesn't stand out as much, but hopefully the animation will take care of that.

**Comment by fk** [comment]
@calcsam 

> what's your preference re: the css here? I'm not really a fan of the glamor keyframes syntax which is core to the logic here so would prefer to leave as is

No preference—leave it as it is!

**Comment by calcsam** [comment]
Going to merge this in! Builds are failing but should go live shortly.

**Pull request merged**
