### PR TITLE
Remove unnecessary constructors

### PR DESCRIPTION
**Pull request by alexisshriov**
## Description
I removed constructors where their only purpose is to initialize the state, as with es6 we can declare state as a class property, we can get rid of these constructors in these components

### CODE REVIEW

**Comment by 12vanblart** [comment]
Hey - Don't think I was meant to be tagged here?

**Comment by LekoArts** [comment]
@alexisshriov Please stop requesting reviews from random people. The Gatsby Docs team needs to review this.

@12vanblart What comment have you given? @alexisshriov deleting comments is a big no-go and I ask you to follow our [Code of Conduct](https://www.gatsbyjs.org/contributing/code-of-conduct/) as otherwise we'll need to remove your access to this repository.

**Comment by alexisshriov** [comment]
@LekoArts sorry I wasn't sure who to add to review this, since the PR was not getting reviewd I thought I wasn't adding the right people

**Comment by laurieontech** [comment]
@LekoArts Since not all of these are docs changes, is this fine from a core perspective?

**Comment by LekoArts** [comment]
Looking more closely at the contents of this PR I don't think we should merge this. This isn't improving any metric we value and is more a change for the sake of changing things. The official React docs also still show it like this and it's valid syntax.

So I'll close this then. Thanks for the PR nevertheless!

Please take a look at [our open issues][open-issues] for ideas, and please reach out to us on Twitter at `@gatsbyjs` with questions.

[open-issues]: https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Pull request closed without merging**
