### PR TITLE
[1.0] Refactor data layer

### PR DESCRIPTION
**Pull request by KyleAMathews**
* new node schema"
  * require all nodes to have a "content digest"
  * all nodes required to use official "mime-type" from https://www.npmjs.com/package/mime-db
* New cache module for typegen plugins to cache their data
* Save and restore node data state (time to finish bootstrap for one larger site dropped from ~45 seconds to ~5 seconds).

## TODOs

- [x] change "parser" to "transformer"
- [x] move `.intermediate-representation` to `.cache`
- [x] add tests for transformers
- [ ] refactor graphql query runner and cache queries and query results
- [ ] write out images to `.cache`
- [ ] ensure hot reloading of content/queries working correctly
- [ ] document node
- [ ] HN clone with new source plugin for HN data

### CODE REVIEW

**Comment by fabien0102** [comment]
@KyleAMathews I already move `.intermediate-representation` to `.cache` into #802 ;) (you have mention it into targeted directory structure ^^)

**Comment by KyleAMathews** [comment]
Indeed! I'll merge that branch in a bit.

**Comment by KyleAMathews** [comment]
I'm going to just merge this and work on the remaining TODOs on subsequent PRs.

**Comment by KyleAMathews** [comment]
And as of https://github.com/gatsbyjs/gatsby/pull/818/commits/a18ee330d759e0a5e6ccddc1704aeb9e82f0c741 we're now actually building the websites from the latest code.

**Comment by KyleAMathews** [comment]
We do a Babel build of all src code and then copy the packages into the website overwriting what was installed from npm. It uses `gatsby-dev-cli` for this.

**Pull request merged**
