### PR TITLE
docs(gatsby-plugin-manifest): Allow icons to be used without a mask on other devices

### PR DESCRIPTION
**Pull request by pranjaljately**
When using 'maskable' with the automatic mode configuration **without 'any'**, the browser displays the following issue with the manifest:

image

Using 'any' allows maskable icons to be used for Android but also allows the icons to meet the size (144px) and shape (square) required on desktops/browsers.

> The purpose field tells the browser how your icon should be used. By default, icons will have a purpose of "any". These icons will be resized on top of a white background on Android.

> Maskable icons should use a different purpose: "maskable". This indicates that an image is meant to be used with icon masks, giving you more control over the result. This way, your icons will not have a white background. You can also specify multiple space-separated purposes (for example, "any maskable"), if you want your maskable icon to be used without a mask on other devices.

https://web.dev/maskable-icon/

### CODE REVIEW

**Comment by moonmeister** [comment]
Looks like a reasonable change. Thanks for bringing it up. You have only edited the docs though...please update the default config used by Automatic mode, I believe you'll find it in `src/common.js`

**Comment by pranjaljately** [comment]
So I've made some changes based on my understanding of how this should work. If the icon_options key is **not** present in the manifest, then the defaultIconOptions are used. 

I am unsure about how to handle the empty `icon_options: {}` case so your input would be great.

PS: Newbie to contributing so apologies if this was not the best/right approach 😅

**Comment by moonmeister** [comment]
Nio worries on being new, we've all been there and are happy to direct. I just realized...For some reason I thought we were already marking icons as "maskable"...probably from the readme you edited and I didn't understand the context of the edit till I read closer...but my point is we're not...and to me that makes sense. We don't know if users are providing maskable icons, if they don't know what that is, they probably won't, unless they get lucky in their icon design. But in this case we don't want to mark them as maskable. If a dev/team is creating maskable icons they will probably also know they need to mark them as maskable and will configure them as such. 

Questions for you: 
1. Do you have a differing opinion on this?
2. Is there a reason to mark `purpose: any` and drop maskable on all the defaultIcons?

Also, instead of using our custom icon options array as you have we just want to edit defaults, so we'd want to modify the `defaultIcons` array.

Thanks for bringing this up and being willing to put in the work. Even if we don't end up making code changes we could improved the docs with links and resources you shared above!

**Comment by pranjaljately** [comment]
Okay, great. I think we are in agreement on this thus why I only updated the docs originally. I will revert the changes 👍

**Comment by moonmeister** [comment]
Ah okay, makes sense now, sorry for the detour. yeah, update the docs and maybe link to that resource and anything else you think is helpful.

**Comment by pranjaljately** [comment]
No worries, it was an enjoyable experience to see and edit the internals 😄 

I have added a new resource and updated the icon_options in the README to 'any maskable'. I found that the original links in the docs provide the user with information about using 'maskable' but not that it should be used in conjunction with 'any'. 

The updated icon_options in the README should help users avoid running into the same issue that I did in the [image above](https://github.com/gatsbyjs/gatsby/pull/24490#issue-423323071) and thus avoid them having to go off and find a solution. 👍

**Comment by moonmeister** [comment]
Looks good. I'm about to make a request/suggestion...if you don't have time or just don't feel like it, don't worry about it.

 This comment and maybe in other locations there are links to external resources. Move them out of comments and into the "[Additional resources](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-manifest/README.md#additional-resources)" appendix in a list. Finally, add a sentence at the end of the opening paragraph of the readme letting folks know that the readme will focus on configuring the plugin, if they'd like resources on the using web app manifest they should check out the appendix.

**Comment by pranjaljately** [comment]
Updated as per your suggestion 😀👍 
I'm pretty happy with the updated README but do let me know if there is anything I should change.

**Review by wardpeet — APPROVED** [review]
LGTM, thank you for your patience!

**Pull request merged**
