### PR TITLE
Added developers.sparkpost.com to showcase

### PR DESCRIPTION
**Pull request by avigoldman**
Take 2 😉

Added [developers.sparkpost.com](https://developers.sparkpost.com) to the site showcase.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 6d262f4d090c9192306c17f20a3120316e18e0b7

https://app.netlify.com/sites/using-postcss-sass/deploys/5b60549f02ed831f7f47667d

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit 6d262f4d090c9192306c17f20a3120316e18e0b7

https://app.netlify.com/sites/image-processing/deploys/5b60549f02ed831f7f476681

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit 6d262f4d090c9192306c17f20a3120316e18e0b7

https://app.netlify.com/sites/using-contentful/deploys/5b6054a002ed831f7f476687

**Comment by m-allanson** [comment]
and thanks @amandeepmittal :)

**Pull request merged**
