### PR TITLE
fix(security): update vulnerable packages, include React 17 in peerDeps

### PR DESCRIPTION
**Pull request by hoobdeebla**
This PR aims to reduce the amount of warnings users see from their package manager on first install.

1) Updates React peerDependency of Gatsby and plugins to include React 17
2) Updates the following packages to remove vulnerabilities and peerDependency warnings: axios, babel-plugin-add-module-exports, contentful-management, debug, documentation, gatsby-plugin-webfonts, hicat, lodash-webpack-plugin, node-fetch, probe-image-size, rewire, subfont, verdaccio, webpack-dev-server, yargs, yurnalist. Major changes are as follows:

| Package | Change | Breaking Changes |
| -- | -- | -- |
| [babel-plugin-add-module-exports](/lijunle/babel-plugin-add-module-exports) | [`^0.3.3` -> `^1.0.4`](https://app.renovatebot.com/package-diff?name=babel-plugin-add-module-exports&from=0.3.3&to=1.0.4) | [actually work with Babel 7 (does not affect usage here)](/59naga/babel-plugin-add-module-exports/compare/v0.3.3...lijunle:v1.0.4)
| [contentful-management](/contentful/contentful-management.js) | [`^5.26.3` -> `^7.5.1`](https://app.renovatebot.com/package-diff?name=contentful-management&from=5.26.3&to=7.5.1) | [none that affect usage in gatsby-recipes](/contentful/contentful-management.js/releases?after=v7.0.1)
| [documentation](/documentationjs/documentation) | [`^12.3.0` -> `^13.1.0`](https://app.renovatebot.com/package-diff?name=documentation&from=12.3.0&to=13.1.0) | [require Node 10](/documentationjs/documentation/blob/master/CHANGELOG.md#1300-2020-05-09)
| [hicat](/rstacruz/hicat) | [`^0.7.0` -> `^0.8.0`](https://app.renovatebot.com/package-diff?name=hicat&from=0.7.0&to=0.8.0) | [none (I made the changes myself)](/rstacruz/hicat/releases)
| [node-fetch](/node-fetch/node-fetch) | [`^1.7.3` -> `^2.6.1`](https://app.renovatebot.com/package-diff?name=node-fetch&from=1.7.3&to=2.6.1) | [none that affect usage in gatsby-source-graphql](/node-fetch/node-fetch/blob/master/docs/CHANGELOG.md#v200) |
| [probe-image-size](/nodeca/probe-image-size) | [`^5.0.0` -> `^6.0.0`](https://app.renovatebot.com/package-diff?name=probe-image-size&from=5.0.0&to=6.0.0) | [require Node 10, switch from request to needle - none that affect usage in gatsby packages](/nodeca/probe-image-size/blob/master/CHANGELOG.md) |
| [rewire](/jhnns/rewire) | [`^4.0.1` -> `^5.0.0`](https://app.renovatebot.com/package-diff?name=rewire&from=4.0.1&to=5.0.0) | [require Node 8 (does not affect usage in gatsby-plugin-offline)](/jhnns/rewire/blob/master/CHANGELOG.md) |
| [subfont](/Munter/subfont) | [`^4.2.2` -> `^5.2.5`](https://app.renovatebot.com/package-diff?name=subfont&from=4.2.2&to=5.2.5) | [require Node 10 (does not affect usage in gatsby-plugin-subfont)](/Munter/subfont/releases/tag/v5.0.0) |
| [yargs](/yargs/yargs) | [`^10.1.2` -> `^15.4.1`](https://app.renovatebot.com/package-diff?name=yargs&from=10.1.2&to=15.4.1) | [none that affect usage at the root of the monorepo](/yargs/yargs/blob/master/docs/CHANGELOG-historical.md) |
| [yurnalist](/0x80/yurnalist) | [`^1.1.2` -> `^2.1.0`](https://app.renovatebot.com/package-diff?name=yurnalist&from=1.1.2&to=2.1.0) | [improve silent mode, update dependencies - none that affect usage in gatsby-cli](/0x80/yurnalist/compare/v1.1.2...v2.1.0) |

Fixes https://github.com/gatsbyjs/gatsby/issues/28781
Fixes https://github.com/gatsbyjs/gatsby/issues/28858

### CODE REVIEW

**Comment by hoobdeebla** [comment]
No idea why the bootstrap run keeps failing 🤔 everything bootstraps locally. Even the Windows run (which includes its own bootstrap step) is passing on CI.

Each run fails on the gatsby-plugin-image build step. Here is the output from the most recent run:
```
lerna ERR! yarn run prepare stderr:
(node:6686) ExperimentalWarning: The fs.promises API is experimental
(node:6722) ExperimentalWarning: The fs.promises API is experimental
(node:6708) ExperimentalWarning: The fs.promises API is experimental
(node:6707) ExperimentalWarning: The fs.promises API is experimental
(node:6730) ExperimentalWarning: The fs.promises API is experimental
internal/child_process.js:358
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at spawn (child_process.js:533:9)
    at Object.fork (child_process.js:108:10)
    at ChildProcessWorker.initialize (/home/circleci/project/node_modules/jest-worker/build/workers/ChildProcessWorker.js:137:44)
    at ChildProcessWorker.onExit (/home/circleci/project/node_modules/jest-worker/build/workers/ChildProcessWorker.js:263:12)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
error Command failed with exit code 1.
ERROR: "build:browser" exited with 1.
error Command failed with exit code 1.
error Command failed with exit code 1.

lerna ERR! yarn run prepare exited 1 in 'gatsby-plugin-image'
```

The two errors it generates are: 1) fs.promises is an experimental API; 2) there is a memory leak somewhere during the microbundle build. Neither of these errors occur when I bootstrap locally on Node 10.13.0 or 12.20.0. Whether the first, the second, or both errors throw on each CI run seems to be random.

**Comment by hoobdeebla** [comment]
Updated the PR to include an upstream security fix for `hicat` and a yarn.lock security patch for `ini`.

I am still receiving the aforementioned errors on CircleCI but not locally. Also, it seems like ALL current PRs are erroring on `windows_unit_tests` runs because of a connection problem. I would appreciate if a team member could look into these issues.

**Review by kailan — APPROVED** [review]

**Comment by hoobdeebla** [comment]
Still getting the bootstrap errors about every 9 out of 10 CI runs (but never locally). Occasionally it passes without erroring, but then it doesn't pass some e2e tests, which I have been unable to run because I develop in WSL.

**Comment by hoobdeebla** [comment]
I guess the issue was because I removed `react` and `react-dom` from the peerDeps of `gatsby-plugin-image`. Again, I only saw this issue on CI and never had a build fail locally with either of the two errors CircleCI gave.

**Comment by LekoArts** [comment]
Can you please revert `Removes React peerDependency from Gatsby dependents since it will be met by Gatsby itself` as those are necessary for module resolutions? Thanks!

**Comment by LekoArts** [comment]
Due to https://github.com/gatsbyjs/gatsby/issues/28877 you'll need to revert the socket.io changes / will fix merge conflicts once https://github.com/gatsbyjs/gatsby/pull/28885 is merged.

**Comment by hoobdeebla** [comment]
Thank you for the feedback @LekoArts, this should be ready to go now. Had no idea about the minor-release breaking change - agreed that it is unfortunate, unexpected, and unreasonable.

**Review by w3bdesign — APPROVED** [review]

**Review by wardpeet — APPROVED** [review]

**Review by wardpeet — APPROVED** [review]

**Pull request merged**
