### PR TITLE
Security md update

### PR DESCRIPTION
**Pull request by mlgualtieri**
## Description

Updating vulnerability reporting guidelines

### CODE REVIEW

**Review by bradledford — COMMENTED** [review]
👍

**Review by TylerBarnes — DISMISSED** [review]
This is a lot nicer :rocket:

**Review by TylerBarnes — APPROVED** [review]
Just ran the linter bot so tests pass :+1:

**Comment by mlgualtieri** [comment]
Thanks!  I wasn't sure how to run it through the linter or if it was necessary.

**Pull request merged**
