### PR TITLE
[v2] Versions are confusing

### PR DESCRIPTION
**Pull request by m-allanson**
Fix #5890

### CODE REVIEW

**Comment by nihgwu** [comment]
but why `next` is behind `latest`, and the current dependent version with next will match to `latest` actually, for example, as `gatsby` depends on `"gatsby-link": "^1.6.38-15",`, but `gatsby-link@1.1.58` will be installed

**Comment by pieh** [comment]
@nihgwu Yeah, you seem right, this was reverting changes we made earlier today here when we were merging master into v2 - https://github.com/gatsbyjs/gatsby/commit/b5ff2b69ed544fcc1ca94cfdb94134967a8e14c6#diff-d42476695f98af8f85d595ac39bc0653

so this didn't really change from previous alpha releases (or I can't see how) - but it defenitely is wrong and we are trying to cleanup versions mess in v2

**Comment by nihgwu** [comment]
I've mentioned about the confusing version problem in another PR, I think we should bump the version for `gatsby-link` and `gatsby-cli`, I'm using `resolutions` to lock the correct version in my projects

**Comment by pieh** [comment]
@nihgwu  Yeah, we are doing this right now, and should have PR ready soon

**Comment by pieh** [comment]
@nihgwu please check #5899

**Pull request merged**
