### PR TITLE
[gatsby-image] re: fade out base64 on full image load

### PR DESCRIPTION
**Pull request by alexkirsz**
See https://github.com/gatsbyjs/gatsby/issues/2330

### CODE REVIEW

**Comment by alexkirsz** [comment]
This issue still happens when JavaScript is disabled.

**Comment by KyleAMathews** [comment]
Seems reasonable! Sorry for being so slow in reviewing @alexkirsz! Getting v2 clogged up working on PRs. Could you update from the latest master as there's merge conflicts now.

**Comment by m-allanson** [comment]
Thanks @alexkirsz! I merged the latest version of `master` into your branch, then spent some time testing your fix. I _think_ I've found a simpler solution here.

The bug was happening in browsers without Intersection Observer (IE11 and Safari), and was caused because the component was marking the image as loaded before the image had actually loaded. This meant that when the image really _was_ loaded, things were going a bit wonky.

Safari Tech Preview supports Intersection Observer and was working correctly without this fix.

I'm going to do some more tests on this, but so far it looks good on:

- Chrome
- Chrome Canary
- Firefox
- Safari
- Safari Tech Preview
- MS Edge
- IE11

😅

**Comment by m-allanson** [comment]
Thanks again @alexkirsz, this was published as `gatsby-image@2.0.24`

**Pull request merged**
