### PR TITLE
[v2] [gatsby-plugin-offline] [see #7605] Fix service worker failing to install due to incompatible regex

### LINKED ISSUE #7547: [v2] [gatsby-plugin-offline] Service worker install fails on non-Blink browsers
Thanks to @dbrookes for finding this - I used a negative lookbehind in a regex in `gatsby-plugin-offline/gatsby-node.js`, which isn't compatible with Firefox or older versions of Node. I'll submit a PR shortly - just creating this issue to keep track

### PR DESCRIPTION
**Pull request by davidbailey00**
PR #7605 also fixes the same issue, as well as upgrading to Workbox.
I've left this PR open because it might take less time to review than #7605, in case the bug needs to be fixed urgently - I thought it's quite a nasty bug since SWs fail to install entirely on most non-Chromium-based browsers.

---

In #7355 I used regex lookbehind, which I thought works in every modern browser but later realised it only works in Chrome at the moment, since it's an ES2018 feature. This is breaking the SW entirely on most other browsers.

This PR uses my fork of sw-precache which supports more options, so we no longer need to use a lookbehind regex, or patch the output file.

~~In #7547 I suggested creating an official Gatsby fork of this package, since Google has abandoned it and having it as part of Gatsby would allow other contributors to write fixes easily. If this is thought to be a good idea, all that needs to happen is a fork from [my repo](https://github.com/davidbailey00/sw-precache) to gatsby-sw-precache and a few changes to `package.json` - I've already added all the copyright notices. If not, I'll just change Gatsby in those copyright notices to my name.~~

~~Inkteam - please let me know your thoughts regarding a fork of sw-precache! I can't really think of another way of getting gatsby-plugin-offline to work nicely, but maybe there's something better which I haven't thought of.~~

We'll use my forked version for now, but migrate to Workbox in the future.

Fixes #7547.

- [X] manual testing complete (as with #7355)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
We probably should update to workbox at some point. There's no particular reason we're on sw-precache other than "if it ain't broke, don't fix it". That being said, 
@kkemple  did try briefly to upgrade to workbox but we decided to back it out as it changed things more than we wanted to tackle for an upgrade.

But no pressure to do that if your fork was pretty easy to make and as you said, sw-precache isn't being upgraded anymore so we won't have to sync with upstream.

**Comment by davidbailey00** [comment]
Thanks for the info, I guess that rules out the possibility of a Gatsby-official fork of sw-precache. I could definitely try tackling the upgrade to Workbox though - I'll run through all the tests for this PR and then try starting that.

**Comment by davidbailey00** [comment]
I've retested the relevant tests from #7355 (some don't need to be retested since I've only changed gatsby-plugin-offline) - this should now be ready for review.

I had a look at Workbox earlier - like my fork of sw-precache, it has a `navigateFalbackBlacklist` option although no equivalent to `navigateFallbackRegExpsIncludeParameters`. This means it would still need to be modified to add such an option, or we would have to generate the service worker using the Workbox API instead of using a simple JSON config, which would be significantly more complex to understand and maintain.

Since Workbox seems less active (i.e. PRs would take longer to be accepted), and its codebase  is much more complex than that of sw-precache, I'll think about an alternative to appending `no-cache=1` in order to load pages directly, so that Workbox can be implemented.

**Comment by davidbailey00** [comment]
Sorry again for breaking this in my last PR, I'll try to test more carefully in different environments from now on.

**Pull request closed without merging**
