### PR TITLE
fix(gatsby-source-wordpress):issue #29535 not finished createSchemaCu…

### PR DESCRIPTION
**Pull request by lwz7512**
fix issue #29535 

## Description

There is a bug in `gatsby-source-wordpress` plugin version 4.0.1 that cause the Wordpress blog build failure using developer's Graphql url. It turned out because of null value of transformedFields in build-types.js.

### Documentation

no

## Related Issues

#29535

### CODE REVIEW

**Comment by LekoArts** [comment]
Hi, thanks for the PR! Please revert the changed `yarn.lock` file as that shouldn't be part of this PR. Thanks!

**Comment by TylerBarnes** [comment]
Just tried this out and it works great 👍 thanks @lwz7512 ! Once you make the change requested above this is ready.

**Comment by lwz7512** [comment]
> Hi, thanks for the PR! Please revert the changed `yarn.lock` file as that shouldn't be part of this PR. Thanks!

Reverted! Thank you for reminding!

**Review by ascorbic — APPROVED** [review]

**Comment by ascorbic** [comment]
Published in `gatsby-source-wordpress@4.0.3`

**Pull request merged**
