### PR TITLE
Added AngularToReact.com to Showcase List

### PR DESCRIPTION
**Pull request by michael-martin-al**
I just rebuilt my site with Gatsby, so I thought I would link to it here -- if you don't mind.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Nice! Congrats on the launch!

BTW, it doesn't look like you're using the `<Link>` component from React Router. If you use that, page transitions will be client only instead of reloading from the server each time :-)

**Comment by michael-martin-al** [comment]
Thanks @KyleAMathews! 

I'm using `<a>` instead of `<Link>` so that the page reloads fully each time. It's not ideal for performance, but it's a workaround for now until I can figure out a way to get the Adsense ads and AddThis api to recognize when a user loads a new page client-side. I added a a `gatsby-browser.onRouteUpdate` hook that I'm using for Google Analytics, but I can't get it to work for Adsense or AddThis yet. 😢

**Comment by KyleAMathews** [comment]
Ah cool :-) well luckily it's still as fast as any other normal site out there hehe :-)

**Comment by jlengstorf** [comment]
Hiya @michael-martin-al! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
