### PR TITLE
Create new page docs/creating-hybrid-pages-with-static-and-dynamic-components.md

### PR DESCRIPTION
**Pull request by dominicfallows**
Update docs/creating-and-modifying-pages.md to expand on the use of client-only routes - enabling Gatsby to be used to hybrid or "app-shell" Gatsby apps.

### CODE REVIEW

**Comment by dominicfallows** [comment]
This helps clear up my question on issue #3451

**Comment by calcsam** [comment]
Nice, this is really helpful. Could you actually break these two sections out into their own page, called eg Creating Dynamic Pages? This is a topic we're hearing about more and more and it would be good to have a top-level guide.

Glad you worked through this & took the time to help the next person!

**Comment by dominicfallows** [comment]
@calcsam no problem, that makes sense to split into its own page. Commit pushed.

**Comment by KyleAMathews** [comment]
Thanks @dominicfallows! This is something I'd been planning on working on so took your edits and made a number more of my own :-)

**Comment by sedubois** [comment]
Thanks this is super helpful 🙏 One more thing that would be super helpful is documentation/examples with the "authentication gate" for client-only routes. I have no clue how to do this securely yet, many places talk about storing tokens in localStorage while others say that's subject to XSS attacks. So some doc that points in the right direction to have minimal integration with things like ad-hoc, auth0, aws cognito would be super duper.

**Comment by sedubois** [comment]
Ref about avoiding localStorage: https://www.rdegges.com/2018/please-stop-using-local-storage

**Comment by jlengstorf** [comment]
Hiya @dominicfallows! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
