### PR TITLE
feat(gatsby-source-wordpress): improve error logging for wordpress API requests

### LINKED ISSUE #8928: [gatsby-source-wordpress] log failed HTTP requests
## Summary

When setting up a new Gatsby Wordpress site, I was experiencing a lot of errors that looked like this:

```
⠄ source and transform nodesThe server response was "401 Unauthorized"
Inner exception message : "You are not currently logged in."
```

As a new Gatsby user, I had no idea what this meant. It appeared to be a major blocking issue, but turned out to not be a big deal.

My suggestion is to log the paths to the routes that are failing so it's easy for the developer to update `excludedRoutes`. I ended up hacking the plugin to print the routes so I could figure out what was going on.

### Motivation

These errors are very intimidating to new users, and difficult to debug. We can improve the developer experience significantly with a little bit of work on the error logs.

### PR DESCRIPTION
**Pull request by maxlapides**
closes #8928

### CODE REVIEW

**Comment by jlengstorf** [comment]
The gatsbot failure was a false positive; we've fixed it now!

**Comment by pieh** [comment]
@maxlapides do we have acceess to `request` object there? It would be great if we display path as first console output

**Comment by maxlapides** [comment]
@pieh Yes, we have access to the entire axios request object. Is your suggestion to move my new `console.log` above the existing "Inner exception message" log, or am I misunderstanding?

**Comment by pieh** [comment]
I think all of errors would benefit from displaying paths - like this one https://github.com/gatsbyjs/gatsby/blob/2ac2365c3d63f24b5ad6f47f88f956b59a73d69e/packages/gatsby-source-wordpress/src/http-exception-handler.js#L11-L16 doesn't seem to show path either. So it would be good to say at the start of error handler function that request to <path> failed and then display additional information

**Comment by maxlapides** [comment]
@pieh sure, that makes sense. how's this new update?

screen shot 2018-10-09 at 4 15 03 pm

**Comment by pieh** [comment]
> how's this new update?

Yeah, I think it's ok - people at least have context now for failed requests. Updated branch to get things that should fix CI errors and will merge as soon as tests are green. Thanks @maxlapides!

**Comment by maxlapides** [comment]
thanks @pieh!

**Pull request merged**
