### PR TITLE
chore: update Prettier, ESLint, SVGO and plugins

### PR DESCRIPTION
**Pull request by lipis**
## Description

Updated to the latest versions of Prettier, ESLint, SVGO, Plugins, Husky, Lint-staged

### CODE REVIEW

**Comment by KyleAMathews** [comment]
What breaking changes does husky have?

**Comment by lipis** [comment]
@KyleAMathews https://github.com/typicode/husky/blob/master/CHANGELOG.md#200
- Breaking change drop Node 6 support

**Comment by lipis** [comment]
I reverted husky since we support node 6.

**Comment by wardpeet** [comment]
we only support node 6 for dependencies. We don't need to support it for dev stuff :) So feel free to upgrade to the lasest version as long as gatsby itself is node 6 compliant we are good!

**Comment by lipis** [comment]
Updated.. but not sure why it's complaining.. synced with master as well.

**Pull request merged**
