### PR TITLE
Chore: uuid major upgrade

### PR DESCRIPTION
**Pull request by herecydev**
Relevant changelog: https://github.com/uuidjs/uuid#upgrading-from-uuid3x

### CODE REVIEW

**Comment by pvdz** [comment]
@herecydev can you confirm that the bundle did not grow to include the entire uuid library? There are two cases in the PR where `v4` is `required` rather than `imported` and since their changelogs explicitly mention tree shaking as a reason for no longer exposing deep imports, I'd also want to make sure the whole library unnecessarily reaches the front end. That would be bad :)

**Comment by herecydev** [comment]
I'll do my best to work that out

**Review by pvdz — APPROVED** [review]

**Comment by pvdz** [comment]
Great, thanks :)

**Comment by vladar** [comment]
Published in `gatsby@2.24.52`

**Comment by pvdz** [comment]
This change is being reverted in https://github.com/gatsbyjs/gatsby/pull/26824 because the ESM changes applied in v7/v8 are causing problems and we're not expecting support from the maintainers. Additionally, there's no real benefit from bumping the dep version so we're just gonna pin it to 3.4.0 and move on, ultimately replacing it with something custom. In all use cases of this library we mostly care about generating a random string, not an actual uuid.

**Pull request merged**
