### PR TITLE
gatsby release version template tag

### PR DESCRIPTION
**Pull request by illucent**
## Description
Current gatsby release version template tag to use e.g. in footer 

```
import { Version } from 'gatsby'
```
and

```
<Version />
```
or Gatsby Config API?

## Related Issues

n/a

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Looks like a bunch of extra changes got included?

**Comment by illucent** [comment]
I do not know, just some extra possibly, useful features.

**Comment by KyleAMathews** [comment]
It works best if each PR is small and focused as those are much easier to review. Could you please back out all the changes except the version component and open them up as separate PRs. Thanks!

**Comment by illucent** [comment]
okay, it is unattended, how to revert changes, this is just a theoretical proposition, an idea. Thanks in advance.

**Comment by illucent** [comment]
Or please just erase my PR I will recreate it as separate PR. Thanks!

**Pull request closed without merging**
