### PR TITLE
chore(functions): added functions examples to examples folder.

### PR DESCRIPTION
**Pull request by jsumnersmith**
## Description

Adding the functions examples that were originally shared with a [separate repo](https://github.com/gatsbyjs/gatsby-functions-beta) into the main examples folder.

### Documentation
Functions are already documented [here](https://www.gatsbyjs.com/docs/how-to/functions/) (though we will remove the beta flag shortly).

### CODE REVIEW

**Review by sidharthachatterjee — APPROVED** [review]
Looks good, thank you!

**Comment by sidharthachatterjee** [comment]
@jsumnersmith We have some linting issues, it appears

**Comment by jsumnersmith** [comment]
Will lint and fix locally!

**Review by sidharthachatterjee — APPROVED** [review]
Let's ship!

**Pull request merged**
