### PR TITLE
Add example sites

### PR DESCRIPTION
**Pull request by agarrharr**
This adds 3 example sites to the docs.

- [ ] I'm having trouble overriding the `border-bottom` and `box-shadow` on the link I put around the images. A class isn't as specific as `.main-body a`.
- [ ] I'm also not sure how it should look exactly.
- [ ] We also need to add a few examples to the homepage and link here.
- [ ] I'm not sure how it should look, or if there should be a description.
- [ ] I'm not sure where it should go in the menu. Right now, I put it under "Getting Started".
- [ ] And of course, we need to find a better way to automate getting the screenshots.

gatsbyjs

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Awesome! So glad you're taking this on. This will be a big attraction on gatsbyjs.org

Googled around for some design inspiration and found the following:

* http://www.siteinspire.com/websites?categories=135
* https://showcase.joomla.org/browse-sites.html
* https://bestwebsite.gallery/sites
* https://webflow.com/discover/popular#recent
* https://wordpress.org/showcase/
* https://www.studiopress.com/showcase/

**Comment by KyleAMathews** [comment]
Hey hey! https://chromeless.netlify.com

**Comment by agarrharr** [comment]
@KyleAMathews Nice! I just saw that on Twitter and came here to post the link.

So yeah, that should help automate screenshots. You said something about not wanting to store the images in the repo? So would they just get regenerated on every build?

**Comment by KyleAMathews** [comment]
Yeah, the screenshots would be stored in the `.cache` folder. We could also do something like store when the screenshot was taken so if it's > 2 weeks old or whatever, we generate a new one.

**Comment by oliverbenns** [comment]
Nice! I think there should also be a link to the source somewhere when it's available. Which might mean we need 2 cta buttons instead of the one container link. Unless you see another area for sources @KyleAMathews .

**Comment by KyleAMathews** [comment]
Would love to get this in still but since this PR is stalled at a fairly early stage, closing it now to cleanup PRs.

Lemme know @agarrharr if you want to start working on this again!

**Pull request closed without merging**
