### PR TITLE
graphql rewrite codemod

### PR DESCRIPTION
**Pull request by jquense**
The codemod is done i think but the package isn’t cleaned up enough for publishing, I need to add some real testing but ran out of time.

### CODE REVIEW

**Comment by m-allanson** [comment]
This will be really nice to have, thanks @jquense! Refs: https://github.com/gatsbyjs/gatsby/issues/5038

**Comment by KyleAMathews** [comment]
This looks great!

@jquense you want to run this against www and the example sites and include that in the PR?

**Comment by m-allanson** [comment]
@jquense shall I merge this in and publish as a 0.0.0-beta version?

**Comment by jquense** [comment]
whatever you think is best! it's done tho, i've used it a few times on my projects with no issue (so far)

**Comment by pieh** [comment]
I think we just miss "how to use" section somewhere.

As I understand currently to use this we need to install `jscodeshift` seperately and then run it with something like `jscodeshift -t <path_to_gatsby-codemods/src/transforms/global-graphql-calls.js> <path_to_project_src_dir>`?

**Comment by pieh** [comment]
Or add `jscodeshift` as dependency here and add cli that will use that and tell people to install this package globally?

**Comment by m-allanson** [comment]
I haven't run this yet, but added a first draft at a README.

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit a91bdf25ab66afee6acdace1fafe3478a99cad95

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6b3f0fc6aed638f531447f

**Comment by KyleAMathews** [comment]
Deploy preview for *using-styled-components* failed.

Built with commit f82cae4ebf274962332e5c5d3acf2e56263cace8

https://app.netlify.com/sites/using-styled-components/deploys/5b6b40bd4ed62f67fabee146

**Comment by m-allanson** [comment]
I think this is ready for review 🎉 

@jquense I hooked your fixtures into jscodeshift's `testUtils` module, which will run them in Jest along with the rest of Gatsby's tests. The codemod itself is unchanged from your initial version 💪

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 360ace3856996b33940c24b3b562a4ee52fc4025

https://app.netlify.com/sites/gatsbyjs/deploys/5b6d7b84c6aed6224c59b56f

**Pull request merged**
