### PR TITLE
[gatsby-source-wordpress] use queue to manage all requests

### PR DESCRIPTION
**Pull request by pieh**
This is request for comments PR - it removes all direct axios calls and wraps them in queue so we can parallelise all requests (and not just requests to paged endpoints). This also would make it easier to implement features like request throttling/rate-limitting - this can be done in single place now.

This do work and it does speeds up fetching data - fetching `validRoutes` now is parallelized (and limitted by `concurrentRequests` option)

Tests will fail, as I knowingly didn't spend time on adjusting them - first I'd like to hear opinion on this approach.

@sebastienfi , @tsimons I would appreciate your feedback

### CODE REVIEW

**Comment by KyleAMathews** [comment]
This is awesome! Perhaps we should extract this (eventually — totally cool with this going in as is right now) to a helper library in its own package? I wonder also if there's a generic request queue / limiter we could use for this? It'd be great to find a common pattern that we could document so it's easy to add to additional source plugins.

**Comment by KyleAMathews** [comment]
K, we might as well do our own queue then. It's not a hard problem and we might want a pretty custom API.

**Comment by tsimons** [comment]
Looks great! One thing I don't really like. even from the PR I submitted, is how the queue is initialized/configured. Piggybacking on @KyleAMathews 's idea of making our own queue, what if each step in the gatsby-node file had it's own request queue.

This would make configuration easier since the config is right there. We could also tie in a nice progress bar in the console to show the build progressing. ATM, I can't tell if the build is taking a long time or is hung.

Utilizing different queues would allow more precise config as well. In my recent PRs, the config for better-queue is different between the source-filesystem plugin and the request-in-queue file. This is due to system limitations of different machines. The first problem for me was that my machine maxed out on requests while downloading static files. The second issue arose when I tried to download 10k objects from a Wordpress instance that runs on a potato. I could speed up the build by bumping the concurrency while downloading static files; but then had to lower concurrency when I hit server limits while making dynamic requests.

I definitely like the idea of making this a util found in core, then passing that to all plugins to use when downloading anything.

**Comment by pieh** [comment]
@tsimons @KyleAMathews I created separate issue for discussion about utility package: https://github.com/gatsbyjs/gatsby/issues/4904

let's keep comments here about this PR - if this change seems good I will adjusts tests, so this can go in while we discuss http request queue in dedicated issue

**Comment by pieh** [comment]
I'll close this for now as this is not being actively worked on

**Pull request closed without merging**
