### PR TITLE
chore(gatsby): Update more dependencies to support graphql@14

### PR DESCRIPTION
**Pull request by janicduplessis**
## Description

I noticed a few peer dependencies warning since updating to graphql@14 (#11377), the goal is to fix those by updating some dependencies to the latest version that supports graphql@14. Nothing is broken because of this but this will remove some peer dep warnings.

Verified the changelog of each updated lib to make sure there were no breaking changes affecting us.

## Related Issues

Follow up to PR #11377

### CODE REVIEW

**Comment by RomanGotsiy** [comment]
Looks like broken CI has nothing to do to the changes.

@janicduplessis could you try rebasing this PR?

**Comment by janicduplessis** [comment]
@RomanGotsiy Rebased, tests are now passing

**Comment by RomanGotsiy** [comment]
cc @stefanprobst

**Comment by sidharthachatterjee** [comment]
Published in
```
gatsby-source-graphql@2.0.12
gatsby@2.1.25
```

**Comment by stefanprobst** [comment]
@janicduplessis @RomanGotsiy Unfortunately this had to be reverted because the updated `graphql-tools` does not seem to serialize enums correctly.

**Pull request merged**
