### PR TITLE
chore(docs): Styleguide changes

### PR DESCRIPTION
**Pull request by josephkmh**
## Description

This PR fixes capitalization and punctuation issues in documentation pages starting with "p" and "q".

## Related Issues

Related to #18284

### CODE REVIEW

**Comment by josephkmh** [comment]
@Lennart fixed :-) or at least I hope so!

**Comment by marcysutton** [comment]
Thanks for the PR! I think it needs to be updated again, as there are a few conflicts and the PR introduces a docs JS page that has since been converted to Markdown. Can you take another look at it? (and thanks for your patience!)

**Comment by marcysutton** [comment]
I merged the conflicts and updated from master, we'll see if that clears things up!

**Comment by marcysutton** [comment]
This looked good to me so I merged it in. Thanks so much for the PR!

**Pull request merged**
