### PR TITLE
fix: migrate from request to alternative modules

### PR DESCRIPTION
**Pull request by hoobdeebla**
## Description

Removes request and replaces it with appropriate alternatives, namely [got](/sindresorhus/got/tree/v10.7.0) for gatsby-dev-cli and [node-fetch](https://github.com/node-fetch/node-fetch) for the pipeline integration test.

### Documentation

N/A

## Related Issues

Deprecation notice/reasoning: [request/request#3142](/request/request/issues/3142)
List of alternative libraries: [request/request#3143](/request/request/issues/3143)

### CODE REVIEW

**Comment by hoobdeebla** [comment]
Not sure as to why the Windows check failed. Ran `yarn jest` locally on Windows and in WSL and both had identical results.

**Comment by herecydev** [comment]
Out of interest, why use 2 separate libs?

**Comment by hoobdeebla** [comment]
got was more of a drop-in replacement for gatsby-dev-cli because the error (or lack thereof) is returned in the .then() Promise method; with node-fetch we'd have to explicitly .catch() it or use a try...catch statement. I used node-fetch in the test because the error is not being caught, and the test itself is pretty simple and unlikely to return an error unless the whole test fails, which would mean it's working as intended

**Review by wardpeet — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
