### PR TITLE
Removed dead link to johnm.io

### PR DESCRIPTION
**Pull request by adarshp**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 278147c5405ca6448d479b58901912471eb17b42

https://app.netlify.com/sites/gatsbyjs/deploys/591006368ebdd94e51dd8052

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 278147c5405ca6448d479b58901912471eb17b42

https://app.netlify.com/sites/gatsbygram/deploys/591006368ebdd94e51dd8055

**Comment by Piyush3dB** [comment]
@adarshp johnm.io has actually changed to [http://johnmorris.io/](http://johnmorris.io/), so we can keep this.

**Comment by KyleAMathews** [comment]
@adarshp could you just update the link then instead of removing it?

**Comment by adarshp** [comment]
Will do.

**Comment by KyleAMathews** [comment]
Merged this PR instead https://github.com/gatsbyjs/gatsby/pull/947

**Pull request closed without merging**
