### PR TITLE
Travis config update

### PR DESCRIPTION
**Pull request by m-allanson**
Speed up Travis CI runs by setting jobs to run in parallel instead of sequentially.

This also splits linting out to a separate job from unit testing, and unit testing is now run on Node 6, 8 and 10.

Refs #7792

### CODE REVIEW

**Comment by m-allanson** [comment]
```
Ran for 6 min 58 sec          <--- how long the CI run took to finish
Total time 26 min 42 sec      <--- cumulative total time taken by all jobs
```

**Comment by KyleAMathews** [comment]
Hmmm maybe that's just the "total" time for all jobs? Perhaps restart the job and watch for when they all finish?

This seems promising!

**Comment by pieh** [comment]
Current `stages` are definitely run serially (first unit-tests, then integration tests, then gatsbygram dev cypress and then production cypress). 

I'll restart suite for that and watch if they run in parallel

**Comment by pieh** [comment]
So it seems this does run somewhat in parallel - it's just it runs 3 tests at most right now (either open source plan limitation or not enough workers available?):

screen shot 2018-09-03 at 14 35 00
---
screen shot 2018-09-03 at 14 37 33
---
screen shot 2018-09-03 at 14 38 43

**Comment by KyleAMathews** [comment]
Let's merge it then!

**Pull request merged**
