### PR TITLE
Cleanup doc code (async / await usage)

### PR DESCRIPTION
**Pull request by reconbot**
- unnecessary promise creation
- uncaught error if `graphql()` throws (eg a bad query) or if graphql doesn't return a promise because all of it's resolvers are sync.

### CODE REVIEW

**Comment by pieh** [comment]
async/await is not available in node 6 which Gatsby still supports. But we could get away from creating explicit `new Promise` and chain `then` from `graphql` function

**Comment by pieh** [comment]
> I saw async being used in other docs... 

Then we need either to update docs or annotate that it needs node 8. Here's what I found searching for `await` in `docs`:
- https://next.gatsbyjs.org/docs/create-source-plugin/ ( `const data = await fetch(REMOTE_API)` )
- https://next.gatsbyjs.org/blog/2017-10-01-migrating-my-blog-from-hexo-to-gatsby/ (commented it needs node 8)

**Comment by pieh** [comment]
I'd say blog post is fine as is. If you are up for it, `create-source-plugin` doc could be changed from `await` to using `then` as source plugins are more likely to be used by more people.

**Comment by KyleAMathews** [comment]
Thanks for the efforts here @reconbot! We'll be updating everything to use async/await next year when Node 6 is EOLed!

**Pull request closed without merging**
