### PR TITLE
feat(gatsby-plugin-sharp): cache image metadata

### PR DESCRIPTION
**Pull request by ascorbic**
## Description

Caches image metadata between builds

### Documentation

Currently gatsby-plugin-sharp uses an in-memory cache to store image metadata during a build, but it is not persisted between builds. This means that the relatively expensive dominant color calculations need to be re-done each time. This PR switches to use the `GatsbyCache` if it is available, falling back to the in-memory cache otherwise. In my tests, this saved over a minute for warm-cache builds of a site with 100 images.

### CODE REVIEW

**Review by pieh — DISMISSED** [review]
Nice!

**Comment by ascorbic** [comment]
Thanks! I'll investigate what's going on with the development runtime tests and see if I can reproduce locally

**Comment by ascorbic** [comment]
They're all failing on `hot-reloading/new-file.js`, which seems unlikely to be related

**Comment by LekoArts** [comment]
Yeah, `hot-reloading/new-file.js` is unrelated, I fixed this in https://github.com/gatsbyjs/gatsby/pull/35730/files#diff-b1afd70a3b70f0af3ded5b10840884a6563ba768424b5390b9dcf0ffac753ccf

**Comment by ascorbic** [comment]
Aha. Another PR [failing with the same test](https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/83014/workflows/e0ada300-0d82-4c42-b875-04b5192c809e/jobs/988699). Must be unrelated.

**Comment by LekoArts** [comment]
But in https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/82992/workflows/a0fe5b63-96e0-491f-ae20-9b68f4732e5d/jobs/988774 the `gatsby-plugin-image.js` one fails

**Comment by ascorbic** [comment]
Hah. Jinx. OK, so should this wait til that fix lands?

**Comment by LekoArts** [comment]
Published at `next` 👍

**Comment by ascorbic** [comment]
I have another optimisation coming in shortly

**Comment by ascorbic** [comment]
@LekoArts https://github.com/gatsbyjs/gatsby/pull/35814

**Pull request merged**
