### PR TITLE
Add my homepage to the showcase

### PR DESCRIPTION
**Pull request by azer**
I loved using Gatsby to build my new website. Excellent tool! I'm hoping to write a blog post about it soon.

This is a tiny commit for adding [azer.bike](http://azer.bike) to the showcase list in the README.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 084245eecc65aa51b870b23ba8bdb5e6c69d0982

https://app.netlify.com/sites/using-glamor/deploys/59d8e8fcdf9953586186c37e

**Comment by KyleAMathews** [comment]
Woah, gorgeous! Love the typography 😍 

BTW, have you see https://www.gatsbyjs.org/packages/gatsby-image/ ? It's quite new but I'd love to hear reports on using it from the "wild". It'd be a great fit I think for your photography section.

**Comment by azer** [comment]
@KyleAMathews Thank you! The image package seems perfect btw, I'll try it.

**Comment by fk** [comment]
Merhaba @azer! Thanks for sharing – beautiful work on the website, and amazing photography! http://roadbeats.com/ on Gatsby next? 😋

**Comment by azer** [comment]
@fk that's exactly what I'm planning :+1:

**Comment by jlengstorf** [comment]
Hiya @azer! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
