### PR TITLE
upgrade really compiler and use their printer

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 76894400f2dc095e85c1f86a0782cd81fba2a534

https://app.netlify.com/sites/using-glamor/deploys/59f9e185a6188f7a853869c0

**Comment by KyleAMathews** [comment]
appveyor failed building Gatsbygram

```
error GraphQLIRPrinter: Need an InputObject type to print objects.
  Error: Invariant Violation: GraphQLIRPrinter: Need an InputObject type to prin  t objects.
  
  - invariant.js:42 invariant
    [gatsby]/[fbjs]/lib/invariant.js:42:15
  
  - GraphQLIRPrinter.js:168 printValue
    [gatsby]/[relay-compiler]/lib/GraphQLIRPrinter.js:168:34
  
  - GraphQLIRPrinter.js:156 
    [gatsby]/[relay-compiler]/lib/GraphQLIRPrinter.js:156:24
  
  - Array.forEach
  
  - GraphQLIRPrinter.js:155 printArguments
    [gatsby]/[relay-compiler]/lib/GraphQLIRPrinter.js:155:8
  
  - GraphQLIRPrinter.js:58 printField
    [gatsby]/[relay-compiler]/lib/GraphQLIRPrinter.js:58:81
  
  - GraphQLIRPrinter.js:65 printSelection
    [gatsby]/[relay-compiler]/lib/GraphQLIRPrinter.js:65:11
  
  - GraphQLIRPrinter.js:47 
    [gatsby]/[relay-compiler]/lib/GraphQLIRPrinter.js:47:12
  
  - Array.map
  
  - GraphQLIRPrinter.js:46 printSelections
    [gatsby]/[relay-compiler]/lib/GraphQLIRPrinter.js:46:28
  
  - GraphQLIRPrinter.js:35 print
    [gatsby]/[relay-compiler]/lib/GraphQLIRPrinter.js:35:135
  
```

Also run `npm run format`

**Comment by KyleAMathews** [comment]
Will be nice to get back on latest GraphQL — starting to see GraphQL version mis-matches crop up in the wild again 🤦‍♂️

**Comment by jquense** [comment]
The error here is due to the lock file in gatsbygram set for gatsby@latest, when it's removed and the  local version is replaced it breaks. 

The error here is actually just a "you have duplicate graphql" instances, which is annnooooooying

**Comment by KyleAMathews** [comment]
:-| yeah annoying :-(

Ok, will merge

**Comment by jquense** [comment]
btw that problem would go away if we added the examples to the workspace

**Comment by KyleAMathews** [comment]
Getting this error on new installs of the default/blog starter

```
⠁ TypeError: transform is not a function
    at /private/tmp/bll/blog/node_modules/relay-compiler/lib/ASTConvert.js:106:12
    at Array.map (<anonymous>)
    at convertASTDefinitions (/private/tmp/bll/blog/node_modules/relay-compiler/lib/ASTConvert.js:105:31)
    at Object.convertASTDocuments (/private/tmp/bll/blog/node_modules/relay-compiler/lib/ASTConvert.js:39:10)
    at Runner._callee3$ (/private/tmp/bll/blog/node_modules/gatsby/dist/internal-plugins/query-runner/query-compiler.js:262:77)
    at tryCatch (/private/tmp/bll/blog/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/private/tmp/bll/blog/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/private/tmp/bll/blog/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/private/tmp/bll/blog/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /private/tmp/bll/blog/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/private/tmp/bll/blog/node_modules/core-js/library/modules/es6.promise.js:171:7)
    at Runner.<anonymous> (/private/tmp/bll/blog/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Runner.write (/private/tmp/bll/blog/node_modules/gatsby/dist/internal-plugins/query-runner/query-compiler.js:312:20)
    at Runner._callee$ (/private/tmp/bll/blog/node_modules/gatsby/dist/internal-plugins/query-runner/query-compiler.js:105:27)
    at tryCatch (/private/tmp/bll/blog/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/private/tmp/bll/blog/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/private/tmp/bll/blog/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/private/tmp/bll/blog/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /private/tmp/bll/blog/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at run (/private/tmp/bll/blog/node_modules/core-js/library/modules/es6.promise.js:66:22)
    at /private/tmp/bll/blog/node_modules/core-js/library/modules/es6.promise.js:79:30
    at flush (/private/tmp/bll/blog/node_modules/core-js/library/modules/_microtask.js:18:9)
```

**Comment by KyleAMathews** [comment]
This line needs two more arguments https://github.com/gatsbyjs/gatsby/blob/2f92d30dadd100a42208c5466eaf979322816a12/packages/gatsby/src/internal-plugins/query-runner/query-compiler.js#L128

**Comment by KyleAMathews** [comment]
Well one more, some sort of "transform" function

**Comment by jquense** [comment]
hmm why didn't i see this...

**Pull request merged**
