### PR TITLE
chore(showcase): add ellingtonhammond.com

### PR DESCRIPTION
**Pull request by PHironaka**

### CODE REVIEW

**Comment by muescha** [comment]
i got a 404

should is not be more with a dash?

https://ellington-hammond.com/

**Comment by muescha** [comment]
fixed in #25528 `fix(showcase): 404 link ellingtonhammond.com -> ellington-hammond.com`

**Comment by PHironaka** [comment]
sorry about that, thank you @muescha

**Comment by muescha** [comment]
@PHironaka no problem 
u r welcome :)

**Pull request merged**
