### PR TITLE
fix: dont remove query declaration hash, terser will remove it anyway and it can be useful for 3rd party tools

### PR DESCRIPTION
**Pull request by jfrolich**
I have some generated code (bucklescript/graphql_ppx) whereby the reference of the query is used in another data structure (which is also unused, but it is still referenced). So if this is removed from the code Gatsby won't build. I think removing this shouldn't need to happen in the babel plugin as it will happen anyway in the dead code removal of webpack (I believe).

### CODE REVIEW

**Comment by blainekasten** [comment]
Hey @jfrolich, looks like some tests are breaking.

**Comment by jfrolich** [comment]
Yes I didn't update the snapshots yet. Fixed now.

**Comment by pieh** [comment]
Do you have any public project that we could take a look at where babel plugin removing this stuff is problematic?

I don't really like how this impact things and wonder if we can come up with some alternative approaches here

**Comment by jfrolich** [comment]
Yes. To do GraphQL in ReasonML you generally use [GraphQL PPX Re](https://github.com/baransu/graphql_ppx_re), it basically offers fully typed GraphQL using the schema. I've been building a Gatsby integration for ReasonML/Bucklescript, and got it working with a PR to Gatsby some time ago (https://github.com/gatsbyjs/gatsby/pull/20330). But I didn't test it in production yet, and that's when this blocked successful compilation.

In my previous pull request I also added the capability of following reassignments to the graphql query. I think removing the initial assignment is also breaking this (and is better to leave it to dead-code elimination later in the process IMO).

**Comment by jfrolich** [comment]
To further elaborate. GraphQL PPX Re will create (among other things) a query definition, which consist of the query itself and a parse function. The parse function will parse the GraphQL result data to ReasonML data types. We don't need the definition but it's still getting generated. So if the definition of the query itself is being wiped out we get a parse error.

**Comment by pieh** [comment]
Let's test if webpack actually will remove it - if it does then I will be ok with this change

One thing that escaped me initially is that this change targets just static queries, and page queries in master are not actually being removed, as in - we keep the hash assignment for them (which can be seen with those snapshot tests):
https://github.com/gatsbyjs/gatsby/blob/620db5b3dcfef6ef5bda3ffd3d7266213b0b395a/packages/babel-plugin-remove-graphql-queries/src/__tests__/index.js#L238-L248
https://github.com/gatsbyjs/gatsby/blob/620db5b3dcfef6ef5bda3ffd3d7266213b0b395a/packages/babel-plugin-remove-graphql-queries/src/__tests__/__snapshots__/index.js.snap#L156

**Comment by jfrolich** [comment]
I think the best approach is to validate if it the binding is being referenced by something else and if not delete it (like before).

**Comment by jfrolich** [comment]
> One thing that escaped me initially is that this change targets just static queries, and page queries in master are not actually being removed, as in - we keep the hash assignment for them (which can be seen with those snapshot tests):

Ahh ok so that is indeed inconsistent. Not a big deal because it's just a number, so it's not adding much in terms of bundle size, but still inconsistent.

**Comment by jfrolich** [comment]
Cool thanks. Didn't have much time to follow up on this, but this will save a patch-package dependency on https://github.com/jfrolich/reason-gatsby.

**Comment by blainekasten** [comment]
@jfrolich unfortunately it turns out this change is incompatible with React FastRefresh. I can go into the depths of it, but the tl;dr is that file changes scan the parent modules for usages of its dependencies. If it can't find one it's not known to be safe to hot module replace.

Since these queries are exported, but not used by any module in the stack it creates this problem for FastRefresh. 

The only solution I can think of is to add a special pragma marker to keep this export around. Something like:

```js
// gatsby-preserve-export
export const query = graphql``
```

How do you feel about this or do you have any ideas for other work arounds?

**Comment by pieh** [comment]
I guess question here is if those need to be exports. https://github.com/gatsbyjs/gatsby/pull/26664 right now just drop `export` keyword from page queries declaration. The hash and identifier itself stays, so it might be fine for Reason integration?

**Comment by pieh** [comment]
I tried using fast-refresh branch on https://github.com/jfrolich/reason-gatsby-starter-blog and few notes:

1. Babel plugin changes in the PR doesn't seem to impact tooling - it still can figure out types for query results
2. But the hot refresh with fast-refresh doesn't work - it seems something in the chain re-add `query` to export list on top of plenty more exports which make fast-refresh not work:
```js
/***/ "./src/templates/BlogPost.bs.js":
/*!**************************************!*\
  !*** ./src/templates/BlogPost.bs.js ***!
  \**************************************/
/*! exports provided: Raw, query, parse, serialize, serializeVariables, makeVariables, make, $$default, default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* WEBPACK VAR INJECTION */(function(__react_refresh_utils__, __react_refresh_error_overlay__) {/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "Raw", function() { return Raw; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "query", function() { return query; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "parse", function() { return parse; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "serialize", function() { return serialize; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "serializeVariables", function() { return serializeVariables; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "makeVariables", function() { return makeVariables; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "make", function() { return make; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "$$default", function() { return $$default; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return $$default; });
```

For comparison this is regular blog starter:
```js
/***/ "./src/templates/blog-post.js":
/*!************************************!*\
  !*** ./src/templates/blog-post.js ***!
  \************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* WEBPACK VAR INJECTION */(function(__react_refresh_utils__, __react_refresh_error_overlay__) {/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ "./node_modules/react/index.js");
// [...]
/* harmony default export */ __webpack_exports__["default"] = (BlogPostTemplate);
```

It feels like quickest workaround would be to force `react-hot-loader` for reason integration for now? I'm not sure how gatsby specific all those extra exports are and if those exports might be just how react + reason is supposed to work?

**Comment by pieh** [comment]
Hah https://github.com/reasonml/reason-react/issues/549 might be relevant ;)

**Comment by jfrolich** [comment]
I think just dropping the export would be fine!

**Comment by blainekasten** [comment]
Thanks for the feedback and help here y'all! Glad to know It's safe to move forward

**Comment by jfrolich** [comment]
I'll test and update the starter so it works with fast-refresh!

**Pull request merged**
