### PR TITLE
add tests to gatsby-remark-images

### PR DESCRIPTION
**Pull request by DSchau**
Added some basic unit tests (and snapshots) to gatsby-remark-images

Note: there's probably more we can do here, but it's a start! Let me know how it looks

One thing I may want to do is re-run prettier on the code base, so I can do that too

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 3a3074d5344d21266b1f7375a841441ea52cc772

https://app.netlify.com/sites/gatsbygram/deploys/596f8b1ba700c44c45258ece

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 3a3074d5344d21266b1f7375a841441ea52cc772

https://app.netlify.com/sites/using-contentful/deploys/596f8b1ca700c44c45258ee6

**Comment by KyleAMathews** [comment]
Tests! Nice! The tests look spot on. Snapshots are perfect for this sort of thing.

Yeah, running `npm run format` when committing is great. We need to enforce that.

**Comment by DSchau** [comment]
Re-ran prettier! Let me know if you want me to squash those into one commit or something, otherwise I think this stuff is good to go

**Comment by KyleAMathews** [comment]
Awesome! Merging

**Comment by KyleAMathews** [comment]
I always squash so no worries there :-)

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 6d6561648a29a4392fc1fe4ccd4a7824d6a8009d

https://app.netlify.com/sites/image-processing/deploys/596fa49a7960b12ad84b44b0

**Pull request merged**
