### PR TITLE
GraphCMS source plugin and usage example

### PR DESCRIPTION
**Pull request by rafacm**
GraphCMS source plugin and usage example

1. Includes commits from PR #1867 by @Redmega
1. Updated the gatsby-source-graphcms plugin documentation and added "Current limitations" section
1. Added usage example in examples/using-graphcms
1. Added logic in gatsby-source-graphcms to fail processing if GraphQL query is not passed in configuration

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit d02fc43b224f92ef15b76bb75efffe6dbf19a40e

https://app.netlify.com/sites/using-glamor/deploys/59e0b814a6188f1e35a76acb

**Comment by corysimmons** [comment]
@KyleAMathews Anything holding this up?

**Comment by Redmega** [comment]
Issue number 2 in PR #1867 is holding it back. The data isn't found by graphql at build time, despite all the data being pulled in. It might be a simple change to the way `createNode` is being called -- I haven't had a chance to look at it yet.

There is chat going on in the `#gatsby` channel at https://graphcms.slack.com

**Comment by rdela** [comment]
Hey @KyleAMathews getting ready to update this PR, we encountered a similar issue to #1808 gatsby-plugin-feed error testing and developing: https://github.com/hmeissner/gatsby-graphcms-testing/pull/1
Tons of `Error: Couldn't find preset "env" relative to directory`
So I added `babel-preset-env` as a dev dependency and changed node presets env targets from `9` to `current` in plugin .babelrc ([where we also request transform-object-rest-spread plugin](https://github.com/hmeissner/gatsby-graphcms-testing/blob/master/plugins/gatsby-source-graphcms/.babelrc)) which seems to resolve local plugin build issues on different node versions. Looking into the gatsby-plugin-feed issue I see that plugin uses Gatsby’s .babelrc.js and passes browser: true https://github.com/gatsbyjs/gatsby/blob/f9b0870da9ed5f5455789e70e9d57ac32294cab2/packages/gatsby-plugin-feed/.babelrc#L3

What do we want to do here ideally? What should we rely on Gatsby babel setup for and what dependencies do we need in the [plugin package.json](https://github.com/hmeissner/gatsby-graphcms-testing/blob/2680efb94c53f5d22166087b352b2a2a86c99c11/plugins/gatsby-source-graphcms/package.json#L14-L26)?

Is anything we have in here redundant? Looks like spread support goes back to [node 5.12 unflagged](http://node.green/#ES2017-features-Object-static-methods-Object-entries)? But a build with Gatsby might end up targeting 4.0?
https://github.com/gatsbyjs/gatsby/blob/f9b0870da9ed5f5455789e70e9d57ac32294cab2/.babelrc.js#L21

Here is how @hmeissner summed up current confusion in Slack chat:
> Is this because gatsby with it’s own babel setup simply takes care of this for you during the build hence the babel setup in the plugin itself only contributes to local usage of the plugin?

**Comment by KyleAMathews** [comment]
Check out the recommended package format here: https://github.com/gatsbyjs/gatsby/tree/master/plop-templates/package

Also make sure you run yarn bootstrap from the root of the repo before testing. See the contributor instructions https://www.gatsbyjs.org/docs/how-to-contribute/#contributing

**Comment by rdela** [comment]
Thanks Kyle. Will look though both.

**Comment by rdela** [comment]
Do I need to worry about the `yarn.lock` conflict at this point? Or will that get resolved with later merge or rebase?

**Comment by rdela** [comment]
So I built the plugin in this working tree (still no `.babelrc`) and only `babel-cli` and `babel-plugin-transform-runtime` in `devDependencies` and then set up example site with that build and all looks good so moving on to updating example

**Comment by rdela** [comment]
I removed `"gatsby-source-graphcms": "0.0.1"` from example/using-graphcms `package.json` during testing, let me know whether I need to add it back or can hold off til merge

**Comment by rdela** [comment]
Hmm `yarn format-examples` may have mangled the jsx in the example index, let me investigate

**Comment by rdela** [comment]
Ok I am still stumbling around in the dark with yarn but example code seems to have survived `yarn format-examples`

Going to add recommended `.babelrc` and see what, if any, impact that has on builds

**Comment by rdela** [comment]
Ok @KyleAMathews think this is ready for your eyes, AWS CodeBuild succeeded at least

**Comment by rdela** [comment]
By gatsby-source-graphcms-plugin devDep combo in that last commit msg I __mean__ babel-plugin-transform-object-rest-spread (in) devDep combo

**Comment by rdela** [comment]
Confused about what Babel needs to cover all cases and what is extraneous and unsure whether we have everything here to roll this out, but this is everything I could think to do tonight without more insight, feel free to modify anything I have done here so far

**Comment by rdela** [comment]
AWS CodeBuild succeeded for second or third time running so not sure whether any of the last few commits or presence or content of .babelrc make any difference to builds on my system.

Earlier this .babelrc resolved a build issue for me but may be moot now or need to be swapped for recommended package format style .babelrc: https://github.com/gatsbyjs/gatsby/blob/master/plop-templates/package/.babelrc.hbs

Or deleted?https://github.com/gatsbyjs/gatsby/pull/2445/commits/bf476132533cc24a9cf879b1f3bcb92f56d60859

```
Some more changes to bring this more in line and conform with
existing source plugins and ditch cruft/hopefully appease build
servers. All other source plugins…

- do not have a .babelrc
- have babel-runtime in dependencies not devDependencies
- have "prepublish": "cross-env NODE_ENV=production npm run build"
  in scripts
```

Travis seems stuck and netlify build is failing, but think that may be unsatisfied dep for 0.0.1 of this plugin in example. Curious what are real issues and need attention and what will resolve once published.

**Comment by rdela** [comment]
I guess I need to read up on Lerna hoisting to figure out Babel dev/production logic in Gatsby

**Comment by rdela** [comment]
@KyleAMathews what do you need me to do here? Fix something specific? Merge current master into this branch? Get @Redmega to reopen PR #1867? @hmeissner or me open a new PR with clean tree based on current? We are working on new features but dev is getting splintered with https://github.com/hmeissner/gatsby-graphcms-testing being more up to date and approachable. With so many different people having now committed to the brach over 2 PRs and not knowing `lerna` or build setups I am a little lost. I wrote in Slack:

**Comment by rdela** [comment]
I guess 3c5df69 was last successful build on Oct 13 https://github.com/gatsbyjs/gatsby/pull/2445#commits-pushed-c96c236

**Comment by KyleAMathews** [comment]
Hey! First thanks for all the great work here! Sorry about the confusion AWS CodeBuild is causing — I'm working on a new testing tool and it's a WIP still so giving weird results.

I've been thinking too lately that our experiment in putting lots of plugins in this repo is getting unwieldy — I'm reaching my limits for how much maintenance I can do.

How about you put this in your own repo or perhaps a GraphQLCMS repo?

A community member is working on a design for a new plugins page that'll make it really easy to browse/search plugins so it won't be that big of deal anymore which repo plugins come from.

Thoughts?

**Comment by Redmega** [comment]
I definitely don't have a problem hosting this repo on my own github and publishing to npm separately. I can work on that after work tonight if everyone thinks we're ready to go live with `0.0.1`.

**Comment by Redmega** [comment]
@KyleAMathews We're going to host it in the @graphcms org.

**Comment by KyleAMathews** [comment]
Sweet!!

**Comment by rdela** [comment]
Yeah I am super pro all these things @Redmega and @KyleAMathews thank you both let’s close this please!

**Comment by rdela** [comment]
Or we can wait until 0.0.1 is on npm and then add comment here before closing whatever is clever

**Comment by rdela** [comment]
live under @GraphCMS org https://github.com/GraphCMS/gatsby-source-graphcms

**Comment by rdela** [comment]
@corysimmons please let us know if you want to be more involved or have thoughts on alpha https://github.com/GraphCMS/gatsby-source-graphcms / https://github.com/hmeissner/gatsby-graphcms-testing/pull/2

**Comment by rafacm** [comment]
> @KyleAMathews said:
> I've been thinking too lately that our experiment in putting lots of plugins in this repo is 
> getting unwieldy — I'm reaching my limits for how much maintenance I can do.

New repo created at https://github.com/GraphCMS/gatsby-source-graphcms and all commits for this PR pushed there.

**Pull request closed without merging**
