### PR TITLE
[www] Sidebar: Add "Expand/Collapse All" button, store state in localStorage

### LINKED ISSUE #6210: [www] IA redesign: Store expanded/collapsed accordion state in local storage/cookie
(Following up on #6153) This issue is about dropping the current "auto-close non-active accordion" behavior altogether in favor of saving the expanded/collapsed state of the accordions in local storage or a cookie.

If a user had all accordions expanded, he would be able to return to that state even when starting a new "browsing session". We'd only override the saved state regarding the default section: When navigating to /docs/, the "Quick Start" section should always be expanded so the initially selected navigation item is always visible, even if the user previously chose to collapse that accordion.

### LINKED ISSUE #6500: [www] IA redesign: Add "Expand/collapse all" button
To be able to get a quick overview of all content in the "Docs" sidebar (https://next.gatsbyjs.org/docs/), we discussed adding an "Expand/collapse all sidebar accordions" button. This button would

* initially expand all accordions
* on second click collapse all accordions but the accordion that contains the currently active page

`ww/src/components/sidebar/body.js` already contains the "expand all" [button](https://github.com/gatsbyjs/gatsby/blob/4484b14be6af16cac877805d6ee65958138d376c/www/src/components/sidebar/body.js#L8-L35); the "collapse all but the accordion with the currently active item" functionality is still missing.

### PR DESCRIPTION
**Pull request by fk**
Fixes #6500, fixes #6210.
Preview: https://happy-yonath-7796ac.netlify.com/docs/

Adds a "Expand/Collapse All" button; icons are "[Fold](https://octicons.github.com/icon/fold/)" and "[Unfold](https://octicons.github.com/icon/unfold/)" from GitHub's [Octicons](https://octicons.github.com/).
The button

* if one or more accordions are collapsed, expands all accordions, or
* if all accordions are expanded, collapses all accordions but the possible parents of the currently active page.

Also, this now creates, updates and reads three local storage items persisting the expanded/collapsed state:

* `gatsbyjs:sidebar:docs`
* `gatsbyjs:sidebar:tutorial`
* `gatsbyjs:sidebar:features`

The state saved in local storage is overridden to ensure that the currently active sidebar item is visible: E.g. when navigating to https://happy-yonath-7796ac.netlify.com/docs/deploy-gatsby/, both "Guides" and "Deploying & Hosting" will be expanded, even if the user previously chose to collapse those accordions and that state was saved in local storage.

/cc @shannonbux @KyleAMathews @calcsam

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 806985b2ce71045b47a590d4f2596237ad045f64

https://app.netlify.com/sites/using-postcss-sass/deploys/5b65e63573f2cf31d04f7733

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 8599768328a8a407e5e040484e5de0acf5de91eb

https://app.netlify.com/sites/gatsbyjs/deploys/5b6744cb4ed62f54bbf8609a

**Comment by KyleAMathews** [comment]
Deploy preview for *using-remark* failed.

Built with commit e3a76cfaa3cdd2a735829dd645a370e1ee4f0682

https://app.netlify.com/sites/using-remark/deploys/5b677f01b13fb14313a569b1

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit 4a4e38cac6a27f1dbdd121d6adc0f7d08103e09c

https://app.netlify.com/sites/using-contentful/deploys/5b679189b31274133479776c

**Comment by shannonbux** [comment]
This looks awesome, @fk!

**Comment by calcsam** [comment]
@fk this is just gorgeous

**Pull request merged**
