### PR TITLE
absolute css asset loading (fixes #310)

### LINKED ISSUE #310: CSS-included Assets not loading on all routes
I'm using semantic ui framework which requires icon font files. This works on every route in development.

After building, the icons load fine on root url, but if you refresh or visit on a different route, the icons are 404ing - as they're trying to load relatively.

### PR DESCRIPTION
**Pull request by hitchcott**
fixes https://github.com/gatsbyjs/gatsby/issues/310 using https://github.com/webpack/css-loader/issues/113

NPM tests passed, and it works in my project.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
After some research, agree this looks like the right fix. One quick improvement though before I can merge — please wrap the `/` with the [`prefixLink`](https://github.com/gatsbyjs/gatsby#deploying-to-github-pages-and-other-hosts-where-your-sites-links-need-prefixes) helper so that this will work when people are building for Github Pages or other places where their absolute links aren't relative to the domain root.

Thanks!

**Comment by KyleAMathews** [comment]
Hrmm... playing with this a bit and staring at test failures I realized we can't use the `prefixLink` helper here as it tries to import the `config.toml` file which can only be done by Webpack not Node... sigh :-(

So I guess this will be a WTF for any poor sap who needs the publicPath set correctly on his CSS and is building a site with prefixed links. The main solution I see is moving config to a plain js module (which has other advantages as well namely being able to use logic for setting config + responding to env variables).

**Comment by KyleAMathews** [comment]
Published v0.11.4 with this PR, thanks!

**Comment by jlengstorf** [comment]
Hiya @hitchcott! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
