### PR TITLE
Adding page transitions animation  in Gatsby.js  article to Awesome G…

### PR DESCRIPTION
**Pull request by ronthomas345**
…atsby

Adding page transitions animation  in Gatsby.js  article to Awesome Gatsby

### CODE REVIEW

**Comment by ronthomas345** [comment]
@jlengstorf , please review

**Comment by DSchau** [comment]
@ronthomas345 I actually reviewed--could you take a look at the feedback?

**Comment by ronthomas345** [comment]
Hi @DSchau : Please review https://github.com/gatsbyjs/gatsby/pull/13373 and if it is OK, I will close  this PR.

**Comment by DSchau** [comment]
Let's close in favor of #13373; thanks!

**Pull request closed without merging**
