### PR TITLE
Create an Integration Test for the default Gatsby Wrappers

### PR DESCRIPTION
**Pull request by benstepp**
* Add `npm run setup` to setup symlinks for the test suite.
* Add a note about `npm run setup` in CONTRIBUTING
* Add `npm run test-integration` to run the slower tests.
* Added a `test/support.js` to put common testing functions

---

Not too sure on this one. I'm fairly certain either I broke the static wrappers on my last commit, or they were never being used (as all of the starters implement a markdown-wrapper, and I don't think anybody is writing html). I even tried deleting the wrapper in the gatsby-starter-blog, building with `gatsby build` using an older gatsby, and checked to verify that there was no content on the page.

For test fixtures the general Idea is to symlink the `node_modules` folder at the root into each `test/fixtures` directory. Add a `node_modules/gatsby` folder with a `dist` folder and a `package.json` (the bare minimum for node to treat it as a real package). The dist/package.json symlink back to the top level items. On test run, the project is built using `npm run build` (to get a new dist folder) and then the tests are run.

I felt like I wrote a lot of spaghetti, but I think the most important pieces (like the test cases) are easy to follow. Let me know if there are any ideas to improve this implementation. I like the idea of very focused fixtures, it's pretty cool to see how little you actually need to setup a gatsby site.

### CODE REVIEW

**Comment by benstepp** [comment]
`jsdom` [not supported on old node](https://github.com/tmpvar/jsdom#install)

Know of any other alternatives?

**Comment by KyleAMathews** [comment]
Cheerio is great https://github.com/cheeriojs/cheerio

**Comment by benstepp** [comment]
```
Error: Gatsby 0.9+ requires node.js v0.12 or higher (you have v0.12.13) Upgrade node to the latest stable release. 
```

Found a bug just by trying to run the executable. Tests are too strong. If nobody has even reported this error, is it even worth supporting v0.12. 

I'll grab some old node docker containers and play around with it tomorrow.

**Comment by benstepp** [comment]
Added a test case for running the cli (because it was broken on 0.12 and threw an error when it should not have) and this would give a failing test to quickly fix. Would it be better to just remove this version parsing logic and just rely on the `engines` section of `package.json`?

Added a couple more cases to test the behavior of returning help when called both without arguments and with an unknown command.

Building a two page fixture takes twice as long on v0.12 ☹️

**Comment by KyleAMathews** [comment]
Just using `engines` makes a lot of sense :-)

One advantage to the version parsing is we can have custom errors. Perhaps use both?

To your earlier question — I'm ok supporting 0.12 as long as it doesn't prove a support burden. So far it hasn't but we'll see.

I've had a quick look through  your commits. They look really awesome :-) Super glad you decided to take this on.

One the core wrappers — I'm pretty sure I broke them. Mostly because I've been ignoring them as I regret that they're in core at all... I'm going to write up my ideas for the plugin api but very high-level is the core wrappers and loaders will soon be moved out into plugins.

**Comment by KyleAMathews** [comment]
@benstepp I'm going to be working on Gatsby some tomorrow. Is there anything more you wanted to finish up here before I review/merge it in?

**Comment by benstepp** [comment]
I think this PR is good now. I found a way to vastly simplify the cli testing process using `babel-node`. The whole symlinking idea was a good concept, but after talking with a friend we came to the conclusion that it adds a lot of complexity with no real benefits. 

The really big holes in tests right now are the create-routes and post-build stages, but I'm not sure that it is worth unit testing create-routes if the end goal is to refactor it in order to bypass react-router matching.

**Comment by KyleAMathews** [comment]
Awesome work @benstepp! Thanks for the care you've put into this.

**Comment by KyleAMathews** [comment]
Yeah, unit tests are needed for create-routes but yes, let's add them as part of the refactor to bypass react-router matching.

**Pull request merged**
