### PR TITLE
Introduce HJson transformer

### PR DESCRIPTION
**Pull request by barraq**
# Description

This PR introduces support for http://hjson.org/

> Hjson is a syntax extension to JSON. It's NOT a proposal to replace JSON or to incorporate it into the JSON spec itself. It's intended to be used like a user interface for humans, to read and edit before passing the JSON data to the machine.

This Gatsby transformer is an adaptation of the `gatsby-transformer-json` plugin. Nothing fancy: all credits goes to `gatsby-transformer-json`.

**Note**: @KyleAMathews a linting issue (see https://github.com/gatsbyjs/gatsby/commit/c2804726b367f40769e461647e950b8e5e6c1222#diff-346c3005d97c1ca0b5efb170af1b43f6) was introduced by previous commits and trigger this error:
```
/home/travis/build/akadop/gatsby/packages/gatsby/src/commands/develop.js
  206:7  error  'listener' is assigned a value but never used  no-unused-vars
```

This is fixed by https://github.com/gatsbyjs/gatsby/pull/3034

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 9356ecf52079f45c6907174556f033395fc3fd59

https://app.netlify.com/sites/using-glamor/deploys/5a1ac4ebdf99531153c72bc5

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 60102023fc9295bf87179e121b3b72f770e163d4

https://app.netlify.com/sites/using-glamor/deploys/5a1ac583a11477483ae5b725

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 1475e6cfef17083976731c1da4ccbb0a240d20b2

https://app.netlify.com/sites/using-glamor/deploys/5a1ade4aa1147733e5e5b76e

**Comment by barraq** [comment]
@KyleAMathews one question: in `gatsby-transformer-json` where exactly are the GraphQL schema generated? e.g. `allLetterJson` for instance? cause at the moment the schema for `gatsby-transformer-hjson` are not generated and therefore I do not see them in GraphiQL. What should I change and where? thanks for your help

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 6291fe7596b6aec71499aa36c33c256e70b86ca9

https://app.netlify.com/sites/using-glamor/deploys/5a1ae409a6188f304d8c6764

**Comment by calcsam** [comment]
Does it look right for you in GraphiQL now that your other PR has been merged? If so, then we're good to go on this PR.

**Comment by barraq** [comment]
@calcsam nope, the schema is still not loaded in GraphiQL. I am actually curious on this schema should be created? I looked at `gatsby-transformer-json` or `gatsby-transformer-yaml` and there is nothing they do I don't... I am missing something but I don't know what. Do you know by any chance how and what is generating those schema?

In my tests site, I have the following:

```
plugins: [
    'gatsby-plugin-react-helmet',

    // Transformer plugins
    'gatsby-transformer-hjson',
    'gatsby-transformer-json',

    {
      resolve: 'gatsby-source-filesystem',
      options: {
        name: 'data',
        path: `${__dirname}/data/`,
      },
    },
  ],
```

In `data` I have `a.hsjon` and `b.json`, when starting `gatsby develop` I can see the `allDataJson` and `allJson` schema, but not `allDataHJson` nor `allHJson`

**Comment by calcsam** [comment]
Are you using `gatsby-dev-cli` to pick up local changes to gatsby?

https://www.gatsbyjs.org/docs/how-to-contribute/
https://www.gatsbyjs.org/packages/gatsby-dev-cli/

**Comment by KyleAMathews** [comment]
Yeah, how are you testing the plugin now? Can you verify that your functions are being called?

**Comment by barraq** [comment]
Hi @calcsam and @KyleAMathews, yes so I am using the `gatsby-dev-cli` plugin to test my plugin in one of my project. I indeed verified that my plugin is being called (e.g. I made sure that I am going through that test https://github.com/barraq/gatsby/blob/topics/gatsby-transformer-hjson/packages/gatsby-transformer-hjson/src/gatsby-node.js#L32): and it is called. Yet I see nothing in GraphiQL. I also tried to replace my test with https://github.com/barraq/gatsby/blob/topics/gatsby-transformer-hjson/packages/gatsby-transformer-json/src/gatsby-node.js#L29 hopping my plugin will then just return the JSON files, but again same thing: the schemas don't show up in GraphiQL.

**Note:** I found a small issue with `gatsby-dev-cli`, namely in my case `gatsby-transformer-hjson` has `hjson` as a dependencies. When `gatsby-dev-cli` runs it copies the compiled files (i.e. `gatsby-node.js`) but do not copy the dependency (i.e. `hjson`). As a result, running `gatsby in my project fails. To fix it I have to run `yarn` inside the `./node_modules/gatsby-transformer-hjson/`, indeed this will install the dependencies of that package. I can probably create a PR on `gatsby-dev-cli` to fix it in general. What do you think?

**Comment by KyleAMathews** [comment]
@barraq could you add an example site to the PR? I can take a look at it.

re not adding new dependencies — agree that'd be useful — would love a PR for this!

**Comment by barraq** [comment]
@KyleAMathews, interestingly it works fine in the example site ;) I am not sure why... but at least it proves it works.

**Note:** one thing I noticed trying to get the example site running: I ran `gatsby-dev` in the `using-json` folder. This copied `gatsby`, `gatsby-source-filesystem` and `gatsby-transformer-hjson` in `node_modules`. Then running `yarn run develop` through an exception saying that module `async/mapSeries` cannot be found. To fix it I had then to remove `gatsby` folder from `node_modules` then. If I only run `yarn run develop` without all the previous steps I get the following error: ```There were errors with your webpack config: [1] resolveLoader.root.0 path.absolute , "0" "/Users/remibarraquand/Development/community/gatsby/examples/using-hjson/node_modules" should be an existing absolute path, but I found the following problems: The supplied path does not exist on the file system.```

**Comment by barraq** [comment]
@KyleAMathews  ok to merge?

**Comment by KyleAMathews** [comment]
Yup! Thanks!

**Comment by jlengstorf** [comment]
Hiya @barraq! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
