### PR TITLE
Updating 'submit-to-site-showcase' stub in docs

### PR DESCRIPTION
**Pull request by munwr**
We already have a page in docs https://next.gatsbyjs.org/docs/submit-to-site-showcase/, but we created another one https://next.gatsbyjs.org/docs/site-showcase-submissions/ which is being used in https://github.com/orgs/gatsbyjs/teams/maintainers/discussions/21.

I have updated the existing page with content from `site-showcase-submissions` and set the link as available. I also think it would be better if we add a redirect for `site-showcase-submissions` to `submit-to-site-showcase`

@shannonbux @jlengstorf @m-allanson

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit c1a8ab5e75769389a9bd098dbd0c8cc31d2697e4

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5602bdc965925f128f6e8d

**Comment by KyleAMathews** [comment]
Oh, we should probably just link the docs page to the same file?

**Comment by jlengstorf** [comment]
Yeah, seems like we should delete one or the other and update all links.

**Comment by shannonbux** [comment]
@munwr great catch and thanks for the help! Sounds like the plan is this:

1. update `submit-to-site-showcase` doc to include content from `site-showcase-submissions`
That sounds perfect.

2. redirect `site-showcase-submissions` to `submit-to-site-showcase`
I would only do this if tons of people in the community are already visiting `site-showcase-submissions`. My sense is that we can just update the maintainers discussion and the blogpost with the new link to `submit-to-site-showcase` unless I'm missing something--can you think of a reason a redirect is necessary? If so, go ahead and do it!

Feel free to do this! Thanks again!

**Comment by munwr** [comment]
@shannonbux As you mentioned point 2. it only makes sense if people are already using this link and it has already indexed in the search engine. otherwise, this PR would be enough after deleting `site-showcase-submissions` and updating the maintainer's discussion and the blog post

**Comment by KyleAMathews** [comment]
We already have a site submission page so all we need to do in this PR is delete the duplicate stub article and then to link to the existing page in docs-links.yaml

**Comment by munwr** [comment]
@KyleAMathews deleted and updated

**Pull request merged**
