### PR TITLE
fix(gatsby): more reliable way to use prod versions of react/react-dom

### PR DESCRIPTION
**Pull request by KyleAMathews**
back port of https://github.com/gatsbyjs/gatsby/pull/29620 to v2

Fix https://github.com/gatsbyjs/gatsby/discussions/28138#discussioncomment-371276

Set `NODE_ENV` to `production` in the child worker that does the SSR in dev.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Windows tests are failing on the node version used 🤔

**Comment by wardpeet** [comment]
This seems fine, can you update snapshot (I think we already did this in master)

**Comment by pieh** [comment]
> This seems fine, can you update snapshot (I think we already did this in master)

Other backport PRs also had this test failing because of that snapshot so I would say if we want to update snapshot for that branch, let's do this separately

**Review by pieh — APPROVED** [review]

**Comment by KyleAMathews** [comment]
snapshot fix @ https://github.com/gatsbyjs/gatsby/pull/29697

**Review by pieh — APPROVED** [review]

**Comment by ascorbic** [comment]
Published in `gatsby@2.32.5`

**Pull request merged**
