### PR TITLE
Removed dead link to ashk.io

### PR DESCRIPTION
**Pull request by adarshp**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 3869600e0a4bd04fa38168f1bdd987b5ff2b886a

https://app.netlify.com/sites/gatsbyjs/deploys/59100396424ef24f7bd8b314

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 3869600e0a4bd04fa38168f1bdd987b5ff2b886a

https://app.netlify.com/sites/gatsbygram/deploys/59100396424ef24f7bd8b317

**Comment by KyleAMathews** [comment]
Let's see if it was just moved or a temporary outage before removing it https://github.com/wpioneer/blog/issues/2

**Comment by adarshp** [comment]
Sounds good.

**Comment by wpioneer** [comment]
Hi, I will shortly publish a new link to a static blog.
Old ashk.io-link can be removed.

**Comment by KyleAMathews** [comment]
@wpioneer ok! Thanks for chiming in! BTW, I hope you see some of all the gatsby sites using your starter that keep popping up online!

**Comment by jlengstorf** [comment]
Hiya @adarshp! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
