### PR TITLE
[v2] Add gatsby-remark-bracketed-spans plugin

### PR DESCRIPTION
**Pull request by vadimshvetsov**
Support of [remark-bracketed-spans](https://github.com/sethvincent/remark-bracketed-spans) parser plugin for using id and other attributes with spans.

I'm not fluent with gatsby plugin infrastructure and my attempts to bind this in dev mode with test site was failed. I would appreciate any advices about how to do it and why `npm run watch -- --scope=gatsby-remark-bracketed-spans` failing.

### CODE REVIEW

**Comment by vadimshvetsov** [comment]
I'd run `yarn run test:update` several times but CI considers 1 snapshot as obsolete.

**Comment by LeKoArts** [comment]
Normally users publish & maintain such packages by themself and they don’t get merges into Gatsby

**Comment by vadimshvetsov** [comment]
@LeKoArts There is almost the same package already in gatsby repo - https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-custom-blocks

**Comment by vadimshvetsov** [comment]
I still can't pass snapshot test. I've ran every possible shapshot update script including `yarn run jest -u` but locally all tests are passing.

https://travis-ci.org/gatsbyjs/gatsby/jobs/428920529#L2242

**Comment by vadimshvetsov** [comment]
I've published package and it's not working as intended. I'll dive into this but now this PR wouldn't profitable

**Comment by vadimshvetsov** [comment]
I've published package and it's not working as intended. I'll dive into this but now this PR wouldn't profitable

**Pull request closed without merging**
