### PR TITLE
fix(gatsby-theme-blog): fix avatar squishing on mobile (#19172)

### LINKED ISSUE #19172: Default gatsby-theme-blog avatar is squished on mobile
## Description

The default gatsby-theme-blog avatar isn't responsive.

### Steps to reproduce

```sh
npx gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme
cd my-themed-blog
npm run develop
```

Open http://localhost:8000 and view default avatar on small screen sizes.

Example project: https://github.com/trevordmiller/trevordmiller.github.io

### Expected result

Avatar stays a circle on any screen width.

### Actual result

On smaller screen sizes the avatar turns into an oval instead of a circle (it gets squished horizontally).

image

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```sh
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.17.6 => 2.17.6
    gatsby-theme-blog: ^1.1.11 => 1.1.11
```

### PR DESCRIPTION
**Pull request by Qovaros985**
## Description
Add `minWidth` to Avatar in `gatsby-theme-blog` so it won't squish when space for it is too narrow.

## Related Issues
Fixes #19172

### CODE REVIEW

**Comment by Qovaros985** [comment]
Should I also do something like:
```
const Bio = () => {
  const data = useStaticQuery(bioQuery)
  const {
    site: {
      siteMetadata: { author },
    },
    avatar,
  } = data
  const avatarCss = css({
    mr: 2,
    mb: 0,
    width: 48,
    minWidth: 48,
    borderRadius: 99999,
  });

  return (
    <Flex css={css({ mb: 4 })}>
      {avatar ? (
        <Image
          fixed={avatar.childImageSharp.fixed}
          alt={author}
          css={avatarCss}
        />
      ) : (
        <div
          css={avatarCss}
          role="presentation"
        />
      )}
      <Styled.div>
        <BioContent />
      </Styled.div>
    </Flex>
  )
}
```
to remove code duplication?

**Comment by Qovaros985** [comment]
Should I also do something like:
```javascript
const Bio = () => {
  const data = useStaticQuery(bioQuery)
  const {
    site: {
      siteMetadata: { author },
    },
    avatar,
  } = data
  const avatarCss = css({
    mr: 2,
    mb: 0,
    width: 48,
    minWidth: 48,
    borderRadius: 99999,
  });

  return (
    <Flex css={css({ mb: 4 })}>
      {avatar ? (
        <Image
          fixed={avatar.childImageSharp.fixed}
          alt={author}
          css={avatarCss}
        />
      ) : (
          <div
            css={avatarCss}
            role="presentation"
          />
        )}
      <Styled.div>
        <BioContent />
      </Styled.div>
    </Flex>
  )
}```
to remove code duplication?

**Comment by fk** [comment]
@Qovaros985 Thank you (and @m-allanson for handling this)! 🙏 🤗 

> Second: Shouldn't Bio items be center aligned?

Not sure — this would vertically center the avatar and the block containing name, author bio, and time to read, and date, right? So we'd change from this

image

to this?

image

**Comment by Qovaros985** [comment]
@fk, my thought was that when name and bio is short (just two lines) it would look better if center aligned.
From:
Screenshot from 2019-11-09 21-33-44 
To:
Screenshot from 2019-11-09 21-34-08

Or from:
Screenshot from 2019-11-09 21-44-56
To:
Screenshot from 2019-11-09 21-45-39

Or even:
Screenshot from 2019-11-09 21-46-37
To:
Screenshot from 2019-11-09 21-46-30

I feel the same about your example. When items are center aligned it is harder to notice difference in height of those two, and I feel like seeing a difference in size generally looks worse. What I also heard is humans prefer things to be symetric.

That is just a thought I had while making this PR

**Comment by fk** [comment]
@Qovaros985 Oh yeah, I see! That does make sense — thanks so much for taking the time to explain in detail! 💜🙏 Happy to get a PR for that in!

**Comment by Qovaros985** [comment]
Thanks for approval @fk! Here is PR #19445.

**Pull request merged**
