### PR TITLE
testing: cypress test for production builds

### PR DESCRIPTION
**Pull request by shobhitchittora**
### Description

This adds basic cypress setup for checking production builds.

### CODE REVIEW

**Comment by m-allanson** [comment]
Thanks @shobhitchittora! I think @KyleAMathews is working on something similar today, so I've requested a review from him.

**Comment by KyleAMathews** [comment]
@m-allanson yeah we were actually pairing on this earlier! :-D I'll be finishing this up now.

**Comment by m-allanson** [comment]
Looking good! I guess we'll need to figure out how to make these run in parallel instead of sequentially..

**Comment by KyleAMathews** [comment]
Yeah... need to figure that out. CI run times are growing! Doing some research. BTW, seems like Appveyor is happier these days :-)

**Comment by KyleAMathews** [comment]
It might make sense to move to CircleCi as parallelism there looks a lot simpler https://circleci.com/docs/2.0/parallelism-faster-jobs/

**Comment by shobhitchittora** [comment]
Refs: #7421 .

**Pull request merged**
