### PR TITLE
Add official Image component gatsby-image and with accompanying example site

### PR DESCRIPTION
**Pull request by KyleAMathews**
These will be setup to work almost out-of-the-box with Gatsby's image queries.

They will use the "blur-up" effect where they'll show initially a blurry view
of the image and then fade-in the image once it loads.

It also will use the new IntersectionObserver API to efficiently detect when
the image is in the viewport so to start downloading the image. Currently 50% of
browsers support this API and Safari is on track to ship it soon which will get
all the greenfield browsers supporting it. Browsers not supporting IntersectionObserver
will just download images immediately.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
You can see the WIP component in the second red Kayne https://deploy-preview-2195--image-processing.netlify.com/

**Comment by jquense** [comment]
this is so cool. I love that how simple it is for a user to add this sort of optimization to a gatsby site. badass, Kyle 👍

**Comment by KyleAMathews** [comment]
@jquense thanks! Agreed! Gatsby being more "vertically integrated" than most frameworks makes these sorts of optimizations easy! Lots more that can be done…

**Comment by KyleAMathews** [comment]
Some follow up work to do to convert other example sites to use this but… it's the weekend so let's ship! :-)

**Comment by fk** [comment]
🎉 !!!

**Pull request merged**
