### PR TITLE
chore(gatsby-plugin-less): less-loader version 6.1.0 with tests and doc…

### LINKED ISSUE #24867: gatsby-plugin-less alias without tilde
I need less alias without tilde, it's supported in [less-loader version 6](https://github.com/webpack-contrib/less-loader/releases/tag/v6.0.0)

Is it possible to update gatbsy-plugin-less less-loader to version 6.1.0? thanks

### PR DESCRIPTION
**Pull request by minimit**
### Description

I update less-loader to a new major version, it has some bugfixes and some feature (resolve imports without tilde).

node and webpack version should be covered:

> minimum supported Node.js version is 10.13
> minimum support webpack version is 4

### Documentation

[less-loader releases 6.0.0 and 6.1.0](https://github.com/webpack-contrib/less-loader/releases)

## Related Issues

Fixes #24867

### CODE REVIEW

**Comment by minimit** [comment]
I've moved internally `options` to `options.lessOptions`, maybe for some use case it will break if someone was passing to `options` some [less-loader options](https://github.com/webpack-contrib/less-loader#options). But since `sourceMap: !PRODUCTION,` is set internally and since the tests didn't test for it, I thinks it's safe to say the bunch of less-loader options aren't used, or am I wrong?

**Comment by minimit** [comment]
@wardpeet if it's a breaking change it's better to refactor the **gastby-plugin-less**`options: {}` passed to adding `options.lessOptions {}`, can I make a new commit on this pr with this refactor?

**Comment by wardpeet** [comment]
That sounds like a great idea! :)

**Comment by minimit** [comment]
@wardpeet I did add `### v4.0.0` in the readme breaking changes, but i've not done a commit with message `BREAKING CHANGES`, is it needed?

**Comment by wardpeet** [comment]
This is fine! thanks, i'll merge it in a bit

**Comment by minimit** [comment]
Great can't wait!

**Comment by minimit** [comment]
Maybe on merge bump the version of less-loader there are new releases https://github.com/webpack-contrib/less-loader/releases

**Comment by wardpeet** [comment]
sorry I forgot about this, let me get this in today. I'll fix conflicts

**Comment by minimit** [comment]
Great can't wait!

**Comment by wardpeet** [comment]
Published in `gatsby-plugin-less@4.0.0`

**Pull request merged**
