### PR TITLE
feat(gatsby-transformer-react-docgen): upgrade to react-docgen 5

### PR DESCRIPTION
**Pull request by jquense**
BREAKING CHANGE: maybe, the interal api's chagned so folks using custom resolvers will probably be broken, but generally the default user should be unaffected

### CODE REVIEW

**Comment by jquense** [comment]
yup to ya'll whether this counts as a breaking change. Strictly speaking some users will be broken tho

**Comment by jquense** [comment]
ping

**Comment by sidharthachatterjee** [comment]
@jquense Thank you for doing this! The new release looks great (TypeScript support 😍)

I would definitely want to release this as a major version bump (owning to the breaking changes in the resolver signature documented in https://github.com/reactjs/react-docgen/releases/tag/v5.0.0-beta.1) 

Shall we wait till `react-docgen` v5 is out of beta?

**Comment by jquense** [comment]
that is likely to be months at the pace the project tends to move, integers are cheap, so why wait, can always bump again if needed. Up to ya'll but i've published my own version for now so we can get typescript support

**Comment by sidharthachatterjee** [comment]
@jquense Fair enough! I’ll get this published as a major today

**Comment by sidharthachatterjee** [comment]
Published in `gatsby-transformer-react-docgen@5.0.0`

**Comment by jquense** [comment]
🎉 Thanks!

**Pull request merged**
