### PR TITLE
feat(gatsby): Gatsby config validation should suggest related keys

### LINKED ISSUE #12291: Gatsby config validation should suggest related keys
## Summary

When running a gatsby site the gatsby-config is validated. The error message is quite long due to multiple instances of the failed validation error that appear after the initial `ValidationError`. The error also doesn't suggest any possible mis-spellings, so a user new to Gatsby can become frustrated fairly easily, not knowing that `plugin` should be `plugins`. 

<details>
 <summary>full error log</summary>

```
➜ yarn workspace scotchy-site develop
yarn workspace v1.13.0
yarn run v1.13.0
$ gatsby develop
⠁ The site's gatsby-config.js failed validation
ValidationError: "plugin" is not allowed
error The site's gatsby-config.js failed validation


  Error: The site's gatsby-config.js failed validation

  - config.js:29 module.exports
    [Scotch-gastby-theme-demo]/[gatsby]/dist/redux/reducers/config.js:29:17

  - redux.js:451 combination
    [Scotch-gastby-theme-demo]/[redux]/lib/redux.js:451:29

  - redux.js:211 dispatch
    [Scotch-gastby-theme-demo]/[redux]/lib/redux.js:211:22

  - index.js:89 Object.action [as dispatch]
    [Scotch-gastby-theme-demo]/[gatsby]/dist/redux/index.js:89:91

  - index.js:117
    [Scotch-gastby-theme-demo]/[gatsby]/dist/bootstrap/index.js:117:11

  - Generator.next

  - util.js:16 tryCatcher
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:638:18

  - promise.js:432 Promise._resolveCallback
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:432:57

  - promise.js:524 Promise._settlePromiseFromHandler
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:524:17


error UNHANDLED REJECTION


  Error: The site's gatsby-config.js failed validation

  - config.js:29 module.exports
    [Scotch-gastby-theme-demo]/[gatsby]/dist/redux/reducers/config.js:29:17

  - redux.js:451 combination
    [Scotch-gastby-theme-demo]/[redux]/lib/redux.js:451:29

  - redux.js:211 dispatch
    [Scotch-gastby-theme-demo]/[redux]/lib/redux.js:211:22

  - index.js:89 Object.action [as dispatch]
    [Scotch-gastby-theme-demo]/[gatsby]/dist/redux/index.js:89:91

  - index.js:117
    [Scotch-gastby-theme-demo]/[gatsby]/dist/bootstrap/index.js:117:11

  - Generator.next

  - util.js:16 tryCatcher
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:614:10

  - promise.js:694 Promise._settlePromises
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:694:18

  - promise.js:638 Promise._fulfill
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:638:18

  - promise.js:432 Promise._resolveCallback
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:432:57

  - promise.js:524 Promise._settlePromiseFromHandler
    [Scotch-gastby-theme-demo]/[bluebird]/js/release/promise.js:524:17


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/chris/.nvm/versions/node/v10.6.0/bin/node
Arguments: /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js develop
Directory: /Users/chris/tmp/Scotch-gastby-theme-demo/site
Output:
```

</details>

### Basic example

I'd like to see the output truncated to exclude the duplicate errors and also add a suggested option based on Levenshtein distance to possible valid keys.

```
➜ yarn workspace scotchy-site develop
yarn workspace v1.13.0
yarn run v1.13.0
$ gatsby develop
⠁ The site's gatsby-config.js failed validation
ValidationError: the key "plugin" is not allowed, did you mean "plugins"?

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/chris/.nvm/versions/node/v10.6.0/bin/node
Arguments: /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js develop
Directory: /Users/chris/tmp/Scotch-gastby-theme-demo/site
Output:
```

### Motivation

> Why are we doing this? What use cases does it support? What is the expected outcome?

This change supports people new to Gatsby and new to reading error messages in general by showing less "noise" and providing helpful suggestions, making Gatsby an even friendlier tool for newcomers.

### PR DESCRIPTION
**Pull request by matthewshirley**
## Description
Implemented to changes as suggested in #12291:

- If an error is thrown in the configuration validation, if the error type is of "allowUnknown", then it will attempt to find a key to suggestion
- If a plugin has an empty 'options' key and an 'option' key that is not empty, then it will throw an error suggesting to the user to rename 'option' to 'options'
- Tests for the aforementioned changes

### Documentation
Documentation does not apply to these changes.

## Related Issues
Fixes #12291

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hey sweet for jumping on this! This will be really helpful.

Curious if there was a reason you picked `meant`? We use Joi already quite a bit so in general I'd suggest going with that.

**Comment by matthewshirley** [comment]
> Hey sweet for jumping on this! This will be really helpful.
That's awesome to hear!

> Curious if there was a reason you picked meant? We use Joi already quite a bit so in general I'd suggest going with that.
@KyleAMathews Meant is used in this scenario to determine how close the passed string ("plugin" for example) is to a string in the array of known keys (["plugins"]). I feel this was more efficient than adding my string similarity, and, this is used in gatsby-cli.

I'm not aware of any Joi functions that will do similar "did you mean" calculations although I only have a low exposure to the library. Let me know if there is and I can work on using Joi entirely - fewer dependencies are better! :wink:

**Comment by KyleAMathews** [comment]
Ah you're right. I thought I remembered one. Carry on 😅

**Comment by matthewshirley** [comment]
Phew :sweat_smile: 

I'll tackle the typescript issue tomorrow unless if there is an immediate solution to the error. Seems the function conflicts with Joi definitions.

**Comment by matthewshirley** [comment]
This is ready for review again. :+1:

**Comment by wardpeet** [comment]
Hey @matthewshirley, awesome work! Sadly we have some conflicts.. Could you also describe some scenarios to test this? :)

It should work with gatsby-config but also plugins?

**Comment by matthewshirley** [comment]
@wardpeet These merge conflict is resolved. 👍  The scenarios for testing this:

## a gatsby-config with an invalid key
Update "plugins" to "plugin" in gatsby-config.js and run `gatsby develop`. You should receive an error message advising `"plugin" is not allowed. Did you mean "plugins"?

## a gatsby-config with a valid plugin but incorrect options key
In a `gatsby-config` with a plugin, update "options" to "option" and run `gatsby develop`. You should receive an error message advising `"option" is not allowed. Did you mean "options"?

**Pull request merged**
