### PR TITLE
fix(gatsby-source-filesystem): allow regex and functions for ignore option

### LINKED ISSUE #27848: gatsby-source-filesystem  no longer accepts functions as ignore rule
Hey there,

using functions for the ignore rule in gatsby-source-filesystem was working fine till the recently released plugin options validation:

```
Invalid plugin options for "gatsby-source-filesystem", configured by ...
"ignore[0]" must be a string
```

source-filesystem uses chokidar/anymatch and they support regex and function ignores next to strings:

* https://github.com/paulmillr/chokidar#path-filtering
* https://github.com/micromatch/anymatch#anymatchmatchers-teststring-returnindex-options

I guess the only thing to do is to extend the following plugin validation config:
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/gatsby-node.js#L160

### PR DESCRIPTION
**Pull request by axe312ger**
fixes #27848

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]
Fantastic, thank you!!

**Comment by axe312ger** [comment]
@mxstbr i think the test fails are unrelated?

**Comment by mxstbr** [comment]
They were just fixed in b57e41f!

**Review by mxstbr — APPROVED** [review]

**Comment by axe312ger** [comment]
@mxstbr the new failed tests says log to long, i can't see whats wrong 😅 

Would you remerge master again? Or restart the CI? :)

**Comment by axe312ger** [comment]
<3

**Pull request merged**
