### PR TITLE
Make all docs use `.md` instead of `.mdx` for consistency

### PR DESCRIPTION
**Pull request by tesseralis**
Might as well be consistent. Also VSCode doesn't read .mdx files as markdown for me.

There's more files: two blog entries and `how-shadowing-works`. I can get those as well.

### CODE REVIEW

**Comment by muescha** [comment]
the `contributing` need to be a `mfx because of the `EmailCaptureForm` form:

```javascript
import EmailCaptureForm from "../../www/src/components/email-capture-form"

<EmailCaptureForm signupMessage="Want to keep up with the latest tips &amp; tricks? Subscribe to our newsletter!" />
```

**Comment by tesseralis** [comment]
No, it doesn't. Look at `data-fetching.md`, `graphql-api.md`, or even `index/docs.md` for the same component. All the markdown files are treated as MDX even with the `.md` extension.

**Comment by muescha** [comment]
ok - i miss that fact

**Comment by AishaBlake** [comment]
@tesseralis this seems reasonable to me! Looks like the conflicts need to be resolved manually, though?

**Comment by tesseralis** [comment]
@AishaBlake done!

**Pull request merged**
