### PR TITLE
Warn when creating a page on an existing path

### PR DESCRIPTION
**Pull request by oorestisime**
Closes: #5836

I've spent a few hours trying to find out why a blog post was taking the contents of another one. Hope i ve put the warning in the best place.

### CODE REVIEW

**Comment by pieh** [comment]
I think we need more robust check - because this would throw warning for how we recommend to use client-only paths ( https://www.gatsbyjs.org/docs/building-apps-with-gatsby/#client-only-routes--user-authentication ).

I would think this would need to show warning if page template or context changes

**Comment by oorestisime** [comment]
Ah i thought it goes through the same redux action. i ll have a look again at this then

**Comment by pieh** [comment]
> Ah i thought it goes through the same redux action. i ll have a look again at this then

It does go through same action. I meant that this change would show warning for it now and I don't think we want that warning for that usecase.

**Comment by oorestisime** [comment]
So this looks more complicated than i thought at the beginning. We talked a bit on discord and options are:

* move this logic in the remark source and let user specify which field should be unique (frontmatter.path etc). Seems quite error prone and depends on user
* add an updatePage action as a wrapper around createPage that turns off the warning and use it in the docs . Requires a lot of changes in the docs
* find a way to warn only when overriding a path in the same api call (such as the same gatsby-node). that would need adding something like a trackId in the actions (unless there is one already) and use it to know whether we should warn user.
* drop this completely  :D

i am open to further suggestions and how to proceed with this :)

**Pull request closed without merging**
