### PR TITLE
fix(gatsby-plugin-sass): Add support for additionalData option

### PR DESCRIPTION
**Pull request by laneparton**
## Description

Adds [additionalData](https://webpack.js.org/loaders/sass-loader/#additionaldata) option to `gatsby-plugin-sass`

### Documentation

https://webpack.js.org/loaders/sass-loader/#additionaldata

## Related Issues

Fixes https://github.com/gatsbyjs/gatsby/issues/36085

### CODE REVIEW

**Comment by laneparton** [comment]
Still WIP - I'm happy to add to the README

**Comment by LekoArts** [comment]
The unit tests are currently failing () because the snapshots need an update.

And I agree, the README could use an update. A new heading called `additionalData` under https://github.com/laneparton/gatsby/tree/gatsby-plugin-sass-additionalData/packages/gatsby-plugin-sass#other-options should do it 👍

**Comment by laneparton** [comment]
Let me know how I can make any improvements :)

**Comment by LekoArts** [comment]
README looks good to me, unit tests still need an update though. Do you need help with that? :)

**Comment by LekoArts** [comment]
The unknown relates to this: https://joi.dev/api/?v=17.6.0#objectunknownallow

But since this isn't an object that's not needed

**Review by LekoArts — APPROVED** [review]
👍

**Pull request merged**
