### PR TITLE
#2359 Add environment variable to configure css modules class names

### PR DESCRIPTION
**Pull request by jurosh**
See for more details https://github.com/gatsbyjs/gatsby/issues/2359

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks for the PR!

Let's not use environment variables though for this — environment variables should only be used as an API when the data passed in varies by environment e.g. development vs. prod. And even there, it's preferable to pass in config through gatsby-config.js as you can use `process.env.VAR` there as well.

I'm not really convinced this is needed though — is the problem just that the names are annoyingly long?

**Comment by KyleAMathews** [comment]
Though I guess with the custom shared plugin for config, it might be that ENV variables are the only option for customization :-(

**Comment by jurosh** [comment]
> I'm not really convinced this is needed though — is the problem just that the names are annoyingly long?

This might add a little more flexibility to rendering engine - so that everyone can choose how should classes looks like if he needs/wants to - possibly also setup differently for development and production.

Eg. it might be useful with automated functional testing, when you might want classes more compact, eg. `[local]--[hash..]` without full directories paths.

**Comment by KyleAMathews** [comment]
> so that everyone can choose how should classes looks like if he needs/wants to

Isn't the point of CSS Modules that the class names are auto-generated? Curious why people would care.

>it might be useful with automated functional testing, when you might want classes more compact, eg. [local]--[hash..] without full directories paths.

Again — why does this matter? The class names aren't full directories i.e. from the root. They're only from the src directory in a site so unit tests work just fine across machines.

**Comment by m-allanson** [comment]
My 2c on this - For production I'm indifferent about class names, but for development I find it really useful to have short, readable class names. It makes working with the browser's element inspection dev tools much clearer.

e.g. I find this much harder to work with:
31286937-98fa8bae-aab7-11e7-95dd-578b2202774e

Than this:
31286936-98e503d8-aab7-11e7-911b-66cf7e94e579

The second image has removed unnecessary repetition from the classnames, making it much easier to scan through the elements.

That said, I'd prefer it to be configurable via `gatsby-config.js` if that's possible.

**Comment by KyleAMathews** [comment]
>but for development I find it really useful to have short, readable class names

This makes sense — I can see why the longer names can be less helpful.

Ok, thought about this some more — I really dislike the idea of configuring Gatsby with ENV variables so this method is a non-starter. I also dislike adding more global config to Gatsby — we for the more part have avoided that and I'd like to keep that going :-)

What y'all could do however is create a plugin which lets you configure the path pattern and then which modifies the webpack config directly https://www.gatsbyjs.org/docs/add-custom-webpack-config/

How's that sound?

**Comment by m-allanson** [comment]
Sounds good to me, thanks. 

@jurosh I'd be happy to add you to https://github.com/m-allanson/gatsby-plugin-module-local-ident-name if you want to expand on it? Or feel free to take anything from there to make a new plugin.

**Comment by KyleAMathews** [comment]
Oh haha, it already exists!

**Comment by KyleAMathews** [comment]
Could you post a link to it in the attached issue?

**Comment by m-allanson** [comment]
I did already :) https://github.com/gatsbyjs/gatsby/issues/2359#issuecomment-334807168

**Comment by m-allanson** [comment]
Maybe my wording could be clearer though. Will add another link.

**Comment by KyleAMathews** [comment]
Haha ok, thanks!

**Pull request closed without merging**
