### PR TITLE
Ts migrate/query compiler

### LINKED ISSUE #21995: [Umbrella] TypeScript Migration (Help wanted!)
## Hello Community!

Gatsby is rewriting our core codebase in TypeScript! Checkout the RFC: #21798

We would love love love your help! This work is incredibly important in Gatsby being a stable product and you could be a part of it! We are looking for community members who would be willing to jump into the codebase in transition files from .js to .ts and add the proper typings. We have a few guidelines we are wanting to stick to when doing this:

#### Gatsby TS Guidelines

- Only use named exports, no export default.
- When importing a package, always try to find community maintained types instead of typing ourselves. Look at the DefinitelyTyped github repository.
- Opt for using Interfaces for objects and functions.
- Type aliases should be used for primitives, unions and tuples
- Interface declaration merging is an anti-pattern and should not be used internally.
- Use `Array<type>` rather than `type[]` syntax, as it's clearer and matches built-in types such as `Map`.
- Use TypeScript's helper types, such as `Record`, rather than defining your own.
- Every function should type its input and output (even if it’s inferrable)
- Enums are great, but beware they map to index numbers if not redefined. This can cause weird problems for public APIs that interop to normal JS.
- The `any` type can be used for stubbing module types that would be out of scope to migrate. But it should not be used for any functional input/outputs. The end goal of this migration is to have ZERO `any` types in the codebase. See if `unknown` makes more sense in that context. Don't use `@ts-ignore` comments.
- **Lastly and most imporantly**, we want to have simple types whenever possible. Primarily we should try to avoid Generics. Generic code can be highly reusable, but that can also come with the greater chance of breaking things. If you do need to use generics, please either give them default values or ensure the generic value can be inferred. Code should be simple when possible. DRY is not always best.

If you're interested in getting involved, check out the list below. If you're interested in doing something, please respond as a comment, i'll put your name by a file so others know it's "claimed", when the PR is merged i'll check the box. 

Tips to get involved: first read [the contribution docs](https://www.gatsbyjs.com/contributing/), and see [how to set up your local environment](https://www.gatsbyjs.com/contributing/setting-up-your-local-dev-environment/). After you've claimed the file to work on, convert it locally and ensure there are no typing or lint errors displayed in your IDE. Run `yarn typecheck` and `yarn lint:code` in the root before opening the PR, which will show any errors. Once you're ready, open the PR and one of us will review it. Thanks, and good luck!

### File list
---
- [x] packages/babel-plugin-remove-graphql-queries
  - [x] src
    - [x] /index.js (@zachtylr21 in #23954)
    - [x] /murmur.js (@zachtylr21 in #22458)
---
- [ ] packages/babel-preset-gatsby
  - [ ] src
    - [x] /utils/path-serializer.js (@MichaelDeBoey in #22035)
    - [x] /dependencies.js + test (@MichaelDeBoey in #22038)
    - [ ] /index.js + test
---
- [ ] packages/gatsby
  - [x] /cache-dir **DON'T DO**
  - [ ] src/bootstrap
    - [x] load-plugins (@Eyas in #22504)
      - [x] /index.js
      - [x] /load.js
      - [x] /validate.js
    - [ ] load-themes/index.js
    - [x] get-config-file.js (@mottox2 in #22472)
    - [x] graphql-runner.js (@rayriffy in #22860)
    - [x] index.js (@ascorbic in #24816)
    - [x] log-line-function.js (@gabrieluizramos in #23677 )
    - [x] page-hot-reloader.js (@jeffreymeng in #27330)
    - [x] prefer-default.js (@gabrieluizramos in #23677)
    - [x] redirects-writer.js (@mottox2 in #22530)
    - [x] remove-stale-jobs.js (@gabrieluizramos in #23538)
    - [x] requires-writer.js (@alexpyzhianov in #24289)
    - [x] resolve-module-exports.js (@Eyas in #24519)
    - [x] schema-hot-reloader.js (@mottox2 in #22497)
  - [x] src/commands
    - [x] /build.js (@devrchancay in #23695)
    - [x] /build-html.js (@blainekasten in #20535)
    - [x] /build-javascript.js (@mottox2 in #22028)
    - [x] /build-utils.js (@mottox2 in #22262)
    - [x] /clean.js (@mottox2 in #22036)
    - [x] /develop (@blainekasten in #19923)
    - [x] /develop-static.js (@blainekasten in #22106)
    - [x] /repl.js (@mottox2 in #22037)
    - [x] /serve.js (@mottox2 in #22209)
  - [ ] src/db
    - [x] common/query.js
    - [x] `loki/*` **DON'T DO**
    - [ ] index.js (@arthurjdam in #22725)
    - [x] nodes.js (@pvdz in #25199)
    - [ ] sanitize-node.js (@arthurjdam in #22725)
  - [x] src/internal-plugins **DON'T DO**
  - [x] src/joi-schemas/joi.js (@arthurjdam in #22738)
  - [ ] src/query
    - [x] /better-queue-custom-store.js + test (@chooban in #25389)
    - [x] /error-parser.js + test (@LekoArts in #20597)
    - [ ] /file-parser.js + test (@martingreilinger )
    - [ ] /graphql-errors.js (@jeffreymeng)
    - [x] /graphql-runner.js (@ascorbic in #21956)
    - [ ] /index.js + test - data-tracking.js
    - [ ] /query-compiler.js + test (@mohinderps)
    - [x] /query-runner.js (@mottox2 in #22427)
    - [ ] /query-watcher.js (@ArcaneDiver in #27324)
    - [x] /queue.js (@chooban in #25389)
    - [x] /redirects-writer.js (@PerfectPan in #23332), (@taejs in #23785 - this was closed as duplicate)
    - [x] /utils.js + test (@kawamataryo #22171 
  - [ ] src/redux
    - [ ] /actions
      - [x] add-page-dependency.js (@MichaelDeBoey in #22062)
      - [x] index.js (@MichaelDeBoey in #22063)
      - [x] internal.js (@blainekasten in #20457)
      - [ ] public.js **DON'T DO**
      - [x] restricted.js (@1natsu172 in #22297)
      - [x] types.js (@1natsu172 in #22297)
    - [x] machines/page-component.js (@kornil in #23277)
    - [x] /reducers
      - [x] babelrc.js (@kornil in #24115)
      - [x] component-data-dependencies.js (@kornil in #24028)
      - [x] components.js (@Kornil in #24045)
      - [x] config.js (@pieh in #23620)
      - [x] flattened-plugins.js (@alisson-suzigan #24062)
      - [x] index.js (@alisson-suzigan in #23877)
      - [x] inference-metadata.js (@kornil in #24381)
      - [x] jobs.js (@kornil in #24209)
      - [x] jobsv2.js (@gabrieluizramos in #23708)
      - [x] last-actions.js (@alisson-suzigan in #23771)
      - [x] nodes-by-type.js (@alisson-suzigan #24419)
      - [x] nodes-touched.js (@carrotderek in #24247)
      - [x] nodes.js (@alisson-suzigan in #23771)
      - [x] page-data-stats.js (@carrotderek in #24082)
      - [x] page-data.js(@taejs in #23738)
      - [x] pages.js (@hiwelo in #23701)
      - [x] program.js (@tgallacher in #24941)
      - [x] redirects.js (@akshitkrnagpal in #22810)
      - [x] resolved-nodes.js (@alisson-suzigan in #24062)
      - [x] schema-customization.js (@kornil in #24259)
      - [x] schema.js (@hiwelo in #23591)
      - [x] static-query-components.js (@hiwelo in #23475)
      - [x] status.js (@hiwelo in #23474)
      - [x] themes.js (@taejs in #23716)
      - [x] webpack-compilation-hash.js (@chrisq21 in #23439)
      - [x] webpack.js (@hiwelo in #23566)
    - [x] index.js (@blainekasten in #20457)
    - [x] nodes.js (@blainekasten in #21010)
    - [x] persist.js (@blainekasten in #20457)
    - [x] plugin-runner.js (@kawamataryo in #22476)
    - [x] run-fast-filters.js (@pvdz in #25055)
  - [ ] src/schema
    - [ ] extensions/index.js
    - [ ] infer/
      - [ ] add-inferred-fields.js
      - [x] build-example-data.js (@chooban in #23389)
      - [ ] index.js
      - [x] inference-metadata.js (@chooban in #23264)
      - [x] is-32-bit-integer.js (@Pittan in #22138)
      - [x] is-file.js (@chooban in #23093)
      - [x] type-conflict-reporter.js (@chooban in #23264)
    - [ ] types/
      - [x] built-in-types.js (@mottox2 in #22391)
      - [x] date.js (@sasurau4 in #22430) 
      - [x] derived-types.js (@sasurau4 in #22442) 
      - [x] filter.js (@sasurau4 in #22493) 
      - [x] node-interface.js (@alisson-suzigan in #26733)
      - [x] pagination.js (@alisson-suzigan in #23717)
      - [ ] sort.js
      - [x] type-builders.js (@PerfectPan in #23892)
      - [ ] type-defs.js
    - [x] context.js
    - [ ] index.js
    - [ ] node-model.js
    - [ ] print.js (@LinnJS)
    - [x] resolvers.js
    - [ ] schema-composer.js
    - [x] schema.js (@alisson-suzigan in #23717)
  - [ ] src/utils
    - [x] tracer/
      - [x] index.js (@kawamataryo #22296 )
      - [x] jaeger-local.js (@chooban in #23656)
      - [x] zipkin-local.js (@kawamataryo)
    - [x] worker/
      - [x] child.js ( @kawamataryo #22583  )
      - [x] page-data.js (@kawamataryo #22155)
      - [x] pool.js (@kawamataryo #22150)
      - [x] render-html.js( @kawamataryo #22263 )
    - [x] /api-browser-docs.js (@gabrieluizramos in #23688)
    - [x] /api-node-docs.js (@gabrieluizramos  in #23688)
    - [x] /api-runner-error-parser.js (@LekoArts in #20597)
    - [ ] /api-runner-node.js
    - [x] /app-data.js (@kawamataryo  in #22076 )
    - [x] /babel-loader-helpers.js (#kornil in #25100)
    - [ ] /babel-loader.js
    - [x] /babel-parse-to-ast.js (@john015 in #22480)
    - [x] /browserlist.js (@kawamataryo in #22089 )
    - [x] /cache.ts (@mattkane in #20626)
    - [x] /create-node-id.js (@Pittan in #22096)
    - [x] /create-schema-customization.js (@mottox2 in #22392)
    - [x] /detect-port-in-use-and-prompt.js (@mottox2 in #22061)
    - [x] /eslint-config.js (@dvrylc in #22294)
    - [x] /gatsby-dependents.js (@dvrylc in #22422)
    - [x] /gatsby-webpack-eslint-graphql-schema-reload-plugin.js (@sasurau4 #22408) 
    - [x] /gatsby-webpack-stats-extractor.js (@sasurau4 #22404) 
    - [x] /get-cache.js (@cola119 in #22094)
    - [x] /get-latest-apis.js (@cola119 in #22097)
    - [x] /get-public-path.js (@cola119 in #22093)
    - [x] /get-ssl-cert.js (@mottox2 in #22447)
    - [x] /get-static-dir.js (@mottox2 in #22083)
    - [x] /get-value-at.js (@martijnjanssen in #22182)
    - [x] /is-32-bit-integer.js (@Pittan in #22138)
    - [x] /jobs-manager.js (@martijnjanssen in #22189)
    - [x] /js-chunk-names.js (@mottox2 in #22289)
    - [x] /local-eslint-config-finder.js (@mottox2 in #22403)
    - [x] /merge-gatsby-config.js(@taejs in #23789)
    - [x] /normalize-page-path.js (@martijnjanssen in #22188)
    - [x] /page-data.js (@hiwelo in ~#23436~ #23991)
    - [x] /page-html.js (@kawamataryo in #22118)
    - [x] /path.js (@kawamataryo in #22130)
    - [x] /prepare-regex.js (@mottox2 in #22133)
    - [ ] /profile.js
    - [x] /reach-router-add-basecontext-export-loader.js
    - [x] /source-nodes.js
    - [x] /stack-trace-utils.js (@sasurau4 in #22251)
    - [x] /test-require-error.js (@sasurau4 in #22265)
    - [x] /webpack-error-utils.js (@sasurau4 in #22278)
    - [x] /webpack-helpers.js (@sasurau4 in #22279)
    - [x] /webpack-hmr-hooks-patch.js (@sasurau4 in #22280)
    - [x] /webpack-plugins.js (@sasurau4 in #22378)
    - [x] /webpack-utils.js (@sasurau4 in #22381)  
    - [ ] /webpack.config.js
    - [x] /websocket-manager.js (@Eyas in #22510)
---
- [x] packages/gatsby-cli
  - [x] src/reporter
    - [x] loggers
      - [x] ink (@arthurjdam in #22782)
        - [x] components (@arthurjdam in #22782)
          - [x] develop.js (@arthurjdam in #22782)
          - [x] error.js (@Naturalclar in #22098)
          - [x] messages.js (@cola119 in #22084)
          - [x] progress-bar.js (@Naturalclar in #22081)
          - [x] spinner.js (@Naturalclar in #22080)
        - [x] cli.js (@arthurjdam in #22782)
        - [x] context.js (@arthurjdam in #22782)
        - [x] index.js (@arthurjdam in #22782)
      - [x] ipc/index.js (@anoriqq in #23960)
      - [x] json/index.js (@wiput1999 in #24140)
      - [x] yurnalist/index.js (@blainekasten in #24224)
    - [x] redux (@Kornil in #22292)
      - [x] actions.js
      - [x] index.js
      - [x] reducer.js
    - [x] constants.js (@cola119  in #22084)
    - [x] errors.js  (@blainekasten in #24226)
    - [x] index.js (@blainekasten in #22869)
    - [x] prepare-stack-trace.js (@blainekasten in #24226)
    - [x] types.js (@blainekasten in #22869)
  - [x] src/structured-errors (@LekoArts in #20597)
    - [x] construct-error.js
    - [x] error-map.js
    - [x] error-schema.js
  - [x] src/util
    - [x] calc-elapsed-time.js (@Naturalclar in #22081)
    - [x] configstore.js (@mottox2 in #22180 renamed to package-manager)
    - [x] ensure-windows-drive-letter-is-uppercase.js (@mottox2 in #22140)
    - [x] is-tty.js (@mottox2 in #22129)
    - [x] version.js  (@mottox2 in #22176)
  - [x] src/create-cli.js (@alexpyzhianov in #23650)
  - [x] src/did-you-mean.js (@mottox2 in #22068)
  - [x] src/index.js (@blainekasten in #19923)
  - [x] src/init-starter.js (@mottox2 in #22086)
--- 
- [x] packages/gatsby-core-utils
  - [x] src/
    - [x] /ci.js (@danielkov in #22047)
    - [x] /cpu-core-count.js (@danielkov in #22048)
    - [x] /create-content-digest.js (@danielkov in #22049)
    - [x] /create-require-from-path.js (@danielkov in #22050)
    - [x] /get-config-file.js (@danielkov in #22051)
    - [x] /get-gatsby-version.js (@danielkov in #22052)
    - [x] /index.js (@danielkov in #22053)
    - [x] /path.js (@danielkov in #22054)
    - [x] /physical-cpu-count.js (@blainekasten in #22122)
    - [x] /url.js (@danielkov in #22056)
---
- [ ] packages/gatsby-link (@herecydev in #22027)
  - [ ] src/
    - [ ] /index.js + test
    - [ ] /parse-path.js + test
---
- [x] packages/gatsby-page-utils
  - [x] src/
    - [x] /create-path.js + test
    - [x] /ignore-path.js + test
    - [x] /index.js
    - [x] /validate-path.js + test
    - [x] /watch-directory.js
---
- [x] packages/gatsby-telemetry (@Eyas in #22532)
  - [x] src/
    - [x] error-helpers.js + test
    - [x] /event-storage.js
    - [x] /flush.js (@blainekasten in #25886)
    - [x] /index.js
    - [x] /is-truthy.js + test (@blainekasten in #25884)
    - [x] /postinstall.js
    - [x] /repository-id.js + test (@mottox2 in #22474)
    - [x] /send.js
    - [x] /showAnalyticsNotification.js
    - [x] /store.js
    - [x] /telemetry.js + test
---
- [x] packages/gatsby-react-router-scroll (@blainekasten in #24306)
  - [x] src/ 
    - [x] /index.js
    - [x] /ScrollBehaviorContext.js
    - [x] /ScrollContainer.js
    - [x] /StateStorage.js

### PR DESCRIPTION
**Pull request by mohinderps**
I added typings to query-compiler. But at some places I had to use ts-ignore, eslint-disable-next-line and any, where there was no way out. Please let me know of any changes, I would be more than happy to rework on this.

## Description

Migrated gatsby/query-compiler to typescript.

## Related Issues
#21995

### CODE REVIEW

**Comment by mohinderps** [comment]
Hi, do I need to update snapshots ? Why did they even change?

**Comment by ascorbic** [comment]
Hi. Yes, you'll need to update the snapshots, because you've changed the filename. Run `yarn jest -u packages/gatsby/src/query/__tests__/query-compiler.ts` in the root of the project

**Comment by mohinderps** [comment]
Cool, will update the PR with the snapshots. Thanks @ascorbic .

**Comment by mohinderps** [comment]
@ascorbic , need some help here. The tests and build failed. I need some guidance here.

**Comment by mohinderps** [comment]
I updated snapshots of other packages too because `yarn test` was complaining about them.

There are more test cases which are failing. Some of the test cases which have  `testPluginOptionsSchema` function call are  failing too.

**Comment by j0sh77** [comment]
Hey! Thanks so much for opening this pull request!

Sadly this PR got stale and didn't have any activity for some time. We're trying to do better with PR reviews! To get a better overview of all actionable PRs we're going through all open PRs and triage them. Since we won't be able to do everything and adding new features _always_ means added maintenance burden, we have to be more picky about what's beneficial for the average user and the project itself longterm.

We think this is a great PR and would love to see it land in Gatsby. We're closing this PR _for now_ but if you're able to rebase onto the latest `master` branch and try it out with the latest `next` versions, we'd be happy to review the PR when its re-opened.

We absolutely want to have you as a contributor and are sorry for any inconveniences we caused with replying too late to this PR.

Thanks for submitting to Gatsby! :purple_heart:

**Pull request closed without merging**
