### PR TITLE
Site Showcase submission request

### PR DESCRIPTION
**Pull request by YuryShkoda**

### CODE REVIEW

**Comment by bball07** [comment]
Thank you for your contribution!! I am going to merge this :)

**Comment by bball07** [comment]
This looks GREAT!! Once you resolve the conflicts it can be merged :)

**Comment by bball07** [comment]
Thank you for your contribution!! I am going to merge this :)

**Comment by muescha** [comment]
this PR removes the site "See Kids Dream" :(

**Comment by muescha** [comment]
added here #20825 `chore(showcase): Add See Kids Dream website to showcase`

**Comment by muescha** [comment]
#21035 chore(showcase): re-Add See Kids Dream website to

**Pull request merged**
