### PR TITLE
fix: update dependency css-loader to ^3.2.0

### PR DESCRIPTION
**Pull request by dreyks**
## Description

Update css-loader to 3.x
This is needed for correct work of some libraries such as `asotroturf`

### CODE REVIEW

**Comment by wardpeet** [comment]
@dreyks Thanks for upgrading to css-loader. Can you give us the error message you're getting with astroturf?

Upgrading css-loader from version 1x to 3x is a big jump. There are some breaking changes https://github.com/webpack-contrib/css-loader/releases.

I don't feel super confident upgrade without making sure we're 100% backward compatible which I don't think we can be.

**Comment by dreyks** [comment]
astroturf relies on some css-loader@3 magic to allow component interpolation. more info https://github.com/4Catalyzer/astroturf/pull/267
without the info from the loader, it's impossible to do that

This is the list of all breaking changes from v1 to v3. I've ticked the ones that I've handled. I'll try to figure out what to do with the rest but maybe someone from the core team has any tips for me?

V3
- [x] minimum required nodejs version is 8.9.0
- [ ] `@value` at rules now support in `selector`
- [ ] invert `{Function}` behavior for `url` and `import` options (need return `true` when you want handle `url`/`@import` and return `false` if not)
- [x] `exportLocalsStyle` option was remove in favor `localsConvention` option, also it is accept only `{String}` value (use `camelCase` value if you previously value was `true` and `asIs` if you previously value was `false`)
- [x] `exportOnlyLocals` option was remove in favor `onlyLocals` option
- [x] modules option now can be {Object} and allow to setup CSS Modules options:
  - `localIdentName` option was removed in favor `modules.localIdentName` option
  - `context` option was remove in favor `modules.context` option
  - `hashPrefix` option was removed in favor `modules.hashPrefix` option
  - `getLocalIdent` option was removed in favor `modules.getLocalIdent` option
  - `localIdentRegExp` option was removed in favor `modules.localIdentRegExp` option
V2
- [ ] resolving logic for `uls()` and `import` at-rules works the same everywhere, it does not matter whether css modules are enabled (with `global` and `local` module) or not. Examples - `url('image.png')` as `require('./image.png')`, `url('./image.png')` as `require('./image.png')`, `url('~module/image.png')` as `require('module/image.png')`.
- [ ] by default css modules are disabled (now `modules: false` disable all css modules features), you can return old behaviour change this on `modules: 'global'`
- [x] `css-loader/locals` was dropped in favor `exportOnlyLocals` option
import option only affect on import at-rules and doesn't affect on composes declarations
- [x] invalid `@import` at rules now emit warnings
- [ ] use `postcss@7`

**Comment by dreyks** [comment]
Also, worth noting that in any case we might break other users' configs/plugins where they modify the css-loader's options.

I fully understand that this would be a breaking change for gatsby itself and we might not just merge it as is, but I'm glad to try guiding it towards something if this is the direction that we want to move for say next major release

**Comment by pieh** [comment]
In case there are breaking changes that are just not possible to rectify with any config magic, I think way forward would be with creating plugin that replace builtin default css rules (which would still use css-loader@1) with rules that use css-loader@3

**Comment by wardpeet** [comment]
I was thinking the same as @pieh. You could create a separate plugin so others can use it too for their purpose or bake it inside https://github.com/silvenon/gatsby-plugin-astroturf

**Comment by dreyks** [comment]
hmm... that's an interesting thought. thanks! will try to figure something out

**Comment by wardpeet** [comment]
@dreyks we're here to help if you need any. Checkout [Discord](https://gatsby.dev/discord) or register for a [pair programming session](https://www.gatsbyjs.org/contributing/pair-programming/)

Hey! Thanks so much for opening a pull request!

The change you’ve proposed is not going to be accepted because it's not a change we can do in gatsby v2.

Thanks again, and we look forward to seeing more PRs from you in the future! 💪💜

**Pull request closed without merging**
