### PR TITLE
fix(gatsby-plugin-gatsby-cloud): Remove sibling detection code and rely on match paths

### PR DESCRIPTION
**Pull request by sidharthachatterjee**
This cleans up and removes our custom static sibling detection code and instead relies on Gatsby and the match path it generates

### CODE REVIEW

**Review by dmccraw — DISMISSED** [review]
:ship: it!

**Review by dmccraw — APPROVED** [review]

**Comment by ascorbic** [comment]
@sidharthachatterjee  Something is wrong in the release branch. The whole package has disappeared, and no combination of git logs seems to indicate where and how. Could you either find out how, or just open a new PR to add the plugin again!

**Comment by sidharthachatterjee** [comment]
@ascorbic Here you go https://github.com/gatsbyjs/gatsby/pull/29738

**Comment by ascorbic** [comment]
Published in `gatsby-plugin-gatsby-cloud@1.0.2`

**Pull request merged**
