### PR TITLE
feat(showcase): Add Tenon.io blog

### PR DESCRIPTION
**Pull request by AlmeroSteyn**
## Description

I would like to propose adding the new [Tenon.io blog](https://blog.tenon.io/) to the showcase. Just replaced our WordPress blog with a Gatsby version this week! 

Screen capture of the Tenon.io blog

### CODE REVIEW

**Comment by AlmeroSteyn** [comment]
Awesome! Thanks @m-allanson !

**Comment by lannonbr** [comment]
Hey @AlmeroSteyn so our validator for the site showcase picked up that the blog for Tenon.io is now returning 404s. Is this intentional?

**Comment by AlmeroSteyn** [comment]
Hey @lannonbr, thanks for letting me know. 

I am not longer busy on projects for Tenon, so I am not sure. But I did visit the blog and it seems to be online now. Can you recheck it?

Thank you!

**Comment by lannonbr** [comment]
I went to https://blog.tenon.io/ and the page loads, but it is a 404 page as seen in the screenshot below:

Screenshot_2019-10-04 https blog tenon io

**Comment by AlmeroSteyn** [comment]
Oh dear, you are quite right sorry. The service worker was still loading it this side.

It does indeed seem that something is wrong. But unfortunately I do not exactly know what and don't have access to the code and systems anymore as I moved on to another client :-)

I am cc'ing Tenon's Karl Groves on this issue. Shall we see wat he says? Otherwise you can remove it from the showcase.

cc @karlgroves

**Pull request merged**
