### PR TITLE
Update the readme and the docs site to include Netlify hosting

### PR DESCRIPTION
**Pull request by sdras**
## Description

There were chats between Matt, the founder of Netlify and Sam about stating Netlify is providing hosting as per our partnership and Netlify's Open Source terms, so I'm filing a followup PR. Hi! 👋 Thanks for your time in reviewing it!

## Related Issues

Normally I would open an issue but this was discussed already with both teams. :)

### CODE REVIEW

**Comment by calcsam** [comment]
I think there might have been a miscommunication -- in the email chain between Matt, which I've forwarded to you, we were comfortable with Netlify moving to the top of the Deploying and Hosting section, given its popularity as a host for Gatsby sites. We're not okay with adding a "Powered by Netlify" note at the bottom.

**Comment by sdras** [comment]
Hey @calcsam! As per our email conversation, the PR should be all fixed up and in order. Let me know if you need anything else! Thanks.

**Comment by calcsam** [comment]
There's also this section -- https://www.gatsbyjs.org/docs/deploying-and-hosting/ -- you can change the order of the links in `doc-links.yaml`. 

Also you have a merge conflict.

**Comment by m-allanson** [comment]
Thanks @sdras and @calcsam! 

I've fixed up the conflict and updated `doc-links.yaml`. If that all looks good then this should be ready to merge.

**Comment by m-allanson** [comment]
Oh. Looks like I totally failed to merge 🤦‍♂ That's what I get for rushing. I need to step away for a few hours but will fix this up later.

**Comment by sdras** [comment]
Thanks @m-allanson! Let me know if you need anything else on my end.

**Pull request merged**
