### PR TITLE
Added support for nested img tags in html nodes

### PR DESCRIPTION
**Pull request by chiedo**
While migrating some of my larger sites over to Gatsby I noticed that my initial solution for html image tags didn't work nested img tags.

**This would work**

```
<img .../> 
```

**This would not work**

```
<div>
<img .../>
</div> 
```
This should now work for both.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 149441bb224d324f2e76d9b3e518da2bb79b5b9c

https://app.netlify.com/sites/using-styled-components/deploys/5966a079cf321c79dbf87323

**Comment by KyleAMathews** [comment]
This plugin is getting kinda complex but with no tests yet. Doesn't need to go in this PR but we need a way to mock gatsby-plugin-sharp so we can write tests with it. Perhaps just disable actually creating images when in test mode.

**Comment by chiedo** [comment]
Haha agreed.

I just put that on my todo list after I finish moving my other sites to Gatsby 1.0 and then finish a couple small client projects that have been building up.

**Comment by KyleAMathews** [comment]
Awesome thanks! Looking forward to the tests!!

**Pull request merged**
