### PR TITLE
feat(gatsby-source-wordpress): Add missing tests

### PR DESCRIPTION
**Pull request by TylerBarnes**
When we merged the new WP source plugin to master last week I had to remove all tests initially as we were strapped for time. This PR adds back those missing tests. 

I had to remove our docker setup and simplify tests to use a live WP instance on WPE because I was stumped on how to get docker with WP to work in the monorepo test setup.

CircleCI seems to not allow accessing containers on localhost - so I tried putting Gatsby/Jest into a container as well so that that container could call WP by it's service name, but that breaks things because the container doesn't have access to `gatsby-dev` which is used in the tests to use the latest versions of everything. We'll have to circle back on this in a few weeks and try to get it using WP in a container again (after GatsbyConf)

### CODE REVIEW

**Comment by ascorbic** [comment]
@TylerBarnes If this just adds tests, does it need backporting? Unless I'm missing something, it doesn't seem to change the package itself.

**Comment by TylerBarnes** [comment]
@ascorbic I was thinking so that the tests could run as part of the backporting process but if it happens outside of CI then I guess it doesn't make sense to backport the tests.

**Review by vladar — APPROVED** [review]
Everything looks good 👍 But I did a rather shallow review. One thing that brought my attention was `.wordpress-cache` directory and its contents but I assume it is needed to skip downloading these assets on the test run? If it's not and was just left there by mistake - we should remove it. Otherwise, it is good to go 🚢

**Comment by TylerBarnes** [comment]
@vladar yep, that's the reason I included it. For some reason circleCI was downloading files extremely slowly - I guess it's the connection or low resources. I could only get it to run with a hard cache & committing the hard cache.

**Pull request merged**
