### PR TITLE
Added twitch and soundcloud to community plugins

### PR DESCRIPTION
**Pull request by Jedidiah**
I've added links to the community plugins list for:

- https://github.com/jedidiah/gatsby-source-soundcloud
- https://github.com/jedidiah/gatsby-source-twitch

In a separate commit I also sorted the plugin lists alphabetically to make scanning through them easier. Let me know if that isn't wanted and I can revert it.

### CODE REVIEW

**Comment by Jedidiah** [comment]
Not sure why I'm getting a failing test for a copy edit 🤔

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 584e7867eb9a6a70fca2937040775b1c6018ae3d

https://app.netlify.com/sites/using-glamor/deploys/5a1b15cc8198763319b712e7

**Comment by Jedidiah** [comment]
@KyleAMathews Thanks, I don't understand what I need to do to fix it though. Do the tests just need running again or do I need to change something?

**Comment by KyleAMathews** [comment]
Thanks for your contributions!

**Comment by jlengstorf** [comment]
Hiya @Jedidiah! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
