### PR TITLE
enhancement(docs): Remove entries in dictionary.txt and fix alt text values in docs files

### PR DESCRIPTION
**Pull request by meyian**
## Description

This removes "allfile-query", "filesystem-autocomplete", "filesystem-query" and "graphiql-filesystem" from  `dictionary.txt`. These terms occurred in both the `sourcing-from-the-filesystem.md` and `tutorial/part-five/index.md` files, so both these files were edited to remove these terms. The terms were found in alt text values, so they were replaced with more descriptive phrases. 

### Documentation

No documentation required for this change.

## Related Issues

Addresses #25290.

### CODE REVIEW

**Review by AishaBlake — DISMISSED** [review]
Hey, @meyian! Thank you so much for this contribution! This is a really awesome improvement.

Would you mind removing any instances of "Screenshot of" in these files? I know we do it in several blog posts a few other places in the docs but it's generally not necessary information. Screen readers users will know these are images, so we don't need to repeat that each one is a screenshot in the alt text.

Also, it looks like we're still getting lint warnings for instances of "allFile".

Once that's done, I'm happy to have another look. Thanks again!

**Comment by muescha** [comment]
@AishaBlake we could use this linter for better alt texts:
- https://github.com/double-great/remark-lint-alt-text
- which uses rules from https://github.com/double-great/alt-text

**Comment by meyian** [comment]
> Hey, @meyian! Thank you so much for this contribution! This is a really awesome improvement.
> 
> Would you mind removing any instances of "Screenshot of" in these files? I know we do it in several blog posts a few other places in the docs but it's generally not necessary information. Screen readers users will know these are images, so we don't need to repeat that each one is a screenshot in the alt text.
> 
> Also, it looks like we're still getting lint warnings for instances of "allFile".
> 
> Once that's done, I'm happy to have another look. Thanks again!

Sure thing! I've removed references to "allFile" and instances of "Screenshot of."

**Review by LekoArts — APPROVED** [review]
Changed the "Screenshot of" in the docs files, the blog posts are not sourced from here anymore so it's something we'll need to take care of in WordPress.

So this is good to go, thanks a lot! 👍

**Pull request merged**
