### PR TITLE
[wip] feat(www): Spring cleaning, episode 1: Drop „Spectral“ in favor of native sans-serif; moar 

### PR DESCRIPTION
**Pull request by fk**
I like Spectral. I suggested [Spectral to replace TeX Gyre Schola](https://github.com/gatsbyjs/gatsby/pull/1765). But something never sat right with it with me — it runs a little too wide, and IMO renders a little to dark on certain devices and OSes, among other things.

I've also grown a little tired of the serif/Futura-PT-for-inline-links combination; IMO it adds unnecessary visual noise esp. on small screens.

I def. will miss Spectral Italic, but I propose dropping Spectral in favor of the native __sans__-serif font stack. I think Spectral served us well, but not as a `bodyFontFamily`. We have a lot of "UI" needs on gatsbyjs.org, and a sans-serif default just makes sense IMO. We can work towards scoping CSS for long-form content and make it easier to bring back bespoke styles for this type of content, e.g. a (better) serif.

We also mix in Futura PT on i.e. https://www.gatsbyjs.org/features/ and the homepage for regular copy. That's fine per se, but in context things feel messy. Under the hood things really are quite messy, too — _we accumulated a lot of local styling for things that should be defined globally_. This makes it harder for everyone "doing the right thing", to review contributions, and ultimately building and maintaining a consistent UI.

So aside from dropping Spectral and making the required adjustments to do so — which would have caused quite a bit of noise/diff on its own — this PR aims to make a start at cleaning those things up, too, and establishing a basic set of design tokens for spacing and typography.
Thus this PR is a big, ugly blob, and I really don't want to ask anyone to really review the code. But `pliiiis` "Just trust me!" 😅— there's a lot of good things in here! __Nothing will explode.__ There will be follow up PRs, and I'm of course here to address any regression ASAP.  

Here's whats in the bag … roughly:

- simplify link styles — no more Futura PT, no more bold, no more three, but one pixel underline; `colors.lilac` instead of dark gray
- use `monospaceFontStack` for the PrismJS code highlight block badges
- only scale up `baseFontSize` once, at `presets.Xxl`, to 18px — no more 17 and 21px, and adjust for that — `presets.scale` _not_ included yet
- lighten `colors.gray.copy` a tiny bit
- add `presets.space`: it's coupled to` typography.js` (which might be a bit silly), and given `baseLineHeight = 1.5` and `baseFontSize = 16px` it provides the following spacing units:
  - `0`
  - `0.25rem` / `4px`
  - `0.5rem` / `8px`
  - `0.75rem` / `12px`
  - `1rem` / `16px`
  - `1.25rem` / `20px`
  - `1.5rem` / `24px`
  - `2rem` / `32px`
  - `2.5rem` / `40px`
- use `presets.space` in a lot of places; still a lot of work to do though
- remove indention of Docs/Tutorial/Features sidebar content, align it with the left page margin/logo instead; this results in the top-level items active state currently being slightly cut off — but the overall improvements are a first win IMO, and the active navigation items are still standing out enough
- less purple in the homepage diagram
- drop Futura PT for body copy on `/features`, Showcase and Starter card meta
- add `presets.scale`, containing a simple typographic scale, and use it
  - `0.75rem` / `12px`
  - `0.875rem` / `14px`
  - `1rem` / `16px`
  - `1.125rem` / `18px`
  - `1.25rem` / `20px`
  - `1.5rem` / `24px`
  - `1.75rem` / `28px`
  - `2rem` / `32px`
  - `2.25rem` / `36px`
  - `2.625rem` / `42px`
- this abandons using Typography.js' `scale` :/ — but gives frees us of having to worry about subpixel rounding, decimals in our design tools or when calculating line-heights, and most important of all, gives us a single source of truth (please note that this doesn't negate typesetting for vertical rhythm and using Typography.js for long-form content)

WORK IN PROGRESS, NOT READY TO MERGE;
should be enough to vote pro or contra this change though.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Awwww seeing that old PR with screenshots made me a bit nostalgic. I still like TeX Gyre Schola a lot :-D

**Comment by KyleAMathews** [comment]
Before and After

before-after

**Comment by KyleAMathews** [comment]
Looks like the top header got some extra margin-top? Was that intended?

**Comment by lachlanjc** [comment]
> Looks like the top header got some extra margin-top? Was that intended?

Can't speak for @fk but looks like it: 
https://github.com/gatsbyjs/gatsby/pull/12264/files#diff-d5343e3482876401d8bd4358271c3d9dR175

**Comment by krismorf** [comment]
Not sure if this is intentional but most sans-serif system fonts are missing.
Also, `-apple-system` and `BlinkMacSystemFont` are sans-serif, whereas the rest are serif.

Below is a font stack that covers all devices.
```
bodyFontFamily: [
  `-apple-system`,
  `BlinkMacSystemFont`,
  `Segoe UI`,
  `Roboto`,
  `Helvetica Neue`,
  `Arial`,
  `sans-serif`,
  `Apple Color Emoji`,
  `Segoe UI Emoji`,
  `Segoe UI Symbol`,
]
```

**Comment by fk** [comment]
Thanks @KyleAMathews for adding screenshots; should have done so myself.

> Looks like the top header got some extra margin-top? Was that intended?

Yep, but didn't take care of small screens properly yet.

**Comment by fk** [comment]
> Not sure if this is intentional but most sans-serif system fonts are missing.

@krismorf Ouch — yes, quickly hacked this together. Will fix later today.
Thank you! 🙏

**Comment by fk** [comment]
Here's a couple more "larger screen" screenshots (after/before):

Docs page:
image

A plugin README:
image

Finally dropping Futura for the "Features" section copy:
image

**Comment by greglobinski** [comment]
> * simplify link styles — no more Futura PT, no more bold, no more three, but one pixel underline; `colors.lilac` instead of dark gray

@fk do you mean, the `native` browser underlining  or still custom generated using  `border`, `box-shadow` or anything else?

**Comment by jlengstorf** [comment]
I’m in favor of the system font stack + new link styles. It’s more obvious they’re links, and removing custom fonts is a good perf bump.

Nice work!

**Comment by fk** [comment]
> `native` browser underlining or still custom generated using `border`, `box-shadow` or anything else?

@greglobinski For now I just chopped away the `box-shadow` on the existing styles for links (to get a feel for how things would look ASAP); those existing styles were using a 1px `border` plus a 2px `box-shadow`, which resulted in a (not trying to be smart here 😅😉) 3px tall underline.

I haven't put any thoughts into implementation details other than to keep the global `a` styles as simple as possible — really don't want to override stuff anymore 😉— so for the global stuff I thought about setting just the color and _removing_ `text-decoration: underline`. We could then opt-in to whatever default styles for long-form content by a class on the long-form content container (e.g. `.markdown-content`, or the exisiting `.main-body`/`post-body`). Does that make sense? Would love to hear your take on this!

I'm leaning towards `text-decoration: underline` for that, but I have to admit I do not really like how close that underline is to the text.

**Comment by greglobinski** [comment]
> I'm leaning towards text-decoration: underline for that, but I have to admit I do not really like how close that underline is to the text.

@fk :100: agree, if they would add just `1px` of spacing, I would never think of custom styling for that :)

**Comment by fk** [comment]
@KyleAMathews I finally removed `blockMarginBottom: 0.75` — now we're going with the Typography.js default of `1`, which means vertical rhythm FTW! 🎉 

---

Very happy where this is going — and about to wrap up today. Lots of improvements all over the place, e.g. "unbolded" `code` in headlines, correct monospace font-family for the `gatsby-highlight` language badges:

image

I know the changeset exploded, and it's unfair to ask for anyone to review this; but I think it's worth trusting me: I'm quite sure it does more good than it (possibly — not aware of anything at this point) breaks, and I will of course take care of whatever comes up after merging. Having `presets.scale` in there is huge to me personally, and gets us a huge step closer to a sane set of design tokens.

Will follow up with a summary of all changes in a bit.

**Comment by fk** [comment]
OK (phew!), this is good to go!
Please don't hate me. 🙏

**Comment by fk** [comment]
https://www.youtube.com/watch?v=a6P40wLThbc

<3 🙏 🤞

**Comment by DSchau** [comment]
@fk we trust ya 🎉 Excellent work here!

**Comment by fk** [comment]
Thank you @m-allanson @DSchau!
I will be around, and hold myself responsible! ;)

Also I forgot to mention I slightly updated the [PR description](https://github.com/gatsbyjs/gatsby/pull/12264#issue-257762173) — it hopefully provides a good overview of all the additional changes, and expands the motivation behind this a little more now.

Also I just noticed 
image
 — that's not too bad, is it?!

**Pull request merged**
