### PR TITLE
refactor: (gatsby-plugin-manifest) misc code and doc updates

### PR DESCRIPTION
**Pull request by moonmeister**
## Description

Code and Docs updates for `gatsby-plugin-manifest`

- Finished moving to module imports
- Finished migrating off of `bluebird` and onto async/await (order of magnitude speed increase)
- Major doc updates
- Improve logging output for generation

### CODE REVIEW

**Comment by moonmeister** [comment]
One thing I did want to open up for discussion on this is using `gatsby-plugin-sharp` as a peer dependency instead of directly depending on sharp. I'm not sure if there would be any benefits or drawbacks either way. It crossed my mind and wanted to see what others thought.

**Comment by moonmeister** [comment]
@DSchau haha I just mentioned this chat but I'll put it here for everyone:

when I eliminated the final line of code requiring `bluebird` and replaced it with a native promise I saw icon generation drop from between 200ms and 900ms to down to ~13ms.

I'm running latest node 10 lts on linux.

**Comment by moonmeister** [comment]
Rebased after 2 different manifest related PRs and fixed 2 bugs from #12794

**Comment by moonmeister** [comment]
Added tests and refactored the icon options merge as described here: https://github.com/gatsbyjs/gatsby/pull/12794#issuecomment-477165860. Also, fixed bug that was not letting config merge happen (thank you testing).

**Comment by moonmeister** [comment]
Moved bug fixes to #12907

**Comment by moonmeister** [comment]
@DSchau Well, bench marking proved I was wrong. :disappointed: Evidently it was just a strange fluke that I saw execution time drop. That or my bench mark is inaccurate. :man_shrugging: . I've added a bench mark for testing the execution time of `onPostBootstrap` in the manifest plugin.

**Comment by wardpeet** [comment]
I resolved the conflicts but I wasn't sure of
```
<<<<<<< manifest-cleanup -- Incoming Change
The `icon_options` object may be used to iteratively configure the [default icon array](#automatic-mode-configuration). Any options included in this object will be merged with each item of the `icons` array. This may be used in Automatic and Hybrid modes.
=======
The `icon_options` object may be used to iteratively add configuration items to the `icons` array. Any options included in this object will be merged with each object of the `icons` array (custom or default). Key value pairs already in the `icons` array will take precedence over duplicate items in the `icon_options` array.
>>>>>>> master -- Current Change
```

I used master when merging but feel free to change back what you had on this PR

**Comment by moonmeister** [comment]
You made the right call.

**Comment by moonmeister** [comment]
@DSchau @wardpeet Anything I can do to get this done or is it ready to be merged? The only other thing that's been on my mind is whether we should remove the dependency on sharp and use gatsby-plugin-sharp. I'm completely unaware of why we' prefer one method or the other.

**Comment by wardpeet** [comment]
This PR is pretty hard to review as so many things have changed, you added functionality & changed a lot of tests. It looks like you didn't change behaviour in the tests except omitting data but now it's really hard to actually validate if your changes are not breaking.

I'll probably ask some dumb questions in the review to make sure I've understood everything.

**Comment by moonmeister** [comment]
@wardpeet Sorry! I'll keep PRs smaller in the future. yes, there are no new features. I just organized docs and tests. In the test work I found a couple bugs I squashed. Also each commit is generally one change. Maybe reviewing each commit individually might be helpful. I'll be arrund to answer questions

**Comment by moonmeister** [comment]
@wardpeet Awesome. I dond't think build in content digest existed when I wrote that code originally. I think it was still in discussion glad you moved over to that! Thanks!

**Comment by sidharthachatterjee** [comment]
Thanks for all your work in this @moonmeister!

Published in `gatsby-plugin-manifest@2.0.27`

**Pull request merged**
