### PR TITLE
chore(gatsby-source-graphql): upgrade to graphql-tools v6

### PR DESCRIPTION
**Pull request by yaacovCR**
## Description

Upgrade dependency graphql-tools to v6

Major change is that in v6, graphql-js objects are considered immutable, hopefully leading to greater interoperability.

Pending release of v6.

### Documentation

https://www.graphql-tools.com/

### CODE REVIEW

**Comment by blainekasten** [comment]
Marking this as blocked until v6 is released, also assigning to @vladar who leads most of our graphql effort.

**Comment by yaacovCR** [comment]
Happy to help,

I also noticed you seem to have to work around a few issues in GraphQL compose when you are rebuilding a schema...

I wonder if using some of our utilities functions would help you out with that, as you can see from above, mapSchema let's you start from any initial schema and do the composition on built graphql schema objects.

Not really sure why you are rebuilding, what has changed and what hasn't and whether this would help you but just figured I would flag it.

We built some helper functions that can add types and modify object fields using the above approach, but there are additional possibilities that might help you as well.

**Comment by yaacovCR** [comment]
Upgrade to latest graphql-tools version, v6.0.9, also switched gatsby-recipes to use scoped packages for smaller bundle size.

Fix of interest: https://github.com/ardatan/graphql-tools/pull/1572

**Comment by yaacovCR** [comment]
Note that I did not change the metadata recipe to use the newer functional directive approach. We are hoping to still provide backwards compatibility with the current approach.

Also, populating metadata is still an unresolved issue overall, with the guidance from graphql-js to use the extensions field for graphql objects, but no built-in approach to populating it. I think that the eventual solution (possibly built on something like graphql-tools's functional directive approach?) should really be in graphql-js, and it seems counterproductive to iterate through multiple interim solutions.

**Comment by vladar** [comment]
Sorry for the delay with this. We are having a company event this week, so I will revisit it the next week.

Also can you please post a separate PR for `gatsby-recipes` changes? The reason is that we're using [conventional commits](https://www.conventionalcommits.org/en/) and ideally, single PR should affect a single package.

**Comment by yaacovCR** [comment]
@johno

**Comment by yaacovCR** [comment]
Hmmm, looks like Gatsby recipes changes made it, but not this one...

**Comment by yaacovCR** [comment]
@vladar @johno let me know if I messed up something....

**Comment by vladar** [comment]
Can you rebase or merge master? I am going to test it locally first thing tomorrow and then we can merge if everything is fine!

**Comment by vladar** [comment]
Actually the fix was a quick one (just pushed). Trying to resolve conflicts and make the tests pass, which is harder :)

**Comment by vladar** [comment]
Published in `gatsby-source-graphql@2.6.0`

**Pull request merged**
