### PR TITLE
feat(gatsby-source-contentful): add option to resolve custom nested entity references

### PR DESCRIPTION
**Pull request by jheung**
## Description

👋 First PR here, so any help is appreciated! 

Currently, the `gatsby-source-contentful` plugin does not resolve nested entity references in custom JSON object fields. This can be solved by manually create a schema and adding a resolver but would require the developer to add the entity types and update the schema every time the content model is updated or a new content model is created and usable as a reference. I propose to extend the plugin option to allow developers to define field keys where the resolver should attempt to resolve any references inside of it.

### Example use case

To simplify templating / page layout and to reduce the cognitive load of multiple nested entries, a UI extension is created which allows the end-user to define the desired column size for each breakpoint for a group of component entries (think `wrapper[] > column{} > settings + components[]`). The developer would now be able to configure Gatsby to dynamically loop through this wrapper field and render out nested components based on the settings provided without having to define custom schemas or maintaining it (from the sourcing perspective, logic would still need to be defined for querying/ rendering).

#### Content Model - Field configuration
Inside of Contentful, a JSON field would be created as either an array or an object (either manually inputted or controlled via an extension/app) with any field id.

If an array, it expects an array of objects with N keys with the [Contentful's data structure used to define links](https://www.contentful.com/developers/docs/concepts/links/).

```
contentfulFieldId: [
  {
    items: [
      {
        "sys": {
          "id": "1rCAg2qyLJdLmk4W3SRadQ",
          "type": "Link",
          "linkType": "Entry"
        }
      }
    ],
    item: {
      "sys": {
        "id": "1rCAg2qyLJdLmk4W3SRadQ",
        "type": "Link",
        "linkType": "Entry"
      }
    },
    ...otherData
  }
]
```

Or as an object:

```
contentfulFieldId: {
  items: [
    {
      "sys": {
        "id": "1rCAg2qyLJdLmk4W3SRadQ",
        "type": "Link",
        "linkType": "Entry"
      }
    }
  ],  
  item: {
    "sys": {
      "id": "1rCAg2qyLJdLmk4W3SRadQ",
      "type": "Link",
      "linkType": "Entry"
    }
  },
  ...otherData
}
```

#### Gatsby configuration

Inside of `gatsby-config.js`, a new option, `nestedReferences` is added, and needs to be configured based on the use case. `key` refers to the contentful field ID and `referenceKey` refers to the key inside of the object which contains the link references.

For the above examples, we can define the configuration as:

```
{
  resolve: "gatsby-source-contentful",
  options: {
    ...baseConfig,
      nestedReferences: {
      fields: [
        { key: "contentfulFieldId", referenceKey: "items" },
        { key: "contentfulFieldId", referenceKey: "item" },
      ],
    },
  },
}
```

#### Gatsby / GraphQL Queries

With the updated changes, developers will now be able to query using inline fragments to retrieve nested references as if they were using the native reference field.

```
query MyQuery {
  allContentfulNestedReferences {
    nodes {
      contentfulFieldId {
        items {
          __typename
          ... on ContentfulTestEntity {
            ...testEntityModelFragment
          }
          __typename
          ... on ContentfulAnotherTestEntity {
            ...anotherTestEntityModelFragment
          }
        }
      }
    }
  }
}
````

### CODE REVIEW

**Comment by axe312ger** [comment]
Hey @jheung,

thank you for your time and effort.

Sorry, but for now, I won't accept your PR/code in the contentful-source-plugin for the following reasons:

* JSON with an array of (Contentful) links is literally a reference field in Contentful, you don't need to use the JSON field for this. Give it a try! :)
* If you want to have nested references, create a Content type with a multi reference field. This will allow you to create nested references.
* What you do is specific for your use case and none of the ways Contentful + Gatsby is intended to be used. (This is at least valid for the official gatsby-contentful plugin. You can of course do whatever you need in your projects)
* The plugins code & logic for reference resolving is already bloated and will be rewritten in the near future

If you can't reflect your use case with references and a new content type with a multi-reference field:

How about you create another Gatsby plugin specifically for your use case? You could accept a list of entity type/fields you want to extend and add resolvers.

That way you can keep your code and might get help from others with the same problem.


I hope that helped,
Benedikt

**Comment by axe312ger** [comment]
Closing for now. Feel free to convince me that my assumptions above are wrong. Then I happily reopen :)

**Comment by jheung** [comment]
Hey @axe312ger ,

I agree that this can be accomplished using the built-in references but figured that our team can't be the only ones who are constricted by Contentful's content model limit and having too many references to "placeholder/configuration" content models which made it harder for our editors to compose pages.

The core problem that this plugin address is that although Contentful allows you to create custom UI / App extensions, there is a gap within the plugin which limits what you can do with the references within Gatsby.

We were able to simplify the workflow by creating our own custom field that allows our editors to quickly "configure" the list of references.

Would love to have you take a look at it again - but will look into creating a specific plugin to handle this use case.

**Comment by axe312ger** [comment]
@jheung did you consider approaching Contentful itself about these limitations you and your team face?

**Pull request closed without merging**
