### PR TITLE
(fix gatsby - redux cache) Reduced chunk size buffer from 150 gb to 1.5 gb

### LINKED ISSUE #17233: V8 serialize error on build with huge number of pages(100k+)
## Description

Getting various issues(related to V8 serialize etc) when trying to build large number of pages(80k+ docs of 10kb each) with **latest gatsby+remark** resulting in the build failure.

Basically build crashes with below errors.

### Without loki

```sh
success run page queries - 2027.713 s — 3335/3335 1.64 queries/second

node[11428]: ../src/node_buffer.cc:412:MaybeLocal<v8::Object> node::Buffer::New(node::Environment *, char *, size_t): Assertion `length <= kMaxLength' failed.
1: 0x100033d65 node::Abort() [/usr/local/bin/node]
2: 0x100032dab node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
3: 0x100046ff5 _register_buffer() [/usr/local/bin/node]
4: 0x100098391 node::(anonymous namespace)::SerializerContext::ReleaseBuffer(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
5: 0x10022b83f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
6: 0x10022ad81 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
7: 0x10022a3d0 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
8: 0x23830e0841bd
9: 0x23830e093a09
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### With loki(`GATSBY_DB_NODES=loki`)

```sh
success run page queries - 1976.632 s — 3335/3335 1.69 queries/second

Stacktrace:
ptr1=0x25b9d2202321
    ptr2=0x0
    ptr3=0x0
    ptr4=0x0
    failure_message_object=0x7ffeefbed370

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x355f68c041bd]
    1: StubFrame [pc: 0x355f68c85ad7]
Security context: 0x25b9bbd9e6c9 <JSObject>
    2: saveState [0x25b910175701] [/Users/guns/public/node_modules/gatsby/dist/db/index.js:30] [bytecode=0x25b9097edb61 offset=181](this=0x25b90cd96279 <Object map = 0x25b90f1ad969>)
    3: /* anonymous */ [0x25b9850fee71](this=0x25b93d108c59 <JSGlobal Object>,0x25b9d2202321 <the_hole>)
    4: StubFrame [pc: 0x355f68c42871]
    5: StubFrame [pc: 0x355f68c21b9a]
    6: EntryFrame [pc: 0x355f68c0ba01]

==== Details ================================================

[0]: ExitFrame [pc: 0x355f68c041bd]
[1]: StubFrame [pc: 0x355f68c85ad7]
[2]: saveState [0x25b910175701] [/Users/guns/public/node_modules/gatsby/dist/db/index.js:30] [bytecode=0x25b9097edb61 offset=181](this=0x25b90cd96279 <Object map = 0x25b90f1ad969>) {
// stack-allocated locals
var .generator_object = 0x25baaacb2ee9 <JSGenerator>
var /* anonymous */ = 0x25baaacb2eb9 <Promise map = 0x25b9b4783e89>
// expression stack (top to bottom)
[11] : 0x25b9d2202321 <the_hole>
[10] : 0x25b9097ed889 <String[24]: Error persisting state: >
[09] : 0x25b921b04c89 <Object map = 0x25b983544361>
[08] : 0x25b9794ede29 <JSBoundFunction (BoundTargetFunction 0x25b9794ecbf1)>
[07] : 0x25b9101767b9 <FunctionContext[9]>
[06] : 0x25b9850ff331 <CatchContext[5]>
[05] : 0x25b9101767b9 <FunctionContext[9]>
[04] : 0x25b9101767b9 <FunctionContext[9]>
[03] : 0x25b90cd96279 <Object map = 0x25b90f1ad969>
[02] : 0x25b910175701 <JSFunction saveState (sfi = 0x25b9996e74f9)>
--------- s o u r c e   c o d e ---------
function saveState() {\x0a  if (saveInProgress) return;\x0a  saveInProgress = true;\x0a\x0a  try {\x0a    await Promise.all(dbs.map(db => db.saveState()));\x0a  } catch (err) {\x0a    report.warn(`Error persisting state: ${err && err.message || err}`);\x0a  }\x0a\x0a  saveInProgress = false;\x0a}
-----------------------------------------
}

[3]: /* anonymous */ [0x25b9850fee71](this=0x25b93d108c59 <JSGlobal Object>,0x25b9d2202321 <the_hole>) {
// optimized frame
--------- s o u r c e   c o d e ---------
<No Source>
-----------------------------------------
}
[4]: StubFrame [pc: 0x355f68c42871]
[5]: StubFrame [pc: 0x355f68c21b9a]
[6]: EntryFrame [pc: 0x355f68c0ba01]
=====================

error Command failed with signal "SIGILL".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Interestingly the build for 200k(4.5kb each post) runs successfully on `gatsby@2.3.19` which uses `JSON.stringify` to persist state(shows a redux persisting state warning, but everything works). 

### Steps to reproduce

Repro repo: [https://github.com/ganapativs/gatsby-v8-issue-repro](https://github.com/ganapativs/gatsby-v8-issue-repro) (README has everything related to the issue and other observations).

### Expected result

Build should be successful without `V8 serialize` error.

### Actual result

Build crashed with `V8 serialize` error. [`DANGEROUSLY_DISABLE_OOM`](https://github.com/gatsbyjs/gatsby/pull/14767) would have helped temporarily, but, it was removed recently 😅

### Environment

  **System:**
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.7.1 - /bin/zsh

  **Binaries:**
    Node: 10.6.0 - /usr/local/bin/node
    Yarn: 1.7.0 - ~/.yarn/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm

  **Languages:**
    Python: 2.7.16 - /usr/bin/python

  **Browsers:**
    Chrome: 76.0.3809.132
    Safari: 13.0

  **npmPackages:**
    gatsby: 2.14.0 => 2.14.0 
    gatsby-plugin-styled-components: 3.1.3 => 3.1.3 
    gatsby-remark-autolink-headers: 2.1.8 => 2.1.8 
    gatsby-remark-prismjs: 3.3.9 => 3.3.9 
    gatsby-remark-sub-sup: 1.0.0 => 1.0.0 
    gatsby-source-mongodb: 2.1.9 => 2.1.9 
    gatsby-transformer-remark: 2.6.19 => 2.6.19 

  **npmGlobalPackages:**
    gatsby-cli: 2.7.40

### PR DESCRIPTION
**Pull request by bebrian458**
## Description

One of my team members @j218 noticed a buffer issue when trying to run build on our gatsby app with large amounts of rich text content. 

Screen Shot 2020-03-05 at 10 41 24 AM

We were able to narrow it down to a redux caching issue. There seems to have been an attempt in fixing this by chunking the nodes. However, we noticed a slight math error. The intention was to chunk nodes to fit into a 1.5gb buffer, but the calculations indicate chunking for a 150gb buffer. Assuming that the [max buffer length of node is 2GB](https://stackoverflow.com/questions/8974375/whats-the-maximum-size-of-a-node-js-buffer), this calculation issue would create a huge chunk size if the the entries contained a large amount of content. Thus, the issue would always cause the number of chunks to equal one (essentially performing no actual chunking) and cause the issue shown in the screenshot above.

We have made the fix to chunk the nodes to fit into a 1.5 gb cache.

Fixes #17233

### CODE REVIEW

**Comment by blainekasten** [comment]
cc @pvdz

**Comment by blainekasten** [comment]
@bebrian458 a sort of weird nit, do you mind getting rid of the commits that include Hashim's 100 days of Gatsby blog post?

**Comment by pvdz** [comment]
That's not a weird nit! My typo isn't weird! Code review isn't weird!

But also, thank you. That's a weird error indeed :(

**Comment by pvdz** [comment]
But. That probably means my fixes unblocked you. I'm happy about that :D

**Comment by blainekasten** [comment]
Just published a patch under `gatsby@2.19.29`. Thanks for the quick PR!

**Pull request merged**
