### PR TITLE
fix(www): removing section in "Converting a Starter to a Theme"

### LINKED ISSUE #23197: [www] Found outdated section in Themes docs
## Description

The page "Converting a Starter to a Theme" has a section on [Sourcing Pages](https://www.gatsbyjs.org/docs/themes/converting-a-starter/#sourcing-pages). This is no longer relevant as it is built into Gatsby core with this PR #16698

### PR DESCRIPTION
**Pull request by lannonbr**
## Description

Closes #23197. This is no longer needed as gatsby-plugin-page-creator is baked in by default.

### CODE REVIEW

**Comment by lannonbr** [comment]
@wardpeet updated with your suggestions

**Comment by wardpeet** [comment]
Thanks @lannonbr. I'll wait for the documentation team to make sure my rewrite is following the specs.

**Comment by lannonbr** [comment]
@laurieontech Looks like you merged in #23572. Let me resolve the merge conflict and then could we merge the rest of this in as well?

**Comment by laurieontech** [comment]
Yup, this looks good!

**Pull request merged**
