### PR TITLE
FIx highlighted (newly added) lines in Source Plugin Tutorial

### PR DESCRIPTION
**Pull request by igghera**
Perhaps the plugin used to highlight lines starts from 0 while lines start from 1?
I know it's nit-picking, but I've always wanted to contribute to this project :)

### CODE REVIEW

**Comment by DSchau** [comment]
@igghera it looks like the line highlighting is correct to me! It's showing the whole HTTP process (e.g. options, url, etc.).

Do you see something different? It seems like this approach would start a line below apiOptions, which I don't think is what we want

screen shot 2018-10-04 at 1 27 53 pm

**Comment by amberleyromo** [comment]
@DSchau it looks like this change moves it up a line (to encompass the connected comment, and not include that last bracket) which would be correct

**Comment by DSchau** [comment]
@amberleyromo good catch! Thanks for sanity checking me :)

**Comment by igghera** [comment]
Yeah, it's such a small change that it was hard to notice. I guess it's easier when you follow along the tutorial and copy/paste the highlighted lines, as it happened to me. That last bracket was confusing, that's all. Thanks for the quick response guys! Hopefully next time I can contribute with something more important :)

**Comment by DSchau** [comment]
@igghera to be clear, this is a very valuable/important contribution! Anything helps, and whether or not you realize it, this is certainly a meaningful one! It could avoid some confusion for someone in the future too, and that's a win!

So thank you!

**Pull request merged**
