### PR TITLE
Added gatsby-plugin-netlify-headers

### PR DESCRIPTION
**Pull request by pk-nb**
As noted in #1584, netlify supports custom headers [through a `_headers` file](https://www.netlify.com/docs/headers-and-basic-auth/). Through this mechanism, you can enable HTTP/2 server push and other features such as basic auth. Obviously this is a great feature if you are hosting on netlify, so I've added a plugin to easily enable server push and any other headers you may want to add for different routes.

I recommend reading through the README, but in short, the plugin will create a sensible default with no config, which includes the critical scripts already marked with `preload`. Since many assets will be hashed through the bundle process, the plugin is smart enough to map through the webpack manifest if possible. Otherwise, it will ensure the path is valid (for things that may have been copied through the `static` folder.

Sample output:

screen shot 2017-09-17 at 9 15 41 pm

Happy developer errors to avoid silent issues:

screen shot 2017-09-17 at 8 19 05 pm

screen shot 2017-09-17 at 8 42 51 pm

Hopefully I've added everything correctly here. Let me know know what you think—would love to do work to get this in soon!

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Sweet!! Been looking forward to this :-) haven't looked at the code yet but looks like this is already quite featureful!

Could you add it to gatsbyjs (/www) so it's working there/we can test it out?

Also could you add long term caching for everything in /static? Netlify forces change checks on everything by default but files in static are safe to cache due to their content digest based filenames.

**Comment by pk-nb** [comment]
Hopefully this is right for caching—let me know if we need to remove / add. Going to add the www integration now.

screen shot 2017-09-17 at 10 38 12 pm

**Comment by pk-nb** [comment]
Added to www, though not sure if it's working / how to test since it's not a published package yet.

**Comment by KyleAMathews** [comment]
I'll publish a canary release so it builds in the morning and we can test things then 👍

**Comment by KyleAMathews** [comment]
So looks like static assets are being cached correctly! Yeah!

But it looks like the push syntax is off. I got things building on Netlify here: https://deploy-preview-2152--gatsbyjs.netlify.com/

But when you look at the response headers for a resource you see stuff like this

screen shot 2017-09-18 at 7 07 17 am

**Comment by pk-nb** [comment]
When I inspect in the chrome dev tools (Chrome 60), it seems to be working for me! It's a little hard to tell, but you can see effect in the "initiator" in addition to the network waterfall. The timing tab will also show the push information.

screen shot 2017-09-18 at 10 26 01 am

screen shot 2017-09-18 at 10 28 12 am

**Comment by pk-nb** [comment]
Amusingly, I can't find the effect of the caching header on `static` on that site

**Comment by KyleAMathews** [comment]
Oh cool! Yeah it is definitely working for some. It looks like it's just the app/commons bundles that aren't being pushed.

**Comment by pk-nb** [comment]
Strange—maybe I formatted the wildcard incorrectly. Or maybe netlify isn't correctly combining `Link` headers across paths? I'll take a look later today

**Comment by pk-nb** [comment]
I tested this locally and the generated headers are correct. The issue seems to be with Link headers not getting inherited across paths (while all other headers are). I asked support and messaged here https://gitter.im/netlify/community?source=orgpage, and am waiting for a response.


If we are stuck with the existing behavior, I can inject the common and app bundles on each page. Hoping we can fix though, as this approach makes it difficult to add more custom Link headers (a user would have to specify _every_ route to add another link, rather than the root wildcard `/*`).

**Comment by pk-nb** [comment]
screen shot 2017-09-19 at 3 04 46 pm

Got an answer—apparently they don't do inheritance (any matching headers are replaced). I'll update later to include the link header for every path, rather than globally. I'll add a mechanism to add additional links to every path.

**Comment by pk-nb** [comment]
@KyleAMathews I updated the plugin to work around the overridden links for app and common. I also added a new config option to easily add links to each page (for things like a logo image).

The default plugin output is this:

screen shot 2017-09-19 at 6 57 44 pm

And with some config like the following: 

```js
{
  resolve: "gatsby-plugin-netlify-headers",
  options: {
    allPageHeaders: [
      "Link: </static/large.png>; rel=preload; as=image",
      "Link: </lucky.png>; rel=preload; as=image"
    ],
  }
}
```

You get this output:

screen shot 2017-09-19 at 6 57 11 pm

I'd love to try it again with another deploy—it should server push all of the JS now.

**Comment by KyleAMathews** [comment]
It automatically rebuilds when you push so it's already live. And just checked and all the bundles are getting pushed now!!!

**Comment by KyleAMathews** [comment]
Oh hmmm… apparently Netlify isn't compressing pushed content.

* http://www.webpagetest.org/result/170919_KF_a122dfcc41407ac7d8867c5a4c3f7207/
* http://www.webpagetest.org/result/170919_CZ_6e4472adde7c83fc8a39135046d8eaa6/

The first is the deploy preview — it now has a "F" on "Compress Transfer" because all the pushed JS files are uncompressed. Perhaps because of that, the time to interactive is almost identical between the two.

**Comment by pk-nb** [comment]
Glad it's working—but that's really disappointing on the compression. Should file a ticket with them

**Comment by KyleAMathews** [comment]
Got this response back:

>Right now you can't gzip when you use http2 push. We have an open issue for this that David is looking into. We'll let you know when it's supported.

So I'd suggest we just disable the push functionality for now and publish the plugin without it. Adding static caching + easy ability to add other global headers is a great start and we can enable push once it's ready on Netlify.

**Comment by pk-nb** [comment]
Awesome! Thanks for checking with them—and glad they are working on it. I'll disable on www right now—and the plugin should be ready to go once you are happy with the code.

**Comment by KyleAMathews** [comment]
Oh I meant disable http/2 push not disable the plugin altogether :-)

We still should have static assets be cached for example.

**Comment by pk-nb** [comment]
Done

**Comment by KyleAMathews** [comment]
🎉 

Thanks for taking this on!

**Comment by pk-nb** [comment]
It was fun! Thanks for taking the time to review!

**Comment by CallMeLaNN** [comment]
I just play around this plugin with `mergeLinkHeaders: true` option since it was disabled by default. Apparently Netlify already compress the pushed js files:

netlify push gzip

**Comment by KyleAMathews** [comment]
@CallMeLaNN oh nice! Yeah Netlify when we first played with this wasn't gzipping pushed assets. You want to PR a change to gatsby-plugin-netlify so push is enabled by default now?

**Comment by jlengstorf** [comment]
Hiya @pk-nb! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
