### PR TITLE
[1.0] WIP infer deep object input type

### PR DESCRIPTION
**Pull request by 0x80**
Trying to use a nested object in the graphql input data resulted in errors. I've added the deep object test and this result in the following error. Will try to look into it further.

```
● GraphQL Input args › encountered a declaration exception

    RangeError: Maximum call stack size exceeded
      
      at node_modules/flat/index.js:16:41
      at Array.forEach (native)
      at step (node_modules/flat/index.js:16:25)
      at node_modules/flat/index.js:32:16
      at Array.forEach (native)
      at step (node_modules/flat/index.js:16:25)
      at flatten (node_modules/flat/index.js:39:3)
      at reduceSubNode (packages/gatsby/lib/schema/data-tree-utils.js:15:21)
      at packages/gatsby/lib/schema/data-tree-utils.js:30:14
      at Array.reduce (native)
      at Object.<anonymous>.exports.extractFieldExamples (packages/gatsby/lib/schema/data-tree-utils.js:10:24)
      at Object.<anonymous>.exports.inferInputObjectStructureFromNodes (packages/gatsby/lib/schema/infer-graphql-input-fields.js:155:23)
      at Object.<anonymous>.exports.inferGraphQLInputFields (packages/gatsby/lib/schema/infer-graphql-input-fields.js:122:19)
      at packages/gatsby/lib/schema/infer-graphql-input-fields.js:163:25
```

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@0x80 is this still needed?

**Comment by 0x80** [comment]
@KyleAMathews Yes it seems relevant still. For example, this works with the current HEAD
```
[{
  "title": "Some test",
  "slug": "test",
  "type": "_",
  "summary": "_",
  "xcontent": "_",
  "coverImage": {
    "url": "_",
    "size": 720368,
    "width": 2876,
    "height": 1792
  },
  "date": "2015-11-01",
  "dateEnd": "2015-11-01"
}]
```

But this breaks
```
[{
  "title": "Some test",
  "slug": "test",
  "type": "_",
  "summary": "_",
  "xcontent": "_",
  "coverImage": {
    "url": "_",
    "details": {
       "size": 720368,
       "width": 2876,
       "height": 1792
    }
  },
  "date": "2015-11-01",
  "dateEnd": "2015-11-01"
}]
```

**Comment by jquense** [comment]
Breaking in my PR tho I believe is a matter of finishing up null handling. It _should_ be doing a more complete inference and traversal. 

It be super helpful tho if we could work up tests like this that fail to really harden those bits. For instance right now all tests pass!

**Comment by 0x80** [comment]
@jquense Do you want me to help out by committing to your branch? I would for example add the test that you see in this PR.  

I had a bit of a hard time understanding the tests last time I checked, but I think that was partially because I still lack some basic graphql knowledge. I'm getting a bit swamped with work atm so I don't have many hours left to work on Gatsby right now, but I'll help out if I can.

**Comment by jquense** [comment]
@0x80 thanks but I think i'm sorted at this point, no need to jump in :)

**Comment by KyleAMathews** [comment]
@0x80 what's the status here? Does this PR still need to get in?

**Comment by 0x80** [comment]
@KyleAMathews I'll give it a try. I converted my data to flat object structures since, so I don't really know / need it anymore.

**Comment by 0x80** [comment]
@KyleAMathews the snapshots in the 1.0 HEAD seemed to be outdated. But apart from that adding the deep object to the test structure doesn't seem to break the tests like it used to. I didn't write any test to verify the object fields yet.

**Comment by KyleAMathews** [comment]
Cool, glad to hear its working. Let's still get this in with your tests (more tests the merrier) and the snapshot updates.

**Comment by KyleAMathews** [comment]
Closing this now

**Pull request closed without merging**
