### PR TITLE
fix netlify cms admin path redirect

### PR DESCRIPTION
**Pull request by erquhart**
Quick Netlify CMS plugin update to redirect Netlify Identity logins to the right path.

### CODE REVIEW

**Comment by pieh** [comment]
Should this try to handle path prefix ( https://next.gatsbyjs.org/docs/path-prefix/ )? if so  it would need to be:
```diff
-document.location.href = `/admin/`
+document.location.href = `${__PATH_PREFIX__}/admin/`
```

**Comment by erquhart** [comment]
Did not know about that, I'll update. That brought another of our own config options to mind as well, thanks.

**Comment by erquhart** [comment]
@pieh can you confirm that `__PATH_PREFIX__` is set to an empty string when not set?

**Comment by pieh** [comment]
Yes, it's empty string if user doesn't specify it otherwise - https://github.com/gatsbyjs/gatsby/blob/8ae9a196061f8467a2ad790ac6d777aea62432ae/packages/gatsby/src/utils/webpack.config.js#L179-L181

**Comment by erquhart** [comment]
Awesome, thank you. Update comin'.

**Comment by pieh** [comment]
Travis have some problems with reporting status but tests passed - https://travis-ci.org/gatsbyjs/gatsby/builds/426915204 so going to merge that in

**Pull request merged**
