### PR TITLE
docs(gatsby-source-wordpress): Remove lodash + bluebird + fix Promise hell

### PR DESCRIPTION
**Pull request by DylanTackoor**
## Description

This commit:
- Removes lodash in favor of Array.forEach
- Bluebird in favor of the native Promise object
- Avoids nested thenables by using Promise.all()

I've been using this code in my builds and it's been working fine for whatever that worth :)

### CODE REVIEW

**Comment by DylanTackoor** [comment]
Looks like the Azure Pipeline task has a bug pulling something with Yarn, but the code works otherwise 😱

```
2019-02-13T15:46:04.3801464Z ##[section]Starting: CmdLine
2019-02-13T15:46:04.3911190Z ==============================================================================
2019-02-13T15:46:04.3911250Z Task         : Command Line
2019-02-13T15:46:04.3911288Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
2019-02-13T15:46:04.3911345Z Version      : 2.146.1
2019-02-13T15:46:04.3911378Z Author       : Microsoft Corporation
2019-02-13T15:46:04.3911415Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2019-02-13T15:46:04.3911468Z ==============================================================================
2019-02-13T15:46:05.7867622Z Generating script.
2019-02-13T15:46:05.7991716Z Script contents:
2019-02-13T15:46:05.7998822Z yarn bootstrap
2019-02-13T15:46:05.8597677Z ##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\bd085075-59cf-4de0-85c0-3b4f065420e8.cmd""
2019-02-13T15:46:15.0653626Z yarn run v1.13.0
2019-02-13T15:46:15.1773258Z $ yarn
2019-02-13T15:46:16.5975153Z [1/4] Resolving packages...
2019-02-13T15:46:18.2236144Z [2/4] Fetching packages...
2019-02-13T15:47:28.6084712Z error An unexpected error occurred: "https://registry.yarnpkg.com/@xtuc/long/-/long-4.2.1.tgz: Request failed \"502 Bad Gateway\"".
2019-02-13T15:47:28.6085038Z info If you think this is a bug, please open a bug report with the information provided in "D:\\a\\1\\s\\yarn-error.log".
2019-02-13T15:47:28.6085885Z info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2019-02-13T15:47:38.7696222Z error Command failed with exit code 1.
2019-02-13T15:47:38.7697806Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2019-02-13T15:47:39.0497956Z ##[error]Cmd.exe exited with code '1'.
2019-02-13T15:47:39.0894802Z ##[section]Finishing: CmdLine
```

**Comment by DylanTackoor** [comment]
> Would you be interested in refactoring with async/await? (see #11548 for more info on that!)

I initially had an async/await version but decided on this approach as Promise.all() should be faster as both Promises execute in parallel this way :D

**Comment by DSchau** [comment]
@DylanTackoor you can (and should!) use Promise.all with async/await ;)

Using one does not preclude the other.

**Comment by DylanTackoor** [comment]
Sweet, thanks for the tip! I'll update the PR later today when I have a chance 😊

**Comment by DylanTackoor** [comment]
@DSchau I ended up avoiding using Promise.all() in favor of a single async GraphQL query. Thoughts?

**Comment by DylanTackoor** [comment]
Fixed it! Also took the chance to destructure the data property.

**Comment by wardpeet** [comment]
Merged master and ran prettier

@DSchau mind taking another look?

**Pull request merged**
