### PR TITLE
[gatsby-source-drupal] relationship handling improvments

### PR DESCRIPTION
**Pull request by pieh**
- add support for relationships with many values (arrays)
- fix back refs not showing for entities without any relationships
- **BREAKING CHANGE** change backrefs to arrays as we can't ensure that backref will have single value

There is also one more breaking change I'd like to add here, but need to consult first:

Right now back references are added with names of referencing types - so if we would have hypothetical node type "Product" and 2 fields: "cross_sell" and "up_sell" than links to other products then both backrefs would all be dumped into single `node__product` field and we couldn't differentiate if current product is in cross-sell or up-sell relationship.

Proposed solution:
Use name of relationship as base for back reference field name - maybe something like `back_${relationship_name}` and maybe allow setting that name in plugin settings:
```
back_references: {
  `node__product.up_sell` : `is_up_sell_for`
}
```

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Oh interesting — yeah, making the backref fields more explicit makes a lot of sense. What's the usecase for making those overridable in the plugin config?

**Comment by pieh** [comment]
> What's the usecase for making those overridable in the plugin config?

Sorry, I've missed that yesterday.

So situation was that content node had field name `belongs_to_category` linking to taxonomy terms. When I changed back ref name from type name to `back_field_belongs_to_category` it looked like this

```gql
taxonomyTermCategories {
  relationships {
    back_field_belongs_to_category {
      # this is content node, but field name is a bit confusing
      # allowing to name it like "linked_content_node" would make schema more self documented
      # but we can't do that automatically because there would be issue described with 
      # "cross-sell" / "up-sell" scenario in PR description
      title
    }
}
```

I'm not convinced that proposed solution is best (or even good) - not sure what's the nicest way to handle this

**Comment by dubcanada** [comment]
I like this as it stands, tested it in my environment and it works.

I am not sure about the second part, maybe make a todo for that so we can discuss? I am not sure I follow you, are you saying if both fields have the same machine name? Cause you can type different them, they would be added as multiple different types and you would just use

    ... on field_type {}

To get the specific one you want, so for paragraphs you can use

    ... on paragraph_machine_name{}

But maybe I don't follow what you are saying 📦 

👍

**Comment by eojthebrave** [comment]
This PR is working well and solving some problems I was encountering.

FWIW. This merges cleanly with the V1 branch. Should it be re-rolled for Gatsby V2 (master branch)? And then back-ported for V1?

**Comment by KyleAMathews** [comment]
@pieh you want to revisit this and get it landed in v1/master?

**Comment by pieh** [comment]
Yeah, I'll update this so it can be merged to master before I open any new PR - but will have to handle https://github.com/gatsbyjs/gatsby/pull/6261 first

**Comment by eojthebrave** [comment]
Let me know if there's anything I can do to help, and/or test things.

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 3de31d7124b45e2f3c99533d8c28c30ab9285422

https://app.netlify.com/sites/using-postcss-sass/deploys/5b507075e39e7c14c2426131

**Comment by pieh** [comment]
@mglaman can You pull and check again?

**Comment by mglaman** [comment]
Rad! I'll test after my commute and report back

**Comment by mglaman** [comment]
graphiql_and_commerce2x____drupal_sites_commerce2x__-_____gatsby_plugins_gatsby-source-drupal-fork_gatsby-node_js__commerce2x_

Amazing! It fixes the error, and now the query is returning all of my variations!

 💯  💯  💯  💯  💯

**Comment by pieh** [comment]
> It fixes the error, and now the query is returning all of my variations!

That's great to hear! I was about to install docker to setup demo site that would actually test those changes (was doing test driven dev on this on today) :)

> I'm still seeing one issue, but I honestly think it could be done in a follow up, so that multiple valued references can at least be fixed first.

Do You have your site hosted somewhere (I seeYou use local url) so I could debug this issue? If so please let me know - either here or via mail if You don't want to show this publicly (misiek.piechowiak@gmail.com)

**Comment by mglaman** [comment]
@pieh :) here is a site! http://dev-commerce2x-jsonapi.pantheonsite.io/jsonapi

Took a little to get set up (haven't used Pantheon in a long time)

Here is the Gatsby setup I am using https://github.com/mglaman/gatsbyjs_commerce_demo

**Comment by pieh** [comment]
I just checked that locally it all 3 taxonomies show up in relationships (at least for `commerce_product/simple`):
drupal-categories

So I would suspect this is related to how we construct schema - we do that from actual data - so if none of Your products have assigned any Brand / Categories / Special categories, then it won't show up in schema. For testing purpose You can create dummy category and add it to dummy product to force those fields appear in schema.

Let me know if what I wrote make sense and is actually valid in Your case!

**Comment by mglaman** [comment]
Hm, weird. I think my local was just messed up. When I ran this query against that sandbox environment all was great!

```
query test {
  allCommerceProductClothing {
    edges {
      node {
        title
        id
        relationships {
          field_brand {
            id
          }
          field_product_categories {
            id
          }
          variations {
            id
            sku
            relationships {
              attribute_size {
                id
              }
              attribute_color {
                id
              }
              field_images {
                localFile {
                  id
                  relativePath
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by mglaman** [comment]
@pieh thanks so much for helping unblock this :)

**Comment by pieh** [comment]
This is ready for review

**Comment by pieh** [comment]
I'll just merge it (it being opened for 3 months really bugs me) and if it cause problems it will be additional motivation to fix those :)

**Comment by luke-dare** [comment]
Great work .. this is definitely something I'm going to need for a site I'm working on.

Is a release planned for the near future?

**Pull request merged**
