### PR TITLE
feat(gatsby-source-filesystem): Added an 'ignore' property to the options to ignore more files.

### PR DESCRIPTION
**Pull request by Mike-Dax**
One of my clients uses a markdown editor that saves `.~<filename>` temporary files in an auto-save context. These get eaten up by the gatsby-source-filesystem plugin and can cause issues.

This PR allows for an `ignore` array in the options to specify more regex's to ignore.

```
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/packages/pages`,
        name: 'pages',
        ignore: [`**/\.*`],
      },
    },
```

I would argue that adding `**/\.*` to the default list of ignores (ignore dot files) would be a sane default, but that might be considered a breaking change?

I can amend this PR with that change / make a second PR if desired.

### CODE REVIEW

**Comment by nihgwu** [comment]
You are the man! https://github.com/gatsbyjs/gatsby/pull/8017

**Comment by nihgwu** [comment]
please add doc for the new option

**Comment by Mike-Dax** [comment]
@nihgwu Heh, that's a funny coincidence.

I wrote a small note in the README.md of gatsby-source-filesystem. Happy to write more docs if I can be pointed to where they should go.

**Comment by pieh** [comment]
Very nitpicky - could you update list of default ignored stuff ( it was changed very recently in https://github.com/gatsbyjs/gatsby/pull/8017 )

**Comment by pieh** [comment]
Travis has some problems with reporting status but tests passed - https://travis-ci.org/gatsbyjs/gatsby/builds/426692369 so I'm going to merge that in

**Comment by KyleAMathews** [comment]
Any reason to ignore all dot files?

**Comment by Mike-Dax** [comment]
@KyleAMathews I would think it would be unlikely that someone intended for dot files to produce content. Unfortunately chokidar doesn't seem to have any method for whitelisting files explicitly if that is the intention and 'no dot files' is the default.

Some editors unfortunately pollute the file system with autosave files with a dot prefix, if they're pages with page queries that can cause this error:

```
GraphQL Error There was an error while compiling your site's GraphQL queries.
  Invariant Violation: GraphQLCompilerContext: Duplicate document named `ReleaseIndexQuery`. GraphQL fragments and roots must have unique names.
    t: Duplicate document named `ReleaseIndexQuery`. GraphQL fragments and roots must have unique names.
```

**Pull request merged**
