### PR TITLE
Infer input fields from setFieldsOnGraphQLNodeType

### LINKED ISSUE #1931: setFieldsOnGraphQLNodeType does not add fields as input arguments
When I call `setFieldsOnGraphQLNodeType` I expect to be able to use those fields in my GraphQL queries to filter documents just as if the field was included in the original type. I guess it's possible to use `createNodeField` instead, as that can be used as an input field, but it doesn't feel as clean.
 Input fields /arguments are inferred at https://github.com/gatsbyjs/gatsby/blob/524ff171cd890b79ce9535d6dc10550c70365d33/packages/gatsby/src/schema/build-node-types.js#L140 and we can see that fields from plugins are not included.

### PR DESCRIPTION
**Pull request by Zalastax**
Makes fields added by `setFieldsOnGraphQLNodeType` filterable and sortable.
I didn't see any uses of `setFieldsOnGraphQLNodeType` in the tests so adding new tests felt like a non-starter.

Closes #1931

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 73ebcc5f74a62283641c72a6e3cbba299d938d45

https://app.netlify.com/sites/using-glamor/deploys/59b562b8cf321c7aaed3fe17

**Comment by KyleAMathews** [comment]
Hey! From a quick read through everything looks very sensible & workable. Thanks!

Would love some tests for the new functionality. The reason there's not any existing tests is core to this point has had nothing to do with `setFieldsOnGraphQLNodeType` so if things failed, it was on the userland code to handle it. The GraphQL schema inference parts of the code are complex & core to Gatsby so we need to keep them very well tested.

**Comment by Zalastax** [comment]
Good, no problem. It would really help if you can show me how to add usage of `setFieldsOnGraphQLNodeType` to the tests, if you have the time.

**Comment by KyleAMathews** [comment]
@Zalastax awesome! Basically what you want to do is simulate creating various schemas with different GraphQL types using`setFieldsOnGraphQLNodeType` and assert that the correct connection input fields are being created.

Some of the tests in here should be a good guide: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby/src/schema/__tests__

**Comment by KyleAMathews** [comment]
Happy to answer more questions about the process as you dive in!

**Comment by Zalastax** [comment]
How do I mock [`api-runner-node`](https://github.com/Zalastax/gatsby/blob/0f8bffaaac491cd0ed015f7764e8acd2289bade0/packages/gatsby/src/schema/build-node-types.js#L129-L133)? If my test can provide the result of that call, then the rest is a piece of cake. I could of course change the code to instead provide the result of `` await apiRunner(`setFieldsOnGraphQLNodeType` `` to `createType`, but it seems nicer to create some fake plugins.

**Comment by KyleAMathews** [comment]
No need to mock it, that's overkill. Just manually add additional GraphQL fields that aren't in the node data.

**Comment by Zalastax** [comment]
But I need https://github.com/Zalastax/gatsby/blob/0f8bffaaac491cd0ed015f7764e8acd2289bade0/packages/gatsby/src/schema/build-node-types.js#L129-L133 to get a list of fields to add? Sorry if I'm missing something.

**Comment by KyleAMathews** [comment]
There's nothing special about that code. It just calls plugins and gets an array of graphql fields.  You're testing the inference code not how gatsby gets fields from plugins.

**Comment by Zalastax** [comment]
Ah, you mean to just test https://github.com/Zalastax/gatsby/blob/0f8bffaaac491cd0ed015f7764e8acd2289bade0/packages/gatsby/src/schema/infer-graphql-input-fields-from-fields.js#L178, not the whole https://github.com/Zalastax/gatsby/blob/0f8bffaaac491cd0ed015f7764e8acd2289bade0/packages/gatsby/src/schema/build-node-types.js#L28. Sure thing!

**Comment by Zalastax** [comment]
@KyleAMathews I'm quite happy with this now 😃. Tell me if you need something more before merging.

**Comment by KyleAMathews** [comment]
Hey this looks really really good! Thanks for adding this! Some tricky code but definitely fills in a big missing piece to Gatsby's GraphQL story 🙏

**Comment by jlengstorf** [comment]
Hiya @Zalastax! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
