### PR TITLE
Update on Gatsby Windows instructions

### PR DESCRIPTION
**Pull request by sebastienfi**
After solving this myself

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit ca83af533c0c6a090fa8158f98796b23725ad5ec

https://app.netlify.com/sites/using-postcss-sass/deploys/59497fe76f4c5007c37b16bd

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit ca83af533c0c6a090fa8158f98796b23725ad5ec

https://app.netlify.com/sites/using-contentful/deploys/59497fe86f4c5007c37b16cc

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit ca83af533c0c6a090fa8158f98796b23725ad5ec

https://app.netlify.com/sites/image-processing/deploys/59497fe86f4c5007c37b16c3

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit ca83af533c0c6a090fa8158f98796b23725ad5ec

https://app.netlify.com/sites/gatsbyjs/deploys/59497fe76f4c5007c37b16b1

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit ca83af533c0c6a090fa8158f98796b23725ad5ec

https://app.netlify.com/sites/gatsbygram/deploys/59497fe76f4c5007c37b16b4

**Comment by jlengstorf** [comment]
Hiya @sebastienfi! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
