### PR TITLE
Package Library fixes

### PR DESCRIPTION
**Pull request by fk**
Mainly fixes things for Mobile Safari by "unfixing" the sidebar for small screens; see the video @LeKoArts posted in #4411. Also ensures the "Load more" button and the Algolia credit being visible, and removes the inset box-shadow for _all_ sidebars.

Will take a final look tomorrow. ✌️

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 5d8dabe1ccc13348d301c1b897510a815935e23f

https://app.netlify.com/sites/using-glamor/deploys/5aa0caf3a6188f678c20d88b

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by fk** [comment]
GTG now, fixes (most of) #4411—can't do much more about the "Load more" button without overcomplicating things IMO.

**Comment by KyleAMathews** [comment]
💯

**Pull request merged**
