### PR TITLE
chore: lint all shell scripts

### PR DESCRIPTION
**Pull request by cone56**
## Description

Fix linting in shell scripts to conform to [ShellCheck](https://github.com/koalaman/shellcheck) standards. ShellCheck is a static analysis tool that offers suggestions to catch potential warnings and errors.

Specifically, the following rules have been fixed: [SC1090](https://github.com/koalaman/shellcheck/wiki/SC1090), [SC1117](https://github.com/koalaman/shellcheck/wiki/SC1117), [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086), [SC2129](https://github.com/koalaman/shellcheck/wiki/SC2129), [SC2148](https://github.com/koalaman/shellcheck/wiki/SC2148) and [SC2164](https://github.com/koalaman/shellcheck/wiki/SC2164)

### Documentation

N/A

## Related Issues

N/A

### CODE REVIEW

**Comment by cone56** [comment]
@vladar: Agreed - I've dropped changes related to rule SC1117

**Comment by muescha** [comment]
Should it be helpful to add some scripts to `package.json` so it can be rerun regularly by contributors?

**Comment by cone56** [comment]
@muescha: yep, good idea. Something like this?

`package.json`:

```javascript
"lint:scripts": "sh scripts/lint-shell-scripts.sh",
```

`scripts/lint-shell-scripts.sh`: 

```sh
#!/bin/bash

if ! [ -x "$(command -v shellcheck)" ]; then
  echo 'ShellCheck not found.'
  echo 'For more info: https://github.com/koalaman/shellcheck#installing"'
  exit 1
fi

shellcheck **/*.sh
```

Should I open another PR?

**Comment by muescha** [comment]
@wardpeet or @vladar from the core team should decide this

**Comment by vladar** [comment]
Makes sense for me as we already have linters for other things.

**Comment by cone56** [comment]
Ok, done; PR here: https://github.com/gatsbyjs/gatsby/pull/20094

**Pull request merged**
