### PR TITLE
Feature (www): Language dropdown

### PR DESCRIPTION
**Pull request by tesseralis**
## Description

Language dropdown to toggle between different pages.

How to get it to work locally:

* check out this branch
* enable a language by setting `LOCALES` in `.env.development`

TODO: 

* Disable if localization is not enabled
* a11y audit

### CODE REVIEW

**Comment by tesseralis** [comment]
Screenshots:

Closed

Screen Shot of gatsbyjs.org with closed language dropdown

Open

Screen Shot of gatsbyjs.org with open language dropdown

**Comment by fk** [comment]
Yay, nice seeing this come together! 🙏 
Took a quick look:

- Would be nice if the dropdown could have `borderRadius: 2` / `theme.radii[2]`.
- IMO all items on the right side of the header navigation should be the same color. Could you please use `grey.50` for the "Language" link, the "social icons" and the "dark/light mode" switch?  image  
  I did so in the [design](https://www.figma.com/file/UcsUDRdCoJaQdfITkcKMnU/Language-toggle-UI?node-id=1%3A614), and I think it works OK:  
  Tutorial_ English
- I think we can optimize for smaller screens a bit more, e.g. instead of this  
  image  
  we could show just the "Languages" icon, and not hide the "social" (at least the GitHub) and "theme switcher" links?

**Comment by tesseralis** [comment]
@fk I'll put up a separate PR to change the color of the social links, since it's in `gatsby-design-tokens`. I think changing the color is a good thing, since the current color fails WCAG color contrast:

Screen Shot 2020-04-15 at 2 33 08 PM

Should I change the color for the dark theme as well?

**Comment by AishaBlake** [comment]
I'm closing this PR for now because an internal team is working on some website changes that will affect our approach. We'll come back to this work in the near future!

**Pull request closed without merging**
