### PR TITLE
Improve readability of verbose logging code in wordpress source plugin

### PR DESCRIPTION
**Pull request by jdoubleu**
This PR improves the readability of the wordpress source plugin's `fetch.js` code.

For some reason there are several if conditions, each having a single line of `console.log` method calls. Although they can all be put into just one call.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit c80603d06013d413fa4a58441d511049738e7cb3

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6ae9c54ed62f7e89d42828

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit c80603d06013d413fa4a58441d511049738e7cb3

https://app.netlify.com/sites/gatsbyjs/deploys/5b6ae9c24ed62f7e89d4281c

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 6089e304667c80611d7c429253f29d5175aae64b

https://app.netlify.com/sites/gatsbyjs/deploys/5b6aec2802ed83338fc24b70

**Comment by m-allanson** [comment]
Thanks @jdoubleu! Could you post before and after screenshots?

**Comment by jdoubleu** [comment]
I used the [`gatsby-starter-blog` (version 2)](https://github.com/gatsbyjs/gatsby-starter-blog/tree/v2) and installed the `gatsby-source-wordpress@next` plugin with the `verboseOutput` option set to `true`.

screen shot 2018-08-12 at 15 48 31

Then I built the plugin with my changes and linked it into the project's `node_modules/` folder.

screen shot 2018-08-12 at 15 55 00

As you can see, both are identical. I tried to get each log entry (settings, resource/route info, etc) into this screen.

**Pull request merged**
