### PR TITLE
chore: upgrade got package

### PR DESCRIPTION
**Pull request by wardpeet**
## Description

Move all [got](https://npm.im/got) deps to latest version

### CODE REVIEW

**Comment by ascorbic** [comment]
It looks like I forgot to add `got` as a dependency to `gatsby-core-utils` when I moved the file downloading code over.

**Comment by wardpeet** [comment]
It's easily forgotten. That why we should add something like [dependency-cruiser](https://npm.im/dependency-cruiser) to fail when missing packages are used.

**Comment by ascorbic** [comment]
That's neat. Not seen that before. Looks like it's very useful for monorepos.

**Comment by axe312ger** [comment]
@wardpeet I use https://www.npmjs.com/package/check-dependencies to avoid this in my themes. It does not support the gatsby-config.js though.

**Comment by ascorbic** [comment]
Could `got` be added to `gatsby-core-utils` in this PR?

**Comment by axe312ger** [comment]
> Could `got` be added to `gatsby-core-utils` in this PR?

+1 on this

**Comment by wardpeet** [comment]
I thought I added it, now I did :) thanks!

**Review by KyleAMathews — APPROVED** [review]
:shipit:

**Pull request merged**
