### PR TITLE
fix(gatsby-page-utils): path creation on windows filesystem

### PR DESCRIPTION
**Pull request by Lightwight**
## Description

replaces Windows path seperator to UNIX path seperator

## Related Issues
Fixes [#36758](https://github.com/gatsbyjs/gatsby/issues/36758)

### CODE REVIEW

**Comment by LekoArts** [comment]
Thanks! I switched it to use https://github.com/gatsbyjs/gatsby/blob/6396664ab72c5a4305a7d39269d003772109233d/packages/gatsby-core-utils/src/path.ts#L80-L94 since we already have a helper for that.

If tests all pass we can get this in

**Comment by Lightwight** [comment]
Oh sry. Didnt know the slash-core util. Tankstelle for the quick response and have a nice Day:)

**Review by LekoArts — APPROVED** [review]
Thanks!

**Comment by LekoArts** [comment]
Successfully published:
 - gatsby-link@4.24.1
 - gatsby-page-utils@2.24.1
 - gatsby-plugin-page-creator@4.24.1
 - gatsby@4.24.4

**Pull request merged**
