### PR TITLE
build(yarn npm): remove inexact dependencies

### PR DESCRIPTION
**Pull request by Flavien-Pensato**
Hello everyone !

I suggest to use exact dependencies to avoid diff of yarn.lock. Even when we add a exact version of gatsby :)

I didn't find a linter to force everyone to use `yarn add -E`.

What do you think ?

### CODE REVIEW

**Comment by LekoArts** [comment]
Hello, thank you for opening the PR. Unfortunately I'll have to close this PR as the Gatsby team decided against pinning versions (Ref: https://github.com/gatsbyjs/gatsby/pull/8624#issuecomment-425559827)

>Hey, big changes like this are nice to discuss in an issue first to get consensus around first.

> As it is, we dont want to pin unless there's a know bad release as we want to make sure we're getting new bug fixes and other improvements our dependencies are making. Pinning versions means we aren't surprised by potential breaking changes but also means we're not surprised by fixes to annoying bugs :-)

>We all work closely with the code and have a lot of tests and have had very little problems with our upstreams breaking something so I'm going to close this.

**Comment by Flavien-Pensato** [comment]
Sorry, I didn't find the others PRs. I understand. To bad for me :)

**Comment by LekoArts** [comment]
No worries 😊 You can have a look at [our open issues][open-issues] for ideas for future PRs.

We offer pair programming sessions if you’d like to work with one of our maintainers to make your first contribution.

[open-issues]: https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by Flavien-Pensato** [comment]
Oh, okay I will 😃

**Pull request closed without merging**
