### PR TITLE
Fix pathPrefix causing erroneous redirects

### LINKED ISSUE #7861: [v2] pathPrefix is partially ignored
## Description

After upgrading to v2 `pathPrefix` is not working properly. It is added for links and assets in HTML, but ignored in other places which results in redirection like this:
Opening: `githubusername.github.io/reponame`
changes URL in address bar to: `githubusername.github.io/` and screen goes blank.

I see that `pathPrefix` is not included in generated html files (https://github.com/asistapl/tldr-marketing/blob/gh-pages/index.html):
```html
<script id="gatsby-script-loader">/*<![CDATA[*/window.page={"componentChunkName":"component---src-pages-index-js","jsonName":"index","path":"/"};window.dataPath="173/path---index-6a9-NZuapzHg3X9TaN1iIixfv1W23E";/*]]>*/</script>
```

and in one of the chunks (https://github.com/asistapl/tldr-marketing/blob/gh-pages/4-0d5ca849d8ef3a6a86ed.js):
```js
(window.webpackJsonp = window.webpackJsonp || []).push([
  [4],
  {
    155: function(a) {
      a.exports = {
        pages: [
          {
            componentChunkName: 'component---src-pages-404-js',
            jsonName: '404-22d',
            path: '/404/',
          },
          {
            componentChunkName: 'component---src-pages-index-js',
            jsonName: 'index',
            path: '/',
          },
          {
            componentChunkName: 'component---src-pages-404-js',
            jsonName: '404-html-516',
            path: '/404.html',
          },
        ],
        dataPaths: {
          index: '173/path---index-6a9-NZuapzHg3X9TaN1iIixfv1W23E',
          'sq--src-components-layout-js': 755544856,
          '404-22d': '44/path---404-22-d-bce-NZuapzHg3X9TaN1iIixfv1W23E',
          '404-html-516':
            '164/path---404-html-516-62a-NZuapzHg3X9TaN1iIixfv1W23E',
        },
      }
    },
  },
])
//# sourceMappingURL=4-0d5ca849d8ef3a6a86ed.js.map
```

### Steps to reproduce

Include `pathPrefix: '/reponame,` in `gatsby-config.js`.
Use npm script `"deploy": "gatsby build --prefix-paths && gh-pages -d public",`

Or take a look at my repo (with master and gh-pages branches) where problem is occurring:

Repo:
https://github.com/asistapl/tldr-marketing/
GH Pages:
https://asistapl.github.io/tldr-marketing/

### Expected result

`pathPrefix` is taken into account in every stage of a build proccess.

### Actual result

It's not.

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.9.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.8 
    gatsby-plugin-emotion: next => 2.0.0-rc.1 
    gatsby-plugin-google-tagmanager: next => 2.0.0-rc.1 
    gatsby-plugin-manifest: next => 2.0.2-rc.1 
    gatsby-plugin-offline: next => 2.0.0-rc.2 
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### PR DESCRIPTION
**Pull request by davidbailey00**
Fixes #7861

### CODE REVIEW

**Comment by davidbailey00** [comment]
Looks like the other codemod isn't outputting with `\n` endings so AppVeyor is failing again. I'll create another PR to fix this.

**Comment by pieh** [comment]
can you apply these changes? `__PATH_PREFIX__` is "globally available" (webpack replace it with actual string thanks to webpack define plugin) and don't need to write this to window object
```diff
diff --git a/packages/gatsby/cache-dir/production-app.js b/packages/gatsby/cache-dir/production-app.js
index a2cf1566b..9eec3a126 100644
--- a/packages/gatsby/cache-dir/production-app.js
+++ b/packages/gatsby/cache-dir/production-app.js
@@ -83,10 +83,10 @@ apiRunnerAsync(`onClientEntry`).then(() => {
   if (
     window.page &&
     window.page.path !== `/offline-plugin-app-shell-fallback/` &&
-    window.page.pathPrefix + window.page.path !== window.location.pathname
+    __PATH_PREFIX__ + window.page.path !== window.location.pathname
   ) {
     navigate(
-      window.page.pathPrefix +
+      __PATH_PREFIX__ +
         window.page.path +
         window.location.search +
         window.location.hash,
diff --git a/packages/gatsby/cache-dir/static-entry.js b/packages/gatsby/cache-dir/static-entry.js
index 6cc5d26ba..cc6bdc82e 100644
--- a/packages/gatsby/cache-dir/static-entry.js
+++ b/packages/gatsby/cache-dir/static-entry.js
@@ -313,7 +313,6 @@ export default (pagePath, callback) => {
   })
 
   // Add page metadata for the current page
-  page.pathPrefix = __PATH_PREFIX__
   const windowData = `/*<![CDATA[*/window.page=${JSON.stringify(page)};${
     page.jsonName in dataPaths
       ? `window.dataPath="${dataPaths[page.jsonName]}";`
```

**Comment by ahinrichs** [comment]
By using `__PATH_PREFIX__` you could get away with just changing production-app.js. I can confirm, that this fixes my problems with pathPrefix (#7861; page shows and immediately blanks and routes to / )

**Comment by davidbailey00** [comment]
@ahinrichs Yep, that's actually what @pieh has just suggested too so I'll change it :+1:

**Pull request merged**
