### PR TITLE
[blog] gatsby manor focuses on starters

### PR DESCRIPTION
**Pull request by nodox**
The new mission of Gatsby Manor is to provide a showcase for the starters created with Gatsby.

### CODE REVIEW

**Comment by nodox** [comment]
@m-allanson @calcsam thoughts?

**Comment by LeKoArts** [comment]
No offense, but how is this different than the upcoming starter showcase?

**Comment by nodox** [comment]
@LeKoArts I appreciate the feedback. Where can I find that announcement?

**Comment by nodox** [comment]
@LeKoArts I see what you mean on #5334. I'll close this for now to better understand PR. Thank you!

**Comment by nodox** [comment]
@brimtown check this out.

**Pull request closed without merging**
