### PR TITLE
[1.0] Remove deprecated API from gatsby-link

### PR DESCRIPTION
**Pull request by 0x80**

### CODE REVIEW

**Comment by 0x80** [comment]
I was tempted to replace `React.createClass` calls in the examples as well, but figured that it would be better to clean them up properly with functional components or es6 `class` instances. And since that code is not part of the Gatsby core, I guess it doesn't have any priority anyway.

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 5b833edc99b98fd96029553f63b9c9bc5206f846

https://app.netlify.com/sites/gatsbygram/deploys/59084feca700c420cca8ca3a

**Comment by 0x80** [comment]
@KyleAMathews Not sure what caused this to fail the deploy. The Netlify links don't seem to work anymore, so I'm pretty much in the dark here.

Can I maybe trigger a new deploy somehow?

**Comment by KyleAMathews** [comment]
Thanks!

RR v4 could be done I suppose. It's just that it was unstable for most of the time I've been working on this and what I have is working and invisible to the user for the most part so haven't seen any big wins just yet for RR v4.

I do have some big changes in mind for Gatsby v2 that will take advantage of RR v4 in some potentially interesting ways but those go along with a ton of other work so have been pushing this stuff aside for v1.

**Pull request merged**
