### PR TITLE
[1.0] Merge sidebar components

### PR DESCRIPTION
**Pull request by fk**
Sloppy WIP

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Looks good to me — did you have more work you were intending to add here?

**Comment by fk** [comment]
Yes and no ;) … I was wondering if we should pull the container `<div class="sidebar">` which also carries the `display:none` "logic" into the `SidebarBody` component, too (thus making it a `Sidebar` component), but that seemed making things less clear than they are now. Also wanted to check on moving styles back from typography.js into the component.

**Comment by KyleAMathews** [comment]
Yeah move in the typography styles. Whenever possible styles should live in
their component. Don't worry about cleaning up the layout file further.
That'll change quite a bit whenever hierarchal layouts are supported as
then the sidebar will only live in the section of the site where we want it
to live instead of globally as it now does.

**Comment by fk** [comment]
👍 will fix later tonight!

**Comment by fk** [comment]
This should be good to go!

**Comment by KyleAMathews** [comment]
Thanks! Nice refactor! Appreciate you helping up the quality of our website :-)

**Pull request merged**
