### PR TITLE
Use cheap-module-source-map so sourcemaps work in development

### LINKED ISSUE #778: Source maps not working
If I set a breakpoint, the Chrome devtools show me the transpiled source. Are source maps not enabled by default? 

I've created a default starter en run `gatsby develop`.

### PR DESCRIPTION
**Pull request by 0x80**
Similar to fix #778 for master

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Oh thanks!

Looks like you're on an older version of Prettier by chance? The diff seems really noisy.

**Comment by KyleAMathews** [comment]
You can also just run `npm run format`.

**Comment by KyleAMathews** [comment]
Ran prettier for you :-) https://github.com/gatsbyjs/gatsby/commit/2188a85cba531ebe0bc5ee9ed644d385542b5aa4

**Comment by KyleAMathews** [comment]
Thanks for the PR!

**Comment by 0x80** [comment]
@KyleAMathews Thanks, I didn't see your comments in time. I noticed the noise and fixed it shortly after.

I am using prettier-eslint in my IDE, which works like a charm for me for auto format on save, but then you have to set things in eslint like max-len. My own prettier.printWidth setting was messing this up because it wasn't set in eslint rules of gatsby.

I am making a PR later to make eslint more strict, and then the vscode settings in the repository can go as well.

**Pull request closed without merging**
