### PR TITLE
fix(gatsby-plugin-image): Add `outputPixelDensities` to `SHARP_ATTRIBUTES`

### PR DESCRIPTION
**Pull request by Bi11**
`outputPixelDensities` in `StaticImage` was ignored due to its absence in `SHARP_ATTRIBUTES`.

## Related Issues

Fixes #32552 
Fixes #33883

### CODE REVIEW

**Comment by wardpeet** [comment]
Thanks @B11, can you also add a test for it in https://github.com/gatsbyjs/gatsby/tree/master/e2e-tests/visual-regression

**Comment by Bi11** [comment]
It just looks like a simple omission. And it usually doesn‘t cause a noticeable visual difference.

**Comment by LekoArts** [comment]
Since this is a well tested React component we don't want to let this coverage slip, so we'd very much appreciate if you can add a test case to the mentioned suite. Let us know if you need any assistance, thanks!

**Comment by Bi11** [comment]
I'm new to NodeJS and I'm not familiar with Gatsby yet. I encountered this issue, and I found it was just a simple omission in the source code, based on years of experience in other languages.

**Review by LekoArts — APPROVED** [review]
Thanks!

**Pull request merged**
