### PR TITLE
chore(docs): updated doc for payment using square

### PR DESCRIPTION
**Pull request by imshubhamsingh**
This pull request addresses issue #26055 

In this PR, I've 

1. Updated the Doc describing the details of implementing payment using square
2. Implemented backend using netlify lambda for successful payment
3. Updated the dependencies for the example project.

Feel free to provide feedback. Looking forward to it.

### CODE REVIEW

**Comment by LekoArts** [comment]
Hi, thanks for the PR! I think you'll want to revert the changes to the example as https://github.com/gatsbyjs/gatsby/pull/27263 addresses this :)

**Comment by imshubhamsingh** [comment]
@LekoArts should I close the PR as I think this is addressed in  #27263 ?

**Comment by LekoArts** [comment]
Since @jonniebigodes isn't changing the `docs` portion of it, you can make the requested changes for that file :) So no need to close this PR!

**Comment by imshubhamsingh** [comment]
@LekoArts thanks. Sure I'll update PR accordingly then. Thanks ✌️

**Comment by pvdz** [comment]
(-> #27263 ?)

**Comment by imshubhamsingh** [comment]
@LekoArts I've updated the Doc. Rest of the changes are removed.

**Comment by imshubhamsingh** [comment]
@pvdz I've updated the doc. Let me know if I missed something.

**Review by pvdz — APPROVED** [review]
Thanks :purple_heart:

**Pull request merged**
