### PR TITLE
Add active state styles for top navbar items

### PR DESCRIPTION
**Pull request by arzafran**
# Background
The active item in doc's top navbar wasn't being highlighted, hence #7425 

# How I've fixed it:

- Added `activeClassName="active"` to `navigation.js` items
- Added styles for items with the class active

# Screenshots:

**BEFORE**
screen shot 2018-08-17 at 19 03 18

**AFTER**
screen shot 2018-08-17 at 19 03 27

### CODE REVIEW

**Comment by Manoz** [comment]
Good catch @arzafran 👍

**Comment by arzafran** [comment]
I'm not sure why tests are not passing, and didn't understand how to debug failing ci.
Any help would be appreciated :)

**Comment by arzafran** [comment]
hey! sure, I'll take a look later today! thanks.

**Comment by fk** [comment]
Yay! Thank you @arzafran! 🤗 

I don't know anything about `getProps` until now and programming doesn't come easy to me, so I might not be able to help, but others surely can -- so please let us know if you're running into problems!

**Comment by shannonbux** [comment]
@fk #899 is in ichabod-cranes so don't think people can see it perhaps?

Also I moved this issue and #899 into the [EPIC] Docs IA Redesign cleanup epic here: 
https://github.com/gatsbyjs/gatsby/issues/7427

**Comment by fk** [comment]
Hey @arzafran, I just stumbled upon https://github.com/gatsbyjs/gatsby/issues/7526#issuecomment-414858689 which shows how to do this.

**Comment by fk** [comment]
@shannonbux Added a new issue to capture the main navigation expansion: #7544

**Comment by fk** [comment]
Hey @arzafran, I just merged #7933 by @kkemple which adds the active state for the top navbar items. I hope you don't mind 🙏— thanks for your work on this! 🤗

**Pull request closed without merging**
