### PR TITLE
[v2] Update Babel to 7.0.0-beta.49

### PR DESCRIPTION
**Pull request by dennari**
Update to the newest Babel beta in preparation for updating `gatsby-plugin-typescript` to use `@babel/preset-typescript`.

### CODE REVIEW

**Comment by dennari** [comment]
The failing test is the one that is fixed in #5602

**Comment by KyleAMathews** [comment]
I'm working on merging this in

**Comment by KyleAMathews** [comment]
I had to revert this — it seems to have broke things for us somehow — both gatsbyjs.org + gatsby-starter-blog stopped working. Tried digging into Babel changes before giving up as have other v2 stuff want to make progress on.

**Comment by dennari** [comment]
Damn. It would seem worthwhile to investigate what happened and have a test that would catch it. I can try to do that.

**Comment by KyleAMathews** [comment]
It broke hot reloading & anytime I was using bind in my components for a class method and it said it couldn't find the method.

**Comment by dennari** [comment]
Finally got around to testing this. It's quite painful to get the website to resolve its dependencies to the monorepo packages. Managed it in the end by using `file:../packages/gatbsy` type of paths in the www package.json. Anyway, once I managed to do that, I couldn't reproduce any problems.

At one point I had forgotten to run `yarn bootstrap` at the repo root after upgrading to Babel v49 which lead to a broken site with `bind` related errors in the console. In this case the packages had been traspiled with v47 while the runtime etc. was from v49.

**Comment by KyleAMathews** [comment]
Oh yeah — not running yarn bootstrap before upgrading could very well be the problem. @m-allanson or @pieh — want to try merging this PR again and making sure to run bootstrap first then publish?

**Comment by jlengstorf** [comment]
Hiya @dennari! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
