### PR TITLE
Alias unused React polyfills

### PR DESCRIPTION
**Pull request by KyleAMathews**
- react-lifecycles-compat
- create-react-context

Both were added to polyfill coming React APIs. Since we require
versions of React added after the final versions of these APIs came out,
we can remove these polyfills from packages that use them.

This brings our hello-world JS bundle size to 55.0 KBs

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 2c322c578b2df499dd63c8f99b4316a98d27de12

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6d6c6e67610c45c37c02ec

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 995b4a81b5418950404240431e9b50fd19d42a37

https://app.netlify.com/sites/gatsbyjs/deploys/5b6d75f53813f0417b86b897

**Comment by jquense** [comment]
I really want to pull something like this out into a Babel plugin, and go further like remove core-js imports or Babel runtimes for supported browser features

**Comment by KyleAMathews** [comment]
That'd be sweet! `object-assign` is another frequent offender.

**Pull request merged**
