### PR TITLE
gatsby-plugin-netlify-cms: allow manual init

### PR DESCRIPTION
**Pull request by emanueleperuffo**
Allowing manual initialization as specified here:
https://www.netlifycms.org/docs/beta-features/

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit b2e7125971ee5e43dc80c57b010a16cb6beab83e

https://app.netlify.com/sites/using-postcss-sass/deploys/5b51b172fdd72a44d3249f44

**Comment by m-allanson** [comment]
Thanks! Does this need a docs update? How would you set `manualInit = true`?

**Comment by emanueleperuffo** [comment]
Ops...
Now there's some documentation in the Readme.

**Comment by emanueleperuffo** [comment]
Is something blocking this merge?

**Comment by erquhart** [comment]
Great work @emanueleperuffo

**Comment by m-allanson** [comment]
> Is something blocking this merge?

Nope, just trying to work through all the open PRs! Thanks @emanueleperuffo, this is published as `gatsby-plugin-netlify-cms@3.0.0-beta.2`

**Pull request merged**
