### PR TITLE
Add "The State of European Tech 2017" to the showcase

### PR DESCRIPTION
**Pull request by m-allanson**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
🎉  thanks for sharing!

**Comment by KyleAMathews** [comment]
Tweeted it out too :-) https://twitter.com/gatsbyjs/status/941720211807277056

**Comment by m-allanson** [comment]
Nice :)

**Comment by fk** [comment]
Deep in my GitHub inbox, stubling across this again…
So good! 😍

**Comment by m-allanson** [comment]
Hah, thanks @fk 😄!

**Pull request merged**
