### PR TITLE
Add quantityAvailable field for gatsby-source-shopify

### PR DESCRIPTION
**Pull request by ishanloya**
To address issue #25264

### CODE REVIEW

**Comment by jzabala** [comment]
Hi @ishanloya, thank you very much for your PR.

For this change to work I think you'll need a couple of more changes. As you mentioned in the issue #25264 the field `quantityAvailable` was introduced in the api version **2020-04** but the current version in the plugin is **2019-07**:

https://github.com/gatsbyjs/gatsby/blob/d41526fe6e220cfcd5debc08d4dbb67df7e86aba/packages/gatsby-source-shopify/src/gatsby-node.js#L52

So, you'll need to increase it or it will break.

Also, you would need to update the docs to add the new permission: 

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-shopify/README.md#how-to-use

I am not a core maintainer so, I can't tell if the change will be merged but those are the things I see you'll need to complete your PR 🙂

**Comment by avcohen** [comment]
Hello. Any word on this getting merged in? Would be fantastic to start using this.

**Comment by smthomas** [comment]
I think this is a good change to get added in. However, I haven't tested updating the apiVersion to see if it causes any unanticipated issues. I'm a little hesitant to merge this in without first evaluating what has changed.

In the meantime, this PR (#23922) should be merged soon which will allow you to customize the queries in your gatsby-config.js to add these fields.

**Comment by ishanloya** [comment]
Great, #23922 takes care of this. Thanks!

**Pull request closed without merging**
