### PR TITLE
fix(www): persist filters on showcase item click

### LINKED ISSUE #8069: WWW showcase page: after closing show detail modal, it will rerender list page, lose all "more load" data and scroll back to top
## Description

https://next.gatsbyjs.org/showcase. browse this page, and load more showcases, and then click a card to view showcase detail as modal window. after closing the modal. the showcase list page is rerendering, losing all the before status.
I think this experience can be improved. 

### Steps to reproduce

1. Oen https://next.gatsbyjs.org/showcase
2. Select a `category`, for example `app`.
3. Click on any site card. The site modal opens up.
4. Close the modal by clicking on close button.
5. Check the selected categories and the site list.

### Expected result
Selected filter should be maintained.

### Actual result
Selcted filters are cleared, and the site is rendered as the initial page launch.

### Environment
N/A

### PR DESCRIPTION
**Pull request by andrew-anguiano**
This should close #8069. 

**To test:**
1. Apply filters on the showcase view
2. Click a site from the filtered list
3. Close the details modal

**Expected Result:**
Filters applied in step 1 should still be applied

**Previous behavior:**
Filters would get reset

Feel free to make suggestions for improvements 🙂 This is my first Gatsby PR.

### CODE REVIEW

**Comment by LekoArts** [comment]
Working as expected: https://img.lekoarts.de/19_01_5h8385o1.mp4
LGTM 👍

**Comment by amberleyromo** [comment]
Thanks @andrew-anguiano! It looks like the state doesn't persist if you exit after clicking through a few items in the modal (only if you open one, and then immediately close). Would you want to take a look at extending that?

If not, I'm fine to get this in as-is, and add it later.

**Comment by andrew-anguiano** [comment]
If you want to go ahead and merge this one, I can take a look hopefully in the next few days and submit a new PR with the additional behavior :)

**Comment by amberleyromo** [comment]
Thanks again @andrew-anguiano! I opened that other issue here (#10971) if you do want to work on it.

**Pull request merged**
