### PR TITLE
Update capitalization of allowDangerousHtml

### PR DESCRIPTION
**Pull request by cbetta**
Before this change `mdast-util-to-hast` would output a warning.

```
mdast-util-to-hast: deprecation: `allowDangerousHTML` is nonstandard, use `allowDangerousHtml` instead
```

https://github.com/syntax-tree/mdast-util-to-hast/blob/master/lib/index.js#L22-L28

### CODE REVIEW

**Comment by cbetta** [comment]
@ascorbic I can't tell if these errors came from my changes. Can you confirm? If so I will dig into why this is throwing errors.

**Comment by ascorbic** [comment]
It does seem the tests are failing from your change. Can you run tests locally and check?

**Comment by cbetta** [comment]
@ascorbic so it turns out this warning only appears in `mdast-util-to-hast` version `8.2.0+`, when the author changed the capitalization. I have updated the dependency but not sure if that's the right way to go. A different way would be to set the 2 affected packages to only work for a version `<8.2.0`. 

Another way would be to read the version of `mdast-util-to-hast` somehow and then pass the right param along. I would love some guidance.

**Comment by ascorbic** [comment]
I think for now we can just leave it. It's not a breaking change yet, it's just a warning. If the author does eventually make it a breaking change then we can either work around it or set the specific dependency. Does that sound reasonable?

**Comment by cbetta** [comment]
@ascorbic but I hate the warning 😆 . I get it though, I'll close this for now.

**Pull request closed without merging**
