### PR TITLE
Fix crash by rounding auto-calculated height in resize

### LINKED ISSUE #4156: [gatsby-plugin-sharp] Resize issue - "Int cannot represent non-integer value"
## Description

When trying to resize an image using only width, Gatsby doesn't round calculated height.

```graphql
thumbs: allImageSharp {
  edges {
    node {
      id
      img: resize(width: 300) {
        src
        width
        height
      }
    }
  }
}
```

### Environment

Gatsby version: 1.9.202
Node.js version: 8.9.4
Operating System: Ubuntu 16.04 x64

### Actual result

```
The GraphQL query from xxx/index.js failed

        Errors:
          GraphQLError: Int cannot represent non-integer value: 395.9183673469388,
```

### Expected behavior

Calculated height should be rounded.

Example : resize 128x125 with width 64 should give 64x76

### Steps to reproduce

1. Install `gatsby-plugin-sharp` and add it to your `gatsby-config.js`
2. Add a picture with resolution `128x125` (like [this one](https://user-images.githubusercontent.com/1556356/36455998-d3446ae0-16f6-11e8-9b84-17b22e7cc7ce.png))
3. Add the following query :

```graphql
thumbs: allImageSharp {
  edges {
    node {
      id
      img: resize(width: 64) {
        src
        width
        height
      }
    }
  }
}
```

### Causes

I suspect that the root cause is this : https://github.com/gatsbyjs/gatsby/blob/25458558c3f8cc2974297444ee08e04600892d3f/packages/gatsby-plugin-sharp/src/index.js#L318

I'm going to test this hypothesis and I'll make a PR if confirmed.

### PR DESCRIPTION
**Pull request by Betree**
Fix #4156

### CODE REVIEW

**Comment by fk** [comment]
👍 👍 Thank you @Betree!
Wondering if we can add a test for this?

**Comment by Betree** [comment]
I have a working test but it fails to export the resource when trying to process the job in queue, I guess because of test environment. I didn't have the time to investigate furthermore. Here is the test :

```jsx
describe(`queueImageResizing`, () => {
  it(`should round height when auto-calculated`, () => {
    // Resize 144-density.png (281x136) with a 3px width
    const result = queueImageResizing({
      file: getFileObject(path.join(__dirname, `images/144-density.png`)),
      args: { width: 3 },
    })

    // Width should be: w = (3 * 136) / 281 = 1.451957295
    // We expect value to be rounded to 1
    expect(result.height).toBe(1)
  })
})
```

Console log :

```bash
error Failed to process image /home/piouffb/Seafile/Workspace/OpenSource/gatsby/packages/gatsby-plugin-sharp/src/__tests__/images/144-density.png
 PASS  packages/gatsby-plugin-sharp/src/__tests__/index.js
  gatsby-plugin-sharp
    queueImageResizing
      ✓ should round height when auto-calculated (6ms)
    responsiveSizes
      ✓ includes responsive image properties, e.g. sizes, srcset, etc. (70ms)
      ✓ adds pathPrefix if defined (1ms)
      ✓ keeps original file name (1ms)
      ✓ accounts for pixel density (11ms)
      ✓ can optionally ignore pixel density (3ms)
      ✓ does not change the arguments object it is given (3ms)
    resolutions
      ✓ does not warn when the requested width is equal to the image width (19ms)
      ✓ warns when the requested width is greater than the image width (1ms)
    base64
      ✓ converts image to base64 (2ms)

  console.log packages/gatsby-plugin-sharp/node_modules/progress/lib/node-progress.js:179
    

  console.log packages/gatsby-cli/lib/reporter/index.js:46
    
    
      Error: ENOENT: no such file or directory, open '/home/piouffb/Seafile/Workspace/OpenSource/gatsby/public/static/test-1234-dac52.png'
    

Test Suites: 1 passed, 1 total
Tests:       10 passed, 10 total
Snapshots:   4 passed, 4 total
Time:        1.296s
Ran all test suites matching /packages\/gatsby-plugin-sharp/i.
```

**Comment by pieh** [comment]
@Betree this is not introduced by Your change so You can add your test here with no worries - current tests have this too - https://travis-ci.org/gatsbyjs/gatsby/builds/344154206#L1794

**Comment by Betree** [comment]
Thanks for reviewing

**Comment by fk** [comment]
🎉Thank you @Betree and @pieh! 🤗

**Comment by jlengstorf** [comment]
Hiya @Betree! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
