### PR TITLE
(feat)gatsby-remark-copy-linked-files: create hashLength option to specify the digest hash length

### PR DESCRIPTION
**Pull request by kimbaudi**
## Description

This PR adds a new option called `hashLength` that would allow users to specify the length of [contentDigest](https://www.gatsbyjs.org/docs/node-interface/#contentdigest)

```
{
  resolve: `gatsby-remark-copy-linked-files`,
  options: {
      hashLength: 9
  },
},
```

### CODE REVIEW

**Comment by kimbaudi** [comment]
I am new to Jest and unit testing, but feel that the unit tests for this plugin requires actual `fs-extra` functionality (i.e. `existsSync`, `copy`, and `ensureDir`) instead of mocked ones. [Currently, the unit tests expects `undefined` values](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-copy-linked-files/src/__tests__/index.js#L416):

```
expect(imageURL(markdownAST)).toEqual(`/undefined/undefined.gif`)
```

In order to test this new `hashLength` option, I would have to be able to test it using an actual file. Does anybody know if this is possible with Jest? I'll start looking into it, but I am unsure. Maybe this type of test requires end-to-end testing with Cypress instead of Jest? If anyone can point me in the right direction, that would be really helpful.

**Comment by sidharthachatterjee** [comment]
I would be wary of adding this because it if I understand correctly, it strips off characters off the `contentDigest` from a Node. 

This _could_ lead to collisions. Also, if a user needs to set a specific length for a Node's `contentDigest`, they are free to set that themselves. 

Based on the above, I'd prefer to close this and _not_ add this option. What do you think @kimbaudi?

**Comment by sidharthachatterjee** [comment]
@pieh Thoughts?

**Comment by pieh** [comment]
Why do you need that option? I can't really think of situation when I would want/need to mess with `contentDigest`?

**Comment by kimbaudi** [comment]
personally, its fine to close this. I really don't need it. I think I misread something about long filename due to hashing from https://github.com/gatsbyjs/gatsby/issues/10048. I will close this.

**Comment by sidharthachatterjee** [comment]
Thanks @kimbaudi 👍

**Pull request closed without merging**
