### PR TITLE
chore(docs): Revert "fix(docs): Update "gatsby" commands to "npm run""

### PR DESCRIPTION
**Pull request by DSchau**
Reverts gatsbyjs/gatsby#12025

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
Might want to look at https://github.com/gatsbyjs/gatsby/pull/12041 after merging this in

**Comment by wardpeet** [comment]
@DSchau are you going for a reverse sprint? Shouldn't we reverse all npx suggestions in the docs?

**Comment by DSchau** [comment]
@wardpeet missed your comment!

This is something that @KyleAMathews brought up after I merged this PR. We generally want to encourage people use our global version--because we'll be adding (more) features to it at some point in the future, and it can become burdensome to add additional package scripts for each and every new command.

**Comment by DSchau** [comment]
Agreed there will be more work re: this change. I haven't gone through and done that yet--but I plan to soon.

**Comment by DSchau** [comment]
Let's just close this - there will likely be many more we'll have to tweak as per #12195

**Pull request closed without merging**
