### PR TITLE
Update gatsby-starters.md

### PR DESCRIPTION
**Pull request by parmsang**
New Gatsby Starter Project: Gatsby eCommerce store using the Moltin eCommerce API

### CODE REVIEW

**Comment by KyleAMathews** [comment]
BTW, tweeted it out https://twitter.com/gatsbyjs/status/1007786292703199232

People seem to like it! Couldn't find a twitter handle for you — if you have one, would love to give you attribution!

**Comment by KyleAMathews** [comment]
btw, have you looked into using gatsby-image? That'd keep the front page from jumping around as images load and change the layout.

**Comment by parmsang** [comment]
@KyleAMathews  - thank you for the positive feedback.

The site is still work in progress and there are a few little things I need to address. I wasn't expecting it to get tweeted out - the feedback has been great.

As you've suggested, I've updated the site to use gatsby-image for the images. I used createRemoteFileNode as per the guide [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem) and it seems to work well.

I just noticed a minor issue with the nav-menu where the page selected isn't styled as it should be. This works in develop mode but not the built site. When I get the time I'll address that. 

Until 10 minutes ago I didn't have a twitter handle. It's @parmsang. No need to update the existing tweet with that new handle.

Cheers,
Parm

**Comment by jlengstorf** [comment]
Hiya @parmsang! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
