### PR TITLE
fix(*): Remove global namespace hack for a proper workflow

### PR DESCRIPTION
**Pull request by blainekasten**
## Description

a previous "hack" was waiting for a reach router change that never landed. ~But there is a more _acceptable_ hack that does not pollute global namespace and depend on dangerous state.~

Upon testing, it turns out none of this code is needed anymore because scroll-behavior received some updates that allows it to detect PUSH/POP based on location.key

Thanks @pieh !!!

### CODE REVIEW

**Comment by wardpeet** [comment]
Awesome change! Any extra information on this change? What would be the best way to test this?

**Comment by blainekasten** [comment]
@wardpeet the previous code was there to tell the scroll-behavior module what type of navigation it was. Basically, if the navigation is a PUSH, that tells it to scroll to the top, if it's a POP (back navigation) it means to restore scroll position to where it was when previously navigated

**Comment by pieh** [comment]
> I was sort of hoping that our automation tests would catch something if it was broken too. Not sure if that was a good assumption or not

We have those tests - https://github.com/gatsbyjs/gatsby/blob/master/e2e-tests/production-runtime/cypress/integration/scroll-behavior.js that should assert scrolling behaviour - both when navigating to new page and when going back in history - check them up and see if there is anything missing there (or just if tests are broken which can always happen)

**Comment by blainekasten** [comment]
Thanks @pieh I'm running these locally to confirm. The tests passed in CI so i'm guessing they are working. Will confirm and report back

**Comment by blainekasten** [comment]
@pieh / @wardpeet confirmed the scroll position is still maintained on POP and set to 0 on PUSH, as expected.

**Comment by pieh** [comment]
@wardpeet just so the information is not lost in private DMs between me and Blaine:

I was trying to verify that our e2e tests would catch regressions in scroll behaviours - https://github.com/gatsbyjs/gatsby/pull/21797 but instead what we found that we don't seem to need `action` on `location` anymore at all - so we possibly be able to remove `globalHistory` listener too, but this need further verification.

**Comment by wardpeet** [comment]
I've tested it locally that's why I merged :joy: Didn't deep dive to much in all of this.

**Pull request merged**
