### PR TITLE
Add GraphQLParser errors to verbose output

### PR DESCRIPTION
**Pull request by daniel-simpson**
Was having issues with a malformed graphql query due to the differences between allContentfulX and contentfulX mappings.  Very difficult to track down until I added the following GraphQLParser exception.  I've scoped this to only show if verbose output is turned on to ensure newbies have some reference while using graphql, without getting in anyone else's way.

### CODE REVIEW

**Comment by jquense** [comment]
hey there, thanks for the PR. I don't think we need to guard against this for verbose or specific parser errors. It's really a bug that the error details are getting swallowed here. Ideally waht should happen is that if the specialized gql error parsing doesn't turn up anything (as in your case) the default reporter behavior should be used, e.g. `report.error(msg, originalError)`. That would require some or of signalling from this `graphqlError` method that it didn't understand the the error so that it's callsite can adjust. Or maybe we need to rethink how these get called in the first place idk

**Comment by KyleAMathews** [comment]
Yeah, I really dislike "verbose" modes generally speaking.

@daniel-simpson could you try changing the PR to do as @jquense suggests?

**Comment by daniel-simpson** [comment]
No problem.  I've just updated the PR to display the original error if the formatted graphql error is empty.  Very new to the project so please let me know if you prefer different syntax to the one I've used.

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by revolunet** [comment]
thanks ! this improve developer experience a lot :)

**Comment by rudasn** [comment]
thanks 👍

**Comment by jlengstorf** [comment]
Hiya @daniel-simpson! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
