### PR TITLE
Added Command Line instructions for Linux users

### PR DESCRIPTION
**Pull request by KartSriv**
## Description
Added Command Line instructions for Linux users

### CODE REVIEW

**Comment by KartSriv** [comment]
@marcysutton why isn't this PR accept?

**Comment by KartSriv** [comment]
@marcysutton sorry to bug you but it's been 3 days since you reviewed it.

**Comment by KyleAMathews** [comment]
Merging!

**Comment by KyleAMathews** [comment]
Thanks for the contribution!

**Pull request merged**
