### PR TITLE
[WIP]: feat: enable PnP in gatsby-cli

### PR DESCRIPTION
**Pull request by DSchau**
This enables flags in gatsby-cli (i.e. `gatsby new some-project` will enable PnP.

It's hard to test because as @m-allanson noted, gatsby-dev _requires_ a node_modules structure, but fairly certain this is working as intended.

I'll add a comment with metrics in a bit.

### CODE REVIEW

**Comment by jlengstorf** [comment]
@DSchau probably safe to reopen this one again. 😄

**Comment by DSchau** [comment]
I'll circle back to this next week, bot not quite ready yet.

**Comment by DSchau** [comment]
@m-allanson lol my "next week" was optimistic 🙃

**Comment by DSchau** [comment]
Let's just close this for now. The savings were relatively negligible, and there are a few outstanding issues that would still block this from merging (e.g. downstream deps).

**Pull request closed without merging**
