### PR TITLE
Add another hello world starter

### PR DESCRIPTION
**Pull request by dougouverson**

### CODE REVIEW

**Comment by dougouverson** [comment]
I'm sorry. This was meant to be a PR to my forked repo. I do apologize.

**Comment by LekoArts** [comment]
No problem :)

**Comment by dougouverson** [comment]
I know I can deleted my fork, but how could I have deleted the PR? Maybe this isn't possible once the PR has been submitted?

**Comment by LekoArts** [comment]
You can only really close it and delete the branch on the fork. In most if not all cases this is the correct way of doing it.

**Comment by dougouverson** [comment]
Ws there a way for me to "close it"? That's where I got stuck. I didn't see any way of backing up the PR. And regarding deleting the branch. I had already deleted the branch on my local machine after I did the PR. Did you mean delete the fork?

**Pull request closed without merging**
