### PR TITLE
[gatsby-source-wordpress] improve linking acf fields to media nodes

### PR DESCRIPTION
**Pull request by pieh**
this makes matching acf fields to media nodes more flexible and adds support for ACF gallery field

it was tested with structure like this:
```
ACF root
 - Image (return URL)
 - Image (return Image Data)
 - Gallery
 - Post Object
   - featured_media
 - Repeater
   - Image (return URL)
   - Image (return Image Data)
   - Gallery
   - Post Object
     - featured_media
   - Flexible Content (nested in repeater)
     - Image (return URL)
     - Image (return Image Data)
     - Gallery
 - Flexible Content
   - Image (return URL)
   - Image (return Image Data)
   - Gallery
   - Post Object
     - featured_media
   - Repeater (nested in flexible content)
     - Image (return URL)
     - Image (return Image Data)
     - Gallery
```

And this is diff of graphql schema (manually edited, exporting schema to file would be extra handy if I would know how) after applying changes in this PR - https://gist.github.com/pieh/876c8e7a47b11a3609b379e10628068c.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
The using-wordpress site seems to be working just fine https://deploy-preview-2646--using-wordpress.netlify.com/

@sebastienfi could you review this?

**Comment by pieh** [comment]
Note: I will be away from home until monday or tuesday. I just rushed this PR, bacause i had this ready. Ideally I would like to add some documentation https://www.gatsbyjs.org/packages/gatsby-source-wordpress/ about image processing when i come back.

**Comment by KyleAMathews** [comment]
@pieh awesome! Lots to do with gatsby-source-wordpress so the more helpers the merrier!

**Comment by sebastienfi** [comment]
@pieh @KyleAMathews I will definitely test this PR.

@pieh Could you please test the PR I submitted at the same moment ? https://github.com/gatsbyjs/gatsby/pull/2648

I have tested mine against a pretty similar ACF datamodel, I'm curious to see if it works with your model as it is. I have abstracted the media checks so it applies to any JSON node, including those outside of ACF field.

**Comment by pieh** [comment]
@sebastienfi For most part it does work. Just not ACF gallery. Your changes are actually similiar to mine, I just separated matching fields to images and traversing + replacing nodes to different functions and you traverse from entity root.

Only thing really missing for me is support for gallery field - you can do it like that - https://github.com/pieh/gatsby/commit/163719f77da4c9820e9e0bf466bc05e2646cc484 .

Plus I still hit build error described in comments here - https://github.com/gatsbyjs/gatsby/commit/cd0eb2bb58c4b015ccb7435f75761f8fd9a75670#comments

**Comment by sebastienfi** [comment]
Actually I found that your code was more readable so I pulled your code and build from it. Thanks a lot !
Could you please give a go to the current solution and tell me if it works for you ?
https://github.com/gatsbyjs/gatsby/pull/2648

**Comment by ryancoughlin** [comment]
Been trying to dig around the schema tree for an example on how to query various image types and other types via GraphQL (with ACF). Strings, etc. work great, I can't seem to query images though. 

Do you have any examples or documentation to breakdown various queries with ACF? I am using the starter and that was very helpful.

Happy to open a PR against the starter README

**Comment by KyleAMathews** [comment]
Have you checked out the using-wordpress example site?

**Comment by ryancoughlin** [comment]
I️ have. I️ found a working query since posting this. Will close and post the query in case anyone has any questions around this. 

I️ had the transformers installed. Everything was compiling fine, I️ wasn’t sure what to use as a reference to each type of media regarding their specific attributes.

**Pull request closed without merging**
