### PR TITLE
Prevent path prefix from being incorrectly applied

### LINKED ISSUE #2551: --prefix-paths flag is always enabled
Setting a `pathPrefix` in `gatsby-config.js` will cause `gatsby build` to use that path prefix in all production builds - i.e.`gatsby build` and `gatsby build --prefix-paths` produce the same output.

This means that sites built with `gatsby build` will have broken navigation and trigger errors in the browser console.

screen shot 2017-10-20 at 12 15 08

It looks like this is caused by [an unexpected value in the equality check in `loader.js`](https://github.com/gatsbyjs/gatsby/blob/38149a23a87cb91e0c6047cba2e20eb533da97b5/packages/gatsby/cache-dir/loader.js#L113). `__PREFIX_PATHS__` is a `ReferenceError` instead of `undefined`.  This causes the `pathPrefix` to be used, resulting in Gatsby being unable to match window paths with its own list of paths. 

I'm a bit hazy on the precise differences between a ReferenceError and undefined, but hopefully this is enough info for someone to track down the problem.

screen shot 2017-10-20 at 12 06 20

I've created an example repo (based on gatsby's default starter) that demonstrates the problem at https://github.com/m-allanson/gatsby-path-prefix-test

### LINKED ISSUE #2740: Build is broken if you define pathPrefix, but don't use the --prefix-paths flag.
Issue: if I define pathPrefix, then my build is broken if I don't use the --prefix-paths flag. Everything works fine if I simply run `gatsby develop`

**Expected:**
I use pathPrefix because i upload to ghpages, but I still test the build locally, and I will occasionally use a staging server that does not need a prefix. So run `gatsby build` without the flag, and expect to be able to use gatsby serve without any issues.

**What actually happens:**
I tested two different gatsby projects, and both had issues when I defined a pathPrefix, but did not use the --prefix-paths flag. On one project, it would just redirect everything back to the index. On another project the page never loaded and the console spit out a 'TypeError: t is undefined' with a stack trace that isn't very helpful because it is a production build. In both cases, if I removed the pathPrefix line from my gatsby-config.js, and then ran `gatsby build` and `gatsby serve`, then everything would work.

**Steps to reproduce**
Define pathPrefix in a project's gatsby-config.js file, build, and serve (without using the --prefix-paths flag

### PR DESCRIPTION
**Pull request by m-allanson**
This fixes #2551 in my example repo, and it doesn't break any existing tests.

Are there any tests I can add to ensure this stays fixed?

Possibly this resolves the following issues too: #2740 and #3104.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Awesome, thanks for looking into this!

There's a test file already for loader.js — probably could add a new test there.

**Comment by KyleAMathews** [comment]
@m-allanson want to add a test or two here so we can ship it?

**Comment by m-allanson** [comment]
Yeah I was planning to dig into this again today. 

I added a couple of tests before, but either my understanding is wrong (quite likely) or there's another issue with path prefixes. So I need to revisit it.

**Comment by m-allanson** [comment]
@KyleAMathews This is updated now, I think it fixes up an extra couple of oddities around the path prefix handling.

I've tested various path prefix combinations on a demo Gatsby site, but it'd be good to get confirmation that I've done that properly 😀

**Comment by m-allanson** [comment]
Urgh the CI fails on Node 6, but passes on Node 8. I'm out of time for now, but can take another look next week if no one picks it up before then.

**Comment by KyleAMathews** [comment]
Looks like "startsWith" is the problem — added simple polyfill from MDN.

**Comment by KyleAMathews** [comment]
Actually polyfilling this is silly. Implementing the algorithm.

**Comment by KyleAMathews** [comment]
Hmm something still failing in node 6.

**Comment by KyleAMathews** [comment]
Perhaps with how Jest does the global stuff.

**Comment by m-allanson** [comment]
@KyleAMathews I was able to reproduce this in a standalone repo: https://github.com/m-allanson/jest-global-test. I've posted an issue over at facebook/jest in case it's something that can be fixed on that side.

**Comment by m-allanson** [comment]
Now Travis is 💚 on Node 6 and 8.

**Comment by KyleAMathews** [comment]
Nice! Thanks for persevering through the weirdness :-)

**Pull request merged**
