### PR TITLE
Add babel-plugin-macros

### LINKED ISSUE #4684: [v2] Add babel-macros

### PR DESCRIPTION
**Pull request by porfirioribeiro**
Add babel-plugin-macros, closes #4684

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 4d6b9cb5e7fab985da99f0be54326a53d90dcf71

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6a255de39e7c129ec35e92

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 4d6b9cb5e7fab985da99f0be54326a53d90dcf71

https://app.netlify.com/sites/using-glamor/deploys/5b6a255ee39e7c129ec35e9b

**Comment by KyleAMathews** [comment]
Deploy preview for *using-remark* failed.

Built with commit 4d6b9cb5e7fab985da99f0be54326a53d90dcf71

https://app.netlify.com/sites/using-remark/deploys/5b6a2561e39e7c129ec35ea4

**Comment by tomByrer** [comment]
Is this actually used anywhere?  Seems like a mandatory-optional dependency to me, & the [docs are only a stub](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/babel-plugin-macros.md).

**Pull request merged**
