### PR TITLE
Fix recipes README MDX note

### PR DESCRIPTION
**Pull request by duffn**
## Description

Fix the recipes README MDX note. It references a missing newline that's not missing.

### Documentation

n/a

## Related Issues

n/a

### CODE REVIEW

**Comment by LekoArts** [comment]
It was probably there at the beginning, but since `lint` CI fails I'd say that prettier fixed it. So you'd need to add a prettier-ignore before that.

**Comment by KyleAMathews** [comment]
Confused what's this about?

**Comment by duffn** [comment]
The README says this:

```
Q) My recipe is combining steps instead of running them seperately!
We use the --- break syntax from Markdown to separate steps.

One quirk with it is for it to work, it must have an empty line above it.

So this will work:
```

But both of the following sections of MDX were identical.

**Comment by KyleAMathews** [comment]
Oh I see. Hmmm I thought I fixed that as @johno pointed this out too 😅 maybe not. Anyways, thanks!

**Pull request merged**
