### PR TITLE
Run global-graphql-calls codemod on examples

### PR DESCRIPTION
**Pull request by m-allanson**
Run the global-graphql-calls codemod on all example sites. Refs #6122

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit fd60b949838a84ddc04d7a6228977b83e4cf4de3

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6cc739fdd72a38c21cfdcf

**Comment by KyleAMathews** [comment]
Looks like format needs run too

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit fd60b949838a84ddc04d7a6228977b83e4cf4de3

https://app.netlify.com/sites/gatsbyjs/deploys/5b6cc738fdd72a38c21cfdc7

**Comment by m-allanson** [comment]
I've run these changes through prettier

**Pull request merged**
