### PR TITLE
fix(babel-preset-gatsby-package): apply "corejs" only to non-browser target

### PR DESCRIPTION
**Pull request by sidharthachatterjee**
Appears to have been introduced in https://github.com/gatsbyjs/gatsby/pull/17723

### CODE REVIEW

**Comment by gonzarodriguezt** [comment]
Sorry! I should committed the updates on `yarn.lock` after bumping `core-js` to ^2.6.9?

**Comment by sidharthachatterjee** [comment]
@gonzarodriguezt No problem at all! Yeah, the `yarn.lock` needed to be updated but also found an unusual setting for `useBuiltIns` in browser based environments. I'm not hundred percent sure of this change so let's wait on @wardpeet who is our tooling expert

**Comment by gonzarodriguezt** [comment]
Oh okay @sidharthachatterjee let's wait then 🙏

**Comment by pieh** [comment]
This looks quite weird, I don't think we want to add polyfills to browser code we ship in our npm packages? We only want to add them for site bundles (which is handled by `babel-preset-gatsby` (and not `babel-preset-gatsby-package`)?

**Comment by sidharthachatterjee** [comment]
> This looks quite weird, I don't think we want to add polyfills to browser code we ship in our npm packages? We only want to add them for site bundles (which is handled by babel-preset-gatsby (and not babel-preset-gatsby-package)?

@pieh That _does_ make sense! So then if that `browser` is true, we want to remove the `corejs` field and override `useBuiltIns` to false?

**Comment by pieh** [comment]
What is this exactly fixing? I think we are missing some context around why this is needed

**Comment by sidharthachatterjee** [comment]
Good question, the error in https://circleci.com/gh/gatsbyjs/gatsby/226290?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pieh** [comment]
> @pieh That _does_ make sense! So then if that `browser` is true, we want to remove the `corejs` field and override `useBuiltIns` to false?

Ok, so I think this make sense to add `corejs: 2` to `nodeConfig` only and not to all common config, and keep `browserConfig` as is currently (so revert that part)

**Comment by sidharthachatterjee** [comment]
> Ok, so I think this make sense to add corejs: 2 to nodeConfig only and not to all common config, and keep browserConfig as is currently (so revert that part)

Yup, that is the cleanest way to go. Let me update this.

**Comment by pieh** [comment]
And incidentally, `gatsby-transformer-sqip`'s `.babelrc` shouldn't use `browser` variant ;) We should audit .babelrc files really for this stuff

**Comment by sidharthachatterjee** [comment]
@pieh Done

**Comment by gonzarodriguezt** [comment]
You're awesome guys! Hopefully my next contrib will be less messy 😅thank you!

**Comment by pieh** [comment]
> You're awesome guys! Hopefully my next contrib will be less messy 😅thank you!

Don't worry about it! We didn't catch that in review either!

**Comment by sidharthachatterjee** [comment]
> You're awesome guys! Hopefully my next contrib will be less messy 😅thank you!

You did great! And thank you so much 🤗

**Pull request merged**
