### PR TITLE
Standardizing headers, tweaked wording

### PR DESCRIPTION
**Pull request by shannonbux**
While re-reading this, I'm thinking the order of sections could be a bit hard to digest. (components, global styles, typography.js, plugins. @amberleyromo what order is sensible to you? Usually the most basic pathway is the best, so is there anything else we ought to cut out or re-order to make it more basic?

### CODE REVIEW

**Comment by amberleyromo** [comment]
@shannonbux re: the sensible order, some tweaks along the following lines are what make sense to me. This is mostly a very slight reordering, and a very slight change of focus in the way it's explained.

0. Development environment (by getting in place all of the necessary pieces, which would include succinct explanations of concepts (what is a terminal, and why do you need to interface with it, etc).
1. Introduction to gatsby: goal to scaffold out the starter from the gatsby cli, and have a high-level tour of what ships with it -- what are all these pieces?
2. Thinking in components: here introducing the concepts of components and layouts, again by pointing to the concrete example of the starter scaffold.
3. Styling: Here we can introduce some CSS concepts, probably starting with some plain css, and _then_ making the jump to libraries like Typography.js, etc. 
4. Data flow: Instead of making it about learning GraphQL, start with -- the problem we're solving is how to get data from point A to point B. A high-level introduction to the Gatsby style data flow, then some nitty gritty with GraphQL. GraphQL is the tool -- focus on the why, first.

**Comment by shannonbux** [comment]
@amberleyromo I like those ideas! Especially the tour of what ships with
the starter, and the focus on data flow. One thing I've been thinking more
and more about is how the really awesome things people can accomplish with
Gatsby are data specific--i.e. if someone is an awesome photographer, they
can share their work with the world thru Gatsby. If someone has really
important election data to share or important research to share, they can
share it with Gatsby. I feel really excited about focusing on the why
first. Totally on board with all of this.

Another thought: data is not going to be an abstract concept for many
people. It will be very real and very important to them. So GraphQL is just
a way they can get the data they care about out into the world; GraphQL is
not an end in and of itself for many people (unless they just really like
it :)

**Comment by m-allanson** [comment]
Hey @shannonbux does this still need to go in, or was the work covered in your other recent PRs?

**Comment by amberleyromo** [comment]
@shannonbux these changes don't touch what we discussed today (some minimal in the intro). I think go ahead and merge, and we'll just do fresh changes from there.

**Comment by shannonbux** [comment]
Thanks everybody!

**Pull request merged**
