### PR TITLE
chore(benchmarks): upgrade contentful for wib

### PR DESCRIPTION
**Pull request by KyleAMathews**
They're both behind on major releases

### CODE REVIEW

**Comment by TylerBarnes** [comment]
WP will require some additional steps, the benchmark gql queries will need to be updated and the WP backends will need to have their plugins updated.

**Comment by pvdz** [comment]
Contentful is probably fine. Were you able to test it?

**Comment by KyleAMathews** [comment]
I wasn't sure how to actually — DM me please where this is documented?
--
Kyle Mathews

Blog: *http://bricolage.io <http://bricolage.io>*
Twitter: http://twitter.com/kylemathews

**Comment by KyleAMathews** [comment]
Ok tested the Contentful benchmark locally and it built just fine.

I've removed WordPress as that needs more work externally.

**Pull request merged**
