### PR TITLE
ADD storybooks.js.io

### PR DESCRIPTION
**Pull request by ndelangen**
[Storybooks](https://github.com/storybooks) documentation is generated with gatsby, we're really happy with it! ❤️

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit a900a2ff1557060ef13c338772c0984f50a28980

https://app.netlify.com/sites/gatsbygram/deploys/5919785e424ef210fb4618c4

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit a900a2ff1557060ef13c338772c0984f50a28980

https://app.netlify.com/sites/gatsbyjs/deploys/5919785e424ef210fb4618c1

**Comment by ndelangen** [comment]
I can't find what to do about netlify rejecting this:

details link directs to: (which results in a 404, for me)
https://app.netlify.com/sites/using-drupal/deploys/5919785e424ef210fb4618c7

**Comment by shilman** [comment]
@ndelangen I added storybooks to the list a couple weeks ago, so probably this PR is redundant:

https://github.com/gatsbyjs/gatsby/pull/905

**Comment by KyleAMathews** [comment]
@ndelangen sorry about the Netlify errors! They're enabled for building stuff for 1.0 so just error on the master branch but there's no way to disable them for this branch AFAIK...

And yeah, @shilman did add this already but glad it's working out well for y'all!

**Comment by ndelangen** [comment]
Whoops miscommunication on our parts, sorry.

Thanks for the awesome package!

**Pull request closed without merging**
