### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by vyaspranjal33**
fixed navigation to part-one

### CODE REVIEW

**Comment by DSchau** [comment]
Hey! Thanks so much for opening a pull request!

The change you’ve proposed is not going to be accepted because this change doesn't meaningfully improve docs, fix a bug, or otherwise improve functionality. Additionally, this isn't the correct route (index.md -> index.html via the static build process)

We absolutely want to have you as a contributor, so please take a look at [our open issues][open-issues] for ideas, and please reach out to us on Twitter at @gatsbyjs with questions.

We offer pair programming sessions if you’d like to work with one of our maintainers to make your first contribution.

Thanks again, and we look forward to seeing more PRs from you in the future! :muscle::purple_heart:

[open-issues]: https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by vyaspranjal33** [comment]
@DSchau  see this 
image

**Comment by vyaspranjal33** [comment]
@DSchau  i fixed above error by adding index.md

**Comment by DSchau** [comment]
@vyaspranjal33 got it! However, that also means you'd be breaking the [tutorial here](https://www.gatsbyjs.org/tutorial/part-zero/), since they're driven by those exact Markdown files.

**Comment by DSchau** [comment]
@vyaspranjal33 I'm not sure there's an issue here. We expect our docs to be navigated on gatsbyjs.org not _necessarily_ directly within Github. We could re-write links to remove index.md with a Markdown plugin, but that seems like a little more hassle than it's worth!

I'd recommend checking out the [open issues](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), particularly those that are [good for first issues](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22).

**Pull request closed without merging**
