### PR TITLE
fix(blog): MagMutual - fix format

### PR DESCRIPTION
**Pull request by muescha**
## Description

changed:

- apply formatting like on other [`Why xxx?`-sections](https://www.gatsbyjs.org/blog/2020-03-30-Fast-Secure-Flexible-MagMutual/#why-gatsby), otherwise it is a one big paragraph

## Related Issues

- #22602 `Blog case study mag mutual`

## Related Links

- https://www.gatsbyjs.org/blog/2020-03-30-Fast-Secure-Flexible-MagMutual/#why-gatsby

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR, but as this is a stylistic decision rather than a content one I'm going to close this and leave it as is.

**Comment by muescha** [comment]
you see in the markdown code that there is are new lines and it is intended from the author that it should be on a new line and not in one big paragraph.

Please compare the paragraph in Gatsby Blog vs same block on Drupal blog post:

Gatsby:
Bildschirmfoto 2020-04-14 um 16 21 00

Drupal:
https://www.drupal.org/case-study/magmutual-insurance-drupal-8-gatsby-redesign

Bildschirmfoto 2020-04-14 um 16 23 33

**Comment by muescha** [comment]
b/c i ask for a second review i reopen the PR

**Comment by laurieontech** [comment]
Understood. Thanks for the follow up.

**Pull request merged**
