### PR TITLE
Update readme link for Image Query Fragments

### PR DESCRIPTION
**Pull request by steoneill**
## Description
updated the link for Image Query Fragments

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! Since READMEs are leveraged by multiple different tools we don't use a relative path for links in those. So I'm going to close this.

However, we'd love to have you as a contributor so please take a look at open issues!

**Comment by muescha** [comment]
@laurieontech are links in README also relative path?
i was expecting only inside the `/docs/**` relative?

**Comment by laurieontech** [comment]
They are not, which means I flipped this PR around in my head. Going to reopen and merge.

**Comment by muescha** [comment]
@steoneill thx for the catch and the PR :)

**Pull request merged**
