### PR TITLE
chore(showcase): Add narrationbox.com

### PR DESCRIPTION
**Pull request by Immortalin**

### CODE REVIEW

**Comment by Immortalin** [comment]
@aishablake done.

**Comment by AishaBlake** [comment]
Actually, @Immortalin, it looks like we've now got a merge conflict. That's likely because I merged a ton of changes to this file yesterday before I noticed you'd addressed my comment. I'm not entirely sure why I'm not able to do this myself. Do you see a checkbox that says something about [enabling edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests)?

**Comment by Immortalin** [comment]
@debuggermalhotra

**Comment by Immortalin** [comment]
@AishaBlake I think you have access to the repo now

**Comment by AishaBlake** [comment]
> @AishaBlake I think you have access to the repo now

Hey, @Immortalin! I'm sorry about all the back and forth. I still can't edit this PR branch directly, so it's going to continue to fall out of sync anytime the `sites.yaml` file is updated. I'm not sure what's happening there if you've got "Allow edits from maintainers." checked. I don't need access to your repo, only to edit this branch.

**Comment by debuggermalhotra** [comment]
Hey! @AishaBlake sadly there seems to be no option like this and I am the owner of the org. 
Screenshot 2020-07-18 at 00 34 30

**Comment by Immortalin** [comment]
@AishaBlake @debuggermalhotra issue fixed. There is a [bug for organisation-owned repos](https://github.community/t/how-can-we-enable-allow-edits-from-maintainers-by-default/2847/3), transferring it to my personal account fixed it.

**Pull request merged**
