### PR TITLE
Create deploying-to-cloudflare-pages.md

### PR DESCRIPTION
**Pull request by Omar8345**
## Description

I written an informative detailed document on how to deploy a **Gatsby** site on **Cloudflare Pages**

### Documentation

This has been also written on Cloudflare Developer Docs, [Deploy a Gatsby site](https://developers.cloudflare.com/pages/framework-guides/deploy-a-gatsby-site/)

## Related Issues

There are no any related issue to this PR!

**Thanks for your help 😀**

### CODE REVIEW

**Comment by Omar8345** [comment]
Sorry for that @marvinjude, but I didn't have the permission to add the documentation tag! Sorry!

**Comment by marvinjude** [comment]
No worries @Omar8345! It's the work of maintainers to add labels. Thanks for the contribution :)

**Comment by Omar8345** [comment]
Thanks @marvinjude for understanding the situation! Kindly, if possible, if you can check my document and merge the pull request because I am excited for swag 😀! Thanks!

**Comment by LekoArts** [comment]
Hi!

This guide already exists at https://developers.cloudflare.com/pages/framework-guides/deploy-a-gatsby-site/ so there's no need to add this to our own docs.

**Comment by Omar8345** [comment]
Also, that's how? Like see:

This guide and build to Netlify

On Netlify is there https://www.netlify.com/blog/2016/02/24/a-step-by-step-guide-gatsby-on-netlify/

On Gatsby, also there https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/deploying-to-netlify/


Then why declined and that is there repeated? :(

<ins>**I just noticed that the deploying to Netlify doc which I made last PR which was declined, was already there also on Gatsby Docs**</ins>

**Comment by Omar8345** [comment]
As I also added the link on Cloudflare as the doc on Gatsby!

**Pull request closed without merging**
