### PR TITLE
Add 'Site generating with the great GatsbyJS' blog post

### PR DESCRIPTION
**Pull request by daviddeejjames**
Thanks so much again for the opportunity to do a write up and thanks for developing a very cool piece of tech. Looking forward to building more sites with Gatsby and contributing back where I can 😃

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Awesome! Tweaked the title a bit and merging! Will tweet out once live.

**Comment by KyleAMathews** [comment]
@daviddeejjames I noticed after merging the images of the queries were missing. But generally it's a lot better to put code as text directly in the markdown e.g.

    ```graphql
    {
      allWordPressPosts { edges { node { id } } }
    }
    ```

**Comment by KyleAMathews** [comment]
Could you do another PR replacing the images with the queries?

**Comment by daviddeejjames** [comment]
Yep realised I forgot them too and thought I shouldve done them in markdown also... shall do it as soon as I get to a computer, cheers for the tweaks and tweet also!

**Pull request merged**
