### PR TITLE
queue idle work for prefetching

### LINKED ISSUE #21249: Warm route code during idle time to speed rendering new pages
The first time a page component is used requires its code to be parsed & evaled. This happens _after_ a link to the page is clicked at the moment which means the user waits for the 10-300ms required for this.

Ideally this parsing & evaling happens _before_ the link is clicked so the user doesn't experience any delay.

This could be done by a similar mechanism to how we prefetch page resources. When we predict a page might be visited & all its resources are loaded — we watch for quiet CPU time and then simulate rendering the page which would cause webpack to load the code & run it. Then when the page is actually visited, it'll be rendered as fast as possible.

### PR DESCRIPTION
**Pull request by herecydev**
## Description

@KyleAMathews

**Apologies If I've completely misunderstood the requirement**

Use window.requestIdleCallback to queue the `loadPage` (which is normally triggered on link hover). Configured to run if 80% of the frame is idle (as instructed by the browser), otherwise requeue until we get a decent idle frame.

TODO:
- [ ] Track pending idle work and cancel if an actual load page occurs before
- [ ] Lots more testing

From testing most pages takes 10-30ms on my machine.

## Related Issues

Fixes #21249

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Oh hey! Thanks for jumping on this.

I did mean something a bit different. Currently we run `loadPage` when someone hovers on a link — what I was thinking is we could do this in idle time & actually render the component (invisibly e.g. with `visibility: false`)  — `loadPage` is pretty cheap as we just make sure the code/data is available — an actual render would then have the browser JS engine parse/eval the code & make sure all the hot code paths are JITed for the actual render.

Make sense?

**Comment by herecydev** [comment]
> Make sense?

Okay think I'm getting you. As I understand, on the point of hovering over a link we've essentially got to point where: 

1. All resources are now loaded (app-data.json, page-data.json)
2. Component js file is dynamically imported and placed into pageResources

On link click:
3. Navigate occurs
4. Somewhere down the line, createElement is called on the component fetched in step 2

The problem as I see, is if we try to `createElement` any time sooner, surely a bunch of side effects can occur. Creating the element will call class constructors or FC body. Actually mounting the hidden component will start firing componentDidMount/useEffect calls.

Am I missing something or will this not lead to undesirable behavior?

**Comment by KyleAMathews** [comment]
Hmm yeah that's true :-) maybe this won't work... renderToString could work but does that require loading more React code?

**Comment by herecydev** [comment]
ReactDomServer.renderToString does work but does require a little more code. I've tried using that out with a simple test page.

I used `React.createElement` with `ReactDomServer.renderToString` on Link hover and wrapped a timer around those. I then wrapped a timer around the `createElement` in the pageRenderer.

I could see that the hover code was kicking in and rendering the component but the page wasn't sufficiently costly enough to warrant worrying about. For my test page which renders a handful of components chrome was reporting _fractions_ of a ms.

I'm happy to keep investigating, but I think I need something that is far more computationally expensive.

> the user waits for the 10-300ms required for this

From the original issue, where did you see this? Is there a repro that I can work from to test the impact of prerendering?

**Comment by KyleAMathews** [comment]
>the user waits for the 10-300ms required for this

This is most noticeable on slow devices for larger pages. I've noticed this playing with old android devices or laptops for example.

You can try e.g. adding a bunch of larger js modules to a page like d3 or three.js & throttling your CPU to 6x

**Comment by KyleAMathews** [comment]
Thanks for the exploration here @herecydev! It doesn't seem like it has as big of gain as hoped so let's close this PR for now.

**Pull request closed without merging**
