### PR TITLE
Update init-starter.js

### PR DESCRIPTION
**Pull request by kimown**
Fix shouldUseYarn is function

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Oh dear, thanks for fixing!

**Comment by KyleAMathews** [comment]
Published 1.0.5 with the fix.

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 4e8297ccbd73e7a9a928dd457f6b1a897d4a4315

https://app.netlify.com/sites/gatsbygram/deploys/595ece067960b17c9a6706e6

**Comment by jlengstorf** [comment]
Hiya @kimown! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
