### PR TITLE
Adding gatsby-plugin-reason

### PR DESCRIPTION
**Pull request by jasonrose**
There was a post today about integrating graphql into reason which I will try to roll into an update for this package soon.

I'm working on a `using-reason` example as well.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@chenglou @jaredly you'll be able to convert the Reason website soon to Reason! :-)

**Comment by jasonrose** [comment]
I'll probably be doing the port too 👍

**Comment by jasonrose** [comment]
I'm getting a 404 error when I look at the netlify failures.  How can I figure out what went wrong so that I can fix it?

**Comment by KyleAMathews** [comment]
There's a broken plugin atm which is causing a site build to fail...

Our setup with Netlify isn't ideal cause it doesn't allow contributors like yourself to view the build logs... thinking about moving builds off Netlify for that reason.

Anyways, in the meantime, just ignore that error.

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 2d683b3eb75095be2a974dc4a64679eca5731375

https://app.netlify.com/sites/using-glamor/deploys/5993fec4424ef261e444b66c

**Comment by leonfeng** [comment]
Any progress on this? Thanks!

**Comment by jasonrose** [comment]
I haven't looked at this in a while.  Getting embedded GraphQL to work might be sticky.  I haven't looked much into it yet.

**Comment by KyleAMathews** [comment]
>I haven't looked at this in a while. Getting embedded GraphQL to work might be sticky.

If Reason can compile to a template string literal then it can work! There's an API plugins can implement to preprocess source to make queries processable by Gatsby https://www.gatsbyjs.org/docs/node-apis/#preprocessSource

**Comment by kennetpostigo** [comment]
Is this still being worked on?

**Comment by KyleAMathews** [comment]
Anyone want to finish this off?

**Comment by muhajirframe** [comment]
any update?

**Comment by KyleAMathews** [comment]
Closing this so people stop hoping it'll go in soon :-) Would love someone to pick this up and finish it out!

**Pull request closed without merging**
