### PR TITLE
[WIP] webpack 3

### PR DESCRIPTION
**Pull request by craig-mulligan**
Sluggin away at this, still in a very early state.

Moved from `webpack-configurator` to `webpack-merge` it supports webpack > 2 and seems to be well supported. 

I've now hit `webpack-require` which doesn't support > 2.x. It doesn't look very well maintained so wondering if we pr there, or find another solution for loading `html.js`.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit dd11438440e1dd8f1e8757db89f7a98f7ebce378

https://app.netlify.com/sites/using-styled-components/deploys/594dba698ebdd94a112482fc

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit dd11438440e1dd8f1e8757db89f7a98f7ebce378

https://app.netlify.com/sites/using-contentful/deploys/594dba698ebdd94a112482ff

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit dd11438440e1dd8f1e8757db89f7a98f7ebce378

https://app.netlify.com/sites/gatsbygram/deploys/594dba688ebdd94a112482e7

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit dd11438440e1dd8f1e8757db89f7a98f7ebce378

https://app.netlify.com/sites/using-glamor/deploys/594dba698ebdd94a112482f9

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit dd11438440e1dd8f1e8757db89f7a98f7ebce378

https://app.netlify.com/sites/image-processing/deploys/594dba698ebdd94a112482f6

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit dd11438440e1dd8f1e8757db89f7a98f7ebce378

https://app.netlify.com/sites/using-postcss-sass/deploys/594dba698ebdd94a112482f0

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit dd11438440e1dd8f1e8757db89f7a98f7ebce378

https://app.netlify.com/sites/gatsbyjs/deploys/594dba688ebdd94a112482e4

**Comment by KyleAMathews** [comment]
Woah!!! So happy you're working on this. I'd written off upgrading webpack in interest of getting v1 out the door sooner so really excited to see you working on this.

It's late here and I just got home but a few quick notes on my thinking on the upgrade / potential APIs.

* We should copy CRA's webpack config to the extent possible. They've had a lot of people pick over their config and it's a finely tuned piece of art.
* I'd really love to pull over their error model though that can come later.
* Long-term caching is incredibly important to get right. We're not entirely with v1 of webpack and we'll be able to do better. This guide looks spot on https://medium.com/webpack/predictable-long-term-caching-with-webpack-d3eee1d3fa31
* We should make the API for modifying the webpack config work the same way as our other APIs. Specifically use [our operators](https://www.gatsbyjs.org/docs/api-specification/#operators) with bound action creators https://www.gatsbyjs.org/docs/bound-action-creators/ So instead of directly mutating a config like we do now (blech), plugins/sites should call functions like `setWebpackPlugin` or `deleteWebpackModuleRule`, or `createWebpackLoader`, etc. We should have an internal plugin which sets up the default rules and then let's plugins have at it. The config is then "reduced" in Redux to the final config like normal. We could setup some invariants to prevent people from deleting or modifying required configuration. webpack-merge looks perfect for the reducer step. I think an API like this is much easier to reason about but from us maintaining it internally as well as site/plugin authors. It also conveniently makes this trivial to test which has been really nice.

**Comment by KyleAMathews** [comment]
Oh and on webpack-require. What we really need to do for the dev server is just do a ssr build. Right now neither babel or webpack is supporting during development for gatsby-ssr.js plugin files which is causing trouble https://github.com/gatsbyjs/gatsby/issues/1156

So we can retire webpack-require and just reuse what we're doing to build HTML for prod builds.

**Comment by craig-mulligan** [comment]
Sweet that makes sense. Except the ssr, I'll have to take a look at the code.

The one thing about the api is that I wonder if we are over complicating it? Is there a real usecase for deleting a loader/plugin I think our baseConfig should be the mininal required for gatsby to work? And then you'd just add things to the config via way of plugins, it may be better to just have a single redux action `addWebpackConfig` which accepts a object that get's smart merged into the base config.

I can definitely see how some plugins may not work well together, but I don't think having an action for every key would help there. What do you?

**Comment by KyleAMathews** [comment]
We definitely don't have to add all possible APIs at once so I'm fine leaving out deleting until a real use case presents itself.

I do think the bound action creators should be at a higher resolution. The webpack config object is complex so asking people to create merge objects against the entire thing can be pretty challenging and error prone.

Also we use `set` for merging not `add`. See the API spec link I posted previously.

**Comment by KyleAMathews** [comment]
(this is borrowed from React btw e.g. `setState`.)

**Comment by craig-mulligan** [comment]
Heads up, I'm going on holiday for a ~10 days and won't get to this very soon. If someone wants to pick it up then have at it, it should be fairly straight forward now that #1254 is done.

**Comment by KyleAMathews** [comment]
Gatsby 1.0 is out! So please open this PR again against master. Let's aim towards updating Gatsby to webpack 3 for a 2.0 release.

**Comment by cr101** [comment]
webpack 3.4 is out

**Comment by jquense** [comment]
@KyleAMathews I'm gonna make a pass at picking this up. I have a few concerns though. 

- I think that any API we add on top of modifying the webpack config is going to be a "Bad Idea" in the long run. Webpack is too complicated and has too many moving parts. Many have tried and failed to add a nicer interface on top of it and invariably you lose the the expressiveness webpack provides. If we don't allow _full_ control over the webpack config it's going to severely limit potential use-cases.
- The way that plugins reference loaders is flawed right now, plugins just say they want to use `css-loader`, for instance, without installing it locally. they are implicitly relying on webpack resolving that to gatsby's installed loader, and not whatever is hoisted by npm during the install. This is really buggy. Ultimately any loader webpack that gatsby uses needs to be explitly resolved to its local location via `require.resolve`. However this means any plugin that also wants to use `css-loader` will have to install it and do the same thing. You can run into trouble with complex things like `extract-text`, where you _really_ need to use the same instance of the package in the loader.extract, and the plugin in `plugins`. Right now no style plugins add their plugin, again relying on npm/yarn deduping that to one correct instance. 

One way I've seen to handle more module webpack bits is via a stragey like: https://github.com/jquense/webpack-atoms/blob/master/index.js which is **not** really an abstraction but a bunch of functions that return chunks of plain webpack configs. Its really nice though because its very easy to share and pass around. Theoretically you can do something similar in Gatsby and pass the basic atoms down to plugins to use if they want to reuse pieces, but doesn't require learning (or creating) a new thing.

**Comment by KyleAMathews** [comment]
@jquense awesome! Agree with everything you've said. The only thing I care about webpack is that we ship a default config that meets ~90% of use cases and we make it easy to extend/change as people want in plugins or in individual sites.

I haven't paid too much attention to the webpack abstraction world but you're reasoning makes sense. It is complicated and it's still quite new so there'll probably be more breaking changes in the future so better to stay close to the metal for now. Perhaps in a few years it'd make sense to build up heavier abstractions but not now.

webpack-atoms looks really nice. I trust your instincts so if you think it'd make sense to make that a first-class part of Gatsby then go for it.

One really nice thing about upgrading is better naming control over bundles https://medium.com/webpack/predictable-long-term-caching-with-webpack-d3eee1d3fa31

Thoughts on webpack 2 vs 3? Extract-text plugin seems like it's having lots of trouble still in 3 https://github.com/webpack-contrib/extract-text-webpack-plugin/issues

This would be another major release but I have zero problems with shipping some breaking changes early on in 1.0 cycle. Should be an easy upgrade for everyone except those who've made custom modifications to webpack in their sites. That's the nice thing about plugins is we can control ensuring they're upgrading correctly.

@craig-mulligan you been working any more on a webpack upgrade? Ok with @jquense taking a crack at things?

**Comment by craig-mulligan** [comment]
I haven't had a chance to look at it again, but stoked for @jquense get things going again 👍 I definitely agree with not learning a new api to modify webpack, if we can relatively easily smart merge plugin additions. 

Next.js just passes the config to the user who is responsible for mutating the config and sending it back, I think this is a pretty good approach (similar to what we currently do), but there maybe problems with plugin conflicts?

**Comment by sant123** [comment]
Any advance on this? Just asking 😄

**Comment by jquense** [comment]
this isn't happening in `v1`, in v2 it's already been merged!

**Comment by sant123** [comment]
But v2 is already in alpha right?

**Pull request closed without merging**
