### PR TITLE
fix(gatsby-plugin-styletron): Styletron to peerDependencies

### PR DESCRIPTION
**Pull request by nadiia**
## Description

Move `styletron-react` and `styletron-engine-atomic` to `peerDependencies` in `gatsby-plugin-styletron`.

### CODE REVIEW

**Comment by vladar** [comment]
Can you explain the problem you have? We typically encourage everyone to [open an issue before the PR](https://www.gatsbyjs.org/contributing/how-to-open-a-pull-request/#things-to-know-before-opening-a-pr) so that there was enough context on the problem.

**Comment by nadiia** [comment]
We don't want projects to end up with more than one Styletron version or not be able to upgrade as Styletron is plugins dependency vs peer.

**Comment by wardpeet** [comment]
Successfully published in gatsby-plugin-styletron@5.0.0

**Comment by wardpeet** [comment]
Thank you for your PR! And sorry to keep you waiting to get this resolved.

**Pull request merged**
