### PR TITLE
add source_url, date_added, gatsby_version to showcase-submissions

### PR DESCRIPTION
**Pull request by janosh**
Following up on [this discussion](https://github.com/gatsbyjs/gatsby/pull/6692#issuecomment-407380519).

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 446cb78cbf78a9bb90177716b504e1619c212552

https://app.netlify.com/sites/using-postcss-sass/deploys/5b61a5f273f2cf74ae46f184

**Comment by m-allanson** [comment]
Huh, I actually didn't know we had the `date_added` and `gatsby_version` fields. I've removed them for now as it doesn't look like they're being used.

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit ecc1376cb66ffae7b963c5cfc7a54b7409b6bef4

https://app.netlify.com/sites/using-glamor/deploys/5b6314ccb312746eae56073e

**Comment by KyleAMathews** [comment]
Deploy preview for *using-styled-components* failed.

Built with commit ecc1376cb66ffae7b963c5cfc7a54b7409b6bef4

https://app.netlify.com/sites/using-styled-components/deploys/5b6314cdb312746eae560741

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit ecc1376cb66ffae7b963c5cfc7a54b7409b6bef4

https://app.netlify.com/sites/image-processing/deploys/5b6314ccb312746eae56073b

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit ecc1376cb66ffae7b963c5cfc7a54b7409b6bef4

https://app.netlify.com/sites/using-contentful/deploys/5b6314cdb312746eae560744

**Comment by KyleAMathews** [comment]
Deploy preview for *using-jss* failed.

Built with commit ecc1376cb66ffae7b963c5cfc7a54b7409b6bef4

https://app.netlify.com/sites/using-jss/deploys/5b6314cfb312746eae56075c

**Comment by Janosh** [comment]
> Huh, I actually didn't know we had the `date_added` and `gatsby_version` fields. I've removed them for now as it doesn't look like they're being used.

I think it would be a good idea to introduce them, though. I would definitely be interested in that information when browsing the showcase.

**Comment by m-allanson** [comment]
> I would definitely be interested in that information when browsing the showcase.

Yeah I agree it'd definitely be good information to have, but for now I don't think we should encourage people to spend the extra time adding this info if it won't appear in the showcase. 

I've added a note to #6538, as this is somethign that could be automated quite nicely.

**Pull request merged**
