### PR TITLE
Need to check if actual full file is there

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by benstepp** [comment]
Probably going to have to do this for  https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/static-entry.js#L5 too.

I guess webpack prefers a .js in a further down modulesDirectory than another filetype (.jsx/cjsx/*). I'll write a test this evening to cover that the user can overwrite the defaults.

**Comment by KyleAMathews** [comment]
@benstepp well.... the Webpack resolver actual works correctly. The problem here is we're trying to decide if an acceptable html component exists before falling back on the default. Webpack does this automatically for us but since we're in a node environment, this is a crude way to replicate its algorithm. Make sense?

**Comment by benstepp** [comment]
Ah that makes sense.

I get lost in webpack land quickly.

**Comment by KyleAMathews** [comment]
Yeah, that was one of the first tricks I had to learn with Gatsby, keeping track of whether I was in Node or Webpack land as they're parallel but not quite identical lands.

**Comment by KyleAMathews** [comment]
Used node-glob to check if `/html.*` exists. Works now. Will do new release.

**Pull request merged**
