### PR TITLE
Update unit-testing.md

### PR DESCRIPTION
**Pull request by RobinCsl**
Fixes issue #9766

### CODE REVIEW

**Comment by shannonbux** [comment]
@LekoArts and @DSchau want to do a brief review here and then merge?

**Comment by RobinCsl** [comment]
@shannonbux Do you have any example in the current Gatsby docs of what you mean? Do you mean that, for instance, the TypeScript section is somewhat optional for most people so that fact should be clearer?

**Comment by shannonbux** [comment]
Hi @RobinCsl in a second read through, I think what I realized is that the "setting up your environment" section is very long and it would be nice to have level 3 headers to break it up by options. Just an idea if you're interested in working on something like that!

**Comment by RobinCsl** [comment]
Hi @shannonbux, so for instance, you would see all of the main sections of `Unit testing` in the side navigation bar. Do I understand your idea correctly? If that's the case, I could look into that!
screenshot 2018-11-08 at 09 31 20

**Comment by LekoArts** [comment]
She means that you use `<h3>` headings before the different options. The thing you screencaptured is the sidebar and I don't think it would make sense to further split this up there.

**Pull request merged**
