### PR TITLE
WIP new testing infrastructure

### PR DESCRIPTION
**Pull request by KyleAMathews**
We've been using (abusing?) Netlify for testing building example sites as integration tests.

This has a few problems:

* Netlify logs aren't easily accessible to people other than me
* Netlify limits how fast we can build sites
* It's not obvious if a site fails because Netlify adding a comment on every site build got super noisy so I had to turn it off. So sites can stop building and we won't notice it for a while.
* There's a lot of manual work to setup each new site — would much prefer it's automatic — just build every site in the examples directory
* We can't extend what we're testing e.g. would be nice to calculate hash of every generated file and warn if things change.
* Also really want to add build & client performance testing — track build length, max-memory used, various frontend performance metrics on e.g. webpagetest
* Also would like to add automated client testing w/ Chrome Puppeteer. Much easier to do this if we control the infrastructure

### CODE REVIEW

**Comment by KyleAMathews** [comment]
This is part 2 of a PR last month https://github.com/gatsbyjs/gatsby/pull/2920

**Comment by KyleAMathews** [comment]
Oh didn't finish my explanation :-)

So what this PR will add is we'll build every commit of every PR on 
AWS CodeBuild and we'll report back the result in a comment (and updating it as more commits are added).

This will make it easy to see at a glance if all example sites are building giving us more confidence that PRs are solid.

On top of this, we'll add performance testing both for builds & frontend loading.

**Comment by jquense** [comment]
🔥

**Comment by KyleAMathews** [comment]
There's some good stuff here and we're definitely going to do this but we'll be doing it in a somewhat different way so closing this for now.

**Pull request closed without merging**
