### PR TITLE
chore(docs): rewrote the client-only routes chapter

### PR DESCRIPTION
**Pull request by ehrencrona**
Prompted by https://github.com/gatsbyjs/gatsby/issues/23392, I started reading through the client-only routes chapter and found it somewhat confusing.

I therefore rewrote it quite substantially with the following aims:

 * try to make it clearer what this is actually about: how sometimes you don't want or need the server-side HTML for a page. the distinction between client side and build time execution is famously difficult to explain
 * try to make clearer how there are essentially two steps involved: the router page needs to be invoked and then the router page needs to perform the actual routing. i also wanted to mention the role the 404 page plays in this as i could not understand how this was even possible with static HTML when i first read it.
 * disentangle the issue of client-side routing from from authentication. i therefore just removed the authentication part and referred to the existing chapter on this as there was substantial overlap.
 * the existing chapter was mixing elements of a tutorial and documentation. i tried to draw a clearer distinction between the two styles.
 * clarifying that "Configuring and handling client-only routes on a server" is an *alternative* to `matchPath` (and normally not wanted / possible) 
 * cleaned up the language a bit

## Related Issues

Addresses #23392

### CODE REVIEW

**Comment by ehrencrona** [comment]
Question: I'd like to now rename the whole file `client-only-routes` rather than `client-only-routes-and-user-authentication`. Is that safe to do? Existing links to the documentation would break.

**Comment by ehrencrona** [comment]
@Ekwuno, would you want to review this? I saw you were involved in the last major edit of the page.

**Comment by muescha** [comment]
> Existing links to the documentation would break.

for external links there is an `redirects.yml`

**Comment by ehrencrona** [comment]
Great, I renamed the page.

**Comment by ehrencrona** [comment]
No idea why tests fail. Rebasing.

**Comment by marcysutton** [comment]
Thanks for submitting this PR, I'm currently reviewing it. But I also want to drop a note that we prefer issues to be filed before PRs so we can discuss a direction–especially for such significant changes to the docs. That will ensure your time isn't wasted if the team decides against merging a PR that wasn't discussed beforehand. Something to keep in mind! https://www.gatsbyjs.org/contributing/how-to-open-a-pull-request/#things-to-know-before-opening-a-pr

**Comment by marcysutton** [comment]
Hi @ehrencrona, after giving this PR some thought I'm going to opt for closing it since there are pretty significant changes in here that we didn't discuss first in an issue. Most importantly, we don't want want to outright remove the parts on authentication from the client-only routes page without a more thought-through content migration. There is a "Building a Site with Authentication" page up a level in the navigation tree, but it's not a 1:1 substitute for the information on the Client-only Routes and Authentication page. Quite a few of the link changes in this PR don't account for that content removal, either, so further changes throughout the docs would be necessary.

My recommendation would be to open an issue to discuss the intended changes, including what information would be updated or removed and why. You can cherry pick parts of this PR later if they still apply, so you wouldn't have to start completely over.

Thanks for taking the time to contribute to Gatsby. We really appreciate it and look forward to seeing what you're up to next!

**Comment by ehrencrona** [comment]
No worries. You’re right, I should have consulted with you before doing such a major rewrite. I didn’t actually set out to change that much, but it kind of grew :)

**Pull request closed without merging**
