### PR TITLE
Document how to create custom fragments

### PR DESCRIPTION
**Pull request by jiahaog**
I noticed that fragments aren't really documented in the docs, so opening a pull request to document it! Let me know if any of it is wrong / needs to be clarified!

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Oh sweet! This is very nicely written and a great fit.

Could you tweak the example a bit though? Your example is a valid one but I think the most common usage of fragments is and should be when components export a fragment for the data they need e.g. this component on gatsbyjs.org https://github.com/gatsbyjs/gatsby/blob/951af8224514e9db53582bd68d6a05b8cc9047e5/www/src/components/function-list.js

**Comment by jiahaog** [comment]
@KyleAMathews I've added another example for that, please let me know if there are any issues, and if I should remove the other example for "global" helper fragments 😄

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit ae6b958c0bf11c38f902e86f1e13fb015da6af45

https://app.netlify.com/sites/using-glamor/deploys/5a7d0bce0b79b7404383cd37

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
