### PR TITLE
fix(www): showcase’s Collapsible component not behaving properly in Firefox

### PR DESCRIPTION
**Pull request by ryanditjia**
## Description

Collapsible component (the checkboxes in https://www.gatsbyjs.org/showcase/) isn’t scrolling properly in Firefox.

## Related Issues
#11574 
#11644

### CODE REVIEW

**Comment by ryanditjia** [comment]
Trying to scroll on the Category list
Current: https://giphy.com/gifs/3dgeDlHWdT7GJQghmr
Fixed: https://giphy.com/gifs/1YaV2oXB66eZZQN6Fv

Issue is only with Firefox.

**Comment by wardpeet** [comment]
weird I don't get this issue:
I'm running Firefox Quantum 65.0.2 (64-bit)
firefox-bug-showcase

**Comment by ryanditjia** [comment]
Better explanation: the category list should scroll independently from the rest of the page (try it with Chrome / Safari). @wardpeet your GIF shows the same issue.

**Comment by wardpeet** [comment]
Ah thanks for clarifying. I thought something else was going on! i'll check your PR and get it merged! 💪

**Comment by fk** [comment]
Thank you @ryanditjia! 🙏

**Pull request merged**
