### PR TITLE
[1.0] RSS Feed Plugin

### PR DESCRIPTION
**Pull request by nicholaswyoung**
Here's the initial commit of an RSS feed generator plugin for Gatsby 1.0. Documentation forthcoming.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 778379a5444e45ab67de3d8b60185458438eb482

https://app.netlify.com/sites/gatsbygram/deploys/592efa4dcf321c6aafac215c

**Comment by KyleAMathews** [comment]
This is awesome! Exactly how I was hoping someone would build it :-) I'll have to add it to my blog soon. One tweak is modifyHeadComponents got changed yesterday to https://www.gatsbyjs.org/docs/ssr-apis/#createHeadComponents

Also a very simple example site would be great!

**Comment by nicholaswyoung** [comment]
I hope to get this updated and ready to merge today or tomorrow. However, as discussed in chat, I would like to include support for multiple RSS Feeds (this is useful for my site, as I'm creating multiple feeds for various podcasts that I've hosted over the years).

What do you think of this API?

```javascript
{
  resolve: `gatsby-plugin-feed`,
  options: {
    // global query that will be executed and merged into data from feed-specific queries
    query: ``,
    feeds: [{
      // load entries for this specific feed
      query: ``,
      output: `rss.xml`, // automatically map to ./public as root
      addItems: (data, feed) => {}, // serialize each item
      // ... extra options for new Feed generator object
    }]
  }
}
```

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 9e05fd7e02a1a57b8793fe9107c3fd6520acebf4

https://app.netlify.com/sites/using-contentful/deploys/593375df424ef243cb71c92e

**Comment by nicholaswyoung** [comment]
@KyleAMathews This should be ready to go.

**Comment by KyleAMathews** [comment]
Looks awesome! Won't have time to get this properly reviewed and in until Monday but I'm really excited about this. Exactly the sort of thing Gatsby is designed for. Once all your data is structured and queryable, building new projections like this as plugins is very doable.

Two other things you could do. One is add the plugin to the plugins.md file for the docs. Second is add the plugin to gatsbyjs for the blog.

**Pull request merged**
