### PR TITLE
fix(gatsby-plugin-fullstory): Updated to Edge URL + Add Updated JS Code

### LINKED ISSUE #23088: Update Full Story App with the correct URL + JS Code
Refer to the screenshot below from GTMetrix, the URL has been updated to `https://edge.fullstory.com/s/fs.js`

Screenshot 2020-04-14 at 2 19 02 PM

The plugin still calls `https://fullstory.com/s/fs.js`

Also, 
was looking into difference, 
NEW CODE COMPLETE : 

```
<script>
window['_fs_debug'] = false;
window['_fs_host'] = 'fullstory.com';
window['_fs_script'] = 'edge.fullstory.com/s/fs.js';
window['_fs_org'] = '<MY CODE>';
window['_fs_namespace'] = 'FS';
(function(m,n,e,t,l,o,g,y){
    if (e in m) {if(m.console && m.console.log) { m.console.log('FullStory namespace conflict. Please set window["_fs_namespace"].');} return;}
    g=m[e]=function(a,b,s){g.q?g.q.push([a,b,s]):g._api(a,b,s);};g.q=[];
    o=n.createElement(t);o.async=1;o.crossOrigin='anonymous';o.src='https://'+_fs_script;
    y=n.getElementsByTagName(t)[0];y.parentNode.insertBefore(o,y);
    g.identify=function(i,v,s){g(l,{uid:i},s);if(v)g(l,v,s)};g.setUserVars=function(v,s){g(l,v,s)};g.event=function(i,v,s){g('event',{n:i,p:v},s)};
    g.anonymize=function(){g.identify(!!0)};
    g.shutdown=function(){g("rec",!1)};g.restart=function(){g("rec",!0)};
    g.log = function(a,b){g("log",[a,b])};
    g.consent=function(a){g("consent",!arguments.length||a)};
    g.identifyAccount=function(i,v){o='account';v=v||{};v.acctId=i;g(o,v)};
    g.clearUserCookie=function(){};
    g._w={};y='XMLHttpRequest';g._w[y]=m[y];y='fetch';g._w[y]=m[y];
    if(m[y])m[y]=function(){return g._w[y].apply(this,arguments)};
    g._v="1.2.0";
})(window,document,window['_fs_namespace'],'script','user');
</script>
```

OLD CODE (As currently in the plugin) 
```
<script>
window['_fs_debug'] = false;
window['_fs_host'] = 'fullstory.com';
window['_fs_script'] = 'fullstory.com/s/fs.js';
window['_fs_org'] = '<MY CODE>';
window['_fs_namespace'] = 'FS';
(function(m,n,e,t,l,o,g,y){
    if (e in m) {if(m.console && m.console.log) { m.console.log('FullStory namespace conflict. Please set window["_fs_namespace"].');} return;}
    g=m[e]=function(a,b,s){g.q?g.q.push([a,b,s]):g._api(a,b,s);};g.q=[];
    o=n.createElement(t);o.async=1;o.crossOrigin='anonymous';o.src='https://'+_fs_script;
    y=n.getElementsByTagName(t)[0];y.parentNode.insertBefore(o,y);
    g.identify=function(i,v,s){g(l,{uid:i},s);if(v)g(l,v,s)};g.setUserVars=function(v,s){g(l,v,s)};g.event=function(i,v,s){g('event',{n:i,p:v},s)};
    g.shutdown=function(){g("rec",!1)};g.restart=function(){g("rec",!0)};
    g.log = function(a,b) { g("log", [a,b]) };
    g.consent=function(a){g("consent",!arguments.length||a)};
    g.identifyAccount=function(i,v){o='account';v=v||{};v.acctId=i;g(o,v)};
    g.clearUserCookie=function(){};
})(window,document,window['_fs_namespace'],'script','user');
</script>
```

Quick Text Compare Online 
Screenshot 2020-04-14 at 2 25 05 PM

### PR DESCRIPTION
**Pull request by ar0ra1**
Fixes #23088

### CODE REVIEW

**Comment by LekoArts** [comment]
Related to: https://github.com/gatsbyjs/gatsby/pull/18461

I signed up for a new account and was given this code:
image

```js
<script>
window['_fs_debug'] = false;
window['_fs_host'] = 'fullstory.com';
window['_fs_script'] = 'edge.fullstory.com/s/fs.js';
window['_fs_org'] = '<CODE>';
window['_fs_namespace'] = 'FS';
(function(m,n,e,t,l,o,g,y){
    if (e in m) {if(m.console && m.console.log) { m.console.log('FullStory namespace conflict. Please set window["_fs_namespace"].');} return;}
    g=m[e]=function(a,b,s){g.q?g.q.push([a,b,s]):g._api(a,b,s);};g.q=[];
    o=n.createElement(t);o.async=1;o.crossOrigin='anonymous';o.src='https://'+_fs_script;
    y=n.getElementsByTagName(t)[0];y.parentNode.insertBefore(o,y);
    g.identify=function(i,v,s){g(l,{uid:i},s);if(v)g(l,v,s)};g.setUserVars=function(v,s){g(l,v,s)};g.event=function(i,v,s){g('event',{n:i,p:v},s)};
    g.anonymize=function(){g.identify(!!0)};
    g.shutdown=function(){g("rec",!1)};g.restart=function(){g("rec",!0)};
    g.log = function(a,b){g("log",[a,b])};
    g.consent=function(a){g("consent",!arguments.length||a)};
    g.identifyAccount=function(i,v){o='account';v=v||{};v.acctId=i;g(o,v)};
    g.clearUserCookie=function(){};
    g._w={};y='XMLHttpRequest';g._w[y]=m[y];y='fetch';g._w[y]=m[y];
    if(m[y])m[y]=function(){return g._w[y].apply(this,arguments)};
    g._v="1.2.0";
})(window,document,window['_fs_namespace'],'script','user');
</script>
```

**Comment by LekoArts** [comment]
Ok, snapshot tests are failing. Can you please update those?

**Comment by ar0ra1** [comment]
I really don't understand why the tests are failing, it's merely a 3 line update.

**Comment by LekoArts** [comment]
The plugin has a test: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-fullstory/src/__tests__/gatsby-ssr.js

And it creates a snapshot (https://jestjs.io/docs/en/snapshot-testing) for the code. So I needed to run `yarn jest -u gatsby-plugin-fullstory` on your repository. For the future I'd advise to create a separate branch and not change stuff on `master` branch, as written here: https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/

**Comment by ar0ra1** [comment]
My bad, didn't see the docs. 
Will keep in mind for future references. 
Thank you!

**Comment by LekoArts** [comment]
Published in `gatsby-plugin-fullstory@2.2.2`

**Pull request merged**
