### PR TITLE
Rename every occurrence of Javascript to JavaScript

### PR DESCRIPTION
**Pull request by detj**
In most places throughout the docs JavaScript is spelt with uppercase `J` and `S`. But at some places, it was not. This PR fixes that. Only files inside `/docs` directory was touched.

A few of them are blog post files. I'm not sure if there's any practical implication of touching them as this would change modification date & time of those files. Is this a concern?

### CODE REVIEW

**Comment by m-allanson** [comment]
Thanks @detj, this is a nice update to keep things consistent 👍 

However, it seems your pull request is pulling in all the commits from another branch. We recently changed the branches around so the code for Gatsby v2 has been merged into the `master` branch.

Could you create a new Pull Request that includes [just your changes](https://github.com/gatsbyjs/gatsby/pull/6047/commits/7db8adcde8be10e208e040befb961b4c8276f8b9)? You'll probably need to update your local copy of the `master` branch to match the newest changes from GitHub, then re-apply your changes and create a new Pull Request from there.

I'm going to close this Pull Request, but please ask more questions here if my request is not clear!

**Comment by m-allanson** [comment]
Oh and to answer your question - yes, editing the blog files is ok 👍

**Comment by detj** [comment]
@m-allanson Okay. Sure, I'll update my local fork's master and send another PR.

The PR template says

```
  * `v1` branch for updates to the `www` and `docs` directories
```

Should I send the PR to the `v1` branch or the `master` branch ?

**Comment by KyleAMathews** [comment]
Let's just do this to the master branch since we're not going to merge changes like this from v1 anymore.

**Comment by detj** [comment]
Done.

https://github.com/gatsbyjs/gatsby/pull/6115

**Pull request closed without merging**
