### PR TITLE
updated contributor-swag.md

### PR DESCRIPTION
**Pull request by parikshitgupta1**
let it be bold in place of the title.

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@parikshitgupta1 i believe that's intended. You're changing the frontmatter from the page that is required by alot of parts in gatsby site to make it bold? If you look at [here](https://www.gatsbyjs.org/contributing/contributor-swag/) it will be shown as bold.

**Comment by LekoArts** [comment]
Hey! Thanks so much for opening a pull request!

The change you’ve proposed is not going to be accepted because this change doesn't meaningfully improve docs, fix a bug, or otherwise improve functionality.

We absolutely want to have you as a contributor, so please take a look at [our open issues][open-issues] for ideas, and please reach out to us on Twitter at `@gatsbyjs` with questions.

We offer pair programming sessions if you’d like to work with one of our maintainers to make your first contribution.

Thanks again, and we look forward to seeing more PRs from you in the future! :muscle::purple_heart:

[open-issues]: https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by parikshitgupta1** [comment]
Hey, @LekoArts @jonniebigodes  thanks how I can be added in the organization?

**Comment by parikshitgupta1** [comment]
> @parikshitgupta1 i believe that's intended. You're changing the frontmatter from the page that is required by alot of parts in gatsby site to make it bold? If you look at [here](https://www.gatsbyjs.org/contributing/contributor-swag/) it will be shown as bold.

Thankyou

**Pull request closed without merging**
