### PR TITLE
Adds Material Blog starter to the list of starters.

### PR DESCRIPTION
**Pull request by Vagr9K**
This PR adds my new Gatsby starter to the list in the README.
Master currently points to v0 version of it, but I have already begun working on migrating it to Gatsby v1.
I hope I can gather some more feedback about the visual design decisions I have made to make the v1 release as full as possible.

PS. v1 featurelist is really impressive. Kudos for your work!

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 7c7b5464ba0b23e18379a681b0f41f25ba23e958

https://app.netlify.com/sites/gatsbyjs/deploys/5959541f424ef27e0fd38b60

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 7c7b5464ba0b23e18379a681b0f41f25ba23e958

https://app.netlify.com/sites/using-postcss-sass/deploys/59595420424ef27e0fd38b6c

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 7c7b5464ba0b23e18379a681b0f41f25ba23e958

https://app.netlify.com/sites/using-contentful/deploys/59595421424ef27e0fd38b7b

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 7c7b5464ba0b23e18379a681b0f41f25ba23e958

https://app.netlify.com/sites/using-glamor/deploys/59595420424ef27e0fd38b75

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 7c7b5464ba0b23e18379a681b0f41f25ba23e958

https://app.netlify.com/sites/gatsbygram/deploys/5959541f424ef27e0fd38b63

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 7c7b5464ba0b23e18379a681b0f41f25ba23e958

https://app.netlify.com/sites/using-styled-components/deploys/59595420424ef27e0fd38b78

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 7c7b5464ba0b23e18379a681b0f41f25ba23e958

https://app.netlify.com/sites/image-processing/deploys/59595420424ef27e0fd38b72

**Comment by KyleAMathews** [comment]
This is really cool! Thanks for sharing :-)

**Comment by jlengstorf** [comment]
Hiya @Vagr9K! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by jlengstorf** [comment]
Hiya @Vagr9K! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
