### PR TITLE
fix(docs): dictionary.txt -> KintoBlock-kintoblock

### PR DESCRIPTION
**Pull request by kadhirash**
## Description
Changed all the instances of "kintoblock" to the proper "KintoBlock" in  [deploying to kintohub](https://www.gatsbyjs.com/docs/deploying-to-kintohub/) by appending an asterik in dictionary.txt. 

## Related Issues

Addresses [#25290](https://github.com/gatsbyjs/gatsby/issues/25290) enhancement (docs): Improvements to retext-spell.
More specifically, 4. Standardize names of libraries and brands

### CODE REVIEW

**Comment by kadhirash** [comment]
@gatsby/learning

**Comment by kadhirash** [comment]
Hello @LekoArts, I noticed you have been reviewing documentation PR's recently so tagging you. If you aren't the right person please let me know who to tag for review. It is unclear to me who is on the @gatsby/documentation team.

**Comment by ascorbic** [comment]
@kadhirash You don't need to tag anyone. We review all PRs and assign them to the appropriate people.

**Comment by kadhirash** [comment]
@ascorbic I see, sounds good!

**Review by LekoArts — APPROVED** [review]

**Pull request merged**
