### PR TITLE
Add a test case for #259

### PR DESCRIPTION
**Pull request by benstepp**
This currently fails. The change in #259 will make it pass. Currently
the image comes out at the wrong path (/hello-worldimage.jpg)

ava doesnt have test.failing() yet, and our eslint config prevents the
usage of test.todo() so this will most defininitely blow up travis.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Nice! Rerunning tests to ensure they pass.

**Comment by KyleAMathews** [comment]
Lint failed

**Comment by benstepp** [comment]
Rebased over master and force pushed for a new build on travis

I guess I last minute fixuped too hard last night trying to remove noise from test fixtures. It would be nice if gatsby included a default _template, a default config, and a default html file if one isn't found.

**Comment by KyleAMathews** [comment]
Agree re: defaults. I already did that with `gatsby-browser.js` in `/lib/isomorphic`. Perhaps add the bare minimum for the others as well there? 

That *should* work given https://github.com/gatsbyjs/gatsby/blob/master/lib/utils/webpack.config.js#L127

**Comment by KyleAMathews** [comment]
Tests passed except for Node 6 + Mac OSX as currently node-sass won't install there. I'll merge then remove Node 6 from tests for now.

**Pull request merged**
