### PR TITLE
Docs/contributing index to mdx

### PR DESCRIPTION
**Pull request by sever1an**
## Description
This converts `pages/contributing/index.js` to mdx in `docs/contributing/index.md`. The markdown version will appear in place of the js one.

Some changes were introduced by the mdx template.
* Breadcrumbs are added at the top.
* An edit on github link is added at the bottom.

### Screenshots of mdx version in testing
image

image

## Related Issues
Fixes https://github.com/gatsbyjs/gatsby/issues/19034

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
@sever1an Can we use the `mdx` extension for MDX files?

**Comment by sever1an** [comment]
Based in gatsby-config it seems that mdx should work, but I kept getting 404 with it and emulated the referenced pr with the MD extension. 

I will do some debugging today.

**Comment by sidharthachatterjee** [comment]
@sever1an Sure, perhaps restart gatsby develop after changing the extension? As far as I know, `.mdx` should work just fine

**Comment by sever1an** [comment]
It seems that a `gatsby clean && gatsby develop` solved the problem.

**Pull request merged**
