### PR TITLE
example-using-remark reject Promise on error

### PR DESCRIPTION
**Pull request by benjaminabel**

### CODE REVIEW

**Comment by DSchau** [comment]
@benjaminabel can you explain why this change is needed? To me, it looks like the promise will reject now, and it won't be clear _why_ something is failing?

I agree it should probably reject, though.

**Comment by benjaminabel** [comment]
@DSchau I thought that including the `result.errors` in the rejection message, would work. However if you think it should reject and log errors separately it could be done like this.
```js
console.error(result.errors)
reject()
```
But i think it is redundant.

**Comment by DSchau** [comment]
@benadam11 [here's an example](https://runkit.com/dschau/5bdb5f86be2d95001241ac4a)

Also if anything, we should log and then `return reject` in order to stop the control flow. You can see in the example above that the console.log is still triggered.

**Comment by benjaminabel** [comment]
You're right, should return reject, I found this in [gatsby-node](https://github.com/gatsbyjs/gatsby/blob/master/www/gatsby-node.js#L239) of offical site www. I edit the PR.

**Pull request merged**
