### PR TITLE
Decrease images sizes and compress (lossless)

### PR DESCRIPTION
**Pull request by roachnt**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Does anyone know if git keeps downloading older versions of the same file when you do a git clone? If so, this PR wouldn't help decrease the size of our git repo... @jlengstorf Some quick googling couldn't figure it out.

**Comment by roachnt** [comment]
@jlengstorf absolutely!

**Comment by m-allanson** [comment]
It's probably worth keeping the SVG optimisations too.

**Comment by roachnt** [comment]
#6574 this is just image resizes. For some reason some checks didn't pass on image optimizations in the last PR.

**Comment by roachnt** [comment]
Both this PR and #6574 should be closed since the image sizes should be larger than what we originally thought.

**Comment by jlengstorf** [comment]
Thanks again for your help with this, @roachnt! Closing this in favor of a new PR with larger images.

**Pull request closed without merging**
