### PR TITLE
Add live examples to the GraphQL reference page

### PR DESCRIPTION
**Pull request by m-allanson**
This updates the GraphQL reference page with a series of live examples. 

Some of my terminology is probably wrong, and I'm sure there's more sections that can be added.

Refs #3893

### CODE REVIEW

**Comment by KyleAMathews** [comment]
nice! Super excited to see this out there soon!

Netlify is failing on the preview build — it said `lodash.isString` can't be found which is weird. Lemme try restarting the build.

**Comment by KyleAMathews** [comment]
🎉

screen shot 2018-02-20 at 1 40 42 pm

https://deploy-preview-4143--gatsbyjs.netlify.com/docs/graphql-reference/

**Comment by m-allanson** [comment]
Ah some of the queries near the end are truncated. I thought I'd fixed that - it's to do with some values in the url not being url encoded.

I haven't had time to look into https://github.com/gatsbyjs/gatsby/issues/4093 yet, so editing this page is a bit troublesome.

**Comment by m-allanson** [comment]
I'd also like to investigate allowing the iframes to 'break out' to be wider than the rest of the content, but.. one thing at a time :)

**Comment by ajayns** [comment]
This looks great! Would really help in being more indepth and interactive from the tutorial docs itself! @m-allanson  @KyleAMathews

**Comment by m-allanson** [comment]
@ajayns I'd love to have an easy way to put interactive GraphQL queries all over the docs! So far it's been pretty fiddly to get this set up just for gatsbyjs.org. We'd need to find a way to streamline the process so it's easy to do for any Gatsby site.

@KyleAMathews This is ready for a review, although the Netlify preview hasn't updated. I've fixed up the broken links, added a little section at the end and the build issues / flakiness should be fixed by #4291 and #4315.

**Comment by m-allanson** [comment]
The Netlify preview has updated: https://deploy-preview-4143--gatsbyjs.netlify.com/docs/graphql-reference/

**Comment by jlengstorf** [comment]
This is so cool! Great work, @m-allanson!

**Comment by KyleAMathews** [comment]
This is super exciting! Looks awesome! Let's get it out there 🚀

**Comment by KyleAMathews** [comment]
Oh random follow-on improvement I thought of is that the iframes could have a "pop-out" icon or button or whatever so people could play with the query in a full-sized window. We could also make the iframes stretch wider than the text column.

**Comment by KyleAMathews** [comment]
screen shot 2018-03-01 at 3 13 18 pm

**Comment by m-allanson** [comment]
@KyleAMathews I definitely agree on giving the iframes more space, see https://github.com/gatsbyjs/gatsby/pull/4143#issuecomment-367134209 :)

I'll open a new issue for improvements to this page.

**Pull request merged**
