### PR TITLE
chore: update sharp to `^0.21.0`

### PR DESCRIPTION
**Pull request by WaylonWalker**
This will help folks having installation issues on windows resolve without opening an issue. This issue has been seen in Issue https://github.com/lovell/sharp/issues/1382, https://github.com/lovell/sharp/issues/1387,  and in #8325.

### CODE REVIEW

**Comment by lovell** [comment]
Bumping sharp from `^0.20.2` to `^0.21.0` should deal with the underlying cause.

**Comment by KyleAMathews** [comment]
Thanks @lovell! Is there any breaking changes we should worry about?

**Comment by lovell** [comment]
Based on a quick scan of the `gatsby-plugin-sharp` source there is one deprecation that will affect you. The following change would be required to avoid warnings:

```diff
-    .resize(options.width, options.height)
-    .crop(options.cropFocus)
+    .resize(options.width, options.height, {
+      position: options.cropFocus
+    })
```

Full changelog at http://sharp.pixelplumbing.com/en/stable/changelog/#v0210-4th-october-2018

**Comment by pieh** [comment]
@WaylonWalker would you be up for bumping `sharp` version and adjusting `gatsby-plugin-sharp` code?

**Comment by WaylonWalker** [comment]
@pieh I attempted, but am getting confused with some of the errors.  I worked through the ones that seemed obvious to me.  Some things seem unrelated, some seem related to node versions (testing setup??).  Probably doesn't help that I am on a 40 kbps network at the moment, and working from the github ui only..

**Comment by pieh** [comment]
> @pieh I attempted, but am getting confused with some of the errors. I worked through the ones that seemed obvious to me. Some things seem unrelated, some seem related to node versions (testing setup??). Probably doesn't help that I am on a 40 kbps network at the moment, and working from the github ui only..

Dependency changes are hard to test currently, I will get on it - thanks for doing what You already did!

**Comment by WaylonWalker** [comment]
Thanks @pieh, it looks very tricky.  Especially not being too familiar with the codebase. Let me know if there is anything else I can do.

**Comment by DSchau** [comment]
@WaylonWalker looks like the commit histories are a little screwy. Trying to iron it out, and then I'll test this locally. Thanks for your patience!

**Comment by DSchau** [comment]
Well this was fun! 😅 I somehow managed to wipe the history, but I should have all the commits (and a successful merge) in WaylonWalker/gatsby#1, so once we merge that we can re-open this!

**Pull request closed without merging**
