### PR TITLE
fix(gatsby-plugin-netlify): upgrade webpack-assets-manifest for compatibility with webpack@5

### LINKED ISSUE #29974: [gatsby-plugin-netlify] depracated webpack-assets-manifest causing errors during build
## Description

I am upgrading to gatsby v3 and I am using `gatsby-plugin-netlify`, during build time I get the following errors:

> ERROR
>
> (node:17164) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.> getCompilationHooks(compilation).loader
> (Use `node --trace-deprecation ...` to show where the warning was created)
>
> ERROR
>
> (node:17164) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
> BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
> Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
> Make sure to select an appropriate stage from Compilation.PROCESS*ASSETS_STAGE*\*.

I have drilled down a bit and found that cause of the problem was [a deprecated `webpack-assets-manifest` dependency](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify/package.json#L20).

`webpack-assets-manifest` is compatible with webpack v5 as described [here](https://github.com/webdeveric/webpack-assets-manifest#new-in-version-5)

### Steps to reproduce

- Create a project with gatsby v3
- Add `gatsby-plugin-netlify`
- run `npm run build`

### Environment
<details>

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.81)
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1 
    gatsby-plugin-google-analytics: ^3.0.0 => 3.0.0 
    gatsby-plugin-image: ^1.0.0 => 1.0.0 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-mdx: ^2.0.0 => 2.0.0 
    gatsby-plugin-netlify: ^3.0.0 => 3.0.0 
    gatsby-plugin-offline: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5 
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0 
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0 
    gatsby-plugin-styled-components: ^4.0.0 => 4.0.0 
    gatsby-remark-autolink-headers: ^3.0.0 => 3.0.0 
    gatsby-remark-copy-linked-files: ^3.0.0 => 3.0.0 
    gatsby-remark-embedder: ^4.1.0 => 4.1.0 
    gatsby-remark-images: ^4.0.0 => 4.0.0 
    gatsby-remark-prismjs: ^4.0.0 => 4.0.0 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0 
</details>

I would be happy to submit a PR if needed 🚀

### PR DESCRIPTION
**Pull request by pedrolamas**
## Description

Some deprecation errors are showing from `gatsby build` when `gatsby-plugin-netlify` is in use, this fixes the problem by upgrading the `webpack-assets-manifest` version to the same used in the rest of gatsby codebase.

## Related Issues

Fixes #29974

### CODE REVIEW

**Comment by kimbaudi** [comment]
@pedrolamas - did you run `yarn jest gatsby-plugin-netlify` afterwards? If so, you should have gotten an error (at least, it happened to me).

**Comment by pedrolamas** [comment]
@kimbaudi I did indeed, it passed perfectly on my end (tested under Windows 10)!

image

**Comment by kimbaudi** [comment]
@pedrolamas - I just tested after upgrading to `"webpack-assets-manifest": "^5.0.1"` and one of the tests are failing. I'm on Windows 10 also.

not-working

**Comment by pedrolamas** [comment]
@kimbaudi Can I ask you to checkout my branch, run `git clean -x -d -f` to remove all other files (please be aware this is like a new checkout of the repo, so **all non-commited files will be removed!**), and then run `yarn bootstrap` before running the tests again?

**Comment by kimbaudi** [comment]
@pedrolamas - ok I'll check out your branch and give it a shot. btw, you can shorten the command to `git clean -xfd` (i do this often :smile:)

**Comment by pedrolamas** [comment]
Sorry, I'm not a big git cli user, so I'm just copying the commands from Git Extensions! 😁

**Comment by kimbaudi** [comment]
@pedrolamas - I tested on your branch (and on my fork as well) and it works. I guess 

works

**Comment by pedrolamas** [comment]
For the record, I've tested this change locally with [yalc](https://github.com/wclr/yalc) and it worked fine for me (error messages are gone).

image

**Review by sidharthachatterjee — APPROVED** [review]
Thanks!

**Comment by jonathanphz** [comment]
> @pedrolamas - did you run `yarn jest gatsby-plugin-netlify` afterwards? If so, you should have gotten an error (at least, it happened to me):
> 
> > `TypeError: Cannot read property 'RawSource' of undefined
> 
> I guess what I'm trying to say is, you can't just upgrade `webpack-assets-manifest` from current version 3 to the latest version 5.

I just upgraded Gatsby to `v3.9.1` and `gatsby-plugin-netlify v3.9.0` and getting this same error.

**Comment by jonathanphz** [comment]
Never mind - fixed by running ` npm cache clean --force` as a last resort.

**Pull request merged**
