### PR TITLE
fix(recipes): create src/images folder when baking mdx-images (#23820)

### LINKED ISSUE #23820: MDX images recipe throws error if image folder doesn't exist - check if image folder exists and if not, create it
## Problem

The MDX image recipe has `gatsby-source-filesystem` pointing towards a folder that the user may or may not have. 

## Solution
Is it possible to check if the user has the folder, and if not, create it for them?

### PR DESCRIPTION
**Pull request by shrthnd**
## Problem
The MDX image recipe has gatsby-source-filesystem pointing towards a folder that the user may or may not have.

## Solution
Is it possible to check if the user has the folder, and if not, create it for them?

## Notes

I don't think it's possible to check if a folder exists (yet) but we can create one using the `<File />` component.

## Related Issues

Potentially resolves #23820

### CODE REVIEW

**Comment by KyleAMathews** [comment]
This _works_ but I think a better solution would be we add a `<Directory>` component so the recipe could write `<Directory path="src/images" />`

Would you like to work on adding that?

**Comment by shrthnd** [comment]
Thank you for the feedback, @KyleAMathews! I will pursue the `<Directory />` component in another branch.

**Comment by KyleAMathews** [comment]
Great! It'd be in this directory and shouldn't be much code as it just has to ensure the directory exists

https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-recipes/src/providers/fs

Lemme know if you have any questions!

I'll close this PR as well.

**Comment by shrthnd** [comment]
This... is what I was thinking. I appreciate the direction/confirmation, @KyleAMathews. 

Digging into the task last night I realized I was publishing to the gatsby project repository instead of my own fork. Thank you for your patience here. Sorry if I peed in the pool (y'all are good people.)

I've since adjusted my `origin` and added the gatsby project `upstream`, as documented [here](https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/), but am having some trouble with my `yarn workspace`. 

Is this a me thing? 

Screen Shot 2020-05-10 at 9 28 09 AM

Screen Shot 2020-05-10 at 9 17 20 AM

There's a couple errors thrown when running `yarn test` in the gatsby workspace:

Screen Shot 2020-05-10 at 9 39 01 AM

Screen Shot 2020-05-10 at 9 39 41 AM

Otherwise, it is both `the weekend` and `mother's day` so I'm not planning to revisit this until tomorrow. Thanks again for the opportunity to apply myself here but, don't let me hold up this feature or pull you away from other things to solve my workflow issues.

**Comment by KyleAMathews** [comment]
eh I dunno — @pieh has been doing some more work on gatsby-dev-cli recently so probably worth updating to the latest version of that to see if helps. Also yarn locks get weird — worth deleting it and reinstalling.

**Comment by pieh** [comment]
Ugh ... the `JSON.parse` error is a bug (?) in `yarn@1.22` - when you run `yarn workspaces info --json` you will get malformatted json that looks like this:

```
yarn workspaces v1.22.4
{
  "blah": {
    "location": "blah",
    "workspaceDependencies": [],
    "mismatchedWorkspaceDependencies": []
  }
}
✨  Done in 0.04s.
```

notice `yarn workspaces v1.22.4` and `✨  Done in 0.04s.` around actual json output.

Downgrading to `yarn@1.21` fixes that, but I'll add some handling/filtering to our parsing in `gatsby-dev-cli` to workaround that

**Comment by shrthnd** [comment]
Appreciate the insight, @pieh! Downgrading to `yarn@1.21` unblocked me. 

Tomorrow's a new day. My work day is over at 2pm EST so I'll be sure to revisit this when I'm otherwise uncommitted. Thanks again.

**Comment by shrthnd** [comment]
How important is order of operations when starting up `yarn run watch` in the gatsby core project? 

After running `yarn install` in my test site, I run `gatsby-dev --set-path-to-repo /Users/shrthnd/Projects/GatsbyWorkspace/gatsby/` followed by `gatsby-dev` -- which copies over the relevant packages, which has a slightly different behavior than what's being shown in the [demo](https://www.youtube.com/watch?v=D0SwX1MSuas).

I start the main project with (found here `~/Projects/GatsbyWorkspace/gatsby/`) by running `yarn watch bs` and start the example site with `yarn workspace gatsby-starter-hello-world develop`. 

When I edit the files in the `~/Projects/GatsbyWorkspace/gatsby-starter-hello-world` I see the build process is triggered, but only in the local test site. The core project output remains stuck at `gatsby: Successfully compiled 178 files with Babel.`

This was working for me at some point last night (running `../node_modules/.bin/gatsby recipes` from the test site) right up until I branched off master:

Screen Shot 2020-05-10 at 10 54 27 PM

Since then, I've run through this process from slightly different angles (removing node_modules, yarn.lock files, etc.) so I'm not sure what I'm missing.  Based on this output from the gatsby core console, I sort of expect this should be working: 

```
gatsby-recipes: > gatsby-recipes@0.1.14 build /Users/shrthnd/Projects/GatsbyWorkspace/gatsby/packages/gatsby-recipes
gatsby-recipes: > babel src --out-dir dist --ignore "**/__tests__"  --extensions ".ts,.js,.tsx" "--watch"
```

I'm keep at this but feelin' kinda lame since I'm stuck at the starting gate. Step-wise, I'm going to trash this workspace and rebuild momentarily.

**Comment by shrthnd** [comment]
Welp, I'm [unblocked](https://github.com/gatsbyjs/gatsby/compare/master...shrthnd:recipes-directory) (again) thanks to a friendly reminder to `npm i -g gatsby-cli@latest`. 

Of course, revisiting this tonight I realized I was modifying the `gatsby-recipes` directory (in my test site) and not gatsby core. This is really obvious--but I had added the folder into my vscode workspace and failed to revisit (or notice when sharing my notes earlier.)

So, `gatsby-dev` now persists--and editing files in core gatsby-recipes directory works just fine... will revisit tomorrow. If I can't code a solution at least I should be able to write up an awesome explanation of the "getting started" process. 🤦

**Comment by shrthnd** [comment]
Tiny steps forward... I decided to sleep last night instead of code. Quick changes this morning allow a local recipe to create an empty text file at the `<Directory src="src/images" />`.

**Comment by shrthnd** [comment]
I won't tell you my ratio of _mise-en-place_ to actual development effort here... 

@KyleAMathews could you take look a look at [these changes](https://github.com/gatsbyjs/gatsby/compare/master...shrthnd:recipes-directory) when you have a moment and let me know what needs improvement?

Thank you for letting me work on this (test-driven development is fun!)

**Comment by KyleAMathews** [comment]
Looking great!

Some quick notes:

- the e2e test needs an update (just change the directory name) which would then need to move the directory.
- `content` isn't a prop we want — perhaps that's leftover from the file resource?
- why are you exporting the `exists` function?

**Comment by shrthnd** [comment]
> the e2e test needs an update (just change the directory name) which would then need to move the directory.

The test has been updated and seems to pass. This is heretofore out of my wheelhouse but I think it makes sense...

> content isn't a prop we want — perhaps that's leftover from the file resource?

Indeed it is. This has been removed.

> why are you exporting the exists function?

Also a leftover bit. Removing it doesn't break anything but it's not obvious to me where this is being used... (maybe as part of the planning step of the recipe-machine? 

Ensuring a directory exists, and creating it if not, won't overwrite peoples stuff--so I don't think this is critical. Also, the `configResource` object defined in `./src/resources` seems to be the model for these exports so... 🤷 

Let me know if any of this needs to be revisited. Good feedback--thanks again!

**Comment by KyleAMathews** [comment]
Awesome! Is the PR up? Can start reviewing again there.
--
Kyle Mathews

Blog: *http://bricolage.io <http://bricolage.io>*
Twitter: http://twitter.com/kylemathews

**Comment by shrthnd** [comment]
🥳 PR is open now, @KyleAMathews!

**Comment by KyleAMathews** [comment]
Where is it? Don't see it in the list.

**Comment by shrthnd** [comment]
I have some _very real_ change blindness when it comes to working on Github? This is ready for review when you have a moment: #24077

**Pull request closed without merging**
