### PR TITLE
Adjust image sizes

### PR DESCRIPTION
**Pull request by roachnt**
Resized all images > 1240px (that were also > 1 MB) to 1240px.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 2d9d6ce490b25852d18a8afd2f2f45c2d2154a48

https://app.netlify.com/sites/using-postcss-sass/deploys/5b50e2c9e39e7c1217426127

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbygram* failed.

Built with commit 2d9d6ce490b25852d18a8afd2f2f45c2d2154a48

https://app.netlify.com/sites/gatsbygram/deploys/5b50e2c8e39e7c1217426121

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit 2d9d6ce490b25852d18a8afd2f2f45c2d2154a48

https://app.netlify.com/sites/image-processing/deploys/5b50e2c9e39e7c121742612b

**Comment by KyleAMathews** [comment]
Hey, thanks for jumping on this. We do actually create higher resolution thumbnails, up to 2130px. So perhaps just resize down images to e.g. 2400px wide?

cursor_and_community_roundup__1___gatsbyjs

**Comment by jlengstorf** [comment]
Closing this one as well in favor of larger images. Thanks again, @roachnt!

**Comment by jlengstorf** [comment]
@roachnt No problem at all! Thanks so much!

**Pull request closed without merging**
