### PR TITLE
I forgot a few categories :)

### PR DESCRIPTION
**Pull request by ksigler7**

### CODE REVIEW

**Comment by giraffesyo** [comment]
I don't think we should have API and APIs as a category.

**Comment by amandeepmittal** [comment]
@giraffesyo My bad for approving it. I thought they were already existing categories.

**Comment by pieh** [comment]
Let's remove `APIs` and leave just `API` and get this merged in

**Comment by ksigler7** [comment]
@pieh - fair enough

**Comment by ksigler7** [comment]
I removed APIs and changed it to API where that wasn't a category

**Pull request merged**
