### PR TITLE
chore(starters): Add gatsby-github-personal-website

### PR DESCRIPTION
**Pull request by thakkaryash94**
This repo contains a GitHub personal website for JS developers as the original website is written ruby.

### CODE REVIEW

**Comment by thakkaryash94** [comment]
`js-yaml` is old, the npm audit is throwing an error with `moderate severity vulnerability` message. report saying issue patched in v 3.13.0.

**Comment by muescha** [comment]
You have to wait until the svgo package is fixed ...

**Comment by muescha** [comment]
BTW: I also was thinking about do the same in gatsbyjs. You could write GitHub maybe they include it on https://github.dev

**Comment by thakkaryash94** [comment]
no problem, till then I will fix README.md and other issues from my side as well.

**Pull request merged**
