### PR TITLE
fix(gatsby): fix issue with decoding URl

### LINKED ISSUE #34797: % in url params causes website loading to fail.
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Basically title, % in url params causes a gatsby site to fail to load properly.
Culprit 
```
const trimPathname = rawPathname => {
  const pathname = decodeURIComponent(rawPathname)
  // Remove the pathPrefix from the pathname.
  const trimmedPathname = stripPrefix(
    pathname,
    decodeURIComponent(__BASE_PATH__)
  )
    // Remove any hashfragment
    .split(`#`)[0]

  return trimmedPathname
}
```

Error in console.
```
find-path.js:10 Uncaught (in promise) URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at c (find-path.js:10:20)
    at g (find-path.js:141:27)
    at f (find-path.js:57:27)
    at e (find-path.js:122:19)
    at t.loadPage (loader.js:226:22)
    at Object.loadPage (loader.js:638:33)
    at production-app.js:174:3
 ```

### Reproduction Link

https://www.gatsbyjs.com/?ref=%25
 Our website: https://even.in/?param=%25, fails to load with the above error thrown.

### Steps to Reproduce

Open gatsby website with the above URL.

### Expected Result

It should load fine.

### Actual Result

It throws console errors. The page is non responsive with none of the JS bundles loading.

### Environment

```shell
Any env.
```

### Config Flags

_No response_

### LINKED ISSUE #34998: gatsby navigate() function can not navigate url which include "%"
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

gatsby navigate() function can not navigate url which include "%"

import { navigate } from 'gatsby-link';

navigate("/demo/will have 2%")
navigate("/demo/will have 2%25")
this two will through decode error

framework-bde73dc2d2b00752c7c6.js:2 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
and I do some debug,found navigate decodeURIComponent twice

### Reproduction Link

private url can not give you guys,but this is an normal error

### Steps to Reproduce

1.import { navigate } from 'gatsby-link';

2.use navigate("/demo/will have 2%")

3.use navigate("/demo/will have 2%25")
 wil through Uncaught URIError: URI malformed 

### Expected Result

can redirect to "/demo/will have 2%" page

### Actual Result

through error and block navigate

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.1.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.109
    Firefox: 97.0.1
    Safari: 15.3
  npmGlobalPackages:
    gatsby-cli: 2.12.117
```

### Config Flags

_No response_

### PR DESCRIPTION
**Pull request by marvinjude**
## Description

Using a percent encoded character like `%25` in URL breaks due to multiple `decodeURIComponent` calls. This PR address this issue by making sure the query string part of the URL is always encoded.

## Related Issues

 Fixes #34797
 Fixes #34998

### CODE REVIEW

**Comment by Abhirup-99** [comment]
Any updates on this. @marvinjude.

**Comment by wardpeet** [comment]
To make sure do we have tests around query-strings without escaping and paths without escaping. Just making sure that we didn't miss any use case

**Comment by pieh** [comment]
> To make sure do we have tests around query-strings without escaping and paths without escaping. Just making sure that we didn't miss any use case

@wardpeet We have quite a bit of e2e tests using regular query params. Some of them added for trailing slashes like https://github.com/gatsbyjs/gatsby/blob/1d3c331b995b30637c15fa43deb2a3377a4131c4/e2e-tests/production-runtime/cypress/integration/1-production.js#L211-L222

So we should be set for baseline testing and would need just add cases for specifically encoded ones which for now was added for e2e/dev-runtime (we should add same ones to e2e/prod-runtime as well to be sure)

**Comment by marvinjude** [comment]
We also have some here https://github.com/gatsbyjs/gatsby/blob/1d3c331b995b30637c15fa43deb2a3377a4131c4/e2e-tests/development-runtime/cypress/integration/navigation/redirect.js#L47-L66

**Review by pieh — APPROVED** [review]

**Comment by Abhirup-99** [comment]
Thanks for the PR and the approval. Do push a release with the changes as we are eagerly waiting for this.

**Pull request merged**
