### PR TITLE
docs(css-modules): replace postcss-scss

### PR DESCRIPTION
**Pull request by hellobrian**
Hello! 👋  

Just started a fresh gatsby project and was trying to use css-modules using `.scss` files. 

Unfortunately, I wasn't able to get this working with the `postcss-scss` as originally suggested in the docs. I found a solution on a [blog](https://medium.com/@PostgradExpat/using-gatsby-with-css-modules-and-scss-7e75a05533a4) that suggested using `gatsby-plugin-sass` and this worked for me right away. Using css-modules and scss plugins together allowed me to get what I wanted without any obstacles.

When trying to use `postcss-scss` with the filename as `filename.module.scss` or `filename.scss`, I get the following compile error in my terminal: 

```bash
 ERROR  Failed to compile with 1 errors                               22:00:20

 error  in ./src/components/HomePage/index.module.scss

Module parse failed: /Users/brianhan/dev/brianhan.co/src/components/HomePage/index.module.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/brianhan/dev/brianhan.co/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/brianhan/dev/brianhan.co/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/Users/brianhan/dev/brianhan.co/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/Users/brianhan/dev/brianhan.co/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)

 @ ./src/components/HomePage/index.jsx 10:19-49 17:2-19:4 18:4-34
```

Maybe I'm missing a step with using `postcss-scss` but just thought it might be helpful to switch the docs over to suggesting `gatsby-plugin-sass` since this worked for me right out of the box.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 6075a7a0cea665603e7c7ccb43e23517aea66bfe

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5bddaab13fb10758f6cd97

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 6075a7a0cea665603e7c7ccb43e23517aea66bfe

https://app.netlify.com/sites/using-glamor/deploys/5b5bddabb13fb10758f6cd9d

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 6075a7a0cea665603e7c7ccb43e23517aea66bfe

https://app.netlify.com/sites/gatsbyjs/deploys/5b5bdda9b13fb10758f6cd8f

**Comment by ascorbic** [comment]
I think the issue here is that I'm not sure what `gatsby-plugin-react-css-modules` is even for, as CSS modules should just work out of the box. Is it used for anything?

**Comment by jquense** [comment]
React-css-modules is different from css modules, which is confusing. It's a library for adding some unknown value on top of plain css-modules.

It's name implies it's required for react but it's not, it's just an alternative API.

The postcss-sass plugin was needed for v1 because of the old version of webpack. It's not needed in v2 because you can configure Postcss plugins right in the plain sass-plugin.

Names are hard!

**Comment by ascorbic** [comment]
OK, that's certainly confusing, and the README for the plugin is simply misleading. Apart from anything, this doesn't implement [react-css-modules](https://github.com/gajus/react-css-modules), but rather [babel-plugin-react-css-modules](https://github.com/gajus/babel-plugin-react-css-modules), which is related but different. The readme needs to make clear that it's not required for CSS modules, and that it implements `babel-plugin-react-css-modules`.

**Comment by jquense** [comment]
o wow so it's even more confusing...

@KyleAMathews what do you think about moving this plugin out of the main repo here. I think it's presence is very confusing, and it's for a library that i'm sure is fine but not at all "standard" for folks use css modules, and its position here i think lends to much weight that it is?

**Comment by KyleAMathews** [comment]
@jquense sounds fine to me! I don't really know anything about it. I think it was added back early before or just after the v1 release when we were accepting more plugins here.

**Comment by KyleAMathews** [comment]
Another option is adding a big disclaimer at the top that you normally don't want it.

**Comment by m-allanson** [comment]
> Another option is adding a big disclaimer at the top that you normally don't want it.

This seems like the quickest fix? Otherwise we need to find somewhere to move the plugin to. 

How about adding something like this near the top of the [README for `gatsby-plugin-react-css-modules`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-react-css-modules):

>**NOTE**: You probably don't need this plugin! 
>
>Gatsby works with CSS Modules by default, no need for extra plugins. You should only use this if you already know what `babel-plugin-react-css-modules` is and want to enable it for your project.

**Comment by hellobrian** [comment]
Thanks, @m-allanson and everyone for chiming in on this.
I added the disclaimer up top and removed my initial suggestion for including `gatsby-plugin-sass`. At first, I thought CSS Modules wasn't working by default and needed `gatsby-plugin-sass` but just tested it again and it works fine. I'm sure some other setting I had was messing with it. 

Thanks!

**Pull request merged**
