### PR TITLE
[Tutorial] Add notice regarding 4-part tutorial near the top

### PR DESCRIPTION
**Pull request by ryanditjia**
Refs:
* https://github.com/gatsbyjs/gatsby/issues/5612
* https://github.com/gatsbyjs/gatsby/pull/5658

### CODE REVIEW

**Comment by m-allanson** [comment]
cc @shannonbux 

https://deploy-preview-5673--gatsbyjs.netlify.com/tutorial/part-four/
https://deploy-preview-5673--gatsbyjs.netlify.com/tutorial/part-five/
https://deploy-preview-5673--gatsbyjs.netlify.com/tutorial/part-six/

**Comment by m-allanson** [comment]
Coming back to this - the note feels a bit too prominent to me. 

One idea on condensing it would be:

- Drop the note from part 4
- For the remaining parts include the note with just a link back to part 4

Something like:

_This tutorial is part of a series, make sure you've gone through [part X]() before continuing here._

On parts 6 and 7 this could be extended with _Are you new here? Jump [back to the start]() of this tutorial series._

Thoughts @fk @shannonbux @ryanditjia?

**Comment by ryanditjia** [comment]
I agree with my implementation being too prominent! I will tone it down by shortening to concise sentences that you suggested. And, even better, we can replace blockquote with the Butler component. I’ve suggested implementing Butler + MDX in the issue, let’s wait for the responses!

**Comment by m-allanson** [comment]
@ryanditjia it'd be great to get a first version of this merged, then maybe it can be re-visited once there's a proper Butler callout component. 

If you have time to finish this up then I think the least work to getting it merged would be:

- revert the example code changes, as there are newer updates here that are causing merge conflicts
- update the text of the notices based on [my earlier comment](https://github.com/gatsbyjs/gatsby/pull/5673#issuecomment-395435680)

I think that's it!

**Comment by ryanditjia** [comment]
Apologies for letting this go stale for so long. Seems like it’s easier for me to close this and send another PR, doing that now!

**Pull request closed without merging**
