### PR TITLE
gatsby-starter-default useStaticQuery over StaticQuery

### PR DESCRIPTION
**Pull request by DylanTackoor**
## Description

Updates gatsby-starter-default [layout.js](https://github.com/gatsbyjs/gatsby/blob/master/starters/default/src/components/layout.js) and [seo.js](https://github.com/gatsbyjs/gatsby/blob/master/starters/default/src/components/seo.js) components to use the new `useStaticQuery` hook.

I think it looks cleaner, thoughts? 🤷‍♂️

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
Thank you @DylanTackoor 

You'll need to update `package.json` and `package-lock.json` to have react and react-dom 16.8+ and gatsby 2.1+ since hooks won't work below that

**Comment by sidharthachatterjee** [comment]
@pieh just made a great point about how our starters serve to enable discovery of various features. Going by that, do you think it would make sense to keep one instance of `StaticQuery` and `useStaticQuery` each?

**Comment by sidharthachatterjee** [comment]
@DylanTackoor You can also update gatsby-starter-blog if you like since they're mostly the same files 🙂

**Comment by DylanTackoor** [comment]
@sidharthachatterjee I'll update dependencies, and having one of each type of query is a great idea. I'll revert one and add in links to StaticQuery and useStaticQuery docs an dod the same for the blog starter 😄

**Comment by DylanTackoor** [comment]
@sidharthachatterjee Done!

**Pull request merged**
