### PR TITLE
gatsby-transformer-sharp: Remove `sizes` and `resolutions` node

### PR DESCRIPTION
**Pull request by LekoArts**
## Description

This removes the deprecated `ImageSharpSizes` and `ImageSharpResolutions` fragments (that were replaced by `Fixed` and `Fluid`) from `gatsby-transformer-sharp`

### Documentation

Our docs are already using the latest fragment versions.

## Related Issues

[ch23854]

### CODE REVIEW

**Comment by ascorbic** [comment]
This is technically a breaking change. I think we'll do a major with v3, and remove the resolvers too.

**Comment by LekoArts** [comment]
Yeah, this was meant to be a draft for v3, no idea why it didn't do that.

**Comment by ascorbic** [comment]
It'll be great to clear these out!

**Comment by LekoArts** [comment]
@ascorbic Would be ready for a final review! :)

**Review by ascorbic — APPROVED** [review]
🎉

**Pull request merged**
