### PR TITLE
chore: Move back to upstream relay-compiler

### PR DESCRIPTION
**Pull request by stefanprobst**
Move back to upstream `relay-compiler` -- seems to work fine.

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
So this was attempted previously in https://github.com/gatsbyjs/gatsby/pull/15963 but we closed it because Relay regressed on the fix that @freiksenet made! 

Do you know about this regression (I don't)? How do you feel about adding a test that catches that regression if yes?

**Comment by stefanprobst** [comment]
tbh i don't know the exact reason for the fork. i tested this with .org, and checked the sorting of the blog posts (so the sort enum works), but i might not have the full context here

**Comment by stefanprobst** [comment]
if we are not confident to switch back, we should release a new version of our fork with https://github.com/freiksenet/relay/pull/1

**Comment by sidharthachatterjee** [comment]
https://github.com/freiksenet/relay/pull/1 is now published as `2.0.0-printer-fix.3` and an upgrade to it is in https://github.com/gatsbyjs/gatsby/pull/16986

Closing this

**Comment by stefanprobst** [comment]
Can we keep this open until we figure out why we do/don't need to stay on our fork of `relay-compiler`?

**Comment by sidharthachatterjee** [comment]
@stefanprobst Let's track that in https://github.com/gatsbyjs/gatsby/issues/11536

I think we should add a (failing) test if possible but I'd recommend against keeping this open because it's bound to out of date/stale with time

**Comment by stefanprobst** [comment]
@sidharthachatterjee i just think we should figure this out soon. @freiksenet mentioned in #11536 that last time we tried it broke out builds, but i could not reproduce this with v5 anymore.
if we can't remember the reason for the fork it's maybe best to actually move back and wait for a bug report?

**Comment by freiksenet** [comment]
Have you tried www with latest relay? It was fixed with my patch at 2 then broken again in 3.

**Comment by m-allanson** [comment]
@stefanprobst said this:

>tbh i don't know the exact reason for the fork. i tested this with .org, and checked the sorting of the blog posts (so the sort enum works), but i might not have the full context here

So it seems like it's fine on .org? Is there anything else we should check? I agree we should switch back if there's nothing preventing the change.

**Pull request closed without merging**
