### PR TITLE
Update fetch.js to fix WordPress.com integration

### PR DESCRIPTION
**Pull request by kharrop**
Related to https://github.com/gatsbyjs/gatsby/pull/10624

## Description

When running gatsby develop, the terminal showed that all my fetch requests were pointing to 'https://public-api.wordpress.com' instead of the individual wordpress.com pages. By referencing #10624 and a few minor tweaks, I was able to get this to work correctly.

## Related Issues

#10624
#10427

### CODE REVIEW

**Comment by kharrop** [comment]
When running `gatsby develop`, the terminal showed that all my fetch requests were pointing to 'https://public-api.wordpress.com' instead of the individual wordpress.com pages. By referencing https://github.com/gatsbyjs/gatsby/pull/10624 and a few minor tweaks, I was able to get this to work correctly.

**Comment by pieh** [comment]
I will need to check this with self-hosted version of wordpress. I remember we had similar pull request before, but it was breaking those.

**Comment by pieh** [comment]
This breaks non .com sites:
```
=== [ Fetching wordpress__wp_v2 ] === http://localhost:7000/wp/v2
⡀ source and transform nodes
Path: /wp/v2?per_page=100&page=1
The server response was "404 Not Found"
Fetching the wordpress__wp_v2 took: 83.328ms

=== [ Fetching wordpress__POST ] === http://localhost:7000/wp/v2/posts
⠠ source and transform nodes
Path: /wp/v2/posts?per_page=100&page=1
The server response was "404 Not Found"
Fetching the wordpress__POST took: 89.411ms

=== [ Fetching wordpress__PAGE ] === http://localhost:7000/wp/v2/pages
⠐ source and transform nodes
Path: /wp/v2/pages?per_page=100&page=1
The server response was "404 Not Found"
Fetching the wordpress__PAGE took: 106.595ms
```
For those endpoint should be

```diff
-http://localhost:7000/wp/v2/pages
+http://localhost:7000/wp-json/wp/v2/pages
```

**Comment by kharrop** [comment]
Thanks @pieh - I'll look into that.

**Comment by pieh** [comment]
#10624 was merged, so closing this one

**Pull request closed without merging**
