### PR TITLE
feat(showcase) : add mailjet website

### PR DESCRIPTION
**Pull request by prasadseth**
adding website of mailjet which is built using gatsbyjs

### CODE REVIEW

**Comment by prasadseth** [comment]
why 2 checks are failing ?

**Comment by KyleAMathews** [comment]
Looks like you're missing a colon after `categories`

**Comment by KartSriv** [comment]
@KyleAMathews Fixed it.

**Comment by LekoArts** [comment]
@KartSriv Please don't change PRs (in this case the description) without asking the author -- that's considered rude. If you want to propose a change you can use GitHub's review functionality. You can't be sure if he actually wanted this description.

@prasadseth Sorry for merging prematurely, we overlooked the change to your description! If you like the updated description: cool :) If you actually had another one in mind: Please open a new PR.

Sorry for the inconvenience 💜

**Comment by prasadseth** [comment]
@LekoArts  Thanks. Yes I will open a new PR because there is a spelling mistake in the updated description.

**Pull request merged**
