### PR TITLE
fix(gatsby-source-contentful): validation with environment

### PR DESCRIPTION
**Pull request by wardpeet**
## Description

When using contentful environment, we would fail validation as you can setup api keys to only be available to reach the specific environment. By default it's master.

Moved to https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/content-types/content-type/get-a-single-content-type/console/curl api

image

### CODE REVIEW

**Review by pieh — CHANGES_REQUESTED** [review]
API endpoint seems to be working ok - just one request - if we use `environment` here, can we modify https://github.com/gatsbyjs/gatsby/blob/7c38997090f550d2b2cd902128f87fc5b19a631b/packages/gatsby-source-contentful/src/gatsby-node.js#L41-L47 (error message that is shown if we are not authorized) to mention `environment` as well?

Because this is outside of diff view, can't make inline comment/suggest, but something like (+ formatting :P):

```diff
-`Cannot access Contentful space "${maskText(
+`Cannot access enironment "${pluginOptions.environment}" in Contentful space "${maskText(
            pluginOptions.spaceId
          )}" with access token "${maskText(
            pluginOptions.accessToken
          )}". Make sure to double check them!`
```

**Review by vladar — APPROVED** [review]
Thanks 👍

**Comment by vladar** [comment]
Published in `gatsby-source-contentful@4.5.3`

**Comment by kelseyn12** [comment]
@wardpeet May I ask how this issue was solved with the "cannot access contentful.." ? It all of a sudden started occurring and I can't figure out whats going on!

**Pull request merged**
