### PR TITLE
chore(showcase) Removing CMSbased.net from showcase

### PR DESCRIPTION
**Pull request by lannonbr**
Cmsbased.net and 5thgait.com no longer are Gatsby sites so I am removing them from the showcase.

@jonzfisher and @cmsbased, can you validate this and then we can remove them

Edit: @jonzfisher and I worked and the Gatsby site of 5thgait.com is back online

### CODE REVIEW

**Comment by jonzfisher** [comment]
5thgait.com was just made a Gatsby site in April and remains one 👍

**Comment by lannonbr** [comment]
@jonzfisher At least currently when I load the page this is what I get:

Screen Shot 2019-05-14 at 9 22 27 AM

Is it possible that maybe someone uploaded an older version of the website?

**Comment by jonzfisher** [comment]
Huh, we’re a small company, but this is what’s coming up for most of the
people at our company and the gatsby site thumbnail generated the right
image based off the new content.


The screenshot you’ve sent me is a site from years ago 🤔 can you come back
to me on your next combing over and i’ll try to look into  this?

**Comment by lannonbr** [comment]
@jonzfisher So I checked with @DSchau on this and the old site is appearing for him as well. Maybe the CDN has some cache invalidation issues? Possibly try to reupload the new site if that is possible and then we will keep it in the showcase.

I am unsure why the old site is appearing when you visit the page, but it is using a screenshot of the new site in the showcase.

**Comment by jonzfisher** [comment]
If you’re interested in some history, I think this old site was built in Adobe Muse, that old more approachable Dreamweaver they made a decade ago hah. 

I’ll reply back today when I figure out what’s going on! Thanks for the heads-up; you’re really helping me out by letting me know!

**Comment by jonzfisher** [comment]
Hey,

It’s looking like something interesting happened with Netlify. Let me know if the updated site is working now. If not, I might need to transfer my domain to another service I think. Sorry you’ve had to spend time on this. Thanks again!

—Jon

**Comment by pieh** [comment]
5thgait.com seems to be fixed now (at least for me and validator script - https://circleci.com/gh/pieh/gatsby-site-showcase-validator/818 )

**Comment by lannonbr** [comment]
@jonzfisher yep you are all set. Thanks for the help. your site will be staying in the Showcase

**Pull request merged**
