### PR TITLE
Fix bad character escape sequence in typography.js on Windows

### PR DESCRIPTION
**Pull request by JGameCreation**
Fixes the issue discussed here lately: #1669 
This replace single backslashes on windows with double backslashes. Without this the following error occurs on Windows machines:

> Error: Module parse failed: C:\src\node_modules\gatsby-plugin-typography.cache\typography.js Bad character escape sequence (1:56) You may need an appropriate loader to handle this file type. SyntaxError: Bad character escape sequence (1:56)

### CODE REVIEW

**Comment by JGameCreation** [comment]
Could someone please explain to me why the checks failed? This was my first commit and I have no idea.

**Comment by KyleAMathews** [comment]
@JGameCreation woah nice fix! This looks like what we need to do for #1783 as well! @bskimball 

On failing stuff — you jumped in the Gatsby waters during a bit of unstability. PRs are in progress/done with fixes. I'll finish those and merge them into this PR.

Thanks again!

**Comment by kylegalbraith** [comment]
Wow beat me to it @JGameCreation! A million thank yous.

**Comment by jlengstorf** [comment]
Hiya @JGameCreation! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
