### PR TITLE
docs(sites): Add sherpalo.com to showcase.

### PR DESCRIPTION
**Pull request by laradevitt**
Updated docs/sites.yml to include sherpalo.com in the showcase. Thanks!

### CODE REVIEW

**Comment by laradevitt** [comment]
Hmm. Looks like there is something odd with the DNS (you must be seeing the old site). This wasn't the case a few hours ago. Better put this on hold while I inquire with the provider. Sorry about that!

**Comment by wardpeet** [comment]
just ping us when back available. A good choice it to use something like https://tools.pingdom.com/ to test dns resolutions

**Comment by laradevitt** [comment]
@wardpeet Will do, thanks (we use dig). DNS records were switched over successfully last week but there was a change in providers over the weekend and something happened there. Hopefully will be resolved soon!

**Comment by sidharthachatterjee** [comment]
Seeing the new one now. Looks great! Thank you for adding it, @laradevitt 👍

**Pull request merged**
