### PR TITLE
[WIP] swapped inserted and deleted colors to resolve issue #6311

### PR DESCRIPTION
**Pull request by ThomasAnkcorn**
Resolves issue https://github.com/gatsbyjs/gatsby/issues/6311 by changing inserted color to  `#4084a1` and deleted color to `#b3568b`

### CODE REVIEW

**Comment by pieh** [comment]
This doesn't to actually fix the issue - https://deploy-preview-6373--next-gatsbyjs.netlify.com/docs/migrating-from-v1-to-v2/#4-change-query-to-use-code-classlanguage-textstaticquerycode 

Seems like styles You uncommented and modified are getting overwritten

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 98a0c4279e83417dd32ac7bdfb88a70c8716d3a0

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5cd57eb312743a942b7a8a

**Comment by KyleAMathews** [comment]
Deploy preview for *using-styled-components* failed.

Built with commit 98a0c4279e83417dd32ac7bdfb88a70c8716d3a0

https://app.netlify.com/sites/using-styled-components/deploys/5b5cd57fb312743a942b7a92

**Comment by fk** [comment]
Just took a look at this in the context of #6878, and yes @pieh you're right -- the changes in `www/src/css/prism-coy.css` get overwritten in https://github.com/gatsbyjs/gatsby/blob/b6bdb82555893177a6c85d62b28abe471e484b8d/www/src/utils/typography.js#L274-L299

I will close this PR in favor of #6878 now, not only because it works ;-), but because of its slightly different approach (described by the author in https://github.com/gatsbyjs/gatsby/pull/6878#issuecomment-409186574).

Please stick with us @ThomasAnkcorn, and sorry for letting you wait on this for so long! 🙏 🤗I'm hoping we'll merge your first PR soon!

---

I think this PR highlights that we should revisit the CSS and color definitions around the Prism syntax highlighting styles:

*  implement `www/src/css/prism-coy.css` in a way that allows us to use color variables from `www/src/utils/colors`
* I can see how @ThomasAnkcorn searched the repository for "prism" and ended up chaning stuff in `prism-coy.css` only -- overwriting the values in `typography.js` is confusing -- let's consolidate them
* clean up https://github.com/gatsbyjs/gatsby/blob/fba1b59ae6e29948ff1f96c402979212bf77d92c/www/src/utils/colors.js#L3-L51 -- most of these are not in use anymore

Will open a new issue now!

**Comment by m-allanson** [comment]
Taking this approach was based on bad advice from me in https://github.com/gatsbyjs/gatsby/issues/6311#issuecomment-403408894, sorry about that @ThomasAnkcorn!

**Comment by ThomasAnkcorn** [comment]
Thanks guys, I was having a look for that file but could not find it 👎 

I have not worked with a code base this large before!!!

**Pull request closed without merging**
