### PR TITLE
chore(starters): add bradgarropy/gatsby-starter

### PR DESCRIPTION
**Pull request by bradgarropy**
## Description

Adds [bradgarropy/gatsby-starter](https://github.com/bradgarropy/gatsby-starter) to `docs/starters.yml`.

### Documentation

Update [starters](https://www.gatsbyjs.org/docs/starters) list.

## Related Issues

None.

### CODE REVIEW

**Comment by bradgarropy** [comment]
Fixed the merge conflicts, should be all clear now @LekoArts!

**Comment by muescha** [comment]
the readme of this starter is missing some instructions...

**Comment by bradgarropy** [comment]
Hey @muescha I can add some details to the readme. Anything you're looking for in particular?

**Comment by bradgarropy** [comment]
It's [much better](https://github.com/bradgarropy/gatsby-starter#readme) now!

**Pull request merged**
