### PR TITLE
Added linter/formatter for markdown files; Formatted documentation

### PR DESCRIPTION
**Pull request by alexandrtovmach**
## Short story

This PR contain configured [remark-lint](https://github.com/remarkjs/remark) with [remark-preset-lint-gatsby](https://www.npmjs.com/package/remark-preset-lint-gatsby) and formatted documentation.

## Long story

After [translation process initiated](https://github.com/gatsbyjs/rfcs/pull/42), I [started looking for some linter](https://github.com/gatsbyjs/rfcs/pull/42#issuecomment-536273892) for docs. We already have a `prettier`, so I thought:

> "Let's find linter for linting and use prettier for formatting"

I made a big research, and find few good linters:
- https://github.com/DavidAnson/markdownlint
- https://github.com/textlint/textlint
- https://github.com/remarkjs/remark

Then I started playing with configaration, but faced with blocker just in a few hours. This blocker is "formatting ordered list marker values to one stardard". That's awful, but just a first document in Gatsby tutorial can't be formatted in a good way:
<details>
<summary>Example: docs/tutorial/index.md</summary>

```markdown
## Gatsby fundamentals

0.  [Set up your development environment](/tutorial/part-zero/): We'll introduce you to core technologies that power Gatsby, and guide you through setting up your development environment.
1.  [Get to know Gatsby building blocks](/tutorial/part-one/): Starting new projects, developing, and deploying sites.
1.  [Introduction to using CSS in Gatsby](/tutorial/part-two/): Explore libraries like Typography.js and CSS Modules.
1.  [Building nested layouts in Gatsby](/tutorial/part-three/): Layouts are sections of your site that are reused across multiple pages like headers and footers.

## Intermediate tutorials

In these intermediate tutorials, you'll learn how to pull data from almost anywhere into your Gatsby site with GraphQL.

4.  [Querying for data in a blog](/tutorial/part-four/): Create a blog and use a GraphQL query to pull your site title into the blog header.
5.  [Source plugins and rendering queried data](/tutorial/part-five/): Use a source plugin to pull Markdown blog posts into your site and create an index page with a list of blog posts.
6.  [Transformer plugins](/tutorial/part-six/): Use a transformer plugin to transform your Markdown blog posts into a form the blog can render.
7.  [Programmatically create pages from data](/tutorial/part-seven/): Learn how to programmatically create a set of pages for your blog posts.
8.  [Preparing a site to go live](/tutorial/part-eight/): Learn how to audit your site for performance and best practices for accessibility, SEO, and more.
```

</details>

The problem is first ol(ordered list) starting with `0`, and next values is `1`, but for a second ol start value is `4`. That mess of styles, and by good approach should be standartized to one style...

I asked Google ― "how to configure prettier for ordered list". But no response...

Okay, I cloned [`prettier`](https://github.com/prettier/prettier) reviewed codebase, discovered that it's based on https://github.com/remarkjs/remark, mentioned above, but didn't find solution for my question. Then I spend a bit more time and implemented functionality that I needed, [made PR](https://github.com/prettier/prettier/pull/6625)...

It's rejected by [their philosophy](https://github.com/prettier/prettier/pull/6625#issuecomment-539507928)

## What's next?

After changing my mental model, understanding that's prettier won't help me, and I need to looking for something else, I decided to use `remark`.

<details>
<summary>Why remark?</summary>
Because it can lint, format, has CLI and sponsored by Gatsby
</details>

Firstly I created preset of rules for Gatsby:
https://github.com/alexandrtovmach/remark-preset-lint-gatsby

Then installed and configured remark into https://github.com/gatsbyjs/gatsby project

And fixed all linter warnings (400 files changed)

## For what we need this linter?

standard markdown format in original repo -> autotests for new content -> reducing count of problems with translation merges

## Does it final version?

Of course, it's not!
I just initialized the process and hope to have feedback and help from community to complete this part.

### CODE REVIEW

**Comment by pieh** [comment]
Does `remark` has autofix support? Looking just on package.json changes I saw that you added `lint:docs` script, but no equivalent for formatting scripts.

**Comment by alexandrtovmach** [comment]
@pieh Yes `remark` provide autofix functionality. Added npm-script here https://github.com/gatsbyjs/gatsby/pull/18942/commits/b6a548817aab130af00e78d817eddb7953a5ed12

**Comment by alexandrtovmach** [comment]
@gatsbyjs/gatsby-deploy @gatsbyjs/core friendly ping

**Comment by tesseralis** [comment]
What sort of rules do you want to enforce with Remark that Prettier doesn't already auto-format? I feel like configuring Prettier to work in the translation repos (as done [here](https://github.com/gatsbyjs/gatsby-i18n-source/pull/2)) would be the better option.

**Comment by muescha** [comment]
which setting makes an list from - i know it only with 1 space

```diff

My List:

- - word
-   - word
+ -   word
+     -   word
```

**Comment by alexandrtovmach** [comment]
@tesseralis I explained in a long description one case related to ordered list. Here is a full list that I noted
**prettier can't:**
- force one style for everything in a whole project. Instead of that it's formatting each block separately. As result, we get different styles (for example list markers, order, emphasis/bold symbols) in each file
- test files without formatting, like a linter
- be extended with different rules to strictify docs as we want. Remark can do that, just check the list of rules of [`remark-preset-lint-gatsby`](https://github.com/alexandrtovmach/remark-preset-lint-gatsby#rules).

With prettier we haven't any control and strict rules about how markdown should look

**Comment by MichaelDeBoey** [comment]
Prettier will always format lists, emphasis/bold symbols, ... the same (see [Markdown Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAJOBDAJnATgHSgF4TTDCB9AGQggGsAaCgAkh2YCMAbCMOgZ2YZccZgDMIuALYYY8LMwBUMWgEJF5KAAMdzAFb9CYgK5QwMAJbRmFnLAswAngAoAHgEpmwZiJjHcUMyuzAC+hDpamgAKFjwwAD4Agha4AA6SCagQ-oZQALR58UgFSPElhABSEAAWgQAiEHDxAMoA0gDi8QCMAMw9AByVGFCiAEqN8RUAYq3xPV0ALJp5zCtrqxvrW5ubmgDUzFQW-DCEzAcA7g7VQswA2lwWUHQAuszOAPQqH-wQUnAXap4ODuQgHYYKO7DCAwIG4ZjQOAvTRne7Q2F4BEjF5IZjMapyVJID4fOCuDBSVJcOAAOkgUmYAHIAKLkynU5iWGDUxmaGgiBkWVL8YwMrAQHjw-gOIT-GAMVjQfhwcxwPzw7BC45gJ4Ac2YcEeMBphAAwv4MBwHP5FVBlar1cwZK4LFJjIJcMd3QrlQpna73ZzDVxA5YzLZTDADcaQAwQBBUpYlchQMJcBALlFhAh+MgQBgAG4QWyxkAcXAYPhq5qpSt65AwXDGOBxglSLgAdWqDjg-FrYDgzRzDgsBYcjjzYH4ubjT2VuBgUQrupkyDEGC4yrjBlcACEK1WYM0KXAjiM1xutyAd809dSAIrGGFwC+blsgWu4ed5mS4Ojii4oFLVJPVgDtbFhZB+gABjjECIGVDsK1SPMQN7PACxfOMAEcn3gJcE1zFAMH4PIRjgHAsFLERcJSOAlwwFcMFfK9lSkCwGybd9pSgXUHzwl8kHXN84xgS1wKwSCkAAJlEitYj1U0-lXFAoERUt3TgAAVS0iOE5UQhCIA))

**Comment by muescha** [comment]
I tried the playground and it changes all lists there to a one space list even if there are 3 space lists are in the source


```markdown
+   List 3 spaces

+ List 1 space
+  List 2 spaces
```

Becomes:


```markdown
- List 3 spaces

- List 1 space
- List 2 spaces
```

But most of your diffs are going from one space to 3 spaces - that is the question: why?

**Comment by alexandrtovmach** [comment]
@muescha Sorry for long response. It seems like remark autofix from https://github.com/gatsbyjs/gatsby/pull/18942/commits/b6a548817aab130af00e78d817eddb7953a5ed12 commit. I'll check the remark config

@MichaelDeBoey take a look on [this example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiVACGB3CGCuANhgJZQYQBOAJnJRgGZUC2AhjDGQOYbUkMM6CGAB0oYgLQYAMiQDOoqFNkLJM+YrEAqdaqg6VigxrFj0FYm0oBrOhgBurQvjgYFAT0JxTUdJmje4lAAjAB0uophEWJRhj5+GKxyYD6xJlAATOFxUADM2elm5gBedHgKrJTw1D4ADAV6aXpZ0VAgADQgEAAOnNByyKCVlBDYAAqVCAMorPYQJNQdIABGlKxgtjAAyt3r3MgwlC6dABYwzIQA6ick8HK7YHBbU7ck9rfuyOByA51kcnQYGM1lw2MgGE4AZ0AFZyAAeACE1hs4NtWMw4LIoHBwZC4DD4VtuF4AIr4CDwXGEKEgXaUAGUL5WazUUZtTrdShkGCXBYwE7IAActQ5IwBlzW3S+TmwrHcvxAAEdyfBgT1piAkhJsXBaItOpQ4MqSIbgaxQawqTSAcwSAcjviQHJiXAyRScUgIdTHTBWMtedR+cgMp1DqwSIRuABhCDMMEoKABJb4AEAFT90y9AIAvtmgA)

**Comment by MichaelDeBoey** [comment]
@alexandrtovmach The zero-started one is a bug in Prettier I think

**Comment by alexandrtovmach** [comment]
@MichaelDeBoey prettier based on remark, where this issue is coming from https://github.com/remarkjs/remark-lint/pull/219

but if you check the prettier codebase you can find their custom realization:
https://github.com/prettier/prettier/blob/ce008c9593227f99edc55ee12a1349546e9a2470/src/language-markdown/printer-markdown.js#L271-L296

which are not allowed "zero" start value at all

**Comment by alexandrtovmach** [comment]
@MichaelDeBoey Another thing is forcing one style:
```md
1. list
1. list
1. list
```
or 
```md
1. list
2. list
3.list
```
prettier cannot do that

**Comment by MichaelDeBoey** [comment]
> but if you check the prettier codebase you can find their custom realization

Prettier only has 1 Markdown parser, so if they're using `remark`, they should update. If not they have the same bug.

> Another thing is forcing one style

Maybe this can be added as a feature to prettier? 🤔
CC @vjeux @azz @evilebottnawi

**Comment by evilebottnawi** [comment]
@MichaelDeBoey Can you open issue in prettier?

**Comment by alexandrtovmach** [comment]
@MichaelDeBoey I already did that https://github.com/prettier/prettier/pull/6625 but it's rejected in reasons of their philosophy

**Comment by evilebottnawi** [comment]
Maybe you can use `remark-lint` for these cases

**Comment by MichaelDeBoey** [comment]
We could indeed use `prettier` as the base and use `remark-lint` **_if_** we really want to _always_ have an ascending number.

Issue for broken zero-based links : https://github.com/prettier/prettier/issues/6813
Issue for broken double lists: https://github.com/prettier/prettier/issues/6814

**Comment by muescha** [comment]
it looks like it uses some default 4 spaces tab. But can be adjusted in the plugin options - see readme: https://github.com/remarkjs/remark-lint/blob/master/packages/remark-lint-list-item-indent/readme.md

**Comment by muescha** [comment]
is it possible to add bad words for better language like in #18702

**Comment by alexandrtovmach** [comment]
@muescha Yes it's possible to add this plugin https://github.com/zerok/remark-lint-write-good

**Comment by JounQin** [comment]
You can try [eslint-mdx](https://github.com/rx-ts/eslint-mdx) and [remark-preset-prettier](https://github.com/JounQin/remark-preset-prettier).

**Pull request closed without merging**
