### PR TITLE
Add Starter

### PR DESCRIPTION
**Pull request by ikeryo1182**
## Description

This is standard starter with Typescript , TSLint, Prettier, Lint-Staged(Husky) and Sass

### CODE REVIEW

**Comment by ikeryo1182** [comment]
Hi, It seems the command ( `lint:yaml` ) is false.

**Comment by ikeryo1182** [comment]
If i'm wrong, please tell me why ...

**Comment by DSchau** [comment]
@amberleyromo @ikeryo1182 it looks like you need to merge upstream/master (e.g. gatsbyjs/gatsby) _into_ your fork. I can do that, if you'd like!

**Comment by ikeryo1182** [comment]
@DSchau @amberleyromo very very thanks. It's just as you said !

**Comment by ikeryo1182** [comment]
resolve conflict

**Pull request merged**
