### PR TITLE
Rewrite of gatsby-source-contentful query section

### PR DESCRIPTION
**Pull request by jserrao**
I cleaned up the queries part of the documentation (at the request of Kyle: [https://github.com/gatsbyjs/gatsby/issues/3205#issuecomment-414738208](https://github.com/gatsbyjs/gatsby/issues/3205#issuecomment-414738208)) to better reflect how this works in the wild. 

I could use a check on spelling, grammar and content. 

Hope it helps, Gatsby is an excellent project.

### CODE REVIEW

**Comment by m-allanson** [comment]
The failing tests seem to have been a temporary problem. I pushed up some more changes and they've all passed now.

**Comment by m-allanson** [comment]
I also took a run at condensing the content without removing any of the info. Merging now - thanks for your patience!

Also cc @gatsbyjs/docs in case you want to make any edits to this.

**Comment by shannonbux** [comment]
Thanks @jserrao and @m-allanson! Not sure how this got lost in the mix and many thanks for these edits! Looks great!

**Comment by jserrao** [comment]
@shannonbux - thanks. Happy to help out some more. Good docs are the #1 determinant if I'm going to use a tool. If there is a docs group within the maintainers, I'd be happy to take some tasks and improve things. Maybe you have a PM tool where you track what needs help?

**Comment by m-allanson** [comment]
Hey @jserrao ❤️❤️❤️ for more docs contributions. 

[Issues with the `type: documentation` label](https://github.com/gatsbyjs/gatsby/labels/type%3A%20documentation) are a good place to start, and can get an overall idea of where Gatsby's docs are heading from [docs issues with the "Epic" label](https://github.com/gatsbyjs/gatsby/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22type%3A+documentation%22+label%3AEpic).

Gatsby uses [ZenHub](https://www.zenhub.com/) to organise the _Epic_ issues which acts as a layer on top of GitHub. It's helpful, but not essential to contributing docs. 

There's also [a guide to contributing docs](https://www.gatsbyjs.org/docs/how-to-contribute/#contributing-to-the-documentation). You can ping @gatsbyjs/docs if you have any specific questions related to docs - we're all very happy to help 🙏

**Comment by jserrao** [comment]
@m-allanson - ok, great. I've got some time coming up with the holiday break, I'll see where I can be useful.

**Comment by KyleAMathews** [comment]
Thanks @jserrao!

**Comment by shannonbux** [comment]
Yes, thanks @jserrao and ditto to everything @m-allanson said!

**Pull request merged**
