### PR TITLE
chore(starters): add gatsby-wordpress-novela-starter

### PR DESCRIPTION
**Pull request by Gunnerforlife**
## Description

Submitting a new Gatsby starter. It's a blog website integrated with WordPress headless cms.

On-line demo is available at:
https://wp-novela-preview.draftbox.co/

### CODE REVIEW

**Comment by thandaanda** [comment]
Hi @yg ,

We have resolved merge conflicts. Let me know in case of any questions.

**Comment by thandaanda** [comment]
Hi @Ekwuno ,

Can you help us in merging this PR. It's been quite a few days since it is pending without any updates.
Let me know if we have to do something from our side.

-Regards,
Keyur

**Comment by thandaanda** [comment]
Hi @gatsbyjs/learning , folks can you help us with merging this PR.

**Comment by LekoArts** [comment]
Thanks so much for the PR!

Unfortunately, we're not going to merge this at this time. Our starter showcase demonstrates the vast array of vibrant, novel, and unique starters our users are building with Gatsby. We want to give the original authors credit and value their work and therefore won't merge starters with slight modifications of already existing starters.

As such--we're going to close this out. We want you to know that we certainly want to keep you as a contributor to Gatsby (and thanks again for _using_ Gatsby for your great application!), so we'd encourage you to check out our [open issues][open-issues].

Thanks again, and we look forward to seeing more PRs from you in the future! :muscle: :purple_heart:

[open-issues]: https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Pull request closed without merging**
