### PR TITLE
fix(gatsby-plugin-google-gtag): correct script to match google's current

### PR DESCRIPTION
**Pull request by benomatis**
When taking the script from GA directly, it doesn't have this additional check for `window.dataLayer`, also the related documentation shows it without it.

https://github.com/gatsbyjs/gatsby/blob/fc299ec93f90ceda4a80bbcce7b57d042ee480b4/packages/gatsby-script/README.md?plain=1#L40

https://github.com/gatsbyjs/gatsby/blob/fc299ec93f90ceda4a80bbcce7b57d042ee480b4/docs/docs/reference/built-in-components/gatsby-script.md?plain=1#L157

### CODE REVIEW

**Comment by LekoArts** [comment]
https://developers.google.com/tag-platform/gtagjs/install shows a different snippet:

```js
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());
```

Can you also update all the docs that include this? Thanks!

**Comment by benomatis** [comment]
> https://developers.google.com/tag-platform/gtagjs/install shows a different snippet:
> 
> ```js
>   window.dataLayer = window.dataLayer || [];
>   function gtag(){dataLayer.push(arguments)};
>   gtag('js', new Date());
> ```

Yes, indeed, I forgot to remove `window` from in front of `dataLayer.push(arguments)`.

> Can you also update all the docs that include this? Thanks!

Will do!

**Comment by benomatis** [comment]
@LekoArts should be done now.

**Review by LekoArts — APPROVED** [review]
Thanks 👍

**Comment by joaquingatica** [comment]
Came across this older PR while troubleshooting an error in Safari and DuckDuckGo Browser: #11431, and appears to be the reason the `window.dataLayer && window.` check was introduced.

Not questioning the decision of removing it, just wanted to add context in case it was missing at the time of merging, or to anybody who comes across this issue again.

**Comment by benomatis** [comment]
@joaquingatica the changes in this PR are in line with GA's current manual install instructions of the GA4 tag, and in that snippet they only check `window.dataLayer`, not `windows` and then proceed to use `dataLayer` as a standalone object. It is further detailed in the [description of the data layer](https://developers.google.com/tag-platform/tag-manager/datalayer).

I believe it must be happening for some other reason, most probably a browser plugin or privacy settings - [this question on SO](https://stackoverflow.com/q/51958650/2037924) may provide some valid answers to such cases.

**Pull request merged**
