### PR TITLE
Fix/graphql number

### PR DESCRIPTION
**Pull request by Khaledgarbaya**
Fixes https://github.com/gatsbyjs/gatsby/issues/3459

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Oh nice! Hadn't dug into those bug reports to understand what was going but this looks right :-)

Looks like a couple compiled files got included in the PR.

**Comment by Khaledgarbaya** [comment]
Yeah 🤦‍♂️  I will remove those

**Comment by Khaledgarbaya** [comment]
Done

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
