### PR TITLE
chore(docs): fixed links in performance-tracing

### PR DESCRIPTION
**Pull request by anishagg17**
## Description
updated link to  jaeger-local as it was converted to ts few days ago so, link turned obsolete

### CODE REVIEW

**Comment by anishagg17** [comment]
Previous link https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/tracer/jaeger-local.js

New Link
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/tracer/jaeger-local.ts

**Comment by vladar** [comment]
I mean this part is probably incorrect: `[node_modules/gatsby/dist/utils/tracer/jaeger-local.ts]` Because locally it is still `[node_modules/gatsby/dist/utils/tracer/jaeger-local.js]` (note the `.js` not `.ts`)

So I guess it makes sense to fix the link but keep the local path unchanged.

**Comment by anishagg17** [comment]
I have made requested changes 👍

**Comment by marcysutton** [comment]
This PR isn't showing any changes, is there something that needs to be adjusted? Otherwise we'll close it as there's no action to be taken currently.

**Pull request closed without merging**
