### PR TITLE
[gatsby-image] improvements

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@fk some nice simplifications for www in last commit https://github.com/gatsbyjs/gatsby/pull/2320/commits/509c3c2ea07d9d1866c9470f3b06a7c953073f31

**Comment by fk** [comment]
@KyleAMathews 😍 🎉

**Comment by KyleAMathews** [comment]
@fk checkout the fade-in on the avatar images ❤️  https://deploy-preview-2320--gatsbyjs.netlify.com/blog/

**Comment by fk** [comment]
Veeerrry nice!

**Comment by fk** [comment]
Are you seeing that too btw? https://www.dropbox.com/s/drx8ptrxptnv6re/gatsby.mov

**Comment by KyleAMathews** [comment]
Oh weird… sort of saw that. Tracking down bugs before pushing this out. Will look into this.

**Comment by KyleAMathews** [comment]
So looks like some sort of webkit/blink bug. Isn't happening in Firefox nightly

**Comment by KyleAMathews** [comment]
Kaboom. 5 year old bug! https://bugs.chromium.org/p/chromium/issues/detail?id=157218

**Comment by KyleAMathews** [comment]
Hmmm though it says it's fixed...

**Comment by KyleAMathews** [comment]
Ok, this fixes it https://stackoverflow.com/a/26358226/182702

**Comment by fk** [comment]
Esoteric CSS FTW! ;)

**Comment by KyleAMathews** [comment]
This PR turned into a bit of a doozy. List of changes/additions:

* Adds new pattern to Gatsby core for plugins to ship with GraphQL fragments. So now gatsby-transformer-sharp and gatsby-source-contentful ship fragments to be used with gatsby-image
* Added documentation
* Added a cache to the component so it doesn't lazy-load or fade in image on the second time we see an image as we assume it's already loaded by that point.
* Deprecated `responsiveSizes` and `responsiveResolution` and replaced them with shorter `sizes` and `resolutions`
* Improved the fade-in animation
* Worked around chrome/webkit bug
* Fixed support for background color placeholder
* Made all example sites and gatsbyjs.org use the new component

The component is starting to feel pretty production ready! Looking forward to seeing more people using it!

**Comment by ooloth** [comment]
Does gatsby-image work with background images as well?

**Pull request merged**
