### PR TITLE
fix(static-query): Use @babel/traverse for traversing algorithm

### PR DESCRIPTION
**Pull request by victor-cordova**
Hello :wave: , this PR fixes https://github.com/gatsbyjs/gatsby/issues/10016.
## Summary
After digging deep into the rabbit hole of the traversal algorithm in `/packages/gatsby/src/internal-plugins/query-runners/file-parser.js`, I found out that the traversing algorithm wasn't taking into account the ast nodes of type JSXFragment. Internally, this is because considered in the babel-types version used by babel-traverse v6.26. Therefore, I am using now the more updated @babel/traverse which is a dependency this package already had.

## Test code
I created a simple `gatsby new gastsby-test` and created a index with the following code
```javascript
import React from 'react'
import { StaticQuery, graphql } from 'gatsby'

import Layout from '../components/layout'

const query = graphql`
  query {
    site {
      siteMetadata {
        title
      }
    }
  }
`;

const IndexPage = () => (
  <Layout>
      <>
        <h1>Hello world!</h1>
        <StaticQuery query={query} render={() => (<div>Hello world</div>)}/>
      </>
  </Layout>
)

export default IndexPage
```

Then, tested it out with before the changes (displaying loading forever) and after the changes (displays correct text). It works fine and tests are still passing :smile: 

Let me know if you have any comments
Cheers

### CODE REVIEW

**Comment by jgierer12** [comment]
Thanks! We should probably also change the dependency in `package.json` and `yarn.lock`

**Comment by pieh** [comment]
We could also update https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/resolve-module-exports.js (only other place where we import `babel-traverse`). If this is drop-in replacement hopefully this is just matter of adjusting import.

> Thanks! We should probably also change the dependency in `package.json` and `yarn.lock`

We already have `@babel/traverse@^7` in dependencies. So if above is done, then we would need just to remove `babel-traverse@^6` from deps and update lock file.

One thing that could be helpful is to adjust (or add new test) for checking correctness of StaticQuery extraction if its inside `<>`

**Comment by pieh** [comment]
And btw - Awesome job on figuring this one out - it looks like really fringe issue to debug

**Comment by victor-cordova** [comment]
Thanks @pieh :) I'll make those changes and update the PR shortly.

**Comment by KyleAMathews** [comment]
Woah! Thanks for reaching deep and finding this! 🙏

**Pull request merged**
