### PR TITLE
update to webplace.com.au missing / in URL and main URL

### PR DESCRIPTION
**Pull request by webplaceaus**

### CODE REVIEW

**Comment by LekoArts** [comment]
Hi there! :wave: 

With the launch of the new, unified gatsbyjs.com comes some changes to the showcase and starter submission workflow.

You can read more details in the PR here: #26442

The data currently lives inside a WordPress instance so I changed the URL for you as otherwise it would be broken. Thanks for the notice :)

**Comment by webplaceaus** [comment]
Hi There,

Thanks for the prompt reply!

I just checked and the links still look to be broken - Please see
https://www.gatsbyjs.com/showcase/?filters%5B0%5D=Agency

I can still see https://www.gatsbyjs.com/showcase/null/www.webplace.com.au

Is the site cached perhaps?

Kind Regards,


*Cameron Fraser*Technical Director
Webplace

03 9429 1318
58 Duke Street, Abbotsford VIC 3067
<https://maps.google.com/?q=58+Duke+Street,+Abbotsford+VIC+3067&entry=gmail&source=g>

Email: cameron@webplace.com.au   |   Visit: webplace.com.au
<http://www.webplace.com.au/>
Instagram: @design.webplace <https://www.instagram.com/design.webplace/>
 |   Twitter @webplaceau <https://twitter.com/webplaceau>   |   Facebook:
webplaceaus <https://www.facebook.com/webplaceaus>

**Comment by LekoArts** [comment]
I'll let my colleague @gillkyle look into it :)

**Comment by gillkyle** [comment]
Hey @webplaceaus! I tried verifying the logic to build those linked urls was correct and am not seeing any issues in a fresh build. Feel free to ping me if you are still seeing issues but I'm seeing things link and load correctly now 🙂

**Comment by webplaceaus** [comment]
Hey Kyle,

Thanks so much. I can confirm the links are working now. Much appreciated.

I did notice that we are now showing last on all of the lists :( I don't
suppose there is a way to be bumped up a bit higher?

Many thanks,

Cameron


*Cameron Fraser*Technical Director
Webplace

03 9429 1318
58 Duke Street, Abbotsford VIC 3067
<https://maps.google.com/?q=58+Duke+Street,+Abbotsford+VIC+3067&entry=gmail&source=g>

Email: cameron@webplace.com.au   |   Visit: webplace.com.au
<http://www.webplace.com.au/>
Instagram: @design.webplace <https://www.instagram.com/design.webplace/>
 |   Twitter @webplaceau <https://twitter.com/webplaceau>   |   Facebook:
webplaceaus <https://www.facebook.com/webplaceaus>

**Pull request closed without merging**
