### PR TITLE
add javascriptstuff.com to showcase

### PR DESCRIPTION
**Pull request by ahfarmer**
Are you taking any Gatsby sites for the showcase list? I just built a new site and it is 100% Gatsby: https://www.javascriptstuff.com/

### CODE REVIEW

**Comment by KyleAMathews** [comment]
All Gatsby sites! Our list is getting a bit long but we'll be moving this to gatsbyjs.org soon where we can make all the sites searchable/browseable by category etc.

Love the site! One thing I noticed though is… Gatsby's missing haha :-) 

Also random whatever but on a larger screen, the y scrollbar comes and goes when you click to sub-pages from the frontpage. It's nice to make that always on so page transitions smoother.

**Comment by ahfarmer** [comment]
Hey! Thanks - Gatsby will definitely be there. I'm working on a list of 'static site generators' which is coming soon.

Do you think Gatsby belongs on a different list? Maybe I'll add all the gatsby boilerplates to the boilerplates list and then add a 'gatsby' tag.

Thanks for the tip on the y scrollbar. Good call 👍

**Comment by KyleAMathews** [comment]
>Maybe I'll add all the gatsby boilerplates to the boilerplates list and then add a 'gatsby' tag.

Yeah! I think Gatsby works well in both SSG + React Boilerplate lists.

**Comment by ahfarmer** [comment]
Cool great ideas. All done!

Static site generators list: https://www.javascriptstuff.com/static-site-generators/
Gatsby-tagged starters: https://www.javascriptstuff.com/react-starter-projects/#tag:gatsby

**Comment by KyleAMathews** [comment]
Perhaps add Gatsby itself to the React starters as well?

Also, a bit off-topic but since I was doing research on this recently :-) — we've been thinking for a while about expanding the Gatsby plugin page to automatically pull plugins from NPM and make a nice searchable/browseable interface like what you've done there. What are you using to pull the github / npm stats + READMEs? Just have a build server which fetches the data as needed?

**Comment by ahfarmer** [comment]
Hmmm yeah I'll have to think about adding Gatsby as a starter. That kind of stretches the definition a bit, but I think create-react-app does as well (it's not something you copy and modify).

I fetch data from GitHub - I don't actually use npm at all. I don't have a build server, instead I have a script that I run before publishing a new version of `javascriptstuff-db`.

This file is the main piece, it fetches the github repo data, the README, and the package JSON (if relevant). This just uses GitHub though - not NPM.
https://github.com/ahfarmer/javascriptstuff-db/blob/master/gather/src/project/fetchFullProject.js

For the star count, I grab that from GitHub directly from the client so it's always up-to-date.

**Comment by KyleAMathews** [comment]
> I'll have to think about adding Gatsby as a starter. That kind of stretches the definition a bit

Yeah, Gatsby is quite a bit like create-react-app that it hides things from you for the most part. Though we do offer an API/plugin system to modify things cleanly if you want.

>This file is the main piece

Cool! Thanks!

**Comment by KyleAMathews** [comment]
Next.js is also similar in that you don't generally modify it once you start using it.

**Pull request merged**
