### PR TITLE
docs(www): Broken Images in WordPress Image Tutorial

### LINKED ISSUE #15087: Bug: Image links broken in the WordPress Images Tutorial
## Description

In the Adding Images to a WordPress Site tutorial, the image links are broken: https://cl.ly/8f94b00cea7d . It looks like they are relative links.

### Steps to reproduce

In the [Adding Images to a WordPress Site]https://www.gatsbyjs.org/tutorial/image-tutorial/) at the end of the article, there are three broken images.

### Expected result

The images should be displayed (on gif, two images).

### Actual result

Currently, the images are broken.

### Environment

This is on the website here: https://www.gatsbyjs.org/tutorial/image-tutorial/

### Proposed Solution

I'm opening a PR with a modified links, based on the Contributing guidelines [here](https://www.gatsbyjs.org/contributing/gatsby-style-guide/#format-code-blocks-inline-code-and-images).

### PR DESCRIPTION
**Pull request by n8finch**
## Description

The images at the bottom of the Adding Images to a WordPress Site tutorial are broken. 
This commit adds the full URIs for the broken images in this file.

## Related Issues

Fixes #15087

### CODE REVIEW

**Comment by marcysutton** [comment]
Hey thanks for the PR, and good catch! I think this occurred when I moved advanced tutorial content from the docs section. We don't want to merge a change pointing to image source on Github since the images should be hosted on the Gatsby site. But the answer is actually in your code:

The images are still in `/docs/docs/images` in the master branch. The easiest fix would be to move those few images into `/docs/tutorial`, and create a new `/images` folder. Then the relative links should work again!

**Comment by n8finch** [comment]
@marcy gotcha! This pull request was created in browser and I'm not sure how I can pull this down to local to edit... So I opened a new PR... #15099. Sorry for any inconvenience.

**Comment by n8finch** [comment]
@marcysutton Sorry for the back and forth. Finally figured out how to update this PR... 😅

**Comment by n8finch** [comment]
Thanks @wardpeet !!

**Pull request merged**
