### PR TITLE
feat(gatsby-plugin-sharp): make default image quality option configurable

### LINKED ISSUE #4873: Add an option to configure default image quality for ImageSharp queries
Currently, the default quality of ImageSharp-generated images are too low for most of the projects I participate in. I would like to configure a global default for ImageSharp query parameters, because it may become tedious to always specify `quality: 92` in every single image query.

Issue #3837 is related, but it's about specifying a default locale for Moment.js date queries.

### PR DESCRIPTION
**Pull request by ivanicharts**
resolve #4873

### CODE REVIEW

**Comment by pieh** [comment]
Hey, did you see https://github.com/gatsbyjs/gatsby/pull/7548 ? It was using same approach but this not enough, as it won't apply to other uses of `gatsby-plugin-sharp` other than `gatsby-transformer-sharp`

**Comment by ivanicharts** [comment]
@pieh sorry, missed it

**Comment by pieh** [comment]
Note worthy - https://github.com/gatsbyjs/gatsby/pull/10210 sets up foundation to set default quality setting via plugin options for `gatsby-plugin-sharp`

**Comment by LekoArts** [comment]
Hi @ivanicharts 👋 Since https://github.com/gatsbyjs/gatsby/pull/10210 is merged you could rebase your fork onto master and work of that base.

**Comment by wardpeet** [comment]
Thanks so much for the PR!

Unfortunately, we're not going to merge this at this time. We don't set a defaultQuality anymore in transformer sharp, it's handled by sharp-plugin.

As such--we're going to close this out. We want you to know that we certainly want to keep you as a contributor to Gatsby, so we'd encourage you to check out our open issues.

Thanks again, and we look forward to seeing more PRs from you in the future! 💪 💜

**Pull request closed without merging**
