### PR TITLE
Update adding-analytics.md

### LINKED ISSUE #27623: Update analytics doc to use official Gatsby gtag plugin
## Summary

The existing [doc about adding Google analytics](https://www.gatsbyjs.com/docs/adding-analytics/) recommends using the `gatsby-plugin-gtag` plugin. As was pointed out after #27081 was merged, Gatsby actually maintains an official plugin with the same functionality, [`gatsby-plugin-google-gtag`](https://www.gatsbyjs.com/plugins/gatsby-plugin-google-gtag/).
 
The Adding Analytics doc should be updated to use this official plugin instead.

## Steps to resolve this issue

- [ ] Update the [Google analytics docs](https://www.gatsbyjs.com/docs/adding-analytics/) to use `gatsby-plugin-google-gtag` instead of `gatsby-plugin-gtag`.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #27623" in the pull request description

### PR DESCRIPTION
**Pull request by im-adithya**
## Description

Gatsby uses gatsby-plugin-google-gtag instead of gatsby-plugin-gtag. Hence the doc needed to be updated.
This PR closes #27623

### CODE REVIEW

**Comment by pfortes** [comment]
That was fast! Thanks @im-adithya,
I think this little change can be super good for new users looking at how to use gtag correctly with gatsby.

**Comment by im-adithya** [comment]
@LekoArts @meganesu Can you please merge this as Hacktoberfest is going to end 🥺

**Comment by meganesu** [comment]
@im-adithya I haven't gotten a chance to review this in detail yet, but I'll add the `hacktoberfest-accepted` label in the meantime so that you should be able to get credit.

**Comment by Miyou** [comment]
What about the plugin gatsby-plugin-google-analytics? What's the difference? Can't find any info about which one to use which is very confusing.

**Comment by pfortes** [comment]
> What about the plugin gatsby-plugin-google-analytics? What's the difference? Can't find any info about which one to use which is very confusing.
I will try to explain,
gatsby-plugin-google-analytics uses analytics.js which is the old code from google and is an oficial gatsby plugin.
gatsby-plugin-google-gtag uses the gtag script (new one and the one you should use) this is also an oficial plugin.

gatsby-plugin-gtag is not a oficial plugin.

**Review by pvdz — APPROVED** [review]
lgtm, thank you :purple_heart:

**Comment by Miyou** [comment]
> > What about the plugin gatsby-plugin-google-analytics? What's the difference? Can't find any info about which one to use which is very confusing.
> 
> I will try to explain,
> gatsby-plugin-google-analytics uses analytics.js which is the old code from google and is an oficial gatsby plugin.
> gatsby-plugin-google-gtag uses the gtag script (new one and the one you should use) this is also an oficial plugin.
> 
> gatsby-plugin-gtag is not a oficial plugin.

Thanks! That makes a lot of sense. Maybe it is obvious for those who know that there are two different google analytics scripts, but for someone who didn't I really couldn't figure out the difference.

**Pull request merged**
