### PR TITLE
fix(docs): Fix lint errors and add more nouns to the dictionary

### PR DESCRIPTION
**Pull request by tesseralis**
## Description

Fix linting errors on new docs.

### CODE REVIEW

**Comment by marcysutton** [comment]
Thanks for the prompt PR! Is adding every proper noun to the dictionary really the best way forward? That seems like we'll be chasing these warnings forever.

**Comment by tesseralis** [comment]
@marcysutton I'd argue it's not necessarily a *bad* idea. Proper nouns (people names, brand names) have proper spellings/capitalization as well and should be checked. In the initial PR, I ended up fixing a fair amount of inconsistencies in how library/brand names are spelled, so I think it's a good idea to add them. The other main category of "new words" are code, and those should be put in `backticks` anyway to not be linted.

**Comment by tesseralis** [comment]
Once #25275 goes in, I think it'll make the process easier? I can definitely iterate off of it though.

**Comment by marcysutton** [comment]
That makes sense, @tesseralis. Thanks for the follow-up and thinking it through! I'll check out the PR, and comment over there.

**Pull request merged**
