### PR TITLE
Remove magically module resolution

### PR DESCRIPTION
**Pull request by jquense**
removes a lot of the fancy module resolution and basically requires everything specify their own reps correctly. Probably breaks sites

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Yeah — seems pretty conclusive now magic resolution causes more problems than it helps.

To reduce impact (i.e. a site having tons more dependencies), we should export from Gatsby a number of packages e.g. gatsby-react-router-scroll, gatsby-link, perhaps react-router as well). It'd be nice if start Gatsby from scratch just meant installing Gatsby and React and that's it.

**Comment by jquense** [comment]
yeah i've been thinking a bit about that...reexporting is a nice clean solution tho it might lead to larger bundles for bigger plugins. We should definately think about it tho, maybe sort of like how webpack has some plugins built in?

**Comment by KyleAMathews** [comment]
Yeah exactly.

Why larger bundles?

**Comment by jquense** [comment]
thinking about if you have react-router, and then installed your own version. But that's maybe not likely, those sort of packages are really kinda implementation details to gatsby, it makes sense it would export them directly

**Comment by KyleAMathews** [comment]
Yeah — and if react-router makes a breaking change and releases v5 and we're on v4 and someone upgrades to v5, their Gatsby site will break.

Which is why I went with the current module resolution scheme — but that has a lot of disadvantages it's clear.

**Comment by jquense** [comment]
should still be good, does the direction seem right? It seems like others are handling the reexports now as well!

**Comment by jquense** [comment]
Maybe we should document what packages need to be rexported? do something like `gatsby/react-router` or something?

**Comment by KyleAMathews** [comment]
Yeah, let's definitely do this. Just need to finish the re-exporting & make sure everything is still working.

**Comment by pieh** [comment]
Is this still relevant?

**Pull request closed without merging**
