### PR TITLE
Call next() after serving HTML

### LINKED ISSUE #1348: [1.0] Static assets are timing out
Noticed the latest beta (6) seems to have broken static assets in development mode.

I've created a super basic example site here: https://github.com/levibuzolic/gatsby-test-site/tree/broken-static-assets

Seems like assets in the public directory aren't resolving anymore and just time out after ~2mins. However assets that are part of the bundle and are copied into `public/static` by gatsby seem to be working.

You can see the endlessly loading image in this screenshot:

image

### PR DESCRIPTION
**Pull request by levibuzolic**
Fixes #1348

Introduced in #1324

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Does this need to be in an else? Or does calling next have no effect if you've already responded? Don't use express much :-)

**Comment by levibuzolic** [comment]
Looking at the docs I think it's a no-op but will put it in an `else` as it seems to be the common convention.

> If the current middleware function does not end the request-response cycle, it must call next() to pass control to the next middleware function. Otherwise, the request will be left hanging.

**Comment by levibuzolic** [comment]
Commit updated.

**Comment by KyleAMathews** [comment]
Thanks for the quick fix!

**Pull request merged**
