### PR TITLE
chore(docs): Add proseWrap: never option to prettier markdown parsing

### LINKED ISSUE #21707: chore(docs): Add proseWrap: never option to prettier markdown parsing
## Description

Add `proseWrap: never` to the prettier config options for markdown files in the `docs/` directory (or all files if so inclined). Also add it to the prettier config of [gatsby-i18n-source](https://github.com/gatsbyjs/gatsby-i18n-source/blob/master/.prettierrc.js)

## Motivation

The [Translation Style Guide](https://www.gatsbyjs.org/contributing/translation/style-guide/#use-soft-line-wraps) asks to use soft line wraps instead of hard ones. This makes it easier to track changes across repos without causing weird breaks among split-line sentences.

By adding a lint rule to our documentation files we can ensure that this is always the case.

### PR DESCRIPTION
**Pull request by kartikcho**
Fixes #21707

New fixed version of #22688

### CODE REVIEW

**Comment by kartik918** [comment]
Hey @vladar @pvdz, the checks came succesful finally! (well at least most of them)

Thanks for helping me out.

**Comment by kartik918** [comment]
@tesseralis can we get this merged before the prettier purging is successful from Gatsby?  :P 
Thanks!

**Comment by tesseralis** [comment]
@kartik918 could we update this PR and get this merged? We're running into some problems with the remark formatter and so we're still using Prettier as our formatter for now. For resolving the merge commits I would recommend:

```
git merge -X theirs
```

This will resolve the build with the changes from master (which are mostly formatting changes due to remark-lint). From there you can re-run prettier with the `proseWrap: never` option to re-format everything.

**Comment by kartik918** [comment]
@tesseralis done! 

md files with tables seems to be acting out on tests. 

Can we only update the rule and get it merged? Reformatting can be done in a follow-up PR that also rewrites tests accordingly.

**Comment by kartik918** [comment]
I realized those tests are for ``remark-lint`` , this should sit fine then. Let me know if I need to change or add anything else.

**Comment by tesseralis** [comment]
@kartik918 I think there's a bug in prettier that's causing the tables to be formatted incorrectly. If you go to the [Prettier playground](https://prettier.io/playground/) and toggle `proseWrap` on a table with a long heading, it'll toggle between aligned and unaligned.

I think it'll be fine to disable the table alignment rule for now since I think consistent prose wrap is more important, but I'd like to ask @kylegill first on what he thinks.

**Comment by gillkyle** [comment]
I'm all for disabling a rule if it's causing problems!

**Comment by kartik918** [comment]
Should I update the PR again then @tesseralis?

Let me know how to disable table alignment rules @gillkyle.

**Comment by tesseralis** [comment]
@kartik, you just need to add the line

```
[`remark-lint-table-pipe-alignment`, false]
```

to `.remarkrc.js` in the top level directory.

**Comment by kartik918** [comment]
Done! @tesseralis anything else?

**Comment by tesseralis** [comment]
@kartik918 There are still some linting errors, but once that's fixed, this should be good to go!

**Comment by kartik918** [comment]
Hey @tesseralis almost everything is green except this one last test (that I can't comprehend what's wrong). Can you help me out with this one? Thanks :)

**Comment by kartik918** [comment]
@tesseralis *nudge*

**Comment by kartikcho** [comment]
There's context in this [comment](https://github.com/gatsbyjs/gatsby/pull/23429#issuecomment-625557477) on why I disabled `remark-lint-table-pipe-alignment` in this PR.

Do you have something in mind on how I should go with this @sidharthachatterjee ?

**Comment by AishaBlake** [comment]
> @kartik, you just need to add the line
> 
> ```
> [`remark-lint-table-pipe-alignment`, false]
> ```
> 
> to `.remarkrc.js` in the top level directory.

@kartikcho I'm sorry this is taking time to merge in. It looks like this line wasn't actually in there, though. I pushed a commit to add it. Is there something else I'm missing from this conversation? We've still got some linting issues but it looks like the table formatting is no longer causing warnings.

**Comment by kartikcho** [comment]
Thanks @aishablake! You're upto date on all the stuff relevant to this PR as far as I know.

Running prettier makes no changes to formatting for me, yet `yarn lint:other` still fails.

**Comment by kartikcho** [comment]
Hi @AishaBlake , any updates on this?

**Comment by LekoArts** [comment]
Thanks for the PR! For now I'll close this as it's not actionable. The initial reasons for this PR are no longer relevant as our setup has changed a bit.

**Pull request closed without merging**
