### PR TITLE
 [gatsby-image] prefer webp (#2491)

### PR DESCRIPTION
**Pull request by Fetten**
* add new fragments in gatsby-transformer-sharp with additional `srcWebp` and `srcSetWebp` fields

* create additional webp files in gatsby-plugin-sharp

* use `srcWebp` and `srcSetWebp` in gatsby-image if browser supports webp

### CODE REVIEW

**Comment by KyleAMathews** [comment]
From quick look-through it looks awesome!

Could you add webp to www, using-gatsby-image, and image-processing so we can see how things look there?

Excited for this!!

**Comment by KyleAMathews** [comment]
BTW, do you have a sense of how much longer this makes processing?

**Comment by Fetten** [comment]
I haven't really measured before/after, but I'd say image processing time is at least doubled (if not even tripled) now (additional webp images + imagemin-webp).

**Comment by Fetten** [comment]
Ok, after sleeping on it last night I refactored the implementation.

By using individual resolvers for `srcWebp` and `srcSetWebp` instead of always creating additional webp files in `gatsby-plugin-sharp`, webp's now only are created on request. This won't affect build time of (existing) projects that do not use the new webp fragments at all.

**Comment by KyleAMathews** [comment]
Awesome work!

Sorry for the slow reply — been at Chrome Developer Summit last few days.

Going to merge this now so we can get it out there but could you do a follow up PR documenting this in the image-processing site + adding the new graphql fragment to www?

Also at some point it'd be great to add optional support to gatsby-remark-images for webp.

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 300e373a55de87a02d85c0e03f610e630b6e303f

https://app.netlify.com/sites/using-glamor/deploys/59f0e9870b79b77802e376d2

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0f099498f7029917592aaec85b4351f142b6ec73

https://app.netlify.com/sites/using-glamor/deploys/59f0ed18a6188f32f6d49d88

**Comment by jlengstorf** [comment]
Hiya @Fetten! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
