### PR TITLE
Add bartvanderwaerden.com to showcase

### PR DESCRIPTION
**Pull request by BartvdWaerden**

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
Can I suggest that the showcased websites are moved to a new file? The list is getting bigger and bigger and I think it's taking important space of the README that should be reserved to more important info. Perhaps, if you want to "show off", you can keep a few websites like the React one.

**Comment by KyleAMathews** [comment]
We are soon! Check out the discussion over at https://github.com/gatsbyjs/gatsby/issues/4392 — we'll be building a splashy showcase for the website so will trim down the sites in the README down and refocus it on technical overview.

**Comment by BartvdWaerden** [comment]
@KyleAMathews Thank you very much! And thanks for providing such a great tool/experience!

**Comment by jlengstorf** [comment]
Hiya @BartvdWaerden! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
