### PR TITLE
update gatsby-config.js

### PR DESCRIPTION
**Pull request by OMGUPTA21**
commenting
great code

### CODE REVIEW

**Review by Chandu2000 — APPROVED** [review]

**Comment by OMGUPTA21** [comment]
Thanks

**Comment by OMGUPTA21** [comment]
How to claim swag.

**Comment by OMGUPTA21** [comment]
But why.

**Comment by OMGUPTA21** [comment]
sir,
This is to inform that I completed deploy 4 swag -gatby swag  challenge and
also deploy a site I want to get swag mail,
my project link ~https://blogger22018.gatsbyjs.io/
Your faithfully
OM GUPTA

**Comment by OMGUPTA21** [comment]
My project is https://blogger21.gatsbyjs.io/

**Pull request closed without merging**
