### PR TITLE
replace absolute links with relative links for gatsbyjs.org docs

### PR DESCRIPTION
**Pull request by benforshey**
These links have to function both within gatsbyjs.org and within github.com, so I think they should be written as inline HTML. The currently do not resolve correctly within gatsbyjs.org. #2998

### CODE REVIEW

**Comment by benforshey** [comment]
I just realized that it may not be the goal to have gatsbyjs.org links resolve correctly in the docs on GitHub. After all, none of the other gatsbyjs.org relative path links would work in the docs here. I'd be happy to submit another PR with the links written in Markdown, just using relative paths instead of absolute paths.

**Comment by markmichon** [comment]
Looks like the bug is definitely that they should be relative urls like the rest of the docs (as you note in your issue, and in the recent comment). I'd swap them to relative in the PR, but you can always ping Kyle and see what his thoughts are.

The build setup is really the cause of this, as it's not just docs, but also non-doc pages that get pulled into the live site. Small downside, but maybe there should be a note somewhere that the docs source of truth is the site rather than the repo.

sidebar: I knew your name looked familiar! Great to see an FS grad making PRs on Gatsby! 👍

**Comment by benforshey** [comment]
@markmichon You, sir, have great taste in static site generators. :-) Glad to see you here!

I'll edit the PR for relative links, since that's consistent with the rest of the docs.

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 7eb3799e9c1ef9cd886f50a07a45bd19eec86639

https://app.netlify.com/sites/using-glamor/deploys/5a19bd8ba11477454ee5b714

**Comment by KyleAMathews** [comment]
Thanks for this fix! And yeah, we should add a note somehow in the docs on Github to encourage people to not read them there. Every once in awhile people post PRs/issues saying the links are wrong.

**Comment by KyleAMathews** [comment]
Added a README https://github.com/gatsbyjs/gatsby/blob/master/docs/README.md

**Comment by jlengstorf** [comment]
Hiya @benforshey! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
