### PR TITLE
fix(www): tweak docsearch to init algolia when tabbed into

### LINKED ISSUE #21705: bug(www): Docsearch doesn't work when tabbed into.
## Description

The algolia autocomplete doesn't work when using `Tab` to navigate to it.

### Steps to reproduce

1. Open https://gatsbyjs.org.
2. Press `Tab` multiple times until the search bar is highlighted.
3. Type something to search for it.

### Expected result

The Algolia autocomplete loads.

### Actual result

The autocomplete doesn't work.

### Environment

N/A

### PR DESCRIPTION
**Pull request by tbntdima**
Basically this PR fixes a bug described in #21705.
You can find more details on the solution in the thread on an issue.

Fixes #21705

### CODE REVIEW

**Comment by pvdz** [comment]
@madalynrose can you take a look at this, please? Calling `.focus()` makes me itchy but it kinda makes sense. Would love to have your insight on this.

**Comment by pvdz** [comment]
@madalynparker can you take a look at this, please? Calling `.focus()` makes me itchy but it kinda makes sense. Would love to have your insight on this.

**Comment by madalynrose** [comment]
> @madalynparker can you take a look at this, please? Calling `.focus()` makes me itchy but it kinda makes sense. Would love to have your insight on this.

haha that's a very old account from college I think 🙈 calling `.focus()` seems fine here since the bug is that it actually moves focus away from the element, which is disruptive and confusing.

**Comment by dmitriyaa** [comment]
Node: 
It's my first experience writing tests, would love some feedback. I know the code appeared to be pretty repetitive since we have 3 similar cases. If you know some better options, please share? Should I move common login into a separate function?

**Comment by pvdz** [comment]
Fwiw, I like explicit tests. Abstractions tend to hide problems or cause superficial problems and false positives.

**Comment by pvdz** [comment]
( Btw the new tests are not passing. Are they passing when you run `yarn jest` locally? You can run `yarn jest www/src/components/search-form/__tests__/search-form.js` to only test your file, and (for example) ``yarn jest www/src/components/search-form/__tests__/search-form.js -t "it initializes algola docsearch on form focus, and keeps focus"` to test one specific test case. )

**Comment by tbntdima** [comment]
@pvdz thanks for noticing it. Tests used to pass locally. I cleared the cache and reinstalled node modules, and it failed. Should be fixed now 🙃

**Pull request merged**
