### PR TITLE
[chore] update socket.io and ws to remove security vulnerabilities

### PR DESCRIPTION
**Pull request by gabrielcsapo**
## Description

Updates socket.io and ws to remove the following vulnerabilities 

Screen Shot 2021-06-01 at 7 21 06 PM

### Documentation

N/A

## Related Issues

N/A

### CODE REVIEW

**Comment by wardpeet** [comment]
For information, 4.0.0 is a major change. The release logs tell us that it wouldn't harm us but it should be properly tested.
https://github.com/socketio/socket.io/releases/tag/4.0.0

**Comment by gabrielcsapo** [comment]
@wardpeet what's the best way to test this?

**Comment by wardpeet** [comment]
@gabrielcmarinho this was more for the fellow maintainers :joy:. To test this we should run `gatsby develop` but also have a cloud preview running with Sanity as they use Websocket connections.

**Comment by gabrielcmarinho** [comment]
@wardpeet I think you mentioned the wrong Gabriel 😂

**Comment by gabrielcsapo** [comment]
Gabes unite!

**Comment by gabrielcsapo** [comment]
Is there any testing I can do to have these dependencies updates?

**Comment by LekoArts** [comment]
Hi!

We currently don't have the bandwidth to thoroughly test this and while those audit messages might seem scary they are almost always irrelevant in the context of Gatsby as it's a build tool. So there is nothing to "fix" as the warning is not relevant and the update would be a nice to have.

If you know that a vulnerability affects Gatsby because you understand what the vulnerability is, please report it [here](https://github.com/gatsbyjs/gatsby/blob/master/SECURITY.md). Thanks!

**Pull request closed without merging**
