### PR TITLE
feat(docs): add additional info on using filters with GraphQL

### PR DESCRIPTION
**Pull request by RobinCsl**
Summary: The GraphQL Reference will now contain information about all the
 available filter operators, with examples of how to use them.
A link to the test file `/packages/gatsby/src/schema/__tests__/run-query.js` has been added for reference.

Closes https://github.com/gatsbyjs/gatsby/issues/10908

### CODE REVIEW

**Comment by cardiv** [comment]
Exactly what I need. Thanks @RobinCsl! 👍

**Comment by RobinCsl** [comment]
@gatsbyjs/docs Is there a reason why all the tests did not proceed?

**Comment by DSchau** [comment]
@RobinCsl CI working as intended--if not a bit confusingly. When we detect a PR that is just documentation change _or_ a PR with docs/ or docs- in the branch name, we only run a sub-set of the test functionality.

Bit confusing, for sure. Wish Github would be able to be notified of the (not required) status checks on these PRs 😢

**Comment by RobinCsl** [comment]
Sure, I could do that too. I had thought about it, and decided that if you were looking for one specific operator, you would want the example right away, without scrolling through other operator examples. But maybe having all these iframes is harming performance?

So would you prefer the structure to look like:

## Filter

[ Existing description ]

### Operators

[ list of operators with (now expanded) description ]

[ one iframe with all the examples ]

**Comment by LekoArts** [comment]
I'd also prefer one example (iframe) for all operators 👍

**Comment by DSchau** [comment]
@RobinCsl if you have some time--merging into one CodeSandbox example/iframe would be 👌 Thank you in advance!

**Comment by RobinCsl** [comment]
@LekoArts @DSchau I edited my PR and the playground now contains the following content:
```
{
  # eq: I want all the titles that match "Fantastic Beasts and Where to Find Them"
  example_eq:allMarkdownRemark(
    filter: {
      frontmatter: {
        title: {
          eq: "Fantastic Beasts and Where to Find Them"
        }
      }
    }
  ) {
    edges {
      node {
        frontmatter {
          title
        }
      }
    }
  }
  
  # neq: I want all the titles which are NOT equal to the empty string
  example_ne:allMarkdownRemark(
    filter: {
      frontmatter: {
        title: {
          ne:""
        }
      }
    }
  ) {
    edges {
      node {        
        frontmatter {
          title
        }
      }
    }
  }
  
  # regex: I want all the titles that do not start with 'T' -- this is what /^[^T]/ means.
  # To learn more about regular expressions: https://regexr.com/
  example_regex:allMarkdownRemark(
    filter: {
      frontmatter: {
        title: {
          regex: "/^[^T]/"
        }
      }
    }
  ) {
    edges {
      node {
        frontmatter {
          title
        }
      }
    }
  }
  
  # glob: I want all the titles that contain the word 'History'.
  # The wildcard * stands for any non-empty string.
  example_glob:allMarkdownRemark(
    filter: {
      frontmatter: {
        title: {
          glob: "*History*"
        }
      }
    }
  ) {
    edges {
      node {
        frontmatter {
          title
        }
      }
    }
  }
  
  # in: I want all the titles and dates from `frontmatter`
  # where the title is either 
  # - "Children's Anthology of Monsters", or
  # - "Hogwarts: A History".
  example_in:allMarkdownRemark(
    filter: {
      frontmatter: {
        title: {
          in: [
            "Children's Anthology of Monsters",
            "Hogwarts: A History"
          ]
        }
      }
    }
  ) {
    edges {
      node {
        frontmatter{
          title
        	date
     		}
      }
    }
  }
  
  # nin: I want all the titles and dates from `frontmatter`
  # where the title is neither 
  # - "Children's Anthology of Monsters", nor
  # - "Hogwarts: A History".
  example_nin:allMarkdownRemark(
    filter: {
      frontmatter: {
        title: {
          nin:[
            "Children's Anthology of Monsters",
            "Hogwarts: A History"
          ]
        }
      }
    }
  ) {
    edges {
      node {
        frontmatter{
          title
        	date
     		}
      }
    }
  }
  
  # lte: I want all the titles for which `timeToRead` is less than or equal to 4 minutes.
  example_lte:allMarkdownRemark(
    filter: {
      timeToRead: {
        lte: 4
      }
  	}
  ) {
    edges {
      node {
        frontmatter {
          title
        }
      }
    }
  }
  
  # elemMatch: I want to know all the plugins that contain "chokidar" in their dependencies.
  # Note: the `allSitePlugin` query lists all the plugins used in our Gatsby site. 
  example_elemMatch: allSitePlugin(
    filter:{
      packageJson:{
        dependencies:{
          elemMatch:{
            name:{
              eq:"chokidar"
            }
          }
        }
      }
  	}
  ) {
    edges {
      node{
        name
      }
    }
  }
}
```

**Comment by DSchau** [comment]
Looks great; thanks for updating!

**Pull request merged**
