### PR TITLE
match graphql var to fn prop

### PR DESCRIPTION
**Pull request by holylander**
## Description

Super small update to match the created `const` with the function `props`

### CODE REVIEW

**Comment by muescha** [comment]
this variable is not used as parameter - renaming it would give wrong implicitly connection

see also: https://www.gatsbyjs.com/docs/page-query/#how-does-the-graphql-tag-work

**Comment by holylander** [comment]
omg...its true. Thanks @muescha, lets cancel the PR then. 
However, I am confused, I cant cleary see how the values retrieved on the query magically appear on that function prop. I guess its all matter of rereading the documention.

**Comment by LekoArts** [comment]
Hi, thanks for the PR! As Muescha correctly linked the name of the variable doesn't correspond to the available prop in the React component (it doesn't matter in fact). The document also links to our Internals which can also give you another angle on this: https://www.gatsbyjs.com/docs/gatsby-internals/

**Comment by holylander** [comment]
thanks guys :9

**Comment by muescha** [comment]
i see this confusion a second time, maybe because of this line:

```javascript
const data = useStaticQuery(
```
in https://www.gatsbyjs.com/tutorial/part-four/#use-a-staticquery

is it worth to add to this previous section https://www.gatsbyjs.com/tutorial/part-four/#use-a-page-query an hint how the `query` consumed? 


or is it too much for this tutorial?

**Pull request closed without merging**
