### PR TITLE
fix(gatsby): remove 404 pagedata logic on client side pages

### LINKED ISSUE #16097: Requests for page-data.json return 404 in client side routes
## Description

Hey team! I've noticed an issue with client side routes recently.

When navigating to client side routes, Gatsby requests the associated `page-data.json` which returns a 404. For example, navigating to `/app/profile` loads `/page-data/app/profile/page-data.json`, which returns a 404 if the `/app` page has a matchPath of `/app/*`. This is reproducible in the [simple-auth example](https://github.com/gatsbyjs/gatsby/tree/master/examples/simple-auth) which has a `gatsby-node.js` like this:

```js
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions

  // page.matchPath is a special key that's used for matching pages
  // only on the client.
  if (page.path.match(/^\/app/)) {
    page.matchPath = `/app/*`

    // Update the page.
    createPage(page)
  }
}
```

Note this doesn't seem to affect the rendering of the page. It looks like it's still getting the correct page data for the matchPath page even though Gatsby is making a request for different page data.

### Steps to reproduce

You can reproduce this in the the [simple-auth example](https://github.com/gatsbyjs/gatsby/tree/master/examples/simple-auth).

1. Clone the simple-auth example
2. Install the latest gatsby
3. `gatsby build` and `gatsby serve`
4. Navigate to `localhost:9000/app/login`

You get some 404s for page-data
image

### Expected result

Gatsby shouldn't request `page-data.json` for client side routes.

### Actual result

Gatsby requests `page-data.json` for client side routes and receives a 404.

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.3.1 - ~/.asdf/shims/node
    Yarn: 1.16.0 - ~/.asdf/shims/yarn
    npm: 6.9.0 - ~/.asdf/shims/npm
  Languages:
    Python: 2.7.15 - /Users/thanx/.asdf/shims/python
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.41 => 2.13.41
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.12

### PR DESCRIPTION
**Pull request by wardpeet**
## Description
We have got a few complaints about page-date returning 404s when doing client side only pages. We fetched page-data of every page and when it returned a 404 we fallback to matchpath.

This pr writes pages that are inside a matchpath to matchpath.json so we can safely rely on  match-path.json.

It reverts most of https://github.com/gatsbyjs/gatsby/pull/15762 which was added to do the 404 page-data checks.

Still on my todo is to add a simple test for the findPath function.

## Related Issues
Fixes #16097

### CODE REVIEW

**Comment by wardpeet** [comment]
looks like tests aren't passing yet

**Comment by wardpeet** [comment]
I've tested it manually and our e2e tests cover it basically pretty well.

I've published a canary version on `gatsby@page-data-404`

**Comment by sidharthachatterjee** [comment]
This looks great overall to me! Will hold off on merging this in for now since you've added the _needs manual testing_ label

**Comment by oorestisime** [comment]
Not sure if this is helpful but i tried this with a project that was impacted by these 404s (and limiting page speeds) and problems "vanished". thanks for working on this :)

**Comment by sever1an** [comment]
Is there anything I can do to help with this PR? Does it just need testing code?

**Comment by wardpeet** [comment]
It seems like there are some troubles with prefetching page-data that is still happening, I can't really reproduce it so I would suggest merging this one and I'll ask for reproduction for a follow-up fix.

**Comment by JustFly1984** [comment]
I have issues with `/` page and localized copies `/ru/` and `/en/`, rendering as 404 page after this PR was merged and published in 2.15.23

All other pages rendering properly. rolling back to 2.15.22 solves an issue.

I have created this issue: https://github.com/gatsbyjs/gatsby/issues/17980

**Comment by antoinerousseau** [comment]
Same here, had to rollback to 2.15.22, otherwise pages created with `createPage()` are not accessible and land to 404 instead.

**Comment by metamn** [comment]
Hmmm ... rolled back to 2.15.22 but still this particular post gives 404: http://metamn.io/react/react-follows-the-functional-reactive-programming-paradigm/

Try to refresh it: First the page is rendered then it is replaced by the 404.

I've done everything: empty cache, renamed the post twice, upgraded all packages ... and nothing.

Thanks!

**Comment by metamn** [comment]
If it helps: the 404 comes from page-data.json

Screenshot from 2019-10-03 03-02-28

**Comment by sever1an** [comment]
@metamn Do you have a matchPath or client only route to provide the 404 page? Can you share the contents of .cache/match-paths.json in your project?

**Comment by metamn** [comment]
@sever1an For the first question: I don't know but here is the repo: https://github.com/metamn/react
For the second: 

```
[]
```

**Comment by sever1an** [comment]
@metamn Probably not related to the issue reported above by JustFly1984.

A brief examination reveals that the page is attempting to fetch the page-data.json from an incorrect url:  `http://metamn.io/react/page-data/-follows-the-functional-reactive-programming-paradigm/page-data.json`

The page-data.json does exist at the *correct* url: `http://metamn.io/react/page-data/react-follows-the-functional-reactive-programming-paradigm/page-data.json`

**Comment by metamn** [comment]
Thanks @sever1an !!

Any hints why is that? Cleaning cache would help?

**Comment by metamn** [comment]
Or should I file a separate issue?

**Comment by sever1an** [comment]
I think it would be helpful to create a new issue referencing your suspicion that it started with this pull request and sharing the insight about searching at the wrong url for a `page-data.json` that exists. 

The Gatsby core team is at a conference and not available this week so keeping things as well structured and clean as possible here will help tremendously.

**Comment by metamn** [comment]
Thanks again! :)

**Comment by sever1an** [comment]
@antoinerousseau Do you have a github of the affected project? Do you have anything in `.cache/match-paths.json` after a build?

**Pull request merged**
