### PR TITLE
use consistent chunk ids

### PR DESCRIPTION
**Pull request by stevensurgnier**
Consistent chunk ids are generated by truncating the md5 of the chunk name to a 64 bit integer.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit a63f1a73001737a71cb95687f723024e635f3b48

https://app.netlify.com/sites/using-styled-components/deploys/596cfd386f4c5075cc3c3b5f

**Comment by craig-mulligan** [comment]
Hey @stevensurgnier doesn't the `webpack-md5-hash` plugin cover this? Or is it do something else?

**Comment by stevensurgnier** [comment]
The webpack-md5-hash produces the chunkhash - a hash of the chunk's content. This PR modifies the chunk id - an internal webpack id. By default the chunk id is represented as a sequential integer. You can see it in the manifest and a final chunk file. The problem I ran into is that the chunk id can change when you add more chunks. However, the chunkhash is a function of the chunk content not the file content. Thus, the file can change while the chunkhash remains the same. If you're caching based on chunkhash (or filename) this will cause big problems. This PR provides a consistent chunk id based on chunk name. Unfortunately, the version of webpack we're on requires the chunk id to be an integer. Thus, the not so ideal amount of entropy used in this PR.

**Comment by KyleAMathews** [comment]
This is awesome! Thanks for researching the fix and creating the PR.

**Comment by craig-mulligan** [comment]
@stevensurgnier, Hmm I didn't consider that, super interesting thanks for the explanation 👍

**Pull request merged**
