### PR TITLE
fix(gatsby): Reorder head tags

### LINKED ISSUE #22206: gatsby-plugin-react-helmet orders the components too late in <head>
## Description

When I use `gatsby-plugin-react-helmet` I notice that the `<Helmet />` components come way too late in the head tag. I have noticed that on occasion for instance Facebook does not always parse the `og` tags if they come too late in the head.

### Steps to reproduce

Just use `<Helmet />`, and notice in the static output files there is a lot of CSS related stuff etc. above the helmet tag in the `<head>`.

### Expected result

Helmet tags should be prioritised when doing the `<head />` tag.

### Workaround
Currently there is easy workaround, but I consider that gatsby's default is broken. We should not need workaround for this.

gatsby-ssr.js
```javascript
var React = require("react");

// Hack, to reorder the helmet components as first in <head> tag
exports.onPreRenderHTML = ({ getHeadComponents, replaceHeadComponents }) => {
    /**
     * @type {any[]} headComponents
     */
    const headComponents = getHeadComponents();

    headComponents.sort((a, b) => {
        if (a.props && a.props["data-react-helmet"]) {
            return 0;
        }
        return 1;
    });
    replaceHeadComponents(headComponents);
};
```

### PR DESCRIPTION
**Pull request by graysonhicks**
## Description

Reorder tags to e.g. move css below meta tags as apparently larger stylesheets block the parsers

## Related Issues

Fixes #22206

### CODE REVIEW

**Review by KyleAMathews — DISMISSED** [review]
🙏🥳

**Comment by KyleAMathews** [comment]
Actually why don't we just do this in the framework itself?

**Comment by graysonhicks** [comment]
Fine by me.  Probably a better 'batteries included' experience than needing this plugin configured for that best practice.  As long as the plugin wouldn't undo the framework's sorting.

**Comment by KyleAMathews** [comment]
Yeah we'd do the sorting after all plugins have run. This is in the oddly named static-entry.js files

**Review by mygoldpaw — APPROVED** [review]

**Comment by graysonhicks** [comment]
@KyleAMathews I moved the same sorting logic to right before head components are sent to static HTML.  One thing I am not sure of is whether this will interfere with [this line](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/static-entry.js#L378) for determining whether to inline styles.

**Comment by graysonhicks** [comment]
I still need to make a contrived example with lots of head tags to compare the sorting order.

**Comment by Ciantic** [comment]
I looked at the diff, what does it do to tags that are not listed in this?

```
   headComponents = [
      ...groupedByType.title,
      ...groupedByType.base,
      ...groupedByType.meta,
      ...groupedByType.style,
      ...groupedByType.link,
      ...groupedByType.script,
      ...groupedByType.noscript,
    ]
```

For example, if you have `<template />` tags in your head, will they be removed?

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head#see_also), allowed tags are: 

```<title>, <base>, <link>, <style>, <meta>, <script>, <noscript>, <template>````

**Comment by graysonhicks** [comment]
@Ciantic Yea, that is a good point about tags not listed there.  Technically there is already some opinionated ordering done by when certain tags are pushed to `headComponents`, but we could, as you say, just preserve those and move `meta` to the top.

**Comment by graysonhicks** [comment]
Possible other solution in `static-entry` then is just:

```
 headComponents.sort((a, b) => {
        if (a.type && a.type === 'meta') {
            return -1;
        }
        return 0;
    });
```

**Comment by KyleAMathews** [comment]
The inline styles are already added by the time you sort right?

We should definitely sort rather than rewrite.

**Comment by graysonhicks** [comment]
Yea, the inline styles are added via `unshift` before I have the `sort`.

**Comment by graysonhicks** [comment]
In my first bit of testing on this with the sort, the ordering looks correct during SSR, but then the tags are back out of order (meta tags from helmet specifically) in DevTools.  Is there something updating the head components during/after hydration?

@KyleAMathews

**Comment by KyleAMathews** [comment]
So if you curl the page the tags are correct?

Once on the client, tags are added by react-helmet in the order of the code so they'll be back to that. But to fix the issue with crawlers we only need to worry about the SSRed html.

**Comment by graysonhicks** [comment]
I didn't curl exactly, but yea the first network request with the SSR'd HTML looks correct.  Cool, that makes sense about the crawlers!  I'm gonna try to repro the actual `og:image` failure.

**Comment by graysonhicks** [comment]
URL with this fork patched in shows the correct tags on the initial request now:

*go here:*
https://headtagstestmain.gatsbyjs.io/

*do this:*
open network tab
select first network request (the domain)
open the HTML from the first request (can prettify in chrome with {} button)

*see this:*
`meta` tags are above all `script` and `style` tags

I tried testing with the [Twitter Card Validator](https://cards-dev.twitter.com/validator), but I think it may be using a cached version (the image is missing) since I had tested before without the patch.  The [Facebook sharing tester](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fheadtagstestmain.gatsbyjs.io%2F) is showing the correct data.

**Review by KyleAMathews — APPROVED** [review]
:shipit:

**Comment by m99coder** [comment]
Will it be backported/be part of Gatsby 3.x?

**Comment by manutdkid77** [comment]
Similar question to @m99coder, will this be backported to Gatsby 2.x ? we have some sites still running on Gatsby 2.19

**Comment by LekoArts** [comment]
It'll only be backported to v3

**Comment by manutdkid77** [comment]
> It'll only be backported to v3

Thats a bummer, we have sites which we dont want to upgrade to v3 and would be nice if it could be backported to v2

**Comment by t2ca** [comment]
I have just tested v4.5 and I noticed that the meta tags show up on top only on initial page load. Once I click on a link it gets reordered again and certain meta tags are under the styles once again.

**Comment by KyleAMathews** [comment]
@t2ca crawlers only grab the HTML so you should be fie

**Comment by m99coder** [comment]
Hi @graysonhicks and @KyleAMathews, I updated my Gatsby dependency to 4.5.2 and deployed the new version. Unfortunately, I still see a suboptimal order of tags in the `<head>`.

```
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">

<link rel="manifest" href="/site.webmanifest">

<title>Geschenkanhänger Wolke aus Holz · woodist</title>
<title data-react-helmet="true"></title>

<meta name="generator" content="Gatsby 4.5.2">

<link rel="sitemap" type="application/xml" href="/sitemap/sitemap-index.xml">

<!-- script preloads omitted -->
<!-- fetch preloads omitted -->

<noscript>
  <style>
    /* Gatsby image styles */
  </style>
</noscript>
<script type="module">/* Gatsby Image code */</script>
<style data-href="/styles.f096984017ec13218975.css" data-identity="gatsby-global-css">
  /* massive initial styles (probably because of importing them in the layout component */
</style>
<style>/* Gatsby Image styles */</style>

<!-- dns-prefetchs omitted -->

<meta name="description" content="Dieser Holzanhänger in Form einer Wolke zaubert den Beschenkten mit Sicherheit ein Lächeln ins Gesicht. Es ist ausreichend Platz für ein paar liebe Zeilen, ein kurzes Statement, den Namen oder oder oder... Leb dich aus mit Acrylfarben, Brandmalerei oder Acrylstiften." data-react-helmet="true">
<meta name="keywords" content="Geschenkanhänger,Anhänger aus Holz,Wolke aus Holz,Anhänger Wolke" data-react-helmet="true">
<meta name="image" content="https://cdn.shopify.com/s/files/1/0279/1938/4659/products/20210801_134314_400x533_crop_center.jpg?v=1629974153" data-react-helmet="true">

<meta property="og:url" content="https://woodist.de/produkt/anhaenger-wolke" data-react-helmet="true">
<meta property="og:title" content="Geschenkanhänger Wolke aus Holz" data-react-helmet="true">
<meta property="og:description" content="Dieser Holzanhänger in Form einer Wolke zaubert den Beschenkten mit Sicherheit ein Lächeln ins Gesicht. Es ist ausreichend Platz für ein paar liebe Zeilen, ein kurzes Statement, den Namen oder oder oder... Leb dich aus mit Acrylfarben, Brandmalerei oder Acrylstiften." data-react-helmet="true">
<meta property="og:image" content="https://cdn.shopify.com/s/files/1/0279/1938/4659/products/20210801_134314_400x533_crop_center.jpg?v=1629974153" data-react-helmet="true">
<meta name="twitter:card" content="summary_large_image" data-react-helmet="true">
<meta name="twitter:image" content="https://cdn.shopify.com/s/files/1/0279/1938/4659/products/20210801_134314_400x533_crop_center.jpg?v=1629974153" data-react-helmet="true">

<!-- prefetchs omitted -->
```

I might make so wrong that `gatsby-global-css` gets so big, but on the other hand, the reordering of meta tags should have moved the `<meta …>` ones way up, I guess.

Source: https://woodist.de/produkt/anhaenger-wolke/

**Comment by graysonhicks** [comment]
@m99coder When I visit that site and look at the network tab, I see a different set of head tags than you've posted above.  The meta tags are totally missing when I look, but otherwise the order is correct.  How are they being added?  The network tab is what a crawler would see.

**Comment by m99coder** [comment]
The meta tags are added using `react-helmet` like this:

```javascript
import { Helmet } from "react-helmet"

const Layout = () => {
  return (
    <Helmet
      title={seo.title}
      titleTemplate={seo.title === defaultTitle ? seo.title : titleTemplate}
    >
      <meta name="description" content={seo.description} />
      <meta name="keywords" content={seo.metatags.join(",")} />
      <meta name="image" content={seo.image} />

      {/* DNS prefetch */}
      <link rel="dns-prefetch" href="//images.ctfassets.net/" />
      <link rel="dns-prefetch" href="//cdn.shopify.com/" />
      <link rel="dns-prefetch" href="//m99.io/" />

      {/* Open Graph, see https://ogp.me/ */}
      {seo.url && <meta property="og:url" content={seo.url} />}
      {seo.title && <meta property="og:title" content={seo.title} />}
      {seo.description && (
        <meta property="og:description" content={seo.description} />
      )}
      {seo.image && <meta property="og:image" content={seo.image} />}

      {/* Twitter, see https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started */}
      <meta name="twitter:card" content="summary_large_image" />
      {seo.image && <meta name="twitter:image" content={seo.image} />}
    </Helmet>
  )
}
```

**Comment by graysonhicks** [comment]
@m99coder Yes, would be interesting to see if there is a difference between the Helmet attributes vs children.

**Comment by m99coder** [comment]
@graysonhicks Sadly doesn’t change the result. Even https://github.com/nfl/react-helmet shows that defining the tags as children should work. Now I’m a bit clueless 😕 May it be related to how the SSR works? On the other side I don’t think my setup is anyhow unique, so wonder why it doesn’t happen for others as well.

**Comment by desktopofsamuel** [comment]
Same issues here @graysonhicks. Twitter validator & Facebook Sharing Debugger cannot crawl the meta tags after upgrading to v4.5.2 even tags order shifted already. My SEO components was pretty much copied from another site coming from v3 which is totally working right now.

What I discovered is that the crawler completed even before content from the `react-helmet` injected. 
From what Facebook crawler see exactly for the URL https://developers.facebook.com/tools/debug/echo/?q=https%3A%2F%2Fjuxtdesign.cc%2Fblog%2Ftry-our-keystroke-figma-template%2F 
All react-helmet content is not present but it's totally there when I open it in Chrome Devtools. Maybe @m99coder you can also try and see the same behavior? (Bottom of the [Sharing Debugger](https://developers.facebook.com/tools/debug/))

My testing link:
https://juxtdesign.cc/blog/try-our-keystroke-figma-template/

Just for reference, my SEO component, placed in `layout.tsx`
```
  return (
    <Helmet>
      {/* General tags */}
      <html lang="en" />
      <title>{title}</title>
      <meta name="title" content={title} />
      <meta name="description" content={description} />
      <meta name="image" content={image} />
      <meta name="keywords" content={keywords} />
      <meta name="publisher" content={config.siteTitleShort} />
      <meta name="author" content={config.siteTitleShort} />
      <meta name="copyright" content={config.copyright} />

      {/* Schema.org tags */}
      <script type="application/ld+json">
        {JSON.stringify(schemaOrgJSONLD)}
      </script>

      {/* OpenGraph tags */}
      <meta property="og:url" content={postURL} />
      {postSEO ? (
        <meta property="og:type" content="article" />
      ) : (
        <meta property="og:type" content="website" />
      )}
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:image" content={image} />
      <meta
        property="fb:app_id"
        content={config.siteFBAppID ? config.siteFBAppID : ``}
      />

      {/* Twitter Card tags */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta
        name="twitter:site"
        content={config.userTwitter ? config.userTwitter : ``}
      />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={image} />
    </Helmet>
  );
}
```
My info:
```
  System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 97.0.4692.71
    Safari: 15.2
  npmPackages:
    gatsby: 4.5.2 => 4.5.2
    gatsby-plugin-google-tagmanager: 4.5.0 => 4.5.0
    gatsby-plugin-image: 2.4.0 => 2.4.0
    gatsby-plugin-manifest: 4.5.1 => 4.5.1
    gatsby-plugin-sharp: 4.4.0 => 4.4.0
    gatsby-plugin-sitemap: 5.5.0 => 5.5.0
    gatsby-source-filesystem: 4.4.0 => 4.4.0
    gatsby-source-prismic: 5.2.3 => 5.2.3
    gatsby-theme-stitches: 1.0.0 => 1.0.0
    gatsby-transformer-sharp: 4.4.0 => 4.4.0
```

**Comment by graysonhicks** [comment]
Okay, thanks.  This seems like a separate issue.  The original issue was tags were out of order (no matter how they were added).  This seems like react-helmet isn't getting SSR'd.  There shouldn't be a 'too late' because the static markup should have the correct tags before hydration.  Can you open a new issue?

**Comment by desktopofsamuel** [comment]
> Okay, thanks. This seems like a separate issue. The original issue was tags were out of order (no matter how they were added). This seems like react-helmet isn't getting SSR'd. There shouldn't be a 'too late' because the static markup should have the correct tags before hydration. Can you open a new issue?

Sorry, I created a reproduction repo and realised `gatsby-plugin-react-helmet` has not been installed. Installing it and adding in `gatsby-config.js` has resolved the issue now.

**Comment by m99coder** [comment]
@desktopofsamuel @graysonhicks I checked the Facebook Developer Echo result you shared, and in my case the `react-helmet` extensions to the `<head>` are not there. Maybe because I played around with the hydrate function in `gatsby-browser.js` in that sense:

```javascript
import ReactDOM from "react-dom"
import { wrapPageElement as wrapper } from "./src/utils/wrap-page-element"

export const wrapPageElement = wrapper

// this is a hack to fix missing styles on refresh in production
// see: https://github.com/gatsbyjs/gatsby/issues/8560#issuecomment-535265414
// and: https://github.com/gatsbyjs/gatsby/discussions/17914
export function replaceHydrateFunction() {
  return (element, container, callback) => {
    ReactDOM.render(element, container, callback)
  }
}
```

As soon as I find time, I will strip down my setup to the bare minimum and see at which point the functionality is broken. Chances are high that I added some custom logic that killed the expected behaviour 😅

**Comment by m99coder** [comment]
Created a bare, unmodified repository like this:

```
gatsby new gatsby-metatags https://github.com/gatsbyjs/gatsby-starter-default
```

You can find the respective code here: https://github.com/m99coder/gatsby-open-graph-metatags.

Now when I run `gatsby develop`, I get the following response when running a request with `curl -s http://localhost:8000`:

```html
<!DOCTYPE html>
<html>

<head>
  <meta charSet="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="note" content="environment=development" />
  <title data-react-helmet="true"></title>
  <style>
    .gatsby-image-wrapper {
      position: relative;
      overflow: hidden
    }

    .gatsby-image-wrapper picture.object-fit-polyfill {
      position: static !important
    }

    .gatsby-image-wrapper img {
      bottom: 0;
      height: 100%;
      left: 0;
      margin: 0;
      max-width: none;
      padding: 0;
      position: absolute;
      right: 0;
      top: 0;
      width: 100%;
      object-fit: cover
    }

    .gatsby-image-wrapper [data-main-image] {
      opacity: 0;
      transform: translateZ(0);
      transition: opacity .25s linear;
      will-change: opacity
    }

    .gatsby-image-wrapper-constrained {
      display: inline-block;
      vertical-align: top
    }
  </style><noscript>
    <style>
      .gatsby-image-wrapper noscript [data-main-image] {
        opacity: 1 !important
      }

      .gatsby-image-wrapper [data-placeholder-image] {
        opacity: 0 !important
      }
    </style>
  </noscript>
  <script
    type="module">const e = "undefined" != typeof HTMLImageElement && "loading" in HTMLImageElement.prototype; e && document.body.addEventListener("load", (function (e) { if (void 0 === e.target.dataset.mainImage) return; if (void 0 === e.target.dataset.gatsbyImageSsr) return; const t = e.target; let a = null, n = t; for (; null === a && n;)void 0 !== n.parentNode.dataset.gatsbyImageWrapper && (a = n.parentNode), n = n.parentNode; const o = a.querySelector("[data-placeholder-image]"), r = new Image; r.src = t.currentSrc, r.decode().catch((() => { })).then((() => { t.style.opacity = 1, o && (o.style.opacity = 0, o.style.transition = "opacity 500ms linear") })) }), !0);</script>
  <link rel="icon" href="/favicon-32x32.png?v=4a9773549091c227cd2eb82ccd9c5e3a" type="image/png" />
  <link rel="manifest" href="/manifest.webmanifest" crossorigin="anonymous" />
  <link rel="apple-touch-icon" sizes="48x48" href="/icons/icon-48x48.png?v=4a9773549091c227cd2eb82ccd9c5e3a" />
  <link rel="apple-touch-icon" sizes="72x72" href="/icons/icon-72x72.png?v=4a9773549091c227cd2eb82ccd9c5e3a" />
  <link rel="apple-touch-icon" sizes="96x96" href="/icons/icon-96x96.png?v=4a9773549091c227cd2eb82ccd9c5e3a" />
  <link rel="apple-touch-icon" sizes="144x144" href="/icons/icon-144x144.png?v=4a9773549091c227cd2eb82ccd9c5e3a" />
  <link rel="apple-touch-icon" sizes="192x192" href="/icons/icon-192x192.png?v=4a9773549091c227cd2eb82ccd9c5e3a" />
  <link rel="apple-touch-icon" sizes="256x256" href="/icons/icon-256x256.png?v=4a9773549091c227cd2eb82ccd9c5e3a" />
  <link rel="apple-touch-icon" sizes="384x384" href="/icons/icon-384x384.png?v=4a9773549091c227cd2eb82ccd9c5e3a" />
  <link rel="apple-touch-icon" sizes="512x512" href="/icons/icon-512x512.png?v=4a9773549091c227cd2eb82ccd9c5e3a" />
  <script src="/socket.io/socket.io.js"></script>
  <link rel="stylesheet" href="/commons.css" />
</head>

<body>
  <div id="___gatsby"></div>
  <script src="/polyfill.js" nomodule=""></script>
  <script src="/framework.js"></script>
  <script src="/commons.js"></script>
</body>

</html>
```

As you can see there are no SEO-related metatags included.
But wait 😄 As soon as I use `gatsby serve`, I get the following `<head>` tag content which is expected and correct:

```html
<head>
  <meta charSet="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta data-react-helmet="true" name="twitter:description"
    content="Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need." />
  <meta data-react-helmet="true" name="twitter:title" content="Home" />
  <meta data-react-helmet="true" name="twitter:creator" content="@gatsbyjs" />
  <meta data-react-helmet="true" name="twitter:card" content="summary" />
  <meta data-react-helmet="true" property="og:type" content="website" />
  <meta data-react-helmet="true" property="og:description"
    content="Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need." />
  <meta data-react-helmet="true" property="og:title" content="Home" />
  <meta data-react-helmet="true" name="description"
    content="Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need." />
  <meta name="generator" content="Gatsby 4.5.4" />
  <!-- more non-meta tags -->
</head>
```

So there is clearly an issue somewhere in my original project. I will try to narrow it down.

**Comment by m99coder** [comment]
@graysonhicks @KyleAMathews I might have found the issue 🤭 

With my last commit https://github.com/m99coder/gatsby-open-graph-metatags/commit/3f63d1239be9cf17bd0e65837f2652286d022aca I create a dynamic page like this in `gatsby-node.js`:

```javascript
exports.createPages = async ({ actions }) => {
  const { createPage } = actions
  createPage({
    path: "/using-dsg",
    component: require.resolve("./src/templates/using-dsg.js"),
    context: {},
    defer: true,
  })
  
  createPage({
    path: "/test",
    component: require.resolve("./src/templates/test.js"),
    context: {},
  })
}
```

When the path is requested the original request is redirected to the one with a trailing slash:

```
Request URL: http://localhost:9000/test
Request Method: GET
Status Code: 301 Moved Permanently

Request URL: http://localhost:9000/test/
Request Method: GET
Status Code: 200 OK
```

This is in contrast to the `/using-dsg` dynamic page – it’s path is not redirected to a trailing-slash version. I also assume that the `defer` option (using DSG) should not determine if the redirect is happening or not. Finally, I assume that the social share tools work similar to using curl they might not follow the redirect.

**Comment by m99coder** [comment]
Human error… pure human error 🚯 

In my `wrapPageElement` method, I just forgot to use `{element}` in non-browser environments as well. This prevented `react-helmet` from setting the `headComponents` correctly.

I really apologize for all the hassle. This feature works as intended.

**Comment by graysonhicks** [comment]
No worries, thanks @m99coder !

**Comment by mixdmark** [comment]
I understand from this thread, that Gatsby should now sort the head tags automatically. Or is there something I have to specify in my code for the sorting to be enabled?

I'm using Gatsby 4.10.1, gatsby-react-helmet-plugin and SEO component as defined in official Gatsby site template. My pages are created in gatsby-node.js with createPages. I'm using static site generation as rendering method.

And Chrome Network tab shows that meta tags are still in random places in the head, mostly after scripts, links and styles.

**Comment by graysonhicks** [comment]
@mixdmark Could you please open a new issue with a reproduction?  Should be working by default.

**Comment by niksumeiko** [comment]
@mixdmark, I just tried it with [gatsby@v4.19](https://github.com/gatsbyjs/gatsby/releases/tag/gatsby%404.19.0) and can confirm the production build contains meta tags correctly ordered (at the very top of the `<head>` section) automatically.

**Pull request merged**
