### PR TITLE
fix(www): Remove crashing starter

### PR DESCRIPTION
**Pull request by tesseralis**
## Description

Fix builds crashing due to not finding a starter:

Error getting repo data for starter “gatsby-starter-auth-aws-amplify”: Could not resolve to a User with the username ‘ben-siewert’.: {“response”:{“data”:{“repository”:null},“errors”:[{“type”:“NOT_FOUND”,“path”:[“repository”],“locations”:[{“line”:3,“column”:15}],“message”:“Could not resolve to a User with the username ‘ben-siewert’.“}],“status”:200},“request”:{“query”:“\n query {\n repository(owner:\“ben-siewert\“, name:\“gatsby-starter-auth-aws-amplify\“) {\n name\n stargazers {\n totalCount\n }\n createdAt\n pushedAt\n owner {\n login\n }\n nameWithOwner\n }\n }\n “}}

### CODE REVIEW

**Comment by muescha** [comment]
showcase url changed to: 

old: https://github.com/ben-siewert/gatsby-starter-auth-aws-amplify
new: https://github.com/seabeams/gatsby-starter-auth-aws-amplify

**Comment by muescha** [comment]
code snippet from: `onCreateNode`
https://github.com/gatsbyjs/gatsby/blob/1ecc0ec84f473f6e18ccb175ec96cb4dc3b62064/www/src/utils/node/starters.js#L198-L203

should this just ignore this starter in `onCreateNode` when something fails (print a warning and send out some notification)?

**Comment by tesseralis** [comment]
@muescha I think so. We've had a couple of issues with moved/broken starters breaking the build recently. It would be better to just ignore it and send a warning than failing builds each time. Could you make an issue for it?

**Comment by muescha** [comment]
@tesseralis 

added issue #21813

**Comment by muescha** [comment]
should this starter readded?

**Pull request merged**
