### PR TITLE
[v2][www] Move YAML link files to data

### PR DESCRIPTION
**Pull request by ryanditjia**
This feels like the proper directory to store the files.

Also renamed the extension of one of the files to .yaml as recommended by [YAML official FAQ](http://yaml.org/faq.html)

### CODE REVIEW

**Comment by pieh** [comment]
i think we would need more organization in `data` dir if we would move files there - maybe new `sidebars` dir for yamls you moved and `site-showcase` for sites.yml? I'll keep it open a little longer for more feedback

**Comment by ryanditjia** [comment]
I’ve moved the sidebar links to a `sidebars` subdirectory.

I have yet to touch `sites.yml` though, because I’m not sure if it has any dependants.

**Comment by m-allanson** [comment]
Refs: #5348

**Comment by KyleAMathews** [comment]
Nice! Makes a lot of sense.

**Pull request merged**
