### PR TITLE
chore(gatsby-plugin-preact): update docs after Preact X release

### PR DESCRIPTION
**Pull request by vitordino**
## Description

Preact X has released! And as I we’ve already had this plugin dependency updated (on #18057) i imagine it would be nice to update our docs too 👐

### CODE REVIEW

**Comment by gustavpursche** [comment]
@vitordino I was using the last preact beta and had to realize that `gatsby-link` is not compatible with preact (the URL was updated, but the new content isn't loaded). In case this problem still exists, do you think it would make sense to mention it here?

**Comment by vitordino** [comment]
hi @gustavpursche doesn’t your problem isn’t the same as [**preact**’s `#1966`](https://github.com/preactjs/preact/issues/1966)? if so, it’s probably fixed, and you just have to pin the stable `10.0.0` version

**Comment by gustavpursche** [comment]
✨ 

> Yes but which version of Preact X, that bug was present in rc.2 and rc.3 but should be resolved in the final.

Ohlala. Thanks for the pointer, seems to be fixed!

**Comment by wardpeet** [comment]
published in gatsby-plugin-preact@3.1.15

**Pull request merged**
