### PR TITLE
chore(gatsby): upgrade `null-loader`

### LINKED ISSUE #22409: Unable to exclude an imported css file from static build
## Description

Given a css file is excluded leveraging null-loader from static build
When gatsby build triggered
Then error is thrown

### Steps to reproduce

1. npx gatsby new gatsby-site
2. adjust gatsby-node.js
```
exports.onCreateWebpackConfig = (
  { stage, actions },
) => {
  if (stage === 'build-javascript') {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /\/layout\.css$/,
            use: 'null-loader',
          },
        ],
      },
    });
  }
};
```
3. gatsby build

or try to build from

https://github.com/beliayeu/gatsby-starter-default/tree/bug/null-loader

### Expected result

gatsby build finishes without errors. layout.css is not included in the bundled css

### Actual result

error is thrown

```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(1:1) Unknown word

> 1 | // empty (null-loader)
```

### Related issue

* https://github.com/webpack-contrib/null-loader/pull/24

### Note
* please suggest if there is a better pattern how to exclude an asset from static build

### PR DESCRIPTION
**Pull request by beliayeu**
## Description

see #22409

## Related Issues

Fixes #22409

### CODE REVIEW

**Comment by pieh** [comment]
There are few breaking changes on the way - https://github.com/webpack-contrib/null-loader/blob/master/CHANGELOG.md

Will have to wait for https://github.com/gatsbyjs/gatsby/pulls to be able to use v3 of null-loader (because right now we have 8.0 support still)

**Comment by beliayeu** [comment]
@pieh, as an option null-loader can be upgraded to v2 since v2 contains the fix for the problem I encountered and per my understanding v2 is node 8 compatible. btw, is there a better pattern how to exclude assets from build? lets assume there is a css file imported by a component, we want to include this file while in gatsby develop but exclude it during gatsby build

**Comment by pieh** [comment]
> @pieh, as an option null-loader can be upgraded to v2 since v2 contains the fix for the problem I encountered and per my understanding v2 is node 8 compatible.

We do plan to drop Node 8 tomorrow - we worked out most of CI problems today (but there can be delays), so if you are fine with holding to this PR a bit longer we can keep `null-loader@3`. The note was as much for you as much for anyone else checking this PR after me ;)

> is there a better pattern how to exclude assets from build? lets assume there is a css file imported by a component, we want to include this file while in gatsby develop but exclude it during gatsby build

This is probably best way to do this, but I'm pretty confused about aplying `null-loader` just for build step. You ultimately do have to add styles somehow to your site?

**Comment by beliayeu** [comment]
> We do plan to drop Node 8 tomorrow - we worked out most of CI problems today (but there can be delays), so if you are fine with holding to this PR a bit longer we can keep null-loader@3

sounds great. I am totally fine

> This is probably best way to do this, but I'm pretty confused about aplying null-loader just for build step. You ultimately do have to add styles somehow to your site?

the styles are added in gatsby-browser.js and in components. we have some styles that are needed only while we are in gatsby develop (styles needed for admin ui), that is why I was looking for a way how to exclude those admin styles from static build

**Comment by pieh** [comment]
> the styles are added in gatsby-browser.js and in components. we have some styles that are needed only while we are in gatsby develop (styles needed for admin ui), that is why I was looking for a way how to exclude those admin styles from static build

not ideal, but you probably could try something like this (pretty sure `import` syntax won't work with conditional like that, that's why it's require):
```js
if (process.env.BUILD_STAGE !== `build-javascript`) {
  require(`./layout.css`)
}
```

We use similar thing in gatsby ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/public-page-renderer.js )

**Comment by pieh** [comment]
Just note, that I don't think we document `BUILD_STAGE` "env var" (it's not really env var, it's using webpack's DefinePlugin), so this is not really part of public API

**Pull request merged**
