### PR TITLE
fix(gatsby-recipes): Add `file` note to fs provider describe

### PR DESCRIPTION
**Pull request by muescha**
## Description

suggestion:
- update description to be equal to directory

https://github.com/gatsbyjs/gatsby/blob/0f2be968c0e3b889650f5fa5dd05692b50cd7b2a/packages/gatsby-recipes/src/providers/fs/directory.js#L55

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Oh snapshots need updated — could you run from the `gatsby-recipes` directory this command: `GATSBY_RECIPES_NO_COLOR=true jest --testPathPattern "src/.*plugin.test" --watch`

Thanks!

**Comment by muescha** [comment]
this is the output:

```javascript
$ GATSBY_RECIPES_NO_COLOR=true jest --testPathPattern "src/.*plugin.test" --watch
 PASS  src/providers/gatsby/plugin.test.js
  gatsby-plugin resource
    ✓ e2e plugin resource test (470ms)
    ✓ e2e plugin resource test with hello world starter (54ms)
    ✓ all returns plugins as array (103ms)
    ✓ does not add the same plugin twice by default (7ms)
    ✓ removes plugins by name and key (9ms)
    ✓ validates the gatsby-source-filesystem specifies a key
    ✓ validates the gatsby-source-filesystem specifies a key that isn't equal to the name (1ms)
    ✓ adds multiple gatsby-source-filesystems and reads with key (52ms)
    ✓ handles config options as an object (4ms)
    ✓ creates default gatsby-config.js if there isn't one already (8ms)

Test Suites: 1 passed, 1 total
Tests:       10 passed, 10 total
Snapshots:   13 passed, 13 total
Time:        2.443s
Ran all test suites matching /src\/.*plugin.test/i.

Active Filters: filename /src/.*plugin.test/
 › Press c to clear filters.

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press o to only run tests related to changed files.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
```

but when i run all tests i see errors

**Comment by muescha** [comment]
should i run jest with `--updateSnapshot`?

**Comment by KyleAMathews** [comment]
yeah sorry, yes run it with `--updateSnapshot`

**Comment by KyleAMathews** [comment]
not `--watch`

**Comment by muescha** [comment]
updated screenshots with `GATSBY_RECIPES_NO_COLOR=true jest -u`

**Comment by LekoArts** [comment]
https://github.com/gatsbyjs/gatsby/pull/26821 removed those test files, so if you're up for it you'll need to rebase onto latest master :)

**Comment by LekoArts** [comment]
I'll close this PR as stale, feel free to reopen :)

**Pull request closed without merging**
