### PR TITLE
Fixes to docs

### PR DESCRIPTION
**Pull request by LeKoArts**
I split up the changes into their own commits which should speak for themselves. I did the `Change npm i to install` to keep it consistent with the rest of the docs.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit fe54d3ec7dba7e9930627c5d1b24f3bbd4af1c0c

https://app.netlify.com/sites/using-postcss-sass/deploys/5b681db3c9659234122eaf8a

**Comment by KyleAMathews** [comment]
Deploy preview for *using-styled-components* failed.

Built with commit fe54d3ec7dba7e9930627c5d1b24f3bbd4af1c0c

https://app.netlify.com/sites/using-styled-components/deploys/5b681db4c9659234122eaf96

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit fe54d3ec7dba7e9930627c5d1b24f3bbd4af1c0c

https://app.netlify.com/sites/image-processing/deploys/5b681db3c9659234122eaf90

**Comment by KyleAMathews** [comment]
Deploy preview for *using-jss* failed.

Built with commit fe54d3ec7dba7e9930627c5d1b24f3bbd4af1c0c

https://app.netlify.com/sites/using-jss/deploys/5b681db6c9659234122eafb1

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit fe54d3ec7dba7e9930627c5d1b24f3bbd4af1c0c

https://app.netlify.com/sites/using-contentful/deploys/5b681db4c9659234122eaf99

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit fe54d3ec7dba7e9930627c5d1b24f3bbd4af1c0c

https://app.netlify.com/sites/using-glamor/deploys/5b681db3c9659234122eaf93

**Comment by LeKoArts** [comment]
Bots will take over the world 😦

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 32ca50cf5f6b9cc78712314d1017c7df035b6e97

https://app.netlify.com/sites/using-postcss-sass/deploys/5b681e2c67610c6bf5ed4d5a

**Comment by KyleAMathews** [comment]
Deploy preview for *using-styled-components* failed.

Built with commit 32ca50cf5f6b9cc78712314d1017c7df035b6e97

https://app.netlify.com/sites/using-styled-components/deploys/5b681e2c67610c6bf5ed4d66

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit 32ca50cf5f6b9cc78712314d1017c7df035b6e97

https://app.netlify.com/sites/image-processing/deploys/5b681e2c67610c6bf5ed4d60

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 32ca50cf5f6b9cc78712314d1017c7df035b6e97

https://app.netlify.com/sites/using-glamor/deploys/5b681e2c67610c6bf5ed4d63

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit 32ca50cf5f6b9cc78712314d1017c7df035b6e97

https://app.netlify.com/sites/using-contentful/deploys/5b681e2c67610c6bf5ed4d69

**Comment by KyleAMathews** [comment]
Deploy preview for *using-jss* failed.

Built with commit 32ca50cf5f6b9cc78712314d1017c7df035b6e97

https://app.netlify.com/sites/using-jss/deploys/5b681e2c67610c6bf5ed4d81

**Pull request merged**
