### PR TITLE
feat(gatsby-source-filesystem): add an environment variable to control concurrent queue size

### PR DESCRIPTION
**Pull request by violy**
related to #13073

### CODE REVIEW

**Comment by pieh** [comment]
Thanks for changes @violy!

Just curious what were values you used for timeout / retries - maybe better approach would be to change defaults there?

**Comment by violy** [comment]
as I explain on the issue #13073 — during my troubleshooting, I observed this warning, for different reasons (server overload, network / local overload) related to my stack and my work environment, and my successive attempts to valid locally my build. 

During my troubleshooting, I've try to change `timeout` & `retries` values, **but with no effect**. The only success was changing `concurrent` to lower value (`10` instead of `200`, in my case) the original question in my issue / PR. 
But I think to _other case_ where troubleshooting could be painful, access to `const` via `.env` variables or equivalent, is a good way to adjust the stack with no pain. 

When I finally deployed my app, via _netlify_, there was **no problem** (no need to fix with custom fork 😅)! 
So initial default static values may be not so bad!

**Comment by pieh** [comment]
So if changing those didn't have any effect I'm not sure it makes sense to add yet more moving parts. I would prefer to just add `GATSBY_CONCURRENT_DOWNLOAD` and more detailed error message here.

**Comment by muescha** [comment]
the new possible env variables should be anywhere documented:

- GATSBY_CONCURRENT_DOWNLOAD
- GATSBY_DOWNLOAD_TIMEOUT
- GATSBY_DOWNLOAD_RETRIES

**Comment by violy** [comment]
Thank you, according your comment @pieh 
I've update my PR, by removing the variables `GATSBY_DOWNLOAD_TIMEOUT` & `GATSBY_DOWNLOAD_RETRIES` maybe useless.

**Comment by muescha** [comment]
Maybe it would be nice to have an "main entry point" for all "magic numbers" and a default solution how to overwrite it.

**Comment by LekoArts** [comment]
@violy Hi 👋 Do you have time to update your PR (adding information to README) and resolve the conflicts? Would be cool to have this in!

**Comment by violy** [comment]
@LekoArts thanks for your request, 
so I've resolve conflict and add a small word in the README Configuration paragraph and force-push all the change in one commit.

**Comment by violy** [comment]
Any news / reviewer ?

**Comment by muescha** [comment]
This download manager should also include an cache and some strategies how not redownload media assets when nothing is changed.

**Comment by DSchau** [comment]
@muescha I think the issue (#10049) is a better place for that comment; thanks! Otherwise it's very possible we'll lose track of your suggestions.

**Comment by muescha** [comment]
Is there also a stragegy only to download the used media assets (when maybe more assets are saved in wordpress but only some used in the used articles)?

**Comment by muescha** [comment]
Thanks for your hint. I was thinking i am already in the other issue.

**Comment by KyleAMathews** [comment]
Yeah, env variables seem appropriate now as a temporary fix until we can work on #10049

**Pull request merged**
