### PR TITLE
chore(docs): fix commas and tweak small issues in tutorial

### PR DESCRIPTION
**Pull request by dhurlburtusa**

### CODE REVIEW

**Comment by DSchau** [comment]
Thanks for unifying these! Let me know when it's ready for a review--and I'll take another look!

**Comment by dhurlburtusa** [comment]
@DSchau A question for you. Many times I have two reasonable choices for some of the changes involving commas: 1) simply remove the comma so that a list of two phrases are connected or 2) leave in the comma and add a subject to the second phrase thus turning it into an independent clause.

Do you have a preference?

**Comment by marcysutton** [comment]
@dhurlburtusa it definitely depends on the context and at the same time is quite subjective. I would say use your best judgement and only change something if absolutely necessary!

**Comment by DSchau** [comment]
@dhurlburtusa let me know if this is ready for a review. Appreciate the work you're doing here!

**Comment by dhurlburtusa** [comment]
Hi @DSchau,

I made it all the way through the tutorial and one blog article (written by you), which was very good by the way. Thanks.

I hope that I did a good job with the punctuation. I am by no means a grammar expert. I had to lookup several rules that I either never learned or had forgotten.

Thanks for accepting my contributions. I am enjoying learning about Gatsby. I am using it to build a business website.

What should I do about the prettier failure? Is there an easy way to find out what prettier is complaining about without having to clone the repo, setting it up, and then running the lint script?

Once I get the lint error resolved, then this PR will be ready to merge.

**Comment by pieh** [comment]
> What should I do about the prettier failure? Is there an easy way to find out what prettier is complaining about without having to clone the repo, setting it up, and then running the lint script?
> 
> Once I get the lint error resolved, then this PR will be ready to merge.

Hey @dhurlburtusa, we will handle running formatting. 

This is something we work on, to make it easier for contributors - specially for documentation changes when you don't really clone repository.

But in the meantime, you can leave it to us to handle prettier.

**Comment by dhurlburtusa** [comment]
Thanks @pieh.

I see that the code formatter basically undid the change I made in the code examples that were between the `highlight-start` and `highlight-end` "tags". There appears to be a bug with the way highlighted code is rendered.

In the following screen shot from https://www.gatsbyjs.org/tutorial/part-seven/, notice how the closing brace for the `css` prop of the `Link` has had a newline added with no indentation.

tutorial_part_seven-screen_shot

Do you or anyone know how to fix this? Is this is known issue when highlighting chunks of code?

**Comment by pieh** [comment]
Ugh, sorry about that. Let me take a look

**Comment by pieh** [comment]
It definitely is line highlighting bug. I do think we need to keep it as it is right now and fix highlighting, but this should not block other changes in this pull request

**Comment by dhurlburtusa** [comment]
@pieh Agreed.

**Comment by dhurlburtusa** [comment]
@DSchau Ready to merge. Thanks again.

**Comment by DSchau** [comment]
Just wanted to mention how much we appreciate these types of PRs and all the work you've done.

Thank you! 💜

**Comment by dhurlburtusa** [comment]
Thanks @DSchau!

Would you mind elaborating a little on "we appreciate these types of PRs"?

Or do you say that to all the anal-retentive, grammar nazis? 🍩 😊

**Comment by lannonbr** [comment]
@dhurlburtusa I think it's more so that the tiniest of tweaks can really help out in the long run. For instance, if someone is non-native English speaker, correcting the grammar can help out with the understanding of the documentation

**Comment by DSchau** [comment]
@dhurlburtusa we really do love these types of PRs! Grammatical issues and improvements are very much just as important as other types of contributions--even if you think they're nit-picky (I don't think this!).

**Pull request merged**
