### PR TITLE
fix(gatsby-image): fix memory leak and use more appropriate data structures for cache and listeners

### PR DESCRIPTION
**Pull request by alexandernanberg**
- Refactor to use `Set` and `Map` instead of objects and arrays.
- Remove item from `listeners` when element is no longer observed (was probably a memory leak before, since we pushed items to the array with out ever removing them?).
- Add io listener in `componentDidMount` instead of in the refHandler.
- Remove io listener in `componentWillUnmount`.

### CODE REVIEW

**Comment by alexandernanberg** [comment]
Hmm can someone re-run the circleci e2e test? Can't reproduce it locally 🤔

**Comment by pieh** [comment]
I did rerun, but it still happened - didn't code yet, but maybe it's not false negative if it happened 2 times in a row?

**Comment by alexandernanberg** [comment]
Yeah I had forgotten to change the `ref` on the fixed div wrapper, e2e tests can be pretty useful 😬

**Comment by alexandernanberg** [comment]
I might need to give this another proper look after I merged master into this again, there were some issues that I thought the tests would've picked up 🤔

**Comment by wardpeet** [comment]
> I might need to give this another proper look after I merged master into this again, there were some issues that I thought the tests would've picked up 🤔

Could you elaborate which tests? And mabye add them ^^

**Pull request merged**
