### PR TITLE
Improve GQL query error handling

### PR DESCRIPTION
**Pull request by 0x80**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0cdcef88670d73be8c82dffbba1f795c02ca57a3

https://app.netlify.com/sites/using-contentful/deploys/5948cae1cf321c334af81b00

**Comment by KyleAMathews** [comment]
What does an error message look like with this PR?

**Comment by 0x80** [comment]
Instead of only an unhandled reject error pointing to `getGraphQLTag` you'll see something like this

```
ERROR in ./src/pages/index.js
Module build failed: Error: /Users/me/project/src/pages/index.js: BabelPluginGraphQL: GraphQL syntax error in query:

query IndexPage {
  site {
    siteMetadata {
      title
      description
    }
  }
  allWorkJson() {
    edges {
      node {
        title
        slug
        type
        summary
      }
    }
  }
}


message:

Syntax Error GraphQL (8:15) Expected Name, found )
```

**Comment by KyleAMathews** [comment]
Looks great, thanks!

**Pull request merged**
