### PR TITLE
Combine two docs into one and add redirects

### LINKED ISSUE #9259: Combine two docs into one and add redirects
There are two docs that basically cover the same topic.

The goal here is to combine these two docs into one titled: “Add offline support with a Service Worker”
1. https://www.gatsbyjs.org/docs/add-offline-support/
2. https://www.gatsbyjs.org/docs/add-a-service-worker/

Process:
Read both docs thoroughly and make sure the final doc covers all the necessary information to help someone "add offline support with a service worker."

## Motivation

We want to reduce redundancy in the docs, which improves clarity.

### PR DESCRIPTION
**Pull request by yeskunall**
- [x] Combine two docs
- [x] Add redirects

I'm not a 100% sure on how to add redirects ATM. I'll look into this ASAP. In the meantime, feel free to review the changes I've made.

The new combined doc will live under `/docs/add-offline-support-with-a-service-worker`.

💖

<hr />
Closes #9259.

### CODE REVIEW

**Comment by yeskunall** [comment]
@shannonbux can you go over this when you have the chance? Thanks!

**Comment by pieh** [comment]
See https://github.com/gatsbyjs/gatsby/blob/e4ca0189f6c59defca479616efbee912ba32b985/www/gatsby-node.js#L99-L103 for how to add redirects - you would need to add 2 redirects for files you removed to new one

**Comment by yeskunall** [comment]
OK you guys seem to be finding more and more places I need to make changes 😅today evening I'll go over this again and try and make sure the next time someone reviews it, it's 👌🏽 to be merged!


Thanks for the feedback so far Florian and Michal!

**Comment by yeskunall** [comment]
> I think we also want to update/consolidate the sidebar links to the old pages in the sidebar

I thought by combine, we were going to remove the two links and for users still with the old hyperlink, they'd just be redirected to the new doc. What's confusing me is the "to the old pages in the sidebar" part.

In any case, I've pushed an update which I _think_ is what @fk was looking for in the first place.

**Comment by yeskunall** [comment]
@shannonbux if you don't mind waiting, can I quickly resolve the merge conflicts and incorporate the typos and fixes made in the other PRs related to this one? 😅

**Comment by shannonbux** [comment]
You mean to reopen the other PR? Sure, I just did that! No problem!

**Comment by yeskunall** [comment]
@shannonbux whoops 🤭 no I didn't mean that, and I've closed that PR once again (sorry for the trouble)

I just wanted you to wait a few minutes before I could push the changes I just did! Feel free to merge, now that the tests pass!

Thanks 💖

**Comment by fk** [comment]
Late to the merge party, just wanted to add a quick…
Thank you @yeskunall! 🤗

**Pull request merged**
