### PR TITLE
[gatsby] Report an error when layout file is missing

### PR DESCRIPTION
**Pull request by szimek**
This issue adds better error reporting when a layout file is missing. It's related to https://github.com/gatsbyjs/gatsby/issues/3183.

Before:
```
$ gatsby develop
success delete html files from previous builds — 0.011 s
success open and validate gatsby-config.js — 0.006 s
success copy gatsby files — 0.023 s
success onPreBootstrap — 0.007 s
success source and transform nodes — 4.761 s
success building schema — 4.282 s
success createLayouts — 0.017 s
success createPages — 2.744 s
success createPagesStatefully — 0.049 s
success onPreExtractQueries — 0.000 s
success update schema — 6.861 s
success extract queries from components — 0.271 s
success run graphql queries — 57.004 s
error UNHANDLED REJECTION


  TypeError: Cannot read property 'jsonName' of undefined

  - pages-writer.js:79
    [blog]/[gatsby]/dist/internal-plugins/query-runner/pages-writer.js:79:36

  - Array.forEach

  - pages-writer.js:70 _callee$
    [blog]/[gatsby]/dist/internal-plugins/query-runner/pages-writer.js:70:19

  - pages-writer.js:141 writePages
    [blog]/[gatsby]/dist/internal-plugins/query-runner/pages-writer.js:141:17

  - index.js:459 _callee$
    [blog]/[gatsby]/dist/bootstrap/index.js:459:20


error Command failed with exit code 1.
```

After:
```
$ gatsby develop
success delete html files from previous builds — 0.008 s
success open and validate gatsby-config.js — 0.005 s
success copy gatsby files — 0.026 s
success onPreBootstrap — 0.007 s
success source and transform nodes — 0.912 s
success building schema — 3.641 s
success createLayouts — 0.017 s
success createPages — 2.872 s
success createPagesStatefully — 0.015 s
success onPreExtractQueries — 0.001 s
success update schema — 6.851 s
success extract queries from components — 0.265 s
success run graphql queries — 60.000 s
error Failed to write out page data


  Error: Could not find layout 'de'. Check if such file exists in 'src/layouts'.

  - pages-writer.js:46 pages.forEach.p
    [blog]/[gatsby]/dist/internal-plugins/query-runner/pages-writer.js:46:15

  - Array.forEach

  - pages-writer.js:37 writePages
    [blog]/[gatsby]/dist/internal-plugins/query-runner/pages-writer.js:37:9

  - index.js:325 module.exports
    [blog]/[gatsby]/dist/bootstrap/index.js:325:11



error Command failed with exit code 1.
```

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Awesome! Much nicer. Thanks!

**Comment by szimek** [comment]
@KyleAMathews Thanks for merging it so quickly! Have you thought about adding e.g. `husky` + `lint-staged` to automatically run `prettier` (and maybe `eslint`) on commit? This would probably simplify your life a bit ;) I can create a PR for it if you think it's a good idea.

**Comment by KyleAMathews** [comment]
lint-staged breaks `git add -p` which I always use... https://github.com/okonet/lint-staged/issues/62

Prettier recommends another solution which seems more robust! https://prettier.io/docs/en/precommit.html#option-2-pretty-quick-https-githubcom-azz-pretty-quick

Yeah — would love it if you could investigate adding that. It would save me a lot of time 😅

**Comment by szimek** [comment]
I'll check `pretty-quick` then, but I thought it works exactly like `lint-staged`.

**Pull request merged**
