### PR TITLE
feat: add option to configure default image quality

### LINKED ISSUE #4873: Add an option to configure default image quality for ImageSharp queries
Currently, the default quality of ImageSharp-generated images are too low for most of the projects I participate in. I would like to configure a global default for ImageSharp query parameters, because it may become tedious to always specify `quality: 92` in every single image query.

Issue #3837 is related, but it's about specifying a default locale for Moment.js date queries.

### PR DESCRIPTION
**Pull request by DSchau**
Fixes #4873 

Don't love exporting the `__DEFAULT_QUALITY__`, but hey it works and makes it testable, so that's a win.

### CODE REVIEW

**Comment by pieh** [comment]
Nice! People actually really want that, so only nitpicky comment here is to add `defaultQuality` to `resize` transform 
https://github.com/gatsbyjs/gatsby/blob/1b2a4b6ad885dfd26aba20b75a85866f519f5271/packages/gatsby-transformer-sharp/src/extend-node-type.js#L392 and this is good to go

**Comment by KyleAMathews** [comment]
Hmm this still isn't global unfortunately as it only affects transformer-sharp and not remark-images or other plugins using plugin-sharp.

**Comment by pieh** [comment]
> Hmm this still isn't global unfortunately as it only affects transformer-sharp and not remark-images or other plugins using plugin-sharp.

Given that `gatsby-plugin-sharp` isn't really gatsby plugin, but an utility library, to add this there, we would need to store default quality in some global state (either plugin or gatsby managed - `cache` util?). And also remove any graphql defaultValue as it will always override things

**Comment by DSchau** [comment]
Don't know how I missed these comments (maybe an e-mail filter or something) but I'll take a look at improving this soon.

**Pull request closed without merging**
