### PR TITLE
feat(gatsby-plugin-utils): enable tracedsvg

### PR DESCRIPTION
**Pull request by wardpeet**
## Description

Enable traced SVG for image cdn and convert all implementations to our own [@gatsbyjs/potrace](https://github.com/gatsbyjs/node-potrace) with GNU 3 License to be compatible with MIT.

I've updated all potrace usage

### CODE REVIEW

**Review by TylerBarnes — APPROVED** [review]
Very nice! :) What benefit does `@gatsby/potrace` give us over the original package?

**Comment by wahidshafique** [comment]
> Very nice! :) What benefit does `@gatsby/potrace` give us over the original package?

Just pitching here in support of this, our team is blocked heavily since the original package has the viral GPL license. Our clients can't move forward without assurance that all code we use is compliant with their particular license agreements

**Comment by wardpeet** [comment]
>Just pitching here in support of this, our team is blocked heavily since the original package has the viral GPL license. Our clients can't move forward without assurance that all code we use is compliant with their particular license agreements

I upgraded the license to GPL v3 (which is allowed by their License) and GPL v3 is compatible with MIT

**Comment by muescha** [comment]
> I upgraded the license to GPL v3 (which is allowed by their License) and GPL v3 is compatible with MIT

in Readme there is still noted v2:

> The GNU General Public License version 2 (GPLv2).

**Comment by tony** [comment]
> GPL v3 is compatible with MIT

(I assume this means **L**GPLv3, per this thread and https://github.com/gatsbyjs/node-potrace/blob/f182e9e/LICENSE)

Lesser GPL isn't interoperable as it looks. The wording can be muddy as it wasn't written with scripting languages and package systems in mind. 

<details>

<summary>Diagram on license compatibility</summary>

image
image

source: https://en.wikipedia.org/wiki/License_compatibility

</details>

**Pull request merged**
