### PR TITLE
[WIP] Gatsby-remark-flowchart

### PR DESCRIPTION
**Pull request by jbolda**
I thought this would be quick and simple to add, but I am stumped on these errors. I can't figure out the correct scheme to `require` both flowchart.js and raphael. And even when npm installing, it seems to leave one or the other out. I suspect it is an issue with how flowchart.js is setup, but that is as far as I have gotten. (Ignoring the hours of installing and trying different requires.)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Check out the other remark plugins, you need to set the resulting value to raw html not node.value.

**Comment by jbolda** [comment]
@KyleAMathews that's not the issue, I'm having trouble just getting the library imported. That node.value was just placeholder really. I think I'm going to try a different library. The current one does not play nice with our webpack scheme from what I can tell.

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 8bdb2f18308cac1b32ec8e4489f2647a86552635

https://app.netlify.com/sites/using-glamor/deploys/5986a261424ef2292f2da8da

**Comment by jbolda** [comment]
All the libraries out there are pretty old and expect the DOM. This is more involved than I had expected. I might have to partially roll my own d3.js and use their parser to get it to work. If you don't want to leave a PR open for an extended time, we can close it and I can just work on the fork and rePR when really ready.

**Pull request closed without merging**
