### PR TITLE
Added lint rules to warn against using Suspense in SSR

### LINKED ISSUE #14678: [idea] linter to warn against using Suspense in SSR
## Description

build-only bug when using Suspense in gatsby. i used it, got no warning, waited for build, then got this in my netlify logs: https://reactjs.org/docs/error-decoder.html/?invariant=294

### Steps to reproduce

https://github.com/sw-yx/plsdelete-netlify-identity-loop-bug/tree/a487389a2c5f289b2759058394e41dd54d375d82

### Expected result

just warn me in some sort of lint rule that suspense is not allowed in Gatsby pages? i'm sure someone's already written this?

### PR DESCRIPTION
**Pull request by samovertonjr**
## Description

Added lint rules to warn against using Suspense in SSR.

Fixes #14678

### CODE REVIEW

**Comment by samovertonjr** [comment]
I was able to test out the two eslint rules I added.

If you are using `import React from 'react'` `<React.Suspense> </React.Suspense>`
[Example 1](https://share.getcloudapp.com/d5uemdLx)

If you are using `import React, {Suspense} from 'react'` `<Suspense> </Suspense>`
[Example 2](https://share.getcloudapp.com/Jru7K9P5)

**Comment by samovertonjr** [comment]
@sidharthachatterjee how would I go about checking if routes are client side only?

**Comment by blainekasten** [comment]
@samovertonjr I'm not sure that's going to be easily doable without some processing of code.

FWIW, this is only a temporary problem. Suspense will be supported by SSR in the coming releases. I'm not certain this level of warning is necessary.

**Comment by samovertonjr** [comment]
Ok thanks for all the help. I'm going to close this now.

**Pull request closed without merging**
