### PR TITLE
More hot reloading fixes

### PR DESCRIPTION
**Pull request by stevensurgnier**
When upgrading to 1.9.146 recently, I ran into the `Unexpected end of JSON input` race condition as reported in #3094 #3201 and improved in #3218 . 12328d8 further decreases the chance of running into the race condition by writing `pages.json`, `sync-requires.js`, and `async-requires.js` to a temporary file followed by a rename.

Once I was able to get past the `Unexpected end of JSON input`, I ran into the `infinite compile and no dev-404-page.js found` error reported in #3551. I don't fully understand the root cause. The `createPage` call appears to be related to the infinite compile loop. As a bandaid for now, I chose to make the `fs.copy` and `createPage` call a singleton which eliminates the observed failure mode.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Ooo nice! Great ideas.

On the dev-404-page infinite reloop — I haven't seen this but I could imagine this happening. I think what we should do actually is have that plugin implement `createPagesStatefully`. `createPages` is called every time nodes are updated https://github.com/gatsbyjs/gatsby/blob/ecc7e1406009ea4cd1a1f67d437a8e0bf954e348/packages/gatsby/src/bootstrap/page-hot-reloader.js so new pages can be created when your site's data changed. But we only need to create this page once i.e. we handle the "state" of the dev 404 page.

Could you test making that change?

**Comment by stevensurgnier** [comment]
@KyleAMathews `createPagesStatefully` makes a ton of sense in this case. The last commit calls `createPage` when `createPagesStatefully` is called and copies the raw js file if it changes.

**Comment by stevensurgnier** [comment]
I didn't see any errors in the gatsbygram build logs on AppVeyor. The only error message I could find was 

> Build execution time has reached the maximum allowed time for your plan (60 minutes).

I think the PR is ready to go now.

**Comment by KyleAMathews** [comment]
Awesome, looks perfect! Hopefully this solves both your problem + the windows copying issues.

**Pull request merged**
