### PR TITLE
[v2][cache-dir] Don't try to prefetch something that does not exist

### PR DESCRIPTION
**Pull request by sktt**
Fixes this annoying error on development

image

Cheers!

### CODE REVIEW

**Comment by pieh** [comment]
Hey just letting you know that error is already fixed in master ( https://github.com/gatsbyjs/gatsby/pull/7938 ), we just didn't do new release with it yet. But your changes are also reasonable will get those in before doing new release

**Comment by sktt** [comment]
thanks!

**Comment by pieh** [comment]
Hey, no need to close this - I wanted to merge this once test checks are green. At very least dead code removal is valuable :)

**Comment by sktt** [comment]
https://github.com/gatsbyjs/gatsby/pull/7966 ;)

**Pull request closed without merging**
