### PR TITLE
misc(showcase): add Playlist Detective

### PR DESCRIPTION
**Pull request by bobylito**
Hi there :)

## Description

This PR adds Playlist Detective to the site showcase, a website that makes Spotify playlist search easy using Algolia.

### CODE REVIEW

**Comment by laurieontech** [comment]
Cool site! I noticed the README includes yarn instructions instead of gatsby. Is there a reason for that?

**Comment by bobylito** [comment]
Sorry the readme is outdated :/ i usually use the package manager for launching the project tasks. I'll fix that tomorrow.

**Comment by laurieontech** [comment]
Sounds good. Just put a comment here when it's ready and we can get this merged!

Heads up that I just committed to this branch since the GitHub connectivity challenges resulted in a weird merge on this branch.

**Comment by bobylito** [comment]
I updated the readme so that it reflects the current setup :)

**Comment by laurieontech** [comment]
Great! Thanks.

**Comment by bobylito** [comment]
> Great! Thanks.

Thank you 🙏

**Pull request merged**
