### PR TITLE
Include pathPrefix in <Link />

### PR DESCRIPTION
**Pull request by sktt**
When using `{ pathPrefix: 'my-prefix' }` in `gatsby-config.js`, the `<Link />` would not include the pathPrefix by default. 

This pr will always add any `pathPrefix` to the `to` attribute, such that `/about` will get the href `/my-prefix/about`

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbygram* failed.

Built with commit f863d6073f216ef1240c5a950ae4f2efb7a67606

https://app.netlify.com/sites/gatsbygram/deploys/5b6b3a80b3127429b792b84c

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit f863d6073f216ef1240c5a950ae4f2efb7a67606

https://app.netlify.com/sites/gatsbyjs/deploys/5b6b3a7fb3127429b792b84a

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit f863d6073f216ef1240c5a950ae4f2efb7a67606

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6b3a81b3127429b792b852

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit f863d6073f216ef1240c5a950ae4f2efb7a67606

https://app.netlify.com/sites/using-glamor/deploys/5b6b3a82b3127429b792b858

**Comment by KyleAMathews** [comment]
Hey, this actually happens automatically here: https://github.com/gatsbyjs/gatsby/blob/6e46c6a1134b064ea499ed1373c3f6b326a00321/packages/gatsby/cache-dir/production-app.js#L96

What may be tripping you up is that path prefixes aren't used unless you build your site like so: `gatsby build --path-prefix`

https://www.gatsbyjs.org/docs/path-prefix/

**Comment by sktt** [comment]
@KyleAMathews this is not true for latest beta 

`<Link to='/about'>about</Link>` will *not* include the path prefix. I am indeed using `--prefix-paths` which you are referring to. Then I assume the problem lies elsewhere.

**Comment by KyleAMathews** [comment]
Ah hmm ok, lemme check it out.

**Comment by sktt** [comment]
Seems like pathPrefix does not work with other /static/ resources too. should i create an issue instead?

**Comment by sktt** [comment]
issue @ https://github.com/gatsbyjs/gatsby/issues/7163
likely to be related but will split up if they are not.

**Comment by sktt** [comment]
Thank you too, @m-allanson! It's super cool to have a few lines approved! This is definitely motivates me for further contributions on this project! :D

**Pull request merged**
