### PR TITLE
fix(starters): change name, url, and repo url for gatsby-starter-anoun-1-markdown

### PR DESCRIPTION
**Pull request by jaydanurwin**

### CODE REVIEW

**Comment by jaydanurwin** [comment]
Hey @KyleAMathews  if I go to https://www.gatsbyjs.org/starters/?s=material&v=2 in the starter library the name is updated but if I click on the starter it's still the old name, url, and repo and directs to https://www.gatsbyjs.org/starters/ANOUN/gatsby-starter-anoun-1-markdown/

Do we know why the site hasn't rebuilt this page?

**Comment by muescha** [comment]
somehow it is not in the repo. the links in master still to the old one:

https://github.com/gatsbyjs/gatsby/blame/master/docs/starters.yml#L2721

**Comment by muescha** [comment]
maybe the best is to resubmit as new PR your change?

**Comment by jaydanurwin** [comment]
That's strange...ya I'll give it another shot! Thank you!

**Pull request merged**
