### PR TITLE
fix(gatsby-plugin-mdx)

### LINKED ISSUE #37704: MDX tableOfContents field doesn't populate titles correctly when headings contain Markdown formatting
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi y'all! Running into issues using the `tableOfContents` field on MDX nodes when the headings in my .mdx file contain Markdown formatting (bold, italics, inline code, links). The `title` field truncates the full heading text from the body of the page.

### Reproduction Link

https://github.com/meganesu/repro-gatsby-mdx-table-of-contents-with-markdown-formatting

### Steps to Reproduce

1. Start up the dev server
2. Go to `localhost:8000`

### Potential solution

I was able to get the table of contents titles to display correctly by changing `node_modules/gatsby-plugin-mdx/dist/remark-infer-toc-meta.js` ([lines 52-54](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/src/remark-infer-toc-meta.ts#L52-L54)) to this:

```js
if (item.type === `text` || item.type === `inlineCode`) {
  if (typedCurrent.title) {
    typedCurrent.title = typedCurrent.title + item.value;
  }
  else {
    typedCurrent.title = item.value;
  }
}
```

### Expected Result

The Table of Contents should show the full heading text for each `h2` in the body of the page.

Screenshot of the index page. The heading titles in the table of contents match the headings in the body of the page.

### Actual Result

The Table of Contents shows truncated versions of the headings for each `h2` in the body of the page.

Screenshot of the index page. The heading titles in the table of contents don't match the headings in the body of the page.

### Environment

```shell
System:
    OS: macOS 11.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 109.0.1
    Safari: 14.0.3
  npmPackages:
    gatsby: ^5.7.0 => 5.7.0 
    gatsby-plugin-mdx: ^5.7.0 => 5.7.0 
    gatsby-source-filesystem: ^5.7.0 => 5.7.0 
  npmGlobalPackages:
    gatsby-cli: 3.6.0
```

### Config Flags

_No response_

### PR DESCRIPTION
**Pull request by predatorprasad**
## Description

I have fixed the code in 52-54 with the potential solution.

## Related Issues

Fixes #37704

### CODE REVIEW

**Comment by LekoArts** [comment]
Hi, thanks for the PR!

Please read my comment on the issue: https://github.com/gatsbyjs/gatsby/issues/37704#issuecomment-1445879407

You'll need to add a test here: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/src/__tests__/remark-infer-toc-meta.ts

And then pushing your changes be sure to run the postcommit linting hooks

**Comment by predatorprasad** [comment]
ok, I will figure it out

**Comment by predatorprasad** [comment]
@LekoArts can you help me, cause I am not able to figure out how to write tests. I am relatively new to OSS 😅

**Comment by LekoArts** [comment]
1. Clone your fork locally and install dependencies by running `yarn` inside the monorepo as shown in https://www.gatsbyjs.com/contributing/code-contributions/#fork-clone-and-branch-the-repository
2. Go to https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/src/__tests__/remark-infer-toc-meta.ts and add new headlines to https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/src/__tests__/remark-infer-toc-meta.ts#L7-L13 to test the new behavior
3. Update the test to validate that new behavior
4. Run `yarn jest packages/gatsby-plugin-mdx/src/__tests__/remark-infer-toc-meta.ts` to test that the test passes locally as shown in https://www.gatsbyjs.com/contributing/code-contributions/#add-tests

**Comment by predatorprasad** [comment]
thanks for help

**Comment by LekoArts** [comment]
You won’t need to run `yarn run bootstrap` for your PR so feel free to skip that :)

**Pull request closed without merging**
