### PR TITLE
docs(gatsby-source-contentful): clean up changelog

### PR DESCRIPTION
**Pull request by stefanjudis**
Clean up change log for gatsby-source-contentful. Superseeds https://github.com/gatsbyjs/gatsby/pull/27999. :)

### CODE REVIEW

**Review by vladar — DISMISSED** [review]
Thank you! 💜

**Comment by stefanjudis** [comment]
Sweet! Thanks for the swift handling. My job is done then. 👋  :D

**Comment by vladar** [comment]
@stefanjudis Something is not right with linting but I don't see what. Can you please run `yarn format:other` in the monorepo root. It should fix formatting problems.

**Comment by stefanjudis** [comment]
Hah, I hoped I could get away without cloning. Will do. Give me a few minutes. :)

**Comment by vladar** [comment]
Did you run `yarn format:other`? The new formatting seems to be using a set of prettier/eslint rules that is incompatible with Gatsby.

**Comment by stefanjudis** [comment]
@vladar Sorry about that. :/ I tried it prettier.com first for the lazy route (didn't work obviously). Cloning and installing right now. :)

**Comment by stefanjudis** [comment]
@vladar That should be it now, from my machine and after `yarn format:other`. :)

**Review by vladar — APPROVED** [review]

**Pull request merged**
