### PR TITLE
feat(gatsby-remark-copy-linked-files): allow communities plugins to work

### PR DESCRIPTION
**Pull request by cedricdelpoux**
## Description 

Hi, I'm the creator of [gatsby-source-google-docs](https://github.com/cedricdelpoux/gatsby-source-google-docs).

The make it fast, the plugin transform **Google Docs** Documents into **Markdown** and is fully compatible with **Gatsby Remark** ecosystem. It downloads all **Google** images using `createRemoteFileNode` from **gatsby-source-filesystem** and replace urls by relative paths to make **gatsby-remark-images** works. 

Nodes are created using:
```
createNode({
  internal: {
    type: "GoogleDocs",
    mediaType: "text/markdown",
    content: markdown,
    contentDigest: createContentDigest(markdown),
  },
  dir: process.cwd(), // To make gatsby-remark-images works
})
```

Users can **add GIF** to **Google Docs** documents and I looked for a way to handle them using remark.

Following [GIF is not recognized in gatsby-remark-images](https://github.com/gatsbyjs/gatsby/issues/7317), I tried [gatsby-remark-copy-linked-files](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-remark-copy-linked-files) like [KyleAMathews said](https://github.com/gatsbyjs/gatsby/issues/7317#issuecomment-412984851) but because of two conditions, the plugin works only with [gatsby-source-filesystem](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem).

My suggestion is to test if `getNode(markdownNode.parent).dir` exist instead of `getNode(markdownNode.parent).internal.type === "File"` because it is less restrictive and more compatible with communities plugins.

Thank you 

## Related Issues

https://github.com/gatsbyjs/gatsby/issues/7317

### CODE REVIEW

**Comment by KyleAMathews** [comment]
How about we just add direct support for gatsby-source-google-docs? The logic you're modifying there is directly for working with File nodes. Instead of trying to make your markdown nodes behave like local files, just add a new if clause that says if the parent is a google doc, here's how you can get the file.

How's that sound?

**Comment by cedricdelpoux** [comment]
It sounds good to me! 

If it's the good way to go, after this PR I can also make the same update to "gatsby-remark-images" plugin.

**Comment by KyleAMathews** [comment]
You also don't want to use `process.cwd()` inside plugins as people don't have to run Gatsby from the root of their site.

I assume you're putting in the absolute path to the File created by `createRemoteFileNode`? If so, just return that.

**Comment by cedricdelpoux** [comment]
After downloading remote images and replace urls by local files relative path, the markdown contains relative paths to the "cache" folder used by `createRemoteFileNode` from **gatsby-source-filesystem**.

```markdown
[](.cache/caches/gatsby-source-google-docs/cc7e93b6c699fda40449960dc2d6913f/google-docs-image-6a460490-b082-501f-8dee-b0b0cc9a6d83.png )
```

To make [gatsby-source-google-docs](https://github.com/cedricdelpoux/gatsby-source-google-docs) compatible with **gatsby-remark-images**, I need to fill the "dir" data of my **Google Docs** nodes ([Because gatsby-remark-images needs it](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/index.js#L134)).

Maybe it's no the good way to go. Do you know an other plugin using this behavior that can inspire me?

I'm not sure to understand what you mean. I found `process.cwd()` worked pretty well for this case. You are right it can break if someone build the site from a other folder but I did not get any issue about this.

**Comment by cedricdelpoux** [comment]
what should I do with the 2 failing tests? I don't have access to **circleci**

**Comment by cedricdelpoux** [comment]
Closing it after 2 years without any activity

**Pull request closed without merging**
