### PR TITLE
docs-stub-redirct

### PR DESCRIPTION
**Pull request by bball07**
## Description

This is a redirect for the stub on gatsby-source-filesystem Programmatic Import.

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks @bball07! I'm going to wait to merge this until you push the commit for removing the stub file as we discussed earlier :)

**Comment by bball07** [comment]
Hi @laurieontech the stub file has been deleted :)

**Comment by laurieontech** [comment]
They really should be in the same PR so that we can push the changes at the same time. Can you make both changes in either this or the other PR and close one?

**Comment by bball07** [comment]
@laurieontech made both changes on "delete stub file #21471" I will delete this one

**Pull request closed without merging**
