### PR TITLE
chore(starters): add gatsby-starter-i18n-bulma

### PR DESCRIPTION
**Pull request by kalwalt**
## Description
Proposed starter https://github.com/kalwalt/gatsby-starter-i18n-bulma to add to the starters list

### Documentation
The main feature of this starter is the slug switcher for multilanguage. Basically with this system you can have any slug that you want. With i18n plugin you can not change the slug, with it instead let you have a slug in a language, example:
```
in English:

 /en/about/

in Italian:

/it/presentazione/
```
The starter is also based on **Bulma**, **Netlify CMS** and many more features...

## Related Issues
See https://github.com/gatsbyjs/gatsby/issues/14250

### CODE REVIEW

**Comment by kalwalt** [comment]
I don't understand what is to be changed followed this result https://github.com/gatsbyjs/gatsby/runs/490472157 i think i added the tags included in **categories.yml** but maybe i'am wrong...

I also upgraded gatsby-plugin-sharp gatsby-transformer-sharp gatsby-transformer-sharp to the latest, because the fails in CircleCi [build-test](https://github.com/gatsbyjs/gatsby/pull/22014/checks?check_run_id=490472082)

**Comment by laurieontech** [comment]
Thanks for the PR! It looks like "Media" and "Freelance" are the tags causing this to fail.

**Comment by kalwalt** [comment]
> Thanks for the PR! It looks like "Media" and "Freelance" are the tags causing this to fail.

Thanks to you @laurieontech ! ok i will remove them. Can you tell me something more about the other errors? I upgraded some pkgs but i think it's needed also to fix other dependencies. It's not included yarn.lock or package-lock.json in the starter so maybe that is the problem...

**Comment by kalwalt** [comment]
i found that there is an issue with decompress https://github.com/gatsbyjs/gatsby/issues/21791 the fix is on the way https://github.com/kevva/decompress/pull/73 waiting for the fix.

**Comment by kalwalt** [comment]
WOW! Thank you @gillkyle @laurieontech very happy for this!

> The validation tests failing due to the npm audit will fail for other starts like yours that use similar plugins. From what I understand they actually don't pose a real vulnerability because what's shipped to the browser won't have the vulnerability anyway so I'm going to merge this.
 yes, i saw the discussion will see when it will be solved...

**Pull request merged**
