### PR TITLE
fix(examples): GraphQL reference codesandbox issue

### PR DESCRIPTION
**Pull request by LekoArts**
Codesandbox apparently fails on that

image

### CODE REVIEW

**Comment by pieh** [comment]
> Actually... this should be fixed by [a4621c6](https://github.com/gatsbyjs/gatsby/commit/a4621c6f578a4bb5d43f4d20ee765042e1b72d46) and the PR #10220 correct?

Yeah, I hit this when I was using blog starter after deleting `.eslintrc` file there, so I added that to common eslint config

**Comment by LekoArts** [comment]
Codesandbox doesn't have access to that file (I think)

**Comment by pieh** [comment]
It wasn't published yet I think

**Comment by LekoArts** [comment]
Ah, I see. However I think Codesandbox will only restart the dev server (instance) if something changed on the repo. So if we don't change the PATH_PREFIX we'd need to change something else to trigger a new run.

**Comment by DSchau** [comment]
> However I think Codesandbox will only restart the dev server (instance) if something changed on the repo

We'd need to upgrade to the version of gatsby that contains this change--so maybe we do that in this PR?

**Comment by LekoArts** [comment]
Didn't work out as expected, `.83` didn't have the fix in it.

**Comment by DSchau** [comment]
@LekoArts I'm not sure the change has been published yet.

The `eslint-config.js` does _not_ contain the additional global.

**Comment by pieh** [comment]
I just published .84 with the change

**Pull request merged**
