### PR TITLE
chore(examples): Update using-drupal to work with Drupal 8.7

### PR DESCRIPTION
**Pull request by JohnAlbin**
## Description

The `Using Drupal` demo is hard-coded to use the JSON:API endpoints at `https://live-contentacms.pantheonsite.io/api`. That site is using ~~Drupal 8.6.x or earlier~~ *a Drupal installation called Contenta* and not the latest Drupal 8.7.0 series which has the new, stable JSON:API module.

When using the `examples/using-drupal` files and editing the Gatsby config to use a Drupal 8.7.x site, the files report multiple errors because the endpoint structure ~~wasn't stable with Drupal 8.6.x and has changed now that 8.7.0 has been released~~ *from the Contenta endpoint doesn't match vanilla Drupal 8.7's endpoint structure*.

## Related Issues

#15693

### CODE REVIEW

**Comment by JohnAlbin** [comment]
The code in this PR works great if you have a Drupal 8.7.x site.

Unfortunately, the Drupal site that is configured in `examples/using-drupal/gatsby-config.js` (`https://live-contentacms.pantheonsite.io/`) is a Drupal 8.6.x (or earlier) site. So this PR can't be merged until that website is updated or replaced.

**Comment by wardpeet** [comment]
I'm wondering if we shouldn't be backwards compatible? can't we make it so it works for "any" drupal version > 8?

**Comment by pieh** [comment]
@wardpeet This is dependent on Drupal version. I'm in favour of doing this actually - recently I had to do exactly same thing when testing one of Drupal PRs against new Drupal instance.

What we need to do is either upgrade `https://live-contentacms.pantheonsite.io/` or create new one

**Comment by JohnAlbin** [comment]
> I'm wondering if we shouldn't be backwards compatible

Unfortunately, it's not just a matter of using different field names for Drupal 8.6 vs Drupal 8.7. There is also a different level of nesting when querying for images.

IMO, since the Drupal 8.7 is the first version of Drupal where the JSON:API module is NO LONGER experimental, we should forget about demonstrating the experimental 8.6 version.

> What we need to do is either upgrade https://live-contentacms.pantheonsite.io/ or create new one

Upgrading makes the most sense to me. Let me see if I can get the owners of that site to participate in this issue.

**Comment by wardpeet** [comment]
Thanks for the explanation! 🎉 Let see if we can get it upgraded

**Comment by eojthebrave** [comment]
> Upgrading makes the most sense to me. Let me see if I can get the owners of that site to participate in this issue.

I also commented in #15693 but I think that instead of upgrading this site, which appears to be based on [Contenta](http://www.contentacms.org/) (a Drupal distribution) we should switch to using Drupal core + the Umami demo profile.

**Comment by eojthebrave** [comment]
I believe things like this:

```js
--  if (node.internal.type === `recipes`) {
++  if (node.internal.type === `node__recipe`) {
```

Are because the demo site uses Contenta, not because of Drupal 8.6 vs Drupal 8.7. The Contenta distribution ships with a bunch of additional configuration that does things like map the default `/jsonapi/node/recipe` resource endpoint to `/api/recipes` and change the resource name from `node--recipe` to `recipe` using the Drupal [JSON:API Extras module](https://drupal.org/project/jsonapi_extras). None of which is required for getting Drupal + Gatsby to work together.

**Comment by JohnAlbin** [comment]
> we should switch to using Drupal core + the Umami demo profile.

Yep, this makes sense.

FYI, this PR is to get the code to work with vanilla Drupal 8.7 (w/ Drupal core's umami profile).

I'm now working on getting a public website donated to host a vanilla D8.7+Umami site. I'll report back next week.

**Comment by DSchau** [comment]
@JohnAlbin awesome! Please let us know when you have something more to share -- I'd love to be able to edit content in a version of this so that we can [test it out with Gatsby Preview](https://gatsbyjs.com/preview/) as well!

**Comment by JohnAlbin** [comment]
> I'll report back next week.

Jetlag is a bitch. (I flew 12 timezones into the future last week.)

I'm working with the Amazee.io hosting company to setup a vanilla Drupal 8.7 server to work with this PR. It should be done this week — fingers crossed.

**Comment by JohnAlbin** [comment]
Ok! The new website is up and running at https://using-drupal.amazee.io and the JSON:API endpoint is available at https://using-drupal.amazee.io/jsonapi

So I've updated this PR to use that endpoint and confirmed that the Gatsby build still works. This PR is ready for full review.

**Comment by JohnAlbin** [comment]
> Can you share credentials with me to be able to test this on Gatsby Preview?

I'm not sure what website permissions you need to get this to work with Preview.

If it helps, the complete source code for the using-drupal.amazee.io site and a copy of its content in a sqlite database is available publicly. I've written instructions on how to get it running pretty easily. https://github.com/AmazeeLabs/using-drupal

**Comment by sidharthachatterjee** [comment]
@JohnAlbin I meant to ask for the credentials to login to the Drupal admin via https://using-drupal.amazee.io/en/user/login

**Comment by markconroy** [comment]
Hi folks,

Just to mention - as one of the maintainers of the Drupal Umami Profile - we are hoping to move from using image fields in the content types to using media (image) fields. We're hoping to do this sooner rather than later, but need to wait for media browser type stuff to be stable first.

Just thought I'd drop that here, when I noticed mention of nesting/fields for getting images mentioned above.

Thanks for all the great work you are doing on this.

**Comment by sidharthachatterjee** [comment]
Just had a chat with @DSchau and he's now using https://github.com/gatsby-inc/gatsby-example-drupal to test Preview so that removes the need to test this with it. Let's ship this!

**Pull request merged**
