### PR TITLE
fix(gatsby): Add `allowNamespace` option to ESLint config

### PR DESCRIPTION
**Pull request by LekoArts**
## Description

Add the `allowNamespace` option to our default config so that Theme UI isn't warning anymore.
Thanks @Kev-Y-Huang for the upstream PR: https://github.com/yannickcr/eslint-plugin-react/pull/2917

## Related Issues

Fixes https://github.com/gatsbyjs/gatsby/issues/29287
Fixes https://github.com/gatsbyjs/gatsby/issues/24327

[ch26618]

### CODE REVIEW

**Review by pieh — DISMISSED** [review]

**Comment by LekoArts** [comment]
@pieh weird, failing tests 🤔

**Comment by pieh** [comment]
```
Error Generating development JavaScript bundle failed

BaseConfig:
	Configuration for rule "react/jsx-pascal-case" is invalid:
	Value {"allowNamespace":true} should NOT have additional properties.

failed Building development bundle - 17.982s
ERROR in BaseConfig:
	Configuration for rule "react/jsx-pascal-case" is invalid:
	Value {"allowNamespace":true} should NOT have additional properties.
```

**Comment by pieh** [comment]
Seems like referenced PR wasn't released yet :(

**Comment by LekoArts** [comment]
Closing for now until this is released.

**Comment by Kev-Y-Huang** [comment]
@LekoArts just wanted flag that eslint-plugin-react just had a release where the new feature was added

**Review by ascorbic — APPROVED** [review]

**Pull request merged**
