### PR TITLE
chore(docs): Adds Dgraph's GraphQL API example link

### PR DESCRIPTION
**Pull request by vardhanapoorv**
Simple blog app with Gatsby and Dgraph. Adds the example to "Further reading" section.

### CODE REVIEW

**Comment by laurieontech** [comment]
Thank you for the PR! However, I'm opting not to merge it at this time. The other links in that section are owned by Gatsby team members and other technologies Gatsby integrates with. 
However, this looks like a great plugin and we're glad to have it in the ecosystem!

**Comment by vardhanapoorv** [comment]
@laurieontech thanks for the swift response. I don't quite understand since this link points to the repo containing the app build using Gatsby and Dgraph's GraphQL API. Since I just saw that other links in the section are by Gatsby team members or official repo of the organization they integrate with, didn't know about it before. If I move this project to an official repo under the Dgraph organization that will work right?

**Comment by laurieontech** [comment]
If you're looking to share the project I'd suggest doing so as part of the [site showcase](https://www.gatsbyjs.org/contributing/site-showcase-submissions/).

**Comment by vardhanapoorv** [comment]
@laurieontech  No, I mean the other apps links that are present in that section like Hasura, AWS AppSync etc, are under the organization repo. Since I work at Dgraph I can do the same and move it from my personal repo to the official one. That should work, right?

**Pull request closed without merging**
