### PR TITLE
fix(gatsby-source-mongodb): sanitize type of nodes to only contain alphanumeric chars and underscores

### PR DESCRIPTION
**Pull request by michalczaplinski**
Fixes: #7218 

(copied from issue)
This is due to the fact that `graphql` requires the node's `name` to match the `/^[_a-zA-Z][_a-zA-Z0-9]*$/` regex: 

https://github.com/graphql/graphql-js/blob/5fe39262a308df944a87cc85b225228e7556aaa4/src/utilities/assertValidName.js#L14

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit f74ff400ab19cb1c09a327f06a7c8066782aa82b

https://app.netlify.com/sites/gatsbyjs/deploys/5b6ed3e973f2cf410662584c

**Comment by jquense** [comment]
I believe that gatsby exports a utility for doing this, we should use instead of the inline one for consistency

**Comment by michalczaplinski** [comment]
@jquense could you point me to the right place in gatsby repo? 
I cannot see anything relevant in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/

**Comment by jquense** [comment]
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/create-key.js

**Comment by pieh** [comment]
Also following up on it - perhaps we should sanitize type (and not only field names) in core so plugins don't need to care about it?

**Comment by pieh** [comment]
Just to follow up on my previous comment - this could be done here when creating nodes - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/actions.js#L506 - use `createKey` linked above: `node.internal.type = createKey(node.internal.type)`

**Pull request merged**
