### PR TITLE
[www] add search input to home page

### PR DESCRIPTION
**Pull request by m-allanson**
This is here to start a discussion on adding search form onto the homepage. 

I've removed the Discord and Twitter logos and added some inverse styling for the search icon.

@fk and @KyleAMathews what do you think, is this approach worth pursuing or should we try something else? The main downsides I can see are:

- we've lost those two icons
- the expanded search input overlaps the purple diagonals at some widths

Refs #3603 and particularly @fk's comment at https://github.com/gatsbyjs/gatsby/issues/3097#issuecomment-349389921 

(This will probably need to be revisited once #3639 is in)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
I'm not super concerned about losing the icons. We should double-check analytics but I'd guess not a ton of people click on those links. Search feels like it's more important?

Also there's the community page with links to both of those.

**Comment by KyleAMathews** [comment]
Looking good though! https://deploy-preview-3662--gatsbyjs.netlify.com/

Maybe though the input background should be more muted when not focused? It feels overly contrasty / attention-grabbing right now.

**Comment by m-allanson** [comment]
> Maybe though the input background should be more muted when not focused? It feels overly contrasty / attention-grabbing right now.

Yeah it's definitely a bit bright atm, I'll take a look.

**Comment by m-allanson** [comment]
Oh one of the AppVeyor builds failed.. does it just need a restart?

**Comment by KyleAMathews** [comment]
Appveyor is pretty unreliable. Looking at the build, there's what looks like an install error 🤷‍♂️

**Comment by m-allanson** [comment]
@KyleAMathews Alright, a few updates here:

- prevent search input from overlapping bg stripes (home page)
- mute colours of the unfocussed, expanded search input (home page)
- add Twitter and Discord icons back in when there's enough space
- rebase to include @fk's recent colour updates

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 42c20b218deb1b607e6447573a6644c3266439cf

https://app.netlify.com/sites/using-glamor/deploys/5a738ac8a6188f5aecbd0a0e

**Comment by KyleAMathews** [comment]
@m-allanson it looks like the input's background is still white when unfocused?

**Comment by m-allanson** [comment]
@KyleAMathews it should look like this: 

screen shot 2018-02-02 at 20 51 52

I've just tried to trigger a rebuild on netlify.

**Comment by KyleAMathews** [comment]
Ugh ok sorry — yeah Netlify builds were broken because of the bad publish.

**Comment by KyleAMathews** [comment]
Looks great! Thanks for taking this on!

**Comment by fk** [comment]
❤️  🙏  @m-allanson!

Special thanks for dealing with my messy color palette changes! 😉

**Comment by m-allanson** [comment]
🎉 🎉

**Pull request merged**
