### PR TITLE
Field inferring changes and cleanup

### LINKED ISSUE #3556: Add date formatting query options to lists of date strings in YAML in addition to scalars
## Description

The `gatsby-transformer-yaml` plugin has a great behavior for parsing date strings and exposing them as rich Dates with the ability to format them through GraphQL query parameters! The ability to write simple, human-readable date strings like `2018-01-01` in YAML and have a rich date to query against for things like days of the week, abbreviations, etc., is excellent.

I was disappointed to discover that this feature is limited to scalars. Creating a list of date strings exposes no ability to format all of them through the query.

My workaround is to add another object layer, e.g. a list of objects that have a single property called date, but it would be nice to not have to do that.

### Environment

Gatsby version: 1.9.151
Node.js version: 8.9
Operating System: macOS Siera 10.12.6

#### Data

```yaml
# events.yaml
# assume configured for processing with gatsby-source-filesystem

- name: Greatest show on earth
  dates:
    - 2018-01-01
    - 2018-01-02
    - 2018-01-03
- name: Average show
  dates:
    - 2018-01-04
    - 2018-01-05
    - 2018-01-06
```

#### Query

```graphql
query EventsQuery {
  allEventsYaml {
    edges {
      node {
        name
        dates(formatString: "ddd MMMM Do, YYYY")
      }
    }
  }
}
```

#### Desired result

```json
{
  "data": {
    "allEventsYaml": {
      "edges" : [
        {
          "node": {
            "name": "Greatest show on earth",
            "dates": [
              "Monday January 1st, 2018",
              "Tuesday January 2nd, 2018",
              "Wednesday January 3rd, 2018",
            ],
          },
        },
        {
          "node": {
            "name": "Average show",
            "dates": [
              "Thursday January 4th, 2018",
              "Friday January 5th, 2018",
              "Saturday January 6th, 2018",
            ]
          }
        }
      ]
    }
  }
}
```

#### Current result

```json
{
  "errors": [
    {
      "message": "Unknown argument \"formatString\" on field \"dates\" of type \"EventsYaml\".",
      "locations": [
        {
          "line": 30,
          "column": 23
        }
      ]
    }
  ]
}

### PR DESCRIPTION
**Pull request by pieh**
1. Remove special case for inferring array of objects - it seems to not be needed and removing not needed special cases improves code readability.
2. Currently when inferring arrays gatsby takes just type of array items discarding field args and resolve function. Adding them back allows to use date formatting function in array of dates (so this one closes #3556)
3. Code organization - move date and file related code to separate file to make type inferring file more readable.
4. Add tests for linking fields to file nodes

Probably more changes will come soon.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
PR looks great! Much cleaner and great to fix the date args on an array bug while refactoring :-)

Looks like there's a test failure that needs cleaned up still.

**Comment by pieh** [comment]
I forgot to add this is WIP / RFC. 

Didn't get jest to work yesterday to run tests but I will try to fix that :)

**Comment by KyleAMathews** [comment]
This ready for another review?

**Comment by pieh** [comment]
I'm pretty happy about how it looks but maybe wait few days. 

I use this branch as "starting point" for my work on schema definition thing ( https://github.com/gatsbyjs/gatsby/compare/master...pieh:schema_wip ) and I might change few things along the way and I don't want introduce another changes later and make reviewing schema definition branch harder than it has to be. 

Also I want to expand on some stuff I did there in commit messages / code comments, but I was changing code often and didn't want to waste time on writing explanations that were later obsolete.

**Comment by KyleAMathews** [comment]
👍 sounds great!

**Comment by KyleAMathews** [comment]
PR looks great! I assume it's ready to go? Much cleaner and good foundation work for adding additional custom types (e.g. was chatting with someone about adding http://numeraljs.com/ for adding support for formatting/manipulation of numbers similar to what we do for dates). We could do something similar for strings.

**Comment by pieh** [comment]
I think this can go in. I can do incremental changes and refactoring which now I think is better approach than trying to squeeze everything in 1 PR (easier to review things).

I plan to add more stuff to available fields. Mainly was thinking about expanding filter options on date and number fields - adding `gt`, `gte`, `lt`, `lte` operators (to allow after/before/between dates filters). Adding number formatting seem like good to add to my to-do list.

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
