### PR TITLE
Added Chiedo Labs site to the list of sites

### PR DESCRIPTION
**Pull request by chiedo**
Moved my site from WordPress to Gatsby. :)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Pretty!

How'd the conversion go? Did you just dump the data into markdown and then rebuild the views? A writeup would be awesome if you find the time.

**Comment by chiedo** [comment]
Thanks! :)

It actually went pretty well. I exported all my posts and custom post types using the WordPress exporter then used [this tool](https://github.com/dreikanter/wp2md) to convert them all to markdown. 

Then I rewrote the WordPress page templates as React Templates and moved my data over with some manual intervention to fix some issues with shortcodes and code samples I had. I'll plan to write up a blog post in the next few weeks or so. I will need to figure out a way to make it more general so it applies to more people maybe I'll start with one of the starter WordPress templates.

Thanks again for the awesome library!

**Comment by KyleAMathews** [comment]
Cool! Good to hear the conversion went pretty smoothly — looking forward to the post!

**Comment by ivanoats** [comment]
Thanks for writing about this @chiedo - really looking forward to the blog post.  One thing that would be interesting, that I have been looking at in other themes, is the lines of code in the project. I use [`cloc`](https://www.google.com/search?client=safari&rls=en&q=cloc&ie=UTF-8&oe=UTF-8) to measure the LOC in WP themes and my Gatsby project.

**Comment by chiedo** [comment]
I'm curious now @ivanoats, I'll add that to the post :)

**Comment by chiedo** [comment]
Hey fellas,

This is what I've gotten so far:
https://labs.chie.do/moving-your-wordpress-blog-to-gatsby/

Anything in particular you want to see other than what's included? I always struggle with writing tutorials on these kinds of things without getting to the point where I just rewrote the whole codebase in the blog post. So I'm trying to combat that urge here. As a result, I'm not sure if this is too broad or just right.

I didn't end up running the cloc tests @ivanoats mainly due to time constraints lol. I looked at the cloc docs and ran out of time.

**Comment by ivanoats** [comment]
Nice post! Great to have articles like this out there mentioning Gatsby. 

If you're curious still, it's easy to run `cloc $(git ls-files)` if your WP theme is in its own git repo, and then run it on Gatsby.

**Comment by chiedo** [comment]
Thanks fellas!

Also thanks @ivanoats :) the results are below but don't know if they tell us anything considering that I'm committing my public directory to the repo which practically duplicates the lines of code and also because all the pages are hard coded into the repo whereas the WordPress theme doesn't have the content in the repo since WordPress uses a Database.

**Gatsby**
```
github.com/AlDanial/cloc v 1.70  T=0.72 s (294.2 files/s, 24041.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
HTML                            92            181              0           5497
Markdown                        80           1169              0           4593
SASS                             7            232             10           2108
JavaScript                      26            192             77           1674
CSS                              5            212            292            988
XML                              1              0              0             89
JSON                             1              0              0             55
YAML                             1              0              4             35
-------------------------------------------------------------------------------
SUM:                           213           1986            383          15039
-------------------------------------------------------------------------------
```

**WordPress**
```
github.com/AlDanial/cloc v 1.70  T=0.18 s (264.1 files/s, 57738.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                              2           1088            259           4090
SASS                             7            223             10           2058
PHP                             30            178            110           2031
JavaScript                       9             54             54            339
-------------------------------------------------------------------------------
SUM:                            48           1543            433           8518
-------------------------------------------------------------------------------
```

**Comment by jlengstorf** [comment]
Hiya @chiedo! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by jlengstorf** [comment]
Hiya @chiedo! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by chiedo** [comment]
YOU GUYS ROCK @jlengstorf

**Pull request merged**
