### PR TITLE
Modifications to support netlify-cms v2

### PR DESCRIPTION
**Pull request by steverandy**
Got the following error when I tried to upgrade netlify-cms to v2:
```
ERROR  Failed to compile with 1 errors                                                                      

This dependency was not found:

* netlify-cms/dist/cms.css in ./node_modules/gatsby-plugin-netlify-cms/cms.js
```

This PR removes the import line and bump netlify-cms version.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit c19267d517700cf8f8dc8820b758f6ea4d397c7b

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5abd2182d3f15b36a05fdb

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit c19267d517700cf8f8dc8820b758f6ea4d397c7b

https://app.netlify.com/sites/gatsbyjs/deploys/5b5abd2082d3f15b36a05fd3

**Comment by m-allanson** [comment]
Thanks @steverandy! Are there any other changes required for netlify-cms v2?

**Comment by steverandy** [comment]
@m-allanson that's all that I'm currently aware of. With these changes I should be able to run develop and will test more.

**Comment by erquhart** [comment]
This is all that's necessary, thanks @steverandy!

**Comment by steverandy** [comment]
Close this ad PR https://github.com/gatsbyjs/gatsby/pull/6871 already fixes the issue.

**Pull request closed without merging**
