### PR TITLE
gatsby-plugin-robots-txt

### PR DESCRIPTION
**Pull request by mdreizin**
`lerna` has very useful `import` feature which allows to migrate any external packages with their `git`-history and I used it.

In addition, I have applied related code changes to fit the code style.

### CODE REVIEW

**Comment by m-allanson** [comment]
I didn't know about that `import` feature, it sounds useful! 

Note that this PR is pending outcome of the discussion in #6345

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit af8db51c7cff6cc9eea116d749aff336ccd7bb36

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5626da82d3f156b92087f4

**Comment by wdavidw** [comment]
Since `env` default to "development" and disallow indexing, it seems a bit dangerous, no?

**Comment by m-allanson** [comment]
Hey @mdreizin thanks for opening this PR 👍 - it's great to see high quality plugins like this, especially with good docs and tests. However, I'm going to close this PR based on my comment in https://github.com/gatsbyjs/gatsby/issues/6345#issuecomment-409553436

**Pull request closed without merging**
