### PR TITLE
feat(gatsby-core-utils): Add isHttpUrl function

### PR DESCRIPTION
**Pull request by xSyki**
## Description

Adding the isHttpUrl function to remove the problematic valid-url package.

The tests fail because a new version of gatsby-core-utils needs to be released that will have the feature I added. You will also need to update the package in gatsby-source-filesystem and gatsby-source-wordpress.

Unfortunately, url validation is not identical to valid-url. Two example urls that will pass with our function that would not pass in isWebUri: `https:www.gatsbyjs.com`, `http:www.gatsbyjs.com`.

I don't quite understand what this file is https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/__tests__/fixtures/kitchen-sink.json and why there is a valid-url.

### Tests

Unit tests were added

## Related Issues

Fixes https://github.com/gatsbyjs/gatsby/issues/37722

### CODE REVIEW

**Comment by LekoArts** [comment]
Hi, thanks for the PR!

The tests are currently not running because of:

> yarn.lock is dirty. Please run 'yarn' in root of monorepo and commit changes to 'yarn.lock' file.

So you can get our CI running by running `yarn` in the root of the monorepo. This way the lock file will be updated.

> I don't quite understand what this file is [master/packages/gatsby/src/schema/__tests__/fixtures/kitchen-sink.json](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/schema/__tests__/fixtures/kitchen-sink.json?rgh-link-date=2023-03-06T17%3A10%3A09Z) and why there is a valid-url.

It was a snapshot of the `package.json` of the files you removed valid-url from and is used as a fixture for a test. So I think you don't need to worry about this as it's just used for tests.

**Comment by xSyki** [comment]
@LekoArts yarn.lock fixed

**Comment by LekoArts** [comment]
> Unfortunately, url validation is not identical to valid-url. Two example urls that will pass with our function that would not pass in isWebUri: https:www.gatsbyjs.com, http:www.gatsbyjs.com.

We tested it a bit, this should be fine as the libraries we use to fetch files handles that 👍

**Comment by TylerBarnes** [comment]
@LekoArts it does seem to be causing it to fail though I'm not sure why. I merged master so the tests would run again and it failed the same way. Looking at other recent PR's the WP int tests are all passing

**Comment by TylerBarnes** [comment]
@xSyki the tests shouldn't fail because the monorepo test setup links all the packages together when running tests. Also out of curiosity why is support for `https:www.gatsbyjs.com, http:www.gatsbyjs.com` needed? I've never seen that before, is there some CMS or data source that formats urls that way?

**Comment by xSyki** [comment]
@TylerBarnes We don't need support for this weird link format, this support is because this kind of link is passed by new URL(). We want to move from the valid-url library to our own function that uses new URL(). The valid-url library is problematic, has many bugs and not clearly defined license in package.json, in many scanners it is referred to as a serious bug.

**Comment by xSyki** [comment]
@LekoArts Could you look at it again? To be honest, I don't quite understand the setup of these tests, and the logs they give don't tell me much.

**Comment by pieh** [comment]
From checking failing wordpress tests it seems that another difference between new implementation on previous packages is handling of url like this `http://localhost:8001/wp-content/uploads/2020/08/1002-4312x2868-1-scaled.jpg\\`

previous package reported this is not valid, new code report this is valid.

What happens next and triggers
```
gatsby-source-wordpress  (undefined) location: line 4, column: 139 
	 Syntax Error: Unterminated string. 
```

error is we construct some query like this (in https://github.com/gatsbyjs/gatsby/blob/17c3da3a4c359979058531b701f2816db0a1116d/packages/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-referenced-media-items.js#L394):

```
query: '\n' +
    '            query MEDIA_ITEMS {\n' +
    '              \n' +
    '                mediaItem__index_0: mediaItem(id: "http://localhost:8001/wp-content/uploads/2022/05/gaussian2.svg\\", idType: SOURCE_URL) {\n' +
    '                  ...MediaItemFragment\n' +
    '                }\n' +
    '               \n' +
    '                mediaItem__index_1: mediaItem(id: "http://localhost:8001/wp-content/uploads/2022/05/gaussian2-scaled.svg", idType: SOURCE_URL) {\n' +
    '                  ...MediaItemFragment\n' +
    '                }\n' +
    '               \n' +
    '                mediaItem__index_2: mediaItem(id: "http://localhost:8001/wp-content/uploads/2022/05/gaussian2-scaled.svg\\", idType: SOURCE_URL) {\n' +
    '                  ...MediaItemFragment\n' +
    '                }\n' +
    '              \n' +
    '            }\n' +
```

and those urls ending in slashes are not properly escaped so we get `Unterminated string` error. 

I changed referenced query builder to escape urls and that made it no longer error on that.

```diff
-                mediaItem__index_${index}: mediaItem(id: "${sourceUrl}", idType: SOURCE_URL) {
+                mediaItem__index_${index}: mediaItem(id: "${encodeURI(sourceUrl)}", idType: SOURCE_URL) {
```

I'm not sure if this is correct fix or rather we should make new `isHttpUrl` function behave more like `valid-url` instead?

**Comment by xSyki** [comment]
@pieh In my opinion, we should not edit the default link validation. The "\" character is considered unsafe and should always be encrypted. That's why I added encryptURI for the test, but it's hard for me to assess what consequences it may have.

Now for some reason windows tests fail which seems very strange.

**Comment by pieh** [comment]
> Now for some reason windows tests fail which seems very strange.

Ah, those are sometimes flaky, not related to your change, I'll restart them

**Comment by pieh** [comment]
> @pieh In my opinion, we should not edit the default link validation. The "" character is considered unsafe and should always be encoded. That's why I added encodeURI for the test, but it's hard for me to assess what consequences it may have.

Generally yes, but in this case this is part of "body" of the request not the request url - and body is consumed and processed by external graphql server. `encodeURI` can change more things there than just escaping of slashes. The value we encode now is used as `id` matcher and those other cases I mentioned might break (or actually it might fix unknown problem heh), so that's why I mean it's potentially dangerous change as it might introduce regressions elsewhere.

I'm not sure if our wordpress tests have example of image urls which do require encoding - probably easiest one to test if the image file contained " " space character as that would be encoded to "%20", so another pass to verify this would be required

**Comment by TylerBarnes** [comment]
I think in this case it's not necessarily about what's the most correct way but wether or not this is a breaking change. There are millions of images being run through this is url function every day so it makes me nervous to think that we would change its behaviour in a way that can produce a totally different output. I think changing implementation is fine but it should work the same as before.

**Comment by xSyki** [comment]
So we really have three options:
1. Copy the validation function implementation from valid-url (not recommended in my opinion) - https://github.com/ogt/valid-url/blob/master/index.js
2. Try to test the validation by regex (however, snyk writes that we should not, as we wrote earlier)
3. Test these changes as well as possible

I tried to check if wordpress allows to upload photos with names with dangerous characters and does not allow it, but it behaves very strangely. Examples of wordpress encoding:
```
test\ -> /wp-content/uploads/2023/03/unnamed-file.png (imo this should be reported to wordpress as bug, this should not remove the characters before \)
test\\-co py -> /wp-content/uploads/2023/03/co-py.png
gatsby/gatsby -> /wp-content/uploads/2023/03/gatsbygatsby.png
```
This is definitely not php encoding, and I can't find their implementation of that.
If we were sure that wordpress will never contain characters that will be encoded in the basic version, then if I understand the problem correctly, the changes are relatively safe.

**Comment by TylerBarnes** [comment]
I'm not too worried about WP since we have some tests for it and we can patch it, I'm more worried about other CMS's we don't have integration tests for or other cases we aren't thinking of or don't know about. I think we should be certain we're reasonably accounting for most of the cases valid-url checks for to not break sites by accident. 

I believe you that `valid-url` has problems but also old packages have spent a lot of time doing bug fixes for strange edge cases and there's a lot of value in that history usually imo. Have we considered making PR's to valid-url instead to improve/fix whatever is wrong with it? (or forking it)

**Comment by xSyki** [comment]
@pieh @LekoArts What do you think we can do with this pr?

**Comment by pieh** [comment]
@xSyki I agree with @TylerBarnes about this:

> I think in this case it's not necessarily about what's the most correct way but whether or not this is a breaking change.

We can make a change that would change behavior like that only in major version, minor is not enough, so to drop `valid-url` we do have to be sure that our implementation behaviour matches `valid-url` behavior.

So far we know about:
 - `https:www.gatsbyjs.com`
 - `http://localhost:8001/wp-content/uploads/2020/08/1002-4312x2868-1-scaled.jpg\\` (doing a little bit of checking  `valid-url` discards this path because it deems `\\` is treated as illegal character in uri - https://github.com/ogt/valid-url/blob/5da88e7b31e6c07d4ba3c6ea8c43fa25460a8a64/index.js#L27-L28 ), so that's something I would probably bring into our function

It honestly feel like not something we should do right now, as there is no way to reliably ensure compat. 

What's published on npm for `valid-url` does have LICENSE file - https://unpkg.com/browse/valid-url@1.0.9/LICENSE so if we want to get rid of a package that doesn't have proper license field in `package.json` because it trips out license scanners - the safest thing to do is to literally vendor their code as-is (with appropiate credit and linkage to original repo) and postpone any potential behavior changes to time when we will be looking to do major version bump

**Pull request closed without merging**
