### PR TITLE
fix(sw): use NetworkFirst strategy for page-data

### LINKED ISSUE #24930: [gatsby-plugin-offline]: Wrong default caching strategy for page-data
## Description

I had some weird, apparently random rendering issues after I renamed some fields in a GraphQL page query. On the initial load, UI components were displayed with empty texts, whenever they were sourced from updated page query data. After a reload, the page appeared correctly.

I do believe it's a service worker caching issue and I think this piece of configuration is the source of the problem: https://github.com/gatsbyjs/gatsby/blob/f14c99b80b77f0d9094c1521976ec8e805aaa87f/packages/gatsby-plugin-offline/src/gatsby-node.js#L142-L144

I think it should be `NetworkFirst` since `StaleWhileRevalidate` creates the possibility that changed code that expects an updated page query structure can potentially run on temporarily served, outdated `page-data.json`

The [official plugin documentation](https://www.gatsbyjs.org/packages/gatsby-plugin-offline/#overriding-workbox-configuration) states, that it is `NetworkFirst` by default, but in code, it is not. I will send a PR if this is approved.
 
### Steps to reproduce

Make breaking structural changes in a GraphQL page query like renaming frontmatter fields in markdown and update the page query (after the site has been deployed and cached before). Make use of the updated query result in UI components of the page/template.

### Expected result

Texts of UI components that are sourced from the updated query structure should be displayed since the initial load.

### Actual result

Texts of UI components that are sourced from the updated query structure were empty on the initial load. They were displayed on subsequent loads. 

### Environment
<details>
  <summary>gatsby info --clipboard</summary>

 ```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 10.20.1 - /tmp/yarn--1591893009228-0.6481271662017773/node
    Yarn: 1.22.4 - /tmp/yarn--1591893009228-0.6481271662017773/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 68.8.0esr
```

</details>

<details>
  <summary>yarn list | grep gatsby | grep -v deduped</summary>

```
├─ babel-preset-gatsby@0.4.1
│  └─ gatsby-core-utils@^1.2.1
│  ├─ gatsby-image@^2.4.1
│  ├─ gatsby-plugin-env-variables@^1.0.1
│  ├─ gatsby-plugin-manifest@^2.2.41
│  ├─ gatsby-plugin-nprogress@^2.1.19
│  ├─ gatsby-plugin-offline@^3.0.35
│  ├─ gatsby-plugin-preact@^3.1.26
│  ├─ gatsby-plugin-preload-fonts@^1.0.27
│  ├─ gatsby-plugin-purgecss@^4.0.0
│  ├─ gatsby-plugin-react-helmet@^3.0.4
│  ├─ gatsby-plugin-sass@^2.0.7
│  ├─ gatsby-plugin-sharp@^2.2.9
│  ├─ gatsby-plugin-tinacms@~0.1.37
│  ├─ gatsby-plugin-tslint@^0.0.2
│  ├─ gatsby-plugin-typegen@^2.2.0
│  ├─ gatsby-plugin-typescript@^2.1.5
│  ├─ gatsby-plugin-webpack-bundle-analyser-v2@^1.1.8
│  ├─ gatsby-remark-copy-linked-files@^2.0.7
│  ├─ gatsby-remark-images@^3.1.6
│  ├─ gatsby-remark-relative-images@^0.2.1
│  ├─ gatsby-source-filesystem@^2.0.26
│  ├─ gatsby-source-stripe@^3.0.4
│  ├─ gatsby-tinacms-git@~0.4.11
│  ├─ gatsby-tinacms-json@~0.8.22
│  ├─ gatsby-tinacms-remark@~0.7.18
│  ├─ gatsby-transformer-json@^2.2.25
│  ├─ gatsby-transformer-remark@^2.6.9
│  ├─ gatsby-transformer-sharp@^2.1.9
│  ├─ gatsby@2.21.13
├─ gatsby-cli@2.12.11
│  ├─ gatsby-core-utils@^1.2.1
│  ├─ gatsby-recipes@^0.1.11
│  ├─ gatsby-telemetry@^1.3.2
├─ gatsby-core-utils@1.2.1
├─ gatsby-graphiql-explorer@0.4.1
├─ gatsby-image@2.4.2
├─ gatsby-link@2.4.1
├─ gatsby-page-utils@0.2.1
│  ├─ gatsby-core-utils@^1.2.1
├─ gatsby-plugin-env-variables@1.0.2
├─ gatsby-plugin-manifest@2.4.2
│  ├─ gatsby-core-utils@^1.2.1
├─ gatsby-plugin-nprogress@2.3.1
├─ gatsby-plugin-offline@3.2.1
│  ├─ gatsby-core-utils@^1.2.1
├─ gatsby-plugin-page-creator@2.3.1
│  ├─ gatsby-page-utils@^0.2.1
├─ gatsby-plugin-preact@3.3.1
├─ gatsby-plugin-preload-fonts@1.2.1
│  ├─ gatsby-core-utils@^1.2.1
├─ gatsby-plugin-purgecss@4.0.1
├─ gatsby-plugin-react-helmet@3.3.1
├─ gatsby-plugin-sass@2.3.1
├─ gatsby-plugin-sharp@2.6.1
│  ├─ gatsby-core-utils@^1.2.1
├─ gatsby-plugin-tinacms@0.1.37
├─ gatsby-plugin-tslint@0.0.2
├─ gatsby-plugin-typegen@2.2.0
├─ gatsby-plugin-typescript@2.4.2
├─ gatsby-plugin-webpack-bundle-analyser-v2@1.1.9
├─ gatsby-react-router-scroll@2.3.1
├─ gatsby-recipes@0.1.11
│  ├─ babel-preset-gatsby@^0.4.1
│  ├─ gatsby-core-utils@^1.2.1
│  ├─ gatsby-telemetry@^1.3.2
├─ gatsby-remark-copy-linked-files@2.3.2
├─ gatsby-remark-images@3.3.1
│  ├─ gatsby-core-utils@^1.2.1
├─ gatsby-remark-relative-images@0.2.3
├─ gatsby-source-filesystem@2.3.1
│  ├─ gatsby-core-utils@^1.2.1
├─ gatsby-source-stripe@3.0.7
│  ├─ gatsby-source-filesystem@2.1.55
│  ├─ gatsby-source-filesystem@2.1.55
│  │  ├─ gatsby-core-utils@^1.0.33
├─ gatsby-telemetry@1.3.2
│  ├─ gatsby-core-utils@^1.2.1
├─ gatsby-tinacms-git@0.4.11
├─ gatsby-tinacms-json@0.8.22
├─ gatsby-tinacms-remark@0.7.18
├─ gatsby-transformer-json@2.4.1
├─ gatsby-transformer-remark@2.8.7
│  ├─ gatsby-core-utils@^1.2.1
├─ gatsby-transformer-sharp@2.5.1
├─ gatsby@2.21.13
│  ├─ babel-preset-gatsby@^0.4.1
│  ├─ gatsby-cli@^2.12.10
│  ├─ gatsby-core-utils@^1.2.1
│  ├─ gatsby-graphiql-explorer@^0.4.1
│  ├─ gatsby-link@^2.4.1
│  ├─ gatsby-plugin-page-creator@^2.3.1
│  ├─ gatsby-plugin-typescript@^2.4.2
│  ├─ gatsby-react-router-scroll@^2.3.1
│  ├─ gatsby-telemetry@^1.3.2
```

</details>

### PR DESCRIPTION
**Pull request by nibtime**
Fixes #24930

### CODE REVIEW

**Comment by nibtime** [comment]
I just found out that `app-data.json` is not considered in caching strategies. According to its function [described in the official docs](https://www.gatsbyjs.org/docs/caching/#app-data), it should be cached with `NetworkFirst` as well.

**Comment by pvdz** [comment]
Relevant history around this: https://github.com/gatsbyjs/gatsby/pull/19342

Bottom line, the change of handler is non-trivial and probably really depends on user preference. We have to pick a default that makes sense for most.

The upside to `NetworkFirst` is that the data is always up to date, according to the caching rules anyways. The downside is that it triggers an extra, blocking, round trip when the resource is stale.

For now we would like to keep the handler as is. However, the addition of app-data is good. Could you please update the PR to add `app-data` with `StaleWhileRevalidate`? Thank you!

**Comment by pvdz** [comment]
Also, note that this setting can be changed by a user. The docs could need a little updating around this.

**Comment by nibtime** [comment]
Hi @pvdz 

I looked into #19342 and of course `StaleWhileRevalidate` would be beneficial, I just don't think that it is applicable for page-data and app-data. 

@KyleAMathews [describes the possible implications](https://github.com/gatsbyjs/gatsby/pull/19342#issuecomment-554670045) there and those are exactly the kinds of problems I ran into. Updated Markdown data was missing, and uncaught unexpected TypeErrors were thrown from intermixing outdated with updated code. 

I got those same errors reported from several internal users in a field test scenario (only with as much information as "text missing" and "white page") who all have visited the site before. I also observed those issues on my mobile devices where I did not clear up application caches. 

This kind of stuff is very hard to reproduce (it's kind of possible like I described in #24930) and very detrimental to UX.  Since I use `NetworkFirst` for both page-data and app-data via the plugin configuration I wasn't able to reproduce any of the problems.

I can hardly imagine that anybody want's their users to see missing content or white pages on a regular basis after code updates, so I think this should definitely be reconsidered.

**Comment by 21c-HK** [comment]
Quoting @pvdz:

> Relevant history around this: #19342
> 
> Bottom line, the change of handler is non-trivial and probably really depends on user preference. We have to pick a default that makes sense for most.

That can't be the right default and in this case, it cannot depend on user preference if it is causing caching bugs in the real world. The quoted issue you referenced above [changed the handler from originally `NetworkFirst` to `StaleWhileRevalidate`](https://github.com/gatsbyjs/gatsby/pull/19342/commits/7f416f610699d351da81313fdb6aa8f6c5fa7c5c), which is the cause of these extremely hard to reproduce caching bugs as explained above by @nibtime that ruin the user experience (by suggesting to the user that the web site is completely broken). The current configuration even contradicts [the official documentation](https://www.gatsbyjs.org/docs/caching/):

> Similar to HTML files, the JSON files in the public/page-data/ directory **should never be cached by the browser.** In fact, it’s possible for these files to be updated even without doing a redeploy of your site. Because of this, **browsers should be instructed to check on every request if the data in your application has changed.**

Issue #19342 basically kills any kind of caching reliability for web sites in production, so this cannot be the right default. Gatsby feels so fast because of its aggressive caching and preloading, which is only employable if you can expect it to be reliable, but this PR makes Gatsby's caching unreliable.

**Comment by pvdz** [comment]
> At least the docs should be updated and mention those kinds of problems and explain the implication of caching strategies in more detail.

A PR on that is welcome (this is for the learning team to process). I agree this could be exposed better and described more clearly.

I also agree with the inconsistency pointed out by @21c-HK on caching json files. This may be the case of outdated docs or it may be the case of incorrect implementation. I'm not sure tbh.

> However, I do not think it is the right default.
> That can't be the right default and in this case, it cannot depend on user preference if it is causing caching bugs in the real world. 

I appreciate those thoughts. I do understand your point and am not saying we're not going to change it. If and when we do, we want to make sure all implications are considered. A double blocking round trip could have severe impact on site perf. If we can prevent that by other means then that might have a preference. But other means have a cost too, so it's an equation we have to solve.

My suggestion on this would be to open a discussion issue and hash out the pro's, cons, and alternative solutions. Answer the question: Why should AND why should this not be changed? Then weigh the cost of each option.

I'm going to merge this PR. Thank you for making the changes and the PR in the first place :purple_heart:

**Comment by 21c-HK** [comment]
> This may be the case of outdated docs or it may be the case of incorrect implementation. I'm not sure tbh.

I am pretty sure that the current implementation (even after the merge) is incorrect with `StaleWhileRevalidate` (see my explanation below).

> A double blocking round trip could have severe impact on site perf. If we can prevent that by other means then that might have a preference.

I am not arguing that there might not be a better caching strategy or implementation, but `StaleWhileRevalidate` is causing bugs after merging the PR (#19342) that was intended to improve performance and that problematic PR just 6 months old. It was `NetworkFirst` before that PR. The explanation in the [current documentation](https://www.gatsbyjs.org/docs/caching/) is clear and consistent with regards to caching the page data and app data (see my earlier quote), so `StaleWhileRevalidate` cannot be correct. You might not notice the caching bugs that this caching strategy causes because these bugs are extremely hard to reproduce if you don't know exactly how they are caused, but those bugs are still there.

> My suggestion on this would be to open a discussion issue and hash out the pro's, cons, and alternative solutions. Answer the question: Why should AND why should this not be changed? Then weigh the cost of each option.

What is confusing to me is that this was not done for that problematic PR, which is causing bugs that went unnoticed until now. In any case, the cost of these caching bugs is so high that they outway any possible performance benefit, IMO.

@KyleAMathews had doubts about that PR back then because he anticipated these problems: 

> The big downside to this PR is that now page data won't be updated until the second time you visit a page as the browser will first get the cached page (however old it is) & then while the SW gets the newer version, the browser won't.

> Also... on data changing shape. With the webpack compilation hash now not being in the page-data.json — how do we know what version of page data we're working with? Someone could have cached a version weeks ago and then the page component changed & we'd still try to use it which would throw an error...

> **This PR might need reverted.**

I hope @KyleAMathews can weigh in because he probably knows what would be the best solution.

**Comment by 21c-HK** [comment]
Issue #24930 is not fixed despite the commit and merge, because only `NetworkFirst` actually fixes the reported bug. You would notice this if you tried to reproduce it.

**Comment by 21c-HK** [comment]
I clicked on a link to https://www.gatsbyjs.org/ today, which showed a blank (black) page. So there you have it. This bug even shows up on your own web site.

**Pull request merged**
