### PR TITLE
fix(gatsby-source-wordpress): always hydrate images and use the right parent element

### PR DESCRIPTION
**Pull request by TylerBarnes**
The code here is causing issues for some sites where there's only ever an initial hydration. For those sites images don't load until you navigate elsewhere and navigate back.

@wardpeet I know you initially added this code but I'm not sure why. Is there a specific reason? And what are the downsides to removing it?

cc @graysonhicks 

Also fixed a bug where sometimes the right image to hydrate on is either the parent or grandparent dom node and we were previously only ever hydrating on the parent.

### CODE REVIEW

**Comment by TylerBarnes** [comment]
Canary available as `gatsby-source-wordpress@6.18.0-alpha-wordpress-image-hydration.28`

**Comment by TylerBarnes** [comment]
New canary available on `gatsby-source-wordpress@6.18.0-alpha-wordpress-image-hydration.29`

**Review by DanielSLew — APPROVED** [review]

**Comment by TylerBarnes** [comment]
The failing tests are unrelated so I'm going to merge

**Comment by ui-jb** [comment]
Thank you @TylerBarnes, this issue was the main reason my team wasn't able to upgrade to Gatsby 4. Keep up the great work!!

**Pull request merged**
