### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by gvarandas**
Adding the "Novatics" page to the "Built with Gatsby" list.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit fcbf24bc79946c180874afa45156d4f160a294d0

https://app.netlify.com/sites/gatsbyjs/deploys/5b6078a902ed835cb2d3cf2c

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit fcbf24bc79946c180874afa45156d4f160a294d0

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6078aa02ed835cb2d3cf34

**Comment by gvarandas** [comment]
@m-allanson Ooops, my bad on that. Seems to be fine now. 🤖

**Comment by gvarandas** [comment]
@m-allanson all good now 🤖

**Pull request merged**
