### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by PHironaka**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit bf14de2bde27417c6d67feea11b7900b3860253b

https://app.netlify.com/sites/gatsbyjs/deploys/5b58f209e39e7c17ba29746f

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit bf14de2bde27417c6d67feea11b7900b3860253b

https://app.netlify.com/sites/using-postcss-sass/deploys/5b58f20ae39e7c17ba297477

**Comment by PHironaka** [comment]
made changes to indentation of title and added a category

**Comment by PHironaka** [comment]
@KyleAMathews Hi! I've passed the netlify deploy preview, but came back to find that it's now changed status to fail. What's the issue?

**Comment by PHironaka** [comment]
thank you, @m-allanson !

**Pull request merged**
