### PR TITLE
docs(gatsby-plugin-feed): fix examples link

### PR DESCRIPTION
**Pull request by CanRau**
Or should it link to https://www.gatsbyjs.org/docs/adding-an-rss-feed/ ?

### CODE REVIEW

**Comment by pieh** [comment]
The https://gatsbyjs.org/docs/adding-an-rss-feed is better option - most of our docs are not meant to be read on github - but plugins README can be found on github, npm and https://www.gatsbyjs.org/packages/gatsby-plugin-feed , so using absolute path to .org page seems best option here

**Comment by CanRau** [comment]
Fair enough 👍

**Comment by DSchau** [comment]
Closing due to the reasons @pieh specified.

Thanks for this nonetheless--sorry it didn't get merged in!

**Comment by DSchau** [comment]
Whoops - long day @CanRau! Sorry about that!

Merging this in rather than closing

**Comment by CanRau** [comment]
Paha, yeah I'm glad I didn't mess up, had a long night yesterday and am really over due now 😪 haha
Then thanks for the merge and have a restful night 😉

**Pull request merged**
