### PR TITLE
Adds support for NetlifyCMS markdown images

### PR DESCRIPTION
**Pull request by danielmahon**
This might hardcode the options a bit too much but maybe it should be NetlifyCMS specific? Since both Gatsby and NetlifyCMS are based on conventions.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
yeah... this is way too specific of code — it'd be fussy to explain and have people setup.

Can't NetlifyCMS support relative paths?

**Comment by danielmahon** [comment]
@KyleAMathews not when you are importing images through markdown I dont think, the paths are prefixed to the `public_folder`. But I am still pretty new to working with it so I could be missing something. Im trying to find the other issues I saw that address this problem of `gatsby-remark-images` not working with NetlifyCMS... I know there is this fork which attempts a solution as well but I felt like my approach, since the only real problem is the path comparison inside `gatsby-remark-images`. https://github.com/fk/netlify-cms/commit/2ebbed8e86b17dce4fa8a9dfd8822275d73361d1

**Comment by danielmahon** [comment]
Heres the main issue: https://github.com/netlify/netlify-cms/issues/325

**Comment by KyleAMathews** [comment]
Yeah, it sounds like there's plenty of support there for relative paths — seems like someone just needs to implement it.

**Comment by danielmahon** [comment]
Roger that, then I'll go poke around fk's fork and such. Thanks.

**Pull request closed without merging**
