### PR TITLE
fixing of broken link in the tutorial

### PR DESCRIPTION
**Pull request by johnlow95**
i have fix the broken link from the Tutorial 0 to 7

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 79e8788c8899ce75bd41d0043a5dd89cebf50599

https://app.netlify.com/sites/using-postcss-sass/deploys/5b62486482d3f1535f2724c0

**Comment by johnlow95** [comment]
pardon me, you mean that the link i edit it not working?

**Comment by m-allanson** [comment]
Thanks @johnlow95! It looks like you're reading the tutorial on GitHub? 

It's recommended to instead follow it from the website: [gatsbyjs.org/tutorial/](https://www.gatsbyjs.org/tutorial/)

Or to preview the Gatsby v2 tutorial, see [next.gatsbyjs.org/tutorial/](https://next.gatsbyjs.org/tutorial/)

I'm going to close this as we want to encourage people to use gatsbyjs.org for viewing the docs.

**Comment by johnlow95** [comment]
actually im trying to do some contribution since it required by my assignment so i was looking for place to contribute, would you mind merge the branch i did?

**Pull request closed without merging**
