### PR TITLE
docs(www): Add livestream section to Awesome Gatsby

### LINKED ISSUE #15164: [docs] Add Livestreams to Awesome Gatsby Resources page
## Summary

As suggested during the Gatsby Maintainers Meeting, I suggested adding a new section titled "Livestreams" to the [Awesome Gatsby Resources](https://www.gatsbyjs.org/docs/awesome-gatsby/) to list live streamers on sites like Twitch or YouTube who regularly stream development of Gatsby sites.

We could link Jason's stream page as well as other streamers who develop Gatsby sites

### Motivation

Being able to view Gatsby sites being created in real-time I see as a benefit rather than digging through some code or looking at a end product. With this as well, you can interact directly with a developer who uses Gatsby and can ask questions about either their usage of Gatsby or the Gatsby ecosystem at large.

cc: @jlengstorf

### PR DESCRIPTION
**Pull request by Aswinpookkatt**
## Description
Added livestream section and few links in it.

## Related Issues
 fixes #15164

### CODE REVIEW

**Comment by lannonbr** [comment]
A thing to think about is whether we should have links to videos on Twitch or not given there is a max shelf life before they are removed by twitch (14 days for normal streamers, 60 days for affiliates), My idea for this section was more to promote the channels rather than specific videos. Anyone on the learning team have a say about this?

**Comment by Aswinpookkatt** [comment]
ys we should promote channels

**Comment by lannonbr** [comment]
So I updated the PR to align closely more to the original issue. This is more specifically for livestreams rather than recorded content as that is better for the videos section.

**Comment by Aswinpookkatt** [comment]
But we have to manually add links each time a livestreams goes up ryt ?
Or is there any alternative way to do this automatically?

**Comment by lannonbr** [comment]
No, I'd say it would be more for those of us who are frequent viewers of Twitch programming streams, if we see a streamer who frequently streams Gatsby things, then we can add them to this curated list so we can promote their channels, so even if they aren't live when a person sees their channel in the list, they could follow the channel so they could be notified when that person goes live next.

**Comment by Aswinpookkatt** [comment]
Should I close the PR then?

**Comment by lannonbr** [comment]
No I'd say this PR is good as it is right now

**Comment by jlengstorf** [comment]
Maybe it's worth linking to archived videos on YouTube? For example, I post all of mine at https://www.youtube.com/playlist?list=PLz8Iz-Fnk_eTpvd49Sa77NiF8Uqq5Iykx

Another thing to consider: are these streams _always_ on Gatsby? If not, we should probably add context so people know what to expect; otherwise it might look like we're promoting certain people, but not others.

**Comment by marcysutton** [comment]
> are these streams always on Gatsby?

That's my biggest question. I think linking to archived content is a better idea, as then it doesn't put an expectation on streamers to always cover Gatsby content.

**Comment by lannonbr** [comment]
Yeah those points are valid as some developers I know who stream do swap to other projects and as well swap to different things entirely like doing work with hardware or game streams, so I could see it becoming a maintenance issue.

As well, as I mentioned earlier Twitch doesn't permanently save stream VODs, so then the streamer would have to put the videos up on another site to store the content for a long period of time.

**Comment by amberleyromo** [comment]
Hey! Circling back on this. I created a [YouTube playlist](https://www.youtube.com/playlist?list=PLCU2qJekvcN0RuMHCnjMYAKlpSKQ_e1hO) so we can curate archived Gatsby-related livestreams. I'd suggest we link to that instead!

**Comment by amberleyromo** [comment]
@Aswinpookkatt Want me to go ahead and make the suggested updates? https://github.com/gatsbyjs/gatsby/pull/15199#issuecomment-513385647

**Comment by Aswinpookkatt** [comment]
@amberleyromo yeah sure go ahead.

**Pull request merged**
