### PR TITLE
source-contentful: Add environment support

### PR DESCRIPTION
**Pull request by Khaledgarbaya**
This PR adds support for the new shiny Contentful environment.
Fixes https://github.com/gatsbyjs/gatsby/issues/5101

## Changes

* if an environment is not provided the plugin will fallback to master which is the default one for every contentful `space`
* the caching key will change from just the `spaceId` to `spaceId:environmentId` to support multiple environments caching
* Instead of using `client.getSpace()` we use `client.getLocales()` to ensure that we get the current environment locales

### CODE REVIEW

**Comment by pieh** [comment]
`using-contentful` example site fails with this change:
```
3:33:56 PM: Starting to fetch data from Contentful
3:33:56 PM: Fetching default locale
3:33:56 PM: Accessing your Contentful space failed. Perhaps you're offline or the spaceId/accessToken is incorrect.
```
( https://app.netlify.com/sites/using-contentful/deploys/5ae1d42911b73b3bdf1a923a ). Other builds from today worked fine.

Does this need any sort of enabling environments feature on contentful?

**Comment by Khaledgarbaya** [comment]
hmm, I'll check the org, thanks for the heads up

**Comment by Khaledgarbaya** [comment]
@pieh yep that was it I will ping the team to enable env for the test org

**Comment by Khaledgarbaya** [comment]
@pieh Fixed ! can you check again?

**Comment by pieh** [comment]
Netlify will automatically trigger new build if there were changes in PR - new one is already running ( https://app.netlify.com/sites/using-contentful/deploys ).

I was reading about contentful environments and noticed this:

> This feature is only available with subscriptions created since 16th April 2018. Please sign up or contact our support team to upgrade your account.

My question here is - is contenful api backward compatible so users without environments will still be able use updated source plugin? If not I think we should bump major version or add some fallback mechanism

**Comment by Khaledgarbaya** [comment]
ok the last deploy was successful https://app.netlify.com/sites/using-contentful/deploys/5ae1f1d1e39e7c51cd0938db
It was probably a lock file issue

**Comment by pieh** [comment]
@Khaledgarbaya this is build for different PR (builds for all PRs are listed there) so we still have that build problem - I'll try to spend some time on it tomorrow and check why it is failing.

**Comment by pieh** [comment]
Hmm, just tried it locally and it works, so it really does seem like we are not using 6.1.0 contentful package in our test builds :/

**Comment by pieh** [comment]
I fixed netlify build, but this in general upadting package in plugins seem problematic, will need to investigate if we can adjust `gatsby-dev` to handle updated package.json as this seems to be problem here.

**Comment by Khaledgarbaya** [comment]
Thanks @pieh, yeah that was the issue

**Comment by KyleAMathews** [comment]
Thanks! Excited to environments supported now.

**Pull request merged**
