### PR TITLE
Add gatsby-plugin-feed to www

### PR DESCRIPTION
**Pull request by nicholaswyoung**
I'm not 100% on-board with defining logic in `gatsby-config`. What do you think?

Otherwise, the API exposed by the feed plugin makes this very simple to do.

### CODE REVIEW

**Comment by nicholaswyoung** [comment]
Looks like I have some cleanup to do: [the feed doesn't validate](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdeploy-preview-1569--gatsbyjs.netlify.com%2Fblog%2Frss.xml).

**Comment by KyleAMathews** [comment]
It's not my favorite either but then I never have seen a pretty config on any real-world project.

The config could be moved to a separate module but I'm not sure that's any better

**Comment by nicholaswyoung** [comment]
That's kinda where I'm at. My site has a `config/` folder that keeps all this junk out.

If you think this is good to go, I give it 👍 .

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 250b07739ef5bd482d04a5484c7dffcfad7c6eb5

https://app.netlify.com/sites/gatsbygram/deploys/596fb84f8ebdd90d817ffcec

**Comment by KyleAMathews** [comment]
Looking good!

screen shot 2017-07-20 at 10 56 41 am

**Pull request merged**
