### PR TITLE
arg

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 4236bc205cb721d8d2c8026941622a61e4c77a8f

https://app.netlify.com/sites/using-glamor/deploys/59fa2ffd0b79b75a1e3d0cbc

**Comment by jquense** [comment]
yo i think i fixed this by reverting the original original change. The windows symlink issue doesn't seem present with the yarn workspaces install in the way it was with lerna bootstrap...

**Comment by KyleAMathews** [comment]
Sweeeeet! Looks like our long national nightmare is over finally :-)

**Comment by KyleAMathews** [comment]
I'll fix the lint errors in a separate PR since I added those

**Pull request merged**
