### PR TITLE
Add gatsby-universal starter.

### PR DESCRIPTION
**Pull request by fabe**
Add [`gatsby-universal`](https://github.com/fabe/gatsby-universal) starter 🔮

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 3b20546399ea8cfc17fa160c59dd4d30c9700902

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5b3df902ed83441c90f407

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 3b20546399ea8cfc17fa160c59dd4d30c9700902

https://app.netlify.com/sites/gatsbyjs/deploys/5b5b3df802ed83441c90f3ff

**Comment by fabe** [comment]
@m-allanson Thanks, don't think there can be done much as the perf score usually fluctuates anyways. But I'll do some investigating 🕵️

**Comment by fabe** [comment]
Using the lighthouse node API I'm getting 100 across the board pretty consistently 🙌

screen shot 2018-07-27 at 2 42 39 pm

**Pull request merged**
