### PR TITLE
docs(api-ssr-docs): Improve onRenderBody example

### LINKED ISSUE #26144: Improve SSR-API onRenderBody example.
## Summary

Where: https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody

What: Improve the example for `onRenderBody` or add another example, simple, that is not tied to a plugin.

### Suggestion

```
// Object of props
const HtmlAttributes = {
  "data-whatever": "content"
}

// Magic
exports.onRenderBody = (
  { setHtmlAttributes }
) => {
   setHtmlAttributes(HtmlAttributes)
}

// Output
<html data-whatever="content">
```
In my opinion looks much easier to understand the description:

> Takes an object of props which will spread into the `<html>` component.

### Motivation

It may help anyone starting with this API.

The process on how to contribute to Gatsbyjs docs is too complicated.

### PR DESCRIPTION
**Pull request by thehanimo**
## Description

Improves the example for onRenderBody (https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody),

from:
```
const { Helmet } = require("react-helmet")

exports.onRenderBody = (
  { setHeadComponents, setHtmlAttributes, setBodyAttributes },
  pluginOptions
) => {
  const helmet = Helmet.renderStatic()
  setHtmlAttributes(helmet.htmlAttributes.toComponent())
  setBodyAttributes(helmet.bodyAttributes.toComponent())
  setHeadComponents([
    helmet.title.toComponent(),
    helmet.link.toComponent(),
    helmet.meta.toComponent(),
    helmet.noscript.toComponent(),
    helmet.script.toComponent(),
    helmet.style.toComponent(),
  ])
}
```

to:

```
// Object of props
const HtmlAttributes = {
  "data-whatever": "content"
}

// Magic
exports.onRenderBody = (
  { setHtmlAttributes }
) => {
   setHtmlAttributes(HtmlAttributes)
}

// Output
<html data-whatever="content">
```

## Related Issues

Fixes #26144

### CODE REVIEW

**Review by LekoArts — CHANGES_REQUESTED** [review]
I don't think that this change improves the example in its current form. The `onRenderBody` function shouldn't be described with "Magic" as that's confusing, and also the example should use `setBodyAttributes` and `setHeadComponents`.

Please add an example for those two, too.

**Comment by thehanimo** [comment]
@LekoArts, how about this:
```js
// Object of attributes for <html>, <body>
const HtmlAttributes = {
  lang: "en-US"
}

const BodyAttributes = {
  "data-whatever": "content"
}

// Components to be rendered under <head>
const HeadComponents = [
  MyTitle,
  CustomStylesheets
]


// Set attributes and components inside onRenderBody
exports.onRenderBody = (
  { setHtmlAttributes, setHeadComponents, setBodyAttributes }
) => {
  setHtmlAttributes(HtmlAttributes)
  setBodyAttributes(BodyAttributes)
  setHeadComponents(HeadComponents)
}
```

It takes out react-helmet from the example and that kinda helps imo.

**Comment by LekoArts** [comment]
I'd propose this:

```js
// Import React so that you can use JSX in HeadComponents
const React = require("react")

const HtmlAttributes = {
  lang: "en"
}

const HeadComponents = [
  <script key="my-script" src="https://gatsby.dev/my-script" />
]

const BodyAttributes = {
  "data-theme": "dark"
}

exports.onRenderBody = ({
  setHeadComponents,
  setHtmlAttributes,
  setBodyAttributes
}) => {
  setHtmlAttributes(HtmlAttributes)
  setHeadComponents(HeadComponents)
  setBodyAttributes(BodyAttributes)
}
```

**Comment by thehanimo** [comment]
That looks perfect. Do we need additional comments (like the one in my example) or will that be oversimplified?

**Comment by LekoArts** [comment]
I'd keep it as is and can iterate on it later if it's still unclear :)

**Review by LekoArts — APPROVED** [review]
Thanks! 👍

**Pull request merged**
