### PR TITLE
Fix typography styles for "image-processing" example build

### PR DESCRIPTION
**Pull request by fk**
I can't test this right now, still running into `UNHANDLED REJECTION TypeError: Cannot read property 'component' of undefined` – but should be OK ;)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@fk oh sorry, meant to comment on this last night — looks like that's a bug of some sort — I'll investigate further but in the meantime, if you just delete you're .cache things will work. Sorry for the bother!

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit d6c2b8d935411cfc0f0ea9237e7484a1241de04f

https://app.netlify.com/sites/gatsbyjs/deploys/592d7d328ebdd905386dabb3

**Comment by KyleAMathews** [comment]
Oops, those failures are my fault. Will fix shortly.

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by fk** [comment]
> Sorry for the bother!

No worries!

**Pull request merged**
