### PR TITLE
Add Völlig Ohne to the list of sites

### PR DESCRIPTION
**Pull request by timurc**
Just founded a little studio for graphic design and web stuff in Berlin and used gatsby.js. It is my first gatsby project and my first react project too! Thanks a lot!

I features lots of responsive images, I just saw you are working on making this build-in :-) I used `sharp` (http://sharp.dimens.io/) because `jimp` was very slow. 

I got one question I would love to have an advice about: 
I am having a little problem with the inline CSS: it only works when the CSS is in the public folder already. Otherwise I get an error because it misses `./public/style.css`. So the order is somewhat messed up and I don't get why its working in the starters but not in my project.

The one thing I would wish for is a simpler boiler-plate starter with less stuff in it. Maybe I'll just do that myself the next days :)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Awesome site! Very interesting design / interaction patterns. The responsive design is ++ as well. It looks like you picked up Gatsby/React very quickly :-)

Yeah, Sharp is awesome.

On inline css — I'm not sure why this is broken for you... I'm in the middle of installing your site and will report back if I learn anything. The CSS is supposed to be built before the static HTML pages are built but perhaps that's broken somehow...

A simpler starter would be great! Please build one and I'll add it to the README (and future website whenever that gets built).

**Comment by timurc** [comment]
Thanks a lot! I would be really happy if you were able to spot the problem with the inlined css :)

**Comment by KyleAMathews** [comment]
@timurc So I uncommented the line in your html.js to inline the css... and it just worked. Perhaps you just need to delete `node_modules` and reinstall? This is the fix for a distressing number of bugs :-)

**Comment by timurc** [comment]
Oh no, I could have gotten this idea myself, it is not the first time that fixes things. And it did again. Thanks anyways :-)

**Comment by jlengstorf** [comment]
Hiya @timurc! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
