### PR TITLE
fix(babel-preset-gatsby-package): remove explicit `@babel/plugin-proposal-class-properties` and let `@babel/preset-env` add it

### PR DESCRIPTION
**Pull request by Js-Brecht**
## Description

[A constraint was added](https://github.com/babel/babel/blob/e6d873e061a967c64c9999f15b831aa121cc5a68/packages/babel-preset-env/src/index.js#L303-L326) to `@babel/preset-env` [recently](https://github.com/babel/babel/commit/e6d873e061a967c64c9999f15b831aa121cc5a68), which is causing `babel-preset-gatsby-package` to throw the error shown here: https://github.com/Js-Brecht/gatsby-plugin-ts-config/issues/11.  (I use `babel-preset-gatsby-package` for transpiling TS `gatsby-*` files from `gatsby-plugin-ts-config`).

Apparently, if `loose: true` is set for `@babel/plugin-proposal-private-methods`, then it must also be set to `true` for `@babel/plugin-proposal-class-properties`.  According to [this comment](https://github.com/babel/babel/issues/11622#issuecomment-634390210), both `@babel/plugin-proposal-private-methods` and `@babel/plugin-proposal-class-properties` are included by `@babel/preset-env` when `shippedProposals: true`, and they're assigned uniform options then.  However, `babel-preset-gatsby-package` [imports `@babel/plugin-proposal-class-properties`](https://github.com/gatsbyjs/gatsby/blob/master/packages/babel-preset-gatsby-package/index.js#L42) itself, which overrides that option.

To fix it, I've just added `loose: true` to `@babel/plugin-proposal-class-properties` so that it matches `@babel/preset-env`.  Since `@babel/preset-env` imports those plugins itself, maybe `@babel/plugin-proposal-class-properties` could just be removed from the list?

### CODE REVIEW

**Comment by pieh** [comment]
> Since `@babel/preset-env` imports those plugins itself, maybe `@babel/plugin-proposal-class-properties` could just be removed from the list?

We have `shippedProposals: true` in our preset-env settings which make it so preset doesn't add few of plugins (including class properties ones), so I think the change in this PR is actually least invasive one (tho I need to look up meaning of `loose` setting :) )

That said - I wonder if `gatsby-package` is right preset we need to look at? Usually this one is used only to build package to publish to npm and shouldn't be causing problem in runtime? https://github.com/Js-Brecht/gatsby-plugin-ts-config/issues/11 is the issue I refer to - unless your plugin make use of that `gatsby-package` preset - I would expect stuff to be problematic with `babel-preset-gatsby` one?

**Comment by Js-Brecht** [comment]
> We have `shippedProposals: true` in our preset-env settings which make it so preset doesn't add few of plugins (including class properties ones)

Looks like they use a round-about way to define what plugins the preset pulls:

* It uses [this list](https://github.com/babel/babel/blob/master/packages/babel-compat-data/data/plugins.json#L13-L23) to find what plugin names to pull.
* Then it gets the actual imported modules from [here](https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/available-plugins.js#L15).
* [pluginsFiltered](https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/plugins-compat-data.js#L25) is the [plugins list being used](https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/index.js#L61).

So it appears as though `class-properties` and `private-methods` are being used, but [here](https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/plugins-compat-data.js#L22-L23) it sets `class-properties` to be the same as `private-methods`.  Not sure of the implications there.

> tho I need to look up meaning of `loose` setting

Yeah, I'm not really sure about that either.  If it cannot be `loose: true`, then `private-methods` could also be imported, and they could both be set to `loose: false`, that way it overrides what `preset-env` is pulling 🤷‍♂️

**Comment by Js-Brecht** [comment]
So, with `class-properties`:

*  `loose: true`: class members will be defined using an assignment expression.
   ```js
   var Foo = function Foo() {
      this.y = 'bar';
   }
   ```
* `loose: false`, class members are defined using `Object.defineProperty()`.
   ```js
   var Foo = function Foo() {
      Object.defineProperty(this, "y", {
         configurable: true,
         enumerable: true,
         writable: true,
         value: 'bar'
      })
   }
   ```

Seems like the assignment is a little more thorough using `Object.defineProperty()`.

In `private-methods`:

* `loose: true`: private class methods will be defined using `Object.defineProperty()`
* `loose: false`: private class methods will be defined using a `WeakSet()`.

Here it means the difference between the class accessing private methods with the normal property access methods, or by using `.get()`.  [Their example](https://babeljs.io/docs/en/babel-plugin-proposal-private-methods#loose) uses some helpers that I haven't looked at, so I don't really know exactly what it's doing without looking deeper.  I think the point of the `loose` property is whether or not private members can be accessed from outside the class.

**Comment by pieh** [comment]
I found this post - https://2ality.com/2015/12/babel6-loose-mode.html helpful when checking on `loose` - seems like it trades correctness for some perf and potentially some compat with "older engines" (... just not quite sure what this part means in concerete terms - also that blog post was from 2015 so aeons ago in JS time :P)

> So it appears as though class-properties and private-methods are being used

I'm not exactly sure if it does (at least with our config) - I was trying this out with some monkey patching in babel (logging `config` in https://unpkg.com/browse/@babel/core@7.10.2/lib/transform-file.js) to log stuff out and when using `babel-preset-gatsby-package` version without `class-properties` (to build one of our packages)- that plugin was not auto added by `preset-env`.

**Comment by Js-Brecht** [comment]
I think the install that's being done when my plugin is installed might be winding up with a newer version of `@babel/preset-env`.  If I run `yarn upgrade` in the Gatsby repository, then try to run a build, I get this error:
```
Though the "loose" option was set to "true" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "false" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": false }]
to the "plugins" section of your Babel config.
```

**Comment by Js-Brecht** [comment]
But if I don't do any upgrade, then it works fine.

I totally understand if you don't want to take a chance with this right now.  I can also adjust the options of `class-properties` during runtime; I'm already doing it once for `tranform-runtime` to inject the `absoluteRuntimePath`

**Comment by pieh** [comment]
> I think when my plugin is installed it might be winding up with a newer version of `@babel/preset-env`. If I run `yarn upgrade` in the Gatsby repository, then try to run a build, I get this error:

We recently bumped `@babel/*` packages and we do get those now - but it seems like those are warnings and not errors (as in it's not terminal)

> I totally understand if you don't want to take a chance with this right now. I can also adjust the options of `class-properties` during runtime; I'm already doing it once for `tranform-runtime` to inject the `absoluteRuntime` (for yarn2 support)

We do need to address it in some way, with our recent `babel/*` bump in monorepo this puts more priority on this

**Comment by wardpeet** [comment]
I feel we should exclude the transforms from babel-preset-env so we use ours and not the one from preset-env, this would remove any issues we will have in the future.

**Comment by pieh** [comment]
> I'm not exactly sure if it does (at least with our config) - I was trying this out with some monkey patching in babel (logging `config` in https://unpkg.com/browse/@babel/core@7.10.2/lib/transform-file.js) to log stuff out and when using `babel-preset-gatsby-package` version without `class-properties` (to build one of our packages)- that plugin was not auto added by `preset-env`.

After trying it again from scratch after chat with @wardpeet it seems like my previous comment is wrong. I can't really reproduce problem I had anymore and I also don't exactly remember errors I was seeing :S

**Comment by pieh** [comment]
> After trying it again from scratch after chat with @wardpeet it seems like my previous comment is wrong. I can't really reproduce problem I had anymore and I also don't exactly remember errors I was seeing :S

Lol - sorry for back and forth - I figured out how I was getting those errors before - it was before https://github.com/gatsbyjs/gatsby/pull/24432 (bump for `@babel/*`) was merged and then errors - after commenting out explicit `class-properties` plugin I was seeing things like:

```
➜  gatsby-remark-katex git:(40d241b12e) ✗ yarn prepare              
yarn run v1.21.0
$ cross-env NODE_ENV=production npm run build
npm WARN lifecycle The node binary used for scripts is /var/folders/7b/7_tqb8f50bx7jhyj0bn9r8v80000gn/T/yarn--1591268500771-0.2962234383578015/node but npm is using /Users/misiek/.nvm/versions/node/v10.16.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> gatsby-remark-katex@3.3.2 build /Users/misiek/dev/gatsby/packages/gatsby-remark-katex
> babel src --out-dir . --ignore "**/__tests__"

@babel/preset-env: `DEBUG` option

Using targets:
{
  "node": "10.13"
}

Using modules transform: commonjs

Using plugins:
  proposal-numeric-separator { "node":"10.13" }
  proposal-nullish-coalescing-operator { "node":"10.13" }
  proposal-optional-chaining { "node":"10.13" }
  syntax-json-strings { "node":"10.13" }
  syntax-optional-catch-binding { "node":"10.13" }
  syntax-async-generators { "node":"10.13" }
  syntax-object-rest-spread { "node":"10.13" }
  transform-modules-commonjs { "node":"10.13" }
  proposal-dynamic-import { "node":"10.13" }

Using polyfills with `entry` option:
{ SyntaxError: /Users/misiek/dev/gatsby/packages/gatsby-remark-katex/src/index.js: Support for the experimental syntax 'classProperties' isn't currently enabled (7:20):

   5 | class Bork {
   6 |   //Property initializer syntax
>  7 |   instanceProperty = `bork`
     |                    ^
   8 |   boundFunction = () => {
   9 |     return this.instanceProperty
  10 |   }

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-class-properties (https://git.io/vb4yQ) to the 'plugins' section to enable parsing.
    at Object._raise (/Users/misiek/dev/gatsby/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:742:17)
    at Object.raiseWithData (/Users/misiek/dev/gatsby/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:735:17)
    at Object.expectPlugin (/Users/misiek/dev/gatsby/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:8784:18)
    at Object.parseClassProperty (/Users/misiek/dev/gatsby/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12133:12)
    at Object.parseClassProperty (/Users/misiek/dev/gatsby/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:2947:18)
    at Object.pushClassProperty (/Users/misiek/dev/gatsby/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12093:30)
    at Object.parseClassMemberWithIsStatic (/Users/misiek/dev/gatsby/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:12026:14)
    at Object.parseClassMember (/Users/misiek/dev/gatsby/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:11963:10)
    at Object.parseClassMember (/Users/misiek/dev/gatsby/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:2837:11)
    at withTopicForbiddingContext (/Users/misiek/dev/gatsby/node_modules/@babel/core/node_modules/@babel/parser/lib/index.js:11908:14)
  loc: Position { line: 7, column: 19 },
  pos: 180,
  missingPlugin: [ 'classProperties' ],
  code: 'BABEL_PARSE_ERROR' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-remark-katex@3.3.2 build: `babel src --out-dir . --ignore "**/__tests__"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-remark-katex@3.3.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/misiek/.npm/_logs/2020-06-04T11_01_44_240Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

But this is not happening after the bump - so I think we can go ahead with your suggestion to remove explicit `class-properties` from plugin list (and likely direct dependencies of that preset?) and let `preset-env` handle this (which should also ensure `loose` setting is consistent there)

**Comment by Js-Brecht** [comment]
> We recently bumped `@babel/*` packages and we do get those now too in here - but it seems like those are warnings and not errors (as in it's not terminal)

I'm not sure exactly why it's throwing an error on mine; it's the same message, though.  The major difference is that mine is doing runtime transpiling through `@babel/register`, and building Gatsby packages is done on the CLI... ?  I don't really know if that's why it throws instead, but it seems reasonable to assume.

---

> so I think we can go ahead with your suggestion to remove explicit `class-properties` from plugin list (and likely direct dependencies of that preset?) and let `preset-env` handle this (which should also ensure `loose` setting is consistent there)

I just want to verify: you want to remove `class-properties` from `preset-gatsby-package`?  I ask because it sounded like @wardpeet wanted the config to be more explicit, I assume by adding `private-methods` as well?  Unless there's another way to tell `preset-env` not to include `class-properties` or `private-methods`.

**Comment by pieh** [comment]
> I just want to verify: you want to remove `class-properties` from `preset-gatsby-package`? I ask because it sounded like @wardpeet wanted the config to be more explicit, I assume by adding `private-methods` as well? Unless there's another way to tell `preset-env` not to include `class-properties` or `private-methods`.

Ops, sorry for spreading confusion here - I didn't realize @wardpeet left comments on the PR that didn't align with my suggestion :P. As mentioned in previous comments - I did chat with him about this PR / issue with `loose` and here's part of "transcript" (just so the exchange is not lost)

```
pieh:  12:47
but it seems like removing explicit class-properties and let preset-env handle this is way to go - just need to verify it a bit more

Ward:  12:49 PM
or the other way around

pieh:  12:49 PM
sure, yeah

Ward:  12:49 PM
probably letting babel-preset-env handle it is better cause it's only used when necessary
```

this was couple of minutes after Ward's comment in the PR now that I check times - so I think we should be ok with letting `preset-env` handle autoadding `proposal-class-properties` as needed 

TBH, I don't have any issue with doing this other way around - keeping explicit `proposal-class-properties` with `loose: true` and excluding it from being auto added by `@babel/preset-env` (this is mostly to not have duplicate plugins in there because AFAIK babel does not dedupe plugin instances and duplicates just "waste" CPU cycles

**Comment by Js-Brecht** [comment]
Okay, I went ahead and removed `@babel/plugin-proposal-class-properties` from the plugin list

**Comment by Js-Brecht** [comment]
That results in this error:
```
Support for the experimental syntax 'classProperties' isn't currently enabled
```

**Comment by pieh** [comment]
> That results in this error:
> 
> ```
> Support for the experimental syntax 'classProperties' isn't currently enabled
> ```

I think that's because this branch was branched of master before we bumped `babel/*` (mostly just yarn.lock bump is important here, because version selectors already would pull newest if not for a lock file). So my comment in https://github.com/gatsbyjs/gatsby/pull/24640#issuecomment-638784895 probably apply here.

I just merged master in here to validate my assumption

**Comment by pieh** [comment]
Ok, so merging master in fixed the problem. I'm good with the PR as it is right now - I just want to make sure this also fixes original problem described in `gatsby-plugin-ts-config` as well - can you let me know if it does or we need to iterate further?

**Comment by Js-Brecht** [comment]
I monkey patched `gatsby-package` to exclude `class-properties`, and it works.

Versions being used:
* `babel-preset-gatsby-package@0.4.3`
* `@babel/preset-env@7.10.2`

Question: should `@babel/plugin-proposal-class-properties` be removed from the dependencies for `babel-preset-gatsby-package`?

**Comment by pieh** [comment]
> Question: should `@babel/plugin-proposal-class-properties` be removed from the dependencies for `babel-preset-gatsby-package`?

I think so yes. `@babel/preset-env` has `@babel/plugin-proposal-class-properties` as its own dependency ( https://unpkg.com/browse/@babel/preset-env@7.10.2/package.json )

**Comment by Js-Brecht** [comment]
Done

**Comment by pieh** [comment]
Will do one last master merge and get this merged and published

**Comment by pieh** [comment]
Published in `babel-preset-gatsby-package@0.4.4`

**Comment by Js-Brecht** [comment]
thanks!

**Pull request merged**
