### PR TITLE
Import chalk as a namespace

### PR DESCRIPTION
**Pull request by mike-north**
## Description

This small change to how `chalk` is imported into the cli reporter, allows consumers of Gatsby to decide whether they want to enable [`esModuleInterop`](https://www.typescriptlang.org/tsconfig#esModuleInterop) or not. Without this change, they're forced to enable it.

This TS compiler option is kind of "viral" in that once a dependency's types require the flag to be `true` in order to build properly, all consumers of that library must also set that flag to `true` in order to compile.

### Documentation
`N/A`

## Related Issues
`N/A`

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Interesting. Is there any where else in the code base we should change like this? Is this something we should enforce?

**Comment by mike-north** [comment]
@KyleAMathews you could either

(a) remove this line from the project's tsconfig https://github.com/gatsbyjs/gatsby/blob/5ba1ac2aca063577a907560627f262649c732279/tsconfig.json#L16
and make a large quantity of straightforward changes throughout the code base

````diff
- import path from 'path';
+ import * as path from 'path';
````

**or**

(b) you could add a fixture project of some sort as part of your test suite, with a tsconfig that doesn't have `esModuleInterop: true` and ensure it compiles properly


choice (a) would effectively eliminate these kinds of imports from the entire project, while (b) would only ensure that none of these kinds of imports are present in the externally consumable types

**Comment by KyleAMathews** [comment]
Typescript is complaining in ci/circleci: bootstrap:

```
$ yarn build
$ microbundle -i src/index.ts --no-pkg-main --target=node -f=cjs --sourcemap=false --compress --alias worker_threads=@ascorbic/worker-threads-shim
rpt2: options error TS5069: Option 'declarationDir' cannot be specified without specifying option 'declaration' or option 'composite'.
Build "createGatsby" to lib:
      65.5 kB: index.js.gz
      56.5 kB: index.js.br
```

**Comment by LekoArts** [comment]
Hey! Thanks so much for opening this pull request!

Sadly this PR got stale and didn't have any activity for some time. We're trying to do better with PR reviews! To get a better overview of all actionable PRs we're going through all open PRs and triage them. Since we won't be able to do everything and adding new features _always_ means added maintenance burden, we have to be more picky about what's beneficial for the average user and the project itself longterm.

Having said all this, we dropped the ball on this PR and we're sorry about not responding to it earlier. As said above, we want to do better in the future but here we should have communicated earlier what will happen with the PR.

We think this is a great PR and would love to see it land in Gatsby. We're closing this PR for now but if you're able to rebase onto latest `master` branch and try it out with latest `next` versions, we'd be happy to review the PR and re-open it again.

We absolutely want to have you as a contributor and are sorry for any inconveniences we caused with replying too late to this PR.

Thanks for submitting to Gatsby! 💜

**Pull request closed without merging**
