### PR TITLE
fix(gatsby): Track nodes when mutated

### PR DESCRIPTION
**Pull request by stefanprobst**
After a field is added to a node with `createNodeField`, we should re-track inline objects.

Fixes:  #15699

### CODE REVIEW

**Comment by stefanprobst** [comment]
Failing tests look unrelated, failure with NPM registry?

**Comment by pieh** [comment]
> Failing tests look unrelated, failure with NPM registry?
Yeah, seems so - I restarted workflow - those tests don't fail anymore, so it probably was temporary registry/CI problem

**Comment by pieh** [comment]
I restarted just CircleCi tests as I have no idea how to do that for azure and seems to work

**Comment by zce** [comment]
When do you plan to merge?

**Comment by pieh** [comment]
Oh, sorry @zce. It was suppose to automerge, but seems like some recently required tests didn't even run. Let me update PR be syncing master and if nothing breaks, it will automerge.

**Pull request merged**
