### PR TITLE
Add viewport-based prefetching to gatsby-link

### PR DESCRIPTION
**Pull request by markmichon**
Makes use of IntersectionObserver, for browsers with support, to load page chunks once the `gatsby-link` component enters the viewport.

Minor gains for the average user, but in some instances like on reactjs.org's all blog articles page it reduces initial requests from ~150 to 30. Benefits increase for lower bandwidth connections, as the side benefit of only loading visible page data is that the likelihood of the next page being available isn't reliant on it competing with downloads of off-screen page data.

### CODE REVIEW

**Comment by jquense** [comment]
this is so cool!

**Comment by KyleAMathews** [comment]
Thanks! This is super exciting stuff!

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit f9016972e26a0a85399ba7029c5d32308336c2ee

https://app.netlify.com/sites/using-glamor/deploys/59dfb14e0b79b77403e37718

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit ab49c5b60bad44b862f5165a63874c6bff5f68f1

https://app.netlify.com/sites/using-glamor/deploys/59dfb1ec0b79b77403e37761

**Comment by KyleAMathews** [comment]
Woah, this had a *huge* impact on gatsbyjs.org. I tested on gatsbyjs.org the impact of this change + gatsby-image which does the same trick of lazy loading images and our "fully loaded" downloaded bytes is 1/2 (!) what it was a week ago — from 1355kb to 610kb!

Most of the gains is from not starting immediately downloading all pages in docs. gatsbyjs.org actually mounts them on the frontpage in a hidden div in the layout component so previously they started downloading immediately but with this change they aren't downloaded until you visit the docs page.

Nice!

**Comment by KyleAMathews** [comment]
before: http://www.webpagetest.org/result/171012_Q5_c8a8d6e158a9fba1621069200e27c984/
after: http://www.webpagetest.org/result/171012_SX_c8b0392899c755d79c627a3e3e4b81fd/1/details/#waterfall_view_step1

**Comment by KyleAMathews** [comment]
oops, after is http://www.webpagetest.org/result/171012_SX_c8b0392899c755d79c627a3e3e4b81fd/

**Pull request merged**
