### PR TITLE
Add new plugin to handle csv files

### PR DESCRIPTION
**Pull request by ssonal**
Adds support for csv parsing.

Related to #1199

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 6f913b7e9f0ef9d0ba4070fb935ff145d6638c60

https://app.netlify.com/sites/using-styled-components/deploys/5967450ba700c4082663d76f

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 6f913b7e9f0ef9d0ba4070fb935ff145d6638c60

https://app.netlify.com/sites/using-contentful/deploys/5967450ba700c4082663d772

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 6f913b7e9f0ef9d0ba4070fb935ff145d6638c60

https://app.netlify.com/sites/using-postcss-sass/deploys/5967450ba700c4082663d763

**Comment by KyleAMathews** [comment]
Looks great!

Could you also add a really simple example site? One JS component page that queries data from a sample csv file. Perhaps could just output it into a table or something?

**Comment by ssonal** [comment]
Sure thing!

**Comment by ssonal** [comment]
Very basic example but I hope it explains enough.

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 944429b93f9dbf21783efdfce90b61d6ff94d248

https://app.netlify.com/sites/image-processing/deploys/59687c9e424ef26655a899ff

**Comment by KyleAMathews** [comment]
Sorry for the slow merge, been traveling but this is really really awesome! Thanks for such a nice PR!

**Comment by jlengstorf** [comment]
Hiya @ssonal! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
