### PR TITLE
Fix DESC to ASC in the tutorial

### PR DESCRIPTION
**Pull request by greenhamsam**
Hullo! I've never done a pull request before, please bear with me :)

I noticed that the order DESC in the tutorial (part 6) should be ASC.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-remark* failed.

Built with commit c599cfb07d01d60d2a215f8bd30b904c2b7dfa7e

https://app.netlify.com/sites/using-remark/deploys/5b756cef73f2cf550557c7cb

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit c599cfb07d01d60d2a215f8bd30b904c2b7dfa7e

https://app.netlify.com/sites/using-postcss-sass/deploys/5b756ced73f2cf550557c7b9

**Comment by pieh** [comment]
I think `DESC` is correct here - this should make newest post to show first. It doesn't work in your case?

**Comment by greenhamsam** [comment]
Nope! In my case, DESC had the older post showing first. When I changed it
to ASC, it worked as described. Not sure whether I was just doing something
strange, though. Thanks for checking :)

**Comment by pieh** [comment]
What's the format you have dates in your files? It's quite possible that we actually do string comparisons, so if you have something else than `YYYY-MM-DD` this might be causing troubles

**Comment by calcsam** [comment]
I'm going to close this PR since current behavior is as intended -- please keep conversation going though :)

**Comment by greenhamsam** [comment]
Hmm, that's not it, I also have YYYY-MM-DD. What a mystery!

Thanks for checking up, anyway :)

**Pull request closed without merging**
