### PR TITLE
Add note about nodes replacing edges, node in queries

### PR DESCRIPTION
**Pull request by laurieontech**
## Description

GraphQL queries that include the 

``` 
edges {
 node
}
```
pattern can replace that piece of the query with `nodes`. It's important to note that this is available when using Gatsby v2.2.0 or later.

### CODE REVIEW

**Comment by AishaBlake** [comment]
That note should definitely be there but I'm wondering if there are other places it should be as well. I'm not immediately sure where but want to say something before I forget!

**Comment by laurieontech** [comment]
Ya, I was starting here as it seemed the "root cause" place? Though I could be wrong about that. Perhaps we could add this and make an issue for the community to find other places it should go or link to?

**Comment by marcysutton** [comment]
I think it would be fine to address this one here, and do additional entries in future PRs. One thing I think would help, though, is some kind of example. It could be a plain code example or in a Codesandbox–I'm actually not sure how to create those, @gillkyle do you know? (whatever we uncover here should go in the contributing docs in a future PR, too)

**Comment by gillkyle** [comment]
Having a better process around Codesandbox would be great. My guess is existing Codesandboxes probably link off to individual accounts in places they might already exist. For the [GraphQL Query Options Reference page](https://www.gatsbyjs.org/docs/graphql-reference/) there is a Codesandbox (I think maybe @pieh set it up) that's just running in develop mode and it's how we embed the GraphiQL window for demos.

You can go here: https://711808k40x.sse.codesandbox.io/___graphql

Write your query there and copy the url for an example. 

I could make an update to the contributing docs to explain that process?

**Comment by laurieontech** [comment]
That'd be awesome to have a written process, thanks @gillkyle. And I'll get that added to this before we merge.

**Pull request merged**
