### PR TITLE
chore(gatsby): Grammatical improvement in flags-description

### PR DESCRIPTION
**Pull request by kilinkis**
## Description

This PR proposes an update in the description of two of the Feature Flags, where in their description, says `Don't` instead of `Doesn't`. 
In English, auxiliar `Do` is used for `I`, `you`, `we`, `they`, whilst `Does` is used for `he`, `she`, `it`.

Diagram showing the use of 'do' and 'does'

Sources for more info:

https://www.grammar.cl/Present/Do_Does.htm
https://www.ecenglish.com/learnenglish/lessons/do-or-does

### CODE REVIEW

**Review by LekoArts — APPROVED** [review]
Thanks!

**Comment by KyleAMathews** [comment]
I used "don't" deliberately as I was writing the description from the perspective of the flag telling Gatsby what to do like a mom telling a child: "don't walk in here with your dirty shoes!".

Does that make sense?

**Comment by LekoArts** [comment]
Yeah, makes sense! I couldn't find the formal grammatical term for it but it sounded fine to me.

**Comment by kilinkis** [comment]
@KyleAMathews ah okay then! makes sense :)

**Pull request closed without merging**
