### PR TITLE
add gatsby-starter-barebones and gatsby-starter-barebones-preact

### PR DESCRIPTION
**Pull request by Rusta**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hey thanks for sharing! Could you publish somewhere demos for these starters and add them to the PR?

**Comment by Rusta** [comment]
I've added the repos as github pages, and updated the docs with a link to each of them as Demo. 

HOWEVER, the demo sites themselves seem to be ignoring the JS routing (they full page re-load instead). I'm not exactly sure why. I guess we should hold off merging this until I've worked it out... :(

**Comment by KyleAMathews** [comment]
I can help! They're missing the `prefixLink` around links (which thankfully will be abstracted away in v1). Check out https://github.com/gatsbyjs/gatsby-starter-default/blob/master/pages/index.js

**Comment by Rusta** [comment]
Hi - the links in both repos do actually use the prefixLink helper function. The two pages on the site are very noddy (I should probably add a little more CSS to make them prettier!) and the links between the pages are prefixed correctly - see it here https://rusta.github.io/gatsby-starter-barebones/

Something else must be up...

**Comment by Rusta** [comment]
Ah, just spotted this error in the console 

Uncaught Error: Cannot find module "config"

from gatsby-helpers.js

**Comment by Rusta** [comment]
interestingly if I fix the gatsby version in package.json to:

  "gatsby": "0.12.28"

rather than 

  "gatsby": "^0.12.28"

the problem goes away - suggesting a breaking change somewhere along the way (at least in terms of how my starter kit is utilising the helper functions anyway)

**Comment by Rusta** [comment]
looks like I can fix this by ensuring I import 'config' alongside 'gatsby-helpers' as it seems to be an implicit dependency now. this was probably an edge case as most people probably do import the two alongside each other anyway in normal usage.

So we should be good to go on this one now

**Comment by KyleAMathews** [comment]
Huh... that's a super strange bug. `gatsby-helpers.js` does import config so if that fails, it must be due to some sort of webpack whateverness...

**Pull request merged**
