### PR TITLE
[www] Update/consolidate palette, monogram and logo, favicons

### PR DESCRIPTION
**Pull request by fk**
This replaces the current brand color with a slightly ["bolder" purple](https://github.com/gatsbyjs/gatsby/issues/3363#issuecomment-359118402) across icons, logos, and UI. It also tries to consolidate palette colors where possible, improve their naming, and favicons along the way, plus a few more things:

* `rebeccapurple` `#663399` replaces `#744C9E` – we're lucky, most of the other "purple" palette colors are already matching the new brand color hue (270: `hsla(270, 50%, 40%, 1)`):
  * `#9D7CBF`, formerly `brandLight`, now `lilac`: `hsla(270, 34%, 62%, 1)`,
  * `#e0d6eb`, formerly `lightPurple`, now `ui.bright`: `hsla(269, 34%, 88%, 1)`
  * `#f5f3f7`, formerly `brandLighter`, now `ui.light`: `hsla(270, 20%, 96%, 1)`
  * `#fbfafc`, formerly `sidebar`, now `ui.whisper`: `hsla(270, 25%, 98%, 1)`
* add  `colors.success`: `#37b635`,  `colors.warning`: `#ec1818`
* give naming colors a shot
* replace `veryLightPurple` `#f6f2f8` with `ui.light` `#f5f3f7`
* move colors from `utils/presets`  to `utils/colors`, expose them at `presets.colors`
* add `colors.gray` and create colors via `https://github.com/KyleAMathews/gray-percentage``
  * `calm` becomes `gray.calm` and is updated to pass [WCAG AA standards](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html), see [here](https://leaverou.github.io/contrast-ratio/#hsla%28270%2C6.8076334240000005%25%2C0%25%2C0.54%29-on-white)
* adjust mobile navigation icon colors
* fix manifest `background_color`, `theme_color`
* start handling rgb(a) values via https://github.com/remarkablemark/hex2rgba
* provide a `logo.svg` that contains both monogram and wordmark and use it to replace the `gatsby-negative.svg` + `<h1>Gatsby</h1>` combo in `components/navigation` – the wordmark should not depend on webfonts IMO
* update and fix favicons: [before](https://realfavicongenerator.net/favicon_checker?protocol=http&site=www.gatsbyjs.org)/[after PR](https://realfavicongenerator.net/favicon_checker?protocol=https&site=deploy-preview-3639--gatsbyjs.netlify.com), giving a white-on-purple version of the monogram a shot for iOS home screen and Windows 8/10 tile icons
* (TBD ;-)) fancy links in blog posts: 
image

Along the way this also generically fixes the horrible combination of purple and "almost-gray" for the explanatory diagram on the home page:

image

image

### CODE REVIEW

**Comment by fk** [comment]
https://deploy-preview-3639--gatsbyjs.netlify.com/

**Comment by KyleAMathews** [comment]
Looks awesome 😍!

BTW, instead of `b500` or whatever, this website is great for getting real-ish color names http://www.color-blindness.com/color-name-hue/ which I find more fun / useful.

**Comment by fk** [comment]
Oh hey, totally missed your comment!

Re:chroma.js – I fully agree, only threw it in to play around with generating the palette and will remove it after I'm done (especially since my ["experiments"](https://deploy-preview-3639--gatsbyjs.netlify.com/colors/) didn't turn out to be really successful, at least not w/o the scale getting unneccessary big, or hacking around this with two to three different scales (dark<->brand, brand<->bright, bright<->light), and then stitching them together).

**Comment by KyleAMathews** [comment]
Cool :-)

Looks like some of the icons got replaced with the inverted version? Was that intentional? https://github.com/gatsbyjs/gatsby/pull/3639/files#diff-c4166dbdce601582ea056b6a66083465

**Comment by fk** [comment]
Yep, figured let's give the inverted version a spin for Windows 8/10 and iOS. I just updated the issue description with links that show the [current](https://realfavicongenerator.net/favicon_checker?protocol=http&site=www.gatsbyjs.org) favicons and the ones [in the PR](https://realfavicongenerator.net/favicon_checker?protocol=https&site=deploy-preview-3639--gatsbyjs.netlify.com). Please check those links if you'd like, they should clarify the thoughts behind.

Not attached to the inverted version but works well for Windows 8/10, where they add a gradient to that tile apparently.

**Comment by KyleAMathews** [comment]
This looks awesome! :-D

Thanks for the great work cleaning up our logo + color palette. Great foundation for future work.

**Pull request merged**
