### PR TITLE
chore(docs): remove remaining spectrum references

### LINKED ISSUE #26351: Remove Spectrum Community Reference From Documentation
## Summary

What problem(s) did you run into that caused you to request additional documentation? What questions do you think we should answer? What, if any, existing documentation relates to this proposal?

@AishaBlake opened issue #26282 which removed references to the Spectrum community chat from the Gatsby Github Issue templates. There are still additional references in the Gatsby repo (mostly in readme files and #100DaysOfGatsby blog posts).

If appropriate, this issue would remove these remaining Spectrum references.

### Motivation

Why should we document this and who will benefit from it?

Documentation and blog post readers should be directed to Gatsby's active communities to interact with maintainers and other users.

## Steps to resolve this issue

Input would be appreciated here, but references to Spectrum _could_ be removed from the files list below.

Searching for `Spectrum` in Markdown files yields the following references:

**Documentation referencing Spectrum:**

- https://github.com/gatsbyjs/gatsby/blob/9042a7607463cdd7f4156db11bf3ef8dffe60257/docs/contributing/where-to-participate.md
- https://github.com/gatsbyjs/gatsby/blob/0e98ad417f56eb5f577d89bd386fad8987e60ee6/starters/README.md
- https://github.com/gatsbyjs/gatsby/blob/9ec02711eb21b4b446c5792a99618e67959e439b/packages/gatsby/README.md
- https://github.com/gatsbyjs/gatsby/blob/bc82867cec6076fa83adef4de319e8e6d03beb75/docs/contributing/gatsby-style-guide.md

**Blog posts referencing Spectrum:**

- https://github.com/gatsbyjs/gatsby/blob/64b93455deca40b1872aefbcd5d4a329b2a7d732/docs/blog/100days/apps/index.md
- https://github.com/gatsbyjs/gatsby/blob/831e478f467fed6e5dac56932163bebbb72f7be8/docs/blog/100days/mdx/index.md
- https://github.com/gatsbyjs/gatsby/blob/14ac8fbfb6ca17095abcde2dcd8bb35f32011ba7/docs/blog/100days/start-blog/index.md
- https://github.com/gatsbyjs/gatsby/blob/9b3faa25e9dd93c81e48254ef55e4c53bcba3072/docs/blog/100days/create-themes/index.md
- https://github.com/gatsbyjs/gatsby/blob/9b3faa25e9dd93c81e48254ef55e4c53bcba3072/docs/blog/100days/index.md
- https://github.com/gatsbyjs/gatsby/blob/a62927522d231e1fa7a726d748a8ef3f7db824d9/docs/blog/100days/use-themes/index.md
- https://github.com/gatsbyjs/gatsby/blob/426f1eb4cc82444f09f74c11e0ad3deea27355d1/docs/blog/100days/free-hosting/index.md
- https://github.com/gatsbyjs/gatsby/blob/e42d3ea7998a63d410996c6ffa6d35f07268e05b/docs/blog/100days/accessibility/index.md
- https://github.com/gatsbyjs/gatsby/blob/e42d3ea7998a63d410996c6ffa6d35f07268e05b/docs/blog/100days/seo/index.md
- https://github.com/gatsbyjs/gatsby/blob/2435fb861e8651cf696593b7b4a8980f00a9c430/docs/blog/100days/pwa/index.md
- https://github.com/gatsbyjs/gatsby/blob/b957d3ed6e2b0d07ea581ea426a38ed351e472ea/docs/blog/100days/react-component/index.md
- https://github.com/gatsbyjs/gatsby/blob/91530826f6c491b96a2ca7e9cde9ccebc27e855e/docs/blog/100days/cms/index.md
- https://github.com/gatsbyjs/gatsby/blob/7131cb8b9aae439414f0790638fb4687e2b495ba/docs/blog/100days/gatsby-image/index.md
- https://github.com/gatsbyjs/gatsby/blob/9b3faa25e9dd93c81e48254ef55e4c53bcba3072/docs/blog/100days/comments/index.md
- https://github.com/gatsbyjs/gatsby/blob/9b3faa25e9dd93c81e48254ef55e4c53bcba3072/docs/blog/100days/serverless/index.md
- https://github.com/gatsbyjs/gatsby/blob/a62927522d231e1fa7a726d748a8ef3f7db824d9/docs/blog/100days/performance/index.md
- https://github.com/gatsbyjs/gatsby/blob/9ec02711eb21b4b446c5792a99618e67959e439b/docs/blog/2018-11-11-introducing-gatsby-themes/index.md
- https://github.com/gatsbyjs/gatsby/blob/bc82867cec6076fa83adef4de319e8e6d03beb75/docs/blog/2019-02-27-reactiflux-q-and-a/index.md

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

### PR DESCRIPTION
**Pull request by taylorcjohnson**
## Description

This PR attempts to remove remaining references to the Gatsby Spectrum community in documentation. Currently, it is separated into two commits:
[Removing Spectrum from contributing and README files](https://github.com/gatsbyjs/gatsby/commit/9d9db78326669c83963d869769dcd3dd560c2031)
[Removing Spectrum from #100DaysOfGatsby blog series](https://github.com/gatsbyjs/gatsby/commit/1f8b56d5423d50b01a5fe43f4c7521ee2d3a822e)

I have two outstanding questions:
Is it appropriate for this PR to remove the Spectrum reference from already published blog posts (_i.e._, the second commit)?

If so, there are two additional blogs posts (not yet included in the PR) where Chris Biscardi introduces Gatsby themes and specifically discusses the `gatsby-themes` channel in Spectrum (not simply linking out to them) - could someone suggest how (or if) I should modify these? Thank you in advance!

1. https://github.com/gatsbyjs/gatsby/blob/9ec02711eb21b4b446c5792a99618e67959e439b/docs/blog/2018-11-11-introducing-gatsby-themes/index.md
2. https://github.com/gatsbyjs/gatsby/blob/bc82867cec6076fa83adef4de319e8e6d03beb75/docs/blog/2019-02-27-reactiflux-q-and-a/index.md

### Documentation

Not applicable - this PR does not change/add any code that would require documentation

## Related Issues

Fixes #26351

### CODE REVIEW

**Comment by AishaBlake** [comment]
Hey, @taylorcjohnson! Thanks for following up on this! I generally prefer not to mess with blog posts once they've been published but I'll tag @mgienow in here for the final word. Once she's made a call, one way or the other, I'll be happy to review this.

**Comment by taylorcjohnson** [comment]
Sounds great @AishaBlake - that completely makes sense. Looks like the build failed due to dependency issues anyway (not sure why exactly), so I may wait until the final verdict and start over with a fresh fork 🤷?

Apologies for the triple reviewer request! Didn't realize GitHub would automatically add those maintainer groups with you already in them! 🤦

**Comment by muescha** [comment]
personally i would expect that blogpost get updated with with small bug fixes or generic information changes like the spectrum link.

**Comment by AishaBlake** [comment]
> personally i would expect that blogpost get updated with with small bug fixes or generic information changes like the spectrum link.

In this specific case, yes, I'd agree. Regardless, I'd like to run this by Michelle. @taylorcjohnson, I appreciate you breaking this up into the two commits. Either way, this should be a smooth change!

**Review by LekoArts — APPROVED** [review]
I talked to @mgienow and while doing that realized that the blog posts are stored in WordPress now anyways (the live ones), so changing the markdown files here only helps when people browse the repository on their own.

I'll file an internal ticket to update the posts in WordPress. I also replaced Spectrum with our AskGatsbyJS twitter account in both READMEs

**Pull request merged**
