### PR TITLE
Remove the other comment as well

### PR DESCRIPTION
**Pull request by smakosh**
## Description
Same as https://github.com/gatsbyjs/gatsby/pull/13749

### CODE REVIEW

**Comment by DSchau** [comment]
Let's carry over the work from this to #13749, as they're very much linked and should be co-located.

**Comment by smakosh** [comment]
You could have just merged this into the base branch set here

**Comment by DSchau** [comment]
@smakosh sorry, what exactly do you mean?

**Comment by smakosh** [comment]
Check the base branch that this will get merged into

**Comment by DSchau** [comment]
Ah - yeah, you're right! Sorry - not usually a practice many follow--but thank you!

**Comment by smakosh** [comment]
YW

**Pull request closed without merging**
