### PR TITLE
(#7113): Add short link section to tutorial part one

### PR DESCRIPTION
**Pull request by amberleyromo**
Adds back an abbreviated section on linking within Gatsby sites.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 6643cf89ecb137503662e5c25f78ae30fdce2dbe

https://app.netlify.com/sites/using-postcss-sass/deploys/5b69bfc2b312740a0b5ab0f2

**Comment by KyleAMathews** [comment]
Could you restore please the original flow where you created a link to a new page? I think it's important to familiarize people with the dev 404 page + that adding pages is really seamless/easy.

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 6643cf89ecb137503662e5c25f78ae30fdce2dbe

https://app.netlify.com/sites/gatsbyjs/deploys/5b69bfc1b312740a0b5ab0e6

**Comment by amberleyromo** [comment]
@KyleAMathews my thinking was that since we had already gone through creating a new page, this part could be abbreviated, but i certainly can.

**Comment by KyleAMathews** [comment]
Check out how the tutorial works now https://www.gatsbyjs.org/tutorial/part-one/#linking-between-pages

**Comment by amberleyromo** [comment]
@KyleAMathews I'm actually seeing errors creating a link to a non-existent page, trying to 404 -- perhaps a bug with the reach/router integration.

screen shot 2018-08-07 at 10 30 16 am

**Comment by KyleAMathews** [comment]
hmm this must have got broken in the recent refactors... lemme look

**Comment by KyleAMathews** [comment]
Just tested it with the latest beta and it worked:

My `src/pages/index.js` looks like:

```jsx
import React from 'react'
import Layout from '../components/layout'
import { Link } from 'gatsby'

class IndexPage extends React.Component {
  render() {
    return (
      <Layout>
        <h1>yo</h1>
        <Link to="/about/">About</Link>
      </Layout>
    )
  }
}

export default IndexPage
```

Then I click on the about link and see:

screenshot 2018-08-07 18 39 20

**Comment by amberleyromo** [comment]
It's strange, I tested a fresh v2 default-starter site (worked), and fresh v2 hello-world site (still seeing the same error). confirmed they're both using the same version...

**Comment by amberleyromo** [comment]
Alright, the hello-world starter doesn't come with a 404 file like the default starter does.

In v1, the default/develop 404 page will show, even if there's no 404 page file. In v2, without a 404 page, I get the errors shown above.

**Comment by KyleAMathews** [comment]
Yeah, it was a bug — fix here: https://github.com/gatsbyjs/gatsby/pull/7140

**Comment by KyleAMathews** [comment]
This shouldn't have been merged https://github.com/gatsbyjs/gatsby/pull/7114#issuecomment-411107266

Please redo the flow @amberleyromo in another PR

**Comment by amberleyromo** [comment]
I had pushed the changes we discussed after the 404 fix -- was there something else, too?

**Comment by KyleAMathews** [comment]
Oh it had changed. I'd expected you'd ask me for another review once you'd finished making changes. Since you hadn't, I assumed nothing had changed. Nvm then.

**Comment by amberleyromo** [comment]
Sorry, we had talked about it in standup-- miscommunication.

**Comment by KyleAMathews** [comment]
Nah it looks good. But generally when someone asks for changes, you should ping them again once you're done to get another review.

**Pull request merged**
