### PR TITLE
feat(gatsby-cli): move progressbar into ink

### PR DESCRIPTION
**Pull request by wardpeet**
## Description
Moving progressbar into reporter so it's part of the reporter and not a seperate package. A seperate package like we have now doesn't play well with ink-cli. This will also make the move easier to structured logging and a json formatter.

## Related Issues
#11076

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@wardpeet can you post a gif of how this looks now?

**Comment by wardpeet** [comment]
old behaviour: (you can see how it's fighting for real estate in the cli)
old-progressbar

new behaviour:
ink-progressbar

**Comment by wardpeet** [comment]
it looks like ink has some issues repainting on windows, unsure how it behaves on mac/linux.

**Comment by m-allanson** [comment]
@Ward This looks good! Did you find any more info about the Windows repainting issue?

**Comment by wardpeet** [comment]
I think it's an issue with ink and nothing we can do about. It mostly happens when to activities are running.

**Comment by sidharthachatterjee** [comment]
@wardpeet Shall we open an issue in ink for this? Is this a blocker or can we merge this in for now?

**Comment by wardpeet** [comment]
it's not a blocker, i'll write an upstream issue. It's still better what we have now.

**Comment by sidharthachatterjee** [comment]
Published in `gatsby-cli@2.6.8`

**Pull request merged**
