### PR TITLE
fix(gatsby): Ensure that bootstrapped .cache is writable [fixes #19555]

### LINKED ISSUE #19555: gatsby breaks when .cache has been created from read-only node_modules
## Description

To ensure reproducibility of my build environments, I'd like to package my build dependencies with Nix package manager. This has the side-effect of `node_modules` becoming read-only to ensure immutability for integrity and security (technically it gets located under read-only mount).

Unfortunately, gatsby expects files under `node_modules` have writable mode when it copies files into its `./cache`, resulting in errors like the following:

```
gatsby build
success open and validate gatsby-configs - 0.021s
success load plugins - 0.021s
success onPreInit - 0.007s
success delete html and css files from previous builds - 0.015s
success initialize cache - 0.009s

 ERROR 

EACCES: permission denied, open '/.../.cache/api-runner-browser-plugins.js'
```

### Steps to reproduce

Make node_modules not longer writable, for example on Linux with

```
chmod u-w -R node_modules
```

### Expected result

Gatsby should ensure that files it copies under `./cache` are writable (removable) after it has been copied them, and run just fine.

### Actual result

Gatsby creates `.cache`, but populates it with read-only files failing to replace them later in build (either by unlinking or opening them in writable mode as in below):

```
gatsby build
success open and validate gatsby-configs - 0.021s
success load plugins - 0.021s
success onPreInit - 0.007s
success delete html and css files from previous builds - 0.015s
success initialize cache - 0.009s

 ERROR 

EACCES: permission denied, open '/.../.cache/api-runner-browser-plugins.js'
```

### Environment

```
  System:
    OS: Linux 5.3 NixOS 19.09.976.c75de8bc12c (Loris) 19.09.976.c75de8bc12c (Loris)
    CPU: (4) x64 Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz
    Shell: 4.4.23 -   Binaries:
    Node: 10.16.0 - 
    Yarn: 1.17.3 - 
    npm: 6.9.0 -
  Languages:
    Python: 3.7.5 -
  Browsers:
    Firefox: 70.0b2
```

### PR DESCRIPTION
**Pull request by datakurre**
See: https://github.com/gatsbyjs/gatsby/issues/19555

gatsby expects that files under `node_modules` have writable mode when it bootstraps its `./cache`, resulting in errors when then source is not writable, resulting in errors like:

```
gatsby build
success open and validate gatsby-configs - 0.021s
success load plugins - 0.021s
success onPreInit - 0.007s
success delete html and css files from previous builds - 0.015s
success initialize cache - 0.009s

 ERROR 

EACCES: permission denied, open '/.../.cache/api-runner-browser-plugins.js'
```

This patch is my current workaround to ensure writable `.cache` even when `node_modules` was not writable. You could be able to figure something better and more complete.

Just using `chmodr` could be easier, but that would introduce a new dependency.

I don't know how this level of things could be automatically tested with the current CI. (For manual test `chmod a-w -R node_modules` should work fine.)

I'm aware that this is a marginal issue, but to have "live preview" on-premises without the cloud, one needs to run `gatsby develop` on a server, and I'd prefer not to allow the process to rewrite `node_modules` if possible.

### CODE REVIEW

**Comment by pieh** [comment]
Is it just `.cache/api-runner-browser-plugins.js` that's is being problematic? Maybe instead we could catch trying to overwrite to it and delete it and create new one instead of pre-emptively changing file permissions as this is not needed in 99% of cases?

**Comment by datakurre** [comment]
@pieh It is not just about `api-runner-browser-plugins.js`, but about any file under `.cache` that is bootstrapped from read-only `cache-dir` and needs to be modified, overridden or deleted later. I assume those kind of tasks may happen anywhere in gatsby code base, so this would be harder to fix later.

If indeed this is considered a bug at all, this might be a bit philosophical Issue...

To phrase this other way, the problem is that GatbyJS expects that files under the installed gatsby package have the same file permissions as in the distribution package. This is not a problem with npm or yarn, but only with immutable packaging / deployment solutions like [Nix](https://nixos.org/nix/).

JS community in general seems to consider node_modules part of every project and as mutable as the project itself.

But while I am on this, I can add check for writability and only do chmod if the copied file is not writable.

**Comment by pieh** [comment]
> @pieh It is not just about `api-runner-browser-plugins.js`, but about any file under `.cache` that is bootstrapped from read-only `cache-dir` and needs to be modified, overridden or deleted later.

Right, but most of the files there will be read only and only very few would be written to (`api-runner-browser-plugins.js` for sure being one, as we do write plugins in pluginOptions there). We do also create some new files there, but those shouldn't be impacted by read-only permission from files copied from `node_modules/gatsby/cache-dir`.

Alternatively (much more involved PR) we would be to avoid copying files to `.cache` from `node_modules` completely, but this would require some webpack magic to make it work, so I wouldn't say it's in scope for this change.

**Comment by datakurre** [comment]
> Right, but most of the files there will be read only and only very few would be written to (api-runner-browser-plugins.js for sure being one, as we do write plugins in pluginOptions there). We do also create some new files there, but those shouldn't be impacted by read-only permission from files copied from node_modules/gatsby/cache-dir.

I stand corrected. You are right that it would be enough to delete `.cache` files before updating, but that would still require ensuring that all directories copied from `cache-dir` to `.cache` are writable :thinking: .

So, is it really that so few files are overwritten that fixing those places would be better? I could look into that. (In addition to ensuring that directories are writable.)

**Comment by pieh** [comment]
> So, is it really that so few files are overwritten that fixing those places would be better? I could look into that. (In addition to ensuring that directories are writable.)

We can pro-actively try to make them writeable - so in this case we can prooactively `chmod` just `api-runner-browser-plugins.js`? (and whatever else is needed)? I just don't want too much I/O overhead when in 99% of cases (non-Nix), it won't be needed

**Comment by datakurre** [comment]
@pieh So, if I refactor this pull in a way it does minimal amount of extra I/O-calls, you could review and maybe support this? That would be cool. I can do that and ping you once I’ve updated this (in two weeks).

**Comment by pieh** [comment]
> Since these chmod-calls would be done only when bootstrapping cache and the amount of touched files/folders is constant, this should result in very little io-overhead.

Sure, point about overhead is mostly because it's unnecessary for majority of users, and each time we add a little overhead to support "niche" cases this adds up. 

I feel like it would just be nicer if those calls:
```
fs.writeFileSync(
    `${siteDir}/api-runner-browser-plugins.js`,
    browserAPIRunner,
    `utf-8`
  )
  fs.writeFileSync(`${siteDir}/api-runner-ssr.js`, sSRAPIRunner, `utf-8`)
```

In bootstrap could use some wrapper that would first try write and if it fails, then try to chmod and re-try etc. Then 99% of users are not affected, and Nix users aren't blocked?

**Comment by vladar** [comment]
@datakurre Do you plan to continue with this PR or should we close it for now and have you start a new one when you get back to this?

**Comment by datakurre** [comment]
@vladar I’ll open a new on with a reference to this. Thanks for caring 👍

**Pull request closed without merging**
