### PR TITLE
Blog add author greg thomas

### PR DESCRIPTION
**Pull request by mgienow**
(blog) setting up new author in the db

### CODE REVIEW

**Comment by laurieontech** [comment]
Can we make this part of the blog PR itself?

**Comment by mgienow** [comment]
I tried that first. But it seems like the build was feeling because Greg didn’t yet exist as an author. logically it seemed that it made sense to do a separate branch, add avatar and yaml , commit, PR. then push the branch with the blog post itself that would be calling upon these assets.

**Comment by laurieontech** [comment]
It looked like the other PR got closed?

**Comment by mgienow** [comment]
I closed the original PR because it kept failing

**Comment by mgienow** [comment]
This one is live, though. The avatar is failing for some reason. I ran the linter.

**Comment by laurieontech** [comment]
Duplicate of #22671

**Pull request closed without merging**
