### PR TITLE
Fix/square starter features file

### LINKED ISSUE #21635: bug(www): square-starter causing validation errors
## Description

The recently added square-starter is causing a validation error:

https://github.com/gatsbyjs/gatsby/runs/459451213

Please fix this error by removing the invalid tags or adding a new tag to categories.yml.

### PR DESCRIPTION
**Pull request by jonniebigodes**
This pr fixes #21635

What was done:
- Added a new category to the `categories.yml` to include Square.
- Updated the `gatsby-square-starter` to fix the issue introduced.

Feel free to provide feedback

### CODE REVIEW

**Comment by jonniebigodes** [comment]
It seems that once again the contentfull starter is causing havok with the pr. Despite the fix applied by @laurieontech in the starter submission and me once more updating my gatsby fork .

**Comment by wardpeet** [comment]
@gatsbyjs/learning How do we feel about bundling all eCommerce categories the same as we do with CMSes? Maybe we should just put them under the eCommerce namespace instead as we probably don't have too many.

```
eCommerce:shopify
eCommerce:square
```

**Comment by laurieontech** [comment]
@wardpeet that feels reasonable, let me know who you'd like to implement that

**Comment by laurieontech** [comment]
Also, this starter will still fail as Serverless is not a valid category for starters. So we should address that in this PR as well.

**Comment by laurieontech** [comment]
I'm thinking we can solve the potential category changes elsewhere and would like to get this in to fix the current breaking tests for other PRs.

**Comment by jonniebigodes** [comment]
@laurieontech once again thank you for the fix. I'm going to delete the branch as it's no longer necessary and prevent the repo from having unecessary stale branches.

**Pull request merged**
