### PR TITLE
WIP: [gatsby-source-filesystem] add relative path from project root

### PR DESCRIPTION
**Pull request by chaseadamsio**
On my blog (and on other websites I've seen) there's a "view this on (Github|Gitlab)" where it points to the path on the VCS that the project uses. As an example:

"View https://gitlab.com/chaseadamsio/chaseadamsio.gitlab.io/src/content/articles/2013/3-resources-for-sharing-code-snippets.md on Gitlab"

I looked at the Docs site to both see if this is currently available or if there's an example in the source itself, but I didn't see anything similar.

This PR adds an extra exported property on the fileNode called `relativePathToProjectRoot` that would have the path of the file relative to the project root (wherever `package.json` lives) like this:

```
src/content/articles/2013/3-resources-for-sharing-code-snippets.md
```

I'm not opinionated on what it's called, but I find it's useful and it'd be awesome if Gatsby exported this property for the `gatsby-source-filesystem` plugin.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 719967f2d700ccfbd1da6c2233c5057f9ee43621

https://app.netlify.com/sites/using-postcss-sass/deploys/5b610438c6aed66338762f7f

**Comment by pieh** [comment]
What about way it's done on gatsbyjs.org? https://github.com/gatsbyjs/gatsby/blob/5dfd4d3335493fa1fac1a858e1f6e17331ce572c/www/src/components/markdown-page-footer.js#L93-L95

**Comment by chaseadamsio** [comment]
I can see how that works as a solution, but to me it feels clunky and more prone to user error than if there was a property that leveraged the file system path that the plugin already has for something related to "I want to have the full parent path relative to the repo route". 

I want to point out that this isn't a unique request, this is exposed by the other 2 most common static site generators that use the filesystem:

- **Hugo** exposes ([`File.Path`](https://gohugo.io/variables/files/)).
- **Jekyll** exposes ([`page.path`](https://jekyllrb.com/docs/variables/)).

Is there anyway it could still be implemented? Like I said earlier, I'm not tied to the name of the property but it seems like an easy property to add that would help others looking to switch from another JAM/static site generator tool.

**Comment by pieh** [comment]
@chaseadamsio You defenitely have good point - let's continue with Your approach. My only concern is finding out proper name for that field, because `relativePathFromProjectRoot` is little verbose, but not sure if we can find better one, given that `relativePath` is already used to for path relative to one we set in gatsby-config

**Comment by pieh** [comment]
How about making `relativePath` field to accept arguments (which would need some refactor)
so you could use:
`relativePath` (same behaviour as now - relative to path set in gatsby-config)
`relativePath(to:ProjectRoot)` to get value You are after in this PR?

**Comment by chaseadamsio** [comment]
What about renaming the `relativePathFromProjectRoot ` variable to `filePath`? It's still (accurately) descriptive, short and doesn't require a refactor of an existing property?

**Comment by pieh** [comment]
Yeah, or even just `path` :) I like direction where this is going

**Comment by chaseadamsio** [comment]
I'm happy to use `path` but it seems like it might need some explaining...does leaving `file` make it more clear?

**Comment by pieh** [comment]
> I'm happy to use path but it seems like it might need some explaining...does leaving file make it more clear?

Yeah, let's settle on `filePath` 👍

**Comment by KyleAMathews** [comment]
We could go one further and automatically look at the `.git/config` settings to find where the file is hosted and add a field with the link to the file on github/gitlab/etc.

**Comment by chaseadamsio** [comment]
I'm leveraging netlify's branch env variable to compose it correctly per in a build, is there an easy way to do that without adding the overhead of doing a git inspection at build time? 

reading the config would give you the first part, what's exposed in this PR gives you access to the third part but I'm not sure of a good way to do the second/middle part.

**Comment by KyleAMathews** [comment]
It'd be extremely quick. You'd just read one file and parse it. There's probably an npm package that does the dirty work. We can make this lazy and memoized too.

Actually yeah, there is a repo https://www.npmjs.com/package/git-info

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 38c0dfcffa90ebbdc0b683f8b73ded6fd03b2433

https://app.netlify.com/sites/gatsbyjs/deploys/5b68571bb312740fc77976fc

**Comment by chaseadamsio** [comment]
Gonna clean up my PR and PR it as a new PR. Sorry for the mess.

**Comment by KyleAMathews** [comment]
Deploy preview for *using-jss* failed.

Built with commit 8d21d8888b8642e93c79777febf962345b9b4444

https://app.netlify.com/sites/using-jss/deploys/5b6d19cc82d3f17412405199

**Pull request closed without merging**
