### PR TITLE
fix(gatsby): Fix matchpath ordering

### PR DESCRIPTION
**Pull request by sever1an**
## Description
Path matching should always chose the most specific match, such that paths like `/app/static-page` should be chosen over `/app/*`. There is presently a regression where `/app/*`  is chosen over `/app/<index.js>`, which is actually just `/app/`.

In this commit ( https://github.com/gatsbyjs/gatsby/commit/6c64948edf547b59bf68133956f6be55954f7735#diff-ac5196f8e8e35e4455b30b9164e3c45b ), the way static pages are handled within match paths was changed, such that any static page within the domain of a glob (`*`) match path is given its own entry in `.cache/match-paths.json`. To allow for static pages to take precedence the over glob paths, the order of this file is important... more specific routes must be tested before less specific ones. 

The order of entries in `.cache/match-paths.json` is ultimately determined by `packages/gatsby/src/bootstrap/requires-writer.js`.

Paths are assigned a score based on how specific they are by basically counting slashes, but the trailing slash is removed first. For an index page the trailing slash is significant, as it implies /index. Globs like `/*` and `/app/*` initially score one point higher than `/` and `/app/` then are equal after a bonus for no `*`. Yes, this might even present undefined behavior. Removing a trailing `*` along with the trailing `/` puts glob paths at the equivalent level of an index page with removed slash instead of a child page during the initial scoring, then the index gains a point for not having a `*`. I believe that this always places glob paths after static pages that they might shadow. It should also maintain the relative order of specificity among different glob paths. For example `/app/stuff/*` should be chosen over `/app/*` and `/*`.

## Related Issues

I believe that this a regression which will break existing apps when `gatsby` is updated. The author of 17980 discovered it with CI testing.

Fixes https://github.com/gatsbyjs/gatsby/issues/17980

### CODE REVIEW

**Comment by wardpeet** [comment]
Hey, codewise this looks good. I couldn't reproduce the bug. Do you have a reproduction?

**Comment by sever1an** [comment]
I have created two reproductions

This one shows an error on the path `/app/` https://github.com/sever1an/match-path-error/tree/folder-error

This one shows an  error on `/` and generates the wrong `match-paths.json` , but for some reason the `/*` route matches everything with `gatsby serve`
https://github.com/sever1an/match-path-error/tree/root-error

```javascript
[
    {
        "path": "/404.html",
        "matchPath": "/404.html"
    },
    {
        "path": "/zapp-glob/",
        "matchPath": "/app/*"
    },
    {
        "path": "/app/",
        "matchPath": "/app/"
    },
    {
        "path": "/404/",
        "matchPath": "/404/"
    },
    {
        "path": "/root-glob/",
        "matchPath": "/*"
    },
    {
        "path": "/",
        "matchPath": "/"
    }
]
```

**Comment by sever1an** [comment]
Having the `/*` match everything in the root-error branch is bothering me a bit, any ideas why this would happen?

**Comment by JustFly1984** [comment]
Is there any movement?

**Comment by sever1an** [comment]
@wardpeet Were you able to use the reproduction?

**Comment by JustFly1984** [comment]
Can you please merge this PR and publish?

**Comment by JustFly1984** [comment]
I'm sorry to buzz, but 5 of my projects having bugs, which will be fixed with this commit

**Comment by sever1an** [comment]
Have you tested this branch on your codebase?

**Comment by sever1an** [comment]
@JustFly1984 Have you pulled and tested this branch with your projects?

**Comment by JustFly1984** [comment]
@sever1an how can I test this branch in my project?

**Comment by JustFly1984** [comment]
is there any movement?

**Comment by pieh** [comment]
Published `gatsby@2.17.3`

**Comment by JustFly1984** [comment]
Thank you, it solved my issues with 404

**Pull request merged**
