### PR TITLE
fix(gatsby): add pages to saved redux state

### LINKED ISSUE #26520: createPages uses stale cached data for "previous" and "next" pages
## Description

I noticed this on my own blog's "previous post" and "next post" links, and it's reproducible on `gatsby-starter-blog`. It may have broader implications beyond my use case as well.

If you have links to "previous" and "next" posts on each blog post's page, then those are not updated on each build. As you add posts, they remember their cached "previous" link, but are never updated with the "next." If a post is removed, then existing "previous/next" links are preserved. (And its page will still exist in the build.)

### Steps to reproduce

I made a sample repo (almost identical to `gatsby-starter-blog`): https://github.com/johnridesabike/gatsby-prev-next

```
git clone https://github.com/johnridesabike/gatsby-prev-next.git
cd gatsby-prev-next
gatsby build
```

If you serve the built site, everything should be normal. The next part is where the problem happens:

```
mv test-post content/blog/test-post # add a new post
gatsby build
gatsby serve
```

### Expected result

The build should use up-to-date data in regards to "previous" and "next" links.

### Actual result

If you open the new built site, the new post ("Test Post") should be present. The previous post ("New Beginnings") does _not_ link to it. Clearing the cache fixes the problem:

```
gatsby clean
gatsby build
gatsby serve
```

The site should build as expected.

But now, if you remove the `content/blog/test-post` directory, and run `gatsby build`, "Test Post" won't appear on the index page but the "New Beginnings" post will still link to it (and the "Test Post" page will still exist in the build.)

### Additional information

I played around a bit trying to figure out how to bust the stale data, but with no luck. One thing I noticed is that the `createPages` function uses this logic to generate the `previous` and `next` data:

```js
const previous = index === posts.length - 1 ? null : posts[index + 1].node
const next = index === 0 ? null : posts[index - 1].node
```

I tried to update it to use a GraphQL query instead:

```diff
{
  allMarkdownRemark(sort: {fields: [frontmatter___date], order: DESC}, limit: 1000) {
    edges {
      node {
        fields {
          slug
        }
        frontmatter {
          title
        }
      }
+      previous {
+        fields {
+          slug
+        }
+        frontmatter {
+          title
+        }
+      }
+      next {
+        fields {
+          slug
+        }
+        frontmatter {
+          title
+        }
+      }
    }
  }
}
```

This had no effect. The stale cache was still used.

If it's not feasible to make the caching "smart" enough for this scenario, it would be also good if `createPages` had the ability to manually use or override the cache, as well as delete cached pages after their source data has been deleted.

### Environment

```
  System:
    OS: macOS 10.15.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.41 => 2.24.41 
    gatsby-image: ^2.4.15 => 2.4.15 
    gatsby-plugin-feed: ^2.5.11 => 2.5.11 
    gatsby-plugin-google-analytics: ^2.3.13 => 2.3.13 
    gatsby-plugin-manifest: ^2.4.22 => 2.4.22 
    gatsby-plugin-offline: ^3.2.23 => 3.2.23 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sharp: ^2.6.26 => 2.6.26 
    gatsby-plugin-typography: ^2.5.10 => 2.5.10 
    gatsby-remark-copy-linked-files: ^2.3.12 => 2.3.12 
    gatsby-remark-images: ^3.3.25 => 3.3.25 
    gatsby-remark-prismjs: ^3.5.10 => 3.5.10 
    gatsby-remark-responsive-iframe: ^2.4.12 => 2.4.12 
    gatsby-remark-smartypants: ^2.3.10 => 2.3.10 
    gatsby-source-filesystem: ^2.3.24 => 2.3.24 
    gatsby-transformer-remark: ^2.8.28 => 2.8.28 
    gatsby-transformer-sharp: ^2.5.12 => 2.5.12 
  npmGlobalPackages:
    gatsby-cli: 2.12.66
```

### LINKED ISSUE #28281: Cache is not invalidated when programatically build pages and the data is changed
## Description

I am using Netlify CMS with markdown files and generating pages from certain collections. When the data for an entry in the collection changes the page is not updated with new data after the build. The site is deployed in Netlify and a caching plugin is used to persist cache between builds for faster builds.

### Steps to reproduce

Use Netlify CMS with markdown files and build pages in gatsby-node using a certain collection.

### Expected result

Page data should be updated with the changes.

### Actual result

The page is displaying old data.

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: 1.22.1 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
  Languages:
    Python: 3.8.5 - /Users/macintoshhd/.pyenv/shims/python
  Browsers:
    Chrome: 86.0.4240.198
    Firefox: 72.0.2
    Safari: 14.0
  npmPackages:
    gatsby: ^2.27.1 => 2.27.1 
    gatsby-image: ^2.3.1 => 2.6.0 
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1 
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2 
    gatsby-plugin-manifest: ^2.3.3 => 2.7.0 
    gatsby-plugin-netlify: ^2.6.0 => 2.6.0 
    gatsby-plugin-netlify-cms: ^4.5.0 => 4.5.0 
    gatsby-plugin-offline: ^3.1.2 => 3.5.0 
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^3.2.1 => 3.5.0 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.3 
    gatsby-plugin-sass: ^2.2.1 => 2.6.0 
    gatsby-plugin-sharp: ^2.5.3 => 2.9.0 
    gatsby-plugin-sitemap: ^2.3.2 => 2.7.0 
    gatsby-remark-images: ^3.2.2 => 3.6.0 
    gatsby-source-filesystem: ^2.2.2 => 2.6.1 
    gatsby-transformer-remark: ^2.7.1 => 2.11.0 
    gatsby-transformer-sharp: ^2.4.3 => 2.7.0

### PR DESCRIPTION
**Pull request by redabacha**
## Description

it looks like pages is needed for gatsby to figure out if the page context has been modified since the last build: https://github.com/gatsbyjs/gatsby/blob/2e3ec895a227c8de5a7d8c69e92548c935c0fdcc/packages%2Fgatsby%2Fsrc%2Fredux%2Factions%2Fpublic.js#L399-L401

but pages isn't included during saveState 🤔 

## Related Issues

fixes #28281 
fixes #26520

### CODE REVIEW

**Comment by pieh** [comment]
Hey @redabacha!

This is implementation of the fix is pretty unsafe to do, due to some sites putting enourmous amount of data via page context. This can cause cache persistance to not work at all in those cases (and actually cause fatal, unrecoverable crashes). We had issues like that before when persisting `nodes` which forced us to chunk what we save ( https://github.com/gatsbyjs/gatsby/pull/21555 ), but that chunking wouldn't be covered for `pages`.

We do have idea how to solve this by persisting not entire page objects, but rather just some "hash" generated from page context. So instead of comparing contexts between old page and new page, we would compare newly generated hash with hash stored for previous page. This will require adding seperate reducer (something like `pageContextHashes`), that would react to `CREATE_PAGE` and `DELETE_PAGE` actions (to keep it in sync with actual pages that are alive).

`createPage` action should generate this hash and provide it when emitting `CREATE_PAGE` action as part of payload that will be stored in this new reducer.

Then it would be only matter of adding the new reducer state to list of things we persist (so similar as you did in your PR, just not entire `pages` slice of state)

**Comment by pieh** [comment]
Oh - and lastly - this should also allow us to "unskip" this test scenario - https://github.com/gatsbyjs/gatsby/blob/2e68af883ccdcf2e80eecda90aadeaf16449ad48/packages/gatsby/src/query/__tests__/data-tracking.js#L809

**Comment by redabacha** [comment]
hi @pieh 

thanks for the explanation, it makes much more sense now. we also store most of our data via page context when building the site (https://www.hollandandbarrett.com/) so i'm glad this issue is being thought about. as it stands currently, upgrading to gatsby (to 2.26+ i think) is not feasible due to this bug as the pages do not update when using cache from a previous build.

**Comment by pieh** [comment]
Hey @redabacha - I opened draft PR using idea I menioned in previous comments - https://github.com/gatsbyjs/gatsby/pull/28351 . I did found some extra considerations that we will need to make (as noted in PR), but it actually did allow me to unskip the test scenario ;)

**Pull request closed without merging**
