### PR TITLE
chore(docs): Reference new ComponentModel component rather than generic LayerModel

### PR DESCRIPTION
**Pull request by AishaBlake**
## Description

After merging #23115, we realized there were a couple of places in the docs still referencing the `LayerModel` component which should now be referencing `ComponentModel`. 

While `LayerModel` was abstracted so that it could be reused in that PR, the documentation on it in `docs-and-blog-components.md` also needed to be updated to reflect the new `ComponentModel`. Notably missing in this PR is documentation on how to construct a _new_ component from `LayerModel`. I don't know how much we necessarily want to encourage that vs make it an _option_, so I left this page pretty much intact.

### CODE REVIEW

**Comment by AishaBlake** [comment]
@gillkyle @laurieontech I don't know if this is a browser cache thing but I'm actually not seeing the `ComponentModel` at all anymore, even on the [Building with Components page](https://www.gatsbyjs.org/docs/building-with-components/). I refreshed and it collapsed. That's on me and we can revert if we need to but I'd rather fix it if we can!

**Comment by AishaBlake** [comment]
I think this is all fixed and ready to go for real this time!

**Comment by marcysutton** [comment]
Hmm, the `<ComponentModel />` sample isn't loading for me. Perhaps it needs to be included through MDX? I'm still seeing some mentions of `<LayerModel />` locally, should those have been renamed as well?

**Comment by marcysutton** [comment]
I will admit I'm pretty confused by the name change, as the word `Component` is overloaded by using it in this way. And from looking at the source code more closely, the `ComponentModel` returns a `LayoutModel`? I still wonder if there's a missing reference to make that component available to the Docs and Blog Contributions page since it won't render. No errors at build time, though there are a few in the browser console.

**Comment by gillkyle** [comment]
It seems to render just fine on the build: https://build-6aab64c3-30ca-4f64-b613-395649f1348e.gtsb.io/docs/using-gatsby-image/ (I'm looking here)

The only exception I do see is this behavior where the titles are rendered as `{title}` instead of their proper values that appears to be a side effect of Lingui I'd guess 🤔:

image

Seems to be happening on both models:

image

**Comment by marcysutton** [comment]
Weird, thanks @gillkyle! I can clear my cache to test again locally, I've had issues with MDX and caching in the past, but it usually throws an error. This will take a long time to rebuild...

**Comment by AishaBlake** [comment]
And _I'm_ seeing it with the correct titles as of that last commit. 🤔

**Comment by AishaBlake** [comment]
Just so that we have this in the PR itself, it seems like we're currently seeing different things in different environments. All components are currently loading properly for me locally and Marcy is unable to see _any_ of the components listed in `/contributing/docs-and-blog-components.md` render on this branch or master. :/

**Comment by laurieontech** [comment]
Looked at this this morning and it's rendering fine for me. I assume we'd like to get translations working before we push it? Or did we want to solve the fact that it's broken at the moment and then open an issue/PR for translating it?

**Comment by AishaBlake** [comment]
I’m inclined to say fix  what’s broken and document the change, then translate.

**Comment by laurieontech** [comment]
Opened the issue and going to merge this since 1. It's broken and 2. The original version wasn't translated either, so this does not lose any existing functionality.

**Comment by marcysutton** [comment]
I'm not seeing a fix on the contributing docs (Components aren't rendering), should this be updated by now?

**Comment by marcysutton** [comment]
Oops, disregard my last comment – I was looking at the wrong thing. All good!

**Pull request merged**
