### PR TITLE
chore(showcase): Add `gabrielgiordano.com` to the showcase

### PR DESCRIPTION
**Pull request by gabrielgiordan**
Add my open-sourced personal [Gatsby site](https://gabrielgiordano.com) to the showcase.

[Source code](https://github.com/gabrielgiordan/gabrielgiordano.com)

### CODE REVIEW

**Comment by gabrielgiordan** [comment]
> Do you think you can add more information to the file structure of the README.md in https://github.com/gabrielgiordan/gabrielgiordano.com

No problem @Ekwuno, what kind of information should I add to the README.md?

**Comment by Ekwuno** [comment]
> > Do you think you can add more information to the file structure of the README.md in https://github.com/gabrielgiordan/gabrielgiordano.com
> 
> No problem @Ekwuno, what kind of information should I add to the README.md?

File structure is the most important.

**Comment by gabrielgiordan** [comment]
Hey @Ekwuno, thanks for the feedback. I have provided some updates about the project structure besides adding more information to the README.md. Could you please tell me if those changes are enough?

**Comment by Ekwuno** [comment]
> Hey @Ekwuno, thanks for the feedback. I have provided some updates about the project structure besides adding more information to the README.md. Could you please tell me if those changes are enough?

Looks good now. Thanks.

**Pull request merged**
