### PR TITLE
fix(gatsby-react-router-scroll): Respect hash as source of truth for scroll position

### LINKED ISSUE #25778: Internal anchors with hashes not working
## Description

Internal anchors with hashes stop working after the first click. See the minimal test case repo at https://github.com/ediblecode/gatsby-anchors-issue and demo site at https://frosty-brown-de3460.netlify.app/. Click into page 2 and click the various internal anchors on that page. 

Note: this is using simple anchor tags as per the docs for [gatsby link](https://www.gatsbyjs.org/docs/gatsby-link/#recommendations-for-programmatic-in-app-navigation):

> Neither `<Link>` nor `navigate` can be used for in-route navigation with a hash or query parameter. If you need this behavior, you should either use an anchor tag...

I thought this was fixed by #25749 and released in [2.24.3](https://github.com/gatsbyjs/gatsby/releases/tag/gatsby%402.24.3) but it still seems to be an issue. I think it's related to, if not the same as, #25554, #25745 and #25522. I wonder if it was caused by #24306 (or at least related in some way).

The _first_ anchor seems to be OK but it's definitely something to do with subsquent clicks. *Weirdly* though it's non-determinate: sometimes it will work fine and sometimes it won't and I can't seem to work out the pattern. Looking into it, session storage is used under the hood for the scroll position, so I wonder if it's something to do with that - maybe the key used isn't including the anchor hash or something? Anyway, that's as far as I got with my digging, sorry. Hoping @blainekasten you might be able to take a look as you've looked at the other related issues. Thank you very much.

### Steps to reproduce

1. Clone the gatsby starter
2. Upgrade dependencies to latest via `npx npm-check-updates -u`
    1. This includes Gatsby 2.24.3
4. Run `npm i` to install these dependencies
5. Create a page with hash links to elements on a page with matching ids (see example repo and site)
6. Click the internal hash anchors to try to jump up and down the page.

### Expected result

The URL is updated with the hash, and the page is scrolled to the element with an id matching the hash in the URL.

### Actual result

The first click scrolls to the target element and updates the URL but subsequent clicks only update the URL without moving down the page.

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.11 - C:\Python27\python.EXE
  Browsers:
    Edge: 44.19041.1.0
  npmPackages:
    gatsby: ^2.24.3 => 2.24.3 
    gatsby-image: ^2.4.13 => 2.4.13 
    gatsby-plugin-manifest: ^2.4.18 => 2.4.18 
    gatsby-plugin-offline: ^3.2.18 => 3.2.18 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sharp: ^2.6.19 => 2.6.19 
    gatsby-source-filesystem: ^2.3.19 => 2.3.19 
    gatsby-transformer-sharp: ^2.5.11 => 2.5.11

### PR DESCRIPTION
**Pull request by sidharthachatterjee**
Currently we do not navigate correctly to hashes unless the scroll position is zero. If you're scrolled to any position other than the top, you will need to click twice to scroll to the correct position. This behaviour is completely broken at the moment. 

This PR fixes this (albeit not completely) by _always_ respecting the hash and scrolling to it irrespective of if there is browser scrolling state or not. This is iteratively better than our current behaviour. However, the ideal behaviour (which we ought to handle in a separate PR) is to respect hash except when navigating back in the browser (in which case, we ought to restore scroll position). Reach currently has this bug which we can track at https://github.com/reach/router/issues/228

Closes #25778

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]
This is so much better than before! :100: Let's see if we can fix the reach bug in the future, but this is a massive improvement over users having to double click on links to navigate to anchors.

**Review by mxstbr — APPROVED** [review]

**Comment by KyleAMathews** [comment]
Ooo nice! I'd noticed this too.

**Comment by sidharthachatterjee** [comment]
@KyleAMathews Yeah, it was annoying one. @mxstbr and I paired on this earlier today.

**Comment by sophstad** [comment]
@sidharthachatterjee Thanks for this fix, very much appreciated! Was wondering about this:

> the ideal behaviour (which we ought to handle in a separate PR) is to respect hash except when navigating back in the browser (in which case, we ought to restore scroll position)

Is there an issue/PR where we can track this work? Thanks!

**Comment by blueboxes** [comment]
Has a fix been merged in? I am using gatsby-react-router-scroll 3.7 and still seeing the issue

**Comment by TheDarkStrix** [comment]
Using gatsby-react-router-scroll `gatsby-react-router-scroll": "^3.7.0"` still doesn't fix the issue, is there anything that must be done specific to get this working ?

**Comment by jonathanphz** [comment]
I can also confirm that this is not working using `gatsby-react-router-scroll": "^3.7.0"`

**Pull request merged**
