### PR TITLE
Don't add a forward slash to page path twice

### PR DESCRIPTION
**Pull request by tryzniak**
Hi folks. Here's a fix for #7528. We simply need to omit adding any slashes if a __PREFIX_PATH__ is empty.

### CODE REVIEW

**Comment by m-allanson** [comment]
Thanks @tryzniak! I updated this with an alternate approach.. it should be ok to use `__PATH_PREFIX__` directly without needing any logic around it. 

I haven't had a chance to investigate, but I think as a follow up to this we could maybe remove the urlJoin function too? Something like this:

```diff
- href={urlJoin(__PATH_PREFIX__, script.name)}
+ href={`${__PATH_PREFIX__}/${script.name}`}
```

**Comment by tryzniak** [comment]
Hoping to take a look at this in a few days

**Comment by chasemccoy** [comment]
@KyleAMathews this bug has been popping up for a lot of people and is causing several issues. Could you take a look?

**Comment by tryzniak** [comment]
@m-allanson and folks, I've updated the code to remove `urlJoin`. Not sure I like this version, because now we have to track slashes (if they're present or not in a variable). Maybe we could use `urlJoin` everywhere instead to join/sanitize paths, it would kind of make me feel safer haha.

**Comment by m-allanson** [comment]
Oh hmm, UI tests are failing. I'll check that locally.

**Comment by m-allanson** [comment]
Published as `gatsby@2.0.0-rc.1`

**Pull request merged**
