### PR TITLE
Add a noscript tag for better DX in develop mode with JS disabled

### PR DESCRIPTION
**Pull request by nason**
See #374

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@nason this looks perfect! How's the other PR coming? If you'll finish in the next day or two I'll wait until that's done to do another release otherwise I'll push this out today.

**Comment by nason** [comment]
Hi @KyleAMathews, thanks! I've made some progress on that other task, but have run into a small blocker. I'll write up some details on that issue and see you how you'd like to proceed later this evening.

**Comment by KyleAMathews** [comment]
Released in 0.12.20 https://github.com/gatsbyjs/gatsby/releases/tag/v0.12.20

**Comment by jlengstorf** [comment]
Hiya @nason! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
