### PR TITLE
Fix typo in blog post

### PR DESCRIPTION
**Pull request by sarasate**
Just a typo fix for our `comments` post.

### CODE REVIEW

**Comment by m-allanson** [comment]
Thanks @sarasate! GitHub is reporting a conflict with this PR, I guess your Gatsby fork is outdated? Could you update this PR to just include the typo fix commit.

Also note that Gatsby recently added a requirement that contributors sign-off commits. Could you do `git commit --amend --signoff` and force push the amended commit?

Check out the [new developer sign-off docs](https://www.gatsbyjs.org/docs/how-to-contribute/#developer-certificate-of-origin) or just comment here if you've any questions.

**Comment by m-allanson** [comment]
Actually let me just fix the typo and then I'll close this, that's probably less faff for everyone :)

**Comment by sarasate** [comment]
@m-allanson ah sorry, didn't pay attention to it. sure, fix its, its just one character ;) thanks..

**Comment by m-allanson** [comment]
Handled in #4936. Thanks again @sarasate!

**Pull request closed without merging**
