### PR TITLE
chore(starters): add gatsby-firebase-hosting-starter

### PR DESCRIPTION
**Pull request by bijenkorf-james-wakefield**
## Description

Offering a new starter for Gatsby with Firebase Hosting, Cloud Build deployment, ESlint, Commitizen and Jest Testing Framework

### CODE REVIEW

**Comment by wardpeet** [comment]
Also https://gatsby-firebase-hosting.firebaseapp.com/page-2/ is broken :) Your readme is 👍 💯

**Comment by wardpeet** [comment]
Could you redeploy your site as the link is still broken

**Comment by bijenkorf-james-wakefield** [comment]
> Could you redeploy your site as the link is still broken

Redeployed.

**Comment by wardpeet** [comment]
Awesome! I <3 firebase so I'm really happy to get this merged.

James Wakefield doesn't really sound really dutchy but let me try anyway. "Hartelijk bedankt voor je pull request!"

**Pull request merged**
