### PR TITLE
Adds missing extract-text-webpack-plugin dependancy

### PR DESCRIPTION
**Pull request by danielmahon**
Signed-off-by: Daniel Mahon <danielmahon@users.noreply.github.com>

### CODE REVIEW

**Comment by pieh** [comment]
@erquhart could you check this? You did some work with extract text plugin lately and probably you are most qualified to check this :)

**Comment by danielmahon** [comment]
@erquhart When building a freshly installed project using `gatsby-plugin-netlify-cms`, it complained about missing `extract-text-webpack-plugin`. After installing, the build succeeded. The package is requiring it here: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify-cms/src/gatsby-node.js#L2

**Comment by danielmahon** [comment]
I included the version [recommended here](https://github.com/webpack-contrib/extract-text-webpack-plugin#install) for webpack v1 (which is what Gatsby v1 is currently using right?)

**Comment by erquhart** [comment]
Yep, just include it as a peer dependency instead of as a standard dependency.

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
