### PR TITLE
chore(starters): add gatsby-starter-try-ghost

### PR DESCRIPTION
**Pull request by styxlab**

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! I noticed that this is a theme and not a starter? Did you mean to link to the [starter repo](https://github.com/styxlab/gatsby-starter-try-ghost)?

Also, Casper and Ghost are not supported categories. So we'll want to remove those in order to pass tests.

**Comment by styxlab** [comment]
Thanks for catching the tags, they should be:
    - Blog
    - CMS:Headless
    - SEO
    - Styling:PostCSS

The repo is a starter repo but the starter uses the corresponding theme.

**Comment by laurieontech** [comment]
Great, if you want to go ahead and update the tags we can get this in.

**Comment by styxlab** [comment]
Was not able to merge. Shall I issue a new pull request?

**Comment by styxlab** [comment]
All checks completed.

**Comment by laurieontech** [comment]
Great, thanks!

**Pull request merged**
