### PR TITLE
feat(gatsby-plugin-emotion): upgrade plugin for emotion 10 support

### PR DESCRIPTION
**Pull request by DSchau**

### CODE REVIEW

**Comment by DSchau** [comment]
Ugh, meant to open this vs. my own repo. Closing 😅

**Comment by wKovacs64** [comment]
Aw man, finding this in search results had me excited. 🙂 Is that branch in your fork ready to go, @DSchau? If not, anything I can do to help?

**Comment by DSchau** [comment]
@wKovacs64 feel free to take what I have and run with it! It's _mostly_ done, but it honestly felt a little janky and I wasn't sure if I was doing things in an emotion-recommended way!

**Comment by DSchau** [comment]
This is the most up-to-date changes -> https://github.com/DSchau/gatsby/pull/3/files

**Comment by wKovacs64** [comment]
Anything in particular you felt was unfinished? I upgraded one of my Gatsby sites to v10 using your branch via gatsby-dev and it seemed fine.

**Comment by wKovacs64** [comment]
Moved to #10226

**Pull request closed without merging**
