### PR TITLE
fix for https://github.com/gatsbyjs/gatsby/issues/14

### PR DESCRIPTION
**Pull request by phlogisticfugu**
fix for #14 

using path mangling in glob-pages

### CODE REVIEW

**Comment by phlogisticfugu** [comment]
better fix for https://github.com/gatsbyjs/gatsby/issues/14

**Comment by KyleAMathews** [comment]
Thanks! Published new release 0.2.3.

**Comment by jlengstorf** [comment]
Hiya @phlogisticfugu! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by phlogisticfugu** [comment]
Thanks!  I just ordered a cap + bought some stickers!  go Gatsby!

And joined the organization.

-Brad

**Pull request merged**
