### PR TITLE
Starter showcase card layout update

### PR DESCRIPTION
**Pull request by riencoertjens**

### CODE REVIEW

**Comment by amberleyromo** [comment]
Hi @riencoertjens! Now that the first push for the starter library is out, any interest in revisiting/updating this PR?

**Comment by riencoertjens** [comment]
yes, I'll do it this weekend...

**Comment by LekoArts** [comment]
Hi @riencoertjens :) Do you the time to update your PR? Otherwise I could tackle this. Please let me know, thanks 👍

**Comment by riencoertjens** [comment]
go for it @LekoArts !

**Comment by LekoArts** [comment]
Sorry, my git messed up the rebase. There were so many conflicts ...
@riencoertjens I'd prefer to open up a new PR with a fresh Gatsby branch. Is that ok?

**Pull request closed without merging**
