### PR TITLE
Added github pages docs

### PR DESCRIPTION
**Pull request by dinodsaurus**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 5636d3e9303d99ef1c4d6fccc5b9627e71261da8

https://app.netlify.com/sites/using-glamor/deploys/5a38ef464c4b933b3ba717ea

**Comment by dinodsaurus** [comment]
Deploy failed because it cannot create `.yarn_cache`, it doesn't have permissions 👎

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by shannonbux** [comment]
Hey @dinodsaurus this is awesome, thank you!  I created all the stub article titles and it's so awesome to see people starting to fill them out b/c it will make the process so much faster. Looking forward to your future PR's! :D 🎁 😸 🙌

**Comment by jlengstorf** [comment]
Hiya @dinodsaurus! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
