### PR TITLE
chore(deps): switch from fast-levenshtein to fastest-levenshtein

### PR DESCRIPTION
**Pull request by hoobdeebla**
Updates [fast-levenshtein](/sindresorhus/p-queue) from [v2 to v3.](https://app.renovatebot.com/package-diff?name=fast-levenshtein&from=2.0.6&to=3.0.0) [No breaking changes.](/hiddentao/fast-levenshtein/commits/master)

### CODE REVIEW

**Review by pvdz — COMMENTED** [review]
This package is essentially now a proxy for `fastest-levenshtein`, while supporting an additional option that we don't use in `gatsby-theme`. Any chance you could update `gatsby-theme` to use `fastest-levenshtein` directly and reduce the stack? :)

**Comment by hoobdeebla** [comment]
It looks like `gatsby` itself doesn't use that option either, so I switched both to use `fastest-levenshtein`. I also removed the DefinitelyTyped definitions as `fastest-levenshtein` ships its own type defs.

**Review by pvdz — CHANGES_REQUESTED** [review]
Yeah that's great.

I'm only missing package.json updates for adding the `fastest-levenshtein` packages, while removing the old package from them.

**Comment by hoobdeebla** [comment]
I changed the package.json for both already - [gatsby-theme](/gatsbyjs/gatsby/pull/27282/files#diff-967a36556f40e89f47ec0bea78f61891), [gatsby](/gatsbyjs/gatsby/pull/27282/files#diff-d42476695f98af8f85d595ac39bc0653)

**Comment by pvdz** [comment]
Huh. Okay, can't argue with that. Not sure why I didn't see it before.

**Review by pvdz — APPROVED** [review]
Awesome, thank you! :purple_heart:

**Pull request merged**
