### PR TITLE
breaking(gatsby-plugin-postcss): Upgrade gatsby-plugin-postcss to PostCSS 8

### LINKED ISSUE #26939: Upgrade gatsby-plugin-postcss to PostCSS 8
## Summary

PostCSS 8 was released. It added a new plugin API. Right now Gatsby does not support PostCSS 8 plugins.

Updating `postcss-loader` and adding `postcss` to dependencies for `gatsby-plugin-postcss` will fix the problem.

[PostCSS 8 changelog](https://github.com/postcss/postcss/releases/tag/8.0.0) does not have breaking changes related to Gatsby only removing Node.js 6 and 8 support).

### PR DESCRIPTION
**Pull request by chlorophyllkid**
## Description

Updating `postcss-loader` and adding `postcss` to dependencies for `gatsby-plugin-postcss`.

## Related Issues
Fixes #26939

### CODE REVIEW

**Comment by chlorophyllkid** [comment]
@LekoArts what are the next steps on this PR? Seems like it just needs a review?

**Comment by moonmeister** [comment]
@chlorophyllkid Thanks for working on this. I believe we would want `postcss` as a `peerDependency`. https://evilmartians.com/chronicles/postcss-8-plugin-migration/#step-1-move-postcss-to-peerdependencies

**Comment by chlorophyllkid** [comment]
Wouldn't that mean the install instructions of the plugin itself would need a change too? 
Because a user then has to install postcss separately?

**Comment by moonmeister** [comment]
Correct. But either way this will be a breaking change. This way we'll be letting people choose the postcss version that's compatible with their plugins.

**Comment by LekoArts** [comment]
Yeah, we'll be releasing a new major version then so the breaking change is okay 👍

**Comment by chlorophyllkid** [comment]
Alright, in that case I'll update the PR later. 👍🏼

**Review by LekoArts — APPROVED** [review]
Thanks for the PR! 👍

**Comment by LekoArts** [comment]
```
Successfully published:
 - gatsby-plugin-postcss@3.0.0
```

**Pull request merged**
