### PR TITLE
fix(gatsby-source-wordpress): handle woocommerce categories and tags

### PR DESCRIPTION
**Pull request by rotexhawk**
Gatsby Source Plugin Crashes with Woocommerce products because `normalize.mapPostsToTagsCategories` function tries to normalize product categories the same way that it does for posts. The problem is that product categories are not ids but instead they are objects so t => tags.find(tObj => t === tObj.wordpress_id).id t never equals tObj.wordpress.id. and we get error, can't get id of undefined

Fixes: https://github.com/gatsbyjs/gatsby/issues/11526

All the tests passed locally and the build passed on a local site with woocommerce installed.

### CODE REVIEW

**Comment by wardpeet** [comment]
@rotexhawk mind sharing an reproduction (private message is fine too) or write a test for it so we can validate

**Comment by rotexhawk** [comment]
@wardpeet I don't know if this is what you meant, but I added a sample product and couple of `wc_categories` and updated the snapshot. Thanks.

**Comment by pieh** [comment]
I'll try to verify this locally

**Comment by pieh** [comment]
Ok, verified that this fixes the woocommerce issues.

I'm actually curious how you made it work @rotexhawk in more production ready env - I had serious problems with auth for WooCommerce and resorted to this hack:
```php
add_filter( 'woocommerce_rest_check_permissions', 'my_woocommerce_rest_check_permissions', 90, 4 );

function my_woocommerce_rest_check_permissions( $permission, $context, $object_id, $post_type  ){
  return true;
}
```
That essentially disable auth/permission check for WooCommerce endpoint, but obviosuly wouldn't advise anyone to use it (as they could edit your product or order data heh)

**Comment by rotexhawk** [comment]
Thanks guys for taking care of this so quickly. @pieh first I used https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/ but it only worked partially. Some endpoints still returned 403. 
So I switched to basic auth and everything worked. https://github.com/WP-API/Basic-Auth

**Pull request merged**
