### PR TITLE
Fix query params not captured in Google Analytics (#4527)

### LINKED ISSUE #4527: Query params not captured in Google Analytics
## Description

Query params not captured in Google Analytics.

### Steps to reproduce

1) Install google analytics plugin
2) Go to the website using a url with query params e.g. `http://www.example.com/?from=abc`
3) Go to google analytics console

### Expected result

If a user goes to my website using a url like this `http://www.example.com/?from=abc`, I expect in my analytics console I would see:
```
Page         Page Views
/?from=abc     123
```

### Actual result
Instead, I can only see the path without the query params:
```
Page         Page Views
/                123
```

### Environment

* Gatsby version (`npm list gatsby`): ^1.9.223
* gatsby-cli version (`gatsby --version`): 1.1.29
* Node.js version: v6.11.0
* Operating System: --

### PR DESCRIPTION
**Pull request by longsangstan**
fix #4527

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Nice! You want to add location.hash as well? e.g. https://stackoverflow.com/a/4813223/182702

**Comment by longsangstan** [comment]
Good, added location.hash too.

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by jlengstorf** [comment]
Hiya @longsangstan! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
