### PR TITLE
docs(gatsby-remark-images): Update gatsby-remark-images doc to include srcSetBreakpoints

### PR DESCRIPTION
**Pull request by manindr**
## Description

Users today are unaware of the fact that they can pass `srcSetBreakpoints` option to `gatsby-remark-images` which can be used to reduce the number of thumbnails generated at build time.
I'm trying to update the doc to address this.

### Documentation

To test that `srcSetBreakpoints` was usable i tried it on a gatsby starter : https://github.com/greglobinski/gatsby-starter-personal-blog

It was generating 6 thumbnails for one image as mentioned in the original issue.
When i changed the `gatsby-remark-images` plugin config as following, it only generated three thumbnails. See the `srcSetBreakpoints` option.

    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 500,
              srcSetBreakpoints: [200, 500],
            },
          },
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {
              wrapperStyle: `margin-bottom: 1.0725rem`,
            },
          },
          `gatsby-remark-prismjs`,
          `gatsby-remark-copy-linked-files`,
          `gatsby-remark-smartypants`,
        ],
      },
    }
## Related Issues

Fixes issue #12857

### CODE REVIEW

**Comment by manindr** [comment]
@alexfornuto Please review once.

**Comment by manindr** [comment]
I think i'm missing something. When i go to check `gatsby-remark-images` docs on my local env, it doesn't reflect my changes. I can see that `readme` is updated but the doc site is not.
@alexfornuto Do you know where am i going wrong?

**Comment by pieh** [comment]
Just so there is paper trail (author is most likely aware of that) - we do have already `srcSetBreakpoints` explanation in our docs (just not for `gatsby-remark-images`) - https://github.com/gatsbyjs/gatsby/search?q=srcSetBreakpoints&unscoped_q=srcSetBreakpoints (added description in this PR copies what we already have).

> I think i'm missing something. When i go to check `gatsby-remark-images` docs on my local env, it doesn't reflect my changes. I can see that `readme` is updated but the doc site is not.

You mean building gatsbyjs.org locally? It should have picked up local changes, but we might have regression there where it pulls docs from npm (like for all the packages that are not maintained in this repository)

**Comment by manindr** [comment]
@pieh Yes i copied it from the gatsby sharp plugin. This is just additional docs for `gatsby-remark-images` to address issues like #12857 . 

Yes i build gatsby locally (only the www part. is that right? ). And it didn't reflect my changes.

**Comment by vpicone** [comment]
@pieh @manindr I think there's an important piece of content that's missing here and in the plugin docs in regards to `srcSetBreakpoints`.

The docs say to use `srcSetBreakpoints` "if you want more control," but don't say why you might want more control or make any connection between the number of thumbnails and dramatic increases in build times. Elsewhere in the plugin docs we talk about the tradeoff/motivation for changing the `pngCompressionSpeed`, perhaps we should mention build times here as well. 

Personally, I've seen far more significant reductions in build time from changing the `srcSetBreakpoints` as compared to the `pngCompressionSpeed`.

**Comment by manindr** [comment]
@pieh Is there anything blocking this PR? Can i please get a review from you?

**Comment by manindr** [comment]
@alexfornuto Can i get some traction on this PR?

**Pull request merged**
