### PR TITLE
[RFC] Gatsby Admin

### PR DESCRIPTION
**Pull request by mxstbr**
# [Click here to see the latest version rendered](https://github.com/mxstbr/gatsby/blob/rfc/gatsby-admin/rfcs/text/0000-gatsby-admin.md)

### CODE REVIEW

**Comment by shrthnd** [comment]
Looking forward to a theme/plugin manager. Here are some other feature-requests:

1. An interface for creating/managing page-type templates stored in yaml or markdown, a la [netlify-cms collection types](https://www.netlifycms.org/docs/collection-types/); and an interface for building complex UI for creating new content based on these templates;

2. Authentication; (plug-and-play with existing auth systems/services? multi-user environments, roles/privileges, etc.)

3. White-labeling. The ability to add company logo, colors, etc. Could this be inherited from theme?

I'm not sure this should be enabled for all sites. Maybe include a flag for enabling or disabling during installation? 

Is the interface intended to be self-hosted or cloud-only? The name "admin" makes sense. 
Proprietary CMSs may use this namespace but the only commercial products where I think this is reserved would be Kentico (.NET) and the netlify-cms noted above. Otherwise... "gatsby manager",  "gatsby management console", or something like "gatsby builder/creator" might make sense.

**Comment by ehowey** [comment]
My quick take - this sounds great. It would be a huge win for folks who are coming from a GUI background and would benefit from more support in the development process. It sounds like an optional way to deal with your Gatsby site, kind of like GitHub Desktop, an added bonus but not a necessary infrastructure component. As someone who has been dealing with stacked/sandwhiched themes having a clean way to see shadowing would be awesome and enable some more complex theme interactions while not making the DX/UX too complicated. I am currently stacking about 4-5 themes deep and across in a finished site - core theme, header theme, footer theme, CMS theme/data theme, presentational theme -> Starter.

**Comment by KyleAMathews** [comment]
@ehowey haha that's amazing! Are any of these sites open source? That'd be perfect for testing our designs.

**Comment by ehowey** [comment]
> @ehowey haha that's amazing! Are any of these sites open source? That'd be perfect for testing our designs.

You bet - https://github.com/ehowey/gatsby-theme-catalyst

I would love to help test.

A few caveats.  I am about to release v1.0 in alpha/beta format, with quite a few improvements and updates. I would probably want to wait for that.  As it stands right now in v0.x.x it is using a core theme, header theme, footer theme, and then presentation themes.  v1.0 I have sort of managed to introduce a "core" theme for SANITY.io but that itself is a bit tricky because of data structures. But with theme shadowing you can shadow the query or presentation component and change up the data your are pulling pretty easily if you know what you are doing. You can look at the open PR for v1.0 and that should be working/passing tests right now to see that in action.

The vision I had is for a "core" theme and then plug and play sibling themes that extend that core theme via latent component shadowing and smart architecture. Everything using Theme-UI under the hood to maintain styles. I am pretty happy with where this is at now.  For instance you can hot-swap the header from a "top bar" to a "side bar" just  by switching themes. The latent shadowing in the core theme provides a "hook" of sorts for the sibling themes to grab onto.

You should also know that this is my side-hustle/hobby.  I work full time, in healthcare(mental health), and it is getting pretty full on right now with COVID. My time/energy is more limited than usual, but I would be really curious to help out!

**Comment by mxstbr** [comment]
@PaulieScanlon submitted a very interesting idea in [their response tweet](https://twitter.com/PaulieScanlon/status/1245584593157152769):

> Is there anything regarding SEO, or more specifically how meta data is used / rendered in Twitter cards/Facebook debugger etc.

We have been talking about rendering this visual sitemap of your site, this could totally tie into that to highlight potential SEO problems! (cc @hashimwarren for awareness, I know you're into SEO)

**Comment by hashimwarren** [comment]
I love Paulie's suggestion.  Managing your sitewide format for page titles and meta descriptions, enabling open graph for social media cards, setting redirects for pages and no-index for whole sections - all from Admin would be super useful for SEO work.

**Comment by mor10** [comment]
This is a promising idea, and I'd love to pitch in.

At the onset, do some basic UX research work:
- accessibility first at all times
- clearly define the target audience(s) and their wants, needs, goals, and challenges
- invite real user representatives into the project early on (especially non-devs)
- assume today's use case will not be a good gauge of what the community will expect a year from now
- prioritize non-dev language and interfaces (remove developer goggles while working on the project)

The major blocker for many to get started with Gatsby and similar tools is the dev-centric approach to interfaces and documentation. A Gatsby Admin will be perceived by the wider user population (including non-devs and novice devs) to be a pathway to doing advanced stuff without understanding the code or what goes on behind the scenes. This is an inevitability and needs to be considered from day one.

Clearly defining _who_ the target audiences are, what _reasonable expectations_ they have from a Gatsby Admin interface, and how to best meet their _goals_ and _needs_ up front is an essential step in this process. Persona spectrums, empathy maps, affinity maps, journey maps, service blueprints, all these UX and IxD tools exist for this exact type of project, and I highly recommend adopting them early on.

I'm here for all of it if you want it.

**Comment by KyleAMathews** [comment]
@mor10 wow, thanks for the offer! We're kicking off the project this next week so will reach out to you soon. As you infer — the goal of Admin (and [related initiatives like Recipes](https://github.com/gatsbyjs/gatsby/pull/22610)) is 100% to make Gatsby approachable to non-devs so UX research like this is a big part of the work we'll be doing. Very excited to have part of this process.

**Comment by selinahuang20304** [comment]
Hey! I am an Interaction Designer and I am interested in helping out. Please let me know how I can help with design and testing :)

**Comment by mor10** [comment]
I can vouch for @selinahuang20304. One of my IxD students and an extremely talented individual.

**Comment by jbolda** [comment]
Vue has a similar initiative and it may be worth considering shared effort in this space: https://guijs.dev/

**Comment by AndreasJacobsen** [comment]
I think Gatsby has done a better job than pretty much all of the other frameworks I have used at promoting accessibility, it's one of the reasons I love Gatsby. 

Not sure if this is even possible but wouldn't it be nice if the Gatsby admin dashboard could show an accessibility score for the page, and maybe even the accessibility errors. Something like axe-core should help for this. 
It would also be nice to see active deployments and build status on stuff like Netlify and Gatsby Cloud. I know at least for me showing accessibility score would be a huge reason for me to use Gatsby admin more, and I'm sure many others will feel the same.

**Comment by LekoArts** [comment]
This is currently on hold, if it's revisited the RFC should be moved here: https://github.com/gatsbyjs/gatsby/discussions/categories/rfc

**Pull request closed without merging**
