### PR TITLE
fix(gatsby-image): React hydration buster on `image`

### LINKED ISSUE #16763: [gatsby-image] Fixed image with media query are not resized
## Description

I defined two fixed Image:
- for desktop with a media query
- for mobile without media query

When my screen resized it downloads the smallest image but it doesn't resize the `gatsby-image-wrapper` :/

### Steps to reproduce

I define the Graphql queries like this:
```javascript
export const query = graphql`
  query {
    imageDesktop: file(relativePath: { eq: "home/partners/image.png" }) {
      childImageSharp {
        fixed(width: 161) {
          ...GatsbyImageSharpFixed
        }
      }
    }
    imageMobile: file(relativePath: { eq: "home/partners/image.png" }) {
      childImageSharp {
        fixed(width: 111) {
          ...GatsbyImageSharpFixed
        }
      }
    }
  }
`;
```

Then I define the sources like this: 
```javascript
const sources = [
  data.imageMobile.childImageSharp.fixed,
  {
    ...data.imageDesktop.childImageSharp.fixed,
    media: `(min-width: 768px)`,
  },
]
```

And I use the sources:
```jsx
<Img
  alt="Alt for image"
  fixed={sources}
></Img>
```

### Expected result

What should happen?

### Actual result

The size of the Image is `161px` even after the breakpoint of `768px`, but id downloads the `111px` Image.

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.2 - /usr/local/opt/node@10/bin/node
    Yarn: 1.17.3 - /usr/local/Cellar/yvm/3.6.1/shim/yarn
    npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 67.0.4
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.5.5 => 2.13.59
    gatsby-image: ^2.1.0 => 2.2.8
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.1.1 => 2.2.5
    gatsby-plugin-nprogress: ^2.0.10 => 2.1.2
    gatsby-plugin-offline: ^2.1.1 => 2.2.5
    gatsby-plugin-postcss: ^2.0.7 => 2.1.2
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.3
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.2
    gatsby-plugin-robots-txt: ^1.4.0 => 1.5.0
    gatsby-plugin-sharp: ^2.1.3 => 2.2.11
    gatsby-plugin-sitemap: ^2.1.0 => 2.2.6
    gatsby-source-filesystem: ^2.0.36 => 2.1.9
    gatsby-transformer-sharp: ^2.1.21 => 2.2.6
```

### LINKED ISSUE #16888: [gatsby-image] art-directing with images of different proportions breaks the layout
## Description

`gatsby-image` art-directing with images of different proportions breaks the layout.
I want to show a portrait image on mobile and a landscape image on desktop, but gatsby-image keeps the portrait layout on desktop.

#### My GraphQL Query
```js
export const query = graphql`
  query {
    sadlers: file(relativePath: { eq: "sadlers-citrus-tide.jpg" }) {
      childImageSharp {
        fluid(maxWidth: 1400, quality: 100) {
          ...GatsbyImageSharpFluid_withWebp
          presentationWidth
        }
      }
    }
    sadlersMobile: file(
      relativePath: { eq: "sadlers-citrus-tide-ipad-pro.jpg" }
    ) {
      childImageSharp {
        fluid(maxWidth: 800, quality: 100) {
          ...GatsbyImageSharpFluid_withWebp
          presentationWidth
        }
      }
    }
  }
`
```

#### My Definition of the sources
```js
    const sources = [
      {
        ...data.sadlersMobile.childImageSharp.fluid,
        media: `(max-width: 768px)`,
      },
      {
        ...data.sadlers.childImageSharp.fluid,
        media: `(min-width: 769px)`,
      },
    ]
```

#### Using the sources
```js
<Img fluid={sorces} />
```

### Expected result

 - When the windows width is smaller that 768px it should show the smaller portrait image
 - When the windows width is biggern that 768px it should show the larger landscape image with the correct "proportions"

### Actual result

 - On small screens all is well
 - On desktop screens the image keeps the portrait proportions

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v8.10.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.31 => 2.13.31
    gatsby-background-image: ^0.8.3 => 0.8.3
    gatsby-image: ^2.2.7 => 2.2.7
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3
    gatsby-plugin-sass: ^2.1.3 => 2.1.3
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.2.5 => 2.2.5
  npmGlobalPackages:
    gatsby-cli: 2.7.32
```

### LINKED ISSUE #24748: [gatsby-image] Wrong responsive aspect ratios on initial load
## Description

When loading images with different aspect ratios the wrong ratio is applied on initial page load.
In the following example this is shown by loading a 2x3 image on mobile (<678px) and a 16x9 on desktop (>678px).

This only occurs when on the built version of the website. Dev mode is working as expected.

### Steps to reproduce

In this [repo](https://github.com/jonathangraf/aspect-ratios) you will find a description on how to recreate this, as well as an example build of this issue.

Load this [website](https://relaxed-bartik-f6857a.netlify.app/) on a browser with a viewport-width <678px. 

### Expected result

The image should be displayed with a 2x3 aspect-ratio.

### Actual result

The image is displayed with a 16x9 aspect-ratio.

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 72.0.2
    Safari: 13.1
  npmPackages:
    gatsby: ^2.22.15 => 2.22.15
    gatsby-image: ^2.4.5 => 2.4.5
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9
    gatsby-plugin-offline: ^3.2.7 => 3.2.7
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9
    gatsby-source-filesystem: ^2.3.8 => 2.3.8
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3
  npmGlobalPackages:
    gatsby-cli: 2.11.2
    gatsby: 2.20.29

### LINKED ISSUE #25938: Fixed image with media queries renders slowest image available on first render
## Description

When using multiple sources for a  fixed image, each with a media query set, the first source is rendered ignoring the media queries and the issue is fixed only after resizing the window, something end user will of course wont do.

### Steps to reproduce

meros created a [repro repo](https://github.com/meros/gatsby-bug-repro-image-media-queries), and provided it in [this comment](https://github.com/gatsbyjs/gatsby/issues/16763)

### Expected result

The image matching the media query should be rendered

### Actual result

The first image is rendered

### Environment

It only happens on production environments

This was first reported in #16763 but since that issue was closed and is being ignored, I'm opening a new one refering to the same bug.

### PR DESCRIPTION
**Pull request by polarathene**
## Description

If you use art-direction with differing aspect ratios(fluid) or dimensions(fixed), SSR bakes in the CSS for the first image, but the first load(hydration) expects the initial state to match the CSS, this is not always the case if your breakpoint differs from SSR, React doesn't realize it needs to update the CSS.

The PR provides addresses this by setting `image` variable to `{}` for initial state(first frame), so that React will update image state correctly with the next rendered frame(triggered when the component mounts).

## Related Issues

Fixes #25938
Fixes #24748
Fixes #16888
Fixes #16763 

---

<details>
<summary>Extra details</summary>

### Original issue
SSR and Client states differ for what image is used which can change the `aspectRatio` affecting the `fluid` image component `bottomPadding` style, causing incorrect rendering.

### `isBrowser && !isHydrated` to bust the hydration state
This introduces a new bool state value as advised for handling this situation by the [official React docs](https://reactjs.org/docs/react-dom.html#hydrate) on hydration. I combine it with `isBrowser` to temporarily ~adjust the `aspectRatio` state a minimal amount~ set an empty initial `image` state before the next render(triggered upon component mount once hydrated).

### Unable to resolve for slow connections prior to React being loaded
That would require embedding JS during SSR to run ASAP on the client, or injecting style tags into the HTML `head` covering each images breakpoints(I know how to do this with `styled-components`, but not without it.
</details>

---

Marked some discussion below as "outdated" to hide it, it's all addressed in visible content, should help minimize time needed to review.

Main considerations for reviewer:

1. Is this an acceptable fix to the hydration issue?
2. Should `<style>` be added to the component with opt-out prop? (handles drawbacks, while the main hydration fix will still work)

### CODE REVIEW

**Comment by polarathene** [comment]
The issue was also present for `fixed` images width/height values(again, does not fix for placeholders prior to React).

As other properties of `image` are referenced as well when available, I've opted for just providing a dummy empty object for `image` on the first rendered frame. That doesn't appear to cause any problems. 

I'm not sure if the associated comment is useful, I wasn't able to explain the issue clearly in a terse manner so I provided a reference link to this PR.

**Comment by polarathene** [comment]
Perhaps at SSR, we could inject a style element into the head with classname and media queries to update relevant properties instead? 

I'm not familiar with how to approach that with SSR/gatsby, I remember Kyle was talking of a CSS feature for such a thing some time ago... did it ever get supported?

**Comment by polarathene** [comment]
For fixing the CSS before react has loaded, I have been suggested to use the `<style>` element within the HTML body, instead of the documents head. However, while that is supported by most browsers AFAIK, [it is against spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style), so HTML validators will flag such usage, which may be undesirable for a core gatsby package?

There is advice [like this](https://stackoverflow.com/questions/2830296/using-style-tags-in-the-body-with-other-html#:~:text=...then%20there%20is%20literally,it%20to%20the%20whole%20document.) around on the internet from a while ago that suggests it's ok because of the `scoped` attribute being a future specification browsers would support, but as MDN points out that is presently deprecated due to issues mentioned in their linked issue.

If we ignore this and just add `<style>` element into the component markup, this should solve pre-React phase of loading a page with this issue, but using style elements out of the document head is said to potentially cause FOUC(flash of unstyled content) / re-paint / re-layout](https://github.com/whatwg/html/issues/1605#issuecomment-235956455).

**Comment by Tokenizers** [comment]
Hi, Any news ? Can i help ?

**Comment by polarathene** [comment]
@Tokenizers waiting on review and merge, just need to be patient.

**Comment by circlingthesun** [comment]
I mistakenly posted this on the issue instead of the PR:

While this kinda works, it results in a flash of the wrong image until the JS kicks in. If the paddingBottom was determined via media queries instead that would eliminate the issue.

**Comment by circlingthesun** [comment]
@polarathene by default emotion sticks style tags all over the body and then moves them to the head when the js loads. So maybe that's okay?

**Comment by polarathene** [comment]
> While this kinda works, it results in a flash of the wrong image until the JS kicks in.

Yes, I did point this issue out already. This PR does not introduce that, it's a fix for once React is loaded, so that at least an initial load is not bugged, only on slower connections which can be dealt with with a 2nd PR and issue. It's been 3 weeks now and still no review, so I'd like to see it just get merged now.

> by default emotion sticks style tags all over the body and then moves them to the head when the js loads. So maybe that's okay?

Gatsby doesn't use emotion by default though. If feedback from the reviewer suggests adding style tags into the body for each component instance, then having them removed once hydrated, that can be done. 

I don't know if going against specifications is going to be accepted, it might not be received well if anyone is using a linting/validation step on their HTML(eg in CI builds), no clue if it has any other negative consequences(eg lighthouse score or page rank?)

**Comment by circlingthesun** [comment]
> > While this kinda works, it results in a flash of the wrong image until the JS kicks in.
> 
> Yes, I did point this issue out already. This PR does not introduce that, it's a fix for once React is loaded, so that at least an initial load is not bugged, only on slower connections which can be dealt with with a 2nd PR and issue. It's been 3 weeks now and still no review, so I'd like to see it just get merged now.

Yeah, sorry, I did see that after I copied the post from the other thread.

> 
> > by default emotion sticks style tags all over the body and then moves them to the head when the js loads. So maybe that's okay?
> 
> Gatsby doesn't use emotion by default though. If feedback from the reviewer suggests adding style tags into the body for each component instance, then having them removed once hydrated, that can be done.
I know emotion isn't the default, but Gatsby appears to be all in on emotion with ThemeUI/Themes, so the style tags in the body approach might be acceptable given that. It probably better to wait for some feedback from someone with merge privileges before going down that path.
> 
> I don't know if going against specifications is going to be accepted, it might not be received well if anyone is using a linting/validation step on their HTML(eg in CI builds), no clue if it has any other negative consequences(eg lighthouse score or page rank?)
I used gastby-image for a hero image at the top of a home page, so the flash of incorrect image was quite jarring. It would be nice to get a standards compliant solution, for me personally UX is more important though. It might be worth looking at what react-helmet does to inject tags into the head.

I use emotion in my project so it was quite easy to modify your PR it to use media queries. Thanks for making this PR, it was really helpful.

**Comment by polarathene** [comment]
I use `styled-components` myself, and it's something that solves quite well too but properly places the styles into the head.

A bigger change that I've been asked to hold off until a breaking change can be introduced was to split `gatsby-image` up into being more modular/composable. Preferably with hooks. Then having more user specific tweaked variants of this component would be easier and we could leverage our preferred styling solutions instead.

> I used gastby-image for a hero image at the top of a home page, so the flash of incorrect image was quite jarring. It would be nice to get a standards compliant solution, for me personally UX is more important though

Fair enough, hopefully the PR gets a review soon. We could always provide the style tag as opt-in/opt-out.

**Comment by wardpeet** [comment]
@polarathene is this something we can test in our e2e tests? I would love to have this cause this feels like something that can easily break in refactors

**Comment by polarathene** [comment]
I have no e2e test experience, and I'm not sure if anyone on the gatsby team has the spare time to provide personal guidance on that? Is the `window` object available for such tests? Or is it like SSR during builds with a limited environment?

This approach shouldn't break in future, it enforces the state update by making the initial state empty when run on the client. There's an associated comment to go with it, and if anyone is refactoring and don't understand what a line is for, hopefully they have the common sense to use `git blame`.

I'm available on the Discord server(same username) if someone knows how to approach writing the tests and can get me up to speed with e2e testing. I don't have the time at present to figure that all out on my own. is available.

---

I'm waiting on feedback about `<style>` in body. Do you want that added by default, with opt-out for those it is a problem for?

**Comment by polarathene** [comment]
Failing `e2e_tests_gatsby-image`:

```
fluid.js
1) renders a spacer div
1) fluid renders a spacer div:
CypressError: Timed out retrying: expected 'width: 100%; padding-bottom: 66.4%;' to match /width:100%;padding-bottom/

image.js
1) contains position relative
1) Production gatsby-image wrapping elements outer div contains position relative:
CypressError: Timed out retrying: expected 'position: relative; overflow: hidden;' to include 'position:relative'
```

**Comment by polarathene** [comment]
I've added support for `<style>` embeds within the component. This is only used during SSR and only if Art Direction feature is in use. For correct targeting as the styles are global scope, I've added a unique class name to the wrapper, which is derived from an FNV-1a hash of the combined `srcSet` values across `fluid`/`fixed` data. 

I previously converted the number to a base64 string, but noticed the performance and additional code complexity wasn't worth it vs base36. You can see a comparison benchmark(including against `JSON.stringify()`) [here](https://jsben.ch/L6HJg).`JSON.stringify()` there is about ~40% faster than the hash+base36 logic, but it's really small computation time(~0.1ms).

An alternative hash would be `djb2` which styled-components uses for example, slightly more chance of a collision, but still highly unlikely to be an issue.

**Comment by polarathene** [comment]
I have looked into DJB2 with [the following bench test](https://jsben.ch/FSZwE) against short and long strings with some variations. A newer variant over the original uses XOR(`^`) operator which gives a notable perf boost, this is what `styled-components` switched to early this year for v5. [Here](https://jsben.ch/XWv8o) I compare against FNV-1a and `JSON.stringify()`, there is a notable 2x gain over `JSON.stringify()` with the XOR variant, ~~while the original DJB2 is on par with FNV-1a.~~(original DJB2 is flawed in JS land). Note that the ~200% performance displayed here drops down to ~120% after `.toString(36)` is involved.

Local naive test with `console.time("label")`+`console.timeEnd("label")` and noted the following example on `gatsby build`:

- `JSON.stringify( image.srcSet )`: 0.077ms
- `getShortKey( image.srcSet )`: 0.067ms
- `getShortKey( imageVariants.map(x => x.srcSet).join() )`: 0.051ms

Same results in Chrome however, JSON is much faster, less than `0.01ms`.

---

I investigated `styled-components` implementation. For anyone curious, their `phash` doesn't return with `>>> 0` because this is a [progressive/rolling version](https://github.com/styled-components/styled-components/commit/216f03deb084b8c8c8980a35e25924457ff8f6e4) where they feed the returned hash into the method again with the next string contents, apparently to make it more unique and avoid hash collisions from their inputs. Not likely to be a concern for how it's being used in `gatsby-image` here.

I also did some tests on other variants, original `33 * h + character`, and bitshift mul `((h << 5) +h) + character`. Original can end up with `Infinity`(`.toString(36)` therefore casts to `"0"`), and the bitshift mul seemed to avoid that issue, but still ran into consistency issues(`long_str` in the linked benches produces different results if not cast to unit(`>>> 0`), likely due to the addition following the bitshift mul. For the XOR variant, JS will operate on the number as 32-bit with bitwise operators, the number therefore never exceeds the 32-bit range, but is still an `int` which can be negative, so to avoid the `-` prefix being added, casting to `uint` is still required.

Thus XOR is the way to go. `while` vs `for` loops didn't seem to matter performance wise(historically they did afaik), so that difference is negligible.

---

Unit tests are failing and the CircleCI output isn't all that helpful as to why, lot of repeated log spam. Unclear if this PR has anything to do with that.

For reviewing changes, you'll want to disable whitespace diffing, as the indentation added adds far too much noise.

**Comment by polarathene** [comment]
@wardpeet I am having trouble with running tests locally to troubleshoot build errors. I see no reason why the style tests that e2e is failing would happen when the wrapping div is verified to exist.

If someone has time to provide some guidance, that'd be helpful. Until then, there isn't much I can do, I've tried reaching out on Discord but activity seems to be low there.

**Comment by polarathene** [comment]
Did a little refactoring, no more whitespace diff problem. Fixed up some issues and updated two e2e tests. `gatsby-image` Jest tests also had an issue with the `matchMedia()` API, replaced the existing test mock functionality to leverage [a package that covers this support better](https://github.com/dyakovk/jest-matchmedia-mock).

Added another feature related to this that had been bothering me. If art direction is triggered on a slow connection, previously there was a delay in adapting the image until the new image started to download, on a slow connection it can take a few seconds for React to re-render as a result, not great if you're on mobile and switch orientation or the OS supports resizing app windows(partitioning the display for multi-tasking).

## Summary of features / fixes:

- Fix state rehydration - Do not implicitly trust initial load state matches when Art Direction is used.
- Embed media queries in `<style>` - SSR adds MQs to HTML so that the same Art Direction issue with hydration is avoided prior to JS being available.
- Transition to variants correctly - No longer blocked by new image response delay, resets placeholder for smooth transition UX.

**Comment by polarathene** [comment]
Currently failing lint test due to:

```
yarn install v1.21.0
[1/4] Resolving packages...
[2/4] Fetching packages...
 
error An unexpected error occurred: "https://github.com/okonet/listr-update-renderer/tarball/upgrade-log-update: Request failed \"500 Internal Server Error\"".
 
info If you think this is a bug, please open a bug report with the information provided in "/home/circleci/project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 
Exited with code exit status 1 
CircleCI received exit code 1 
```

Which is a forked package that's not been updated since 2017, it's required for `lint-staged@8.2.1`, which was release [June 2019](https://github.com/okonet/lint-staged/releases/tag/v8.2.1), their latest version 10.x drops Node.js v8 support. I don't see any unit tests for that version anymore, so I guess I'll update that dependency. 

It's potentially caused by a temporary service issue as CircleCI points out a "degraded" status when dealing with Github. **EDIT:** Getting a lot of 500 errors atm with github just browsing the web interface.. So definitely a temporary issue..

**Comment by polarathene** [comment]
@wardpeet sorted out tests issues, should be good for merging.

I'm not sure if any additional e2e tests can be added. Still not familiar with Cypress, I can probably look into a test that fails prior to this PR for the hydration issue, but with the CSS embeds, it'd probably hide the hydration problem. I could make the embeds opt-out?

I don't know if the transition feature can be tested automatically either.

**Comment by polarathene** [comment]
For review, some questions.

- Should it use the multiple `<style>` element output, one per art direction media condition, or a single element with strings concatenated?
- The hydration fix may only be relevant for art direction, should I make a change to only force a re-render on mount if an array of fluid/fixed data is supplied?

**Comment by polarathene** [comment]
This PR introducing an empty initial render has effectively changed the order of logic run with `componentDidMount()` and `handleRef()`. `handleRef()` initially triggered prior to `componentDidMount()`, it's now deferred until after where the hydration state is toggled.

That prevents the `isCritical` check in `componentDidMount()` from ever working now. It's purpose was to reveal the main image early if the `img.complete` attribute was true already(finished loading prior to mounting). I think that also relied on hydration not causing a DOM update which this PR enforces, updating the DOM however will make `img.complete` false, it will be true at the same time `handleImageLoaded()` is called.

Removing the hydration render guard, I noted that `handleImageLoaded()` was called twice, unless I disabled the cache. I would need to verify with the current `gatsby-image` in master to check if it's the same behaviour but I don't think this snippet prior to this PR was providing it's intended value anymore.

**Comment by polarathene** [comment]
> That would also be a good place to comment on why that is a relevant and necessary change

[This commit](https://github.com/gatsbyjs/gatsby/pull/24811/commits/db4c4a85df20c281bd5015f85a45391da2eca5f6) adds the mock and updates tests to accommodate. The commit message is perhaps not clear enough, but the added code to `gatsby-image` that uses the `matchMedia` API fails tests as the API isn't mocked fully, rather than more DIY mocking, I opted to leverage a third-party package that covers the API.

[This commit](https://github.com/gatsbyjs/gatsby/pull/24811/commits/1d2e4447f3c48f6176a5fbebca847a830b7877cf) adds whitespace for e2e tests that were failing. I'm not sure what introduced that subtle change.

---

> But I think that mock change affects more than half the diff of this PR while it doesn't really address the reason of the PR.

It's for the `matchMedia` fix related to Art Direction usage, I mentioned this separate feature [here](https://github.com/gatsbyjs/gatsby/pull/24811#issuecomment-657387494), on high latency / slow connections if the user triggers a media change(orientation change, split view on mobile, or maximize browser on desktop say), there is a delay between the change while the layout may be broken as a result. 

I figured I might as well bundle it into this PR, [due to how long these take to get reviewed/merged](https://github.com/gatsbyjs/gatsby/issues/25487)(even if [simple PRs](https://github.com/gatsbyjs/gatsby/pull/25371)).

If you prefer I can split it out to it's own PR? Or are you just wanting the commits tidied up for code review?

---

> leaving me wondering whether the changes in this PR are tested at all, and if so, what they fixed.

They're required for the feature described above, I would need to move that out to it's own PR. Or perhaps simpler, I create a new PR with just the rehydration changes, then I can rebase this and rename the PR to merge after, or close this PR and split each one out into new PRs if that's cleaner.

---

> As an aside, please undo the rename of `isUsingArtDirection`, as I think the old name is better and it adds noise to the PR.

Disagree. `hasArtDirectionSupport` does not describe what the method does. It's not checking if support exists, it's checking if this type of support is to be used due to providing an array of image data.

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L68-L77

See how this naming convention is used here:

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L383-L391

`hasXYZ` is used to actually check if support for native lazy loading or Intersection Observer is available. `useIOSupport` should likewise be renamed `isUsingIOSupport`, but it's distinction of when `hasXYZ` is appropriate for it is fairly clear.

Technically I would likewise assign a value for `ArtDirection` to the class there like has been done for `IOSupport`, but for some reason we currently support changing the image source data at runtime, so I left that alone. This PR does move some logic specifically related to `ArtDirection` into the constructor though as that really shouldn't be something we're processing each time in `render()`, but would be required to move to `render()` if someone does wants to change the data at runtime.

---

Do you want to keep `<style>` embed with the hydration fix? The embed is used for SSR and removed after hydrating, it ensures the right variant is used prior to JS being available/ready, technically should fix the problem in itself without requiring hydration fix afaik.

#### `matchMedia()` transition fix(+Jest mock):

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L412-L431

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L492-L494

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L501-L515

### `<style>` embeds

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L21-L36

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L213-L237

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L406-L410

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L573-L577

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L582-L584

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L595-L599

+ same for `fixed` render section

### Actual hydration fix

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L435-L438

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L536-L540

https://github.com/gatsbyjs/gatsby/blob/84b812d7161771d6f7533f79b66c3627bb90fef2/packages/gatsby-image/src/index.js#L393-L399

**Comment by polarathene** [comment]
I'm going to split the PRs out, should be easy enough to review the basic hydration fix, then consider the `<style>` embed as a complimentary addition to merge afterwards, related `matchMedia()` fix will also be split out into it's own PR as requested.

**Comment by pvdz** [comment]
Thanks for your detailed response.

In the end, PRs get squashed and merged so individual commits are mostly useful for review time. But when a PR contains 22 individual commits I tend to skip the individual commits in favor of the whole PR because it's just more efficient. Otherwise often you'd be reviewing a commit and then read a followup commit undoing that because reasons. I'm very sorry if you did happen to have 22 clean commits. I wish there were more of you.

> If you prefer I can split it out to it's own PR?

Yes, looking at the PR on a whole, I think that should be split out.

> They're required for the feature described above, ...

Unfortunately github doesn't really do "stacks". So your suggestion to have a chain of PRs might be best. I _think_ two is fine here? One with the mock change stuff and then one followup PR with the concrete changes?

> It's not checking if support exists, it's checking if this type of support is to be used due to providing an array of image data.

It literally checks if the `currentData` _has_ any image with a `.media` property that is not `undefined`. Ugh, too much bikeshedding, whatever. If you feel strong about it then keep it.

> Do you want to keep <style> embed with the hydration fix?

I think you created good splits. Would be great if you can.

>  due to how long these take to get reviewed/merged

Sorry about that. The team isn't that large and we have a lot on our plate. I merged the PR that you mentioned, sometimes things just slide off our radar. That and holiday season ... Oh well. Request a review from me in these split PR's and I'll try my best to keep up.

Thank you! :purple_heart:

**Comment by polarathene** [comment]
> I'm very sorry if you did happen to have 22 clean commits. I wish there were more of you.

They're reasonably documented/focused commits, but some are outdated after original submission. I will split the PR apart into clean commits and hopefully we can get them merged with less delay :)

> Sorry about that. The team isn't that large and we have a lot on our plate.

I'm available for any paid part-time/full-time remote work if that'd help :sweat_smile: 

> I merged the PR that you mentioned, sometimes things just slide off our radar. 

Thanks! I understand that how that is, all good. I created a [tracking issue](https://github.com/gatsbyjs/gatsby/issues/25487), mostly for myself for the image related PRs and will continue to chase those up.

> Request a review from me in these split PR's and I'll try my best to keep up.

Will do! Thanks for taking the time to review and merge these, it's very much appreciated.

**Comment by polarathene** [comment]
React Hydration fix, new PR can be found [here](https://github.com/gatsbyjs/gatsby/pull/26097). I need to add the e2e tests and that should be good for merging.

Had the other PRs split out into commits but I hadn't quite pushed the commits to github...machine froze up had to hard reboot and this is a first but the git index got corrupted as a result, so I've lost all local commits/branches that were not pushed, and quite possibly my stashes(which you can't push) :\

Will do all that over again tomorrow then..

**Comment by kaushalyap** [comment]
@pvdz Can we get this done please? since there are PRs, just need to review and merge them.

- https://github.com/gatsbyjs/gatsby/pull/26117
- https://github.com/gatsbyjs/gatsby/pull/26119

**Pull request closed without merging**
