### PR TITLE
Store page metadata in the data attribute of the script element

### PR DESCRIPTION
**Pull request by dzsibi**
## Description

Right now, static pages generated by Gatsby contain a one-line script to set the value for `window.pagePath`. The script will be different on each page - when generating hashes for a sitewide Content Security Policy, this will add one hash per page to the length of the header, which will become longer and longer as the site grows. This pull request changes the generated code to store the target value for `window.pagePath` in a data attribute of the script element, and use a one-liner to set the value from there. This way the actual JavaScript code will be the same on all pages, so only a single hash needs to be added to the Content-Security-Policy header. The JavaScript APIs used should not cause any compatibility issues (getElementById and getAttribute are both as ancient as they come), but I wasn't able to test this in all supported browsers. 

Note: the same method could be applied to `window.___chunkMapping` - while its value is the same on all pages, so it won't cause CSP to expand indefinitely, it is not constant, so the build pipeline still needs to extract its hash and modify the CSP header to whitelist it after each build. Alternatively, inline scripts could be skipped entirely by loading these from data attributes directly when they are first needed.

### CODE REVIEW

**Comment by wardpeet** [comment]
For us to actually merge this, we'll need an example on why this is necessary.

**Comment by dzsibi** [comment]
Understandable. For a static page at `/page1`, Gatsby will include the following one liner script:

```html
<script id="gatsby-script-loader">/*<![CDATA[*/window.pagePath="/page1";/*]]>*/</script>
```

Similarly, for another page at `/page2`, you will have:

```html
<script id="gatsby-script-loader">/*<![CDATA[*/window.pagePath="/page2";/*]]>*/</script>
```

And so on. Let's try to generate a Content Security Policy for this website. For simplicity's sake, we can do this with `gatsby-plugin-csp`. This will generate a `meta` element for each page that contains the policy. For `/page1`, this might look like this:

```html
<meta http-equiv="Content-Security-Policy" content="...; script-src &#x27;self&#x27; &#x27;sha256-DWsRx2pt67PQs7LHkgC21wQzKc4c/qxSD7oSHOnEz+0=&#x27; &#x27;sha256-O1yZXjNDKkL9cqeiyMK/2TvvFmfpMulHhepbSCwaSY4=&#x27 ..."/>
```

For `/page2`, it will look similar but one of the hashes will be different, as the script blocks are also different:

```html
<meta http-equiv="Content-Security-Policy" content="...; script-src &#x27;self&#x27; &#x27;sha256-KIpdfkOgnHuzc/PzN38EgUcCAxRJhM83HAy22Ydl+as=&#x27; &#x27;sha256-O1yZXjNDKkL9cqeiyMK/2TvvFmfpMulHhepbSCwaSY4=&#x27 ..."/>
```

If we wanted to use a single Content-Security-Policy header for our entire site, we can then extract and merge the generated policies from these `meta` elements. (We could have parsed the HTML files and generated the hashes without  `gatsby-plugin-csp`, so the issue is not specific to the plugin.) In the end, we will end up with a policy that looks like this:

```
...; script-src 'self' 'sha256-KIpdfkOgnHuzc/PzN38EgUcCAxRJhM83HAy22Ydl+as=' 'sha256-DWsRx2pt67PQs7LHkgC21wQzKc4c/qxSD7oSHOnEz+0=' 'sha256-O1yZXjNDKkL9cqeiyMK/2TvvFmfpMulHhepbSCwaSY4=' ...
```

The number of hashes included in the header will depend on the total number of pages we have, each adding an additional 54 bytes to the header. The large number of ever changing hashes makes it basically impossible to audit the site's policy without delving into the code behind it. 

With the changes in this pull request, there will only be 2 hashes in there, one for setting `window.pagePath`, and one for setting `window.___chunkMapping` (not counting any custom additions that are not Gatsby's responsibility). Also, one can then generate / extract the hashes from any particular HTML page, since they will all be the same (instead of having to parse all pages). 

In my note, I mentioned that this could also be applied to `window.___chunkMapping`, which would have another advantage: no extraction or generation is necessary, since unless Gatsby changes the content of those snippets, they will stay the same across builds (so setting up a CSP header for an entire Gatsby based website that does not use inline scripting elsewhere will be as simple as adding those two known hashes to the header). I opted not to do that in this pull request, as I wanted to make the smallest possible change that still solves the bigger problem, and relying on the scripts staying the same across Gatsby versions might also not be the best practice, so an extractor based solution might still be preferred.

**Comment by dzsibi** [comment]
(I resolved the merge conflict that was due to recent upstream changes)

**Comment by dzsibi** [comment]
@wardpeet Could you provide any feedback on whether you find the explanation above reasonable?

**Comment by wardpeet** [comment]
Yes it does, it's an interesting workaround 😄. This seems to be fine, need to think a little bit about it.

**Review by wardpeet — COMMENTED** [review]
After some consideration were not going to merge this for the following reason:

This is a nice workaround to have only one CSP for all pages but it means we're locking ourselves into a corner where if we do other changes to our page scripts we'll be breaking this behavior. It doesn't seem wise to lock us in and we need to come up with a better CSP story.

**Comment by dzsibi** [comment]
I quite understand the sentiment - this was a quick and partial fix for a larger issue. Do you have any guidance on what would be a better CSP story in your opinion? I guess the most comprehensive solution would be to eliminate all inline scripts, declare it as a policy for the project not to include new ones (at least in the core packages), and modify tests to run with a CSP that does not allow unsafe-inline. While I can help eliminate the existing fragments, I have no idea if this is something the project would be willing to pursue as a goal in terms of policy, nor do I feel competent to set the scope of this change in terms of packages included. I can also accept if this is simply not a priority, and simply fix this for our use case (that is what I am going to do right now, anyways).

**Pull request closed without merging**
