### PR TITLE
Update katex package to 0.8.3

### PR DESCRIPTION
**Pull request by thomaskuntzz**
Related to #3527

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Looks good! https://deploy-preview-3548--using-remark.netlify.com/katex/

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by thomaskuntzz** [comment]
But now, which package will be used: the one with the updated KaTeX package that is in the git repo, or the one hosted on NPM that is (I guess) not yet updated?

**Comment by KyleAMathews** [comment]
Just published the new version of the package on NPM so run `npm upgrade` or `yarn upgrade` and get the new version 👍

**Comment by thomaskuntzz** [comment]
Cool! And one last thing: with this mono repo architecture, I'm always a little confused about where I should run the NPM commands from: the root of the repo, or the subfolder in which resides the site I'm working on (in this case `examples/using-remark`)?

Thanks! 😊

**Comment by KyleAMathews** [comment]
Depends which command you're running :-)

Have you see the contributing doc page? https://www.gatsbyjs.org/docs/how-to-contribute/

**Comment by thomaskuntzz** [comment]
Not this one... Thanks for pointing it out!

**Pull request merged**
