### PR TITLE
docs: better call-out for recommended learning paths

### PR DESCRIPTION
**Pull request by jlengstorf**
This makes it more obvious that there are two recommended paths for developers (i.e. learn using the tutorial or dive into the docs for code samples).

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 4450c4f60f1a80a0f6b26c6fc671d7c547f21429

https://app.netlify.com/sites/using-postcss-sass/deploys/5b60c621c6aed61e216c7eb3

**Comment by m-allanson** [comment]
What about splitting the groups differently, currently it's _most developers_ and _advanced developers_. Could that instead be _If you're new to Gatsby_ and _If you're already familiar with Gatsby_?

Sorry I realise that's not really what your PR was making changes to! Your changes look good, so feel free to merge this as-is.

**Comment by shannonbux** [comment]
Hm, if there's a way to avoid saying "advanced developers" I would. I like the rest of the changes. Perhaps it could just say "for most developers" and just skip straight to "to dive straight into code examples". This gently persuades people to the tutorial and then remains neutral about the other choice.

**Comment by m-allanson** [comment]
> This gently persuades people to the tutorial and then remains neutral about the other choice.

👍 

I think we should nudge Gatsby first-timers towards the tutorial whether they're beginners or pros, as it's a great introduction to a lot of Gatsby's core concepts. More advanced folks might skim through it before moving on, but that should provide a nice foundation for jumping further into the docs.

**Comment by m-allanson** [comment]
Let's go with @shannonbux's edit, merge this in and then adjust as needed?

**Comment by jlengstorf** [comment]
Sounds good to me!

**Pull request merged**
