### PR TITLE
Lighthouse audit documentation 

### LINKED ISSUE #24778: Lighthouse Audit Documentation outdated
Was browsing the docs and noticed the Lighthouse Audits page was very outdated.

I've made some tweaks and a PR will be on its way shortly.

### PR DESCRIPTION
**Pull request by shanejones**
Giving the page a bit of an update and using up to date screenshots.

This PR closes #24778

### CODE REVIEW

**Comment by ascorbic** [comment]
Hi. Thanks for the contribution. Can you separate out the parts which add the site to the showcase from the part that adds the docs please?

**Comment by shanejones** [comment]
Hi @ascorbic 

What's the best way to do that? I thought the 2 PR's being separate would have done that for me.

**Comment by ascorbic** [comment]
Hi. You'll need to create a separate branch for each PR, based on master

**Comment by shanejones** [comment]
Got it, will kill this PR for now

**Pull request closed without merging**
