### PR TITLE
fix(refresh-endpoint): call refresh while refreshing

### LINKED ISSUE #20576: Calling __refresh while refreshing
## Description

Our team is leveraging the Gatsby refresh endpoint (`ENABLE_GATSBY_REFRESH_ENDPOINT`) for development purposes. The amount of time to build/refresh has increased over time. We are wanting to use a service that will make a POST call to `__refresh` on demand. The problem that we are encountering is that if you make the POST call in the middle of a refresh then unexpected behavior starts to occur and eventually the dev server crashes. It would be nice to have some way to either offer some kind of throttling or at least have a way to know if we are in the middle of a refresh. (with the latter at least a custom endpoint can be created)

Our understanding was that it did not behave like this before (2.16.5) and if this were to occur Gatsby would wait until the existing refresh would finish.

### Steps to reproduce

Make a POST call to `__refresh` while it's refreshing.

### Expected result

Expected behavior.

### Actual result

Query failures, crashes, etc.

### Environment

(This also occurs in Windows)

EDIT: Updated `gatsby` to 2.18.21 and it is still an issue.

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 72.0
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.18.15 => 2.18.15
    gatsby-background-image: ^0.9.11 => 0.9.11
    gatsby-image: ^2.2.4 => 2.2.36
    gatsby-plugin-lodash: ^3.1.2 => 3.1.18
    gatsby-plugin-manifest: ^2.2.1 => 2.2.33
    gatsby-plugin-polyfill-io: ^1.1.0 => 1.1.0
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.18
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sass: ^2.1.12 => 2.1.26
    gatsby-plugin-sharp: ^2.2.3 => 2.3.7
    gatsby-plugin-sitemap: ^2.2.9 => 2.2.24
    gatsby-plugin-styled-components: ^3.0.7 => 3.1.16
    gatsby-plugin-typescript: ^2.0.15 => 2.1.22
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.5 => 1.1.8
    gatsby-source-filesystem: ^2.1.2 => 2.1.42
    gatsby-transformer-sharp: ^2.2.1 => 2.3.9
  npmGlobalPackages:
    gatsby-cli: 2.6.7
```

### PR DESCRIPTION
**Pull request by apaniel**
## Description

changes:
- Queue unique refreshing requests when a refresh request is being processed

## Related Issues

Fixes #20576

### CODE REVIEW

**Comment by xavivars** [comment]
@danabrit , @freiksenet , is there anything else needed in this PR to get reviewed?

**Comment by freiksenet** [comment]
Hi!

Thanks a lot for you PR!

Core team is currently not working because of Gatsby Company Gathering. We'll make sure to review this on Monday next week.

**Comment by pieh** [comment]
> In my case, it is useful for doing health-checks when having the development server in a container as a preview server. Otherwise health-checks can fail because development server cannot respond while refreshing.

@apaniel90vp Can you expand on this? Does your develop server not serving requests when data is being refreshed? This should only really happen if there is massive chunk of sync code being executed as part of refresh (not allowing express app to process and serve requests), but most refreshes are hugely async so that should give room for server to respond to requests

**Comment by apaniel90vp** [comment]
@pieh
> Can you expand on this? Does your develop server not serving requests when data is being refreshed?

no, it doesn't, it hangs until refresh finishes

> This should only really happen if there is massive chunk of sync code being executed as part of refresh (not allowing express app to process and serve requests), but most refreshes are hugely async so that should give room for server to respond to requests

We are using contentful as source of our data, and we have a huge amount of data there

**Comment by pieh** [comment]
Ok, so from reading this PR I _do think_ this PR should be split into 2:
 - 1 adding queue (and no ui changes, so just queueing part)
 - follow up adding optional screen ( I'm really torn about this one, I would much prefer fix core issue about server being unresponsive than put band aid like "we are refreshing" screen). The thing about this screen is that webhook data refreshes are not the only thing that can keep `gatsby develop` busy. There are some plugins that don't use those for data updates, so data updates from those category of plugins wouldn't be handled by code like that.

Some of my initial thoughts:

You are implementing queue mostly in `develop-proxy` - in some ways this is nice because you can immediately create response even if gatsby itself is busy/unresponsive - but not sure if that would be desired tbh. I do think that queue should be implemented much closer to code that executes `sourceNodes` (etc), just not sure if requests can be stalled long enough to not cause other problems elsewhere

**Comment by apaniel90vp** [comment]
I can split it in two, no problem.

I created the queue in the proxy for immediate response, as I said in earlier comment, we have contentful as source of data and our refresh gets totally busy, so creating that queue in other place didn't work for me.

I saw this refreshing screen in place for config and node changes and just reused it, as you say that could not be the desired experience, that is why I added it behind an env variable.

I have no idea where the core issue making the server not responsive could be, any idea?

**Comment by apaniel90vp** [comment]
@pieh I updated the MR to keep only the queue part, makes much more sense to split it :)

About the optional restarting screen, I still believe it would be helpful, let me explain our case and you can give me your thoughts.
For us having a preview container is more oriented to content authors (non developers), so showing this restarting screen is also useful, because they can know that after having the refreshing screen on sight they will have the page with updated data.
Keeping it behind an env variable for opt in is because we know that could not be the desired behavior for all the use cases, but when gatsby is working as a develop server on a preview container, is there any other way to make develop server to reload rather than the /__refresh endpoint? Would there be any other way to let our non developers know that data refresh has finished?

I can totally help on fixing the underlying issue or to expand the optional refreshing screen to other cases if you like, but I think that it is an enhancement on the user experience, specially from a non-developer gatsby-user perspective.

**Comment by xavivars** [comment]
Hey @pieh,

Thanks for reviewing this!

The problem moving the queue management closer to where the nodes are creating are, as @apaniel90vp says, the whole server gets stuck. The PR is not only to prevent unnecessary refreshes, but also to have a responsive server that will return something (even if it's a temporary unavailable message) instead of just hanging the connection and, eventually, timing out.

Your point about the page (the piece of the initial PR that got removed in the second iteration) it's also very good. This page may not cover all times where Gatsby develop is busy, but it's definitely an (optional, behind a flag) improvement for some cases, like when using gatsby-source-contentful, and can be a good first step towards a wider and more exhaustive management of busy states. 

What do you think of the current status of the PR?

**Comment by apaniel90vp** [comment]
I opened a MR to the same branch, in case someone is interested in the refresh screen that we mention in the comments of this MR:
https://github.com/apaniel90vp/gatsby/pull/2

**Comment by xavivars** [comment]
hey @pieh, @freiksenet, 

With the latest changes @apaniel90vp had to do a small change in the PR, but the build is failing in Gatsby Cloud and we don't know anymore what the problem is....

https://github.com/gatsbyjs/gatsby/pull/24887/checks?check_run_id=798498038

**Comment by apaniel90vp** [comment]
Another piece that I'm missing is how to get the **CYPRESS_PROJECT_ID** and **CYPRESS_RECORD_KEY** for a new cypress e2e test, so they are recorded in the cypress dashboard

**Comment by xavivars** [comment]
> Hi!
> 
> Thanks a lot for you PR!
> 
> Core team is currently not working because of Gatsby Company Gathering. We'll make sure to review this on Monday next week.

@freiksenet , any updates?

**Comment by xavivars** [comment]
Thanks for the information, @wardpeet! We didn't know if there was any step missing for this to get reviewed 😉

Regarding the reason of creating a new set of e2e tests, @apaniel90vp will need to chime in (he's also out today 😅).

**Comment by pieh** [comment]
I was thinking more about this- primarily having queue in parent process because of unresponsiveness of actual express app during refresh. I think I would prefer to change Contenful plugin so it doesn't block event loop for long periods of time and instead use something like this - https://github.com/gatsbyjs/gatsby/blob/b73cc5d7fc553266180f62248df6bb7b1fd9f35b/packages/gatsby/src/schema/index.js#L72-L73
as it does work to let other parts of gatsby react to external events. This would mean that gatsby is _fully_ still usable (slower, sure, but usable) during refresh as opposed to this approach that allow just refresh requests to come through. To be fair - it might make sense to do both as blocking event loop is likely not limited to Contentful plugin. Adding ability to flush event loop periodically would also mean there would be no need for that optional "we are working" screen that you originally had in this PR beucase gatsby would still be able to handle response (might be less snappy, but shouldn't timeout completely).

> A piece that I'm missing is how to get the **CYPRESS_PROJECT_ID** and **CYPRESS_RECORD_KEY** for a new cypress e2e test, so they are recorded in the cypress dashboard

That would need one of the gatsby cypress org admin to set up, but they are not needed per se to land e2e test. But I do think we could integrate this in already existing e2e dev runtime and not create new one - those e2e tests are "expensive" to bootstrap - we already do have some refresh webhook tests there so adding more cases would fit well there

**Comment by apaniel90vp** [comment]
Hey, sorry for not answering earlier, I've been out until today with limited connection.
To your comments:
> What's the reason for creating a new e2e test and not just adding it to e2e_tests_development_runtime?

> But I do think we could integrate this in already existing e2e dev runtime and not create new one - those e2e tests are "expensive" to bootstrap - we already do have some refresh webhook tests there so adding more cases would fit well there

The original PR (second part here: https://github.com/apaniel90vp/gatsby/pull/2) had a new env variable `ENABLE_GATSBY_RESTARTING_SCREEN_ON_REFRESH` so I needed to spin up a new development process to be able to have this variable. 
When I did the split of the MR in two I did't move it to the existing e2e dev runtime because I there is no way to know whether the refresh has finished or not, as a way of not affecting other tests I left this new cypress e2e tests. But I can try to find another way if you guys this that is too much.

> To be fair - it might make sense to do both as blocking event loop is likely not limited to Contentful plugin. 

I agree, I gave you the contentful plugin example, but any plugin using any gatsby node API and doing any long blocking operation would block the event loop.

**Comment by apaniel90vp** [comment]
@pieh @wardpeet is there anything else on my side to do?

**Comment by xavivars** [comment]
Any updates here?

**Comment by ascorbic** [comment]
@xavivars Yes, I think it's best to hold off on this until #25479 and the other state machine PRs are in. We can then see how much of this makes sense to keep (and whether it's still needed). The state machine work makes some fundamental changes to how we handle develop, which should make things more reliable in all cases, so maybe this won't be needed.

**Comment by ridi-mz** [comment]
Hi, any updates in this PR ?  Will it be merged ?

**Comment by seidtgeist** [comment]
Well, looks like #25479 has been merged and there are still problems that could be alleviated by not doing multiple refresh passes.

If I call `__refresh` more than once, everything goes irreparably wrong:

- First I had OOM errors, so I updated to the latest version of gatsby that fixed some of this via #27685 
- Now I’m hopefully getting less OOM errors (I don’t know to be honest), so I’m getting a new error:

```
error Missing onError handler for invocation 'building-schema', error was
'Error: Schema must contain uniquely named types but contains multiple types named "XYZ".'
```

(XYZ being the configured `typeName` of the `gatsby-source-graphql` plugin)

I have a feeling that Gatsby as a project might have reached a complexity ceiling a couple of years ago, where the sheer amount of STUFF happening under the hood now made it impossible to be either fast or correct/reliable in any way. Every senior/principal developer I’m talking to is having similar feelings. What’s the feeling inside, I wonder?

**Comment by LekoArts** [comment]
Hey! Thanks so much for opening this pull request!

Sadly this PR got stale and didn't have any activity for some time. We're trying to do better with PR reviews! To get a better overview of all actionable PRs we're going through all open PRs and triage them. Since we won't be able to do everything and adding new features _always_ means added maintenance burden, we have to be more picky about what's beneficial for the average user and the project itself longterm.

Having said all this, we dropped the ball on this PR and we're sorry about not responding to it earlier. As said above, we want to do better in the future but here we should have communicated earlier what will happen with the PR.

In the meantime Gatsby 5 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

We absolutely want to have you as a contributor and are sorry for any inconveniences we caused with replying too late to this PR.

Thanks for submitting to Gatsby! 💜

**Pull request closed without merging**
