### PR TITLE
Adds support for more date/time formats

### PR DESCRIPTION
**Pull request by miktirr**
## Description

Support for `YYYY-MM-DD HH:mm:ss Z` could be useful since this is the format [Jekyll uses](https://jekyllrb.com/docs/front-matter/#predefined-variables-for-posts) in the frontmatter. Supporting the same format would make it easier to move from Jekyll to Gatsby.

It’s not perfectly clear to me if using a space instead of the uppercase T is valid in ISO 8601 format (strictly speaking probably not), but at least [Moment.js regards these as valid date strings](https://momentjs.com/docs/#/parsing/string/) and handles them in the same way as those with the T.

### CODE REVIEW

**Comment by wardpeet** [comment]
I'll let @freiksenet & @pieh comment on this one. I have no idea how this works 😋

**Comment by wardpeet** [comment]
> We are working on big changes to GraphQL in #11480. We plan to merge it next week. I wonder if you could either wait until next week and make a new PR against master or just make the PR for the schema refactor branch. Otherwise there will be merge conflicts that might result in this code getting lost.

I quoted this from https://github.com/gatsbyjs/gatsby/pull/12511

**Comment by miktirr** [comment]
Thanks for the info! This can wait, and I can open a new PR against the master after the schema refactor branch has been merged.

It might also be that the schema refactor itself makes these changes unnecessary, and the [#12533](https://github.com/gatsbyjs/gatsby/pull/12533) by @himynameistimli would seem to address the same concerns anyway.

So probably just close this PR for now.

**Comment by wardpeet** [comment]
Thanks so much for the PR and we're very sorry about this!

We're going to close this out. We want you to know that we certainly want to keep you as a contributor to Gatsby, so we'd encourage you to check out our open issues.

Thanks again, and we look forward to seeing more PRs from you in the future! 💪 💜

**Pull request closed without merging**
