### PR TITLE
Small Typo in doc

### PR DESCRIPTION
**Pull request by alexluong**
I just found this typo in the doc while I was learning about this. Figured I should make a quick PR!!

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 06eeb66eee16a1647e0513892590d9b9f234c844

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5a96404ed62f2a4c670ef7

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 06eeb66eee16a1647e0513892590d9b9f234c844

https://app.netlify.com/sites/gatsbyjs/deploys/5b5a963f4ed62f2a4c670eef

**Comment by KyleAMathews** [comment]
Deploy preview for *using-remark* failed.

Built with commit 06eeb66eee16a1647e0513892590d9b9f234c844

https://app.netlify.com/sites/using-remark/deploys/5b5a96424ed62f2a4c670f03

**Comment by m-allanson** [comment]
Haha I wonder if [the Gruffalo](http://www.gruffalo.com) writes GraphlQL?

Thanks @alexluong and review team!

**Pull request merged**
