### PR TITLE
docs(www): improve steps for Gatsby and Docz tutorial 

### PR DESCRIPTION
**Pull request by thegrims**
Updated initial instructions for gatsby-config so that they work correctly

Old instructions did not work with new CLI

### CODE REVIEW

**Comment by gillkyle** [comment]
Do you have an example repo where it's not working? I haven't been able to replicate it.

Both

```
__experimentalThemes: [`gatsby-theme-docz`],
```

and 

```
__experimentalThemes: [
  {
    resolve: 'gatsby-theme-docz',
  },
],
```

should work just the same (and seem to be okay on small examples I tried), using the longer object syntax just allows more configuration of the plugin like by passing options.

I did notice that the instructions weren't totally straightforward because following the steps exactly as outlined doesn't show a docz page on the initial page load unless you change the `src/pages/index.js` file to the content of what is instructed to insert at `src/docs/index.mdx` and rename it to `.mdx`, maybe that would be something we could improve in this or another PR? @thegrims

**Comment by thegrims** [comment]
> Do you have an example repo where it's not working? I haven't been able to replicate it.
> 
> Both
> 
> ```
> __experimentalThemes: [`gatsby-theme-docz`],
> ```
> 
> and
> 
> ```
> __experimentalThemes: [
>   {
>     resolve: 'gatsby-theme-docz',
>   },
> ],
> ```
> 
> should work just the same (and seem to be okay on small examples I tried), using the longer object syntax just allows more configuration of the plugin like by passing options.
> 
> I did notice that the instructions weren't totally straightforward because following the steps exactly as outlined doesn't show a docz page on the initial page load unless you change the `src/pages/index.js` file to the content of what is instructed to insert at `src/docs/index.mdx` and rename it to `.mdx`, maybe that would be something we could improve in this or another PR? @thegrims

Oh you're totally right! I must have been confusing the two issues. I'll write up some documentation changes and then resubmit them for review

**Comment by gillkyle** [comment]
Thanks @thegrims that would be awesome! This also relates tangentially to the improvements to the MDX workflow in #14258 so this will be a great addition!

**Comment by gillkyle** [comment]
Hey @thegrims! Have you had any chance to look at this? If not maybe we should just close the PR or open up an issue if the instructions are still unclear.

**Comment by wardpeet** [comment]
The documentation got updated and is correct now. Feel free to re-open a new one if you have any improvements! :muscle:

Thanks for creating this PR, and we look forward to seeing more PRs from you in the future! 💪 💜

**Pull request closed without merging**
