### PR TITLE
fix(docs): fix brand name -> gatsby-transformer-{cloudinary,yaml,remark}

### PR DESCRIPTION
**Pull request by JazibJafri**
## Description

changes: 
* Gatsby-transformer-cloudinary -> gatsby-transformer-cloudinary (always lowercase)
* gatsby-transformer-yaml -> `gatsby-transformer-yaml` (always in codeblocks)
* gatsby-transformer-remark -> `gatsby-transformer-remark` (always in codeblocks)

## Related Issues

#25290 `enhancement (docs): Improvements to retext-spell`

### CODE REVIEW

**Review by pvdz — CHANGES_REQUESTED** [review]
Hi @JazibJafri. Thanks for your PR.

Could you please expand this PR with a bunch of words from that dictionary, rather than just one? For example an acceptable PR would at least go through all plugins on the list and make them consistent, even double checking whether all the plugins in the monorepo are actually in there and making sure they're all spelled consistently.

I mean otherwise I might be tempted to think you're just doing the minimal effort for a certain piece of clothing. And I'm sure you really just wanted to help.

Also, please mark the words you've processed in the linked issue, as requested.

Thanks in advance!

**Comment by JazibJafri** [comment]
@pvdz hey I understand, I can definitely expand this PR, but don't you think it'll be much work for review if all plugins are processed in one PR? Let me know and I'll update with adding more plugins. Thanks

**Comment by pvdz** [comment]
Yes, but so is a single PR for each of those changes. Probably even more so.

**Comment by JazibJafri** [comment]
@pvdz I'll do it.

**Comment by JazibJafri** [comment]
> Also, please mark the words you've processed in the linked issue, as requested.

@pvdz Hey, I can't edit the original issue comment to add items to that list. No option to edit is visible to me.

**Comment by JazibJafri** [comment]
@pvdz I processed `gatsby-transformer-yaml` & `gatsby-transformer-remark` and the PR got lot of changes already. Is it now an acceptable PR? If not, let me know and I'll add some more plugins. Also I cannot edit the original comment, so if you can do that and add the plugins I'm processing here, that'd be great. Thanks in advance.

PS: If I did something wrong in this PR, let me know, and I'll fix it as soon as I can. :)

**Comment by JazibJafri** [comment]
@pvdz Also, tell me what did I do that failed the checks, so I fix them too.

**Comment by pvdz** [comment]
I'm not sure how to explain this properly but the bottom line is that I don't think this is a good PR.

If you look through the PR you can see that it leaves certain pages in a worst state, like when you change a header that mentions two package names and you only add backticks to one package name but not the other. I think that inconsistency is objectively a worse state than having no backticks at all.

There are some other cases where I'm not sure the backticks are useful or necessary. Fwiw, I hope you got your shirt, but I am going to close this issue.

**Pull request closed without merging**
