### PR TITLE
[WIP] Starter Showcase PR 

### PR DESCRIPTION
**Pull request by sw-yx**
related issue: https://github.com/gatsbyjs/gatsby/issues/5334

currently has a bug when two filters are active.

also want to make the detail pages and a way to link directly to starters that use a Gatsby dependency.

starter1

### CODE REVIEW

**Comment by tsiq-swyx** [comment]
new look 
image

**Comment by tsiq-swyx** [comment]
gatsbystarters

**Comment by tsiq-swyx** [comment]
https://dreamy-shannon-191f15.netlify.com/starter-showcase/

**Comment by sw-yx** [comment]
@KyleAMathews hmm should I re-PR to master?

**Comment by KyleAMathews** [comment]
Yeah — deleted the v2 branch yesterday as people were still PRing changes to it :-)

**Comment by sw-yx** [comment]
makes sense

**Pull request closed without merging**
