### PR TITLE
chore(gatsby): Unpin @reach/router version with latest release

### PR DESCRIPTION
**Pull request by blainekasten**
## Description

@reach/router published a 1.3.1 fixing the issue that was causing gatsby sites to not navigate correctly. This updates and unpin's the version. I've tested this manually and am hoping that our automated tests will catch anything else.

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
Looks like snapshots are failing because the `role=\"group\" ` is gone. @madalynrose should be able to add more context of if that's a good thing or bad!

**Comment by blainekasten** [comment]
Related commit and change: https://github.com/reach/router/commit/edea55da9160c9f3b54caaf3d23868f60395697a#diff-e7c4a8f76dc66da880856189f69b846cR22

Would love to understand more about this.. Feels like it might be the wrong approach

**Comment by trevorblades** [comment]
@blainekasten I just pushed a commit that removes `role=\\"group\\"` from the failing snapshots. This should make sense since the new version of `@reach/router` doesn't add this tag any more.

**Comment by trevorblades** [comment]
Now the e2e test for the development runtime is failing with `Error: Cannot find module 'isomorphic-fetch'`. I suspect this is unrelated to this change since `@reach/router` doesn't use this module, however I don't see other PRs failing with this error. I'll do some more digging later.

**Comment by trevorblades** [comment]
Everything is passing now, but the Gatsby Build step has been in progress for the last >1 hour. Is this typical? @gatsbyjs/inkteam

**Pull request merged**
