### PR TITLE
Allow sharp image processing for files without extension

### PR DESCRIPTION
**Pull request by cezarneaga**
s3 images can be saved without extension. this change allows those images to be processed.

### CODE REVIEW

**Comment by pieh** [comment]
maybe we could change `createRemoteFileNode` to attach ext for non extension files using something like https://www.npmjs.com/package/file-type ?

**Comment by cezarneaga** [comment]
Not sure that helps. 
here's an image example: https://impact-startarium.s3.eu-central-1.amazonaws.com/images/a_cover/original/020e4ede-24ac-45a2-ba2b-c632f62c6974

to this image if you read the file type and add it to the url as in `https://impact-startarium.s3.eu-central-1.amazonaws.com/images/a_cover/original/020e4ede-24ac-45a2-ba2b-c632f62c6974.png` the url isnt valid anymore.

or maybe i misunderstood your solution.

**Comment by KyleAMathews** [comment]
Perhaps we could add support to gatsby-source-filesystem for inferring the file type w/o a file extension. But we can't make this change as now _every_ file will be treated as an Image which doesn't make sense.

Ideally also you'd be able to add the file extension to the files you're downloading from s3.

**Comment by chpio** [comment]
@KyleAMathews ext guessing seems to be implemented now, but it's causing crashes:
```
Unexpected error value: "failed to process https://fakeimg.pl/300x300/?text=2\nError: ENOENT: no such file or directory, stat '.../.cache/gatsby-source-filesystem/7a1221ea4c61551f928908dd873a3738/300x300'"
```
the cache seems to assume that there's a file without an ext (cause there's no ext in the url) and crashes

**Comment by muescha** [comment]
@chpio could you create a new issue with your problem?

**Comment by chpio** [comment]
https://github.com/gatsbyjs/gatsby/issues/21901

it got closed without any explanation

**Pull request closed without merging**
