### PR TITLE
Quick grammar fixes in tutorial

### PR DESCRIPTION
**Pull request by twhiteaker**

### CODE REVIEW

**Comment by m-allanson** [comment]
See the new developer sign-off docs at https://www.gatsbyjs.org/docs/how-to-contribute/#developer-certificate-of-origin.

Or jump in here with any questions.

**Comment by twhiteaker** [comment]
e37cab5 shows "Signed-off-by: Tim Whiteaker <whiteaker@utexas.edu>" but I still see "DCO — The sign-off is missing."  Here's my shell output. Did I miss a step?
```
$ git commit --amend --signoff
[master e37cab5c] Update index.md, add signoff
 Date: Tue Apr 10 16:40:03 2018 -0500
 1 file changed, 1 insertion(+), 1 deletion(-)

me@computer MINGW64 ~/Documents/gatsby (master)
$ git push origin master -f
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Username for 'https://github.com': whiteaker@utexas.edu
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 533 bytes | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
To https://github.com/twhiteaker/gatsby.git
 + 35b902ed...e37cab5c master -> master (forced update)
```

**Comment by twhiteaker** [comment]
Thanks @pieh and @m-allanson!

**Comment by jlengstorf** [comment]
Hiya @twhiteaker! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
