### PR TITLE
chore(gatsby): migrate schema-composer and types/type-defs to typescript

### PR DESCRIPTION
**Pull request by ThakurKarthik**
## Description

1. Migrate `packages/gatsby/src/schema/schema-composer.js` to `schema-composer.ts`
2. Migrate `packages/gatsby/src/schema/types/type-defs.js` to `type-defs.ts`

## Related Issues

Related to #21995 

Hi @LekoArts I have made some file changes for migrating to typescript, please review this.All comments are most welcome as i am new to typescript, I will incorportate the changes in the review. 
Thanks !

### CODE REVIEW

**Comment by ascorbic** [comment]
Hi @ThakurKarthik 
This is failing typechecks. Can you run `yarn typecheck` in the root and see the errors that you need to fix? You can also click on one of the failing tests above to see the messages too.

**Comment by ThakurKarthik** [comment]
@ascorbic I will check and update the PR.Thanks !

**Comment by ThakurKarthik** [comment]
Hey @ascorbic ! I have fixed the typechecks by running `yarn typecheck` and also fixed some jest cases failing earlier, but i am not sure about what is failing now,can you see if any thing is missing in my current branch as it is saying some missing/does not exist package in failing tests.
Thanks !

**Comment by ThakurKarthik** [comment]
Hey @LekoArts can you tell what's failing these tests ? I am not sure what's causing the issue

**Comment by j0sh77** [comment]
Hey! Thanks so much for opening this pull request!

Sadly this PR got stale and didn't have any activity for some time. We're trying to do better with PR reviews! To get a better overview of all actionable PRs we're going through all open PRs and triage them. Since we won't be able to do everything and adding new features _always_ means added maintenance burden, we have to be more picky about what's beneficial for the average user and the project itself longterm.

We think this is a great PR and would love to see it land in Gatsby. We're closing this PR _for now_ but if you're able to rebase onto the latest `master` branch and try it out with the latest `next` versions, we'd be happy to review the PR when its re-opened.

We absolutely want to have you as a contributor and are sorry for any inconveniences we caused with replying too late to this PR.

Thanks for submitting to Gatsby! :purple_heart:

**Pull request closed without merging**
