### PR TITLE
docs: Add Recipe on Deploying to ZEIT Now

### PR DESCRIPTION
**Pull request by leo**
## Description

This is a follow-up to https://github.com/gatsbyjs/gatsby/pull/16398 and adds [ZEIT Now](https://zeit.co) (the easiest way to deploy Gatsby) to the list of recipes.

## Related Issues

No related issues.

### CODE REVIEW

**Comment by leo** [comment]
@marcysutton Thanks for the suggestion, I've applied it!

To answer your question: No, it's not necessary to have a GitHub account – that's merely an option in the onboarding. If you want to connect your GitHub account, you can do so. Otherwise, you can just skip it and deploy Gatsby without it.

**Comment by marcysutton** [comment]
Ok, thanks for the info! I think we should mention something about needing a Zeit account, since people might get derailed by that step.

**Comment by leo** [comment]
@marcysutton Okay! I added it to the requirements. 😊

**Comment by wardpeet** [comment]
Awesome! Thank you @leo, it's an US holiday so let's wait for @marcysutton to give a final approve ^^

**Comment by leo** [comment]
@wardpeet Got it. Thanks so much!

**Comment by leo** [comment]
Thanks!

**Pull request merged**
