### PR TITLE
Assets use file-loader instead of url-loader

### LINKED ISSUE #6963: [v2] url-loader for miscAssets? (webpack-utils.js)
## Summary

A small PDF file gets a base64 encoded URL, whereas in gatsby v1 it got a normal hashed URL.

## Relevant information

In [webpack-utils.js](https://github.com/gatsbyjs/gatsby/blob/001158ebe5725eed045fd8439c05e8abbc5916e7/packages/gatsby/src/utils/webpack-utils.js#L239-#L258) you define the url-loader for the loaders.file object and use it for audio, video and pdf files [here](https://github.com/gatsbyjs/gatsby/blob/001158ebe5725eed045fd8439c05e8abbc5916e7/packages/gatsby/src/utils/webpack-utils.js#L355-L360)

Is this wrong and it should be the normal file-loader (which is not producing base64 encoded urls) or is this the expected behavior and I should change my webpack config in the gatsby-node.js file to get the v1 behavior?

In my code is something like this:

```js
import downloadPdf from '../../assets/downloads/file.pdf';

<a href={downloadPdf} target="_blank">Download</a>
```

In gatsby v1 the URL is like this: `/static/file.a01dde10.pdf`.  
In gatsby v2 the URL is like this: `data:application/pdf;base64,JVBERi0xLjYNJeLjz9...lRU9GDQo=`

Thanks for any help or explanation!

### PR DESCRIPTION
**Pull request by zauni**
Fixes #6963

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit f0f24fad5919d2d2e6a61c6891b7103aa156f540

https://app.netlify.com/sites/using-postcss-sass/deploys/5b683b851f12b70f769aaa98

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit f0f24fad5919d2d2e6a61c6891b7103aa156f540

https://app.netlify.com/sites/gatsbyjs/deploys/5b683b841f12b70f769aaa8c

**Comment by KyleAMathews** [comment]
Thanks for jumping on this!

We don't actually want to eliminate the use of `url-loader` altogether. Most asset types we _do_ want to use the `url-loader` for smaller assets. It's just a few types like `pdf` (to start with, we can add others perhaps later) that we want to switch to always using `file-loader.`

**Comment by zauni** [comment]
How about something like this:

```js
  /**
   * Loads audio and video and inlines them via a data URI if they are below
   * the size threshold
   */
  rules.audioVideo = () => {
    return {
      use: [loaders.url()],
      test: /\.(mp4|webm|wav|mp3|m4a|aac|oga|flac)$/,
    }
  }

  /**
   * Loads assets without inlining
   */
  rules.miscAssets = () => {
    return {
      use: [loaders.file()],
      test: /\.(pdf)$/,
    }
  }
```

**Comment by KyleAMathews** [comment]
Looks great! If @jquense is around, I'm sure he has thoughts too as he wrote this code.

**Comment by zauni** [comment]
Gatsby v1 loaded font files also with file-loader ([link](https://github.com/gatsbyjs/gatsby/blob/b7d8d244cc7631fc325b4a139be5e3cbe6c3c9fe/packages/gatsby/src/utils/webpack.config.js#L422)), whereas v2 loads it with the url-loader. Some additional insight would be nice 👍 

This also reminds of this issue: https://github.com/facebook/create-react-app/issues/3722

Like, it would be nice to let the user decide what he wants

```js
import { url } from './image.png'; // file-loader
import image from './image.png'; // url-loader
```

But thats not solved yet :)

**Comment by KyleAMathews** [comment]
We think GraphQL is better for letting people specify transforms :-)

I think fonts are fine leaving w/ url-loader. We have url-loader setup to only inline assets < 10kb. If a font file is < 10kb then it's probably better to inline it to speed rendering.

PDFs are different as you _never_ want it inlined as you really only want a link so you can offer it to someone to download if they'd like so inlining is almost always a waste.

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by zauni** [comment]
Thank you very much for your fast responses!

**Comment by KyleAMathews** [comment]
Thank you very much for fixing the problem!

**Pull request merged**
