### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jdhorwitz**
Added in my site built with Gatsby, thank you so much!

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Awesome! Congrats on the launch!

**Comment by jdhorwitz** [comment]
Thank you so much,
Do you have any suggestions on how to go about learning react/redux? I'm going to document it all

Joshua Horwitz Senior Software Engineer
On Mon, Aug 1, 2016 at 10:39 PM, Kyle Mathews <notifications@github.com> wrote:
Awesome! Congrats on the launch!

**Comment by KyleAMathews** [comment]
On React i'd say build more Gatsby sites ;-)

Beyond that, there's a number of good tutorials on Redux. I don't have any
particular recommendations as I don't use Redux. I'd focus though first on
React. Redux is often not needed for React projects.

**Comment by jlengstorf** [comment]
Hiya @jdhorwitz! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
