### PR TITLE
[1.0] Added support for html image tags in the gatsby-remark-responsive-image

### PR DESCRIPTION
**Pull request by chiedo**
Prior to this additions

This would work

```
![](image.png)
```

This wouldn't work

```
<img src='image.png' />
```

Now they should both work.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks! These are really great, we're really starting to fill in a lot of edge cases/gaps etc. in Gatsby's functionality which is exciting to see.

BTW, could you add a quick example of this to the https://using-remark.gatsbyjs.org/ example website? Perhaps showing how you can use the `` form to add inline styles to an image which is a fairly common need.

**Comment by chiedo** [comment]
Yes I can @KyleAMathews :)

Now that I'm starting to understand how things work with Gatsby 1.0 as far as the codebase is concerned, I hope my questions decrease haha and my solutions increase.

Really impressed and thankful for what you've built.

This will be a dumb question though which is ironic. Where can I find the codebase for https://using-remark.gatsbyjs.org/?

**Comment by KyleAMathews** [comment]
>I hope my questions decrease haha and my solutions increase.

you've already submitted more useful PRs than 99% of people so I think you're doing great :-D

>Where can I find the codebase for https://using-remark.gatsbyjs.org/?

In the examples folder in 1.0

**Comment by chiedo** [comment]
Here you go! 

https://github.com/gatsbyjs/gatsby/compare/1.0...chiedo:topic/inline-html-img-tags-in-remark?expand=1

**Pull request merged**
