### PR TITLE
[gatsby-plugin-sharp] Add "opacity" setting to the "duotone" option

### PR DESCRIPTION
**Pull request by fk**
Allows mixing the duotone version with the original image: Given an `opacity`, a semi-transparent version of the duotone version is composited over the original image. This works by adding an alpha channel to the duotone'd image (after [flattening](http://sharp.dimens.io/en/stable/api-operation/#flatten) a potentially existing one) – then sharp does all [teh magic](http://sharp.dimens.io/en/stable/api-composite/#overlaywith): 

> If the overlay image contains an alpha channel then composition with <a href="https://en.wikipedia.org/wiki/Alpha_compositing">premultiplication</a> will occur.

Nothing super amazing, but hey … how about a "watermark" option?
How 'bout gatsby-plugin-sharp-plugins? :P

---

I added the duotone filter as an easy way to spice up the images used on (the otherwise very bare-bones) yisela.com. A few months later, we decided to "tone it down" a little on the image side while keeping the "each post has it's own colorspace" thing going, and the "shadow" and "highlight" colors already defined to duotone the images served as a good base for this.

Here's duotone, 50% opacity and the original image side-by-side:

image

WIP, todo:

* [x] Rename the whole thing to "opacity" :)
* [x] Add documentation
* [x] Add example to examples/image-processing

### CODE REVIEW

**Comment by fk** [comment]
image

**Comment by fk** [comment]
Ready!

**Comment by KyleAMathews** [comment]
Looks awesome, thanks!

**Comment by fk** [comment]
And thank you! :)

Sorry about teh format!
You think I should take a look at gatsby-remark-images x gatsby-image btw.?

**Pull request merged**
