### PR TITLE
chore(starters): update gatsby-theme-oss

### PR DESCRIPTION
**Pull request by robinmetral**
## Description

The `gatsby-starter-under-construction` was redesigned, renamed and extended into a Gatsby Theme: https://github.com/robinmetral/gatsby-theme-oss ([demo](https://gatsby-theme-oss.netlify.com/)).

This PR updates its details in the Starter Library.

### Documentation

None.

## Related Issues

None.

### CODE REVIEW

**Comment by robinmetral** [comment]
Any idea what's going on with the CI's `starters_validate` check? It seems that it's failing on a dependency audit.

**Comment by laurieontech** [comment]
Thanks for the PR! At the moment, we don't include themes in the starters showcase. Given that the starter was redesigned it likely makes the most sense to remove it from the starters list and add a site that is using the theme to the site showcase?
Since that's a significant change from this PR I'll close this one. Appreciate your work creating more community resources!

**Comment by robinmetral** [comment]
Thanks @laurieontech for the info!

The theme actually includes a starter (basically the theme's demo), which is also deployed to Netlify [here](https://gatsby-theme-oss.netlify.com/). Would it make sense to simply update the repo link to point the `starter` directory?
```yaml
repo: https://github.com/robinmetral/gatsby-theme-oss/tree/master/starter
```

Alternatively, I've seen that some contributors create starters using themes in separate repos, and publish those to the starter library. Would this be better? (although it goes against the theme monorepo approach recommended in [gatsby-starter-theme-workspace](https://github.com/gatsbyjs/gatsby-starter-theme-workspace/)).

**Comment by laurieontech** [comment]
If there is a starter using a theme then that's a great option!

**Comment by robinmetral** [comment]
@laurieontech thank you!

I looked into it, and actually it's not enough to have the starter as part of a monorepo, because then bootstrapping with `gatsby new` wouldn't work (it expects a standalone GitHub repo).

A workaround that others have been relying upon is to extract the starter from the theme on merge, and auto-publish it to a separate repo. There's even a nice GitHub Action for this: [`johno/actions-push-subdirectories`](https://github.com/johno/actions-push-subdirectories)

I've set it up for my theme, and the starter is now published and ready to be used at [`robinmetral/gatsby-starter-oss`](https://github.com/robinmetral/gatsby-starter-oss). I've updated the PR accordingly.

Let me know if anything else is missing!

PS. the CI is still failing:
> Any idea what's going on with the CI's starters_validate check? It seems that it's failing on a dependency audit.

**Pull request merged**
