### PR TITLE
fix typo and remove repetition about page queries having access to pa…

### PR DESCRIPTION
**Pull request by janosh**
…geContext

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 973f67daf4d15e6ca8b5a4a70edda0819ccdba50

https://app.netlify.com/sites/gatsbyjs/deploys/5b7295e082d3f145d9f4ab39

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 973f67daf4d15e6ca8b5a4a70edda0819ccdba50

https://app.netlify.com/sites/using-postcss-sass/deploys/5b7295e282d3f145d9f4ab45

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit 973f67daf4d15e6ca8b5a4a70edda0819ccdba50

https://app.netlify.com/sites/using-contentful/deploys/5b7295e382d3f145d9f4ab54

**Comment by m-allanson** [comment]
Thanks @janosh! I reverted one change as I think the original version was as intended. Then I took a go at clarifying the differences between page query and StaticQuery. Do you think that's clearer or should I revert it back to your edit? 

cc'ing @amberleyromo to take a look too.

**Comment by amberleyromo** [comment]
@m-allanson @janosh this is great, y'all 👍🏼

**Comment by janosh** [comment]
@m-allanson @amberleyromo  Sorry, to do this piece by piece, but there are two more things I would change:
- The example on how to do type checking with `StaticQuery` woukd actually throw a deprecation warning since it doesn't explicitly import `query` from `gatsby`.
- The v2 migration guide mentions that GraphQL queries that don't use query variables, i.e. all static queries no longer need the `query` keyword. I think it should therefore be removed in the docs whereever possible.

Shall I reopen the branch with those changes?

```js
import React from "react"
- import { StaticQuery } from "gatsby"
+ import { StaticQuery, query } from "gatsby"
import PropTypes from "prop-types"

const Header = ({ data }) => (
  <header>
    <h1>{data.site.siteMetadata.title}</h1>
  </header>
)

export default props => (
  <StaticQuery
    query={graphql`
-     query {
+    {
        site {
          siteMetadata {
            title
          }
        }
      }
    `}
    render={data => <Header data={data} {...props} />}
  />
)

Header.propTypes = {
  data: PropTypes.shape({
    site: PropTypes.shape({
      siteMetadata: PropTypes.shape({
        title: PropTypes.string.isRequired,
      }).isRequired,
    }).isRequired,
  }).isRequired,
}
```

**Pull request merged**
