### PR TITLE
fix(gatsby-react-router-scroll): debounce function for scollListener

### LINKED ISSUE #26878: gatsby-react-router-scroll: scrolling performance
Currently scroll handler for saving scroll position in session storage fires about 60  times per second, but it should fire only when user stop scrolling? Should it be debounced? I noticed poor scrolling performance on phone on gatsby sites with this just this one scroll listener.

### PR DESCRIPTION
**Pull request by ahmetcanaydemir**
## Description
Added debounce function to improve scrolling performance.

## Related Issues
Fixes #26878

### CODE REVIEW

**Comment by wardpeet** [comment]
Do we want to debounce or rather throttle? + Do we want to explicitly save it on componentWillUnmount?

**Comment by ahmetcanaydemir** [comment]
@wardpeet if you are asking to me, this is my first contribution so I am not sure for throttle. Besides,  `componentDidUpdate` uses **scrollPosition**, could save in `componentWillUnmount` be a problem?

**Comment by pindjur** [comment]
i cannot think of situation where  throttle is better than debounce in this case

**Review by wardpeet — APPROVED** [review]

**Comment by wardpeet** [comment]
I changed it a little bit to use rAF so we're sure to update on time but keep perf.

Thank you for your PR!

**Pull request merged**
