### PR TITLE
Warn users when sharp is used for large images

### PR DESCRIPTION
**Pull request by oorestisime**
Contributes: #11798

This ia draft because:

- [ ] i am not sure how to generate shortened link
- [ ]  Should we update the documentation to talk about the thresholds and how to configure them?
- [ ] I think it is a little hacky to export the warn function but at the same time it enables me to unit-test this easily. Or maybe I should put it in a different file ?
- [ ] i need to test this on using-remark or similar to see if the output is too much or ..

### CODE REVIEW

**Comment by pieh** [comment]
> * I think it is a little hacky to export the warn function but at the same time it enables me to unit-test this easily. Or maybe I should put it in a different file ?

Normally it would be fine to export, but given that those exports are user facing, then yeah probably moving it to some `utils` (or something like that) file would be good idea (to not export internals to users).

> [ ] i need to test this on using-remark or similar to see if the output is too much or ..

What we could do is track if we already displayed message for image and not show it again for same source file - maybe also add some tracking that if there are over 10 images that cause this warning to stop showing this in console? and say "X more"?

**Comment by LekoArts** [comment]
Hey @oorestisime and @pieh 👋 Any suggestions on what to do with this PR? If you don't have the time at the moment we could close this or edit this PR to a warning in the docs first?

**Comment by oorestisime** [comment]
hey @LekoArts thanks for pinging me here! I somehow forgot this! I ll try and work on this sometime next week!

**Comment by freiksenet** [comment]
Thank you very much for working on this @oorestisime! 

As this PR hasn't had much activity lately, we are going to close for now, as part of our regular stale PR cleanup. However, we feel this PR is valuable for Gatsby, so feel free to reopen it when you have time to update it.

Thank you very much for your contribution! :purple_heart: :muscle:

**Pull request closed without merging**
