### PR TITLE
chore(starters): Add gatsby-theme-sky-lite starter

### PR DESCRIPTION
**Pull request by iRyanBell**
## Description

Adding a new lightweight starter for modular theme stacking: Sky Lite.

## Related Issues

n/a

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! I noticed in the READ ME that the recommended instructions for running this in development is not `gatsby develop`. Is there a reason for that?

**Comment by iRyanBell** [comment]
@laurieontech The package.json script calls `gatsby develop` through `npm start` or `yarn start`, both of which are shorter commands.

**Comment by laurieontech** [comment]
@iRyanBell You’re definitely right about yarn develop or npm develop being shorter commands. However, we encourage documenting gatsby develop (and gatsby build) as a way to run your site for the following reasons:
- It’s consistent with the rest of our documentation so reduces the likelihood of confusion for our users
- It’s easier to pass in command line flags to gatsby
Also, gatsby-cli is already a required global dependency when using Gatsby. Could you please update the README to follow this? :slightly_smiling_face:

**Comment by iRyanBell** [comment]
@laurieontech Got it. Updated 👍

**Comment by laurieontech** [comment]
Thanks! Looks great.

**Pull request merged**
