### PR TITLE
feat(gatsby): Add "gatsby plugin add" command

### PR DESCRIPTION
**Pull request by ascorbic**
Adds a WIP gatsby plugin add command, which uses the recipes providers to install the npm package and add the plugin to the config

[ch17925]
[ch17779]

### CODE REVIEW

**Review by wardpeet — COMMENTED** [review]
Can we not add these commands to gatsby but keep them in gatsby-cli?

**Comment by ascorbic** [comment]
@wardpeet By putting them in gatsby we can be sure that when running on a site we're using a version of the command that matches the site's version of gatsby. If they're using the command in a globally-installed version of gatsby-cli we can't be sure of that. While at this stage we're not doing much in the commands, this will change. We'll be doing options validation, for example, which uses lots of code in the gatsby package.

**Comment by wardpeet** [comment]
Sure but why does that matter? If 
I use `gatsby plugin add` on a project that did not bootstrap yet no yarn install. This command will fail for no real reason other than that we need gatsby to actually run this command. Plugin validation can also be done in gatsby-cli.

We need to keep things decoupled so we can iterate more quickly and keep things where they belong.

**Comment by ascorbic** [comment]
We need a better way of handling the global CLI. This would be moot if it defaulted to the locally-installed version. As it stands, we rely on the fact that most people call the cli via an npm script, because nobody updates the global CLI. Putting stuff in the CLI package means that we're never able to make breaking changes.

**Comment by mxstbr** [comment]
Closing as this will be shipped as part of #27703!

**Pull request closed without merging**
