### PR TITLE
fix(gatsby): Add reporter.panic in empty catch in load-themes

### LINKED ISSUE #29545: Add reporter.panic to empty catch in load-themes
In my case I did use a wrong version of Gatsby and I ve got an incorrect error about it

to replicate just change version to a wrong one in package.json of Gatsby and 
semver will throw out an error than the catch on 
https://github.com/gatsbyjs/gatsby/blob/a6be92eb80bb98c308310a0fb3c340dab8e104aa/packages/gatsby/src/bootstrap/load-themes/index.js#L40

do not output and do not stop the code.

as a result themeDir in 
https://github.com/gatsbyjs/gatsby/blob/a6be92eb80bb98c308310a0fb3c340dab8e104aa/packages/gatsby/src/bootstrap/load-themes/index.js#L44
is null

and send to the user an error not related

I think output the catch and stop the execution will be more relevant

### PR DESCRIPTION
**Pull request by blenderskool**
## Description
This PR adds a `reporter.panic` in an empty `catch` block within `load-themes/index.js` file, and hence throws the error caught in the block instead of reporting an unrelated error in the later `if (!themeDir)` block.

I'm not sure if additional context needs to be passed here or just throwing the error caught is sufficient.

## Related Issues
Fixes #29545

### CODE REVIEW

**Comment by AbsoluteSuccess** [comment]
The documentation for the ```reporter.panic``` says that this function should receive 2 arguments like so:
```reporter.panic(`text`, new Error('something'))```
The link to the documentation: https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/
Correct me if I am wrong.

**Comment by blenderskool** [comment]
@AbsoluteSuccess Right, I had checked the expected types for `reporter.panic` and it seemed like passing `Error` object as 1st argument is also valid because of the definition of `ErrorMeta`  here

https://github.com/gatsbyjs/gatsby/blob/b3b19d30a560a8e66dbd0258461d4fb44e386eb7/packages/gatsby-cli/src/reporter/types.ts#L4-L13

Either we can change to pass two arguments or maybe update the documentation if things have changed over time. @LekoArts What do you suggest?

**Comment by LekoArts** [comment]
Internally we sometimes only receive the `Error` (and it's a fallback), but whenever possible a text should be passed (so the public API description is recommending best practice here).

**Review by LekoArts — APPROVED** [review]
Thanks!

**Pull request merged**
