### PR TITLE
Adds meetfabric.com to readme

### PR DESCRIPTION
**Pull request by scottyeck**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Cool! Congrats on the launch!

**Comment by scottyeck** [comment]
@KyleAMathews Thanks!

Ps. Is there a _gatsby_ slack channel or gitter (or similar)? We love _gatsby_ and would love to be a part of the conversation!

**Comment by KyleAMathews** [comment]
yup! We're on Discord #gatsby — join link is https://discord.gg/0ZcbPKXt5bVoxkfV looking forward to seeing y'all there!

**Comment by jlengstorf** [comment]
Hiya @scottyeck! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by scottyeck** [comment]
@jlengstorf Thanks a ton for the kind shoutout here. Please excuse me while I crawl out of my email hole.

Appreciate the swag offer and would love to join as a maintainer, though I'm not sure I got that email invite. Regardless, we at Fabric are chugging along with Gatsby and are glad to be a part of it all. 😎🌈

**Pull request merged**
