### PR TITLE
chore(babel-preset-gatsby-package): Convert TS

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Description
Convert `babel-preset-gatsby-package` to TS

## Related Issues
Related to #21995

### CODE REVIEW

**Comment by blainekasten** [comment]
This is great! However, I think that the resolver.js needs to stay, it's sort of a set up to let the jest tests mock the require.resolve function. I suspect thats why tests are failing. Revert that and I think this will pass and we can merge!

**Comment by MichaelDeBoey** [comment]
@blainekasten I've done this, because we do this in other places too

https://github.com/gatsbyjs/gatsby/blob/f0724e8d6e6164d5488cebc17032bd6f8ed45f0a/packages/babel-preset-gatsby/src/dependencies.js#L5

https://github.com/gatsbyjs/gatsby/blob/f0724e8d6e6164d5488cebc17032bd6f8ed45f0a/packages/babel-preset-gatsby/src/index.js#L3

**Comment by blainekasten** [comment]
@MichaelDeBoey I understand that, but the reason the tests are failing is because of this change. This was intentionally set up so we could mock require.resolve and have stable tests. So if you revert it, tests will pass and then I can merge it!

**Comment by pieh** [comment]
I'm not so sure about converting this package? This package doesn't have any package build setup - there is nothing in here to go from TS to JS - and we would have to have different setup, because this is `babel-preset-gatsby-package` so it can't use same preset to build itself I feel like?

**Comment by blainekasten** [comment]
@pieh good point. This package benefits relatively little from TS, and we would need to change the infra on this package to work. @MichaelDeBoey thank you so much for your work on this, and sorry it was on lost effort. We're going to close this and remove the package from the list of qualified transitions.

Again, thank you so much and I hope you can keep involved with the transition. You've been extremely responsive and helpful! 🎉

**Pull request closed without merging**
