### PR TITLE
plugin authoring blogpost first draft

### PR DESCRIPTION
**Pull request by shannonbux**
@oorestisime, @TylerBarnes, @rexxars, @ChristopherBiscardi, @pieh, @m-allanson is it alright with you if I mention you to thank you in this post? I will probably link to your twitter or github accounts too, if you're cool with that. There are also a couple quotes.

### CODE REVIEW

**Comment by oorestisime** [comment]
yeap and thanks :)
(small note from the draft, I am not the author of gatsby-source-pilon, i have just worked on it as part of a contract)

**Comment by rexxars** [comment]
Of course! And thanks 😊

**Comment by TylerBarnes** [comment]
Totally cool with that :)

**Comment by ChristopherBiscardi** [comment]
@shannonbux cool with me 👍

**Comment by m-allanson** [comment]
@shannonbux all good with me too :)

**Comment by missmatsuko** [comment]
I noticed this folder is in the docs root which seems kind of out of place:
https://github.com/gatsbyjs/gatsby/tree/master/docs

Was this intentional (because it's a draft?) or should it be moved?

The page does seem to be public on the site already:
https://www.gatsbyjs.org/2019-04-25-plugin-authoring-study/

**Comment by KyleAMathews** [comment]
@missmatsuko that was a mistake — I'll move it real quick

**Comment by KyleAMathews** [comment]
Thanks for noticing!

**Comment by shannonbux** [comment]
yes @missmatsuko thank you for noticing!

**Pull request merged**
