### PR TITLE
fix(gatsby): make SSR more compatible with PnP (fixes gatsby-plugin-sitemap usage in PnP)

### PR DESCRIPTION
**Pull request by Js-Brecht**
## Description

This makes plugin `gatsby-plugin-sitemap` compatible with yarn 2.

There is an issue with the packages that `gatsby-plugin-sitemap` imports into `gatsby-ssr`.  Because of how that file gets bundled into `public/render-page.js` by webpack, it contains a couple of `require()` statements for packages that don't exist for the project.  Specifically, `minimatch` and `pify`.

We know those dependencies exist for `gatsby-plugin-sitemap`, so I just needed to tell the parent where to find them.  To do that, I used `babel-plugin-module-resolver` to `require()` each package from its absolute path, relative to `gatsby-plugin-sitemap`.

However, using that babel plugin like that could potentially cause issue if other plugins, or the root project, need to use their own specific versions of those packages.  The solution was to use a custom resolver that will only allow the paths to be resolved if they are the ones that belong to `gatsby-plugin-sitemap`.

Because it was dropping the `resolvePath` option with the custom paths resolver function, I had to use `setBabelPreset`, so that babel would pull the `module-resolver` plugin setup during its runtime, instead of storing that setup using `setBabelPlugin`. 

## Related Issues

Related to https://github.com/gatsbyjs/gatsby/issues/20949#issuecomment-594312803

### CODE REVIEW

**Comment by pieh** [comment]
This should not be fixed in plugin, instead this should be fixed in core. I assume this is related to webpack externals that we use for SSR? https://github.com/gatsbyjs/gatsby/blob/83ae63daad88ce1ee294e0f7092fbae72caa58da/packages/gatsby/src/utils/webpack.config.js#L532-L591

I do wonder if we should instead just:
 a) remove `minimatch`, `pify` and `es6-promise`
 b) or make that work somehow with those being imported from plugins (tho I don't see a way to do it)

**Comment by Js-Brecht** [comment]
It would make sense to me to remove those from the externals list.  Do you know what the reasoning was behind making them an external?

**Comment by pieh** [comment]
Putting things into `externals` is speeding up SSR bundle generation (because webpack doesn't need to bundle those). This doesn't work very well with PnP approach tho (or rather it relies on those modules being top level in `node_modules` and generally skips package dependencies check).

Mael (@arcanis) did initial fixes here (with distinction between gatsby deps and peerDeps. But really userExternalList should only contain peer dependencies of gatsby that user will need to install (react and react-dom). Having anything more there is dangerous.

Also check https://github.com/gatsbyjs/gatsby/pull/14208 (description and comments)

**Comment by Js-Brecht** [comment]
Okay, that makes sense.  The SSR speed was something I was measuring while I was making these changes, to see how much the path resolutions were affecting it... I will see what kind of impact removing those packages from the list causes.

In case the impact is high, I wonder if it would make sense to include some similar logic like `babel-plugin-module-resolver` in the core (a custom effort, though, because of how it implements its visitors), and then add a hook like `addModuleResolution` to `onCreateBabelConfig` (maybe with an `external: boolean` option to automatically add it to the Webpack externals list?).  

With that kind of hook, the core and plugins could add/use dependencies that are required, but cause a performance hit so shouldn’t get bundled.  The paths could be resolved during the bundling, but the dependency itself doesn’t get bundled.  This would make the process available to 3rd party plugins, too, that might include some heavy weight deps, and don’t want it to have a severe impact on consumer’s builds.

**Comment by pieh** [comment]
Would be interested to hear about perf impact of removing those tho. If it's even hard to measure for those 3 - I wouldn't even think about it too much and just remove them. The heavy hitters here is react-dom and core-js I think and those will stay as externals.

I don't like having to come up with additional API surface and some even more complex setup to account for cases like this.

**Comment by Js-Brecht** [comment]
I’ve been trying to sneak some time in to run some test cases; hopefully in the next couple days I’ll have something to report.

This plugin alone seems to add quite a bit of time to SSR... it definitely has some hang time.

**Comment by Js-Brecht** [comment]
@pieh okay, I traced a dozen runs each, using a few different scenarios:
* With the externals list, without sitemap
* With the externals list, with sitemap
* Without the externals list, without sitemap
* Without the externals list, with sitemap

I tracked the duration of the JS/CSS bundling, and the static HTML creation.

What's interesting is there was very little appreciable difference.  All of the runs were, on average, within 10-30 ms of each other.  This was all with a pretty light site.  Usually only takes ~30s to build as it is... didn't really have anything larger on-hand to test with.  Even though the site itself is relatively small, I would have expected to see an impact from these changes if it was going to be at all noticeable. :man_shrugging: 

I went ahead and removed `es6-promise`, `pify`, and `minimatch` from the externals list, and reverted the changes I had made originally.

Important to note: this fixes the issue with `gatsby-plugin-sitemap`, and fixes some issues I had also been having with `@emotion`, too.

**Comment by pieh** [comment]
Published in `gatsby@2.19.42`

**Pull request merged**
