### PR TITLE
[gatsby-transformer-javascript-frontmatter] Parse out js and typescript files

### PR DESCRIPTION
**Pull request by olehchem**
On my project I use typescript. So, I need to get frontmatter from typescript files as well.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Will this work though? Babel 6, which this is using, can't parse Typescript. If we update to babel 7 this could work. The transformer directly parses files to pull out the exported data.

**Comment by olehchem** [comment]
Yes, you are right. 
Babylon 6 which is used to parse files can't work with Typescript :( 
Actually, I tested on some .ts and .tsx files and it worked. 
I guess it is because ```exports.frontmatter = ``` and ```export const frontmatter = ``` statements where parsed correctly.

**Comment by KyleAMathews** [comment]
You could upgrade this plugin to Babel 7 which would get this working. This plugin uses Babel independently of the rest of Gatsby so it wouldn't be a breaking change.

**Comment by olehchem** [comment]
As I know babel 7 is still in beta and isn't available on npm.  :(

**Comment by KyleAMathews** [comment]
Babel 7 is available on NPM — we're using it for Gatsby v2 and it's already really stable. It's a fantastic upgrade https://github.com/gatsbyjs/gatsby/blob/f98688eefba89eb72254e1e5ab0627cdd9be239f/packages/gatsby/package.json#L14

**Comment by olehchem** [comment]
Hi,
I have updated the dependencies and tested on my project. It works :)
Thank you for your help.

**Comment by m-allanson** [comment]
Thanks @olehchem!

**Comment by jlengstorf** [comment]
Hiya @olehchem! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
