### PR TITLE
Removed unregistering of service workers on reload

### PR DESCRIPTION
**Pull request by prajapati-parth**
## Description

Fixed issue https://github.com/gatsbyjs/gatsby/issues/9770

### CODE REVIEW

**Comment by davidbailey00** [comment]
> Let's see if we can make this only remove gatsby-plugin-offline instances?

I think in this case it _does_ make sense to remove all service workers.

Firstly, SWs are port-specific, so for example if you're testing a production build on port 9000, the worker won't be removed when testing the development version on port 8000. Therefore it shouldn't interfere with SWs from other HTTP servers as long as they're on different ports.

Secondly, I think if anything, it's more important to remove _non-Gatsby_ service workers, rather than vice versa. Otherwise there would be random things going on outside of our control if another SW is installed from a different non-Gatsby site on the same port.

**Comment by prajapati-parth** [comment]
> Secondly, I think if anything, it's more important to remove non-Gatsby service workers, rather than vice versa.

Isn't the main purpose of this PR to not remove non-Gatsby service workers? I tried developing firebase cloud messaging on a gatsby site and every time I reload the page in development mode, it de-registers the service worker.

**Comment by davidbailey00** [comment]
> Isn't the main purpose of this PR to not remove non-Gatsby service workers? I tried developing firebase cloud messaging on a gatsby site and every time I reload the page in development mode, it de-registers the service worker.

Ah, I understand the reasoning now. In this case I think it does make sense to remove this code and possibly display a warning instead - we can't really tell which SWs a user wants to keep or not so it's best not to guess, but at least if we display a warning in the console then it'll save people time when they're confused about why a site isn't updating on refresh.

@DSchau thoughts on this?

**Comment by DSchau** [comment]
> Isn't the main purpose of this PR to not remove non-Gatsby service workers? I tried developing firebase cloud messaging on a gatsby site and every time I reload the page in development mode, it de-registers the service worker.

This seems like a reasonable use case--to me. I don't think we should remove "user code" that we're not in control of.

> Ah, I understand the reasoning now. In this case I think it does make sense to remove this code and possibly display a warning instead - we can't really tell which SWs a user wants to keep or not so it's best not to guess, but at least if we display a warning in the console then it'll save people time when they're confused about why a site isn't updating on refresh.

Warning/prompt is _OK_ but some outstanding questions are helpful:

1. Is it reasonable to remove the **Gatsby** service worker in development?
    - I think the answer to this is (apparently and historically) yes.
1. Is it reasonable to remove _all_ service workers?
    - I think the answer to this is probably no--especially if it's breaking/preventing a development workflow for a common tool like Firebase.
1. Is there a clean way to remove a Gatsby specific service worker?
    - e.g. filename is _decent_ (sw.js) but some way to uniquely identify would be even better

That being said--the solution should not be to entirely prevent removal of _any_ service workers here (as in this PR)--we should target the Gatsby service worker for removal and leave others alone.

**Comment by prajapati-parth** [comment]
> Is there a clean way to remove a Gatsby specific service worker?
e.g. filename is decent (sw.js) but some way to uniquely identify would be even better

Correct. Because most of the services that ask users to create service workers with a specific name also allows them to configure the use of an existing service worker with different name. Eg. Firebase cloud messaging needs a SW with name firebase-messaging-sw.js but it can also be configured with name sw.js. So we'll definitely need other way for unique identification.

**Comment by davidbailey00** [comment]
I've created a PR at #13716 in favour of this one, which warns about SWs detected but doesn't remove them. In development, we shouldn't have any Gatsby SWs since gatsby-plugin-offline only creates a SW in production mode, so I think detecting the "creator" of a SW might be unnecessary.

As a result I'll be closing this PR, but thanks anyway your contribution! Feel free to open an issue or another PR in the future if you feel anything else is wrong and we'll be sure to have a look :)

**Pull request closed without merging**
