### PR TITLE
Add support to plugin-offline for precaching preloaded fonts/json files

### LINKED ISSUE #7066: Add "preload" items to service worker cache
A page's JSON file isn't being cached which prevents offline from working. Also we should precache critical fonts.

### PR DESCRIPTION
**Pull request by KyleAMathews**
Fixes #7066

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 365bb7d7a20c36fa1761d90729318450b2774de9

https://app.netlify.com/sites/gatsbyjs/deploys/5b695ca13813f0678121bac3

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 365bb7d7a20c36fa1761d90729318450b2774de9

https://app.netlify.com/sites/using-postcss-sass/deploys/5b695ca33813f0678121bacf

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 365bb7d7a20c36fa1761d90729318450b2774de9

https://app.netlify.com/sites/using-glamor/deploys/5b695ca43813f0678121bad8

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbygram* failed.

Built with commit 365bb7d7a20c36fa1761d90729318450b2774de9

https://app.netlify.com/sites/gatsbygram/deploys/5b695ca23813f0678121bac6

**Comment by KyleAMathews** [comment]
Deploy preview for *using-styled-components* failed.

Built with commit 365bb7d7a20c36fa1761d90729318450b2774de9

https://app.netlify.com/sites/using-styled-components/deploys/5b695ca43813f0678121badb

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit 365bb7d7a20c36fa1761d90729318450b2774de9

https://app.netlify.com/sites/image-processing/deploys/5b695ca33813f0678121bad5

**Comment by kkemple** [comment]
oh this looks good! nice refactor!

**Pull request merged**
