### PR TITLE
Add gatsby-plugin-builder

### PR DESCRIPTION
**Pull request by teleaziz**
## Description

Plugin for integrating [Builder.io](https://www.builder.io) with Gatsby.

### Documentation
it puts the Builder.io schema under an `allBuilderModels` field of the Gatsby GraphQL query, If a templates map in options, this plugin will create pages dynamically for each model entry on the path specified.

#### Install

`npm install --save gatsby-plugin-builder`

#### How to use

```javascript
// In your gatsby-config.js
const path = require('path')
module.exports = {
  plugins: [
    {
      resolve: "gatsby-plugin-builder",
      options: {
        // public API Key
        publicAPIKey: "MY_PUBLIC_API_KEY",
        templates: {
          myPageModel: path.resolve('templates/my-page.tsx')
        }
      },
    },
  ]
}

```

#### How to Query
For an up-to-date complete examples check out the examples on [BuilderIo/SDK](https://github.com/BuilderIO/builder/tree/master/examples)

```graphql
{
  allBuilderModels {
    myPageModel {
      everything
    }
  }
}
```

### CODE REVIEW

**Comment by pieh** [comment]
Hi @teleaziz 

It's unlikely that we will merge this PR into gatsby monorepo - we don't have lot of context on the BuilderIO so we won't be able to properly support the plugin. So the plugin being in our repo, would just make us a bottleneck for the maintenance and future development of it (ultimately it would be on us to make final reviews and approval)

We are actually in the process of trying move some of the plugins that we already have in the repository to separate repositories and hand over maintenance of those to community.

**Comment by pieh** [comment]
To add to the above - our plugin library ( https://www.gatsbyjs.org/plugins/ ) shows plugins maintained by community ( if the plugin follows requirements listed in https://www.gatsbyjs.org/contributing/submit-to-plugin-library/ ). So there's really not that much benefit for anyone to maintaining the plugin in this repository.

**Comment by teleaziz** [comment]
Thanks Michael for taking a look, I agree with your points.

moving this to https://github.com/BuilderIO/builder/tree/master/packages

**Comment by muescha** [comment]
@teleaziz 

i think, a `sourcing-from-builderio` guide in this section would be a a nice option to add the builder.io cms?
https://www.gatsbyjs.org/docs/headless-cms/#how-to-add-new-guides-to-this-section

**Comment by teleaziz** [comment]
I'll write up a guide and send a pr, thanks @muescha, great suggestion!

**Pull request closed without merging**
