### PR TITLE
Update adding-search.md

### PR DESCRIPTION
**Pull request by deemaagog**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 40404fea61d7e654faa42662d4ef6a6353cac7a4

https://app.netlify.com/sites/using-postcss-sass/deploys/5b4efd9afdd72a3d0edf0c4d

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbygram* failed.

Built with commit 40404fea61d7e654faa42662d4ef6a6353cac7a4

https://app.netlify.com/sites/gatsbygram/deploys/5b4efd99fdd72a3d0edf0c47

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit 40404fea61d7e654faa42662d4ef6a6353cac7a4

https://app.netlify.com/sites/image-processing/deploys/5b4efd9afdd72a3d0edf0c51

**Comment by m-allanson** [comment]
Cherry-picked to `v1`

**Pull request merged**
