### PR TITLE
Replace gatsby-source-stripe-products with gatsby-source-stripe

### PR DESCRIPTION
**Pull request by njosefbeck**
Got it done! Yahoo!

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Looks like there's a conflict.

**Comment by njosefbeck** [comment]
OK, I think I've fixed the conflict...

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 52e72772bb59ef41fefa1dcbb34cb52a4d310680

https://app.netlify.com/sites/using-glamor/deploys/59f7b060a6188f504bfeeba7

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
