### PR TITLE
chore: removed unused imports and changes related to code formatting

### PR DESCRIPTION
**Pull request by KirankumarAmbati**

### CODE REVIEW

**Comment by KirankumarAmbati** [comment]
**CC:** @DSchau

**Comment by KirankumarAmbati** [comment]
**chore: removed unused imports and changes for code formatting** change set is the current one. The rest of them came through merges.

**Comment by DSchau** [comment]
@KirankumarAmbati for the merge conflicts, in the future I'd recommend (before working on a feature) to always do:

`git fetch upstream && git reset --hard upstream/master`

(presuming you have an upstream set to gatsbyjs/gatsby, which if you don't is just `git remote add upstream git@github.com:gatsbyjs/gatsby.git`)

But thanks again for the PR!

**Comment by KirankumarAmbati** [comment]
Thank You @DSchau for the suggestion ! I'll keep that in my mind while doing any changes ! :+1:

**Pull request merged**
