### PR TITLE
fix(gatsby): Decode base path in runtime

### LINKED ISSUE #30533: `Loader` does not decode pathPrefix correctly
## Description

Supplying an unencoded pathPrefix, such as `/امتحان` fails validation with an error message: `"pathPrefix" must be a valid relative uri`. 

So one can supply something like ` pathPrefix: "/" + encodeURI("امتحان"),` which solves that problem but then the app is not functional:

Screenshot 2021-03-29 141748

The issue looks to stem from these lines of code: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/find-path.js#L9-L11

The matching decodes the pathname uri, but because the path_prefix is not decoded it will fail to match.

### Steps to reproduce

1. Clone `https://github.com/herecydev/encoding-path-prefix-bug`
2. Run `yarn build`
3. Run `yarn serve`
4. Navigate to `http://localhost:9000/%D8%A7%D9%85%D8%AA%D8%AD%D8%A7%D9%86/`

### Expected result

Either the config should allow an unencoded pathPrefix or `loader` can correctly encode/decode when it needs to

### Actual result

Gatsby loader fails to decode the pathPrefix

### Environment

```
  System:
    OS: Windows 10 10.0.19043
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor            
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.63)
  npmPackages:
    gatsby: ^3.1.2 => 3.1.2 
    gatsby-plugin-gatsby-cloud: ^2.1.0 => 2.1.0 
    gatsby-plugin-image: ^1.1.2 => 1.1.2 
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0 
    gatsby-plugin-offline: ^4.1.0 => 4.1.0 
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0 
    gatsby-plugin-sharp: ^3.1.2 => 3.1.2 
    gatsby-source-filesystem: ^3.1.0 => 3.1.0 
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0 
```

### PR DESCRIPTION
**Pull request by herecydev**
## Description

Decodes the base_prefix as this could also be encoded.

## Related Issues

Fixes #30533

### CODE REVIEW

**Comment by herecydev** [comment]
I'm pretty sure the test failures aren't a cause of the changes (other PRs seem to be failing with the same results)

**Comment by vladar** [comment]
I suspect it could be a breaking change. Can you add another test case for prefix `/test/blog`?

**Comment by herecydev** [comment]
> 
> 
> I suspect it could be a breaking change. Can you add another test case for prefix `/test/blog`?

Of course, I'll get on that ASAP

**Comment by herecydev** [comment]
Screenshot 2021-04-12 151640

@vladar was that what you had in mind? They're all passing fine

**Review by vladar — APPROVED** [review]
Actually, I've looked into it a bit more and this seems to be a safe change. Thanks 👍

**Pull request merged**
