### PR TITLE
Styleguide example

### PR DESCRIPTION
**Pull request by scottyeck**
An example demonstrating how to build a living styleguide using Gatsby as inspired by [react-styleguidist](react-styleguidist.js.org).

- Uses `gatsby-transformer-react-docgen` to parse over inline docs and feed them to components.
- Uses `gatsby-transfomer-remark` to parse over included component `README.md` files.
- Uses `react-to-html` to parse markdown to react-components
- Uses `react-live` to render hot-rendering component demos

### CODE REVIEW

**Comment by jquense** [comment]
SWEEEEEEEET 👏  👏  🙌

**Comment by KyleAMathews** [comment]
Fun stuff!

Only question is why do you redirect from `/` to `/components/`?

**Comment by KyleAMathews** [comment]
Oh also is it possible to query the possible button prop values? Was playing with changing e.g. the backgroundColor and took me a bit to discover that most values weren't supported.

**Comment by scottyeck** [comment]
Re: `/components`, no reason at all. I should probably just eliminate that route and have all the components be their own individual routes, a la `/button/`, etc.

Re: the button values, I've been looking into that. I think it's an issue with `react-docgen`'s ability to inspect the return value of the `Object.keys` call passed to the type-checker. I have a few ideas, but none of them feel quite right. I'll spec them out here for discussion at some point.

**Comment by KyleAMathews** [comment]
@scottyeck happy new year! Had any chance to look into things more?

**Comment by scottyeck** [comment]
@KyleAMathews You too! Sorry - been in the weeds with some other work and haven't gotten around to fleshing this out. Definitely plan to!

**Comment by KyleAMathews** [comment]
Cool, no worries :-) someone was asking about styleguides with Gatsby on twitter so thought of this PR

**Comment by scottyeck** [comment]
No of course - I appreciate the checkin.

FWIW, there's an issue with `react-live` that is going to prevent the _build-html_ phase from completing successfully here at the moment anyhow. I've [submitted a PR](https://github.com/FormidableLabs/react-live/pull/50) but for now we're [using a fork](https://github.com/fabrictech/react-live) until it gets merged. I suppose we could do that here too, though I'm not a huge fan tbh.

**Comment by ar-stackrox** [comment]
I'm super interested in this! Is there a live demo of a styleguide to click around somewhere by any chance?

**Comment by selbekk** [comment]
Amazing work! We'll look into the work done here to create our own styleguide. We're currently using react-styleguidist, but that doesn't work well when you need some static pages in addition to a component library.

Let me know if there's anything I can do to help out!

**Comment by KyleAMathews** [comment]
I'll just merge this — feel free @scottyeck and others to submit PRs adding any improvements you'd like!

**Comment by ar-stackrox** [comment]
@KyleAMathews 

Sorry, I'm new to Gatsby - How would I try this out? Is it available as a Gatsby plugin, or is there an example repo I can pull and run locally to generate the styleguide?

**Comment by LeKoArts** [comment]
@ar-stackrox Download the Gatsby repo and only keep this folder:
https://github.com/gatsbyjs/gatsby/tree/master/examples/styleguide

Then run `npm install` and you can use it.

**Comment by ar-stackrox** [comment]
Ohh thank you @LeKoArts !

**Comment by ar-stackrox** [comment]
One last question @LeKoArts - do you know if this can be combined with something like this? Not sure if needed, but some functions seem useful - https://www.gatsbyjs.org/packages/gatsby-remark-design-system/?=desigh

**Comment by LeKoArts** [comment]
@ar-stackrox Yeah, sure, just follow the instructions (I wrote the plugin + instructions, so if something is unclear or you got problems please open a issue on the repo).

**Pull request merged**
