### PR TITLE
Added article for 'Building i18n with Gatsby'

### PR DESCRIPTION
**Pull request by sgoudie**
Including edits from draft round. Added front-matter too.

### CODE REVIEW

**Comment by angeloocana** [comment]
Hello @sgoudie !
Congratulations for the Article, It is very good!

I'm happy to see other solutions for i18n =D

I liked i18n-next, I don't like so much the **<FormattedMessage** from **react-intl**


One question, How are you doing about google search for?

All the best!

**Comment by sgoudie** [comment]
Hey @angeloocana. In the article there's a little snippet that shows you can use i18n in Helmet!

**Comment by angeloocana** [comment]
I saw the Helmet.
I'm saying about the languages.
How can google index the English and Cymraeg versions?

I'm changing the language in the URL, example:
/en/about/  = About for English 
/cy/about/  = About for Cymraeg

In this way google can crawl the 2 versions.

I still have to work on the sitemap to add the **hreflang** prop, in order to google to be 100% ok.

------------------------------------------------

Sorry for the docs for **gatsby-plugin-i18n** I'm still working on it, and any help would be awesome!

You can use **gatsby-plugin-i18n** with your solution, using **i18next** and everything else.

**gatsby-plugin-i18n** just takes files extensions and create a i18n url, like:
test.en.js => /en/test/
test.cy.js => /cy/test/

**Comment by monsieurnebo** [comment]
Amazing! I was looking for i18next on a Gatsby project.

**Comment by KyleAMathews** [comment]
@sgoudie that is a good question — does Google care that you use the same URLs for different languages? Not an i18n expert obviously :-)

**Comment by KyleAMathews** [comment]
Merging! Thanks for the great writeup of your project!

**Comment by sgoudie** [comment]
Thanks guys!

@angeloocana I'm not sure, we haven't had to look at that ourselves. If I find anything I'll let you know!

**Comment by monsieurnebo** [comment]
@sgoudie How do you handle multiple layouts? In your article, you are creating the `i18n` instance from the index layout, but we can't pass it to another layout via `props` (and we can't use the `I18nextProvider` neither, because of the lack of a root component as `<App />`).

**Comment by sgoudie** [comment]
You can import the i18n component anywhere. You could import it into multiple layout components too.
The props get passed by the translate HOC.

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.8.83&pv=11.0.1&source=email_footer_2]
On Tue, Oct 24, 2017 at 11:42, Cyril BONNET <notifications@github.com> wrote:
@sgoudie [https://github.com/sgoudie] How do you handle multiple layouts? In your article, you are creating the i18n instance from the index layout, but we can't pass it to another layout via props (and we can't use the I18nextProvider neither, because of the lack of a root component as <App /> ).

**Comment by monsieurnebo** [comment]
@sgoudie Did you encounter the following error during your tests?

```js
ReferenceError: XMLHttpRequest is not defined
    at Object.ajax (render-page.js:39317:6)
    at Backend.loadUrl (render-page.js:39188:21)
    at Backend.read (render-page.js:39181:13)
    at Connector.read (render-page.js:38785:33)
    at Connector.loadOne (render-page.js:38895:11)
    at render-page.js:38841:17
    at Array.forEach (<anonymous>)
    at Connector.load (render-page.js:38840:22)
    at render-page.js:37093:43
    at Connector.load (render-page.js:38972:42)
```

It seems related to the `locales` loading by the `Backend`, but I have no clue...

```js
// createI18n.js
import i18n from "i18next";
import Backend from "i18next-xhr-backend";
import { reactI18nextModule } from "react-i18next";
import config from "config";

const NAMESPACES = [
  "app"
];

export default function createI18n() {
  const options = {
    fallbackLng   : "en",
    whitelist     : ["en", "fr"],
    ns            : NAMESPACES,
    debug         : true,
    interpolation : {
      escapeValue : false
    },
    react         : {
      wait : true
    },
    backend       : {
      loadPath : `${config.pathPrefix}locales/{{lng}}/{{ns}}.json`
    }
  };

  return i18n
    .use(Backend)
    .use(reactI18nextModule)
    .init(options);
}
```

It's working on the local dev server, but not with the build.

**Comment by monsieurnebo** [comment]
@sgoudie By any chance, did you try to support an URL prefix for the wanted lang?

## Example:
`http://gatsby.com/en/contact/` would display the `contact` page while switching `i18next` to  `fr`.

We could create two directories at the `pages` root, duplicating each page with the right language:

```
|- pages
  |- fr
    |- contact.jsx
  |- en
    |- contact.jsx
```

But I don't really like the duplication thing.

**Pull request merged**
