### PR TITLE
Updated Static Folder docs

### PR DESCRIPTION
**Pull request by 416serg**
Moved the `Adding Assets Outside of the Module System` and `When to Use the static Folder` from `docs/docs/adding-images-fonts-files.md` to `docs/docs/static-folder.md`

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 1f000ee7a44e7e1fb7edb715c61a0bf8a023fb86

https://app.netlify.com/sites/using-postcss-sass/deploys/5b671f793813f02e87db06e7

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 1f000ee7a44e7e1fb7edb715c61a0bf8a023fb86

https://app.netlify.com/sites/gatsbyjs/deploys/5b671f783813f02e87db06db

**Comment by 416serg** [comment]
@KyleAMathews following the errors from Netlify

```
12:21:48 PM: Failed to screenshot https://chiedo.tv/. Retrying...
12:22:18 PM: Failed to screenshot https://chiedo.tv/. Retrying...
12:22:48 PM: Failed to screenshot https://chiedo.tv/. Retrying...
12:23:18 PM: Failed to screenshot https://chiedo.tv/. Retrying...
12:23:48 PM: Failed to screenshot https://chiedo.tv/. Retrying...
12:23:49 PM: Failed to screenshot https://chiedo.tv/. Retrying...
12:24:19 PM: Failed to screenshot https://chiedo.tv/. Retrying...
12:24:21 PM: Failed to screenshot https://chiedo.tv/. Retrying...
12:24:51 PM: Failed to screenshot https://chiedo.tv/. Retrying...
12:25:21 PM: Failed to screenshot https://chiedo.tv/. Retrying...
12:25:21 PM: error Plugin gatsby-transformer-screenshot returned an error
12:25:21 PM: 
12:25:21 PM:   Error: Request failed with status code 504
```

https://chiedo.tv/ is not loading for me when trying to access it directly, is that what's causing the tests to fail?

**Comment by KyleAMathews** [comment]
Deploy preview for *using-remark* failed.

Built with commit e71e0a72cf22cb391166dc6c61b20e5b71eae22d

https://app.netlify.com/sites/using-remark/deploys/5b6818aa792f8925529ddd3f

**Comment by m-allanson** [comment]
Thanks @416serg 👍 The chiedo.tv errors should be fixed now.

I think the `static-folder` article should be a new article rather than taking the second half of `adding-images-fonts-and-files`, as it relies on a things talked about in the first half of the article.

Ideally the article would be structured something like this:

>- What is the static folder?
>- Why should you use the static folder?
>- Why _shouldn't_ you use the static folder (list alternatives)?
>- How do you use the static folder (with examples)?
>
>And then the `adding-images-fonts-and-files` article could be shortened to include only a few lines about the static folder and a link to the `static-folder` article.

Doing that would be a fair bit of work though - would love if you wanted to take it on?! but understandable if not 😅

Maybe a good next step would be to revert your changes, and then add the above outline to the stub article?

**Pull request closed without merging**
