### PR TITLE
Fixed typo brackets in file-system-route-api.md

### PR DESCRIPTION
**Pull request by runningdeveloper**
## Description

Docs fix a typo for file-system-route-api.md.
There was extra curly brackets and a missing backtick in 2 the examples. Noticed when I copy pasted an example.

### CODE REVIEW

**Review by pvdz — APPROVED** [review]
lgtm. thank you :purple_heart:

**Comment by pvdz** [comment]
(Running formatter to attemt and fix lint error)

**Comment by pvdz** [comment]
Ok the problem is that Prettier did not run before because of the syntax error you're fixing. Now that the syntax error is fixed, a few lines above it are reformatted.

I can't push to your branch, neither can the bot, so please run the formatter (`yarn format`) and commit the changes so we can merge this. I can also do this for you but that means creating a new PR and I don't want to steal your thunder :)

**Review by pvdz — CHANGES_REQUESTED** [review]
Please run `yarn format` and commit changes.

**Comment by runningdeveloper** [comment]
Thanks @pvdz I'll do it shortly. Thanks for the guidance, I'll remember this next time.

**Review by pvdz — APPROVED** [review]
Thanks! :purple_heart:

**Pull request merged**
