### PR TITLE
consolidate CLI logic and depend on it in gatsby

### PR DESCRIPTION
**Pull request by jquense**
I think this is done, its a bit hard to test. wouldn’t say no to some more eyes on it :)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit dc991d04de7faed89ef2385710778e0bb25d16f8

https://app.netlify.com/sites/using-glamor/deploys/599c97f30752d03e0da58547

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 4522e62a4dde07eb02a9a9e7aecc5ee0ecdf0a58

https://app.netlify.com/sites/using-glamor/deploys/599c98407960b107e455a27a

**Comment by KyleAMathews** [comment]
On quick read through looks great! Love your refactors :-)

I'll test the PR manually in the morning to make sure nothing is broken.

Also looks like the yarn.lock got deleted.

**Comment by jquense** [comment]
oops on the yarn lock let me fix that

**Comment by KyleAMathews** [comment]
Oooo and you fixed up `gatsby new`! Yeah that was super ugly looking. And very much like just letting the underlying tools log out normally so easier for people to debug problems.

**Comment by KyleAMathews** [comment]
Only thing I saw missing was `gatsby` needed `gatsby-cli` as a dependency so added that. Other than than, things look great! Hopefully :-) big refactors like this are a bit hard to understand their implications so I guess let's be on our toes to fix any bugs that crop up.

**Pull request merged**
