### PR TITLE
Update update-notifier package

### PR DESCRIPTION
**Pull request by herecydev**
Assists to resolve: #26128

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
@herecydev Can you push a lock file resolution? (Should be able to merge master and run `yarn`)

**Comment by herecydev** [comment]
All resolved Sidhartha

**Comment by herecydev** [comment]
Anything stopping this progressing @sidharthachatterjee ?

**Comment by sidharthachatterjee** [comment]
@herecydev Nope, just the weekend and I was on holiday yesterday! 😅  Thanks a tonne again!

**Comment by herecydev** [comment]
You're most welcome!

**Pull request merged**
