### PR TITLE
Add our tech blog to sites.yml

### PR DESCRIPTION
**Pull request by Destroy666x**
As the title says.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@Destroy666x can you fix the git conflict?

**Comment by pieh** [comment]
@Destroy666x this site is heavily based on https://github.com/greglobinski/gatsby-starter-personal-blog - it's ok to use it of course as starter is open sourced, but site showcase entries should be original work - after all, You are claiming that https://www.boldare.com/ built site, which is not fully correct here (as big part of look and feel of the site was built by @greglobinski)

**Comment by DSchau** [comment]
@Destroy666x I'm going to close this out for the reasons that @pieh specified.

We appreciate you using Gatsby, but we want to make sure that the original creators get the credit they deserve, and adding non-original showcase sites just blurs that line.

Please feel free to re-open or discuss further if you feel differently though. Thank you!

**Comment by Destroy666x** [comment]
@DSchau @pieh your choice, but your reasoning doesn't make much sense to me. Nothing is really "original" here because everything's based on Gatsby, yet people don't claim Gatsby built the site either because that's simply invalid. And proper credits for the heavily modified base are given where the creator left them - in the footer.

All you did here was discourage people from using starters to make things happen faster because then they won't be able to share their site no matter what the idea is.

**Pull request closed without merging**
