### PR TITLE
Use awesome-typescript-loader instead of ts-loader for typescript plugin

### PR DESCRIPTION
**Pull request by auser**

### CODE REVIEW

**Comment by jquense** [comment]
Hi there, can you talk about what this change is for and what it accomplishes over using the official loader?

**Comment by auser** [comment]
@jquense Certainly. 

The `awesome-typescript-loader` is much faster than the `ts-loader` and can be configured with `tsconfig.json`, whereas the `ts-loader` isn't. 

Specifically, their [README](https://github.com/s-panferov/awesome-typescript-loader) does a great job of highlighting the differences.

> atl has first-class integration with Babel and enables caching possibilities. This can be useful for those who use Typescript with Babel. When useBabel and useCache flags are enabled, typescript's emit will be transpiled with Babel and cached. So next time if source file (+environment) has the same checksum we can totally skip typescript's and babel's transpiling. This significantly reduces build time in this scenario.
>
> atl is able to fork type-checker and emitter to a separate process, which also speeds-up some development scenarios (e.g. react with react-hot-loader) So your webpack compilation will end earlier and you can explore compiled version in your browser while your files are typechecked.

**Comment by KyleAMathews** [comment]
One option is to make this a new plugin for awesome-typescript-loader. Pretty cheap to just add new packages.

**Comment by KyleAMathews** [comment]
@auser want to change the PR to just add a new plugin?

**Comment by KyleAMathews** [comment]
@auser feel free to resubmit this PR as a new package. Closing for now.

**Pull request closed without merging**
