### PR TITLE
feat(www): Add gatsby-plugin-theme-ui, dark theme MVP

### PR DESCRIPTION
**Pull request by fk**
Haaaaaacktooooobeeeer!  
🍂⚗️📐🔦🧰🧹🔨🙃

This PR ~(draft)~ puts `www` on `gatsby-plugin-theme-ui` 🔌, adding a "dark mode" 🌙 along the way. It's ~fairly~ functional ~already~ (and builds ;-)), but not without a few rough edges ~—both visible, and~ below the surface.

image

image

image

image

**Basic questions (IMO ;-)) …**

- _Do we even want .org on `theme-ui`?_ 😛
- If so, do we want to ship the initial version with or without dark mode?  
  The current state of the dark theme is usable, but MVP.

**… and a few 🙄 notes on where this is at:**

- [x] add [`gatsby-plugin-theme-ui`](https://www.gatsbyjs.org/docs/theme-ui/#using-theme-ui-in-gatsby) using the [`sx` prop](https://theme-ui.com/sx-prop) along the [custom pragma comment](https://theme-ui.com/jsx-pragma)
  - [x] ditch `utils/presets` in favor of `src/gatsby-plugin-theme-ui`, which now is our single (and currently pretty ugly) [shadowed](https://theme-ui.com/gatsby-plugin) source of truth
  - [x] no need for `wrap-root-element` anymore in [`www/gatsby-ssr.js`](https://github.com/gatsbyjs/gatsby/pull/18027/files#diff-fcd07cc82c362910f0734270336e9b30)—`src/gatsby-plugin-theme-ui/components` instead
  - [x] refactor a lot of CSS to use `sx`, so most token imports (from the removed `utils/presets`) are gone
    - still importing a couple tokens here and there, now from `src/gatsby-plugin-theme-ui`—(mostly) `mediaQueries`
    - didn't opt in to the `theme-ui` responsive styles array for now; not against it, just a bit scared ;-)
- [x] move global styles out of `utils/typography` to `utils/styles/global` and break those into chunks (Prism tokens, code block styles and language badges)—I'm not attached to the new location though; both things simply helped refactoring
- [x] add a first shot at a dark theme
  - [x] adjust styles and assets for dark mode
    - [x] layer model component
    - [x] algolia docsearch dropdown
    - [x] `homepage-logo-banner` logo colors
    - [x] feedback widget
    - [x] homepage section
    - [x] newsletter components
      - [x] default
      - [x] homepage
    - [x] Showcase and Starters
      - [x] modal
      - [x] share menu (along the way/easier: ditch the share menu "themes" (orange for starter, purple for showcase items))
    - [x] `/features`
    - [x] mobile navigation icons — realigned all icons currently in use: 6950d67 . 
       image .  
       image
    - [x] sidebars
      - [x] docs
      - [x] showcase (sites/starters)
      - [x] plugin search
  - [x] add _that dark mode switch_ to the main navigation—[kudos to our friends at narative.co](https://github.com/narative/gatsby-theme-novela/blob/fb38329e17595df6e846be1d33517ff6125cde4e/src/components/Navigation/Navigation.Header.tsx) and to and [Aaron Iker](https://codepen.io/aaroniker/pen/KGpXZo)
  - [x] ~find out why using `theme-ui`'s `useCustomProperties` errors~ _edit: updating `theme-ui` helped_
  - [x] fix `/guidelines/*.*` pages
    - [x] remove `utils/guidelines/theme` 
    - [x] remove `utils/guidelines/theme-inverted` (used in `/guidelines/typography`)—one dark mode is enough ;-)
  - [x] remove `emotion-theming`
- extend tokens from `gatsby-design-tokens` to
  - provide default [`colors` required by `theme-ui`](https://theme-ui.com/theme-spec#color):
    - [x] text
      - [x] fix conflict with `gatsby-design-tokens`' `colors.text` object
    - [x] background
    - [x] primary
    - [x] secondary
    - [x] accent
    - [x] muted
  - [x] fulfill [theme-ui's typography conventions](https://theme-ui.com/theme-spec/#typography):
    - [x] fontWeights
    - [x] fonts
      - [x] fonts.heading
      - [x] fonts.body
    - [x] lineHeights
      - [x] lineHeights.body
      - [x] lineHeights.heading
- refactor `colors.ui`
  - [x] rename `colors.ui.border.subtle` -> `colors.ui.border`
- _along the way…_
  - [x] consolidate various "screen-reader-only" CSS styles (`clip: rect(0, 0, 0, 0)`) in `utils/styles` — rule of three easy ;-)
  - [x] consolidate 3️⃣ skip-nav-links + styles in component
  - [x] tidy `avatar` component, use it in `template-contributor-page`
  - [x] increase main navigation "social links" icon sizes, make them calmer
  - [x] fiddle around with main navigation search form UI (WIP)—keep it expanded where possible for larger screens, and always expand it for mobile
  - [x] make the blog post headers a little more interesting
  - [x] increase whitespace below breadcrumbs path
  - [x] remove a bunch of `WebkitFontSmoothing: antialiased`—we switched to using it on `html` some time ago
  - a11y improvements:
    - [x] adjust token colors for (Prism) syntax highlighting to comply to WCAG 2.0 AA standard contrast ratios (tried to test quite a bit using random code from the docs, but didn't go the whole mile and set up proper examples to test)
    - [x] fix "Edit this page on GitHub" link color contrast

image

**Now and / _or_ later…**

- port theme changes and additions to `gatsby-design-tokens`, and give the new tokens (and their names) a good second look, consolidate
- if possible, switch our custom syntax highlighting implementation to the "theme-ui way" (cc @DSchau)
- improve showcase/starter sidebar and item/card styles—dark mode shows a lot of its issues
- maybe try to use Typography.js' styles only for the "main content"

## Related Issues

#8789 — Documentation Dark Theme

### CODE REVIEW

**Comment by t2ca** [comment]
Wow!

**Comment by fk** [comment]
Preview (with a subset of "Showcase" sites): https://5d9b0aeb7cf4dd9d42c83261--relaxed-saha-83a4fd.netlify.com/

**Comment by johnletey** [comment]
> Preview (with a subset of "Showcase" sites): https://5d9b0aeb7cf4dd9d42c83261--relaxed-saha-83a4fd.netlify.com/

@fk If I may, I've noticed on the deployed site that the moon/sun icon isn't aligned with the other icons in the header

| Light | Dark |
| :----: | :---: |
| Shot 2019-10-07 at 14 28 58 | Shot 2019-10-07 at 14 28 52 |

I think it has something to do with varying sizes of the icons.

**Comment by fk** [comment]
@johnletey Sure you may! Thank you for taking the time! 🤗 

>  the moon/sun icon isn't aligned with the other icons in the header

Thanks for calling that out, the switch button needs a little nudge indeed! 🙏 
Will take care of that later today!

**Comment by fk** [comment]
🚨Almost mandatory YT link: https://www.youtube.com/watch?v=tm6x0q2INSs

**Pull request merged**
