### PR TITLE
Changed to !

### PR DESCRIPTION
**Pull request by tyj144**

### CODE REVIEW

**Comment by jlengstorf** [comment]
Hey, @tyj144! Thanks so much for opening a pull request!

The change you’ve proposed is not going to be accepted becase the docs aren’t improved by this change (e.g. it doesn’t fix an error or clarify a point).

Additionally, a stylistic change to the stubs would require changing _all_ the stubs. (Which, in this case, is too much effort for the change that’s being made.)

We absolutely want to have you as a contributor, so please take a look at our [open issues](https://git.io/gatsby-gfi) for ideas, and please reach out to us on Twitter at @gatsbyjs with questions.

We offer [pair programming sessions](https://gatsby.app/pairing) if you’d like to work with one of our maintainers to make your first contribution.

Thanks again, @tyj144, and we look forward to seeing more PRs from you in the future! :muscle::purple_heart:

**Comment by shannonbux** [comment]
Hi @jlengstorf!

My bad! I was helping @tyf144 learn how to make a contribution so we just
did a fake one and I meant to close it!

Thanks for your patience @tyf144!

**Comment by tyj144** [comment]
It's all good. Plus it's cool to see that you guys give such detailed responses to these kinds of things.

**Comment by shannonbux** [comment]
@jlengstorf is really great at that! He is an awesome person whenever you have contribution questions @tyj144 👍

**Pull request closed without merging**
