### PR TITLE
Unbreak `gatsby develop`

### PR DESCRIPTION
**Pull request by LegNeato**
Fixes https://github.com/gatsbyjs/gatsby/issues/6421

### CODE REVIEW

**Comment by t2ca** [comment]
gatsby 2.0.0-beta.32

info bootstrap finished - 4.276 s

error The "id" argument must be of type string. Received type object
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object

problem fixed when going back to beta.29

**Comment by KyleAMathews** [comment]
@t2ca is your site with this error open source?

**Comment by KyleAMathews** [comment]
Know where the error is but not sure how to reproduce it.

**Comment by t2ca** [comment]
If this helps

error UNHANDLED REJECTION


  Error: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
  
  - loader.js:631 Module.require
    internal/modules/cjs/loader.js:631:11
  
  - helpers.js:20 require
    internal/modules/cjs/helpers.js:20:18
  
  - worker.js:26 Promise
    [poutsopretty]/[gatsby]/dist/utils/worker.js:26:35
  
  - new Promise
  
  - worker.js:25 Object.renderHTML
    [poutsopretty]/[gatsby]/dist/utils/worker.js:25:10
  
  - child.js:90 execMethod
    [poutsopretty]/[jest-worker]/build/child.js:90:29
  
  - child.js:40 process.on
    [poutsopretty]/[jest-worker]/build/child.js:40:7
  
  - child_process.js:811 emit
    internal/child_process.js:811:12
  
  - next_tick.js:63 process._tickCallback
    internal/process/next_tick.js:63:19

**Comment by KyleAMathews** [comment]
I know where the error is coming from. I just need a way to reproduce it. Can you link to your site's source code?

**Comment by t2ca** [comment]
https://github.com/poutsopretty

**Comment by KyleAMathews** [comment]
Oh hmmm that site requires your Contentful credentials to work unfortunately.

**Comment by charlesvdv** [comment]
@KyleAMathews  I have the same problem with my website and the code can be found at https://github.com/charlesvdv/charlesvdv.github.io

**Comment by mchernin34** [comment]
The issue can be reproduced by just running the following: 

`$ gatsby new my-default-project https://github.com/gatsbyjs/gatsby-starter-default#v2`

and then `$ gatsby develop`

I was going through the V2 tutorials and encountered it today.

**Comment by chibicode** [comment]
I can confirm @mchernin34's repro.

> $ gatsby new my-default-project https://github.com/gatsbyjs/gatsby-starter-default#v2
> 
> and then $ gatsby develop

**Comment by danilobuerger** [comment]
2.0.0-beta.29 works, 2.0.0-beta.32 does not.

**Comment by KyleAMathews** [comment]
@m-allanson's PR https://github.com/gatsbyjs/gatsby/pull/6428 fixed the remainder of the problems. Just tested beta.33 and it works. Sorry for the blockage/frustration everyone!

**Comment by t2ca** [comment]
@KyleAMathews 

Just upgraded to beta.35

Getting this error on gatsby develop

info bootstrap finished - 7.494 s

error UNHANDLED REJECTION

  TypeError: Cannot read property 'setStatus' of undefined
  
  - html-renderer-queue.js:38 
    [poutsopretty]/[gatsby]/dist/utils/html-renderer-queue.js:38:14
  
  - Generator.next
  
  - next_tick.js:61 process._tickCallback
    internal/process/next_tick.js:61:11

beta.34 works fine.

**Comment by KyleAMathews** [comment]
@t2ca oops 🤦‍♂️ gotta test develop

Fix up at https://github.com/gatsbyjs/gatsby/pull/6449

Will publish soon.

**Comment by t2ca** [comment]
Thanks @KyleAMathews, and thank you for creating Gatsby! It's so much fun using it while learning react, javascript, and graphql.

**Comment by jlengstorf** [comment]
Hiya @LegNeato! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
