### PR TITLE
feat(gatsby-cli): add alias with-prefix to prefix-paths

### PR DESCRIPTION
**Pull request by frinyvonnick**
## Description

Add an command `with-prefix` that alias `prefix-paths`

## Related Issues

#13549

### CODE REVIEW

**Comment by wardpeet** [comment]
See https://github.com/gatsbyjs/gatsby/issues/13549#issuecomment-485804375

**Comment by frinyvonnick** [comment]
Thanks for you review @sidharthachatterjee @wardpeet, I'll wait until the discussion has been resolved 👍 !

**Comment by frinyvonnick** [comment]
I close this since the issue has been too ?

**Comment by KyleAMathews** [comment]
Yeah let's close it. It's an excellent suggestion for a flag name and I wish you'd been around when it got named it a few years ago as that might have won out — but the current name is fine enough and adding aliases causes more confusion than would help.

Perhaps creating a custom npm script would work better for you?

**Pull request closed without merging**
