### PR TITLE
Update to babel 7 beta 52

### PR DESCRIPTION
**Pull request by beardedpayton**
Fixes issue #6371

### CODE REVIEW

**Comment by jquense** [comment]
are there any noteable differences we should be on the lookout for?

**Comment by chuntley** [comment]
@jquense, one notable thing is:

> Deprecating the yearly/stage presets in v7 (will remove next beta). Ran npm deprecate on @babel/preset-es2015, @babel/preset-es2016, @babel/preset-es2017, @babel/preset-stage-0, @babel/preset-stage-1, @babel/preset-stage-2, @babel/preset-stage-3 only for versions >v7.0.0-beta.52

But looking through Gatsby dependencies it does not seem like any of these are used, so you should be good moving forward with the next babel beta when it comes out.

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 1faa27c7c73de3a98d6e0f6089fe1db90aff3881

https://app.netlify.com/sites/using-postcss-sass/deploys/5b4f49384ed62f6b8dfb88fd

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 1faa27c7c73de3a98d6e0f6089fe1db90aff3881

https://app.netlify.com/sites/gatsbyjs/deploys/5b4f49374ed62f6b8dfb88f5

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit eeb5931543736c162dcbc683f71f755f0c7e09a5

https://app.netlify.com/sites/gatsbyjs/deploys/5b4f4c5ec6aed654dfb90ec5

**Comment by m-allanson** [comment]
Hmm this will need a bit more investigation. With this PR checked out, running `yarn` then `yarn run bootstrap` will result in the following error:

```
yarn run bootstrap
yarn run v1.7.0
$ yarn
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ npm-run-all -s check-versions lerna-prepare
$ babel-node scripts/check-versions.js
/Users/mike/dev/gatsby-v2/node_modules/@babel/core/lib/config/full.js:127
    throw e;
    ^

Error: [BABEL] /Users/mike/dev/gatsby-v2/scripts/check-versions.js: You gave us a visitor for the node type ClassPrivateProperty but it's not a valid type
    at verify (/Users/mike/dev/gatsby-v2/node_modules/@babel/traverse/lib/visitors.js:130:13)
    at explode (/Users/mike/dev/gatsby-v2/node_modules/@babel/traverse/lib/visitors.js:52:3)
    at Object.merge (/Users/mike/dev/gatsby-v2/node_modules/@babel/traverse/lib/visitors.js:165:5)
    at Object.<anonymous> (/Users/mike/dev/gatsby-v2/node_modules/@babel/helper-replace-supers/lib/index.js:90:46)
    at Module._compile (module.js:652:30)
    at Module._compile (/Users/mike/dev/gatsby-v2/node_modules/pirates/lib/index.js:91:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/Users/mike/dev/gatsby-v2/node_modules/pirates/lib/index.js:96:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "check-versions" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I can investigate this in the next couple of days.

**Comment by m-allanson** [comment]
Hmm I tried this again and it seemed fine. I'm going to merge and release this.

**Pull request merged**
