### PR TITLE
PrefixLink fixes

### PR DESCRIPTION
**Pull request by jakubrohleder**
When `url-loader` is used with `limit` option some of images are encoded to base64 data url, this fix prevent such links from being prefixed.

It also makes link prefixing safer by using `path.join` instead of string concatenation.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Oh interesting! Wouldn't have thought of this problem. Thanks for the PR!

Two request — could you break up the code into individual if statements and document each. I don't think  it'd occur to many people reading the code why a link would be a data url. Second, how big is the path module? As this function gets loaded into every Gatsby site, we should keep this as small as possible so if there's a more focused "path join" module then we should use that.

**Comment by KyleAMathews** [comment]
I ended up not using path.join as it added 2kb extra code after minification. I'd rather we just add more invariants as needed to teach people how to form their path prefix as that's more effective plus doesn't add any needless code weight.

**Comment by jakubrohleder** [comment]
@KyleAMathews Thanks for finishing my PRs. I had really busy time recently :)

**Comment by KyleAMathews** [comment]
No worries :-) thanks for starting it!

**Pull request merged**
