### PR TITLE
fix(gatsby-theme-notes): Fix path in config

### PR DESCRIPTION
**Pull request by sonapraneeth-a**
Updating path in gatsby-config for notes based on theme options.

Updating path in gatsby-source-filesystem plugin which was throwing error 

The path passed to gatsby-source-filesystem does not exist on your file system:

content/notes

### CODE REVIEW

**Comment by sonapraneeth-a** [comment]
Fixes [Issue #15792 ](https://github.com/gatsbyjs/gatsby/issues/15792)

**Comment by sonapraneeth-a** [comment]
Any reason as to why the CircleCI is failing, @johno ?

**Comment by lannonbr** [comment]
@sonapraneeth-a it's failing due to your branch being a little outdated. it is tripping the check-repo-filelds script. I would say try merging in master to get the updates in your branch and then you should be good to go

**Comment by sonapraneeth-a** [comment]
The PR got automatically closed while updating patch-1 to master which is a mistake

**Comment by sonapraneeth-a** [comment]
Hi @lannonbr , @johno ,

Finally all tests are passing. I think this PR can be merged.

**Pull request merged**
