### PR TITLE
Add minimize option to css-loader

### PR DESCRIPTION
**Pull request by wpioneer**
Fixes for https://github.com/gatsbyjs/gatsby/issues/318

### CODE REVIEW

**Comment by MoOx** [comment]
This is the same thing: css-loader use cssnano under the hood ;)

**Comment by wpioneer** [comment]
@MoOx I agree, but for some reason, there were problems with the Autoprefixer (before you made the change)

**Comment by MoOx** [comment]
No problem. This is good enough ;)

**Comment by KyleAMathews** [comment]
LGTM. I'll merge it for the next release. Anyone else with thoughts?

**Comment by benstepp** [comment]
Do we still need `cssnano` in package.json with this change?

**Comment by wpioneer** [comment]
@benstepp Exactly! `cssnano` no longer need in package.json

**Comment by KyleAMathews** [comment]
Published v0.11.4 with this PR, thanks!

**Pull request merged**
