### PR TITLE
Fixed table syntax error.

### PR DESCRIPTION
**Pull request by joseph-cloudthing**

### CODE REVIEW

**Comment by pieh** [comment]
Cherry-picked to v1

**Comment by jlengstorf** [comment]
Hiya @joseph-cloudthing! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by jlengstorf** [comment]
Hiya @joseph-cloudthing! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by joseph-cloudthing** [comment]
Wow that’s awesome, thank you very much for this!

Unfortunately I hit a roadblock on the discount code:
[cid:image001.png@01D4C76B.CE5D34F0]

FWIW I will be deleting my joseph-cloudthing account – I’m leaving my current employer this week and will be swapping back to my personal account, “PriceChild<https://github.com/pricechild>” so won’t be accepting the organisation invitation.

Kind regards,
Joseph Price

Joseph Price  .  <cloudThing>  Senior DevOps Engineer  .  +44 (0) 121 393 4700

**Comment by jlengstorf** [comment]
Hi @joseph-cloudthing!

For the discount to work, you have to use exactly the same email associated with this GitHub account. If you'd prefer not to do that, send us a message at team@gatsbyjs.com and we'll manually switch it out. We can invite your personal account to the org in place of this one as well — just say the word. 

Thanks!

**Comment by joseph-cloudthing** [comment]
@jlengstorf Brill, thanks that worked!

wrt inviting to the org, thank you but I'm not quite sure I've earnt that too. Hopefully you'll see me around on my main login!

**Pull request merged**
