### PR TITLE
feat(gatsby): enable page-creator on all themes

### PR DESCRIPTION
**Pull request by ChristopherBiscardi**
## Description

this enables the page-creator plugin on all themes (and by extension, all plugins), allowing themes to ship pages in `src/pages`. The order of page-creators matches the order of theme application. No one should be using `src/pages` for anything today unless it's an additional page-creator instance, so this should be non-breaking as a change.

I thought we did this already but apparently it slipped through the cracks.

## Related Issues

Fixes https://github.com/gatsbyjs/gatsby/issues/15873

### CODE REVIEW

**Comment by ChristopherBiscardi** [comment]
The failing test here is because of (as far as I can tell) a malformatted test plugin spec that doesn't include `resolve`

```
{ id: 'c731052f-1e62-5905-9fb3-edc9057be8f1',
  name: 'TEST',
  pluginOptions: { plugins: [] } }
```

**Comment by ChristopherBiscardi** [comment]
Turns out that in the source code for the relevant function there's special handling for this test input specifically: https://github.com/gatsbyjs/gatsby/blob/71f133b9b8d90d5d029b268f7a548c40e201805f/packages/gatsby/src/bootstrap/load-plugins/load.js#L143-L153 that doesn't return a full spec, which is then hidden by using the `replaceFieldsThatCanVary` function, which inserts a `resolve` field after the fact.

```js
      // Add some default values for tests as we don't actually
      // want to try to load anything during tests.
      if (plugin.resolve === `___TEST___`) {
        const name = `TEST`

        return {
          id: createPluginId(name, plugin),
          name,
          pluginOptions: {
            plugins: [],
          },
        }
      }
```

**Comment by ChristopherBiscardi** [comment]
It is unclear to me what needs to be done to get the tests passing on windows and node v8. The id generation for plugins seems somehow unstable across node versions and platforms.

**Comment by wardpeet** [comment]
How would you disable pages in themes? Like I want to use a theme but it's also serving pages. Should I run `deletePage` for the pages I don't want in gatsby-node?

Maybe this is an edge case but we probably want to add documentation on how to remove them as well? I might be overthinking this :joy:.

**Comment by wardpeet** [comment]
to make tests work, you should try
```
 const replaceFieldsThatCanVary = plugins =>
    plugins.map(plugin => {
      if (plugin.pluginOptions && plugin.pluginOptions.path) {
        plugin.pluginOptions = {
          ...plugin.pluginOptions,
          path: plugin.pluginOptions.path.replace(
            slash(process.cwd()),
            `<PROJECT_ROOT>`
          ),
        }
      }

      return {
        ...plugin,
        resolve: ``,
        version: `1.0.0`,
      }
    })
```

We probably want to rewrite the `jest-serializer-path` to also convert posix paths.

**Comment by ChristopherBiscardi** [comment]
> How would you disable pages in themes? 

yeah, `deletePage` would be it. Or you can shadow them.

**Comment by sidharthachatterjee** [comment]
Published in `gatsby@2.15.6`

**Comment by ChristopherBiscardi** [comment]
Thanks for getting this over the finish line @sidharthachatterjee!

**Comment by universse** [comment]
Anyone keen to look into this issue #17373. Seems like this PR caused it.

**Pull request merged**
