### PR TITLE
chore(gatsby-image): Clarify IntersectionObserver support in README.md

### PR DESCRIPTION
**Pull request by bjfresh**
The latest Safari releases for Desktop and iOS now include support for IntersectionObserver:
https://caniuse.com/#feat=intersectionobserver

## Description

Documentation edits gatsby-image

### CODE REVIEW

**Comment by lannonbr** [comment]
I'm curious if it is needed to comment for people using older versions of safari given the quick turnaround of people upgrading to new versions of MacOS & iOS. For instance here on [Apple's App Store support site](https://developer.apple.com/support/app-store/), about 88% of people on iOS are running at least iOS 12 now. So if there's less and less people on these older versions of iOS / MacOS, should we need to say this for older versions or just comment that if you are supporting IE that you need polyfills

**Comment by bjfresh** [comment]
I weighed both options, figuring that a March 2019 release was recent enough to warrant the specificity, especially given that there's just 88% support for IntersectionObserver globally. Of course, that'll fade quickly. According to the stats, 3% are still using incompatible versions of Safari. Realistically it's probably enough to simply encourage people to check browser support, and highlight IE as an outlier.

**Comment by wardpeet** [comment]
I agree with @lannonbr  if we can just drop Safari that would be great :)

**Comment by bjfresh** [comment]
OK, done. Safari is out.

**Pull request merged**
