### PR TITLE
style(blog): remove unnecessary closing tags

### PR DESCRIPTION
**Pull request by JohnTitor**
## Description

`<source>` is not needed to close so I removed `</source>`.

cf. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source

### CODE REVIEW

**Comment by marcysutton** [comment]
I think if you're going to remove closing tags, they need to be self-closing: `<source />`

**Comment by JohnTitor** [comment]
@marcysutton Thank you for your advice, I pushed following commit (should I squash commits?)

**Comment by marcysutton** [comment]
> should I squash commits?

@JohnTitor no need, we'll squash on merge!

**Comment by freiksenet** [comment]
Thanks!

**Pull request merged**
