### PR TITLE
[WIP] Starter Showcase v2

### PR DESCRIPTION
**Pull request by sw-yx**
resubmitting with a rebase to `master` instead of `v2`; prior work in https://github.com/gatsbyjs/gatsby/pull/5831

closes https://github.com/gatsbyjs/gatsby/issues/5334

EDIT: preview is here: https://dreamy-shannon-191f15.netlify.com/starter-showcase/

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 7b419846678283490c30f817d20c55a04b58594b

https://app.netlify.com/sites/using-postcss-sass/deploys/5b55801a1f12b702ee807d8f

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 7b419846678283490c30f817d20c55a04b58594b

https://app.netlify.com/sites/gatsbyjs/deploys/5b5580191f12b702ee807d87

**Comment by sw-yx** [comment]
The preview is here https://dreamy-shannon-191f15.netlify.com/starter-showcase/

**Comment by calcsam** [comment]
Great work @sw-yx! Going to merge this in so it's dark-deployed.

**Pull request merged**
