### PR TITLE
feat(gatsby-plugin-sitemap): expose `gzip` option

### PR DESCRIPTION
**Pull request by soudai-s**
## Description

Expose [gzip option for sitemap](https://github.com/ekalinin/sitemap.js/blob/4d76fa496ab6cf0730f19c1f01c7501918ec793b/lib/sitemap-simple.ts#L46) that the plugin depends on.

### CODE REVIEW

**Comment by wardpeet** [comment]
Hi, Thank you for the PR. Any reason why you need this option to be enabled at the build level? Normally gzip is handled by the server so curious what the use case is before exposing it.

**Comment by soudai-s** [comment]
I thought it made sense to expose the options if there was a file size limit.

> Please use gzip to compress your Sitemaps. Remember, your Sitemap must be no larger than 50MB (52,428,800 bytes), whether compressed or not.
> https://www.sitemaps.org/faq.html#faq_compression

**Comment by LekoArts** [comment]
The plugin automatically splits the sitemap into multiple files with enough entries, so there shouldn't be a case ever where a single sitemap item is larger than 50MB.

**Comment by soudai-s** [comment]
> The plugin automatically splits the sitemap into multiple files with enough entries, so there shouldn't be a case ever where a single sitemap item is larger than 50MB.
Yes, it does. Also, the split file gzip compression should be good for the server as it reduces the size of each file and the amount of data transferred.

**Comment by wardpeet** [comment]
Thanks for the PR? we're not going to accept this PR as gzip should be handled by the server it gets hosted on and not by the plugin. Thank you for your contribution! 💪 💙

**Comment by soudai-s** [comment]
Thanks for the review!

**Pull request closed without merging**
