### PR TITLE
chore(starters): add gatsby-sanity-developer-portfolio

### PR DESCRIPTION
**Pull request by jneterer**
Adding Gatsby Sanity Developer Portfolio Starter!

My Github repository is located here: https://github.com/jneterer/gatsby-sanity-developer-portfolio-starter
Demo Site: https://gatsby-sanity-developer-portfolio-starter.jacobneterer.com/

## Description

This project was built using Sanity as a CMS, Typescript, and TailwindCSS and SCSS.

### Documentation

Documentation can be found here: https://github.com/jneterer/gatsby-sanity-developer-portfolio-starter/blob/master/README.md

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! I love math :)

I noticed that the README includes `npm run start` rather than `gatsby develop`. We're aiming for consistency amongst starters so that those new to Gatsby have an easier time getting started! Would you mind updating that?

**Comment by jneterer** [comment]
> Thanks for the PR! I love math :)
> 
> I noticed that the README includes `npm run start` rather than `gatsby develop`. We're aiming for consistency amongst starters so that those new to Gatsby have an easier time getting started! Would you mind updating that?

@laurieontech Hello! Did you mean to comment this on another PR?

**Comment by laurieontech** [comment]
😅I didn't, but I accidentally looked at the old site below yours rather than your new content. Sorry about that!

**Comment by laurieontech** [comment]
Thanks!

**Pull request merged**
