### PR TITLE
Rename deploying-to-zeit-now.md to deploying-to-vercel.md

### PR DESCRIPTION
**Pull request by bcye**
## Description

The title of the docs article was updated, but the changes weren't reflected in it's path, so it's still shown as zeit Now in the sidebar

### Documentation

n/a

## Related Issues

n/a

### CODE REVIEW

**Comment by KyleAMathews** [comment]
This would be great. We'd also need a redirect added to gatsby-node.js so direct traffic gets shifted as well.

**Comment by bcye** [comment]
@KyleAMathews this could be done by adding an `exports.createRedirect` to `www/gatsby-node.js`, right?

**Comment by bcye** [comment]
Also does this need to be changed in the side bar manually or does that work automatically?

**Comment by ascorbic** [comment]
Hey. My apologies, but I merged another PR that already fixed this, though it was created a little after yours. My mistake entirely!

**Comment by bcye** [comment]
No worries!

**Pull request closed without merging**
