### PR TITLE
feat: Use gatsby clean for the build command

### PR DESCRIPTION
**Pull request by endormi**
## Description

Using gatsby clean for the build command on the examples to remove cache rather than doing it manually if needed.

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
This shouldn't be necessary. We only want to delete `.cache` and `public` (via `gatsby clean`) when needed and not after every build.

**Comment by endormi** [comment]
Okay, thanks for clarifying

**Comment by 2x2xplz** [comment]
There are some builds which seem to fail more than half the time without clearing the cache. There are also environments (ahem, Netlify) where developers don't have an entire CLI, just a single command we can execute to build our projects. While I agree that clearing the cache shouldn't be the default, an option like `gatsby build --clean` should be possible which would internally, run `gatsby clean` then `gatsby build`

**Comment by endormi** [comment]
Thoughts @sidharthachatterjee ?

**Comment by m-allanson** [comment]
Hey @2x2xplz!

If there's an issue with builds failing intermittently, let's try and find out the root cause and fix it. If you're able to create a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) that regularly fails to build, please open an issue and link to it.

In the mean time, for environments where you can just run a single command there are workarounds. You could add a command to your `package.json` file that runs a couple of commands together. An example might look like:

```js
// package.json
// ...
"scripts": {
    "clean-build": "gatsby clean && gatsby build"
},
// ..etc
```

There are packages like [npm-run-all](https://github.com/mysticatea/npm-run-all) that provide more control.

I hope that helps!

**Pull request closed without merging**
