### PR TITLE
feat(gatsby-remark-prismjs): don't highlight output lines

### LINKED ISSUE #31794: [gatsby-remark-prismjs] command-line plugin ouput lines retain syntax highlighting
## Description

In the prismjs command line plugin, output lines are not highlighted (cf. https://prismjs.com/plugins/command-line/). This gives consistent coloring for outputs that may happen to be alphanumeric / numeric / capital / lower case / etc.

With the gatsby-remark-prismjs plugin, the line is colored the same whether it is marked as an outputLine or not.

### Steps to reproduce

Follow installation instructions for gatsby-remark-prismjs, use the commandline plugin (also in instructions)

<pre>
```bash{outputLines: 2}
echo "123"
123
```</pre>

observe unexpected (with prismjs) syntax-highlighting in the second line.


### Expected result

These blocks would have their second line rendered the same color

<pre>
```bash{outputLines: 2}
echo "hello"
hello
```</pre>

<pre>
```bash{outputLines: 2}
echo "123"
123
```
</pre>

### Actual result

The  second value is syntax highlighted as an integer

### Environment

```
  Browsers:
    Chrome: 90.0.4430.85
    Firefox: 88.0.1
  npmPackages:
    gatsby: ^3.4.1 => 3.6.1
    gatsby-plugin-gatsby-cloud: ^2.4.1 => 2.6.1
    gatsby-plugin-goatcounter: ^0.4.0 => 0.4.0
    gatsby-plugin-image: ^1.4.0 => 1.6.0
    gatsby-plugin-manifest: ^3.4.0 => 3.6.0
    gatsby-plugin-offline: ^4.4.0 => 4.6.0
    gatsby-plugin-postcss: ^4.6.0 => 4.6.0
    gatsby-plugin-react-helmet: ^4.4.0 => 4.6.0
    gatsby-plugin-sharp: ^3.4.1 => 3.6.0
    gatsby-remark-copy-linked-files: ^4.3.0 => 4.3.0
    gatsby-remark-katex: ^4.0.0 => 4.2.0
    gatsby-remark-prismjs: ^5.3.0 => 5.3.0
    gatsby-remark-remove-comments: ^0.1.0 => 0.1.0
    gatsby-source-filesystem: ^3.4.0 => 3.6.0
    gatsby-transformer-remark: ^3.2.0 => 3.2.0
    gatsby-transformer-sharp: ^3.4.0 => 3.6.0
  npmGlobalPackages:
    gatsby-cli: 3.6.0
```

### PR DESCRIPTION
**Pull request by ben-dyer**
## Description

The original command line plugin for prismjs does not highlight output lines, but this plugin does. See an example here https://prismjs.com/plugins/command-line/.

## Related Issues

Fixes #31794

### CODE REVIEW

**Comment by ben-dyer** [comment]
This worked for my simple test cases, but is still a work in progress since some tests are failing.

What I will try next is instead of mapping on `code.split("\n")`, split the array into alternating blocks of code and output, and call Prism.highlight on each block, which should reproduce usual behavior when no outputLines are specified.

I will try to get back to that tomorrow.

**Comment by ben-dyer** [comment]
The tests that were failing after the initial commit are documented in this commit https://github.com/gatsbyjs/gatsby/pull/31835/commits/7a7784bd4c6bd92e0a31c4559ee0e34be927d37b.

It might make sense to do a special case when `outputLines` are present since its very specific to the command-line plugin. This is done in b61f4b7, but it looks like there weren't tests for the command-line plugin previously, so I can't be confident there is not a regression or an incompatibility.

I have added one test case for outputLines, also here is code for a demo app https://github.com/ben-dyer/gatsby-demo (the examples I have checked are in `test.md`)

**Comment by wardpeet** [comment]
Thank you for your PR! Sorry for taking so long, I'll be trying it out and thanks for the demo app, that will help me a lot getting this merged!

**Comment by ben-dyer** [comment]
Hi @wardpeet, no worries, and thanks for the reply.

I realized that the current version wouldn't be able to line-highlight output lines (sounds like a valid use case though). I haven't checked if this is possible in prismjs either yet.

If we need to support line-highlighting shell output lines, we might be able to break `codeLindes` into alternating chunks of output and non-output, and then call `Prism.highlight` on each block, only using "text" or "none" for the language in output lines. I'm not sure if this may cause an issue when consecutive output and non-output lines are both highlighted though.

**Comment by LekoArts** [comment]
Hey! Thanks so much for opening this pull request!

Sadly this PR got stale and didn't have any activity for some time. We're trying to do better with PR reviews! To get a better overview of all actionable PRs we're going through all open PRs and triage them. Since we won't be able to do everything and adding new features _always_ means added maintenance burden, we have to be more picky about what's beneficial for the average user and the project itself longterm.

Having said all this, we dropped the ball on this PR and we're sorry about not responding to it earlier. As said above, we want to do better in the future but here we should have communicated earlier what will happen with the PR.

If you (or anyone else) still want this feature, please open a [feature request](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) and we can talk through the details.

We absolutely want to have you as a contributor and are sorry for any inconveniences we caused with replying too late to this PR.

Thanks for submitting to Gatsby! 💜

**Pull request closed without merging**
