### PR TITLE
feat(gatsby-remark-images-contentful): enable webp sources

### PR DESCRIPTION
**Pull request by AlbericTrancart**
## Description

Add a `withWebp` option to include a webp source in parsed images from contentful.

## Related Issues

Addresses #11268.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Is there any reason to not just make this the default? Seems like everyone should have webp enabled :-)

**Comment by AlbericTrancart** [comment]
@KyleAMathews I didn't enabled it by default because it isn't in `gatsby-remark-images` so I thought there should be a good reason, but I will make it the default then :+1: 

@wardpeet what kind of structure are you thinking of? Something like this? (I will implement this TODO rightaway if possible :wink: )

```
srcSet: {
  original: ...,
  webp: ...
}
```

**Comment by wardpeet** [comment]
hey @AlbericTrancart it's super cool that you want to take this on right away but it would be a breaking change so we have to wait for gatsby v3. Also I haven't thought about it yet 😄.

**Comment by AlbericTrancart** [comment]
Updated!

**Comment by KyleAMathews** [comment]
@wardpeet this wouldn't be a breaking change actually because it's hidden from the user — nobody's code would break — their sites would just get faster :-)

**Comment by KyleAMathews** [comment]
@AlbericTrancart the only reason we don't include it by default in gatsby-remark-images is that generating webp thumbnails is a _lot_ more expensive than jpg. So we want people to opt into webp so they realize the cost they're taking on (as not everyone wants to tradeoff longer build times for smaller images).

But with a hosted service like Contentful where webp images are generated on demand, it makes a lot more sense to default to webp.

**Comment by AlbericTrancart** [comment]
@KyleAMathews @wardpeet any news on merging this PR? :)

**Comment by AlbericTrancart** [comment]
@wardpeet PR rebased to fix a merge conflict on the README.

**Comment by ryanwiemer** [comment]
Any update on this? I would love to see the gatsby-remark-images-contentful plugin get some improvements.

**Comment by AlbericTrancart** [comment]
@wardpeet @KyleAMathews ping to merge this PR :)

**Comment by sidharthachatterjee** [comment]
Published in gatsby-remark-images-contentful@2.0.9

**Pull request merged**
