### PR TITLE
Project AMP starter

### PR DESCRIPTION
**Pull request by chiedo**
Try this.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Looks great!

**Comment by chiedo** [comment]
:D

**Comment by KyleAMathews** [comment]
It'd be great if could also update the README there with a bit of explanation about what AMP is and how to use the CLI tool + deploy the site so people can easily see what it looks like.

**Comment by chiedo** [comment]
Done!

**Comment by KyleAMathews** [comment]
👍

**Pull request merged**
