### PR TITLE
Add Gatsby CLI options to docs

### PR DESCRIPTION
**Pull request by LeKoArts**
I couldn't find the options in the documentation. Or did I oversee something?

### CODE REVIEW

**Comment by LeKoArts** [comment]
*overlook
(GitHub‘s mobile website is trash)

**Comment by LeKoArts** [comment]
I don‘t mind putting it on its own Docs page. I just thought this would be the most obvious place as the commands are only described there.

**Comment by KyleAMathews** [comment]
Yeah, that page is meant only as a high-level intro to the CLI, not detailed documentation.

What we could do is say something like:

>To see detailed documentation about the commands, run in the terminal `gatsby --help` or for command help `gatsby COMMAND_NAME --help` e.g. `gatsby develop --help`.

**Comment by LeKoArts** [comment]
> To see detailed documentation about the commands, run in the terminal gatsby --help or for command help gatsby COMMAND_NAME --help e.g. gatsby develop --help

And how about a dedicated page for the Gatsby CLI and its commands (under Reference)?
Even if you include it into the CLI directly you should write it down somewhere in my opinion.

(Sidenote: Could I "revert" the first commit of this PR and commit a page for the docs?)

**Comment by LeKoArts** [comment]
Something like that? :)

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by KyleAMathews** [comment]
I removed the link (it should link to `/packages/gatsby-cli/` btw not GitHub). It'd still make sense to link there but the README is missing documentation on the build & serve command so isn't overly helpful right now.

**Pull request merged**
