### PR TITLE
Blur input on search submit

### PR DESCRIPTION
**Pull request by m-allanson**
Fixes https://github.com/gatsbyjs/gatsby/pull/4561#issuecomment-373873417

### CODE REVIEW

**Comment by m-allanson** [comment]
Preview is here: https://deploy-preview-4605--gatsbyjs.netlify.com/

**Comment by tsriram** [comment]
I'm not sure if this fixes the issue. If I understand it correctly, issue happens specifically when you select a search result with mouse. Pressing `Enter` to select a search result takes the focus out of the search box and clicking on the search box opens up the search results. But when you select a search result using mouse, you're taken to the result page but the search input's focus doesn't go away for some reason. With the search input already focused, when you click on the input it doesn't pop up the results and you've to type something to see the search results. This behaviour seems to persist even with this fix.

**Comment by shannonbux** [comment]
@tsriram I'm not much of a developer so I don't know how to test whether this PR fixes the issue...

**Comment by tsriram** [comment]
@shannonbux you can open up the preview link - https://deploy-preview-4605--gatsbyjs.netlify.com/ - which @m-allanson posted above and see if the issue is fixed. It contains the patch from this PR.

**Comment by shannonbux** [comment]
Thanks @tsriram, and @m-allanson the issue I described before persists in this preview, unfortunately.

**Comment by m-allanson** [comment]
> you're taken to the result page but the search input's focus doesn't go away for some reason

@tsriram You're right. [This line](https://github.com/gatsbyjs/gatsby/pull/4605/files#diff-f772c656e3adc950a1dfc1c014c753e1R255) should be clearing the focus, but doesn't seem to do  anything. Experimenting here I can see the blur event being fired, but the cursor remains in the input element. Odd.

**Comment by m-allanson** [comment]
Closing this for now, but have opened #4997 for anyone that wants to investigate further.

**Pull request closed without merging**
