### PR TITLE
fix(gatsby-cli): Fix --clipboard on Windows

### PR DESCRIPTION
**Pull request by sidharthachatterjee**
`gatsby info --clipboard` has issues on Windows as documented in https://github.com/gatsbyjs/gatsby/issues/11496

envinfo dropped clipboard support in v6 and removed `clipboardy` so using it directly here. Not sure if it will fix https://github.com/gatsbyjs/gatsby/issues/11496 since no behaviour should've changed 

### Todo
- [ ] Get a reproduction of https://github.com/gatsbyjs/gatsby/issues/11496 from @saranshkataria and open issue in https://github.com/sindresorhus/clipboardy
- [ ] Upgrade to latest envinfo
- [ ] Fix issue upstream in clipboardy

### Related 
https://github.com/tabrindle/envinfo/issues/83 and https://github.com/gatsbyjs/gatsby/issues/11496

### Test

`npm i gatsby-cli@clipboardy`

### Other Changes
- The underline to the sections is gone since we log to console ourselves now (not a big deal in my opinion)
- Added `duplicates` and `showNotFound` options (useful for debugging and cra uses them too) 

### Before
Screenshot 2019-04-08 18 14 21
### After
Screenshot 2019-04-08 18 14 48
(Notice the Not Found for Firefox)

### CODE REVIEW

**Comment by saranshkataria** [comment]
Though this gives a better output, node version is still missing here:

D:\test> gatsby info --clipboard

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: Not Found
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.3.16 => 2.3.16
    gatsby-cli: ^2.5.5-clipboardy.1 => 2.5.5-clipboardy.1
    gatsby-image: ^2.0.37 => 2.0.37
    gatsby-plugin-manifest: ^2.0.28 => 2.0.28
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32
    gatsby-source-filesystem: ^2.0.29 => 2.0.29
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17

**Comment by sidharthachatterjee** [comment]
@saranshkataria Node version and browsers not showing up seems strange! Can you open an issue in https://github.com/tabrindle/envinfo for this? 

Does the clipboard stuff work by any chance?

**Comment by saranshkataria** [comment]
@sidharthachatterjee this was the output from clipboardy (I installed `gatsby-cli@clipboardy` globally and `ran gatsby info --clipboard`)

**Comment by sidharthachatterjee** [comment]
@saranshkataria Oh, alright! I meant to ask if gatsby info --clipboard correctly copied over to the clipboard or not?

**Comment by sidharthachatterjee** [comment]
Potentially relevant/useful stack trace at https://github.com/gatsbyjs/gatsby/issues/13274#issue-431614082

**Comment by saranshkataria** [comment]
The above output was copied to the clipboard correctly. Though it is relatively less information than the sample you provided, but it is atleast copying it to the clipboard which was not happening before.

**Comment by wardpeet** [comment]
@sidharthachatterjee same here

```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: Not Found
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - C:\Users\WardPeeters\.windows-build-tools\python27\python.EXE
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.3.3 => 2.3.3
    gatsby-image: ^2.0.35 => 2.0.35
    gatsby-plugin-manifest: ^2.0.25 => 2.0.25
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.11 => 3.0.11
    gatsby-plugin-sharp: ^2.0.32 => 2.0.32
    gatsby-source-filesystem: ^2.0.28 => 2.0.28
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17
```

**Comment by sidharthachatterjee** [comment]
Just reverted the `envinfo` config to what it was before (I'd added `duplicates` and `showNotFound` options) and published a new version. 

@saranshkataria @wardpeet Can you try `npm i gatsby-cli@clipboardy` again and confirm that --clipboard works correctly on Windows?

**Comment by wardpeet** [comment]
```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 10.15.3 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.15.2 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.9.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - C:\Users\<user>\.windows-build-tools\python27\python.EXE
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.3.23 => 2.3.23 
```

**Pull request merged**
