### PR TITLE
feat: Added encoding arg to "loadNodeContent" method

### PR DESCRIPTION
**Pull request by alexandrtovmach**
## Description

Added second argument to set custom encoding in `loadNodeContent` method.

### Documentation

https://www.gatsbyjs.org/docs/node-api-helpers/#loadNodeContent
In PR added more details to documentation.

## Related Issues

#26173

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
Find another thing that's Node.js doesn't support `windows-1251` out-of-box:
https://github.com/nodejs/node/blob/a97b5f9c6acd101ec20d9278a840b2cb6ef94ac9/deps/npm/node_modules/sorted-union-stream/node_modules/string_decoder/index.js#L27

Converted PR to draft to think deeper

**Comment by alexandrtovmach** [comment]
Added [`iconv-lite`](https://www.npmjs.com/package/iconv-lite) to support as much as possible encodings

**Comment by pieh** [comment]
This adds 2nd param (encoding), but it isn't actually used anywhere? Now it's up to transformers to make use of it? Do you use custom transformer in the usecase you shared in https://github.com/gatsbyjs/gatsby/issues/26173 where you would make use of it?

**Comment by alexandrtovmach** [comment]
Hey,
You're totally right, this is an optional parameter, and shouldn't be a BREAKING CHANGE for anyone. If transformer maintainers need this, they just can pass custom encoding. For my case it was a custom transformer to handle legacy code files, that used `windows-1251` encoding.

**Comment by alexandrtovmach** [comment]
@pieh Sorry for lack of activity here for last year))
I resolved conflicts, could you take a look please?

**Comment by LekoArts** [comment]
Hey! Thanks so much for opening this pull request!

Sadly this PR got stale and didn't have any activity for some time. We're trying to do better with PR reviews! To get a better overview of all actionable PRs we're going through all open PRs and triage them. Since we won't be able to do everything and adding new features _always_ means added maintenance burden, we have to be more picky about what's beneficial for the average user and the project itself longterm.

Having said all this, we dropped the ball on this PR and we're sorry about not responding to it earlier. As said above, we want to do better in the future but here we should have communicated earlier what will happen with the PR.

Unfortunately we won't merge this PR at the moment because there doesn't seem to be a need for it (since no one else requested it).

If you still think that this should be added, please open a [feature request](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) in our discussions. Thanks!

We absolutely want to have you as a contributor and are sorry for any inconveniences we caused with replying too late to this PR.

Thanks for submitting to Gatsby! 💜

**Pull request closed without merging**
