### PR TITLE
WIP: fix: fixes regression with pathPrefix and gatsby-link

### PR DESCRIPTION
**Pull request by DSchau**
Note: this is not done! Want to get the tests actually working. Unsure why the globals aren't setting, and why I need to use Jest globals :/

Also similar to #1574. We should probably consolidate our efforts

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 26c2d78c6b3d97e39bc1f9b09e11581ba30b7f26

https://app.netlify.com/sites/using-glamor/deploys/5970dac87960b15b567a2c7a

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 26c2d78c6b3d97e39bc1f9b09e11581ba30b7f26

https://app.netlify.com/sites/using-remark/deploys/5970dac87960b15b567a2c83

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 26c2d78c6b3d97e39bc1f9b09e11581ba30b7f26

https://app.netlify.com/sites/gatsbygram/deploys/5970dac77960b15b567a2c68

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 26c2d78c6b3d97e39bc1f9b09e11581ba30b7f26

https://app.netlify.com/sites/gatsbyjs/deploys/5970dac77960b15b567a2c65

**Comment by KyleAMathews** [comment]
Looks like the tests are failing due to the glamor issue I'm fixing in #1580

**Comment by DSchau** [comment]
@KyleAMathews yeah I wasn't so concerned with those, and figured they'd be fixed at some point.

Just unsure _why_ I can't set globals like I am for the `DefinePlugin` replaced values :/ It'd be nice to have some tests so we can catch a regression in the future

**Comment by KyleAMathews** [comment]
Looks like you're setting them right... https://stackoverflow.com/a/40460395

**Comment by KyleAMathews** [comment]
Merged #1574 and making a release. Would love to get your tests in soon!

**Pull request closed without merging**
