### PR TITLE
refactor: use Array.includes()

### PR DESCRIPTION
**Pull request by johnsgeorge14**
## Description
Minor code refactoring.

## Related Issues
N/A

### CODE REVIEW

**Comment by m-allanson** [comment]
Thank you @johnsgeorge14! I'm going to close this PR as I don't think it makes a meaningful improvement to Gatsby.

While we have merged a couple of PRs like this in the past, we will not continue to do so as this change does not fix or improve Gatsby's documentation or functionality.

I'd love to see a contribution from you that updates the documentation, or resolves an open issue. Check out [the Contributing docs](https://www.gatsbyjs.org/contributing/how-to-contribute/) if you'd like more info on getting started.

**Comment by johnsgeorge14** [comment]
@m-allanson I'm not sure what you guys're pretending. We're targetting Node.js above `v6` and the respective change makes much sense :confused:

**Comment by sidharthachatterjee** [comment]
@johnsgeorge14 Left a comment on your new PR! 

> @m-allanson I'm not sure what you guys're pretending. We're targetting Node.js above v6 and the respective change makes much sense 😕

Also, we’d appreciate friendlier language in the future. We’re certainly not pretending to be anything 🤷🏻‍♂️ We’re here to help you contribute!

**Comment by johnsgeorge14** [comment]
> @johnsgeorge14 Left a comment on your new PR!
> 
> > @m-allanson I'm not sure what you guys're pretending. We're targetting Node.js above v6 and the respective change makes much sense confused
> 
> Also, we’d appreciate friendlier language in the future. We’re not pretending to be anything and are here to help you contribute!

Sincere apologies :pray:

**Pull request closed without merging**
