### PR TITLE
chore(starters): add semantic-ui-docs-gatsby

### PR DESCRIPTION
**Pull request by whoisryosuke**
Adding my Semantic UI documentation starter.

## Description

Added my starter to YML file.

### CODE REVIEW

**Comment by whoisryosuke** [comment]
Interesting. It failed because `Styling:Semantic UI` isn't available as a primary category. I'm going to add it to the `categories.yml`. 

If there's a reason to limit the number of categories, we can also just remove it from my starter description.

**Comment by laurieontech** [comment]
Thanks for the PR! This starter looks great. However, we're not planning on adding any new categories for tagging at the moment. If you want to remove/change that tag we'd love to add the starter!

**Comment by whoisryosuke** [comment]
@laurieontech awesome, no worries, I figured. Removed the SUI category.

**Comment by laurieontech** [comment]
Wonderful! Thanks for the PR :)

**Pull request merged**
