### PR TITLE
fix(cache-dir): catch exception preventing dev mode load

### LINKED ISSUE #16076: SecurityError: The operation is insecure in Firefox Developer edition
## Description

With gatsby develop and Firefox Developer Edition (latest version, 69.07b), firefox throws a security error exception when `app.js` checks `if  (`serviceWorker` in navigator)`, and hence the app cannot be used:

SecurityError

### Steps to reproduce

1. Install firefox developer edition
2. Run gatsby develop on any gatsby project (no offline plugin nor anything sw-related)

### Expected result

You see the website and can develop it normally.

### Actual result

You get the error above and hence cannot do anything (the error triggers the react overlay error and does not let you interact with the site at all)

### Environment

```
  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.16.0 - /tmp/yarn--1564036896798-0.009151794373142508/node
    Yarn: 1.17.3 - /tmp/yarn--1564036896798-0.009151794373142508/yarn
    npm: 6.9.0 - /usr/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 68.0
  npmPackages:
    gatsby: ^2.1.27 => 2.13.32
    gatsby-image: ^2.0.31 => 2.2.6
    gatsby-plugin-create-client-paths: ^2.0.4 => 2.1.3
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.0.22 => 2.2.3
    gatsby-plugin-react-helmet: ^3.0.8 => 3.1.2
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1
    gatsby-plugin-remote-images: ^1.0.1 => 1.0.3
    gatsby-plugin-sass: ^2.0.11 => 2.1.3
    gatsby-plugin-sharp: ^2.0.25 => 2.2.8
    gatsby-plugin-typescript: ^2.1.0 => 2.1.2
    gatsby-source-filesystem: ^2.0.23 => 2.1.5
    gatsby-source-s3-image: ^1.5.8 => 1.6.5
    gatsby-transformer-sharp: ^2.1.15 => 2.2.4
```

### PR DESCRIPTION
**Pull request by bradobro**
This addresses #16706. In dev mode, app.js checks for
service workers and warns on the console that they might
cause unanticipated behavior. This causes Gatsby apps
to fail loading using `npm run develop` and current stable
FireFox. As browser security settings tighten, we can only
expect this to happen more often.

## Description

In `develop` mode, Gatsby apps check to see if a service worker is present and warns in the browser console that the developer might want to remove them.

Unfortunately, browser security settings can throw a fatal, uncaught, exception that prevents the app from loading. This is seen in FireFox 78.0.2 Linux (current stable release when this PR was authored) and perhaps others.

There have been several fixes proposed. This PR opts for the minimal route:

- Following best practices it catches the exception.
- Following the behavior of the original code, it simply warns in the browser console that a service worker could cause unexpected behavior during development.
- It *swallows* the exception, regardless of the browser, since we can't know when this default policy may be adopted by other browsers and because we don't want to crash the app just because a subtle attempt to aid developers failed.

More aggressive solutions could include:
- Put the warning in the the build console output whenever a service worker is built.
- In dev mode, warn if a service worker fails to update.

### Documentation

This fixes a small, undocumented, developer experience feature. The larger issue is that service workers can make debugging more difficult for the unaware. A browser `console.warn` is a minimal attempt to help.

We may want to add documentation at https://www.gatsbyjs.org/docs/resource-handling-and-service-workers/#service-worker-swjs and https://www.gatsbyjs.org/docs/add-offline-support-with-a-service-worker, something like:

> Be aware that introducing a service worker, while increasing your PWA Lighthouse score, also has implications for debugging. Commonly, this will include stale data or behavior appearing despite a clean build. The simplest solution is to simply delete the service worker(s). See the development tools documentation for you browser to learn more. A more complete discussion of service workers can be found on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API#Service_worker_concepts_and_usage).

## Related Issues

Fixes #16076.

### CODE REVIEW

**Comment by TylerBarnes** [comment]
Sorry @moonmeister , tagged the wrong person!

**Comment by bradobro** [comment]
Just a note, this is now default behavior in Firefox current stable, not just developer edition.

**Comment by f00f** [comment]
Any news on this? I ran into it after 30 min. of using gatsby. Not a pleasant welcome...

**Comment by j0sh77** [comment]
Hey! Thanks so much for opening this pull request!

Sadly this PR got stale and didn't have any activity for some time. We're trying to do better with PR reviews! To get a better overview of all actionable PRs we're going through all open PRs and triage them. Since we won't be able to do everything and adding new features _always_ means added maintenance burden, we have to be more picky about what's beneficial for the average user and the project itself longterm.

We think this is a great PR and would love to see it land in Gatsby. We're closing this PR _for now_ but if you're able to rebase onto the latest `master` branch and try it out with the latest `next` versions, we'd be happy to review the PR when its re-opened.

We absolutely want to have you as a contributor and are sorry for any inconveniences we caused with replying too late to this PR.

Thanks for submitting to Gatsby! :purple_heart:

**Pull request closed without merging**
