### PR TITLE
Removing https://chiedo.tv from sites.yaml, as its failing to screens…

### PR DESCRIPTION
**Pull request by robwalkerco**
…hot and causing a build error

screen shot 2018-08-06 at 09 42 15

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit ac4010bd784e28ca07f2279fbfe0238d724c2099

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6809fd3813f04e1adb0757

**Comment by KyleAMathews** [comment]
Got there 3 minutes before you ;-)

https://github.com/gatsbyjs/gatsby/pull/7048

Thanks!

Doing some edits to the website?

**Comment by m-allanson** [comment]
Thanks @robwalkerco! @KyleAMathews got in just before you with #7048, so I'm going to close this.

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbygram* failed.

Built with commit ac4010bd784e28ca07f2279fbfe0238d724c2099

https://app.netlify.com/sites/gatsbygram/deploys/5b6809fc3813f04e1adb074e

**Pull request closed without merging**
