### PR TITLE
Windows CLI

### PR DESCRIPTION
**Pull request by NogsMPLS**
This PR attempts to fix the whole cli issue over at #80 

With these changes I was able to execute the ```gatsby new docs-site gh:gatsbyjs/gatsby-starter-documentation``` command without having to rename a bin file.

One note: in order to run ```gatsby develop``` I had to go into the docs-site folder and add ```"use strict";``` to the ```app.js``` file. After that it all ran fine. Ideally this wouldn't be needed, but can't think of a good alternative right now.

This was tested on a Windows 7 machine running Node 5.7.0 and npm 3.6.0

I would advise testing this branch on mac as well, just to make sure it is still cross compatible. Changes don't seem like they will break anything, but with this cross platform stuff, you never know.

### CODE REVIEW

**Comment by NogsMPLS** [comment]
oh. right. didn't do a lint run before PRing. One minute....

**Comment by NogsMPLS** [comment]
The eslint config in the starter repo doesn't like "use strict" so there is still some work to do around that, unless we want to attach an eslint override on it.

**Comment by KyleAMathews** [comment]
Why the need for the "use strict" in the first place?

**Comment by NogsMPLS** [comment]
usage of let/const, etc.

```
C:\dev\docs-site\app.js:2
  let context = require.context('./pages', true)
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

Might be something with babel I can mess with though

**Comment by NogsMPLS** [comment]
okay, switched up the babel register options and it seems to handle all three commands. :tada:

**Comment by KyleAMathews** [comment]
I'm a bit confused about that error and your fix... was that an eslint error or was that a node.js error? If I run `npm run lint` in the starter-blog for example, it lints `app.js` just fine.

**Comment by NogsMPLS** [comment]
Commit 7c7bf5f288392abc2e9ef3d5906cd289fa29b32e was just lint stuff related to the babel-register options I added to gatsby-new/gatsby-develop/gatsby-build files inside of ```bin```. Double quote/single quote and dangling comma stuff.

Commit ab83d3607e20757398561736f291463c99b9d1d6 was to change the babel-register option from being exclusive 'only' to instead be more inclusive for everything and ignore everything in node_modules *except* gatsby.

**Comment by NogsMPLS** [comment]
oh wait, unless you were referring to https://github.com/gatsbyjs/gatsby-starter-documentation/pull/3

that lint error came from trying to use ```"use strict"``` inside app.js.

With commit ab83d3607e20757398561736f291463c99b9d1d6 in this repo, that PR in the starter repo is no longer needed, and so I closed it.

**Comment by KyleAMathews** [comment]
Yeah I don't get https://github.com/gatsbyjs/gatsby/commit/ab83d3607e20757398561736f291463c99b9d1d6 as Gatsby is actually distributed as already compiled by Babel so it shouldn't need this. Also app.js isn't part of Gatsby so I don't understand why changing the babel register option would affect an error in app.js.

**Comment by NogsMPLS** [comment]
hmmmm...that would explain some stuff. 

For testing I was just doing npm install -g my fork of gatsby, but that fork didnt have the build files, so that would make sense.

im out right now, but ill remove those babel-register options and push the commit up when i get home.

**Comment by NogsMPLS** [comment]
Maybe a good idea for me to close this branch/PR and squash these commits into 1 since all those changes ended up being reverted and really its just a simple file name change. Agree/Disagree?

**Comment by KyleAMathews** [comment]
+1 though I don't think you need to close the PR to squash. Just squash and
do a force push.

**Comment by NogsMPLS** [comment]
yeah, just wasn't sure how you'd feel about a push -f ;P

I'll do that right now.

**Comment by KyleAMathews** [comment]
This is awesome @NogsMPLS! Turned out to be a pretty simple fix, weird. Whatevers, stay weird Windows :) Going to merge my other PRs real quick and make a new release so hopefully Windows folks will be happy now.

**Comment by NogsMPLS** [comment]
:tada: :notes: :trumpet: :notes: :tada:

**Pull request merged**
