### PR TITLE
Makes trailing slash optional

### PR DESCRIPTION
**Pull request by scottyeck**
Addresses #651

### CODE REVIEW

**Comment by scottyeck** [comment]
Oof - not sure what that build failure is. Happy to take a look if you guys grant access to contributors 😄

**Comment by KyleAMathews** [comment]
Oh the Netlify thing? Ignore that for now — it's for 1.0 but you can't turn it off afaik for other branches. :man_shrugging:

**Comment by KyleAMathews** [comment]
The PR looks good! I'm assuming you didn't put the route modification in `create-routes` because that'd break server rendering?

**Comment by scottyeck** [comment]
@KyleAMathews Didn't have much to do with _breaking_ something, per se - just thought at the outset that this was a react-router issue, but that could very well be a product of my own experience with _gatsby_ on the server.

**Comment by scottyeck** [comment]
Any more thoughts on this guy? Happy to revise if people aren't happy with it.

**Comment by KyleAMathews** [comment]
I haven't had time to pull the PR and properly review it yet. Code looks good though.

@gatsbyjs/gatsby-core-maintainers any thoughts?

**Comment by scottyeck** [comment]
@KyleAMathews Sorry don't mean to ruffle anything. Thanks so much for taking a look - much appreciated. 🙌  🙌  🙌

**Comment by KyleAMathews** [comment]
No ruffling done! :-) Just haven't had time yet.

**Comment by scottyeck** [comment]
👌

**Comment by scottyeck** [comment]
FWIW, I forked this and published it privately. We're currently using it in production on www.meetfabric.com.

**Comment by KyleAMathews** [comment]
Hmmm... ok just had a thought — the name seems wrong. With your regex, the trailing slash isn't "optional", it's *always* removed correct? So the config name should be `noTrailingSlash` right?

**Comment by scottyeck** [comment]
True - but per my testing, the router was able to consume the route the same way regardless, so you _could_ conceivably still use the trailing slashes if you wanted.

**Comment by scottyeck** [comment]
I could very well be wrong - I'll poke around in a bit and return with a definitive answer.

**Comment by scottyeck** [comment]
Looks like this is a way better implementation for the same effect: https://github.com/gatsbyjs/gatsby/pull/657

Feel free to disregard this work! 😎

**Pull request merged**
