### PR TITLE
#3024 Exclude 404 pages from sitemap

### PR DESCRIPTION
**Pull request by jurosh**
More details https://github.com/gatsbyjs/gatsby/issues/3024

I had to use regex as it was not possible to do with simple path matching as was initially.
Regex contains negative look-ahead.

Now all paths starting with `404` & `dev-404-page` are automatically filtered out.

### CODE REVIEW

**Comment by jurosh** [comment]
Please wait with merging - need to test latest changes...

**Comment by jurosh** [comment]
PS would be good to add sitemap plugin into preview site cause now it's not generated...and not possible to verify if on preview server are 404 gone

**Comment by KyleAMathews** [comment]
nice! Thanks for tackling this!

I just updated this PR with the latest code from master as there's some fixes to the preview build but gatsbyjs.org has also has previews built that we can look at its preview at https://deploy-preview-3239--gatsbyjs.netlify.com/sitemap.xml

**Comment by KyleAMathews** [comment]
Hrmmm not sure why the preview stuff isn't working. Ran this locally on the gatsbyjs.org site and it worked so 🤷‍♂️ guess it's working

**Comment by jlengstorf** [comment]
Hiya @jurosh! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by jurosh** [comment]
Hey @jlengstorf I like to be part of such great product :) Thanks

From Gatsby swag I like t-Shirts, but currently no M size, will you have those in future ?
Btw. I am not part of Gatsby organization and also cannot see your invite yet - can you try to re-send ?

**Comment by jurosh** [comment]
Hey @jlengstorf I like to be part of such great product :) Thanks

From Gatsby swag I like t-Shirts, but currently no M size, will you have those in future ?
Btw. I am not yet part of Gatsby organization and also cannot see your invite yet.

**Comment by jlengstorf** [comment]
@jurosh we'll have shirts back in stock the first or second week of March. For the invite, can you try visiting https://github.com/orgs/gatsbyjs/invitation?

If you don't see it, let me know.

**Pull request merged**
