### PR TITLE
[docgen] better error handling and update to v3

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by jquense** [comment]
look good? less the conflicts, i'll fixem up

**Comment by m-allanson** [comment]
Travis is failing on some `transformer-react-doc-gen` tests... I've restarted it.

**Comment by jquense** [comment]
I really don't know what the deal with these test are this works locally

**Comment by m-allanson** [comment]
I'll try it locally here and see what happens.

**Comment by m-allanson** [comment]
I'm seeing the same test failure when running this locally...

**Comment by jquense** [comment]
let me nuke everything and try again :P

**Comment by m-allanson** [comment]
I spent a bit of time poking at it, this looks like the line that's throwing the error: https://github.com/reactjs/react-docgen/blob/6a192c07703d99507871ba8730879ed1aa80ad46/src/utils/normalizeClassDefinition.js#L43

**Comment by jquense** [comment]
arg i found it. CI was right all a long

**Pull request merged**
