### PR TITLE
Add woff and woff2 extension to the file loader

### PR DESCRIPTION
**Pull request by davycheung**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 675ff5af5089955b3be4d4d0532fa3b64af4a539

https://app.netlify.com/sites/image-processing/deploys/595651d78ebdd97dee86e530

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 675ff5af5089955b3be4d4d0532fa3b64af4a539

https://app.netlify.com/sites/using-contentful/deploys/595651d78ebdd97dee86e539

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 675ff5af5089955b3be4d4d0532fa3b64af4a539

https://app.netlify.com/sites/using-postcss-sass/deploys/595651d78ebdd97dee86e52a

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 675ff5af5089955b3be4d4d0532fa3b64af4a539

https://app.netlify.com/sites/gatsbygram/deploys/595651d68ebdd97dee86e521

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 675ff5af5089955b3be4d4d0532fa3b64af4a539

https://app.netlify.com/sites/using-styled-components/deploys/595651d78ebdd97dee86e536

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 675ff5af5089955b3be4d4d0532fa3b64af4a539

https://app.netlify.com/sites/gatsbyjs/deploys/595651d68ebdd97dee86e51e

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 675ff5af5089955b3be4d4d0532fa3b64af4a539

https://app.netlify.com/sites/using-glamor/deploys/595651d78ebdd97dee86e533

**Comment by davycheung** [comment]
sorry looks like this is already in the 1.0 closing.

**Pull request closed without merging**
