### PR TITLE
add gatsby days blog post

### PR DESCRIPTION
**Pull request by amberleyromo**
Add Linda's Gatsby Days blog post

### CODE REVIEW

**Comment by amberleyromo** [comment]
Dated for tomorrow (Tue Nov 27).

**Comment by pieh** [comment]
What do you think about swapping banner from "Watch: “Rise of the Content Mesh: Webcast with Contentful and Gatsby”." to point to this blog post (or eventbrite page directly)?

**Comment by amberleyromo** [comment]
@lindaleebumblebee ^see @pieh's comment

**Comment by amberleyromo** [comment]
@pieh I can make that change separately if @lindaleebumblebee wants, but I know she wants this blog post up this morning. Please merge if 👍

**Comment by lindaleebumblebee** [comment]
@pieh I love that idea- swap the banner on .org to point to this blog post. Let's get this post up first and then we can focus on the banner. Thanks!

**Comment by DSchau** [comment]
Merged!

**Comment by lindaleebumblebee** [comment]
Thanks all! Anything else that needs to be done for it to go live? (this whole merging, squashing process is new to me :)

**Comment by amberleyromo** [comment]
@lindaleebumblebee the merge triggered a build -- once that's complete it will be reflected live 👍

**Pull request merged**
