### PR TITLE
gatsby-remark-responsive-images: use span instead of div (#1150)

### PR DESCRIPTION
**Pull request by rstacruz**
Fixes invalid HTML being generated by gatsby-remark-responsive-images.

Full story: #1150

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hmmm this doesn't seem to be working see https://deploy-preview-1151--gatsbyjs.netlify.com/blog/gatsbygram-case-study/ for example — all the images are gone

It looks like `span.gatsby-resp-image-background-image` needs a `display: block` added. Does that still work with html-to-react?

BTW, curious why you choose to use html-to-react?

**Comment by KyleAMathews** [comment]
Also we lost the base64 preview image recently — I'll add that back in a separate PR real quick.

**Comment by fk** [comment]
> Also we lost the base64 preview image recently

@KyleAMathews Damn … my fault?!

**Comment by KyleAMathews** [comment]
@fk haha yes :-) looks like you used the wrong variable name when [converting things to use your new `responsiveSizes` helper function](https://github.com/gatsbyjs/gatsby/pull/1047). NBD!

**Comment by fk** [comment]
@KyleAMathews Yeah totally missed adjusting that – and I thought I tested thoroughly… :/
Sorry + thanks for fixing!

**Comment by KyleAMathews** [comment]
It was a big PR and we're still in alpha so no big deal :-)

**Comment by rstacruz** [comment]
I've added `display: block`, because I've tested that, and it I believe it works.

I really want it to be `display: inline-block` so we have support for inline images (eg, emoji's), because without it, the image replacement isn't a "transparent" process that has no side effects.

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 40755ad46e23a53de666746bdc3b7755ef3a2d5c

https://app.netlify.com/sites/image-processing/deploys/594012a3424ef2549dfc0186

**Comment by KyleAMathews** [comment]
Hmmm yeah inline image support is kinda necessary.

Cool, this is looking good so let's get this merged in and work on inline image support in another PR.

Thanks for the PR!

**Comment by jlengstorf** [comment]
Hiya @rstacruz! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
