### PR TITLE
fix(gatsby): Recognise null pages as not found

### LINKED ISSUE #26988: Error when redirect route '/' to '/lang/'
## Description

When i make localized paths like routes `/en/`, `/fr/`, etc, and for that i have delete the page `/` for recreate with localized path. But i have error when access to `/`.

### Steps to reproduce

1. Clone my repo https://github.com/orblazer/gatsby-i18n-issues/tree/page-errors (branch `page-errors`)
2. Run `gatsby develop`
3. Go to `http://localhost:8000/`
4. Open console and see errors

### Expected result

Redirect to `/{defaultLanguage}/` (like `/en/`) without error.

### Actual result

Two error is throwed when access to '/'
1. `The route "/" matches both a page and a redirect; this is probably not intentional.`
    This is come from https://github.com/gatsbyjs/gatsby/blob/1a7a446bf67e5d79cf62dbb67fc4610d7a1f198a/packages/gatsby/cache-dir/navigation.js#L25
2. 
    ```
    Uncaught Error: EnsureResources was not able to find resources for path: "/"
    This typically means that an issue occurred building components for that path.
    Run `gatsby clean` to remove any cached elements.
    ```
    This is come from https://github.com/gatsbyjs/gatsby/blob/030d927cddbdc64f8d93d409a5ada7442d5e62bf/packages/gatsby/cache-dir/ensure-resources.js#L79

### Environment

```
$ gatsby info --clipboard

  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.10.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.7 - /usr/bin/npm
  Languages:
    Python: 3.8.5 - /usr/bin/python
  Browsers:
    Firefox: 80.0.1
  npmPackages:
    gatsby: ^2.24.63 => 2.24.63
```

### Other

*I think i just no understand something.*
**Additional question :** how i can create an redirect the page like `/test` to `/en/test` (or `/en/404`) for localized error page ?

### PR DESCRIPTION
**Pull request by ascorbic**
In the client side loader, if a page in the db is null it is not shown as "not found". This causes an error in some situations with client-side redirects. See #26988 for an example. This returns true for `isPageNotFound` if the page is null. Additionally, it doesn't register a path in websocket manager if it is null, which would otherwise occur in this case with a client-side redirect.

Fixes #26988

### CODE REVIEW

**Review by wardpeet — APPROVED** [review]
nice! Thanks!

**Comment by jablonski** [comment]
This change seems  to break existing code which uses "navigate" & RouterLink from @reach/router to navigate between pages in Dev-Mode. Navigating from page to page results in the 404-dev-page. Reloading the 404-page shows the correct page. Gatbsy 2.24.64 works fine, so I guess that this change introduced in 2.24.65 might cause the problen.

**Comment by ascorbic** [comment]
Hi @jablonski . Could you share a reproduction? It worked in my testing.

**Comment by jablonski** [comment]
Okay, here are the steps. Create a new starter project:

> gatsby new gatsby-test https://github.com/gatsbyjs/gatsby-starter-hello-world

As src/pages/index.js use:

```
import { Link } from "@reach/router"
import React from "react"

export default function Home() {
  return <Link to="/page2">Page2</Link>
}
```

As src/pages/page2.js use:

```
import { Link } from "@reach/router"
import React from "react"

export default function Page2() {
  return <Link to="/">Home</Link>
}
```

Now run it in develop mode. Clicking on the link works fine with Gatsby version up to 2.24.64, but results in the error page with 2.24.65 and above.

We need to use Link from @reach/router in our project because we have to rebundle our components without a Gatsby dependency. With Link from "gatsby" it works fine.

**Pull request merged**
