### PR TITLE
chore(showcase): Add nexweave site to gatsby showcase

### PR DESCRIPTION
**Pull request by KashafS**
Add Nexweave site to gatsby showcase
### Description:
Nexweave is a SaaS platform built by a team of experienced product, design & technology professionals in India. Nexweave allows brands to create personalized & interactive video experiences at scale. We would love for our site to be featured at the gatsby showcase since we have long been appreciating the flexibility and speed of the sites we have created using the same.

### CODE REVIEW

**Comment by KashafS** [comment]
> Thanks for the PR, @KashafS ! Could you please add a detailed README to the repo, this would help for more clarity as to what the site is about. Thank you

Hey, @Ekwuno where do you want me to add this README file exactly?

**Comment by Ekwuno** [comment]
> Hey, @Ekwuno where do you want me to add this README file exactly?

Where you have this "Add Nexweave site to gatsby showcase" 🙂.

**Comment by KashafS** [comment]
> > Hey, @Ekwuno where do you want me to add this README file exactly?
> 
> Where you have this "Add Nexweave site to gatsby showcase" .

Is it the PR description you're talking about? Do you want me to update commit message?

**Comment by Ekwuno** [comment]
> Is it the PR description you're talking about? Do you want me to update commit message?

 I apologize for being unclear. Yes, please. 😄

**Comment by KashafS** [comment]
> > Is it the PR description you're talking about? Do you want me to update commit message?
> 
> I apologize for being unclear. Yes, please.

Hi @Ekwuno the changes you requested have been made, kindly let me know if it suffices the requirements  :-)

**Pull request merged**
