### PR TITLE
Add Fathom Analytics to Gatsby Starter Blog

### PR DESCRIPTION
**Pull request by bcye**
## Description
This PR adds the functionality to add the [Fathom Analytics](https://usefathom.com) tracking script to your site created with the gatsby-starter-blog

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
The official starters are meant to be unopinionated and as minimal as possible so while I think Fathom is awesome, I don't think adding it by default is a good idea. 

Nonetheless, thank you for taking the time to open this! 💜

**Comment by bcye** [comment]
So why is Google Analytics getting an exception? Because of its size?

**Comment by sidharthachatterjee** [comment]
@bcye That's actually a great question. I'd forgotten that that's included by default! I reckon it's there since it's popular enough to be a default but I wouldn't be opposed to removing it to be honest. 

Curious what the rest of @gatsbyjs/core thinks

**Comment by bcye** [comment]
Another option might be to simply document in the README how to install either into the project (or maybe add it as a blog post or a page in the docs something along the lines of "How to add analytics to your Gatsby website").

**Comment by bcye** [comment]
Would be interested in working on that if that's something wanted.

**Comment by bcye** [comment]
So thumbs up means yes?

**Comment by bcye** [comment]
There is already a doc page about this: https://gatsbyjs.org/docs/adding-analytics/

**Pull request closed without merging**
