### PR TITLE
fix(showcase): Remove Stitch Fix from featured sites

### PR DESCRIPTION
**Pull request by allypalanzi**
## Description

Stitch Fix is no longer using GatsbyJS

### CODE REVIEW

**Comment by allypalanzi** [comment]
I'm not sure, I can't find it!

**Comment by barrymcgee** [comment]
@allypalanzi Yeah, me either.. it does seem to reflect your homepage exactly as it is right now though which makes me think it might be generated on the fly?

**Comment by wardpeet** [comment]
@allypalanzi mind sharing with us in DM or email why you switched so we can improve our product based on your feedback

**Comment by barrymcgee** [comment]
@wardpeet Do you mind explaining where the screenshot is?

**Comment by LekoArts** [comment]
@barrymcgee https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-screenshot creates the initial image, Sharp transforms the image then: https://github.com/gatsbyjs/gatsby/blob/master/www/src/pages/showcase.js#L29

**Comment by barrymcgee** [comment]
@LekoArts Thank you 🙏🏻

**Pull request merged**
