### PR TITLE
Relative path for Webpack HMR

### PR DESCRIPTION
**Pull request by jdbence**
Walks around many of the issues with online editors like C9.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hmmm wouldn't this break people using Gatsby on their localhost or or a remote server (and set their host to their IP address)?

**Comment by jdbence** [comment]
@KyleAMathews I've tested the change on localhost, local network IP and Cloud9. Can you clarify more on the last one?

**Comment by KyleAMathews** [comment]
You removed `http://${ program.host }`

**Comment by jdbence** [comment]
The development server starts at the custom host/port and then HMR connects relative to that path without needing to be absolute. Our team has been using it this way but I'll close this out since a proxy can be used for the same thing.

**Pull request closed without merging**
