### PR TITLE
[WIP] fix(gatsby-remark-images): Reduce default image thumbnail sizes

### PR DESCRIPTION
**Pull request by tanaypratap**
## Description

This PR introduces changes to fix issue #12857

### CODE REVIEW

**Comment by KyleAMathews** [comment]
It's a bit hard to review this PR with all the (unrelated?) changes to the test file — can you revert those and maybe make that change in a separate PR?

**Comment by tanaypratap** [comment]
Sure I'll do that. The tests needed to be separated and so I went ahead and
did it. I'll send a separate PR for that.

**Comment by wardpeet** [comment]
Friendly ping @tanaypratap any chance you can pick this one up again? 💪

**Comment by tanaypratap** [comment]
hey @wardpeet I am sorry that I am unable to spend time on this PR. Especially the separation part. Please feel to free to unassign this PR from me as I won't be able to complete it in near future due to some work commitments. 
I wanted to contribute to Gatsby but looks it is not happening anytime soon. I'll be back when I can spend more time and pick any open issue at that moment.

**Comment by sidharthachatterjee** [comment]
@tanaypratap No worries at all! We understand. Let's close this out for now and circle back to it later in the future. 

Thanks again for your work on this nonetheless 💜

**Pull request closed without merging**
