### PR TITLE
chore(showcase): Update showcase website list

### PR DESCRIPTION
**Pull request by mhel14**
Update GreenOrbit site url.

### CODE REVIEW

**Comment by Nina0708** [comment]
Hi @m-allanson, @mhel14 is no longer working for the Effective Digital company which builds the GreenOrbit website. Is there any way we can edit our site submission, not through @mhel14 but someone else like me?

**Comment by lannonbr** [comment]
@Nina0708 Of course. We can close this PR and then you can submit a new PR if you wish to modify the entry in the site showcase

**Comment by Nina0708** [comment]
Thanks, @lannonbr, it would be great if you can do that for us.

**Comment by lannonbr** [comment]
Alright. closing this PR

**Pull request closed without merging**
