### PR TITLE
[www] Fix/improve masthead background across breakpoints

### PR DESCRIPTION
**Pull request by fk**
* still not 100, but only minor overlaps now and no more issues with seemingly disappearing (white-on-white) Github/Twitter/Discord icons
* comment color palette in utils/presets

Quite happy with this.
Now let's get some content for the right part! 😋 ✌️

### CODE REVIEW

**Comment by fk** [comment]
Good to go!

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit f751776e61543cbc32724fabaaa03221980cdd61

https://app.netlify.com/sites/image-processing/deploys/597aa65a6f4c5016484025e1

**Comment by fk** [comment]
Can be merged, no more random follow up commits here ;-)

**Comment by KyleAMathews** [comment]
Very nice!

**Pull request merged**
