### PR TITLE
feat(gatsby): Adds a way to exclude folders from query compiler search

### LINKED ISSUE #17691: [Request] Add ability to exclude files / folders when compiling query
## Summary

I would like the ability to exclude whole folders form the query compiler rather than scanning every js / ts file in the repo.  
There are use cases where often you don't want every file parsed / built, for example when needing to use the same codebase with separate CMS's. 

### Basic example
In gatsby.config.js` could be defined by 

```
module.exports = {
  excludeFiles: ['/src/templates/folderName/**.js'],
}
```
### Motivation

Motivation for this is the desire to use the same codebase for maintainability / code sharing but the ability to build some templates under certain circumstances. 

My use case is we have one website for UK and one for Germany. The design is similar enough to warrant the same codebase but the layout and content are very different. 
We are using two different Contentful spaces to achieve this. However currently we need to create "Dummy" pages in some occasions to prevent gatsby throwing 
`- Unknown field on type 'Query'.` errors

What i would like to do is separate my templates in the codebase and then exclude those templates and the queries in them from getting built / parsed

### PR DESCRIPTION
**Pull request by ssijak**
## Description

This change adds a way to exclude folders from query compiler search using env variable. I have worked in several projects where this is useful and needed. For example if there are several different sites built from the same project source, if one site is using graphql sources or models which are not needed in the build of the other then the build of the other site will fail unless there is a way to exclude those not needed queries (or include pages or models which are not meant for that site).

With this change we would be able to exclude queries which we do not need so based on the example explained above we could run:
`EXCLUDE_QUERY_COMPILER=src/mobile-site,src/marketing-site npx gatsby build` to build one site from the same source
or `EXCLUDE_QUERY_COMPILER=src/marketing-site,src/admin-site npx gatsby build` to build another one, excluding queries which are not relevant to the site which we are currently building.
There are also other usecases which other people reported through time where they needed this feature.

## Related Issues

Fixes #17691

### CODE REVIEW

**Review by vladar — COMMENTED** [review]
Thank you for suggesting this. It makes sense as an escape hatch. But it involves a bit more work to get this merged:

1. This feature must be discoverable. So we should add a note to related Gatsby errors saying something like: 

    `If you are not using this file you can exclude it from processing by passing environment variable GATSBY_EXCLUDE_PATHS=path_to_file`

    I suggest adding this line here (apeend to the error message you are seeing, probably `85923`?): https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/structured-errors/error-map.ts

2. We need some tests for it. A good place for them would be this file: [`__tests__/query-compiler.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/query/__tests__/query-compiler.js).

**Comment by ssijak** [comment]
> Thank you for suggesting this. It makes sense as an escape hatch. But it involves a bit more work to get this merged:
> 
>     1. This feature must be discoverable. So we should add a note to related Gatsby errors saying something like:
>        `If you are not using this file you can exclude it from processing by passing environment variable GATSBY_EXCLUDE_PATHS=path_to_file`
>        I suggest adding this line here (apeend to the error message you are seeing, probably `85923`?): https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/structured-errors/error-map.ts
> 
>     2. We need some tests for it. A good place for them would be this file: [`__tests__/query-compiler.js`](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/query/__tests__/query-compiler.js).

I've added the documentation to the error message and a test for this feature.

**Comment by vladar** [comment]
Another problem with this is that the default Gatsby eslint ruleset still fails the build even with this flag (just tried). So, we should also adjust eslint rule to make this feature complete. Otherwise it is pretty useless for majority of Gatsby users with default eslit settings.

Do you have custom eslint rules in your projects? Do you see this error as well?

**Comment by ssijak** [comment]
> Another problem with this is that the default Gatsby eslint ruleset still fails the build even with this flag (just tried). So, we should also adjust eslint rule to make this feature complete. Otherwise it is pretty useless for majority of Gatsby users with default eslit settings.
> 
> Do you have custom eslint rules in your projects? Do you see this error as well?

Sorry I am not sure I understand what you are referring to, can you clarify? What does this feature has to do with eslint settings to be useless for majority of users?
When I run `yarn lint` and `yarn test` in the root of the gatsby project I get no errors.

**Comment by vladar** [comment]
Sorry, let me try to explain:

1. Say you have a query that produces a GraphQL error in the current build
2. You exclude the file with this query from query compiling with this env variable
3. But the file is still processed by webpack and it runs eslint against it. Gatsby uses [eslint-plugin-graphql](https://github.com/apollographql/eslint-plugin-graphql) to check queries against current schema in eslint
4. So even if you've excluded the query from compiling, the build still fails with webpack/eslint error:

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


src/pages/test.js
  88:5  error  Cannot query field "nonExistingField" on type "Query"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)
```

So, ideally excluding query should also exclude it from webpack/eslint processing.

**Comment by ssijak** [comment]
I understand the possible issue now, thanks for clarification. For my use-cases which I explained in the first message, this is not the issue, because this queries are needed and should be formatted per eslint rules, they are just not needed in all the build targets the project has. For example in the current project I have the following build targets in Makefile:
```
build-www:
	yarn --pure-lockfile;
	make lint
	rm -rf .cache && rm -rf public && GATSBY_BUILD_WEBSITE=www npx gatsby build

build-blog:
	yarn --pure-lockfile
	make lint
	GATSBY_BUILD_WEBSITE=blog npx gatsby build

build-mobile:
	yarn --pure-lockfile
	make lint
	GATSBY_BUILD_WEBSITE=mobile npx gatsby build
```
etc. So from the same project I am reusing much of the code, UI library, and other components and am building several sites from it. I just need a way to ignore each other site queries with the `GATSBY_EXCLUDE_PATHS` flag but each query is used in some of the builds and is maintained.

On the other hand, I see your point. So if I would like to ignore **only** graphql part of the file by adding a eslint rule, how should I do it? I do not see that it is supported by browsing the `https://github.com/apollographql/eslint-plugin-graphql`. Or should I try to add `excludedFiles` entry in the base of the `gatsby` repo in the `.eslintrc.js` file which is based on the `GATSBY_EXCLUDE_PATHS`? Maybe this should be left to the user if they want to additionally exclude this files from eslint check.

**Comment by vladar** [comment]
Just to clarify - which error number are you seeing in your situation? Is it `GraphQL 85923` or something else for you?

**Comment by ssijak** [comment]
Yes, it is `85923` error.

**Comment by vladar** [comment]
And what error message specifically? Also about the missing field? In this case, you should be seeing eslint errors too. Do you have standard Gatsby eslint, or using a custom ruleset?

**Comment by ssijak** [comment]
So, I removed my `eslintrc` config and build passes with no eslint problems

Screenshot 2020-10-07 at 21 08 20

But if I run it without GATSBY_EXCLUDE_PATHS set I just get a bunch of `85923` errors.

Screenshot 2020-10-07 at 21 09 53

What example are you running to get the eslint errors on build, in the context of this patch.

**Comment by vladar** [comment]
Oh, right, this will show up in `gatsby develop` not in `gatsby build`.

> What example are you running to get the eslint errors on build, in the context of this patch.

I am trying on a simple [gatsby blog starter](https://github.com/gatsbyjs/gatsby-starter-blog) - basically just copied `pages/index.js` to `pages/test.js`, added a non-existent field to query and tried excluding the file with the env var.

But the build fails for me too with webpack error (which makes sense because the template expects `data` to be defined here):

```
failed Building static HTML for pages - 1.765s

 ERROR #95313

Building static HTML failed for path "/test/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


   7 |
   8 | const Test = ({ data, location }) => {
>  9 |   const siteTitle = data.site.siteMetadata?.title || `Title`
     |                          ^
  10 |   const posts = data.allMarkdownRemark.nodes
  11 |
  12 |   if (posts.length === 0) {


  WebpackError: TypeError: Cannot read property 'site' of undefined

  - test.js:9
    src/pages/test.js:9:26
```

So ideally we should exclude those paths from webpack compilation as well (this will solve the eslint problem too, obviously).

**Comment by wardpeet** [comment]
@ssjak I'm not really in favor of this change. It's another `process.env` variable that changes behavior, we already have a few and sooner or later it becomes a head-scratcher or we remove it and we break your builds.

The official way to do what you're looking for is going with [themes](https://www.gatsbyjs.com/docs/themes/what-are-gatsby-themes/) they allow you do re-use a site and built on top of it.

Would that work for you?

**Comment by ssijak** [comment]
@vladar My latest changes should solve the eslint issue. I've also refactored the feature so that GATSBY_EXCLUDE_PATHS is a list of glob patterns to exclude. In your example with the latest changes this should pass with no errors `GATSBY_EXCLUDE_PATHS=**/pages/test.js gatsby develop`

@wardpeet Themes is not what I am looking for. This is a simple flag, I think that it will not be problematic regarding future updates where it could clash with some other possible future update. [There is already a way to exclude/ignore files from which to generate pages ](https://github.com/gatsbyjs/gatsby/blob/03950cf83daccbfadf052533cd5d40c39fa5fb1f/packages/gatsby-plugin-page-creator/src/create-page-wrapper.ts#L32). I am using `gatsby-plugin-page-creator` to pick which files to use to generate pages for particular websites (using GATSBY_BUILD_WEBSITE env variable to make a decision in the example from previous messages) in my use-cases, but the problem is that there is no way to do the same for queries. This is a small pull request which will allow that too.
So if one of my sites built from the same project is using another CMS or the same CMS with the different config/model as the other site, currently I need to pull the data from all the CMS-es and include all the models in each and every site I build from the same source so that I can have passing builds.
People have similar issues like mine [#17691](https://github.com/gatsbyjs/gatsby/issues/17691), [another one who patched query compiler himself](https://spectrum.chat/gatsby-js/general/exclude-from-extract-queries-from-components~bafe4128-801f-4ef4-b9c4-f1f6a756d6a8), [etc](https://spectrum.chat/gatsby-js/general/is-there-a-way-to-ignore-graphql-queries~61255f18-2a9a-4be9-96b4-9f022d2984ca)..

**Comment by wardpeet** [comment]
@ssijak I get that it seems like a small thing and it always is but it's another diversion in code so needs extra maintenance from us. It might lead to subtle issues when people set the variable wrongly, ... The env-var also deals with eslint config so there are now 2 pieces of our code base that diverge. It will be hard in a month or 2 to know what's happening.

I get that you want a quick fix but themes does fix this issue. You can have multiple themes and a site that uses 1 or more of them.

As such--we're going to close this out. We want you to know that we certainly want to keep you as a contributor to Gatsby, so we'd encourage you to check out our open issues.

Thanks again, and we look forward to seeing more PRs from you in the future! 💪 💜

**Comment by vladar** [comment]
After thinking about this (and in light of changes required to webpack processing) I tend to agree with @wardpeet 

The initial code in this PR was constrained to a single file and seemed easy. But in practice, we need to also ignore those files for the whole webpack processing (eslint fix is not enough here). And there can be other pitfalls as we change this part of the codebase.

Realistically this is a very fragile solution and we can't guarantee that it won't break when we add some new feature involving file scanning or custom webpack config.

I understand that it works for you at the moment but realistically this is unreliable in the long run.

**Pull request closed without merging**
