### PR TITLE
Remove /app for path route

### PR DESCRIPTION
**Pull request by ipatate**
Related to #15532

### CODE REVIEW

**Comment by pieh** [comment]
@ipatate we will be fixing issue that introduced the need for this change (it's considered a bug because it breaks v2 behaviour)

**Comment by ipatate** [comment]
Ok, i close the PR.

**Comment by ipatate** [comment]
@pieh i tried the version 2.13.10, it's ok now. That work fine.

**Comment by pieh** [comment]
Awesome! Thanks for update on that @ipatate!

**Pull request closed without merging**
