### PR TITLE
fix: make elemMatch operator work with ___NODE arrays

### LINKED ISSUE #7385: Support filtering on deep nested nodes
## Description

First of all I don't know if it's the best fitting title (feel free to change it to a better one 😉).
So basically my issues are described in this PR:
https://github.com/gatsbyjs/gatsby/pull/6315

This PR unfortunately didn't fix my issues on filtering tags. Those tags are custom types (in the Prismic backend) and look like this in the GraphQL response:
https://github.com/gatsbyjs/gatsby/pull/6315/commits/a17c1d36e949bb66e5ab8c630380c8472fd24855

### Steps to reproduce

I can't give everyone access to my API keys so you'd need to setup a project on your own (though @pieh has one key for testing)

### Expected result

I should be able to query like with markdown:
https://github.com/LeKoArts/portfolio/blob/master/src/templates/tag.jsx#L65

And also be able to use group like with markdown:
https://github.com/LeKoArts/portfolio/blob/master/src/pages/tags.jsx#L78

### PR DESCRIPTION
**Pull request by pieh**
closes #7385

### CODE REVIEW

**Comment by LeKoArts** [comment]
Copying over the changes to my local node_modules folder didn't resolve the issue. Is that the wrong way of testing it?

**Comment by pieh** [comment]
This need some more work, as @LeKoArts mentioned - this needs some changes to `run-sift.js` (it will not resolve node properly to be filtered if ___NODE is inside array currently) - I have working dirty copy of `run-sift` but it needs cleanup ( https://gist.github.com/pieh/91fd2643fa5a0e2f8bbfbd1f47a7a279 - clean me up please :D)

**Comment by LeKoArts** [comment]
Just to document it here, too:
When comparing the old and new `run-sift.js` these lines are new and fix the issue:

https://gist.github.com/pieh/91fd2643fa5a0e2f8bbfbd1f47a7a279#file-run-sift-js-L110
https://gist.github.com/pieh/91fd2643fa5a0e2f8bbfbd1f47a7a279#file-run-sift-js-L142-L177

**Comment by gurtjun** [comment]
Hi @pieh, will this fix #7251?

**Comment by pieh** [comment]
@gurtjun this isn't related to mapping, I will try to take a look at your case soon

**Comment by btk** [comment]
@camsloanftc oh this is also what happened to me, and have been pulling my hair over this;
```
    allposts: allWordpressPost(filter: {categories: {slug: {eq: $slug}}}, limit: 12, skip: $skip)
```

This query have been working before this PR, now on (2.0.24), the working version has to be this;

```
    allposts: allWordpressPost(filter: {categories: {elemMatch: {slug: {eq: $slug}}}}, limit: 12, skip: $skip)
```

> Maybe this affects a small number of people 

I'm sure this breaks a lot of projects, 2 of my projects are using the old filtering syntax on at least 5 different places.

@camsloanftc also, your comment helped me find out what was the problem, thank you. Hope others can find it too.

**Comment by pieh** [comment]
@camsloanftc @btk was it even working before those changes? filtering on array of ___NODE seemed pretty broken to me when I was working on that PR

**Comment by btk** [comment]
@pieh, yes it was working as intended, what I mean by intended;

```
    allposts: allWordpressPost(filter: {categories: {slug: {eq: $slug}}}, limit: 12, skip: $skip)
```
filters the posts which includes an object with `$slug` slug in its categories array (the property `categories` is an array of object) And If I remember it correctly I have seen it used in this format online (in stackoverflow or starter github repos etc)

And after this PR it does not work the same way, graphql throws an error.

```
success onPreExtractQueries — 0.018 s
success update schema — 1.356 s
error GraphQL Error Field "slug" is not defined by type wordpressPostConnectionCategoriesQueryList_2.

  file: /builds/btk/******/src/templates/Category/category.js

   1 | 
   2 |   query($slug: String!, $skip: Int!) {
   3 |     wordpressCategory(slug: {eq: $slug}){
   4 |       slug
   5 |       name
   6 |       description
   7 |       count
   8 |     }
>  9 |     allposts: allWordpressPost(filter: {categories: {slug: {eq: $slug}}}, limit: 12, skip: $skip) {
     |                                                      ^
  10 |       edges{
```

Not sure if it helps.

**Comment by pieh** [comment]
I think I will look into making it backward compatible - from my tests it seemed pretty broken so that's why I did this change because it seemed like it never worked

**Comment by btk** [comment]
@pieh yeah, if there wont be any conflict with making it backward compatible that would be great. Also using the new syntax, (introducing elemMatch) is a more readable and understandable for the long run I think.

For example this github search: https://github.com/search?q=allWordpressPost%28filter%3A+%7B+categories&type=Code

Gives 100 results that would probably be broken now, and this is only for querying in wordpress-sourced data.

**Pull request merged**
