### PR TITLE
feat(gatsby-plugin-utils): add `contentDigest` to image cdn args

### PR DESCRIPTION
**Pull request by veryspry**
## Description

Adds Image Node's content digest as a url param to all Image CDN urls. This allows for hosting to set cache control headers for images.

### CODE REVIEW

**Review by wardpeet — COMMENTED** [review]
can we add a test that this works as expected

**Comment by veryspry** [comment]
> can we add a test that this works as expected

Totally

**Comment by veryspry** [comment]
Tests are updated to check for and validate that the `cd` param has been added :+1:

**Review by wardpeet — APPROVED** [review]

**Review by marvinjude — APPROVED** [review]
LGTM

**Review by TylerBarnes — APPROVED** [review]

**Pull request merged**
