### PR TITLE
fix(gatsby): createSchemaCustomization typings

### PR DESCRIPTION
**Pull request by RIP21**
fix: update GatsbyNode typings adding `createSchemaCustomization` typings

### CODE REVIEW

**Comment by RIP21** [comment]
I didn't run prettier or whatever. I did this change right from the GitHub UI, sorry :) Will be grateful for some to apply proper code formatting for me :P

**Comment by wardpeet** [comment]
Hey @RIP21

I cleaned up the PR a little as the typings weren't 100% correct. I do get why you've used pick for the actions but they aren't 100% on the same line as the args the `createSchemaCustomization` actually gets.

**Comment by RIP21** [comment]
@wardpeet question. It's a second time I see in the typings people using backticks to define some string. Isn't it not valid syntax? Cause Webstorm for example, complains :)

Anyway, thanks a lot, my main idea was to show the absence of such thing in typings :) Will be glad that to be merged and added next patch or whatever version :)

**Comment by wardpeet** [comment]
yeah sorry bad copy :) Good catch 😉

**Pull request merged**
