### PR TITLE
updates on how-to-contribute page

### PR DESCRIPTION
**Pull request by MarcCoet**
Added 2 lines:
* Install yarn and lerna globaly: `npm install -g yarn lerna`
* Checkout to the 1.0 branch: `git checkout 1.0`

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by jlengstorf** [comment]
Hiya @MarcCoet! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by MarcCoet** [comment]
Hey @jlengstorf . Thanks.
To be honest I don't think I deserve it. ^^ I use Gatsby everyday since early V1 alphas. I basically learned web development with Gatsby but I have never made a significant contribution.
For the past 3-4 years I have been freelancing and for the past 2-3, working on a website builder based on Gatsby. I am getting very close to something I will be proud to share and I hope this will be beneficial for the Gatsby ecosystem and community.
If I understand correctly you are in charge of community relations?! Then I will get back to you when I have something to show.
Have a great day.

**Comment by jlengstorf** [comment]
That sounds super exciting! Definitely let me know when you're ready to share. 💜

**Pull request merged**
