### PR TITLE
chore(showcase): add guillaumebriday.fr to showcase

### PR DESCRIPTION
**Pull request by guillaumebriday**
## Description

Adds "guillaumebriday.fr" to showcase.

### CODE REVIEW

**Comment by oliver-gomes** [comment]
@guillaumebriday  Everything looks good but the checking failed due to linting

**Comment by oliver-gomes** [comment]
@guillaumebriday  *npx prettier "**/*.yml" --write* should fix it

**Comment by guillaumebriday** [comment]
Thank you @oliver-gomes ! I think it's good now 👍

**Comment by oliver-gomes** [comment]
@guillaumebriday This still requires someone from the ecosystem to review so have to wait on that 😃

**Comment by guillaumebriday** [comment]
Thank the gatsby community ! 👍

**Pull request merged**
