### PR TITLE
chore(showcase): add recent site builds

### PR DESCRIPTION
**Pull request by dbrookes**
Adds a few recent site builds to the showcase

### CODE REVIEW

**Comment by oliver-gomes** [comment]
Although I might want to double check with the errors

**Comment by wardpeet** [comment]
seems like danger has spotted a linting error

**Comment by dbrookes** [comment]
@wardpeet it has but it's not in my commit, do you want me to fix it?

**Comment by wardpeet** [comment]
ah sorry, missed it. I've put up a fix :)

**Pull request merged**
