### PR TITLE
update to include 'npm install' bash command

### PR DESCRIPTION
**Pull request by eghan**

### CODE REVIEW

**Comment by LeKoArts** [comment]
Hi, thanks for the PR, we appreciate it!

Sadly I have to close this PR as `gatsby new` is already running `npm install`/`yarn install` in the background and hence this additional step is not necessary.

Hope to see another PR from you soon!

**Comment by eghan** [comment]
is there a local environmental reason this would not happen?  
I have repeated the test, I have to run npm install manually.
would you attempt to replicate?

thanks!

**Comment by DSchau** [comment]
@eghan as info, here's the code for `gatsby-cli` (e.g. gatsby new) https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/src/init-starter.js#L31

So it definitely runs `npm install` (or `yarn` if yarn is detected). Not sure what's going on in the local environment. Would you be able to open an issue if you can reproduce?

**Comment by eghan** [comment]
@DSchau Thanks!  I'll do a little digging and see if I should make a bug report

**Pull request closed without merging**
