### PR TITLE
Moving file to src/utils from src/schema/node-model

### LINKED ISSUE #19027: Move `node-model` documentation to `utils`
## Summary

Move the documentation in `src/schema/node-model` to a stub documentation file in `src/utils` (where `api-node-docs` and `api-browser-docs` are.

### Motivation

This would make it easier to translate this API, since it will be in its own page without any code and can be copied over to the [gatsby-i18n-source repo](https://github.com/gatsbyjs/gatsby-i18n-source).

### Details

All the documentation comments in `src/schema/node-model` should be moved to a file called `api-node-model-docs` with stubs of the content, similar to files `api-node-docs` and `api-browser-docs`.

All graphql queries that reference `node-model` documentation (namely, `www/src/pages/docs/node-model`) should be redirected to use the new file.

### PR DESCRIPTION
**Pull request by SunveerSingh**
## Description

As mentioned by @tesseralis in #19027 file destination needs to be changed from src/schema/node-model to a stub documentation file in src/utils (where api-node-docs and api-browser-docs are.

## Related Issues

Fixes #19027

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
@SunveerSingh Leaving this in case you missed the previous comment. Anything I can do to help get this in?

**Comment by LekoArts** [comment]
Friendly ping @SunveerSingh

**Comment by SunveerSingh** [comment]
Hello @LekoArts sorry for the delay, actually my exams are going on. I would love to start again, @sidharthachatterjee  can you please explain me through it like what specifically I have to do?

**Comment by tesseralis** [comment]
@SunveerSingh I don't think this is actually what we want to end up doing: https://github.com/gatsbyjs/gatsby/issues/19027#issuecomment-551992563

That said, I'll close this PR out for now. You can take a look at the new issue (#19382) for more information.

**Pull request closed without merging**
