### PR TITLE
chore(gatsby-transformer-sqip): Improve documentation

### PR DESCRIPTION
**Pull request by axe312ger**
Turned out the documentation was out of date. This update shows how to actually use the plugin.

Additionally decreases the npm bundle size by not bundling the demo videos.

### CODE REVIEW

**Comment by LekoArts** [comment]
Hi, thanks for the update. Would you mind also updating the bits referring to images (`sizes` and `resolutions` + GraphQL fragments)? Since these are now outdated, too :)

**Comment by axe312ger** [comment]
Thanks, good catch. Should be fine now @LekoArts

**Comment by LekoArts** [comment]
Ha, what I also meant is this:

```graphql
sizes(maxWidth: 400, maxHeight: 400) {
  ...GatsbyImageSharpSizes_noBase64
}
```

To be:

```graphql
fluid(maxWidth: 400, maxHeight: 400) {
  ...GatsbyImageSharpFluid_noBase64
}
```

And so one (for `resolutions`, too).

Thanks!

**Comment by axe312ger** [comment]
Opps, thank you. Fixed :)

**Pull request merged**
