### PR TITLE
gatsby-plugin-netlify-functions

### PR DESCRIPTION
**Pull request by porfirioribeiro**
This plugin builds netlify functions using the gatsby webpack config
So you can use the same babel features as the rest of your project.
If you install `gatsby-plugin-typescript` you can write functions in typescript.

It also creates a middleware on dev server when you run `gatsby develop`, alowing to run the functions locally. For that i had to implement a new API on gatsby-node
`onRunDevServer` will be called when creating the dev server and pass the express `app` allowing to add proxies or middlewares.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 0411c24c30ec254c38582cb642d3d454b6506c5a

https://app.netlify.com/sites/using-postcss-sass/deploys/5b59975ae39e7c269b83cb7e

**Comment by porfirioribeiro** [comment]
Things i have been considering:
Merge this plugin with `gatsby-plugin-netlify` with just a option to support functions.
Probably read netlify.toml, i personally prefer to have all the config on `gatsby-config.js` 
and this way you don't even need the netlify.toml file as you can have the functions path set on 
Netlify back-office, and we still need to know the source of the functions.

**Comment by porfirioribeiro** [comment]
After vacations i tested a bit more and this seems to be working ok on my tests.
I don't know if the name of the API `onRunDevServer` follows the right naming convention @KyleAMathews

**Comment by pieh** [comment]
Maybe `onCreateDevServer`? 

Would you be willing to host plugin outside of this repo and leave just API addition in this PR?

**Comment by porfirioribeiro** [comment]
`onCreateDevServer` seems good to me.
And yes i can host the plugin outside of this repo, just added it here as it already have
`gatsby-plugin-netlify` and `gatsby-plugin-netlify-cms`
This weekend i will try to update the PR with those changes

**Comment by porfirioribeiro** [comment]
This pull request can be closed when #7556 is merged.
And i will implement the plugin in a different place

**Comment by pieh** [comment]
Now that #7556 is merged we can close this, right?

**Comment by porfirioribeiro** [comment]
Yes, as soon as i have time i will adapt the plugin to the new API and put it on my GitHub

**Pull request closed without merging**
