### PR TITLE
Fix image references in contributing.md

### PR DESCRIPTION
**Pull request by SD10**
**Summary of PR:**
Fixes a few broken links in CONTRIBUTING.md

### CODE REVIEW

**Comment by SD10** [comment]
@m-allanson Thanks for clarifying. Sorry I didn't check for previous issues 🙃 Let me know if my changes are what you had in mind.

**Comment by m-allanson** [comment]
The changes to CONTRIBUTING.md look good 👍.  Could you also update [docs/docs/how-to-contribute.md](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/how-to-contribute.md)? Replacing that symlink with the contents that you've just removed from CONTRIBUTING.md.

Then the links should all be correct, and the site will have the right contributing info.

**Comment by SD10** [comment]
Doh. Yeah that's probably a good idea 😅. Updated

**Comment by m-allanson** [comment]
💥 thanks! You will have saved multiple people from trying to edit those links in the future :)

**Comment by jlengstorf** [comment]
Hiya @SD10! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
