### PR TITLE
[examples/using-remark]: Custom React components in Markdown files

### PR DESCRIPTION
**Pull request by r24y**
I'm not too attached to the article itself, so feel free to edit/rewrite/etc. as needed.

### CODE REVIEW

**Comment by r24y** [comment]
I tested this with the version of `gatsby-transformer-remark` after the changes introduced in #3711, but this PR can't merge until those changes have been published.

**Comment by KyleAMathews** [comment]
This is super exciting! I didn't realize rehype-react could do this! This might be the holy grail :-D Excited to get this out there so people can explore it.

Curious if you did any size/performance comparisons? Like how practical is it to just switch all markdown rendering to use rehype-react instead?

**Comment by r24y** [comment]
Shoot, I hadn't thought of that! Shipping the AST to the browser in JSON form certainly takes more bandwidth than shipping the HTML; I can compare load times using the Chrome dev tools. I've got to learn more about how Gatsby manages the data since it might be possible to ship the AST only if the file specifies something like `liveAst: true` in its YAML header and save some bytes. I could also compare load times against reparsing the HTML client-side to create the AST, but I suspect that above a certain sized file the hit we take on reparsing would be larger than the hit we take on sending the AST over the wire.

I might not get to this soon, but I'll keep it in mind and write it up when I do 😃

**Comment by KyleAMathews** [comment]
Cool! Would love to hear reports about you and others trying this in the wild. I think the extra overhead wouldn't be too excessive but probably you wouldn't want to use the htmlAST yeah unless you have React components inside.

**Comment by rayk** [comment]
This is **_awesome_** I have been building also of interactive content with [idyll](http://idyll-lang.org/) over the last few weeks and shoehorning it into Gatsby via the static directory and a few other nasty hacks. As far as I can see this opens the door to doing doing explorable documents within Gatsby.   

Still early days, I noticed that components ```<my-component></my-component>``` always gets placed in the tree as ```"tagName": "p",``` which is not ideal, as [p tags](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element) tag don't like div under them. Obviously it still works, but will probably trigger a reflow because of bade nesting.

Anyhow this is such and exciting develop... Thanks Ryan @r24y and Kyle @KyleAMathews .

**Comment by r24y** [comment]
@rayk good point! I think the reason it gets nested like that is because Markdown wants to wrap everything in a paragraph; the problem would be alleviated with a Remark plugin that says, "for every paragraph: if the paragraph contains a single item which is a custom element, replace it with a `div`".

**Comment by r24y** [comment]
@KyleAMathews, would it be possible for someone like me to use the current plugin system to swap out the transport layer? Looking at https://using-remark.gatsbyjs.org I can see that the GraphQL response is loaded with `webpackJsonp`, but if this were traded for a mechanism that used a binary format like msgpack then the AST would actually consume _less_ bandwidth than the HTML source. 

I'm not looking for anyone to spend time investigating 😄 just your hot take on whether it would take a ton of effort, or be really simple. I really appreciate the time you've already spent helping me out. Obviously `webpackJsonp` works really well for Gatsby, and I don't want to mess with Gatsby's stability at all. I'm just a nerd with an itch to scratch

**Comment by KyleAMathews** [comment]
> I'm just a nerd with an itch to scratch

Haha :-)

I'm not sure msgpack would be much faster given webpackJsonp is already loading (on most sites) data compressed with gzip.

I don't think loading the AST is a serious problem for smaller usages. I was just more curious on getting numbers for the exact hit we're taking e.g. loading the AST is 15% more expensive.

**Comment by raphadeluca** [comment]
@rayk , did you find a way to integrate idyll in Gatsby. Do you think it could possible to write a idyll document as we do with markdown and transform it during the bootsrap process into a static file?

**Pull request merged**
