### PR TITLE
fix a typo in prop types on README.md

### PR DESCRIPTION
**Pull request by eladams**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
What did you fix? Having trouble seeing it for some reason in the diff...

**Comment by eladams** [comment]
Sorry :),  prop types `string|object` look messed up on github `md` file viewer.

**Comment by KyleAMathews** [comment]
Oh gotcha. Yeah, we write markdown for our website — https://www.gatsbyjs.org/packages/gatsby-image/ but it'd be nice if it works on both — once the preview version finishes loading https://deploy-preview-4853--gatsbyjs.netlify.com/ we can check if the website version still looks good.

**Comment by pieh** [comment]
@KyleAMathews can you trigger rebuild for this PR? There was issue in master that was fixed with https://github.com/gatsbyjs/gatsby/pull/4840 but build preview for this PR already failed because of that - https://app.netlify.com/sites/gatsbyjs/deploys/5ac65cb5df99536f76036007

**Comment by KyleAMathews** [comment]
Hmm yeah, it doesn't look like we need to escape pipes for our markdown compiler (remark) as the back slashes show up now https://deploy-preview-4853--gatsbyjs.netlify.com/packages/gatsby-image/?=image

We expect people to read docs on the website so I'll close this. It's unfortunate that the markdown rendering differs sometimes.

**Pull request closed without merging**
