### PR TITLE
[starters] Add MDX to blog starter

### PR DESCRIPTION
**Pull request by thomaswangio**
## Description

The official Gatsby blog starter can be converted to MDX, but takes some extra configuration that can be tricky and current online tutorials don't address how to do it. We can include it by default for future installs of the starter blog.

This is a continuation of #18928, which I closed because I removed my original Gatsby fork.

## Related Issues

Blog post #19412 addresses this change

### CODE REVIEW

**Comment by thomaswangio** [comment]
Not sure what those why those tests are failing. 

Screen Shot 2019-11-17 at 8 25 21 PM
Screen Shot 2019-11-17 at 8 25 34 PM

**Comment by laurieontech** [comment]
Hey @thomaswangio, thanks for the PR! The team has opted not to add MDX to the core blog starter for the moment. If you want to fork the repo and create a new blog starter with MDX we'd welcome that. I'm going to close this ticket though.

**Comment by karlhorky** [comment]
@laurieontech was this decision made because of the performance concerns mentioned by @marcysutton in https://github.com/gatsbyjs/gatsby/pull/18928#issuecomment-546629339?

**Comment by laurieontech** [comment]
@karlhorky There were a few factors, but the main reasoning was to support the always use case. Not everyone will want the additions of mdx, and the blog starter is quite popular. Keeping the starter as is gives us both options and we're improving the documentation around making that change for users who want it.

**Pull request closed without merging**
