### PR TITLE
[1.0] New design + new home page 🎉

### PR DESCRIPTION
**Pull request by KyleAMathews**
Beta release prep

* Purpleize
* Start to new homepage
* New Container component so can do full width bleeds + move sidebars to
left.
* SVG icon

This is what it looks like so far. Feel free to jump in and save me from atrocious design mistakes :-P

screen shot 2017-06-14 at 12 49 16

/cc @SachaG

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit cd07afc5f6ae2398846650997e0bb0e1f4bbe71b

https://app.netlify.com/sites/gatsbyjs/deploys/5941947d3c1d5e4a61244050

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 7964301bd760fd8ce2b6b2ad7ffd607c4e7e89e0

https://app.netlify.com/sites/using-contentful/deploys/594196a63c1d5e07ef24406c

**Comment by KyleAMathews** [comment]
In another day of fragile cloud dependencies. One of the websites dependencies downloads a binary from bintray.com which is 500ing right now so the site can't build 🙄 Anyways, the first build succeeded in case you'd like to play around https://5941930e3c1d5e0b2d244062--gatsbyjs.netlify.com/

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 377cde029c42f2a649cf5488db4fe043740e2ae4

https://app.netlify.com/sites/image-processing/deploys/59419c4ea700c4086be60898

**Comment by SachaG** [comment]
I like the purple! It's just an idea (and it'll depend on the actual homepage content), but I was thinking maybe we could play around with the diagonal idea some more?

https://www.figma.com/file/J6IYJEtdRmwJQOrcZ2DfvxDD/Gatsby

**Comment by SachaG** [comment]
Ooh not a fan of that pattern…

**Comment by KyleAMathews** [comment]
Haha why the argyle hate? :-D Just playing around with patterns to liven up the purple a bit.

screen shot 2017-06-14 at 5 24 32 pm

**Comment by KyleAMathews** [comment]
Woahhh... that figma mockup is amazing.

**Comment by KyleAMathews** [comment]
Did we talk about diagonal design ideas before? Last fall? I don't remember seeing this before.

**Comment by SachaG** [comment]
I don't think so. I think it could lead to some fun transitions too, which might be a good way to showcase what Gatsby can do?

**Comment by KyleAMathews** [comment]
>it could lead to some fun transitions too

yeessss that'd be nifty.

**Comment by KyleAMathews** [comment]
Ok clearly I should stop fiddlying with the design :-) going to start mocking up the content I wrote up last night.

**Comment by KyleAMathews** [comment]
Ok, fixed the bug I introduced so the site is building again on Netlify https://deploy-preview-1170--gatsbyjs.netlify.com/

**Comment by KyleAMathews** [comment]
K, just going to merge this as is and start another issue to discuss @SachaG's design + critique what I did today. Got some urgent client work to do the next few days so got to get back to that. Will only have time to squeeze out the beta release (ugh finally).

Would love it if anyone else wanted to take up working on the website!

**Pull request merged**
