### PR TITLE
[v2][WIP] Babel 46 example

### PR DESCRIPTION
**Pull request by m-allanson**
This is a WIP look at upgrading the Gatsby repo to use Babel's beta 46. I've updated all the Babel dependencies to `babel@7.0.0-beta.46`, then attempted to update one of Gatsby's packages (`gatsby-cli`) to compile with beta 46.

Using this setup it's possible to compile the `gatsby-cli` package from the repo root:

`node_modules/.bin/babel ./packages/gatsby-cli/src --out-dir ./packages/gatsby-cli/lib --ignore **/__tests__`

But building the package from the package directory fails:

```shell
cd packages/gatsby-cli 
yarn run build
```

Output:

```shell
$ babel src --out-dir lib --ignore **/__tests__ --configFile="../../babel.config.js"
Error: SyntaxError: src/create-cli.js: Support for the experimental syntax 'objectRestSpread' isn't currently enabled (72:20):

  70 |
  71 |       let localCmd = resolveLocalCommand(command)
> 72 |       let args = { ...argv, ...siteInfo, useYarn }
     |                    ^
  73 |
  74 |       report.verbose(`running command: ${command}`)
  75 |       return handler ? handler(args, localCmd) : localCmd(args)

Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section of your Babel config to enable transformation.
    at /dev/gatsby-v2/node_modules/@babel/cli/lib/babel/dir.js:185:22
    at /dev/gatsby-v2/node_modules/@babel/cli/lib/babel/dir.js:148:23
    at /dev/gatsby-v2/node_modules/@babel/cli/lib/babel/dir.js:120:23
    at /dev/gatsby-v2/node_modules/@babel/cli/lib/babel/dir.js:82:23
    at /dev/gatsby-v2/node_modules/@babel/cli/lib/babel/util.js:126:16
    at runAsync (/dev/gatsby-v2/node_modules/@babel/core/lib/transformation/index.js:37:12)
    at /dev/gatsby-v2/node_modules/@babel/core/lib/transform-file.js:56:36
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:422:3)
error Command failed with exit code 1.
```

This looks like the `--configFile="../../babel.config.js` option isn't being picked up.

I've been digging through the various beta-46 issues on the babel repo, but I'm not sure if I'm doing it wrong or babel is doing it wrong :) 

Does this usage of the `--configFile` flag look reasonable? 

Pinging @loganfsmyth as you've left some helpful comments on other Gatsby / babel issues, I'd love to get your input on this if you have a chance.

### Alternative approach

As an alternative to the above, we could drop a `.babelrc` into every `package/` directory. I tried this approach and it worked with one exception... There are some additional `package.json` files nested [inside the `packages/gatsby/src/internal-plugins/` directory](https://github.com/gatsbyjs/gatsby/tree/ee6953baad60dbd9b66d0699a8e0087fa05edbfa/packages/gatsby/src/internal-plugins), which seems to break Babel for those directories. I assume Babel's config lookup is stopping once it finds a `package.json` file, so those files aren't being compiled with the right Babel config.

Here's an example - with a directory structure like:

```
/
  packages/
    gatsby/
      package.json
      .babelrc
      internal-plugins/
        internal-plugin-a/
          package.json
          index.js          <-- errors when babel runs here
        internal-plugin-b/
          package.json
          index.js          <-- errors when babel runs here
```

And a `.babelrc` in `packages/gatsby/` that looks like:

```json5
{
  "presets": [
    ["../../.babel-preset.js"]
  ]
}
```

Babel tries to compile the JS for the internal plugins, but doesn't pick up a config and so errors out (similar to the error message above).

These internal plugins aren't really npm packages, but they do rely on the `package.json` file existing.

### CODE REVIEW

**Comment by jquense** [comment]
I _think_ we want approach 2 for the most part (babelrc in each package). The idea was originally that babel is located locally there so that each package can build itself without needing to always participate in the repo wide tooling. One change we could make there tho is to use the `extends` keyword they added to extend the root config they all mostly share and turn the "preset" we have into a plain ol bablrc or babel.config.

**Comment by m-allanson** [comment]
Yeah approach 2 seemed to work well _except_ for the `internal-plugins` directories. I didn't spend too much time investigating that before switching to approach 1. I'll take another look.

**Comment by jquense** [comment]
yeah that's a bit tricky maybe the babel-config needs to go in the gatsby package (vs the root) for that case?

**Comment by loganfsmyth** [comment]
Yeah I was under the impression that Gatsby actually already went with the `.babelrc`-per-package approach. Seems like the most consistent with your current setup.

FYI I also just filed #5386 which I noticed while reviewing this.

**Comment by m-allanson** [comment]
Thanks both! I'm closing this and have replaced it with #5399.

**Pull request closed without merging**
