### PR TITLE
gatsby-link: add push (same as navigateTo) and replace methods

### PR DESCRIPTION
**Pull request by tremby**
This addresses #5910.

This patch adds a second argument to `gatsby-link`'s `navigateTo`, which will accept an object. If the object has a truthy `replace` member, `history.replace` is used rather than `history.push`. See the linked issue for my use case.

Since following the history API's `replace` and `push` methods (as suggested in the issue by @KyleAMathews) would be a breaking change, perhaps this is a good solution in the mean time for the 1.x line?

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Let's just add replace and push methods that do the same thing as `navigateTo` and keep `navigateTo` around  for backwards compatibility.

**Comment by KyleAMathews** [comment]
Oh, guess we can keep this open as it'd be pretty easy to modify this PR :-)

**Comment by tremby** [comment]
Should I then modify the documentation and examples to use `push`?

**Comment by tremby** [comment]
OK, while I intend to also deal with v2, it looked today like it has not yet been merged, and so I have amended this v1 patch to have push and replace methods. Let me know if you want any changes. I'll soon get to v2.

**Comment by tremby** [comment]
I've tweaked this version a little since my last comment, and I've also made a patch for v2 (PR referenced above).

**Comment by tremby** [comment]
Fixed a broken test and replaced the commit.

**Comment by tremby** [comment]
The errors in the CI build failure don't seem connected to this patch; they're about `componentDidReceiveProps` being deprecated. Is there anything I need to do?

**Comment by pieh** [comment]
Are we adding this to v1?

**Comment by tremby** [comment]
> Oh, there's a lot of conflicts actually — could you resolve those?

I can most likely do this later today.

> Are we adding this to v1?

That was the idea; see this earlier comment https://github.com/gatsbyjs/gatsby/pull/5934#issuecomment-397796828

**Comment by tremby** [comment]
Rebased on the v1 branch. I'm not sure how to change the base of this pull request to v1... I can either close this and open a new PR, or you can manually merge with v1 your end:

```
git checkout v1
git fetch git@github.com:tremby/gatsby.git navigate-to-options
git merge FETCH_HEAD
git push
```

**Comment by tremby** [comment]
Oh, in the rebase I lost your commit 999f1baa9 and I can't seem to fetch it from Github or follow the link to it above in this thread. Oops...

**Comment by tremby** [comment]
Haha, but I *can* click the link to it from the comment I just posted. Github bug, methinks. Will add it...

**Comment by tremby** [comment]
Added your readme change commit back on, and found the option to change the base for this PR. Should be ready to go.

**Comment by tremby** [comment]
@m-allanson, I actually did have something like that but it was taken out in Kyle's commit: https://github.com/gatsbyjs/gatsby/pull/5934/commits/8a8d89234b605c376866984ad8f9a9b52155add9

Doesn't matter to me either way though! Thanks.

**Comment by tremby** [comment]
...Did you mean to merge this into v1 but accidentally merge v1 into this instead?

**Comment by m-allanson** [comment]
Ah sorry for the delay, GitHub wanted me to update the branch before merging. Merging now.

**Pull request merged**
