### PR TITLE
Front matter in JS (closes #2 and #439)

### LINKED ISSUE #2: Set patterns for page files to declare metadata
Markdown has standardized on frontmatter. Don't want to force frontmatter on other file types e.g. JSX.

My proposal for the post-build is that we create a special metadata gathering webpack entry file that pulls in all pages and grabs their metadata. Each loader would need to return a `metadata` key.

### PR DESCRIPTION
**Pull request by jbolda**
Left out the tests per @KyleAMathews as the existing tests to not pass on Windows.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@jbolda thanks for making this happen! This is a pretty exciting new feature. I'll add an example for this to the starter blog after making a new release.

**Comment by jbolda** [comment]
@KyleAMathews cheers!

**Comment by KyleAMathews** [comment]
Added an example of this to the starter blog!

* http://gatsbyjs.github.io/gatsby-starter-blog/2016-12-9-react-component-post/
* https://github.com/gatsbyjs/gatsby-starter-blog/commit/e333cb1aadbba2d5053a3b471fa841b29b3187c2

**Comment by jlengstorf** [comment]
Hiya @jbolda! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
