### PR TITLE
gatsby-transformer-xml: Replace xml-parser with xml2js.

### LINKED ISSUE #11736: gatsby-transformer-xml uses unmaintained dependencies to parse xml
## Summary

`gatsby-transformer-xml` uses https://github.com/segmentio/xml-parser to parse XML, but this package is not being maintained. 
For me, it's lacking CDATA support, but without a maintainer there is no fix for me to get this working in Gatsby :(
What can we do about it?

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

### PR DESCRIPTION
**Pull request by phulin**
## Description

Replaces the unmaintained xml-parser dependency with xml2js.

## Related Issues

Fixes #11736.

### CODE REVIEW

**Comment by phulin** [comment]
This is broken; will repost when fixed.

**Comment by muescha** [comment]
You don't need to repost the PR - just commit changes to your feature branch and the PR gets updated automatic

**Comment by MadsMadsDk** [comment]
@phulin Any news on this fix? I'd be happy to help if you need it.

**Comment by wardpeet** [comment]
@MadsMadsDk Feel free to create a new PR :)

**Pull request closed without merging**
