### PR TITLE
docs(www): Add note about BEM with CSS Modules

### PR DESCRIPTION
**Pull request by sidharthachatterjee**
Adds a note mentioning that we camelize class names with dashes and its effect on in context of BEM

Fixes https://github.com/gatsbyjs/gatsby/issues/10852

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
@DSchau I definitely agree that CSS Modules + BEM shouldn't be used together! I could edit this into a more generic note about dashes being camelized but I'd guess the most _likely_ scenario a user would hit this in when trying to name classes using BEM

Maybe a good middle ground is making the paragraph generic and then adding another note below—that one ought to keep this in mind if using BEM with CSS Modules (while we certainly discourage it)

**Comment by DSchau** [comment]
> I'd guess the most likely scenario a user would hit this in when trying to name classes using BEM

What if we just _showed_ (rather than told) an example using dash-case/kebab-case, e.g. something like:

```css
.user-avatar {
}
```

import styles from './whatever.css'

// styles.userAvatar

Then it becomes apparent going through the tutorial, rather than needing to be something explicitly called out? I'm not really sold on the idea--but I think I like that better than a separate section. What do you think?

**Comment by KyleAMathews** [comment]
We don't want to add more explanations than necessary to the tutorial. There's a _lot_ of people going through it that have no idea what BEM so any clarification of BEM will likely confuse more than help.

The place for detailed clarifications like this would be a docs page on CSS Modules and not in the tutorial.

**Comment by DSchau** [comment]
@sidharthachatterjee going to close this per @KyleAMathews's comment above.

Feel free to re-open _basically this same_ PR on the CSS Modules doc instead :)

**Pull request closed without merging**
