### PR TITLE
Add multiple collections support to gatsby-source-mongodb

### PR DESCRIPTION
**Pull request by jorishermans**
I found the time to adjust the source mongodb plugin so it can handle multiple collections.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 1b23b45b446321d97cc71b7e735170aac10d3b5d

https://app.netlify.com/sites/using-glamor/deploys/59bbc8ba0752d0483bd6552f

**Comment by jorishermans** [comment]
Probably something wrong with this branch ... 
2 weeks of inactivity 

Another option is to create another topic branch and try to get these changes into that topic branch.

It is still strange that the typescript tests are failing

**Comment by KyleAMathews** [comment]
Yeah, it'd be cleaner to create a new branch off of master and apply the changes there!

**Comment by jorishermans** [comment]
Oké, I will do that.

**Pull request closed without merging**
