### PR TITLE
[1.0] SSR API changes

### PR DESCRIPTION
**Pull request by KyleAMathews**
Made the SSR APIs more "redux-y" or consistent with the rest of the API. Which also had the nice side effect of eliminating two APIs #winning 

So now you do something like the following to add components to the head/body (this is taken from a new plugin I just added while working on this for auto-integration with react-helmet):

```javascript
import helmet from "react-helmet"

exports.onRenderBody = ({ setHeadComponents }, pluginOptions) => {
  setHeadComponents([
    helmet.title.toComponent(),
    helmet.meta.toComponent(),
    helmet.link.toComponent(),
  ])
}
```

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 8e1ee871bdacf4adf0821714ea8b5d7e33496aa1

https://app.netlify.com/sites/image-processing/deploys/5930bbda6f4c5060d157d82d

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 8e1ee871bdacf4adf0821714ea8b5d7e33496aa1

https://app.netlify.com/sites/gatsbyjs/deploys/5930bbd86f4c5060d157d81c

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 8e1ee871bdacf4adf0821714ea8b5d7e33496aa1

https://app.netlify.com/sites/using-postcss-sass/deploys/5930bbda6f4c5060d157d827

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 8e1ee871bdacf4adf0821714ea8b5d7e33496aa1

https://app.netlify.com/sites/gatsbygram/deploys/5930bbda6f4c5060d157d81f

**Comment by akadop** [comment]
Could you add `helmet.script.toComponent(),` as well? It works really well when you want to pull in front matter data for schema.org script data. 

example: I have successfully used this when I was working on a gatsby project -->

```
<Helmet 
...
script={[
            {
              type: 'application/json',
              innerHTML: `{
                "@context": "http://schema.org",
                "@type": "Webpage",
                "breadcrumb": "${post.frontmatter.exam} > ${post.frontmatter.category} > ${post.frontmatter.title}",
                "name": "${post.frontmatter.title}",
                "publisher": {
                  "@type": "Organization",
                  "name": "exampaths",
                  "logo": {
                    "@type": "ImageObject",
                    "url": "https://exampaths.com/wp-content/uploads/epicon.png",
                    "width": 600,
                    "height": 60
                  }
                },
                "mainEntityOfPage": {
                  "@type": "Review",
                  "author": {
                    "@type": "Person",
                    "name": "${post.frontmatter.author}"
                  },
                  "@id": "${post.frontmatter.slug}",
                  "url": "${post.frontmatter.url}",
                  "itemReviewed": {
                    "@type": "Thing",
                    "name": "${post.frontmatter.item}"
                  },
                  "inLanguage": "en",
                  "datePublished": "${post.frontmatter.date}",
                  "description": "${post.frontmatter.seoDescription}",
                  "reviewRating": {
                    "@type": "Rating",
                    "bestRating": 5,
                    "ratingValue": "${post.frontmatter.rating}",
                    "worstRating": 1
                  },
                  "publisher": {
                    "@type": "Organization",
                    "name": "exampaths",
                    "sameAs": "https://exampaths.com",
                    "logo": {
                      "@type": "ImageObject",
                      "url": "https://exampaths.com/wp-content/uploads/epicon.png",
                      "width": 600,
                      "height": 60
                    }
                  },
                  "review": {
                    "@type": "Review",
                    "url": "${post.frontmatter.url}",
                    "itemReviewed": {
                      "@type": "Thing",
                      "name": "${post.frontmatter.item}"
                    },
                    "author": {
                      "@type": "Person",
                      "name": "${post.frontmatter.author}"
                    },
                    "inLanguage": "en",
                    "datePublished": "${post.frontmatter.published}",
                    "description": "${post.frontmatter.seoDescription}",
                    "reviewRating": {
                      "@type": "Rating",
                      "bestRating": 5,
                      "ratingValue": "${post.frontmatter.rating}",
                      "worstRating": 1
                    },
                    "publisher": {
                      "@type": "Organization",
                      "name": "exampaths",
                      "sameAs": "https://exampaths.com",
                      "logo": {
                        "@type": "ImageObject",
                        "url": "https://exampaths.com/wp-content/uploads/epicon.png",
                        "width": 600,
                        "height": 60
                      }
                    }
                  }
                }
              }
             }`,
            },
          ]}
        />
```

**Comment by KyleAMathews** [comment]
@akadop ooo nice example! I didn't realize React Helmet supported that :-) I looked at the docs and am now outputting its other types as components as well https://github.com/gatsbyjs/gatsby/pull/1085/commits/d67253fa7bf66115b97c34db7f85ff84ca2efb4e

**Pull request merged**
