### PR TITLE
Add babelrc to gatsby-plugin-netlify-cms to stop Uglify failure

### PR DESCRIPTION
**Pull request by martynhoyer**
Stops UglifyJS failing at build

As per https://github.com/gatsbyjs/gatsby/issues/4227

### CODE REVIEW

**Comment by martynhoyer** [comment]
Hah, ok... Travis fails because it wants backticks...

**Comment by pieh** [comment]
@martynhoyer you can move gatsby-browser out of `src` dir to root directory - `gatsby-browser.js` is handled by webpack during build so this should work ok.

**Comment by erquhart** [comment]
The plugin source files should remain in the `src` directory.

@KyleAMathews I see other plugins, like [jss](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-jss/src/gatsby-browser.js), having similar code and presumably not having these errors. Any thoughts on why?

**Comment by pieh** [comment]
@erquhart propably because they have this `.babelrc` - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-jss/.babelrc

**Comment by erquhart** [comment]
Ah! Good catch, thank you.

@martynhoyer would you mind updating your PR to just add that babelrc?

**Comment by martynhoyer** [comment]
@erquhart sure, that's done now.

**Comment by martynhoyer** [comment]
Not sure why the netlify check is failing, it says `gatsby not found`, but looking at the history of that Netlify deployment, it doesn't look like it's ever published successfully.

**Comment by pieh** [comment]
Don't worry about netlify "test" too much - it just fails for some examples

**Comment by TheTFo** [comment]
Is this scheduled for release?

**Comment by KyleAMathews** [comment]
Merged code is generally released immediately. Upgrade to the latest version of this package to get it.

**Comment by TheTFo** [comment]
Ugh, I apologize.  I set this up last night thinking I had the latest, but I forgot that I used netlify to deploy my site, and their seed is using 1.0.9.

Updated to 1.0.12 worked like a charm.

**Comment by jlengstorf** [comment]
Hiya @martynhoyer! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
