### PR TITLE
Added logos

### PR DESCRIPTION
**Pull request by shannonbux**
Not sure how to adjust the sizes here. I made them smaller on my computer but not sure if it worked

### CODE REVIEW

**Comment by calcsam** [comment]
@shannonbux https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown

**Comment by shannonbux** [comment]
hehe yes I need to do this for the homepage of my website.

**Comment by KyleAMathews** [comment]
@shannonbux you should resize the images on your computer to say 350px wide and then commit the new resized images.

**Comment by shannonbux** [comment]
done!

**Comment by fk** [comment]
I also had a look at this the other day and then forgot about it. :-(
Unfortunately this is a little tricky currently…

We use [gatsby-remark-images](https://www.gatsbyjs.org/packages/gatsby-remark-images/) to process images in Markdown and make them "responsive". The plugin has an option `maxWidth` which we set to `786` in https://github.com/gatsbyjs/gatsby/blob/7fa2313fb5f00f969d08dd76fc0d4fb4cffccfab/www/gatsby-config.js#L47

That value should correspond to the maximum width an image can have in our layout – as you can see in the screenshot below, our images do not get wider than ~`675px`, so we probably should adjust this value. ;-)

image

Back to topic – the important thing here is the following: If the original image source width is wide enough to fully fill that `maxWidth` (or wider that the latter), `gatsby-remark-images` will fill output the image so that it fills the available space. However when the source image width is _smaller_ than the defined `maxWidth`, it will be displayed at its _original size_. I hope this explains why @KyleAMathews recommended to just scale the image down to the size you want it to display at.

@calcsam Unfortunately the syntax referenced in https://stackoverflow.com/a/21242579/1577599 is not supported by [Remark](https://remark.js.org/) (at least not the last time I checked, and nothing wrong with that). We discussed this in #2609 a while ago.

**Comment by fk** [comment]
Added a commit that scales down those logo images. Since we at some point chose to always center images that are smaller than `maxWidth`, this is how it looks now:

image

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit d004bae1eecb60d26247813aa3981afd89e2501d

https://app.netlify.com/sites/using-glamor/deploys/5a74679892226a60b0fc0e1f

**Comment by KyleAMathews** [comment]
Thanks all!

**Comment by shannonbux** [comment]
Thanks all for helping out with this and for explaining everything, @flo!
Very much appreciated and I'll bookmark this conversation for my future
reference.

**Pull request merged**
