### PR TITLE
Add line numbers to prismjs plugin

### PR DESCRIPTION
**Pull request by phacks**
Hi! First time contributor, please feel free to tell me how I can improve the PR 😊

This PR adds the ability to show line numbers for code blocs using the PrismJS line number plugin.

See example:

image

This relates to the issue https://github.com/gatsbyjs/gatsby/issues/5775.

~~Oops, just realized that it didn’t work well with highlighted lines, I’ll try to take another look at this soon!~~ Edit: fixed! 🎉

image

### CODE REVIEW

**Comment by jasperjn** [comment]
I created a PR https://github.com/phacks/gatsby/pull/1 remove build version file from the source control. Thank you.

**Comment by m-allanson** [comment]
Another thought.. This PR enables or disables line numbering for a whole site. It might be useful to specify line number for individual blocks, and also the starting line number for a block? I'm not sure what the best way to do that, maybe similarly to the line highlighting syntax?

Number lines, starting from 1:
```
 ```js{6-8}{numberLines: true}
```

Number lines, starting from 5:
```
 ```js{6-8}{numberLines: 5}
```

Thoughts?

**Comment by phacks** [comment]
Hi @m-allanson! Thanks for the feedback. I’ll be looking into the layout issues and the possible enhancements, hopefully in the next few days 😊

**Comment by phacks** [comment]
I fixed the issue on `using-remark` and added the featured your suggested @m-allanson !

The issue was caused by this padding overwriting the `prism-line-numbers.css` stylesheet : 

https://github.com/gatsbyjs/gatsby/pull/5821/commits/a2a308e453c1d4e173490960a0d4933b6c83d9d0#diff-2e101cb7175492ace9066869ab398490L135

Removing it doesn’t impact the code block style, so I went with it — what do you think!

**Comment by phacks** [comment]
It looks like recent Travis builds are failing with an obscure versioning error:

image

Would you have an idea on how to fix it?

**Comment by pieh** [comment]
@phacks this is something I introduced and need to fix! Sorry for disturbance

**Comment by phacks** [comment]
@pieh It’s fixed! Many thanks 😊

**Comment by phacks** [comment]
Just tried to rebase to master and it broke the code blocs layout again… Back to the drawing board!

**Comment by phacks** [comment]
…aaand it’s fixed again!

image

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit ae322e49327f4e246fb3ca6ca770acea40658722

https://app.netlify.com/sites/using-glamor/deploys/5b34c83e792f890837b26292

**Comment by phacks** [comment]
@m-allanson I updated the branch to be up to date with `master` and the tests are passing now, so if you want to take another look at the PR please do so :) Thanks 😊

**Comment by phacks** [comment]
@m-allanson Do you think you may have some time in the next few days to have a look? I’m looking forward to land the feature 😃

**Comment by phacks** [comment]
@KyleAMathews maybe you can have a look? Thanks!

**Comment by m-allanson** [comment]
Thanks @phacks, apologies for the delay! This looks good 👍 However it looks like there's some unrelated files that have been added to this PR? There's various files added to the `packages` directory. Can you remove them?

**Comment by phacks** [comment]
@m-allanson Fixed, thanks! I think I made a mistake somewhere while migrating the branch to `v2` 😅

**Comment by phacks** [comment]
@m-allanson @KyleAMathews Hi! Small reminder that I updated my PR and it should be ready to go! Thanks 😊

**Comment by phacks** [comment]
@m-allanson @KyleAMathews Hi! This PR should be ready for you to review and merge, many thanks!

**Comment by m-allanson** [comment]
Thanks for the reminders @phacks, sorry you had to wait so long on another review for this. 

I ran through another check, and generally things look good 👍 However, I noticed one issue that will need fixing. It seems that this change adds extra padding around all code blocks, which it  shouldn't do. Here's a couple of screenshots with this PR on the left, and the currently live example site on the right:

screen shot 2018-08-01 at 10 50 33
screen shot 2018-08-01 at 10 51 10

It seems there's extra padding on all sides of the code blocks. Could you fix that up to match the padding on the live example site? Apologies in advance if this is an annoying CSS specificity thing! 

Hopefully fixing this will remove some of that large gap to the left of the line-numbers which should look a bit neater too. Please drop any questions here if you have them, I'll endeavor to get to them more quickly this time 😅

**Comment by phacks** [comment]
@m-allanson @KyleAMathews How did I miss that 😅Should be better now, as you can see:

image
image

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 53eae6e1667ed48cdb5160dce6520f5a491b24f1

https://app.netlify.com/sites/using-postcss-sass/deploys/5b61d3ecc9659221ab5dfd4a

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 53eae6e1667ed48cdb5160dce6520f5a491b24f1

https://app.netlify.com/sites/gatsbyjs/deploys/5b61d3eac9659221ab5dfd3e

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit a5cc8692becad32d248838dbcec72fd98e6f3991

https://app.netlify.com/sites/gatsbyjs/deploys/5b61d56b3813f07962d6ff19

**Comment by phacks** [comment]
@m-allanson @KyleAMathews Sorry if I come off as a little bit pushy — do you think you can have another look (and hopefully the last one!) at this PR, now that I fixed the CSS padding problem? Many thanks! 😊

**Comment by m-allanson** [comment]
Hey @phacks, don't worry that's not pushy, it's good to get reminders sometimes! I want to get back to this as soon as I can, but it's looking like that'll be early next week. Sorry for the delay and thanks again for your patience.

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit 4ad949f94467162eca6ca33e19bbeb00ed016f5b

https://app.netlify.com/sites/using-contentful/deploys/5b72cd17c96592769c14159b

**Comment by m-allanson** [comment]
This has been published as `gatsby-remark-prismjs@3.0.0-beta.6`

**Pull request merged**
