### PR TITLE
Added Wire website to be featured

### PR DESCRIPTION
**Pull request by teller**

### CODE REVIEW

**Comment by lipis** [comment]
Something is wrong with this PR: https://www.gatsbyjs.org/showcase/nullwire.com

`null/wire.com`?? 

and when I click on the visit site it takes me to https://www.gatsbyjs.org/wire.com, which is a 404

**Comment by fk** [comment]
Argh, thanks for the heads up @lipis! 🙏
Will fix the URLs ASAP!

**Comment by teller** [comment]
Here's a higher resolution screenshot. The current one looks a bit blurry on retina displays.
wire com

**Comment by lipis** [comment]
@fk can we update the preview image with the one from @teller?

**Comment by lipis** [comment]
I don't think that this could fix it.. it's the platform that renders it that way.

**Comment by fk** [comment]
:/ 🙏

**Comment by fk** [comment]
I see, system font stack. Dang.

**Comment by DSchau** [comment]
> the platform

🙃

**Comment by teller** [comment]
We promise not to show it to our designer :)

**Pull request merged**
