### PR TITLE
refactor(www): Organize components in dot-org based on use

### LINKED ISSUE #21331: (www) Organize components in dot-org by section
## Description

Organize the many components of the site based on the section that they fall under.

## Motivation

The components library is very big and disorganized, making discoverability difficult. A lot of components are specific to certain paths (like `showcase-details`) but are dumped into the main `components` directory. In addition, filtering out section-specific components will be beneficial for [splitting the site up into themes](https://github.com/gatsbyjs/gatsby/issues/19105)

## Steps

The following is an (incomplete) lists of components that could be factored into subfolders. The refactor of each section should be in its own pull request.

layout/ - should contain layout components common to all pages

* layout
* site-metadata
* banner
* skip-nav
* navigation
* navigation-mobile
* search-form/
* footer links

homepage/

* card-headline
* card
* diagram
* futura-paragraph
* masthead

docs/ - should contain things in the docs, tutorial, contributing, and features pages

* api-reference/
* sidebar/
* page-with-sidebar
* docs-breadcrumb
* docs-table-of-contents
* markdown-page-footer

blog/

* pagination/
* avatar
* blog-post-preview-item
* tags-section

packages/ or plugins/

* gatsby-monogram
* package-readme
* page-with-plugin-searchbar
* plugiin-searchbar-body
* rotator
* slider

showcase/

* showcase-details

creators/

* creator-data (this is just a graphql fragment)

In addition, the src/views directory can probably be folded into src/components. There really isn't a distinction between "components" and "views".

ecosystem/

* layout-with-heading
* page-heading

## Related Issues

Part of: #19105

### PR DESCRIPTION
**Pull request by DallasGale**
## Description

Re-organized the www/src/components/* files to be grouped into new & existing sub-folders. 

## Related Issues

Fixes #21331
Related to #19105

### CODE REVIEW

**Comment by DallasGale** [comment]
Hey @tesseralis Just checking in about this PR. It looks like the conflicts need to be resolved on your end ?

**Comment by DallasGale** [comment]
Hey @tesseralis. Is there anything I need to do to help get this one over the line? The Resolve conflicts button is disabled for me so I cant resolve the conflicts.

**Comment by tesseralis** [comment]
Hi @DallasGale, unfortunately it seems like there has been enough conflicts here that it might just be easier to start from the beginning. As a suggestion, I think it would be better to make smaller PRs, one for each folder/section. This will make it easier for us to review the PR and get it merged in, and reduce the chance of conflicts happening.

**Comment by tesseralis** [comment]
Since this branch has fallen out of step with master and has too many conflicts, I'll close it out for now. @DallasGale if you'd like to reimplement this PR per my suggestion (separate PRs for each section) we would welcome your contribution!

**Pull request closed without merging**
