### PR TITLE
feat(gatsby-plugin-sharp): Use file streams instead of file paths

### PR DESCRIPTION
**Pull request by LekoArts**
## Description

Converts sharp usage based on file paths to file streams, e.g.

```js
// Before
const imgStats = await sharp(file.absolutePath).stats()

// After
const pipeline = sharp()
fs.createReadStream(file.absolutePath).pipe(pipeline)
const imgStats = await pipeline.stats()
```

For the writing of files we use `sharpPipeline.toBuffer() + fs.writeFile()` for now. We probably will change it to filestream in future PR (will just need to revert https://github.com/gatsbyjs/gatsby/pull/33029/commits/31cfaf32663fb945a8d983227493e6f5f24761a0).

Running the `image-processing` benchmark didn't show any major speed improvement/degradation

## Related Issues

[ch37488]

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Nice! Might reduce memory usage perhaps depending on how Sharp does things

**Comment by wardpeet** [comment]
@LekoArts & @pieh by making `queueImageResizing` and others async, doesn't this break the contract with plugins like gatsby-plugin-sqip? Should we go to a git patch instead to not break this in master?

**Comment by LekoArts** [comment]
Good point, we also use the function in `gatsby-transformer-sharp`. I think we'll want to keep the behavior but then we need to do git patch / adjust more

**Comment by pieh** [comment]
I reverted async change to `queueImageResizing` from this PR - breaking contract with it is valid reason to do so. I still think overall it would be beneficial for it to be async, but it doesn't really belong to this PR. Potential way to move forward with it (in another PR) would be introducing `queueImageResizingAsync` variant, updating plugins we maintatin to use and keeping old sync one (and deprecating that one) to not cause too much problems for 3rd party plugins that might rely on it today.

**Review by wardpeet — APPROVED** [review]
LGTM!

**Pull request merged**
