### PR TITLE
Add a github lint action

### PR DESCRIPTION
**Pull request by pvdz**
Adds a Github Actions lint bot that can post lint results inside a PR :)

### CODE REVIEW

**Comment by pieh** [comment]
I think workflow has to be in `.github/workflows` ( https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#creating-a-workflow-file )

**Comment by pvdz** [comment]
Alright. A million attempts later we have a lint bot, that is part of this repo (this PR right now), all local. It will report only errors and suppresses lint rules that are basically duplicates between eslint/prettier/TS (just one right now but we'll probably want to expand on that list quickly).

I wish we had more control on the output. Honestly, who cares about the file+line number when it's inline. And there is a lot of space being dedicated to the "action" part. But whatever. Room for improvement. Hopefully we won't see these messages at all #trollolloll

So if the concept is good I'll remove the example changes to packages/gatsby-cli/src/index.ts and change the location to point to `master`, instead of a commit on this branch, and we should be good to go.

What say you, @pieh?

**Comment by pvdz** [comment]
Hm, I'm not sure how to prevent the duplicate check in the list here ... Maybe the name has to match exactly the `report_eslint_action`?

image

**Comment by pieh** [comment]
There is also builtin github action thing, so instead of the dedicated action that explictely create notifications:

https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md

this should solve 2 different checks

I don't think using single name would solve this - in eslint-action we explictely create new "check_run" - and those are identified by `ids` and not by names. So I expect if we change the name we would still have 2 checks - just with the same name

**Comment by pvdz** [comment]
I give up :(

**Pull request closed without merging**
