### PR TITLE
feat(gatbsy-starter-blog): draft implementation

### PR DESCRIPTION
**Pull request by kingingcole**
## Description

This should give the developer and blog owner the ability to save posts as draft by just setting published variable to false. 

## Related Issues
None I could find.

### CODE REVIEW

**Comment by wardpeet** [comment]
Thank you for your work on this PR.

Unfortunately, we're not going to merge this at this time. We want our starters to be as simple as possible. Adding draft makes it a little bit more complex. We're currently looking into adding extensions to gatsby-theme-blog to make it possible to add functionalities.

Feel free to create your own gatsby-starter-blog with draft functionality and publish it to our list of starters at https://gatsbyjs.org/starters

As such--we're going to close this out. We want you to know that we certainly want to keep you as a contributor to Gatsby, so we'd encourage you to check out our open issues.

Thanks again, and we look forward to seeing more PRs from you in the future! 💪 💜

**Comment by kingingcole** [comment]
I thought it'd be merged. I seriously wanted Gatsby swag 😔

**Comment by sidharthachatterjee** [comment]
@kingingcole Check out issues tagged with _good first issue_ or _help wanted_ to make your first contribution. We'll look forward to it! You belong here 💜

**Comment by kingingcole** [comment]
Do I get a swag for those ones too? 😀

**Comment by sidharthachatterjee** [comment]
Of course! You’ll get swag on your first merged contribution @kingingcole

**Pull request closed without merging**
