### PR TITLE
Fix 404 page flashing when using a service worker

### LINKED ISSUE #5459: 404 page flashing
## Description

When visiting a link that doesn't exist on a Gatsby site, the page flashes a couple of times as it's rendering the 404 page.

### Steps to reproduce

You can reproduce the issue in the gatsby.org site. Visit: https://www.gatsbyjs.org/flashing which is an invalid link.

### Expected result

404 page should just render like other pages with no flashing.

### Actual result

Safari flashes maybe once, Firefox continues to flash as if it was continuously refreshing the page, and Chrome flashes a couple of times.

### Environment
* Gatsby version (`npm list gatsby`):
* gatsby-cli version (`gatsby --version`):
* Node.js version: 
* Operating System: 

### File contents (if changed)
`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

### PR DESCRIPTION
**Pull request by ijjk**
When using a service worker and a 404 route is hit the service worker doesn't know about the path so it tries to refresh causing the page to flash. So I fixed this by doing a simple check to see if the 404 page was served. Fixes #5459 

Also, to test this using the `gatsby serve` command I had to create a serve.json file with a rewrite for the 404 path since serve doesn't automatically serve the 404 route. I added the serve.json file I used below just in case it's needed for testing.   

``` 
{
  "rewrites": [
    { "source": "/tst", "destination": "/404" }
  ]
}
```

### CODE REVIEW

**Comment by pieh** [comment]
Hey, 
first of all - sorry for delayed reply.

We can test this using PR preview here - https://deploy-preview-5616--gatsbyjs.netlify.com/defenitely-not-existing-page

Instead of checking for `<link rel="preload" ... >` I think we could add more descriptive attribute when we render html - here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/static-entry.js check if we are rendering 404 page and add some htmlAttributes or bodyAttributes and check for that.

**Comment by ijjk** [comment]
Using the bodyAttributes is a good idea it seems like a lot cleaner solution. I updated my branch using that by setting an id of "is404" when rendering the 404 path and checking if that id exists instead of looping through the preload links.

**Comment by KyleAMathews** [comment]
Deploy preview for *using-remark* failed.

Built with commit 30f060254719ee94df48fa0205d55570387680f7

https://app.netlify.com/sites/using-remark/deploys/5b619708c6aed6132e762f7d

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 30f060254719ee94df48fa0205d55570387680f7

https://app.netlify.com/sites/gatsbyjs/deploys/5b619705c6aed6132e762f5f

**Comment by davidbailey00** [comment]
This is now fixed in #7355.

**Pull request closed without merging**
