### PR TITLE
chore(showcase):Added source URL to portfolio site

### PR DESCRIPTION
**Pull request by jakeherp**
## Description

Adding source URL to github repo for portfolio site.

### CODE REVIEW

**Comment by Ekwuno** [comment]
> Since it's a showcase everything is fine!!

Not exactly, we ask that showcases have a detailed `README.md`. So as to provide more information about the site.

**Comment by jakeherp** [comment]
@Ekwuno I've added some content to my README: https://github.com/jakeherp/portfolio/blob/master/README.md

**Comment by Hyraze** [comment]
> > Since it's a showcase everything is fine!!
> 
> Not exactly, we ask that showcases have a detailed `README.md`. So as to provide more information about the site.

What if the source_url is not given? :thinking:

**Comment by jakeherp** [comment]
@Ekwuno do you mind giving this another CR and let me know if this meets the requirements now? Thanks!

**Pull request merged**
