### PR TITLE
feat(gatsby-source-graphql): Default Apollo Link fetch wrapper to show better API errors

### PR DESCRIPTION
**Pull request by antoinerousseau**
## Description

When the source GraphQL API responds with an error (4xx/5xx), the default behavior is to try to read the response body anyway, which is, in case of errors, often unrelated JSON, or HTML, or empty.
In these cases, we throw an error showing the HTTP response code and status text, which is much more relevant.
The user is still free to override the default `fetch` wrapper anyway.

### Documentation

https://www.gatsbyjs.com/plugins/gatsby-source-graphql/#how-to-use
https://www.apollographql.com/docs/link/links/http/#fetch-polyfill

## Related Issues

#10487
#20892
#28766

## Notes

We could add more logging by passing the `reporter` to the wrapper and add some `reporter.verbose(...)` for stuff like the response body or the request body, but it might be better to leave that to the user since it can write its own fetch wrapper anyway.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks for the PR! Looks like a test needs updated https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/55837/workflows/c9813a24-52f9-4308-b7c2-1779939215dc/jobs/589688

**Comment by vladar** [comment]
I've updated those failing tests

**Review by vladar — APPROVED** [review]
Nice improvement, thanks!

**Review by KyleAMathews — APPROVED** [review]
Thanks!

**Comment by antoinerousseau** [comment]
Wow great, that was fast, thanks!

**Comment by hendis85** [comment]
> Terima kasih untuk PR! Sepertinya tes perlu diperbarui https://app.circleci.com/pipelines/github/gatsbyjs/gatsby/55837/workflows/c9813a24-52f9-4308-b7c2-1779939215dc/jobs/589688


[https://t.me/Hendisutrisno85](url)

**Pull request merged**
