### PR TITLE
Omit localized nodes which are missing required fields

### LINKED ISSUE #4170: [gatsby-source-contentful] Do not include localized nodes when required fields are not translated
## Description

It would be great if we could ask that localized nodes should not be included, if required fields in contentful are not localized. I know that there is an option to make localized fields required, but that would required all pages to be translated. What I would like to have is the ability to translate some pages, but not all, but then not include the ones I didn't yet translate in the response.

Is this currently possible? If not, please consider this a polite feature request :)

### PR DESCRIPTION
**Pull request by anjawaldbauer**
⚠️ Unfortunately, this fix does cause issues with nodes pointing to other nodes which have been filtered out by this fix. I would love to discuss with some of the maintainers how to fix this properly.

**Update**: It looks like this is caused by another bug: If a referenced entry has localized fields but the referencing entry has not, a reverse reference is nonetheless created to the localized `id` for the referencing entry, which does not exist.

---

Fixes #4170, at least to the extend possible in a plugin (as far as my understanding goes). The remaining issue is that when data is cached in `.cache`, the `sourceNodes` function (which is the caller of the `createContentTypeNodes` function fixed here) is not called and thus corrupt localised nodes can still produce errors in builds. However, if you delete your cache before applying this fix, the problem should be solved.

The problem being solved being:
* contentful has required fields which cannot be omitted when creating/updating an entry
* this does not apply to non-default locales if a certain setting is not checked; this is useful to progressively translate pages of a large site
* if a page is not (yet) translated (completely), the localised not for this page should be omitted

This fix should be applicable to `v2` branch mutatis mutandis.

I am looking forward to your feedback. 🙂

### CODE REVIEW

**Comment by anjawaldbauer** [comment]
@KyleAMathews mentioning you, because I don't know who else to ask. It seems to me there is some deeper issues with this source plugin and I'd like to contribute to making it better. If anyone who has worked on this before could get me up to speed, I would really appreciate it. It is just very hard for me to dig into the code and discover one pitfall after another because I'm not familiar with the underlying concepts and cannot find any documentation on it. I am talking about nodes, resolvables, foreignReferenceMaps and the handling of ids in particular. Thanks in advance!

**Comment by KyleAMathews** [comment]
I wonder if this PR might have fixed your problem? https://github.com/gatsbyjs/gatsby/pull/4480

If you're struggling with a PR, the easiest way to get help is to build a small site reproducing the problem so someone can jump in and quickly see what's going wrong.

**Comment by anjawaldbauer** [comment]
@KyleAMathews Thanks for responding so quickly. Unfortunately, it seems I didn't make the problem clear. The PR #4480 fixed a different problem. I will create an example site, but it's difficult to test because you need to know the backend contentful content model that goes with it. The problem I am trying to solve can be reproduced with the following 5 step setup:

1. Use contentful with one additional locale, two in total.
2. Set fallback locale to None for the non-default locale.
3. Enable locale in response, editing for this locale and allow empty fields for this locale:

screen shot 2018-03-14 at 07 58 08

4. Create a `Navigation` content type that has a `links` field which has many references of type `Link`:

screen shot 2018-03-14 at 07 59 24

Note that `Navigation` has no localized fields.

5. Create a `Link` content type that has a `title` field which is a required and localized field:

screen shot 2018-03-14 at 08 01 34

screen shot 2018-03-14 at 08 01 45

This setup allows me to have a navigation managed in contentful where individual links of that navigation may or may not be translated. The navigation itself is obviously not localized, because it is just a list of references. Unfortunately, `gatsby-source-contentful` still creates a node for the navigation in the non-default locale and create references (`__NODE`) from the localized `links` to  the non-existent localized navigation. As my fix in this PR tried to filter out completely empty, i.e. not translated localized nodes, there is no node for the localized navigation anymore and that causes a TypeError when that node is accessed. 

There are several ways I can think of fixing this:
* make sure that the completely empty localized nodes are omitted from the resolvable set also
* make sure that when entries are created for each locale, empty nodes are filtered out at that stage before they can even end up in the resolvable set
* keep locales together on a node instead of splitting entries up into one node per locale

I have no idea which is better or more feasible, but any guidance would me much appreciated. Please let me know if my problem description is understandable. Thanks again!

**Comment by anjawaldbauer** [comment]
Unfortunately it seems like localization (at least with contentful and at the scale that I need it) has not be solved in gatsby. I will come up with a workaround and may return to this in the future.

**Comment by KyleAMathews** [comment]
Ok! Would love to see a fix for this @anjawaldbauer. Perhaps @Khaledgarbaya might have an idea how this could be solved.

**Comment by Khaledgarbaya** [comment]
Hey, Sorry I was off for some days.
Unfortunately, the fallback locale feature won't work mainly because the source plugin uses the syn api which does not support the fallback locale. This needs to be done either SDK side or the plugin side.
I will try to allocate some OSS time soon to tackle this issue and others with the plugin and I am happy to give direction on how to approach this also.

**Pull request closed without merging**
