### PR TITLE
♻️Use new createContentDigest helper in gatsby-transformer-toml

### PR DESCRIPTION
**Pull request by charlyx**
## Description

Hi again 👋

This PR makes use of the new createContentDigest helper in gatsby-transformer-toml.
I also have updated the related tests.

## Related Issues

Related to #8805

### CODE REVIEW

**Comment by wardpeet** [comment]
@charlyx I updated your pr to fallback to crypto when it's people are still on an old gatsby as it is technically a breaking change.

**Comment by charlyx** [comment]
Hi @wardpeet, thanks for your review!

I feel a bit concerned though.
Unless I'm wrong, that is not what has been done in other plugins...
Shall we add this fallback everywhere?

**Comment by wardpeet** [comment]
i'm waiting for @gatsbyjs/core to respond on this one as I'm unsure myself but I can't find any other `createDigestContent`in our code when I search in vscode 🙈 .

**Comment by wardpeet** [comment]
Rolling back my changes as we consider this not a breaking change and we have some warnings in place to let people know how to deal with this.

Thanks a bunch for your PR! 💪

**Comment by charlyx** [comment]
@wardpeet Cool! I'll merge my PRs into one as suggested by @DSchau 😄 
Thanks again for your review!

**Comment by charlyx** [comment]
changes moved to #12973

**Pull request closed without merging**
