### PR TITLE
Add serve command in cli

### PR DESCRIPTION
**Pull request by alehlopeh**
I needed to preview the output of ```gatsby build``` before deploying, so I added a serve command to the cli. Pretty basic.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Interesting... I've just been using http-server so hadn't seen a need but I
can see the value of having something built-in. What are other's thoughts?

I think the name "serve" is a bit ambiguous as it would get confused
sometimes with the "develop" command.

**Comment by KyleAMathews** [comment]
I merged this new command and renamed it to `serve-build`. Thanks!

**Comment by alehlopeh** [comment]
Cool. The name I chose was pretty weak, I'll admit, but I'm glad you found it useful enough to merge.
Great work on gatsby btw. I use it a lot.

**Comment by KyleAMathews** [comment]
Definitely a useful idea and great code. Glad Gatsby has been helpful!

**Comment by jlengstorf** [comment]
Hiya @alehlopeh! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
