### PR TITLE
Add Support for Development Middleware

### PR DESCRIPTION
**Pull request by nathanforce**
Provides a solution for #4812 #4797 #2869 

As mentioned by @KyleAMathews in #4797, Create React App is considering exposing proxy configuration via proxy.js.  Gatsby could take a similar approach to maintain familiarity between the two projects, but I felt that since Gatsby already exposes configuration to the user via `gatsby-config.js`, the approach might be overkill.

Let me know what you think!

### CODE REVIEW

**Comment by m-allanson** [comment]
cc: @cball may be interested in this too.

**Comment by cball** [comment]
@m-allanson indeed I am. Things got really busy for me this week so happy to see @nathanforce was able to get something going!

**Comment by nathanforce** [comment]
@m-allanson Yep you've got it right.

**Comment by m-allanson** [comment]
I think this looks good, let's see if @KyleAMathews has any thoughts before it goes in.

**Comment by KyleAMathews** [comment]
My reservation about this PR is the API is intimately connected to Express — we've never exposed Express in the past so with this we're making changing from Express to something else a breaking change. Which is probably fine — Express is ubiquitous after all. And has great middleware like the proxy in the demo.

Thoughts?

**Comment by nathanforce** [comment]
@KyleAMathews That's definitely something I considered as well.  I put some (admittedly brief) thoughts into it but wasn't able to come up with a preferable api. Happy to hear the thoughts of others on this.

**Comment by m-allanson** [comment]
What about condensing the config a little, so that `app.use()` isn't included? The example might change from this:

```js
module.exports = {
  middleware: app => {
    app.use(
      "/.netlify/functions/",
      proxy({
        target: "http://localhost:9000",
        pathRewrite: {
          "/.netlify/functions/": "",
        },
      })
    )
  },
}
```

To something like this:
```js
var proxy = require("http-proxy-middleware")

module.exports = {
  proxyPath: "/.netlify/functions/", // optional?
  proxyCallback: proxy({
    target: "http://localhost:9000",
    pathRewrite: {
      "/.netlify/functions/": "",
    },
  })
}
```

With a note that the callback will be applied as an [application level middleware function](https://expressjs.com/en/guide/using-middleware.html#middleware.application).

That doesn't really solve the problem of exposing Express, but at least its internals are slightly less visible. If you did want to change from Express, this might be easier to manage.

**Comment by KyleAMathews** [comment]
After mulling on this another day — I'm fine with exposing Express. It's super ubiquitous and will be for the foreseeable future. And that it has lots of high-quality plugins makes it more attractive than requiring people to build their own logic.

**Comment by dangerbot-gatsby** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  
Gatsby requires contributors to sign each commit.

You can do this for your branch with `git rebase --signoff`, or for a single commit with `git commit --amend -s`.

Check out the [Developer Certificate of Origin docs](https://www.gatsbyjs.org/docs/how-to-contribute/#developer-certificate-of-origin) or comment here if you've any questions.

  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by jlengstorf** [comment]
Hiya @nathanforce! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by nathanforce** [comment]
Hey @jlengstorf thanks for reaching out.  I actually already grabbed a nice bright purple t-shirt from the Gatsby Swag Store when y'all mentioned it on twitter last summer. Appreciate the follow up though!

**Pull request merged**
