### PR TITLE
Fix a bug with gatsby-browser.js not loading in production

### LINKED ISSUE #6759: [v2] Investigate why gatsby-browser.js isn't loaded in production without a stub function
This issue was split off of #5997 to track a separate bug.

Here is the relevant conversation:

@mquandalle:
> I spent a lot of time trying to solve this apparently simple issue and I didn't think of gatsby-browser.js, happy to find there is such a simple solution! But you're right that this definitely needs to be documented.
> 
> So apparently adding the import line isn't enough for the file to be executed in the browser (and the style to be loaded) and we need to add a stub like exports.onClientEntry = () => {};. If the goal is to have gatsby-browser.js be a main.js for the client maybe this behavior should be changed?

@KyleAMathews:
> Oh... hmm that's odd. I'll look into this soon-ish then.

@KyleAMathews:
> Also welcome anyone else who wants to investigate why gatsby-browser.js isn't loading css

@chasemccoy:
> @KyleAMathews I am also being affected by this. My fonts are loading many times and flashing on load in production.
> 
> @mquandalle did you find a way to get this to work in gatsby-browser.js? You mentioned a stub.

@chasemccoy:
> @mquandalle Actually, I was just able to get this to work. Putting this (and only this) in gatsby-browser.js worked for me and loaded all of the appropriate packages and files:
> 
> require("./src/styles/index.scss");
> require("./src/fonts/fonts.css");
> require("svgxuse");
> Edit: This worked on dev, but not in production...
> 
> Edit 2: Ah yes, I understand now. The shim (exports.onClientEntry = () => {};) is required for this to work introduction. Works fine in dev without the shim.

@ahlusar1989:
> @KyleAMathews Would you still like someone to look into why gatsby-browser.js isn't loading css (production)?

@KyleAMathews:
> That'd be great!

### PR DESCRIPTION
**Pull request by tryzniak**
Hey folks. I think I've got it. This PR fixes #6759. Now we always import the default browser plugin, because I may have styles imported.

Closes #6759 .

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit e45b29b5cff25506dc00744d992e335407658808

https://app.netlify.com/sites/using-postcss-sass/deploys/5b656c3b4ed62f75e0f8611d

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit e45b29b5cff25506dc00744d992e335407658808

https://app.netlify.com/sites/image-processing/deploys/5b656c3c4ed62f75e0f86123

**Comment by KyleAMathews** [comment]
Deploy preview for *using-jss* failed.

Built with commit e45b29b5cff25506dc00744d992e335407658808

https://app.netlify.com/sites/using-jss/deploys/5b656c3f4ed62f75e0f86144

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit e45b29b5cff25506dc00744d992e335407658808

https://app.netlify.com/sites/using-glamor/deploys/5b656c3c4ed62f75e0f86126

**Comment by KyleAMathews** [comment]
Deploy preview for *using-styled-components* failed.

Built with commit e45b29b5cff25506dc00744d992e335407658808

https://app.netlify.com/sites/using-styled-components/deploys/5b656c3c4ed62f75e0f86129

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit e45b29b5cff25506dc00744d992e335407658808

https://app.netlify.com/sites/using-contentful/deploys/5b656c3d4ed62f75e0f8612c

**Comment by tryzniak** [comment]
Ooops, there are a lot of preview fails...

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit e45b29b5cff25506dc00744d992e335407658808

https://app.netlify.com/sites/gatsbyjs/deploys/5b656c3a4ed62f75e0f86111

**Pull request merged**
