### PR TITLE
Adding bootstrap CV starter

### PR DESCRIPTION
**Pull request by mhjadav**
Add bootstrap based template to list of starters

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit ac6b72271585d6d3aab1726f28c35efdeda6acd7

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6ca8e782d3f15c7e38aa8a

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit ac6b72271585d6d3aab1726f28c35efdeda6acd7

https://app.netlify.com/sites/gatsbyjs/deploys/5b6ca8e482d3f15c7e38aa82

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 74ef7cc321b270358de999ec4d24b64ff45d7453

https://app.netlify.com/sites/gatsbyjs/deploys/5b6caa01fdd72a7c9c1cfdf4

**Comment by mhjadav** [comment]
Sorry, i have created this PR by mistake, very sorry.

**Pull request closed without merging**
