### PR TITLE
fix extract-text--webpack-plugin instance reuse errors

### PR DESCRIPTION
**Pull request by erquhart**
Gatsby reuses the main extract-text-webpack-plugin instance across webpack.config.js. The [docs](https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/webpack-1/README.md#api) for the plugin state that separate instances should be created for multiple loaders, and doing so fixed one Netlify CMS implementor's experience of #1043.

May address #1043, but should be community tested before closing.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Ah cool! Looks good / makes sense. Seems like a pretty safe change so I'll pull it in and release it.

**Comment by pie6k** [comment]
Is it released to npm? @KyleAMathews ?

**Comment by erquhart** [comment]
Yep, 1.9.165: https://github.com/gatsbyjs/gatsby/commits/gatsby%401.9.165

**Comment by dirtyredz** [comment]
This fixed my issue thanks, I had to manually run a npm install to get the latest version.
gastby new
doesnt settup the src with the latest version.

**Pull request merged**
