### PR TITLE
Update README.md with Calpa's Blog

### PR DESCRIPTION
**Pull request by calpa**
Thank you Kyle! I use Gatsby to rebuild my blog. The source code is also released so that other developer may find this is useful as a blog system.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks for sharing!

**Comment by KyleAMathews** [comment]
It looks like some links aren't working though?

**Comment by calpa** [comment]
@KyleAMathews Which links?

**Comment by KyleAMathews** [comment]
E.g. the frontpage links to https://calpa.me/2017/08/30/react-markdown-render-markdown-as-component/ which doesn't exist

**Comment by calpa** [comment]
@KyleAMathews Oops... I hope I can fix this problem...

**Comment by calpa** [comment]
Fixed with thanks.

**Comment by jlengstorf** [comment]
Hiya @calpa! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by calpa** [comment]
@jlengstorf Thank you

**Pull request merged**
