### PR TITLE
chore(gatsby): upgrade webpack

### LINKED ISSUE #15775: upgrade webpack version
## Description

Gatsby fix webpack version at `~4.28.4` in [this commit](https://github.com/gatsbyjs/gatsby/commit/f460b7f59f3e2a71c9ca65276a3e2f0d2c9a7fef), because [there is an regression in webpack 4.29](https://github.com/webpack/webpack/issues/8656).
But now that regression is fixed. It should be ok to use `4.35.x` or later.

Some newer plugin expect [webpack's finishModules hook](https://github.com/webpack/webpack/blob/37d4480382d362a6f44325f13b2f728ef6f1bfb1/lib/Compilation.js#L242) to be `AsyncSeriesHook`. But in webpack~4.28.4, [it is a SyncHook](https://github.com/webpack/webpack/blob/fdb6b139b94273e5b18870262c193a93f65132e8/lib/Compilation.js#L242), which will complain `tapPromise is not supported on a SyncHook` and cause a build failure.

### Expected result

We should use newer webpack version.

### Actual result

Webpack version is fixed at `4.28.x`.

### Environment

all

### PR DESCRIPTION
**Pull request by wardpeet**
## Description
Upgrades webpack to the latest again so we can remove the mjs hack. It got fixed by webpack upgrading to acorn@^6.

I've linked an issue below that seems to have issues with webpack 4.29.0 on npm. I've tried reproduce it with their repo's and npm versions but sadly no way for me to reproduce.

To let people test I created a gatsby version on npm. `npm install gatsby@webpack-acorn`

## Related Issues
https://github.com/gatsbyjs/gatsby/issues/11198
fixes #15775

### CODE REVIEW

**Comment by freiksenet** [comment]
Did you try it with developrunner?

**Comment by DSchau** [comment]
Marking as blocked until we fix [this comment](https://github.com/gatsbyjs/gatsby/issues/11198#issuecomment-502443775)

Also @wardpeet you'll want to remove the `.mjs` tests for webpack.config :)

**Comment by wardpeet** [comment]
This is currently blocked by `@pieh/friendly-errors-webpack-plugin` on npm. 

```
There was a problem loading the local build command. Gatsby may not be installed. Perhaps you need to run "npm install"? Cannot find module 'webpack/lib/RequestShortener'



  Error: Cannot find module 'webpack/lib/RequestShortener'
```

This is fixed in `friendly-errors-webpack-plugin@v2.0.0-beta.2` still in beta.

**Comment by pieh** [comment]
> This is currently blocked by `@pieh/friendly-errors-webpack-plugin` on npm.

I have to check but maybe we don't need to use my fork anymore

**Comment by wardpeet** [comment]
@pieh we do, unless we are ok with going for a beta package?

**Comment by pieh** [comment]
> @pieh we do, unless we are ok with going for a beta package? Your pr got merged but is only published in the beta package

Is the actual error:
```
  Error: Cannot find module 'webpack/lib/RequestShortener'
```
fixed there as well?

**Pull request closed without merging**
