### PR TITLE
Check if node.value is set as otherwise cheerio throws an error

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit ab171c4b81876ab9f1d92dfb911cdce14e2cf883

https://app.netlify.com/sites/image-processing/deploys/596e6de08ebdd96b04637184

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit ab171c4b81876ab9f1d92dfb911cdce14e2cf883

https://app.netlify.com/sites/gatsbygram/deploys/596e6ddf8ebdd96b0463717a

**Comment by KyleAMathews** [comment]
@biilmann you asked a while ago about what types of errors we're seeing from preview builds on Netilfy. There seems to be two broad categories — random failures from upstreams so NPM or the service that's hosting the binaries for Sharp. The most common weird failures from Netlify are when builds just stall for no apparent reason and then hit the 15 minute timeout. That's what the gatsbygram & image-processing failures above seem to be from.

Both took ~7-8 minutes to run a step which normally takes ~2-3. Perhaps the build servers just got really busy for a bit? For both of those sites, the deploy preview built just fine.

**Comment by KyleAMathews** [comment]
Using Remark lives again! https://596e6de08ebdd96b0463718c--using-remark.netlify.com/

**Comment by biilmann** [comment]
Thanks @KyleAMathews - we're looking into those!

**Comment by KyleAMathews** [comment]
@biilmann also see this now and then where Netlify will report a failure while the site is still building. Just happened with this build https://app.netlify.com/sites/gatsbyjs/deploys/596eba25cf321c5f2fb6150f Reported a failure probably 5-8 minutes before it finished.

**Pull request merged**
