### PR TITLE
feat(gatsby): Add default schema type for siteMetadata

### PR DESCRIPTION
**Pull request by ascorbic**
All starters use the `siteMetadata` field on `Site` to get the title and description to put in the header. However, if you delete that section from gatsby-config then the schema for that field isn't inferred and you get a GraphQL error `Cannot query field "siteMetadata" on type "Site"`. This is a very common error in the wild. Papercuts!

This PR creates a schema customisation that adds default fields of `title` and `description` to `Site.siteMetadata`. These are nullable, which is fine, but the queries in all of our starters will no longer break if a user removes that part of the config.

### CODE REVIEW

**Review by vladar — COMMENTED** [review]
Technically it can be a breaking change: now if some plugin defines a `SiteMetadata` type it will be ignored with the following warning:

```
warn Plugin `my-plugin` tried to define the GraphQL type `SiteMetadata`, which has already been defined by the plugin `internal-data-bridge`.
```

Note that it only relates to plugins (and themes). If you define this type in site's `gatsby-node` it will have precedence over other definitions.

I am not sure if there is a single plugin that does this though.

**Comment by ascorbic** [comment]
I could give it a name that's less likely to collide like  `InternalDataBridgeSiteMetadata`

**Comment by ascorbic** [comment]
@vladar I've gone with `InternalSiteMetadata`

**Comment by ascorbic** [comment]
Are there any examples of e2e tests of the creation of types? I'm asuming this would involve hitting GraphiQL?

**Comment by sidharthachatterjee** [comment]
@ascorbic Good question. I wanted to suggest adding a query including `siteMetadata` in one of the end to end test suites (and removing the value in `gatsby-config`) and then asserting that the query didn't fail but that would probably break existing tests 🤦

**Comment by sidharthachatterjee** [comment]
@ascorbic So instead I suggest adding a unit test in the tests file build-schema that asserts that built schema _always_ include this newly added internal type. What do you think?

**Comment by vladar** [comment]
Sadly, I don't think renaming will help. Yeah, we avoid the name conflict but the `SiteMetadata` type from the plugin won't be applied anymore to `site.siteMetadata`. It will be just an orphan type.

I did a quick [scan in google](https://www.google.com/search?sxsrf=ALeKk00jIGnOplJwwZNe337ZalzN-eTiBA%3A1599813891221&ei=AzlbX6KBDa_5qwHlmZ7AAw&q=site%3Agithub.com+%22type+SiteMetadata%22&oq=site%3Agithub.com+%22type+SiteMetadata%22&gs_lcp=CgZwc3ktYWIQA1AAWABg5usYaABwAHgAgAF1iAHkAZIBAzAuMpgBAKoBB2d3cy13aXrAAQE&sclient=psy-ab&ved=0ahUKEwjijsWV2-DrAhWv_CoKHeWMBzgQ4dUDCAw&uact=5) and [github](https://github.com/search?p=1&q=%22type+SiteMetadata+%7B%22&type=Code) and I don't see a single usage of `SiteMetadata` in plugins (there are some in starters but that's fine).

So I am OK to have it with the old `SiteMetadata` type name but probably publish as a minor (just in case)?

P.S. Also, I think we should have a way to search in all existing gatsby plugins - maybe aggregate forks into a separate repo

**Comment by ascorbic** [comment]
I deleted my question because I worked out a solution

**Comment by ascorbic** [comment]
@vladar But currently there's no types on `siteMetadata` on `Site`, so surely nobody could be doing that. They could be changing the `Site` type, but then they can keep using the type they chose, right?

**Review by sidharthachatterjee — DISMISSED** [review]
@ascorbic Worst case scenario, someone might have a type that will take precedence over this type so we should be fine. @vladar Correct me if I'm wrong please.

**Comment by vladar** [comment]
@sidharthachatterjee Only types defined in the site's `gatsby-node` will take precedence. If the same type is defined in some plugin or theme - their definition will be effectively ignored (and warning emitted).

But we've discussed this with @ascorbic and @freiksenet and will probably allow merging type definitions via #26864

**Comment by vladar** [comment]
Now that #26864 and #26866 are merged, we're good to close this as it is effectively done via those other PRs.

**Pull request closed without merging**
