### PR TITLE
[www] add ventura to community showcase

### PR DESCRIPTION
**Pull request by Fetten**
Adds Ventura Digitalagentur to the community showcase

### CODE REVIEW

**Comment by shannonbux** [comment]
Hi @Fetten I added: 
`for_hire: false`
`portfolio: false`

Feel free to change those if you want!

**Comment by Fetten** [comment]
Thank you for the approval, @shannonbux !
I'm a bit confused about `for_hire` and `portfolio` as I have set both to true: https://github.com/gatsbyjs/gatsby/pull/8555/commits/61328f2b88d1964353326cfd0aed7252b12376f1
Therefor I cannot change them in this PR, but will do this later :)

**Comment by Fetten** [comment]
Thank you @jlengstorf!

**Comment by shannonbux** [comment]
Apologies @Fetten, for some reason when I first viewed this PR, it didn't show the `for_hire` and `porfolio` fields at all (even when I edited the file) so I just added them with their default settings! I can't seem to recreate what happened, but I didn't mean to override any of your changes. Thanks @jlengstorf for fixing this!

**Pull request merged**
