### PR TITLE
Added StaticQuery Explanation in Tutorial-part-4

### PR DESCRIPTION
**Pull request by Chuloo**
Here's a one-liner explaining the usage of StaticQuery to query data in components using GraphQL.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 50fbd354c1453afbec71fd2e4262791f60185ede

https://app.netlify.com/sites/using-postcss-sass/deploys/5b60db5273f2cf28b19c9955

**Comment by m-allanson** [comment]
@amberleyromo I tried to come up with something short to add here (based on https://next.gatsbyjs.org/docs/static-query/#how-staticquery-differs-from-page-query) but found it kinda tricky to describe `StaticQuery` in an introductory way in a couple of lines. Which makes me wonder...

should this section of the tutorial should be rewritten to introduce `StaticQuery` and page queries separately? Adding them both into the same section seems like a lot to explain in one go.

The ["Querying for the site title"](https://next.gatsbyjs.org/tutorial/part-four/#querying-for-the-site-title) section could be split into:

- _Make a query from your About page_ - this could be mostly the same content that the tutorial has now 
- _Make a query from any component_ - this would introduce StaticQuery and how to query from any component, along with explaining the tradeoffs of using `StaticQuery`

Do you think it's worth opening an issue to do this?

Also note this issue that talks about ways that Gatsby could make the two different types of query easier to understand: https://github.com/gatsbyjs/gatsby/issues/6596

**Comment by m-allanson** [comment]
Oh haha I just realised this is what's happening in #6892

**Comment by amberleyromo** [comment]
I do think it's worth opening an issue to do this, personally. I agree that introducing them together is a lot in one go. Good to read through the issue you linked (#6596) -- What would you say the likelihood of a shift like this would be before v2 launch? (For context in prioritizing doc work).

I'm happy to run with this, if y'all want. @Chuloo @m-allanson?

**Comment by m-allanson** [comment]
I opened #7059 to follow up on this discussion. 

> What would you say the likelihood of a shift like this would be before v2 launch? (For context in prioritizing doc work).

I think this should happen before v2 release, so I marked that issue as a blocker for v2, but let's see if @shannonbux or @KyleAMathews disagree.

> I'm happy to run with this, if y'all want.

Sounds great to me!

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit db220dd9ff4d86ea48844f4b165ebd5f8d78be7b

https://app.netlify.com/sites/gatsbyjs/deploys/5b683920c9659271652eaefc

**Comment by amberleyromo** [comment]
@m-allanson quick point of clarification:

> What would you say the likelihood of a shift like this would be before v2 launch? (For context in prioritizing doc work).

I didn't mean writing the docs, I meant the potential shift described in #6596. (The new issue, #7059, addressing the docs specifically). So if that shift was going to happen before v2 goes stable, I was going to wait on those docs.

**Comment by KyleAMathews** [comment]
https://github.com/gatsbyjs/gatsby/issues/6596 def won't happen before release (if ever, needs investigating).

**Comment by m-allanson** [comment]
> I didn't mean writing the docs, I meant the potential shift described in #6596. 

Ahh that makes sense, sorry for the confusion @amberleyromo.

I'm going to merge this in, and we can follow up with #7059

**Pull request merged**
