### PR TITLE
chore(gatsby): Update load-plugins to Typescript.

### PR DESCRIPTION
**Pull request by Eyas**
## Description

This PR migrates `packages/gatsby/src/bootstrap/load-plugins` to TypeScript.

## Related Issues

Part of #21995.

### CODE REVIEW

**Comment by Eyas** [comment]
@gatsbyjs/core friendly ping on this -- can someone take a look at this chore PR?

**Comment by blainekasten** [comment]
@Eyas Thanks for the PR and sorry for the delay! We've got a lot going on!

This PR is pretty outdated now and has several conflicts. Could you resolve them and then I'll prioritize reviewing and get this merged!

**Comment by Eyas** [comment]
@blainekasten done. I'm having issues bootstrapping my local env (I'm on windows at the moment), but I'm happy to push follow-up fixes if anything is off.

**Comment by Eyas** [comment]
@blainekasten can you review #24519 first? The Babel typescript transform is producing confused imports of resolve-module-exports, causing some integration tests to misbehave.

**Comment by blainekasten** [comment]
@Eyas merged that other PR! Let's get this one caught up and ready to merge!

**Comment by Eyas** [comment]
@blainekasten Rebased and pushed.

**Comment by Eyas** [comment]
Lint failure is due to new blog post :( I also sent #24543

**Comment by Eyas** [comment]
@blainekasten Ready for review :) the linked issue got fixed.

**Comment by blainekasten** [comment]
On it!

**Pull request merged**
