### PR TITLE
Add new starter to starters.xml

### PR DESCRIPTION
**Pull request by billp72**
Fixed readme and other bugs

## Description

Add new starter to starters page

### CODE REVIEW

**Comment by billp72** [comment]
I wasn't sure if my original PR was in the process of being approved or
not. How long does it usually take?

thanks, Bill

**Comment by billp72** [comment]
Closing PR

**Comment by muescha** [comment]
i think this was the best commit (link to github repo was fine, link to netlify was fine)

i think you can reopen this to get your commit merged?

**Comment by muescha** [comment]
(branch deleted, to reopen is not possible)

**Comment by muescha** [comment]
BTW: you can add more commits to your branch, so you not need to close and create a new PR

**Pull request closed without merging**
