### PR TITLE
Add CodeSandbox to gatsby-remark-code-repls plugin

### PR DESCRIPTION
**Pull request by bvaughn**
CodeSandbox support added via the new GET API; docs and tests updated.

Here is an example sandbox created with this plug-in:
[https://codesandbox.io/api/v1/sandboxes/define?parameters=...](https://codesandbox.io/api/v1/sandboxes/define?parameters=N4IgZglgNgpgziAXKADgQwMYGs0HMYB0AVnAPYB2SoGFALjObVSACYwoNvkYTzMBOMTE0QgoaenCYAaEIOEBaFqQC2SMRPhMAvrtkRybAB7EEyEDUYMRICCpSl-tAAQAlIRloARAPIBZZzB-VWcAcnlPJVVQgG4AHXI7Byc3DxcgkPC02ISEsABXbloICkDHFQkAOTQVGAAKfLgYfgBKZ2AE52dBWnz-cmdG5oJIfilq2ucAajDZmaH-AnFxmph48m1c7gopQab-ZwBeds7AiDHaCZhEMIAJNH4OflDpU-XL1ZvQgAVmmAAvF4JbTrBKWXYwWC1RhHZx1U4AHgAFgBGAB8py6t0hUFI0naYHKVVWDX2LW0AEJEQB6VEY8gtUHkdzCXx-AiCQzNeEDZyQmDQ2ivXnKDD5QUEfC0ACiUOsACEAJ4ASRYdXCpFItFCLQSjISIG0-i5JiRtBUUGYlnojHUCJYEAAbs4ICxDnE5JraB60QjqQ7HWjDbogA)

### CODE REVIEW

**Comment by CompuIves** [comment]
Ah, I gave the wrong endpoint. The right endpoint is `https://codesandbox.io/api/v1/sandboxes/define`. It should work with this POST data:

```
{
  "files": {
    "package.json": {
      "content": "{
        \"dependencies\": {
          \"react\": \"latest\",
          \"react-dom\": \"latest\"
        }
      }"
    },
    "index.js": {
      "content": "ReactDOM.render(\n  <h1>Hello, world!</h1>,\n  document.getElementById('root')\n);\n"
    }
  }
}
```

This is the cURL:

```
curl -X POST \
  https://codesandbox.io/api/v1/sandboxes/define \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
  "files": {
    "package.json": {
      "content": "{
        \"dependencies\": {
          \"react\": \"latest\",
          \"react-dom\": \"latest\"
        }
      }"
    },
    "index.js": {
      "content": "ReactDOM.render(\n  <h1>Hello, world!</h1>,\n  document.getElementById('\''root'\'')\n);\n"
    }
  }
}'
```

I can also make it accept JSON objects as `content` parameter. Would make it easier.

**Comment by bvaughn** [comment]
Okay @KyleAMathews I think we have some new hotness for you 😄

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 9f3a091e41e9787a2fbc68f4386554b0de4c0c8d

https://app.netlify.com/sites/using-glamor/deploys/5a162605819876016db7129f

**Comment by bvaughn** [comment]
I'm not sure what that link is supposed to tell me. 😄

screen shot 2017-11-23 at 7 32 31 am

**Comment by bvaughn** [comment]
Travis failure is unrelated to this diff:
screen shot 2017-11-23 at 7 46 14 am

Netlify failure contains no helpful information:
screen shot 2017-11-23 at 7 46 40 am

**Comment by KyleAMathews** [comment]
Awesome!!!

Back from vacay so let's get this out there.

**Comment by bvaughn** [comment]
Welcome back, Kyle

**Pull request merged**
