### PR TITLE
feat(gatsby): Allow explicitly defining parent-child relations with type extensions

### PR DESCRIPTION
**Pull request by stefanprobst**
This allows defining parent-child relations between types with the `@childOf` type extension, either by specifying parent type names, or by defining parent mime-types.
On types with the `@dontInfer` extension, only explicitly defined children fields will be added.

More details in #15305.

Fixes: #15305
Related: #15545

### CODE REVIEW

**Comment by freiksenet** [comment]
@pieh made a good point that this breaks behavior of `@dontInfer`. We might need an argument for `@dontInfer` again and maybe a deprecation in v3 that will default to non-children inferred behaviour, with current behaviour still inferring children.

**Comment by stefanprobst** [comment]
We can just leave these lines commented out, and wait until v3:
https://github.com/gatsbyjs/gatsby/blob/d9ccb9c639d97bc5cd7f3017c5faf3228d295e6e/packages/gatsby/src/schema/schema.js#L772-L777
and maybe add a deprecation warning?

I'm not so sure about adding a directive argument to `@dontInfer`, might make controlling inference behavior too complicated since we already have deprecated `noDefaultResolvers` arg? Would be easy to add though.

**Comment by stefanprobst** [comment]
Now handles interfaces with `@nodeInterface` extension as well - tests should hopefully cover all scenarios.

**Comment by freiksenet** [comment]
> and maybe add a deprecation warning?
> I'm not so sure about adding a directive argument to @dontInfer, might make controlling inference behavior too complicated since we already have deprecated noDefaultResolvers arg? Would be easy to add though.

You are right. Let's add deprecation warning when implicit children are added through `dontInfer` (when they weren't added explicitly).

**Pull request merged**
