### PR TITLE
fix(cli): Console errors should have a background color

### LINKED ISSUE #2645: Console errors should have a background color
The error `window is not defined` renders white text.  If this error is read in a browser or terminal with a white brackground, the text is essentially hidden.  See attached.  May want to include a darker bg color so this text stands out.  [
screen shot 2017-10-26 at 12 11 56 pm
](url)

### PR DESCRIPTION
**Pull request by alexparish**
Fixes #2645 

# Before

screen shot 2018-03-19 at 11 53 38
screen shot 2018-03-19 at 11 53 49

# After

screen shot 2018-03-19 at 11 50 34
screen shot 2018-03-19 at 11 51 00

### CODE REVIEW

**Comment by alexparish** [comment]
@m-allanson No worries! I'm looking for other small issues to work on in order to get to know the codebase. Shout if you have any in mind! :)

**Comment by m-allanson** [comment]
Great stuff, that's exciting to hear :) Shout if you have questions at any point. 

Soon I'm hoping to go through and label up issues, so it should be much easier to pick out things that need to be worked on (see #4311). For now it's a case of digging through the issues list. Docs changes are always welcome, and building [plugins](https://www.gatsbyjs.org/docs/plugin-authoring/) or [starters](https://www.gatsbyjs.org/docs/gatsby-starters/) could be a good intro to working with Gatsby's codebase.

**Comment by alexparish** [comment]
@m-allanson Awesome thanks. Tempted to build a plugin. Know of any outstanding requests for plugins?

**Comment by m-allanson** [comment]
@alexparish 👍 You might find some ideas in https://github.com/gatsbyjs/gatsby/issues/1199. It's probably easiest if it's a plugin for a tool or service that you're already familiar with.

**Comment by alexparish** [comment]
@m-allanson Super, thanks!

**Comment by jlengstorf** [comment]
Hiya @alexparish! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
