### PR TITLE
chore(docs): Updates for the Square payments example

### PR DESCRIPTION
**Pull request by jonniebigodes**
With this pull request the issue #26055 is partially addressed. As i've mentioned in a comment in said issue i was tasked with adjusting the example and starter. 

What was done:
- The example's Gatsby dependencies were updated and simplified.
- Included the serverless function (netlify) and necessary dependencies and configurations.
- Updated the `src/paymentForm` to include the call to the serverless function.
- Renamed `page-2` to `paymentreciept` and updated the file contents to display the payment receipt information obtained from Square api.

Feel free to provide feedback

### CODE REVIEW

**Comment by pvdz** [comment]
(-> #27272 ?)

**Comment by jonniebigodes** [comment]
@pvdz as i've mentioned in the underlying docs i updated the starter and example to match the latest version of the dependencies. @LekoArts already addressed the author of said pull request on how we could proceed. 

Let me know if you need anything else and we'll move from there, sounds good?

**Comment by jonniebigodes** [comment]
Just a friendly reminder of the status on this pull request? Is this ok to go? Or not. Regarding the conflicts someone else with admin rights will have to take care of them.

Stay safe

**Comment by pvdz** [comment]
Hey. I'll have to defer to @meganesu for this one. My comment before was not a review but a quick triage. Sorry about the delay.

**Comment by LekoArts** [comment]
Hey! Thanks so much for opening this pull request!

Sadly this PR got stale and didn't have any activity for some time. We're trying to do better with PR reviews! To get a better overview of all actionable PRs we're going through all open PRs and triage them. Since we won't be able to do everything and adding new features _always_ means added maintenance burden, we have to be more picky about what's beneficial for the average user and the project itself longterm.

Having said all this, we dropped the ball on this PR and we're sorry about not responding to it earlier. As said above, we want to do better in the future but here we should have communicated earlier what will happen with the PR.

Unfortunately we won't merge this PR at the moment because with https://github.com/gatsbyjs/gatsby/pull/36268 the page got actually removed.

We absolutely want to have you as a contributor and are sorry for any inconveniences we caused with replying too late to this PR.

Thanks for submitting to Gatsby! 💜

**Pull request closed without merging**
