### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by wildpow**
Fix migration guide link in the Getting involved section.

### CODE REVIEW

**Comment by m-allanson** [comment]
Thanks @wildpow! I'm a bit puzzled though - for me both the old and updated url work, and the updated one actually redirects back to the old one. Was the old url not working for you?

**Comment by wildpow** [comment]
Screen shot of what I was getting
screen shot 2018-07-12 at 3 03 07 pm

**Comment by wildpow** [comment]
I figured since that was the only link with a training slash, than removing it would fix the link.

**Comment by m-allanson** [comment]
Ohhh ok this is happening only on next.gatsbyjs.org, not on gatsbyjs.org. Clicking that link from [this page](https://next.gatsbyjs.org/blog/2018-06-16-announcing-gatsby-v2-beta-launch/) will trigger the error you're seeing.

I'm going to close this as I don't think changing the URL will fix it. I'd love if you could open an issue describing the bug though?

**Comment by wildpow** [comment]
Done.
 [issue 5420](https://github.com/gatsbyjs/gatsby/issues/6420)

**Pull request closed without merging**
