### PR TITLE
Feat(gatsby-source-drupal): Added rateLimit to prevent ECONNREFUSED

### PR DESCRIPTION
**Pull request by timhagn**
I ran into a similar Problem like the already closed issue #3998 for gatsby-source-wordpress
(hosting provider using a DDOS prevention module, in this case mod_qos for apache),
leading to "mod_qos(010): access denied, QS_LocRequestLimit*" errors on the
server and resulting in **ECONNREFUSED** or **socket closed** failures for 
`gatsby develop` & `gatsby build` as well as the often cited
`warning The gatsby-source-drupal plugin has generated no Gatsby nodes. Do you need it?`.

I therefore added an option `rateLimit` and replaced the calls to `axios.get()` with an 
`axios.create()` Client call and added a `rateLimiter` request interceptor.

The tests are running through, only the coverage fell from 90% line to 89% (I didn't know how
to handle the `setTimeout()` call).

### CODE REVIEW

**Comment by pieh** [comment]
This is looking cool - one thing that might be more user friendly:

- don't require explicit `rateLimit` setting
- create abstraction around `axios` that would catch `ECONNREFUSED` errors and then apply rate limiting automatically - do you think it would be feasible to do?

**Comment by timhagn** [comment]
Thanks for the comment, although I don't fully understand what you mean by "explicit `rateLimit` setting",
it's optional by default (and doesn't get used if none is given), see [README.md](packages/gatsby-source-drupal/README.md).
For your second remark I have to confess, that this would go beyond my (current) knowledge of `axios`,
but as deep as I went in the sources, it seems that `axios` is generally treating any post 400 statuses as errors and the 403 returns an `undefined` `error.response` Object. Would be great if the rate limiting could be done automatically, though...

**Comment by pieh** [comment]
With explicit `rateLimit` setting I meant if code could automatically apply rateLimiting (when getting `ECONNREFUSED`), then setting wouldn't be needed at all as this would be hidden from user. (I understand it's optional in current form :) ).

**Comment by timhagn** [comment]
> With explicit `rateLimit` setting I meant if code could automatically apply rateLimiting (when getting `ECONNREFUSED`), then setting wouldn't be needed at all as this would be hidden from user. (I understand it's optional in current form :) ).

Ah, OK, so both refer to your second remark ^^. Yeah, would be great, but there I'm sadly out of my depth at the moment (just did this PR, as I had exactly the mentioned problem and from SO it seemed like I wasn't the only one ; ).

**Comment by dubcanada** [comment]
There is axios-retry and other libraries that catch certain HTTP codes and retry the connection. Could use one of those to do this?

**Comment by timhagn** [comment]
@dubcanada Thanks for the suggestion, axios-retry looks promising with exponentialDelay().
Gonna look into it : ).
Don't know which other modules you thought about, though, most I looked into on npmjs depend on axios's error-handling (at least the ones dependent on ^0.18.0)...

**Comment by timhagn** [comment]
Hi @wardpeet,
after @KyleAMathews asked around on Twitter for a way to solve this issue for "Gatsby Core",
I put this matter on hold. But if there's still interest I'd be happy to find some time to look into it further,
after rebasing onto the current master of the Gatsby repo.

**Comment by wardpeet** [comment]
ok i'll be closing until this issue comes up again. Thank you for your time!

**Pull request closed without merging**
