### PR TITLE
feat(gatsby-source-contentful): Support storing assets locally

### LINKED ISSUE #10587: contenful images to local folders
When building a site with data/images from contentful, is there a way to copy images to local folder and generate links to local copies?

### PR DESCRIPTION
**Pull request by polarathene**
Downloads and caches Contentful Assets to the local filesystem. Useful for reduced data usage or projects where you want the assets copied locally with builds for deploying without links to Contentful CDN.

Resolves #10587 #5919

### CODE REVIEW

**Comment by polarathene** [comment]
`ci/circleci: e2e_tests_path-prefix` fails with:

```
 Production pathPrefix
    ✓ returns 200 on base route (529ms)
    navigation
      ✓ prefixes link with /blog (225ms)
      ✓ can navigate to secondary page (343ms)
      ✓ can navigate back from secondary page (303ms)
      1) can go back


  4 passing (12s)
  1 failing
```

I'm not sure what's causing that or how to fix it. Navigating my own project works fine. Any advice?

**Comment by DSchau** [comment]
@polarathene don't worry about that e2e failure--it's unrelated.

I'll create an issue now so that we can track on it.

**Comment by DSchau** [comment]
Whoops--I already _did_ create that issue.

See gatsbyjs/gatsby#9233, but once more, unrelated to any changes here!

**Comment by polarathene** [comment]
@DSchau @sidharthachatterjee Would either of you be happy to review and merge this then if the failing e2e test is nothing to worry about? :)

I'm not sure if it will work well if an asset is modified on Contentful, it might not invalidate the cache and either not update the asset locally or create a new file copying over old data while the cache hasn't been cleared? (I have mentioned this in the README.md)

The wordpress plugin uses a modified metadata value to handle this, Contentful isn't providing one for ContentfulAsset afaik, there is `internal.contentDigest` but I'm not sure if that's useful.

**Comment by wardpeet** [comment]
@polarathene just to make sure we won't have any regressions in the future could you add a few tests to test your cache invalidation code (https://github.com/gatsbyjs/gatsby/pull/10682/files#diff-caa2171e85ea277bf3075bd98f17c16eR51)?

**Comment by polarathene** [comment]
@wardpeet I could try, but I've not really written much tests before. 

It's been a while since I wrote this, I vaguely remember referencing some existing implementations(although I'm not sure that they had any testing in place either). Any advice(link to a similar test could suffice).

**Comment by wardpeet** [comment]
It's more or less testing your download function to make sure it's only called when options.localDownload is set and if nodes are called correctly.

I have only found one package that tests sourceNodes https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-drupal/src/__tests__/index.js so I understand that this won't help you much as contentful doesn't have a lot of tests either. I don't want to burden you with this so if you're not up for it, no biggy.

**Comment by wardpeet** [comment]
Tested this on www.gatsbyjs.com and seems to work. Looks identical to https://www.gatsbyjs.org/docs/image-tutorial/ 👍

**Pull request merged**
