### PR TITLE
fix(gatsby): Exclude build time when calculating dirty Ids

### PR DESCRIPTION
**Pull request by sidharthachatterjee**
This significantly speeds up consecutive builds if all changed is buildTime in the `Site` node

Co authored with @ascorbic

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
Closing this for now because some folks might actually use `buildTime` 😛

**Comment by sidharthachatterjee** [comment]
We can't do what we added in https://github.com/gatsbyjs/gatsby/pull/21795/commits/299626f46cb0c59b0b999ac5f5112b89f7a7da0e because some folks _might_ just use `buildTime`

Now there's an alternative that @pieh brought up:
- Create a separate top level Node for `buildTime`
- Calculate and put it there (in the `internal-data-bridge` internal plugin)
- Add a link resolver for `buildTime` that does a passthrough to the new Node 

This would let us track dependencies when `buildTime` is used in a query (at query resolution time) but not affect the Site node (which includes the heavily used `siteMetadata`)

This would however need some more work for data dependency tracking to work correctly:
- The `Site` node would need to be of type `Node`

Also there used to be `ignoreType` that kinda would suffice for this

@freiksenet Do you remember why we stopped supporting it?

**Comment by freiksenet** [comment]
`ignoreType` was gone as not important somewhere in schema customization time, I think it was always quite a hack.

**Comment by sidharthachatterjee** [comment]
@freiksenet How do you feel about adding it back? 😛 Or do you have another preferred way to exclude something from appearing as a top level field in `Query`?

**Comment by freiksenet** [comment]
I don't think number of fields in root fields is really an important consideration. I'd call it SiteBuildTime so that it's analogous with other Gatsby site stuff.

**Comment by sidharthachatterjee** [comment]
Closed in favor of https://github.com/gatsbyjs/gatsby/pull/21827

**Pull request closed without merging**
