### PR TITLE
Add science outreach site ocean-artup.eu

### PR DESCRIPTION
**Pull request by JanoshRiebesell**
The site showcases the use of styled-components and Contentful with Gatsby v2.
It creates the new content category "science".

### CODE REVIEW

**Comment by JanoshRiebesell** [comment]
@KyleAMathews Thanks! Btw, wouldn't it make sense to include a `source_url` field to include a link to e.g. the GitHub repo for sites that are open source?

**Comment by m-allanson** [comment]
> wouldn't it make sense to include a source_url field

It would 😄 In fact, there is a `source_url` field but it's not mentioned in the docs.. do you want to update this submission to include a `source_url`?

And if you want to add `source_url` to the docs at https://github.com/gatsbyjs/gatsby/blob/acfe4415b37b0d44a6ef76d8be4d52c8affff679/docs/docs/site-showcase-submissions.md that would be 👍

**Comment by pieh** [comment]
> @KyleAMathews Thanks! Btw, wouldn't it make sense to include a source_url field to include a link to e.g. the GitHub repo for sites that are open source?

We have exactly that and it will display link to source in site details f.e: https://github.com/gatsbyjs/gatsby/blob/acfe4415b37b0d44a6ef76d8be4d52c8affff679/docs/sites.yml#L4

Just something I noticed - [`built_by_url: https://janosh.io`](https://janosh.io/) seems to points to default gatsby starter site - I think hiding it for now and updating your entry when your personal site is ready would be good idea!

**Comment by JanoshRiebesell** [comment]
> do you want to update this submission to include a source_url?
I went ahead and linked to the GitHub repo.

> And if you want to add source_url to the docs at https://github.com/gatsbyjs/gatsby/blob/acfe4415b37b0d44a6ef76d8be4d52c8affff679/docs/docs/site-showcase-submissions.md that would be
I'd be happy to. This'll be a first for me though. Which branch should I be on to do this?

**Comment by JanoshRiebesell** [comment]
> Just something I noticed - built_by_url: https://janosh.io seems to points to default gatsby starter site - I think hiding it for now and updating your entry when your personal site is ready would be good idea!

I'll publish my personal site the day after tomorrow and was hoping I could already sneak in the link. :)

**Comment by m-allanson** [comment]
> I'd be happy to. This'll be a first for me though. Which branch should I be on to do this?

On `master` would be perfect, that will get published to next.gatsbyjs.org

**Comment by m-allanson** [comment]
> Sorry for the delay

No worries! Gatsby 💜's contributions, but _your_ life should always come first and you should never feel bad about having other things to do :)

**Pull request merged**
