### PR TITLE
chore: Skip typechecks for libs

### PR DESCRIPTION
**Pull request by sidharthachatterjee**
When compiling `gatsby`, it seems that we currently run typechecks for all imported libraries in `node_modules`

This is both slow and very unnecessary. This PR fixes this setting the skipLibCheck option in `tsconfig.json`

### CODE REVIEW

**Review by mxstbr — APPROVED** [review]
> Turning [skipLibCheck] on will prevent Typescript from type-checking the entire imported libraries. Instead, Typescript will only type-check the code you use against these types.

([source](https://stackoverflow.com/a/56268670))

This looks good to me 👍

**Comment by wardpeet** [comment]
My big question here do we really want this cause it doesn't do any typechecking of libs which mean we reduce the benefit of Typescript.

What issue are we actually fixing?

**Comment by sidharthachatterjee** [comment]
@wardpeet 

> Turning [skipLibCheck] on will prevent Typescript from type-checking the entire imported libraries. Instead, Typescript will only type-check the code you use against these types.

From documentation, this will continue type checking our code that uses imported libraries, just not the entire libraries source itself.

**Comment by wardpeet** [comment]
Okay, TIL. Nice. I see that it's also the default when running `typescript --init`. Could you remove all occurences where we did it on package level.

**Comment by sidharthachatterjee** [comment]
@wardpeet Yup, all of them extend the root config (and I updated the ones which don't)

**Review by wardpeet — DISMISSED** [review]

**Pull request closed without merging**
