### PR TITLE
Add stylus example

### PR DESCRIPTION
**Pull request by iansinnott**
**What changed:**

* Added an exmaple using Stylus with and without CSS Modules

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 73952a29606d69e280f41937a8ac8310c5d245d3

https://app.netlify.com/sites/using-styled-components/deploys/5965cfc98ebdd956a89a6d40

**Comment by KyleAMathews** [comment]
Looks awesome! Traveling today but tomorrow I'll get this merged and setup on the interwebs.

**Comment by iansinnott** [comment]
Cool, thanks. Happy travels ✈
          
            
            On Jul 12 2017, at 9:47 am, Kyle Mathews <notifications@github.com> wrote:
            
            
              Looks awesome! Traveling today but tomorrow I'll get this merged and setup on the interwebs.

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
