### PR TITLE
Default Starter Theme duplicate H1

### PR DESCRIPTION
**Pull request by julians300**
## Description

This PR updates the default starter theme to remove the duplicate h1 in the header. This will promote better accessibility and SEO best practice.

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
Pinging our accessibility experts @marcysutton and @madalynrose

**Comment by wardpeet** [comment]
For my understanding, h1 are in different landmarks so multiple h1's are okay. So I don't think changing this is something we want.

I'm happy to be wrong about this :joy:

**Comment by hashimwarren** [comment]
Google has made it clear that multiple H1's have no impact on their crawler's ability to understand the content on a page, and no impact on search rankings.

See more: https://youtu.be/zyqJJXWk0gk
Also: https://youtu.be/WsgrSxCmMbM

**Comment by julians300** [comment]
Ideally we should have a single top level heading (h1) to describe the page intent. Also the heading in the navigation doesn't govern any content as far as page structure goes.

**Comment by wardpeet** [comment]
Hey! Thanks so much for opening a pull request!

The change you’ve proposed is not going to be accepted because this change doesn't meaningfully improve docs, fix a bug, or otherwise improve functionality.

We absolutely want to have you as a contributor, so please take a look at our open issues for ideas, and please reach out to us on Twitter at @gatsbyjs with questions.

We offer pair programming sessions if you’d like to work with one of our maintainers to make another contribution.

Thanks again, and we look forward to seeing more PRs from you in the future! 💪💜

**Pull request closed without merging**
