### PR TITLE
The cms build is compiled by webpack on a separate configuration

### PR DESCRIPTION
**Pull request by emanueleperuffo**
This tries to fix the netlify-cms plugin for v2 creating a separate webpack compilation

### CODE REVIEW

**Comment by erquhart** [comment]
Thanks for digging so far into this @emanueleperuffo! I didn't try the development build, but production builds are still pulling the main application styles in alongside the cms styles.

**Comment by emanueleperuffo** [comment]
Really? That doesn't happen to my cms builds...

**Comment by erquhart** [comment]
It's a single bundle, but it includes the styles from the main application. This may depend on plugins, which has long been the problem with CMS styles in Gatsby. I'm using the Gatsby Netlify CMS starter to test against, which uses the sass plugin.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by m-allanson** [comment]
@emanueleperuffo it looks like this can be closed now that #6356 has landed? Please-reopen if I've got it wrong.

**Comment by emanueleperuffo** [comment]
Perfect

**Pull request closed without merging**
