### PR TITLE
(docs) Include link to search plugin

### PR DESCRIPTION
**Pull request by andrew-codes**
Relevant to #332, this PR includes a link to a plugin that facilitates local site searching. If there is anything else I need to do with this PR, additional information, documentation, etc. please let me know.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 5e46d39cd3e0410abb4a0f7090fffc0f2ccc713e

https://app.netlify.com/sites/using-glamor/deploys/5a1c4814a11477717ae5b82a

**Comment by andrew-codes** [comment]
Oh no! I took a look at the deployment log and it appears like it never really started. It looks like there were several others with a similar output; all happening before 12:15 PM today. Has anything changed with netlify that may have caused this error and/or to have been corrected?

I am happy to help in troubleshooting the problem, though I am unsure in what ways I can try to be helpful. Please let me know if there is any thing I can do to help resolve this for this PR and the others. Thanks.

**Comment by KyleAMathews** [comment]
Netlify is flaky :-) we're switching off it soon for testing PRs. Appreciate the offer to help!

**Comment by jlengstorf** [comment]
Hiya @andrew-codes! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by andrew-codes** [comment]
Oh wow! Thank you! I will do my best! 😄

**Pull request merged**
