### PR TITLE
feat(www): Add Themes to "Ecosystem" on home page (option 1)

### PR DESCRIPTION
**Pull request by thomaswangio**
## Description

In this PR, to improve the discoverability of Themes, adding Themes to:
1. the homepage, in the "Ecosystem" section. 
1. the "Ecosystem" page.

#### Home Page
Screen Shot 2019-10-08 at 2 55 49 PM

#### Ecosystem Page

Screen Shot 2019-10-08 at 2 53 54 PM

#### Home Page
Screen Shot 2019-10-08 at 2 51 32 PM

#### Ecosystem Page
Screen Shot 2019-10-08 at 2 53 46 PM

## Related Issues/PRs

Part of Workflows Issue https://github.com/gatsbyjs/gatsby/issues/18242
https://github.com/gatsbyjs/gatsby/pull/18586 (option 2)

### CODE REVIEW

**Comment by wardpeet** [comment]
On the homepage it looks a bit misplaced in my opinion. I'm unsure how this fits nicely in the current design. We could just mix it up with starters and add a themes marker 🤷‍♂.

Let's wait for @gatsbyjs/learning, @shannonbux and @fk

**Comment by thomaswangio** [comment]
> On the homepage it looks a bit misplaced in my opinion. I'm unsure how this fits nicely in the current design. We could just mix it up with starters and add a themes marker 🤷‍♂.
> 
> Let's wait for @gatsbyjs/learning, @shannonbux and @fk

Yea, agreed, could definitely use a re-design. I noticed @fk just merged his re-design with dark mode so I'll post the new screenshots and see how it looks. 

I think the issue is that Themes are actually technically plugins (but not all plugins are themes), and Themes function similarly to a starter, effectively making Themes a combination of both plugins and starters. Would like to get @marcysutton's opinion on the best way to convey how Themes fit in with the rest of the Ecosystem, since people are having trouble understanding how to use Themes.

**Comment by thomaswangio** [comment]
> > On the homepage it looks a bit misplaced in my opinion. I'm unsure how this fits nicely in the current design. We could just mix it up with starters and add a themes marker 🤷‍♂.
> > Let's wait for @gatsbyjs/learning, @shannonbux and @fk
> 
> Yea, agreed, could definitely use a re-design. I noticed @fk just merged his re-design with dark mode so I'll post the new screenshots and see how it looks.
> 
> I think the issue is that Themes are actually technically plugins (but not all plugins are themes), and Themes function similarly to starters, effectively making Themes a combination of both plugins and starters. Would like to get @marcysutton's opinion on the best way to convey how Themes fit in with the rest of the Ecosystem, since people are having trouble understanding how to use Themes.

## New screenshots

Screen Shot 2019-10-08 at 2 51 32 PM
Screen Shot 2019-10-08 at 2 53 46 PM

**Comment by thomaswangio** [comment]
Updated description of Themes to: "Themes are special Plugins that add preconfigured functionality to Gatsby sites. You can update central themes across sites and use multiple themes in your project!"

**Comment by marcysutton** [comment]
Here's an idea: what if we rename "Plugins" to be "Plugins & Themes" so that we don't have to change the layout? Since themes are essentially plugins with a `gatsby-config` file, that might make the most sense -- and it would make it less of an impact on the layout.

**Comment by marcysutton** [comment]
We decided to close this to allow more of a discussion for homepage approaches, since that cuts across multiple teams at Gatsby. Thanks for your thinking on this though, @thomaswangio!

**Pull request closed without merging**
