### PR TITLE
[www] tracedSVG contributor avatars

### PR DESCRIPTION
**Pull request by fk**
Haven't checked SVG sizes yet, had to adjust the default options to see anything on the smaller images.

I think we need to revisit the default settings for traceSVG …
at least add a heads up to the README again.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
AWESOME!

Let's ship it :-)

Tweak as you please later. Wanna tweet about us so get it out there

**Comment by fk** [comment]
👍 … (but hey I thought we wanted to keep things _about us_ on the hush-hush a little longer?! 😊😄)

**Comment by KyleAMathews** [comment]
:-) it's always a good time to tweet about things!

**Comment by fk** [comment]
Of course! (That joke was bad, was it? ;-))

**Pull request merged**
