### PR TITLE
Replace class=language-* w data-language=* to avoid potential Prism bug

### PR DESCRIPTION
**Pull request by bvaughn**
Potential bug fix for issue #1486

Note that this would be a breaking change in terms of custom themes. If this approach seems reasonable going forward, I could hide it behind an option flag.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 582706af2714f6aef812f359fc63c4dd0216e9e4

https://app.netlify.com/sites/using-styled-components/deploys/5966b0d4a700c4199b63d6fd

**Comment by bvaughn** [comment]
Hello fake @KyleAMathews bot 😁  It seems your deploy previews have been failing a lot lately, based on other recent PRs I see, so I'm going to ignore this message for now.

**Comment by KyleAMathews** [comment]
Bot Kyle has 1/100 my intelligence and all of my charm :-)

**Comment by KyleAMathews** [comment]
So I like the solution but how about making this an option with the default false? With this change, prism themes would stop working unless you modify their selector which is doable but more work and confusing. I doubt most people will load prismjs into their page so won't run into the bug you're seeing.

**Comment by bvaughn** [comment]
Sounds great. That was what I had in mind when I mentioned the options flag. Just wanted to run the general approach by you first before spending too much time on it.

**Comment by KyleAMathews** [comment]
👍

**Comment by bvaughn** [comment]
What do you think of this approach?

**Comment by bvaughn** [comment]
Or check out the alternate approach, #1491

**Comment by bvaughn** [comment]
Closing in favor of #1491

**Pull request closed without merging**
