### PR TITLE
added instructions to use gatsby-transformer-csv

### PR DESCRIPTION
**Pull request by nenu-git**
add instructions to use the plugin with `gatsby-source-filesystem`

### CODE REVIEW

**Comment by dangerbot-gatsby** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  
Gatsby requires contributors to sign each commit.

You can do this for your branch with `git rebase --signoff`, or for a single commit with `git commit --amend -s`.

Check out the [Developer Certificate of Origin docs](https://www.gatsbyjs.org/docs/how-to-contribute/#developer-certificate-of-origin) or comment here if you've any questions.

  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by nenu-git** [comment]
Hey @m-allanson ! 

I'm sorry but I'm a little bit stuck here with the sign-off. 

I created this pull-request directly on GitHub with the editor mode. But I don't really know how (or where) to run `git commit --amend -s` ?

Also, am I not already verified if I edit files directly on GitHub ? I can see a `verified` chips near my commit mentionning it:

>This commit was created on GitHub.com and signed with a verified signature using GitHub’s key.

Thank you for your help :)

**Comment by m-allanson** [comment]
Hey @nenu-git, good question... The `verified` chip is different from the DCO signoff unfortunately.

For the DCO it looks like it's not possible to edit a commit using github.com. As a workaround, could  create a new PR with these changes?

When you commit the changes, add the line `Signed-off-by: Sébastien Belmon <sebastien.belmon@gmail.com>` to the commit message. 

It will look like this:

screen shot 2018-04-17 at 15 25 29

Then I will close this PR and we can merge the new one.

Apologies for the awkward request!

**Comment by m-allanson** [comment]
Replaced by #5019. Thanks again!

**Pull request closed without merging**
