### PR TITLE
Mini-tutorials for Glamor and Styled Components

### PR DESCRIPTION
**Pull request by shannonbux**
Do the intros and code examples make sense even though these are now removed from the context of Part Two of the Tutorial?

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0168b457ccf3f83a56b3ca6e08ff537cd8515ee4

https://app.netlify.com/sites/using-glamor/deploys/5a4ebeb20b79b728d04bcd48

**Comment by benjaminhoffman** [comment]
@shannonbux I think the code snippets are definitely still helpful but I will defer to others.  Rule of thumb with this stuff, an example is 100x more helpful than an explanation.  That's my #1 complaint about most tutes... not enough code snippets.

**Comment by benjaminhoffman** [comment]
@shannonbux happy to help get this cleaned up... just need a bit more context.  If you got it, no worries but if you'd like a hand, send a text and we'll go from there.

**Comment by benjaminhoffman** [comment]
yay!  you got it! 👍 😄

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
