### PR TITLE
test: don't fail `starters_validate` on low severities

### PR DESCRIPTION
**Pull request by pieh**
This is just a test at first - but maybe something to consider if this works

### CODE REVIEW

**Comment by wardpeet** [comment]
Should we add some kind of slackbot to remind us to also check the low severity ones? Or is low severity something we shouldn't care about?

**Comment by pieh** [comment]
I didn't go that far - this is mostly testing the waters to see what people think about loosening what level of vulnerabilities should fail `starters_validate`. In my mind `low` failing it means that noone ever looks at those because there will almost always be some `low` threat problem - and so we will miss (or be late) on something that's actually a problem

**Comment by pieh** [comment]
In perfect world we would mark `starters_validate` check with warning when there are `low` vulernabilites but fail above (at least that's my thinking) ... but I don't think GitHub have warning status - maybe it would need something else to not hide low level audit issues

**Comment by wardpeet** [comment]
Just checking, i'm all good with this!

**Comment by pieh** [comment]
I think I'll close this for now. ATM starters_validate is green (not even "low" severity alert). Something to potentially revive next time we have starters_valdiate dance

**Pull request closed without merging**
