### PR TITLE
Cross posting  Moving from create-react-app to Gatsby.js

### PR DESCRIPTION
**Pull request by Khaledgarbaya**
This PR is adding my recent blog post [Moving from create-react-app to Gatsby.js](https://khaledgarbaya.net/articles/moving-from-create-react-app-to-gatsby-js) as a cross post.

hemingway scores: [Good] 
Readability: Grade 4.
Pageviews in the last 30 days: 1,774

### CODE REVIEW

**Comment by Khaledgarbaya** [comment]
Netlify Failed to build `Build exceeded maximum allowed runtime`

**Comment by m-allanson** [comment]
Thanks @Khaledgarbaya! I made some small edits, everything else looks good. The netlify build has restarted 🤞 it should be ok this time.

**Comment by Khaledgarbaya** [comment]
Thanks @m-allanson, I tested it locally and the blog post showed up. let's wait for Netlify 🤞

**Comment by m-allanson** [comment]
> any news about this PR ?

It looks good to me. I've just merged another pending blog post, so let's publish this one tomorrow.

**Comment by m-allanson** [comment]
Cherry-picked to `v1`

**Pull request merged**
