### PR TITLE
fix(core): added event source polyfill in develop to fix IE/edge hmr

### LINKED ISSUE #11495: Hot module replacement not working in IE
## Description

I get a console error: webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools

### Steps to reproduce

1. Create new project
2. Run gatsby develop
3. open IE
4. (warning shows in console)

### Expected result

HMR should work in IE

### Actual result

HMR is not working

### PR DESCRIPTION
**Pull request by saranshkataria**
fixes #11495

## Description

Added event source polyfill in develop mode for IE. I am not sure how to test the CLI after making these changes, would need some pointers for that.

### CODE REVIEW

**Comment by saranshkataria** [comment]
I tried using gatsby-dev-cli, but was not able to, but do not see the event source plugin hooked up when I run it. I am not sure if I am missing something while setting up gatsby-dev-cli or I missed some statement while importing the polyfill. I looked for some implementations in other projects, they have added the same files that I added, but I cannot get it working for me somehow. Would need some help on how to proceed further.

**Comment by pieh** [comment]
Yeah, `gatsby-dev-cli` doesn't support yet installing added/modified deps - you would need to manually install `event-source-polyfill` first in your example site, and then run `gatsby-dev`

**Comment by saranshkataria** [comment]
@pieh already did that, but still, IE throws the warning that event source is missing

**Comment by saranshkataria** [comment]
@pieh did you get a chance to look into it?

**Comment by pieh** [comment]
I did not - I keep doing too many TO-DOs to complete them all :(

**Comment by wardpeet** [comment]
@pieh I'll check this one :)

**Pull request merged**
