### PR TITLE
[1.0] Add NPM 5 lock file

### PR DESCRIPTION
**Pull request by 0x80**
Node v8 is out and ships with NPM v5. Using NPM packages automatically generates this [lock file](https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md).

It is generated for me even though I am using `yarn` to install packages. I am guessing that is because Lerna or some other part of Gatsby uses `npm` under the hood?

Anyway I think this should be committed to the repository.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit e76ff88a0404c2c19a51b52de5d3838a02a56f35

https://app.netlify.com/sites/image-processing/deploys/592e9497424ef2471a332cce

**Comment by jquense** [comment]
I was having this break Lerna house before, I might hold off a bit

**Comment by KyleAMathews** [comment]
Having two lock files sounds like a recipe for ugh... they're supposed to be the single source of truth. I don't want to have to be updating both of them every time I update the root package.json.

Why the package-lock file is showing up is because for some reason I set the lerna client to `npm` a while ago. EDIT oh actually @thejameskyle did in https://github.com/gatsbyjs/gatsby/commit/9680770ccda74ba228e002c88072b35384a32e4c — James, do you remember why?

**Comment by jquense** [comment]
mostly because yarn support in lerna is pretty broken, it didn't work at all with hoisting. I think we are all in for a bit of unfortunate lockfile woes. Even if you set the client, that's not gonna force anyone to use `yarn` or `npm` for the root install, and both package managers insist now on adding a lockfile. 

that said I _believe_ the goal with `package-lock.json` is to be a unified format that _all_ managers can use. I have no idea though if yarn is planning on adapting that...

**Comment by 0x80** [comment]
Yeah I figured two having lock files is not ideal, but hopefully it won't hurt either. Hope things get cleared up soon. It's all a bit confusing.

**Comment by KyleAMathews** [comment]
I'd rather not commit two lockfiles. That'll cause more confusion than help it seems. Let's limp along for now until there's a better solution.

**Pull request closed without merging**
