### PR TITLE
docs(less-plugin): use next branch when install

### PR DESCRIPTION
**Pull request by B3zo0**
Specify to use next branch to work with v2. #6252

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 1fc7a016ddf6d0f326d84c28b2f8e19f358b8b79

https://app.netlify.com/sites/using-postcss-sass/deploys/5b675988c6aed63e5ea87af6

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 1fc7a016ddf6d0f326d84c28b2f8e19f358b8b79

https://app.netlify.com/sites/gatsbyjs/deploys/5b675987c6aed63e5ea87aea

**Comment by KyleAMathews** [comment]
Curious what prompted you to jump to v2?

**Comment by B3zo0** [comment]
Prompted? Nothing really, I've just seen that there is a new version and wanted to try that out.

**Comment by KyleAMathews** [comment]
Cool :-)

So... v2 official is coming out soon — I'm not sure it makes much sense to change all the READMEs just to change them back. I appreciate you wanting to help out with the docs!

I'll add a note to the repo README about using the `next` version for plugins if people are trying out v2.

**Comment by B3zo0** [comment]
Awsome, thanks :)

**Pull request closed without merging**
