### PR TITLE
Remove react-emotion from tutorial

### PR DESCRIPTION
**Pull request by garrowp**
Emotion removed react-emotion package. Not sure which version to put this in but part 4 of the tutorial will be fixed.

### CODE REVIEW

**Comment by DSchau** [comment]
@KyleAMathews sorry missed this, but yeah - there are some changes in emotion 10 that make things slightly more complicated--at least at first glance.

I need to dive in a bit more before I fully propose that though.

@LekoArts and I have also talked about it briefly. If the changes in emotion 10 seem substantive enough, styled-components could be a little more beginner friendly, and more applicable to a tutorial.

**Comment by BoyWithSilverWings** [comment]
The sheer number of plugins that are being installed in the tutorial could be a bit confusing for a beginner (`@emotion/core emotion/styled emotion gatsby-plugin-emotion emotion-server` and much more available in docs) Switching over the tutorial to `styled-components` should be nice and easy for the tutorial purpose.

**Comment by shannonbux** [comment]
So for now, @garrowp it sounds like it's best to stick with Emotion v9 and make that clear. Do you mind changing this PR to account for that change?

Then, the suggestions to either use emotion v10 or styled components ought to be put into another issue. @BoyWithSilverWings and/or @DSchau, want to make that issue?

**Comment by DSchau** [comment]
Going to close this out.

The complexity argument is certainly noted here, but I think that's a separate discussion. Happy to have it, just don't think it's applicable here.

As we've made some changes to the tutorial to account for Emotion 10, we can safely close this out.

See #10307 and #10306 for further context.

**Pull request closed without merging**
