### PR TITLE
 Add option for configuring page view submission only on first page load

### PR DESCRIPTION
**Pull request by som-matrix**
### Issue
- When a page loads, GA4 sends a page view event, and gatsby GTM plugin sends a page view event. We don’t need 2 events. We need only 1

### What need's to be done
- When `doNotSendPageViewOnFirstPageLoad=false` and `prevLocation === null` do not fire the events to gtm.

### What is changed
-  We are adding a new option called `doNotSendPageViewOnFirstPageLoad`.
-  Then we are using this plugin option in `onRouteUpdate()` method.
- There we are adding a condition `!doNotSendPageViewOnFirstPageLoad` && `prevLocation === null` do not fire the events to gtm
- So when gatsby detects it as second page load and option is set to false then only fire the events to GTM

### CODE REVIEW

**Comment by LekoArts** [comment]
Hey, thanks for the PR! However, I'll ask you to first open a feature request for this: https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests

Currently I don't see why this should be added because

> When a page loads, GA4 sends a page view event, and gatsby GTM plugin sends a page view event. We don’t need 2 events. We need only 1

Then you should only use one of them. I don't get the problem right now so I'd not want to add an option without a longer explanation of why it's needed. Hope that makes sense, thanks!

**Comment by som-matrix** [comment]
Hi @LekoArts  , can i explain it again with better example and explanations and open a PR again ?
Or what should i do first ?  open a feature request to https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests and then proceed ?

**Comment by LekoArts** [comment]
Yes, please open a new discussion in https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests to explain the need for that option. Best with a concrete example/repository showing it

**Comment by som-matrix** [comment]
@LekoArts  created a discussion here https://github.com/gatsbyjs/gatsby/discussions/37057

**Pull request closed without merging**
