### PR TITLE
Remove FlashMobile from README

### PR DESCRIPTION
**Pull request by tribou**
Alas, the Gatsby version was replaced. 😩

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Ah man, that site was so cool that you could toggle between spanish and english *while* the ball thing was animating across the screen and the text in the ball would change w/o a glitch.

Alas.

Thanks for updating us.

Perhaps just as well — that new site would not reflect well on Gatsby 👿  http://www.webpagetest.org/result/161025_MZ_350D/

**Comment by KyleAMathews** [comment]
6.6 MBs damn.

Speed index of 11440.

They should ask for their money back.

Then again, a telecom site that is humongous is an excellent idea on their part as they make money every time someone visits their site!!!

**Comment by tribou** [comment]
Yep, overruled by the big bad CMS... 😜

**Comment by KyleAMathews** [comment]
Gatsby 1.0 is going to have excellent integration with various CMSs as a service :crossed_swords:

**Pull request merged**
