### PR TITLE
chore(CoC): add notes about blocking/removing someone

### PR DESCRIPTION
**Pull request by marcysutton**
## Description

Stemming from an internal discussion, this PR adds some clarifying language to when we might block someone on social media or remove them from a GitHub repo. When we've made an attempt to hear them out and they don't respect our space or boundaries (e.g. by filing an issue instead of on someone's personal Twitter feed), we reserve the right to block them. In the case of GitHub, we also reserve the right to remove someone if their behavior hasn't aligned with the Code of Conduct.

Now is the time to comment! Let me know if there is more appropriate or accurate language we should use here. The goal is to make it clear that harassing behavior may result in a block or removal as it doesn't align with our community standards.

## Related Issues

N/A

### CODE REVIEW

**Comment by laurieontech** [comment]
I don't have any issue with the language. Is it worth mentioning something about this decision being made by more than one person? As in, at least two Gatsby team members were consulted on the action?

**Comment by marcysutton** [comment]
That sounds like an excellent idea, @laurieontech! I can make an update.

**Comment by marcysutton** [comment]
Updated!

**Comment by pieh** [comment]
Do we need to provide a formal way for those blocked users to "appeal the verdict"? Do we need something for transparency? (i.e. to not have "team made decision behind closed doors" scenarios)

Not saying we do, just asking questions ;)

**Comment by pieh** [comment]
Also should we store logs/reports somewhere (probably not publicly) when we block users that list what user action led to blocking (so there's no scenario where we blocked someone, and after a while no-one remembers about reasons)

**Comment by marcysutton** [comment]
> should we store logs/reports somewhere

Currently those conversations are in Slack. I could add them to a doc internally with links to conversations and reasoning? That does seem useful.

**Comment by marcysutton** [comment]
I created that doc internally, and since there's no other feedback I'm going to merge this in! We can always update it later. Thanks for the input!

**Pull request merged**
