### PR TITLE
Add tripby.org to sites.yml

### PR DESCRIPTION
**Pull request by dalbinaco**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit a4d952347a1fc96ac38627f01092dff317642bdd

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5cad2167610c5bde168957

**Comment by daliadefelipee** [comment]
Nice site indeed but I think it would be nice having a PR description.

**Comment by dalbinaco** [comment]
@amandeepmittal 
Sorry, dindn't notice the overall file formatting.

**Comment by amandeepmittal** [comment]
@dalbinaco NP.

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 7c18bb8dce71ef684b15a7d2060a821811076447

https://app.netlify.com/sites/gatsbyjs/deploys/5b5f0764dd28ef05c4046f0e

**Comment by calcsam** [comment]
Technically, this is a great website! Unfortunately, we'd prefer not to be linking to a website mentioning substances like MDMA that are illegal in key jurisdictions across the world. Thanks for submitting this and good luck!

**Comment by dlbnco** [comment]
@calcsam 

I understand why you wouldn't want to link to it, and I respect that ☺️

Just want to leave it registered that harm reduction is of key importance to safe drug usafe and it has probably saved more people than any prohibition laws made by governments.

**Pull request closed without merging**
