### PR TITLE
[gatsby-plugin-offline] Add criticlal scripts and links to static file globs

### LINKED ISSUE #6212: [v2] [gatsby-plugin-offline] Service Workers throw errors when offline
It seems that service workers are broken on v2. They are successfully installed, but return errors when the user is offline:

> Cannot read property 'pageContext' of undefined

screen shot 2018-06-28 at 10 42 56 am

This also leads to this Lighthouse warning:

> Service worker does not successfully serve the manifest's start_url.

Could potentially be related to the `pageContext` rename?

### Steps to reproduce

Example repo: https://github.com/fabe/test-gatsby-v2-offline  
Production build: https://peaceful-wozniak-ecfc89.netlify.com

Reload the site while offline (after installing the service worker).

### Environment

```bash
  System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Safari: 11.1.1
  npmPackages:
    gatsby: next => 2.0.0-beta.12
    gatsby-plugin-offline: ^2.0.0-beta.2 => 2.0.0-beta.2
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

### PR DESCRIPTION
**Pull request by kkemple**
This PR adds all the scripts and links added to `public/index.html` to the `staticFileGlobs` config for `sw-precache`. This resolves the issue of service worker updates breaking sites.

It seems the breakage was caused by index.html being loaded out of cache and when the JS kicks in, there are times when the needed data file (which isn't currently cached) isn't downloaded yet, this causes an error which causes the dreaded white screen.

Closes #6212

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 99335e807711c8ffe62fe7e52c5a103cbe5f00ca

https://app.netlify.com/sites/using-glamor/deploys/5b3e9b5b02ed83757e4c634d

**Comment by kkemple** [comment]
Taking a look!

**Comment by kkemple** [comment]
glamor deploy fixed!

https://app.netlify.com/sites/using-glamor/deploys/5b3ebc61fdd72a753ed94594

**Comment by KyleAMathews** [comment]
Just tested gatsbygram and it loaded perfectly when offline!

screen shot 2018-07-06 at 11 00 28 am

**Pull request merged**
