### PR TITLE
Update deps for gatsby-react-router-scroll

### PR DESCRIPTION
**Pull request by ptb**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit da2ce8e498ba965a99ecb4e93942e26905222507

https://app.netlify.com/sites/using-glamor/deploys/5a391d18df9953762fbdcb89

**Comment by ptb** [comment]
This is to eliminate these warnings from a new `npm install`:
`npm WARN gatsby-react-router-scroll@1.0.6 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.`
`npm WARN gatsby-react-router-scroll@1.0.6 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by ptb** [comment]
The [original source](https://github.com/ytase/react-router-scroll) has react & react-dom at "^16.0.0" already and the differences between this and the original are still just the gatsby-specific bits.

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
