### PR TITLE
Appveyor Performance Improvements

### PR DESCRIPTION
**Pull request by jbolda**
Working on trying to cache some things, and do builds of many examples on publish

### CODE REVIEW

**Comment by jbolda** [comment]
Well, if we want to run more than one example... working on one branch, [this is the best we will get](https://ci.appveyor.com/project/KyleAMathews/gatsby/build/1.0.1948). It will run every example, but exit on everything except gatsbygram. When the commit message is "Publish" (as it looks like it has been for tags), then it will run all of the examples. I will keep an eye on the cache, and maybe if that helps enough we can run two or three examples on every commit.

The only way we can change the "matrix" is by [having multiple branches](https://www.appveyor.com/docs/build-configuration/#build-matrix). And saving the cache is [disabled in pull requests](https://www.appveyor.com/docs/build-cache/#saveupdate-cache-before-build-finishes) so it won't be terribly reliable for us to save any more cache than I have with the amount of PRs we do. So it looks like we are looking at about [10 to 15 minutes per example](https://ci.appveyor.com/project/KyleAMathews/gatsby/build/1.0.1946).

**Comment by jbolda** [comment]
I think it should be ready to merge, @KyleAMathews, if you are ok with the examples running like this. (We kind of had it this way before.)

**Comment by KyleAMathews** [comment]
So what's this PR do exactly?

**Comment by jbolda** [comment]
It adds caching. Also, building all of the examples on tag in Github never worked because an env never seemed to be set. I switched it to be based on the commit message = "Publish".

A few of the intermediate commits were testing some theories that weren't very well documented.

**Comment by KyleAMathews** [comment]
Sounds great!

**Pull request merged**
