### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jainishan28**

### CODE REVIEW

**Comment by acagastya** [comment]
@jainishan28 This PR does not add any new functionality or improve docs.  Please do not create PRs for the sake of Hacktoberfest.  Consider solving those problems ("issues") that are marked for hacktoberfest.

@pvdz can you please close this PR and mark it as invalid.

**Comment by LekoArts** [comment]
@acagastya While I appreciate your help by commenting here there's no need to always tag `@pvdz` in those comments. He's not the only maintainer here and eventually we'll see those PRs and comments. Thanks!

**Comment by acagastya** [comment]
Thanks, @LekoArts.

**Comment by jainishan28** [comment]
@acagastya is not a genuine Id though. Simply copying the code from other repository and spamming other ids causing disturbance to genuine users.
@pvdz kindly block that user.

**Pull request closed without merging**
