### PR TITLE
chore(gatsby-source-graphql): upgrade graphql-tools to v7

### PR DESCRIPTION
**Pull request by yaacovCR**
upgrade graphql-tools to v7

https://github.com/ardatan/graphql-tools/releases/tag/graphql-tools%407.0.0

v7 finally includes bug fixes that required breaking changes (e.g. https://github.com/ardatan/graphql-tools/issues/1047).

### CODE REVIEW

**Comment by yaacovCR** [comment]
Hi team! Hard for me to tell if this is a failure in graphql-tools.

Locally, I am getting a lot of spurious errors. Thoughts?

**Comment by DSchau** [comment]
@yaacovCR can you provide a reason as to what this is doing or enabling?

What benefits for users of `gatsby-source-graphql` will moving to graphql-tools@^7.0.0 enable?

**Comment by yaacovCR** [comment]
Mostly getting bug fixes, for example, that will improve error reporting like https://github.com/ardatan/graphql-tools/issues/1047

**Comment by yaacovCR** [comment]
In terms of failing ci, are you able to shed some light on whether that looks related to this PR?

**Comment by pvdz** [comment]
Restarted the test, I think it's unrelated.

Same question as in #27791 and as Dustin asked before.

What breaking change required the bump to v7 and why does it not affect us? Why is it safe to upgrade? I can't find reasonable changelogs to verify this and it seems our version is relatively old. I have very little insight into this package myself so it's very hard to judge. 

Thanks

**Comment by yaacovCR** [comment]
https://github.com/ardatan/graphql-tools/releases/tag/graphql-tools%407.0.0

I don't think the breaking changes affect Gatsby. Can get more complicated in typescript as some types have changed.

In terms of advantages, answered above, mostly bug fixes, like #1047.

Definitely would be more confident it tests passed!

Not sure what's up with them.

**Review by vladar — COMMENTED** [review]
Hey @yaacovCR 

I want to try it locally before merging. Will get back to you as soon as I have a chance. Thanks for the PR! 💜

**Comment by yaacovCR** [comment]
Won't feel confident however until tests pass... Tried rebasing.... No joy

**Review by vladar — COMMENTED** [review]
For some reason, our example project fails with this error on this PR:

```
Error: Schema must contain uniquely named types but contains multiple types named "Node".
```

Works fine with `master`. Any ideas?

**Comment by yaacovCR** [comment]
Not at the moment. :( Will have to dig in.....

**Comment by yaacovCR** [comment]
@vladar 

Works for me now when I test locally using gatsby-dev in example project. And tests pass!

**Review by vladar — APPROVED** [review]
Worked for me too now. Thank you for the PR! 💜

**Pull request merged**
