### PR TITLE
Fix incorrect height calculation for image asset

### PR DESCRIPTION
**Pull request by oscar-b**
Line #187 does `/ desiredAspectRatio`, this calculation should probably be the same? I'm getting incorrect heights when querying images from Contentful.

This change has not been tested yet, but the mistake seems obvious?

### CODE REVIEW

**Comment by oscar-b** [comment]
Is there any need for the height variable in the request at all?

**Comment by KyleAMathews** [comment]
It could very well be wrong :-)

Could you test it real quick on your machine by following the instructions at https://www.gatsbyjs.org/docs/how-to-contribute/#contributing

Also I'm guessing the tests will need updated.

**Comment by oscar-b** [comment]
Yup I'll give it a try locally and verify it :)

**Comment by oscar-b** [comment]
@KyleAMathews Updated tests and verified correct size calculation on local site, all good to go!

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
