### PR TITLE
chore(starters): add gatsby-landing-page-starter

### PR DESCRIPTION
**Pull request by btahir**
## Description

Added new starter to starters.yml

### CODE REVIEW

**Comment by btahir** [comment]
> Actually, this is close. Can you make sure to satisfy all of the "DangerJS" concerns before we merge?

Thanks! I'm not really seeing any changes? Is it some spacing/ indent issue?

**Comment by btahir** [comment]
> Hey @btahir! Made some suggestions on the tags below, thanks for the PR!

@gillkyle Sorry I must be missing something obvious here but I don't see any suggestions?

Screen Shot 2020-05-18 at 1 43 46 PM

**Comment by gillkyle** [comment]
Oh boy I'm so sorry 🤦 maybe I had this open in another tab or something. I don't see my comments either. This is probably my fault!

We have a whitelist of tags here: https://github.com/gatsbyjs/gatsby/blob/master/docs/categories.yml

Your features entry in the `yml` file can include arbitrary text, but tags have to come from that list so they don't get out of hand. I think the ones like Lead gen, conversion, and responsive layout aren't included in our whitelist.

**Comment by btahir** [comment]
> Oh boy I'm so sorry 🤦 maybe I had this open in another tab or something. I don't see my comments either. This is probably my fault!
> 
> We have a whitelist of tags here: https://github.com/gatsbyjs/gatsby/blob/master/docs/categories.yml
> 
> Your features entry in the `yml` file can include arbitrary text, but tags have to come from that list so they don't get out of hand. I think the ones like Lead gen, conversion, and responsive layout aren't included in our whitelist.

Gotcha! I've updated now. Let me know if there is anything else. :)

**Pull request merged**
