### PR TITLE
chore: update outdated puppeteer versions

### LINKED ISSUE #23421: Puppeteer: upgrade from v1 to v3
## Summary

> @muescha Puppeteer v1 is very out-dated - we just released v3. I'll see if we can get Gatsby (or the plugin) to upgrade their version.

_Originally posted by @jackfranklin in https://github.com/puppeteer/puppeteer/issues/5685#issuecomment-617246723_

### Motivation

new version is available

### Usages:

- `gatsby-plugin-preload-fonts`: 
  - `"puppeteer": "^1.20.0"`
- `gatsby-transformer-screenshot/lambda`: 
  - `"puppeteer-core": "^2.1.1"`

### PR DESCRIPTION
**Pull request by ElijahCano33**
## Description
This PR introduces changes made to two versions of two libraries used within the Gatsby project. One library is called puppeteer and is used for the gatsby-plugin-preload-fonts package. The other library is called puppeteer-core which is used for the gatsby-transformer-screenshot package. Both of the versions of these two packages were outdated, and this PR has changes that upgraded them to the latest version.

## Related Issues
Fixes #23421

### CODE REVIEW

**Comment by pieh** [comment]
Are there any breaking changes? We will also need to sync root `yarn.lock` file (install dependencies and commit that file)

**Comment by ElijahCano33** [comment]
I read through all the release notes of puppeteer from v1.20.0 up until v3.4.0. There doesn't appear to be any breaking changes; however, starting from v3.0.1 it was noted in the release notes that, "The docs now include the libgbm-dev dependency that's needed for Linux builds." It's unclear to me whether or not this could be a problem for our Linux users if they don't have this library. Here's the link to the [release notes](https://github.com/puppeteer/puppeteer/releases)

**Comment by ElijahCano33** [comment]
Hi, I wanted to ask if there's any current update regarding the status of this pull request?

**Comment by danabrit** [comment]
@ElijahCano33 Sorry for the delay in responding to you. Could you please resolve the conflicts above?

**Comment by ElijahCano33** [comment]
No worries! I have went along and resolved the conflict. Please let me know if there is anything else I should do or fix.

**Comment by sidharthachatterjee** [comment]
I'll go ahead and update the `yarn.lock` on this

**Pull request merged**
