### PR TITLE
[1.0] Renamed remark-responsive-image-plugin

### PR DESCRIPTION
**Pull request by chiedo**
Renamed the plugin and all references found as discussed here https://github.com/gatsbyjs/gatsby/issues/1286#issuecomment-311709926

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 2eebe09ddeb657687e2615cf0a837876b193ba35

https://app.netlify.com/sites/gatsbyjs/deploys/5953da28424ef2136dabbd0d

**Comment by chiedo** [comment]
@KyleAMathews wouldn't we expect it to fail since I added references to a npm package that hasn't yet been published? `gatsby-remark-build-images`

Also what is that deploy preview supposed to do? I just see a 404. Could you explain how your using it in a couple of sentences?

**Comment by chiedo** [comment]
Nevermind on the deploy preview question. The most recent one built and it's clear now. haha

**Comment by KyleAMathews** [comment]
I ended up going with `gatsby-remark-images` instead (pushed some changes onto your branch) as "build" is implied.

Thanks!

**Comment by chiedo** [comment]
Awesome @KyleAMathews :)

**Pull request merged**
