### PR TITLE
[www] run prettier on pre-commit

### PR DESCRIPTION
**Pull request by NickyMeuleman**
references #7964

Runs prettier on all supported file-types in the www/ directory on pre-commit through a husky git-hook.

Started branch to mess around on my own, originally wanted to integrate ESLint and Prettier on www, dropped ESLint because the rules from higher up already apply. Figured I'd also submit this PR since it isn't huge.

### CODE REVIEW

**Comment by m-allanson** [comment]
Nice, thanks @NickyMeuleman! Do you know if husky / pre-commit hooks work nicely with git GUI tools like [GitHub Desktop](https://desktop.github.com/) and [SourceTree](https://www.sourcetreeapp.com/) (to pick two examples)?

**Comment by NickyMeuleman** [comment]
I have no experience with GUI tools so I can't confirm, but Huskys github page claims  support for GUI tools
https://github.com/typicode/husky#features

**Comment by macklinu** [comment]
In my experience, husky has worked nicely with GitHub Desktop. 👍

**Comment by KyleAMathews** [comment]
Looks pretty reasonable. If this works well, we should add it to the root as well.

**Comment by jlengstorf** [comment]
@NickyMeuleman I think a single PR that only fixes Prettier stuff is probably ideal. It's hard to review PRs that mix style fixes with new code, so a style PR helps us rip off the Band-Aid.

**Comment by NickyMeuleman** [comment]
@jlengstorf Assume I have to open a new PR since this one is already merged. It's 2am here, so, can I do this tomorrow please? ^^

**Pull request merged**
