### PR TITLE
[gatsby-image] Remove outer wrapper div

### PR DESCRIPTION
**Pull request by stefanprobst**
* Remove unnecessary outer wrapper div
* Remove unused `position` prop
* Update README and gatsby-image example
* Update jest snapshots

See #7797

### CODE REVIEW

**Comment by pieh** [comment]
Hmm, this might break styling for some people who rely on current structure/classnames

**Comment by stefanprobst** [comment]
Yes that is a problem. OTOH having two wrapper elements (both position: relative) is unnecessary, makes it harder to position absolutely, and issues like #7822 could be easily avoided. Anyway, v2 not being final yet, I thought this might be a good time to do small changes like these. If not, I could change this to only remove the unused `position` prop.

**Comment by janosh** [comment]
> Anyway, v2 not being final yet, I thought this might be a good time to do small changes like these. If not, I could change this to only remove the unused position prop.

@stefanprobst I definitely concur with you all the way. The outer wrapper div is superfluous, hence should be removed and with v2 and other breaking changes around the corner now is a great time to do it.

I believe there are more people annoyed by the outer `div` than would be annoyed by the slight code modifications necessary if it was removed. In fact, it's become quite infamous. [Scott Tolinski of Level Up Tuts even calls it stupid](https://youtu.be/zhM6C0P7VO0?t=419). 😄

**Comment by KyleAMathews** [comment]
LOL!!

**Comment by KyleAMathews** [comment]
But yeah, it'd be good to fix this.

**Comment by KyleAMathews** [comment]
I'm probably not the best to review this as I haven't thought closely about gatsby-image in a while. The change seems to make sense but I don't really remember any more why the outer wrapper is there in the first place 😅

Was it there in my original PR or added after?

**Comment by janosh** [comment]
@KyleAMathews Nope, looks like `gatsby-image` started off with just a [single wrapper div](https://github.com/gatsbyjs/gatsby/commit/f07caac0d3947bae025a68882e39c15f55933785#diff-5941a73c5d794b120294a0429b6351c1R96).


But the outer wrapper was added by you in a [later commit on Oct 7, 2017](https://github.com/gatsbyjs/gatsby/commit/971c4af38a588cd54c18cb9645d60d50856fd9ea#diff-5941a73c5d794b120294a0429b6351c1). Based on the [comments in that commit](https://github.com/gatsbyjs/gatsby/commit/971c4af38a588cd54c18cb9645d60d50856fd9ea#diff-5941a73c5d794b120294a0429b6351c1R225), it appears as though the only reason for introducing the outer wrapper `div` was in order to reset a `z-index`.
```
// The outer div is necessary to reset the z-index to 0.
```
I can't quite figure out why this was necessary though nor why it couldn't have been achieved with just a single wrapper `div`.

**Comment by KyleAMathews** [comment]
@janosh cool 👍 can you build a little example site to verify how z-index works with this change?

**Comment by stefanprobst** [comment]
* While the outer wrapper, and the comment about resetting `z-index`, were only added later, what *was* there in the original PR was the example using `` with a negative z-index (see [using-gatsby-image](https://github.com/gatsbyjs/gatsby/blob/f07caac0d3947bae025a68882e39c15f55933785/examples/using-gatsby-image/src/pages/index.js#L12)). So my guess would be that the outer wrapper was introduced to solve problems with how the component was used there?
* Since #4468 the outer wrapper does not reset `z-index` anymore.
* What remains a problem is that removing the wrapper `div` and `outerWrapperClassName` might break stuff for people.

**Comment by KyleAMathews** [comment]
I'm ok with a breaking change as long as all existing behavior works and we have a good migration guide.

This is the deploy preview for using-gatsby-image and this PR https://deploy-preview-7826--using-gatsby-image.netlify.com/ seems to look correct.

**Comment by janosh** [comment]
@KyleAMathews Yep, looking good! Sorry I didn't do it myself. I have a deadline tonight and I'm slightly behind schedule.

**Comment by stefanprobst** [comment]
I checked that the examples work and added a small note to the migration guide. Let me know if there's something else missing from my side?

**Comment by janosh** [comment]
Can this PR be merged now?

**Comment by Siyfion** [comment]
@stefanprobst Great work, I'm having similar issues with the extra `<div>` and styling with `emotion`.

**Comment by agarrharr** [comment]
Is this a breaking change in v2?

**Comment by DSchau** [comment]
@agarrharr it's documented as such in the [migration guide](https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#gatsby-images-outerwrapperclassname-was-removed)

Anywhere else we should document it? PRs welcome!

**Comment by agarrharr** [comment]
Oh ok. I was looking here: https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/

**Comment by DSchau** [comment]
@agarrharr we should probably redirect that soon! Thanks for the reminder!

**Comment by lightstrike** [comment]
FYI I ended up here somehow too: https://v2--gatsbyjs.netlify.com/docs/migrating-from-v1-to-v2 -- probably was looking at the `next` subdomain as well

**Pull request merged**
