### PR TITLE
chore: use commit lint for consistent commit message

### PR DESCRIPTION
**Pull request by ekoeryanto**
## Motivation
there are so many version change recently and I always see the changelogs that just tell me a note about version bump only

### CODE REVIEW

**Comment by pieh** [comment]
I think we want merge commits to follow convention and not each individual commit that will get squashed when PR get's merged

**Comment by ekoeryanto** [comment]
I don't think so, I even thought to include [commitizen](https://github.com/commitizen/cz-cli) here

**Comment by pieh** [comment]
Did you check https://github.com/gatsbyjs/gatsby/issues/7625 by any chance? we don't want to add additional barrier of entry for people enforcing convention in their commit messages - we are squashing and merging so any conventional commit enforcing should be at PR title level

**Comment by pieh** [comment]
Following discussion in #7625 (this comment in particular https://github.com/gatsbyjs/gatsby/issues/7625#issuecomment-424175770) - this isn't something we want to enforce on every contributor, so I'll close this PR.

**Pull request closed without merging**
