### PR TITLE
feat(gatsby-source-shopify): support multi currency

### PR DESCRIPTION
**Pull request by stoufa88**
## Description

Query variant presentment prices from Shopify Storefront API and create necessary nodes.

## Related Issues

Related to #19453

## Screenshot
example

### CODE REVIEW

**Comment by pieh** [comment]
How do I enable multi currency in shopify? I do want to verify PR locally, just can't figure out how to get more than just USD there

**Comment by pieh** [comment]
I'm not sure if we need to create new node type? We don't seem to use it really and all we need is to adjust query to that selection?
```
presentmentPrices(first: 250) {
                    edges {
                      node {
                        price {
                          amount
                          currencyCode
                        }
                      }
                    }
                  }
```

**Comment by stoufa88** [comment]
Here you can find details about enabling multi currency in admin https://help.shopify.com/en/manual/payments/shopify-payments/multi-currency/setup

I will remove the node creation, and leave the query only, maybe it is better to keep it simple.

**Comment by stoufa88** [comment]
@pieh You are right, I removed VariantPresentmentPriceNode related code, and it worked like expected. I thought Gatsby needs node for all children.

**Comment by pieh** [comment]
Ok, seems like this require to enable "shopify payments" which I can't do for some reason on demo shop we have. But it works without it (I just get single currency), so this is fine to merge for me.

**Pull request merged**
