### PR TITLE
 import link codemod

### PR DESCRIPTION
**Pull request by tsriram**
Taking the idea from @m-allanson's comment https://github.com/gatsbyjs/gatsby/issues/5038#issuecomment-411516865, this codemod updates `Link` import from `gatsby-link` to `gatsby` package.

### CODE REVIEW

**Comment by mikelax** [comment]
I know there is always debate about linting test files, fixtures vs. ignoring. I don't want to hijack this PR but as a separate task would it instead be better to add pretterier and linting support to the test files and fixtures, and just add any needed overrides within the given top-level folders for "tests" special cases?

**Comment by m-allanson** [comment]
> I know there is always debate about linting test files, fixtures vs. ignoring.

@mikelax I'm fully in favour of linting and prettiering test specs, if there's anywhere in the repo where that's not happening then we should fix it. 💪 

For the fixtures themselves it doesn't seem like such a clear win though.. I won't complain if someone wants to remove the `/* eslint-disables */` and replace them with specific exceptions for each fixture, but I don't think it should be a requirement for landing PRs like this.

**Comment by tsriram** [comment]
So here's the story behind disabling ESLint for testfixtures.

The main complaint from ESLint with these testfixtures is having a semicolon. jscodeshift automatically adds a semicolon when we insert a statement (import in my case). Though we should be able to tell (I'm assuming, will have to figure it out) jscodeshift to not insert the semicolon, I'm not sure if it's the right way. A lot of people using Gatsby could have coding style with semicolon!

And if I add `/* eslint-disable */` in each test fixture, it's breaking one of the tests - `import-default` since we have this:

*Input:*
```
/* eslint-disable */
import Link from "gatsby-link"
import React from "react"

const IndexPage = () => (
  <div>
    <h1>Hi people</h1>
    <p>Welcome to your new Gatsby site.</p>
    <p>Now go build something great.</p>
    <Link to="/page-2/">Go to page 2</Link>
  </div>
)

export default IndexPage
```

*Output:*
```
import { Link } from "gatsby";
import React from "react"

const IndexPage = () => (
  <div>
    <h1>Hi people</h1>
    <p>Welcome to your new Gatsby site.</p>
    <p>Now go build something great.</p>
    <Link to="/page-2/">Go to page 2</Link>
  </div>
)

export default IndexPage
```

And we actually remove the first import from `gatsby-link` and insert a new import statement. Apparently the comment `/* eslint-disable */` is attached to the first statement in the AST and when we remote it, comment is gone as well. So the output from `jscodeshift` will not have the `/* eslint-disable */` comment in the first line. So if I remove that line from the testfixture output, linting fails in the repo.

Looks like there's a workaround for this given in facebook/jscodeshift#44. Will try it out and see how it goes!

**Comment by tsriram** [comment]
@m-allanson we want `navigateTo` also to be imported from `gatsby` right?

**Comment by m-allanson** [comment]
Thanks for the background info @tsriram! 

> we want navigateTo also to be imported from gatsby right?

Yep, that should be handled in https://github.com/gatsbyjs/gatsby/pull/7532, so an extra test should cover cases where this codemod has been run, but the navigateTo codemod hasn't. Possibly we should look at sharing code between the codemods?

**Comment by DSchau** [comment]
@m-allanson definitely. I was _super_ close to refactoring some fo the code in #7532 so perhaps this PR is a good opportunity to start some of that work?

**Comment by tsriram** [comment]
@m-allanson have added additional test.

**Comment by m-allanson** [comment]
Released as `gatsby-codemods@1.0.0-rc.3`, thanks again 🙏 I think these codemods are going to be really useful for v1 upgraders!

**Pull request merged**
