### PR TITLE
Add owner to starter showcase URL slugs

### PR DESCRIPTION
**Pull request by jbranchaud**
Issue #9249

### CODE REVIEW

**Comment by amberleyromo** [comment]
@pieh but this will create redirects for all new starters added moving forward, as well? we'd also need a way to resolve when there are two repos of the same name (the issue that prompted this improvement)

**Comment by amberleyromo** [comment]
@pieh bump?

**Comment by pieh** [comment]
I thought I replied earlier :/ Sorry about that.

> but this will create redirects for all new starters added moving forward, as well?

Didn't think about that and agree, we probably shouldn't. So We would need to create static list of already existing staters that need redirects.

> we'd also need a way to resolve when there are two repos of the same name (the issue that prompted this improvement)

We can't really do much about old/current URLs for those. I think redirects will need to redirect to same repo that gatsbyjs.org currently show. And the slug change will take care of future instances of that.

**Comment by amberleyromo** [comment]
@jbranchaud see https://github.com/gatsbyjs/gatsby/pull/9304#issuecomment-433530667

**Comment by chmac** [comment]
What about adding a generic redirect like `/starters/slug/` to `/starters/?s=slug`. I think the starter URLs will change from `/starters/slug/` to `/starters/user/slug/` so ideally we could safely redirect with a regex like `^/starters/[\w-]+/$` that would not affect the new starter URLs.

**Comment by jbranchaud** [comment]
From what I can tell, the [`createRedirect`](https://www.gatsbyjs.org/docs/actions/#createRedirect) function doesn't support regex. I think we have to go the route of working from a static list of project slugs. Given that list, I think the suggestion of redirecting to `/starters?s=slug` is a great idea because it helps put the user in a context where they are more likely to see either of the starters they were looking for.

Any suggestions on how I can get a listing of starter projects? It's not clear to me where the set of starters is being seeded from.

**Comment by chmac** [comment]
@jbranchaud The data is at [`docs/starters.yml`](
https://github.com/gatsbyjs/gatsby/blob/master/docs/starters.yml).

**Comment by pieh** [comment]
Updated PR with static redirect map (to not create new redirects in the future)

the 2 starters that are currently problematic are:
- `gatsby-starter` (from `cosmicjs` and `fabien0102` users/orgs)
- `gatsby-starter-typescript` (from `goblindegook` and `haysclark` users/orgs)

**Comment by pieh** [comment]
Thanks @jbranchaud for implementation! And sorry it took so long to actually merge :( - we lost track on this one.

**Pull request merged**
