### PR TITLE
[1.0] Use a union type for an array linked node field pointing to heterogenous types

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hit need for this while working on the contentful source plugin as you can have an array of linked mixed types but (crucially) where the order is important. E.g. `pageContent` is an array of fields some fields have an image and text and others are just text. I think converting this into a union type makes the most sense.

So I think I changed my mind from https://github.com/gatsbyjs/gatsby/pull/928#discussion_r115818466 :-)

An array/list of mixed things just makes sense from a data modeling perspective sometimes so we need to support it.

@jquense thoughts here?

**Comment by KyleAMathews** [comment]
Gonna merge now as but feel free to comment so we can tweak things before next beta.

**Comment by KyleAMathews** [comment]
@0x80 do you have anything like this with your use of Contentful?

**Comment by 0x80** [comment]
@KyleAMathews No, I don't have a use-case for that currently. All my arrays are of a single type.

**Pull request merged**
