### PR TITLE
fix(gatsby-plugin-typography): sort typography style tag first to avoid overwriting issues

### PR DESCRIPTION
**Pull request by KyleAMathews**
Fixes https://github.com/gatsbyjs/gatsby/pull/12295
Fixes https://github.com/gatsbyjs/gatsby/issues/6302
Fixes https://github.com/gatsbyjs/gatsby/issues/9911
Fixes https://github.com/gatsbyjs/gatsby/issues/1994

### CODE REVIEW

**Comment by DSchau** [comment]
Looks good to me--added some unit tests to validate behavior.

Merging and publishing!

screen shot 2019-03-04 at 7 13 35 pm

**Comment by DSchau** [comment]
Successfully published `gatsby-plugin-typography@2.2.8`

**Comment by KyleAMathews** [comment]
🎉

**Comment by octalmage** [comment]
woohoo, glad to see this make it in! Thanks!

**Comment by jbolda** [comment]
I am still seeing some things inlined differently. I can reproduce it in the [examples on the theme](https://github.com/jbolda/gatsby-theme-bulma) I have thrown together. Particularly noticeable with the Links being light green vs blue on the /articles/ page.

**Comment by Krizzu** [comment]
I've come across the same issue today.
My issue was that my `CSS` files were added to `Head` before `typography.js` injection, hence few styles were overridden. 

So I've fixed it by overriding `injectStyles` method from `typography` instance. 

```js
// override method before exporting typography
typography.injectStyles = function() {
  if (typeof document !== 'undefined') {
    // Replace existing
    const styleNode = document.getElementById('typography.js');
    if (styleNode !== null) {
      styleNode.innerHTML = this.toString();
    } else {
      const node = document.createElement('style');
      node.id = 'typography.js';

      // note: use typography context 
      node.innerHTML = typography.toString();

	  // note here: I use prepend, not appendChild
      document.head.prepend(node);
    }
  }
};
```

**Comment by KyleAMathews** [comment]
@jbolda @Krizzu I assume this is development? @DSchau has a PR open for the same change as @Krizzu at https://github.com/KyleAMathews/typography.js/pull/201

**Comment by jbolda** [comment]
@KyleAMathews yep, thanks for the heads up!

**Comment by DSchau** [comment]
@jbolda any interest in validating the changes in that PR with your repo?

You can just build out and copy over files, or use `npm|yarn link` with the PR Kyle linked above.

Would help us assert that it's actually the fix--although it seems pretty obvious that is the fix!

**Comment by KyleAMathews** [comment]
@DSchau's PR with the `injectStyles` fix is merged and published. Upgrade to `typography@0.16.19`

**Comment by robert-claypool** [comment]
Now that `<style id="typography.js">` is forced to the top of `<head>`, I don't know how to include my own reset CSS file, or any other file that I want evaluated before typography.js CSS.

[Ejecting](https://www.gatsbyjs.org/docs/custom-html/) `default-html.js` to `src/html.js`, and adding `<link rel="stylesheet" href="reset.css" />` is now useless since there is no way to keep that reset tag above typography.js CSS. A reset should be the baseline on which typography.js and other custom CSS override.

**Comment by robert-claypool** [comment]
This PR also pushes `<meta charset="utf-8">` down, but UTF-8 must be completely within the first 1024 bytes of the document, see https://github.com/h5bp/html5-boilerplate/blob/7.0.1/dist/doc/html.md#the-order-of-the-title-and-meta-tags

**Comment by KyleAMathews** [comment]
@robert-claypool the expectation is that you'd use the normalize.css file Typography.js includes. Is there something special about your reset? Perhaps we could add support for custom resets to Typography.js. The assumption is that Typography.js _is_ your reset — so you wouldn't need anything more than that.

The second issue should definitely be fixed. Would you like to give it a go at fixing it? You'd need to edit the sort so that it puts `meta charset` above typography.js https://github.com/gatsbyjs/gatsby/blob/632f0356d2c75f91dfbd7cb6853499c17050f074/packages/gatsby-plugin-typography/src/gatsby-ssr.js#L26-L32

**Pull request merged**
