### PR TITLE
gatsby-plugin-is-child-of-type

### PR DESCRIPTION
**Pull request by scottyeck**
Sets up environment-specific check for child type detection. See https://github.com/gatsbyjs/gatsby/issues/3486 for context.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 27e58f06655b0729256d617d33d5f7adffe33111

https://app.netlify.com/sites/using-glamor/deploys/5a7d2f1edf99537d2f894263

**Comment by scottyeck** [comment]
Yeek. Looking at https://github.com/gatsbyjs/gatsby/pull/3864, it looks like this should probably be *in* _gatsby_ rather than being configured as a plugin. @KyleAMathews if you agree lmk and I can amend the PR.

**Comment by KyleAMathews** [comment]
Hmm yeah — making this a built-in core util makes sense since it's Gatsby that causes the problem so we should also provide the means to fix it (in again a Gatsby specific way).

**Comment by scottyeck** [comment]
Roger that. 😉

**Comment by KyleAMathews** [comment]
Hey, would love to have this finished up! Closing out old PRs but please @scottyeck or anyone else interested open a new PR adding a util.

**Pull request closed without merging**
