### PR TITLE
Remove the slash between the pathPrefix and pathname when navigating

### PR DESCRIPTION
**Pull request by DaleWebb**
This bug was introduced by (#1550)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks for the fix!

Could you not do the replace though? We already ensure that the pathPrefix doesn't end with a slash [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/redux/reducers/config.js#L32)

**Comment by KyleAMathews** [comment]
Just pushed a fix myself so can get this out

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit f6bd1095c2f08c5eed057db83ec6b086a3fccee9

https://app.netlify.com/sites/using-glamor/deploys/5970e985cf321c644355a7aa

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit f6bd1095c2f08c5eed057db83ec6b086a3fccee9

https://app.netlify.com/sites/using-remark/deploys/5970e985cf321c644355a7b3

**Comment by KyleAMathews** [comment]
Fix is out in 1.3.2

**Comment by jlengstorf** [comment]
Hiya @DaleWebb! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
