### PR TITLE
[CLI] Change `--no-*` commands to `--disable-*`

### LINKED ISSUE #4820: Unknown argument: uglify
PR #4755 introduced a ` --no-uglify` flag but it doesn't work for me when invoked from an npm script or via `npx`:

```
$ npx gatsby build --no-uglify
node_modules\gatsby\dist\bin\gatsby.js build

Options:
  -h, --help      Show help                                                       
  --verbose       Turn on verbose output                                          
  --no-color      Turn off the color in output                                    
  --prefix-paths  Build site with link paths prefixed (set prefix in your config).
  --no-uglify     Build site without uglifying JS bundles (for debugging).        
  -v, --version   Show version number                                             

Unknown argument: uglify
```

As a workaround, it is possible to do

```
$ npx gatsby build --noUglify
```

or

```
{
  "scripts": {
    "build": "gatsby build --noUglify"
  }
}
```

---

Note: I previously made it sound like the CLI parsing is incorrect but doing `$ gatsby build --no-uglify` (using global gatsby-cli) works correctly. Sorry!

### PR DESCRIPTION
**Pull request by tsriram**
Resolves #4820

### CODE REVIEW

**Comment by borekb** [comment]
Sorry that I was late to comment but I think `--no-xyz` is better than `--disable-xyz` (the `--no-` prefix seems to be preferred by most CLIs). Originally commented here: https://github.com/gatsbyjs/gatsby/issues/4820#issuecomment-378508571

A possible way to "fix" the `--no-uglify` parsing is to configure yargs with `boolean-negation: false`.

**Comment by tsriram** [comment]
Hmm, I'm quite not sure which is better. Will let @KyleAMathews take a call :smile: 

Feel free to close this PR if `--no-*` prefix is the way we want to go.

**Comment by KyleAMathews** [comment]
Yeah, actually just defining uglify and setting it to default to true sounds like a good solution. Can we only show `--no-uglify` in the docs?

**Comment by m-allanson** [comment]
Maybe the docs message could be something like:

>Uglify JS bundles. Defaults to true. For debugging use `--no-uglify` to build with non-uglified JS bundles.

**Comment by tsriram** [comment]
Hmm, that could work. Looking at @KyleAMathews' comment https://github.com/gatsbyjs/gatsby/issues/4820#issuecomment-380297974, I'm not sure if we just want to leave the command as is & close this PR?

**Comment by m-allanson** [comment]
Hmm. Let's close this for now and revisit if needed. Thanks @tsriram, as always!

**Pull request closed without merging**
