### PR TITLE
gatsby-plugin-netlify-cms: using webpack-utils

### PR DESCRIPTION
**Pull request by emanueleperuffo**
I discovered the existence of webpack-utils, so I changed my previous contribution and removed the mini-css-extract-plugin in favor of rules.css() and plugins.extractText() of webpack-utils

### CODE REVIEW

**Comment by shaunbent** [comment]
Nice this looks like a nicer solution. 😎

**Comment by emanueleperuffo** [comment]
Yeah I know.
There's an issue though...

The CMS does not work in production mode, and I've noticed that if I remove webpackConfiguration.optimization.runtimeConfig it works.

How can we fix this?

**Comment by erquhart** [comment]
@emanueleperuffo check out #6356. I've been fixing this plugin for quite some time, and I'm more or less convinced that it's not going to "just work" within Gatsby's own build system, so the new PR runs a small standalone Parcel build instead.

**Comment by m-allanson** [comment]
Thanks @emanueleperuffo and @erquhart! Closing this in favour of #6356.

**Pull request closed without merging**
