### PR TITLE
Cleared Grammatical Errors in index.md

### PR DESCRIPTION
**Pull request by Ishaan28malik**

### CODE REVIEW

**Comment by aesthytik** [comment]
Thanks for the PR!❤️

**Comment by Ishaan28malik** [comment]
will ie be merged ? @aesthytik and when please someone review this .

**Comment by DSchau** [comment]
@Ishaan28malik unfortunately, these grammatical errors are more subjective than meaningful, which is a bummer! We do love grammatical fixes though, and PRs fixing true grammatical errors, fixing links, and otherwise fixing up documentation are so valuable and we'd love to have your input on those.

One thing that may help clarify what we mean by how to make a meaningful PR is checking out these two documents:

- [Gatsby Style Guide](https://www.gatsbyjs.org/docs/gatsby-style-guide/)
- [Contributing to Gatsby](https://www.gatsbyjs.org/docs/how-to-contribute/)

As such, I'm going to close this out as this isn't a substantial improvement to our documentation nor to comprehension of this documentation. Thank you for the PR, and we hope to see more from you soon!

**Comment by Ishaan28malik** [comment]
@pieh can u please merge it this time i will be doing more PR's but I want my this PR to be merged can u do this ?
@DSchau can u do this please ?

**Comment by DSchau** [comment]
@Ishaan28malik hey! So, unfortunately that's not going to be possible for the reasons I specified. I've also left some feedback on the PR itself, so you can gain some further insight into _why_ this won't be merged in its current state.

Thanks for understanding!

**Comment by Ishaan28malik** [comment]
@DSchau no issues i will go through the docs and will solve some good issues thank u ....

**Pull request closed without merging**
