### PR TITLE
fix(gatsby-remark-images): support resolving markdown images from child nodes

### PR DESCRIPTION
**Pull request by rburgst**
- in case where remark nodes are created from other nodes
  (e.g. gatsby-plugin-json-remark) the parent node
  of a remark document is not a file.
- in order to resolve the images still, it is necessary
  to go up the parent chain until the closest File node

Fixes https://github.com/gatsbyjs/gatsby/issues/28094

### CODE REVIEW

**Comment by rburgst** [comment]
any chance to get this reviewed?

**Comment by rburgst** [comment]
still waiting for feedback

**Review by KyleAMathews — DISMISSED** [review]
👍 from me

**Comment by rburgst** [comment]
rebased on master, hoping that the patch builds through

**Comment by rburgst** [comment]
@KyleAMathews I am not sure what to do, the build-test failures do not appear to be related to my changes

**Comment by rburgst** [comment]
Anyone home?

**Comment by KyleAMathews** [comment]
Tested the PR against @rburgst's reproduction and the image is now processed correctly:

Screen Shot 2022-05-02 at 12 40 20 PM

So this looks ready to go in assuming tests pass now with updated snapshots.

**Comment by KyleAMathews** [comment]
Thanks again @rburgst for this PR and I'm very sorry it's taken so long to get merged.

**Review by j0sh77 — APPROVED** [review]
As Kyle said, sorry this took so long to get to. Thanks for your contribution! 😄

**Review by KyleAMathews — APPROVED** [review]
🚢

**Comment by j0sh77** [comment]
Failing tests were unrelated, merged! Thanks again! 🚀

**Pull request merged**
