### PR TITLE
[Site Showcase] Adding Dan Abramov's personal blog

### PR DESCRIPTION
**Pull request by daydream05**
Saw his post on Twitter so i thought it might be great to add his new blog to the showcase

Questions though:
- What's the rule on posting other people's site? 
- Should we ask Dan for permission first before adding it?

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Generally you shouldn't add someone's personal blog without permission as individuals should be able to make that decision. Corporate sites are ok. We can ask him here though — @gaearon — would adding your blog to the gatsby site showcase be ok? https://www.gatsbyjs.org/showcase/

**Comment by daydream05** [comment]
Understood 👍

**Comment by LekoArts** [comment]
Closing this PR then since he didn't answer to this. If he wants it added at some later point he can open up a new PR 👍

**Comment by gaearon** [comment]
I don't mind

**Pull request closed without merging**
