### PR TITLE
Gatsby + Prismic plugin update

### PR DESCRIPTION
**Pull request by PaulinaVPG**
## Description
Update on the Gatbsy + Prismic docs to recommend the gatsby-source-prismic-graphql plugin. And made descriptions in general a little bit simpler.

### CODE REVIEW

**Comment by LekoArts** [comment]
@Ekwuno 2 days ago this PR contained content. It most likely vanished as this PR was created from @PaulinaVPG `master` branch. You should create a separate branch on your repository and push the changes to that and then create a new PR :)

**Comment by PaulinaVPG** [comment]
Thank you for the heads up @LekoArts, i will have to do it again haha

**Comment by Ekwuno** [comment]
Hey @PaulinaVPG I am sorry, the mistake was on my part. If you can implement the same changes in another PR I will review right now. I apologise for the mix-up

**Comment by marcysutton** [comment]
Oh bummer. Perhaps the work could be saved from this commit? https://github.com/gatsbyjs/gatsby/commit/38e88d31654c6074565a5511dec1cb6b0cbcb56e

**Comment by PaulinaVPG** [comment]
Yes, there it is, I'm going to make another PR for it. Thank you very much @Ekwuno @marcysutton

**Pull request closed without merging**
