### PR TITLE
Submitting Multiple Site Showcase Contributions

### PR DESCRIPTION
**Pull request by axthomas29**
## Description

Updated sites.yml file to add site showcase contributions for review

### CODE REVIEW

**Comment by marcysutton** [comment]
It looks like this PR introduced a file that shouldn’t be part of the showcase, can someone explain why it was included? Thank you 🙏

**Comment by axthomas29** [comment]
@marcysutton After I sent the final pull I did notice there was a separate file that was outside of the "sites.yml" file that I edited in my request. I wasn't quite sure if that was added as in part of Code Contributions guideline I followed or something else. I left it alone in fear of messing something up. All I know is...it's a mystery to me! 🔍

I'm sure this isn't a significant file and can be removed and hopefully won't cause any issues. 👍

Sorry about that! 😬 Thank you!!!!

**Comment by axthomas29** [comment]
@marcysutton Let me know if you need me to remove it, etc. 😊

**Comment by marcysutton** [comment]
@axthomas29 thanks for the update! This has been resolved in master, so you can disregard. It should have been caught on our end, but no worries for the future and thanks again for your contribution!

**Comment by axthomas29** [comment]
@marcysutton Woohoo! Glad it has been resolved!

You are very welcome!

**Pull request merged**
