### PR TITLE
Quick typo fix in README

### PR DESCRIPTION
**Pull request by tonyxiao**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by KyleAMathews** [comment]
Could you fix this on the master branch too?

**Comment by KyleAMathews** [comment]
Oh nvm, I'll do it as I had to grab my laptop to merge anyways as the tests are failing on 1.0 atm.

**Comment by tonyxiao** [comment]
👍 . Finally getting a chance to actually sit down and dig into the code here so expect more PRs coming.

**Comment by jlengstorf** [comment]
Hiya @tonyxiao! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
