### PR TITLE
Feature: use npx to run gatsby cli

### LINKED ISSUE #8665: Quick start using npx
## Summary

Add documentation to use `npx` to get started with Gatsby

### Basic example

```bash
npx gatsby new gatsby-site https://github.com/gatsbyjs/gatsby-starter-default
```

### Motivation

This way you don't have to install the CLI globally which also keeps the CLI always up to date. Also Facebooks `create-react-app` switched to it

### PR DESCRIPTION
**Pull request by marcobiedermann**
Use `npx` to run `gatsby cli` - fix #8665

### CODE REVIEW

**Comment by marcobiedermann** [comment]
@DSchau Yes that is right. It does require >= npm 5.2.0 which comes by default with >= node v8.
But since Node v.8 is currently in LTS I would say that is fine.

**Comment by pieh** [comment]
We still do support node 6, so probably no-go (at least for current major release). 

Will `npx` install deps? Because you removed installation part - but I think we still would need to install gatsby-cli (just not globally), correct?

**Comment by DSchau** [comment]
@pieh not actually needed to install anything else. `npx gatsby new` behaves the same as `gatsby new`.

But yeah, that was my concern too.

**Comment by pieh** [comment]
I mean, you still ned to install `gatsby-cli` locally to be able to use `npx gatsby new`?

**Comment by DSchau** [comment]
@pieh nope! `npx gatsby new` basically installs `gatsby-cli` _or_ refers to a cached version.

So on a clean machine with npm/node, the following will work `npx gatsby new test-site`

**Comment by KyleAMathews** [comment]
npx is a nice option for advanced users but isn't one we're going to recommend as the default as it's an extra thing for people to understand and is only actually interesting for trying out npm not using a tool every day.

**Comment by marcobiedermann** [comment]
@KyleAMathews 
I understand and that is absolutely fine but I would disagree with your statement.
Using npx ist way easier and it also ensures that `gatsby-cli` is always up to date.
The only "tricky" part is, that you must have >= Node v8 installed on your machine.
I would make the decision based on which version of Node you would like to support.
In case you stick with v6 I would close this PR, if you decide to require newer versions, I would go for it.

**Comment by jlengstorf** [comment]
I tend to agree with @marcobiedermann on this. Global deps are a minefield, _especially_ for less advanced users. On an up-to-date version of Node, using `npx` for global commands is much more beginner friendly. That being said, I'd agree that we shouldn't talk about `npx` until we've dropped support for Node < 8.

**Pull request closed without merging**
