### PR TITLE
chore(gatsby-source-wordpress): Test html link transforms

### PR DESCRIPTION
**Pull request by TylerBarnes**
This PR adds a test for html field link transforms (from absolute urls to relative paths).

### CODE REVIEW

**Review by wardpeet — APPROVED** [review]
Looks good! I would want to advise moving away from execall to match-all https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll

**Review by wardpeet — APPROVED** [review]
Does this need to be backported?

**Comment by TylerBarnes** [comment]
@wardpeet my understanding is that tests aren't running as part of the backporting process. When I tagged the integration tests as needing backporting Matt mentioned they don't need to be backported.

**Comment by wardpeet** [comment]
I thought you created a function to mitigate a bug, that's all :)

**Comment by TylerBarnes** [comment]
Ahh, got it! I created the function to make the regexp testable 👍 thanks for checking :)

**Comment by wardpeet** [comment]
Because regexes are stateful in javascript - that's why I was thinking that 😄 
https://javascript.plainenglish.io/most-surprising-behavior-of-javascript-regular-expression-you-have-ever-seen-1ddb84539163

**Comment by TylerBarnes** [comment]
Interesting! I didn't know that - thanks for the link

**Pull request merged**
