### PR TITLE
fix(core): Only delete html/css files during prod builds

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by wardpeet** [comment]
Couldn't this enable more edge cases on develop? Like ghost pages that should have been deleted but aren't because invalidation didn't kick in. It's not a bug with this part of the code base but more a general issue we're having. Xstate refactoring will fix most if not all bugs we're seeing on this front.

Not against merging just double checking ^^

**Comment by pieh** [comment]
@wardpeet has very good point here - we fallback to serving `index.html` in express app running in develop, but first we do serve existing static assets, so we can serve stale html pages with this on first render:

screenshot 2019-03-04 at 23 17 32

This is solvable. Easiest option would be to blacklist `.html` files in `express.static`, but it doesn't expose this option easily

**Comment by KyleAMathews** [comment]
oh hmmm... yeah great point @wardpeet. We used to have code to ignore .html files — but that was removed at some point. It looks like we can just set `index` to false so I'll add that.

**Comment by KyleAMathews** [comment]
Pushed up commit that seems to fix things with testing locally.

**Pull request merged**
