### PR TITLE
chore(showcase): Add Paul Scanlon Blog

### PR DESCRIPTION
**Pull request by PaulieScanlon**
Hi, i'm adding my theme for site showcase submission

### CODE REVIEW

**Comment by lannonbr** [comment]
Technically this is a Gatsby Theme and although they do have an example site of using it, the site has just sample data showing the theme off, so I would recommend against merging this. Although, if you build a site with the theme that has real data & posts, then I think that would be acceptable.

**Comment by PaulieScanlon** [comment]
@lannonbr that's a fair point. 

I am working on my new portfolio... (which was the reason i built the theme) which you can see here https://paulie.dev/ 

It's real data... albeit not fully completed. If i amend my PR could this get merged in?

**Comment by lannonbr** [comment]
yeah if you replace the current entry in this PR with paulie.dev that likely will be accepted

**Comment by PaulieScanlon** [comment]
@lannonbr hmmm what would the `source_url:` be the repo for the blog or the repo for the theme?

**Comment by lannonbr** [comment]
The blog as you are going to showcase your site instead of the theme

**Comment by lannonbr** [comment]
if the site repo is not public, you can just remove the `source_url` field

**Comment by PaulieScanlon** [comment]
done and done @lannonbr thanks for your help 😎

**Comment by laurieontech** [comment]
Hey @PaulieScanlon! Looks like your yarn.lock file got added to the commit accidentally. If you remove that we should be good to merge this in!

**Comment by PaulieScanlon** [comment]
🤦oh good lord!!  Thanks @lannonbr! should be good to go now!

**Comment by bball07** [comment]
Thank you!! This looks awesome!!! I am going to merge this PR :)

**Pull request merged**
