### PR TITLE
Change gatsby-transformer-remark excerpt behavior

### PR DESCRIPTION
**Pull request by riywo**
## Description

This commit changes `excerpt` behavior of `gatsby-transformer-remark`:

- Plain text even with separator
- New format for MARKDOWN

Previously, `PLAIN` excerpt returns different format with/without `excerpt_separator` because it respected `gray-matter`'s `excerpt` (which is raw markdown) when `excerpt_separator` is specified. Now, it applies the same logic used by without separator.

To keep the current behavior somewhere, we also introduces `MARKDOWN` format. So, `excerpt(format: MARKDOWN)` + `excerpt_separator` is identical with the current `excerpt(format: PLAIN)` + `excerpt_separator`.

## Related Issues

Addresses #4459

### CODE REVIEW

**Comment by riywo** [comment]
I have no idea why some of tests are failing.

**Comment by freiksenet** [comment]
There was a stale snapshot (happens sometimes when writing tests). I've removed it now. 

I'll merge it and release as a minor version update for the plugin, thanks a lot!

**Comment by freiksenet** [comment]
Published as `2.4.0`. Thank as a lot! :purple_heart: :muscle:

**Comment by riywo** [comment]
OMG, thank you so much!!!

**Comment by zslabs** [comment]
cc @wardpeet https://github.com/gatsbyjs/gatsby/issues/15286

**Pull request merged**
