### PR TITLE
Add self to showcase

### PR DESCRIPTION
**Pull request by giraffesyo**
Personal site is still on v1. Been doing a lot at work with v2 and hope to be able to add that to the showcase later.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 6dd5ca2dd157eef63a0f5da872786b8e70dbf560

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5a96a302ed8306d390f3d8

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 6dd5ca2dd157eef63a0f5da872786b8e70dbf560

https://app.netlify.com/sites/gatsbyjs/deploys/5b5a96a202ed8306d390f3d0

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit d5ee773878729bca0f01bbc8973ebf6fa656cc7f

https://app.netlify.com/sites/gatsbyjs/deploys/5b5a976eb13fb117c0f667e9

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit d5ee773878729bca0f01bbc8973ebf6fa656cc7f

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5a976eb13fb117c0f667f1

**Comment by m-allanson** [comment]
Nice, thanks 👍👍

**Pull request merged**
