### PR TITLE
Add 'minimal reproduction' doc link in bug_report template

### PR DESCRIPTION
**Pull request by sagarnasit**
fixes: #18601

### CODE REVIEW

**Comment by sagarnasit** [comment]
@pieh Let me know if this works for you.

**Comment by pieh** [comment]
Hey! @camilaavilarinho claimed the issue before you posted this pull request, so I'd like to give her a chance for her first gatsby contribution, if that's all right with you (as you already are contributor here)?

**Comment by sagarnasit** [comment]
No Problem @pieh. Always welcome new contributors. Let me know if you have anything else for me.

**Comment by pieh** [comment]
I'll set blocked label, at least for ~2 days, I think that's reasonable time for it.

**Comment by sidharthachatterjee** [comment]
Looks like she opened a pull request! Closing this but thank you @sagarnasit 👍

**Pull request closed without merging**
