### PR TITLE
chore(starters): add gatsby-bootstrap-italia-starter

### PR DESCRIPTION
**Pull request by dej611**
## Description

Adding the Gatsby Bootstrap Italia starter to the library.

### CODE REVIEW

**Comment by bball07** [comment]
Thank you for your contribution!! I am going to merge this :)

**Comment by bball07** [comment]
This looks GREAT!! Once you resolve the conflicts it can be merged :)

**Comment by dej611** [comment]
Sure, resolved! 👍

**Comment by dej611** [comment]
It is complaining about things in `master`, not in this PR.
Should I move the stuff in this PR at the bottom of the file?

**Pull request merged**
