### PR TITLE
Allow for env files

### LINKED ISSUE #660: Pass GATSBY* environment variables into app
I'd like to set some envionment variables and read them from my site, but I haven't found a way to do so.

If I run `FOO=foo npm run dev`

There is no way to read that FOO variable, as far as I know.

`console.log(process.env)` returns only `{NODE_ENV: "development"}`

Any way to solve that ? 

Is it supported ?

Thanks

### PR DESCRIPTION
**Pull request by okcoker**
Usually dotenv is used to throw variables on `process.env` but in this case I'm just using the `parse` method and adding those variables to webpack's DefinePlugin. This way `process.env` never gets altered. 

This also make sure not to overwrite `NODE_ENV` or `PUBLIC_DIR`.

To use, you'd just put an `.env.development` or `.env.production` file in your root folder and those variables will be provided at dev/build time.

Could fix #660

### CODE REVIEW

**Comment by KyleAMathews** [comment]
This looks great! Could you start a docs page discussing using .env files? Really glad to see this pattern supported. Would be great too to get `GATSBY_*` support in as well someday.

**Comment by okcoker** [comment]
Sure thing. 

I could easily add `GATSBY_*` only functionality but I'm not sure of the benefit. 

From my [understanding](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables), the reason that create-react-app went  the `REACT_APP_*` route, (and someone can correct me if I'm wrong), is because they didn't want to potentially expose private variables on the environment. They are similarly using `dotenv` to load environment variables but the difference is they are using `dotenv.config` [here](https://github.com/facebookincubator/create-react-app/blob/36904959996d2b5a32b737af43635fffad91181c/packages/react-scripts/config/env.js#L44-L46) which by default alters the `process.env` object. I'm just using `dotenv.parse` which does not alter the environment. I'm just parses the variables from your `.env.development` or `.env.production` file and providing them to webpack at build time.

Am I missing something from Dan's comment [here](https://github.com/facebookincubator/create-react-app/issues/865#issuecomment-252199527)? I feel one could equally do `REACT_APP_WHATEVER=some secret that shouldnt be exposed`

Thoughts?

**Comment by KyleAMathews** [comment]
I want Gatsby to work with other ways of setting environment variables other than .env files. So for .env, yeah you've done a great job there not overriding things so that's perhaps fine. But it'd be great to be able to run `GATSBY_API=https://example.com gatsby develop`. Also many hosting platforms just expose a way to add runtime environment variables not .env files.

**Comment by okcoker** [comment]
Ah, I see. Baby steps 👶 🍼 😬 

Just added a docs file. Let me know what you think!

**Comment by KyleAMathews** [comment]
No yeah, definitely don't feel like you have to solve everything in this PR :-) this is a great improvement!

**Comment by okcoker** [comment]
Fixed the docs typo

**Comment by KyleAMathews** [comment]
Great PR! Thanks for helping improve Gatsby's abilities around env variables. That's something people have had to hand-code before.

**Pull request merged**
