### PR TITLE
fix(gatsby): respect plugin parent dir

### PR DESCRIPTION
**Pull request by Js-Brecht**
## Description

This makes the plugin/theme resolution process respect `parentDir` if it is defined on the plugin metadata.  This will allow consumers/themes to dynamically define where plugins can be found.

This is important for `gatsby-plugin-ts-config`, which acts as a type of proxy for the default site `gatsby-config` and `gatsby-node`.  It serves up those files as its own.  Because of this, when using pnpm or yarn2, combined with Gatsby's plugin path resolution, the plugins proxied by `gatsby-plugin-ts-config` cannot be resolved, since they exist as dependencies on the default site and not actually as dependencies of `gatsby-plugin-ts-config`.

Since plugins proxied by `gatsby-plugin-ts-config` cannot be resolved by the core, it will resolve them before passing them back to Gatsby.  This has a couple of problems:
* deduplication does not work correctly
* If a plugin's `main` module is not in the root of its directory, the core cannot read the `package.json` because it looks in the `path.dirname` of the resolved plugin's path.  This came up with `gatsby-plugin-image`, because `main` points to `/dist/gatsby-image.js`; therefore, when `resolve` is already a fully-qualified path, Gatsby will try to read the file `/dist/package.json`... which doesn't exist, of course.

If `parentDir` is respected, then `gatsby-plugin-ts-config` can tell the core where those particular proxied plugins can be found.

## Related Issues

https://github.com/Js-Brecht/gatsby-plugin-ts-config/issues/23
https://github.com/Js-Brecht/gatsby-plugin-ts-config/issues/26

### CODE REVIEW

**Review by vladar — COMMENTED** [review]
We have a e2e test suite for themes here: https://github.com/gatsbyjs/gatsby/tree/master/e2e-tests/themes

Do you think it is possible to add a test for this case that will also prevent regressions?

**Comment by Js-Brecht** [comment]
Writing an e2e test for this scenario would be interesting.  What are the expectations?  That the site can build successfully, or should it also be testing the DOM?  Do you expect to see a new e2e testing site created, or do you want to see it integrated into both the `development-runtime` and `production-runtime` sites?

I could definitely model the expectations in the [`load-themes` tests](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/load-themes/__tests__/index.js), if that seems appropriate as well.

**Comment by vladar** [comment]
Any test that you feel appropriate for this change to prevent regression and demonstrate the broken workflow. I am not insisting on e2e test. `load-themes` works too.

**Comment by Js-Brecht** [comment]
@vladar sorry for the delay.  I've got those tests implemented in `load-themes`.  I modeled both a broken workflow where plugins/themes are not deduplicated because `resolve` has been set to an absolute path, and where `parentDir` is used to explicitly resolve the plugin to a specific location while still allowing it to be deduplicated.

Please let me know if they are clear enough, or if you think it may deserve some e2e tests, as well

**Comment by vladar** [comment]
Thank you so much for adding those tests. Codewise looks good to me 👍 

But I need to play with this locally with some other use-cases before merging. Will come back to you later this week. And my apologies for the delay.

**Comment by vladar** [comment]
For me, this looks solid. I couldn't find problems with it but feel that it needs another pair of eyes from the core team to check for potential pitfalls that I may be missing.

**Comment by Js-Brecht** [comment]
Thanks for looking it over @vladar.  I completely understand, and I would welcome another pair of eyes.

One problem I see with it is that it is essentially creating a new kind of api, which could have all sorts of ramifications that I may not fully grasp atm

**Comment by alvis** [comment]
@KyleAMathews Do you think you can help having an eyes on this PR?
This has been blocking https://github.com/Js-Brecht/gatsby-plugin-ts-config/issues/29

**Comment by Js-Brecht** [comment]
@alvis I appreciate you trying to get some action on this, but I have begun a v2 of the plugin that would render this PR unnecessary.  It’s just taking a little bit longer than I hoped it would because of how swamped I have been with my real job.  I will add some notes to the other ticket

I think we can just close this one, unless you think it may have some other value @vladar (or @KyleAMathews)

**Pull request closed without merging**
