### PR TITLE
feat(gatsby-link): adds support for partiallyActive=true to Link

### LINKED ISSUE #7208: Add option to gatsby-link for matching active when on child routes
## Summary

Would be great to mirror reach router's `isCurrent` and `isPartiallyCurrent` options to `gatsby-link`s `activeStyle` and `activeClassname` props. Basically I'd want to be able to designate a Link as active when any child routes are also active, without having to bypass gatbsy-link and use `isPartiallyCurrent` directly. 

### Basic example

Hesitant to suggest just tacking on another prop as lazy DX, but that would probably make the most sense. Something like this:

```js
<Link ... activeStyle={{...}} greedyActive={true} />
```

Would default to false, so non-breaking change that doesn't really add much cognitive overhead for people.

### Motivation

Common use-case is top-level nav for any nested content (eg: a blog), where you'd often want to designate the nav item active (eg: 'Blog') when on a child path (eg: `/blog/some-post`).

If this isn't added, would at least be worth documenting how to achieve by accessing react router APIs directly in gatsby-link docs, as I imagine it's a common pattern.

### PR DESCRIPTION
**Pull request by arcanis**
## Description

Implements a new option in the `<Link/>` component: `partiallyActive={bool}`. If true, the route will activate its `activeStyle` and `activeClassName` parameter even if only partially active.

I've put the settings on the component rather than the route, as there might be places where you want this settings to be on and others where you want it to be off. Also it was simpler 🙂 

I've also moved `@reach/router` into the peerDependencies (from the regular dependencies) since it's a stateful package (due to the context ref) and you don't want to run the risk of having version conflicts. It shouldn't be a problem because the `gatsby` package already provides `@reach/router`.

## Related Issues

Fixes #7208

### CODE REVIEW

**Comment by arcanis** [comment]
Here's the cherry! I won't have the time to make an egghead video, though 😄

**Comment by DSchau** [comment]
```
Successfully published:
 - gatsby-link@2.0.16
 - gatsby@2.1.31
```

**Comment by dustinhorton** [comment]
curious about that gatsby-link version—I'm on latest Gatsby (`2.1.35`), and `partiallyActive` is not working, and if I look at my lockfile, I'm only on gatsby-link `2.0.6`.

Are we not supposed to import gastby-link via Gatsby anymore?

**Comment by lmcjt37** [comment]
@dustinhorton try running `npm update -S gatsby` this updated my Gatsby package and also included the addition of `partiallyActive`. Fixed my issue where the prop didn't exist.

**Comment by dustinhorton** [comment]
@lmcjt37 what's the `-S` flag? not seeing it @ https://docs.npmjs.com/cli/update.html

**Comment by lmcjt37** [comment]
@dustinhorton sorry my fault, that's second nature to add the --save flag. `npm update gatsby` should update your package. But if you're on 2.1.35 then you should be able to use the `partiallyActive` prop now?

**Comment by dustinhorton** [comment]
Now on `2.2.9`, and it has gatsby-link `2.0.16` but `partiallyActive` still isn't working for me.

Tried with both `activeClassName` and `activeStyle` props.

**Comment by lmcjt37** [comment]
@dustinhorton Do you have an example of how you're using Gatsby-Link? Maybe I can help identify the issue

**Comment by dustinhorton** [comment]
@lmcjt37 Thanks for the offer—caused me to take _another_ fresh look and I realized the error in my implementation (just some leftover destructuring from when I was handling it myself).

**Comment by lmcjt37** [comment]
@dustinhorton Awesome! Glad you managed to fix it 👍

**Comment by imshuffling** [comment]
Thanks for doing this.

As I'm bringing my navigation in dynamically I had to add a conditional to the activeClassName to stop the homepage menu item being rendered as active.

Leaving this here as it might help someone.

```                
<Link partiallyActive={true} activeClassName={slug === '/' ? null : 'active'}>
   {item}
</Link>

**Comment by gpspake** [comment]
I run in to a similar issue where the home `/` link is always active when partially active is set to true.

**Comment by gpspake** [comment]
I ran in to a similar issue where the home `/` link is always active when `partiallyActive` is set to true but my navigation is kinda fancy so I had a slightly different fix. Mine ended up looking like
```jsx
<Link
  key={page.name}
  className={navigationStyles.navLink}
  to={page.link}
  partiallyActive={true}
  activeStyle={page.link === '/' && pathname !== '/' ? {} : { background: "#0084B4" }}
  >
  {page.name}
</Link>
```
It aint pretty but it works...

Here's the navigation component where I used it, for context. I also had to import `Location`:
```jsx
import React from 'react'
import { Link, StaticQuery } from "gatsby"
import navigationStyles from "./navigation.module.scss"
import { Location } from '@reach/router';

const Navigation = props => {
  const { menuLinks } = props.siteMetadata
  const { pathname } = props.location

  return (
    <div className={navigationStyles.siteNavigation}>
      <nav >
        {menuLinks.map(page => (
          <Link
            key={page.name}
            className={navigationStyles.navLink}
            to={page.link}
            partiallyActive={true}
            activeStyle={page.link === '/' && pathname !== '/' ? {} : { background: "#0084B4" }}
          >
            {page.name}
          </Link>
        ))}
      </nav>
    </div>
  )
}

export default () => (
  <Location>
    {locationProps => <StaticQuery
      query={graphql`
      query {
        site {
          siteMetadata {
            menuLinks {
              name
              link
            }
          }
        }
      }
    `}
      render={data => <Navigation {...locationProps} siteMetadata={data.site.siteMetadata} />}
    />}
  </Location>
)
```
Thanks for the tip, @imshuffling

**Pull request merged**
