### PR TITLE
[WIP] : Use the sync endpoint to pull data from Contentful 

### PR DESCRIPTION
**Pull request by Khaledgarbaya**
## Summary
This PR kinda rewrite the contentful source plugin to use sync endpoint to pull data. This PR is still a WIP also I would like to have some feedback about how we can store the cached data better.
The ci may fail also

## Why this PR?
Using sync endpoint will make the build time lower and lower since you are pulling only the changed data.
The amount of request will be lower compared to the old approach since we can get entries and assets in the same payload.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 5b7152c78b2cc861103f792cf6138f6e4def43bf

https://app.netlify.com/sites/using-contentful/deploys/594cffa9cf321c4cb38b3a05

**Comment by KyleAMathews** [comment]
Woah hey! Thanks for stopping by :-) These changes look great! I think this source plugin is about finished with this and localization support (working on that early next week).

On storing the last fetched time, there's a Gatsby API for this exact purpose. Plugins can set "status" data of any sort — https://www.gatsbyjs.org/docs/bound-action-creators/#setPluginStatus

This is how you get the status back on the next run. Really should add an equivalent `getPluginStatus` helper actually... https://github.com/gatsbyjs/gatsby/blob/1.0/packages/gatsby-source-drupal/src/gatsby-node.js#L42

**Comment by Khaledgarbaya** [comment]
🎉  that's exactly what I need Thanks a lot

**Comment by Khaledgarbaya** [comment]
hi @KyleAMathews ,
I'm almost done here I might need your help in the image manipulation using graphql.
the problem is when you call sync you get the data in this format `fieldName: {'locale': 'value'}` same for assets the file property will be `{file: {'locale': {url:'imageurl', ...}}}` I manged to get the text content and tried a workaround for the assets but seems that I'm missing something. Can you take a look maybe you can spot what I'm doing wrong there . This is the error `NHANDLED REJECTION Error: ContentfulAsset.responsiveResolution field type must be Output type`.

screen shot 2017-06-24 at 15 58 53

**Comment by KyleAMathews** [comment]
Yeah so when @mericsson first wrote this plugin and I made some extensions, neither of us realized that when you fetched additional locales it'd change the shape of data. I was planning on adding support for that Monday.

The easiest way to fix this would be to update the tests for image generation. There's an image object hard-coded. Update that to add locale and then fix the tests.

**Comment by Khaledgarbaya** [comment]
@KyleAMathews @mericsson I think I will your help on updating the entryNode schema to support the locales, since I'm kinda a graphql n00b. we can for now resolve to the default locale and later extends it

**Comment by KyleAMathews** [comment]
Hey, if you want to just get this working with the default locale that'd be great. I was already planning on adding support for more locales tomorrow.

**Comment by KyleAMathews** [comment]
Or oh wait so you're saying you need help getting this to work with the graphql stuff? If you want I can take this over tomorrow. Don't have time today to give detailed help right now.

**Comment by Khaledgarbaya** [comment]
That would be great if you can test this with the example `using-contentful`, you will maybe spot it faster than me, otherwise I will try to find some time for it this week, worse case scenario, next weekend :/

**Comment by Khaledgarbaya** [comment]
👋  is there a way to debug the graphql schema ?

**Comment by KyleAMathews** [comment]
@Khaledgarbaya hey! This is looking awesome! I'm going to just merge this in and then do another quick PR to fix the graphql query error. Getting sync support is huge. Really glad you've hopped in to help build this out 🙏

**Comment by Khaledgarbaya** [comment]
@KyleAMathews wooohoo 🎉  glad to help.

**Comment by jlengstorf** [comment]
Hiya @Khaledgarbaya! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
