### PR TITLE
fix(starters):replace all old links with correct ones

### PR DESCRIPTION
**Pull request by thecodingaviator**
Does what it says on the label

### CODE REVIEW

**Comment by thecodingaviator** [comment]
Somebody help me with why the tests are failing 🤦‍♂

**Comment by wardpeet** [comment]
Hey! Thanks for opening a pull request!

The change you’ve proposed is not going to be accepted because the `gatsby.dev` links are shortlinks which redirect to the correct page. If we ever change the page we just need to change the redirect.

We absolutely want to have you as a contributor, so please take a look at our open issues for ideas, and please reach out to us on Twitter at @gatsbyjs with questions.

Thanks again, and we look forward to seeing more PRs from you in the future! 💪💜

**Comment by thecodingaviator** [comment]
Woop! I missed something, I typed something which wasn't redirecting maybe a copy-paste error

**Comment by wardpeet** [comment]
No problem, we appreciate you taking to time to trying to fix this! ❤️

**Pull request closed without merging**
