### PR TITLE
Topics/update prismjs language dependencies

### PR DESCRIPTION
**Pull request by fyrkant**
Updated the `prismjs-language-dependencies.js` file to add some more languages that prismjs supports.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Ah nice! Thanks for updating the language list :-) Forgot about that. Curious if there's a way to automate updating?

Looks like some of the snapshots you updated didn't need updated? TravisCI is failing.

**Comment by fyrkant** [comment]
Hmm, the snapshots failed without updating for me, weird... Should I revert them?

But yeah, automating the language list update shouldn't be that hard, might worth looking into!

**Comment by KyleAMathews** [comment]
It's odd your snapshots are turning up differently than travisci — could you try investigating a bit why? But in any case, yeah, revert the snapshot changes that are causing trouble on Travis.

**Comment by fyrkant** [comment]
Reverted and travis seems happy!

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by jlengstorf** [comment]
Hiya @fyrkant! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
