### PR TITLE
doc: add webpack+JSON example

### PR DESCRIPTION
**Pull request by revolunet**
related to #484

### CODE REVIEW

**Comment by KyleAMathews** [comment]
JSON doesn't work? Hmmm… we already have the JSON loader included https://github.com/gatsbyjs/gatsby/blob/3449cbfc461ac912e66e7fcd62a3f48f0e754bdd/packages/gatsby/src/utils/webpack.config.js#L376

**Comment by revolunet** [comment]
ok so my bad, this is about another issue, where json in node_modules arent loaded

Without the json extension specified, these modules cannot load for me :

capture d ecran 2017-10-03 a 00 33 08

After digging a bit, looks like both of these files are json :
 - https://github.com/syntax-tree/hast-util-sanitize/blob/master/lib/index.js#L5
 - https://github.com/wooorm/remark/blob/master/packages/remark-parse/lib/defaults.js#L9

**Comment by KyleAMathews** [comment]
Hmmm yeah it's not conventional to support loading `.json` files *without* specifying their extension.

These look like node packages though — why are you loading them in the browser?

**Comment by revolunet** [comment]
(they specify `.json` in the source)

for some reason i have a legacy UI component that use remark which use these modules

**Comment by wooorm** [comment]
Those packages used to load without the `.json` extension. If you have `hast-util-santize@1.1.2` and `remark-parse@8.0.0` it should work!?

**Comment by KyleAMathews** [comment]
Would love to have more examples on modifying webpack! But closing this one as JSON support should be enabled already.

**Pull request closed without merging**
