### PR TITLE
[WIP] chore(www): add tabindex attr to Img components in home-logo-banner (#22383)

### PR DESCRIPTION
**Pull request by shrthnd**
### Description

This pull-request attempts to improve the keyboard-nav experience of the homepage-logo-banner section. 
 
### Documentation

The changes here were modeled after original approach in PR, ongoing issue feedback, and the approach used in the [homepage-blog-post](src/components/homepage/homepage-blog-post.js) component. 

Changes here were tested on Chrome, Firefox, and Safari in OS X (using Voiceover), and Chrome, Firefox, IE11, and Edge in Windows 10 using NVDA. 

* Firefox in OS X is a mess--seems okay using NVDA in Windows 10.
* Chrome seems okay. Works better using the modified navigation or NVDA than with standard tabbing
* Safari was fine
* Edge and IE11 were okay, but only when the issue noted below isn't present. It's not obvious to me whether this is a more deeply nested issue, only occuring when running `gatsby develop`, or if this would be resolved during `gatsby build` (I need a GitHub token set up to build?)

## Related Issues
* #22214
* This [pull request](https://github.com/gatsbyjs/gatsby/pull/22383/commits/0c55723a596b183fb141fc8ea116d29558e4d7f5) related to the original issue

### To-do

When testing in IE11/Edge I encountered the following error:

image

This is reproducible, but also seems to be triggered (occasionally) on the homepage-blog-post section, which makes me think it's a deeper issue. Did I overlook some part of the HorizontalScroller component or is this a side-effect of running `gatsby develop`? 

Note: after additional testing, it looks like horizontal scrollbar is missing on mobile breakpoints, so it's not possible to pan left-right on these logos without using keyboard nav or swiping. Any feedback here would be much appreciated--I'm happy to revisit this pull-request if this solution looks like it's on the right track.

### CODE REVIEW

**Comment by pvdz** [comment]
Thanks @shrthnd for picking up this PR. I'm going to leave it for the @gatsbyjs/website people to review.

**Comment by marcysutton** [comment]
Hey there, thanks for the PR! It has a pretty major change that still needs to be made, which I mentioned in the original PR: the wrapper element for the logos should be the focusable thing that scrolls, not the individual logos. The current implementation forces keyboard users to focus on every logo image, which even though it does technically make the group scrollable with the keyboard, also makes non-interactive images focusable but not operable.

For the issue to be satisfied, the wrapper element with horizontal scrolling alone should have `tabindex: 0` so it can be scrolled with the arrow keys. People do use Bluetooth keyboards with mobile devices in addition to other assistive technologies and swiping.

Let me know if you have any questions about the above, I'm happy to explain further!

**Comment by shrthnd** [comment]
Thank you for the feedback. The latest commit in this branch moves the z-index/focus-ring from the logo elements, to the scrollable/interactive wrapper (let me know if you see any further issues here.)

**Comment by marcysutton** [comment]
Thanks for making updates! I looked at the code, and I'm not sure it needs to this complex. My recommendation would be to keep it simple and create one region with tabindex on it, and you might not even need the special styling. This section may be getting design updates soon too, so I wouldn't want you to put much more time into it! Let me know what you think.

**Comment by shrthnd** [comment]
> keep it simple and create one region with tabindex on it, and you might not even need the special styling

Sounds like a plan, @marcysutton. My latest commit here reverts the homepage-logo-banner to its original state, and adds a tabindex to the surrounding element.

**Pull request merged**
