### PR TITLE
Ignore 405 responses from drupal jsonapi

### LINKED ISSUE #7075: Plugin gatsby-source-drupal returned an error
### Steps to reproduce

Installed Drupal8 on localhost
Installed JSON api module and gave anonymous users permission
Installed gatsby drupal module
Entered baseurl and apibase correctly
my http://localhost/jsonapi is returning valid json and I can curl it perfectly

### Expected result

Should run without errors

### Actual result

Throws 405 error:
error Plugin gatsby-source-drupal returned an error
Error: Request failed with status code 405

### Environment

  System:
    OS: macOS High Sierra 10.13.3
    CPU: x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.9.4 - /usr/local/bin/node
    npm: 6.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.84
    Safari: 11.0.3
  npmPackages:
    gatsby: ^1.9.277 => 1.9.277 
    gatsby-link: ^1.6.46 => 1.6.46 
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11 
    gatsby-source-drupal: ^2.0.41 => 2.0.41 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

### PR DESCRIPTION
**Pull request by tmccombs**
Fixes #7075

This should probably be applied to version 1 as well, should I create a seperate PR for that?

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 79a8bbee5ae2c49801f0e7c720b25695b2aad203

https://app.netlify.com/sites/using-postcss-sass/deploys/5b732621792f8926aabec8aa

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 79a8bbee5ae2c49801f0e7c720b25695b2aad203

https://app.netlify.com/sites/gatsbyjs/deploys/5b73261f792f8926aabec89e

**Comment by tmccombs** [comment]
the failed builds look unrelated to my changes

**Comment by KyleAMathews** [comment]
And yeah, the errors are unrelated. It looks like the registry was down temporarily which caused some of the site builds / tests to fail.

**Comment by m-allanson** [comment]
> This should probably be applied to version 1 as well, should I create a seperate PR for that?

That would be great, thanks 👍

**Pull request merged**
