### PR TITLE
Added blog post on <img/> tags

### PR DESCRIPTION
**Pull request by chiedo**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hey, thanks for starting this! I was thinking though, since there's already a responsive image page, that you add just add another paragraph/image there. Maybe just before https://deploy-preview-1291--using-remark.netlify.com/responsive-images-and-iframes/#okay-nice-but-what-about-gifs

The text would explain how you can use both syntaxes and you could add code snippets for both then an image that's 1/2 width and floated to the right or whatever.

How's that sound?

**Comment by chiedo** [comment]
Haha I completely misunderstood your request.

This makes much more sense.

Will do

**Comment by chiedo** [comment]
I didn't see any place that made sense for me to add an image but I updated the existing post and added code samples. 

Let me know if you want the commits squashed.

😄

**Comment by KyleAMathews** [comment]
No need to squash commits as I squash everything when merging PRs :-) thanks for the update! And the original PR of course :-D

**Comment by chiedo** [comment]
My pleasure! :)

**Pull request merged**
