### PR TITLE
Update broken `using-page-transitions` example

### LINKED ISSUE #7603: examples/using-page-transitions/ does not transition out
## Description

The example "using-page-transitions" stopped working correctly. Specifically, it does not seem to perform a "transition-out". When navigating, the current page should fade out before the next page fades in.

I was relying on this example for my website, and I noticed this problem today, when upgrading from `2.0.0-beta.67` to `2.0.0-rc.0`.

### Expected result

When navigating, the current page should fade out before the next page fades in.

### Actual result

The current page does not fade out, but disappears abruptly, and the next page immediately fades in.

### Environment

  System:
    OS: OS X El Capitan 10.11.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    npm: 6.2.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 9.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.0
    gatsby-plugin-react-helmet: next => 3.0.0-rc.0
  npmGlobalPackages:
    gatsby: 2.0.0-rc.0

### PR DESCRIPTION
**Pull request by fabe**
This fixes the `using-page-transitions` example which was still using React Router APIs and therefore was broken with the latest betas. Instead of `react-transition-group` I'm using `react-pose`, which simplifies this whole process quite a bit. Not sure if this should be a separate example then?

Closes #7603.

<sub>Oh, and because of #7564 I'm using the same exact code in both `gatsby-browser.js` and `gatsby-ssr.js`. Also, props to [this guide](https://popmotion.io/pose/learn/route-transitions-reach-router/).</sub>

### CODE REVIEW

**Comment by LeKoArts** [comment]
Thanks, will have a look at the example then :)

**Comment by cpboyd** [comment]
@fabe I think, given [gatsby-plugin-layout](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-layout/src), the expected usage of `wrapPageElement` is that it's included in both `gatsby-browser.js` and `gatsby-ssr.js` as you've done.

Keep in mind, that I think it's currently being applied twice in the `build` / production version (per [my comment](https://github.com/gatsbyjs/gatsby/issues/7564#issuecomment-415501551) on the bug).

**Comment by nopjia** [comment]
Great. Will be waiting for update for #7603.

**Comment by KyleAMathews** [comment]
Thanks for the PR! Looks great!

`react-pose` is awesome — one downside though is that for simple uses, it's a lot more code than `react-transition-group` — ~20kb vs ~5kb. Could we switch back to `react-transition-group` and add a note to the README that `react-pose` is awesome for more complex transitions? And if you're interested, PR a fully decked out example of a Gatsby site with complex transitions using react-pose.

**Comment by fabe** [comment]
@KyleAMathews I've been trying to get page transitions work with the new Reach Router integration, however it doesn't seem to be possible to animate only parts of a page with `react-transition-group`+`@reach/router`+`gatsby` due to the `Router` being wrapped around the page entirely (and delaying the route change is not possible either). Only if the header/nav and the Router are separated we can achieve the split animations (e.g. [this example](https://codesandbox.io/s/18282617n3)).

This is as far as I can take it with `react-transition-group`, but I'd love to hear any other ideas:

kapture 2018-08-29 at 13 45 57

<sup>Notice the header being animated as well.<sup>

I could prepare this as the "simple" example and add a `-complex` one using `react-pose`, but it does change the previous, v1 behavior:

kapture 2018-08-29 at 14 06 01

**Comment by KyleAMathews** [comment]
Perhaps try using gatsby-plugin-layout? https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-layout/README.md

@pieh added it to restore the v1 layout behavior for those that need it e.g. for stuff like this.

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit c04e780a3b9295ea490749b82d940e9729a46dc5

https://app.netlify.com/sites/using-glamor/deploys/5b86f41dc6aed677709eff15

**Comment by KyleAMathews** [comment]
Deploy preview for *using-styled-components* failed.

Built with commit c04e780a3b9295ea490749b82d940e9729a46dc5

https://app.netlify.com/sites/using-styled-components/deploys/5b86f41dc6aed677709eff18

**Comment by fabe** [comment]
Thanks for the suggestion, that works! 👊

I'll PR the `react-pose` example after this is merged.

**Pull request merged**
