### PR TITLE
Guest post - Modern Static Generation w/ Gatsby

### PR DESCRIPTION
**Pull request by kbariotis**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hey so the blog template currently requires post have a template. Would you like to pick one out from unsplash or wherever?

**Comment by KyleAMathews** [comment]
Ahem. Each post have an image (in the frontmatter).

**Comment by kbariotis** [comment]
yeah sorry didn't try to build before pushing. :)

**Comment by KyleAMathews** [comment]
And looking forward to this going live!

**Comment by kbariotis** [comment]
Looks sleek! :)

**Comment by KyleAMathews** [comment]
Here's the public preview link :-) https://deploy-preview-2143--gatsbyjs.netlify.com/blog/2017-09-18-gatsby-modern-static-generation/

**Comment by KyleAMathews** [comment]
Hoping on the plane now but will deploy it Monday morning 💯

**Comment by sebastienfi** [comment]
Looks good !

**Pull request merged**
