### PR TITLE
Update starters.yml

### PR DESCRIPTION
**Pull request by billp72**
## Description

Gatsby eCommerce starter blog with contentful

# Features
* contenful 
* snipcart
* stripe
* algolia search
* blogging
* e-commerce
* PWA (Progressive web app)
* BundleAnalyzerPlugin (run gatsby build to see heatmap)
* modal (displays for first-time visitors using cookies)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hi, looks like some of your tags aren't one of the allowed ones https://github.com/gatsbyjs/gatsby/runs/532438906

**Comment by KyleAMathews** [comment]
Hmm also the linked starter repo isn't there anymore so I guess you've abandoned this? Please open a new PR when the starter is ready to go!

**Comment by billp72** [comment]
To open a new PR, do I have to fork the repo and add my code to a clone?

thanks

**Comment by laurieontech** [comment]
We have a doc for that! https://www.gatsbyjs.org/contributing/submit-to-starter-library/

**Pull request closed without merging**
