### PR TITLE
[v2] Upgrade to v3

### PR DESCRIPTION
**Pull request by jquense**
upgrades web pack to v3 and updates the webpack-utils api to be more consistent.

I’d like to just user webpack-atoms and remove a bunch of code here, but at the moment it’s not structured super well for the gatsby use-case i need to change stuff a bit

### CODE REVIEW

**Comment by jquense** [comment]
so i'm fairly sure the only reason Appveyor is failing is because the build setup for example sites uses gatsby-dev which doesn't handle updates to depedencies, so its using webpack1

**Comment by RomanGotsiy** [comment]
Hey @jquense,

Great job with this! Any ETA when this PR is merged?
Can I help somehow?

**Comment by jquense** [comment]
i'm theoretically waiting for @KyleAMathews new testing infrastructure so i can properly test this. IF you need webpack 2+ support the current gatsby v2 prereleases already have v2, this is just a minor upgrade to v3 there

**Comment by scottyeck** [comment]
Also happy to pitch in if I can. @jquense KILLER work putting a dent in the webpack upgrades.

**Comment by jquense** [comment]
Just to be clear folks :)  this is a PR to the v2 branch it won't make it into gatsby v1

thanks for the offers of help, this is done really, we just need to get some testing done

**Comment by KyleAMathews** [comment]
@jquense check this out! https://twitter.com/dan_abramov/status/951427300070916096

**Comment by KyleAMathews** [comment]
@jquense assuming this is good to go :-)

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
