### PR TITLE
chore(starters): Created a Template using Shards UI library

### PR DESCRIPTION
**Pull request by wcisco17**
I've been using Shards UI for 3 of my projects now, and I was getting really tired of repeating myself every project. To avoid this redundancy I created a special template that uses all of the standards to start your own Gatsby Project. Those are typescript, styled-components, and a UI framework.

## Description

I mostly created this out of frustration from having to recreate the same type of projects every time, I hope it serves everyone in terms of getting up to speed with Shards UI - which is a clean React UI library. Embedded in the starter is typescript, styled-components, and bootstrap.
 
### Documentation

The documentation should be [here](https://github.com/wcisco17/gatsby-typescript-shards-starter)

### CODE REVIEW

**Comment by wcisco17** [comment]
Hey my test failed on CircleCI anyway I can update it?

**Comment by laurieontech** [comment]
Thanks for the PR! The failing tests are unrelated to your additions.

I noticed that your README is using `yarn start` rather than `gatsby develop`. Can you update that? We're trying to keep consistency across starters.

**Comment by wcisco17** [comment]
Hey @laurieontech, just updated my repo thanks for the feedback.

**Comment by laurieontech** [comment]
Did you mean to close this?

**Comment by wcisco17** [comment]
Hey sorry lol I accidentally closed this Reopening it now.

**Comment by laurieontech** [comment]
Thanks for the PR!

**Pull request merged**
