### PR TITLE
docs(api-proxy): update code exmaple with explicit require

### PR DESCRIPTION
**Pull request by hangindev**
## Description

The code examples for advanced proxying and self-signed certificates use package `http-proxy-middleware` which introduces a breaking change in the latest version `v1.0.0`. ([release notes](https://github.com/chimurai/http-proxy-middleware/releases))

require/import of http-proxy-middleware is now explicit.

`v0.x.x` with implicit require

`const proxy = require('http-proxy-middleware');`

`v1.0.0` with explicit require

`const { createProxyMiddleware } = require('http-proxy-middleware');`

### Documentation

[https://www.gatsbyjs.org/docs/api-proxy/#advanced-proxying](https://www.gatsbyjs.org/docs/api-proxy/#advanced-proxying)

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! This is definitely a good thing to update.

However, as the plugin notes, anyone using a previous version should follow the old example. Perhaps we can add a note that explains the alternative and what version it applies to? 

It makes sense for the main example to be up to date with the latest plugin, so everything thus far should stay.

**Comment by hangindev** [comment]
Thanks Laurie.

How about I add two lines of comments below the require statement?
```
const { createProxyMiddleware } = require('http-proxy-middleware') 
// Use implicit require for v0.x.x of 'http-proxy-middleware'
// const proxy = require('http-proxy-middleware')
```

**Comment by laurieontech** [comment]
That seems like a good solution. Perhaps a third comment should say: 
// be sure to replace createProxyMiddleware with proxy where applicable

**Comment by laurieontech** [comment]
Awesome! Thanks

**Pull request merged**
