### PR TITLE
chore(docs): Update schema doc to second person reference

### PR DESCRIPTION
**Pull request by sagarnasit**
issue: #18284

### CODE REVIEW

**Comment by LekoArts** [comment]
Hi, thanks for the PR!
However, in this current state we can't merge it as your changes are wrong referring to this paragraph in our docs:

> When updating a doc to adhere to this part of the Gatsby Style Guide, one exception in English is when “we” refers to Gatsby’s core processes. The subject is the code in this case, rather than a teacher/reader connotation, and should be rewritten or restructured to not confuse the reader about what they are responsible for doing when something is happening automatically behind the scenes.

Please change your PR accordingly as switching we with you is not appropriate here. Thanks!

**Comment by sagarnasit** [comment]
@LekoArts Updated the doc.

**Comment by marcysutton** [comment]
Hi there, the changed file still has the word "we" in it. Can you update it to follow the style guide to use Gatsby as the subject?

**Comment by sagarnasit** [comment]
Done.

**Comment by LekoArts** [comment]
Hi, I'm closing this PR since the current state of this PR is not addressing our comments. Changing we to you isn't enough in this context.
Feel free to open a new PR when you've made those changes. Thanks!

**Pull request closed without merging**
