### PR TITLE
chore(gatsby-plugin-preload-fonts): Use createContentDigest helper

### PR DESCRIPTION
**Pull request by muescha**
## Description

use `createContentDigest`

updated tests

## Related Issues

#8805 feat: update gatsby plugins to use new createContentDigest helper

### CODE REVIEW

**Comment by muescha** [comment]
### need help

@freiksenet i need help to fix this

the problem with both failing test is that the new hashes are different on my local machine


steps i have done:

### run test on Node 12

run test locally on v12.13.1 with out errors

### run test on Node 8

i and i also switched to Node v8.17:

```bash
$ nvm list
->      v8.17.0
       v10.15.3
       v12.13.1
        v13.0.1
        v13.1.0
         system
default -> v12.13.1
node -> stable (-> v13.1.0) (default)
stable -> 13.1 (-> v13.1.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/erbium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0
lts/dubnium -> v10.18.0 (-> N/A)
lts/erbium -> v12.14.0 (-> N/A)
[09:29:49] muescha@Michaels-MacBook-Pro-2:~/Work/gatsby/github/gatsby/packages/gatsby-plugin-preload-fonts 
```


but still the tests passing with the new hashes:

```bash
$ jest

 RUNS  src/__tests__/fetch-routes.test.js

 RUNS  src/__tests__/fetch-routes.test.js

 RUNS  src/__tests__/fetch-routes.test.js
 PASS  src/__tests__/utils.test.js

 RUNS  src/__tests__/fetch-routes.test.js

 RUNS  src/__tests__/fetch-routes.test.js
 PASS  src/__tests__/cache.test.js

 RUNS  src/__tests__/fetch-routes.test.js
 PASS  src/__tests__/gatsby-ssr.test.js

 RUNS  src/__tests__/fetch-routes.test.js
 PASS  src/__tests__/index.test.js
  ● Console

    console.log src/prepare/logger.js:49
      undefined

 PASS  src/__tests__/logger.test.js
 PASS  src/__tests__/fetch-routes.test.js

Test Suites: 6 passed, 6 total
Tests:       20 passed, 20 total
Snapshots:   6 passed, 6 total
Time:        3.237s
Ran all test suites.
```

### check master tests

- the test on master branch (without my changes) also run without errors

**Comment by pieh** [comment]
That's very weird, I'll take a look at this

**Comment by pieh** [comment]
Can you run `yarn bootstrap` in root of repository and try rerun tests again? I suspect that you might not have built `gatsby-core-utils` recently and if your built version is from before https://github.com/gatsbyjs/gatsby/pull/19832 it could explain difference in generated hashes

(I get the same results as on CI locally)

As for node 8 vs other node versions - we just run this first and don't run more (potentially long) checks if it fails, so it doesn't mean that it's node version related issue

**Comment by muescha** [comment]
Ah ok. That was my idea with the node version

Good catch. That maybe is different. I will rerun bootrap again later and try it again

**Comment by muescha** [comment]
bootstrapped and now my local hashes the same as CI - now test run successful

thanks @pieh for help

**Pull request merged**
