### PR TITLE
[www][showcase] Add dynamic shadows to Collapsible component, indicating content overflow

### PR DESCRIPTION
**Pull request by ryanditjia**
Refs: https://github.com/gatsbyjs/gatsby/issues/6735

Closes half the issue. With this PR, Collapsible component now has dynamic shadows to indicate content overflow.

### CODE REVIEW

**Comment by ryanditjia** [comment]
Hi there, @fk. I haven’t tried running it locally again, as `source and transform nodes` seem to take forever on my machine. But checking the deploy preview (https://deploy-preview-6957--gatsbyjs.netlify.com/showcase), it seems that my Chrome (also in Mac) behave the same as other browsers. Can you check with all extensions turned off?

I’ll change the styling, just have to wrap my head around gradient’s syntax 😄

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit edab3f1480687986ad7620d773937012442a44cb

https://app.netlify.com/sites/gatsbyjs/deploys/5b6d5413fdd72a48c8b2891d

**Comment by fk** [comment]
> Can you check with all extensions turned off?

I tested in incognito mode and unfortunately still see the same. :/

> I haven’t tried running it locally again, as source and transform nodes seem to take forever on my machine.

I noticed that you merged master -- could you try deleting `yarn.lock` and reinstall deps? Also to speed up things locally, I delete most of the data for the site showcase in `docs/sites.yml` so it looks like this:

```
- title: ReactJS
  main_url: 'https://reactjs.org/'
  url: 'https://reactjs.org/'
  source_url: 'https://github.com/reactjs/reactjs.org'
  featured: true
  categories:
    - Web Dev
    - Featured
- title: NEON
  main_url: 'http://neonrated.com/'
  url: 'http://neonrated.com/'
  description: "Foo"
  featured: true
  categories:
    - Gallery
    - Cinema
    - Featured
- title: The State of European Tech
  main_url: 'https://2017.stateofeuropeantech.com/'
  url: 'https://2017.stateofeuropeantech.com/'
  featured: true
  categories:
    - Featured
    - Technology
  plugins: 'gatsby-plugin-react-helmet, gatsby-plugin-react-next'
  built_by: Studio Lovelock
  built_by_url: 'http://www.studiolovelock.com/'
```

**Comment by ryanditjia** [comment]
Thanks for your tip on how to speed up local development. Haven’t had time to fix this PR as I’m facing a work deadline! Will definitely fix this soon 🙏

**Comment by fk** [comment]
👍 No worries @ryanditjia! Good luck with the deadline! 🤗

**Comment by amberleyromo** [comment]
Hey @ryanditjia -- any interest in circling back to this?

**Comment by ryanditjia** [comment]
Hi @amberleyromo. Thanks for the reminder. Unfortunately, I’m not in love with the implementation after all, the way the shadows appear just look weird. Going to close this PR.

**Pull request closed without merging**
