### PR TITLE
chore(starter): Add minimal Typescript starter

### PR DESCRIPTION
**Pull request by marvinjude**
## Description

Adds minimal TypeScript Starter `gatsby-starter-minimal-ts`

see  -  https://github.com/gatsbyjs/gatsby-starter-minimal

### CODE REVIEW

**Comment by LekoArts** [comment]
We don't want to use the canary yet, the starter should only use things that are stable and tested. Initially I wanted this also in there but we shouldn't block the CLI work by this.

**Comment by marvinjude** [comment]
Yup same thoughts too. Wanted to put it up temporarily.. Ideally the tests shouldn't be failing right?

**Comment by LekoArts** [comment]
It uses 4.6.1 and not the canary I think

**Comment by LekoArts** [comment]
We'll need to add `gatsby-starter-minimal-ts` here, too: https://github.com/gatsbyjs/gatsby/blob/master/scripts/publish-starters.sh#L40

**Comment by LekoArts** [comment]
Heh, did mean to commit this to the PR, not on `master`: https://github.com/gatsbyjs/gatsby/commit/130d1dc634144d2cd541f844a120342d3aa1f239

But yeah, it's in there now 😅

**Review by LekoArts — APPROVED** [review]

**Pull request merged**
