### PR TITLE
fix links in blog post and plugin readme

### LINKED ISSUE #4964: internal, absolute links broken in documentation
Links such as this one are broken.

at /docs/blog/2018-01-22-getting-started-gatsby-and-wordpress/index.md: 

`([Source](https://www.gatsbyjs.org/docs/api-specification/#concepts)).`
leads to
`https://www.gatsbyjs.org/blog/2018-01-22-getting-started-gatsby-and-wordpress/https://www.gatsbyjs.org/docs/api-specification/`

I made a couple of these links relative, and that fixes them, but perhaps this is a configuration issue?

### PR DESCRIPTION
**Pull request by Strangehill**
Ref #4964

### CODE REVIEW

**Comment by pieh** [comment]
Gatsby recently added a requirement that contributors sign-off commits. Could you do 
```
git commit --amend -s
``` 
and force push the amended branch?

Check out the new [Developer Certificate of Origin docs](https://www.gatsbyjs.org/docs/how-to-contribute/#developer-certificate-of-origin) or comment here if you've any questions.

**Comment by Strangehill** [comment]
Got it. Done. Thx!

**Comment by m-allanson** [comment]
Adding a note that the source of this problem is described in #4964.

**Comment by KyleAMathews** [comment]
Thanks for the fixes!

**Comment by jlengstorf** [comment]
Hiya @Strangehill! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
