### PR TITLE
chore(starter): add Kentico Kontent Intranet showcase

### PR DESCRIPTION
**Pull request by Simply007**
## Description

New Intranet stater using Kentico Kontent as a data source.

### Documentation

Used these [instructions for submittions](https://www.gatsbyjs.org/contributing/submit-to-starter-library/).

### CODE REVIEW

**Comment by pvdz** [comment]
(Hey, yeah I only triaged it, put the right label on the PR etc. Somebody from the learning team will eventually pick up your PR and process it. This sometimes takes time, sorry about that.)

**Comment by Simply007** [comment]
> Somebody from the learning team will eventually pick up your PR and process it. This sometimes takes time, sorry about that.)

Thx for answer @pvdz 
I suppose I shouldn't I should run `npm audit` in this pull request to pass the circle ci pipeline, right?

**Comment by pvdz** [comment]
As a sanity check, yes, to make sure it's not your starter that's causing this. It's more than likely one of the others has a dependency on something that trips on npm audit, though. Such is the way of it.

**Comment by Simply007** [comment]
Still nobody from @gatsbyjs/learning? 😿

**Pull request merged**
