### PR TITLE
feat(gatsby-source-contentful): Remove default image transform width

### LINKED ISSUE #14156: [gatsby-source-contentful] Image transforms still have default width
## Description

[This pull request](https://github.com/gatsbyjs/gatsby/pull/7680) removed the default image width for image transforms to enable you to only set a `height` and have the image infer the correct width automatically, just like it does with the height when setting a `width`.

This default still exists and can be removed in gatsby-source-contentful because [this pull request](https://github.com/gatsbyjs/gatsby/pull/6970) for gatsby-plugin-sharp infers the defaults automatically if neither width nor height are given.

### Steps to reproduce

Source an image from contentful and only set the height for the image transform with a query like:

```
query getImageFixedHeight {
  allContentfulImages {
    nodes {
      image {
        fixed(height: 160) {
          width
          height
        }
      }
    }
  }
}
```

### Expected result

`height` should be 160 and `width` should be scaled according to the aspect ratio of the image.

### Actual result

`width` is always 400.

### Environment
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
  Binaries:
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Python27/python
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.4.3 => 2.4.3 
    gatsby-cli: ^2.5.8 => 2.5.13 
    gatsby-image: ^2.0.41 => 2.0.41 
    gatsby-plugin-material-ui: ^2.0.0-alpha.4 => 2.0.0-beta.0 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.37 => 2.0.37 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-source-contentful: ^2.0.40 => 2.0.56 
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19

### PR DESCRIPTION
**Pull request by LuudJanssen**
## Description

This PR resolves the width of an image automatically using the aspect ratio when only the height is given in an image transform. Previously, a default width was used resulting in a cropped image.

This PR also creates unit tests to test this behaviour.

## Related Issues

Fixes #14156 
Related to #6752
Related to #6954
Related to [this pull request about removing the default width when using gatsby-transformer-sharp](https://github.com/gatsbyjs/gatsby/pull/7680/files)
Related to [this pull request about calculating the right dimensions / aspect ratio based on the passed arguments when using gatsby-plugin-sharp](https://github.com/gatsbyjs/gatsby/issues/6752)

### CODE REVIEW

**Comment by LuudJanssen** [comment]
I have no idea why the end-to-end test is failing. It's failing on the `Gatsby Preview (Updating) "before each" hook for "updates when content is deleted"` because it reached a timeout of 9999ms. Could any of the core contributors help me resolve this?

**Comment by LekoArts** [comment]
I re-run the CI, seems like it was a hiccup. What do you think about adding some notes to the README, e.g. about the defaults for width/height?

**Comment by LuudJanssen** [comment]
@LekoArts, sure! I'll try to add the changes to the documentation as soon as possible!

**Comment by LuudJanssen** [comment]
@LekoArts, I merged the `master` branch into my branch and added some documentation about the `height` parameter. I didn't change the `gatsby-plugin-sharp` documentation, as `gatsby-source-datocms` and `gatsby-source-sanity` don't support setting only the `height` parameter.

Should we file issues to those repositories to fix this difference?

Also, I noticed `gatsby-source-contentful`, `gatsby-plugin-sharp`, `gatsby-transformer-sharp`, `gatsby-source-santiy` and `gatsby-source-datocms` share a lot of code regarding the definition of the additional node types (like `resize`, `fixed`, `fluid`; see [this definition](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/extend-node-type.js#L519) for example) and utilties for resolvers (like calculating `width` based on `height` and vice versa). Would it be wise to create some sort of utility library? Or offload most of this work to some other part of Gatsby I don't know about?

**Comment by LuudJanssen** [comment]
Also, @LekoArts, I'm experiencing build issues again.

**Comment by pieh** [comment]
> Also, @LekoArts, I'm experiencing build issues again.

Sorry for that, sometimes development runtime tests are flaky. After restarting them we are good again.

> @LekoArts, I merged the `master` branch into my branch and added some documentation about the `height` parameter. I didn't change the `gatsby-plugin-sharp` documentation, as `gatsby-source-datocms` and `gatsby-source-sanity` don't support setting only the `height` parameter.
> 
> Should we file issues to those repositories to fix this difference?

I think it's worth at least notifying datocms and sanity we did this change and they might apply it too for uniformity

> Also, I noticed `gatsby-source-contentful`, `gatsby-plugin-sharp`, `gatsby-transformer-sharp`, `gatsby-source-santiy` and `gatsby-source-datocms` share a lot of code regarding the definition of the additional node types (like `resize`, `fixed`, `fluid`; see [this definition](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/extend-node-type.js#L519) for example) and utilties for resolvers (like calculating `width` based on `height` and vice versa). Would it be wise to create some sort of utility library? Or offload most of this work to some other part of Gatsby I don't know about?

There might be already lib for that. This could be good idea (depending how much that utility would abstract and make it easier to read code), but it's not critical to do

**Comment by sidharthachatterjee** [comment]
Published in `gatsby-source-contentful@2.0.69`

**Pull request merged**
