### PR TITLE
[www] Hide the "Submit a starter" button for now

### PR DESCRIPTION
**Pull request by Manoz**
So this button is broken on mobile as you can see.

What should we do? Should we hide it on mobile?

submit-a-starter

### CODE REVIEW

**Comment by amberleyromo** [comment]
I also don't think removing is the best course of action. It's definitely not broken, just not optimized!

I would suggest doing something similar to what we've done on the starter detail pages, and as you size down have the search bar and "submit" button drop below the "Gatsby Starters (XX)".

**Comment by Manoz** [comment]
What about something like this?
image

We just need to move the `<Button>` component after the search form `div` and ovveride the padding on mobile:
```javascript
overrideCSS={{
  marginLeft: 10,
  [presets.Mobile]: {
    padding: `${rhythm(2 / 6)} ${rhythm(1 / 4)}`,
  },
}}
```

**Comment by amberleyromo** [comment]
I think it makes more sense to drop below, but that's me. I'll defer to @fk on that

**Comment by Manoz** [comment]
> I think it makes more sense to drop below, but that's me. I'll defer to @fk on that

We will have to create a `<Button>` for mobile only then. If I move the actual button outside his container it will be good on mobile but broken on desktop.

Should we dupplicate the component ?

**Comment by amberleyromo** [comment]
Hey @fk -- want to pop in here?

**Comment by fk** [comment]
Thanks to @LekoArts for reminding me of this.

I'm with @amberleyromo, seconding her [comment](https://github.com/gatsbyjs/gatsby/pull/8969#issuecomment-428634201) — dropping both search and "Submit" button down below the headline is a straight-forward solution.

We _could_ explore dropping the "Gatsby" from the headline, or adjusting search to only show the icon as long as it's not focussed (similar to what we do for the main search in the header), or cutting down the "Submit" button copy, but I'm generally in favor of a non-specific solution like Amberley suggested. Having the full viewport width available for the headline provides a nice amount of flexibility in terms of copy, while the aforementioned limits the potential "all in one row" solution quite a bit.

**Comment by amberleyromo** [comment]
Closing, handled in #10567.

**Pull request closed without merging**
