### PR TITLE
fix/feat(gatsby-source-drupal): Copy relationship meta (if any) to a node's field

### LINKED ISSUE #10339: gatsby-source-drupal image alt tags
## Summary

I'm trying to query an image's alt-text / title but it seems like it's not available. I'd love to fork it and fix it myself but can't seem to wrap my head around gatsby-source-drupal/gatsby-node.js (which is where I suppose the changes should be made).

### Basic example

```
{
  nodeHome {
    id

    relationships{
field_slides {
  id
  alt
  localFile {
publicURL
  }
}
    }
  }
}
```

### PR DESCRIPTION
**Pull request by hanoii**
## Description

Drupal data structure allows for properties that are part of a relationship, and not on the relationship itself. A common example for this is an image field, which relates to a file entity, but each relationship has an "alt" field. (See #10339).

I believe as far as content goes, this meta information belongs not to the relationship, but to the node that uses the relationship.

So this means that if there's meta on the relationship, it will be copied to a field name of the same name, for an image field as an example, this now works:

```graphql
{
  allTaxonomyTermSite {
    edges {
      node {
        relationships {
          field_logo {
            localFile {
              publicURL
            }
          }
        }
        field_logo {
          alt
          title
          width
          height
        }
      }
    }
  }
}
```

Ideally, I like this to be part of the relationship data, but I think this it not possible currently with the inference or by changing too much on gatsby.

I.e., if you have 

A ----> Relates to ----> B

This is properly handled if A has data and B has data, but what happens when the "relationship" has data, which is what's happening in this place.

I might have expected that instead of doing `node.relationships[`${ref.type}___NODE`] = UUID`, I could have done something like:

```jsx
node.relationships[`${ref.type}___NODE`] = {
  id: UUID,
  foo: bar
}
```

And support both, I bet this is a lot of changing.

Maybe with this added and schema customization this can be improved, or maybe adding schema customization to the source plugin as well, but I haven't gotten there yet.

## Related Issues

Fixes #10339 
Another approach to #14187 
https://www.drupal.org/project/jsonapi/issues/2860886#comment-12040685

### CODE REVIEW

**Comment by bakeruk** [comment]
Will this work with nested entities from Drupal modules such as Paragraphs?

In my opinion, I find it odd to make duplicate references as well as separating the field data apart

**Comment by hanoii** [comment]
> Will this work with nested entities from Drupal modules such as Paragraphs?

It does, this affects just Node A and its relationship with Node B (gatsby node, aka any entity on drupal). It doesn't really matter how depth the relationship goes:

```graphql
  allNodeSponsors {
    edges {
      node {
        relationships {
          field_content {
            ... on paragraph__affiliate {
              relationships {
                field_affiliate {
                  field_media_image {
                    alt
                    title
                    width
                    height
                  }
                  relationships {
                    field_media_image {
                      localFile {
                        publicURL
                      }
                    }
                  }
                }
	     }
            }
          }
        }
      }
    }
  }
```

> In my opinion, I find it odd to make duplicate references as well as separating the field data apart. Is this to get around the issue of having different `alt` and `title` tags on a node that uses the same image as another?

Yes, but also to keep it data consistent. alt/title is one specific case of meta in relationships with a file entity. But other things, like entity reference revisions can have meta too. I didn't want to touch each one on a case by case basis but rather something more fundamental.

**Comment by freiksenet** [comment]
Thank you!

**Comment by pascal-kubrick** [comment]
Thanks a lot!

**Comment by DhillonN** [comment]
> {
  allTaxonomyTermSite {
    edges {
      node {
        relationships {
          field_logo {
            localFile {
              publicURL
            }
          }
        }
        field_logo {
          alt
          title
          width
          height
        }
      }
    }
  }
}

I cant't figure out how to manage case where field_logo is multi value field.

**Comment by alessandrocalia** [comment]
> `{ allTaxonomyTermSite { edges { node { relationships { field_logo { localFile { publicURL } } } field_logo { alt title width height } } } } }`
> 
> I cant't figure out how to manage case where field_logo is multi value field.

+1

**Comment by hanoii** [comment]
@DhillonN, @alessandrocalia 

In the case of multi_value field you should get an array of elements on both places, and array on field_logo as well as an array on the relationship, like any other multi-value field.

Is that not happening? What is the output of the GraphQL query (and the query) you are running?

**Pull request merged**
