### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kevinfoerster**
changed https to http link as https is not working atm

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hmmm seems to have been a temporary problem? https is working for me. What error did you see?

**Comment by kevinfoerster** [comment]
when accessing https://gatsbyjs.org/ <https://gatsbyjs.org/> chrome shows:


```
This site can’t be reached

gatsbyjs.org unexpectedly closed the connection.
```

these urls are working:
https://www.gatsbyjs.org/ <https://www.gatsbyjs.org/>
http://gatsbyjs.org/ <http://gatsbyjs.org/>

this is happing for weeks now, i don’t think it is a temporary issue.

**Comment by KyleAMathews** [comment]
Oh ok, so we need a redirect from https://gatsbyjs.org to https://www.gatsbyjs.org. Hmmmm... lemme look into that.

**Comment by kevinfoerster** [comment]
don’t get me started with that WWW discussion… ;)

**Comment by KyleAMathews** [comment]
:-)

Could you create a PR adding the www to the link?

**Comment by 0x80** [comment]
@KyleAMathews Netlify [recommends](https://www.netlify.com/docs/custom-domains/) to point your dns record for www to the netlify domain and have your naked domain point to their load balancer. They then automatically configure a 301 from naked to www.

**Comment by KyleAMathews** [comment]
Hmmm yeah I thought Google's subdomain forward would work for https as well but it doesn't. Boo. I'll add the A record.

screen shot 2017-06-03 at 9 04 38 am

**Pull request closed without merging**
