### PR TITLE
fix for ISSUE 2553

### PR DESCRIPTION
**Pull request by 3axap4eHko**
In cheerio v1 Method `.html()` returns `innerHTML` for any selector and `outerHTML` for root element, this fix avoid losing root node
``` diff
-$('body').children().html()
+$('body').html()
```

### CODE REVIEW

**Comment by 3axap4eHko** [comment]
@KyleAMathews could you update snapshots for the updates?

**Comment by KyleAMathews** [comment]
@3axap4eHko run `npm run test -- -u` from the root of the repo to update the snapshots.

**Comment by 3axap4eHko** [comment]
It does not work for me. Yarn does not install required packages

**Comment by KyleAMathews** [comment]
What's the error? It's really important we get this to work for you (and other developers) so let's fix that.

**Comment by 3axap4eHko** [comment]
I found that I need to run `yarn bootstrap` before tests

**Comment by 3axap4eHko** [comment]
Seems like travis error

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit e6baee19141c7c3f2b85298356bede843bbfc623

https://app.netlify.com/sites/using-glamor/deploys/59f0e87bdf99535d15a3b9d1

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
