### PR TITLE
fix(starter-showcase): added description field to mccrodp's starter repo

### PR DESCRIPTION
**Pull request by mccrodp**
## Description

Just a simple description field update on [my starter repo](https://github.com/mccrodp/gatsby-starter-contentful-i18n) added previously.

## Related Issues

Originally added for Gatsby v1 here: https://github.com/gatsbyjs/gatsby/pull/4138, but I just upgraded to v2 and checked the starters.md. Thanks for adding that! 🙇

### CODE REVIEW

**Comment by mccrodp** [comment]
Actually, it seems you pull in the desc from the repo, that's better, **this can be closed**, but might be good to add that as a comment the `starters.md` code snippet in the docs? https://www.gatsbyjs.org/docs/submit-to-starter-library/#steps

**Comment by pieh** [comment]
I didn't even know we read package.json description, but it does seems a bit inconsistent:
 - on listing view we show package.json description ( https://www.gatsbyjs.org/starters?s=gatsby-starter-contentful-i18n&v=2 )
 - but on detail view we show description from .yml file - "N/A" in this case ( https://www.gatsbyjs.org/starters/mccrodp/gatsby-starter-contentful-i18n/ )

Might be worth to look into consolidating those? Not sure if it was intentional or not.

/cc @amberleyromo

**Comment by mccrodp** [comment]
Nice find, @pieh. It also seems that the description pulled and displayed for my starter is not the current one. I updated it 4 days ago, so not sure how those are cached either.

**Comment by pieh** [comment]
I'm not sure either about caching here - I lack lot of context on how starter showcase works, but let's merge PR in meantime, so your starter have proper description ;)

**Pull request merged**
