### PR TITLE
chore(gatsby-plugin-flow): Add pluginOptionsSchema validation

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Description
Just like @mxstbr did in #27356

### CODE REVIEW

**Comment by wardpeet** [comment]
can you add tests?

**Comment by MichaelDeBoey** [comment]
@wardpeet I figured since there's not really anything to test and #27356 also doesn't have tests, I didn't need to add them.
But if you want, I can add them for you

**Comment by wardpeet** [comment]
please add them cause when we add options we should update the tests, even if it's an empty object.

**Comment by mxstbr** [comment]
:wave: @MichaelDeBoey thank you so much for tackling this, love it! :100:

I'm working on the last bits and pieces for plugin option validation to be stable right now, after which I'm going to take a look at shipping these PRs 👍 #27600 #27601 #27602

**Comment by MichaelDeBoey** [comment]
@mxstbr Take your time, there's no rush 😉

**Review by mxstbr — DISMISSED** [review]
Thank you!!

**Review by mxstbr — APPROVED** [review]

**Review by mxstbr — DISMISSED** [review]
Same flakey tests as always that are failing, unrelated to this PR: #27781. Shipping!

**Comment by MichaelDeBoey** [comment]
@wardpeet @mxstbr I think this one can be merged, no? 🤔

**Review by LekoArts — APPROVED** [review]
Thanks!

**Pull request merged**
