### PR TITLE
fix: scripts/assert-changed-files.sh only looks in latest commit

### PR DESCRIPTION
**Pull request by ahinrichs**
More a question than a PR: The ci only looks for files changed in the last commit. If a branch has several commits but the integration tests are not on the last commit, they aren't tested.

This PR would change the script to list all files changed in the branch instead only from last commit.

### CODE REVIEW

**Comment by ahinrichs** [comment]
Testing this script in PR #9050 and it doesn't seem to work. What is CIRCLE_SHA1 set to if not the current HEAD of the PR?

**Comment by DSchau** [comment]
@ahinrichs this was intentional, but we're open to changing it. To explain, let's consider an example:

- Commit a change to packages/gatsby/cache-dir/something.js
- The integration tests will run (and pass/fail)
- A future commit makes a docs change
- The integration tests will "short circuit" and pass without running
- Future commit changes packages/*
- Run integration tests
- Repeat until merged

I think that's a good process, because it saves us from running some unnecessary _heavy_ tests in CircleCI, but like I said, I'm not necessarily against changing this. We would need to monitor to ensure that we're not spending a _ton_ of extra time processing and running these tests. In general, I do think what we have works pretty well and gets feedback back to the user very quickly.

**Comment by DSchau** [comment]
Also!

> What is CIRCLE_SHA1 set to if not the current HEAD of the PR?

It's "The SHA1 hash of the last commit of the current build."

The most helpful way to test this is with `echo` and locally, rather than committing changes and waiting for CI to pass/fail. You can default a variable like so:

```bash
COMMIT_BASE="${CIRCLE_SHA1:-whatever-you-want}"
```

**Comment by DSchau** [comment]
@ahinrichs that's the biggest issue. I honestly wish we could conditionally skip tests entirely, but I was unable to get that working with CircleCI!

I'm fine with adding .circleci to the regex, I suppose!

**Comment by ahinrichs** [comment]
Will change this PR.

**Comment by ahinrichs** [comment]
BTW the naming `ignore_pattern` is somewhat misleading.

**Comment by DSchau** [comment]
@ahinrichs when you're right, you're right. Totally agree! 😅 

I'll fix it in my upcoming PR. We got this, thanks for the feedback and help!

**Comment by DSchau** [comment]
@ahinrichs I actually included this in my new PR #9061.

Would you mind if I closed this one out once that one is reviewed?

**Comment by ahinrichs** [comment]
I'm old enough to get around an unmerged PR ;-)

**Comment by DSchau** [comment]
haha well I'm glad to hear it :) Let's close this out and follow along in the above PR.

**Comment by ahinrichs** [comment]
Pleased to be asked for review. I will take a look but maybe not until monday. Don't wait for me if you want it to proceed before that.

**Pull request closed without merging**
