### PR TITLE
chore(gatsby-core-utils): Autogenerate types declaration

### PR DESCRIPTION
**Pull request by ascorbic**
## Description

This PR removes the manually-generated .d.ts file and instead generates types as part of the build process, using `tsc`. It adds a `typegen` node script, and adds that to the `prepare` script. I've updated the tsconfig so that it doesn't compile tests.

### CODE REVIEW

**Comment by blainekasten** [comment]
@ascorbic I'm noticing a couple things different between what was there and what this change does.

Previously we had one single `index.d.ts` at root (which was distributed via package.json.files field).

This PR now ships a `*.d.ts` within the `dist/` folder for every module. Is that the intended behavior and does that change anything for users?

**Comment by ascorbic** [comment]
@blainekasten That's correct. If you have a `files` key in the package.json, it automatically picks up types from there. I've updated the PR to specifically list `dist/index.d.ts` in the files array. It shouldn't be needed, but the TS docs recommend it as best practice.

**Comment by pieh** [comment]
I guess we should compare current index.d.ts ( https://github.com/gatsbyjs/gatsby/blob/f71fea17f1c6454912858425418d2d2ef4808b17/packages/gatsby-core-utils/index.d.ts ) with generated definition files and see if there any changes in signatures? Generated definitions - https://gist.github.com/pieh/de64afb8e8b0c604b3ed99a218705121

I don't think that it matters that definitions are not single file anymore, as long as IDE/ts can work with multiple .d.ts files properly?

**Comment by pieh** [comment]
From my manual check seems like only `cpuCoreCount` has a bit different signature:

```diff
- export declare function cpuCoreCount(ignoreEnvVar?: boolean): number
+ export declare const cpuCoreCount: (ignoreEnvVar?: boolean | undefined) => number;
```
Which seems weird because `?:` should be enough to cover `| undefined` part, right? Seems like .d.ts autogeneration quirk, because we don't have `boolean | undefined` in source code for that

**Comment by blainekasten** [comment]
> Which seems weird because ?: should be enough to cover | undefined part, right? Seems like .d.ts autogeneration quirk, because we don't have boolean | undefined in source code for that

Quirk sure, but the net result is the same so it shouldn't be a problem

**Pull request merged**
