### PR TITLE
chore(starters): add gatsby-sidedrawer

### PR DESCRIPTION
**Pull request by Mr404Found**

### CODE REVIEW

**Comment by Mr404Found** [comment]
Hey! Why I am getting this circle-ci starters validate error.. someone please figure out this issue and help me

**Comment by laurieontech** [comment]
Thanks for the PR! I am running a merge which should resolve the tests.

However, before merging it would be good to update the README for your site. The current instructions name the repo `my-default-starter` and then list the instructions `cd gatsby-sidebar-starter/`. Since that's not the name of the directory in the first step that will not work. If we could update those two directories to be consistent this should be good to go!

**Comment by Mr404Found** [comment]
Hola! Thanks for the response Lourie mam. And I've just updated my README.md file.

**I have a query regarding ParticleJs and Gatsbyjs.**
_When i'm trying to use ParticleJs npm package in my gatsby site, It is showing some errors in deployment stage. Is there any solution for this?_

**Comment by laurieontech** [comment]
Thanks for the quick attention but looks like there is still a README problem. 
The current instructions are:
```Create a Gatsby site.

Use the Gatsby CLI to create a new site, specifying the default starter.

# create a new Gatsby site using the default starter
gatsby new **my-default-starter** https://github.com/Mr404Found/gatsby-sidedrawer
Start developing.

Navigate into your new site’s directory and start it up.

cd **gatsby-sidedrawer**/
gatsby develop```

The two bolded sections need to match. If you were to remove the "my-default-starter" name then the directory created would default to the name used in your github project. However, I'd recommend the following:

gatsby new  gatsby-sidedrawer https://github.com/Mr404Found/gatsby-sidedrawer
cd gatsby-sidedrawer/

You can keep the rest of the instructions as is.

In terms of the npm issue you're seeing please open a github issue and provide as much context as you can so the team can replicate what you're seeing!

**Comment by Mr404Found** [comment]
Hope everything is perfect now! Thanks Lourie mam!

**Comment by laurieontech** [comment]
Yup, looks good! Thanks for making the changes.

**Pull request merged**
