### PR TITLE
A bit of code

### PR DESCRIPTION
**Pull request by yashrajbharti**
True and false represents the enable and disable  buttons respectively

### CODE REVIEW

**Comment by yashrajbharti** [comment]
How to turn a button
visible = false
or
disable = true

**Comment by pieh** [comment]
I'm very confused as well - what is this?

**Comment by pieh** [comment]
This PR seems to be just eating our time in order to get hacktoberfest PR count, so I'll close this

**Comment by yashrajbharti** [comment]
This additional information regarding enable and disable shall be
sufficient......
I am trying to accomplish a button so that when those "number of days of
inactivity" happen gradually we can mark the issue as stale
(Sorry for my English is not very good)

**Comment by DSchau** [comment]
@yashrajbharti sorry, I don't think either of us are entirely clear what you're trying to accomplish nor what this PR was trying to accomplish.

Please feel free to open an issue if we can help further, and we will try our best. Thank you!

**Pull request closed without merging**
