### PR TITLE
add entry for gatsby-starter-solid-state :)

### PR DESCRIPTION
**Pull request by theschmocker**

### CODE REVIEW

**Comment by pieh** [comment]
Hey, I'm gonna revert this for now, because starter showcase is not yet finished and automation doesn't really work (pulling repo information + creating screenshot) and currently adding new entries is causing `www` to not build.

For now please add entry for your starter in https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-starters.md

**Comment by theschmocker** [comment]
Added it in there! #7832 

As far as the showcase is concerned, can you point to any issues I could try to help out with?

Thanks!

**Comment by pieh** [comment]
Hey @theschmocker, I honestly am not in the loop when it comes to status of starter showcase - I see that in https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/StarterShowcase/scraper.js there is bunch of code that is commented out and output that should be generated by that commented out code (or rather lack of that output) seems to be what caused build errors yesterday.

I'll try to get more information and get back to You

**Comment by pieh** [comment]
There is https://github.com/gatsbyjs/gatsby/issues/7563 epic / umbrella - you need zenhub to actually extra information that is actually really valuable here:
screen shot 2018-09-04 at 16 15 13

**Pull request merged**
