### PR TITLE
chore(starters): add gatsby-starter-simple

### PR DESCRIPTION
**Pull request by collinsmuriuki**

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! Right now tests are failing since "Styling:CSS" is not a valid category. Please take a look at the [categories you can choose from](https://github.com/gatsbyjs/gatsby/blob/master/docs/categories.yml).

**Comment by collinsmuriuki** [comment]
Fixed

**Comment by laurieontech** [comment]
Thanks so much! It looks like we don't have access to your branch. If you could merge master into this PR that'd be great.

**Comment by collinsmuriuki** [comment]
Done

**Comment by laurieontech** [comment]
Apologies for the back and forth, without access to your branch I can't run some of the fixes we normally would. 

To fix the linter test you'll want to run `yarn format`.

**Comment by collinsmuriuki** [comment]
My bad, mistake on my end. Will close this PR and make a new one in a separate branch to allow you to access it

**Pull request closed without merging**
