### PR TITLE
[gatsby-image/using-gatsby-image] tracedSVG aftercare/expand using-gatsby-image

### PR DESCRIPTION
**Pull request by fk**
* bump deps
* add navigation component
* add masonry-like image gallery at /traced-svg/ along a slew of images (courtesy of Unsplash) to test the tracedSVG default settings, generated SVG sizes – current HTML size is ~750 KB :-D … don’t have a real plan yet, but the outcome ideally has some stat output right on the page
* move placeholder copy to silly components – now featuring Monty Phyton quotes, mainly to prevent Google Chrome from offering to translate Latin (headlines would probably have sufficed… ;-))

### CODE REVIEW

**Comment by fk** [comment]
image

image

**Comment by fk** [comment]
https://deploy-preview-2612--using-gatsby-image.netlify.com/

**Comment by KyleAMathews** [comment]
Amazing!!! 😍 😍 😍 

Doesn't look like WIP to me so let's merge this :-D

**Comment by fk** [comment]
Well, everything is a WIP :D, so let's merge! 👍

**Comment by fk** [comment]
Ah Kyle … 😏 😇  – one thing I have been trying unsuccessfully is to add another weight of the "Oswald" font to the typography.js theme: I'd like to have a `400` along the `700` that the theme includes. I tried to overwrite the `googleFonts` array in `utils/typography.js` (`elkGlenTheme.googleFonts = […]`) and add the weight there, but 😕 . Is that possible somehow?

NBD tho and nothing that should keep you from merging.

**Comment by KyleAMathews** [comment]
Added the typefaces packages for the fonts and deleted the google fonts declaration. That solves the problem as the typefaces package include all the font files.

**Comment by fk** [comment]
> Added the typefaces packages for the fonts and deleted the google fonts declaration. That solves the problem as the typefaces package include all the font files.

D'oh, didn't think of that. Twice as good!

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 632d7b34a5b30cbcfd3b3a0cce06e6f89961dc3e

https://app.netlify.com/sites/using-glamor/deploys/59f0e7d5a6188f2d75d49cbd

**Pull request merged**
