### PR TITLE
fix(gatsby-recipes): support code blocks on cli

### PR DESCRIPTION
**Pull request by KyleAMathews**
Fixes https://github.com/gatsbyjs/gatsby/issues/22991#issuecomment-627078235 cc @jsjoeio

Output
Screen Shot 2020-05-11 at 8 11 01 PM

Code
Screen Shot 2020-05-11 at 8 11 17 PM

Initial stab at this just renders the code blocks as exactly the same as the markdown. Is that... too on the nose?

Another option (not for tonight) is highlighting the code — https://github.com/rstacruz/hicat/blob/master/index.js

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Actually nerd snipped myself into trying it — thoughts?

Screen Shot 2020-05-11 at 8 32 39 PM

**Comment by jsjoeio** [comment]
Besides that blue (which I'm guessing is your own settings), this looks way better 😄

**Comment by muescha** [comment]
I would use an other background (white ?) for the snippet and maybe draw a box around and in box title the language. Then it looks like in the docs as a code block. But I don't know how well this can be copied with a Unicode borderline

**Comment by KyleAMathews** [comment]
Another go with some small dots

Screen Shot 2020-05-13 at 9 27 32 AM

**Comment by KyleAMathews** [comment]
Ok, going with this @pvdz suggested using just two dots to leave some space which looks nice

Screen Shot 2020-05-13 at 1 41 42 PM

**Comment by KyleAMathews** [comment]
Published in `gatsby-cli@2.12.20`

**Comment by KyleAMathews** [comment]
@pvdz pointed out the dots (while COOOL) would break copy / paste — sigh, terminals destroy all good UI ideas https://github.com/gatsbyjs/gatsby/pull/24080

**Pull request merged**
