### PR TITLE
fix(*): cache tracedSVG calculations when cache is present

### PR DESCRIPTION
**Pull request by oorestisime**
Fix: #11997

Similar to #9059 but for tracedSVG.

### CODE REVIEW

**Comment by wardpeet** [comment]
sweet, mind adding some tests to make sure your cachekeys are working

**Comment by oorestisime** [comment]
hey, thanks for the feedback! I am not sure i follow here.
Is there a test somewhere doing this? Doesn't sound good to me to export the cache key generator.
But i might be seeing this completely wrong so a few more details would be appreciated!

**Comment by wardpeet** [comment]
oh sorry, more or less I mean if we call base64 twice it is only ran once.

**Comment by oorestisime** [comment]
Heya,

doing so would produce the same result but without actually testing cache keys. I won't be able to pass a cache object in the arguments since there is no way to import the cache as a standalone (i think).
Only solution i see here is mocking the cache object, although it seems that doing so beats the purpose of the test

**Comment by LekoArts** [comment]
Would be cool to have this in! Any follow-up questions/additions from your side @wardpeet ?

**Comment by oorestisime** [comment]
@wardpeet kind reminder :)

**Comment by wardpeet** [comment]
@oorestisime oh my bad. It loosk great, can you fix conflicts and we'll merge! 👍

**Comment by oorestisime** [comment]
Rebased :) please have a close look i hope i did a correct merge, there were a lot of changes

**Comment by wardpeet** [comment]
Patched a few things. I'll be testing this one and getting this in. Thanks for your patience and rebasing it!

**Comment by oorestisime** [comment]
Yeah sorry i did this quickly because i ll be with no pc for a week so i didn't want to get it stalled! thanks for taking over !

**Pull request merged**
