### PR TITLE
feat(www): Add tooltip in Plugin Result search preview

### PR DESCRIPTION
**Pull request by RohitChattopadhyay**
## Description
Adds title to badges in plugin search preview and for showing number of downloads in the last 30days.
This will be shown as a tooltip when hovered.

## Screenshots
*For Gatsby Official Plugin*
image
*For Community Plugin*
image
*Tooltip showing number of downloads*
image

### CODE REVIEW

**Comment by marcysutton** [comment]
Note to reviewer: check out the markup for these widgets in general, and be sure to test in a browser. For example, there is an `alt` attribute on a SPAN element here that isn't doing anything (as `alt` mostly only works on images), and the entire block looks to be wrapped in an `aria-hidden` attribute.

**Comment by RohitChattopadhyay** [comment]
Need help resolving the CI fail

**Comment by tesseralis** [comment]
Tagging @madalynrose since this is an a11y issue.

**Comment by freiksenet** [comment]
@RohitChattopadhyay Hello! I wonder if you would have time to address the review comments above.

**Comment by RohitChattopadhyay** [comment]
Yes, I have already started work on it,
Apologies for the delay, I had to go in quarantine due to pandemic, so I
had very limited resources.

Thanks
Rohit R. Chattopadhyay

**Comment by RohitChattopadhyay** [comment]
@madalynrose , thanks for your comment, it was very helpful, I have made the changes
I found similar scope of improvement in other files, like in https://github.com/gatsbyjs/gatsby/blob/96a8abb1793583b1926f70667320b13dba810377/www/src/templates/template-package-readme.js#L45
Should this PR cover them as well?

**Comment by LekoArts** [comment]
Hey! Thanks so much for opening a pull request!

Since we merged gatsbyjs.org and gatsbyjs.com the website code isn't open source anymore (for now) and thus changes made to the old code can't be accepted anymore (see the [blogpost](https://www.gatsbyjs.com/blog/announcing-unified-gatsby/)). Feel free to send in a bug report via an issue here in this repository if you encounter a problem. Thanks!

We absolutely want to have you as a contributor, so please take a look at [our open issues][open-issues] for ideas, and please reach out to us on Twitter at `@gatsbyjs` with questions.
Thanks again, and we look forward to seeing more PRs from you in the future! :muscle::purple_heart:

[open-issues]: https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Pull request closed without merging**
