### PR TITLE
upgrade and use polyfill

### PR DESCRIPTION
**Pull request by jquense**
I am slightly unsure if the component-renderer logic is the same…

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Nice! Fixes https://github.com/gatsbyjs/gatsby/issues/4692 :-)

Will review and merge as soon as I get some dev time... :-|

**Comment by pieh** [comment]
for `gatsby-link` stuff - try updating it - I had same error earlier and _I think_ I fixed it with https://github.com/gatsbyjs/gatsby/pull/4805

**Comment by m-allanson** [comment]
Aha, thanks @pieh! I pulled that change in via GitHub in `dacfe28`, but haven't run it locally yet.

**Comment by jquense** [comment]
The lifecycle warning message, i think, is coming from react hot loader which is proxying the components

**Comment by m-allanson** [comment]
> The lifecycle warning message, i think, is coming from react hot loader which is proxying the components

I guess we can ignore that for now? 

> I am slightly unsure if the component-renderer logic is the same…

Me neither... I _think_ it's the same?

I pushed a couple of commits to `gatsby-link`, if those look OK then I think this is good to merge.

**Comment by m-allanson** [comment]
A new version of `react-hot-loader` that adds React v16.3 was released a couple of hours ago :) PR updated.

**Comment by jquense** [comment]
ya!

**Comment by nihgwu** [comment]
can we release a new version for v2? alpha-13 breaks a lot of things:
1. mini-css plugin version mismatch (fixed)
2. the new json-store seems not compatible with redirects, I always get erorr caused by `dev-404-page` not found, I changed the source code to workaround, but still get errors for `getLayout` when deploying
3. I also get a strange regression the Type defined in my custom transformer plugin not find in `RootQueryType` which is not happening in alpha-12, I manage to solve that by moving the plugin to the very top of the config, the custom transformer plugin runs after scheme update, have no idea why

so I'm still staying with alpha-12, but that version has a bug with pathPrefix when building, I know that's not the right place to post those things, but I'd like to try the latest version to see if they still there

**Comment by KyleAMathews** [comment]
Probably going to release another alpha once my layout removal PR is done https://github.com/gatsbyjs/gatsby/pull/4887

**Pull request merged**
