### PR TITLE
fix(gatsby-transformer-react-docgen): clean up and declare types for react-docgen

### PR DESCRIPTION
**Pull request by jquense**
## Description

Updates the to the newer customization API's and ensures all the types are fully specified. Avoids an issue where the schema TypeComposer can't find types on a second build from cache

### CODE REVIEW

**Comment by blainekasten** [comment]
@jquense thanks for the PR! Is there a specific reason you switched to cjs over modules?

**Comment by jquense** [comment]
Consistency mostly, it was half and half. Also CJS makes it easier to upstream changes from our fork so it's a bit selfish as well

**Comment by vladar** [comment]
I'd like to start reviewing but there are conflicts with `master`. Mind rebasing?

**Comment by vladar** [comment]
@jquense Just a friendly reminder about this PR. Do you have plans to move it forward? If not, I can probably take over.

**Comment by jquense** [comment]
To be honest I'm now maintaining and releasing a fork of this plugin so I can make changes more freely (and release more quickly), I like to send the changes back but haven't had time recently to update this. If you want to take over please do :)

**Comment by muescha** [comment]
@jquense is there a public repo of your fork?

**Comment by jquense** [comment]
@muescha there is public repo, it's currently nested in my docs theme tho: https://github.com/jquense/docpocalypse/tree/master/packages/theme-core/plugins/react-docgen. I am probably gonna publish it tho

**Comment by pvdz** [comment]
I'm going to close this PR seeing how the author indicated they're working on their own fork now and do not intend to finish this PR. If somebody wants to pick it up go ahead and open a new PR. Thanks :)

**Comment by jquense** [comment]
Or hand over ownership of important plugins to those doing the work maintaining them instead of insisting they stay in this repo and die on the vine ;)

**Pull request closed without merging**
