### PR TITLE
Fixes #1007, Add lowdb support

### LINKED ISSUE #1007: Add lowdb support
[lowdb](https://github.com/typicode/lowdb) is a pure local JSON file database, and gatsby support JSON file nicely.

I think it'll be a  great combination, gatsby for reading JSON and lowdb for write JSON. But the format is slightly different between them.

gatsby use

```json
# posts.json
[
  {"id": 1, "title": "Facebook"}
]
```

While lowdb use

```json
# db.json
{
   "posts": [
      {"id": 1, "title": "Facebook"}
    ]
}
```

### PR DESCRIPTION
**Pull request by gutenye**
I've a few questions and left notes in code.

Maybe we can extends builtin `gatsby-transfomer-json` with `{"posts": [{"value": "a"}, ..]}` support instead of a new package.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
I think putting this in its own package makes the most sense as there's an infinite number of ways JSON can be structured so trying to support those all in `gatsby-transformer-json` won't work.

Also with each transformer type being its own package, they'll be easy to find via Google or the Gatsby website.

Could you just add your questions here as a comment please.

**Comment by gutenye** [comment]
@KyleAMathews 
Okay, I'll create a new package.

What's `children` and `parent` used for in `createNode()`? 
It seems works fine when I provide empty values for these.

**Comment by KyleAMathews** [comment]
@gutenye they're useful conventions not a hard things-will-break-without-them requirement. They're there so that you can write queries following the transform chain. It's often useful for example to jump up from a transformed node to its file parent to get file specific information e.g. its size or file name, etc. I sometimes write queries too where I query for files and then jump to the right child.

So it's strongly encouraged you add them.

**Comment by gutenye** [comment]
Published: https://github.com/gutenye/gatsby-transformer-lowdb

**Comment by KyleAMathews** [comment]
Looking good!

FYI, there'll be some breaking changes for the API soonish see https://github.com/gatsbyjs/gatsby/issues/858

Should be a pretty easy upgrade.

**Comment by gutenye** [comment]
@KyleAMathews Thanks for the heads up.

**Pull request closed without merging**
