### PR TITLE
tests: Update pluginOptionsSchema tests

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Bring tests in line with the docs

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! I certainly agree with the docs update, I'm less convinced that we need to look at both `isValid` and `errors` in all scenarios. Though we certainly can. cc: @mxstbr for his take.

**Review by mxstbr — APPROVED** [review]
This seems like a good idea to me, as it showcases the full API of `testPluginOptionsSchema` for people who are looking at our usage of it! Thank you @MichaelDeBoey!! 👍

**Comment by MichaelDeBoey** [comment]
@laurieontech @mxstbr I think this one can be merged, no? 🤔

**Comment by MichaelDeBoey** [comment]
@ascorbic Tests should be fine now

**Review by LekoArts — APPROVED** [review]

**Pull request merged**
