### PR TITLE
[WiP][www] IA redesign: Allow "accordions" on any navigation level

### LINKED ISSUE #6605: [www] IA redesign: Allow "accordions" on any navigation level
… not only the top-level items.

While we're at that, add the following as discussed around https://github.com/gatsbyjs/gatsby/pull/6245#issuecomment-403487321:

- add optional toggle and direct-click areas for items with subitems: an item can thus either be
  - a "plain" item which on click shows the associated page
  - a "item list header" item which on click expands/collapses its contents
  - a "hybrid" item that allows both expanding a subsection of the item by clicking on the caret as well as navigating to the page associated with the item itself directly by clicking on the item title
- auto-collapse nested subitems
- allow navigation items to be infinitely nested
- adjust UI to clearly convey the "hybrid" item functionality: 
bildschirmfoto 2018-07-19 um 14 17 09

### PR DESCRIPTION
**Pull request by fk**
Fixes #6605 🤞 
Preview at https://elated-goldwasser-ec35d0.netlify.com/docs/.

Along the way:

* analog to store.gatsbyjs.org, darken `colors.lilac` to meet WCAG 2.0 level AA (ref. https://github.com/gatsbyjs/store.gatsbyjs.org/pull/92)
* fix one more "import graphql from gatsby" occurence (`src/pages/showcase.js`)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit d2fbbd5f22d2d2ca8f072bd8145f634fbaa47087

https://app.netlify.com/sites/using-postcss-sass/deploys/5b51f6143813f010d89d9f3a

**Comment by calcsam** [comment]
I _really_ like this approach. Let's keep at this @fk 

Querying your data with GraphQL => Querying data with GraphQL so it stays on one line

Some additional sub-items may make sense:

* Pulling data from content store(s)
* Adding third-party services [search, analytics....]
* Testing

We should see a key audience for "navigating the hierarchy" an architect, eng manager, or developer trying to answer the question & form an opinion: "How do I do X with Gatsby?"

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 9cafe61dd953989bfb73962b73ab659fb984e4ce

https://app.netlify.com/sites/gatsbyjs/deploys/5b57cfa5b13fb118f9d1d9b8

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 37be4efce368c710cefd1027560eab8e56bdc3e9

https://app.netlify.com/sites/using-glamor/deploys/5b632b79c6aed650f979085b

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit 6b2840b774a245873e88f331e73e122bf001c3d0

https://app.netlify.com/sites/image-processing/deploys/5b632c031f12b7302ee295d9

**Comment by KyleAMathews** [comment]
Deploy preview for *using-remark* failed.

Built with commit 37be4efce368c710cefd1027560eab8e56bdc3e9

https://app.netlify.com/sites/using-remark/deploys/5b632b79c6aed650f9790864

**Pull request merged**
