### PR TITLE
Added Etcetera Design to Showcase

### PR DESCRIPTION
**Pull request by chrisjingram**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit a5b6bc3ee4bb5212977ca330e53b556281234599

https://app.netlify.com/sites/using-glamor/deploys/59d8b2cba6188f09a7d196ed

**Comment by KyleAMathews** [comment]
Awesome, thanks for sharing!

btw, would love feedback on the gatsby-image work I've been doing — might be something you could use on this site https://www.gatsbyjs.org/packages/gatsby-image/

**Comment by chrisjingram** [comment]
Thanks, will check it out! Etcetera definitely needs something to load the images more seamlessly

**Comment by jlengstorf** [comment]
Hiya @chrisjingram! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
