### PR TITLE
[gatsby-source-contentful] Add support to prefer WebP images

### PR DESCRIPTION
**Pull request by nsimonson**
💁‍♂️  adds new fragments and fields for `srcWebp` and `srcSetWebp` to match the `gatsby-image` interface.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
This looks great! Could you add an example or two of using this to the using-contentful site? https://using-contentful.gatsbyjs.org/image-api/

**Comment by szimek** [comment]
Some time ago I asked Contentful support if it was possible for them to add `fm=auto` option (or something similar) to their Image API that would automatically switch between optimal format based on `Accept` header from the browser. 🤞

**Comment by nsimonson** [comment]
@szimek That feels like the real solution; don't make me think about it. It's probably how `fm=webp` should work. Give me webp if it's support, otherwise fall back.

**Comment by szimek** [comment]
@nsimonson You can ping their support about it as well, maybe more people asking about it will convince them to put it higher on their priority list 😏

**Comment by KyleAMathews** [comment]
Awesome, thanks!

@szimek yeah, that'd be great if their image API supported it natively.

**Pull request merged**
