### PR TITLE
Fixes broken link from Gatsbygram

### PR DESCRIPTION
**Pull request by kindavishal**
## Description

Fixes a broken link to ```packages-gatsby``` and closes the third task inside #14693
## Related Issues

Closes third task in #14693

### CODE REVIEW

**Comment by kindavishal** [comment]
Reverted the last commit to open a new PR which fixed another issue. I was working on the same branch, so forgot to switch!
The new PR is here https://github.com/gatsbyjs/gatsby/pull/15142

**Comment by kindavishal** [comment]
Thank you!

**Comment by m-allanson** [comment]
Thank you @kindavishal! Can I ask you to update these links in a new PR? They should be relative instead of absolute URLs. See my comments on https://github.com/gatsbyjs/gatsby/pull/15142 for an example.

The reason for relative urls is that when using absolute urls, clicking the link will trigger a full page refresh. Using relative urls means that Gatsby's Link component can prefetch the page content and update the window without having to refresh the page.

**Comment by kindavishal** [comment]
> Thank you @kindavishal! Can I ask you to update these links in a new PR? They should be relative instead of absolute URLs. See my comments on #15142 for an example.
> 
> The reason for relative urls is that when using absolute urls, clicking the link will trigger a full page refresh. Using relative urls means that Gatsby's Link component can prefetch the page content and update the window without having to refresh the page.

Got it! Will do that :D

**Pull request merged**
