### PR TITLE
fix(gatsby-remark-images): remove clickable whitespace around image when linking

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR changes the way that `gatsby-remark-images` handles linking image thumbnails to their originals.

## Behavior Before PR
Currently, the `a` tag that links to the original image expands to fill the entire parent.
before

## Behavior After PR
The new behavior makes the link only contain the image and not any extra whitespace.
after

The Jest snapshots for this package were updated to reflect this change.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
@pieh, @DSchau, is there anything I can do to get this reviewed/merged quickly?

**Comment by DSchau** [comment]
@ajschmidt8 can you allow permission to push to your branch?

https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by ajschmidt8** [comment]
@DSchau, done!

**Comment by ajschmidt8** [comment]
> Is the general idea here that we _don't want_ the extra space surrounding the image to be clickable?
> 
> I'm not really sure which behavior is preferable--could you provide why it's advantageous one way or the other?

@DSchau yes, that is the idea. The screenshots above are from a page on a site that I'm building. As indicated in the pictures, if you click in the whitespace surrounding the image, it will open the original image in a new URL. I found this to be kind of an annoyance. I thought it would be better if the original image only opened when the actual _thumbnail_ was clicked and _not_ the surrounding whitespace.

**Comment by ajschmidt8** [comment]
It seems like it would be misleading to users if they clicked whitespace and an image popped up.

**Comment by ajschmidt8** [comment]
@DSchau, just pulled the latest and fixed some merge conflicts. let me know if this can be merged soon :grimacing:

**Comment by freiksenet** [comment]
@ajschmidt8 Could you allow me to push to your repo so that I can merge the conflicts?

**Comment by ajschmidt8** [comment]
@freiksenet i just resolved the conflicts and pushed the changes :+1:

**Comment by wardpeet** [comment]
Published in `gatsby-remark-images@3.1.1`

**Pull request merged**
