### PR TITLE
Remove micro modules

### PR DESCRIPTION
**Pull request by 43081j**
Nobody really needs these. Less dependencies means less overhead and higher trust.

wip: im having trouble with local setup so this'll probably fall over in CI to begin with

### CODE REVIEW

**Comment by DSchau** [comment]
@43081j Hey! Thanks so much for this pull request, we really appreciate it (and thanks for your first PR to this repo!).

In general -- pull requests that remove dependencies (particularly those which may not have tests or end-to-end tests) are slightly challenging to review. First thing I would like to dive into more is what were you trying to improve with this pull request? 

> Less dependencies means less overhead and higher trust.

You mention this -- but in general, the hard part of removing dependencies is that these may have been necessary or useful in some cases. Particularly, the `query-string` dependency used in `www` may have been useful because some APIs that you swapped to, notably `URLSearchParams` and the `entries` method for arrays may not have the best browser support, which means that this could then break in older browsers.

In any scenario -- we really appreciate this pull request, but we could use a little more information and understanding as to what you were trying to accomplish before we'd want to take further action on this.

Thank you!

**Comment by 43081j** [comment]
Thanks for the quick response.

Micro-packages (one line packages) inevitably add the overhead of an extra dependency for something you could have achieved in code yourself. Often they have since been made redundant by introduction of native equivalents. On top of that, some of us audit dependency trees and these tiny packages come with less trust than our direct dependencies (e.g. you, gatsby) so the less of them that exist, the more trustable your own package becomes.

There are a couple of things in this PR though, not all are replacement of what packages did:
* Some packages were no longer in use (i searched the entire directory of the associated gatsby sub-package for them, and also read the dependency's docs to make sure it wasn't somehow implicitly loaded)
* Some have native equivalents now (e.g. query-string)
* Some were bloat from the beginning (e.g. is-blank, is-string)

While you are right about `query-string`, IMO you should be polyfilling that native functionality rather than depending on a package which has been redundant for many years. For example, `whatwg-url` package could possibly achieve this.

**Comment by 43081j** [comment]
in order to get this through with minimal code changes we could keep the query-string module for now, at least.

that allows us to clear out a lot of the cruft still.

**Comment by LekoArts** [comment]
Hi @43081j 👋 We'd be happy to move forward with this PR. Can you fix the merge conflicts and remove the replacements with `URLSearchParam` in our runtime parts? As it's supported by Node 10 were fine with replacing this in Node parts, but for our runtime we want to keep `query-string` for now.

**Comment by 43081j** [comment]
FYI ci seems to fail because of some unrelated yarn error (it couldn't build a dependency or something errored during install).

**Comment by freiksenet** [comment]
Thanks a lot for creating and following up on this PR @43081j!

**Pull request merged**
