### PR TITLE
Added support for a custom locale when querying a date

### PR DESCRIPTION
**Pull request by briced**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0779ef144aed6de694b84f6d6ccc7936a088be29

https://app.netlify.com/sites/using-glamor/deploys/59d9336edf995304e986c41d

**Comment by briced** [comment]
moment.utc can use locales **and** strict mode, but the website is out of date. I've made a PR to explain & fix the website (https://github.com/moment/momentjs.com/pull/454), but you can see in the PR that moment's code support it since 2013.

**Comment by KyleAMathews** [comment]
Oh interesting! What does it mean when you pass in a locale for parsing?

**Comment by briced** [comment]
The locale is used for formatting (I want to display a french formatted date with fulltext month) . After reflecting on it, it seems a bit odd with this syntax. Do you want me to submit something with a local locale change instead (http://momentjs.com/docs/#/i18n/instance-locale/)?

**Comment by KyleAMathews** [comment]
>Do you want me to submit something with a local locale change instead

Yeah, that's more self-documenting.

**Comment by briced** [comment]
Done

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by sprmn** [comment]
I noticed that this is not working properly yet. The locale argument is not in the list of `args`. I guess something like this should be added [here](https://github.com/gatsbyjs/gatsby/blob/6fe44fe2e4d694a84f9a2339dd0eabc4106a44f5/packages/gatsby/src/schema/infer-graphql-type.js#L129):

``` diff
+        locale: {
+          type: GraphQLString,
+          description: oneLine`
+            Configures the locale Moment.js will use to format the date.
+          `
+        },
```

Shall I commit a PR for this?

**Comment by KyleAMathews** [comment]
Ah yeah, that does need added. A PR would be great!

**Comment by jlengstorf** [comment]
Hiya @briced! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
