### PR TITLE
Resolve user configured webpack loaders

### PR DESCRIPTION
**Pull request by pamo**
Added some clarification to the readme in addition to a link to my site. 
Also just noticed a space is needed between the link and the source link on line 44 :sleepy:

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Awesome! This is so helpful. I'll cut a new release. Sorry for persevering past my inaccurate advice ;-)

**Comment by KyleAMathews** [comment]
I added an example of how to use this to the default starter

http://gatsbyjs.github.io/gatsby-starter-default/markdown/
https://github.com/gatsbyjs/gatsby-starter-default/commit/d49ac2d31a886fc741caac28e06c6289ea26807d

**Comment by jlengstorf** [comment]
Hiya @pamo! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by pamo** [comment]
This is super cool @KyleAMathews @jlengstorf! Thanks for the ❤️. Going to have a hard time choosing among all the swag 🙃

**Pull request merged**
