### PR TITLE
fix(gatsby): change order of feedbackDisabled checks to allow CI AWS lambda build

### LINKED ISSUE #30647: Error Building Gatsby Site inside AWS Lambda
I am trying to build a gatsby site inside an AWS Lambda function.

There are many issues that arrises when you try to do something like this (250Mb Lambda Limit, the fact that only /tmp folder is writable) I have handled all those issues (I can share a repo if anyone is interested) and got it to work in gatsby v2 but the build does not work in gatsby v3. 

When building I get the following error:

```
ENOENT: no such file or directory, mkdir '/home/sbx_user1051/.config/gatsby'
at Object.mkdirSync (fs.js:987:3)
at AsyncFunction.module.exports.sync (/var/task/node_modules/make-dir/index.js:114:6)
at Configstore.set all [as all] (/var/task/node_modules/configstore/index.js:59:12)
at new Configstore (/var/task/node_modules/configstore/index.js:25:13)
at getConfigStore (/var/task/node_modules/gatsby-core-utils/dist/get-config-store.js:18:14)
at isFeedbackDisabled (/var/task/node_modules/gatsby/dist/utils/feedback.js:145:43)
at userGetsSevenDayFeedback (/var/task/node_modules/gatsby/dist/utils/feedback.js:162:7)
at build (/var/task/node_modules/gatsby/dist/commands/build.js:275:52)
at async h (/var/task/src/functions/build/handler.js:1:5594) {
 errno: -2,
 syscall: 'mkdir',
 code: 'ENOENT',
 path: '/home/sbx_user1051/.config/gatsby'
}
```

From this I have found the error is related to the function isFeedbackDisabled in feedback.ts, this is the function:

```
function isFeedbackDisabled(): boolean {
  // Heuristic 2
  if (getConfigStore().get(feedbackKey) === true) {
    return true
  }

  // Heuristic 3
  if (process.env.GATSBY_FEEDBACK_DISABLED === `1`) {
    return true
  }

  if (isCI()) {
    return true
  }

  return false
}
```

Here we can see that this function tries to get access to the config store before checking if we are in CI. Checking the config store does not work in the lambda environment because only the /tmp folder is writable. 
Even the comments seem to indicate that heuristics are out of order with what would be heuristic 1 at the end. Changing the order of heuristics to put isCi() check first fixes the issue for me. I can create a pull request if that is something that can be done for this error, I'm not sure if the order is put that way for a reason that I don't understand.

### PR DESCRIPTION
**Pull request by mathisobadia**
## Description

Change the order of feedback disabled heuristics to check first if we are in CI, avoiding the getConfigStore() call in that case

## Related Issues

Fixes #30647

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Could we just work on preventing getConfigStore from erroring?

**Comment by mathisobadia** [comment]
@KyleAMathews yes you are right working on the getConfigStore function would prevent this error and possibly others in the future. As someone new to Gatsby dev, I just thought this particular fix looked painless to me and didn't change any functionality. As a minor point it would also solve the somewhat weird comments that start the function with heuristic 2, then 3 then 🤷 that led me to believe it was the intended order.

**Comment by LekoArts** [comment]
No, the 1) heuristic comes in the function that calls `isFeedbackDisabled` (that has the 2) comment) so it's correct:

https://github.com/gatsbyjs/gatsby/blob/cfe399ddffeb5a134adb57c707c36ba16599de2e/packages/gatsby/src/utils/feedback.ts#L66-L83

But I'd agree that moving the order is the easier fix here. The check for the ENV var should also go above the `getConfigStore()` call

**Comment by mathisobadia** [comment]
Yes you are right about the comment numbers, I forgot about the first heuristic placed before in the code. 
I have created a new commit to put the env var above getConfigStore as you suggested.

**Review by LekoArts — APPROVED** [review]
Thanks!

**Pull request merged**
