### PR TITLE
[gatsby-image] Optional “slot” inside wrapper

### PR DESCRIPTION
**Pull request by ryanditjia**
Currently, the [recommended](https://css-tricks.com/text-blocks-over-image/) [method](https://www.w3schools.com/howto/howto_css_image_text.asp) to overlay text is difficult to implement in gatsby-image.

This PR adds a [“slot”](https://reactjs.org/docs/composition-vs-inheritance.html) that you can use to add any React node.

I’m not 100% sold on the name `innerChild` and am open to suggestions.

### CODE REVIEW

**Comment by ryanditjia** [comment]
That’s doable, but it feels brittle because `Img` already has a position relative wrapper, plus an aspect ratio placeholder div inside of it. It makes me think that there could be edge cases where the `<h4>` could be positioned outside of the image.

**Comment by pieh** [comment]
Maybe we could use `children` prop here?
For fluid, it probably doesn't bring much value, but for `fixed` I could see this being useful when you don't have to repeat `width` and `height` styling for wrapping div

**Comment by stefanprobst** [comment]
I think it would work the same for fixed images.
@ryanditjia has helpfully linked to the docs on React's composition model, and this seems like a very good candidate
```js
const ImageWithOverlay = ({ children, ...rest }) => (
  <div style={{ position: 'relative' }}>
    <Image {...rest} />
    <div style={{ position: 'absolute', top: '50%' }}>
      {children}
    </div>
  </div>
)

// Usage:
<ImageWithOverlay fixed={data.file.childImageSharp.fixed}>
  Hello World
</ImageWithOverlay>

<ImageWithOverlay fluid={data.file.childImageSharp.fluid} />
  <h4>Hello World</h4>
</ImageWithOverlay>
```
See in action: https://github.com/stefanprobst/gatsby-issue-8316.git

**Comment by pieh** [comment]
@stefanprobst for most usecases this will work - but with some changes it won't - that's what I meant with repeating `width` style for wrapping div
screen shot 2018-09-28 at 00 08 37

**Comment by ryanditjia** [comment]
Apologies for taking so long to reply, and thanks for the discussion.

@pieh has found an edge case here. I believe the cleanest and most reliable way to constrain the overlay is by placing it as a sibling of the image.

The API increase is minimal and it prevents another level of div soup.

`children` can work.

```jsx
<Img fluid={data.image.fluid}>
  <div>An overlay text</div>
</Img>

// compiles to HTML

<div class="wrapper">
  <div class="aspect-ratio-placeholder" />
  <img />
  <picture>
    <source />
    <source />
    <img />
  </picture>
  <noscript>
    <picture>
      <source />
      <source />
      <img />
    </picture>
  </noscript>
  <div class="slot">
    <h2>Text</h2>
  </div>
</div>
```

But looking at the code, I fear `children` might be too encompassing (this slot is just _one_ of the children) and not structurally/semantically correct (this slot is a child of wrapper, not the img tag).

An alternative I thought of is `wrapperLastChildSlot` (or `wrapperLastChild` if we want to be terse).

Naming things are hard 😅.

The call is yours, @pieh. Perhaps you can bring this up during the weekly meeting and see what the consensus is?

**Comment by stefanprobst** [comment]
I see your point now, but I remain unconvinced that adding another prop is necessary. I guess my general point is that we should encourage composition, and this seems like a good usecase for creating a reusable component -- and I don't really mind another level of `div` nesting:)

I updated my test repo at https://github.com/stefanprobst/gatsby-issue-8316.git to better handle fixed images:
```jsx
const ImageWithOverlay = ({ children, fixed, ...rest }) => (
  <div
    style={{
      display: 'inline-block',
      overflow: 'hidden',
      position: 'relative',
      width: (fixed && fixed.width) || '100%',
      height: (fixed && fixed.height) || 'auto',
    }}
  >
    <Image fixed={fixed} {...rest} />
    <div
      style={{
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: 'rgba(0,0,0,0.5)',
      }}
    >
      {children}
    </div>
  </div>
)
```

In any case, this is of course a maintainer's decision.

**Comment by stefanprobst** [comment]
Thanks @ryanditjia , this looks very interesting! I have myself been playing with ideas for `gatsby-image` [over here](https://github.com/stefanprobst/gatsby-image-compact), not using prop-getters and function child, but with an optional `as` prop:
```jsx
<Image fluid={fluid} as={MyCustomImageComponent} />
```

**Comment by stefanprobst** [comment]
I also removed stuff from state that does not really need to live there, removed some duplication between fixed and fluid, and render the noscript image with reactdom to keep it in sync with the component. Not yet feeling confident enough about this, but if there is a place to discuss possible v3 stuff I's be happy to iterate on this!

**Comment by pieh** [comment]
> I see your point now, but I remain unconvinced that adding another prop is necessary. I guess my general point is that we should encourage composition, and this seems like a good usecase for creating a reusable component -- and I don't really mind another level of `div` nesting:)

Yeah I think you are right, let's not overcomplicate `gatsby-image` if this can be done with composition. But it might be worth documenting your wrapper component in `gatsby-image` docs - it's not rocket science, but I feel like this is common use case that would benefit from some docs.

**Pull request closed without merging**
