### PR TITLE
fix(gatsby): Only use one redux namespace for plugins

### PR DESCRIPTION
**Pull request by stefanprobst**
Currently we have three redux namespaces for plugins (`flattenedPlugins`, `plugins`, `apiToPlugins`). This PR reduces this to just `flattenedPlugins`.
Also: use `flattenedPlugins.nodeAPIs` in `api-runner-node` and `page-hot-reloader`.

### CODE REVIEW

**Comment by wardpeet** [comment]
this is cool! Thanks for the cleanup, I still need to test this out. Removing these namespaces does this mean it's a breaking change? I haven't looked really at it.

**Comment by stefanprobst** [comment]
I don't think this was public API (?), so should be good.
`apiToPlugins` was introduced in #2588; and `plugins` is used once in `page-hot-reloader`. Both can easily just use `flattenedPlugins`.

**Comment by stefanprobst** [comment]
Looks like the one usage in `page-hot-reloader` also got removed recently in #12671

**Comment by stefanprobst** [comment]
@wardpeet Have you had a chance to look at this? Thanks!

**Comment by stefanprobst** [comment]
Anything missing from this?

**Comment by wardpeet** [comment]
doing it tomorrow!

**Comment by wardpeet** [comment]
Tomorrow took a while but i've tested it and read through the code and it looks 👌 

Thanks!

**Comment by stefanprobst** [comment]
Cool thanks!

**Comment by sidharthachatterjee** [comment]
Published in gatsby@2.3.5

**Pull request merged**
