### PR TITLE
[gatsby-link] update TypeScript typings for `navigate` function

### PR DESCRIPTION
**Pull request by resir014**
Some additions:

* Added `@types/reach__router` as a devDependency
* Exported `navigate` function in the root `gatsby` package
* Included `push` and `replace` into the "to-deprecate" list

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit f14a1984c50b3600875cf47786e223e9c781b98e

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6f054673f2cf742962591d

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit f14a1984c50b3600875cf47786e223e9c781b98e

https://app.netlify.com/sites/gatsbyjs/deploys/5b6f054573f2cf7429625912

**Comment by resir014** [comment]
@porfirioribeiro Oops, I didn't see that PR already existed!

It's mostly the same, but that PR didn't feature the newly-added `navigate` method which will replace both the `push` and `replace` methods in the future, so I added it here as well.

I've also updated the Link component props to extend `@reach/router`'s `LinkProps` instead, since that might work better

@KyleAMathews What should I do, close this PR and include these changes in #7150 as a review or keep this PR and wait for that to be merged?

**Comment by m-allanson** [comment]
Hey @resir014 thanks for adding this!

> close this PR and include these changes in #7150 as a review

I think that will be the simplest option if you're happy to do that? Then the types will be updated in one PR.

**Comment by resir014** [comment]
@m-allanson Sure! I'll close this shortly.

**Pull request closed without merging**
