### PR TITLE
Upgrade style-loader to fix CSS modules issue

### PR DESCRIPTION
**Pull request by eramdam**
Upgrade style-loader in `gatsby` to fix https://github.com/webpack-contrib/style-loader/issues/182

I was running with a weird CSS Modules issue within my gatsby site involving composition. Turns out it was caused by an old version of `style-loader` and was fixed in a more recent version than the one that `gatsby` is using. So this PR just upgrades said package.

I gotta admit I only have one testsite (it's still private for now so I can't share it, sorry!) and I did not see any issues by running this PR on it.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Huh so there's no breaking changes for webpack 1 between 0.13 & 0.19? Hard to tell from https://github.com/webpack-contrib/style-loader/releases

**Comment by eramdam** [comment]
@KyleAMathews not that I can see. Maybe there are some testsites that I could try this PR to see if it breaks something?

**Comment by KyleAMathews** [comment]
There's a bunch :-) https://github.com/gatsbyjs/gatsby/tree/master/examples

**Comment by eramdam** [comment]
@KyleAMathews oh lord that's a lot 😅  Worst case we can look at the diff between 0.13.x and the last version https://github.com/webpack-contrib/style-loader/compare/v0.13.1...v0.19.1

**Comment by KyleAMathews** [comment]
Haha sorry :-) I meant spot check the update against a few that use css.

**Comment by eramdam** [comment]
Here's the list of the examples sites I think is relevant for this PR, I'll be checking them off as I test them:
- [ ] using-css-modules
- [ ] using-emotion
- [ ] using-emotion-prismjs
- [ ] using-glamor
- [ ] using-jss
- [ ] using-postcss-sass
- [ ] using-sass
- [ ] using-styled-components
- [ ] using-styled-jsx
- [ ] using-styletron
- [ ] using-stylus

**Comment by KyleAMathews** [comment]
Tried the upgrade on a few sites and it seems fine... I really dislike that style-loader is < 1.0 — makes it hard to know what's changing/breaking. Looking through the list of commits, it seems all the changes are either fixes or new features so hopefully merging this will work, YOLO right? :-)

**Comment by jlengstorf** [comment]
Hiya @eramdam! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
