### PR TITLE
Copy EnvVar docs improvements back to v1 Docs

### PR DESCRIPTION
**Pull request by Brondahl**
See PR #9194 .
v2 Docs were still unchanged from v1, so all the same information and statements still hold, thus we should apply the Doc improvements to v1 docs too.

### CODE REVIEW

**Comment by Brondahl** [comment]
Re: CircleCI error - I assume that CircleCI just doesn't work on the v1 branch atm? Surely a doc change can't have broken that, right?

**Comment by Brondahl** [comment]
@m-allanson Could you do the honours?

**Comment by Brondahl** [comment]
@m-allanson Could you do the honours?

**Comment by Brondahl** [comment]
@m-allanson Could you do the honours?

**Comment by Brondahl** [comment]
@m-allanson Could you do the honours?

**Comment by pieh** [comment]
> Re: CircleCI error - I assume that CircleCI just doesn't work on the v1 branch atm? Surely a doc change can't have broken that, right?

Yeah, we no longer actively develop v1 and switched to circleCI recently and just didn't update config in v1 branch.

**Pull request merged**
