### PR TITLE
Update gatsby-transformer-xml README.md

### LINKED ISSUE #13773: gatsby-transformer-xml README with wrong example
## Summary
The ['How to query'](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-xml#how-to-query) section of the README for gatsby-transformer-xml package is wrong.

## Relevant information
I have run the example from [this page](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-transformer-xml#how-to-query) to try to understand better how queries work. I have saved the book.xml file into my project, and when querying with graphql with the query in the example:
```
{
  allBooks {
    edges {
      node {
        content
      }
    }
  }
}
```
what I get is:
```
{
  "data": {
    "allBooksXml": {
      "edges": [
        {
          "node": {
            "content": ""
          }
        },
        {
          "node": {
            "content": ""
          }
        }
      ]
    }
  }
}
```

when the example says I should be getting this:
```
{
  allBooks: {
    edges: [
      {
        node: {
          content: "Gambardella, Matthew",
        },
      },
      {
        node: {
          content: "XML Developer's Guide",
        },
      },
    ]
  }
}
```

As far as I understand, the books are the nodes, so it'd be expected to get back `content: ""` from within the nodes, having to go one layer deeper to get the content.
So with the following query:
```
{
  allBooksXml {
    edges {
      node {
        name
        content
        xmlChildren {
          content
        }
      }
    }
  }
}
```

I get all these data, which is more than just the author and title as in the example:
```
{
  "data": {
    "allBooksXml": {
      "edges": [
        {
          "node": {
            "name": "book",
            "content": "",
            "xmlChildren": [
              {
                "content": "Gambardella, Matthew"
              },
              {
                "content": "XML Developer's Guide"
              },
              {
                "content": "Computer"
              },
              {
                "content": "44.95"
              },
              {
                "content": "2000-10-01"
              },
              {
                "content": "An in-depth look at creating applications\n      with XML."
              }
            ]
          }
        },
        {
          "node": {
            "name": "book",
            "content": "",
            "xmlChildren": [
              {
                "content": "Ralls, Kim"
              },
              {
                "content": "Midnight Rain"
              },
              {
                "content": "Fantasy"
              },
              {
                "content": "5.95"
              },
              {
                "content": "2000-12-16"
              },
              {
                "content": "A former architect battles corporate zombies,\n      an evil sorceress, and her own childhood to become queen\n      of the world."
              }
            ]
          }
        }
      ]
    }
  }
}
```

Is this example wrong, or am I completely misunderstanding how this should work and doing something wrong?

### PR DESCRIPTION
**Pull request by violetamenendez**
## Description

Updating the documentation with complete examples of the queries and the results. As well as updating some comments for better understanding of how the plugin works.

## Related Issues

Fixes #13773

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@violetamenendez why did you close it?

**Comment by violetamenendez** [comment]
I edited it on github and couldn't run the linting tests. Now that I'm editing it locally on my workspace I was getting errors running `yarn test` from linting in other files that I haven't modified. I've commited my changes and they do pass linting now. I will send a new PR.

**Comment by muescha** [comment]
@violetamenendez you can easy update your pull request: 
Just push changes to your local branch ( I see it was `violetamenendez:patch-1`) and this PR gets updated automatic with you new contributions. 

PS: it works also if you are only change in GitHub web ui - change to you branch on GitHub. Hit the edit button.

**Comment by jonniebigodes** [comment]
@muescha a little late, this pull request was already merged.

**Comment by muescha** [comment]
@jonniebigodes I know. It was just for the next time if some change request of an PR coming.

**Comment by violetamenendez** [comment]
@muescha thanks for the advice. To be honest I tried to just update this PR by pushing to the branch but I couldn't find the branch in my fork for some reason. I had never used github UI before so I wasn't sure if the branch wasn't created on my fork or just for this PR or what, so I just scraped all that and pushed to a new branch. I will keep it in mind in the future though.

**Pull request closed without merging**
