### PR TITLE
Closes #569 Add port process conflict resolution and Chalk

### LINKED ISSUE #569: Log which process is using port when there's a conflict
This is too cool — added recently to create-react-app https://github.com/facebookincubator/create-react-app/pull/816

### PR DESCRIPTION
**Pull request by vinnymac**
I tested this out, it seems to work great, but I had to add someone else's repo as a dependency because the `getProcessForPort` method hasn't been pushed to the officially available `react-dev-utils` package on npm.

I also added some chalk here and there.

If you want me to change the wording or add the dependency a different way let me know 👍

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Awesome!

Could you add some screenshots?

Since this isn't much code — how about you just copy/paste the necessary code into Gatsby for now and then in a follow-up PR we use react-dev-utils once the function is published?

**Comment by vinnymac** [comment]
Okay I'll bring it over from `react-dev-utils` then. Looks like I need to fix a failing spec too. I'll see if I can get any good screenshots as well👍

**Comment by vinnymac** [comment]
I brought the source in and fixed the lint issues that came with it. I also made the formatting look prettier. Here are some screenshots of the changes. Would you like me to put them somewhere?

screen shot 2016-11-28 at 4 39 48 pm
screen shot 2016-11-28 at 4 42 05 pm

**Comment by KyleAMathews** [comment]
Nah — just wanted screenshots to document here the changes you were making. Lots great. Once the tests finish running, I'll merge the changes and make a quick release.

Thanks! This is a really nice little UX improvement.

**Comment by KyleAMathews** [comment]
Released in 0.12.20 https://github.com/gatsbyjs/gatsby/releases/tag/v0.12.20

**Comment by jlengstorf** [comment]
Hiya @vinnymac! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
