### PR TITLE
Update package.json to add url-loader

### PR DESCRIPTION
**Pull request by alacret**
Importing CCS and image files fails in a fresh installation of Gatsby 1.9.277.

A fix is to run:     

    `npm install url-loader --save-dev`

as described in #5479

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit da9b9b2c7db3fa4f1a0fbbea19414b01e8265c51

https://app.netlify.com/sites/using-postcss-sass/deploys/5b670f02dd28ef184d4726d5

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit da9b9b2c7db3fa4f1a0fbbea19414b01e8265c51

https://app.netlify.com/sites/gatsbyjs/deploys/5b670f01dd28ef184d4726c9

**Comment by LeKoArts** [comment]
This shouldn't be necessary as it's normally getting installed. Some people reported that on the Discord server and after deleting the node_modules folder and trying it again it got installed.

**Comment by Manoz** [comment]
Correct me if I'm wrong but the `master` branch is for _Gatsby v2.x_
If you're working with _Gatsby v1.x_ and want to contribute you should do it in the `v1` branch, right?
I never had your issue with Gatsby v2.x

Or do I write nonsense?

**Comment by KyleAMathews** [comment]
Yeah, also this is for the root of the repo where there's only packages for developing Gatsby plugins and core.

Appreciate the attempt to help @alacret!

**Comment by alacret** [comment]
Roger that... my first time... i'll be more carefull

**Pull request closed without merging**
