### PR TITLE
feat(gatsby): Webpack API for dependencies

### PR DESCRIPTION
**Pull request by pieh**
## Description

This PR adds couple of APIs that will allow adding arbitrary "code" modules to pages via graphql data layer. Make sure to check limitations section for current state of this PR

### `context.pageModel.setModule`

Function available in graphql resolvers (can be implemented via `createSchemaCustomization` / `createResolvers` hooks).

#### Signature:

```ts
context.pageModel.setModule({
  source: string,
  type?: "default" | "named" | "namespace",
  importName?: string
}): string
```

#### Arguments

- `source`: Absolute path to module to be added. If user wants to add some package - `require.resolve` should be used to get absolute path
- `type`: Defines type of import:
   - `default` - `import A from "b"`
   - `named` - `import { A } from "b"`
   - `namespace` - `import * as A from "b"`
- `importName`: only used when `type` is set to `named` - specifies named import to use

#### Return value

`context.pageModel.setModule` returns string identifier that later will be used to get instance of a module in frontend code. You will want to return this identifier in resolver where you implement `context.pageModel.setModule` function.

### `getModule`

This is frontend code function used to get instance of module. Function is imported from `gatsby`:

```
import { getModule } from "gatsby"
```

#### Signature

```ts
getModule(moduleId: string): any
```

#### Arguments

- `moduleId`: `getModule` expect module identifier (returned by `context.pageModule.setModule`) as argument. Module identifier is purposely not easily guessable (similar to `id` in nodes)

#### Return value

Actual module - this can be React component or any kind of arbitrary code.

### Example usage:

Check demo site - https://github.com/pieh/query-webpack-modules-demo-site/tree/0bba2e2158473689850fa9b6112c26dc6f6c8461 . In particular:
 - [`createSchemaCustomization` hook](https://github.com/pieh/query-webpack-modules-demo-site/blob/0bba2e2158473689850fa9b6112c26dc6f6c8461/gatsby-node.js#L43-L58) that converts `component` field in data ( for example https://github.com/pieh/query-webpack-modules-demo-site/blob/0bba2e2158473689850fa9b6112c26dc6f6c8461/content/hello-world/index.json5 ) to module identifiers of actual components implemented in https://github.com/pieh/query-webpack-modules-demo-site/tree/0bba2e2158473689850fa9b6112c26dc6f6c8461/src/components/page-builder.
 - [`getModule` usage](https://github.com/pieh/query-webpack-modules-demo-site/blob/0bba2e2158473689850fa9b6112c26dc6f6c8461/src/templates/page.js#L11-L22) in the frontend

### Limitations (currently)

- ~As-is this PR supports using new APIs only in page queries. To support static queries we will need https://github.com/gatsbyjs/gatsby/pull/23837 to be finished and merged.~ Static queries are now supported, not yet very much testing done as there can be surprising chains of things (static query adds a module which has static query and this can repeat over and over again)
- ~Hot data updates in `gatsby develop` are not working properly when new modules are added to a page - user does need to manually refresh browser to load new modules ( To handle this we will need https://github.com/gatsbyjs/gatsby/pull/24808 + some additional refactor on top ). EDIT: with state machine in place this is almost done, there are few more timing issues to solve (making long running process rewrite modules at proper time slots, we will need to put bit more things into state machine)~ this should be handled now. Due to various timing difficulties it might still not be 100% reliable (there are 2 levels - timing in node process, which is now nicely handled by state machine, but there is also timing in runtime - we receive webpack HMR updates and data updates without sync, so there is a code that tries to account for that (dev-loader changes that tries to wait for webpack updates)
- This PR doesn't implement public facing `registerModule` action that would allow users/plugins to stabilize webpack builds (add module to bundle even if not used currently so we don't have to rewrite whole lot of html files because of webpack hash changes)

### Trying it out

I published `gatsby@query-webpack-modules` that includes those changes - feel free to take it for a spin and let me know what you think

### Documentation

❌  This draft PR lacks any documentation related to added new APIs. 

## Related Issues

Related to https://github.com/gatsbyjs/gatsby/issues/18689

### CODE REVIEW

**Comment by imarenco** [comment]
Hello, thanks for this contribution, I did test on this feature, and I see that all the components that I bring with "getModule", are loaded async in the front-end, I wanted to ask if you had planned to add support server-side-rendering for this feature.

**Comment by imarenco** [comment]
Thanks for contribution, We test that, and work :)

**Comment by rasmuswoelk** [comment]
This is awesome 🚀

Tested and working! 💪🏼 Looking forward for this to be merged in!

Check it out on https://samhaeng.com (using wordpress-source-gatsby, advanced custom fields and flexible content)

**Comment by rasmuswoelk** [comment]
Hi @pieh 

Are there any plans for this feature to get merged into the official version any time soon? I have a setup running using this draft but Gatsby Cloud won't allow using incremental builds for this unofficial version.

Thank you for your work on this 🙌🏼

**Comment by pieh** [comment]
> Are there any plans for this feature to get merged into the official version any time soon? I have a setup running using this draft but Gatsby Cloud won't allow using incremental builds for this unofficial version.

I'm working right now on adding incremental build support (it's not just matter of this feature landing in stable release, there are some more code paths to cover when deciding which pages need to be rebuilt, because of how modules can include static queries, which can add more modules (which can have more static queries), the reconciliation is getting much more complex here. The plan is to land this within ~2 weeks right now

**Comment by rasmuswoelk** [comment]
@pieh Ah, I see. 2 weeks sounds great! I am already using this feature and I can let you know if I run into any issues.

Thank you so much for your work on this! Looking forward to seeing these features in an official version 💪🏼🚀

**Comment by oskareke** [comment]
This looks great though I'm getting "Adding modules doesn't work in gatsby-node" when I try to add a module through createFieldExtension inside of createSchemaCustomization. Any ideas?

**Comment by pieh** [comment]
> This looks great though I'm getting "Adding modules doesn't work in gatsby-node" when I try to add a module through createFieldExtension inside of createSchemaCustomization. Any ideas?

Do you try to use that field in gatsby-node? If not this might be a bug with `createFieldExtension` API. I will try using this setup tomorrow and report back

**Comment by oskareke** [comment]
Great, thanks. That was the error I get when I query it from GraphiQL, when I look for it in a page query 'elements' is just null.

**Comment by pieh** [comment]
Ah, graphiql part would explain the error. This is kind of expected, because graphiql is very similar case as gatsby-node. I didn't released new canary version, but current code also mention graphiql part ( https://github.com/gatsbyjs/gatsby/blob/0016fb14b3b5c2e512947de7f9a7bbad4d0370d8/packages/gatsby/src/schema/context.ts#L50-L52 )

I'm still trying to figure out proper way of handling this (or at least adding more context to that error message I guess), but the gist is that API relies on running within page or static query context, because this allows us to figure out which pages need to load those additional resources. The `getModule` is sync method because resources were already loaded by the time it gets called (one of my design goals for the API was so users don't need to figure out which pages need to load which resources, and so they don't need to specify this when they create pages - it's all "managed" for them with the only part they need to care about is using the API in resolver and `getModule` in frontend).

Neither gatsby-node, nor graphiql allow us to do so. I guess instead of error we could return a non-usable string saying that it's not supported, but users might just miss that because ... it's not an error. I think expanding on error message with additional explanation would be the way to go here?

**Comment by oskareke** [comment]
Ok! I'm not getting the component through the page query either though (it's null). Can you see what I'm doing wrong here?

Schema:

```
type MyType implements Node @dontInfer {
  elements: [JSON] @Elements
}
```

Schema customization:
```
exports.createSchemaCustomization = ({ actions, reporter }, options = {}) => {
  const { createTypes, printTypeDefinitions, createFieldExtension } = actions;
  createFieldExtension({
    name: 'Elements',
    extend(options, prevFieldConfig) {
      return {
        type: '[JSON]',
        resolve(source, args, context, info) {
          const moduleID = context.pageModel.setModule({
            source: require.resolve(
              `gatsby-theme-mytheme/src/components/testing`
            ),
          });
          return [{ component: moduleId }]
        },
      }
    },
  })
}
```

**Comment by pieh** [comment]
Code snippet looks about right, so it seems like a true bug. Are you able to share your site?

**Comment by oskareke** [comment]
I moved it to createResolvers instead and got it working. Great work @pieh.

**Comment by pieh** [comment]
> I moved it to createResolvers instead and got it working. Great work @pieh.

Ok, that is very interesting! I will take a closer look at this

**Comment by pieh** [comment]
Hmmm, I couldn't reproduce with using `createFieldExtension` - it seems to work just fine ( https://github.com/pieh/query-webpack-modules-demo-site/commit/02ac1291348525cb00c83c1122765aae82445184 ) is what I tried. But I also use latest code that wasn't yet published to npm canary. I will release new canary - it might be that I "randomly" fixed that since then (or this was fixed separately and I got it locally because I did quite a few rebases since last canary release).

**Comment by oskareke** [comment]
Ok, nice. The problem was probably on my end.

**Comment by oskareke** [comment]
Switching Gatsby version to this one seems to be breaking emotion-theming. The theme is no longer getting passed to components such as the one below. Do you have any ideas why?
```
const TextBlock = styled.p`
    color: ${(props) => props.theme.primaryColor};
`
```

**Comment by pieh** [comment]
> Switching Gatsby version to this one seems to be breaking emotion-theming. The theme is no longer getting passed to components such as the one below.

Are those components inside those "new" modules? Or they are just in pages? I wonder if that could matter here. Other thing that could happen is multiple copies of some libraries in `node_modules` causing bugs like that, but hard to tell without reproduction :(

**Comment by pieh** [comment]
I released new canary version of `gatsby@query-webpack-modules` ( concrete version is `gatsby@2.24.54-query-webpack-modules.25`).

What changed since last one:
 - base has been updated so all the fixes/improvements that happened on main branch are there
 - static queries are supported
 - better handling for hot data updates, especially ones that add new modules (but I wouldn't be surprised if it's still not rock solid, but at least I couldn't cause runtime crashes because of it anymore)
 - quite important - you need to use `GATSBY_EXPERIMENTAL_QUERY_MODULES` env var to enable this. Due to how it's handled right now - you can add `process.env.GATSBY_EXPERIMENTAL_QUERY_MODULES = 1` somewhere in `gatsby-config` to not have to remember about this much

Will update PR description shortly

**Comment by rasmuswoelk** [comment]
Hi @pieh 

I'm getting this error after upgrading to the newly released canary version:

image

I have set the `GATSBY_EXPERIMENTAL_QUERY_MODULES ` flag.

Do you have an idea why this could be happening? 

I can send you more info – just let me know what you need!

**Info:**
Node v13.7.0
Yarn 1.22.4
Mac OSX 10.15.6

**Comment by pieh** [comment]
@rasmuswoelk I think this is unrelated to this feature and rather is related to https://github.com/gatsbyjs/gatsby/issues/26723 (that I don't have much context on, but it seems to be a problem in one of packages used during image transformation - I see that people can kind of work around that by messing with quality, but proper fix appears to be https://github.com/imagemin/imagemin-pngquant/pull/71 which was not merged/published yet.

**Comment by rasmuswoelk** [comment]
@pieh Ah! I will check that out instead. Thanks! 👍

**Comment by rasmuswoelk** [comment]
Any progress on this one or perhaps an ETA? :)

**Comment by rasmuswoelk** [comment]
Any news? This feature is all I want for Christmas 😆🤞🏼🎅🏼

**Comment by pieh** [comment]
@rasmuswoelk Sorry, no news on this :(

This is unfortunately postponed for now due to refactors that aim to speed up time time it takes to start up development server and/or improve development experience taking priority. Some of those would be much harder to do if we got this feature in first (this feature does make a lot of things more complicated which would make it much harder for us to do those refactors).

**Comment by rasmuswoelk** [comment]
Hey @pieh 👋 

No worries – Thanks for the update! 🙌🏼

I'm just eager to be able to use this feature 👍  (I'm building a large page builder based site that could benefit a lot from this feature)

Do you think it would be possible to merge the changes from the latest Gatsby version into this draft?

Thank you so much for your work. It's greatly appreciated!

**Comment by lunelson** [comment]
I am also excited for this feature to be in Gatsby core, but @rasmuswoelk if you need a page-builder capability now, this package—based on my experiments so far—works very well right now (it is a part of the WP GraphQL Gutenberg project):

https://github.com/pristas-peter/gatsby-plugin-graphql-component

**Comment by rasmuswoelk** [comment]
@lunelson This looks awesome! I will try it out soon 👌🏼

Thank you for sharing this! 🙌🏼

**Comment by Grsmto** [comment]
> development server and/or improve development experience taking priority

dev experience taking priority over end user experience? 😕 This should be merged!

**Comment by manuelJung** [comment]
@pieh any updates on this?

**Comment by wardpeet** [comment]
This has been on hold. We've been focusing on the development experience with lazy images, query on-demand and ssr in develop. Currently, our focus is to speed up builds.

This feature has been moved to the backlog.

**Comment by lnikell** [comment]
Just out of curiosity, is there are any ETA when that PR could reach the stable version of Gatsby?

**Comment by rshackleton** [comment]
> This has been on hold. We've been focusing on the development experience with lazy images, query on-demand and ssr in develop. Currently, our focus is to speed up builds.
> 
> This feature has been moved to the backlog.

Faster builds are nice, but shipping too much code to the end-user is a serious issue for client-side performance and PSI scores. 

How likely is it that this PR or others related to lazy loading components, better code splitting, etc, will be brought in scope in the near future?

**Comment by SimonKlausLudwig** [comment]
Is there any update on this issue ?

**Comment by coreyward** [comment]
Hey @wardpeet + @pieh, any chance that this might get some time again now that SSR has shipped? Maintaining performance with localization without having to remove static queries is tough, and this would help a lot.

**Comment by phil-lgr** [comment]
Now that this is closed, is there another issue/discussion we can follow for this topic? @LekoArts Thanks

**Pull request closed without merging**
