### PR TITLE
docs(typography): add some references about typography to tutorial

### PR DESCRIPTION
**Pull request by JABedford**
## Description

Makes the process of creating a `typography.js` file more explicit in the tutorial. Removal of the code tags in the link below to make the link behave/appear better.

## Related Issues

Fixes my own issue of [gatsbyjs#12102](https://github.com/gatsbyjs/gatsby/issues/12102)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hmm previously we had the actual typography.js file people should use. We don't want people going through the tutorial to need to visit other doc pages as that increases risk beginners will get lost.

Was the typography file lost in your refactor @amberleyromo?

**Comment by marcysutton** [comment]
Ah, good point @KyleAMathews! That would be good to look into.

**Comment by KyleAMathews** [comment]
The tutorial did used to tell you to write out a typography.js config file — the screenshots and some of the language don't make sense without it so I restored the previous flow https://github.com/gatsbyjs/gatsby/pull/12131

**Comment by marcysutton** [comment]
Thank you, @KyleAMathews! 💪

**Pull request merged**
