### PR TITLE
fix(gatsby-source-filesystem): fix race condition when using `publicURL` field

### PR DESCRIPTION
**Pull request by styxlab**
## Description

Fixes the race condition as discussed in #27984. @pieh: Please review.

### CODE REVIEW

**Comment by styxlab** [comment]
Let me know how I can fix the `ci/circleci: integration_tests_gatsby_cli` test.

**Comment by pieh** [comment]
> Let me know how I can fix the `ci/circleci: integration_tests_gatsby_cli` test.

Ah sorry about this - please don't worry about this - this been flaky test that we didn't yet found a way to fix ( it's very likely unrelated to your changes)

**Review by pieh — APPROVED** [review]
Thank you

**Comment by vladar** [comment]
Published in `gatsby-source-filesystem@2.6.1`

**Pull request merged**
