### PR TITLE
Removed unnecessary component state, used props instead

### PR DESCRIPTION
**Pull request by alexisshriov**
removed unnecessary component state

## Description

there is no need to have a state in this component, we can use props directly

### Documentation

  this is part of the documentation of LanguageSwitcher, is a code example.

### CODE REVIEW

**Comment by pieh** [comment]
I was looking through this component, and now I wonder if we even need to have state here at all? It just seems like it's just shortcut for `this.props.i18n.language` (?)

**Comment by alexisshriov** [comment]
@pieh you are probably right, the only place where it's used is in renderLanguageChoice, and is just making a comparison, it could use props for the same purpose, do you want me to change it?

**Comment by pieh** [comment]
> @pieh you are probably right, the only place where it's used is in renderLanguageChoice, and is just making a comparison, it could use props for the same purpose, do you want me to change it?

If it doesn't have any functional difference, we should change it to drop using state. 

[`When to Use Derived State` section in react docs](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#when-to-use-derived-state) is good place to read a little bit about usage of derived state, and I don't think this case is good one for it

**Comment by pieh** [comment]
It even explitely calls "Unconditionally copying props to state" as anti-pattern ;) few section later

**Comment by alexisshriov** [comment]
I was using it as a replacement for componentWillReceiveProps which was already there, but since we don't even need to have a component state then the whole thing is unnecessary, if you want me I can remove the component state and just use props

**Comment by pieh** [comment]
> if you want me I can remove the component state and just use props

If you could do that, that would be awesome!

**Comment by alexisshriov** [comment]
@pieh okay I think it's done

**Comment by pieh** [comment]
Ok, there is just that line after edited code block:
> This is a pretty simple component. We're setting the language state based on the i18n prop so that we can check which language is currently active and show that in our menu.

That needs a bit of adjust as we don't have state anymore - maybe something like (additionally trying to avoid language like "easy"):
> This is a pretty small component. We are using `i18n` prop so that we can check which language is currently active and show that in our menu

(feel free to reword in different way)

**Comment by alexisshriov** [comment]
@pieh you are right!, okay I finished the text change, let me know if you want me to change anyhting else :)

**Comment by pieh** [comment]
I think we are good - it should automatically merge pull request now once all the checks finish

**Comment by alexisshriov** [comment]
@pieh thank you!

**Pull request merged**
