### PR TITLE
fix autolink-headers for in page hash navigation

### LINKED ISSUE #7475: [www] header hidden behind top nav when clicking on links in ToC
### Steps to reproduce behavior
1. Go to this doc: https://next.gatsbyjs.org/docs/deploy-gatsby/
2. Click on any of the ToC links, like "Heroku"

### Expected behavior
1. Page jumps to show Heroku at top of page

### Actual behavior
1. Page jumps and the header "Heroku" is hidden behind the top nav bar

### LINKED ISSUE #7590: gatsby-remark-autolink-headers doesn't apply offset when clicking on hash link within same page
## Description
If the history updates without the update originating from a `Link` component `onRouteUpdate`  won't fire, eg. `<a href="#some-id">Scroll to some id</a>`.

This causes plugins like `gatsby-remark-autolink-headers` to not work like you would expect when having inline links in the markdown. Try using the links in the TOC and you'll notice that they don't align correctly with the viewport.
https://deploy-preview-1104--reactjs.netlify.com/docs/getting-started.html 

Same thing happens on https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/

### Steps to reproduce

- Add a simple anchor tag on the site like `<a href="#some-id">Scroll to some id</a>` + and element with the id.
- Add a custom `onRouteUpdate` function.

Notice that it won't fire when clicking the anchor tag.

### Expected result

`onRouteUpdate` should be called.

### Actual result

`onRouteUpdate` isn't called.

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-beta.64 => 2.0.0-rc.0 
    gatsby-plugin-catch-links: ^2.0.2-beta.5 => 2.0.2-rc.0 
    gatsby-plugin-feed: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-plugin-glamor: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-plugin-google-analytics: ^2.0.0-beta.4 => 2.0.0-rc.0 
    gatsby-plugin-manifest: ^2.0.2-beta.4 => 2.0.2-rc.0 
    gatsby-plugin-netlify: ^2.0.0-beta.6 => 2.0.0-rc.0 
    gatsby-plugin-nprogress: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-plugin-react-helmet: ^3.0.0-rc.0 => 3.0.0-rc.0 
    gatsby-plugin-sharp: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-plugin-twitter: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-remark-autolink-headers: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-remark-code-repls: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-remark-copy-linked-files: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-remark-embed-snippet: ^3.0.0-rc.0 => 3.0.0-rc.0 
    gatsby-remark-images: ^2.0.1-beta.10 => 2.0.1-rc.0 
    gatsby-remark-prismjs: ^3.0.0-rc.0 => 3.0.0-rc.0 
    gatsby-remark-responsive-iframe: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-remark-smartypants: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-source-filesystem: ^2.0.1-rc.0 => 2.0.1-rc.0 
    gatsby-transformer-remark: ^2.1.1-beta.6 => 2.1.1-rc.0 
    gatsby-transformer-sharp: ^2.1.1-beta.7 => 2.1.1-rc.0 
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

### PR DESCRIPTION
**Pull request by pieh**
fixes #7590
fixes #7475

### CODE REVIEW

**Comment by chasemccoy** [comment]
Is there any way to easily know if this has been published yet?

**Comment by chasemccoy** [comment]
@pieh @m-allanson

**Comment by pieh** [comment]
This was published - you can click on merge commit (in X merget commit <sha>) and inspect tags:
screen shot 2018-09-19 at 22 02 30

**Comment by chasemccoy** [comment]
Great, thanks!

**Pull request merged**
