### PR TITLE
Style Guide code example fixups

### PR DESCRIPTION
**Pull request by cmwall**
- The tick marks showed up as an empty code example (screenshot below)
- The HTML code snippet was indented too far.
- The console statement in the JS example did not have a semicolon (which may confuse readers who see the first bullet point)

Tick marks issue: 
screen shot 2017-11-29 at 3 46 44 pm

Code indentation issue: 
screen shot 2017-11-29 at 3 46 50 pm

### CODE REVIEW

**Comment by KyleAMathews** [comment]
I added an npm script to format markdown recently — could you try running it on your markdown? `npm run format-markdown`

**Comment by cmwall** [comment]
The `format-markdown` script seems to be removing the semicolon from the JavaScript snippet as well as showing the empty tick marks:

screen shot 2017-11-30 at 5 31 45 pm

**Comment by KyleAMathews** [comment]
We don't want semi-colons in code — we're in the no-semi camp here :-D

As for the 6 back ticks — probably we should be escaping the back ticks.

**Comment by cmwall** [comment]
Should the first bullet be removed then?

screen shot 2017-12-03 at 10 08 39 am

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
