### PR TITLE
Update caching.md to conform to webpack 4 standard

### LINKED ISSUE #9151: Documentation about caching javascripts assets needs an update
## Description
Documentation about caching javascript is outdated:

https://www.gatsbyjs.org/docs/caching/#javascript

> Other files e.g. JavaScript files are not (yet) cachable. Gatsby v1 is using webpack 1 which doesn’t make it possible to produce paths tied directly to the content of the file. Gatsby v2 will ship with webpack 4 which will make possible long-term caching of our JavaScript files.

> The cache-control header should be cache-control: public, max-age=0, must-revalidate

### Steps to reproduce

mmmh, visit the documentation link https://www.gatsbyjs.org/docs/caching/#javascript

### Expected result

have the documentation about caching javascript assets for gastsby v2

### Actual result

The documentation describe what to do for gatsby v1

### Environment

/

Thanks !

### PR DESCRIPTION
**Pull request by tanvibhakta**
This PR will close #9151 
This doc talks about best practices, and I have read up on them to come to this conclusion. Please let me know if I'm missing anything or if I need to write a more detailed document for the same 

(the max-age should ideally be set based on how often you are likely to update your website)

### CODE REVIEW

**Comment by pieh** [comment]
js and css files in should be safe to cache forever now (similiar to files in `static` directory). Is that correct @KyleAMathews, @m-allanson?

See:
- https://github.com/gatsbyjs/gatsby/tree/master/integration-tests/long-term-caching
- https://github.com/gatsbyjs/gatsby/pull/6905
- https://github.com/gatsbyjs/gatsby/pull/5808

**Comment by KyleAMathews** [comment]
Yes exactly @pieh. @tanvibhakta JS & CSS file names are derived now from their content so we know now that these files are safe to be cached.

**Comment by tanvibhakta** [comment]
Thank you for the clarifications! Hopefully this is okay. :)

**Comment by LekoArts** [comment]
Duplicate: https://github.com/gatsbyjs/gatsby/pull/9254

**Comment by DSchau** [comment]
@LekoArts it's _sort of_ a duplicate, but there's some differences between the two here. I think we should prefer this one, since it seems to be doing things a little more cleanly and clearly.

**Pull request merged**
