### PR TITLE
feat(docs): Stub List page

### LINKED ISSUE #12362: [docs] Aggregate stub articles on page in docs
## Summary

So there are a various amount of docs pages that are stubbed out so if an individual comes upon the page and they wish to flesh it out, they can go click on the link to guide them to the GitHub issue so they can get an understanding on what is suggested on this page.

That said, if someone wishes to come to the docs page and wishes to see all of the currently stubbed pages, it would be nice to aggregate them on a single page. I propose some automated way to aggregate the links on a route in either the docs or contributing section.

On top of this, we could also use this as a quick check to make sure that all pages which were previously stubbed have the asterisk removed from the yaml files.

### PR DESCRIPTION
**Pull request by lannonbr**
## Description

I implemented a new page in the contributing section of the docs to aggregate all of the stubbed files in a single location so people can see any available articles that yet have to be written at a quick glance.

screenshot_2019-03-08 stub list gatsbyjs

## Related Issues

Closes #12362

### CODE REVIEW

**Comment by lannonbr** [comment]
> If some test coverage could be added for the business logic so that we can ensure it doesn't break over time. Is that something you could work on?

Yeah definitely, I would have to look how to write tests for it, but I think it likely will be possible. Is there anywhere currently references for tests that are for logic for portions of the website?

**Comment by lannonbr** [comment]
I'll go submit another commit to fix that lint error.

@DSchau, I'd be up for a pair session with someone to do the tests if someone is available to do such.

**Comment by DSchau** [comment]
@lannonbr for sure - here's general idea of how to get it up and running :)

https://github.com/DSchau/gatsby/pull/8

We'd have to add CI support, but that's fairly trivial!

**Comment by lannonbr** [comment]
Opened up an issue for adding testing for the .org site: #12545.

**Pull request merged**
