### PR TITLE
[gatsby-source-wordpress] Handle all media types

### PR DESCRIPTION
**Pull request by sebastienfi**
At the moment, only the photo files are handled.
This PR adds handling all media types.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hmmm why do we limit what media files we download? It seems by default we should just fetch all files and then if people want to blacklist some they could?

**Comment by pieh** [comment]
We don't limit/filter files we download, we do filtering when we try to match field values to media objects (wordpress file/attachment wrappers), so maybe better solution would be to just check if value looks like url and then try to match it to media object?

This is in general problematic because wordpress doesn't give as type schema- only values :/

**Comment by KyleAMathews** [comment]
Ah ok. Yeah, let's just download anything that looks like a URL. createRemoteFileNode will just error if it's not actually a URL so it's pretty harmless.

**Comment by sebastienfi** [comment]
Got rid of media inclusion / exclusion alltogether. Code is simplier and we don't need Regex anymore.

**Comment by sebastienfi** [comment]
Tested against example/wordpress and a couple big sites here, merging.

**Pull request merged**
