### PR TITLE
(#7134): tutorial; minimize confusion between npm/yarn

### LINKED ISSUE #7134: [v2] tutorial: minimize confusion between npm/yarn
Uninstall yarn and regenerate animated install gif and file tree screenshot (parts 0 and 1) to minimize npm/yarn confusion.

### PR DESCRIPTION
**Pull request by amberleyromo**
closes #7134.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 590ecc74a4adbb0e05fcf6399064b1ed8748968d

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6a78e573f2cf3859501ccf

**Comment by KyleAMathews** [comment]
Could you use mp4s instead of gifs? They're ~10x smaller and modern browses have nice built-in controls for controlling the playing of videos. [Handbrake](https://handbrake.fr/) is great for producing slimmed down videos for embedding.

**Comment by amberleyromo** [comment]
I certainly can. Have you done gif => mp4 with Handbrake before? Looked into it, not sure it supports that conversion. If not I'll find another solution.

While I'm at it, I'll convert the other gifs in part 0/1, too.

**Comment by amberleyromo** [comment]
Gifs in parts zero/one replaced with mp4s.

**Comment by KyleAMathews** [comment]
Deploy preview for *using-styled-components* failed.

Built with commit 7b9df2134b8327296984f9c219d46d8ae803cd53

https://app.netlify.com/sites/using-styled-components/deploys/5b6b1f33b31274306e89f573

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 7b9df2134b8327296984f9c219d46d8ae803cd53

https://app.netlify.com/sites/using-glamor/deploys/5b6b1f32b31274306e89f571

**Comment by KyleAMathews** [comment]
Did you run them through handbrake as well? One I looked at is 740kb still. They seem rather wide as well — they'll be displaying on a fairly narrow box so handbrake can resize as well.

**Comment by KyleAMathews** [comment]
sorry for giving advice in batches but one more tweak I'd suggest is the clips are a bit long — e.g. the hot reloading should be edited to making one change and seeing the result e.g. 3-4 seconds. Also you could eliminate a lot of the chrome on vscode so that it'd more readable on the narrow ~680px wide column in the docs. Perhaps stack the code editor on top of the browser or vice versa.

**Comment by amberleyromo** [comment]
Nah those are great suggestions, thanks. Rather get it right! I'll regenerate, no prob.

**Comment by amberleyromo** [comment]
Regenerated the hot reloading one, 46 kb.

The point of the other one (create-site) one is so that anyone doing it for the first time could feel confident they were seeing exactly what should happen in the terminal. It's definitely long, but I already paused through part of the install -- not sure how to further cut that down beyond the handbrake optimizations

**Pull request merged**
