### PR TITLE
[gatsby-plugin-sharp] Bump sharp to 0.18.2

### PR DESCRIPTION
**Pull request by jeffrey-xiao**
Switched my operating system to solus and `./node_modules/.bin/gatsby build` started to failed. I dug into it and it seems like solus support was added in `sharp@0.18.2`. See [issue](https://github.com/lovell/sharp/issues/856). I manually tested and `gatsby-plugin-sharp` installed properly after bumping sharp.

Operating system: Solus
Node: v8.4.0
Npm: v5.3.0

### CODE REVIEW

**Comment by KyleAMathews** [comment]
I've been waiting on the improvements to the `attention` crop to get it since that's our default crop mode https://github.com/lovell/sharp/issues/832#issuecomment-325472224

**Comment by KyleAMathews** [comment]
It looks like they've been added to libvips already. So we just need to wait for an update to sharp.

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 770233765fbc1cf14af1d128e8a6fe8795b67daa

https://app.netlify.com/sites/using-glamor/deploys/59dfd520df99531fda7ab38b

**Comment by KyleAMathews** [comment]
Closing this until sharp updates.

**Comment by fk** [comment]
@jeffrey-xiao sharp v0.19 is here: #3675!

**Pull request closed without merging**
