### PR TITLE
chore(showcase): meetup.com

### PR DESCRIPTION
**Pull request by cranberyxl**
## Description

Add meetup.com to the showcase

### CODE REVIEW

**Comment by muescha** [comment]
@Ekwuno are you sure that it is done with Gatsby? Because I can not find the mandatory body tag marker with `__gatsby`

**Comment by lannonbr** [comment]
The unauthenticated route is using Gatsby. If you open it in an incognito window you'll see

**Comment by cranberyxl** [comment]
You can also see an example of our new event pages that we are beta testing here: https://www.meetup.com/e/hans-solo-fan-club-monthly-meetup/sZ0wHqZN8o

**Comment by muescha** [comment]
ok i see it now.  my fault. sorry

i checked it many times. 

but i think only after a logout, but after logout i was at https://www.meetup.com/de-DE/ - i assumed the language specific pages are the same as the main

and on main https://www.meetup.com then i only looked at the `body` tag not subsequent tags


sorry again :)

**Comment by cranberyxl** [comment]
Internationalization is coming up next. Stay tuned.

**Pull request merged**
