### PR TITLE
new showcase site

### PR DESCRIPTION
**Pull request by urakymzhan**

### CODE REVIEW

**Comment by urakymzhan** [comment]
Is it removed or in the process of review?

**Comment by alexperronnet** [comment]
Your tests failed on CircleCI. U need to fix all failing checks before review.

Try to remove the extra space in front of `- title: urTitle`

**Comment by alexperronnet** [comment]
> Is it removed or in the process of review?

Your tests failed on CircleCI. U need to fix all failing checks before review.

Try to remove the extra space in front of `- title: urTitle`

**Comment by gillkyle** [comment]
Hi there! 👋 

With the launch of the [new, unified gatsbyjs.com](https://www.gatsbyjs.com/blog/announcing-unified-gatsby/) comes some changes to the showcase and starter submission workflow. We want the showcase pages to be useful to the community members who visit them as well as those that submit contributions. That means reevaluating the submission processes and criteria. To allow more time to complete that work, we’re pausing showcase submissions for the time being.

You can read more details about these updates in the PR here: #26442

I’m going to close this for now as the submission process likely won’t be the same as we try to improve upon it, but please submit your work once we have updated it!

**Pull request closed without merging**
