### PR TITLE
feat(gatsby): Add aggregation resolvers to group

### PR DESCRIPTION
**Pull request by nagiek**
## Description

This allows the GraphQL aggregate resolvers to be used in `group`, not just the high level `pagination`.

### Documentation
No changes.

## Related Issues

Builds upon the work done in #30789, but more of a fix to `group`, which never had the ability to recursively sub-group.

### CODE REVIEW

**Comment by nagiek** [comment]
@vladar mind if I tag you?

**Comment by vladar** [comment]
@nagiek This is pretty cool!

Those nested aggregations will likely be slow at scale but I am afraid it is already the case when they have to traverse many nodes, so this won't change the status quo. Mind resolving the conflict and I'll approve?

**Review by vladar — APPROVED** [review]
Thank you for this nice feature! 👍 

I've merged master and fixed tests (the remaining failing one is unrelated)

**Comment by nagiek** [comment]
Thanks so much!

**Pull request merged**
