### PR TITLE
Issue#20000 markdown caption error for remarks image

### PR DESCRIPTION
**Pull request by shan-hua**
About the issue: https://github.com/gatsbyjs/gatsby/issues/20000
It is caused by using the async function in `compiler.generateHTML()`. Since the caption written in Markdown will not be converted into a node, I changed it into using unified parser directly. It works but maybe it affords a better solution..

### CODE REVIEW

**Comment by shan-hua** [comment]
Related to this PR: https://github.com/gatsbyjs/gatsby/pull/16574/

**Comment by shan-hua** [comment]
Hi! Any feedbacks from the owner? :)

**Comment by LekoArts** [comment]
Hi, thanks for the PR!

This plugin option seems a bit convoluted as there is also this PR: https://github.com/gatsbyjs/gatsby/pull/21188

I suppose this wouldn't fix #2000 correct?

---

Can you please add tests to make sure that the intended behavior is working with this change and we don't see any regressions in the future? Thanks!

**Comment by shan-hua** [comment]
Hi @LekoArts , thank you for the reply! I checked the code in #21188, I've not tried or tested it but I guess it was a solution to solve the issue #20000 using `mdx.sync`, but the `mdx` plugin is required and I (and I think there are others) don't use mdx in the product. 

I'll add tests to it once I have time!

**Comment by wraithy** [comment]
I'd like to help out here if I can, as I'd love to be able to use markdown in captions.

@LekoArts I agree that the `compiler` option looks a bit problematic. I'm not super familiar with the codebase, so I'm going to break it down and write down my thought process here. Maybe you can correct me if I'm wrong here.

- Plugins are called recursively via `gatsby-plugin-mdx` or directly from `gatsby-transformer-remark`.  PR https://github.com/gatsbyjs/gatsby/pull/21188 fixes a `plugin-mdx` specific issue, so let's leave that to one side.
- The relevant `transformer-remark` code is [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/extend-node-type.js#L173,L195). It passes the compiler option to all "sub" plugins.
- There is no issue with `compiler.parseString`.
- There _is_ an issue with `compiler.generateHTML` which runs [this](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/extend-node-type.js#L343,L363) function. _Sometimes_, the `markdownNode` argument being passed into this function doesn't contain the "internal" property, which is relied on by the caching logic.

Here's what I propose: While this PR would solve the problem, I think it would be cleaner to follow the existing pattern of using the given `compiler` to do the heavy lifting. I think we should instead focus on fixing the broken caching logic in the [getHTML](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/extend-node-type.js#L343,L363) function.

I think that PR https://github.com/gatsbyjs/gatsby/pull/19288 was on the right track. However, there are at least three levels of caching and the same fix would likely need to be applied to all of them.

The thing which makes me a bit uneasy here is that there are _so many_ caching layers, and I'm not sure how necessary they are. If they _are_ necessary, maybe it would be more beneficial to dig into why the `markdownNode` object doesn't have that `internal` property, because side-stepping the caching mechanism (like PR https://github.com/gatsbyjs/gatsby/pull/19288) may cause performance problems.

**Comment by wraithy** [comment]
I've done more digging and I'm now convinced that the `internal` property is the real problem.

The functions in [gatsby-transformer-remark/extend-node-type.js](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/extend-node-type.js) are written expecting markdownNode to look like this:
```
const markdownNode = {
  id: createNodeId(`${node.id} >>> MarkdownRemark`),
  children: [],
  parent: node.id,
  internal: {
    content: data.content,
    type: `MarkdownRemark`,
  },
}
```
Normally, they seem to be invoked with objects created [in the normal way](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/on-node-create.js#L39,L47).

I think this problem started with `gatsby-remark-images` [using the code](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/index.js#L121) from PR https://github.com/gatsbyjs/gatsby/pull/16574 *incorrectly*. For context, this was added in PR https://github.com/gatsbyjs/gatsby/pull/16574.

My limited understanding here is:
```
compiler: {
  parseString: remark.parse.bind(remark),     // <---- The output of this
  generateHTML: getHTML                       // <---- Cannot be chained into this
},
```

I'm now fully on board with @LekoArts about this compiler option. I think we should consider other ways of doing this.

Sorry for the roundabout investigation here - like I said I'm not very familiar with the codebase.

**Comment by wraithy** [comment]
@LekoArts There is already a full suite of tests for this feature. Previously, the tests were passing because the compiler option was mocked out incorrectly (the mock does exactly what this PR is doing and uses the parsing libs directly). The discrepancy between the mock and production code was a real issue.

This PR now causes the tests to pass correctly.

I think the only possible change to the tests might be to remove [this line](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/__tests__/index.js#L83), since it's no longer used. I've tried this locally and the tests still pass.

---

Perhaps we could get this PR merged so long, and open up a different discussion about the `compiler` option?

**Comment by vladar** [comment]
I guess the idea is that `gatsby-remark-images` must be compatible with both - `gatsby-transformer-remark` AND `gatsby-plugin-mdx`.

This fix will make it work with `gatsby-transformer-remark` but not with `gatsby-plugin-mdx`. 

@mathieudutour What do you think on this?

**Comment by mathieudutour** [comment]
Yeah, the idea was that `gatsby-remark-images` is given the compiler so that it can be used anywhere.

This fix is hardcoding `hast-util-to-html` and so:
- won't work with mdx
- won't use the other remark options 

I think the proper fix is to make `getImageCaption` and await the compiler

**Comment by vladar** [comment]
So ideally the issue should be fixed in #21188. I label this PR as blocked, for now, to make sure it is not merged prematurely. We'll circle back here after #21188 is resolved.

**Comment by pvdz** [comment]
- Confirmed the current implementation is broken due to async. The compiler call is async and the calling function (that's changed in this PR) is using the return value directly in jsx, except the return value _must_ be a promise, so this will fail.
- The compiler call is async for two reasons;
  - Some loading stuff. and
  - It runs userland plugins, which may be async
- The proposed change in this PR does not run plugins and skip certain caches
- The linked PR adds `hast-util-to-html` and `hast-util-to-html` as `devDependencies` but I think those must now be regular `dependencies` as they're no longer "just" used in tests

This PR will be subsumed by https://github.com/gatsbyjs/gatsby/pull/21188 and is actively being worked on. Considering this issue has been open since December, I don't think an extra week delay for the fix is a big deal.

As such I'm going to close this PR in favor and anticipation of merging #21188

@shan-hua Thank you for submitting the PR. Please don't feel discouraged for this closure! Your PR attempted to fix a bug in the codebase and we're grateful for it. If the issue is not fixed by the time #21188 lands, or if #21188 turns out to take much longer to land than "just a week", please reopen this and we'll try to get it merged as a workaround.

**Comment by shan-hua** [comment]
> * Confirmed the current implementation is broken due to async. The compiler call is async and the calling function (that's changed in this PR) is using the return value directly in jsx, except the return value _must_ be a promise, so this will fail.
> * The compiler call is async for two reasons;
>   
>   * Some loading stuff. and
>   * It runs userland plugins, which may be async
> * The proposed change in this PR does not run plugins and skip certain caches
> * The linked PR adds `hast-util-to-html` and `hast-util-to-html` as `devDependencies` but I think those must now be regular `dependencies` as they're no longer "just" used in tests
> 
> This PR will be subsumed by #21188 and is actively being worked on. Considering this issue has been open since December, I don't think an extra week delay for the fix is a big deal.
> 
> As such I'm going to close this PR in favor and anticipation of merging #21188
> 
> @shan-hua Thank you for submitting the PR. Please don't feel discouraged for this closure! Your PR attempted to fix a bug in the codebase and we're grateful for it. If the issue is not fixed by the time #21188 lands, or if #21188 turns out to take much longer to land than "just a week", please reopen this and we'll try to get it merged as a workaround.

Thank you very much! Sorry I've been completely out of Github community for workload reasons in the last two months. As I mentioned in the quick PR that there should be a better solution on the async issue which I could not be familiar with :) I already see there are updates regarding to #21188 and I'll have a look right away! Happy to continue working with Gatsby team

**Pull request closed without merging**
