### PR TITLE
Update to latest Guess.js API changes

### PR DESCRIPTION
**Pull request by mgechev**
This PR introduces:

- [x] Update of the Guess.js API calls
- [x] Introduce a `reportProvider` property to let folks provide the GA report from a JSON file.
- [x] Allows GA authentication with a token from file

Please, also look at https://github.com/guess-js/guess/pull/60.

I tested the `gatsby-browser.js` part with the [wiki demo](https://github.com/guess-js/gatsby-guess) and it seems to be prefetching modules just fine. I also looked at the generated `link[rel="prefetch"]` tags by `gatsby-ssr.js`. Everything there looks fine too.

It'll be still very helpful if you can double check that everything is well functioning.

The PR depends on `guess-webpack@0.2.0` which is not yet published. See https://github.com/guess-js/guess/pull/60.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 12254bc67c041b868250892ad1851809a2533428

https://app.netlify.com/sites/using-glamor/deploys/5b2deaf89a0806346ef0d3c8

**Comment by mgechev** [comment]
❤️

**Comment by addyosmani** [comment]
💯

**Comment by jlengstorf** [comment]
Hiya @mgechev! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
