### PR TITLE
Bugfix for gatsby-remark-embed-snippet

### PR DESCRIPTION
**Pull request by bvaughn**
Noticed a possible off-by-N error when integrating the `gatsby-remark-embed-snippet` plug-in into the React website. Fixed and added a test.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks!

BTW, noticed another great reason to do this — now that Prettier is formatting snippets in markdown, if a snippet uses jsx{1-2} then Prettier ignores it :-(

**Comment by bvaughn** [comment]
Oh snap!

I tried _briefly_ to get Prettier to format our Markdown examples on reactjs.org but it threw an error b'c of the frontmatter section. Didn't have much time to look into it. Based on the `format-markdown` script, I guess you made it work though? 😄

**Comment by KyleAMathews** [comment]
Yeah — it works great! Perhaps they fixed the frontmatter thing — that seems like an obvious thing to make work.

**Comment by bvaughn** [comment]
That's really great to hear! I'll try it again then. I just updated Prettier this morning so 🤞

**Pull request merged**
