### PR TITLE
fix(documentationjs): fix example caption string

### PR DESCRIPTION
**Pull request by axe312ger**
# The problem

I want to display the description and some examples on how to use components via `gatsby-transformer-documentationjs`

Here is how it would look like in one of my components:

```js
/**
 * Amazing description
 *
 * @example <caption>My custom example title</caption>
 * doSth()
 * ...
 */
export default function SomeComponent({
...
```

See: https://jsdoc.app/tags-example.html

If I now try to get the caption value of the example via GraphQL, I get the following:

```
String cannot represent value: { type: "root", children: [[Object]], position: { start: [Object], end: [Object] } }
```

Means: Captions support is at the moment broken, if your code contains captioned examples and you try to query them, it will fail.

# The reason

We expect a string for `examples.caption`: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-documentationjs/src/gatsby-node.js#L104

But documentationjs gives us an object, representing that `<caption/>` xml tag

# Solution

Extract the caption string from the `<caption />` xml tag and pass this value to GraphQL.

### CODE REVIEW

**Review by vladar — COMMENTED** [review]
This looks like a breaking change, right? Failing tests seem to support this statement 😃

**Comment by axe312ger** [comment]
@vladar Havent have a look at the tests yet.

Well that title property is broken. You won't get ever any title out of documentationjs.

So no, its a fix :)

I'll come back to this soon and have a look at the tests.

**Comment by axe312ger** [comment]
@vladar I adjusted the original test and added a new one :)

**Comment by axe312ger** [comment]
Last failed tests are unrelated to my code.

I rebased on master. Lets see 👀

**Comment by wardpeet** [comment]
Correct me if I'm wrong but this adds a caption to the node? So, this is not a breaking change, correct?

**Comment by vladar** [comment]
Oh right, with the given schema for this plugin this is a bugfix indeed. My original point was that we already had `caption` on this node but it was an object:

```js
example?.caption?.children[0]?.children[0].value || null
```

So this PR changes it to `string` or `null`. But schema customization is already set to `string`, so now I am good with this.

Thanks for the PR! 👍

**Review by vladar — APPROVED** [review]

**Review by pvdz — APPROVED** [review]
lgtm

**Pull request merged**
