### PR TITLE
feat(gatsby): Includes ts/tsx files to eslint rules

### LINKED ISSUE #15114: Update eslint-config-react-app to ^4.0.0
For typescript-eslint supports.
Also, this Webpack rule needs to be changed to include `.ts`/`.tsx`

https://github.com/gatsbyjs/gatsby/blob/9fb78f8634d42e0f5547e320aafed9ae5b489223/packages/gatsby/src/utils/webpack-utils.js#L327-L334

### PR DESCRIPTION
**Pull request by ashr81**
## Description

Includes ts/tsx files extensions to check for the eslint rules.

Fixes #15114

### CODE REVIEW

**Comment by ashr81** [comment]
@wardpeet can you please rerun the tests. They failed because of GitHub downtime.

**Comment by me4502** [comment]
This appears to have broken builds of Gatsby sites using Typescript, as they're now expecting TypeScript files to just use JavaScript syntax?

**Comment by wardpeet** [comment]
rolled back in gatsby@2.13.39

**Comment by ashr81** [comment]
@wardpeet what shall I do to fix this issue?

**Comment by LekoArts** [comment]
I don't think the initial issue was valuable anyways. typescript-eslint is outdated (you now use eslint) and a typical Gatsby project is still JS, not TypeScript. People who want to use TypeScript can probably setup their own eslint setup.

**Comment by ashr81** [comment]
@LekoArts Ok, Makes sense.

**Comment by TheBear44** [comment]
@ashr81 You have to also move eslint-config-react-app to `^4.0.0` for typescript support otherwise it will fail all typescript files.

**Comment by wardpeet** [comment]
we've reverted the change for now as it seems to give some troubles in monorepos

**Pull request merged**
