### PR TITLE
fix(www): remove comments that are causing builds to fail

### PR DESCRIPTION
**Pull request by gillkyle**
## Description

When #22381 was merged builds started failing for `www` (the docs site). The error looks like this:

```
11:01:06 AM: error { "commentNumber": null, "level": 1, "id": "827a9a3a-6d53-5ec1-bde7-32147298b648", "parent": "ec28ebff-f198-59bc-9d97-9f0662e37679", "children": [ "f923a690-d5e9-5170-a02b-b51a17706ae7", "4bddd280-f7d7-5922-821a-89604b600b2f", "ed3d70f6-d142-5e7b-92f7-29ede823380d" ], "internal": { "type": "DocumentationJs", "contentDigest": "358a5703a82d2d403134479c9cf283fe", "counter": 7689, "owner": "gatsby-transformer-documentationjs" }, "kind": "function", "memberof": "plugins", "name": "minifyJs", "scope": "static", "examples": [], "tags": [], "optional": false, "docsLocation": { "start": { "line": 519, "column": 2 }, "end": { "line": 522, "column": 5 } }, "codeLocation": { "start": { "line": 523, "column": 2 }, "end": { "line": 551, "column": 6 } }, "description___NODE": "f923a690-d5e9-5170-a02b-b51a17706ae7", "params___NODE": [ "4bddd280-f7d7-5922-821a-89604b600b2f" ], "returns___NODE": [ "ed3d70f6-d142-5e7b-92f7-29ede823380d" ], "members": {} } error The node internal.owner field is set automatically by Gatsby and not by plugins
11:01:06 AM: not finished source and transform nodes - 21.021s
11:01:06 AM: ERROR Failed to compile: Error: Exited with code 1
```

This error pointed at the documentationjs transformer and the lines it identified didn't seem problematic, but removing them is enough to fix builds.

The problematic lines are:

https://github.com/gatsbyjs/gatsby/blob/e65eef43570c41c4f49c9e7dd177218702bb7bf5/packages/gatsby/src/utils/webpack-utils.ts#L519-L522
https://github.com/gatsbyjs/gatsby/blob/e65eef43570c41c4f49c9e7dd177218702bb7bf5/packages/gatsby/src/utils/webpack-utils.ts#L625-L628

I'm really not sure why this works or what the transformer is complaining about, so if there's an alternative way to do this I'm all ears!

## Related Issues

_None_

### CODE REVIEW

**Comment by KyleAMathews** [comment]
:yikes:

well... hmmm — yeah let's get this in — we need to fix this as we need comments in code haha

**Comment by KyleAMathews** [comment]
We need to see what's up with `documentationjs`

**Comment by gillkyle** [comment]
It only became a problem when the file changed to TypeScript. Maybe there's a discrepancy between how it parses JS and TS?

**Comment by KyleAMathews** [comment]
yeah must — `documentationjs` might have an old typescript version perhaps? Spitballing

**Comment by muescha** [comment]
created Issue on this - so it not get lost:

- #22492 `www: error with documentationjs at comments in TS files`

**Pull request merged**
