### PR TITLE
feat(babel-plugin-remove-graphql-queries) - Add rootDir option to plugin

### PR DESCRIPTION
**Pull request by isaac-martin**
## Description
The current approach taken by the `babel-plugin-remove-graphql-queries` assumes that you will always be running Storybook alongside a built gatsby site. ie a `public` folder is present. However, this is not the case for some users. 

This PR adds an option for advanced users to overwrite that default behaviour, it also adds some documentation as there was non documented here before (I had to dig around to even find how to overwrite the `static/d` directory)

### Documentation
There were no docs for this - I added a readme, not sure what else I need to do @gatsbyjs/documentation

## Related Issues

https://github.com/gatsbyjs/gatsby/pull/26242
https://github.com/gatsbyjs/gatsby/issues/26099

### CODE REVIEW

**Comment by LekoArts** [comment]
Hey, thanks for the PR!

The addition of the README is a bit misleading. The package is purely for internal usage and only through some more edge-casy situations (like Storybook) people got aware of it. So the plugin was never created for this use case:

> This [Babel](https://babeljs.io/) plugin is used when a component that you would like to render in [Storybook](https://storybook.js.org) uses `useStaticQuery` hook or `StaticQuery` component.

The documentation of this should go into the doc about Storybook itself :)

**Comment by isaac-martin** [comment]
Ok thanks, @LekoArts - I'll move this to storybook docs - is it worth keeping a really basic readme directing to the storybook docs? 

Any other comments on PR or is it looking pretty good?

**Comment by isaac-martin** [comment]
@LekoArts moved documentation.

**Comment by isaac-martin** [comment]
@gatsbybot @wardpeet @LekoArts how can I get a review here?

**Comment by ericabenojar** [comment]
I'm having the same issue, are there any updates on this? @gatsbybot

**Comment by wardpeet** [comment]
Thank you for you contribution. Sadly, we're not going to accept this PR. Like @LekoArts said, this is used for internal usage only. Removing static queries would still give you incorrect results.

We should create an addon for Storybook that does the necessary changes to make this work and to support mocking static-query

**Comment by isaac-martin** [comment]
thanks for the context @wardpeet - did you see the attached issue? This is negatively impacting many people since an update in the gatsby build pipeline that changes the output of the static queries. We only ran into these issues once we updated gatsby and its keeping us behind versions.

**Comment by wardpeet** [comment]
I'm not disagreeing. I well understand that it's an issue and that it comes from moving static-query out of webpack into seperate files. We can't measure the impact of these changes so we rather not merge these things as they might give us more headaches/maintenace than we can handle.

I hope you understand.

The fix that I would recommend is that you bring the babel plugin in your repository and change it yourself.

**Comment by lukesmurray** [comment]
@wardpeet could you at least document that the instructions in the [current storybook page do not work for static queries](https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/#storybook-version-5). Just wasted an hour trying to figure out why it wasn't working.

**Pull request closed without merging**
