### PR TITLE
Support 'import' option in gatsby-plugin-stylus

### PR DESCRIPTION
**Pull request by nkohari**
Hi there! This patch adds support to `gatsby-plugin-stylus` for the `import` option used by `stylus-loader`. It lets you define one or more files that will always be implicitly imported to all of your `.styl` files. (Typically I use it for variable definitions and other things that I want to use globally.)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@iansinnott this look good?

**Comment by iansinnott** [comment]
Awesome! Thanks @nkohari. This isn't something I use with stylus so I overlooked it when making the plugin initially. 

@KyleAMathews looks good to me 🚢

**Comment by KyleAMathews** [comment]
Sweet, thanks!

**Comment by KyleAMathews** [comment]
Published!

**Comment by jlengstorf** [comment]
Hiya @nkohari! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
