### PR TITLE
Improve plugin and cli resolution

### PR DESCRIPTION
**Pull request by Alxandr**
Solves #2748

### CODE REVIEW

**Comment by jquense** [comment]
It might be enough to combine usages and just go with the `resolve` package. We should be able to lean on the normal node resolution logic I think(?)

**Comment by Alxandr** [comment]
I'm not sure. There is so much magic going on here that I'm considering whether I will have to rewrite my entyre blog (again) :-/. For now I'm trying to fix things, but I'm running in to one issue after another with next to zero usable error information.

**Comment by KyleAMathews** [comment]
This isn't entirely a Gatsby problem — I spent a *long* time early in the Gatsby v1 cycle trying to make something similar to work but ran into a lot of weird problems with webpack and babel — neither of which like it when you try to put code outside of the root of the project.

For better or worse, we're kinda stuck right now unless someone wants to slug through fixing all the upstream dependencies that'd also need to work.

A much more viable solution is to just copy your other package into the Gatsby site directory on startup.

A local plugin using `onPreBootstrap` should do the trick https://www.gatsbyjs.org/docs/node-apis/#onPreBootstrap https://www.gatsbyjs.org/docs/plugins/#locally-defined-plugins

**Comment by jquense** [comment]
So I would start by splitting this into solutions for two seperate issues. The CLI resolution really should be safe to switch to the normal node resolution via `resolve`, that will give you same behavior as `require('gatsby') does locally.

For plugin resolution that's a bit tricker per Kyle's comments. There is already a mechanism for locally defined plugins, by sticking them in `src/plugins` which should help mitigate the issue. Longer we need to make sure that the module resolution logic is consistent across gatsby :/

**Comment by Alxandr** [comment]
My conclusion was just that this is a clusterfuck and I need to publish my plugins on npm :-/. Trying to get my blog building again has already taken me more than a day, and debugging into why gatsby isn't loading things correctly isn't helping.

**Comment by jquense** [comment]
you might want to try moving them to a local `plugins` directory, i've done that with a few sites with no issues.

**Comment by Alxandr** [comment]
@jquense that's what I originally had, and where my issues started.

**Comment by KyleAMathews** [comment]
What issues where you having with a local plugin?

**Comment by Alxandr** [comment]
Multiple graphql versions amongst others

**Pull request closed without merging**
