### PR TITLE
maintenance(docs): Add retext-spell to check spelling

### PR DESCRIPTION
**Pull request by tesseralis**
## Description

Add retext-spell in order to spell-check our docs and fix a couple of spelling errors. Also add an `update-dictionary` script to make adding new words to the dictionary easier.

## Motivation

Being able to auto-check words means that we can keep the Gatsby Style easier.

## Method

I created `dictionary.txt` by running retext-spell once and then extracting/sorting the "mispelled" words. I looked over the file by hand to find any obvious misspellings, brand name capitalizations, and locale-specific spellings and applied them. There's more stuff that we can improve/regularize, such as putting filenames and code in `backticks`, but I can leave it to follow-up PRs and community maintainers.

## TODO

* Make sure that emoji are spell-checked correctly.
* Script to update dictionary if new words are used.

## Caveats

* If "new words" are used, they have to be added to the dictionary. I'll write a script to enable that but it may get cumbersome having to constantly update the dictionary with new words (or it might catch some misspellings more, who knows!)

## Follow-up PRs

* Backticks on function names like `useStaticQuery`
* Backticks on package names (e.g. `gatsby-source-filesystem`)
* Standardize more brands and term names:
  * Gatsby/GatsbyJS
  * GraphQL
  * "CMS" (we have like five different ways we pluralize CMS)

### CODE REVIEW

**Comment by tesseralis** [comment]
@AishaBlake thanks! Right now it's failing because it doesn't recognize emoji, and I'm trying to figure out a way to fix that. Once that's done this should be good to go :)

**Comment by AishaBlake** [comment]
Yup. Was just about to leave a followup comment! I've dismissed my review for now but I _did_ check all the changes.

**Comment by muescha** [comment]
yeah - brand names :)


### split dictionary

maybe we split up the dictionary into "normal" words and brand names? that makes more easy to contribute to some parts - and for each part is better to check.

for example split into: 
- person names
- brand names
- Gatsby related file names, function names


### how to handle wrong settings

when i see the `dictionary.txt` i see some "wrong settings" like:

- macOS / MacOS
- NodeJS -> Node.js
- Paypal
- powershell / PowerShell

how we handle this?

### fine tune with hunspell

Titus (@wooorm) sayed the retext-spell implemented the [hunspell dictionaryformat](https://github.com/wooorm/nspell#personal-dictionary-documents), where some things can be better fine tuned?


### my settings

here is my list of brand names i found since i am looking for them... 

i prepared a setting for [`remark-lint-prohibited-strings`](https://github.com/Trott/remark-lint-prohibited-strings) which is obsolete with the `remark-spell` - here is the gist of it:

```text
AVA
Agility CMS
ButterCMS
BuzzFeed
CircleCI
CommonJS
Cosmic #(no Cosmic.?JS)
ESLint
Gatsby #(no Gatsby.?JS)
GitHub
Gitlab
GraphQL
Gzip
HalfStack
JavaScript #(no JS)
Linux
macOS
Markdown
npm #(always small)
Node.js
OpenTracing
PoseNet
PowerPoint
Prettier
React #(no React.?JS)
Snipcart
Socket.IO
Tailwind CSS
Theme UI
Travis CI
TypeScript
website
Vercel
WordPress
webpack #(always small)
Windows
Yarn
```

**Comment by tesseralis** [comment]
@muescha 

> maybe we split up the dictionary into "normal" words and brand names? that makes more easy to contribute to some parts - and for each part is better to check.

I was thinking this too and would probably do it in a follow-up PR. One thing we have to consider is  the workflow for adding new words to the dictionary. Right now the `update-dictionary` script adds all new words to `dictionary.txt`, and it would take more manual effort to move people names/brands/etc. to separate files.

> Titus (@wooorm) sayed the retext-spell implemented the hunspell dictionaryformat, where some things can be better fine tuned?

We can definitely fine-tune some of these names. I tried to standardize as much as I could, left some things out because there were many inconsistencies and they would be better put in another PR (for example, the many spellings of Gatsby/GatsbyJS and GraphQL). Since you've been so helpful so far with making things consistent, I was hoping you would be able to help us out with those :)

**Comment by muescha** [comment]
> @muescha
> 
> > maybe we split up the dictionary into "normal" words and brand names? that makes more easy to contribute to some parts - and for each part is better to check.
> 
> I was thinking this too and would probably do it in a follow-up PR. One thing we have to consider is the workflow for adding new words to the dictionary. Right now the `update-dictionary` script adds all new words to `dictionary.txt`, and it would take more manual effort to move people names/brands/etc. to separate files.
> 

if it splitted up, then the script can save new found words in a file: `new-misspellings.txt` which can manually spread over the different files. so the script would not touch existing dictionary files


> > Titus (@wooorm) sayed the retext-spell implemented the hunspell dictionaryformat, where some things can be better fine tuned?
> 
> We can definitely fine-tune some of these names. I tried to standardize as much as I could, left some things out because there were many inconsistencies and they would be better put in another PR (for example, the many spellings of Gatsby/GatsbyJS and GraphQL). Since you've been so helpful so far with making things consistent, I was hoping you would be able to help us out with those :)

yes - i like to help out :)

if the dictionary not helps that much we can also catch the some hard to defined word combinations with the `remark-lint-prohibited-strings` for example i see here the "always lovercase npm / webpack"?

**Comment by muescha** [comment]
is there a rule to ignore twitter handles like `@iam_timsmith`?

**Comment by wooorm** [comment]
@muescha there’s `retext-syntax-mentions`, see: https://github.com/remarkjs/remark-retext/issues/13#issuecomment-643737427

**Comment by tesseralis** [comment]
> if the dictionary not helps that much we can also catch the some hard to defined word combinations with the remark-lint-prohibited-strings for example i see here the "always lovercase npm / webpack"?

I think if you use hunspell's syntax you can make sure npm and webpack are lowercase:

```
webpack
*Webpack
npm
*NPM
```

> is there a rule to ignore twitter handles like @iam_timsmith?

We have `retext-syntax-mentions` installed and configured but for some reason it's not picking up `@iam_timsmith` as a mention?

**Comment by muescha** [comment]
> We have `retext-syntax-mentions` installed and configured but for some reason it's not picking up `@iam_timsmith` as a mention?

thats a twitter handle which allow underscore which is not catched with the `github` setting of `retext-syntax-mentions`

since this plugin not handle multiple styles ([a feature request](https://github.com/retextjs/retext-syntax-mentions/issues/7#issuecomment-644283909) it is not possible to add multiple configs 

multiple [config are not possible](https://github.com/unifiedjs/unified/issues/79)

but this "hacky hack" works on my machine:

```javascript
  .use(() => require("retext-syntax-mentions")({ style: 'twitter'}))
  .use(() => require("retext-syntax-mentions")({ style: 'github'}))
```

but [this hack is not recommended](https://github.com/unifiedjs/unified/issues/79#issuecomment-644853705) by the unify team

**Comment by muescha** [comment]
btw i [find out](https://github.com/retextjs/retext-syntax-mentions/issues/9) that many of the mentions are triggered by mdx import statements. but the team recommend for MDX files the `remark-mdx` plugin ( https://github.com/retextjs/retext-syntax-mentions/issues/7#issuecomment-644283909)

**Comment by muescha** [comment]
BTW: is it possible to deactivate via label or something the `Typo CI
/ TypoCheck` plugin for each commit? sometimes it makes to much noise

**Comment by tesseralis** [comment]
@muescha I definitely want to add `remark-mdx` but right now it's causing some linting because the MDX parser doesn't recognize `<!-- lint-ignore` comments. I want to get to the bottom of it and include the MDX parser in a different PR.

As for `Typo CI`, I was hoping we could get rid of it once this PR merges. Spell checks are most useful on text and documentation, not package names, so it would make sense to use retext-spell instead.

**Comment by muescha** [comment]
BTW: this is a better setting for mentions:

```javascript
.use(require("retext-syntax-mentions"), {style: /^@[\w-]{1,40}$/})
```

i have written a small tracer which checks the tree diffs - and there i see that the `github` setting are mostly catching mdx imports like `@compontents/nav-bar`

**Comment by muescha** [comment]
> @muescha I definitely want to add `remark-mdx` but right now it's causing some linting because the MDX parser doesn't recognize `<!-- lint-ignore` comments. I want to get to the bottom of it and include the MDX parser in a different PR.

i am not sure, but maybe this util helps with the lint-ignore messages?

https://github.com/unifiedjs/unified-message-control

**Comment by muescha** [comment]
> As for `Typo CI`, I was hoping we could get rid of it once this PR merges. Spell checks are most useful on text and documentation, not package names, so it would make sense to use retext-spell instead.

i was looking for an option to only have changed lines marked, but there is not this option.

in retext on CI we can use this tool for checking only changed lines: https://github.com/unifiedjs/unified-diff

**Comment by tesseralis** [comment]
@muescha this PR is merged in so feel free to start working on other PRs to standardize names and stuff.

**Pull request merged**
