### PR TITLE
fix(gatsby): remove default noscript tag from html.js template

### LINKED ISSUE #20021: remove noscript "This app works best with JavaScript enabled." from gatsby
### Basic example
https://user-images.githubusercontent.com/3924690/50913894-07cb6500-13fb-11e9-8102-dc833a71f8a3.png

### Motivation
Currently, we show a banner "This app works best with JavaScript enabled." when javascript is disabled. This was necessary to keep Lighthouse happy when gatsby-plugin-offline was enabled. We fixed gatsby-plugin-offline to refresh when javascript was disabled + lighthouse checks if any content is available so we should be able the message.

The message can be found at https://github.com/gatsbyjs/gatsby/blob/07e4b1165317a3b5a795f79b683e5ddeeaa441d2/packages/gatsby/cache-dir/default-html.js#L18-L20

### PR DESCRIPTION
**Pull request by gilbertoayala12**
## Description

Removed banner saying `This app works best with JavaScript enabled` as requested.
This is no longer necessary because ` gatsby-plugin-offline` was fixed to refresh when javascript was disabled plus lighthouse checks if any content is available.

## Related Issues
Fixes #20021

### CODE REVIEW

**Comment by wardpeet** [comment]
Hey, thanks for your first contribution! :tada: It seems like our tests are failing. To fix this, could you run `yarn jest -u packages/gatsby/cache-dir/__tests__/static-entry.js` in your terminal? This should change some of our snap files.

**Comment by gilbertoayala12** [comment]
@wardpeet Thank you! I ran the command you said, let's hope it passes the test 😅

**Comment by nkhil** [comment]
@gilbertoayala @pieh @wardpeet I'm desperately trying to remove the `This app works best with JavaScript enabled.` message displayed when my Gatsby site is viewed with JS turned off. 

I'm currently on Version `2.13.73`of Gatsby. Will upgrading to the latest turn off the `This app works best with JavaScript enabled.` message? 

I've tried a few other things, and haven't been successful.

**Comment by pieh** [comment]
@nkhil This changes was added in `gatsby@2.18.11`. You can either upgrade or use guide in https://www.gatsbyjs.org/docs/custom-html/ to customize html template

**Comment by nkhil** [comment]
@pieh Thank you so much - that's worked!

**Pull request merged**
