### PR TITLE
Migrate to React Hot Loader v4

### PR DESCRIPTION
**Pull request by noelebrun**
Simple migration to React Hot Loader v4 done. All in-browser test works fine on my side.

Unit test are not passing. They were already failing on origin/v2 before my changes.

Thanks,

Noé

### CODE REVIEW

**Comment by noelebrun** [comment]
#4314

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by noelebrun** [comment]
Np 😃For the v2 change, should we use the v2 branch? Cause there's a few test failing on the branch and the branch can't be merged.
Thx!

**Comment by KyleAMathews** [comment]
What v2 change? This PR was to v2 :-)

**Comment by noelebrun** [comment]
I mean for the next PR on the v2 😃

**Comment by KyleAMathews** [comment]
Oh right :-) yeah! Keep them coming!

**Comment by jlengstorf** [comment]
Hiya @noelebrun! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
