### PR TITLE
docs(gatsby-plugin-manifest): link to plugin-offline

### PR DESCRIPTION
**Pull request by CanRau**
I thought it would be a nice addition for easier discoverability

Off topic question related to `gatsby-plugin-manifest` wouldn't it be good to add some kind of cache busting to the generated icons?

### CODE REVIEW

**Comment by pieh** [comment]
I wonder if this link will work on NPM and/or gatsbyjs.org

> Off topic question related to `gatsby-plugin-manifest` wouldn't it be good to add some kind of cache busting to the generated icons?

There is WIP on that https://github.com/gatsbyjs/gatsby/pull/8343 (unfortunate PR name - it won't actually be random)

**Comment by CanRau** [comment]
You're right haven't thought about npm, so then better link to npm or absolute github link?

thanks for the link!

**Comment by pieh** [comment]
I would say use absolute link to gatsby site - https://www.gatsbyjs.org/packages/gatsby-plugin-offline

**Comment by CanRau** [comment]
great, done 👍

**Pull request merged**
