### PR TITLE
chore(starters): add gatsby-blogger

### PR DESCRIPTION
**Pull request by aslammultidots**
* added gatsby-blogger to starters

* Updated docs/starters.yml

### CODE REVIEW

**Comment by aslammultidots** [comment]
Can someone take a look at this PR? @gatsbyjs/ecosystem

**Comment by aslammultidots** [comment]
Can someone take a look at this PR? @gatsbybot [@gatsbyjs/ecosystem](https://github.com/orgs/gatsbyjs/teams/ecosystem)

**Comment by wardpeet** [comment]
Hey, thank you for using Gatsby and wanting to share this starter.

It's a little bit rude to bump your PR when it only been 20 hours since your PR. We are working hard to resolve PRs and issues as fast as we can.

Nonetheless, the starter looks pretty nice! Thank you for contributing but it seems like you have some linting issue. I think you want to run `npm run format`

**Comment by aslammultidots** [comment]
Thank you for your assistance with this.
Comment resolved, could you please take a look again? @wardpeet

**Comment by DSchau** [comment]
@aslammultidots looks like there's still an issue!

You can also run `npx prettier --write docs/starters.yml` and then commit that file, that should resolve the linting error.

**Comment by aslammultidots** [comment]
I've run the `npx prettier --write docs/starters.yml` command and pushed that to the branch that resolves the linting error.

**Pull request merged**
