### PR TITLE
chore(gatsby-plugin-mdx): refactor mdx-loader async code

### PR DESCRIPTION
**Pull request by pvdz**
This function was not optimally using the syntactic sugar of `async` functions. It was manually creating and returning a promise, including dealing with exceptions. Instead, the `async` keyword takes care of all of that for you implicitly. So this simplifies the function a little bit.

Suggest to review without whitespace.

### CODE REVIEW

**Comment by laurieontech** [comment]
Should this merge into master or merge into #25757?

**Comment by pvdz** [comment]
#25757 is likely to merge to master long before this one so I'll rebase this PR to master once it does and resolve the inevitable merge conflict.

**Comment by pvdz** [comment]
Once I fix the tests ... :thinking:

**Comment by pvdz** [comment]
I'm going to need more time to validate this is not going to break webpack so I'm going to put it in draft mode and return to it after my vacation,

**Pull request closed without merging**
