### PR TITLE
[Documentation] Conditional rendering in templates

### PR DESCRIPTION
**Pull request by Zephir77167**

### CODE REVIEW

**Comment by benjaminhoffman** [comment]
yes this is in fact true, but do we want to be advocating this as a best practice?  I'm not sure but curious.

**Comment by Zephir77167** [comment]
My personal opinion is that it is easier, particularly to newcomers who already know how to do conditional rendering in JSX, but don't know about GraphQL and could never write the `createPages` function from the docs by themselves (I know I couldn't). But maybe there are some cons I am not aware of with the way I just documented!

**Comment by KyleAMathews** [comment]
@benjaminhoffman this is very much expected and encouraged — render functions often respond to state that's passed in — the page location is just another bit of state. Creating separate layouts should be relatively uncommon.

**Comment by KyleAMathews** [comment]
Thanks @Zephir77167 for the PR!

**Comment by benjaminhoffman** [comment]
ah true.  Good call. Thanks @Zephir77167 for the PR!

**Comment by jlengstorf** [comment]
Hiya @Zephir77167! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
