### PR TITLE
Add error-overlay from CRA

### PR DESCRIPTION
**Pull request by nickmaltsev**
#1824 #582
aug-16-2017 16-18-57

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit d47956df014257bc28fd75f00193e894842ee3da

https://app.netlify.com/sites/using-glamor/deploys/599579cb424ef208680a7e4a

**Comment by KyleAMathews** [comment]
Hey @nickmaltsev thanks for looking into this! Your change though doesn't seem to have changed anything… check out the screenshot below I pulled from the CRA README. The error is styled differently than the one in your GIF.

**Comment by nickmaltsev** [comment]
@KyleAMathews i just used `react-error-overlay` the same way as it used in CRA. Screenshot that you linked above probably just outdated. Sorry if i miss something again ;)

**Comment by KyleAMathews** [comment]
No—webpack has a default error overlay which is why it looks like it's working.

Here's a screenshot I just took with the default starter.

screen shot 2017-08-19 at 9 06 23 am

It might be that CRA's overlay only works on webpack 2+. Did you investigate that?

**Comment by nickmaltsev** [comment]
@KyleAMathews oh.. my bad :) will investigate

**Comment by KyleAMathews** [comment]
This looks like the latest state of using the overlay elsewhere https://github.com/facebookincubator/create-react-app/pull/2515#issuecomment-325401249

**Pull request closed without merging**
