### PR TITLE
Proposed change for #6512

### LINKED ISSUE #6512: [www][v2] Button overlap with mobile navbar
## Description

The button that opens the sliding menu is overlapping with the "Showcase button"

screen shot 2018-07-17 at 3 23 54 pm

I'm wondering if this was an intended design

### PR DESCRIPTION
**Pull request by steoneill**
Fixes #6512

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 16affbd9a9bd9e9802b9a995a3fda04398a29d47

https://app.netlify.com/sites/using-postcss-sass/deploys/5b4f6540b13fb111c3599753

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 16affbd9a9bd9e9802b9a995a3fda04398a29d47

https://app.netlify.com/sites/gatsbyjs/deploys/5b4f653fb13fb111c359974b

**Comment by steoneill** [comment]
screen shot 2018-07-20 at 14 05 45


Hi there @m-allanson , screenshot above!

I've just moved the button away from the Showcase button to allow both to be used properly :)

**Comment by m-allanson** [comment]
Thanks :) cc @fk

**Comment by steoneill** [comment]
@fk no problem :) Glad to help!

**Pull request merged**
