### PR TITLE
[showcase] Built with (Cloudflare) Workers

### PR DESCRIPTION
**Pull request by tomByrer**
PR is more @signalnerve's deportment, so I'd like for him to approve, especially my sarcastic line 9684 ;)

## Description

Add to showcase: Built with (Cloudflare) Workers

I searched all PRs & Showcase, & found this site was missing.
Added "JavaScript" category since most will use JavaScript for some if not all of the Cloudflare Worker code.

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! A couple things to address before we get this merged.

- "Official" is not a designated category so that should be removed.
- The README for the github repo does not include instructions for running this site. Can you update it to do so?

**Comment by tomByrer** [comment]
>     * "Official" is not a designated category so that should be removed.

Sure I can do that.  But should I also make a PR to remove "Official" from [your official catagories](https://github.com/gatsbyjs/gatsby/blob/master/docs/categories.yml#L38)?

> The README for the github repo does not include instructions for running this site.  Can you update it to do so?

Sorry, but not at this time:
1. It's not my repo; & I'm not employed by Cloudflare (perhaps later? ;) )
2. It is [built upon Sanity.io headless CMS](https://www.sanity.io/blog/how-cloudflares-built-with-workers-was-built), which is a full tutorial in itself.

I'd rather nuke the reference, or leave it in as a simple 'proof' it uses GatsbyJS.  Which do you think is best?

**Comment by laurieontech** [comment]
Ah, I see the confusion. That list of categories is for starters and sites, two separate arrays. Official is only valid for starters.

And I'd agree, let's remove the GitHub link.

Thanks!

**Comment by tomByrer** [comment]
compleated

**Comment by laurieontech** [comment]
Thanks!

**Comment by signalnerve** [comment]
thanks @tomByrer! super cool :)

**Pull request merged**
