### PR TITLE
Build-html static file using the Webpack magic comment to provide the link rel

### PR DESCRIPTION
**Pull request by gkawin**
Follow from this article
 [https://medium.com/webpack/link-rel-prefetch-preload-in-webpack-51a52358f84c](https://medium.com/webpack/link-rel-prefetch-preload-in-webpack-51a52358f84c)

the new Webpack version also has a magic comment to help to do the Code splitting using by dynamic import like this.
```js
import(
  /* webpackChunkName: "redeem", webpackPrefetch: true */
  "./RedeemModal"
)
```
and that, In the `build-html` we will using the magic comment to generate the `link tag` like.
```html
<link rel="prefetch"  href="/3.0.0/0-7f890f8c04b440c6714b.js" as="script" />
```
But...unforturnaly, the current version of Gastby doesn't has support yet. This PR will be the brand new feature to build-html in the dynamic import and improvement the UX experience.

### CODE REVIEW

**Comment by pieh** [comment]
Hey, can you add some more context to changes here? I know it's WIP, but it would be helpful to know what You are trying to do

**Comment by dtinth** [comment]
@pieh This PR solves this issue: https://github.com/gatsbyjs/gatsby/issues/5683

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 48418634271d0a1cb40f24713fa522310a289205

https://app.netlify.com/sites/using-glamor/deploys/5b18f25be39e7c159ec54e1d

**Comment by gkawin** [comment]
Oh, It's my fault. It might be ok if I close this branch and open again when I stayed on the `v2` branch. 
@dtinth Oh god. I totally forgot that v2 branch is using `webpack4.4.1` but `childAssets` is provided on v4.6.1 😂😂

**Comment by KyleAMathews** [comment]
Haha no worries :-)

Gatsby uses a tilda for the webpack version so we're pulling the latest. Your PR can up that number to ensure everyone has a new enough version.

**Comment by gkawin** [comment]
@KyleAMathews Gatsby package will get the latest package version including Webpack (I just check the webpack version on my local computer. I got 4.10.2). That means I can switch the `webpack-stats-plugin` to  `webpack --profile --json > stats.json` instead?

**Comment by dtinth** [comment]
@gkawin Some users may be using Gatsby v2 at an earlier time and have webpack < 4.6.1 installed in their tree/package-lock/yarn.lock. Increasing the webpack version here will ensure that webpack is upgraded to a version that supports this feature when they upgrades Gatsby.

**Pull request closed without merging**
