### PR TITLE
Add star icon to featured sites

### PR DESCRIPTION
**Pull request by berraknil**
fixes https://github.com/gatsbyjs/gatsby/issues/6742

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 2a01a7720de744db946bd8280a5cd28da83b920c

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5b44ca82d3f13412a05fd2

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 2a01a7720de744db946bd8280a5cd28da83b920c

https://app.netlify.com/sites/gatsbyjs/deploys/5b5b44c982d3f13412a05fca

**Comment by fk** [comment]
Hey @berraknil, thank you and sorry for getting around to review this so late!
Just pushed some changes and will merge now. 

Please take a look at 8f9d930 which replaces some of the CSS property values with their equivalents from `www/src/utils/presets.js` and `www/src/utils.colors.js`.

**Comment by berraknil** [comment]
@fk thanks for the review and fixes, will keep those pre-assigned property values in mind next time!

**Comment by fk** [comment]
👍

**Pull request merged**
