### PR TITLE
Fixes component-renderer to allow for use of client-only-paths

### PR DESCRIPTION
**Pull request by scottyeck**
According to https://github.com/gatsbyjs/gatsby/issues/1501, it looks like client-only-paths are broken in `1.0`. (It actually looks like this has been broken since `v1.0.0-beta.6`.)

Looks like `componentShouldUpdate` assumes that, a route-change should only trigger a re-render if its accompanied by a corresponding change in the higher-level `pageResources.component`. In theory, this makes sense, though it's directly in conflict with the notion of client-only paths. My thought is that the re-render should be triggered if either the component changes OR the found page has a corresponding `matchPath`, (as demonstrated in the client-only-paths docs), in which case gatsby may not know whether or not a re-render is necessary and should optimistically trigger one.

If there's a better way to go about this, great. 😎

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 8a4bde079c58d00ec2759c3176a5870bde57c55f

https://app.netlify.com/sites/using-styled-components/deploys/596e526e424ef25aaa0bf7a7

**Comment by KyleAMathews** [comment]
Nice! I liked how tightly scoped the fix is. Don't fix one thing and inadvertently break another (like I did for beta.6 ;-))

**Comment by skorowarkin** [comment]
With a current (1.9.67) version of Gatsby I came upon non-working links to the client-only path in production build. I found this thread and discovered the following mismatch between the contents of this fix and the master, in the loader.js:

      ...
      const done = () => {
        if (component && json && (!page.layoutComponentChunkName || layout)) {
          pathScriptsCache[path] = { component, json, layout } <<< here missing the "page" member
          const pageResources = { component, json, layout } <<< and here too

After I added that "page" member, links began to work. Maybe at some point it was overwritten with a "layout" by mistake?

**Comment by KyleAMathews** [comment]
@skorowarkin someone else was mentioning that this was broken — could you submit a PR with the fix!?

**Comment by skorowarkin** [comment]
@KyleAMathews done: https://github.com/gatsbyjs/gatsby/pull/2506

**Pull request merged**
