### PR TITLE
add Segment Blog to list of sites built with gatsby

### PR DESCRIPTION
**Pull request by stephenmathieson**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit df7f5c57abf10f9d4d9f09e8547195ca370ca058

https://app.netlify.com/sites/gatsbygram/deploys/590bb9d9424ef231ab297729

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit df7f5c57abf10f9d4d9f09e8547195ca370ca058

https://app.netlify.com/sites/gatsbyjs/deploys/590bb9d9424ef231ab297726

**Comment by KyleAMathews** [comment]
Woot! Thanks for sharing!

(and ignore the error comments — they're expecting the 1.0 branch so fail on master)

**Comment by jlengstorf** [comment]
Hiya @stephenmathieson! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
