### PR TITLE
Use Prismjs dependency info from library instead of vendored version

### LINKED ISSUE #5001: Remark prismjs fails to highlight PHP with errors
## Description

Using `gatsby-remark-prismjs` to decorate code blocks on PHP code produces the following errors:
```
TypeError: Cannot read property 'tokenizePlaceholders' of undefined
  
  - prism-php.js:121 
    [static]/[prismjs]/components/prism-php.js:121:40
...
```
It looks like the PHP language now requires the `markdown-templating` language dependency.

### Steps to reproduce

1. Using a fresh install, add `gatsby-remark-prismjs`.
2. Set up the following minimal configuration in `gatsby-config.js`:
    ```js
    // gatsby-config.js
    module.exports = {
        plugins: [
            {
                resolve: 'gatsby-transformer-remark',
                options: {
                    plugins: [
                        {resolve: 'gatsby-remark-prismjs'},
                    ]
                }
            },
            {
                resolve: 'gatsby-source-filesystem',
                options: {
                    path: `${__dirname}/content`,
                    name: "markdown-pages",
                }
            }
        ]
    }
    ```
3. Set up `gatsby-node.js` to create markdown pages:
    ```js
    exports.createPages = ({ boundActionCreators, graphql }) => {
        const { createPage } = boundActionCreators;
    
        const blogPostTemplate = path.resolve(`src/templates/blog.js`);
    
        const query = graphql(`{
          allMarkdownRemark(
            sort: { order: DESC, fields: [frontmatter___date] }
            limit: 1000
          ) {
            edges {
              node {
                frontmatter {
                  path
                }
              }
            }
          }
        }`);
    
        return query.then(function(result) {
            if (result.errors) {
                return Promise.reject(result.errors);
            }
    
    
            result.data.allMarkdownRemark.edges.forEach(function({node}) {
                createPage({
                    path: node.frontmatter.path,
                    component: blogPostTemplate,
                    context: {}, // additional data can be passed via context
                });
            });
        });
    };
    ```
4. Create a markdown file with any PHP code block in it.
5. Observe errors.

### Expected result

Syntax should be highlighted.

### Actual result

`gatsby develop` fails with errors.

### Environment

* Gatsby version (`npm list gatsby`): `gatsby@1.9.250`
* gatsby-cli version (`gatsby --version`): `1.1.50`
* Node.js version: `v8.9.4`
* Operating System: OSX 10.13.4

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`:

### PR DESCRIPTION
**Pull request by rbayliss**
`gatsby-remark-prismjs` has historically used a vendored copy of PrismJS's language dependencies, because this data wasn't exposed on the PrismJS side.  This is no longer the case - as of 1.13.0, language dependency data is exposed in `components.js`.  This PR uses the data from `components.js` to load languages, meaning there will be no more maintenance required to stay current with PrismJS changes.  

Fixes #5001

### CODE REVIEW

**Comment by dangerbot-gatsby** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  
Gatsby requires contributors to sign each commit.

You can do this for your branch with `git rebase --signoff`, or for a single commit with `git commit --amend -s`.

Check out the [Developer Certificate of Origin docs](https://www.gatsbyjs.org/docs/how-to-contribute/#developer-certificate-of-origin) or comment here if you've any questions.

  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by pieh** [comment]
Couldn't prismjs be peerDependency then? This update still ties prismjs version to gatsby-remark-prismjs. If  prismjs would become peerDependency it would be up to user to pick prismjs version and even less maintenance needed for gatsby plugin. (just thinking here)

**Comment by rbayliss** [comment]
I don't have an opinion there.  As long as we're using prismJS > 1.13.0, whatever version of Prism should be fine.  Would peerDependency require the user to install PrismJS explicitly, or would it be installed automatically still? (ie: Would the instructions need to change to `yarn add gatsby-remark-prismjs prismjs`?)

**Comment by pieh** [comment]
User would have to explicitly install prismjs - we already do this with react helmet plugin ( https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-react-helmet#install )

**Comment by rbayliss** [comment]
Ok, will do shortly.

**Comment by pieh** [comment]
Thanks for adding it to devDeps too. I've missed that this would cause issues with tests.

Last things from me:
- could you bump `gatsby-remark-prismjs` version to 2.0.0 as this is breaking change (requiring to install prismjs package seperately)
- update installation instruction in readme and add `prismjs` to `npm install` command there?

**Comment by rbayliss** [comment]
Ok, think we're all set with the requested changes.  Sorry for the commit noise... having some trouble remembering to `-s` on my commits.

**Comment by pieh** [comment]
Don't worry about the noise. One snapshot is missing update - I guess this change got lost in all the signoff handling, because that test was passing before change to peerDeps.

**Comment by KyleAMathews** [comment]
Oh, and congrats on snagging issue #5000!!! :-D

**Pull request merged**
