### PR TITLE
upgrade dependency probe-image-size

### PR DESCRIPTION
**Pull request by CanRau**
update probe-image-size to fix issues with padding bytes as of https://github.com/nodeca/probe-image-size/issues/20 in gatsby-plugin-sharp, gatsby-transformer-sharp, gatsby-remark-copy-files, add test image which failed prior to this fix

please let me know if I'll need to change anything, as I'm still quite new to contributions, pull requests etc

### CODE REVIEW

**Comment by CanRau** [comment]
hm..I guess I should've committed the new snapshot right?

**Comment by pieh** [comment]
For testing this I think it would be better to export `getImageSize` function from `gatsby-plugin-sharp/src/index.js` and use just that in your test. If I understand issue here correctly - we would only really care about return value of that function, correct?

You also need to commit updated snapshot. To generate it you need to run `jest --updateSnapshot`.

> I'm still quite new to contributions, pull requests etc

This is very good start! :)

**Comment by CanRau** [comment]
okay i've got some time now…
last time i did all the update testing in another install just copying my changes to gatsby fork, so i did no actual testing in the fork *bad me*

i'm undoing my changes to properly follow the [How to Contribute Guide](https://www.gatsbyjs.org/docs/how-to-contribute/) is it okay to just force push my changes to my fork?
the pr will just update? or should i open a new clean pr?

**Comment by KyleAMathews** [comment]
No need to create a new PR unless the goal of the PR complete changes. You don't need to rewrite history unless you want to. We squash commits when merging so the commit added to master is always clean.

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 63ef65412726033968f0deb0ba063e9f11c4a7d7

https://app.netlify.com/sites/using-glamor/deploys/5ad67e1bdd6a543645100ffa

**Comment by CanRau** [comment]
thanks for chiming in kyle 👍 let me know if i can improve anything :)

forgot to signoff so repushed..

i'm curios why how-to-contribute guide is all `yarn` except for `npm run watch`?

and one more question, how to best keep my fork synced? till now i always reforked but that takes time and what am i having git for right^^ i followed [Syncing a fork](https://help.github.com/articles/syncing-a-fork/)
just wanted to check back with you guys, so `git fetch upstream` and then merge or rebase? or @KyleAMathews hint on squashing commits maybe means that it actually doesn't matter in this case?

tests are passing, still i'm getting this
```
console.error packages/gatsby-plugin-sharp/src/index.js:55
    Failed to process image /Users/Can/Sites/Repositories/forks/gatsby/packages/gatsby-plugin-sharp/src/__tests__/images/144-density.png { Error: ENOENT: no such file or directory, open '/Users/Can/Sites/Repositories/forks/gatsby/public/static/test-1234-dac52.png'
      errno: -2,
      code: 'ENOENT',
      syscall: 'open',
      ✓ adds pathPrefix if defined (11ms)s/forks/gatsby/public/static/test-1234-dac52.png' }
```
and
```
console.log packages/gatsby/src/bootstrap/load-plugins/validate.js:66

    Your plugins must export known APIs from their gatsby-ssr.js.
    The following exports aren't APIs. Perhaps you made a typo or
    your plugin is outdated?

    See https://www.gatsbyjs.org/docs/ssr-apis/ for the list of Gatsby SSR APIs
     — Your site's gatsby-ssr.js is exporting a variable named "foo" which isn't an API. Perhaps you meant to export "notFoo"?

warning replaceRenderer API found in these plugins:
```

thought it might be interesting

**Comment by pieh** [comment]
You can do either rebase or merge, doesn't really matter as we squash commits - use method you are most comfortable with. 

We decided to remove signoff requirement for now - it proved to be real pain for both contributors (having to do signoff) and maintainers (asking people to do signoff and guiding through it).

Console output in tests surely isn't nice, but this isn't something you introduced - it was already there and doesn't impact test results, so don't worry about it.

**Comment by pieh** [comment]
It seems some of changes in your `yarn.lock` are pointing to local registry ( https://github.com/gatsbyjs/gatsby/pull/5007/files#diff-8ee2343978836a779dc9f8d6b794c3b2L10821 )

**Comment by CanRau** [comment]
ahaa..that's probably because i'm using [verdaccio](http://www.verdaccio.org/) for a while now..haven't looked into lock files since then..good catch and good to know! humm..maybe i shouldn't use it anymore, or find a workaround…

**Comment by CanRau** [comment]
nice thanks :)

**Comment by pieh** [comment]
@CanRau did you want to close this PR? It's wasn't merged yet and I just wanted to approve it

**Comment by CanRau** [comment]
aha..okay i misinterpreted the green tick not reading properly
now i understand the "… **approved** these changes.." :D

**Comment by CanRau** [comment]
🙏 i'm sorry guys…lesson learned ☺️

**Comment by m-allanson** [comment]
No problem! Thanks for the fix :)

**Pull request merged**
