### PR TITLE
Lighthouse doc

### PR DESCRIPTION
**Pull request by shannonbux**
Wondering if it'd be worth creating a doc about webpagetest.org too?

Need feedback on the division of these docs--does it make sense to have them all separate? I was thinking it does because people might search for them separately.

Another titling option would be to use the names of each plugin, since three of these docs have you use a gatsby plugin.

### CODE REVIEW

**Comment by shannonbux** [comment]
Hey @amberleyromo we already merged this but I wanted to see what you thought / any edits or changes you'd suggest since I took liberally (read: nearly wholesale) from what you wrote!

**Comment by amberleyromo** [comment]
@shannonbux looks good to me! One thing though -- since this is copied and spread into separate pages from tutorial part eight, we have to maintain it in both places, if there are changes. I know we have this problem in a lot of other areas, just to note that this is one more.

**Comment by shannonbux** [comment]
Right. That is something I dread--figuring out how to maintain all the
docs! If we were using a CMS it might be easier to repurpose content in a
more maintainable format. Not sure how else to do it with our content
living in Github...I'll give it some thought!

**Comment by shannonbux** [comment]
Oh, and the reason to divide it up was to have URLs that are more specific
for google searches

**Pull request merged**
