### PR TITLE
Strapi blog post content

### PR DESCRIPTION
**Pull request by shannonbux**
Avatar and bio still coming, will make those edits and edit yaml later

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks @shannonbux!

**Comment by KyleAMathews** [comment]
Oh oops, it looks like the screenshots didn't get added. @shannonbux could you do another PR when you have a chance add add those + correct the image paths?

**Comment by shannonbux** [comment]
Yeah I forgot to get those from Pierre! @strapi Pierre is that your name here? We need all the screenshots from your blog post. I forgot to ask.

**Comment by KyleAMathews** [comment]
You could probably just grab them from his original post. That'll be good enough for now.

**Pull request merged**
