### PR TITLE
breaking(gatsby-source-contentful): remove gatsby-image support

### PR DESCRIPTION
**Pull request by axe312ger**
We want to drop the support for the deprecated gatsby-image plugin. The successor gatsby-plugin-image is superior in so many ways and we want to fully concentrate to give you the best responsive image experience you can offer to your users.

This is a replacement for #32782.

Planned changes:
* [x] remove all code related to gatsby-image
* [x] update and simplify readme file
* [x] refactor image related code to increase maintainability
* [x] (Contentful) e2e tests no more care about the exact css gatsby-plugin-image applies to the rendered output

### CODE REVIEW

**Review by wardpeet — APPROVED** [review]

**Comment by atwoodjw** [comment]
@axe312ger Is there an example of using `createUrl` in this context? I'm trying to adapt the code in https://github.com/contentful/starter-gatsby-blog to work in my project, but coming up short.

https://github.com/contentful/starter-gatsby-blog/blob/47f473de7293f36c6f5f6c2c21c18415d6fc828e/src/templates/blog-post.js#L88-L90

**Comment by axe312ger** [comment]
@atwoodjw as this function is internal, there is no documentation for it.

There is a PR that would introduce a hook which generates ImageURLs: https://github.com/gatsbyjs/gatsby/pull/29263

Would this help you?

**Comment by atwoodjw** [comment]
Definitely! 🙇

**Comment by axe312ger** [comment]
@atwoodjw I think you should use gatsby-plugin-image to render images.

See:

* https://www.gatsbyjs.com/plugins/gatsby-source-contentful/#displaying-responsive-image-with-gatsby-plugin-image
* https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/
* https://github.com/gatsbyjs/gatsby/blob/master/e2e-tests/contentful/src/pages/gatsby-plugin-image.js

**Pull request merged**
