### PR TITLE
in template-blog-post.js file   //find & remove protocol (http, ftp, …

### PR DESCRIPTION
**Pull request by sayanmondal2098**
…etc.) and get hostname function added

### CODE REVIEW

**Comment by pieh** [comment]
Can you tell more what is this doing?

**Comment by sayanmondal2098** [comment]
get hostname function added which help to add the hostname on template . An implementation towards the  problem of empty hostname in blog post. (previous written)

**Comment by sayanmondal2098** [comment]
Add missing publishedAt entries to blog posts -> this prob ca be solved with this .

**Comment by DSchau** [comment]
Hey! Thanks so much for opening a pull request!

The change you’ve proposed is not going to be accepted because this change doesn't meaningfully improve docs, fix a bug, or otherwise improve functionality.

We absolutely want to have you as a contributor, so please take a look at [our open issues][open-issues] for ideas, and please reach out to us on Twitter at @gatsbyjs with questions.

We offer pair programming sessions if you’d like to work with one of our maintainers to make your first contribution.

Thanks again, and we look forward to seeing more PRs from you in the future! :muscle: :purple_heart:

If we missed the mark here--please feel free to send a comment, and we'll re-open and take another look at this PR!

[open-issues]: https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Pull request closed without merging**
