### PR TITLE
Use oneLineTrim in gatsby-module-loader

### PR DESCRIPTION
**Pull request by bskimball**
This is to fix this issue [https://github.com/gatsbyjs/gatsby/issues/1704]

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Took a quick look at the builds for this and the last PR for gatsbyjs.org.

* https://deploy-preview-1782--gatsbyjs.netlify.com/
* https://deploy-preview-1783--gatsbyjs.netlify.com/

The current PR breaks things in chrome so presumably as well in IE.

This previous PR works in Chrome but causes some sort of syntax error in IE so clicking links just reloads everything.

**Comment by bskimball** [comment]
I tested a little on the site, I am working on. I'll test some more. Sorry for the extra commits. I was messing with some settings in my IDE

**Comment by bskimball** [comment]
It's not the carriage returns or even the template literals in the loader causing it to be undefined. I removed them all and still receive the original error
code without the returns and literals looks like this
```javascript
"use strict";

/*
  Based on Tobias Koppers @sokra bundle-loader
  https://github.com/webpack/bundle-loader

  and Arthur Stolyar's async-module-loader
*/
var loaderUtils = require(`loader-utils`);
var path = require(`path`);

module.exports = function () {};
module.exports.pitch = function (remainingRequest) {
  this.cacheable && this.cacheable();

  var query = loaderUtils.parseQuery(this.query);
  var chunkName = ``;

  if (query.name) {
    chunkName = loaderUtils.interpolateName(this, query.name, {
      context: query.context,
      regExp: query.regExp
    });
    chunkName = `, ` + JSON.stringify(chunkName);
  }

  var result = [
    "require(", loaderUtils.stringifyRequest(this, '!' + path.join(__dirname, 'patch.js')), ");",
    "module.exports = function(cb) {",
    " return require.ensure([], function(_, error) {",
    "   if (error) {",
    "     console.log('bundle loading error', error);",
    "     cb(true);",
    "   } else {",
    "     cb(null, function() {",
    "       return require(", loaderUtils.stringifyRequest(this, '!!' + remainingRequest), ");",
    "     });",
    "   }",
    " }", chunkName, ");",
    "}"
  ];

  return result.join("");
};
```
at this point I don't think I am any closer to fixing the original issue of resourceFunction returning executeChunk as undefined in IE/Edge

**Comment by bskimball** [comment]
what's strange is the function when I log to the console looks like this (page name is redux) 
```javascript
function (cb) { 
    return __webpack_require__.e/* nsure */(18284910286500342000, function(_, error) {   
        if (error) {     
            console.log('bundle loading error', error);     
            cb(true);   
       } else {     
            cb(null, function() {       
                return __webpack_require__("./node_modules/json-loader/index.js!./.cache/json/redux.json");     
            });   
        } 
    });
}
```
this is exactly what gatsby-module-loader should output however inside the callback err = true and executeChunk = undefined.

**Comment by bskimball** [comment]
I think you're right. I can check in to this later tonight.

**Comment by bskimball** [comment]
Not sure that is the issue.
in this example this page is named redux

```javascript
console.log(resourceFunction)
// the above function is located in gatsby/bin/cache-dir/loader and the function is created using 
// the gatsby-module-loader at gatsby/dist/loaders/gatsby-module-loaders/index 
// it returns the following

function (cb) { 
	     return __webpack_require__.e/* nsure */(18284910286500342000, function(_, error) {
	        if (error) {
	          console.log('bundle loading error', error)
	          cb(true)
	        } else {
	          cb(null, function() { return __webpack_require__("./node_modules/jsonloader/index.js!./.cache/json/redux.json") })
	        }
	      });
	     }

```
as you can see the path is a forward slash and is relative to the directory which is fine. The problem is that require.ensure() returns an error. I do not know what that error (only in IE) is yet.

**Comment by KyleAMathews** [comment]
Have you tried the trick from the other PR of splitting the module string when on windows and replacing it with windows new lines?

**Comment by bskimball** [comment]
Yeah this is the code I tried
```javascript
/*
  Based on Tobias Koppers @sokra bundle-loader
  https://github.com/webpack/bundle-loader
  and Arthur Stolyar's async-module-loader
*/
const loaderUtils = require(`loader-utils`)
const path = require(`path`)
const os = require(`os`)

module.exports = function() {}
module.exports.pitch = function(remainingRequest) {
  this.cacheable && this.cacheable()

  const query = loaderUtils.parseQuery(this.query)
  let chunkName = ``

  if (query.name) {
    chunkName = loaderUtils.interpolateName(this, query.name, {
      context: query.context,
      regExp: query.regExp,
    })
    chunkName = `, ${JSON.stringify(chunkName)}`
  }

  const request = loaderUtils.stringifyRequest(this, `!!` + remainingRequest)

  const callback = `function() { return require(` + request + `) }`

  const executor = `
     return require.ensure([], function(_, error) {
        if (error) {
          console.log('bundle loading error', error)
          cb(true)
        } else {
          cb(null, ${callback})
        }
      }${chunkName});
    `

  const result = `
    require(
      ${loaderUtils.stringifyRequest(
    this,
    `!${path.join(__dirname, `patch.js`)}`
  )}
    );
    module.exports = function(cb) { ${executor} }
    `


  if (os.platform == `win32`) {
    return result.split(`\\`).join(`\\\\`);
  } else {
    return result
  }
}
```

**Comment by bskimball** [comment]
it's failing on require.ensure() before it even loads the bundle.

**Comment by bskimball** [comment]
I didn't mean to close the issue 
Found this https://github.com/webpack/webpack/issues/2506

**Comment by KyleAMathews** [comment]
Oh hmmm... so basically nothing we can do without upgrading to webpack 2?

**Comment by KyleAMathews** [comment]
That's… unexpected

**Comment by KyleAMathews** [comment]
Did the line ending trick at least fix things in Edge?

**Comment by bskimball** [comment]
I'm pretty sure it's an issue with require.ensure and IE/Edge, as that's the part that is returning an error. The best I have been able to do in IE is skip the error and run the callback regardless. This forces Edge to do a page reload, which works, but the console logs the error.

**Comment by bskimball** [comment]
The only other thing I can think is that IE is having trouble requiring the .json file as opposed to a normal exported js file.

**Comment by KyleAMathews** [comment]
>IE is having trouble requiring the .json file as opposed to a normal exported js file.

That wouldn't be it as the JSON file is turned into a normal JS bundle when it's required.

**Comment by bskimball** [comment]
The best I have been able to get is a console error (only in IE/Edge) the first time a page loads, but the page still loads. Any navigation to that page afterwards, there isn't any error (i'm assuming because the page is loaded in webpack's cache). This is probably the best I can get it until the webpack 2 upgrade is complete.
the errors are
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - http://bdk-gatsby.localhost/undefined
SCRIPT5007: Unable to get property 'call' of undefined or null reference
bootstrap c1e4701643ccf4d020f9 (58,1)

The 404 is going to happen but the property 'call' error points to webpack's require section
```javascript
 	// The require function
 	function __webpack_require__(moduleId) {

 		// Check if module is in cache
 		if(installedModules[moduleId])
 			return installedModules[moduleId].exports;

 		// Create a new module (and put it into the cache)
 		var module = installedModules[moduleId] = {
 			exports: {},
 			id: moduleId,
 			loaded: false
 		};

 		// Execute the module function
 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

 		// Flag the module as loaded
 		module.loaded = true;

 		// Return the exports of the module
 		return module.exports;
 	}
```

**Pull request closed without merging**
