### PR TITLE
Fix #4503

### LINKED ISSUE #4503: frequent server crashes with "Cannot read propert 'children' of undefined"
## Description

Describe the issue or the enhancement that you want to see.

### Steps to reproduce

I don't have a large enough scope of the problem to get repro steps yet, will add them when and if I do.

Clear steps describing how to reproduce the issue.

### Expected result

No dev server crash

What should happen?

### Actual result

server crashed with trace

```
info file deleted at /Users/Jeff/go/src/github.com/deltaskelta/interviews/frontend/src/pages/app/index.js
error UNHANDLED EXCEPTION


  TypeError: Cannot read property 'children' of undefined

  - actions.js:379 actions.deleteNode
    [frontend]/[gatsby]/dist/redux/actions.js:379:54

  - bindActionCreators.js:7 Object.deleteNode
    [frontend]/[redux]/lib/bindActionCreators.js:7:35

  - gatsby-node.js:163
    [frontend]/[gatsby]/dist/internal-plugins/internal-data-bridge/gatsby-node.js:163:23

  - mitt.js:1
    [frontend]/[mitt]/dist/mitt.js:1:268

  - Array.map

  - mitt.js:1 Object.emit
    [frontend]/[mitt]/dist/mitt.js:1:252

  - index.js:72
    [frontend]/[gatsby]/dist/redux/index.js:72:11

  - createStore.js:186 dispatch
    [frontend]/[redux]/lib/createStore.js:186:7

  - index.js:58
    [frontend]/[gatsby]/dist/redux/index.js:58:79

  - bindActionCreators.js:7
    [frontend]/[redux]/lib/bindActionCreators.js:7:12

  - api-runner-node.js:47 doubleBoundActionCreators.(anonymous function)
    [frontend]/[gatsby]/dist/utils/api-runner-node.js:47:13

  - gatsby-node.js:69
    [frontend]/[gatsby]/dist/internal-plugins/component-page-creator/gatsby-node.js:69:17

  - Array.forEach

  - gatsby-node.js:68 FSWatcher.<anonymous>
    [frontend]/[gatsby]/dist/internal-plugins/component-page-creator/gatsby-node.js:68:18

  - index.js:196 FSWatcher.<anonymous>
    [frontend]/[chokidar]/index.js:196:15


error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c gatsby develop
Directory: /Users/Jeff/go/src/github.com/deltaskelta/interviews/frontend
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/Jeff/go/src/github.com/deltaskelta/interviews/frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What happened.

### Environment

I am in the middle of trying to integrate an external Apollo store when this happens, It happens when I am editing and saving graphql queries that are external to gatsby's static build queries 

* Gatsby version (`npm list gatsby`): gatsby@1.9.231
* gatsby-cli version (`gatsby --version`): 1.1.41
* Node.js version: v9.8.0
* Operating System: OSSierra 10.13.3

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`:
```
import { ApolloLink } from 'apollo-link';
import { ApolloProvider } from 'react-apollo';
import { HttpLink, InMemoryCache } from 'apollo-client-preset';
import { Provider } from 'react-redux';
import { withClientState } from 'apollo-link-state';
import PropTypes from 'prop-types';

import { ApolloClient } from 'apollo-client';
import { Router } from 'react-router-dom';
import React from 'react';

import { getCookie } from './utils';
import apolloState from './src/state/defaults';
import newStore from './src/state/createStore';
import resolvers from './src/state/resolvers';
import urls from './urls';

// this is for the usage of redux
exports.replaceRouterComponent = ({ history }) => {
  const ConnectedRouterWrapper = ({ children }) => {
    const store = newStore();
    return (
      <Provider store={store}>
        <Router history={history}>{children}</Router>
      </Provider>
    );
  };

  ConnectedRouterWrapper.propTypes = {
    children: PropTypes.object
  };

  return ConnectedRouterWrapper;
};

exports.wrapRootComponent = ({ Root }) => {
  return () => {
    const cache = new InMemoryCache();

    const stateLink = withClientState({ resolvers, cache, apolloState });

    const httpLink = new HttpLink({
      uri: urls.graphqlServer + urls.graphqlEndpoint,
      credentials: 'same-origin',
      headers: {
        authorization: getCookie('Authorization')
      }
    });

    const client = new ApolloClient({
      cache,
      link: new ApolloLink.from([stateLink, httpLink]),
      connectToDevTools: true
    });

    window.__APOLLO_CLIENT__ = client;

    return (
      <ApolloProvider client={client}>
        <Root />
      </ApolloProvider>
    );
  };
};
```
`gatsby-ssr.js`:

### PR DESCRIPTION
**Pull request by deltaskelta**
- added check to make sure node exists before tying to get descendents and delete
- added test case that calls deleteNode on an undefined node

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Nice! Thanks!

Can you run `npm run format` to clean up the semi-colons you added?

**Comment by deltaskelta** [comment]
I tried to run it but I am not seeing a `format` script in the package.json. How is that supposed to be run?

**Comment by KyleAMathews** [comment]
It's at the root of the repo

**Comment by deltaskelta** [comment]
It ran and changed a bunch of files that I didn't touch in my commit? Were these just things that never had format run on them before, or is this a mistake?

**Comment by pieh** [comment]
It seems it just wasn't run before and wasn't noticed by eye-test. Most of format changes seems fine - just ones in `docs/tutorial/index.md` seems weird (list numbering seems off).

**Comment by m-allanson** [comment]
Fixes #4503.

**Comment by KyleAMathews** [comment]
Yeah, prettier has a bug with indenting code blocks on every run — it's fixed upstream but not yet released :-\ https://github.com/prettier/prettier/issues/4112

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by jlengstorf** [comment]
Hiya @deltaskelta! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Comment by deltaskelta** [comment]
@jlengstorf thanks for the message, I'm actually already part of the org and I already got some free swag from other pull requests. I do have a request related to Gatsby though I would like to speak to you about so I will send you an email.

**Comment by jlengstorf** [comment]
@deltaskelta great, thanks!

**Pull request merged**
