### PR TITLE
chore: Add starters to README

### LINKED ISSUE #22503: docs: starter missing in README and in /starters/
## Summary

when i look at this places:

- https://github.com/gatsbyjs/gatsby/tree/master/starters
- https://www.gatsbyjs.org/starters?s=gatsby-starter&v=2
- https://www.gatsbyjs.org/docs/starters/
- https://www.gatsbyjs.org/docs/gatsby-cli/
- https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/README.md
- https://github.com/gatsbyjs/gatsby/blob/f79f26b268c635874fb4eb8199a8231b31fd889b/packages/gatsby-cli/src/init-starter.ts#L224-L232

there are only 3 starters listed.

but there are much more listet in: https://github.com/gatsbyjs/gatsby/tree/master/starters

this starters also not have a home page like https://www.gatsbyjs.org/starters/gatsbyjs/gatsby-starter-hello-world/

### Motivation

all official starters should have should be visible also in the starters library

## Steps to resolve this issue

- [ ] add more starters to the readme at https://github.com/gatsbyjs/gatsby/blob/master/starters/README.md

### Draft the doc

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.org/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.org/contributing/docs-templates/)
  - [Example of a similar article]()
- [ ] Add the article to the [docs sidebar](https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml) under the [parent doc] section.

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

### PR DESCRIPTION
**Pull request by Roshanjossey**
I've two questions

1. Can I use the following to generate the generated part in https://github.com/gatsbyjs/gatsby/blame/master/starters/README.md#L61

https://github.com/gatsbyjs/gatsby/blob/0e98ad417f56eb5f577d89bd386fad8987e60ee6/markdown.config.js#L7

How do I generate it?

2. The issue mentions

>  Add the article to the docs sidebar under the [parent doc] section.

Should it be here https://github.com/gatsbyjs/gatsby/blob/master/www/src/data/sidebars/doc-links.yaml#L333

For example:

```
- title: Workspace theme
              link: /starters/workspace-theme/
```

## Related Issues

Fixes #22503

### CODE REVIEW

**Comment by LekoArts** [comment]
Hi, thanks for the PR!
Since we moved the showcase to WordPress and out of the .yml files you won't need to update the file.

The only actionable thing out of the issue you linked is editing https://github.com/gatsbyjs/gatsby/blob/master/starters/README.md - I haven't used the script you linked before so I'd just copy/paste the contents. The "description" comes from the "description" field of the respective package.json file.
You can leave the Demo fields blank as we'll need to set this up.

**Comment by Roshanjossey** [comment]
@LekoArts , thank you for your reply. I'll revert my changes in starters.yml and update starters Readme

**Review by LekoArts — APPROVED** [review]
Thank you! 👍

**Comment by muescha** [comment]
`gatsby-starter-plugin` is not listed 🤔

**Comment by Roshanjossey** [comment]
@muescha, before starting on these changes, I looked at another pull request (https://github.com/gatsbyjs/gatsby/pull/24089) aimed at addressing #22503. In the review thread, I found the following comment that led me to decide not to put `gatsby-starter-plugin`

https://github.com/gatsbyjs/gatsby/pull/24089#pullrequestreview-412223594

> These starters are mirrored in their own repositories on the gatsbyjs organization. Ie you can find them each at https://github.com/gatsbyjs/gatsby-starter-*. All with the exception of gatsby-starter-plugin would technically be considered official starter sites (the plugin starter creates a new plugin which can't be run as a site by itself). Meaning there are really 8 plugins we should be listing.

If plugin should also be added, I'd gladly add it. :)

**Comment by Roshanjossey** [comment]
@muescha, create a pull request https://github.com/gatsbyjs/gatsby/pull/27017

**Pull request merged**
