### PR TITLE
chore: add Square Starter to the starters list

### LINKED ISSUE #20975: Starter processing Square payments
## Summary

In attempting to write a reference guide for processing payments with Square, I realized we could use a starter to help people do this without quite as much digging into the Square documentation and adapting of available examples.

### Motivation

Square is a solid choice for people who are just starting a business because they don't charge a monthly fee for their basic service. Right now, there's no starter that people can use to get up and go and the existing plugin is pretty minimal.

### Build the starter

- Potentially helpful resources:
  - [`SqPaymentForm` documentation](https://developer.squareup.com/docs/api/paymentform#navsection-paymentform)
  - [Square's tutorial for online payment options](https://developer.squareup.com/docs/online-payment-options)
  - Square's blog post on [Online Payments with React + Square](https://developer.squareup.com/blog/online-payments-form-react/)
- [ ] Read through the contributing [docs on contributing code](https://www.gatsbyjs.org/contributing/code-contributions/)
- [ ] Make sure your starter is [accessible](https://www.gatsbyjs.org/docs/making-your-site-accessible/)
- [ ] Include a README file

### Open a pull request to add it to the Starter Library

- [ ] Read through the [docs on adding to the Starter Library](https://www.gatsbyjs.org/contributing/submit-to-starter-library/)
- [ ] Open a pull request with your work including the words "Fixes #20975" in the pull request description

### PR DESCRIPTION
**Pull request by jonniebigodes**
This pr will introduce a barebones starter for handling Square payments with Gatsby

Fixes #20975

Feel free to provide feedback

### CODE REVIEW

**Comment by laurieontech** [comment]
Thanks for the PR! Looks super useful. 

For the contentful starter I noticed the README has `gatsby clone` instructions? I suspect you meant `git clone` or `gatsby new` so would be good to update that.

And for the Square starter the instructions include `yarn start`. We recommend `gatsby develop` for consistency. If that's not possible, npm is preferred to match the main documentation.

**Comment by jonniebigodes** [comment]
@laurieontech thanks for the feedback. But i left only the cli option as i under the impression that the recomended way for a starter usage was with the cli and avoid cloning them directly. If i'm wrong, i'll update the readme accordingly and push it to the repo.

Also i'm aware that the recomended approach is to use `yarn develop`, but in this case the script will run concurrently both the site in development mode and the sample serverless function to allow the most complete experience to the user. If need be i can once again update the readme with why the command is used. Sounds good?

**Comment by laurieontech** [comment]
The contentful README currently says:
```gatsby clone https://github.com/escapemanuele/gatsby-contentful-blog-portfolio  your-project-name```
Where as other starters use `gatsby new` commands? That's where my confusion stems from. Was the `gatsby clone` intentional?

As for the square starter `yarn` instructions, I'd ask that it use npm commands if it cannot use gatsby ones.

I know it's a bit confusing since there are two starters under discussion. So I'm attempting to put comments in the order the starters appear in the file.

**Comment by jonniebigodes** [comment]
@laurieontech sorry to ask, but why are you mentioning the contentful starter? This starter was based off the hello world starter? The Readme file is almost a carbon copy of the said starter readme? 

My readme clearly states;

>Use the Gatsby CLI to create a new site, specifying the hello-world starter. 

And with that i found out a typo...it shouldn't mention the hello world starter, but proves my point.

It's up to the people or person behind the said starter to address that issue. It's not my role, i'm sorry.

**Comment by laurieontech** [comment]
The contentful starter is included as part of the changes for this PR. Was that not intentional? If so, we should remove that starter and only add the square starter since that’s the one you’ve so graciously worked on.

**Comment by jonniebigodes** [comment]
it shouldn't be included as i did not touch the said starter. That was someone's submission. And to be honest i don't know why the yaml file is picking up the said starter, when the only change i made was introduce the own that is covered in this pr and i ran the script to format the file to avoid linting issues.

**Comment by laurieontech** [comment]
That makes a lot more sense! Thanks for clarifying. Let me see if I can determine how it was introduced and then we can merge yours. Appreciate your patience!

**Comment by laurieontech** [comment]
Ok, was able to research this! The contentful site is already in the master branch and I'm not sure why it appears as part of yours, but that's ok!

I'm fixing the tests for this branch and then should be good to merge.

**Comment by muescha** [comment]
maybe add an info about this serverless solution somewhere in the https://www.gatsbyjs.org/docs/processing-payments-with-square/
(related #20977 `docs: Add reference guide for processing payments with Square`)

**Comment by jonniebigodes** [comment]
@muescha i'd rather not. I added the serverless function on my own volition as a example and i don't intend to force the reader on one direction. The documentation that was created by @AishaBlake covers the requirements needed to set up Square with Gatsby, it's up to the developer /team to implement their own strategy. So with that in mind i would rather leave it as is.

More even for this tidbit that i've left in the readme:

> Should you have your own backend solution, you'll need to adjust accordingly.

@laurieontech thank you for taking the time to solve the issue and merge this. If you don't mind i'm going to delete the branch as it's not longer required.

**Pull request merged**
