### PR TITLE
[gatsby-link] Accept innerRef function

### PR DESCRIPTION
**Pull request by sarahatwork**
It'd be great if we could pass along an `innerRef` property to `gatsby-link` so we can access the `<a>` tag created by `react-router-dom`.

About my use case: I'm making an accessible menubutton a la http://davidtheclark.github.io/react-aria-menubutton/demo/, but with links. I need the reference to be able to focus the element based on keyboard controls.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Nice! This will be very useful.

Could you add a mention to the docs w/ a quick example as well?

**Comment by sarahatwork** [comment]
@KyleAMathews Sure thing - updated! 👌

**Comment by KyleAMathews** [comment]
Oh nice, you rewrote other parts of the README too haha :-) Always appreciate docs gardening!

**Comment by jonrh** [comment]
chrome_console_error_innerref_prop_gatsbyjs

When developing locally I get the following warning in the Chrome & Firefox console when `gatsby-link`s are present:

```
Warning: Unknown prop `innerRef` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

Am I the only one seeing it?

**Comment by joeshub** [comment]
@jonrh I'm seeing this warning as well.

The issue is that if you're using React DOM 15.x you will see the error, since they manually filter props via this utility https://unpkg.com/react-dom@15.6.2/lib/HTMLDOMPropertyConfig.js and throw that warning.

Starting with Fiber (16.x) React is no longer filtering component props and they are letting everything through from what I understand.

Overall, this seems to be the issue so some folks will still see this annoying warning which is not ideal

**Comment by sarahatwork** [comment]
I think this issue might predate my PR but can try to take a look anyway.

@joeshub @jonrh Are you able to reproduce this issue on a Gatsby starter repo? I just tried on a few but couldn't see the error message.

**Comment by joeshub** [comment]
@sarahatwork  I think I noticed this when I was using the advanced starter. https://github.com/Vagr9K/gatsby-advanced-starter. 

Since I've just switched to using the built in Gatsby starter, and haven't noticed any issues.

**Pull request merged**
