### PR TITLE
gatsby-remark-graph plugin mention

### PR DESCRIPTION
**Pull request by konsumer**
I made a nice plugin for making graphs with [mermaid](https://mermaidjs.github.io/)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 9f1f6f7f91d63a9c0318b144520ad54a62aebf9c

https://app.netlify.com/sites/using-glamor/deploys/5a0bb6b2df99532513c8bd1d

**Comment by KyleAMathews** [comment]
Nice!

BTW, you could make this a bit more plug-n-play by adding a gatsby-browser.js file where you import the mermaid package (or if that doesn't work, gatsby-ssr.js can add the script tag to the HTML).

**Comment by konsumer** [comment]
I like the idea. mermaid uses client-side ODM api to make the SVG, so I'm not sure how to import it into the client-side code. Do you have any suggestions?

**Comment by KyleAMathews** [comment]
You could use onRouteUpdate e.g. in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-analytics/src/gatsby-browser.js & https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-twitter/src/gatsby-browser.js

**Comment by konsumer** [comment]
Will this work If I just do this in my index.js? Awesome. Much better solution.

**Comment by KyleAMathews** [comment]
Add a gatsby-browser.js file. It has a number of APIs you can implement include the `onCreateUpdate` https://www.gatsbyjs.org/docs/browser-apis/

There's a bunch of plugins you can look at for examples https://github.com/gatsbyjs/gatsby/search?utf8=%E2%9C%93&q=gatsby-browser.js&type=

**Comment by konsumer** [comment]
Added in ` gatsby-remark-graph@0.1.0`. Thanks for your help!

**Pull request merged**
