### PR TITLE
fix(gatsby-source-drupal): Fix relationships for multi value reference fields

### LINKED ISSUE #19450: [source-drupal] weird behaviour with Drupal entity references when inside a paragraph
## Description

There's some strange behaviour happening with I use an entity reference inside a paragraph with Drupal.   I can see the JSON:API is formatting everything as I expect.   If I have an entity reference field on its own in a content type Gatsby can see the data and I am able to query values of the reference in my local GraphiQL instance.   However, as soon as that is nested inside a reference it just returns `NULL`

I've created two fields within my "Page" content type.  

Screenshot 2019-11-12 at 14 59 13

`field_test` — An entity reference field

`field_test2` — A paragraph field (entity reference revisions).  Inside that field, there is an entity reference field called `field_embed` which is identical to `field_test`

Screenshot 2019-11-12 at 15 00 03

On my content that I am querying, I've referenced the same content. "Travel tip-offs: the best places to visit in August" (Node 56 in Drupal)

Screenshot 2019-11-12 at 15 01 24

### Steps to reproduce

Either use my site's data using the following in `gatsby-config.js`

```
resolve: `gatsby-source-drupal`,
      options: {
        baseUrl: `https://app.master-7rqtwti-shreqbivaapoy.eu-2.platformsh.site/`,
        preview: true,
        apiBase: `api`, // optional, defaults to `jsonapi`
    }
```

or 

Add a paragraph field to your content type in Drupal and then add an entity reference field in that paragraph.

Next, running the following query in GraphiQL 

```
query pageQuery($drupal_id: String) {
  nodePage(drupal_id: {eq: $drupal_id}) {
    relationships {
      field_test {
        title
        drupal_internal__nid
        drupal_id
      }
      field_test2 {
        relationships {
          field_embed {
            title
            drupal_id
            drupal_internal__nid
          }
        }
      }
    }
  }
}

```

### Expected result

`field_embed` returns the same information as `field_test`

### Actual result

`field_embed` is returning `NULL`

Screenshot 2019-11-12 at 15 13 06

### Environment

    System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.1 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.12.1 - ~/.npm-packages/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 66.0.5
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.17.2 => 2.17.2
    gatsby-cli: ^2.8.5 => 2.8.5
    gatsby-image: ^2.2.29 => 2.2.29
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13
    gatsby-plugin-sass: ^2.1.20 => 2.1.20
    gatsby-plugin-sharp: ^2.2.32 => 2.2.32
    gatsby-plugin-styled-components: ^3.1.11 => 3.1.11
    gatsby-plugin-typography: ^2.3.15 => 2.3.15
    gatsby-source-drupal: ^3.3.0 => 3.3.0
    gatsby-source-filesystem: ^2.1.33 => 2.1.33
    gatsby-transformer-sharp: ^2.3.0 => 2.3.0
  npmGlobalPackages:
    gatsby-cli: 2.8.0

### PR DESCRIPTION
**Pull request by arshad**
## Description

This PR fixes the relationships for multi value reference fields. See related issue.

## Related Issues

Fixes #19450

### CODE REVIEW

**Comment by pvdz** [comment]
@arshad 
> Yeah let's see what breaks. Go CI :)

So it broke packages/gatsby-source-drupal/src/__tests__/index.js ;) You should be able to run `yarn jest packages/gatsby-source-drupal/src/__tests__/index.js` to repro that (quickly) locally. 

Additionally, I think the failure is fairly superficial. Would you mind adding a more thorough test for this PR? Clearly the actual problem in #19450 is not currently covered by tests.

**Comment by pieh** [comment]
As mentioned in the linked issue - this is breaking change as it converts single references to arrays (that's also reason why tests started failing). I'm not yet convinced this is good change as it affects plenty of correctly working single value references

**Comment by jonearley** [comment]
@pieh The fix might not be to make Drupal paragraph entity reference fields multi-valued, but to allow for multiple types in a single value entity reference. I'm not sure what this change looks like in the code, but hoping this prompts some ideas for an official solution.

In my scenario I have multiple Drupal content types populating a paragraph entity reference field, but only a single type is picked up when querying that field on Gatsby's end. It seems like `gatsby-source-drupal` assumes a paragraph entity reference field will only be of one type.

**Comment by vladar** [comment]
I think the underlying issue should be fixed via #19916 (not published yet)

**Comment by arshad** [comment]
Closing. Fixed by #19916. Thanks @vladar

**Pull request closed without merging**
