### PR TITLE
Add a site(https://mojaave.com) to showcase list

### PR DESCRIPTION
**Pull request by mhjadav**
[Mojaave.com](https://mojaave.com) is Mahipat's Portfolio, I have developed it using Gatsby v2 and Bootstrap.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit ca6927f848699b41c085b5eb4f7423149cbe0252

https://app.netlify.com/sites/gatsbyjs/deploys/5b715bacfdd72a7d8c2449d5

**Comment by m-allanson** [comment]
screen shot 2018-08-13 at 23 16 27

**Comment by mhjadav** [comment]
Hi @m-allanson 

There was an issue with certificate generation, but now it's working fine. and the site is on a secure channel.

Thanks  😄 


screen shot 2018-08-14 at 10 20 12 am

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit 715db3324fdce7c64ae1611f7cb942461083d624

https://app.netlify.com/sites/using-contentful/deploys/5b7261233813f001b4c3394b

**Pull request merged**
