### PR TITLE
Add gatsby-link as a dependency and update documentation

### LINKED ISSUE #3069: Gatsby depends on gatsby-link implicitly
I'm new to Gatsby and experimenting with migrating a single page site to it. Because I only need a single page I have no need for `gatsby-link`. However, after removing the package (which was included by the default `gatsby new` starter) I get the following error:

```
 ERROR  Failed to compile with 1 errors          9:21:45 AM

This dependency was not found:

* gatsby-link in ./.cache/dev-404-page.js

To install it, you can run: npm install --save gatsby-link
```

It's clear to me that Gatsby's internal development 404 page relies on `gatsby-link` so I should keep it in my own `package.json`. However, I found it surprising that `gatsby-link` isn't just included in the `gatsby` package because it seems that every single Gatsby project will use this in development. Alternatively, `gatsby-link` could be listed as a `peerDependency` in `package.json`, giving users a hint to include it manually, or the 404 page could be rewritten to not use the plugin. Another idea is that this could be an internal plugin with the `Link` component exported somewhere in the `gatsby` module or a submodule like `gatsby/link`, leading to a similar developer experience but without the extra npm package.

To be clear, I'm specifically referring to the cyclical dependency between the `gatsby` and `gatsby-link` packages and the developer experience around using the `gatsby` package without any dependent packages. I'm not necessarily suggesting that Gatsby should force users to use `gatsby-link` by default, I like that this functionality is more explicitly provided in a separate package.

### PR DESCRIPTION
**Pull request by nickmccurdy**
Fixes #3069 

## Todo
- [x] install `gatsby-link` with Gatsby
- [x] update documentation

### CODE REVIEW

**Comment by nickmccurdy** [comment]
I noticed that while there is a plop code generator in this repository (which seems to be for generating Gatsby packages, not sites that use Gatsby), the starters are in other repositories. Am I correct to assume that if this gets merged and we want to remove the extra `gastby-link` in theme `package.json` files, I should send a PR to each starter?

**Comment by KyleAMathews** [comment]
Please leave gatsby-link in the starters as a dependency. We're adding it as a dependency strictly for the dev-404-page issue you uncovered. The only change this PR should make is adding gatsby-link as a dependency to the `gatsby` package.

**Comment by nickmccurdy** [comment]
Alright, I'll skip removing it from any `package.json` files or templates (which I haven't committed anyway). Should I keep or revert my doc changes? My intention was to just make it clear that `gatsby-link` is included in Gatsby so you don't need to add it back if you weren't using a starter or removed it from your `package.json` for some reason.

**Comment by KyleAMathews** [comment]
I don't think the doc changes are needed — I haven't heard of anyone else running into the problem of removing gatsby-link as almost every site (except one pagers) need it. Let's just add gatsby-link as a dependency so you can remove gatsby-link if you want.

**Comment by nickmccurdy** [comment]
I also fixed the merge conflicts, but does `gatsby-link`'s dependency need to be updated to `^ 1.6.31`?

**Comment by KyleAMathews** [comment]
>does gatsby-link's dependency need to be updated to ^1.6.31?

Nope — the caret means "match any version up to the next major version" so we're good. Thanks!

**Comment by jlengstorf** [comment]
Hiya @nickmccurdy! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
