### PR TITLE
chore(showcase): add diogorodrigues.dev

### PR DESCRIPTION
**Pull request by diogorodrigues**
Pushing my new portfolio/blog built with Gatsby.

### CODE REVIEW

**Comment by diogorodrigues** [comment]
Hello. How can I fix this issue?

**Comment by diogorodrigues** [comment]
I don´t have access to the log:

image

**Comment by diogorodrigues** [comment]
I don´t have access to the log:

image

**Comment by diogorodrigues** [comment]
@muescha @pvdz pvdz Is there something I need to do? I don´t understand what´s wrong.

image

**Comment by muescha** [comment]
no you don't need to rerun this tests.

it just takes time if it checked by the gatsby team, just wait :)

**Comment by diogorodrigues** [comment]
Thank you @muescha. :)

**Comment by diogorodrigues** [comment]
@muescha 
I don't know what´s happening. It was goods and passed in all tests. But when a merge button appeared and I resolve a some conflicts during the merge process, I got this new error and now I don´t know how to fix it. Can you help me, please?

**Comment by muescha** [comment]
danger says that the line `diogorodrigues-patch-1` is wrong in this place to be a valid yaml file - i guess it was a leftover from the merge process

you can solve the problem with removing the line 10903 `diogorodrigues-patch-1`

**Comment by diogorodrigues** [comment]
@muescha Thank you. But the problem is that every time I resolve the conflict and all checks passed, a "Resolve conflicts" button appear. Do I need to do something in this case? 
image

**Comment by muescha** [comment]
since the showcase file is changing fast, with every pull request approved to this file (today 3 and i see [14 open showcase PR](https://github.com/gatsbyjs/gatsby/labels/topic%3A%20showcase)) there can be a new conflict there ...

but when i look through [merged showcase PRs](https://github.com/gatsbyjs/gatsby/issues?q=label%3A%22topic%3A+showcase%22+is%3Aclosed) i see the team also merge some of the showcase PR before approving. so just wait. if changes needed then you see the label `Changes requested`

**Comment by AishaBlake** [comment]
Exactly as @muescha says, I'm going through and trying to get us caught up on showcase PRs. Please don't worry about addressing merge conflicts, @diogorodrigues. I'm doing it as I go!

**Comment by diogorodrigues** [comment]
Thank you so much @muescha and @AishaBlake !! ✌

**Pull request merged**
