### PR TITLE
Add upgrade docs to error messages for deprecated APIs

### LINKED ISSUE #6825: boundActionCreators warning should say to replace them with "actions" and also link to the upgrade docs for this
boundActionCreators warning should say to replace them with "actions" and also link to the upgrade docs for this

### PR DESCRIPTION
**Pull request by thefifthisa**
Fixes #6825

Error messages for deprecated APIs (`boundActionCreators` and `pathContext`) now include links to their upgrade docs, like this:

gatsby_link

However, the link gets cut if I make my terminal window smaller. Not sure if it's just me (I'm using Hyper).

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 4a2d827cd0f8b6372c453a07af3fe7dd6a210ebf

https://app.netlify.com/sites/using-postcss-sass/deploys/5b60d0c14ed62f297ac0d50d

**Comment by jlengstorf** [comment]
I'm setting up a short link domain; will report back once it's working with a shorter link.

**Comment by jlengstorf** [comment]
We have a short link!

Please add https://gatsby.app/boundActionCreators instead. 

Can we edit the text to read:

> `boundActionCreators` is deprecated. Please use `actions` instead. For migration instructions, see https://gatsby.app/boundActionCreators

Thanks again for your help!

**Comment by thefifthisa** [comment]
Got it, thanks! How does this look?

gatsby_link

**Comment by KyleAMathews** [comment]
Deploy preview for *using-styled-components* failed.

Built with commit a19c84432505bbce5bf57ebea7bdbe5f9a366084

https://app.netlify.com/sites/using-styled-components/deploys/5b61b4bbb13fb11495a78623

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit a19c84432505bbce5bf57ebea7bdbe5f9a366084

https://app.netlify.com/sites/using-contentful/deploys/5b61b4bbb13fb11495a78626

**Pull request merged**
