### PR TITLE
feat(gatsby): Prevent generation of polyfill bundle if not needed

### PR DESCRIPTION
**Pull request by herecydev**
## Description

Removes the generation of a polyfill **if** all the browsers support ES6 modules. This should have a few benefits:

1. Reduce confusion in discussions, see https://github.com/gatsbyjs/gatsby/issues/28736, https://github.com/gatsbyjs/gatsby/issues/26894 etc
2. Reduce noise in bundle analysis tools like webpack-bundle-analyzer. It still gets generated and therefore displayed.
3. Reduce files webpack has to produce and then subsequently get deployed

The implementation simply uses the browserslist and checks whether there are any browsers that do not support ES6 modules. If there are then include the polyfills.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
This makes sense. The question I have is how often will this be used? As in, you'd have to manually change your browser list right? What would it need to be?

**Comment by herecydev** [comment]
@KyleAMathews I'm not sure I'm following, if you're browserlist is `["last 2 Chrome versions"]` there's no need to generate a polyfills bundle, so that's what this PR solves.

**Comment by KyleAMathews** [comment]
Right, I'm just wondering how common it is to do that.

**Comment by herecydev** [comment]
Well you have a [page dedicated to it](https://www.gatsbyjs.com/docs/how-to/custom-configuration/browser-support/#specify-what-browsers-your-project-supports-using-browserslist) so I guess it's important enough 😁

I'm not sure statistically what percentage of gatsby users change their browserslist, the question that's more important is how many gatsby users *benefit* from generating a polyfills bundle, looking at [caniuse](https://caniuse.com/es6-module), it's getting marginal.

**Comment by KyleAMathews** [comment]
Aye so it's more a future-facing thing? A few will benefit now who only support the latest browsers and more and more will benefit over time.

**Comment by herecydev** [comment]
Yer that's probably accurate. It's really hard to know without monitoring (I guess Gatsby is in a position to collect some stats). But I've tried to be inclusive; if you *do* want to support older browsers then we're not excluding that behavior. It's simply a clear benefit for those who don't.

I am certainly in the camp where it would be beneficial to remove the polyfills!

**Comment by wardpeet** [comment]
Thanks for creating this PR. The code looks good, let me have a quick test and see if we can merge. There is not much user benefit but there is also no downside, so let's get this merged 💪

**Review by wardpeet — APPROVED** [review]
We were still loading the polyfill.js in the browser for develop. I've added some code to fix that. it's ready now :)

Thank you!

**Comment by herecydev** [comment]
Cheers Ward!

**Review by wardpeet — APPROVED** [review]

**Pull request merged**
