### PR TITLE
[WIP][www] Replace main navigation item "Community" with "Plugins"

### PR DESCRIPTION
**Pull request by fk**
* Add "Plugins" item to mobile navigation.
* Replace main navigation item "Community" with "Plugins".
* Move "Community" page to "Docs" and redirect from `/community` to `/docs/community/`.

Ref. #4394

### CODE REVIEW

**Comment by fk** [comment]
Icon alternatives:

36557742-68f30e44-1809-11e8-9f00-60e7246f8731

Quoting myself from https://github.com/gatsbyjs/gatsby/pull/3456#issuecomment-367786647

> The two above the "magic wand" icon a) pick up the quite common "puzzle pieces" metaphor for "Plugins", b) show data flowing through those plugins (and/or "Transformers"), all within the Gatsby monogram/"G" shape. Not super clear, so probably not a way to go.

**Comment by KyleAMathews** [comment]
Quick review:

* Move community link to the top "Quick Start" section
* The mobile nav looks a bit crowded — drop the community link now?

Otherwise looks great! Excited to go public with this :-D

**Comment by fk** [comment]
@KyleAMathews Updated! One more thing: "Plugin Library" currently lives at `/packages/` and is the only page section where the URL does not match the section title…

**Comment by fk** [comment]
Probably should fix this 😅

image

**Comment by fk** [comment]
GTG!

**Comment by KyleAMathews** [comment]
🎉

**Pull request merged**
