### PR TITLE
typescript compile error if no ; in the end for interface.

### PR DESCRIPTION
**Pull request by magicly**
this is about https://github.com/gatsbyjs/gatsby/issues/1741 issue.

I found in fact there is no need for ';' in the end in typescript, but gatsby compiles error like below:
```js
⠁ Failed to parse /Users/magicly/development/blog/gatsby/examples/using-typescript/src/pages/index.tsx
{ SyntaxError: Unexpected token (10:8)
    at Parser.pp$5.raise (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$8.flowObjectTypeSemicolon (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:5466:10)
    at Parser.pp$8.flowParseObjectType (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:5446:16)
    at Parser.pp$8.flowParsePrimaryType (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:5610:19)
    at Parser.pp$8.flowParsePostfixType (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:5728:19)
    at Parser.pp$8.flowParsePrefixType (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:5745:17)
    at Parser.pp$8.flowParseAnonFunctionWithoutParens (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:5750:20)
    at Parser.pp$8.flowParseIntersectionType (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:5765:19)
    at Parser.pp$8.flowParseUnionType (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:5776:19)
    at Parser.pp$8.flowParseType (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:5787:19)
    at Parser.pp$8.flowParseTypeInitialiser (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:4988:19)
    at Parser.pp$8.flowParseObjectType (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:5442:29)
    at Parser.pp$8.flowParsePrimaryType (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:5610:19)
    at Parser.pp$8.flowParsePostfixType (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:5728:19)
    at Parser.pp$8.flowParsePrefixType (/Users/magicly/development/blog/gatsby/examples/using-typescript/node_modules/babylon/lib/index.js:5745:17) pos: 267, loc: Position { line: 10, column: 8 } }
```

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@DominikGuzei @timsuchanek does this look right?

**Comment by DominikGuzei** [comment]
@KyleAMathews i moved away from typescript because it was more hassle than help.

**Comment by berwyn** [comment]
TypeScript uses the same rules as JavaScript as far as semicolons are concerned (being a strict superset of the language). Semicolons can be used, replaced with commas, or omitted from field declarations in interfaces and type declarations

**Comment by KyleAMathews** [comment]
Hmmm @magicly looks like you deleted your branch? Git is saying I can't merge it anymore. Anyways, sorry for not getting to this earlier. Would love the PR added still if you could resubmit it.

**Pull request closed without merging**
