### PR TITLE
Update plugins with plugin authoring link

### PR DESCRIPTION
**Pull request by shannonbux**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
There is a link at the bottom of this page — do you think we should have both?

**Comment by shannonbux** [comment]
Oh hehe! @kyleamathews hm...No, not both. Probably what needs to happen is
just better IA overall so the plugin stuff is all clustered together
visually in the sidebar.

The question right now though is whether linking at top or bottom of this
page makes more sense. I think top, in case someone came to the page and is
actually looking for plugin authoring. Then they don't have to read the
whole thing (it's admittedly short, but still). What do you think?

**Comment by KyleAMathews** [comment]
Yeah, IA redesign would be great :-)

I actually, looking at it again, like the mention better at the top than the bottom. I'll tweak your a PR a bit to remove the old mention and merge this in.

**Comment by shannonbux** [comment]
Thanks!!

**Pull request merged**
