### PR TITLE
fix(www): hide feedback and edit on github for remote packages 

### PR DESCRIPTION
**Pull request by hbish**
For plugins not hosted in gatsby/package, the 2 features (feedback and edit in github) in the footer does not work as intended. 

This PR adds a toggle to disable those feature when no page metadata is available.

screen shot 2018-11-03 at 8 24 14 pm

### CODE REVIEW

**Comment by shannonbux** [comment]
@pieh I think this is a question for @amberleyromo! My vote is that we get rid of those things for the plugin library entirely and instead introduce other kinds of sorting and filtering to help ensure quality. We've also talked about having a feedback form on the plugin library in general.

**Comment by amberleyromo** [comment]
> @pieh I think this is a question for @amberleyromo! My vote is that we get rid of those things for the plugin library entirely and instead introduce other kinds of sorting and filtering to help ensure quality. We've also talked about having a feedback form on the plugin library in general.

@pieh @shannonbux sorry, somehow I had missed this (thanks @LekoArts). Shannon, I agree we can just get rid of this entirely for the plugin library. #10784 is adding the Unbird feedback form to all plugin package pages.

**Comment by LekoArts** [comment]
Since https://github.com/gatsbyjs/gatsby/pull/10784 is merged, we can get this merged, too, right?

**Comment by amberleyromo** [comment]
@LekoArts yep. i just pushed some changes. if you could re-review:

- removed the feedback thumbs up / thumbs down entirely (Unbird replaces this)
- conflict resolution adding Unbird to remote package template (after persisting sidebar #10590 was merged)
- existing fix for only showing "edit on GitHub" CTA for internal pages is intact

**Comment by hbish** [comment]
Thanks for fixing this @amberleyromo, I wasn't aware there was a plan to replace all the feedback features with unbird. 👍

**Pull request merged**
