### PR TITLE
Improve semver compatibility of resolutions

### PR DESCRIPTION
**Pull request by karlhorky**
## Description

Improves the semver compatibility of the Yarn Resolutions used in the workspace `package.json`:

### Before

Yarn Resolutions forces `write-file-atomic@2.4.3` for all versions of `write-file-atomic`, also for the packages requesting `write-file-atomic^3.0.0` via `configstore@^5.0.1`.

Screen Shot 2020-03-30 at 21 15 44

### After

Those packages have `write-file-atomic@3.0.3` manually overridden for them. One less warning during installation.

Screen Shot 2020-03-30 at 21 17 10

## Related Issues

May be impacted by merging #22434

cc @pieh

### CODE REVIEW

**Comment by pieh** [comment]
Ok, back tracking to why we even have initial `write-file-atomic` yarn resolution entry - https://github.com/gatsbyjs/gatsby/pull/16844/files#r316104813 which seems to stem from some `jest` related issue. If that's the case - maybe instead of targetting every `write-file-atomic` we could target one that is dep of `jest` and only pin that and then we wouldn't have 5 separate rules to unpin rest of those?

**Comment by pieh** [comment]
Ah, we also  had task to remove that - https://github.com/gatsbyjs/gatsby/issues/16885 but we never followed up on it

**Comment by karlhorky** [comment]
Ah right yeah... I mean, if you think it's better that I either A) remove the resolution completely or B) come up with a new resolution to target just Jest, I'd be happy to do either of those.

Just let me know what is the most desired at this point.

**Comment by pieh** [comment]
If we can remove the `yarn resolution` completely - that would be ideal, but there might be failing tests on windows CI - worth a try, maybe the problem causing the need for it was fixed already upstream.

If we can't completely remove it, let's just target `write-file-atomic` dep of `jest` (it's probably not direct dependency?)

**Comment by karlhorky** [comment]
Ok, trying to remove it completely first... done in ad9fc7963

**Comment by pieh** [comment]
@sidharthachatterjee seems like removing the `yarn resolutions` here doesn't case CI issues? Or the issues where intermittent? Do you remember?

**Comment by karlhorky** [comment]
Thanks as well @sidharthachatterjee @pieh !

**Pull request merged**
