### PR TITLE
page-data.json cleanup PR. Remove jsonName and dataPath

### PR DESCRIPTION
**Pull request by Moocar**
**Note: merges to `per-page-manifest`, not master. See https://github.com/gatsbyjs/gatsby/pull/13004 for more info**

## Description

Cleanup PR. Now that we've removed the central pages-manifest and are using `page-data.json` everywhere in Gatsby, we can remove the concepts of `jsonName` and `dataPath`. 

## Related Issues

- Sub-PR of https://github.com/gatsbyjs/gatsby/pull/13004

### CODE REVIEW

**Comment by Moocar** [comment]
@wardpeet @KyleAMathews Final required PR for the `per-page-manifest` series. Once this is merged, we can create a canary and get folks to start testing.

**Comment by Moocar** [comment]
The `e2e-tests-path-prefix` failure is legit. Will work on it later.

**Comment by wardpeet** [comment]
i'll try to review in a jiffy :)

**Comment by Moocar** [comment]
ok, fixed the `prefixPaths` e2e test. The latest production-runtime error isn't really an error. it's complaining that `gatsby-plugin-offline@2.1.1` is exporting `onPostPrefetchPathname`, which is no longer a gatsby api (it has been replaced by `onPostPrefetch` on the `per-page-manifest` branch). But, the latest offline plugin code [does implement the correct API](https://github.com/gatsbyjs/gatsby/blob/per-page-manifest/packages/gatsby-plugin-offline/src/gatsby-browser.js#L60), for some reason it isn't being picked up by the e2e-tests on circleCI. It does work with the appropriate `gatsby-dev -s -q` on my local machine.

@KyleAMathews and I encountered this while reviewing PRs on `per-page-manfiest` branch before and decided to just merge it.

**Comment by KyleAMathews** [comment]
@Moocar thinks it might because he's not merging to master here

**Comment by Moocar** [comment]
@wardpeet I'm just going to merge this. If you have any feedback, let me know and I can open another PR

**Comment by wardpeet** [comment]
all good! 😉

**Pull request merged**
