### PR TITLE
Updated .gitignore with proper essentials

### PR DESCRIPTION
**Pull request by Rajchowdhury420**
## Description

Added some essentials in git ignore file !

### CODE REVIEW

**Comment by blainekasten** [comment]
@Rajchowdhury420 Thanks for the contribution. When would we run into these issues? I'm hesitant to merge a change that doesn't actually affect us currently.

**Comment by Rajchowdhury420** [comment]
> @Rajchowdhury420 Thanks for the contribution. When would we run into these issues? I'm hesitant to merge a change that doesn't actually affect us currently.



then should i close it ??

**Comment by Rajchowdhury420** [comment]
@KyleAMathews what should i do man ??

**Comment by blainekasten** [comment]
@Rajchowdhury420 You never answered my question! 😄

**Comment by Rajchowdhury420** [comment]
> @Rajchowdhury420 You never answered my question! smile

@blainekasten  i don't get it what u saying

**Comment by blainekasten** [comment]
@Rajchowdhury420 You added 3 items to the .gitignore: `Thumbs.db, jspm_packages/, .npm`

What would cause those files/directories to be created in the first place? Im hesitant to merge this PR because we haven't previously ran into the need to ignore these files/directories.

**Comment by blainekasten** [comment]
Hey! I’m going close this PR as I don’t see us needing this change. If you can show me resources of why it’s important I’m happy to consider.

**Pull request closed without merging**
