### PR TITLE
Guide: Deploy Gatsby with Layer0

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
## Description
This PR aims to document how to deploy Gatsby applications with [Layer0](https://www.layer0.co/).

[Layer0](https://www.layer0.co) is an all-in-one platform to develop, deploy, preview, experiment on, monitor, and run your headless frontend. It is focused on large, dynamic websites and best-in-class performance through EdgeJS (a JavaScript-based Content Delivery Network), predictive prefetching, and performance monitoring. Layer0 offers a free tier.

## Some of the Layer0 Customers
- https://www.layer0.co/customers

## References
- [Example Source](https://github.com/layer0-docs/layer0-gatsby-example)
- [Official Gatsby with Layer0 Guide](https://docs.layer0.co/guides/gatsby)
- [Layer0 Deployment Docs](https://docs.layer0.co/docs)

### CODE REVIEW

**Comment by LekoArts** [comment]
Hi, thanks for the PR!

We're not accepting any new guides as from our experience those quickly get outdated. For a while now we ask third-party providers to host their own guides and optionally add a link to it here: https://www.gatsbyjs.com/docs/how-to/sourcing-data/headless-cms/

If you have a guide on your site, feel free to open a new PR adding a link to the page I mentioned. Thanks!

**Comment by rishi-raj-jain** [comment]
> Hi, thanks for the PR!
> 
> We're not accepting any new guides as from our experience those quickly get outdated. For a while now we ask third-party providers to host their own guides and optionally add a link to it here: https://www.gatsbyjs.com/docs/how-to/sourcing-data/headless-cms/
> 
> If you have a guide on your site, feel free to open a new PR adding a link to the page I mentioned. Thanks!

@LekoArts I see https://github.com/gatsbyjs/gatsby/pull/19960 being added, would you be open to adding Edgio (the new Layer0) as well?

**Comment by rishi-raj-jain** [comment]
I see 12 additional guides entailing each deployment process in detail, why not open to adding this one?

Screenshot 2023-02-02 at 2 16 26 AM

**Comment by rishi-raj-jain** [comment]
https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/deploying-to-heroku/ Heroku is paid now!

**Pull request closed without merging**
