### PR TITLE
Examples/using unstated

### PR DESCRIPTION
**Pull request by greglobinski**
This is an example of usage - `unstated` as a central state container.

I tried to ask if such a code is welcome as PR https://github.com/gatsbyjs/gatsby/issues/6840 

If you do not want to fatten the `examples` folder just close this request.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit f90bcc7c4299e42b490c0b543b18daa00750d69c

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6112623813f07d4ad70018

**Comment by KyleAMathews** [comment]
Deploy preview for *using-styled-components* failed.

Built with commit f90bcc7c4299e42b490c0b543b18daa00750d69c

https://app.netlify.com/sites/using-styled-components/deploys/5b6112633813f07d4ad70020

**Comment by pieh** [comment]
Hey, let's try to not multiplicate very similiar examples.
How about instead of adding example, we add guide / recipe to the docs that show how to setup any package that uses `Provider` (so this can be `redux`, `unstated` or even "new" React context)?

Also side note - `replaceRouterComponent` API will probably be removed when we switch from `react-router` to `@reach/router`. It also doesn't make sense to use that API to add providers - if any of other existing APIs doesn't allow to do that (potentially `wrapRootComponent` could be good candidate?) we should add such API

**Comment by pieh** [comment]
As follow up to my previous comment - using `wrapRootComponent` is viable replacement for `replaceRouterComponent` in "Provider" usecases - see https://github.com/gatsbyjs/gatsby/pull/6986

**Comment by greglobinski** [comment]
Ok. Thank you.

**Pull request closed without merging**
