### PR TITLE
(#6943): tutorial part one rewrite

### PR DESCRIPTION
**Pull request by amberleyromo**
- removes environment setup information (fully contained in part zero, in #6967).
- Integrates "Building with components" section from part two into part one.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 10021c3fea8d1f03b87ec7c717da55e9d7127c86

https://app.netlify.com/sites/using-postcss-sass/deploys/5b631c43fdd72a16f70b4385

**Comment by shannonbux** [comment]
Hey @amberleyromo ! This looks amazing! Very smooth intro that will let people jump in here if they didn't want to do part 0, and a nice finish with Deployment :D

**Comment by shannonbux** [comment]
I'm just going to approve part 0 too so we can merge them in quick succession as to not cause confusion to anyone who sees the tutorial soon 👍

**Comment by KyleAMathews** [comment]
Deploy preview for *using-remark* failed.

Built with commit a94332049c6fa5a9dd9a14a22e80bed6ac50d3ec

https://app.netlify.com/sites/using-remark/deploys/5b643f3bb13fb1182db9cb4b

**Pull request merged**
