### PR TITLE
Update tailwind-css.md

### PR DESCRIPTION
**Pull request by alejandronanez**
## Description

Tailwind's CSS-in-JS section was referring to `Styled Components`, but in reality, it is using `Emotion`. I updated the documentation to reflect that.

### Documentation

https://www.gatsbyjs.org/docs/tailwind-css/

## Related Issues
N/A

### CODE REVIEW

**Comment by gillkyle** [comment]
Hey @alejandronanez, I'm reviewing the linked page on using Tailwind CSS and it looks like all references in that page are using Styled Components 🤔 could you link to an example of where you see mentions or examples of Emotion? 

I'm inclined to say this is okay as it is, so will close for now, but feel free to reopen if you find something else that looks like a problem.

**Comment by lannonbr** [comment]
@gillkyle I think they were pointing out here in Option 2 CSS-in-JS: https://www.gatsbyjs.org/docs/tailwind-css/#option-2-css-in-js

it says examples are based on Styled Components, but Option 1 in that section tells you to install Emotion, so things are a little messy in this regard.

**Comment by gillkyle** [comment]
@lannonbr Yes! Okay, I must have seen right through that! 🤦 thanks for pointing that out, in that case I'll reopen and review!

**Comment by alejandronanez** [comment]
Thanks for chiming in @lannonbr!

Happy to help @gillkyle 👍

**Pull request merged**
