### PR TITLE
Fix extra space below the first line of new slogan

### PR DESCRIPTION
**Pull request by joshbuchea**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 0fefaddea1f82c861a9bb51bb5fdf6b96bfc8380

https://app.netlify.com/sites/using-postcss-sass/deploys/5b525123b13fb17d22e59bf4

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbygram* failed.

Built with commit 0fefaddea1f82c861a9bb51bb5fdf6b96bfc8380

https://app.netlify.com/sites/gatsbygram/deploys/5b525123b13fb17d22e59bee

**Comment by m-allanson** [comment]
Thanks for looking into this @joshbuchea 👍 It looks like this doesn't reduce the distance between the lines though?

To do that you'd also need to set `line-height: 1` in slider.css:

https://github.com/gatsbyjs/gatsby/blob/518a5829f77a656464778fe578088b9503ce3392/www/src/components/slider.css#L5

However that causes a new problem as the g of _blazing_ is uncomfortably close to the t of _with_: 
screen shot 2018-07-23 at 12 45 19

@fk, do you have any thoughts on how to resolve this? I guess we can't just write _blazin'_ :)

**Comment by m-allanson** [comment]
Note - the deploy previews aren't working at the moment so you need to run this branch locally to view this PR.

**Comment by fk** [comment]
Let's remove the `line-height` from `.slidingVertical` https://github.com/gatsbyjs/gatsby/blob/518a5829f77a656464778fe578088b9503ce3392/www/src/components/slider.css#L5

and give the `<h1>` a `lineHeight` of `1.1` instead of `1`in https://github.com/gatsbyjs/gatsby/blob/518a5829f77a656464778fe578088b9503ce3392/www/src/components/masthead.js#L51

This should get us here:

image

(This message sponsored by [1979](https://www.youtube.com/watch?v=QHxc3e2TJXc) 🎉 😉)

**Comment by joshbuchea** [comment]
Changes made ✅ Thanks for walking me through this one 🙌

**Comment by joshbuchea** [comment]
@m-allanson & @fk: the **g** in **blazing** is still slightly clipped with the provided values. In my testing `lineHeight` on the `<h1>` needed to be increased to `1.15` to prevent clipping.

**Comment by fk** [comment]
Hey Josh, thanks for your work!
I think I removed an `overflow:hidden` from `.slidingVertical span`, too,
and forgot to mention that.
Could you check once more please? 🙏

>

**Comment by joshbuchea** [comment]
@fk sure 👍 Done ✅

**Pull request merged**
