### PR TITLE
fix(gatsby-plugin-sharp): Allow brackets in paths

### LINKED ISSUE #18222: [gatsby-remark-images] bug with [ ] in path
If in path contains `[ ]` an error occurs -

`
./posts/000.post/ //Ok
./posts/[000]post/ // Error 
`
>/home/user/gatsby-remark-images-bug-with-path/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
throw ex;
^
TypeError: Cannot destructure property `job` of 'undefined' or 'null'.
  at runJobs (/home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/scheduler.js:99:9)
at /home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/scheduler.js:87:7
at /home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/scheduler.js:24:3
at /home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/node_modules/async/queue.js:10:5
at Object.process (/home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/node_modules/async/internal/queue.js:175:17)
at /home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/node_modules/async/internal/queue.js:82:19
at Immediate.<anonymous> (/home/user/gatsby-remark-images-bug-with-path/node_modules/gatsby-plugin-sharp/node_modules/async/internal/setImmediate.js:27:16)

[demo repo](https://github.com/isoftninja/gatsby-remark-images-bug-with-path)

### PR DESCRIPTION
**Pull request by emilpalsson**
## Description

Allow brackets in paths by using this [method](https://github.com/lodash/lodash/issues/3529#issuecomment-448586433), which tells lodash to not parse the `inputFileKey` or `outputFileKey` parts of `jobPath`.

## Related Issues

Fixes #18222

### CODE REVIEW

**Comment by wardpeet** [comment]
Thanks for updating, can you add a unit test so we are sure we tackled this probem correctly? Tests for gatsby-plugin-sharp can be found at https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sharp/src/__tests__

**Comment by emilpalsson** [comment]
I'd be happy to, @wardpeet. But as I understand, the entire `scheduleJob` function (in which my fix is placed) is mocked away in the tests right now. Since I'm new to this repo, I have a hard time figuring out how to properly test that function without a lot of changes. I think I need some pointers.

**Comment by sidharthachatterjee** [comment]
It appears that I broke a couple of other tests 🤦‍♂ Let me revisit this in a bit

**Comment by emilpalsson** [comment]
Thanks alot @sidharthachatterjee, those were just the pointers I needed :) Gj! I think I fixed the other broken tests. Let's see.

**Pull request merged**
