### PR TITLE
fix(www): Fix showcase visit site link overlap

### PR DESCRIPTION
**Pull request by daydream05**
It fixes this issue https://github.com/gatsbyjs/gatsby/issues/10242

- Only moved the top position so it’s not blocking the github button
- Just used arbitrary 8px
- Kept the original layout when it goes back to desktop

site showcase details fix

### CODE REVIEW

**Comment by LekoArts** [comment]
@fk Are you okay with that design decision?

**Comment by wardpeet** [comment]
I don't have a strong opinion on it but I don't having it on the next line without overlapping the image.

I'm expanding the question of @LekoArts to @gatsbyjs/ecosystem.
> Are you okay with that design decision?

**Comment by jlengstorf** [comment]
Is there an a11y issue if we drop the label text for smaller screens and just show the "visit link" icon? Theoretically this would allow keeping all the buttons on the same row.

**Comment by LekoArts** [comment]
As long as the icon isn't hidden (with `aria-hidden=true` and `focusable=false`) and has an appropriate `aria-label` that should be fine I guess.

**Comment by fk** [comment]
🙏 + 👍 to @wardpeet's comment and what Jason is suggesting — we have the site link right below the URL anyway.

**Comment by wardpeet** [comment]
@gatsbyjs/ecosystem @fk I updated the PR it now does the following:

nog github button:
showcase-nogithub-small
with github button:
showcase-withgithub-small

large:
showcase-big

**Pull request merged**
