### PR TITLE
Deleting lint

### PR DESCRIPTION
**Pull request by haysclark**
Added eslint ignore to fix the build while the code is being refactored to unblock the build.

### CODE REVIEW

**Comment by barraq** [comment]
@haysclark actually this variable is not used, it can be removed: see https://github.com/gatsbyjs/gatsby/pull/3034

**Comment by haysclark** [comment]
@barraq You are totally right, I just wimped out of deleting Kyles refactoring code. I deleted the code to kick off another build. I am having the same issue that you are having with Netlify not working, which is lame because it's _master_ without 3 lines of lint. ¯\_(ツ)_/¯

**Comment by haysclark** [comment]
@KyleAMathews there seems to be an issue with Netlify not kicking off builds for Gatsby's CI. The failures appear to be timeouts.

**Comment by KyleAMathews** [comment]
Netlify is really hard to debug and we're moving to a custom system soon :-| sorry about the confusion.

**Comment by KyleAMathews** [comment]
Merged another PR that fixed the linting issue https://github.com/gatsbyjs/gatsby/pull/3034

Thanks!

**Pull request closed without merging**
