### PR TITLE
fix(gatsby-theme-notes): Use basePath as home breadcrumb link

### PR DESCRIPTION
**Pull request by jakewies**
## Description

Use the `basePath` option in `gatsby-theme-notes` to construct the link of the home breadcrumb icon.

## Related Issues

Fixes https://github.com/gatsbyjs/gatsby/issues/15494

### CODE REVIEW

**Comment by sidharthachatterjee** [comment]
@jakewies Is this still necessary now that https://github.com/gatsbyjs/gatsby/pull/16556 is in?

**Comment by jakewies** [comment]
@sidharthachatterjee yes, it solves a different problem. However, if you read https://github.com/gatsbyjs/gatsby/issues/15494#issuecomment-520550971 I brought up an issue that sticks out to me. If others agree with the issue, then I can re-work this PR.

**Comment by sidharthachatterjee** [comment]
@jakewies Just saw the comment. The issue and your proposed solutions makes sense to me!

**Comment by jakewies** [comment]
Ok great I'll make that change in this PR 👍

**Comment by sidharthachatterjee** [comment]
Sounds good! Thanks @jakewies 👍

**Comment by jakewies** [comment]
@sidharthachatterjee so i definitely seem to have made a mistake here 😢 

Sorry, still new at contributing to OSS. Let me see if I can explain:

I tried to update my PR branch locally with recent changes to the `master` branch, so here's what I've done:

```
# locally

git fetch upstream
git checkout master
git merge upstream/master

# check out local PR branch
git checkout themes/fix-breadcrumb-home-link
git rebase master

# make changes and commit
git commit -m "stuff"

# here's where things got fuzzy...
git push
```

I wasn't able to push and git informed me about fails a "non-fast-forward" (I should've taken a snapshot of the actual message, but I imagine this is pretty common for newcomers?).

I did some googling after the fact and came across [this helpful Stackoverflow explanation](https://stackoverflow.com/a/17182696). 

So the main thing is: 

_Did I make a mistake by rebasing on `master` in the first place?_

And how would I go about resolving this current predicament? 

And finally, what should I have done to update this PR with recent changes from `master` so this never happens again 😅 Thanks!

**Comment by sidharthachatterjee** [comment]
@jakewies No worries at all. It happens to the best of us! I think what happened is what you probably forgot to run `git rebase --continue` and committed instead? 

I merged master in and fixed it. Typically I've seen that `git merge master` tends to be easier than `git rebase master` since a rebase goes commit by commit and a merge does not.

**Comment by jakewies** [comment]
Ok awesome! So, just to recap:

The home breadcrumb is now linked to the `basePath`:

```
# home breadcrumb links to basePath

~ / example-dir
```

This structure also supports nested notes:

```
~ / example-dir / nested-dir
```

However, it seems that [`gatsby-node.js`](https://github.com/gatsbyjs/gatsby/blob/master/themes/gatsby-theme-notes/gatsby-node.js#L115) constructs the breadcrumbs in a way that prevents nested "breadcrumbs" from working. This doesn't mean that nested notes can't work in a project, it just means that nested breadcrumbs are broken. I can make a fix for this as well if need be.

**Pull request merged**
