### PR TITLE
Add Brittany Chiang to showcase

### PR DESCRIPTION
**Pull request by bchiang7**
Hello! I was going about adding my site to the bottom of `site.yml`, and I unfortunately discovered that the most recent addition (https://www.kelvinkamau.app/) to the showcase had blatantly plagiarized my code without giving my proper attribution. I do have my repo for the site open source (for now) at https://github.com/bchiang7/v4.

Here is his website: https://www.kelvinkamau.app/
Here is my website: https://brittanychiang.com/

I was wondering if there was anyone who has the power to moderate the showcase, since I know it's not my jurisdiction to remove anyone's submission. However, seeing as they essentially plagiarized my code and submitted it to the showcase under their name, I was wondering if there could be an exception to remove their submission. If not, I understand, and I can add his code back above my submission.

Thank you for your time!

### CODE REVIEW

**Comment by amberleyromo** [comment]
Hey @kelvinkamau, is this true? If so, that's cool (the readme encourages forking, with credit), but we only allow the original version of the site in the showcase to give the creator the credit.

**Comment by akadop** [comment]
`Handcrafted with ❤ in Nairobi.`

lol this is not right

**Comment by jquense** [comment]
@KyleAMathews ^

**Comment by kelvinkamau** [comment]
@amberleyromo Kindy showcase the @bchiang7 site as we focus to build more blazing fast, compelling apps and websites for the future.

**Comment by bchiang7** [comment]
Thanks Amberley! I appreciate it!

**Comment by pieh** [comment]
Here are comments that were deleted (unfortunately I can't just restore them):

@jquense:
> @KyleAMathews ^

@akadop:
> Handcrafted with in Nairobi. lol this is not right

Deleting other people comments is big no here. I've removed @kelvinkamau from gatsby org after he deleted those comments.

**Comment by kelvinkamau** [comment]
@pieh  I apologize for that. However I don't think removing me from the org was really necessary or fair.

**Comment by KyleAMathews** [comment]
@kelvinkamau our code of conduct is here: https://www.gatsbyjs.org/docs/code-of-conduct

You:

- didn't respond to criticism gracefully
- didn't focus on what's best for the community (respecting other people's work)
- didn't show empathy for @bchiang7 by considering how'd she feel by stealing attribution for her work)
- didn't show behavior appropriate for a professional setting


Also:
>Project maintainers are responsible for clarifying the standards of acceptable behavior and are expected to take appropriate and fair corrective action in response to any instances of unacceptable behavior.

That's what we've done here — we've clarified that taking someone else's work and presenting it as your own will mean you're removed as a maintainer on this project.

**Pull request merged**
