### PR TITLE
[docs][recipes] Update to Linking Between Recipe with example + tests

### PR DESCRIPTION
**Pull request by marcysutton**
## Description

This week I started a pilot project for adding recipe examples with tests to create more of a culture of testing in Gatsby. I'd love for this PR to start a conversation about that approach, to see whether folks on the team feel that's a good idea. At the very least, the content updates to the recipe and adding an example are worthwhile changes in my opinion.

### Documentation

The decisions made in this PR may impact contributing docs, but that would happen in later work.

## Related Issues

N/A

### CODE REVIEW

**Comment by laurieontech** [comment]
This is really cool! So the idea would be example repos with testing that matches code tutorials, recipes, etc?
I like the concept a lot though I do wonder what kind of impact that will have on the size of the repo. We'd end up duplicating the code in both written form and project form. It's likely worth it, but I suspect we have duplication in written code steps as well, so perhaps an audit of that to make sure we aren't testing the same code paths would make sense?

**Comment by marcysutton** [comment]
> the idea would be example repos with testing that matches code tutorials, recipes, etc?

Yep. I'm proposing writing simple tests for each one, but not necessarily running them with CI. That impact would be way larger. These are mostly for more robust examples.

> We'd end up duplicating the code in both written form and project form. It's likely worth it, but I suspect we have duplication in written code steps as well, so perhaps an audit of that to make sure we aren't testing the same code paths would make sense?

I would definitely say it's worth it to have more examples, as users can grab those as starting points and play around with them without even having to follow the recipe. It lowers the barrier to entry that much more. What do you mean by "an audit of [duplication in written code steps]" in terms of testing code paths? I didn't quite follow. The tests I'm proposing will be based on the final output, not a branching scenario.

**Comment by laurieontech** [comment]
Certainly could have been clearer. I was thinking about the larger code coverage we'd be aiming for by having numerous example repos and matching tests. I suspect that in the process of aiming to cover snippets in both tutorials and recipes (and maybe more) we'd end up with similar if not identical projects. For example, baseline gatsby-image functionality. 
It's not an immediate concern, but in order to cover the largest amount of code snippets represented in the docs we may want to perform some sort of audit at large to determine what documents to focus on. Rather than divvying up each doc and assuming the code involved is sufficiently discrete.
I may still be struggling to explain this, but it's more of a meta consideration rather than something we need to solve as part of this PR.

My main question out of this PR is how/when are we triggering the testing suite so that we can consistently confirm expected behavior?

**Comment by marcysutton** [comment]
> My main question out of this PR is how/when are we triggering the testing suite so that we can consistently confirm expected behavior?

It's a manual process that the user would run (as per the README), not being run by CI. We could change that in the future, but I don't think it should block this PR.

**Comment by AishaBlake** [comment]
Merging since we're not expecting a review from Core on this! We should continue the conversation about if/how we want to approach building out more examples and tests elsewhere.

**Comment by marcysutton** [comment]
Thanks, Aisha! I agree that it's a bigger conversation than this one PR. I will add it to my list of things to discuss!

**Comment by muescha** [comment]
i would also like to see the testing in the very early tutorials (for example getting started tutorials) to guide new users at the very beginning to the testing

**Pull request merged**
