### PR TITLE
[gatsby-link] Add helper `withPrefix` method

### LINKED ISSUE #2254: Best way to handle path prefix for layout component?
So like some of the example apps, my layout component displays different things to the user on different kind of pages. Currently, I'm just simply testing if the .location property passed into layout component is "/" or not. 

However, I encountered problem when I'm in production build where the site has a pathPrefix. 

Is the best way just to read pathPrefix variable by using a graphql and test on that prefix? It just feels strange though, having to deal with pathPrefix throughly in user code space. I'm kind of thinking that since it was supposed to be a config, it should get over all the labor required in an app..

### PR DESCRIPTION
**Pull request by kripod**
Resolves #2254

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hmm but this isn't exposed so doesn't help you prefix links in your own code.

**Comment by kripod** [comment]
@KyleAMathews Cannot it be imported using `import { withPrefix } from 'gatsby-link'`? If not, then I would appreciate if you could suggest a better location for exposure.

**Comment by KyleAMathews** [comment]
Haha, so it is. Didn't read that closely enough obviously.

Could you update the README as well to document this change.

**Comment by kripod** [comment]
Sure, I will, as soon as I have some free time 😊

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 182b0e6bd1267adc127416baf616b1bb64a7bff5

https://app.netlify.com/sites/using-glamor/deploys/59e708c7a6188f462ab532c1

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
