### PR TITLE
Building and deploying multiple sites within the same Gatsby app - Issue 2189

### PR DESCRIPTION
**Pull request by clarksandholtz**
All gatsby commands (`develop`, `build`, `serve`) now accept an arg `--rootDir` to specify where the root node_modules reside.

NOTE:
Requires `relay-compiler v 1.3.0` for some of the files used in the processes, such as `relayCompilerContext.js`. That file did not exist in `v 1.4.0`

Is a possible solution to the problem discussed in issue #2189

### CODE REVIEW

**Comment by clarksandholtz** [comment]
Pair programmed with @donovanhiland

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 70189c40413b8d1d94e74db4c02fcaa6be587d7b

https://app.netlify.com/sites/using-glamor/deploys/59cacb69cf321c781df2c3cf

**Comment by clarksandholtz** [comment]
Is there a way for us to see the netlify logs so we can understand why the deploy preview failed?

**Comment by KyleAMathews** [comment]
Re: Netlify — no, just try building the site locally.

Quick review, we went away from `process.cwd` a while ago. Also why'd you remove `resolve-cwd`?

@jquense you have any thoughts on possible solutions here?

**Comment by clarksandholtz** [comment]
What are the build commands for testing locally?

We removed `resolve-cwd` because we weren't using it. 

We got the idea for this fix from [Jest's `rootDir` config option. ](https://facebook.github.io/jest/docs/en/configuration.html#rootdir-string)

It may be better to not include it as a command line option though and just have it specified in `gatsby-config.js`. 

Any thoughts on this approach?

**Comment by jquense** [comment]
My inclination is to solve this by using the node resolution strategy, e.g. walk up until you find gatsby. Is there a downside to just trying to `require('gatsby')`?

**Comment by clarksandholtz** [comment]
@jquense where would you `require('gatsby')`?

If you put it in `cli.js`, it errors out, unable to find the `node_module` because the method is being called within the global copy of Gatsby.

You can find the closest copy of Gatsby by changing `gatsby-cli.js` to something like this:
```
.
.
.
const cliFile = `dist/bin/cli.js`
let gatsbyFile = `node_modules/gatsby`
let gatsbyPath = path.resolve(gatsbyFile, cliFile)

let found = false

setTimeout(() => {
  if (!found) {
    throw new Error(`Couldn't find Gatsby. Are you sure its installed?`)
  }
}, 5000)

while (!fs.existsSync(gatsbyPath)) {
  gatsbyFile = `../${gatsbyFile}`
  gatsbyPath = path.resolve(gatsbyFile, cliFile)
}

found = true

try {
  require(gatsbyPath)
} catch (error) {
  report.error(`A local install of Gatsby exists but failed to load.`, error)
}
.
.
.
```

Even if you do this, or a more elegant version of it, you need to make sure that webpack is compiling from the `src` folder in the current working directory and and writing the output to `public` in the current working directory. 

In order to avoid using, `process.cwd`, could we just use `resolveCwd` in its place?

**Comment by KyleAMathews** [comment]
https://github.com/gatsbyjs/gatsby/pull/1969 broke this PR as @jquense refactored much of the code you were testing.

Also, this approach to solving things is… complicated as there's lots of things this could break.

I wonder if https://github.com/jeffbski/pkglink might solve your space problems? That or https://github.com/yarnpkg/yarn/issues/499 might get added eventually.

**Pull request closed without merging**
