### PR TITLE
chore: Move packages from dependencies to dev dependencies

### LINKED ISSUE #20815: Some gatsby package dependencies should be devDependencies
## Description

Migrate some dependencies in devDependencies for gatsby package.

At least these (non exhaustive):
- "@typescript-eslint/eslint-plugin"
- "@typescript-eslint/parser"
- "eslint"
- "eslint-config-react-app"
- "eslint-loader"
- "eslint-plugin-flowtype"
- "eslint-plugin-graphql"
- "eslint-plugin-import"
- "eslint-plugin-jsx-a11y"
- "eslint-plugin-react"
- "eslint-plugin-react-hooks"

### Steps to reproduce

`yarn install --production`
`npm install --production`

### Expected result

No dev packages should be installed.

### Actual result

Load linting dependencies and others

### Environment

All.

### PR DESCRIPTION
**Pull request by maecapozzi**
## Description

Fixes #20815

Move the following packages from dependencies to dev dependencies

* eslint-plugin-flowtype
* @typescript-eslint/eslint-plugin
* @typescript-eslint/parser

### CODE REVIEW

**Comment by DevSide** [comment]
I think you can move all eslint plugins, gatsby-graphiql-explorer, webpack-dev-middleware, webpack-dev-server, webpack-hot-middleware, graphql-playground-middleware-express ?, ...

**Comment by sidharthachatterjee** [comment]
@maecapozzi See https://github.com/gatsbyjs/gatsby/issues/20815#issuecomment-578161285

**Comment by pvdz** [comment]
Doesn't this apply to most of the other packages in this package.json? If not all...

Maybe there's a legacy reason why this package.json exists in the first place. @pieh?

**Comment by pieh** [comment]
That's mostly to silence npm/yarn warning about not met peer dependencies in `eslint-config-react-app`: https://unpkg.com/browse/eslint-config-react-app@5.0.1/package.json - see that those `@typescript-eslint` packages are there

So while we don't need those - users get confused about unmet peer dependency warnings when installing gatsby and it was quickest way to silence those

**Comment by pieh** [comment]
Ideally they would be listed as optional peer dependencies or something like that in `eslint-config-react-app` - but this requires some research to set this up correctly (are they trully optional or not)

**Comment by pieh** [comment]
Also some git hack for history of some line changes:
```
git log --pretty=short -u -L23,23:packages/gatsby/package.json
```
there's probably way to filter out all those renovate bot update commits, but that's usually enough for me to track history of some changes - this one led me to https://github.com/gatsbyjs/gatsby/pull/16168 which added those initially

**Comment by pieh** [comment]
Let's close this PR because we can't remove those dependencies as they are peerDeps of `eslint-config-react-app` which is used as well.

**Pull request closed without merging**
