### PR TITLE
fix dash type in tutorial part two

### PR DESCRIPTION
**Pull request by Mziserman**
Not sure if it should be the em dash or the 3/4 normals dashes.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 128a279856fa0c3df13306d4c6ba302bec46b0f4

https://app.netlify.com/sites/using-glamor/deploys/5982ec1ea700c4426fb089fa

**Comment by KyleAMathews** [comment]
It's whatever CSS Modules generates... were the dash types different? Hard to see in your diff.

**Comment by Mziserman** [comment]
In the first version it was one long dash.
Which was not in line with what css module generate : 
image

In my first fix pr I added dashes (-) to be closer to what css module generates while still using the original dashes (–) :
image

I tried it and css modules use normal dashes. So this version is the closer to css module generated classes

**Comment by KyleAMathews** [comment]
Huh, nice! Thanks for the catch!

**Pull request merged**
