### PR TITLE
[gatsby-plugin-sharp] make width optional for fixed and fluid images

### LINKED ISSUE #6752: [gatsby-plugin-sharp] correctly infer width when passing only target height
If I do 

```graphql
        file(relativePath: {eq: "img"}) {
          childImageSharp {
            fixed(width: 50) {
              ...GatsbyImageSharpFixed
            }
          }
        }
```

it's behaving as expected. The resulting image's height get automatically set according to the aspect ratio.

If on the other hand I want to fix the height:

```graphql
        file(relativePath: {eq: "img"}) {
          childImageSharp {
            fixed(height: 50) {
              ...GatsbyImageSharpFixed
            }
          }
        }
```

unexpected things happen. The width is not inferred by the aspect ratio. Instead it is set to 400 because it's set as a default [here](https://github.com/gatsbyjs/gatsby/blob/af799208eb210bc550caada43b5c1aa777dd82cf/packages/gatsby-plugin-sharp/src/index.js#L65).

For a more consistent behaviour It would be really nice to only use the fallback width of 400 if no height and no width has been set.

### LINKED ISSUE #6954: [ gatsby-image ] resolutions( height ) creates a cropped image
## Description

Using `height` with `resolutions` causes cropped image, while `width` does not. Documentation states that using _both_ will cause cropping.

### Steps to reproduce

In my case, using:

```
img {
    childImageSharp {
        resolutions( height: 400 ) {
            ...GatsbyImageSharpResolutions
```
For a source image that is 710px by 800px produces a slightly down-scaled, partially cropped image. In this case, for some reason, the image will only be scaled down until it reaches a width of 400px and then it is cropped, so the image generated by the above query is 400px by 400px with it's height cropped. If I run the same query but with `width: 355`, the result is an image that is 355px by 400px as expected.

### Expected result

The resulting image should be scaled in the same manner as when `width` is used, right? 

### Actual result

An arbitrary scale limit (of 400px in my case) in the width dimension is enforced.

### Environment

```  System:
    OS: macOS Sierra 10.12.2
    CPU: x64 Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 61.0.1
    Safari: 10.0.2
  npmPackages:
    gatsby: ^1.9.277 => 1.9.277 
    gatsby-image: ^1.0.55 => 1.0.55 
    gatsby-link: ^1.6.46 => 1.6.46 
    gatsby-plugin-catch-links: ^1.0.24 => 1.0.24 
    gatsby-plugin-feed: ^1.3.25 => 1.3.25 
    gatsby-plugin-google-analytics: ^1.0.31 => 1.0.31 
    gatsby-plugin-manifest: ^1.0.27 => 1.0.27 
    gatsby-plugin-nprogress: ^1.0.11 => 1.0.14 
    gatsby-plugin-offline: ^1.0.18 => 1.0.18 
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^1.6.48 => 1.6.48 
    gatsby-plugin-sitemap: ^1.2.25 => 1.2.25 
    gatsby-plugin-twitter: ^1.0.16 => 1.0.20 
    gatsby-plugin-typography: ^1.7.19 => 1.7.19 
    gatsby-remark-autolink-headers: ^1.4.19 => 1.4.19 
    gatsby-remark-copy-linked-files: ^1.5.37 => 1.5.37 
    gatsby-remark-images: ^1.5.67 => 1.5.67 
    gatsby-remark-prismjs: ^1.2.24 => 1.2.24 
    gatsby-remark-responsive-iframe: ^1.4.20 => 1.4.20 
    gatsby-source-filesystem: ^1.5.39 => 1.5.39 
    gatsby-transformer-remark: ^1.7.44 => 1.7.44 
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27
```

Thanks

### PR DESCRIPTION
**Pull request by danielberndt**
This pull request allows to specify only the target height of a fixed image. The width will be inferred based on the aspect ratio.
If neither height nor width are passed, the previous default width of 400 will be applied.

Closes #6954
Closes #6752

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbygram* failed.

Built with commit e60133e54df1343b9b123d26cfe7c969d0f0db6b

https://app.netlify.com/sites/gatsbygram/deploys/5b63298902ed832ba695826f

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit e60133e54df1343b9b123d26cfe7c969d0f0db6b

https://app.netlify.com/sites/using-postcss-sass/deploys/5b63298a02ed832ba6958278

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit e60133e54df1343b9b123d26cfe7c969d0f0db6b

https://app.netlify.com/sites/using-contentful/deploys/5b63298c02ed832ba6958287

**Comment by pieh** [comment]
This looks great! I think we could do similar thing for `fluid` and `maxWidth`?

**Comment by danielberndt** [comment]
Changes for inferring `maxWidth` from setting only `maxHeight` are in :)

**Comment by pieh** [comment]
Published `gatsby-plugin-sharp@2.0.0-beta.9`

**Comment by alexkirsz** [comment]
It looks like this is still happening because of https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/src/extend-node-type.js#L108 / https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-sharp/src/extend-node-type.js#L380.

**Comment by danielberndt** [comment]
Ah, good find!

@pieh it seems like it would be a good idea to have a more comprehensive test which include graphql queries. But I have no idea how to approach this architecturally. Is this something you're willing to do, or at least give some pointers on how to approach it?

How do we deal with the underlying issues, considering this PR didn't actually fix it yet?

**Comment by danielberndt** [comment]
Just for the record. My questions got resolved by #7680 :)

**Pull request merged**
