### PR TITLE
[gatsby-plugin-sharp] Keep file.name

### PR DESCRIPTION
**Pull request by LeKoArts**
Since I really want this change to be done I basically did what was proposed in this PR:
https://github.com/gatsbyjs/gatsby/pull/2306

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 00688d0e3463b14202c1957978b17027d0ee054f

https://app.netlify.com/sites/using-glamor/deploys/59fb05f50b79b728113d0c8a

**Comment by KyleAMathews** [comment]
Cool :-) Yeah finishing up others PRs is cool. Could you base it on his PR though so both of you get credit? Fork from his fork?

You'll also need to update the snapshots by running `npm run test -- -u` from the base of the repo after running `yarn bootstrap` to install everything.

**Comment by LeKoArts** [comment]
I honestly didn't know how to fork his fork respectively include it into here. I did the mentioned changes on the tests though.

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
