### PR TITLE
feat(docs): update tutorial for creating pages

### PR DESCRIPTION
**Pull request by bytrangle**
## Description

The current tutorial only works for blog posts that live in `src/pages` directory. For separation of concern, readers may wish to place your blog posts in a different directory like `content/posts`. I provided a bit of information about that and linked to the relevant page for step-by-step walthrough.

### Documentation

[Programmatically create pages for non-page components](https://www.gatsbyjs.com/docs/mdx/programmatically-creating-pages)

### CODE REVIEW

**Comment by LekoArts** [comment]
Hi!

I don't think it would be correct or good to point people to `createPages` API there. The tutorial is solely focused on the File System Route API and this would distract from that.

I also don't quite get your concern as in Part 4 https://www.gatsbyjs.com/docs/tutorial/part-4/#task-create-some-mdx-blog-posts it gets explained that you place the blog posts in `/blog`. If you want, you could also put them into `content/posts` and point `gatsby-source-filesystem` to that directory. The template in `src/pages/blog/{mdx.slug}.js` would stay the same.

**Comment by bytrangle** [comment]
I see. At the time of editing, I was unable to get the single blog posts to render, so I thought using `{mdx.slug}.js` only works when blog posts are in `src/pages`.

With the emergence of File System Route API mean `createPages` API will become obsolete?

**Comment by LekoArts** [comment]
We're trying to get to feature parity on both APIs but at the moment you can't still do everything with File System Route API as what you can do with `createPages`

**Comment by bytrangle** [comment]
Thanks for the answer. Still on the topic of programmatically creating pages from Mdx files, in this [guide](https://www.gatsbyjs.com/docs/mdx/programmatically-creating-pages/), slugs are created by calling the `createFilePath` API.

I assume it was written for an older version of Gatsby. Currently, `gatsby-plugin-mdx` will automatically create slug from file names and append it to each Mdx node. It's also better than `createFilePath` in that your file names can contain uppercase, special characters, or white space, but `gatsby-plugin-mdx` is smart enough to slugify them for you.

I see no reason for using `createFilePath` anymore. Do you think that guide needs editing?

**Comment by LekoArts** [comment]
Yeah, you're correct, it is indeed outdated. It can be simplified by using the already existing `slug`

**Pull request closed without merging**
