### PR TITLE
[v2] Fix unused Container component references in part-two of tutorial

### PR DESCRIPTION
**Pull request by kboone00**

### CODE REVIEW

**Comment by kboone00** [comment]
The Container component within the _CSS-In-JS_ section is created and imported but not use. It has inline styles that are also included in the **about-css-modules.module.css**
I remove the .container css from the module and replaced the parent div with Container.

**Comment by KyleAMathews** [comment]
Thanks! This section is a bit confusing as we removed the css-in-js examples awhile ago and forgot to change the Container to use css modules. I'll merge this and then make that change.

**Comment by kboone00** [comment]
@KyleAMathews Yeah I also added a container.module.css to the components directory and included the **margin: "3rem auto", maxWidth: 600** but wasn't sure if the inline style was on purpose or not so I didn't commit it.

**Comment by KyleAMathews** [comment]
Ah great! Just put up my PR with the copy changes that were needed as well — would love your review! https://github.com/gatsbyjs/gatsby/pull/6001

**Comment by jlengstorf** [comment]
Hiya @kboone00! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
