### PR TITLE
This request adresses issue #5608 partially

### PR DESCRIPTION
**Pull request by Aloysb**
My apologises guys if this is the wrong spot, I am new to this. I tried to create a PR to V1 but it creates 700+ commits! If I am doing this wrong, please let me know ...

Test on page #1 of tutorial for review by community before changing the rest of the tutorial. Goal: emphasize file names. Added emoji (folder) to file names to differentiate them from the coding instructions and make file name strong to  draw attention.

### CODE REVIEW

**Comment by pieh** [comment]
@Aloysb don't worry about branch for now - we will handle porting it back to v1.

Here's link to preview of this - https://deploy-preview-6220--gatsbyjs.netlify.com/tutorial/part-one/ and screenshot
f

/cc @shannonbux

**Comment by m-allanson** [comment]
Welcome @Aloysb 👋 

I wonder about other approaches to doing this. Maybe including the file name right before each code block?

screen shot 2018-06-29 at 11 30 58

Maybe this is too noisy or not clear enough.

**Comment by pieh** [comment]
I'm thinking if maybe we could add support to prismjs plugin to support something like ` ```jsx{filename:src/pages/index.js}` and display filename as part of codeblock (with distinct styling to seperate it from content)?

**Comment by shannonbux** [comment]
I like the idea of the directory icon @aloysb (and I suppose a page icon,
or other icons might come in handy). I also like the idea @pieh of
displaying the filename as part of the codeblock. Can we combine those two
ideas? How hard would that be? If it would take a while, we can just use
@aloysb 's idea first, and then use @pieh 's idea as a future enhancement!

On Fri, Jun 29, 2018 at 4:48 AM, Michal Piechowiak <notifications@github.com

**Comment by Aloysb** [comment]
Good evening,

I didn't want to modify the content in itself, so I only touched the formating;  but I do think having the filename near the code is a great idea @pieh !

I looked at a few other libraries/framework to see how they do it. The best I've come across is Angular's tutorial.
The name of the file is displayed at the top of the code, it looks clean and readable.

screen shot 2018-06-29 at 10 09 59 pm

Here is the link to their tutorial:
https://angular.io/tutorial/toh-pt0

I am trying to find out how they do it.

P.S.:
I created a local branch to work on this. If anyone is willing to explain me how to do things properly, I am eager to learn! Thank you!

**Comment by Aloysb** [comment]
Ok I found out what you mean @pieh about adding a class to prism. Currently working on it, I'll aim for something similar to Angular's tutorial.

**Comment by Aloysb** [comment]
How about something like this? (on top of the folder icon in paragraphs?)

screen shot 2018-06-30 at 10 42 32 am

**Comment by KyleAMathews** [comment]
woah, that's kinda hot 🔥 

That + a copy to clipboard button will be big improvements!

/cc @fk

**Comment by fk** [comment]
Really nice @Aloysb!

**Comment by shannonbux** [comment]
Yes, very nice @aloysb! Agree with Kyle that the next step will be a
copy/paste button (there is a separate issue for that if you or anyone
reading this is interested in picking it up! #5030

**Comment by Aloysb** [comment]
Sure! I'll update all tutorials. Thanks.

**Comment by shannonbux** [comment]
thanks!

**Comment by daliadefelipee** [comment]
Hi @Aloysb. What was the problem merging this PR? Is issue #5608 still available? Your header looks amazing by the way.

**Comment by Aloysb** [comment]
Hi!

Feel free to finish it, I'm having issue running Gatsby for some mysterious
reasons so I might not be able to finish that PR anytime soon. Thank you

I can send you the modifications to the CSS. I had to do some ugly
tinkering you might be able to refactor it proprely

**Comment by shannonbux** [comment]
Closing this for now. Thanks @Aloysb for the great designs and I copied those over to Issue #5608!

**Pull request closed without merging**
