### PR TITLE
Fixed hash anchor scrolling

### PR DESCRIPTION
**Pull request by f0rr0**
Fixes https://github.com/gatsbyjs/gatsby/issues/462

### CODE REVIEW

**Comment by KyleAMathews** [comment]
This is great! Thanks for tracking down the problem and fixing it! Could you land the same change on the 1.0 branch? 

It'd be on both https://github.com/gatsbyjs/gatsby/blob/1.0/lib/intermediate-representation-dir/production-app.js and https://github.com/gatsbyjs/gatsby/blob/1.0/lib/intermediate-representation-dir/root.js (`root.js` needs renamed but it's the development `web-entry.js` basically.)

**Comment by f0rr0** [comment]
@KyleAMathews Anytime! Opened a PR for the 1.0 branch. It'll be great if you could cut a new release from master though.

**Comment by f0rr0** [comment]
It's worth noting that the back button scrolling will not work for hash anchors on the same page. Could cause confusion for someone.

**Comment by jlengstorf** [comment]
Hiya @f0rr0! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
