### PR TITLE
fix(gatsby): Use crossorigin for link in linkPrefetch strategy

### PR DESCRIPTION
**Pull request by dennisroethig**
## Description

This adds `crossorigin="anonymous"` and `as="fetch"` to the `<link />` elements created in [/packages/gatsby/cache-dir/prefetch.js#L16-L35](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/prefetch.js#L16-L35)

#### Before
```
<link rel="prefetch" href="https://some.assets.cdn.com/myPage/page-data.json">
```

#### After
```
<link rel="prefetch" as="fetch" href="https://some.assets.cdn.com/myPage/page-data.json" crossorigin="anonymous">
```

## Related Issues

Fixes https://github.com/gatsbyjs/gatsby/issues/17578

### CODE REVIEW

**Comment by dennisroethig** [comment]
@wardpeet is there anything I can do to move this forward? Or shall I just wait for someone to come back with a direction on it? Cool either way, just want to make sure I’m not missing anything...

Cheers :)

**Comment by wardpeet** [comment]
Hey @dennisroethig,

Sorry for the late response. I just tested it and everything works fine on my end, the problem that i'm seeing is that the cdn server. Is not adding CORS headers.

This is only described in https://www.gatsbyjs.org/docs/asset-prefix/#usage-with-gatsby-plugin-offline but probably best that you just do it.

**Comment by dennisroethig** [comment]
Hey, thanks for the reply :)

I think there are two things going on here:

#### Chrome disk-cache
We use a service worker to do some unrelated stuff and I feel that somehow sets Chrome into some kind of different behavior of caching things (see https://github.com/gatsbyjs/gatsby/issues/17578#issuecomment-530753430) and using `disk-cache`

#### General
I think independent from the above, the `<link>` tags should have `crossorigin="anonymous"` set as other parts of the code are doing too (see https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/static-entry.js#L325-L335) ... this fixes the issue for us - and yes, I'm aware it's probably an edge case - but wouldn't it be the right thing to use the correct markup/attributes either way?

**Comment by dennisroethig** [comment]
Update: Also sorry, I forgot to actually reply to your point re the headers: 

Are you referring to the `` header? I think this is coming through well:

```
➜ curl -v -s -H "Origin: https://99designs.com.au" "https://microsites.99static.com/acquisition/legacy/en_US/99awards/best-design-awards/page-data/2019/best-use-of-typography/page-data.json" 1> /dev/null
```
```
*   Trying 104.20.70.209...
* TCP_NODELAY set
* Connected to microsites.99static.com (104.20.70.209) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [229 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [96 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3212 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [115 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=ssl507132.cloudflaressl.com
*  start date: Aug 23 00:00:00 2019 GMT
*  expire date: Feb 29 23:59:59 2020 GMT
*  subjectAltName: host "microsites.99static.com" matched cert's "*.99static.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fb605000400)
> GET /acquisition/legacy/en_US/99awards/best-design-awards/page-data/2019/best-use-of-typography/page-data.json HTTP/2
> Host: microsites.99static.com
> User-Agent: curl/7.54.0
> Accept: */*
> Origin: https://99designs.com.au
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Sat, 28 Sep 2019 01:37:18 GMT
< content-type: application/json
< content-length: 21782
< set-cookie: __cfduid=d3b03bea5581d1fcf6af37a963cd2257b1569634637; expires=Sun, 27-Sep-20 01:37:17 GMT; path=/; domain=.99static.com; HttpOnly
< x-amz-id-2: oiqLQjNzHcW1ec79PUGSu+Zkevm7g/A9A2d7JzGxihYHA+U69EhUek+ZmpvZIN1L3A+LedJKZ54=
< x-amz-request-id: 5FFC32968A1E767F
< access-control-allow-origin: *
< access-control-allow-methods: GET, HEAD
< access-control-max-age: 3000
< vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
< last-modified: Sat, 21 Sep 2019 00:20:30 GMT
< etag: "7b00a527f20640a502e253d49098abb2"
< accept-ranges: bytes
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 51d1fdc73e5b6d22-SJC
```

Also, this would probably be an issue for all the cross-origin requests. The issue we are facing is only the stuff that gets triggered by the code in [/packages/gatsby/cache-dir/prefetch.js#L16-L35](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/prefetch.js#L16-L35)

Thanks for looking into this, appreciate it :)

**Comment by dennisroethig** [comment]
@wardpeet any chance to get your thoughts on this? thanks, appreciate the time!

**Comment by wardpeet** [comment]
I was able to reproduce this when gatsby-plugin-offline was into place. Workbox fetches these files using cors by default which end up with a corb blocking request. (see https://www.chromium.org/Home/chromium-security/corb-for-developers).

You can reproduce this when you're using asset-prefix with a CDN (different origin) and gatsby-plugin-offline.

```js
module.exports = {
  assetPrefix: `https://cdn.yoursite.com`,
  plugins: [
    `gatsby-plugin-offline`,
  ]
}
```

I updated the PR to fix this, kinda like you did but cleaned up the code a bit.

**Comment by dennisroethig** [comment]
Thanks for following that up @wardpeet - came back from traveling and saw this ❤️

**Pull request merged**
