### PR TITLE
add a bunch of tests for various plugins

### PR DESCRIPTION
**Pull request by DSchau**
Added a bunch of tests to serve as a baseline for expected functionality.

Let me know if you'd like any further detail!

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0a8e655c0163e1091358b34aa56f7add8ae1e32a

https://app.netlify.com/sites/using-contentful/deploys/59712ba17960b1236a9917b0

**Comment by KyleAMathews** [comment]
This is so cool! A tests PR, amazing :-)

Sorry for the slow response — does not reflect my appreciation of this PR :-) Been out on vacation.

Going to merge from master to re-run tests. Looks like tests failed on Windows?

**Comment by DSchau** [comment]
@KyleAMathews hope the vacay was great, much deserved!

As for this PR, I haven't taken a look at it since I pushed it up, but I'll see if I can take another look tonight! As far as Windows support goes, I wouldn't think there'd be any regressions with Mac v. Windows, so hopefully that's not the case!

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit ad15acc73ad84ddf62537c372b5e28027b47cccf

https://app.netlify.com/sites/image-processing/deploys/597790897960b1659463eea4

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit ad15acc73ad84ddf62537c372b5e28027b47cccf

https://app.netlify.com/sites/using-glamor/deploys/597790897960b1659463eea7

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit ad15acc73ad84ddf62537c372b5e28027b47cccf

https://app.netlify.com/sites/using-styled-components/deploys/597790897960b1659463eeaa

**Comment by KyleAMathews** [comment]
Yeah seems like there's a few problems with windows https://ci.appveyor.com/project/KyleAMathews/gatsby/build/1.0.1400/job/s5r1kblirawji3uh#L526

4 failing tests in copy-linked-files.

**Comment by DSchau** [comment]
Yikes! Well I'll take a look and see if I can't get that figured out

**Comment by DSchau** [comment]
Pretty sure the issue is with this line here. I think `path.normalize` would work here, as would mocking out `path.join` to resolve any OS idiosyncrasies.

Not sure which is better. Gonna try path.normalize first.

**Comment by DSchau** [comment]
Whew, that did fix it!

Should be good to go now

**Comment by KyleAMathews** [comment]
Awesome! Thanks!

**Pull request merged**
