### PR TITLE
feat(gatsby-plugin-manifest): favicon directory can now be customized

### LINKED ISSUE #12233: [gatsby-plugin-manifest] Configurable name for icons folder?
I use gatsby-plugin-manifest in my project to generate icons. When serving it using a popular hosting service, I'm getting 404 errors for all of the icons, however. I found that the `icons` folder is aliased to the apache icons which causes the files not to be found. Since it's a shared environment, it is impossible to change the apache configuration unfortunately. 

Is it possible to configure the icons folder name in `gatsby-config.js` in some way or is there some other way to work around this issue?

### PR DESCRIPTION
**Pull request by evolkmann**
## Description

In reaction to #12233 I added the possibility to override the default favicon path (`icons`).

### Documentation

I added a new plugin option, therefore I appreciate any documentation feedback (@gatsbyjs/learning).

## Related Issues

Fixes #12233

### CODE REVIEW

**Comment by blainekasten** [comment]
Hey @evolkmann! This PR looks fantastic. You did a phenomenal job covering all the bases (tests, quality, documentation). It pains me to do this since you invested your personal time and we're grateful for that! But the attached ticket was closed for a reason.

Ultimately we try to balance the trade-off of a rich feature set to support a wide array of needs, and having a small API surface that we can guarantee to maintain and _ideally_ not break in the future. Since this issue has a solution in userland, e.g. an apache config to change the default icons folder, we've decided (at least for now) to be prudent and not accept this change. Again, I'm really sorry to do this :( We love community PRs and hope you'll keep contributing.

I'm happy to continue the discussion if you have any further thoughts!

**Comment by evolkmann** [comment]
Hi @blainekasten, thanks for your feedback!
I personally do not consider this change a big stability issue, but of course I accept the decision of your team. Given the workaround of copy-pasting the whole array of icon-sizes from the default-file, I would even argue that the current workaround is a bigger risk for future compatibility than just changing that one (now hard-coded) string.

As described in the #12233, customizing the apache config is not possible for a lot of users, including myself. Even if one could change that, it is not possible in an `.htaccess` file on the project level, but rather has to be done in something like `etc/httpd/conf/...`. I would generally consider a project-level configuration option (which many users will never have to touch anyway) better than the dependency to some system wide config change (which also could have side effects). Not everyone uses modern hosting solutions such as Netlify or a completely container-based environment, many still work with traditional web hosting solutions.

**Comment by blainekasten** [comment]
@evolkmann Thanks for continuing the conversation! I definitely understand that sometimes policy and requirements prevent modifying the apache setup in this way. Just curious, did you see the comment [here](https://github.com/gatsbyjs/gatsby/issues/12233#issuecomment-470169871). Describes how you can already achieve this today. Let me know if that doesn't solve your issue.

**Comment by devrnt** [comment]
@blainekasten The hybrid mode is indeed a working solution, but that is the reason @evolkmann created this PR. The hybrid mode requires you to copy and paste a lot of code for every favicon size. I would suggest to solve this by using a helper function as described [here](https://github.com/gatsbyjs/gatsby/issues/12233#issuecomment-572643297).

**Comment by evolkmann** [comment]
@blainekasten I saw the comment and was using the hybrid mode as a first workaround. The solution of @devrnt is also what I ended up with now to avoid copy-pasting the whole array.

**Comment by blainekasten** [comment]
@evolkmann / @devrnt Thanks for the feedback. We're looking into making an `gatsby-plugin-apache` that takes care of this stuff out of the box for our apache users!

**Pull request closed without merging**
