### PR TITLE
Update README to make it clearer about deploying to gh pages

### PR DESCRIPTION
**Pull request by jsfeb26**
I ran into some confusion when trying to deploy to Github Pages last night. Hopefully this makes it clearer

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0c64132f41e692fab83472e9505dfa9b09c4946a

https://app.netlify.com/sites/gatsbyjs/deploys/59592c7e424ef2075bd38b74

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0c64132f41e692fab83472e9505dfa9b09c4946a

https://app.netlify.com/sites/gatsbygram/deploys/59592c7e424ef2075bd38b77

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0c64132f41e692fab83472e9505dfa9b09c4946a

https://app.netlify.com/sites/using-contentful/deploys/59592c7f424ef2075bd38b8f

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0c64132f41e692fab83472e9505dfa9b09c4946a

https://app.netlify.com/sites/image-processing/deploys/59592c7f424ef2075bd38b86

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0c64132f41e692fab83472e9505dfa9b09c4946a

https://app.netlify.com/sites/using-postcss-sass/deploys/59592c7f424ef2075bd38b80

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0c64132f41e692fab83472e9505dfa9b09c4946a

https://app.netlify.com/sites/using-glamor/deploys/59592c7f424ef2075bd38b89

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0c64132f41e692fab83472e9505dfa9b09c4946a

https://app.netlify.com/sites/using-styled-components/deploys/59592c7f424ef2075bd38b8c

**Comment by KyleAMathews** [comment]
This is great! Thanks! Ignore all the error comments as those are for 1.0.

**Comment by jlengstorf** [comment]
Hiya @jsfeb26! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
