### PR TITLE
docs(dynamic-routes): utilize `basepath` of router

### PR DESCRIPTION
**Pull request by kripod**
## Description

As a simplification, the `basepath` prop of `<Router />` can be used for establishing client-only paths.

### CODE REVIEW

**Comment by gillkyle** [comment]
I didn't know about this prop! Thanks for the suggestion @kripod 🙂  I like that this simplifies the example, the advantage I see to how it is currently written is that it's easy to look at and understand without much background of Reach Router. I think it does clean up the repetition of the path names but I think adding another prop people might not be aware of (considering I wasn't aware of it either) could just introduce another thing for people to be confused by.

I lean towards one of two things:

- we merge this with an additional note next to where `basePath` is used in the first example and link to Reach Router's docs (maybe this page where it's mentioned: https://reach.tech/router/api/Router) to explain basePath
- we accept a little repetition in the path names and leave it as is

What do you think?

**Comment by kripod** [comment]
Thank you for the quick review! I’m leaning towards your first idea to embrace the principle of DRY _(don’t repeat yourself)._

**Comment by gillkyle** [comment]
Sounds good! Would you be willing to add in a little note and link then to just briefly explain what `basePath` is doing for those examples? 🙂

**Comment by kripod** [comment]
I’ve just added a brief note about the base path, as you’ve suggested.

**Comment by pieh** [comment]
Not sure if this information will be helpful for this PR, but I think it's worth mentioning:

Fact that we do need `/app` prefix (either in route's `path` or in router's `basepath`) is because we initially implemented `@reach/router` in a very bad way in gatsby core. We did some fixes to way we implemented it later on (few months ago), but damage was already done and we had to preserve this behaviour to not introduce breaking change.

We have this piece of code: https://github.com/gatsbyjs/gatsby/blob/a4d1126e856345ce83f5f9d47dc3a411a924e352/packages/gatsby/cache-dir/root.js#L36-L53

So eventually this will change, so users would be able to use relative paths in their Routers (but not in v2).

**Comment by gillkyle** [comment]
@pieh so it sounds like it was fixed recently so that `basepath` _can_ be used? Do you think suggesting this behavior shown in this PR is okay then? If so I think it can be merged.

**Pull request merged**
