### PR TITLE
[1.0] Fix 100% width code highlight background only being drawn for the vis…

### PR DESCRIPTION
**Pull request by fk**
…ible area of a container scrolling its overflowing content

… ;) :/. This is going to be fun.

`pre code` blocks are now wrapped in a div.gatsby-highlight.
Along with the whitespace changes around `.highlight-code-line` in #1187, we now should fully mimick the approach that the React Tutorial code example uses (see https://facebook.github.io/react/tutorial/tutorial.html).

Essentialy, the new container around our highlighted `pre code` allows us to apply `float:left; min-width:100%` to `<pre>`, which solves the problem of highlighted code line backgrounds not being drawn for the overflowing part of the code block container.
See e. g. https://stackoverflow.com/a/8513330 for a few more pointers as to why and how this works.

To get the new container wrapped _around_ and not appended _in between_ the node's own `<code>` and the apparently later generated `<pre>`, we replace the code node and wrap the highlighted code in `<pre>` and `<code>` plus our additional `<div>` ourselves.

Breaking change to namespace CSS class names: `span.highlight-code-line` is now `span.gatsby-highlight-code-line`.

Phew! ;)

### CODE REVIEW

**Comment by fk** [comment]
To illustrate that 💩 of a commit message – before/after:

image

Also made the highlighted blocks a little calmer and increased line-height a little:

image

**Comment by KyleAMathews** [comment]
Looking good! Looks like there's just a snapshot that needs updated (due to the new classname) for the tests to pass. Thanks!

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by fk** [comment]
Fingers crossed that this is the last time we need to revisit this! 😝

**Pull request merged**
