### PR TITLE
Removed outline on toggle

### PR DESCRIPTION
**Pull request by AkSachin**
Removed outline on toggling between dark and light mode.

### CODE REVIEW

**Comment by marcysutton** [comment]
I don't think we should merge this -- focus outlines are there for keyboard users. If we're going to remove the default outline, it needs some kind of visual indicator on focus, and the links next to it use the default focus outline.

**Comment by AkSachin** [comment]
I see. Makes sense.

**Comment by LekoArts** [comment]
@AkSachin Would you be up for implementing these changes? If not we can close this PR :)

**Comment by AkSachin** [comment]
You can close PR as of now. I'll request for new PR whenever I make proper changes that are keyboard-users friendly.

**Comment by LekoArts** [comment]
Cool!

**Pull request closed without merging**
