### PR TITLE
Update Gatsby WWW site gatsby-plugin-manifest config

### PR DESCRIPTION
**Pull request by moonmeister**
Modified the config to use the new automatic Icon generation in the gatsby-plugin-manifest plugin at @KyleAMathews request.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
👏 

screen shot 2018-04-10 at 3 39 01 pm

**Comment by KyleAMathews** [comment]
We added a requirement recently that contributors sign-off commits! We're still kinda new to the process but could you `git commit --amend --signoff` and force push the amended commit?

**Comment by moonmeister** [comment]
@KyleAMathews yeah I thought I followed the instructions but I'll try what you recommend

**Comment by KyleAMathews** [comment]
Yeah, you have to amend the previous commits.

**Comment by moonmeister** [comment]
@KyleAMathews I had to squash all the commits into a single then signoff on that one commit..so the issue was probably that I didn't sign off on ALL the commits.

**Comment by KyleAMathews** [comment]
That did it, thanks!

**Pull request merged**
