### PR TITLE
feat(gatsby-plugin-sharp): reduce encoding time and install size

### LINKED ISSUE #31792: [gatsby-plugin-image, sharp] Black border is added directly to an image
## Description

A black border is added directly to an image. This happened also with other images, but the issue appeared, vanished and reappeared for two different images.

# **The file** 
amfori

# **The query** 
```
Amfori: file(relativePath: { eq: "amfori.png" }) {
      name
      childImageSharp {
        gatsbyImageData(
          width: 400
          placeholder: NONE
          formats: [WEBP, AVIF, AUTO]
          quality: 75
        )
      }
    }
```
# **The result**

image
image

# **Thoughts**

The issue seems to be related to the `width` image transform. If I change the width of the query slightly (f.e. by one px), the issue vanishes.

As an example, `width: 400` causes the issue, `width: 401` doesn't. `width: 402` doesn't and `width: 404` does again.

# **Possibly related**

1. [https://github.com/lovell/sharp/issues/1185](https://github.com/lovell/sharp/issues/1185)
2. [https://github.com/gatsbyjs/gatsby/issues/31488](https://github.com/gatsbyjs/gatsby/issues/31488)
3. [https://github.com/libvips/libvips/issues/1476](https://github.com/libvips/libvips/issues/1476)

### Reproduction

I am working on a reproduction here:
[https://codesandbox.io/s/gatsby-issue-31792-reproduction-d4jyt](https://codesandbox.io/s/gatsby-issue-31792-reproduction-d4jyt)

So far I haven't been successfully able to reproduce the issue on `codesandbox`. 

### Environment

gatsby info:
```
  System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.1.0 - /usr/bin/node
    Yarn: 1.22.10 - ~/.npm-packages/bin/yarn
    npm: 7.12.1 - /usr/bin/npm
  Languages:
    Python: 3.9.5 - /usr/bin/python
  Browsers:
    Firefox: 89.0
  npmPackages:
    gatsby: ^3.6.2 => 3.6.2 
    gatsby-image: ^3.6.0 => 3.6.0 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-anchor-links: ^1.2.1 => 1.2.1 
    gatsby-plugin-create-client-paths: ^3.6.0 => 3.6.0 
    gatsby-plugin-gdpr-cookies: ^2.0.0 => 2.0.0 
    gatsby-plugin-google-gtag: ^3.6.0 => 3.6.0 
    gatsby-plugin-image: ^1.6.0 => 1.6.0 
    gatsby-plugin-loadable-components-ssr: next => 2.2.1-beta.2 
    gatsby-plugin-manifest: ^3.6.0 => 3.6.0 
    gatsby-plugin-netlify: ^3.6.1 => 3.6.1 
    gatsby-plugin-netlify-headers: ^1.0.1 => 1.0.1 
    gatsby-plugin-offline: ^4.6.0 => 4.6.0 
    gatsby-plugin-perf-budgets: ^0.0.18 => 0.0.18 
    gatsby-plugin-postcss: ^4.6.0 => 4.6.0 
    gatsby-plugin-react-helmet: ^4.6.0 => 4.6.0 
    gatsby-plugin-robots-txt: ^1.6.2 => 1.6.2 
    gatsby-plugin-root-import: ^2.0.6 => 2.0.6 
    gatsby-plugin-sanity-image: ^0.6.0 => 0.6.0 
    gatsby-plugin-sass: ^4.6.0 => 4.6.0 
    gatsby-plugin-sharp: ^3.6.0 => 3.6.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.22 
    gatsby-source-filesystem: ^3.6.0 => 3.6.0 
    gatsby-source-sanity: ^7.0.4 => 7.0.4 
    gatsby-transformer-remark: ^4.3.0 => 4.3.0 
    gatsby-transformer-sharp: ^3.6.0 => 3.6.0 
  npmGlobalPackages:
    gatsby-cli: 3.6.0
```

Flags used: `DEV_SSR`

### PR DESCRIPTION
**Pull request by lovell**
## Description

- Upgrades sharp to v0.29.0
- Replaces use of imagemin with sharp equivalents
- Removes GPLv3 code from the dependency graph
- Reduces JPEG, PNG and AVIF encoding time by up to 50%
- Reduces total Gatsby install size/time by ~10% (~19MB smaller on the filesystem)
- Improves AVIF image quality, will allow them to work with Chrome 93+
  https://github.com/lovell/sharp/issues/2666

## Related Issues

Fixes #31792

### CODE REVIEW

**Comment by lovell** [comment]
The `windows_unit_tests` failure is, I suspect, due to the use of a (shared?) npm cache in CircleCI colliding with https://github.com/lovell/sharp/issues/2848. If there's a way to manually clear this cache then it should work when re-run.

**Comment by LekoArts** [comment]
> Removes GPLv3 code from the dependency graph

So this is in our plugin, not sharp itself?

**Comment by lovell** [comment]
> So this is in our plugin, not sharp itself?

Yes, this PR removes the GPLv3 [pngquant-bin](https://www.npmjs.com/package/pngquant-bin) dependency from Gatsby via the removal of `imagemin-pngquant`. sharp has never shipped GPL code, and now provides the same features via the BSD-2-Clause https://github.com/lovell/libimagequant

**Comment by pieh** [comment]
> The `windows_unit_tests` failure is, I suspect, due to the use of a (shared?) npm cache in CircleCI colliding with [lovell/sharp#2848](https://github.com/lovell/sharp/issues/2848). If there's a way to manually clear this cache then it should work when re-run.

I checked syncinc version of `sharp` used in all packages and that seemed to the trick ( https://github.com/gatsbyjs/gatsby/pull/32852 temporary PR that runs those tests with my small change). I opened PR with this change against your branch in https://github.com/lovell/gatsby/pull/1 (tho I didn't yet check wether there are any breaking changes in `0.29` those other packages might need to address)

**Review by LekoArts — APPROVED** [review]
Thanks! We'll merge and publish under `next` tag and before the 3.13 release check is everything works :) Thanks for your work!

**Pull request merged**
