### PR TITLE
fix(blog): ButterCMS & Car Loans Canada - fix branding

### PR DESCRIPTION
**Pull request by muescha**
## Description

changes:
- fix brand names
  - `Wordpress` -> `WordPress`
  - `Butter` -> `ButterCMS`
  - `Canada Car Loans` -> `Car Loans Canada`
  - `car loans Canada` -> `Car Loans Canada`

## Related Issues

- #23783 `add buttercms blog post`

------

## Description

changes:

- add link to PRPL

## Motivation

- i heard this PRPL the first time, so there can be a link helpful

## Alternatives

- Change A: 

```diff
- PRPL
+ PRPL (Push, Render, Pre-cache, Lazy-load)
```

- Change B: 

```diff
- PRPL
+ Push, Render, Pre-cache, Lazy-load (PRPL)
```

## Related Issues

- #23783 `add buttercms blog post`

### CODE REVIEW

**Comment by muescha** [comment]
ping @mgienow blog author

**Comment by Ekwuno** [comment]
Hey, @muescha thanks for sending this in.  I can see that https://github.com/gatsbyjs/gatsby/pull/24502/files has a change that can be added in this PR; Can you add that in here as I am closing #24502. Also, can you open an issue for these edits? It helps keep things organized.

**Comment by muescha** [comment]
in https://github.com/gatsbyjs/gatsby/pull/22205#issuecomment-598469219 i got the advice that i should split it into smaller packages to make PR easy to check 

> open tightly-scoped PRs for each chunk of work, such as a section of the tutorial, to make it easier for us to review and test

and i agree it is more easy to check the small scoped chunks instead of a big one - thats why i opened it in separate PRs

**Comment by Ekwuno** [comment]
> #22205 (comment)

@muescha in this example you were suggesting changes to 8 separate files so it would make sense to open tightly-scoped PRs for each chunk of work. In this chase, we are dealing with one file and multiple changes to that file. I think one PR and Issue is sufficient. 🙂

**Comment by muescha** [comment]
ok i will include the change from #24502

but see this PR #23153: it is still oben since April with different changes while other will seperated are approved, i am still planning splitting this into multiple PR to get merged....

**Comment by muescha** [comment]
note: added link to PRPL

**Pull request merged**
