### PR TITLE
fix(gatsby-plugin-sharp): Upgrade `probe-image-size` to fix memory leak warning

### LINKED ISSUE #34795: MaxListenersExceededWarning errors with gatsby-plugin-image StaticImage with placeholder
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

A console error occurs on develop and build when using `StaticImage` from `gatsby-plugin-image`  with a `placeholder` attribute, [e.g:](https://github.com/jonohewitt/gatsby-image-bug-repro/blob/b4a5ef2c8ee3aa3a07b762e652468a2021f314a4/src/components/componentWithStaticImage.js#L9)

```jsx
<StaticImage src="../images/photo-1.jpg" alt="" placeholder="blurred" />
```

---

* Using `gatsby develop` or `gatsby build`:

```
ERROR

(node:15194) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

* Using `node --trace-warnings node_modules/.bin/gatsby develop`:

```
ERROR 

(node:15473) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:595:17)
    at PassThrough.addListener (node:events:617:10)
    at PassThrough.Readable.on (node:internal/streams/readable:899:35)
    at eos (node:internal/streams/end-of-stream:169:10)
    at pipe (node:internal/streams/pipeline:348:3)
    at pipelineImpl (node:internal/streams/pipeline:293:9)
    at pipeline (node:internal/streams/pipeline:146:10)
    at probeStream (/Users/hewitt/path/to/project/node_modules/probe-image-size/stream.js:63:8)
    at get_image_size (/Users/hewitt/path/to/project/node_modules/probe-image-size/index.js:13:12)
    at getImageSizeAsync (/Users/hewitt/path/to/project/node_modules/gatsby-plugin-sharp/index.js:63:28)
    at getImageMetadata (/Users/hewitt/path/to/project/node_modules/gatsby-plugin-sharp/image-data.js:33:39)
    at generateImageData (/Users/hewitt/path/to/project/node_modules/gatsby-plugin-sharp/image-data.js:123:26)
    at /Users/hewitt/path/to/project/node_modules/gatsby-plugin-image/dist/node-apis/image-processing.js:255:42
    at step (/Users/hewitt/path/to/project/node_modules/gatsby-plugin-image/dist/node-apis/image-processing.js:33:23)
    at Object.next (/Users/hewitt/path/to/project/node_modules/gatsby-plugin-image/dist/node-apis/image-processing.js:14:53)
    at /Users/hewitt/path/to/project/node_modules/gatsby-plugin-image/dist/node-apis/image-processing.js:8:71
```

Nothing seems to be visibly affected by the error - the build continues successfully afterwards.  

### Reproduction Link

https://github.com/jonohewitt/gatsby-image-bug-repro

### Steps to Reproduce

1. Install the reproduction project
2. Run `gatsby develop` to see basic error
3. Run `node --trace-warnings node_modules/.bin/gatsby develop` to see verbose error

### Expected Result

No error

### Actual Result

Error

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.80
    Safari: 15.2
  npmPackages:
    gatsby: ^4.7.1 => 4.7.1 
    gatsby-plugin-image: ^2.7.0 => 2.7.0 
    gatsby-plugin-sharp: ^4.7.0 => 4.7.0 
    gatsby-source-filesystem: ^4.7.0 => 4.7.0
```

### Config Flags

_No response_

### PR DESCRIPTION
**Pull request by jonohewitt**
## Description

Upgrades `probe-image-size` to `^7.0.0` to fix the `MaxListenersExceededWarning` console error caused by versions prior to  [https://github.com/nodeca/probe-image-size/commit/a6da059439614c399b79c09ea1d406a3e4300b27](https://github.com/nodeca/probe-image-size/commit/a6da059439614c399b79c09ea1d406a3e4300b27)

Thanks to @hendra-go for discovering the cause of the issue. 

## Related Issues

Fixes #34795

### CODE REVIEW

**Comment by LekoArts** [comment]
@jonohewitt Hi! You'll need to run `yarn` in the monorepo to update the `yarn.lock` file

**Comment by jonohewitt** [comment]
Hi @LekoArts! Sorry about that - I've pushed another commit updating the `yarn.lock` and will remember to create a new branch next time.

**Comment by ayushayagatsby** [comment]
Hi! I am occurring in this error as well for an existing project which runs on npm. How could I fix this?
I'm quite new to this, so sorry if this is a silly question.

**Comment by jonohewitt** [comment]
Hi @ayushayagatsby, it looks like this fix was included in gatsby releases since [4.10](https://www.gatsbyjs.com/docs/reference/release-notes/v4.10/) so you would just have to update gatsby to a version since then. 

• [Docs for updating Gatsby](https://www.gatsbyjs.com/docs/reference/release-notes/upgrade-gatsby-and-dependencies/)
• [Docs for migrating from v3 to v4 if you're still on v3](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/)

**Pull request merged**
