### PR TITLE
fix(*): fix gatsby-cli dep in source-filesystem & plugin-sharp

### LINKED ISSUE #14875: Error: Cannot find module 'gatsby-cli/lib/reporter'
## Description

When trying to do `gatsby build`, I'm noticing that my custom source plugins as well as Gatsby packages are trying to find `gatsby-cli/lib/reporter`, so every build fails with something that looks like this:

```
error Error in "/Users/jaredsilver/projects/marketing-app/node_modules/gatsby-plugin-sharp/gatsby-node.js":

  Error: Cannot find module 'gatsby-cli/lib/reporter'
  Require stack:
  - /Users/jaredsilver/projects/marketing-app/node_modules/gatsby-plugin-sharp/utils.js
  - /Users/jaredsilver/projects/marketing-app/node_modules/gatsby-plugin-sharp/scheduler.js
  - /Users/jaredsilver/projects/marketing-app/node_modules/gatsby-plugin-sharp/index.js
  - /Users/jaredsilver/projects/marketing-app/node_modules/gatsby-plugin-sharp/gatsby-node.js
  - /Users/jaredsilver/projects/marketing-app/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
  - /Users/jaredsilver/projects/marketing-app/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
  - /Users/jaredsilver/projects/marketing-app/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
  - /Users/jaredsilver/projects/marketing-app/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
  - /Users/jaredsilver/projects/marketing-app/node_modules/gatsby/dist/bootstrap/index.js
  - /Users/jaredsilver/projects/marketing-app/node_modules/gatsby/dist/commands/build.js
  - /Users/jaredsilver/.nvm/versions/node/v12.2.0/lib/node_modules/gatsby-cli/lib/create-cli.js
  - /Users/jaredsilver/.nvm/versions/node/v12.2.0/lib/node_modules/gatsby-cli/lib/index.js
```

### Environment

I've tried a few different versions of gatsby, gatsby-cli, and where gatsby-cli lives, but this is one example:

```
  System:
    OS: macOS High Sierra 10.13.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 59.0.2
    Safari: 11.0.3
  npmPackages:
    gatsby: ^2.9.4 => 2.9.6
    gatsby-image: ^2.1.4 => 2.1.4
    gatsby-plugin-emotion: ^4.0.6 => 4.0.7
    gatsby-plugin-portal: ^1.0.7 => 1.0.7
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.1
    gatsby-plugin-sass: ^2.0.11 => 2.0.11
    gatsby-plugin-sentry: ^1.0.1 => 1.0.1
    gatsby-plugin-sharp: ^2.1.5 => 2.1.6
    gatsby-source-apiserver: ^2.1.2 => 2.1.2
    gatsby-source-filesystem: ^2.0.39 => 2.0.40
    gatsby-source-graphql: ^2.0.19 => 2.0.19
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
    gatsby-transformer-yaml: ^2.1.12 => 2.1.12
  npmGlobalPackages:
    gatsby-cli: 2.6.9
```

### PR DESCRIPTION
**Pull request by wardpeet**
## Description
I forgot to add gatsby-cli as a dependency in gatsby-source-filesystem & gatsby-plugin-sharp 🤦‍♂. 

Instead of adding it to dependencies we should accept it as a parameter based on the #4118 PR. This makes more sense as we probably get trouble with logging in the future.

I published some versions to test, please install the ones that are in your package.json
`npm install gatsby-plugin-sharp@reporter-npm`
`npm install gatsby-source-contentful@@reporter-npm`
`npm install gatsby-source-drupal@reporter-npm`
`npm install gatsby-source-filesystem@reporter-npm`
`npm install gatsby-source-shopify@reporter-npm`
`npm install gatsby-source-wordpress@reporter-npm`
`npm install gatsby-transformer-screenshot@reporter-npm`
`npm install gatsby-transformer-sqip@reporter-npm`

## Related Issues
Fixes #14875

### CODE REVIEW

**Comment by MitchellCash** [comment]
I tested:

- `gatsby-plugin-sharp@reporter-npm`
- `gatsby-source-filesystem@reporter-npm`

Both solved the `Error: Cannot find module 'gatsby-cli/lib/reporter'` issue for me, as described in #14875.

**Comment by wardpeet** [comment]
Tested using-wordpress & gatsbygram. Seems to work with gatsby-dev. Let me publish canary builds to make sure

**Comment by wardpeet** [comment]
I've tested it on the `using-gatsby-image` example. I've ran it with installing seperate dependendencies and nothing broke.

I tested it with NPM 😎

**Comment by antoinerousseau** [comment]
Hi, I'm using `createRemoteFileNode` in my `sourceNodes` node API, but now that I updated to the latest version, TypeScript wants me to provide that `reporter` (`object`)... isn't it an internal stuff for logging? It's not in the doc anyway:
https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createremotefilenode

**Comment by wardpeet** [comment]
You have to pass it down but you're right about missing it in docs. Perhaps you can create an issue or a PR?

**Pull request merged**
