### PR TITLE
[v2] Fix Gatsbygram Cypress tests

### PR DESCRIPTION
**Pull request by davidbailey00**
- Add delays to Cypress tests to wait until pages are ready after loading/clicking etc
- Force a click where Cypress previously threw an error due to one of its children covering it
  - Clicking its children produces the same result, but it's not predictable which one Cypress will detect in front since there are multiple

### CODE REVIEW

**Comment by davidbailey00** [comment]
100ms worked locally but it looks like it's too short for Travis. I'll see if I can do this programmatically instead, or if not I'll increase the delay

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit 5cc97542429b93131291e194fb10a38e851282d9

https://app.netlify.com/sites/using-contentful/deploys/5b8057e282d3f13fe2fd1a07

**Comment by davidbailey00** [comment]
I tried fixing the AppVeyor problems - the line break issue is solved but now, for whatever reason, it's outputting differently... Again, all tests are passing on my laptop (running Ubuntu, but I can try testing on Windows later since it's dual-boot)

image

**Comment by davidbailey00** [comment]
Great, the AppVeyor builds have got stuck on "queued" right after I think I might've fixed it...

**Comment by davidbailey00** [comment]
The problem is that `--ignore` isn't working on AppVeyor so it's generating additional tests for `gatsby-codemods` - not entirely sure why since it works on my laptop running Windows (on PowerShell).

**Comment by davidbailey00** [comment]
I've decided to stop work on fixing the Windows tests - after more testing it seems to be a bug in the way Babel handles globs on Windows

**Pull request merged**
