### PR TITLE
fix(gatsby): Resolve nodes for sorting and stringify Date on sort field

### PR DESCRIPTION
**Pull request by stefanprobst**
Related: #11368, #11654 

This PR stringifies Dates on sort fields to correctly sort when we have a mix of Date objects and date strings.
It also adds sort fields to `fieldsToSift`, i.e. fields where the field resolver should be called before querying. This allows e.g. sorting on linked fields.

### CODE REVIEW

**Comment by stefanprobst** [comment]
Sorry, I'll fix this tomorrow

**Comment by stefanprobst** [comment]
Ok, this is working, but not yet with Loki.

**Comment by stefanprobst** [comment]
Unfortunately, this has become quite invasive. Probably better for now to just [do this](https://github.com/gatsbyjs/gatsby/compare/master...stefanprobst:stringify-dates-for-sort), which is a small change -- but won't work for Loki???

**Comment by DSchau** [comment]
@stefanprobst do we want to close this? We've fixed the underlying issue (by reverting the regression), but it would be nice to implement this functionality in a clean way--if we can.

**Comment by stefanprobst** [comment]
Yes let's close this for now. I'll try to tackle our sorting issues once the schema refactor is in.

**Pull request closed without merging**
