### PR TITLE
chore: remove progressbar

### PR DESCRIPTION
**Pull request by laurieontech**
[ch24875]

### CODE REVIEW

**Review by ascorbic — APPROVED** [review]
Hooray!

**Comment by pieh** [comment]
Question about this - did we want to remove progress bar completely? Or just fallback to non-reporter one?

**Comment by laurieontech** [comment]
@pieh the todo wasn't clear so I assumed remove the existing function and all of its uses. If we'd like to add it back with the non-reporter one I'm happy to do so.

**Comment by pieh** [comment]
@laurieontech Yeah, I see that TODO wasn't that clear here. Just thinking if right now there is no visual feedback for user why something is taking a long time - not sure if there are other places that was showing some progress or not, so this is more of a question than request.

My interpretation of TODO was that we remove fallback code because `reporter.createProgress` should be there, but I don't know if that was intention of whoever wrote that TODO (and always good to evaluate if those TODOs actually make sense after few months (years?) :)

**Comment by laurieontech** [comment]
Also reasonable to revert! It's not a major change if we'd rather keep it.

**Pull request merged**
