### PR TITLE
Add Lifestone Church to Showcase

### PR DESCRIPTION
**Pull request by agarrharr**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 4afd8c34680223381fb697ca9f48e4c9d784bc99

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5e1e97b31274586d2b7a6b

**Comment by pieh** [comment]
Hey, we will soon be removing list of sites from README (https://github.com/gatsbyjs/gatsby/pull/6843) in favour of using dedicated Site Showcase - please check https://next.gatsbyjs.org/docs/site-showcase-submissions/

**Comment by agarrharr** [comment]
@pieh I made a new PR #6870 for `docs/sites.yml`.

**Comment by pieh** [comment]
Thanks, I'll close this one then.

**Pull request closed without merging**
