### PR TITLE
[gatsby] Fix production build hanging on createPagesStatefully

### LINKED ISSUE #3813: Build stuck at createPagesStatefully
## Description

Build never finishes, gets stuck at `createPagesStatefully`

### Environment

Gatsby version: 1.9.177
Node.js version: 8.9.4
Operating System: Ubuntu 16.04.3

### File contents (if changed):

Nothing was changed.

### Actual result

Build was stuck for 10 minutes until I killed it. Log:

<details>

```
success delete html files from previous builds — 0.040 s
success open and validate gatsby-config.js — 0.004 s
success copy gatsby files — 0.015 s
success onPreBootstrap — 0.005 s
success source and transform nodes — 0.014 s
success building schema — 0.068 s
success createLayouts — 0.023 s
success createPages — 0.000 s
⠐ createPagesStatefully^C
```

</details>

### Expected behavior

Site should build.

### Steps to reproduce

1\. `npm install -g gatsby`

2\. `gatsby new gatsby-site && cd gatsby-site`

3\. `gatsby build`

### PR DESCRIPTION
**Pull request by nsimonson**
Fixes #3813

### CODE REVIEW

**Comment by nsimonson** [comment]
I'd say it'd be good to make sure the AppVeyor build finishes this time, but because of this bug they're queued up for days.

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit be4fb972d16c62514c00560256e35c172c63ca19

https://app.netlify.com/sites/using-glamor/deploys/5a73dceedf99535000d2f472

**Comment by nsimonson** [comment]
🤔Seems like the netlify builds are still hanging

**Comment by Graham42** [comment]
If the globally installed version of gatsby is being used rather than the local one in `node_modules` will the netlify builds ever work until we fix this bug? 
I'm assuming (perhaps incorrectly) that Netlify auto-updates their environments to the latest version of gatsby. If so, this might mean the Netlify deploy with not work until this gets fixed. (ie. new version gets released)

**Comment by nsimonson** [comment]
@KyleAMathews Once this is released we should deprecate `gatsby@1.9.176` and `gatsby@1.9.177` for folks who may have already upgraded.

**Comment by nsimonson** [comment]
Closing in favor of  https://github.com/gatsbyjs/gatsby/commit/7bb93fe195d4c7d0683507da99c3b9602eee3657

**Comment by KyleAMathews** [comment]
Oops sorry! I should have merged this instead :-( I didn't look through PRs this morning before fixing the problem (I'd noticed it when working on something)

**Pull request closed without merging**
