### PR TITLE
update readme with openfda link

### PR DESCRIPTION
**Pull request by rossPatton**
just adds the openfda project to the list of gatsbyjs projects

thanks for making this, it was a little bumpy going but in the end it worked out great!

### CODE REVIEW

**Comment by KyleAMathews** [comment]
awesome! Gatsby's first government site :D

**Comment by KyleAMathews** [comment]
A writeup about your experience (good and bad) would be great!

**Comment by KyleAMathews** [comment]
Oh an a bug report ;-) clicking on blog post links from the front page aren't working — e.g. "Drilling into the details" links to https://open.fda.gov/update/drilling-into-the-details not https://open.fda.gov/update/drilling-into-the-details/

**Comment by rossPatton** [comment]
the project is unfortunately out of my hands now as we were outbid for the contract, but you're welcome to file an issue or a PR :)

**Comment by KyleAMathews** [comment]
Ah too bad. I'll alert them over there then.

**Comment by jlengstorf** [comment]
Hiya @rossPatton! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
