### PR TITLE
[1.0] Avoid infinite loops with onUpsertPage by not calling again the source of the upsertPage action

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@0x80

**Comment by 0x80** [comment]
@KyleAMathews Should I make a special case for index "/" ? It currently breaks for me trying to replace "/" with "" as path.

**Comment by 0x80** [comment]
```
calling api handler in /Users/thijskoerselman/Development/vauxlab for api onUpsertPage
path -> oldPath  /
The upserted page didn't pass validation
ValidationError: child "path" fails because ["path" is not allowed to be empty]
{ component: '/Users/thijskoerselman/Development/vauxlab/src/pages/index.js',
  path: '',
  componentChunkName: 'page-component---src-pages-index-js',
  jsonName: 'index.json',
  internalComponentName: 'ComponentIndex',
  context: {} }
```

**Comment by 0x80** [comment]
I've replace the if statement with `if (page.path && page.path !== oldPath) {`. That seems to fix it. Still curious if this is the way to go

**Comment by KyleAMathews** [comment]
Yeah a path of "" wouldn't be anything so isn't allowed.

**Pull request merged**
