### PR TITLE
[gatsby-source-contentful] Add Support for preview api

### PR DESCRIPTION
**Pull request by Khaledgarbaya**
## Summary
This PR extends the contentful source plugin with the option to provide a host to the contentful client which is useful when trying to test your drafts using the [Contentful Preview API](https://www.contentful.com/developers/docs/references/content-preview-api/).

## Limitation
Due to the preview API limitation, only initial sync is possible now, you will be getting all the data every time you build when using the preview API. Which should be fine for now.

check https://github.com/gatsbyjs/gatsby/issues/1448 for more info

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Is there any other possible hosts? Any reason to not just add a "preview" option that defaults to `false`?

**Comment by KyleAMathews** [comment]
Changed my mind again actually :-)

"preview" is an abstraction that doesn't add much value and possibly confuses people as it's not what they'd expect from reading the docs. Also y'all at Contentful could add another endpoint in the future so this would get in the way of that.

**Comment by KyleAMathews** [comment]
Thanks for the upgrades!

**Comment by Khaledgarbaya** [comment]
Sorry for the later reply (time zone), the host param can be very useful for a user having another proxy server on top contentful, also might be useful for our internal testing at contentful, like getting data from staging or localhost.

Thanks for the merge

**Pull request merged**
