### PR TITLE
chore(gatsby): add TypeScript definitions for config & plugin APIs

### PR DESCRIPTION
**Pull request by JamesMessinger**
## Description

I added TypeScript definitions for the [`gatsby-config.js`](https://www.gatsbyjs.org/docs/gatsby-config/#gatsby-config), [`gatsby-node.js`](https://www.gatsbyjs.org/docs/node-apis/), [`gatsby-browser.js`](https://www.gatsbyjs.org/docs/browser-apis/), and [`gatsby-ssr.js`](https://www.gatsbyjs.org/docs/ssr-apis/) APIs. 

Some of the definitions could use more details (for example, many functions are simply defined as `Function`), but at least every method, parameter, and property are defined, which provides good intellisense and code-completion assistance in tools like VSCode. 😎

## Related Issues
N/A

### CODE REVIEW

**Comment by pieh** [comment]
That's really cool! Users would need to annotate types of the exports in gatsby-X files, right? How does it look like?

I was working on something similar (but using jsdoc) and I did hit lot of problems but made it to somewhat work:
screenshot 2019-01-06 at 17 22 52

Reason for using jsdoc instead of TS definition was that we generate API reference ( https://www.gatsbyjs.org/docs/node-apis/ ) from that, so we wouldn't need to maintain definitions in multiple places (typescript defs could not always be up to date)

**Comment by JamesMessinger** [comment]
@pieh - Sorry, I should have includes a usage example in my original description.  VSCode (and other TypeScript-aware editors) support TypeScript definitions in plain JavaScript files (like `gatsby-config.js`) via a combination of JSDoc and "magic comments", such as:

- `/// <reference types="..." />` ([docs](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html))
- `// @ts-check` ([docs](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html))

For example, here's what my `gatsby-config.js` file looks like:

```javascript
// @ts-check
const gatsby = require("gatsby");

/**
 * @type {gatsby.GatsbyConfig}
 */
const config = {
  siteMetadata: {
    title: "Welcome to my website!",
  },

  plugins: [
    "gatsby-plugin-typescript",
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: "docs",
        path: `${__dirname}/src/docs/`,
      },
    },
  ],
};

module.exports = config;
```

Because I've declared my `config` variable to be of type `gatsby.GatsbyConfig`, I get code-completion, type-checking, and intellisense in VSCode.  Which is really nice!

**Comment by eknowles** [comment]
thank you for this 👍

**Comment by JamesMessinger** [comment]
Oh wait!  Before you merge this!

I hadn't heard any feedback on this PR, so I thought it wasn't going to be merged.  So I was preparing to submit type definitions to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/) instead.  But it's always preferrable to have type definitions in the library package itself, so I'm glad to see that you're interested.

Here are the latest type definitions (attched ZIP file), which I was preparing to submit to DefinitelyTyped.  I've done a lot of cleanup, including separating the definitions into multiple files and correcting a few mistakes in my original definitions.  In addition, I've added types for some Gatsby plugins too.

> [**gatsby-types.zip**](https://github.com/gatsbyjs/gatsby/files/2956642/gatsby-types.zip)

- **gatsby-plugins** <br>This folder has the type definitions for the Gatsby plugin APIs (`gatsby-browser`, `gatsby-config`, `gatsby-node`, and `gatsby-ssr`)

- **gatsby-source-filesystem** <br>This folder has the type definitions for the [gatsby-source-filesystem plugin](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/)

- **gatsby-mdx** <br>This folder has the type definitions for the [gatsby-mdx plugin](https://gatsby-mdx.netlify.com/)

**Comment by LekoArts** [comment]
Hi @JamesMessinger 👋 
Would be great to have this in. Is that what you zipped up also in this PR? And could you also please have a look at the merge conflict? Thanks!

**Comment by KyleAMathews** [comment]
This is great stuff! Would love to have it merged!

**Comment by orta** [comment]
I've tried to merge in the zip changes, and add my own API reference JSDoc comments based on this PR in https://github.com/gatsbyjs/gatsby/pull/13619

**Comment by wardpeet** [comment]
@orta maybe you know how to solve this.

Typings are correct as you can see below:
image

There is a problem because it's a union of functions args & options aren't being detected when you actually need autocompletion. (if I remove the union and put only 1 function inside the d.ts file it works)

image
image


With only one function in d.ts file
image
image

**Comment by orta** [comment]
@wardpeet my PR is the successor to this https://github.com/gatsbyjs/gatsby/pull/13619

**Comment by wardpeet** [comment]
sweet let me rollback my changes.

**Comment by wardpeet** [comment]
published in gatsby@2.3.34

**Pull request merged**
