### PR TITLE
chore: update publishing scripts

### PR DESCRIPTION
**Pull request by vladar**
## Description

This PR brings all the publishing scripts required for the new release process with additional benefits.

#### Branch protection 
- `publish-next` and `publish-preminor` are only allowed in the `master` branch
- `publish-release` and `publish-rc` are only allowed in the `release/*` branches

This should prevent accidental publishing from a wrong branch (i.e. stable release from master or `next` release from the release branch).

#### Deprecated `yarn run publish`

Now it outputs a hint to run `yarn publish-next` or `yarn publish-release`.

**Why?** Lerna [suggests](https://github.com/lerna/lerna/tree/main/commands/publish#lifecycle-scripts) not to use `publish` script for `lerna publish` calls:

> Run `publish` lifecycle in root
> To avoid recursive calls, don't use this root lifecycle to run `lerna publish`

We also had to use `--ignore-scripts` for `--canary` publishing because of this. Now canaries should work with scripts too.

#### Moved pre-publish scripts to lifecycle hooks

- `scripts/check-publish-access` to `prepublishOnly` (as we don't want to run it on `pack`)
- `scripts/clear-package-dir` to `prepack` (we want to run it for both - `pack` and `publish`)

### CODE REVIEW

**Comment by ascorbic** [comment]
Would it be worth adding a "publish-canary" command, to avoid messing it up?

**Comment by vladar** [comment]
Well, canary usually requires specific `--pre-dist-tag` and `--preid` anyway. So we can't have a single command for every canary. Also, I've removed `preDistTag` option from lerna config, so now even the old command for canary should just work.

**Comment by ascorbic** [comment]
Yeah, I meqant something like `yarn publish-canary create-gatsby`

**Comment by KyleAMathews** [comment]
👍 to `publish-canary` https://stackoverflow.com/questions/11580961/sending-command-line-arguments-to-npm-script

**Comment by vladar** [comment]
That would be handy but I still don't quite understand how to interpolate canary name into both - `--preid` and `--pre-dist-tag`.

So with our recommended command for canary:

```sh
yarn lerna publish --canary --ignore-scripts --exact  --preid <preid> --pre-dist-tag <dist_tag>
```

We need to replace both `<preid>` and `<dist_tag>` with a command argument (that's a recommendation in our docs to use the same value for those flags for canaries).

Looks like it requires a separate script or am I missing something? I can revisit this in a follow-up PR unless there is a quick way to do this in yarn scripts.

**Comment by pieh** [comment]
Let's skip canary releases nicer CLI command conversation from this PR. This PR should fix the problem of canary release pushing to `next` tag, so this is already a fix in this area

**Review by pieh — APPROVED** [review]
This looks correct after streamlining changelogs ( lerna will generate changelogs since last release tag and NOT since last time it generated changelog, so we shouldn't mix `--no-changelog` and publishes with changelogs - it should be consistent )

Rest of things looks good here, but changelogs for sure will need some follow up work (and decisions)

**Pull request merged**
