### PR TITLE
Add Lifestone Church to showcase

### PR DESCRIPTION
**Pull request by agarrharr**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit e2812c388ca20163d16331781cba7b4eeb2a1178

https://app.netlify.com/sites/gatsbyjs/deploys/5b5f6a911f12b7296704bd33

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit e2812c388ca20163d16331781cba7b4eeb2a1178

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5f6a931f12b7296704bd3b

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit e2812c388ca20163d16331781cba7b4eeb2a1178

https://app.netlify.com/sites/using-contentful/deploys/5b5f6a951f12b7296704bd45

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit e2812c388ca20163d16331781cba7b4eeb2a1178

https://app.netlify.com/sites/image-processing/deploys/5b5f6a951f12b7296704bd3f

**Comment by m-allanson** [comment]
Thanks @agarrharr 👍 Do you want to add a `description` field too, or are you happy for the site to be added as-is?

**Pull request merged**
