### PR TITLE
[1.0] Hide browser debug logging by default

### PR DESCRIPTION
**Pull request by 0x80**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit dc7fc0e22e9341be13b83b3848c7767cdf7bb6fb

https://app.netlify.com/sites/gatsbygram/deploys/5908630dcf321c63946e5f5f

**Comment by KyleAMathews** [comment]
Could you just comment them out instead of adding Debug? Debug is small but there's still no point in shipping an extra ~kb or so of gzipped javascript to every single Gatsby website.

**Comment by 0x80** [comment]
@KyleAMathews Yes, of course. I didn't think about it. I thought the messages were still useful for development maybe. 

An alternative would be to require it conditionally so that in production it is omitted (maybe isolated via utils/debug or something). But if you see no real value in client side debugging I will just remove it.

**Comment by KyleAMathews** [comment]
Yeah they were useful when I was debugging those things but have stuck around only because I mostly forgot about them. The only production logging that makes sense to me is catching errors and pointing to doc pages similar to what React does.

**Pull request closed without merging**
