### PR TITLE
added Aphrodite support to Gatsby

### PR DESCRIPTION
**Pull request by biw**
I added support for SSR rendering for [Aphrodite](https://github.com/Khan/aphrodite). Not sure if I added everything I need to. I'm happy to change things!

### CODE REVIEW

**Comment by m-allanson** [comment]
Thanks @biw, it's always good to see a new Gatsby plugin :) As far as code review goes, this looks 👍 to me.

However I'm going to close this and ask that you publish the plugin to npm under your own npm account. That means you're in full control of future maintenance for your plugin.

As you've already added the `gatsby` and `gatsby-plugin` keywords to the plugin's `package.json`  it'll automatically show up on [Gatsby's Plugin Library](https://www.gatsbyjs.org/plugins/) once you publish it (after the search index updates, once every 24 hours).

There's a little bit of [info on doing this in the Gatsby docs](https://www.gatsbyjs.org/docs/source-plugin-tutorial/#publishing-a-plugin).

Feel free to ask any questions here or as an issue!

**Comment by biw** [comment]
@m-allanson Awesome, happy to! Is there any way to get the [`gatsby-plugin-aphrodite`](https://www.npmjs.com/package/gatsby-plugin-aphrodite) npm namespace once I have everything ready to go?

**Comment by m-allanson** [comment]
Aha! I didn't know that was there. I guess the best thing to do would be to transfer the package name to you? I guess @KyleAMathews can handle that. What's your `npm` username?

**Comment by KyleAMathews** [comment]
Oh yeah haha I did grab that. Yeah, tell me your npm name and I'll make you an owner.

**Comment by KyleAMathews** [comment]
Thanks for writing the plugin!

**Comment by biw** [comment]
Awesome @KyleAMathews, it's [719ben](https://www.npmjs.com/~719ben). Happy to help, thanks for writing Gatsby 😄

**Comment by biw** [comment]
Ready to go @KyleAMathews https://github.com/biw/gatsby-plugin-aphrodite

**Comment by biw** [comment]
Not trying to be annoying, just making sure you've seen this @KyleAMathews 😃

**Comment by KyleAMathews** [comment]
Not annoying! Completely missed this 😅 You're the owner now! Thanks again!

**Comment by biw** [comment]
Thanks!

**Pull request closed without merging**
