### PR TITLE
[BREAKING] use peer deps for styled components

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Maybe just do this in v2? Is this causing a lot of trouble right now that we need a breaking change?

**Comment by jquense** [comment]
I was thinking since they are versioned independently it wasn't a big deal to do a v2 of this plugin yeah? We can put it whereever, it was making it consistent with the emotion plugin and addresses some of the concerns in #2446

**Comment by KyleAMathews** [comment]
Ah right, yeah do a v2 release. Cool — will do 👍 

I've also been thinking on all the v2s we're doing for plugins that when we bump Gatsby to v2, we can bump all plugins to v2 as well *except* ones we've already bumped to v2. Most plugins except webpack ones shouldn't have a breaking change for Gatsby v2 but moving everything to v2 will reduce confusion I think.

**Comment by monsieurnebo** [comment]
Great, thanks!

**Pull request merged**
