### PR TITLE
[gatsby-plugin-remove-trailing-slashes] - update docs

### PR DESCRIPTION
**Pull request by scottyeck**
Per discussion in https://github.com/gatsbyjs/gatsby/pull/3223

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Try running `npm run format-markdown` — I ended up leaving semi-colons in code samples because otherwise in one-liners e.g. `<div>Hi</div>`, prettier was adding a semi-colon at the front 🤦‍♂️

**Comment by scottyeck** [comment]
Done and done. Had to enable experimental workspaces in order to run the formatter - perhaps I should be setting that on my machine and not at the project-level? There are pros and cons either way I suppose. @KyleAMathews - your call.

**Comment by KyleAMathews** [comment]
@scottyeck what error we're you running into when running the formatter? `workspace-experimental` shouldn't be necessary.

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by scottyeck** [comment]
No problem. Guessing that error might be because I'm on an older version of _yarn_? Idk. Will investigate.

**Pull request merged**
