### PR TITLE
added gatsby-cli package

### PR DESCRIPTION
**Pull request by robsonpf**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hey, what are you trying to solve with this?

**Comment by robsonpf** [comment]
I tough that's the issue that need to be fix on the ticket.

**Comment by KyleAMathews** [comment]
What ticket?

**Comment by pieh** [comment]
Main `package.json` is for lerna monorepo and isn't actually package on itself, so this doesn't actually do anything useful.

I'll close this.

**Pull request closed without merging**
