### PR TITLE
Fix responsiveSizes originalImg and add originalName to all image transformations

### PR DESCRIPTION
**Pull request by agoldenduck**
I needed access to the original name of files when I was using gatsby-transformer-sharp. I thought originalImg would be that field, however it was returning null because of a typo. So I fixed the originalImg typo and added a new field originalName.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Oy! Thanks for the fix and new feature!

**Comment by KyleAMathews** [comment]
Tests are failing atm as you'll need to update the Jest snapshot. Just run `npm run test -- -u` from the root of the repo.

**Comment by agoldenduck** [comment]
Thanks Kyle, updated the snapshot and should work now.

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit d34a6bf3745ecb580e46d6e84af988e9fb7fc574

https://app.netlify.com/sites/using-glamor/deploys/5982720b7960b13799006ea5

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by jlengstorf** [comment]
Hiya @agoldenduck! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
