### PR TITLE
chore(docs): fix typo

### PR DESCRIPTION
**Pull request by akljo**
## Description
fixed typos

## Related Issues
n/a

### CODE REVIEW

**Comment by akljo** [comment]
hasn't yet merged

**Comment by lannonbr** [comment]
@akljo The core team who has merging powers usually doesn't work on the weekends

**Comment by akljo** [comment]
will they merge soon

**Comment by jonniebigodes** [comment]
@akljo please be a little more patient if you don't mind, This is will be reviewed shortly and then will probably be merged in.

**Pull request merged**
