### PR TITLE
[gatsby-image] Support image loading with JavaScript disabled

### LINKED ISSUE #3109: [gatsby-image] Support image loading with JavaScript disabled
I think that by default, images' `src`, `srcSet` and other attributes should be set to the final displayable image instead of e.g. an image with a width of 20 pixels.

If JS is enabled, change to the preview image immediately until the final image is available.

### PR DESCRIPTION
**Pull request by kripod**
Resolves #3109.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Thanks! Sorry for the long delay on getting this out there — been super busy 😅

**Comment by kripod** [comment]
@KyleAMathews You needn’t be sorry, I can totally understand your situation of being extremely busy. I’m glad that this has finally been merged, I highly appreciate your efforts and attitude towards this project! 😊

**Comment by kripod** [comment]
@KyleAMathews I don't know why, but this seems to break production builds (`gatsby build`). I get blurry images all over the place along with the following stack trace on my web browser's console:

```
Uncaught Error: Minified React error #32; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=32&args[]=76 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (reactProdInvariant.js:29)
    at u (ReactDOMComponentTree.js:101)
    at l (ReactDOMComponentTree.js:177)
    at v.f (ReactDOMComponent.js:259)
    at e.notifyAll (CallbackQueue.js:74)
    at r.close (ReactReconcileTransaction.js:78)
    at r.closeAll (Transaction.js:207)
    at r.perform (Transaction.js:154)
    at u (ReactMount.js:124)
    at r.perform (Transaction.js:141)
```

Development builds are fine (`gatsby develop`).

**Comment by KyleAMathews** [comment]
Can you try to duplicate this with the using-gatsby-image example site?

**Comment by kripod** [comment]
@KyleAMathews Just visit https://using-gatsby-image.gatsbyjs.org using Chrome v63.

**Comment by KyleAMathews** [comment]
Huh... weird this didn't show up in your and my testing.

**Comment by KyleAMathews** [comment]
This is the issue we're running into https://github.com/facebook/react/issues/1252

**Comment by KyleAMathews** [comment]
looks like we still have to use `dangerouslySetInnerHTML`

**Comment by KyleAMathews** [comment]
I'll work on a PR to do this.

**Pull request merged**
