### PR TITLE
added  gatsby-styled-blog-starter 

### PR DESCRIPTION
**Pull request by greglobinski**
I added gatsby-styled-blog-starter  to the list of starters on docs page

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit b9b6ec0743ff3b0ae8798411d4829c956a553d0a

https://app.netlify.com/sites/using-glamor/deploys/5a180ee7a114775d26e5b6b6

**Comment by greglobinski** [comment]
Hi @KyleAMathews , did I do something wrong? I simply edited md file with Github editor. I have to admit that I have no idea what to do with this  "Deploy preview failed." message. Could you give me a hint?

**Comment by gagan0723** [comment]
This is a ```eslint``` error.
```
$ eslint --ext .js,.jsx packages/**/src
/home/travis/build/gatsbyjs/gatsby/packages/gatsby/src/commands/develop.js
  206:7  error  'listener' is assigned a value but never used  no-unused-vars
✖ 1 problem (1 error, 0 warnings)
error Command failed with exit code 1.
```

**Comment by KyleAMathews** [comment]
Yeah, I added the linting error before I left on holidays :-( someone else fixed it so things are good! Thanks for building this awesome starter!!

**Pull request merged**
