### PR TITLE
Edited regex in config.yml to bypass CI on pull requests limited to docs

### PR DESCRIPTION
**Pull request by dylanesque**
## Description

This PR is intended to address CI not bypassing checks in the instance of forked branches.

## Related Issues

The motivation for this is discussed in [#19725](https://github.com/gatsbyjs/gatsby/issues/19725)

### CODE REVIEW

**Comment by muescha** [comment]
Now still the same as before that every branch with docs anywhere in the branchname is ignored

The [Circle CI docs](https://circleci.com/docs/2.0/workflows/#branch-level-job-execution) say if it should begin with a word then a `^` marker is needed

for example also:
"jimdoschool:www/myfile"

It should be ignored:

When it starts with "docs":
"docs/"
"docs-"

And when it starts with username and a colon and then docs:
"userName:docs/"
"username:docs-"

can there be also some other usernames formats like @organisation/username ?

**Comment by pvdz** [comment]
Shouldn't this be something like `(^|:).*/docs.+/` ?

("Either start at begin of match or at a colon and search for `/docs.+/` in the path")

Dunno how standard these regexes are

**Comment by pieh** [comment]
I'm not sure if we can make it work at all. It seems like CircleCi set branch name to be `pull/<pr-number>` when PR is from the fork (instead of actual branch name).

See:
 - https://discuss.circleci.com/t/create-separate-steps-jobs-for-pr-forks-versus-branches/13419/4 (here used to have different set of jobs depending if PR is from same repo or from fork)

**Comment by dylanesque** [comment]
> I'm not sure if we can make it work at all. It seems like CircleCi set branch name to be `pull/<pr-number>` when PR is from the fork (instead of actual branch name).
> 
> See:
> 
> * https://discuss.circleci.com/t/create-separate-steps-jobs-for-pr-forks-versus-branches/13419/4 (here used to have different set of jobs depending if PR is from same repo or from fork)

Perhaps it would be easier to tighten up the standard for what a docs branch should be called in order to bypass CI checks, rather than bend over backwards to try and make a regex that fits the current cases?

**Comment by LekoArts** [comment]
Hi, thanks for the issue and PR! As my colleague wrote we don't think we can actually fix this and hence will close this. It would be nice to have this working but since it's out of our hands and it's not too important we can keep it as is.

**Pull request closed without merging**
