### PR TITLE
chore: update prettier

### PR DESCRIPTION
**Pull request by hoobdeebla**
Updates prettier. This should unblock #25546

### CODE REVIEW

**Comment by pvdz** [comment]
I'm pretty sure this is a mistake.

**Comment by hoobdeebla** [comment]
yeah one moment

**Comment by hoobdeebla** [comment]
@pvdz the merge commit wasn't marked as a merge commit 🤔 so it showed +/-11K lines changed. [Fixed now.](/gatsbyjs/gatsby/compare/master...hoobdeebla:update-prettier) Should I open another PR or is there a way to reopen this?

**Comment by pvdz** [comment]
You could open a new PR but for Prettier please defer that. If we bump Prettier then we'll want to flip a switch as well.

Or is there a particular reason to bump Prettier now?

**Comment by hoobdeebla** [comment]
Currently [the `--embedded-language-formatting` option introduced in prettier@2.1.0](https://prettier.io/blog/2020/08/24/2.1.0.html), set to `auto` by default, is generating lint errors that did not exist on prettier@2.0.5. This means that the CI tests for #25546 will endlessly error at the `lint` stage unless Prettier is manually updated while a) fixing the errors like is done here or b) adding `embeddedLanguageFormatting: "off"` to `.prettierrc.js`. Previously #25546 (open since 6 July) had been failing at `bootstrap` for over 2 months until my addition of express-graphql to the <1.0.0-minor group in the Renovate config (#26582). Bumping prettier now enables Renovate to properly do its job again.

**Comment by hoobdeebla** [comment]
My apologies if that came across as condescending - just trying my best to help. The primary reason for the prettier bump is to unblock the renovate/packages branch (#25546) like I mentioned above.

You mentioned bumping prettier and wanting to flip a switch. Does that refer to the new `embeddedLanguageFormatting` option? If so, would you want to switch it on (`auto`/default) or off? I can make a new PR including your preferred state.

**Comment by pvdz** [comment]
We can set packages to not be upgraded in renovate. That should unblock it. Wouldn't that work?

>  just trying my best to help

Nope you're fine and I appreciate bringing Prettier to my attention. My delay in response had nothing to do with you or this ticket.

> Does that refer to the new embeddedLanguageFormatting option? 

No, actually that's to flip the config for arrow header parens and trailing function arg commas.

The reason a Prettier bump is disruptive for us is that all PRs in flight will then have a different config from our CI, as well as PRs being prepared, especially by third parties, based on older tips. It takes a while before that settles again and the bump is not worth that trouble until there's a concrete reason to upgrade it.

Renovate is not a reason because it has an option to suppress packages. So if you're saying a Prettier bump will add more warnings then that seems like a good reason not to bump until we figure out how to deal with that. I hadn't heard about this `embeddedLanguageFormatting` before you mentioned it and I'm not sure what we'd want to do with it :)

**Comment by hoobdeebla** [comment]
Addressed in #26841 :D

**Pull request closed without merging**
