### PR TITLE
Docs sidebar refactor

### LINKED ISSUE #7422: [www] docs sidebar is not sticky
### To recreate the behavior:
1. Clicked on Guides from docs homepage (default is only Quickstart is open)
2. Scrolled down
3. Opened Deployment and Hosting category
4. Scrolled down
5. Clicked on Custom Configuration

### Expected behavior
I would expect to see the custom configuration item stay exactly where it is in the sidebar

### Actual behavior
The sidebar jumps back to the top so I have to scroll back down to see the category again.

### PR DESCRIPTION
**Pull request by kkemple**
This PR attempts to fix some of the behavior issues in the sidebar for certain docs pages.

Closes #7422

### CODE REVIEW

**Comment by calcsam** [comment]
Looks good!

**Comment by Manoz** [comment]
Nice one. Good job and thank you guys o/

**Comment by fk** [comment]
🎉

**Comment by shannonbux** [comment]
Just made a note that this does not actually close #7422. The problem described in that issue still persists, so I re-opened it.

Also, does anyone know why this issue #7495 doesn't show up in the open source repo? I can't find it through search, and therefore cannot link to it in the Epic #7427

**Pull request merged**
