### PR TITLE
adds documentation on how to use custom webpack-config

### PR DESCRIPTION
**Pull request by bananenmannfrau**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 3e40b358aebc4d707b9a00725e52e9cec227d744

https://app.netlify.com/sites/using-contentful/deploys/594d1ed93c1d5e62d602ef86

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 853beb33ae9ad2df8f90d95fb29f8e02fbc1c39e

https://app.netlify.com/sites/using-contentful/deploys/594d1f186f4c5037c549fbee

**Comment by KyleAMathews** [comment]
This is great! Thanks for adding this missing docs page. Could you also add it to the documentation nav bar? https://github.com/gatsbyjs/gatsby/blob/1.0/www/src/pages/docs/doc-links.yaml

**Comment by bananenmannfrau** [comment]
done :zap:

**Comment by KyleAMathews** [comment]
Thanks!

**Comment by jlengstorf** [comment]
Hiya @b-m-f! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
