### PR TITLE
tests(gatsby-transformer-remark): make equality checks stricter

### LINKED ISSUE #16474: gatsby-transformer-remark excerpt tests should not use toMatch but toBe
The [tests](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/__tests__/extend-node.js) for `excerpt` in `gatsby-transformer-remark` currently use `jest`'s  `toMatch` and `toMatchObject`. This seems weird because we want to check the exact excerpt, while `toMatch` will also be cool when the result starts with the expected string -- which is exactly *not* what we want for an excerpt.

### PR DESCRIPTION
**Pull request by nguyenami**
## Description

The tests for except was used `toMatch` and `toMatchObject`. These tests whether the except is in the excepted string, but that is not true since we want it to be `===` with the expected string. So a more strictly test is `toBe`. 

## Related Issues
Fixes #16474

### CODE REVIEW

**Comment by stefanprobst** [comment]
cool :+1:, could you take a look at the other  excerpt tests as well? thanks!

**Comment by nguyenami** [comment]
Sure thing, I will get on to it. Always happy to help.

**Comment by sidharthachatterjee** [comment]
@nguyenami I would add the extra new line or space to the string passed into `toBe` 

This is good because it's telling us more about the behaviour 🙂

**Comment by nguyenami** [comment]
Sorry for bother you, but I don't know how to extract for just a single link. Do you have any suggestions to where to look?
```
bootstrapTest(
    `relative links are not prefixed`,
    `
This is [a link](path/to/page1).

This is [a reference]

[a reference]: ./path/to/page2
`,
    `html`,
    node => {
      expect(node).toMatchSnapshot()
      expect(node.html).toBe(`<a href="path/to/page1">`)
      expect(node.html).toBe(`<a href="./path/to/page2">`)
    },
    { additionalParameters: { pathPrefix: pathPrefix, basePath: basePath } }
  )
})


    Expected: "<a href=\"path/to/page1\">"
    Received: "<p>This is <a href=\"path/to/page1\">a link</a>.</p>
    <p>This is <a href=\"./path/to/page2\">a reference</a></p>"

```

**Comment by sidharthachatterjee** [comment]
@nguyenami You should be able to copy it the expected value there! (I'll be sure to verify the tests once you're done)

**Comment by nguyenami** [comment]
@sidharthachatterjee what I mean is I don't know what to do to the test to make it match the expected string, without having to do string manipulation. 
```
describe(`Relative links keep being relative`, () => {
  const assetPrefix = ``
  const basePath = `/prefix`
  const pathPrefix = assetPrefix + basePath

  bootstrapTest(
    `relative links are not prefixed`,
    `
This is [a link](path/to/page1).

This is [a reference]

[a reference]: ./path/to/page2
`,
    `html`,
    node => {
      expect(node).toMatchSnapshot()
      expect(node.html).toBe(`<a href="path/to/page1">`)
      expect(node.html).toBe(`<a href="./path/to/page2">`)
    },
    { additionalParameters: { pathPrefix: pathPrefix, basePath: basePath } }
  )
})

  ● Relative links keep being relative › relative links are not prefixed

    expect(received).toBe(expected) // Object.is equality

    Expected: "<a href=\"path/to/page1\">"
    Received: "<p>This is <a href=\"path/to/page1\">a link</a>.</p>
    <p>This is <a href=\"./path/to/page2\">a reference</a></p>"

      939 |       expect(node).toMatchSnapshot()
      940 |       console.log(node.html.search(`<a`))
    > 941 |       expect(node.html).toBe(`<a href="path/to/page1">`)
          |                         ^
      942 |       expect(node.html).toBe(`<a href="./path/to/page2">`)
      943 |     },
      944 |     { additionalParameters: { pathPrefix: pathPrefix, basePath: basePath } }

      at toBe (packages/gatsby-transformer-remark/src/__tests__/extend-node.js:941:25)
      at test (packages/gatsby-transformer-remark/src/__tests__/extend-node.js:91:11)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 39 passed, 40 total

```

**Comment by stefanprobst** [comment]
@nguyenami 
It is only necessary to change `toMatch` in the [`describe` block that tests the excerpt behavior](https://github.com/gatsbyjs/gatsby/blob/6dad691f3080a5b3ec9223fe21ccb170519bd395/packages/gatsby-transformer-remark/src/__tests__/extend-node.js#L121-L775).

It is perfectly fine to use `toMatch` in the tests for relative links, so we can just leave those as they are.

**Comment by nguyenami** [comment]
Then it is done.

**Comment by sidharthachatterjee** [comment]
Thank you so much @nguyenami 👍

**Pull request merged**
