### PR TITLE
chore(starters): add gatsby-prismic-blog-starter

### PR DESCRIPTION
**Pull request by iamsainikhil**
Description
Add gatsby-prismic-blog-starter to the starters library

Documentation
Detailed documentation of the starter can be found at https://github.com/iamsainikhil/gatsby-prismic-blog-starter/blob/master/README.md

Related Issues
N/A

### CODE REVIEW

**Comment by iamsainikhil** [comment]
@aaaakshat a lot of files got changed after I did `npm run format`

At first, I simply edited the `starters.yml` file in the github markdown editor itself and created this PR. 

I don't know what else I need to do to fix these errors!!

**Comment by aaaakshat** [comment]
> @aaaakshat a lot of files got changed after I did `npm run format`
> 
> At first, I simply edited the `starters.yml` file in the github markdown editor itself and created this PR.
> 
> I don't know what else I need to do to fix these errors!!

Your branch is 6 commits behind the upstream master. You need to pull from the official gatsby master in order to get all the new changes, then you can change starters.yml.

**Comment by aaaakshat** [comment]
You need to first reset your HEAD to the initial `staters.yml` change because your "fix circleCI lint errors" commit refactored many other files which is why it says 96 files were changed. Do a hard reset till the first commit and then merge the upstream master.

**Comment by pvdz** [comment]
Certain teams got auto-assigned when files from /benchmarks and /docs got changed.

@iamsainikhil I guess something did not go as planned when rebasing/merging/tooling. I'm going to close this PR. Please open a new one with a fresh base and you should be good to go. Thanks! :purple_heart:

**Pull request closed without merging**
