### PR TITLE
Add website

### PR DESCRIPTION
**Pull request by angeloocana**
Add angeloocana.com

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 50399cf30ce9d87b88be4d357f2dce43873d1eb8

https://app.netlify.com/sites/using-glamor/deploys/59a238d27960b12727fb6970

**Comment by cr101** [comment]
It would be helpful to also add some non-blog sites with functions like "search as you type" in the client as well as search filters to filter the search results.

**Comment by angeloocana** [comment]
Hi @KyleAMathews 

What should I do?
The netlify link goes to 404 page.

**Comment by angeloocana** [comment]
Hi @cr101 
Search is on my roadmap, do you know about some code example?

**Comment by cr101** [comment]
@angeloocana Sorry I don't have any but I'd love to see some examples as well.
One idea is to use [react-autosuggest](https://www.npmjs.com/package/react-autosuggest) to do the "search as you type" for post titles in the client and/or use [lunr](https://www.npmjs.com/package/lunr) to filter the search results in the client.

**Comment by angeloocana** [comment]
@cr101  cool! Thank you
I wish to do the search for my website in 1 or 2 weeks.
I'll let you know when I have my solution =D

**Comment by KyleAMathews** [comment]
Thanks!

**Pull request merged**
