### PR TITLE
Add Figma to Showcase

### PR DESCRIPTION
**Pull request by macoughl**
Loving Gatsby over at Figma!

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit aa159fc7996d24383299fd3fbfe0a64180691522

https://app.netlify.com/sites/gatsbyjs/deploys/5b5537e682d3f10b56cf7a93

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit aa159fc7996d24383299fd3fbfe0a64180691522

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5537e782d3f10b56cf7a9b

**Comment by pieh** [comment]
Hey @macoughl, it seems like this didn't pass yaml lint:
https://travis-ci.org/gatsbyjs/gatsby/jobs/406967282#L1162 (seems like incorect intendation of first added line)

**Comment by macoughl** [comment]
Thanks @pieh & @m-allanson!

**Pull request merged**
