### PR TITLE
[1.0] In memory lowdb is significantly faster. Also snuck in yurnalist for better console output

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@abi this should correct the speed slowdowns you were seeing. I switched to lowdb recently from leveldown (to avoid the native dependency) but their file-async storage adapter adds a lot of overhead, weirdly — I would have expected async to be actually async. But when I measured it, each set was taking 10+ milliseconds. I switched to doing everything in-memory with a debounced save to disk and sets now take a tiny fraction of a second as you'd expect.

**Comment by KyleAMathews** [comment]
@0x80 I added Yurnalist as well here :-) 

screen shot 2017-07-01 at 4 53 50 pm

If you want to make the "success" cool check marks (✅) instead, I would not be offended!

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0b8a0f53c613ecd8b688603815939c3b467a64dc

https://app.netlify.com/sites/using-glamor/deploys/595836e07960b10fdfe09ab2

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 0b8a0f53c613ecd8b688603815939c3b467a64dc

https://app.netlify.com/sites/gatsbyjs/deploys/595836e07960b10fdfe09aa4

**Comment by abi** [comment]
Thanks for making this change! :D So, I assume this will help with all file I/O that happens during bootstrap. In particular, the `run queries` phase during bootstrap was by far the slowest for us, fingers crossed that it works there too. Guessing that during `run queries`, you are loading up each of the pages that were just created from disk?

When will this be in a release?

**Comment by KyleAMathews** [comment]
@abi so what I changed was Gatsby's cache API which is used heavily by gatsby-transformer-remark to cache transforming markdown src to the markdown AST and then the AST to html as different queries can request the same transformed data.

Previously each time a new transform was put in cache, it'd immediately save the cache put to disk. This change now debounces saving the cache so disk i/o only happens once things slows down.

When I switched to lowdb I naively assumed it worked like ^^ but it was saving on every put which added a ton of overhead on sites with lots of markdown.

I should *fingers crossed* be putting out a new beta tonight. Got another couple PRs to go :D

**Comment by 0x80** [comment]
@KyleAMathews Awesome! I'll update yurnalist to match te latest yarn code, and I'll see if I can improve the success output with a check icon.

**Pull request merged**
