### PR TITLE
chore(gatsby): speed up redirect creation

### PR DESCRIPTION
**Pull request by me4502**
## Description

This PR prevents redirects massively slowing down the build. The tests needed to be changed so that they don't conflict on the fromPath, and that was a better change than exporting fromPaths.

## Related Issues

https://github.com/gatsbyjs/gatsby/issues/17126

### CODE REVIEW

**Comment by me4502** [comment]
Ah, nice. Thanks - that was my original fix idea however I was unsure whether it was safe to modify the type of state due to it being used in plugins.

**Comment by wardpeet** [comment]
Redux state is a "private" api and on your own risk to use it so no harm done.

**Comment by KyleAMathews** [comment]
@wardpeet -- we haven't considered redux state private. We need to deprecate it and replace it with data access APIs.

Could you revert this to the previous way @me4502 had it?

**Comment by wardpeet** [comment]
I'll do that. Thanks for telling me.

**Pull request merged**
