### PR TITLE
docs: add resources to link to comply with title

### PR DESCRIPTION
**Pull request by thecodingaviator**
## Description

does what it says on the label 😆

### CODE REVIEW

**Comment by marcysutton** [comment]
If we're going to move this page, it also needs a redirect in `gatsby-node.js`. Here's a doc on how to do that: https://www.gatsbyjs.org/contributing/docs-contributions/#docs-renaming-instructions

**Comment by thecodingaviator** [comment]
@marcysutton Does it look fine now?

**Comment by thecodingaviator** [comment]
@marcysutton I've made a bit of mess here. Let me sort it out please

**Comment by marcysutton** [comment]
oh wow, the history changed since I reviewed. I ran the merge bot on this branch to update it from master, looks like there were some other changes merged in? I removed the bot merging label, in any case. Let us know if you need any help

**Comment by thecodingaviator** [comment]
@marcysutton sincere apologies. I was trying to fix the lint errors and I messed up somewhere. How does it look now?

**Comment by thecodingaviator** [comment]
@marcysutton It's not merging. Did I miss something?

**Comment by marcysutton** [comment]
All good!

**Pull request merged**
