### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by vyaspranjal33**
removed bullet from Line 487 "and more" as seen in  image 

image

### CODE REVIEW

**Comment by vyaspranjal33** [comment]
@DSchau after my PR it will look like this 
image

**Comment by DSchau** [comment]
This leads to the document reading as "Stylus... and more!" which isn't really what we want to convey. The bullet is correct.

I'd kindly ask that if you're able your next PR directly should directly correspond to an [open issue](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). That way, we don't have to go through this whole process, and you can _actually_ get a substantive PR merged, which is what we all want.

Thanks again for the PR, and I hope to see your next correspond to an actual issue within the Gatsby repo!

**Comment by DSchau** [comment]
@vyaspranjal33 are [any of these](https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22+label%3AHacktoberfest) something you'd be able to tackle? They're labeled good first issue and Hacktoberfest, both of which conveys they're fairly doable without prior context!

In particular, this seems like a [great one to tackle](https://github.com/gatsbyjs/gatsby/issues/9369) if you have the bandwidth!

**Comment by DSchau** [comment]
@vyaspranjal33 sure, that works. Are you able to commit that up to this branch?

**Comment by vyaspranjal33** [comment]
@DSchau  yes if you allow i can send PR from my Master branch

**Pull request merged**
