### PR TITLE
Remove using-react-native-web example

### PR DESCRIPTION
**Pull request by m-allanson**
:wave: @slorber Thanks for adding this example (and creating the react-native-web plugin)!

In preparation for Gatsby v2 I'm going to remove this example - the plugin isn't in the Gatsby repo which makes it tricky to handle ongoing maintenance. Would you like to host the example yourself or publish it as a starter?

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 0ef17d9163d7472d14b7577c74751e5ab67e0dde

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6967c3b13fb16d27788d84

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit 0ef17d9163d7472d14b7577c74751e5ab67e0dde

https://app.netlify.com/sites/using-contentful/deploys/5b6967c5b13fb16d27788d93

**Comment by slorber** [comment]
I can host the example myself or add the plugin code to this repo if you want @m-allanson .

I added the example in this repo as it was asked by necolas of RNW

**Comment by m-allanson** [comment]
> I can host the example myself 

That would be great! As we're not accepting new plugins to the repo unless they're used by Gatsby itself or are a core part of the Gatsby ecosystem. Plus that means you have full control over both the plugin and the example site.

> didn't have much time to do that lately

No worries, I run into the not-enough-time problem too :)

**Comment by necolas** [comment]
Is there an example integration hosted anywhere now? Looks other examples haven't been removed even if they use their own plugins that aren't part of the Gatsby core :/

**Comment by slorber** [comment]
as far as i know there isn't. Just merged a PR for Gatsby v2. I'll try to bring back the example once Gatsby V2 is published

**Pull request merged**
