### PR TITLE
feature: add option to google tagmanager plugin to be included post body

### PR DESCRIPTION
**Pull request by horacioh**
- add an option to the `gatsby-plugin-google-tagmanager` to choose if you want the script to be inserted at the `<head>` tag or at the end of the `<body>` tag
- add an example how to use the plugin

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 8fc9f540357ebf86b86a8a06dc29cb385fd87f3e

https://app.netlify.com/sites/using-postcss-sass/deploys/5b6195a23813f03095d6ffa3

**Comment by pieh** [comment]
What's the difference between putting it in head vs at the end of the body? When this new option should be used? Maybe we should switch to putting this at the end of the body instead of adding option to select location?

**Comment by piotrkwiecinski** [comment]
There is a way to use an dataLayer.push https://developers.google.com/tag-manager/devguide#async that can be used to trigger event when required and could possibly justify using tag at the end of body, but default behaviour should be head I reckon.

**Comment by horacioh** [comment]
thanks @pieh and @piotrkwiecinski for the review!

The problem I encountered is that sometimes (most cases on users with ad blockers) the execution on the tagmanager create some errors loading other scripts and break some parts of my website (form validation).

I saw this documentation about google recommending to add the script to the head tag, thats why I added as an option, and not forced to be always postBody.

hope this explanation helps!!

**Comment by pieh** [comment]
Hmm, maybe we should investigate why it breaks runtime and try to catch it?

It feels like example site that just adds this plugin to config is not really useful - this is _just_ more verbose version of https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-tagmanager#how-to-use and put additional work on maintainers for no benefit it feels like

**Comment by horacioh** [comment]
@pieh thats a good idea. will delete this and add mode docs to it :)

any advice to catch any errors at runtime? just breakpoints on errors or what you recommend?

**Comment by piotrkwiecinski** [comment]
@horacioh do you know which tags cause this issue or what errors did you get. Maybe we could try to recreate it on more controlled environment.

**Comment by horacioh** [comment]
Hello again!,

I tried the plugin in a more isolated environment and I did not get the errors and the code its working properly, so I will close this issue. Will continue doing profiling because I need this to work properly in my website, so sure I can add more specific content to the docs related to this issue.

thanks for your time @pieh and @piotrkwiecinski :100:

**Pull request closed without merging**
