### PR TITLE
Use StaleWhileRevalidate for page-data files

### LINKED ISSUE #19207: Remove blocking network request when loading site from a service worker (with gatsby-plugin-offline)
You can see the blocking request for the page-data.json in this performance trace of reloading gatsbyjs.org

Screenshot 2019-11-01 10 30 03

We should use https://developers.google.com/web/tools/workbox/reference-docs/latest/workbox.strategies.StaleWhileRevalidate (perhaps just for this initial request) so that the site loads as fast as possible.

### PR DESCRIPTION
**Pull request by davidbailey00**
## Description

Use StaleWhileRevalidate for page-data for better performance and initial renders

## Related Issues

Fixes #19207

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Another option I was just researching is network first but with a timeout. Ideally we _do_ get the latest data — we just don't want to wait that long for that because our top priority is consistently fast loading followed by strong consistency of data.

This issue has some sample code https://github.com/GoogleChrome/workbox/issues/1738#issuecomment-433870661

Perhaps a `networkTimeout` of 0.75 seconds? That would enable us to always render under a second.

**Comment by davidbailey00** [comment]
> Ideally we do get the latest data

Technically we should keep the page-data fetch logic the same as the logic for getting page bundles, since the data may change shape of physical appearance between two deploys of a site - so I think whichever we choose, we should use the same approach for JS/CSS as well. Thoughts?

**Comment by sidharthachatterjee** [comment]
> Technically we should keep the page-data fetch logic the same as the logic for getting page bundles

I agree with this for two reasons
- A different page bundle might expect a different data shape and a mismatch could break the site during rehydration
- Agree that this simplifies debugging

**Comment by KyleAMathews** [comment]
>Technically we should keep the page-data fetch logic the same as the logic for getting page bundles, since the data may change shape or physical appearance between two deploys of a site 

Did we ever start refetching page (and app) bundles on a regular basis to check if they've been updated?

The big downside to this PR is that now page data won't be updated until the second time you visit a page as the browser will first get the cached page (however old it is) & then while the SW gets the newer version, the browser won't.

Also... on data changing shape. With the webpack compilation hash now not being in the page-data.json — how do we know what version of page data we're working with? Someone could have cached a version weeks ago and then the page component changed & we'd still try to use it which would throw an error...

This PR might need reverted.

**Comment by 21c-HK** [comment]
> The big downside to this PR is that now page data won't be updated until the second time you visit a page as the browser will first get the cached page (however old it is) & then while the SW gets the newer version, the browser won't.
> 
> Also... on data changing shape. With the webpack compilation hash now not being in the page-data.json — how do we know what version of page data we're working with? Someone could have cached a version weeks ago and then the page component changed & we'd still try to use it which would throw an error...
> 
> This PR might need reverted.

This is exactly the problem with this PR. This PR must be reverted as it introduces extremely hard to reproduce caching bugs [as explained here](https://github.com/gatsbyjs/gatsby/pull/24940#issuecomment-644755923) that ruin the user experience (suggesting to the user that the web site is completely broken). This PR basically kills any kind of caching reliability for web sites in production with very little real-world performance gain, so this is definitely the wrong default. Gatsby feels so fast because of its aggressive caching and preloading, which is only applicable if you can expect it to be reliable, but this PR makes Gatsby's caching unreliable.

**Comment by 21c-HK** [comment]
I clicked on a link to https://www.gatsbyjs.org/ today, which showed a blank (black) page. So there you have it. This caching bug even shows up on your own web site.

**Pull request merged**
