### PR TITLE
fix(gatsby-remark-copy-linked-files): Support MDX by visiting JSX nodes

### PR DESCRIPTION
**Pull request by trevorblades**
## Description

This PR addresses an issue where files referenced in `` tags were ignored if the file was being parsed as MDX, since those nodes are of the `jsx` type, instead of the expected `html`. To address this, I changed the `test` argument passed to `visit` from the string `'html'` to an array: `['html', 'jsx']`

The `test` argument expects some input that is compatible with [`is`](https://github.com/syntax-tree/unist-util-is#istest-node-index-parent-context), which includes an array of strings as used in this PR. Here's some API reference for the `test` arg as it pertains to the `visit` function: https://github.com/syntax-tree/unist-util-visit-parents#visittree-test-visitor-reverse

## Related Issues

Fixes https://github.com/gatsbyjs/gatsby/issues/12621

### CODE REVIEW

**Comment by pieh** [comment]
The code change looks very reasonable. It's pretty unfortunate that `remark-mdx` requires node 8+ (failing node6 unit tests)

/cc @ChristopherBiscardi 

Does whole mdx ecosystem require node 8+? If so, I'm thinking just skipping mdx related tests in node 6 instead of trying to fix them

**Comment by trevorblades** [comment]
@pieh yea I noticed that! It's too bad 😢  I just made another commit that adds a line to the root `jest` config so that `remark-mdx` is transformed before tests run, but I would also understand if you didn't want to use that kind of workaround. I'm happy to skip on the JSX test if you would prefer that!

**Comment by pieh** [comment]
I would rather see tests being "honest" and not "forced" to pass: those should not pass in node 6 if package itself doesn't work there without some extra work, so skipping test in node 6 (possibly just with comment that `remark-mdx` doesn't support node 6) is (IMO) clearer approach

**Comment by pieh** [comment]
some guidelines to address skipping test in Node 6 only:
we can use `process.versions.node` and `semver` package to something like this:

```
  // helper somewhere near the top of the file
  const semver = require('semver')
  const testInNode8OrHigher = (...args) => {
    const isNode8OrHigher = semver.satisfies(process.versions.node, ">=8")
    if (isNode8OrHigher) {
      it(...args)
    } else {
      // maybe manipulate test title to note it was skipped because it's not node6
      it.skip(...args)
    }
  }


  // use helper
  testInNode8OrHigher(`can copy JSX images`, async () => {
    const path = `images/sample-image.gif`

    const markdownAST = remark()
      .use(mdx)
      .parse(`<img src="${path}" />`)

    await plugin({ files: getFiles(path), markdownAST, markdownNode, getNode })

    expect(fsExtra.copy).toHaveBeenCalled()
  })
```

**Comment by trevorblades** [comment]
@pieh sounds good. At first, I was thinking of wrapping the test in a `if (semver.gte(...`, but your solution using `skip` looks much better. Thanks!

**Comment by trevorblades** [comment]
It turned out that just importing `remark-mdx` was breaking the tests in node 6, so I moved the `require` statement inside the test, so that it only gets imported in node 8 or greater.

**Comment by ChristopherBiscardi** [comment]
> Does whole mdx ecosystem require node 8+? 

yeah, I believe that's the case. Not really intentionally, that's just how it worked out over time.

@johno does this look good on the `remark-mdx` side to you?

**Comment by sidharthachatterjee** [comment]
Published in `gatsby-remark-copy-linked-files@2.0.12`

**Pull request merged**
