### PR TITLE
feat(gatsby-recipes): Add Snipcart

### PR DESCRIPTION
**Pull request by thatfrankdev**
Adds a Gatsby recipe that enables ecommerce with a Snipcart plugin

_💭 I'm not a fan of the external setup script + additional dev dependency on abstract-syntax-tree. I'd be happy revisit once support for user input is added 🙏. I'm also open to remove it if it violates some "anti-bloat" rule_

### CODE REVIEW

**Comment by thatfrankdev** [comment]
Hey guys, I'll just close this for now as I suspect it may have been forgotten.

Cheers,

**Comment by KyleAMathews** [comment]
Yikes, it was forgotten but this is still valuable. If it's alright, I'll try to get it in tomorrow.

**Review by KyleAMathews — APPROVED** [review]
Thanks for the contribution and sorry again for the slow merge.

**Comment by KyleAMathews** [comment]
Manually merged in https://github.com/gatsbyjs/gatsby/commit/642876de0110c2022e3c427a22ac2ab6532f0d1c

**Pull request closed without merging**
