### PR TITLE
[1.0] www: Make the header fixed for tablets and up

### PR DESCRIPTION
**Pull request by fk**
… so simple that I feel I missed something ;)

### CODE REVIEW

**Comment by fk** [comment]
Ah yeah, header height should be a constant…

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit c04026da948ee32b90f5343eb112f8b252c76cc8

https://app.netlify.com/sites/using-contentful/deploys/59496c3a3c1d5e515a459db7

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 222258cbc0db9b1abb509e531cd4e0e6ffc5b3cd

https://app.netlify.com/sites/using-styled-components/deploys/59496e87cf321c2901b5e7e1

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 222258cbc0db9b1abb509e531cd4e0e6ffc5b3cd

https://app.netlify.com/sites/using-glamor/deploys/59496e87cf321c2901b5e7de

**Comment by KyleAMathews** [comment]
Perfect! Thanks :-)

**Pull request merged**
