### PR TITLE
[gatsby-source-wordpress] prevent duplicate nodes for remote media files

### LINKED ISSUE #3562: [gatsby-source-wordpress] After adding wordpress plugin, gatsby develop throws error
I have created a new trial project with gatsby-bootstrap starter and installed gatsby-source-wordpress plugin as instructed with all the wp plugin configuration/credentials etc. 

When trying to build or develop the project to check it in the browser, it throws an error and won't compile.

The error log is as followed: 

`error UNHANDLED EXCEPTION`

`  Error: ENOENT: no such file or directory, rename '/Volumes/Data/WebsiteProjects/GatsbyWordpress/.cache/gatsby-source-filesystem/tmp-e8c2ad91b6179055d0ae09c526e48078.jpg' -> '/Volumes/Data/WebsiteProjects /GatsbyWordpress/.cache/gatsby-source-filesystem/e8c2ad91b6179055d0ae09c526e48078.jpg'`
  
`  - Error`
  
`  - index.js:27 tryRenameSync
    [GatsbyWordpress]/[fs-extra]/lib/move-sync/index.js:27:19`
  
`  - index.js:22 Object.moveSync
    [GatsbyWordpress]/[fs-extra]/lib/move-sync/index.js:22:3`
  
`  - create-remote-file-node.js:101 DuplexWrapper.<anonymous>
    [GatsbyWordpress]/[gatsby-source-filesystem]/create-remote-file-node.js:101:22`
  
` - next_tick.js:74 _combinedTickCallback
    internal/process/next_tick.js:74:11`
  
`  - next_tick.js:98 process._tickCallback
    internal/process/next_tick.js:98:9`

This error occurs after wordpress plugin has finished fetching pages, posts, comments etc.

I have built and used `develop` command to start the local server with the site successfully before I installed the wordpress plugin, after which, I cannot finish the build process.

Please help me resolve this issue.

Thanks.

### PR DESCRIPTION
**Pull request by Fetten**
This fixes #3562

### CODE REVIEW

**Comment by pieh** [comment]
Shouldn't we fix that in `gatsby-source-filesystem` ? To not replicate it in every source plugin?

**Comment by Fetten** [comment]
Yes, I first thought of caching the url in `gatsby-source-filesystem`'s create-remote-file-node.js, but then I realized, that multiple requests can run in parallel. This makes it hard to check for a cached local-file node before a duplicate request, as the first one might not be finished yet.

It would be great if anybody had an idea how to solve this.

**Comment by pieh** [comment]
we can cache promises - like that https://github.com/pieh/gatsby/commit/af21319884661f04131e640b32ad877e32ada6a0 (would just need better comments)

**Comment by Fetten** [comment]
Wow, never thought of caching a whole promise :)  But if this works, let's go for it.
I'll close this PR if you would like to send one for your version.

**Comment by pieh** [comment]
We can keep that PR open for now. My code does work and fix fetching problem, but not sure yet if we won't have similar problem when we try to process those images (using transformer-sharp for example) and will check it tomorrow.

**Comment by KyleAMathews** [comment]
We cache promises like @pieh's PR elsewhere in core and it works great so let's go with his more general solution.

Thanks @Fetten for the PR all the same!

**Pull request closed without merging**
