### PR TITLE
[1.0] WIP Attempt to fix graphql type inference

### PR DESCRIPTION
**Pull request by 0x80**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
This looks close! On graphql, when you're querying subobjects of an array,
you need to select fields. That looks like perhaps the one thing that needs
fixed.

**Comment by 0x80** [comment]
@KyleAMathews I tried fixing the test query but it makes not difference. It looks like when iterating over `anObjectArray` with _.each() the `k` value becomes `"0"` and is then used as `fieldName` in a `inferGraphQLType()` call which the leads to the error: `Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "0" does not.`

But that's about as far as I get. Hope you can find some time to have a closer look. I can't use an important part of my CMS data because of this limitation.

**Comment by KyleAMathews** [comment]
I think this is solvable, lemme take a look.

**Comment by KyleAMathews** [comment]
Ok, figured it out. Going to merge this then apply my change locally 💯

**Comment by KyleAMathews** [comment]
https://github.com/gatsbyjs/gatsby/commit/f9e3da64ecf984df0ce3bed49493a3b190272928

So one caveat to this is that the items in an array have to be a consistent type. So you're example of `[1, 2, 'a string']` won't work. This is a limitation of how GraphQL lists work that they need to have a known type. In theory we could use "union" types to allow for heterogeneous data in arrays but that would complicate querying data a lot as we'd have to automatically come up with the names in the union which isn't very discoverable so not sure it'd be worth it. See the graphql union docs if that doesn't make sense http://graphql.org/learn/schema/#union-types

**Comment by 0x80** [comment]
@KyleAMathews 🎉 Awesome! I can definitely live with that. Array items from CMS data will I guess typically be of the same type anyway. In my case it is.

**Comment by KyleAMathews** [comment]
Great!

And I think it's find just telling people to sort heterogeneous data in arrays into separate buckets before adding it to Gatsby e.g. anArrayTypeA, anArrayTypeB, etc.

**Pull request merged**
