### PR TITLE
Restore layout for page not found when navigating from other page

### PR DESCRIPTION
**Pull request by emmafallancy**
Given when user landed on page not found and then navigated to other page, this seems fine. However, when user press the back button in the browser, the layout went missing. This fix is to restore the layout which previously exist (if it does), that went missing when going back to the page not found again.

### CODE REVIEW

**Comment by emmafallancy** [comment]
@KyleAMathews Is the 404 development page meant to have styling if layout exist?

Image below is the current how the development page looks like:
404-dev-without-layout

Give if we have layout exist, this is how it looks like:
404-dev-with-layout

**Comment by KyleAMathews** [comment]
The dev 404 page should be surrounded by the layout component yes :-)

**Comment by KyleAMathews** [comment]
Hmm doesn't seem to be working — if you go to https://deploy-preview-2980--using-javascript-transforms.netlify.com/sdfjsdf then click on a link and then click back the layout disappears.

**Comment by emmafallancy** [comment]
Hmm that's interesting. Is there by any chance if we can to rebuild the `.cache` again? Somehow, I still got the old `component-renderer.js` with none of my changes.

If you don't mind, I'll sort out the dev-404 page as well in this branch too, later on 😄

**Comment by KyleAMathews** [comment]
Oh hmm that could be why — I noticed our Netlify script isn't updating any of the Gasby runtime files in .cache (part of why https://github.com/gatsbyjs/gatsby/pull/3039 broke us earlier). I'll test this locally.

**Comment by KyleAMathews** [comment]
Let's do the dev-404 fix on another PR — PRs are much easier to review/merge if they're small and focused.

Thanks for all your help fixing these things!

**Comment by emmafallancy** [comment]
Ah, I see. Didn't know that the build script was broken for some reason. Thought that we would need to manually trigger the build if anything regards to `.cache` changes.

Yup, sure. I'd figure you would prefer to have the 404-dev to be fixed in another PR. I'll work on it later today and send a separate PR 😄

Don't thank me though. I should thank you for giving this opportunity and the amazing craftsmanship that you have with Gatsby.

**Comment by KyleAMathews** [comment]
Ok, worked perfectly when tested locally! Thanks!

**Comment by emmafallancy** [comment]
@KyleAMathews awesome! 🎉 I'll get the 404-dev work done later on 😄 Thanks!

**Pull request merged**
