### PR TITLE
chore(starters): add gatsby-antd-starter

### PR DESCRIPTION
**Pull request by alienCY**
gatsby-antd-starter

### CODE REVIEW

**Comment by alienCY** [comment]
It says build failed. Can you please help me what should I do? What's wrong.

**Comment by laurieontech** [comment]
It's unrelated to your PR! Nothing you need to do on your end.

**Comment by alienCY** [comment]
> Hey, could you add a bit more information in the `README.md` of this starter? See https://github.com/gatsbyjs/gatsby-starter-default for reference.

done~ I've changed it quite a bit. I will work more on it in the future :D

**Comment by alienCY** [comment]
> Hey, I just looked through your demo site and I noticed `nudes` points to a 404 page. I would recommend renaming the placeholder to maybe `page-3` as we try to keep content as inclusive as possible.

It was a joke >.< Ok fine :P

**Pull request merged**
