### PR TITLE
fix(gatsby-transformer-remark): properly bubble up errors thrown in subplugins

### LINKED ISSUE #6463: Gatsby development server crashes when gatsby-remark-math has a parse error.
## Description
Whenever there is a parse error in Katex, the gatsby dev server crashes and needs to be restarted everytime.

### Steps to reproduce

1. Use illegal syntax in katex.

### Expected result

The server should not crash and user can correct the incorrect syntax.

### Actual result
```
error UNHANDLED REJECTION


  ParseError: KaTeX parse error: Expected 'EOF', got '𝐅' at position 1: �̲�̲ = r_2
  
  - katex.js:2326 new ParseError
    [allaboutspaceflight]/[gatsby-remark-katex]/[katex]/dist/katex.js:2326:16
  
  - katex.js:10416 Parser.expect
    [allaboutspaceflight]/[gatsby-remark-katex]/[katex]/dist/katex.js:10416:23
  
  - katex.js:10468 Parser.parseInput
    [allaboutspaceflight]/[gatsby-remark-katex]/[katex]/dist/katex.js:10468:18
  
  - katex.js:10454 Parser.parse
    [allaboutspaceflight]/[gatsby-remark-katex]/[katex]/dist/katex.js:10454:30
  
  - katex.js:10284 parseTree
    [allaboutspaceflight]/[gatsby-remark-katex]/[katex]/dist/katex.js:10284:17
  
  - katex.js:9223 renderToDomTree
    [allaboutspaceflight]/[gatsby-remark-katex]/[katex]/dist/katex.js:9223:87
  
  - katex.js:9205 Object.renderToString
    [allaboutspaceflight]/[gatsby-remark-katex]/[katex]/dist/katex.js:9205:18
  
  - index.js:12 
    [allaboutspaceflight]/[gatsby-remark-katex]/index.js:12:24
  
  - index.js:31 one

```
### Environment

  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 9.0.0 - ~/.nvm/versions/node/v9.0.0/bin/node
    Yarn: 1.6.0 - /usr/bin/yarn
    npm: 5.5.1 - ~/.nvm/versions/node/v9.0.0/bin/npm
  Browsers:
    Chrome: 65.0.3325.181
    Firefox: 52.9.0
  npmPackages:
    gatsby: ^1.9.55 => 1.9.273 
    gatsby-link: ^1.3.2 => 1.6.45 
    gatsby-plugin-catch-links: ^1.0.8 => 1.0.24 
    gatsby-plugin-google-analytics: ^1.0.1 => 1.0.31 
    gatsby-plugin-manifest: ^1.0.7 => 1.0.27 
    gatsby-plugin-offline: ^1.0.9 => 1.0.18 
    gatsby-plugin-react-helmet: ^1.0.1 => 1.0.8 
    gatsby-plugin-sharp: ^1.6.9 => 1.6.48 
    gatsby-plugin-sitemap: ^1.2.5 => 1.2.25 
    gatsby-plugin-typography: ^1.7.2 => 1.7.19 
    gatsby-remark-autolink-headers: ^1.4.7 => 1.4.19 
    gatsby-remark-copy-linked-files: ^1.5.0 => 1.5.37 
    gatsby-remark-design-system: ^1.0.9 => 1.0.15 
    gatsby-remark-images: ^1.5.0 => 1.5.67 
    gatsby-remark-katex: ^1.0.14 => 1.0.14 
    gatsby-remark-prismjs: ^1.2.0 => 1.2.24 
    gatsby-remark-responsive-iframe: ^1.4.1 => 1.4.20 
    gatsby-remark-smartypants: ^1.4.1 => 1.4.12 
    gatsby-source-filesystem: ^1.4.1 => 1.5.39 
    gatsby-transformer-remark: ^1.6.3 => 1.7.44 
    gatsby-transformer-sharp: ^1.6.10 => 1.6.27 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

### PR DESCRIPTION
**Pull request by sparshy**
This allow `gatsby-remark-*` subplugins to not have special error handling - `gatsby` will properly panic on build, but dev server won't crash anymore

### CODE REVIEW

**Comment by pieh** [comment]
This will cause `gatsby build` to not terminate and might cause broken (but successful) builds. We should wrap `katex.renderToString` calls in try/catch and use `reporter.panicOnBuild` (it was fixed some time ago)

**Comment by pieh** [comment]
> I didn't check if the build will terminate or not, but i dont think that should happen.

Can you elaborate what do You mean? I don't think we want to build be succesful if there are any errors.

**Comment by hexrcs** [comment]
@sparshy @pieh 

Hi guys I tried to make use of `reporter.panicOnBuild` and added two new test cases, but I wasn't able to get the tests run properly (apparently `panicOnBuild` quits the test runner process immediately). Would be awesome if someone could review those changes!

**Comment by hexrcs** [comment]
Also it was weird that the linting tests were failing due to some markdown files in other packages 🤔

**Comment by pieh** [comment]
You can mock `reporter.panicOnBuild` instead of mocking process.exit (like in here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/load-plugins/__tests__/validate.js) and then we only need 1 test (if `panicOnBuild` was called when there is error)

**Comment by hexrcs** [comment]
@pieh That would be awesome!

**Pull request merged**
