### PR TITLE
Move gatsby-starter-default into monorepo

### PR DESCRIPTION
**Pull request by tsriram**
This is for #1545. I'm new to lerna. I just added `gatsby-starter-default` files to `packages` and ran `yarn lerna bootstrap`. Is this all one has to do? Once I get this right, I'll add other official starters to this repo.

Feel free to close this PR if this is a completely wrong way to add a new package to monorepo.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hey — this is great! This is the plan (did I write that down in an issue already?). But to do this, we also need to set things up so that whenever we update gatsby-starter-default (and the other official starters that we should move into the monorepo), we need to copy those changes out into a separate repo as `gatsby new` can only create new sites from a standalone repo.

**Comment by tsriram** [comment]
Oh yeah, you've mentioned about syncing between monorepo and standalone repos in #1545 - I missed it. Do you have thoughts on how to get this done?

**Comment by pieh** [comment]
maybe git submodule ?

**Comment by KyleAMathews** [comment]
I've only heard awful things about git submodules — am I wrong in this case?

My thought was there'd be a bot somewhere that whenever there's a merge to master, we copy any changes to its starter.

Complicating this as well is that the package-lock.json has to be updated on every package version update or else NPM won't install the latest versions of things.

**Comment by tsriram** [comment]
Tried to find some bot which can do this but can't find any. Quite not sure if it's worth creating this bot :smile: 

On second thought, wonder if having same code both in monorepo as well as a standalone repo complicate things and lead to confusion? We'll have to set up same stuff for every official starter that may be added in future!

**Comment by KyleAMathews** [comment]
Yeah — we'd have a directory of starters and then a bot which could handle all of them. I'll close this for now but thanks for the effort!

**Pull request closed without merging**
