### PR TITLE
Add details to lekoarts in showcase

### PR DESCRIPTION
**Pull request by LeKoArts**
Also added my details.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 8555a6bb88fbffa80516d30cb5e805e3673af2a4

https://app.netlify.com/sites/using-postcss-sass/deploys/5b4f99d767610c36aca0ebe1

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 8555a6bb88fbffa80516d30cb5e805e3673af2a4

https://app.netlify.com/sites/gatsbyjs/deploys/5b4f99d667610c36aca0ebd9

**Comment by KyleAMathews** [comment]
Looks like the yamllint check failed

**Comment by LeKoArts** [comment]
Maybe that was the culprit ^

**Pull request merged**
