### PR TITLE
[gatsby-source-contentful] - Passes down all Contentful options to SDK

### PR DESCRIPTION
**Pull request by jreidgreer**
## Purpose of this PR:

The current implementation of the plugin does not allow for all SDK options to be passed down, resulting in defaults being used. Thus, proxy settings cannot be passed down, as mentioned in #4744.

This passes down all options to the contentful.js SDK.

### CODE REVIEW

**Comment by jreidgreer** [comment]
Looks like some conflicting changes just got merged into the master branch. I'll try to rebase after dinner 😬

**Comment by pieh** [comment]
This looks good - seems like there is conflict we need to resolve and also you would need to update branch and merge master branch here - we recently switched default branch to focus on Gatsby v2, so there was big update

/cc @Khaledgarbaya

**Comment by jreidgreer** [comment]
@pieh @Khaledgarbaya resolved! 👍

**Comment by jlengstorf** [comment]
Hiya @jreidgreer! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
