### PR TITLE
[WIP] Upgrade react-router deps, close #992

### LINKED ISSUE #992: React deprecation warnings
with gatsby@0.12.46 i still get deprecation warnings from some dependencies, so i ran
```
$ npm i -S history@^3.3.0 react-router@^3.0.5 react-router-scroll@^0.4.2 scroll-behavior@^0.9.3
```
and got rid of them, i didn't run gatsby's tests though...

### PR DESCRIPTION
**Pull request by nicholaswyoung**
I need to manually test this PR (happening now in CI), but tests pass locally.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit e9d1907fa1f269eee4b06c9d52da6b9ffe79224a

https://app.netlify.com/sites/gatsbyjs/deploys/592430a5424ef2667529963d

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit e9d1907fa1f269eee4b06c9d52da6b9ffe79224a

https://app.netlify.com/sites/gatsbygram/deploys/592430a6424ef26675299640

**Comment by nicholaswyoung** [comment]
Dug into this, it's a bit more than I'd rather take on for now. Better to push the 1.0 release, for my effort.

**Comment by sillyslux** [comment]
@nicholaswyoung what did you find out?
AppVeyor says `Specify a project or solution file. The directory does not contain a project or solution file.` which is cryptic to me and netlify links are 404.

Is this an issue in 1.0 too or should i switch now?

**Pull request closed without merging**
