### PR TITLE
#6438 add known issue with gatsby-plugin-sass and the way it resolves assets

### LINKED ISSUE #6438: Add resolve-url-loader to gatsby-plugin-sass
## Summary

In sass files that use paths to images, fonts, svg... we need to have the resolve-url loader so that webpack can find the files

### Basic example

```
.header-banner.green {
      background: map-get($group-accelerate, start)
        url('../../../images/new/crowdfunding/banner.png') 45px 30px no-repeat;
    }
    .header-banner {
      color: $white;
      margin: -2px 0 30px 0;
      border-radius: $global-radius;
      padding: 30px;
      background: map-get($foundation-palette, primary)
        url('../../../images/new/crowdfunding/banner.png') 45px 30px no-repeat;
      ::selection {
        background: $white;
        color: $black;
      }
```
this code doesn't compile to css without it.

### Motivation
Common stuff like this should work out of the box.
What do you think?

thanks
tagging: @jquense  :)

### PR DESCRIPTION
**Pull request by cezarneaga**
add temporary advice to people using `sass` plugin.
closes #6438

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 0bbf1613682bd444233b3d475dcf8902302055c5

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5859ca792f8905c021f744

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 0bbf1613682bd444233b3d475dcf8902302055c5

https://app.netlify.com/sites/gatsbyjs/deploys/5b5859c9792f8905c021f73c

**Comment by jquense** [comment]
I don't know that this is correct still. I'm using sass now and this isn't true in my project that I can see

**Comment by cezarneaga** [comment]
It solves the issue in the repo i made eqrlier for you. Did u try it there and it worked? Could you share your repo? I would like to see your setup.

**Comment by m-allanson** [comment]
Hey @cezarneaga thanks for adding this 👍 Looks like a duplicate PR for this was merged over at #7076, so I'll close this one.

**Comment by cezarneaga** [comment]
i am fine with this, but the resolver did not solve the issue for me.

**Pull request closed without merging**
