### PR TITLE
Fix for 1602

### PR DESCRIPTION
**Pull request by Alaev**
Fix for: [issue 1602](https://github.com/gatsbyjs/gatsby/issues/1602)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Awesome!

**Comment by alternatekev** [comment]
This seems a little overboard though:

screen shot 2017-07-25 at 11 36 20 am

I feel like packages listed like this can be all-lowercase, which I didn't specifically call out as a legit use in code situations.

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 9883b952d5762ea8057fc7c74d0e8559b66c2275

https://app.netlify.com/sites/gatsbygram/deploys/59777e20cf321c2dedbbdce4

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 9883b952d5762ea8057fc7c74d0e8559b66c2275

https://app.netlify.com/sites/image-processing/deploys/59777e20cf321c2dedbbdcf3

**Comment by KyleAMathews** [comment]
Deploy preview failed.

Built with commit 9883b952d5762ea8057fc7c74d0e8559b66c2275

https://app.netlify.com/sites/using-styled-components/deploys/59777e21cf321c2dedbbdcf9

**Pull request merged**
