### PR TITLE
gatsby-plugin-typography omitGoogleFont option and README

### PR DESCRIPTION
**Pull request by foggy1**
Been awhile since I brought this up but this references #2526 

Since the typography plugin aims for convenience, users who utilize it should be able to easily omit the inclusion of the \<GoogleFont /\> tag. They can do so with the new `omitGoogleFont` key within the `options` object. Setting it to true will skip the inclusion of \<GoogleFont /\>. Users are advised to use something like [typefaces](https://github.com/KyleAMathews/typefaces) instead to load the fonts right into JS.

An entry in `gatsby-config` using this feature would look like this:

```


module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography.js`,
        omitGoogleFont: true,
      },
    },
  ],
}
```

(It might be cool to add a typefaces option next to require them right here to round out the convenience of this all.)

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Ah nifty! Yeah, this makes sense.

Could you document the new option in the README? Also looks like there's a linting error.

**Comment by foggy1** [comment]
This plugin actually doesn't have a README, right? I can throw one together (unless I'm entirely missing it).

**Comment by KyleAMathews** [comment]
Oh... maybe not :-) yeah, that'd be great!

**Comment by foggy1** [comment]
Let me know if I missed anything!

**Comment by KyleAMathews** [comment]
Looks great! Thanks for tackling the PR and documentation.

**Comment by fk** [comment]
Thank you @foggy1!

**Pull request merged**
