### PR TITLE
[www] Cards for Blog index

### PR DESCRIPTION
**Pull request by fk**
…  and >="Tablet", below that breakpoint it's basically still the same layout for now. Minus the "Blog" headline, which I haven't thought about at all up to writing this TBH… (wouldn't be wrong to keep it around I guess, ~~and properly hide it with screenreaders in mind~~).

image

Explicitly sets the excerpt for (two) blog articles along the way – just so much nicer already without that ellipsis (maybe we should go for extracting the first paragraph somehow). Anyways, those two excerpts probably still need some editing … maybe you could take a look @KyleAMathews and @DSchau? 🙏 

Also refines the "light purple" and sidebar colors – all are now a little warmer, moved towards the homepage masthead backgrounds left triangle color, and brings the sidebars webkit scrollbar thumb color in line with the brand.

image

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Looking great! The wording on the two excerpts looks good to me.

BTW, there's an error when building www right now.

**Comment by fk** [comment]
> BTW, there's an error when building www right now.

Grrrr … lemme have a look.
Btw., I can't get `format-www` to work, should it? packages work just fine.

**Comment by fk** [comment]
Fixed … 🙄 😅 If you're okay with the other two excerpts being truncated this is good to go from my side (not saying that all is done of course ;-)).

Split view for contributor pages next … or sidebar?!

**Comment by KyleAMathews** [comment]
Works!

https://deploy-preview-2017--gatsbyjs.netlify.com/blog/

**Comment by KyleAMathews** [comment]
It might be nice to have the whole card be clickable

**Comment by KyleAMathews** [comment]
Also something that could be fun is to add back the "Blog" header but add some old fashioned curly whatevers around it to look like an old-fashioned [nameplate/masthead](https://en.wikipedia.org/wiki/Nameplate_(publishing))

**Comment by fk** [comment]
Wow, you actually read my mind twice, both were on my (secret ;)) list! You hit the nail on the head regarding the masthead – when I wrote about "keeping the `<h1>` around", I immediately tought of s/th like "The Gatsby Times" :)

Will fix the link in a few. To keep the link to the author page working, we can either handle clicks via JS, add another `<a>` for the article link and [stretch it](http://jsfiddle.net/csswizardry/rxsna/) to cover the whole card, then bring the author link up via `z-index` … or do [weird things](http://kizu.ru/en/fun/nested-links/), namely TLDR wrap the nested (author) link in an `<object>`tag … ;)

**Comment by KyleAMathews** [comment]
Thanks!!

**Pull request merged**
