### PR TITLE
fix(www): Update details modal prev/next button transform

### PR DESCRIPTION
**Pull request by brockduncan**
## Description

Adjusts width and positioning of prev/next button text area, rotates arrows left/right on small screens. Rotate text and remove arrow rotate on medium up.

## Related Issues

#18963

### CODE REVIEW

**Comment by pieh** [comment]
Just so you don't have to build yourself @fk ;)

width: 750px
localhost_8000_showcase_reactjs org (4)

width: 745px
localhost_8000_showcase_reactjs org (5)

width: 480px
localhost_8000_showcase_reactjs org (6)

width: 280px
localhost_8000_showcase_reactjs org (7)

**Comment by fk** [comment]
Sorry for taking so long to review this @brockduncan! 🙏 
I hope to get to it today/night!

**Comment by brockduncan** [comment]
Well I just learned something new, thanks! Looks like I need to read up on theme-ui.

**Comment by fk** [comment]
Hey Brock! 👋
Again, I am late 😞— I hope you can accept another apology for that … and also for "hijacking" your PR. 🙏

> Well I just learned something new, thanks! Looks like I need to read up on theme-ui.

💜 Phew! Really happy to hear this, it's what I hoped for: After such a long time waiting for my review, I didn't want to put you through "more pain" … so instead of leaving comments and guiding you through changes, I decided to make those changes myself — but I tried to leave some helpful commit messages, hopefully doing an OK job at explaining why I decided to make them.

**Your PR would have been perfectly fine to ship without me messing around here!** Please don't get discouraged by me messing around here, or the long wait time — both are def. not something that should happen too often.

`theme-ui` is great IMO, and I hope you'll play around with it a bit and let us know how you like it. Unfortunately, our documentation for it in the context of `www` is not too good yet; that's also on me to fix. :/

**Comment by brockduncan** [comment]
@fk no apologies needed!! I'm just happy to get involved. Thanks for refactoring this and explaining it all like you did. That's very much appreciated. I'll definitely get up to speed with theme-ui. Looking forward to finding some more I can help with.

**Comment by fk** [comment]
<3 Thanks for taking the time to remove a bit of guilt, Brock! I really appreciate that, and I hope I haven't taken too much away from that:

> I'm just happy to get involved.

---

> Looking forward to finding some more I can help with.

I'm sure we can find something — lots to do! 🙀😅  
While I think about things (and get out of bed again, down with a cold since yesterday), maybe take a look at the I18N project: https://github.com/gatsbyjs/gatsby/projects/15?

**Pull request merged**
