### PR TITLE
Fix typo on inc builds blog post

### PR DESCRIPTION
**Pull request by m-allanson**
Congrats on the launch :heart:

### CODE REVIEW

**Comment by KyleAMathews** [comment]
❤️ U MIKE!!!

**Comment by DSchau** [comment]
@m-allanson you're the kindest. Miss you -- hope you've been well!

**Comment by pvdz** [comment]
Mike hype! :purple_heart:

**Comment by m-allanson** [comment]
Thanks for the kind words folks :)

**Pull request merged**
