### PR TITLE
Support template literals as frontmatter for JS pages.

### PR DESCRIPTION
**Pull request by mjesuele**
This seems to work well for me. Open to suggestion as far as whether it's the best approach.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Looks good!

We should get some tests on this though. Write out two simple components with normal strings and literal and make sure they're getting parsed correctly. Could you do this as well?

**Comment by mjesuele** [comment]
Sure! I'll take a look when I'm at my desk again 😎

On Thu, Feb 02, 2017 at 18:15 Kyle Mathews

<
mailto:Kyle Mathews <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Looks good!

We should get some tests on this though. Write out two simple components with normal strings and literal and make sure they're getting parsed correctly. Could you do this as well?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/gatsbyjs/gatsby/pull/656#issuecomment-277146300
, or

**Comment by KyleAMathews** [comment]
Hey you think you'll have a chance to finish this up soon?

**Comment by mjesuele** [comment]
Sorry! Haven’t forgotten. Yes, I can finish it by EOW.

On Wed, Feb 15, 2017 at 11:55 AM Kyle Mathews

<
mailto:Kyle Mathews <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Hey you think you'll have a chance to finish this up soon?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/gatsbyjs/gatsby/pull/656#issuecomment-280120514
, or

**Comment by KyleAMathews** [comment]
Sweet, thanks!

**Comment by mjesuele** [comment]
@KyleAMathews, thanks for bearing with me -- I force-pushed a couple of tests and I think this should be good now.

**Comment by KyleAMathews** [comment]
Sweet! Thanks so much for this :-)

**Comment by jlengstorf** [comment]
Hiya @mjesuele! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
