### PR TITLE
[v2] fix gatsby-link

### PR DESCRIPTION
**Pull request by nihgwu**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Ah nice, thanks!

**Comment by nihgwu** [comment]
close as I think that's not the right solution

**Comment by nihgwu** [comment]
@KyleAMathews sorry I didn't send my comment first, that's the wrong approach

**Comment by nihgwu** [comment]
see #5212

**Comment by nihgwu** [comment]
I will revert this change in that PR

**Pull request merged**
