### PR TITLE
fix(blog): Gatsby Partner program - add links back to Pullquote

### PR DESCRIPTION
**Pull request by muescha**
## Description

changes:
- bring back the links to Pullquote

## Note

- for the linter the JSX components in the MDX items should be on one line - otherwise the closing `>` would be count as quote start marker and get lint errors
- should be fixed with `remark-mdx` implemented (#25290), because now the remark plugin don't know about the JSX components

## Related Issues

- #25173 `Blog: Announcing partner program` 
- #25239 ``fix(blog): Broken link in "Partner Program" article, use `Pullquote` ``
- #25240 ``[www/blog] Allow Markdown in `<Pullquote citation>` ``
- #25251 ``chore(blog): Bring back links in `Pullquote citation` ```
- #25256 ``Revert "chore(blog): Bring back links in `Pullquote citation`" ``
- #25290 `enhancement (docs): Improvements to retext-spell`  *(part: implement `remark-mdx`)*

### CODE REVIEW

**Comment by muescha** [comment]
**NOTE:** 
i was only able to commit when i "disable commit hooks"

**Comment by muescha** [comment]
cloud tests are failing. anything i can do on my site?

**Comment by mgienow** [comment]
This looks like a potentially good solution and  we are grateful for your creativity in trying to solve this links-in-pullquote-components problem. However, even though this builds correctly in preview, there is some ongoing bug that seems to cause the production site build to fail -- and block all subsequent builds. So for now the decision has been made to live without links in pullquotes while some changes are made at the component level. Thanks again, and now this PR will be closed.

**Comment by muescha** [comment]
Fix on component level would be better...

**Comment by muescha** [comment]
Maybe markdown for the parameter?

```javascript
<Pullquote citation="Dennis Brotzky, Founding Partner, [Narative](http://...)">
```

**Pull request closed without merging**
