### PR TITLE
fix(chore): extract style to const

### PR DESCRIPTION
**Pull request by muescha**
## Description

extract style to const

## Related Issues

#19290 

suggested in https://github.com/gatsbyjs/gatsby/pull/19290/files#r368206484
> please extract object to const outside of class scope, or React.useMemo hook

### CODE REVIEW

**Comment by muescha** [comment]
as for "performance" i understand it only need to be a const to not recreated as inline object on each return?

**Comment by muescha** [comment]
i moved style to module scope

**Comment by blainekasten** [comment]
@muescha thanks for the contribution. Sorry to send you for loops. I'm going to not accept this PR right now. Based on Sophie's comment, this change is pretty moot and this code is going to be going through quite a bit of transformation coming up. We'll address real performance issues as they are needed.

**Comment by muescha** [comment]
ok - lets close this PR

https://github.com/gatsbyjs/gatsby/pull/19290#discussion_r369171345

> Former React team manager here – I can guarantee this will never be a performance problem and there is nothing wrong with writing the style object like this. I’d recommend you stop worrying about microoptimizing code.

**Pull request closed without merging**
