### PR TITLE
Add DigitalPsychology.io to showcase

### PR DESCRIPTION
**Pull request by danistefanovic**
Adding [Digital Psychology](http://digitalpsychology.io) to the showcase + source code 🤓

Thank you for creating such a great project!

### CODE REVIEW

**Comment by fk** [comment]
Soooo good! <3

**Comment by KyleAMathews** [comment]
Nice!

**Comment by KyleAMathews** [comment]
BTW, I noticed when clicking on the go to the next page links at the bottom of pages, it didn't scroll to the top? Any idea what's going on there?

**Comment by danistefanovic** [comment]
Thanks for catching that @KyleAMathews! I've introduced this bug this morning when I moved all my ["styled" components](https://www.styled-components.com/) outside of the actual components (https://github.com/danistefanovic/digitalpsychology.io/commit/57f772216ec681f3e0d1f96b90f1ddf5523f6b9a)

This is my fix for now in the `layouts/index.js` file: https://github.com/danistefanovic/digitalpsychology.io/commit/c5727a622dce9ce51b461cdce3a414cc95c97258. Honestly, I don't know why this isn't working.

**Comment by jlengstorf** [comment]
Hiya @danistefanovic! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
