### PR TITLE
Adding NYC Pride 2019 site to showcase sites.yml

### PR DESCRIPTION
**Pull request by lesliecdubs**
Signed-off-by: lesliecdub <lcohn-wein@canvasunited.com>

### CODE REVIEW

**Comment by lesliecdubs** [comment]
@m-allanson Got it, thanks for the more complete explanation of `featured`. Excited for the showcase to launch!

**Comment by KyleAMathews** [comment]
Deploy preview for *using-glamor* failed.

Built with commit 878a313da4ac09cc92c1aa60ef1a95d96705a786

https://app.netlify.com/sites/using-glamor/deploys/5b33e9e202ed8367512ff298

**Comment by fk** [comment]
> I love this site!

Me too! Thanks for sharing @lesliecdubs!

**Comment by jlengstorf** [comment]
Hiya @lesliecdubs! 👋

This is definitely late, but on behalf of the entire Gatsby community, I wanted to say thank you for being here.

Gatsby is built by awesome people like you. Let us say “thanks” in two ways:

1.  **We’d like to send you some Gatsby swag.** As a token of our appreciation, you can go to the [Gatsby Swag Store][store] and log in with your GitHub account to get a coupon code good for one free piece of swag. (We’ve got t-shirts and hats, plus some socks that are really razzing our berries right now.)
2.  **If you’re not already part of it, we just invited you to join the Gatsby organization on GitHub.** This will add you to our team of maintainers. You’ll receive an email shortly asking you to confirm. By joining the team, you’ll be able to label issues, review pull requests, and merge approved pull requests.

If you have questions, please don’t hesitate to reach out to us: tweet at [@gatsbyjs][twitter] and we’ll come a-runnin’.

Thanks again! 💪💜

[store]: https://store.gatsbyjs.org
[twitter]: https://twitter.com/gatsbyjs

**Pull request merged**
