### PR TITLE
Make gatsby-link match active hash

### PR DESCRIPTION
**Pull request by porfirioribeiro**
This will allow a navbar for anchors to have active class / style depending on the hash

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 785c974b66ae40d6fc114dc07998d19e5374d0d8

https://app.netlify.com/sites/using-postcss-sass/deploys/5b4f1ac13813f0756dd2edec

**Comment by KyleAMathews** [comment]
Deploy preview for *image-processing* failed.

Built with commit 785c974b66ae40d6fc114dc07998d19e5374d0d8

https://app.netlify.com/sites/image-processing/deploys/5b4f1ac13813f0756dd2edf0

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbygram* failed.

Built with commit 785c974b66ae40d6fc114dc07998d19e5374d0d8

https://app.netlify.com/sites/gatsbygram/deploys/5b4f1ac03813f0756dd2ede6

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit 785c974b66ae40d6fc114dc07998d19e5374d0d8

https://app.netlify.com/sites/gatsbyjs/deploys/5b4f1abf3813f0756dd2ede4

**Comment by KyleAMathews** [comment]
Deploy preview for *gatsbyjs* failed.

Built with commit c64ddb0e0d3a21e234c42d864a018bb86ab90a59

https://app.netlify.com/sites/gatsbyjs/deploys/5b4f1d5b82d3f142d224957e

**Comment by m-allanson** [comment]
This looksl like it will match any hash on a page, regardless of the path? e.g. a page with the following links:

- `/page-a/#heading-1`
- `/page-a/#heading-2`
- `/page-b/#heading-1`
- `/page-b/#heading-2`

would see both the `heading-1` links highlighted when you're at `/page-a/#heading-1`?

Based on the docs at https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/README.md#link-component, it looks like you can already pass `isActive` in to `gatsby-link`, so I'm not sure this PR is necessary? Or have I missed something 🤔

**Comment by m-allanson** [comment]
I think customising behaviour like this is a good case for creating your own wrapper. I'm going to close this for now, but keep the PRs coming :)

**Comment by porfirioribeiro** [comment]
Yes, i understand. Will do.

Maybe later i'll do a PR to add this behavior on documentation for someone who struggles with the same problem as me.

**Comment by m-allanson** [comment]
> Maybe later i'll do a PR to add this behavior on documentation

That would be great 👍

**Pull request closed without merging**
