### PR TITLE
Add SparkPost to the showcase

### PR DESCRIPTION
**Pull request by avigoldman**
Added [developers.sparkpost.com](https://developers.sparkpost.com) to the showcase list.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Deploy preview for *using-postcss-sass* failed.

Built with commit 222c8b87cbbf09a8a3db2fc1826a9afbff99268a

https://app.netlify.com/sites/using-postcss-sass/deploys/5b5245dc73f2cf0ae456d22b

**Comment by KyleAMathews** [comment]
Deploy preview for *using-contentful* failed.

Built with commit 222c8b87cbbf09a8a3db2fc1826a9afbff99268a

https://app.netlify.com/sites/using-contentful/deploys/5b5245de73f2cf0ae456d235

**Comment by KyleAMathews** [comment]
Hey, the README showcase is now "deprecated" as we have a WIP new showcase on next.gatsbyjs.org — could you follow the submission guidelines here? https://next.gatsbyjs.org/docs/site-showcase-submissions/

**Comment by avigoldman** [comment]
Whoops, missed that. Thanks!

**Comment by m-allanson** [comment]
Thanks @avigoldman 👍 I'm going to close this, but please open a fresh PR to add your site to the new showcase when you get the chance.

**Pull request closed without merging**
